### ISSUE TITLE
Nested Layout in TitleView of TabbedPage causing System.InvalidCastException: 'Specified cast is not valid.' when navigating back to

### ISSUE THREAD

**Issue by jordan-hewitt** [dotnet/maui#10006]
### Description

Whenever a TabbedPage is navigated to via a button push to the root of the tab (//HomePage for example) and that TabbedPage contains a layout (doesn't matter what type, stack, relative, grid, etc.) nested within it's TitleView, an invalid cast exception of 'Specified cast is not valid'. 

_This does not always occur on the first time this navigation occurs, but will happen upon subsequent attempts of going from the TabbedPage to a different page and clicking a button to navigate back to the Tabbed Page that contains the nested layout in the TitleView._ 

### Steps to Reproduce

1. Create a .NET Maui app with a tabbed page within the Shell
2. Within one of the tabbed pages, add a layout within the TitleView.
3. Create a page that can be navigated to via the tabbed page that contains the TitleView that has a nested layout that contains a button that will navigate the user back to the '//HomePage' route.
4. Launch the application
5. Navigate to the tabbed page that contains the TitleView with a nested Layout
6. Navigate to the page that can be navigated to from the tabbed page with a nested layout
7. Click the button to navigate back to the '//HomePage' in which contains the TitleView that has a nested layout
8. A System.InvalidCastException: 'Specified cast is not valid.' error will be thrown.  _This may not be thrown the first time, if it isn't repeat steps 5 - 7._
9. Now, remove the nested layout in the TitleView of the tabbed page and the navigation will work as intended without error.

### Link to public reproduction project repository

https://github.com/jmblakl/MauiTitleViewIssue

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 10, likely all.

**Comment by PureWeen** [comment]
@jordan-hewitt can you post the full exception stack trace?

**Comment by jmblakl** [comment]
Hey @PureWeen - I work on the same team as @jordan-hewitt  Here is the stack trace:

`**System.InvalidCastException:** 'Specified cast is not valid.'

**System.InvalidCastException:** 'Specified cast is not valid.'

[mono-rt] [ERROR] FATAL UNHANDLED EXCEPTION: System.InvalidCastException: Specified cast is not valid.
[mono-rt]    at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.ILayout, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.LayoutViewGroup, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].get_VirtualView() in D:\a\_work\1\s\src\Core\src\Handlers\View\ViewHandlerOfT.cs:line 42
[mono-rt]    at Microsoft.Maui.Handlers.LayoutHandler.SetVirtualView(IView view) in D:\a\_work\1\s\src\Core\src\Handlers\Layout\LayoutHandler.Android.cs:line 33
[mono-rt]    at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.ILayout, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.LayoutViewGroup, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IElement view) in D:\a\_work\1\s\src\Core\src\Handlers\View\ViewHandlerOfT.cs:line 56
[mono-rt]    at Microsoft.Maui.Controls.Toolbar.UpdateTitleView() in D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\Toolbar\Toolbar.Android.cs:line 101
[mono-rt]    at Microsoft.Maui.Controls.Toolbar.MapTitleView(ToolbarHandler arg1, Toolbar arg2) in D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\Toolbar\Toolbar.Android.cs:line 152
[mono-rt]    at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0[[Microsoft.Maui.Controls.Toolbar, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.ToolbarHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v) in D:\a\_work\1\s\src\Core\src\PropertyMapper.cs:line 183
[mono-rt]    at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IElementHandler viewHandler, IElement virtualView) in D:\a\_work\1\s\src\Core\src\PropertyMapper.cs:line 47
[mono-rt]    at Microsoft.Maui.PropertyMapper.UpdateProperty(IElementHandler viewHandler, IElement virtualView, String property) in D:\a\_work\1\s\src\Core\src\PropertyMapper.cs:line 72
[mono-rt]    at Microsoft.Maui.Handlers.ElementHandler.UpdateValue(String property) in D:\a\_work\1\s\src\Core\src\Handlers\Element\ElementHandler.cs:line 82
[mono-rt]    at Microsoft.Maui.Controls.Toolbar.SetProperty[VisualElement](VisualElement& backingStore, VisualElement value, String propertyName) in D:\a\_work\1\s\src\Controls\src\Core\Toolbar.cs:line 73
[mono-rt]    at Microsoft.Maui.Controls.Toolbar.set_TitleView(VisualElement value) in D:\a\_work\1\s\src\Controls\src\Core\Toolbar.cs:line 42
[mono-rt]    at Microsoft.Maui.Controls.Platform.Compatibility.ShellToolbarTracker.ApplyToolbarChanges(Toolbar shellToolbar, Toolbar destination) in D:\a\_work\1\s\src\Controls\src\Core\Compatibility\Handlers\Shell\Android\ShellToolbarTracker.cs:line 494
[mono-rt]    at Microsoft.Maui.Controls.Platform.Compatibility.ShellToolbarTracker.OnToolbarPropertyChanged(Object sender, PropertyChangedEventArgs e) in D:\a\_work\1\s\src\Controls\src\Core\Compatibility\Handlers\Shell\Android\ShellToolbarTracker.cs:line 583
[mono-rt]    at Microsoft.Maui.Controls.Toolbar.SetProperty[IEnumerable`1](IEnumerable`1& backingStore, IEnumerable`1 value, String propertyName) in D:\a\_work\1\s\src\Controls\src\Core\Toolbar.cs:line 74
[mono-rt]    at Microsoft.Maui.Controls.Toolbar.set_ToolbarItems(IEnumerable`1 value) in D:\a\_work\1\s\src\Controls\src\Core\Toolbar.cs:line 34
[mono-rt]    at Microsoft.Maui.Controls.ShellToolbar.ApplyChanges() in D:\a\_work\1\s\src\Controls\src\Core\ShellToolbar.cs:line 84
[mono-rt]    at Microsoft.Maui.Controls.ShellToolbar.<.ctor>b__8_0(Object _, ShellNavigatedEventArgs __) in D:\a\_work\1\s\src\Controls\src\Core\ShellToolbar.cs:line 28
[mono-rt]    at Microsoft.Maui.Controls.Shell.SendNavigated(ShellNavigatedEventArgs args) in D:\a\_work\1\s\src\Controls\src\Core\Shell\Shell.cs:line 1176
[mono-rt]    at Microsoft.Maui.Controls.Shell.<.ctor>b__173_0(Object _, ShellNavigatedEventArgs args) in D:\a\_work\1\s\src\Controls\src\Core\Shell\Shell.cs:line 815
[mono-rt]    at Microsoft.Maui.Controls.ShellNavigationManager.<>c__DisplayClass16_0.<HandleNavigated>g__FireNavigatedEvents|3(ShellNavigatedEventArgs a, Shell shell) in D:\a\_work\1\s\src\Controls\src\Core\Shell\ShellNavigationManager.cs:line 274
[mono-rt]    at Microsoft.Maui.Controls.ShellNavigationManager.<>c__DisplayClass16_0.<HandleNavigated>b__2() in D:\a\_work\1\s\src\Controls\src\Core\Shell\ShellNavigationManager.cs:line 264
[mono-rt]    at Microsoft.Maui.Controls.BaseShellItem.OnAppearing(Action action) in D:\a\_work\1\s\src\Controls\src\Core\Shell\BaseShellItem.cs:line 149
[mono-rt]    at Microsoft.Maui.Controls.ShellNavigationManager.HandleNavigated(ShellNavigatedEventArgs args) in D:\a\_work\1\s\src\Controls\src\Core\Shell\ShellNavigationManager.cs:line 262
[mono-rt]    at Microsoft.Maui.Controls.ShellNavigationManager.GoToAsync(ShellNavigationParameters shellNavigationParameters, ShellNavigationRequest navigationRequest) in D:\a\_work\1\s\src\Controls\src\Core\Shell\ShellNavigationManager.cs:line 209
[mono-rt]    at MauiApp2.ChildModel.Navigate() in C:\Users\jblakley\source\repos\MauiApp2\MauiApp2\Child.xaml.cs:line 21
[mono-rt]    at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask) in /_/CommunityToolkit.Mvvm/Input/AsyncRelayCommand.cs:line 351
[mono-rt]    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
[mono-rt]    at Android.App.SyncContext.<>c__DisplayClass2_0.<Post>b__0() in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.App/SyncContext.cs:line 36
[mono-rt]    at Java.Lang.Thread.RunnableImplementor.Run() in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Java.Lang/Thread.cs:line 36
[mono-rt]    at Java.Lang.IRunnableInvoker.n_Run(IntPtr jnienv, IntPtr native__this) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net6.0/android-31/mcw/Java.Lang.IRunnable.cs:line 84
[mono-rt]    at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(_JniMarshal_PP_V callback, IntPtr jnienv, IntPtr klazz) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 22`

**Comment by PureWeen** [comment]
@jmblakl @jordan-hewitt looking closer at your sample I think this isn't quite a supported scenario. You're registering the pages all as Singletons which means those pages get reused everywhere.  If you change your page registrations to transient everything seems to now work without any issues.  I need to think a bit about the best way to handle what you're doing because it works just well enough that it's definitely confusing.  The thing with xplat elements is that they can only have a single native counter part and that's the point of DataTemplates and the service provider. It's a bit tricky to have the same instance of a page on two different parts because then it makes things like animating between those not really possible. If you want two parts of shell to appear the same I'd recommend registering the VMs as singletons but the pages as transient.

**Comment by jmblakl** [comment]
@PureWeen  - this was an oversight in the example app.  In our "real" app they are all transient.  Additionally, I switched the code in the sample app to be a transient registration and the same behavior occurs.  

I did attempt wrapping the AppShell.xaml Title View in a grid.  That does seem to be a viable work around.  We will look at implementing that.  However, that is definitely not intuitive behavior from the Framework, and IMO should be fixed.

**Comment by jmblakl** [comment]
@PureWeen repository is updated with Page and ViewModels registered as Transients.  I also added a commented out section of the appshell title view which wraps the icon in a grid.  IF you uncomment that, it appears to be a valid work around

**Comment by EthanHipps** [comment]
I'm also experiencing this issue and found that adding `CompressedLayout.IsHeadless="true"` to the outer layout tag removed the error.

**Comment by kubaflo** [comment]
A maintainer explicitly identified singleton page reuse as unsupported, reported the transient-registration form working, and could not reproduce afterward.

Closing as not planned because this is an explicit maintainer or product decision, not an inference from age or inactivity.
