### ISSUE TITLE
Cannot publish a single (.exe) file app for deployment

### ISSUE THREAD

**Issue by luatnt-work** [dotnet/maui#10054]
### Discussed in https://github.com/dotnet/maui/discussions/6631

<div type='discussions-op-text'>

<sup>Originally posted by **DanJBower** April 29, 2022</sup>
Is it possible to build a .exe from MAUI?

Currently, when I build an application targeting windows, it makes appears to make a windows app that it has to be installed.

Ideally the end goal would be to create a single executable file that can be shared without being installed. This is because my workplace has a range of restrictions on machines that makes it difficult to install normal applications and even more difficult to install windows apps, and more difficult still to install apps with self signed certificates. In the past I've made applications in WPF and have been able to make a single exe from that project. However, I've soon got to start a new project and would really like to transition to MAUI

</div>

**Comment by MagicAndre1981** [comment]
Support for WinUI Unpackaged Apps is [still in development](https://github.com/dotnet/maui/issues/3166)

**Comment by luatnt-work** [comment]
More detail about what happened:

1. We built a simple app with MAUI Blazor (hybrid app)
2. We publish it (by using dotnet CLI) as "a single executable file application - only 1 .exe file for the whole application"
3. Try to run the application as a normal Windows application (by double clicking on the .exe file)
4. The app cannot start
5. Take a look at Windows's event viewer and here is what we get
![MicrosoftTeams-image (8)](https://user-images.githubusercontent.com/56961706/189592686-8453be6f-8650-48eb-a612-62d230c8b57d.png)

**Comment by luatnt-work** [comment]
@MagicAndre1981 , can I know when this issue will be solved? It would be great if the fix for this is shipped together with .NET 7 in Nov.

**Comment by MagicAndre1981** [comment]
you get a stowed Exception (those 0xC000027B exception) which is not really related to unpacked apps. Currently the unhandled exception handler is broken for WinUI, so unhandled exception crash the app. 

Create a [crash dump of the app and analyze the dump](https://github.com/dotnet/maui/issues/7473#issuecomment-1140258629) and also use extensions like [this one](https://marketplace.visualstudio.com/items?itemName=carlreinke.ExceptionAnalyzers2022) to show [possible exceptions directly in code editor](https://github.com/tetractic/ExceptionAnalyzers#example)

**Comment by luatnt-work** [comment]
@MagicAndre1981 , Sorry if I'm wrong but I think the real problem here is: `Microsoft.ui.xaml.dll` is not put into the (single) executable file while the app is being published as both a unpacked app and a single executable application, and we cannot do anything in the app logic to handle that -> at my point of view, this is relevant to unpacked apps.

**Comment by MagicAndre1981** [comment]
fix the unhandled exceptions and look if the app still crashes

**Comment by luatnt-work** [comment]
ok, I'll try and get back to you soon

**Comment by MagicAndre1981** [comment]
you need to use the PDE.dll extension to decode the stowed exception to see the underlaying exception

**Comment by luatnt-work** [comment]
ok, I'll try and get back to you soon

**Comment by luatnt-work** [comment]
@MagicAndre1981, we get nothing after using the PDE.dll extension to decode the stowed exception to see the underlaying exception. Below is what we get in Windbg, please help us check if we did everything correctly

0:000> .extpath
Extension search path is: C:\Program Files\WindowsApps\Microsoft.WinDbg_1.2206.19001.0_x64__8wekyb3d8bbwe\amd64\WINXP;C:\Program Files\WindowsApps\Microsoft.WinDbg_1.2206.19001.0_x64__8wekyb3d8bbwe\amd64\winext;C:\Program Files\WindowsApps\Microsoft.WinDbg_1.2206.19001.0_x64__8wekyb3d8bbwe\amd64\winext\arcade;C:\Program Files\WindowsApps\Microsoft.WinDbg_1.2206.19001.0_x64__8wekyb3d8bbwe\amd64\pri;C:\Program Files\WindowsApps\Microsoft.WinDbg_1.2206.19001.0_x64__8wekyb3d8bbwe\amd64;C:\Users\Phuong\AppData\Local\Dbg\EngineExtensions;C:\Program Files\WindowsApps\Microsoft.WinDbg_1.2206.19001.0_x64__8wekyb3d8bbwe\amd64;C:\Program Files\Microsoft\jdk-11.0.12.7-hotspot\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files\Python36\Scripts\;C:\Program Files\Python36\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;D:\Dev\nodejs\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Program Files\dotnet\;C:\Users\Phuong\AppData\Local\Microsoft\WindowsApps;C:\Users\Phuong\AppData\Roaming\npm;D:\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Users\Phuong\.dotnet\tools
0:000> .load "D:\Download\PDE\PDE v11.3\x64\winext\pde.dll"
The call to LoadLibrary(D:DownloadPDEPDE v11.3dwinextpde.dll) failed, Win32 error 0n2
    "The system cannot find the file specified."
Please check your debugger configuration and/or network access.
0:000> .extpath "D:\Download\PDE\PDE v11.3\x64\winext"
Extension search path is: D:\Download\PDE\PDE v11.3\x64\winext
0:000> .load pde
=========================================================================================
 PDE v11.3 - Copyright 2017 Andrew Richards
=========================================================================================
0:000> !PDE.dpx -dse
Start memory scan  : 0x0000006bdbfdc000 ($csp)
End memory scan    : 0x0000006bdbfe0000 (User Stack Base)

**Comment by MagicAndre1981** [comment]
make sure you load the dll with the correct bitness (x86,x64) depending on the bitness of your app.

**Comment by luatnt-work** [comment]
@MagicAndre1981 , we checked again and it seems that nothing changes (please refer to my latest update in the description section of the issue).

**Comment by MagicAndre1981** [comment]
have you generated a full memory dump (dump type = 2 in registry)? By default only minidumps are created which miss the data

**Comment by luatnt-work** [comment]
@MagicAndre1981 , yes, we generated full memory dumps, not the minidumps

**Comment by MagicAndre1981** [comment]
ok, install the mentioned VS extension to see all possible exception in code editor and catch them **all** in code.

**Comment by luatnt-work** [comment]
our application is simple and we catch all possible exceptions already

**Comment by MagicAndre1981** [comment]
ok, only try `!pde.dse `and if this also fails I need to ask if the author still works on the extension and if he provides better WinUI dump support.

**Comment by luatnt-work** [comment]
Sorry, but we won't spend more time on this. Honestly, we don't see any problem with the app here. As I noted earlier, if we publish the app without "a single (.exe) file application" option, it still works well as expected, and together with detailed info from Windbg -> this is clearly a bug of the framework.

**Comment by MagicAndre1981** [comment]
try to add `<WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>` to the [csproj file](https://learn.microsoft.com/en-us/windows/apps/package-and-deploy/self-contained-deploy/deploy-self-contained-apps) and look what happens.

**Comment by luatnt-work** [comment]
we will check and get back to you when we have the result

**Comment by luatnt-work** [comment]
@MagicAndre1981 , we checked and it (add <WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained> to the csproj file) does not work

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.9.0 Preview 1.1 and VSMac 17.6.7.417. Can repro this issue.
![image](https://github.com/dotnet/maui/assets/77434865/49497c78-40d5-4b18-b0d1-73a8c44d8e17)

**Comment by DmitrikSerhiy** [comment]
Are there any updates for the .NET8.0?

**Comment by burhanemre-rightsoft** [comment]
Application: SampleApp.exe
CoreCLR Version: 8.0.123.58001
.NET Version: 8.0.1
Description: The process was terminated due to an unhandled exception.
Exception Info: System.TypeInitializationException: The type initializer for '<Module>' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'WinRT.ActivationFactory`1' threw an exception.
 ---> System.Runtime.InteropServices.COMException (0x80040154): Class not registered (0x80040154 (REGDB_E_CLASSNOTREG))
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at WinRT.BaseActivationFactory..ctor(String typeNamespace, String typeFullName)
   at WinRT.ActivationFactory`1..ctor()
   at WinRT.ActivationFactory`1..cctor()
   --- End of inner exception stack trace ---
   at WinRT.ActivationFactory`1.ActivateInstance[I]()
   at Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentInitializeOptions..ctor()
   at Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentManagerCS.AutoInitialize.get_Options() in %currentuser%\.nuget\packages\microsoft.windowsappsdk\1.3.230724000\include\DeploymentManagerAutoInitializer.cs:line 44
   at Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentManagerCS.AutoInitialize.AccessWindowsAppSDK() in %currentuser%\.nuget\packages\microsoft.windowsappsdk\1.3.230724000\include\DeploymentManagerAutoInitializer.cs:line 30
   at .cctor()
   --- End of inner exception stack trace ---

**Comment by burhanemre-rightsoft** [comment]
Edit: 
i found solution :
https://dev.to/serhii_korol_ab7776c50dba/all-about-the-local-publishing-of-applications-in-net-maui-4ki1
i use this publish command and exe worked successfully
dotnet publish -f net8.0-windows10.0.19041.0 -c Release -p:WindowsPackageType=None

**Comment by mkArtakMSFT** [comment]
@luatnt-work can you please specify the exact command that you use to try to publish as a single file (in your step No. 2).

**Comment by dzmitrymatus** [comment]
@mkArtakMSFT dotnet publish -f net9.0-windows10.0.19041.0 -c Release -p:WindowsAppSDKSelfContained=true -p:PublishSingleFile=true -r win-x64 --self-contained

**Comment by kubaflo** [comment]
Closing as externally owned. The relevant upstream owner or tracking destination is https://github.com/microsoft/WindowsAppSDK/issues. The complete MAUI report and discussion remain available here for reference.

> Disclosure: this comment was generated by AI.

**Comment by kubaflo** [comment]
Reopening — this issue should not have been closed.

It carries `s/verified` (a maintainer or partner reproduced it), `s/triaged` (it already went through triage). Those labels mean the report was already confirmed as a real product defect, so it is not eligible for backlog cleanup closure. Closure here requires specific fix evidence (a merged PR that closes it, or a `fixed-in-*` label), and there was none.

I have also removed the `s/try-latest-version` label that this cleanup pass added, so the policy bot will not auto-close it again.

Sorry for the noise, and thanks to everyone who flagged it.

> Disclosure: this comment was generated by AI.
