### ISSUE TITLE
Run ServiceController.Start(serviceName) throw exception  access is denied

### ISSUE THREAD

**Issue by danies8** [dotnet/maui#10088]
### Description

Run ServiceController.Start(serviceName) throw exception  access is denied

### Steps to Reproduce

1.Create maui app.
2.Create worker service.
3.Run this code from maui in VS as admin or MSIX
  ServiceController service = new ServiceController(servicName);
   service.Start();
    service.WaitForStatus(ServiceControllerStatus.Running);
4.Exception:
2022-09-13 10:57:12,636 [1] ERROR AutomationClient.Shared.Helpers.ServiceHelper - StartService
System.InvalidOperationException: Cannot open 'GS Automation Client Worker Service' service on computer '.'.
 ---> System.ComponentModel.Win32Exception (5): Access is denied.
   --- End of inner exception stack trace ---
   at System.ServiceProcess.ServiceController.GetServiceHandle(Int32 desiredAccess)
   at System.ServiceProcess.ServiceController.Start(String[] args)
   at System.ServiceProcess.ServiceController.Start()
   at AutomationClient.Shared.Helpers.ServiceHelper.StartService(String servicName)

### Link to public reproduction project repository

...

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Window 10 

### Did you find any workaround?

No

### Relevant log output

```shell
2022-09-13 10:57:12,636 [1] ERROR AutomationClient.Shared.Helpers.ServiceHelper - StartService
System.InvalidOperationException: Cannot open 'GS Automation Client Worker Service' service on computer '.'.
 ---> System.ComponentModel.Win32Exception (5): Access is denied.
   --- End of inner exception stack trace ---
   at System.ServiceProcess.ServiceController.GetServiceHandle(Int32 desiredAccess)
   at System.ServiceProcess.ServiceController.Start(String[] args)
   at System.ServiceProcess.ServiceController.Start()
   at AutomationClient.Shared.Helpers.ServiceHelper.StartService(String servicName)
```

**Comment by danies8** [comment]
Instring fileName = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location) + @"\runService.bat";
                    Process proc = new Process();
                    ProcessStartInfo info = new ProcessStartInfo(fileName, string.Empty);
                    info.WindowStyle = ProcessWindowStyle.Hidden;
                    info.UseShellExecute = true;
                    info.Verb = "runas";
                    proc.StartInfo = info;
                    proc.Start(); mean time I used powershell.

@ECHO OFF

echo start GS Automation Worker Service 
echo ---------------------------------------------------
sc.exe start "GS Automation Client Worker Service" 
pause
echo Done
