### ISSUE TITLE
Setting/changing bindable property tied to xaml just before navigating back to previous page results in app crash with error System.InvalidOperationException: View is Missing Handler

### ISSUE THREAD

**Issue by kkohler2** [dotnet/maui#10100]
### Description

If I set a property bound to xaml just before navigating back to previous page, I get the following error:
System.InvalidOperationException: View is Missing Handler
   at Microsoft.Maui.Platform.ViewExtensions.Arrange(IView view, LayoutChangeEventArgs e) in D:\a\_work\1\s\src\Core\src\Platform\Android\ViewExtensions.cs:line 525
   at Microsoft.Maui.Handlers.NavigationViewHandler.OnLayoutChanged(Object sender, LayoutChangeEventArgs e) in D:\a\_work\1\s\src\Core\src\Handlers\NavigationPage\NavigationViewHandler.Android.cs:line 49
   at Android.Views.View.IOnLayoutChangeListenerImplementor.OnLayoutChange(View v, Int32 left, Int32 top, Int32 right, Int32 bottom, Int32 oldLeft, Int32 oldTop, Int32 oldRight, Int32 oldBottom) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net6.0/android-31/mcw/Android.Views.View.cs:line 3535
   at Android.Views.View.IOnLayoutChangeListenerInvoker.n_OnLayoutChange_Landroid_view_View_IIIIIIII(IntPtr jnienv, IntPtr native__this, IntPtr native_v, Int32 left, Int32 top, Int32 right, Int32 bottom, Int32 oldLeft, Int32 oldTop, Int32 oldRight, Int32 oldBottom) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net6.0/android-31/mcw/Android.Views.View.cs:line 3431
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPLIIIIIIII_V(_JniMarshal_PPLIIIIIIII_V callback, IntPtr jnienv, IntPtr klazz, IntPtr p0, Int32 p1, Int32 p2, Int32 p3, Int32 p4, Int32 p5, Int32 p6, Int32 p7, Int32 p8) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 429

It doesn't matter where I am in my app when I navigate back to previous page after modifying bound property, it is the exact same callstack.

My xaml is something like:
    &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
    &lt;ContentPage xmlns=&quot;http://schemas.microsoft.com/dotnet/2021/maui&quot;
                 xmlns:x=&quot;http://schemas.microsoft.com/winfx/2009/xaml&quot; 
                 xmlns:localization=&quot;clr-namespace:Converge.Localization&quot;
                 xmlns:viewModel=&quot;clr-namespace:Converge.ViewModels&quot; 
                 BackgroundColor=&quot;#fffafafa&quot;
                 x:Class=&quot;Converge.Views.NoConnectionPage&quot;&gt;
        &lt;ContentPage.Content&gt;
            &lt;Frame VerticalOptions=&quot;Center&quot; HasShadow=&quot;false&quot; Padding=&quot;0,20,0,0&quot; CornerRadius=&quot;0&quot; x:DataType=&quot;viewModel:NoConnectionPageViewModel&quot; BorderColor=&quot;Transparent&quot;&gt;
                &lt;Grid RowSpacing=&quot;8&quot; &gt;
                    &lt;Grid.RowDefinitions&gt;
                        &lt;RowDefinition Height=&quot;2*&quot;/&gt;
                        &lt;RowDefinition Height=&quot;2*&quot;/&gt;
                        &lt;RowDefinition Height=&quot;1*&quot;/&gt;
                        &lt;RowDefinition Height=&quot;1*&quot;/&gt;
                         &lt;RowDefinition Height=&quot;0.75*&quot;/&gt;
                        &lt;RowDefinition Height=&quot;1.25*&quot;/&gt;
                    &lt;/Grid.RowDefinitions&gt;
                    &lt;Frame HasShadow=&quot;false&quot; Padding=&quot;10,20&quot; BorderColor=&quot;Transparent&quot;&gt;
                         &lt;Image Source=&quot;logo.png&quot; Grid.Row=&quot;0&quot;  VerticalOptions=&quot;End&quot;/&gt;
                    &lt;/Frame&gt;
                    &lt;StackLayout Grid.Row=&quot;5&quot; Orientation=&quot;Horizontal&quot; HorizontalOptions=&quot;CenterAndExpand&quot;&gt;
                        &lt;Label Text=&quot;{Binding RetryCountMessage}&quot; HorizontalOptions=&quot;Center&quot; TextColor=&quot;{StaticResource MyProfileColor}&quot; FontAttributes=&quot;Bold&quot; VerticalOptions=&quot;Start&quot; FontSize=&quot;20&quot; /&gt;
                        &lt;ActivityIndicator IsVisible=&quot;{Binding CheckingForServer}&quot; IsRunning=&quot;True&quot; Color=&quot;#7cb240&quot; VerticalOptions=&quot;Start&quot; /&gt;
                    &lt;/StackLayout&gt;
                &lt;/Grid&gt;
            &lt;/Frame&gt;
        &lt;/ContentPage.Content&gt;
    &lt;/ContentPage&gt;

A ViewModel is bound to BindableContext of the page that contains bindable properties for 
string RetryCountMessage
bool CheckingForServer

Setting/changing either of the properties right before navigating back to previous page results in the error.

All I am doing is setting RetryCountMessage and/or CheckingForServer, then navigating back to previous page:
await _rootPage.Navigation.PopAsync(false);  
_rootPage is a NavigationPage that is set to MainPage in app.xaml.cs

I have seen this a number of times throughout my application, though my attempts to create a very simple app that reproduces the issue have not been successful, thus the reason I am not linking to a repository.  Every crash in my app is the same scenario - navigating back to previous page and app crashes with same call stack.  I have found that I am setting/modifying a bindable property tied to the UI in each crash scenario.

The crash is definitely related to the page I am leaving, not the page I am going back to.  I have done some tests where the first page is nothing more than a button with code that executes on clicking in the code behind for the page.  If I remove or comment out setting the properties on the second page just before navigation back to the first page, then the crash goes away.

Same code (allowing for namespace changes in xaml) executes without issue in Xamarin.Forms

### Steps to Reproduce

Create an app with two pages
Add nuget reference to CommunityToolkit.Mvvm
Add a button to first page to navigate to second page (I am NOT using Shell!).  Add code behind method to navigate to second page.
In second page:
Add ViewModel for page and hook viewmodel up to page's BindingContext.
Derive ViewModel from ObservableObject (from CommunityToolkit.Mvvm) or comparable mvvm library.
Add a control (label, activity indicator, etc) to page and add binding to a property.  Include property with mvvm binding and backing variable to viewmodel, something like

        private bool _checkingForServer = true;
        public bool CheckingForServer
        {
            get { return _checkingForServer; }
            set { SetProperty(ref _checkingForServer, value); }
        }

Add a button to second page.  Add code to execute when button is clicked to navigate back to previous page.  Prior to navigation, change property value like: CheckingForServer = false;

Note: instead if button, a timer can be used to navigate when timer goes off, after setting property.

Run app
Click button on first page to navigate to second page
Click button (or have timer go off) to navigate back to first page (await rootpage.Navigate.PopAsync())

App crashes with callstack:

System.InvalidOperationException: View is Missing Handler
   at Microsoft.Maui.Platform.ViewExtensions.Arrange(IView view, LayoutChangeEventArgs e) in D:\a\_work\1\s\src\Core\src\Platform\Android\ViewExtensions.cs:line 525
   at Microsoft.Maui.Handlers.NavigationViewHandler.OnLayoutChanged(Object sender, LayoutChangeEventArgs e) in D:\a\_work\1\s\src\Core\src\Handlers\NavigationPage\NavigationViewHandler.Android.cs:line 49
   at Android.Views.View.IOnLayoutChangeListenerImplementor.OnLayoutChange(View v, Int32 left, Int32 top, Int32 right, Int32 bottom, Int32 oldLeft, Int32 oldTop, Int32 oldRight, Int32 oldBottom) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net6.0/android-31/mcw/Android.Views.View.cs:line 3535
   at Android.Views.View.IOnLayoutChangeListenerInvoker.n_OnLayoutChange_Landroid_view_View_IIIIIIII(IntPtr jnienv, IntPtr native__this, IntPtr native_v, Int32 left, Int32 top, Int32 right, Int32 bottom, Int32 oldLeft, Int32 oldTop, Int32 oldRight, Int32 oldBottom) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net6.0/android-31/mcw/Android.Views.View.cs:line 3431
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPLIIIIIIII_V(_JniMarshal_PPLIIIIIIII_V callback, IntPtr jnienv, IntPtr klazz, IntPtr p0, Int32 p1, Int32 p2, Int32 p3, Int32 p4, Int32 p5, Int32 p6, Int32 p7, Int32 p8) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 429

### Link to public reproduction project repository

n/a

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 9

### Did you find any workaround?

The only way I found to fix this is to NOT set any bindable properties prior to navigation.

### Relevant log output

```shell
System.InvalidOperationException: View is Missing Handler
   at Microsoft.Maui.Platform.ViewExtensions.Arrange(IView view, LayoutChangeEventArgs e) in D:\a\_work\1\s\src\Core\src\Platform\Android\ViewExtensions.cs:line 525
   at Microsoft.Maui.Handlers.NavigationViewHandler.OnLayoutChanged(Object sender, LayoutChangeEventArgs e) in D:\a\_work\1\s\src\Core\src\Handlers\NavigationPage\NavigationViewHandler.Android.cs:line 49
   at Android.Views.View.IOnLayoutChangeListenerImplementor.OnLayoutChange(View v, Int32 left, Int32 top, Int32 right, Int32 bottom, Int32 oldLeft, Int32 oldTop, Int32 oldRight, Int32 oldBottom) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net6.0/android-31/mcw/Android.Views.View.cs:line 3535
   at Android.Views.View.IOnLayoutChangeListenerInvoker.n_OnLayoutChange_Landroid_view_View_IIIIIIII(IntPtr jnienv, IntPtr native__this, IntPtr native_v, Int32 left, Int32 top, Int32 right, Int32 bottom, Int32 oldLeft, Int32 oldTop, Int32 oldRight, Int32 oldBottom) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net6.0/android-31/mcw/Android.Views.View.cs:line 3431
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPLIIIIIIII_V(_JniMarshal_PPLIIIIIIII_V callback, IntPtr jnienv, IntPtr klazz, IntPtr p0, Int32 p1, Int32 p2, Int32 p3, Int32 p4, Int32 p5, Int32 p6, Int32 p7, Int32 p8) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 429
```

**Comment by jsuarezruiz** [comment]
Could you include a small sample where reproduce the issue?
