### ISSUE TITLE
AndroidMessageHandler or HttpClientHandler throw System.ObjectDisposedException: Cannot access a closed Stream

### ISSUE THREAD

**Issue by PontiacGTX** [dotnet/maui#10121]
### Description

I am trying to do a local http post request from a http client but whenever I tried overriding to check the signed certificate by giving a HttpClientHandler or AndroidMessageHandler  ot the http client, it ends up throwing an exception when I call to PostAsync method

### Steps to Reproduce

Create a Maui Project
On Program Add a HttpClient to the DI container

#if DEBUG
	     var httpHelper = new HttpClientHandlerHelper();

	     var insecureHandler =new CustomAndroidMessageHandler();//httpHelper.GetInsecureHandler()
        builder.Services.AddSingleton<HttpClient>(x=> new HttpClient(httpHelper.GetInsecureHandler(), false));

#else
		builder.Services.AddSingleton<HttpClient>();
#endif

declare a class to get the http client handler

HttpClientHandlerHelper

  public class HttpClientHandlerHelper:IDisposable
    {
        private bool disposedValue;

        public HttpClientHandler GetInsecureHandler()
        {
            HttpClientHandler handler = new HttpClientHandler();
            handler.ClientCertificateOptions = ClientCertificateOption.Manual;
            handler.ServerCertificateCustomValidationCallback = (message, cert, chain, errors) =>
            {
               
                return true;
            };
            return handler;
        }

        protected virtual void Dispose(bool disposing)
        {
            if (!disposedValue)
            {
                if (disposing)
                {
                    // TODO: eliminar el estado administrado (objetos administrados)
                }

                // TODO: liberar los recursos no administrados (objetos no administrados) y reemplazar el finalizador
                // TODO: establecer los campos grandes como NULL
                disposedValue = true;
            }
        }

      
        public void Dispose()
        {
            // No cambie este código. Coloque el código de limpieza en el método "Dispose(bool disposing)".
            Dispose(disposing: true);
            GC.SuppressFinalize(this);
        }
    }

make some service using this HttpClient by DI and then call a method using PostAsync, but in the url the base url should contain
the local ip in my case is like, while calling a webapi running 

http://192.168.250.3:5000/api/Account/Create

### Link to public reproduction project repository

https://github.com/PontiacGTX/MauiChat

### Version with bug

6.0 Release Candidate 2 or older

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

API 30 Android 11, WIndows 10 1709

### Did you find any workaround?

Not yet

### Relevant log output

```shell
System.ObjectDisposedException: Cannot access a closed Stream.
   at System.IO.MemoryStream.EnsureNotClosed()
   at System.IO.MemoryStream.get_Length()
   at System.Net.Http.HttpContent.GetComputedOrBufferLength()
   at System.Net.Http.Headers.HttpContentHeaders.get_ContentLength()
   at Xamarin.Android.Net.AndroidMessageHandler.SetupRequestBody(HttpURLConnection httpConnection, HttpRequestMessage request) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Xamarin.Android.Net/AndroidMessageHandler.cs:line 1132
   at Xamarin.Android.Net.AndroidMessageHandler.SetupRequestInternal(HttpRequestMessage request, URLConnection conn) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Xamarin.Android.Net/AndroidMessageHandler.cs:line 984
   at Xamarin.Android.Net.AndroidMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Xamarin.Android.Net/AndroidMessageHandler.cs:line 374
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at MauiChat.Common.Services.ChatServicesService.CreateUser(String phoneNumber) in C:\Users\PontiacGTX\Source\Repos\MauiChat\Common\Services\ChatServicesService.cs:line 38}
```

**Comment by PureWeen** [comment]
Since you're registering as a singleton I'm guessing you're disposing of it and it keeps returning the disposed instance but need a sample to be sure.

**Comment by PontiacGTX** [comment]
> Since you're registering as a singleton I'm guessing you're disposing of it and it keeps returning the disposed instance but need a sample to be sure.

ok try this repo
https://github.com/PontiacGTX/MauiChat/

**Comment by PontiacGTX** [comment]
> Since you're registering as a singleton I'm guessing you're disposing of it and it keeps returning the disposed instance but need a sample to be sure.

I have looking and I think if I could pass my own HttpMessageInvoker I could assign it to not be disposed
https://github.com/dotnet/runtime/blob/4ff5a3a85a9b0de7ab9e9267959e668142815f4f/src/libraries/System.Net.Http/src/System/Net/Http/HttpMessageInvoker.cs#L124

https://microsoft.github.io/reverse-proxy/articles/http-client-config.html

**Comment by hartez** [comment]
@PontiacGTX If you configure the HttpClient using AddTransient instead of AddSingleton, does the problem persist?

**Comment by PontiacGTX** [comment]
> @PontiacGTX If you configure the HttpClient using AddTransient instead of AddSingleton, does the problem persist?

same exception
System.ObjectDisposedException: Cannot access a closed Stream.
   at System.IO.MemoryStream.EnsureNotClosed()
   at System.IO.MemoryStream.CopyToAsync(Stream destination, Int32 bufferSize, CancellationToken cancellationToken)
   at Xamarin.Android.Net.AndroidMessageHandler.WriteRequestContentToOutput(HttpRequestMessage request, HttpURLConnection httpConnection, CancellationToken cancellationToken) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Xamarin.Android.Net/AndroidMessageHandler.cs:line 458
   at Xamarin.Android.Net.AndroidMessageHandler.DoProcessRequest(HttpRequestMessage request, URL javaUrl, HttpURLConnection httpConnection, CancellationToken cancellationToken, RequestRedirectionState redirectState) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Xamarin.Android.Net/AndroidMessageHandler.cs:line 533
   at Xamarin.Android.Net.AndroidMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Xamarin.Android.Net/AndroidMessageHandler.cs:line 375
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at MauiChat.Common.HelperClass.HttpClientHelper.PostStringDataAsync(HttpClient httpClient, Object data, String url) in C:\Users\PontiacGTX\source\repos\MauiChat\Common\HelperClass\HttpClientHelper.cs:line 19
   at MauiChat.Common.Services.ChatServicesService.CreateUser(String phoneNumber) in C:\Users\PontiacGTX\source\repos\MauiChat\Common\Services\ChatServicesService.cs:line 39}

**Comment by hartez** [comment]
@PontiacGTX does the endpoint you are posting to respond with a redirect?

**Comment by PontiacGTX** [comment]
> @PontiacGTX does the endpoint you are posting to respond with a redirect?

no I have tried it with postman and returns Ok and then I see that it isnt being called with my debugger. I think IISExpress should be fine since I am doing a request from  a local ip, curiously if the server has a timeout the the http client states it has time out but when reading the message it seems to have issues I will try again uninstalling my previous Android SDKs and see if that is the issue, or how can I use the latest version of AndroidClientHandler?

**Comment by joebeernink** [comment]
Also seeing this issue. Only affects POST calls with content and the HttpClient is injected, we see this. If we use the same HttpClient for a get, or a post with no content, it works fine. 

However, if we create a brand new Http client immediately before the call, it's fine.

**Comment by PontiacGTX** [comment]
> Also seeing this issue. Only affects POST calls with content and the HttpClient is injected, we see this. If we use the same HttpClient for a get, or a post with no content, it works fine.
> 
> However, if we create a brand new Http client immediately before the call, it's fine.

So what should I do is instancing a new http client before making a post?as a workaround?

**Comment by joebeernink** [comment]
This is what we had to do. It's not great, but at least it unblocked us.

public async Task AddAttendeeAsync(EventAttendee eventAttendee, CancellationToken cancellationToken = default)
        {
            try
            {
                var content = JsonContent.Create(eventAttendee, typeof(EventAttendee), null, SerializerOptions);



               var authorizedHttpClient = HttpClientService.CreateAuthorizedClient();
                var httpClient = new HttpClient();
                httpClient.BaseAddress = authorizedHttpClient.BaseAddress;



               using (var response = await httpClient.PostAsync(EventAttendeeApi, content, cancellationToken))
                {
                    response.EnsureSuccessStatusCode();
                }
            }
            catch (Exception ex)
            {
                Debug.WriteLine(@"\tERROR {0}", ex.Message);
                throw;
            }
        }

**Comment by thinkOfaNumber** [comment]
I suspect I have the same problem as the OP, given I'm also using a `CustomAndroidMessageHandler` to override the hostname verification and certificate, and I'm also using an IP address and HTTP `http://192.168.2.127:5241/api/v1/Login`.

HttpClient throws the same exception if my server redirects http to https, but if I turn that off without touching the MAUI app, it works.

I am injecting HttpClient as a singleton, using `AddTransient` makes no difference to the exception:

```
builder.Services
	//... other services ...
	.AddSingleton<HttpsClientHandlerService>()
	.AddSingleton<HttpClient>(provider =>
	{
		var handler = provider.GetService<HttpsClientHandlerService>();
		if (handler == null)
		{
			return new HttpClient();
		}
		else
		{
			return new HttpClient(handler.GetPlatformMessageHandler());
		}
	})
```

HttpsClientHandlerService handles both hostname and certificate:
```
public class HttpsClientHandlerService
{
    public HttpMessageHandler GetPlatformMessageHandler()
    {
#if ANDROID
        var handler = new CustomAndroidMessageHandler();
        handler.ServerCertificateCustomValidationCallback = (message, cert, chain, errors) =>
        {
            if (cert != null && cert.Issuer.Equals("CN=localhost"))
                return true;
            return errors == System.Net.Security.SslPolicyErrors.None;
        };
        return handler;
#elif IOS
        var handler = new NSUrlSessionHandler
        {
            TrustOverrideForUrl = IsHttpsLocalhost
        };
        return handler;
#else
     throw new PlatformNotSupportedException("Only Android and iOS supported.");
#endif
    }

#if ANDROID
    internal sealed class CustomAndroidMessageHandler : Xamarin.Android.Net.AndroidMessageHandler
    {
        protected override Javax.Net.Ssl.IHostnameVerifier GetSSLHostnameVerifier(Javax.Net.Ssl.HttpsURLConnection connection)
            => new CustomHostnameVerifier();

        private sealed class CustomHostnameVerifier : Java.Lang.Object, Javax.Net.Ssl.IHostnameVerifier
        {
            public bool Verify(string hostname, Javax.Net.Ssl.ISSLSession session)
            {
                return Javax.Net.Ssl.HttpsURLConnection.DefaultHostnameVerifier.Verify(hostname, session) ||
                    ((hostname == "10.0.2.2" || hostname == "192.168.2.127") && session.PeerPrincipal?.Name == "CN=localhost");
            }
        }
    }
#elif IOS
    public bool IsHttpsLocalhost(NSUrlSessionHandler sender, string url, Security.SecTrust trust)
    {
        if (url.StartsWith("https://localhost"))
            return true;
        return false;
    }
#endif
}
```

The server is a .NET Core 6 api using 
```
var app = builder.Build();
// ...
app.UseHttpsRedirection(); //
```

commenting out that last `app.UseHttpsRedirection();` on the server makes the MAUI client connect without exception.

**Comment by owl-guy** [comment]
I have the same problem in the .NET 8 Release Version with the following Stacktrace:
   at System.IO.MemoryStream.EnsureNotClosed()
   at System.IO.MemoryStream.CopyToAsync(Stream destination, Int32 bufferSize, CancellationToken cancellationToken)
   at Xamarin.Android.Net.AndroidMessageHandler.WriteRequestContentToOutput(HttpRequestMessage request, HttpURLConnection httpConnection, CancellationToken cancellationToken) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Xamarin.Android.Net/AndroidMessageHandler.cs:line 547
   at Xamarin.Android.Net.AndroidMessageHandler.DoProcessRequest(HttpRequestMessage request, URL javaUrl, HttpURLConnection httpConnection, CancellationToken cancellationToken, RequestRedirectionState redirectState) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Xamarin.Android.Net/AndroidMessageHandler.cs:line 623
   at Xamarin.Android.Net.AndroidMessageHandler.DoSendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Xamarin.Android.Net/AndroidMessageHandler.cs:line 456
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
