### ISSUE TITLE
Tapping on entry field throws an NSInvalidArgumentException running on an iPhone device

### ISSUE THREAD

**Issue by Muesli84** [dotnet/maui#10194]
### Description

I have an entry field on my page with a text set.

When I tap on that field at the end of the text, everything is fine.
When I tap on that field in the middle of the text, an unhandled exception is thrown.

No exception is thrown on the iPhone simulator, it happens only on my real device.

**Exception:**

`ObjCRuntime.ObjCException
  Nachricht = Objective-C exception thrown.  Name: NSInvalidArgumentException Reason: -[<_UIObscurableTextContentStorage: 0x2826b9b30> offsetFromLocation:toLocation:] received invalid locations 0 (null)

_**[more information in log output]**_

  Stapelüberwachung:
   at UIKit.UITextField.GetOffsetFromPosition(UITextPosition , UITextPosition )
   at Microsoft.Maui.Platform.TextInputExtensions.GetCursorPosition(IUITextInput platformView, Int32 cursorOffset)
   at Microsoft.Maui.Handlers.EntryHandler.OnSelectionChanged(Object sender, EventArgs e)
   at Microsoft.Maui.Platform.MauiTextField.set_SelectedTextRange(UITextRange value)
   at UIKit.UIApplication.Main(String[] , Type , Type )
   at EntryFieldOffsetError.Program.Main(String[] args) in C:\Users\mstro\source\repos\Muesli84\Issues\VisualStudioIssues\EntryFieldOffsetError\Platforms\iOS\Program.cs:line 13

**Environment**

Visual Studio 2022 Version 17.3.4 on Windows 11 21H2; 
iPhone SE Gen 3 with iOS 16.0; 
MacBook with macOS Monterey 12.6, XCode 13.4.1, Visual Studio for Mac 17.4 Preview (build 1552)

### Steps to Reproduce

1. Create a new project with template ".NET Maui-App" using .NET 6 (6.0.401)
2. I disabled android as a target.
3. Add an entry-field on MainPage.xaml. Set the Text-property with a text you like.
4. Deploy and run the app on an iPhone device.
5. Tap on the entry-field in the middle of the text.

### Link to public reproduction project repository

https://github.com/Muesli84/Issues/tree/master/VisualStudioIssues/EntryFieldOffsetError

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Windows

### Affected platform versions

Windows 11 21H2; iOS 16.0; 

### Relevant log output

```shell
Loaded assembly: /private/var/containers/Bundle/Application/25F84BB2-DF53-4E22-BC8B-38D67FE7F0D2/EntryFieldOffsetError.app/Microsoft.iOS.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/25F84BB2-DF53-4E22-BC8B-38D67FE7F0D2/EntryFieldOffsetError.app/EntryFieldOffsetError.dll
Loaded assembly: /private/var/containers/Bundle/Application/25F84BB2-DF53-4E22-BC8B-38D67FE7F0D2/EntryFieldOffsetError.app/System.Runtime.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/25F84BB2-DF53-4E22-BC8B-38D67FE7F0D2/EntryFieldOffsetError.app/System.Private.Uri.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/25F84BB2-DF53-4E22-BC8B-38D67FE7F0D2/EntryFieldOffsetError.app/Microsoft.Maui.Controls.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/25F84BB2-DF53-4E22-BC8B-38D67FE7F0D2/EntryFieldOffsetError.app/System.Runtime.InteropServices.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/25F84BB2-DF53-4E22-BC8B-38D67FE7F0D2/EntryFieldOffsetError.app/System.Collections.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/25F84BB2-DF53-4E22-BC8B-38D67FE7F0D2/EntryFieldOffsetError.app/Microsoft.Maui.Graphics.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/25F84BB2-DF53-4E22-BC8B-38D67FE7F0D2/EntryFieldOffsetError.app/System.Numerics.Vectors.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/25F84BB2-DF53-4E22-BC8B-38D67FE7F0D2/EntryFieldOffsetError.app/System.ObjectModel.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/25F84BB2-DF53-4E22-BC8B-38D67FE7F0D2/EntryFieldOffsetError.app/System.Xml.ReaderWriter.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/25F84BB2-DF53-4E22-BC8B-38D67FE7F0D2/EntryFieldOffsetError.app/System.Private.Xml.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/25F84BB2-DF53-4E22-BC8B-38D67FE7F0D2/EntryFieldOffsetError.app/System.Runtime.CompilerServices.Unsafe.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/25F84BB2-DF53-4E22-BC8B-38D67FE7F0D2/EntryFieldOffsetError.app/System.Net.Primitives.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/25F84BB2-DF53-4E22-BC8B-38D67FE7F0D2/EntryFieldOffsetError.app/System.Net.Http.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/25F84BB2-DF53-4E22-BC8B-38D67FE7F0D2/EntryFieldOffsetError.app/System.Collections.Concurrent.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/25F84BB2-DF53-4E22-BC8B-38D67FE7F0D2/EntryFieldOffsetError.app/System.Text.RegularExpressions.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/25F84BB2-DF53-4E22-BC8B-38D67FE7F0D2/EntryFieldOffsetError.app/System.Collections.NonGeneric.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/25F84BB2-DF53-4E22-BC8B-38D67FE7F0D2/EntryFieldOffsetError.app/System.ComponentModel.TypeConverter.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/25F84BB2-DF53-4E22-BC8B-38D67FE7F0D2/EntryFieldOffsetError.app/System.Drawing.Primitives.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/25F84BB2-DF53-4E22-BC8B-38D67FE7F0D2/EntryFieldOffsetError.app/System.ComponentModel.Primitives.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/25F84BB2-DF53-4E22-BC8B-38D67FE7F0D2/EntryFieldOffsetError.app/System.ComponentModel.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/25F84BB2-DF53-4E22-BC8B-38D67FE7F0D2/EntryFieldOffsetError.app/System.Linq.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/25F84BB2-DF53-4E22-BC8B-38D67FE7F0D2/EntryFieldOffsetError.app/System.Collections.Specialized.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/25F84BB2-DF53-4E22-BC8B-38D67FE7F0D2/EntryFieldOffsetError.app/System.Memory.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/25F84BB2-DF53-4E22-BC8B-38D67FE7F0D2/EntryFieldOffsetError.app/System.Threading.Thread.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/25F84BB2-DF53-4E22-BC8B-38D67FE7F0D2/EntryFieldOffsetError.app/System.Threading.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/25F84BB2-DF53-4E22-BC8B-38D67FE7F0D2/EntryFieldOffsetError.app/Microsoft.Maui.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/25F84BB2-DF53-4E22-BC8B-38D67FE7F0D2/EntryFieldOffsetError.app/Microsoft.Extensions.Logging.Abstractions.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/25F84BB2-DF53-4E22-BC8B-38D67FE7F0D2/EntryFieldOffsetError.app/Microsoft.Extensions.DependencyInjection.Abstractions.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/25F84BB2-DF53-4E22-BC8B-38D67FE7F0D2/EntryFieldOffsetError.app/System.Security.Cryptography.Primitives.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/25F84BB2-DF53-4E22-BC8B-38D67FE7F0D2/EntryFieldOffsetError.app/Microsoft.Maui.Essentials.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/25F84BB2-DF53-4E22-BC8B-38D67FE7F0D2/EntryFieldOffsetError.app/System.Console.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/25F84BB2-DF53-4E22-BC8B-38D67FE7F0D2/EntryFieldOffsetError.app/Microsoft.Extensions.Configuration.Abstractions.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/25F84BB2-DF53-4E22-BC8B-38D67FE7F0D2/EntryFieldOffsetError.app/Microsoft.Extensions.Primitives.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/25F84BB2-DF53-4E22-BC8B-38D67FE7F0D2/EntryFieldOffsetError.app/Microsoft.Extensions.Configuration.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/25F84BB2-DF53-4E22-BC8B-38D67FE7F0D2/EntryFieldOffsetError.app/Microsoft.Extensions.Logging.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/25F84BB2-DF53-4E22-BC8B-38D67FE7F0D2/EntryFieldOffsetError.app/Microsoft.Extensions.Options.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/25F84BB2-DF53-4E22-BC8B-38D67FE7F0D2/EntryFieldOffsetError.app/Microsoft.Extensions.DependencyInjection.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/25F84BB2-DF53-4E22-BC8B-38D67FE7F0D2/EntryFieldOffsetError.app/System.Linq.Expressions.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/25F84BB2-DF53-4E22-BC8B-38D67FE7F0D2/EntryFieldOffsetError.app/System.Diagnostics.TraceSource.dll [External]
Loaded assembly: /private/var/containers/Bundle/Application/25F84BB2-DF53-4E22-BC8B-38D67FE7F0D2/EntryFieldOffsetError.app/Microsoft.Maui.Controls.Xaml.dll [External]
Thread started:  #2
Resolved pending breakpoint for 'EntryFieldOffsetError.Program.Main(System.String[])' to C:\Users\mstro\source\repos\Muesli84\Issues\VisualStudioIssues\EntryFieldOffsetError\Platforms\iOS\Program.cs:10 [0x00000].
**ObjCRuntime.ObjCException:** 'Objective-C exception thrown.  Name: NSInvalidArgumentException Reason: -[<_UIObscurableTextContentStorage: 0x282f20870> offsetFromLocation:toLocation:] received invalid locations 0 (null)
Native stack trace:
	0   CoreFoundation                      0x0000000194fa6254 42C5C917-0447-3995-B50F-DE4D132C2435 + 41556
	1   libobjc.A.dylib                     0x000000018e373a68 objc_exception_throw + 60
	2   CoreFoundation                      0x0000000195095e04 42C5C917-0447-3995-B50F-DE4D132C2435 + 1023492
	3   UIFoundation                        0x000000019f2076a0 835A018D-AF1D-38C8-A2D5-4464EA59D0B9 + 140960
	4   UIKitCore                           0x0000000197ab4904 7B942FA4-CB76-3375-9972-F58C14492FB4 + 10004740
	5   UIKitCore                           0x0000000197477ce4 7B942FA4-CB76-3375-9972-F58C14492FB4 + 3464420
	6   UIKitCore                           0x0000000197477c7c 7B942FA4-CB76-3375-9972-F58C14492FB4 + 3464316
	7   UIKitCore                           0x0000000197477c10 7B942FA4-CB76-3375-9972-F58C14492FB4 + 3464208
	8   EntryFieldOffsetError               0x0000000100f2a6e8 _ZN16XamarinCallState3selEv + 3740
	9   EntryFieldOffsetError               0x0000000100efd32c EntryFieldOffsetError + 86828
	10  EntryFieldOffsetError               0x00000001011bf8e0 _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 2149132
	11  EntryFieldOffsetError               0x00000001011b4ecc _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 2105592
	12  EntryFieldOffsetError               0x00000001011b32d0 _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 2098428
	13  EntryFieldOffsetError               0x0000000101181728 _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 1894740
	14  EntryFieldOffsetError               0x00000001010cbdac _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 1150936
	15  EntryFieldOffsetError               0x00000001010cf758 _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 1165700
	16  EntryFieldOffsetError               0x00000001011fd60c _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 2402360
	17  EntryFieldOffsetError               0x00000001011fd720 _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 2402636
	18  UIKitCore                           0x000000019727e238 7B942FA4-CB76-3375-9972-F58C14492FB4 + 1393208
	19  UIKitCore                           0x0000000197d47d70 7B942FA4-CB76-3375-9972-F58C14492FB4 + 12705136
	20  UIKitCore                           0x0000000197d49570 7B942FA4-CB76-3375-9972-F58C14492FB4 + 12711280
	21  UIKitCore                           0x0000000197ffc054 7B942FA4-CB76-3375-9972-F58C14492FB4 + 15540308
	22  UIKitCore                           0x0000000197ffbe4c 7B942FA4-CB76-3375-9972-F58C14492FB4 + 15539788
	23  UIKitCore                           0x0000000197ffc5e0 7B942FA4-CB76-3375-9972-F58C14492FB4 + 15541728
	24  UIKitCore                           0x00000001973796f8 7B942FA4-CB76-3375-9972-F58C14492FB4 + 2422520
	25  UIKitCore                           0x0000000197a6b728 7B942FA4-CB76-3375-9972-F58C14492FB4 + 9705256
	26  UIKitCore                           0x00000001971e9180 7B942FA4-CB76-3375-9972-F58C14492FB4 + 782720
	27  UIKitCore                           0x0000000197556dfc 7B942FA4-CB76-3375-9972-F58C14492FB4 + 4378108
	28  UIKitCore                           0x00000001972d0b94 7B942FA4-CB76-3375-9972-F58C14492FB4 + 1731476
	29  UIKitCore                           0x00000001971b11dc 7B942FA4-CB76-3375-9972-F58C14492FB4 + 553436
	30  UIKitCore                           0x000000019725d358 7B942FA4-CB76-3375-9972-F58C14492FB4 + 1258328
	31  UIKitCore                           0x0000000197ade1d8 7B942FA4-CB76-3375-9972-F58C14492FB4 + 10174936
	32  UIKitCore                           0x0000000197221d18 7B942FA4-CB76-3375-9972-F58C14492FB4 + 1015064
	33  UIKitCore                           0x0000000197226674 7B942FA4-CB76-3375-9972-F58C14492FB4 + 1033844
	34  UIKitCore                           0x0000000197225944 7B942FA4-CB76-3375-9972-F58C14492FB4 + 1030468
	35  UIKitCore                           0x0000000197225000 7B942FA4-CB76-3375-9972-F58C14492FB4 + 1028096
	36  UIKitCore                           0x000000019726cd64 7B942FA4-CB76-3375-9972-F58C14492FB4 + 1322340
	37  UIKitCore                           0x0000000197eb3a30 7B942FA4-CB76-3375-9972-F58C14492FB4 + 14195248
	38  UIKitCore                           0x000000019777b678 7B942FA4-CB76-3375-9972-F58C14492FB4 + 6624888
	39  UIKitCore                           0x0000000197dba904 7B942FA4-CB76-3375-9972-F58C14492FB4 + 13175044
	40  UIKitCore                           0x0000000197db9ad0 7B942FA4-CB76-3375-9972-F58C14492FB4 + 13171408
	41  CoreFoundation                      0x000000019507222c 42C5C917-0447-3995-B50F-DE4D132C2435 + 877100
	42  CoreFoundation                      0x000000019507e614 42C5C917-0447-3995-B50F-DE4D132C2435 + 927252
	43  CoreFoundation                      0x000000019500251c 42C5C917-0447-3995-B50F-DE4D132C2435 + 419100
	44  CoreFoundation                      0x0000000195017eb8 42C5C917-0447-3995-B50F-DE4D132C2435 + 507576
	45  CoreFoundation                      0x000000019501d1e4 CFRunLoopRunSpecific + 612
	46  GraphicsServices                    0x00000001cde3d368 GSEventRunModal + 164
	47  UIKitCore                           0x00000001974ccd88 7B942FA4-CB76-3375-9972-F58C14492FB4 + 3812744
	48  UIKitCore                           0x00000001974cc9ec UIApplicationMain + 340
	49  EntryFieldOffsetError               0x00000001011c03c0 _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 2151916
	50  EntryFieldOffsetError               0x00000001011bf5c8 _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 2148340
	51  EntryFieldOffsetError               0x00000001011b4dd0 _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 2105340
	52  EntryFieldOffsetError               0x00000001011b32d0 _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 2098428
	53  EntryFieldOffsetError               0x0000000101181728 _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 1894740
	54  EntryFieldOffsetError               0x00000001010cbdac _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 1150936
	55  EntryFieldOffsetError               0x00000001010d1848 _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 1174132
	56  EntryFieldOffsetError               0x0000000101186840 _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 1915500
	57  EntryFieldOffsetError               0x0000000100f2963c xamarin_log + 21332
	58  EntryFieldOffsetError               0x00000001011f462c _ZNK3icu6number23NumberFormatterSettingsINS0_24LocalizedNumberFormatterEE10toSkeletonER10UErrorCode + 2365528
	59  dyld                                0x00000001b3341948 341BBF64-6034-357E-8AA6-E1E4B988E03C + 88392
'

Die App wurde beendet.
```

**Comment by RonnyRos** [comment]
Having the same issue, with .net 7 RC1 + newest Xamarin iOS.
long tapping entry and selecting different character position, causes a application crash:
	ex	{ObjCRuntime.ObjCException: Objective-C exception thrown.  Name: NSInvalidArgumentException Reason: -[<_UIObscurableTextContentStorage: 0x600002fb8690> offsetFromLocation:toLocation:] received invalid locations 0 (null) Native stack trace: 	0   CoreFoundation  …}

**Comment by robertff** [comment]
Having the same issue, with Win10+IOS16+VS2022 Preview 2.1   17.4.0

**Comment by jsuarezruiz** [comment]
Might be related to this one:
https://github.com/xamarin/xamarin-macios/issues/15677

**Comment by Redth** [comment]
We have a workaround you can implement for now:

1. Create the following class
```
#if IOS
public class WorkaroundMauiTextField : Microsoft.Maui.Platform.MauiTextField
{
    public WorkaroundMauiTextField()
        : base()
    {
        BorderStyle = UIKit.UITextBorderStyle.RoundedRect;
        ClipsToBounds = true;
    }
    [Foundation.Export("selectedTextRange")]
    public new UIKit.UITextRange SelectedTextRange {
        get => base.SelectedTextRange;
        set => base.SelectedTextRange = value;
    }
}
#endif
```

2. In your MauiProgram.cs (or anywhere before Entry handlers will be created in the app), call the following:
```
#if IOS
Microsoft.Maui.Handlers.EntryHandler.PlatformViewFactory =
    handler => new WorkaroundMauiTextField();
#endif
```

This should work around the crash for now for iOS 16.

**Comment by RonnyRos** [comment]
Can confirm this work, great work and response time as always! Thank you!

**Comment by Muesli84** [comment]
I made the mistake and upgraded Visual Studio to 17.3.5.
Now I have other errors, that prevent VS to deploy the app. 
A reinstalled 17.3.4 now does not provide any simulator or device to deploy to.

Sorry, but I cannot confirm the workaround to work for me, but RonnyRos did.

**Comment by Redth** [comment]
Fixed in the latest release.
