### ISSUE TITLE
[Android] Build fails when using a MAUI class library

### ISSUE THREAD

**Issue by ivan-todorov-progress** [dotnet/maui#10200]
### Description

With the recent update I am receiving the following build error when I am referencing a MAUI class library from a MAUI app:

```
Error	XAPRAS7023	System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Work\TestApp\TestLib\bin\Debug\net6.0-android\android-x64\TestLib.dll'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Xamarin.Android.Tasks.MonoAndroidHelper.HasMonoAndroidReference(ITaskItem assembly)
   at Xamarin.Android.Tasks.ProcessAssemblies.SetMetadataForAssemblies(List`1 output, Dictionary`2 symbols)
   at Xamarin.Android.Tasks.ProcessAssemblies.RunTask()
   at Microsoft.Android.Build.Tasks.AndroidTask.Execute() in /Users/runner/work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/AndroidTask.cs:line 17	TestApp	C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.448\targets\Microsoft.Android.Sdk.AssemblyResolution.targets	98	
```

The reason for the error is that the build outputs the compiled class library to the following location:

```
C:\Work\TestApp\TestLib\bin\Debug\net6.0-android\TestLib.dll
```

However, when building the app, the build task searches for the library in the following location:

```
C:\Work\TestApp\TestLib\bin\Debug\net6.0-android\android-x64\TestLib.dll
```

I am using the latest preview version of Visual Studio:
Microsoft Visual Studio Professional 2022 (64-bit) - Preview
Version 17.4.0 Preview 2.0

### Steps to Reproduce

1. Create a new MAUI app in Visual Studio
2. Add a class library to the app
3. Add a reference to the class library in the app
4. Try to build for Android

### Link to public reproduction project repository

N/A

### Version with bug

6.0.486 (current)

### Last version that worked well

6.0.424

### Affected platforms

Android

### Affected platform versions

N/A

**Comment by pijnappel** [comment]
Can confirm. I had to go back to 17.4.0 Preview 1.0 to compile.

**Comment by PureWeen** [comment]
[duplicate](https://github.com/dotnet/maui/issues/10150)

**Comment by samhouts** [comment]
Duplicate of #10150
