### ISSUE TITLE
NullReferenceException from Shell GetBackButtonBehavior

### ISSUE THREAD

**Issue by Myrkai** [dotnet/maui#10348]
### Description

Directly after app start it crashed with an exception.

If i look into the stackTrace it must comes from Maui it self.

Type: System.NullReferenceException
TargetSite: Microsoft.Maui.Controls.BackButtonBehavior GetBackButtonBehavior(Microsoft.Maui.Controls.BindableObject)
Message: Object reference not set to an instance of an object
Source: Microsoft.Maui.Controls
StackTracke:
   at Microsoft.Maui.Controls.Shell.GetBackButtonBehavior(BindableObject obj)
   at Microsoft.Maui.Controls.ShellToolbar.UpdateBackbuttonBehavior()
   at Microsoft.Maui.Controls.ShellToolbar.ApplyChanges()
   at Microsoft.Maui.Controls.Platform.Compatibility.ShellToolbarTracker.OnPageChanged(Page oldPage, Page newPage)
   at Microsoft.Maui.Controls.Platform.Compatibility.ShellToolbarTracker.set_Page(Page value)
   at Microsoft.Maui.Controls.Platform.Compatibility.ShellSectionRenderer.OnCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState)
   at AndroidX.Fragment.App.Fragment.n_OnCreateView_Landroid_view_LayoutInflater_Landroid_view_ViewGroup_Landroid_os_Bundle_(IntPtr , IntPtr , IntPtr , IntPtr , IntPtr )
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPLLL_L(_JniMarshal_PPLLL_L , IntPtr , IntPtr , IntPtr , IntPtr , IntPtr )

The installed version is: .NET Core sdk version 6.0.401
Maui version: 6.0.540…

### Steps to Reproduce

its throws not every time, but in 50%

### Link to public reproduction project repository

not avaiable

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

### Did you find any workaround?

i dont have find a workaround

**Comment by Myrkai** [comment]
Hello,

i can't create a small sample Code.
The app crashes with the appearing of the splashscreen.

If you look into the stackTrace there aren't any calls from your app.
I realy hope some developer figure it out which problem it is.
