### ISSUE TITLE
[Android] While debugging, app with ACTION_SEND Intent-Filter crashes when a file is shared to it

### ISSUE THREAD

**Issue by mavispuford** [dotnet/maui#10384]
### Description

In my app, I want to accept image file shares from other apps.  Currently, this crashes the app with a null reference exception (see below) while debugging.

### Steps to Reproduce

1. Create a File -> New Project MAUI app
2. Add the following attribute to the MainActivity class:
`[IntentFilter(new[] { Android.Content.Intent.ActionSend }, Categories = new[] { Android.Content.Intent.CategoryDefault }, DataMimeType = "image/*")]
`
3. Build and deploy the app
4. Minimize the app, go to any app that shares images (a file explorer, or the recents screen when you tap and hold on an image, for example)
5. Share any image to the new app

Expected outcome: The app should finish calling OnCreate() successfully
Actual outcome: The app crashes during OnCreate()

Additional notes:  You can actually get the Intent and the extras off of it, but the crash will still happen afterwards when base.OnCreate() is called (which can't be skipped).

### Link to public reproduction project repository

https://github.com/mavispuford/MauiTestShareApp

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 13

### Did you find any workaround?

Run the app without the debugger being attached.  This makes it hard to diagnose issues with reading in the shared image file etc., though.  Lots of Console.WriteLine() calls to walk through things. 🤮

### Relevant log output

```shell
Exception:
System.NullReferenceException
Message=Object reference not set to an instance of an object.

Stack trace:
 	0xFFFFFFFFFFFFFFFF in Android.Runtime.JNIEnv.monodroid_debugger_unhandled_exception	C#
 	0x1A in Android.Runtime.JNINativeWrapper._unhandled_exception at /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:12,5	C#
 	0x1E in Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPL_V at /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:122,26	C#
 	0x13 in Microsoft.Maui.Controls.Platform.Compatibility.ShellToolbarTracker.OnToolbarPropertyChanged at D:\a\_work\1\s\src\Controls\src\Core\Compatibility\Handlers\Shell\Android\ShellToolbarTracker.cs:581,4	C#
 	0x3F in Microsoft.Maui.Controls.Toolbar.SetProperty<System.Collections.Generic.IEnumerable<Microsoft.Maui.Controls.ToolbarItem>> at D:\a\_work\1\s\src\Controls\src\Core\Toolbar.cs:74,4	C#
 	0xD in Microsoft.Maui.Controls.Toolbar.set_ToolbarItems at D:\a\_work\1\s\src\Controls\src\Core\Toolbar.cs:34,79	C#
 	0xB7 in Microsoft.Maui.Controls.ShellToolbar.ApplyChanges at D:\a\_work\1\s\src\Controls\src\Core\ShellToolbar.cs:84,4	C#
 	0x1 in Microsoft.Maui.Controls.ShellToolbar.<.ctor>b__8_2 at D:\a\_work\1\s\src\Controls\src\Core\ShellToolbar.cs:44,39	C#
 	0x24 in Microsoft.Maui.Controls.Element.OnHandlerChangedCore at D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\Element\Element.Impl.cs:33,4	C#
 	0x1 in Microsoft.Maui.Controls.VisualElement.OnHandlerChangedCore at D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\VisualElement\VisualElement.Impl.cs:42,4	C#
 	0x6B in Microsoft.Maui.Controls.Element.SetHandler at D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\Element\Element.Impl.cs:66,5	C#
 	0x2 in Microsoft.Maui.Controls.Element.set_Handler at D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\Element\Element.Impl.cs:20,11	C#
 	0x18 in Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.set_Handler at D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\VisualElement\VisualElement.Impl.cs:301,5	C#
 	0xB0 in Microsoft.Maui.Platform.ElementExtensions.ToHandler at D:\a\_work\1\s\src\Core\src\Platform\ElementExtensions.cs:96,4	C#
 	0x2 in Microsoft.Maui.Platform.ElementExtensions.ToPlatform at D:\a\_work\1\s\src\Core\src\Platform\ElementExtensions.cs:127,4	C#
 	0x5F in Microsoft.Maui.Platform.ContainerView.SetView at D:\a\_work\1\s\src\Core\src\Platform\Android\ContainerView.cs:72,5	C#
 	0x3 in Microsoft.Maui.Platform.ContainerView.set_CurrentView at D:\a\_work\1\s\src\Core\src\Platform\Android\ContainerView.cs:51,11	C#
 	0x8 in Microsoft.Maui.Platform.ElementExtensions.ToContainerView at D:\a\_work\1\s\src\Core\src\Platform\Android\ElementExtensions.cs:11,4	C#
 	0x15 in Microsoft.Maui.Platform.NavigationRootManager.Connect at D:\a\_work\1\s\src\Core\src\Platform\Android\Navigation\NavigationRootManager.cs:51,4	C#
 	0x26 in Microsoft.Maui.Handlers.WindowHandler.CreateRootViewFromContent at D:\a\_work\1\s\src\Core\src\Handlers\Window\WindowHandler.Android.cs:38,4	C#
 	0x15 in Microsoft.Maui.Handlers.WindowHandler.MapContent at D:\a\_work\1\s\src\Core\src\Handlers\Window\WindowHandler.Android.cs:16,4	C#
 	0x21 in Microsoft.Maui.PropertyMapper<Microsoft.Maui.IWindow,Microsoft.Maui.Handlers.IWindowHandler>. at D:\a\_work\1\s\src\Core\src\PropertyMapper.cs:183,6	C#
 	0x18 in Microsoft.Maui.PropertyMapper.UpdatePropertyCore at D:\a\_work\1\s\src\Core\src\PropertyMapper.cs:47,4	C#
 	0x1D in Microsoft.Maui.PropertyMapper.UpdateProperties at D:\a\_work\1\s\src\Core\src\PropertyMapper.cs:82,5	C#
 	0xCB in Microsoft.Maui.Handlers.ElementHandler.SetVirtualView at D:\a\_work\1\s\src\Core\src\Handlers\Element\ElementHandler.cs:74,4	C#
 	0x65 in Microsoft.Maui.Controls.Element.SetHandler at D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\Element\Element.Impl.cs:64,6	C#
 	0x2 in Microsoft.Maui.Controls.Element.set_Handler at D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\Element\Element.Impl.cs:20,11	C#
 	0xA2 in Microsoft.Maui.Platform.ElementExtensions.SetHandler at D:\a\_work\1\s\src\Core\src\Platform\ElementExtensions.cs:156,4	C#
 	0x3 in Microsoft.Maui.Platform.ElementExtensions.SetWindowHandler at D:\a\_work\1\s\src\Core\src\Platform\ElementExtensions.cs:166,4	C#
 	0x79 in Microsoft.Maui.Platform.ApplicationExtensions.CreatePlatformWindow at D:\a\_work\1\s\src\Core\src\Platform\Android\ApplicationExtensions.cs:46,4	C#
 	0x54 in Microsoft.Maui.MauiAppCompatActivity.OnCreate at D:\a\_work\1\s\src\Core\src\Platform\Android\MauiAppCompatActivity.cs:32,4	C#
 	0x11 in Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ at /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net6.0/android-31/mcw/Android.App.Activity.cs:2781,4	C#
 	0x9 in Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPL_V at /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:121,5	C#


Logcat output:
09-28 17:38:34.315 11978 11978 D AndroidRuntime: Shutting down VM
09-28 17:38:34.315 11978 11978 E AndroidRuntime: FATAL EXCEPTION: main
09-28 17:38:34.315 11978 11978 E AndroidRuntime: Process: com.companyname.testshareapp, PID: 11978
09-28 17:38:34.315 11978 11978 E AndroidRuntime: android.runtime.JavaProxyThrowable: System.NullReferenceException: Object reference not set to an instance of an object.
09-28 17:38:34.315 11978 11978 E AndroidRuntime:    at Microsoft.Maui.Controls.Platform.Compatibility.ShellToolbarTracker.OnToolbarPropertyChanged(Object sender, PropertyChangedEventArgs e)
09-28 17:38:34.315 11978 11978 E AndroidRuntime:    at Microsoft.Maui.Controls.Toolbar.SetProperty[IEnumerable`1](IEnumerable`1& backingStore, IEnumerable`1 value, String propertyName)
09-28 17:38:34.315 11978 11978 E AndroidRuntime:    at Microsoft.Maui.Controls.Toolbar.set_ToolbarItems(IEnumerable`1 value)
09-28 17:38:34.315 11978 11978 E AndroidRuntime:    at Microsoft.Maui.Controls.ShellToolbar.ApplyChanges()
09-28 17:38:34.315 11978 11978 E AndroidRuntime:    at Microsoft.Maui.Controls.ShellToolbar.<.ctor>b__8_2(Object _, EventArgs __)
09-28 17:38:34.315 11978 11978 E AndroidRuntime:    at Microsoft.Maui.Controls.Element.OnHandlerChangedCore()
09-28 17:38:34.315 11978 11978 E AndroidRuntime:    at Microsoft.Maui.Controls.VisualElement.OnHandlerChangedCore()
09-28 17:38:34.315 11978 11978 E AndroidRuntime:    at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler)
09-28 17:38:34.315 11978 11978 E AndroidRuntime:    at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value)
09-28 17:38:34.315 11978 11978 E AndroidRuntime:    at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.set_Handler(IElementHandler value)
09-28 17:38:34.315 11978 11978 E AndroidRuntime:    at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context)
09-28 17:38:34.315 11978 11978 E AndroidRuntime:    at Microsoft.Maui.Platform.ElementExtensions.ToPlatform(IElement view, IMauiContext context)
09-28 17:38:34.315 11978 11978 E AndroidRuntime:    at Microsoft.Maui.Platform.ContainerView.SetView(IElement view, Boolean forceRefresh)
09-28 17:38:34.315 11978 11978 E AndroidRuntime:    at Microsoft.Maui.Platform.ContainerView.set_CurrentView(IElement value)
09-28 17:38:34.315 11978 11978 E AndroidRuntime:    at Microsoft.Maui.Platform.ElementExtensions.ToContainerView(IElement view, IMauiContext context)
09-28 17:38:34.315 11978 11978 E AndroidRuntime:    at Microsoft.Maui.Platform.NavigationRootManager.Connect(IView view, IMauiContext mauiContext)
09-28 17:38:34.315 11978 11978 E AndroidRuntime:    at Microsoft.Maui.Handlers.WindowHandler.CreateRootViewFromContent(IWindowHandler handler, IWindow window)
09-28 17:38:34.315 11978 11978 E AndroidRuntime:    at Microsoft.Maui.Handlers.WindowHandler.MapContent(IWindowHandler handler, IWindow window)
09-28 17:38:34.315 11978 11978 E AndroidRuntime:    at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0[[Microsoft.Maui.IWindow, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.IWindowHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v)
09-28 17:38:34.315 11978 11978 E AndroidRuntime:    at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IElementHandler viewHandler, IElement virtualView)
09-28 17:38:34.315 11978 11978 E AndroidRuntime:    at Microsoft.Maui.PropertyMapper.UpdateProperties(IElementHandler viewHandler, IElement virtualView)
09-28 17:38:34.315 11978 11978 E AndroidRuntime:    at Microsoft.Maui.Handlers.ElementHandler.SetVirtualView(IElement view)
09-28 17:38:34.315 11978 11978 E AndroidRuntime:    at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler)
09-28 17:38:34.315 11978 11978 E AndroidRuntime:    at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value)
09-28 17:38:34.315 11978 11978 E AndroidRuntime:    at Microsoft.Maui.Platform.ElementExtensions.SetHandler(Context nativeElement, IElement element, IMauiContext context)
09-28 17:38:34.315 11978 11978 E AndroidRuntime:    at Microsoft.Maui.Platform.ElementExtensions.SetWindowHandler(Activity platformWindow, IWindow window, IMauiContext context)
09-28 17:38:34.315 11978 11978 E AndroidRuntime:    at Microsoft.Maui.Platform.ApplicationExtensions.CreatePlatformWindow(Activity activity, IApplication application, Bundle savedInstanceState)
09-28 17:38:34.315 11978 11978 E AndroidRuntime:    at Microsoft.Maui.MauiAppCompatActivity.OnCreate(Bundle savedInstanceState)
09-28 17:38:34.315 11978 11978 E AndroidRuntime:    at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_(IntPtr jnienv, IntPtr native__this, IntPtr native_savedInstanceState)
09-28 17:38:34.315 11978 11978 E AndroidRuntime:    at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPL_V(_JniMarshal_PPL_V callback, IntPtr jnienv, IntPtr klazz, IntPtr p0)
09-28 17:38:34.315 11978 11978 E AndroidRuntime:        at crc6488302ad6e9e4df1a.MauiAppCompatActivity.n_onCreate(Native Method)
09-28 17:38:34.315 11978 11978 E AndroidRuntime:        at crc6488302ad6e9e4df1a.MauiAppCompatActivity.onCreate(MauiAppCompatActivity.java:47)
09-28 17:38:34.315 11978 11978 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:8290)
09-28 17:38:34.315 11978 11978 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:8269)
09-28 17:38:34.315 11978 11978 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)
09-28 17:38:34.315 11978 11978 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3657)
09-28 17:38:34.315 11978 11978 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3813)
09-28 17:38:34.315 11978 11978 E AndroidRuntime:        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
09-28 17:38:34.316 11978 11978 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
09-28 17:38:34.316 11978 11978 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
09-28 17:38:34.316 11978 11978 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308)
09-28 17:38:34.316 11978 11978 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
09-28 17:38:34.316 11978 11978 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:201)
09-28 17:38:34.316 11978 11978 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:288)
09-28 17:38:34.316 11978 11978 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7898)
09-28 17:38:34.316 11978 11978 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
09-28 17:38:34.316 11978 11978 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
09-28 17:38:34.316 11978 11978 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
09-28 17:38:34.317 11978 11978 W monodroid-assembly: Shared library 'liblog' not loaded, p/invoke '__android_log_print' may fail
09-28 17:38:34.319 11978 11978 W monodroid-assembly: open_from_bundles: failed to load assembly System.Console.dll
09-28 17:38:34.322 11978 11978 I MonoDroid: UNHANDLED EXCEPTION:
09-28 17:38:34.326 11978 11978 I MonoDroid: Android.Runtime.JavaProxyThrowable: Exception of type 'Android.Runtime.JavaProxyThrowable' was thrown.
09-28 17:38:34.327 11978 11978 I MonoDroid:
09-28 17:38:34.327 11978 11978 I MonoDroid:   --- End of managed Android.Runtime.JavaProxyThrowable stack trace ---
09-28 17:38:34.327 11978 11978 I MonoDroid: android.runtime.JavaProxyThrowable: System.NullReferenceException: Object reference not set to an instance of an object.
09-28 17:38:34.327 11978 11978 I MonoDroid:    at Microsoft.Maui.Controls.Platform.Compatibility.ShellToolbarTracker.OnToolbarPropertyChanged(Object sender, PropertyChangedEventArgs e)
09-28 17:38:34.327 11978 11978 I MonoDroid:    at Microsoft.Maui.Controls.Toolbar.SetProperty[IEnumerable`1](IEnumerable`1& backingStore, IEnumerable`1 value, String propertyName)
09-28 17:38:34.327 11978 11978 I MonoDroid:    at Microsoft.Maui.Controls.Toolbar.set_ToolbarItems(IEnumerable`1 value)
09-28 17:38:34.327 11978 11978 I MonoDroid:    at Microsoft.Maui.Controls.ShellToolbar.ApplyChanges()
09-28 17:38:34.327 11978 11978 I MonoDroid:    at Microsoft.Maui.Controls.ShellToolbar.<.ctor>b__8_2(Object _, EventArgs __)
09-28 17:38:34.327 11978 11978 I MonoDroid:    at Microsoft.Maui.Controls.Element.OnHandlerChangedCore()
09-28 17:38:34.327 11978 11978 I MonoDroid:    at Microsoft.Maui.Controls.VisualElement.OnHandlerChangedCore()
09-28 17:38:34.327 11978 11978 I MonoDroid:    at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler)
09-28 17:38:34.327 11978 11978 I MonoDroid:    at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value)
09-28 17:38:34.327 11978 11978 I MonoDroid:    at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.set_Handler(IElementHandler value)
09-28 17:38:34.327 11978 11978 I MonoDroid:    at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context)
09-28 17:38:34.327 11978 11978 I MonoDroid:    at Microsoft.Maui.Platform.ElementExtensions.ToPlatform(IElement view, IMauiContext context)
09-28 17:38:34.327 11978 11978 I MonoDroid:    at Microsoft.Maui.Platform.ContainerView.SetView(IElement view, Boolean forceRefresh)
09-28 17:38:34.327 11978 11978 I MonoDroid:    at Microsoft.Maui.Platform.ContainerView.set_CurrentView(IElement value)
09-28 17:38:34.327 11978 11978 I MonoDroid:    at Microsoft.Maui.Platform.ElementExtensions.ToContainerView(IElement view, IMauiContext context)
09-28 17:38:34.327 11978 11978 I MonoDroid:    at Microsoft.Maui.Platform.NavigationRootManager.Connect(IView view, IMauiContext mauiContext)
09-28 17:38:34.327 11978 11978 I MonoDroid:    at Microsoft.Maui.Handlers.WindowHandler.CreateRootViewFromContent(IWindowHandler handler, IWindow window)
09-28 17:38:34.327 11978 11978 I MonoDroid:    at Microsoft.Maui.Handlers.WindowHandler.MapContent(IWindowHandler handler, IWindow window)
09-28 17:38:34.327 11978 11978 I MonoDroid:    at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0[[Microsoft.Maui.IWindow, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.IWindowHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v)
09-28 17:38:34.327 11978 11978 I MonoDroid:    at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IElementHandler viewHandler, IElement virtualView)
09-28 17:38:34.327 11978 11978 I MonoDroid:    at Microsoft.Maui.PropertyMapper.UpdateProperties(IElementHandler viewHandler, IElement virtualView)
09-28 17:38:34.327 11978 11978 I MonoDroid:    at Microsoft.Maui.Handlers.ElementHandler.SetVirtualView(IElement view)
09-28 17:38:34.327 11978 11978 I MonoDroid:    at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler)
09-28 17:38:34.327 11978 11978 I MonoDroid:    at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value)
09-28 17:38:34.327 11978 11978 I MonoDroid:    at Microsoft.Maui.Platform.ElementExtensions.SetHandler(Context nativeElement, IElement element, IMauiContext context)
09-28 17:38:34.327 11978 11978 I MonoDroid:    at Microsoft.Maui.Platform.ElementExtensions.SetWindowHandler(Activity platformWindow, IWindow window, IMauiContext context)
09-28 17:38:34.327 11978 11978 I MonoDroid:    at Microsoft.Maui.Platform.ApplicationExtensions.CreatePlatformWindow(Activity activity, IApplication application, Bundle savedInstanceState)
09-28 17:38:34.327 11978 11978 I MonoDroid:    at Microsoft.Maui.MauiAppCompatActivity.OnCreate(Bundle savedInstanceState)
09-28 17:38:34.327 11978 11978 I MonoDroid:    at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_(IntPtr jnienv, IntPtr native__this, IntPtr native_savedInstanceState)
09-28 17:38:34.327 11978 11978 I MonoDroid:    at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPL_V(_JniMarshal_PPL_V callback, IntPtr jnienv, IntPtr klazz, IntPtr p0)
09-28 17:38:34.327 11978 11978 I MonoDroid:     at crc6488302ad6e9e4df1a.MauiAppCompatActivity.n_onCreate(Native Method)
09-28 17:38:34.327 11978 11978 I MonoDroid:     at crc6488302ad6e9e4df1a.MauiAppCompatActivity.onCreate(MauiAppCompatActivity.java:47)
09-28 17:38:34.327 11978 11978 I MonoDroid:     at android.app.Activity.performCreate(Activity.java:8290)
09-28 17:38:34.327 11978 11978 I MonoDroid:     at android.app.Activity.performCreate(Activity.java:8269)
09-28 17:38:34.327 11978 11978 I MonoDroid:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)
09-28 17:38:34.327 11978 11978 I MonoDroid:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3657)
09-28 17:38:34.327 11978 11978 I MonoDroid:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3813)
09-28 17:38:34.327 11978 11978 I MonoDroid:     at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
09-28 17:38:34.327 11978 11978 I MonoDroid:     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
09-28 17:38:34.327 11978 11978 I MonoDroid:     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
09-28 17:38:34.327 11978 11978 I MonoDroid:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308)
09-28 17:38:34.327 11978 11978 I MonoDroid:     at android.os.Handler.dispatchMessage(Handler.java:106)
09-28 17:38:34.327 11978 11978 I MonoDroid:     at android.os.Looper.loopOnce(Looper.java:201)
09-28 17:38:34.327 11978 11978 I MonoDroid:     at android.os.Looper.loop(Looper.java:288)
09-28 17:38:34.327 11978 11978 I MonoDroid:     at android.app.ActivityThread.main(ActivityThread.java:7898)
09-28 17:38:34.327 11978 11978 I MonoDroid:     at java.lang.reflect.Method.invoke(Native Method)
09-28 17:38:34.327 11978 11978 I MonoDroid:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
09-28 17:38:34.327 11978 11978 I MonoDroid:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
09-28 17:38:34.327 11978 11978 I MonoDroid:
09-28 17:38:34.327 11978 11978 I MonoDroid:   --- End of managed Android.Runtime.JavaProxyThrowable stack trace ---
09-28 17:38:34.327 11978 11978 I MonoDroid: android.runtime.JavaProxyThrowable: System.NullReferenceException: Object reference not set to an instance of an object.
09-28 17:38:34.327 11978 11978 I MonoDroid:    at Microsoft.Maui.Controls.Platform.Compatibility.ShellToolbarTracker.OnToolbarPropertyChanged(Object sender, PropertyChangedEventArgs e)
09-28 17:38:34.327 11978 11978 I MonoDroid:    at Microsoft.Maui.Controls.Toolbar.SetProperty[IEnumerable`1](IEnumerable`1& backingStore, IEnumerable`1 value, String propertyName)
09-28 17:38:34.327 11978 11978 I MonoDroid:    at Microsoft.Maui.Controls.Toolbar.set_ToolbarItems(IEnumerable`1 value)
09-28 17:38:34.327 11978 11978 I MonoDroid:    at Microsoft.Maui.Controls.ShellToolbar.ApplyChanges()
09-28 17:38:34.327 11978 11978 I MonoDroid:    at Microsoft.Maui.Controls.ShellToolbar.<.ctor>b__8_2(Object _, EventArgs __)
09-28 17:38:34.327 11978 11978 I MonoDroid:    at Microsoft.Maui.Controls.Element.OnHandlerChangedCore()
09-28 17:38:34.327 11978 11978 I MonoDroid:    at Microsoft.Maui.Controls.VisualElement.OnHandlerChangedCore()
09-28 17:38:34.327 11978 11978 I MonoDroid:    at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler)
09-28 17:38:34.327 11978 11978 I MonoDroid:    at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value)
09-28 17:38:34.327 11978 11978 I MonoDroid:    at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.set_Handler(IElementHandler value)
09-28 17:38:34.327 11978 11978 I MonoDroid:    at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context)
09-28 17:38:34.327 11978 11978 I MonoDroid:    at Microsoft.Maui.Platform.ElementExtensions.ToPlatform(IElement view, IMauiContext context)
09-28 17:38:34.327 11978 11978 I MonoDroid:    at Microsoft.Maui.Platform.ContainerView.SetView(IElement view, Boolean forceRefresh)
09-28 17:38:34.327 11978 11978 I MonoDroid:    at Microsoft.Maui.Platform.ContainerView.set_CurrentView(IElement value)
09-28 17:38:34.327 11978 11978 I MonoDroid:    at Microsoft.Maui.Platform.ElementExtensions.ToContainerView(IElement view, IMauiContext context)
09-28 17:38:34.327 11978 11978 I MonoDroid:    at Microsoft.Maui.Platform.NavigationRootManager.Connect(IView view, IMauiContext mauiContext)
09-28 17:38:34.327 11978 11978 I MonoDroid:    at Microsoft.Maui.Handlers.WindowHandler.CreateRootViewFromContent(IWindowHandler handler, IWindow window)
09-28 17:38:34.327 11978 11978 I MonoDroid:    at Microsoft.Maui.Handlers.WindowHandler.MapContent(IWindowHandler handler, IWindow window)
09-28 17:38:34.327 11978 11978 I MonoDroid:    at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0[[Microsoft.Maui.IWindow, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.IWindowHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v)
09-28 17:38:34.327 11978 11978 I MonoDroid:    at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IElementHandler viewHandler, IElement virtualView)
09-28 17:38:34.327 11978 11978 I MonoDroid:    at Microsoft.Maui.PropertyMapper.UpdateProperties(IElementHandler viewHandler, IElement virtualView)
09-28 17:38:34.327 11978 11978 I MonoDroid:    at Microsoft.Maui.Handlers.ElementHandler.SetVirtualView(IElement view)
09-28 17:38:34.327 11978 11978 I MonoDroid:    at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler)
09-28 17:38:34.327 11978 11978 I MonoDroid:    at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value)
09-28 17:38:34.327 11978 11978 I MonoDroid:    at Microsoft.Maui.Platform.ElementExtensions.SetHandler(Context nativeElement, IElement element, IMauiContext context)
09-28 17:38:34.327 11978 11978 I MonoDroid:    at Microsoft.Maui.Platform.ElementExtensions.SetWindowHandler(Activity platformWindow, IWindow window, IMauiContext context)
09-28 17:38:34.327 11978 11978 I MonoDroid:    at Microsoft.Maui.Platform.ApplicationExtensions.CreatePlatformWindow(Activity activity, IApplication application, Bundle savedInstanceState)
09-28 17:38:34.327 11978 11978 I MonoDroid:    at Microsoft.Maui.MauiAppCompatActivity.OnCreate(Bundle savedInstanceState)
09-28 17:38:34.327 11978 11978 I MonoDroid:    at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_(IntPtr jnienv, IntPtr native__this, IntPtr native_savedInstanceState)
09-28 17:38:34.327 11978 11978 I MonoDroid:    at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPL_V(_JniMarshal_PPL_V callback, IntPtr jnienv, IntPtr klazz, IntPtr p0)
09-28 17:38:34.327 11978 11978 I MonoDroid:     at crc6488302ad6e9e4df1a.MauiAppCompatActivity.n_onCreate(Native Method)
09-28 17:38:34.327 11978 11978 I MonoDroid:     at crc6488302ad6e9e4df1a.MauiAppCompatActivity.onCreate(MauiAppCompatActivity.java:47)
09-28 17:38:34.327 11978 11978 I MonoDroid:     at android.app.Activity.performCreate(Activity.java:8290)
09-28 17:38:34.327 11978 11978 I MonoDroid:     at android.app.Activity.performCreate(Activity.java:8269)
09-28 17:38:34.327 11978 11978 I MonoDroid:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)
09-28 17:38:34.327 11978 11978 I MonoDroid:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3657)
09-28 17:38:34.327 11978 11978 I MonoDroid:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3813)
09-28 17:38:34.327 11978 11978 I MonoDroid:     at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
09-28 17:38:34.327 11978 11978 I MonoDroid:     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
09-28 17:38:34.327 11978 11978 I MonoDroid:     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
09-28 17:38:34.327 11978 11978 I MonoDroid:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308)
09-28 17:38:34.327 11978 11978 I MonoDroid:     at android.os.Handler.dispatchMessage(Handler.java:106)
09-28 17:38:34.327 11978 11978 I MonoDroid:     at android.os.Looper.loopOnce(Looper.java:201)
09-28 17:38:34.327 11978 11978 I MonoDroid:     at android.os.Looper.loop(Looper.java:288)
09-28 17:38:34.327 11978 11978 I MonoDroid:     at android.app.ActivityThread.main(ActivityThread.java:7898)
09-28 17:38:34.327 11978 11978 I MonoDroid:     at java.lang.reflect.Method.invoke(Native Method)
09-28 17:38:34.327 11978 11978 I MonoDroid:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
09-28 17:38:34.327 11978 11978 I MonoDroid:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
09-28 17:38:34.327 11978 11978 I MonoDroid:
09-28 17:38:34.328 15861 15919 D QuickstepModelDelegate: notifyAppTargetEvent action=1 launchLocation=task-switcher
09-28 17:38:34.332  2006  6208 W ActivityTaskManager:   Force finishing activity com.companyname.testshareapp/crc642acc75300c790e2f.MainActivity
```

**Comment by mattleibow** [comment]
Fixed in #10457 and https://github.com/dotnet/maui/commit/a0afb2d07598bfc3e5b290de843d8a43fbedea14
