### ISSUE TITLE
Resizetizer cannot find existing images

### ISSUE THREAD

**Issue by matthericks** [dotnet/maui#10380]
### Description

We are working on an iOS app that is consuming a nuget package, and resizetizer is having issues finding the images from the library. We are specifically getting:

```
  Microsoft.Maui.Resizetizer.targets(531, 9): Unable to find background file: /Users/matthericks/.nuget/packages/matthericks.maui.imagepackage/0.0.1/buildTransitive/Resources/Images/checkmark.svg
   at Microsoft.Maui.Resizetizer.ResizeImageInfo.Parse(IEnumerable`1 images) in D:\a\_work\1\s\src\SingleProject\Resizetizer\src\ResizeImageInfo.cs:line 67
   at Microsoft.Maui.Resizetizer.ResizetizeImages.ExecuteAsync()
   at Microsoft.Maui.Resizetizer.MauiAsyncTask.<Execute>b__0_0() in D:\a\_work\1\s\src\SingleProject\Resizetizer\src\MauiAsyncTask.cs:line 18
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
```

The image exists in the specified location:
<img width="1322" alt="Screen Shot 2022-09-28 at 1 36 46 PM" src="https://user-images.githubusercontent.com/19779550/192862108-2819478b-d9be-45f3-af30-efc8628569dc.png">

We have followed steps [here](https://github.com/dotnet/maui/issues/10019) to get our library to properly pack the images.

We have also tried clearing out bin and obj folders with no improvements.

currently using .NET SDK 6.0.401

Created a public nuget package for repro: https://www.nuget.org/packages/MattHericks.MAUI.ImagePackage/

### Steps to Reproduce

1. Create library with images
2. Consume library in another MAUI app
3. note build errors in resizetizer

Expected behavior:
-resizetizer can find existing images

Actual behavior:
- Resizetizer throw error saying that images cannot be found.

### Link to public reproduction project repository

https://github.com/matthericks/bug_repro

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15.4

### Did you find any workaround?

no

### Relevant log output

```shell
Microsoft.Maui.Resizetizer.targets(531, 9): Unable to find background file: /Users/matthericks/.nuget/packages/matthericks.maui.imagepackage/0.0.1/buildTransitive/Resources/Images/checkmark.svg
   at Microsoft.Maui.Resizetizer.ResizeImageInfo.Parse(IEnumerable`1 images) in D:\a\_work\1\s\src\SingleProject\Resizetizer\src\ResizeImageInfo.cs:line 67
   at Microsoft.Maui.Resizetizer.ResizetizeImages.ExecuteAsync()
   at Microsoft.Maui.Resizetizer.MauiAsyncTask.<Execute>b__0_0() in D:\a\_work\1\s\src\SingleProject\Resizetizer\src\MauiAsyncTask.cs:line 18
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
```

**Comment by mattleibow** [comment]
The package seems to be incorrect. The 0.0.1 package says the image is in Resources:

```
<MauiImage Include="$(MSBuildThisFileDirectory)\Resources\Images\checkmark.svg" />
```

but is not actually there:

![image](https://user-images.githubusercontent.com/1096616/193112582-14c2a093-8d6e-4729-ac1d-b6bdd77d3f95.png)


The 0.0.4 version is using contentFiles instead of buildTransitive.

**Comment by matthericks** [comment]
I believe [0.0.9](https://nuget.info/packages/MattHericks.MAUI.ImagePackage/0.0.9) should be correct now? No longer getting compilation errors, but I also cannot get my image to actually display, either on its own or when used in a contentview from the package.

the project file now has:
```    
    <ItemGroup>
      <MauiImage Include="Resources\Images\checkmark.svg" Pack="True" PackagePath="Resources\Images\" />
    </ItemGroup>
    <ItemGroup>
        <None Include="Resources\Images\checkmark.svg" Pack="True" PackagePath="Resources\Images\" />
        <None Include="Resources\MattHericks.MAUI.ImagePackage.targets" Pack="True" PackagePath="Resources\" />
    </ItemGroup>
```

and the target file, which has been moved to Resources, has been changed to:
```
<Project>
    <ItemGroup>
        <MauiImage Include="$(MSBuildThisFileDirectory)\Resources\Images\checkmark.svg" />
    </ItemGroup>
</Project>
```

From the what I am seeing, the files all match up at this point, and I am now at the original issue I was encountering before trying to pack the images.

**Comment by mattleibow** [comment]
I had a look at the package and had to make 2 changes:

move the Resources folder under buildTransitive and then move the targets file to the root of the buildTransitive (out of the Resources) 

```xml
    <ItemGroup>
        <None Include="Resources\Images\checkmark.svg" Pack="True" PackagePath="buildTransitive\Resources\Images\" />
        <None Include="Resources\MattHericks.MAUI.ImagePackage.targets" Pack="True" PackagePath="buildTransitive\" />
    </ItemGroup>
```

**Comment by matthericks** [comment]
That worked. Thanks!

**Comment by matthericks** [comment]
As a general workflow thought, it would be nice if indicating that a .svg file should be packaged managed a bit of this in the background. Manually editing the project file is not ideal, and gets overwritten quite easily when files are added/changed, making maintaining this a bit of a pain.
