### ISSUE TITLE
Native iOS applications not running

### ISSUE THREAD

**Issue by arivoir** [dotnet/maui#10462]
### Description

Native iOS applications aren't running anymore since last vs update

### Steps to Reproduce

- Create new iOS Application
- Run it

### Link to public reproduction project repository

No demo

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

6.0.400

### Affected platforms

iOS

### Affected platform versions

Microsoft Visual Studio Enterprise 2022 (64-bit) - Preview Version 17.4.0 Preview 2.1 dotnet version 7.0.100-rc.1.22431.12

### Did you find any workaround?

No

### Relevant log output

```shell
ObjCRuntime.ObjCException
  Message=Objective-C exception thrown.  Name: NSInternalInconsistencyException Reason: Unable to instantiate the UIApplication delegate instance. No class named AppDelegate is loaded.
Native stack trace:
	0   CoreFoundation                      0x00000001148d0604 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x0000000121c4fa45 objc_exception_throw + 48
	2   Foundation                          0x0000000116f6fa19 -[NSMutableDictionary(NSMutableDictionary) classForCoder] + 0
	3   UIKitCore                           0x000000012bfdea20 _UIApplicationMainPreparations + 1885
	4   UIKitCore                           0x000000012bfde299 UIApplicationMain + 73
	5   libmonosgen-2.0.dylib               0x00000001112c8aa2 do_icall + 194
	6   libmonosgen-2.0.dylib               0x00000001112c7abd do_icall_wrapper + 253
	7   libmonosgen-2.0.dylib               0x00000001112b9cda interp_exec_method + 2970
	8   libmonosgen-2.0.dylib               0x00000001112b7f5f interp_runtime_invoke + 239
	9   libmonosgen-2.0.dylib               0x00000001110d2198 mono_runtime_invoke_checked + 136
	10  libmonosgen-2.0.dylib               0x00000001110d8f3b mono_runtime_exec_main_checked + 107
	11  libmonosgen-2.0.dylib               0x0000000111212042 mono_jit_exec + 354
	12  libxamarin-dotnet-debug.dylib       0x00000001103efe9d xamarin_main + 1949
	13  FlexGridExplorer                    0x000000010f9dd924 main + 68
	14  dyld                                0x000000010ffd0f21 start_sim + 10
	15  ???                                 0x0000000110faa52e 0x0 + 4579829038

  Source=Microsoft.iOS
  StackTrace:
   at ObjCRuntime.Runtime.ThrowNSException(IntPtr ns_exception)
   at ObjCRuntime.Runtime.throw_ns_exception(IntPtr exc)
   at UIKit.UIApplication.Main(String[] args, String principalClassName, String delegateClassName)
   at FlexGridExplorer.Application.Main(String[] )
```

**Comment by jfversluis** [comment]
This issue was moved to xamarin/xamarin-macios#16219
