### ISSUE TITLE
Microsoft.Maui.ApplicationModel.VersionTracking.Default throws exception

### ISSUE THREAD

**Issue by developer9969** [dotnet/maui#10499]
### Description

I am writing some tests and I need to inject IVersionTracking into a service and in tests when I do the following it crashes

### Steps to Reproduce

1. Create a test
2.  Write this line of code 
3.  **IVersionTracking versionTrackerService = Microsoft.Maui.ApplicationModel.VersionTracking.Default**  
4. it throws the following:

System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'Microsoft.Maui.ApplicationModel.VersionTrackingImplementation' threw an exception.
  Source=Microsoft.Maui.Essentials
  StackTrace:
   at Microsoft.Maui.ApplicationModel.VersionTrackingImplementation.InitVersionTracking()
   at Microsoft.Maui.ApplicationModel.VersionTracking.get_Default() in 
Inner Exception 1:
NotImplementedInReferenceAssemblyException: This functionality is not implemented in the portable version of this assembly. You should reference the NuGet package from your main application project in order to reference the platform-specific implementation.

### Link to public reproduction project repository

no link

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, I was *not* able test on other platforms

### Affected platform versions

Android 11,12

### Did you find any workaround?

I had to create a fake so that I could use in testing, Not sure I get how the concrete classes in maui how implemented.
Testing is still hard - I get that you have to use "Current" or Default  - not sure if intuitive , 
what was wrong with 

 ISomething something=new Something()

### Relevant log output

```shell
System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'Microsoft.Maui.ApplicationModel.VersionTrackingImplementation' threw an exception.
  Source=Microsoft.Maui.Essentials
  StackTrace:
   at Microsoft.Maui.ApplicationModel.VersionTrackingImplementation.InitVersionTracking()
   at Microsoft.Maui.ApplicationModel.VersionTracking.get_Default() in 
Inner Exception 1:
NotImplementedInReferenceAssemblyException: This functionality is not implemented in the portable version of this assembly. You should reference the NuGet package from your main application project in order to reference the platform-specific implementation.
```

**Comment by drasticactions** [comment]
That doesn't seem like a bug and it's throwing the correct message: You're trying to use an API that's designed to run on a platform and you're running it from a net standard or non-platform instance, which doesn't have "Default".

I think you can create the `IVersionTracking` instance yourself and register it? So it'll be set to default and you can call it from there? https://github.com/dotnet/maui/blob/18ed02b41a35edad98aef79ec677c42ebff52890/src/Essentials/src/VersionTracking/VersionTracking.shared.cs#L102-L106

**Comment by developer9969** [comment]
@drasticactions hi you are absolutely correct I am creating this when its not running on a platform. 
I need to tests some classes where this is injected and I dont/cant run the app just to test this service.

But what I dont get why is VersionTrackingImplementation is internal ? I had to create a version of it myself as you said as a workaround.

The problem would have been solved if VersionTrackingImplementation was public.   

Am I missing something but the all other of having interfaces is to solve the testing problem we had before with these set of classes?

**Comment by mattleibow** [comment]
I'll try explain our thinking and maybe it makes sense or maybe we need to do more work. A lot of the description is in the second half of this description here (https://github.com/dotnet/maui/pull/5407) but I will duplicate as this is a good place as well.

Initially there was a discussion to have the static API swap out the internals - like with SetDefault - and make the implementation public, but this was not super useful in that it did not solve DI issues.

In the end, we decided to not allow you to swap out the static implementations as this caused issues in testing - a static field being swapped out concurrently is all sorts of bad. The implementations are internal as we were going for a default implementation that did not really need an instance class AND a static API.


#### Static APIs

If you are writing a simple app and don't believe in testing, you can write code like this using the static APIs `Geolocation.GetLocationAsync()`:

```cs
class MyViewModel
{
    public async Task UploadLocationAsync()
    {
        var location = await Geolocation.GetLocationAsync();
        var uploader = MyUploader();
        await uploader.UploadLocationAsync(location);
    }
}
```

#### Instance / DI-Friendly APIs

However, if you _want_ to create a testable system or use DI, you now can using the instance APIs `Geolocation.Default.GetLocationAsync()`:

```cs
class MauiProgram
{
    public static MauiApp CreateMauiApp()
    {
        // register the default/platform service
        builder.Services.AddSingleton<IVersionTracker>(VersionTracker.Default);
    }
}
```

```cs
class MyViewModel
{
    public MyViewModel(IGeolocation geolocation, IUploader uploader)
    {
        // TODO: set fields
    }

    public async Task UploadLocationAsync()
    {
        var location = await deolocation.GetLocationAsync();
        await uploader.UploadLocationAsync(location);
    }
}
```

Now you can also use DI or write tests:

```cs
async Task TheBigTest()
{
    var vm = new MyViewModel(new StubGeolocation(), new StubUploader());
    await UploadLocationAsync();

    // TODO: assert location was retrieved and then uploaded
}
```

**Comment by developer9969** [comment]
@mattleibow thank you very much for your detailed answer , I get it on  why you decided on this implementation as it would not mean a total break , however it does not feel natural.

Where I work unless we have a test the functionality does not get approved and some services we inject those interfaces and we need the ability to test without launching the app but just the service in isolation.

So what you are saying that in order to test essentials we have to create our own stub  

```
IVersionTracker versionTrackingService=new FakeVersionTrackingService();

public class FakeVersionTrackingService:IVersionTracker
etc...
```

I was not expecting this implementation with fakes but I guess it is what it is.

**Comment by mattleibow** [comment]
I think the version tracker api is the only one that does not rely on platform things. For example, it uses the preferences api and that 100% platform specific and will never work in unit test code.

Not sure how we would make it work as even though the api is technically portable, the pieces it uses are not.

For example, if you are tracking versions, how will it work in tests? Where would the files be stored?

**Comment by developer9969** [comment]
May be is an edge case and Its ok to be a fake -  Basically I needed to test a scenario where if is firstTime launching do xyz otherwise do abc etc...

So when   testing this class I needed to set this depending on the scenario.

For instance for connectivity because we have a check for connectivity before we make a call to any rest api I do something like 
below - for testing I set it to "DevicePlatform.Unknown.

Its tricky if you want to run unit tests - or some functional tests that dont require the app to be running when you have essentials in the middle of it,

```
  private bool IsConnected
    {
        get
        {
            if (DeviceInfo.Platform == DevicePlatform.Unknown)
            {
                return true;
            }
            return Connectivity.NetworkAccess == NetworkAccess.Internet;
        }
    }
```
But happy to close this - as I dont see any other solutions
