### ISSUE TITLE
ListView duplicate first item

### ISSUE THREAD

**Issue by mike3sullivan** [dotnet/maui#10582]
### Description

If a ListView is initially hidden, then made visible, the first item added appears twice, even though the ItemSource contains only one item. Adding more items causes the second item to display the 2 values overlapping.
![MauiListViewDuplicateItem](https://user-images.githubusercontent.com/26934129/194788068-f5866524-9dd2-4056-994d-0f8cfeecc6d0.png)

### Steps to Reproduce

Per repo, click Show radio button to show the ListView and add the first value (which shows twice). Click the button to add more rows -- the second entry ("2") shows on the second row as it should, but the first value is still there overlapping it.

### Link to public reproduction project repository

https://github.com/mike3sullivan/MauiViewListDuplicateItem

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10

### Relevant log output

if it helps, attempting to Clear the ItemSource parameter causes a crash with the stack trace of:
This collection cannot work with indices larger than Int32.MaxValue - 1 (0x7FFFFFFF - 1). (Parameter 'index')
   at ABI.System.Collections.IList.ToAbiHelper.EnsureIndexInt32(UInt32 index, Int32 listCapacity)
   at ABI.System.Collections.IList.ToAbiHelper.GetAt(UInt32 index)
   at ABI.System.Collections.IList.Vftbl.Do_Abi_GetAt_0(IntPtr thisPtr, UInt32 index, IntPtr* result)
--- End of stack trace from previous location ---
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Microsoft.UI.Xaml.IUIElementMethods.UpdateLayout(IObjectReference _obj)
   at Microsoft.Maui.Controls.Internals.TemplatedItemsList`2.OnProxyCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at Microsoft.Maui.Controls.ListProxy.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at Microsoft.Maui.Controls.ListProxy.WeakNotifyProxy.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.ClearItems()
   at System.Collections.ObjectModel.Collection`1.Clear()

**Comment by rmarinho** [comment]
Sorry but this seems you didn't upload the sample to the repository, can you check that please. 

Thanks

<img width="1529" alt="image" src="https://user-images.githubusercontent.com/1235097/194886671-407392f4-504d-4ff4-86c9-b1f876af6e6b.png">

**Comment by mike3sullivan** [comment]
Sorry - guess I didn't commit the upload.  Done.

**Comment by bengavin** [comment]
We are also seeing a situation similar to this when removing the last item from an ObservableCollection that is bound to a ListView, a similar exception happens and then the ListView is left with an 'orphaned' child ViewCell that sits above the list and cannot be cleared, even when re-binding the ListView.

   at ABI.System.Collections.IList.ToAbiHelper.EnsureIndexInt32(UInt32 index, Int32 listCapacity)
   at ABI.System.Collections.IList.ToAbiHelper.GetAt(UInt32 index)
   at ABI.System.Collections.IList.Vftbl.Do_Abi_GetAt_0(IntPtr thisPtr, UInt32 index, IntPtr* result)
--- End of stack trace from previous location ---
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Microsoft.UI.Xaml.IUIElementMethods.UpdateLayout(IObjectReference _obj)
   at Microsoft.UI.Xaml.UIElement.UpdateLayout()
   at Microsoft.Maui.Controls.Handlers.Compatibility.ListViewRenderer.<OnCollectionChanged>b__23_0()
   at Microsoft.Maui.Controls.DispatcherExtensions.DispatchIfRequired(IDispatcher dispatcher, Action action)
   at Microsoft.Maui.Controls.Handlers.Compatibility.ListViewRenderer.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at Microsoft.Maui.Controls.Internals.TemplatedItemsList`2.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at Microsoft.Maui.Controls.Internals.TemplatedItemsList`2.OnProxyCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at Microsoft.Maui.Controls.ListProxy.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at Microsoft.Maui.Controls.ListProxy.<>c__DisplayClass36_0.<OnCollectionChanged>b__0()
   at Microsoft.Maui.Controls.DispatcherExtensions.DispatchIfRequired(IDispatcher dispatcher, Action action)
   at Microsoft.Maui.Controls.ListProxy.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at Microsoft.Maui.Controls.WeakNotifyCollectionChangedProxy.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.Collection`1.Remove(T item)

**Comment by busitech** [comment]
Same issue: https://github.com/microsoft/microsoft-ui-xaml/issues/8684

**Comment by Felicity-R** [comment]
I've been experiencing this too. 
I created an updated version of mike3sullivan's demo: https://github.com/Felicity-R/ListViewBugDemo

It still reproduces:
![image](https://github.com/dotnet/maui/assets/62772237/c39923b4-9319-4d3c-a2d1-a13fbe3a77bc)

**Comment by Felicity-R** [comment]
I don't have the power to re-open this. @mike3sullivan can you re-open it?

**Comment by mike3sullivan** [comment]
Sorry -- I gave up on Maui desktop after all the problems I had getting consistency between Windows and MacOS [moved to Blazor hybrid]. I briefly tried to recreate the simple app in a brand new .Net 8 project and it didn't work right away.  If this is a problem for you, i suggest you open a new bug report.
