### ISSUE TITLE
Failed To Build/Publish "Maui Blazor App" In Android Release Mode 

### ISSUE THREAD

**Issue by mALIk-sHAHId** [dotnet/maui#10602]
### Description

Hi I am Using Visual Studio 2022 Preview 2.1 
when i build MAUI Blazor or Maui App In the Release Mode Of ANDROID It shows the following error
<code>
<b>Severity	Code	Description	Project	File	Line	Suppression State</b>

> Error<i>	XAGJS7004 </i>

System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Xamarin.Android.Tasks.TypeMapGenerator.GenerateRelease(Boolean skipJniAddNativeMethodRegistrationAttributeScan, List`1 javaTypes, String outputDirectory, ApplicationConfigTaskState appConfState)
   at Xamarin.Android.Tasks.GenerateJavaStubs.WriteTypeMappings(List`1 types, TypeDefinitionCache cache)
   at Xamarin.Android.Tasks.GenerateJavaStubs.Run(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.GenerateJavaStubs.RunTask()
   at Microsoft.Android.Build.Tasks.AndroidTask.Execute() in /Users/runner/work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/AndroidTask.cs:line 17	PointOfSale	C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.465\tools\Xamarin.Android.Common.targets	1438	
</code>

But In Windows Release Mode It is working 

### Steps to Reproduce

1.Created new App 
2. Build in Debug Mode (working Fine)
3. trying To Build In Release Mode throws Error in **Android**
**Severity	Code	Description	Project	File	Line	Suppression State**

> Error	XAGJS7004	

```
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Xamarin.Android.Tasks.TypeMapGenerator.GenerateRelease(Boolean skipJniAddNativeMethodRegistrationAttributeScan, List`1 javaTypes, String outputDirectory, ApplicationConfigTaskState appConfState)
   at Xamarin.Android.Tasks.GenerateJavaStubs.WriteTypeMappings(List`1 types, TypeDefinitionCache cache)
   at Xamarin.Android.Tasks.GenerateJavaStubs.Run(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.GenerateJavaStubs.RunTask()
   at Microsoft.Android.Build.Tasks.AndroidTask.Execute() in /Users/runner/work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/AndroidTask.cs:line 17	PointOfSale	C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.465\tools\Xamarin.Android.Common.targets	1438	
```
Same Happen with Cloned App From Git repo

### Link to public reproduction project repository

https://github.com/dotnet/maui-samples/tree/main/6.0/Apps/PointOfSale

### Version with bug

dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.401
 Commit:    0906eae6f8

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.401\

Host:
  Version:      7.0.0-rc.1.22426.10
  Architecture: x64
  Commit:       06aceb7015

**Comment by PureWeen** [comment]
Once `RC2` releases can you try again there?

**Comment by mALIk-sHAHId** [comment]
Still facing the same issue
Please help me
I am unable to release or publish my apps

**Comment by TanayParikh** [comment]
This should be resolved in the RC2 public bits, can you please confirm what version you're running @mALIk-sHAHId?

Please see: https://github.com/dotnet/maui/issues/10408#issuecomment-1263689264 for workarounds.
