### ISSUE TITLE
Java.Lang.NullPointerException: boolean android.view.View.isInLayout()

### ISSUE THREAD

**Issue by DamirLisak** [dotnet/maui#10867]
### Description

My application crashes with a Null-Object-Reference exception:
Java.Lang.NullPointerException: 'Attempt to invoke virtual method 'boolean android.view.View.isInLayout()' on a null object reference'
This happens in a ListView when the bound value to the SelectedItem-Property changes to null through a Property-Changed event.

### Steps to Reproduce

I don't have a small example for reproducing this bug.

Maybe the following explanation helps:

The ListView is inside of a "Custom-Control" that is derived from ContentView:

```
**<ContentView** xmlns="http://schemas.microsoft.com/dotnet/2021/maui"... x:Class="gip.vbm.mobile.Controls.BarcodeScannerView">
    <ContentView.Content>
        <Grid>
...
            **<ListView**  Grid.Row="2"
                            x:Name="BarcodeListView" 
                            ItemsSource="{Binding DecodedEntitiesList}"
                            **SelectedItem="{Binding SelectedEntity}"**    
                            IsGroupingEnabled="false" 
                            RowHeight="70"
                            **ItemTemplate="{StaticResource BarcodeEntitySelector}"**
                            HasUnevenRows="true"
                            IsPullToRefreshEnabled="false"
                            IsRefreshing="{Binding IsBusy, Mode=OneWay}"
                            ItemSelected="BarcodeListView_ItemSelected"
                            ItemTapped="BarcodeListView_ItemTapped"
                            IsVisible="{Binding Source={RelativeSource Self}, Path=ShowDecodedEntities}" />
        </Grid>
    </ContentView.Content>
</ContentView>
```

The ContentView is used as a Control inside of a ContentPage:

```
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui" .... x:Class="gip.vbm.mobile.Views.BSOBarcodeTasksManu">
    <ContentPage.Content>
        <Grid>
            **<ctl:BarcodeScannerView** Grid.Row="1" VerticalOptions="CenterAndExpand"
                    x:Name="barcodeScanner" 
                    BarcodeIssuer="Production"
                    BarcodeServiceMethod="UseBarcodeSequences"
                    OnBarcodeEntityTapped="barcodeScanner_OnBarcodeEntityTapped" />
        </Grid>
    </ContentPage.Content>
</ContentPage>
```

Then I have a Base-Class for the implementation of INotifyPropertyChanged-Event:

```
    public abstract class EntityBase : INotifyPropertyChanged
    {
        protected bool SetProperty<T>(ref T backingStore, T value,
            [CallerMemberName]string propertyName = "",
            Action onChanged = null)
        {
            if (EqualityComparer<T>.Default.Equals(backingStore, value))
                return false;

            backingStore = value;
            onChanged?.Invoke();
            OnPropertyChanged(propertyName);
            return true;
        }

        public event PropertyChangedEventHandler PropertyChanged;
        protected void OnPropertyChanged([CallerMemberName] string propertyName = "")
        {
            var changed = PropertyChanged;
            if (changed == null)
                return;

            changed.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }
    }
```

Inside my datamodel I have this property, that raises the Property-Changed-Event:

```
        private object _SelectedEntity;
        public object SelectedEntity
        {
            get
            {
                return _SelectedEntity;
            }
            set
            {
                SetProperty(ref _SelectedEntity, value);
            }
        }
```

And when the Model-Property "SelectedEntity", that is bound to the "ItemSelected"-Property in the View, gets null (setter is invoked with null) then this Java-Exception appears randomly.

We have ported this application some days from Xamarin an there we didn't have this problem.

### Link to public reproduction project repository

https://github.com/DamirLisak/MAUI-issue-NullPointerException.git

### Version with bug

6.0.424

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

android 12

### Did you find any workaround?

No. We use Maui-Version 6.0.536.0

### Relevant log output

```shell
The thread 0x17 has exited with code 0 (0x0).
Thread finished: <Thread Pool> #23
Thread started: <Thread Pool> #27
[mono-rt] [ERROR] FATAL UNHANDLED EXCEPTION: Java.Lang.NullPointerException: Attempt to invoke virtual method 'boolean android.view.View.isInLayout()' on a null object reference
[mono-rt]    at Java.Interop.JniEnvironment.StaticMethods.CallStaticVoidMethod(JniObjectReference type, JniMethodInfo method, JniArgumentValue* args) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniEnvironment.g.cs:line 13250
[mono-rt]    at Java.Interop.JniPeerMembers.JniStaticMethods.InvokeVoidMethod(String encodedMember, JniArgumentValue* parameters) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniStaticMethods.cs:line 41
[mono-rt]    at Microsoft.Maui.PlatformInterop.RequestLayoutIfNeeded(View view) in D:\a\_work\1\s\src\Core\src\obj\Release
et6.0-android\generated\src\Microsoft.Maui.PlatformInterop.cs:line 421
[mono-rt]    at Microsoft.Maui.Platform.ViewExtensions.InvalidateMeasure(View platformView, IView view) in D:\a\_work\1\s\src\Core\src\Platform\Android\ViewExtensions.cs:line 258
[mono-rt]    at Microsoft.Maui.Handlers.ViewHandler.MapInvalidateMeasure(IViewHandler handler, IView view, Object args) in D:\a\_work\1\s\src\Core\src\Handlers\View\ViewHandler.cs:line 271
[mono-rt]    at Microsoft.Maui.CommandMapper`2.<>c__DisplayClass6_0[[Microsoft.Maui.IView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.IViewHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v, Object o) in D:\a\_work\1\s\src\Core\src\CommandMapper.cs:line 89
[mono-rt]    at Microsoft.Maui.CommandMapper.InvokeCore(String key, IElementHandler viewHandler, IElement virtualView, Object args) in D:\a\_work\1\s\src\Core\src\CommandMapper.cs:line 30
[mono-rt]    at Microsoft.Maui.CommandMapper.Invoke(IElementHandler viewHandler, IElement virtualView, String property, Object args) in D:\a\_work\1\s\src\Core\src\CommandMapper.cs:line 48
[mono-rt]    at Microsoft.Maui.Handlers.ElementHandler.Invoke(String command, Object args) in D:\a\_work\1\s\src\Core\src\Handlers\Element\ElementHandler.cs:line 90
[mono-rt]    at Microsoft.Maui.Controls.VisualElement.InvalidateMeasureOverride() in D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\VisualElement\VisualElement.Impl.cs:line 141
[mono-rt]    at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IView.InvalidateMeasure() in D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\VisualElement\VisualElement.Impl.cs:line 136
[mono-rt]    at Microsoft.Maui.Controls.VisualElement.InvalidateMeasureInternal(InvalidationTrigger trigger) in D:\a\_work\1\s\src\Controls\src\Core\VisualElement.cs:line 978
[mono-rt]    at Microsoft.Maui.Controls.Label.OnTextPropertyChanged(BindableObject bindable, Object oldvalue, Object newvalue) in D:\a\_work\1\s\src\Controls\src\Core\Label.cs:line 369
[mono-rt]    at Microsoft.Maui.Controls.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, Boolean silent) in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 532
[mono-rt]    at Microsoft.Maui.Controls.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes) in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 466
[mono-rt]    at Microsoft.Maui.Controls.BindingExpression.ApplyCore(Object sourceObject, BindableObject target, BindableProperty property, Boolean fromTarget) in D:\a\_work\1\s\src\Controls\src\Core\BindingExpression.cs:line 160
[mono-rt]    at Microsoft.Maui.Controls.BindingExpression.Apply(Boolean fromTarget) in D:\a\_work\1\s\src\Controls\src\Core\BindingExpression.cs:line 56
[mono-rt]    at Microsoft.Maui.Controls.BindingExpression.BindingExpressionPart.<PropertyChanged>b__49_0() in D:\a\_work\1\s\src\Controls\src\Core\BindingExpression.cs:line 750
[mono-rt]    at Microsoft.Maui.Controls.DispatcherExtensions.DispatchIfRequired(IDispatcher dispatcher, Action action) in D:\a\_work\1\s\src\Controls\src\Core\DispatcherExtensions.cs:line 53
[mono-rt]    at Microsoft.Maui.Controls.BindingExpression.BindingExpressionPart.PropertyChanged(Object sender, PropertyChangedEventArgs args) in D:\a\_work\1\s\src\Controls\src\Core\BindingExpression.cs:line 750
[mono-rt]    at Microsoft.Maui.Controls.BindingExpression.WeakPropertyChangedProxy.OnPropertyChanged(Object sender, PropertyChangedEventArgs e) in D:\a\_work\1\s\src\Controls\src\Core\BindingExpression.cs:line 653
[mono-rt]    at gip.core.datamodel.EntityBase.OnPropertyChanged(String propertyName) in D:\Devel\iPlusGit\iPlusV4\trunk\iPlus\gip.core.datamodel.shared\ACHelperclasses\EntityBase.cs:line 48
[mono-rt]    at gip.core.datamodel.EntityBase.SetProperty[Object](Object& backingStore, Object value, String propertyName, Action onChanged) in D:\Devel\iPlusGit\iPlusV4\trunk\iPlus\gip.core.datamodel.shared\ACHelperclasses\EntityBase.cs:line 34
[mono-rt]    at gip.vbm.mobile.ViewModels.BarcodeScanModelBase.set_SelectedEntity(Object value) in D:\Devel\iPlusGit\iPlusV4\trunk\Mobile\gip.vbm.mobile\gip.vbm.mobile\gip.vbm.mobile\ViewModels\Barcode\BarcodeScanModelBase.cs:line 100
[mono-rt]    at gip.vbm.mobile.ViewModels.BarcodeScanModelBase.Clear() in D:\Devel\iPlusGit\iPlusV4\trunk\Mobile\gip.vbm.mobile\gip.vbm.mobile\gip.vbm.mobile\ViewModels\Barcode\BarcodeScanModelBase.cs:line 278
[mono-rt]    at gip.vbm.mobile.ViewModels.BarcodeScanManuModel.Clear() in D:\Devel\iPlusGit\iPlusV4\trunk\Mobile\gip.vbm.mobile\gip.vbm.mobile\gip.vbm.mobile\ViewModels\Barcode\BarcodeScanManuModel.cs:line 132
[mono-rt]    at gip.vbm.mobile.Controls.BarcodeScannerView.Clear() in D:\Devel\iPlusGit\iPlusV4\trunk\Mobile\gip.vbm.mobile\gip.vbm.mobile\gip.vbm.mobile\Controls\BarcodeScannerView.xaml.cs:line 284
[mono-rt]    at gip.vbm.mobile.Controls.BarcodeScannerView.btnClearList_Clicked(Object sender, EventArgs e) in D:\Devel\iPlusGit\iPlusV4\trunk\Mobile\gip.vbm.mobile\gip.vbm.mobile\gip.vbm.mobile\Controls\BarcodeScannerView.xaml.cs:line 182
[mono-rt]    at Microsoft.Maui.Controls.Button.Microsoft.Maui.Controls.Internals.IButtonElement.PropagateUpClicked() in D:\a\_work\1\s\src\Controls\src\Core\Button.cs:line 196
[mono-rt]    at Microsoft.Maui.Controls.ButtonElement.ElementClicked(VisualElement visualElement, IButtonElement ButtonElementManager) in D:\a\_work\1\s\src\Controls\src\Core\ButtonElement.cs:line 61
[mono-rt]    at Microsoft.Maui.Controls.Button.SendClicked() in D:\a\_work\1\s\src\Controls\src\Core\Button.cs:line 179
[mono-rt]    at Microsoft.Maui.Controls.Button.Microsoft.Maui.IButton.Clicked() in D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\Button\Button.Impl.cs:line 23
[mono-rt]    at Microsoft.Maui.Handlers.ButtonHandler.OnClick(IButton button, View v) in D:\a\_work\1\s\src\Core\src\Handlers\Button\ButtonHandler.Android.cs:line 197
[mono-rt]    at Microsoft.Maui.Handlers.ButtonHandler.ButtonClickListener.OnClick(View v) in D:\a\_work\1\s\src\Core\src\Handlers\Button\ButtonHandler.Android.cs:line 212
[mono-rt]    at Android.Views.View.IOnClickListenerInvoker.n_OnClick_Landroid_view_View_(IntPtr jnienv, IntPtr native__this, IntPtr native_v) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net6.0/android-31/mcw/Android.Views.View.cs:line 2280
[mono-rt]    at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPL_V(_JniMarshal_PPL_V callback, IntPtr jnienv, IntPtr klazz, IntPtr p0) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 121
[mono-rt]   --- End of managed Java.Lang.NullPointerException stack trace ---
[mono-rt] java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.view.View.isInLayout()' on a null object reference
[mono-rt] 	at com.microsoft.maui.PlatformInterop.requestLayoutIfNeeded(PlatformInterop.java:47)
[mono-rt] 	at crc64fcf28c0e24b4cc31.ButtonHandler_ButtonClickListener.n_onClick(Native Method)
[mono-rt] 	at crc64fcf28c0e24b4cc31.ButtonHandler_ButtonClickListener.onClick(ButtonHandler_ButtonClickListener.java:30)
[mono-rt] 	at android.view.View.performClick(View.java:7792)
[mono-rt] 	at android.widget.TextView.performClick(TextView.java:16112)
[mono-rt] 	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1194)
[mono-rt] 	at android.view.View.performClickInternal(View.java:7769)
[mono-rt] 	at android.view.View.access$3800(View.java:910)
[mono-rt] 	at android.view.View$PerformClick.run(View.java:30218)
[mono-rt] 	at android.os.Handler.handleCallback(Handler.java:938)
[mono-rt] 	at android.os.Handler.dispatchMessage(Handler.java:99)
[mono-rt] 	at android.os.Looper.loopOnce(Looper.java:226)
[mono-rt] 	at android.os.Looper.loop(Looper.java:313)
[mono-rt] 	at android.app.ActivityThread.main(ActivityThread.java:8751)
[mono-rt] 	at java.lang.reflect.Method.invoke(Native Method)
[mono-rt] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
[mono-rt] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
[mono-rt] 
[mono-rt]   --- End of managed Java.Lang.NullPointerException stack trace ---
[mono-rt] java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.view.View.isInLayout()' on a null object reference
[mono-rt] 	at com.microsoft.maui.PlatformInterop.requestLayoutIfNeeded(PlatformInterop.java:47)
[mono-rt] 	at crc64fcf28c0e24b4cc31.ButtonHandler_ButtonClickListener.n_onClick(Native Method)
[mono-rt] 	at crc64fcf28c0e24b4cc31.ButtonHandler_ButtonClickListener.onClick(ButtonHandler_ButtonClickListener.java:30)
[mono-rt] 	at android.view.View.performClick(View.java:7792)
[mono-rt] 	at android.widget.TextView.performClick(TextView.java:16112)
[mono-rt] 	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1194)
[mono-rt] 	at android.view.View.performClickInternal(View.java:7769)
[mono-rt] 	at android.view.View.access$3800(View.java:910)
[mono-rt] 	at android.view.View$PerformClick.run(View.java:30218)
[mono-rt] 	at android.os.Handler.handleCallback(Handler.java:938)
[mono-rt] 	at android.os.Handler.dispatchMessage(Handler.java:99)
[mono-rt] 	at android.os.Looper.loopOnce(Looper.java:226)
[mono-rt] 	at android.os.Looper.loop(Looper.java:313)
[mono-rt] 	at android.app.ActivityThread.main(ActivityThread.java:8751)
[mono-rt] 	at java.lang.reflect.Method.invoke(Native Method)
[mono-rt] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
[mono-rt] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
[mono-rt]
```

**Comment by jsuarezruiz** [comment]
What are the steps to reproduce the issue?
![issue-10867](https://user-images.githubusercontent.com/6755973/199930726-d53cbab8-6692-4089-a804-6efe9d155633.gif)
