### ISSUE TITLE
iOS ScrollView inside VerticalStackLayout Crashes with infinite height measurement

### ISSUE THREAD

**Issue by Redth** [dotnet/maui#11017]
> Moved from: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1601659

If you attempt to place a `<ScrollView></ScrollView>` inside of a `<VerticalStackLayout></VerticalStackLayout>` on iOS, it will crash with the output:

```
Unhandled Exception:
ObjCRuntime.ObjCException: Objective-C exception thrown.  Name: CALayerInvalidGeometry Reason: CALayer bounds contains NaN: [0 nan; 368 inf]. Layer: <CALayer:0x6000002b2080; position = CGPoint (214 inf); bounds = CGRect (0 0; 368 inf); delegate = <UIScrollView: 0x7faaf7c9a600; frame = (30 nan; 368 inf); clipsToBounds = YES; gestureRecognizers = <NSArray: 0x60000068e280>; layer = <CALayer: 0x6000002b2080>; contentOffset: {0, 0}; contentSize: {0, 0}; adjustedContentInset: {0, 0, 0, 0}>; sublayers = (<CALayer: 0x6000002b2180>, <CALayer: 0x6000002b23e0>); opaque = YES; masksToBounds = YES; allowsGroupOpacity = YES; >
Native


at UIKit.UIView.set_Bounds(CGRect value)
   at Microsoft.Maui.ViewHandlerExtensions.PlatformArrangeHandler(IViewHandler viewHandler, Rect rect)
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IScrollView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[UIKit.UIScrollView, Microsoft.iOS, Version=16.0.700.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065]].PlatformArrange(Rect rect)
   at Microsoft.Maui.Handlers.ScrollViewHandler.PlatformArrange(Rect rect)
   at Microsoft.Maui.Controls.ScrollView.ArrangeOverride(Rect bounds)
   at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IView.Arrange(Rect bounds)
   at Microsoft.Maui.Layouts.VerticalStackLayoutManager.ArrangeChildren(Rect bounds)
   at Microsoft.Maui.Controls.Layout.CrossPlatformArrange(Rect bounds)
   at Microsoft.Maui.Platform.LayoutView.LayoutSubviews()
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName)
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)
   at maui7ga.Program.Main(String[] args) in /Users/redth/Desktop/maui7ga/Platforms/iOS/Program.cs:line 13
```

While you should avoid putting a scrollview inside a VSL like this, this should still not _crash_ the app.

**Comment by hartez** [comment]
Note that the original bug report is adding a ScrollView with _no content_. That might be important.

**Comment by hartez** [comment]
> Inside a `<ScrollView></ScrollView>` if you add a WebView with the property **IsVisible="False"** the app crashes on iOS with the same error reported by our friend @Redth .

Since this is happening in a different order (the ScrollView is the outer control rather than the inner) and with a different control (WebView rather than StackLayout), please open a separate issue. Thanks!
