### ISSUE TITLE
MAUI Conversion From XF App does not read App.xml at all

### ISSUE THREAD

**Issue by norton287** [dotnet/maui#11039]
### Description

Like the title say when building the app it does not seem to be reading the App.xml file for resources at all.  So I moved the dictionary merges into the <Content.Resources> tag and it works fine on debug.  But when I try to build on release I get the following error:

```
   at System.RuntimeType.CreateInstanceMono(Boolean nonPublic, Boolean wrapExceptions)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at Microsoft.Maui.Controls.ResourceDictionary.<>c.<SetAndLoadSource>b__8_0(Type key) in D:\a\_work\1\s\src\Controls\src\Core\ResourceDictionary.cs:line 49
   at System.Runtime.CompilerServices.ConditionalWeakTable`2[[System.Type, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Microsoft.Maui.Controls.ResourceDictionary, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].GetValueLocked(Type key, CreateValueCallback createValueCallback)
   at System.Runtime.CompilerServices.ConditionalWeakTable`2[[System.Type, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Microsoft.Maui.Controls.ResourceDictionary, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].GetValue(Type key, CreateValueCallback createValueCallback)
   at Microsoft.Maui.Controls.ResourceDictionary.SetAndLoadSource(Uri value, String resourcePath, Assembly assembly, IXmlLineInfo lineInfo) in D:\a\_work\1\s\src\Controls\src\Core\ResourceDictionary.cs:line 49
   at IsItUp.Views.HomePage.InitializeComponent() in C:\Users\norton287\source\repos\IsItUp\IsItUp\Microsoft.Maui.Controls.SourceGen\Microsoft.Maui.Controls.SourceGen.CodeBehindGenerator\Views_HomePage.xaml.sg.cs:line 33
   at IsItUp.Views.HomePage..ctor() in C:\Users\norton287\source\repos\IsItUp\IsItUp\Views\HomePage.xaml.cs:line 13
```

If I remove the dictionary entries from the tag then it throws errors on the StaticResource references to the styles and colors.  If I change the StaticResource to DynamicResource it builds but not the of the styles or colors are applied.

I'm sure it is something simple that I missed in the conversion but if anyone has an idea please let me know.
[App.zip](https://github.com/dotnet/maui/files/9912558/App.zip)
[Styles.zip](https://github.com/dotnet/maui/files/9912562/Styles.zip)

### Steps to Reproduce

Create a blank .Net MAUI Shell App and then copy the XF content over making the required changes.

After the changes run in Debug on Android (successfully) then try release which fails to read the App.xml resource dictionary.  Move the merged dictionaries into each view which works fine in Debug and applies them but throws an error when trying to build a release.

### Link to public reproduction project repository

new project doesn't reproduce the issue

### Version with bug

7.0 Release Candidate 2

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows

### Affected platform versions

iOS 15, Android 11, 12, 13, Windows 10 and 11

### Did you find any workaround?

I just removed the merged dictionaries from the individual views and allowed it not to read app.xml.

**Comment by jfversluis** [comment]
I'm going to assume that this was resolved one way or another and it was mostly a one-time thing rather than a bug and since this has been a while now I'll close it. If someone stumbles on this and it's still an issue for you, please feel free to let us know!
