### ISSUE TITLE
MSAL auth - Android - Release - crash after splashscreen

### ISSUE THREAD

**Issue by nk54** [dotnet/maui#11067]
### Description

Hello,

I followed https://learn.microsoft.com/en-us/azure/developer/mobile-apps/azure-mobile-apps/quickstarts/maui/authentication

It works well in Debug on each platform.

But on Android, it crashes after splashscreen in Release mode.
It works well in Debug.

Maybe there is a permission to add but it's not in the documentation so I don't know.

Will provide a repro project tomorrow morning

### Steps to Reproduce

Add a new activity with

```
[Activity(Exported = true)]
[IntentFilter(new[] { Intent.ActionView },
    Categories = new[] { Intent.CategoryBrowsable, Intent.CategoryDefault },
    DataHost = "auth",
    DataScheme = "msal{CANNOT_SHARE_MY_ID_HERE")]
public class MsalActivity : BrowserTabActivity
{
}
```

and in MainActivity, add 

    protected override void OnActivityResult(int requestCode, [GeneratedEnum] Result resultCode, Intent data)
    {
        base.OnActivityResult(requestCode, resultCode, data);
        // Return control to MSAL
        AuthenticationContinuationHelper.SetAuthenticationContinuationEventArgs(requestCode, resultCode, data);
    }

### Link to public reproduction project repository

https://github.com/nk54/maui_bug_msal

### Version with bug

7.0 Release Candidate 2

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 9 and maybe up

### Did you find any workaround?

Archive in Debug instead of Release but the app is so slow....
Or remove authentication ? 💥 🙅

**Comment by rachelkang** [comment]
@jonathanpeppers thoughts?

**Comment by rachelkang** [comment]
@nk54 Could you please [share a logcat](https://learn.microsoft.com/xamarin/android/deploy-test/debugging/android-debug-log?tabs=windows) so that we can investigate further? Thanks :)

**Comment by nk54** [comment]
From my test, the bug appears if this code (if put in comment, it starts) :
```[Activity(Exported = true)]
[IntentFilter(new[] { Intent.ActionView },
    Categories = new[] { Intent.CategoryBrowsable, Intent.CategoryDefault },
    DataHost = "auth",
    DataScheme = "msal{CANNOT_SHARE_MY_ID_HERE")]
public class MsalActivity : BrowserTabActivity
{
}

**Comment by nk54** [comment]
I've updated the repo on Github. Everything is included.

Even a ReproSteps.txt file

**Comment by nk54** [comment]
Time	Device Name	Type	PID	Tag	Message
11-03 10:35:21.515	nexus_9_-_api_33	Error	6757	AndroidRuntime	
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IStackNavigationView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Android.Views.View, Mono.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065]].OnCreatePlatformView()
   at Microsoft.Maui.Handlers.ViewHandler.OnCreatePlatformElement()
   at Microsoft.Maui.Handlers.ElementHandler.CreatePlatformElement()
   at Microsoft.Maui.Handlers.ElementHandler.SetVirtualView(IElement view)
   at Microsoft.Maui.Handlers.ViewHandler.SetVirtualView(IElement element)
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IStackNavigationView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Android.Views.View, Mono.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065]].SetVirtualView(IView view)
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IStackNavigationView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Android.Views.View, Mono.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065]].SetVirtualView(IElement view)
   at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler)
   at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value)
   at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.set_Handler(IElementHandler value)
   at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context)
   at Microsoft.Maui.Platform.ElementExtensions.ToPlatform(IElement view, IMauiContext context)
   at Microsoft.Maui.Platform.ScopedFragment.OnCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState)
   at AndroidX.Fragment.App.Fragment.n_OnCreateView_Landroid_view_LayoutInflater_Landroid_view_ViewGroup_Landroid_os_Bundle_(IntPtr , IntPtr , IntPtr , IntPtr , IntPtr )
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPLLL_L(_JniMarshal_PPLLL_L , IntPtr , IntPtr , IntPtr , IntPtr , IntPtr )
	at crc6452ffdc5b34af3a0f.ScopedFragment.n_onCreateView(Native Method)
	at crc6452ffdc5b34af3a0f.ScopedFragment.onCreateView(ScopedFragment.java:39)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:3104)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:524)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1890)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1814)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1751)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2976)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2886)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:263)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:351)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1510)
	at android.app.Activity.performStart(Activity.java:8310)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3711)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2306)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7892)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

**Comment by nk54** [comment]
Time	Device Name	Type	PID	Tag	Message
11-03 10:35:21.515	nexus_9_-_api_33	Error	6757	AndroidRuntime	FATAL EXCEPTION: main
11-03 10:35:21.515	nexus_9_-_api_33	Error	6757	AndroidRuntime	
11-03 10:35:21.515	nexus_9_-_api_33	Error	6757	AndroidRuntime	android.runtime.JavaProxyThrowable: System.InvalidProgramException: Invalid IL code in Microsoft.Maui.Handlers.NavigationViewHandler:CreatePlatformView (): IL_002a: ldnull    
11-03 10:35:21.515	nexus_9_-_api_33	Error	6757	AndroidRuntime	Process: com.eramet.setrag.vehiclereading, PID: 6757

**Comment by nk54** [comment]
Time	Device Name	Type	PID	Tag	Message
11-03 10:35:21.314	nexus_9_-_api_33	Error	435	SurfaceFlinger	Only WindowManager is allowed to use eEarlyWakeup[Start|End] flags

Time	Device Name	Type	PID	Tag	Message
11-03 10:35:20.841	nexus_9_-_api_33	Error	1606	HwDetectorWithState	a: 3


Time	Device Name	Type	PID	Tag	Message
11-03 10:35:20.730	nexus_9_-_api_33	Error	381	android.hardware.audio@7.0-impl.ranchu	device/generic/goldfish/audio/device_port_sink.cpp:start:75 failure: Result::INVALID_STATE
Time	Device Name	Type	PID	Tag	Message
11-03 10:35:20.729	nexus_9_-_api_33	Error	381	android.hardware.audio@7.0-impl.ranchu	device/generic/goldfish/audio/stream_out.cpp:updateSourceMetadata:388 failure: Result::NOT_SUPPORTED

**Comment by nk54** [comment]
@rachelkang Visual Studio log console (logcat) SHOULD (must?) avec columns filterable : I cannot search error only. It doesn't help at all. Visual Studio must be the best experience to develop MAUI app. But it doesn't feel like it is. It's been years developpers wait for such things.

Adding support and improving accessibility is good. But Microsoft spend its resource to help 0.0001% of developpers while remaining are waiting for basic things since years.

**Comment by nk54** [comment]
The more I dig, the more I'm not sure if MSAL if the problem.

**Comment by nk54** [comment]
I've created a new issue and closed this one because the title of this thread is misleading.
