### ISSUE TITLE
Android Release : MainPage = new NavigationPage(new ContentPage()); crashes

### ISSUE THREAD

**Issue by nk54** [dotnet/maui#11083]
### Description

https://learn.microsoft.com/en-us/dotnet/maui/user-interface/pages/navigationpage

The code given crashes in Release mode on Android (no problem on Debug. I didn't test iOS).
Works on Windows (Debug & Release too).

    public App()
    {
        InitializeComponent();

        ContentPage startPage = new ContentPage() { Content = new Label() { Text = "Hello" } };

        // App Crashes
        // MainPage = new NavigationPage(startPage);

        // App starts
        MainPage = startPage;
    }

### Steps to Reproduce

Just try to set MainPage as a NavigationPage
(AppShell is too far from being ready to be used : relative navigation not supported, those kind of stuff)

### Link to public reproduction project repository

https://github.com/nk54/maui_bug_navigation

### Version with bug

7.0 Release Candidate 2

### Last version that worked well

7.0 Release Candidate 1

### Affected platforms

Android

### Affected platform versions

Android 9 and up

### Did you find any workaround?

Deploy my debug app of 60 MB instead of 30 MB....... (once optimized otherwise 160 MB)

### Relevant log output

```shell
none
```

**Comment by nk54** [comment]
This must be a P1 because it is very trivial and I never saw a Xamarin/MAUI app without navigation.

It is mandatory. It is a regression.

I'm a XAML guy since Silverlight and I can wait.

But a developper without experience of Xamarin/MAUI will uninstall everything if the basic Navigation from the documentation,  one of the first thing he will try crashes.

**Comment by nk54** [comment]
Time	Device Name	Type	PID	Tag	Message
11-03 15:01:47.432	nexus_9_-_api_33	Info	10968	MonoDroid	
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IStackNavigationView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Android.Views.View, Mono.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065]].OnCreatePlatformView()
   at Microsoft.Maui.Handlers.ViewHandler.OnCreatePlatformElement()
   at Microsoft.Maui.Handlers.ElementHandler.CreatePlatformElement()
   at Microsoft.Maui.Handlers.ElementHandler.SetVirtualView(IElement view)
   at Microsoft.Maui.Handlers.ViewHandler.SetVirtualView(IElement element)
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IStackNavigationView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Android.Views.View, Mono.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065]].SetVirtualView(IView view)
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IStackNavigationView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Android.Views.View, Mono.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065]].SetVirtualView(IElement view)
   at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler)
   at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value)
   at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.set_Handler(IElementHandler value)
   at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context)
   at Microsoft.Maui.Platform.ElementExtensions.ToPlatform(IElement view, IMauiContext context)
   at Microsoft.Maui.Platform.ScopedFragment.OnCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState)
   at AndroidX.Fragment.App.Fragment.n_OnCreateView_Landroid_view_LayoutInflater_Landroid_view_ViewGroup_Landroid_os_Bundle_(IntPtr , IntPtr , IntPtr , IntPtr , IntPtr )
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPLLL_L(_JniMarshal_PPLLL_L , IntPtr , IntPtr , IntPtr , IntPtr , IntPtr )
	at crc6452ffdc5b34af3a0f.ScopedFragment.n_onCreateView(Native Method)
	at crc6452ffdc5b34af3a0f.ScopedFragment.onCreateView(ScopedFragment.java:39)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:3104)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:524)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1890)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1814)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1751)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2976)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2886)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:263)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:351)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1510)
	at android.app.Activity.performStart(Activity.java:8310)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3711)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2306)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7892)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

**Comment by PureWeen** [comment]
Hmm running this I'm seeing the following exception in release mode

@jonathanpeppers thoughts?

```C#
2022-11-03 13:20:44.737 12723-12723/com.companyname.dotnetconfdemo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.companyname.dotnetconfdemo, PID: 12723
    android.runtime.JavaProxyThrowable: System.InvalidProgramException: Invalid IL code in Microsoft.Maui.Handlers.NavigationViewHandler:CreatePlatformView (): IL_002a: ldnull    
    
    
        at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IStackNavigationView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Android.Views.View, Mono.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065]].OnCreatePlatformView()
        at Microsoft.Maui.Handlers.ViewHandler.OnCreatePlatformElement()
        at Microsoft.Maui.Handlers.ElementHandler.CreatePlatformElement()
        at Microsoft.Maui.Handlers.ElementHandler.SetVirtualView(IElement view)
        at Microsoft.Maui.Handlers.ViewHandler.SetVirtualView(IElement element)
        at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IStackNavigationView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Android.Views.View, Mono.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065]].SetVirtualView(IView view)
    ```

**Comment by PureWeen** [comment]
Related to 
https://github.com/dotnet/maui/commit/b73147e124cfc983a18ac2d7884fc7667b4eaf7d
