### ISSUE TITLE
Android Designer for Visual Studio doesn't load custom components

### ISSUE THREAD

**Issue by arivoir** [dotnet/maui#11112]
### Description

The Android designer for Visual Studio fails to load custom controls

### Steps to Reproduce

1.Create an native Android Application
2.Add a custom control
3.Add an instance of that control to a layout axml file
4.Look at the designer

"Custom controls disabled, There was an internal issue with process"

### Link to public reproduction project repository

No demo

### Version with bug

7.0 Release Candidate 2

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Visual Studio Version 17.4.0 Preview 6.0 dotnet --version 7.0.100-rc.2.22477.23

### Did you find any workaround?

No

### Relevant log output

```shell
[2022-11-04 12:37:19.8] INFO: : Android Designer version: 17.4.138 (d36bba3cc9)
[2022-11-04 12:37:20.1] INFO: : JDK version: 1.8.0_302
[2022-11-04 12:37:20.1] INFO: : JDK vendor: Temurin

[2022-11-04 12:37:21.5] Renderer >> INFO: Parsing C:\Program Files (x86)\Android\android-sdk\build-tools\29.0.2\package.xml
[2022-11-04 12:37:21.7] Renderer >> INFO: Parsing C:\Program Files (x86)\Android\android-sdk\build-tools\29.0.3\package.xml
[2022-11-04 12:37:21.7] Renderer >> INFO: Parsing C:\Program Files (x86)\Android\android-sdk\build-tools\30.0.2\package.xml
[2022-11-04 12:37:21.7] Renderer >> INFO: Parsing C:\Program Files (x86)\Android\android-sdk\build-tools\31.0.0\package.xml
[2022-11-04 12:37:21.7] Renderer >> INFO: Parsing legacy package: C:\Program Files (x86)\Android\android-sdk\build-tools\32.0.0
[2022-11-04 12:37:21.8] Renderer >> INFO: Exception while marshalling C:\Program Files (x86)\Android\android-sdk\build-tools\32.0.0\package.xml. Probably the SDK is read-only
[2022-11-04 12:37:21.8] Renderer >> INFO: Parsing C:\Program Files (x86)\Android\android-sdk\build-tools\33.0.0\package.xml
[2022-11-04 12:37:21.8] Renderer >> WARNING: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
[2022-11-04 12:37:21.8] Renderer >> WARNING: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
[2022-11-04 12:37:21.8] Renderer >> WARNING: Mapping new ns http://schemas.android.com/sdk/android/repo/common/03 to old ns http://schemas.android.com/sdk/android/repo/common/01
[2022-11-04 12:37:21.8] Renderer >> WARNING: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/03 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
[2022-11-04 12:37:21.8] Renderer >> WARNING: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/03 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
[2022-11-04 12:37:21.8] Renderer >> INFO: Parsing C:\Program Files (x86)\Android\android-sdk\cmdline-tools\2.1\package.xml
[2022-11-04 12:37:21.8] Renderer >> INFO: Parsing C:\Program Files (x86)\Android\android-sdk\cmdline-tools\3.0\package.xml
[2022-11-04 12:37:21.8] Renderer >> INFO: Parsing legacy package: C:\Program Files (x86)\Android\android-sdk\cmdline-tools\7.0
[2022-11-04 12:37:21.8] Renderer >> INFO: Parsing C:\Program Files (x86)\Android\android-sdk\emulator\package.xml
[2022-11-04 12:37:21.8] Renderer >> INFO: Parsing C:\Program Files (x86)\Android\android-sdk\emulator.old1239082176\package.xml
[2022-11-04 12:37:21.8] Renderer >> WARNING: Observed package id 'emulator' in inconsistent location 'C:\Program Files (x86)\Android\android-sdk\emulator.old1239082176' (Expected 'C:\Program Files (x86)\Android\android-sdk\emulator')
[2022-11-04 12:37:21.8] Renderer >> WARNING: Already observed package id 'emulator' in 'C:\Program Files (x86)\Android\android-sdk\emulator'. Skipping duplicate at 'C:\Program Files (x86)\Android\android-sdk\emulator.old1239082176'
[2022-11-04 12:37:21.8] Renderer >> INFO: Parsing C:\Program Files (x86)\Android\android-sdk\ndk-bundle\package.xml
[2022-11-04 12:37:21.8] Renderer >> INFO: Parsing C:\Program Files (x86)\Android\android-sdk\patcher\v4\package.xml
[2022-11-04 12:37:21.8] Renderer >> INFO: Parsing legacy package: C:\Program Files (x86)\Android\android-sdk\platform-tools
[2022-11-04 12:37:21.8] Renderer >> INFO: Exception while marshalling C:\Program Files (x86)\Android\android-sdk\platform-tools\package.xml. Probably the SDK is read-only
[2022-11-04 12:37:21.8] Renderer >> INFO: Parsing C:\Program Files (x86)\Android\android-sdk\platform-tools.old69446700\package.xml
[2022-11-04 12:37:21.8] Renderer >> WARNING: Observed package id 'platform-tools' in inconsistent location 'C:\Program Files (x86)\Android\android-sdk\platform-tools.old69446700' (Expected 'C:\Program Files (x86)\Android\android-sdk\platform-tools')
[2022-11-04 12:37:21.8] Renderer >> WARNING: Already observed package id 'platform-tools' in 'C:\Program Files (x86)\Android\android-sdk\platform-tools'. Skipping duplicate at 'C:\Program Files (x86)\Android\android-sdk\platform-tools.old69446700'
[2022-11-04 12:37:21.8] Renderer >> INFO: Parsing C:\Program Files (x86)\Android\android-sdk\platforms\android-28\package.xml
[2022-11-04 12:37:21.8] Renderer >> INFO: Parsing C:\Program Files (x86)\Android\android-sdk\platforms\android-29\package.xml
[2022-11-04 12:37:21.8] Renderer >> INFO: Parsing C:\Program Files (x86)\Android\android-sdk\platforms\android-30\package.xml
[2022-11-04 12:37:21.8] Renderer >> WARNING: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
[2022-11-04 12:37:21.8] Renderer >> WARNING: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
[2022-11-04 12:37:21.8] Renderer >> WARNING: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
[2022-11-04 12:37:21.8] Renderer >> WARNING: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
[2022-11-04 12:37:21.8] Renderer >> WARNING: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
[2022-11-04 12:37:21.8] Renderer >> INFO: Parsing C:\Program Files (x86)\Android\android-sdk\platforms\android-31\package.xml
[2022-11-04 12:37:21.8] Renderer >> WARNING: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
[2022-11-04 12:37:21.8] Renderer >> WARNING: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
[2022-11-04 12:37:21.8] Renderer >> WARNING: Mapping new ns http://schemas.android.com/sdk/android/repo/common/03 to old ns http://schemas.android.com/sdk/android/repo/common/01
[2022-11-04 12:37:21.8] Renderer >> WARNING: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/03 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
[2022-11-04 12:37:21.8] Renderer >> WARNING: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/03 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
[2022-11-04 12:37:21.9] Renderer >> WARNING: unrecognized type name: platform. Did you mean archives?
[2022-11-04 12:37:21.9] Renderer >> WARNING: Unable to create an instance of com.android.repository.impl.generated.v1.TypeDetails:
[2022-11-04 12:37:21.9] Renderer >> java.lang.InstantiationException
[2022-11-04 12:37:21.9] Renderer >> 	at sun.reflect.InstantiationExceptionConstructorAccessorImpl.newInstance(InstantiationExceptionConstructorAccessorImpl.java:48)
[2022-11-04 12:37:21.9] Renderer >> 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[2022-11-04 12:37:21.9] Renderer >> 	at com.sun.xml.internal.bind.v2.ClassFactory.create0(ClassFactory.java:118)
[2022-11-04 12:37:21.9] Renderer >> 	at com.sun.xml.internal.bind.v2.runtime.ClassBeanInfoImpl.createInstance(ClassBeanInfoImpl.java:270)
[2022-11-04 12:37:21.9] Renderer >> 	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext.createInstance(UnmarshallingContext.java:684)
[2022-11-04 12:37:21.9] Renderer >> 	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.StructureLoader.startElement(StructureLoader.java:171)
[2022-11-04 12:37:21.9] Renderer >> 	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.XsiTypeLoader.startElement(XsiTypeLoader.java:65)
[2022-11-04 12:37:21.9] Renderer >> 	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext._startElement(UnmarshallingContext.java:559)
[2022-11-04 12:37:21.9] Renderer >> 	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext.startElement(UnmarshallingContext.java:538)
[2022-11-04 12:37:21.9] Renderer >> 	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.SAXConnector.startElement(SAXConnector.java:153)
[2022-11-04 12:37:21.9] Renderer >> 	at org.xml.sax.helpers.XMLFilterImpl.startElement(XMLFilterImpl.java:551)
[2022-11-04 12:37:21.9] Renderer >> 	at com.android.repository.impl.meta.SchemaModuleUtil$NamespaceFallbackFilter.startElement(SchemaModuleUtil.java:398)
[2022-11-04 12:37:21.9] Renderer >> 	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509)
[2022-11-04 12:37:21.9] Renderer >> 	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:374)
[2022-11-04 12:37:21.9] Renderer >> 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2784)
[2022-11-04 12:37:21.9] Renderer >> 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
[2022-11-04 12:37:21.9] Renderer >> 	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
[2022-11-04 12:37:21.9] Renderer >> 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
[2022-11-04 12:37:21.9] Renderer >> 	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842)
[2022-11-04 12:37:21.9] Renderer >> 	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
[2022-11-04 12:37:21.9] Renderer >> 	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
[2022-11-04 12:37:21.9] Renderer >> 	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
[2022-11-04 12:37:21.9] Renderer >> 	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
[2022-11-04 12:37:21.9] Renderer >> 	at org.xml.sax.helpers.XMLFilterImpl.parse(XMLFilterImpl.java:357)
[2022-11-04 12:37:21.9] Renderer >> 	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:243)
[2022-11-04 12:37:21.9] Renderer >> 	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:214)
[2022-11-04 12:37:21.9] Renderer >> 	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:140)
[2022-11-04 12:37:21.9] Renderer >> 	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:123)
[2022-11-04 12:37:21.9] Renderer >> 	at com.android.repository.impl.meta.SchemaModuleUtil.unmarshal(SchemaModuleUtil.java:192)
[2022-11-04 12:37:21.9] Renderer >> 	at com.android.repository.impl.manager.LocalRepoLoaderImpl.parsePackage(LocalRepoLoaderImpl.java:313)
[2022-11-04 12:37:21.9] Renderer >> 	at com.android.repository.impl.manager.LocalRepoLoaderImpl.parsePackages(LocalRepoLoaderImpl.java:160)
[2022-11-04 12:37:21.9] Renderer >> 	at com.android.repository.impl.manager.LocalRepoLoaderImpl.getPackages(LocalRepoLoaderImpl.java:125)
[2022-11-04 12:37:21.9] Renderer >> 	at com.android.repository.impl.manager.RepoManagerImpl$LoadTask.run(RepoManagerImpl.java:521)
[2022-11-04 12:37:21.9] Renderer >> 	at com.android.repository.api.RepoManager$DummyProgressRunner.runSyncWithProgress(RepoManager.java:397)
[2022-11-04 12:37:21.9] Renderer >> 	at com.android.repository.impl.manager.RepoManagerImpl.load(RepoManagerImpl.java:365)
[2022-11-04 12:37:21.9] Renderer >> 	at com.android.repository.api.RepoManager.loadSynchronously(RepoManager.java:290)
[2022-11-04 12:37:21.9] Renderer >> 	at com.android.sdklib.repository.AndroidSdkHandler$RepoConfig.createRepoManager(AndroidSdkHandler.java:731)
[2022-11-04 12:37:21.9] Renderer >> 	at com.android.sdklib.repository.AndroidSdkHandler.getSdkManager(AndroidSdkHandler.java:297)
[2022-11-04 12:37:21.9] Renderer >> 	at com.android.sdklib.devices.DeviceManager.initSysImgDevices(DeviceManager.java:370)
[2022-11-04 12:37:21.9] Renderer >> 	at com.android.sdklib.devices.DeviceManager.initDevicesLists(DeviceManager.java:267)
[2022-11-04 12:37:21.9] Renderer >> 	at com.android.sdklib.devices.DeviceManager.getDevices(DeviceManager.java:247)
[2022-11-04 12:37:21.9] Renderer >> 	at mono.android.AndroidDesignerHost.getDevices(AndroidDesignerHost.java:205)
[2022-11-04 12:37:21.9] Renderer >> 	at mono.android.AndroidDesignerHost.processMessage(AndroidDesignerHost.java:296)
[2022-11-04 12:37:21.9] Renderer >> 	at mono.android.MessageListener.executeMessage(MessageListener.java:88)
[2022-11-04 12:37:21.9] Renderer >> 	at mono.android.MessageListener$Runner.run(MessageListener.java:44)
[2022-11-04 12:37:21.9] Renderer >> 	at java.lang.Thread.run(Thread.java:748)

[2022-11-04 12:37:39.3] Renderer >> WARNING: Xamarin.Android support for custom controls has been disabled by IDE request.

[2022-11-04 12:37:39.6] Renderer >> INFO: Not loading custom component, monodroid is not ready
```

**Comment by arivoir** [comment]
I reported it as suggested

https://developercommunity.visualstudio.com/t/Android-Designer-doesnt-load-custom-con/10192182
