### ISSUE TITLE
dotnet workload not work when l update to .net 7!

### ISSUE THREAD

**Issue by Snsaiu** [dotnet/maui#11210]
### Description

when l updated vs for mac on my m1 macbook.my maui project can not loaded.and when l use dotnet workload list command .it show error 
`Unhandled exception: Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadManifestCompositionException: 清单“wasm-tools”[microsoft.net.workload.mono.toolchain] 中的工作负载定义“/usr/local/share/dotnet/sdk-manifests/7.0.100/microsoft.net.workload.mono.toolchain/WorkloadManifest.json”与清单“microsoft.net.workload.mono.toolchain.net7”[/usr/local/share/dotnet/sdk-manifests/7.0.100/microsoft.net.workload.mono.toolchain.net7/WorkloadManifest.json] 冲突
   at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadResolver.ComposeWorkloadManifests()
   at Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadResolver.Create(IWorkloadManifestProvider manifestProvider, String dotnetRootPath, String sdkVersion, String userProfileDir)
   at Microsoft.DotNet.Workloads.Workload.Repair.WorkloadRepairCommand..ctor(ParseResult parseResult, IReporter reporter, IWorkloadResolver workloadResolver, IInstaller workloadInstaller, INuGetPackageDownloader nugetPackageDownloader, String dotnetDir, String tempDirPath, String version, String userProfileDir)
   at Microsoft.DotNet.Cli.WorkloadRepairCommandParser.<>c.<ConstructCommand>b__5_0(ParseResult parseResult)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.DotNet.Cli.Parser.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__17_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass15_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.CommandLineBuilderExtensions.<>c__DisplayClass7_0.<<UseExceptionHandler>b__0>d.MoveNext()` 

### Steps to Reproduce

1. update vs for mac to 17.5 Preview (17.5 build 437)
2. open or create maui project.
3. vs for mac show error:Unable to find SDK 'Microsoft.NET.SDK.WorkloadAutoImportPropsLocator' sdk not found
4. use workload list command  show error:Unhandled exception: Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadManifestCompositionException: 清单“wasm-tools”[microsoft.net.workload.mono.toolchain] 中的工作负载定义“/usr/local/share/dotnet/sdk-manifests/7.0.100/microsoft.net.workload.mono.toolchain/WorkloadManifest.json”与清单“microsoft.net.workload.mono.toolchain.net7”[/usr/local/share/dotnet/sdk-manifests/7.0.100/microsoft.net.workload.mono.toolchain.net7/WorkloadManifest.json] 冲突

### Link to public reproduction project repository

no

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

ventura 13.1 Beta版(22C5044e)

**Comment by Snsaiu** [comment]
fixed.delete usr/local/share/dotnet/sdk-manifests folder and reinstall .net 7 sdk.
