### ISSUE TITLE
Signed apks not working on real devices but working on emulators

### ISSUE THREAD

**Issue by sencagri** [dotnet/maui#11292]
### Description

I have published a .NET Maui app it is working on emulators but not working on real devices.  By the way, I have tested 5 different real device.

### **When trimming and AOT is disabled it works but incredibly slow and sluggish.** 

There is a apk file I have uploaded for testing, you can download it to your devices and emulators also.
https://aktifbarkod.com/d just go and download apk file. ( There is a only one apk file )

The only log output I can find is below from a real device:
```
android.runtime.JavaProxyThrowable: System.TypeLoadException: Could not load type AktifBarkod.AktifPOS.Mobil.EkranDiğer.Ana.AnaPage while decoding custom attribute: (null)
   at System.Reflection.CustomAttribute.GetCustomAttributesBase(ICustomAttributeProvider , Type , Boolean )
   at System.Reflection.CustomAttribute.GetCustomAttributes(ICustomAttributeProvider , Type , Boolean )
   at System.Attribute.GetCustomAttributes(Assembly element, Type attributeType)
   at System.Reflection.CustomAttributeExtensions.GetCustomAttributes(Assembly , Type )
   at System.Reflection.CustomAttributeExtensions.GetCustomAttributes[XamlResourceIdAttribute](Assembly )
   at Microsoft.Maui.Controls.Xaml.XamlResourceIdAttribute.GetTypeForPath(Assembly assembly, String path)
   at Microsoft.Maui.Controls.ResourceDictionary.SetAndLoadSource(Uri value, String resourcePath, Assembly assembly, IXmlLineInfo lineInfo)
   at AktifBarkod.AktifPOS.Mobil.App.InitializeComponent()
   at AktifBarkod.AktifPOS.Mobil.App..ctor()
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags , Binder , Object[] , CultureInfo )
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite , RuntimeResolverContext )
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSiteMain(ServiceCallSite , RuntimeResolverContext )
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite , RuntimeResolverContext )
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSite(ServiceCallSite , RuntimeResolverContext )
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type )
   at System.Collections.Concurrent.ConcurrentDictionary2[[System.Type, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Func2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope, Microsoft.Extensions.DependencyInjection, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].GetOrAdd(Type , Func`2 )
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type )
   at Microsoft.Maui.MauiContext.WrappedServiceProvider.GetService(Type serviceType)
   at Microsoft.Maui.MauiContext.WrappedServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider , Type )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[IApplication](IServiceProvider )
   at Microsoft.Maui.MauiApplication.OnCreate()
   at Android.App.Application.n_OnCreate(IntPtr , IntPtr )
at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(_JniMarshal_PP_V , IntPtr , IntPtr )
 at crc6488302ad6e9e4df1a.MauiApplication.n_onCreate(Native Method)
 at crc6488302ad6e9e4df1a.MauiApplication.onCreate(MauiApplication.java:28)
 at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1193)
 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6975)
 at android.app.ActivityThread.access$1500(ActivityThread.java:257)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1982)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loop(Looper.java:236)
 at android.app.ActivityThread.main(ActivityThread.java:8037)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
```

Real device

https://user-images.githubusercontent.com/7950917/201405363-05593aff-26bb-4aee-bfc3-e8017199dbad.mp4

Emulator

https://user-images.githubusercontent.com/7950917/201408674-68cda6da-3e98-42d6-91d5-ae0782785c0f.mp4

PS:

### Steps to Reproduce

-

### Link to public reproduction project repository

This is a private repo.

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

All android versions

### Did you find any workaround?

no

**Comment by VictorCanovasA** [comment]
Same issue here. I have updated to .net 7 to see if it solves the problem but apk still crashes

**Comment by jsuarezruiz** [comment]
cc @jonathanpeppers

**Comment by Taiizor** [comment]
Try without Turkish characters `AktifBarkod.AktifPOS.Mobil.EkranDiğer.Ana.AnaPage`.

**Comment by alrit-solutions** [comment]
I am getting the same issue with my .net Maui signed app. Has there been any other feedback or way around this?

**Comment by sencagri** [comment]
> Try without Turkish characters `AktifBarkod.AktifPOS.Mobil.EkranDiğer.Ana.AnaPage`.

That seems work for my case. Thanks

**Comment by Taiizor** [comment]
> > Try without Turkish characters `AktifBarkod.AktifPOS.Mobil.EkranDiğer.Ana.AnaPage`.
> 
> That seems work for my case. Thanks

nP

**Comment by jonathanpeppers** [comment]
Moving this to dotnet/runtime, for them to look at it.
