### ISSUE TITLE
Navigating backward produces "Pending Navigations still processing" exception

### ISSUE THREAD

**Issue by pstricks-fans** [dotnet/maui#11307]
### Description

There is no problem when I navigate from master page to detail page. But the reverse produces the following exception.

![Error](https://user-images.githubusercontent.com/50270635/201466727-d0763760-23ae-4932-a66f-2f842dc20ad2.png)

### Steps to Reproduce

**Configuration:**

    public static class MauiProgram
    {
        public static MauiApp CreateMauiApp()
        {
            var builder = MauiApp.CreateBuilder();
            builder
                .UseMauiApp<App>()
                .ConfigureFonts(fonts =>
                {
                    fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
                    fonts.AddFont("OpenSans-Semibold.ttf", "OpenSansSemibold");
                });
    
            builder.Services
                .AddHttpClient<MonkeyService>();
    
            builder.Services
                .AddSingleton<MasterViewModel>()
                .AddSingleton<MasterPage>();
    
            builder.Services
                .AddTransient<DetailViewModel>()
                .AddTransient<DetailPage>();
    
            return builder.Build();
        }
    }

**AppShell:**

    public partial class AppShell : Shell
    {
        public AppShell()
        {
            InitializeComponent();
            Routing.RegisterRoute(nameof(DetailPage), typeof(DetailPage));
        }
    }

**Model:**

    public class Monkey
    {
        public string Name { get; set; } = default!;
        public string Location { get; set; } = default!;
        public string Details { get; set; } = default!;
        public string Image { get; set; } = default!;
        public int Population { get; set; }
        public float Latitude { get; set; }
        public float Longitude { get; set; }
    }

**Service:**

    public class MonkeyService
    {
        private readonly HttpClient httpClient;
        public MonkeyService(HttpClient httpClient)
        {
            this.httpClient = httpClient;
        }
    
    
        public async ValueTask<IEnumerable<Monkey>?> GetMonkeys()
        {
            var response = await httpClient.GetAsync("https://www.montemagno.com/monkeys.json");
    
            if (response.IsSuccessStatusCode)
            {
                return await response.Content.ReadFromJsonAsync<IEnumerable<Monkey>>();
            }
    
            return Enumerable.Empty<Monkey>();
        }
    }

**View Model:**

    public partial class MasterViewModel : ObservableObject
    {
        private readonly MonkeyService service;
    
        public MasterViewModel(MonkeyService service)
        {
            this.service = service;
        }
    
    
        public ObservableCollection<Monkey> Monkeys { get; } = new();
    
    
        public async Task ReloadAsync()
        {
            Monkeys.Clear();
    
            var monkeys = await service.GetMonkeys();
    
            foreach (var monkey in monkeys ?? Enumerable.Empty<Monkey>())
                Monkeys.Add(monkey);
        }
    }
    
    
    [QueryProperty(nameof(Monkey), nameof(Monkey))]
    public partial class DetailViewModel : ObservableObject
    {
        private readonly MonkeyService service;
        public DetailViewModel(MonkeyService service)
        {
            this.service = service;
        }
    
    
        [ObservableProperty]
        Monkey monkey = default!;
    }

**Pages:**

```xml
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:models="clr-namespace:MauiClient.Models"
             xmlns:viewmodels="clr-namespace:MauiClient.ViewModels"
             x:Class="MauiClient.Pages.MasterPage"
             x:DataType="viewmodels:MasterViewModel"
             Title="Master Page"
             >
    <CollectionView 
                    ItemsSource="{Binding Monkeys}"
                    SelectionMode="Single"
                    SelectionChanged="OnSelectionChanged"
                    >

        <CollectionView.ItemsLayout>
            <LinearItemsLayout Orientation="Vertical"/>
        </CollectionView.ItemsLayout>

        <CollectionView.ItemTemplate>
            <DataTemplate x:DataType="models:Monkey" >
                <VerticalStackLayout>
                    <Label Text="{Binding Name}" />
                </VerticalStackLayout>
            </DataTemplate>
        </CollectionView.ItemTemplate>

    </CollectionView>

</ContentPage>
```

```csharp
public partial class MasterPage : ContentPage
{
    public MasterPage(MasterViewModel model)
    {
        InitializeComponent();
        BindingContext = model;
    }

    protected override async void OnAppearing()
    {
        base.OnAppearing();
        if (BindingContext is MasterViewModel model)
        {
            Debug.WriteLine(nameof(OnAppearing));
            await model.ReloadAsync();
        }
    }

    private async void OnSelectionChanged(object sender, SelectionChangedEventArgs e)
    {
        Debug.WriteLine(nameof(OnSelectionChanged));

        var navparam = new Dictionary<string, object?>
        {
            [nameof(Monkey)] = e.CurrentSelection.FirstOrDefault() as Monkey
        };

        await Shell.Current.GoToAsync(nameof(DetailPage), navparam);
    }
}
```

```xml
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:viewmodels="clr-namespace:MauiClient.ViewModels"
             x:Class="MauiClient.Pages.DetailPage"
             x:DataType="viewmodels:DetailViewModel"
             Title="Detail Page"
             >   
    
    <VerticalStackLayout  >
        <Label Text="{Binding Monkey.Name}" />
        <Button Text="Back" Clicked="Back_Clicked"/>
    </VerticalStackLayout>    
    
</ContentPage>
```

```csharp
public partial class DetailPage : ContentPage
{
    public DetailPage(DetailViewModel model)
    {
        InitializeComponent();
        BindingContext = model;
    }

    private async void Back_Clicked(object sender, EventArgs e)
    {
        await Shell.Current.GoToAsync("..");
    }
}
```

### Link to public reproduction project repository

https://github.com/pstricks-fans/MauiClient

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10 build number: 19044.2251

### Relevant log output

```shell
System.InvalidOperationException HResult=0x80131509
Message=Pending Navigations still processing
Source=Microsoft.Maui.Controls StackTrace: at Microsoft.Maui.Controls.ShellSection.Microsoft.Maui.IStackNavigation.RequestNavigation(NavigationRequest eventArgs) at Microsoft.Maui.Controls.Handlers.ShellSectionHandler.SyncNavigationStack(Boolean animated, NavigationRequestedEventArgs e) at Microsoft.Maui.Controls.Handlers.ShellSectionHandler.OnNavigationRequested(Object sender, NavigationRequestedEventArgs e) at Microsoft.Maui.Controls.ShellSection.InvokeNavigationRequest(NavigationRequestedEventArgs args) at Microsoft.Maui.Controls.ShellSection.d__86.MoveNext()
at Microsoft.Maui.Controls.ShellSection.d__70.MoveNext()
at Microsoft.Maui.Dispatching.DispatcherExtensions.<>c__DisplayClass3_0.<b__0>d.MoveNext() at Microsoft.Maui.Dispatching.DispatcherExtensions.<>c__DisplayClass2_0`1.<b__0>d.MoveNext() at Microsoft.Maui.Controls.ShellNavigationManager.d__14.MoveNext() at MauiClient.Pages.DetailPage.<Back_Clicked>d__1.MoveNext() in C:\Projects\MauiClient\MauiClient\Pages\DetailPage.xaml.cs:line 16
```

**Comment by PureWeen** [comment]
There's definitely a bug here where `Shell` should handle this better but I think what's causing your issue is that `OnAppearing` is firing when you navigate back, which fires reload, which fires selection changed, which fires "GotoAsync" while it's going back. 

<img width="682" alt="image" src="https://user-images.githubusercontent.com/5375137/205466126-dd9312d2-8363-45e5-a865-5e39c70dcfd4.png">


If you clear the selection before navigating it all works fine

<img width="555" alt="image" src="https://user-images.githubusercontent.com/5375137/205466215-6d4e28c0-9948-4827-9987-002efb7b5011.png">

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 1.0. Repro on Windows 11 with provided Project:
[MauiClient-main.zip](https://github.com/dotnet/maui/files/11633551/MauiClient-main.zip)

![image](https://github.com/dotnet/maui/assets/97647558/9f20a716-63c7-4dd7-8fcc-64a8c8b83410)

**Comment by BagavathiPerumal** [comment]
This issue has been verified in Visual Studio 17.14.9 preview 1.0 with .NET MAUI version 9.0.110. It can be reproduced on the Windows platform.

https://github.com/user-attachments/assets/d3713463-4a46-43c5-b40a-d09aa3d61c36

**Comment by SuthiYuvaraj** [comment]
Hi @mauler2025, In the reported scenario, navigation from MasterPage → DetailPage using **SelectionChanged** keeps the item selected. When returning to MasterPage, the selection is restored, which retriggers SelectionChanged and causes the **"Pending Navigations still processing"** exception since navigation is still in progress. We can overcome this issue by clearing the selection after navigation to avoid re-triggering.

```
 private async void OnSelectionChanged(object sender, SelectionChangedEventArgs e)
{
    Debug.WriteLine(nameof(OnSelectionChanged));
  if (e.CurrentSelection.Count != 0)
  {

    var navparam = new Dictionary<string, object?>
    {
      [nameof(Monkey)] = e.CurrentSelection.FirstOrDefault() as Monkey
    };

    if (sender is CollectionView collectionView)
      collectionView.SelectedItem = null;

    await Shell.Current.GoToAsync(nameof(DetailPage), navparam);
  }
}
```
