### ISSUE TITLE
 App.Current.Resources.MergedDictionaries.Add Unavailable switch the second time

### ISSUE THREAD

**Issue by fanhai** [dotnet/maui#11334]
### Description

![image](https://user-images.githubusercontent.com/9838830/201603589-b2c51a2f-b85c-480c-96e4-2a44d8698904.png)
![image](https://user-images.githubusercontent.com/9838830/201603684-cbc6435d-b82b-4734-aaaf-07a577eeb38c.png)

### Steps to Reproduce

1. click switch
1. click switch

### Link to public reproduction project repository

null

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

net7.0-windows10.0.19041.0

**Comment by fanhai** [comment]
at Microsoft.Maui.Controls.VisualElement.OnParentResourcesChanged(IEnumerable`1 values) in D:\a\_work\1\s\src\Controls\src\Core\VisualElement.cs:line 1051
   at Microsoft.Maui.Controls.Element.OnParentResourcesChanged(Object sender, ResourcesChangedEventArgs e) in D:\a\_work\1\s\src\Controls\src\Core\Element.cs:line 437
   at Microsoft.Maui.Controls.Element.OnResourcesChanged(IEnumerable`1 values) in D:\a\_work\1\s\src\Controls\src\Core\Element.cs:line 500
   at Microsoft.Maui.Controls.Element.OnParentResourcesChanged(IEnumerable`1 values) in D:\a\_work\1\s\src\Controls\src\Core\Element.cs:line 442
   at Microsoft.Maui.Controls.VisualElement.OnParentResourcesChanged(IEnumerable`1 values) in D:\a\_work\1\s\src\Controls\src\Core\VisualElement.cs:line 1039
   at Microsoft.Maui.Controls.Element.OnParentResourcesChanged(Object sender, ResourcesChangedEventArgs e) in D:\a\_work\1\s\src\Controls\src\Core\Element.cs:line 437
   at Microsoft.Maui.Controls.Element.OnResourcesChanged(IEnumerable`1 values) in D:\a\_work\1\s\src\Controls\src\Core\Element.cs:line 500
   at Microsoft.Maui.Controls.Element.OnParentResourcesChanged(IEnumerable`1 values) in D:\a\_work\1\s\src\Controls\src\Core\Element.cs:line 442
   at Microsoft.Maui.Controls.Element.OnParentResourcesChanged(Object sender, ResourcesChangedEventArgs e) in D:\a\_work\1\s\src\Controls\src\Core\Element.cs:line 437
   at Microsoft.Maui.Controls.Element.OnResourcesChanged(IEnumerable`1 values) in D:\a\_work\1\s\src\Controls\src\Core\Element.cs:line 500
   at Microsoft.Maui.Controls.Element.OnResourcesChanged(Object sender, ResourcesChangedEventArgs e) in D:\a\_work\1\s\src\Controls\src\Core\Element.cs:line 459
   at Microsoft.Maui.Controls.ResourceDictionary.OnValuesChanged(KeyValuePair`2[] values) in D:\a\_work\1\s\src\Controls\src\Core\ResourceDictionary.cs:line 342
   at Microsoft.Maui.Controls.ResourceDictionary.MergedDictionaries_CollectionChanged(Object sender, NotifyCollectionChangedEventArgs e) in D:\a\_work\1\s\src\Controls\src\Core\ResourceDictionary.cs:line 109
   at System.Collections.ObjectModel.ObservableCollection`1[[Microsoft.Maui.Controls.ResourceDictionary, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1[[Microsoft.Maui.Controls.ResourceDictionary, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnCollectionChanged(NotifyCollectionChangedAction action, Object item, Int32 index)
   at System.Collections.ObjectModel.ObservableCollection`1[[Microsoft.Maui.Controls.ResourceDictionary, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].InsertItem(Int32 index, ResourceDictionary item)
   at System.Collections.ObjectModel.Collection`1[[Microsoft.Maui.Controls.ResourceDictionary, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].Add(ResourceDictionary item)
   at Maons.Languages.SwitchLan(String lang) in C:\Users\fanhai\go\src\github.com\asmbio\Maons\MauiApp3\Languages.cs:line 50
   at Maons.my.Mysetup.Picker_SelectedIndexChanged(Object sender, EventArgs e) in C:\Users\fanhai\go\src\github.com\asmbio\Maons\MauiApp3\my\Mysetup.xaml.cs:line 30
   at Microsoft.Maui.Controls.Picker.OnSelectedIndexChanged(Object bindable, Object oldValue, Object newValue) in D:\a\_work\1\s\src\Controls\src\Core\Picker.cs:line 327
   at Microsoft.Maui.Controls.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, Boolean silent) in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 535
   at Microsoft.Maui.Controls.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes) in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 469
   at Microsoft.Maui.Controls.BindableObject.SetValue(BindableProperty property, Object value, Boolean fromStyle, Boolean checkAccess) in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 391
   at Microsoft.Maui.Controls.BindableObject.SetValue(BindableProperty property, Object value) in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 365
   at Microsoft.Maui.Controls.Picker.set_SelectedIndex(Int32 value) in D:\a\_work\1\s\src\Controls\src\Core\Picker.cs:line 146
   at Microsoft.Maui.Handlers.PickerHandler.<OnClick>b__16_1(Object s, DialogClickEventArgs e) in D:\a\_work\1\s\src\Core\src\Handlers\Picker\PickerHandler.Android.cs:line 138
   at Android.Content.IDialogInterfaceOnClickListenerImplementor.OnClick(IDialogInterface dialog, Int32 which) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net7.0/android-33/mcw/Android.Content.IDialogInterface.cs:line 251
   at Android.Content.IDialogInterfaceOnClickListenerInvoker.n_OnClick_Landroid_content_DialogInterface_I(IntPtr jnienv, IntPtr native__this, IntPtr native_dialog, Int32 which) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net7.0/android-33/mcw/Android.Content.IDialogInterface.cs:line 203
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPLI_V(_JniMarshal_PPLI_V callback, IntPtr jnienv, IntPtr klazz, IntPtr p0, Int32 p1) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 165

**Comment by fanhai** [comment]
https://github.com/asmbio/Maons.git

MauiApp1 and MauiApp3 are used for testing. You can uninstall others

![image](https://user-images.githubusercontent.com/9838830/201813793-e0d6a8a3-5aae-4a72-8ed8-810a4adcf1e9.png)

MauiApp3: Error will be reported when switching
MauiApp1: No error will be reported when switching, but the switching is invalid
Key code location: Title="{StaticResource switchlan}"

**Comment by fanhai** [comment]
MauiApp3: Step

![image](https://user-images.githubusercontent.com/9838830/201814707-ddaf0be0-7795-4b80-a5ad-1e18c06fe6e2.png)

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio 17.7.0 Preview 1.0. Can repro on windows platform with sample project.
[Maons-main.zip](https://github.com/dotnet/maui/files/11620224/Maons-main.zip)
MauiApp1:
![Mauiapp1](https://github.com/dotnet/maui/assets/77434865/f0d5cff7-cab8-4b22-9a15-02892842b603)
MauiApp3:
![Mauiapp3](https://github.com/dotnet/maui/assets/77434865/ef8d2bf4-35e8-4fd3-bb3d-75620735e9f9)

**Comment by czezor** [comment]
I have the same error on Android in .Net 8 and VS 17.8.1
