### ISSUE TITLE
Grid.RowSpan="0" throws exception in release mode, but not debug mode

### ISSUE THREAD

**Issue by pekspro** [dotnet/maui#11486]
### Description

If you have an element with the attribute `Grid.RowSpan="0"` an exception is thrown in release mode on Android, but not debug mode. This makes it very hard to detect and troubleshoot.

On WIndows the application will crash in debug mode if error is on the primary page. But it crashes only in release mode if the error occurs after navigation.

This is somewhat related: https://github.com/dotnet/maui/issues/6171

### Steps to Reproduce

1. Create new MAUI application.
2. Add this in MainPage.xaml:

``` XAML
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiIssues.MainPage">

    <VerticalStackLayout 
            Spacing="25" 
            Padding="30,0" 
            VerticalOptions="Center">

        <Button x:Name="CounterBtn"
                Text="Second page"
                Clicked="OnCounterClicked"
                HorizontalOptions="Center" />
    </VerticalStackLayout>

</ContentPage>
```

3. Add this in MainPage.xaml.cs:

``` C#
public partial class MainPage : ContentPage
{
	public MainPage()
	{
		InitializeComponent();
	}

	private async void OnCounterClicked(object sender, EventArgs e)
	{
        await Navigation.PushAsync(new SecondPage());
    }
}
```

4. Add SecondPage.xaml with this content:

``` XAML
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiIssues.SecondPage"
             Title="SecondPage">
    <Grid RowDefinitions="*, *">
        <Label Text="Ups!" Grid.RowSpan="0" />
    </Grid>
</ContentPage>
```

5. To save this, add this into .csproj:

``` XML
    <PropertyGroup>
        <PublishTrimmed>false</PublishTrimmed>
        <RunAOTCompilation>false</RunAOTCompilation>
    </PropertyGroup>
```
6. Run the application in debug mode. No exception will be thrown.
7. Run the application in release mode on Android and Windows. The application will crash.

### Link to public reproduction project repository

coming soon

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 11

### Did you find any workaround?

Use a valid RowSpan value :-)

### Relevant log output

```shell
System.ArgumentException: Value is an invalid value for RowSpan (Parameter 'value')
   at Microsoft.Maui.Controls.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes)
   at Microsoft.Maui.Controls.BindableObject.SetValue(BindableProperty property, Object value, Boolean fromStyle, Boolean checkAccess)
   at Microsoft.Maui.Controls.BindableObject.SetValue(BindableProperty property, Object value)
```

**Comment by jsuarezruiz** [comment]
What do you think @jonathanpeppers?

**Comment by jonathanpeppers** [comment]
The stack trace here is in MAUI, might not be an issue related to Android at all?

You could try this, but looks like something different: https://github.com/dotnet/maui/pull/11096

**Comment by mattleibow** [comment]
This might be an issue in the code that XamlC generates.

Can you try with `<_MauiForceXamlCForDebug>True</_MauiForceXamlCForDebug>` in your csproj?

**Comment by jinxinjuan** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 2.0. Can repro on Androiid platform with sample project.
[11486_Grid_RowSpan_0_throws_exception_in_release_mode](https://github.com/pekspro/MauiIssues/tree/11486_Grid_RowSpan_0_throws_exception_in_release_mode)

**Comment by jonathanpeppers** [comment]
In @jinxinjuan's sample I get a runtime exception in both Debug or Release mode. Both crash the app.

The stack trace is, of course, different if XamlC is enabled or not.

Debug (no XamlC):
```
System.ArgumentException: Value is an invalid value for RowSpan (Parameter 'value')
at Microsoft.Maui.Controls.Xaml.ApplyPropertiesVisitor.SetPropertyValue(Object xamlelement, XmlName propertyName, Object value, Object rootElement, INode node, HydrationContext context, IXmlLineInfo lineInfo)
at Microsoft.Maui.Controls.Xaml.ApplyPropertiesVisitor.Visit(ValueNode node, INode parentNode)
at Microsoft.Maui.Controls.Xaml.ValueNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
at Microsoft.Maui.Controls.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
at Microsoft.Maui.Controls.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
at Microsoft.Maui.Controls.Xaml.RootNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
at Microsoft.Maui.Controls.Xaml.XamlLoader.Visit(RootNode rootnode, HydrationContext visitorContext, Boolean useDesignProperties)
at Microsoft.Maui.Controls.Xaml.XamlLoader.Load(Object view, String xaml, Assembly rootAssembly, Boolean useDesignProperties)
at Microsoft.Maui.Controls.Xaml.XamlLoader.Load(Object view, String xaml, Boolean useDesignProperties)
at Microsoft.Maui.Controls.Xaml.XamlLoader.Load(Object view, Type callingType)
at Microsoft.Maui.Controls.Xaml.Extensions.LoadFromXaml[SecondPage](SecondPage view, Type callingType)
at MauiIssues.SecondPage.InitializeComponent()
at MauiIssues.SecondPage..ctor()
at MauiIssues.MainPage.OnCounterClicked(Object sender, EventArgs e)
at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
at Android.App.SyncContext.<>c__DisplayClass2_0.<Post>b__0()
at Java.Lang.Thread.RunnableImplementor.Run()
at Java.Lang.IRunnableInvoker.n_Run(IntPtr jnienv, IntPtr native__this)
at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(_JniMarshal_PP_V callback, IntPtr jnienv, IntPtr klazz)
at mono.java.lang.RunnableImplementor.n_run(Native Method)
at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:31)
at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7884)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

Release (XamlC):
```
System.ArgumentException: Value is an invalid value for RowSpan (Parameter 'value')
at Microsoft.Maui.Controls.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes)
at Microsoft.Maui.Controls.BindableObject.SetValue(BindableProperty property, Object value, Boolean fromStyle, Boolean checkAccess)
at Microsoft.Maui.Controls.BindableObject.SetValue(BindableProperty property, Object value)
at MauiIssues.SecondPage.InitializeComponent()
at MauiIssues.SecondPage..ctor()
at MauiIssues.MainPage.OnCounterClicked(Object sender, EventArgs e)
at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
at Android.App.SyncContext.<>c__DisplayClass2_0.<Post>b__0()
at Java.Lang.Thread.RunnableImplementor.Run()
at Java.Lang.IRunnableInvoker.n_Run(IntPtr jnienv, IntPtr native__this)
at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(_JniMarshal_PP_V callback, IntPtr jnienv, IntPtr klazz)
at mono.java.lang.RunnableImplementor.n_run(Native Method)
at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:31)
at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7884)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

I think what the OP is actually looking for here is a build-time error instead of runtime.

@mattleibow @StephaneDelcroix do we have a precedent for that? XamlC might already validate `Color` values, so if we had a way for it validate `int` values for certain properties?

**Comment by pekspro** [comment]
The demo project has been updated to .NET 10. Now it has the same behaviour on of debug and release mode, there is no crash.
