### ISSUE TITLE
MSAL missing_entitlements with local iPhone device

### ISSUE THREAD

**Issue by espenrl** [dotnet/maui#11536]
### Description

There is a problem regarding `Entitlements.plist` when deploying to a local device. There seems to be an issue with automatic provisioning for iOS, and probably also macOS.

- If I setup manual provisioning it all works fine. I configured manual provisioning using project settings in Visual Studio. It should be the same settings as with automatic provisioning.
- Except for the MSAL issue automatic provisioning works as it should. I can deploy and use the app. But I can't authenticate with Azure AD.

Please see log output for further details.

### Steps to Reproduce

It's not that easy to reproduce as one has to create an Azure AD authority. I've included a link to the sample code for MSAL with MAUI.

### Link to public reproduction project repository

https://github.com/Azure-Samples/active-directory-xamarin-native-v2/tree/main/MAUI/MauiAppB2C

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16, Visual Studio 2022 17.5.0 Preview 1.0

### Did you find any workaround?

Setup manual provisioning instead of automatic provisioning.

### Relevant log output

```shell
MSAL.Xamarin.iOS.4.48.1.0.MsalClientException: 
	ErrorCode: missing_entitlements
Microsoft.Identity.Client.MsalClientException: The application does not have keychain access groups enabled in the Entitlements.plist. As a result, there was a failure to save to the iOS keychain. The keychain access group '<redacted>.com.microsoft.adalcache' is not enabled in the Entitlements.plist. Also, use the WithIosKeychainSecurityGroup api to set the keychain access group. See https://aka.ms/msal-net-enable-keychain-groups for more details on enabling keychain access groups and entitlements.
   at Microsoft.Identity.Client.Platforms.iOS.iOSTokenCacheAccessor.Save(IiOSKey key, String payload)
   at Microsoft.Identity.Client.Platforms.iOS.iOSTokenCacheAccessor.SaveAccessToken(MsalAccessTokenCacheItem item)
   at Microsoft.Identity.Client.TokenCache.Microsoft.Identity.Client.ITokenCacheInternal.SaveTokenResponseAsync(AuthenticationRequestParameters requestParams, MsalTokenResponse response)
   at Microsoft.Identity.Client.TokenCache.Microsoft.Identity.Client.ITokenCacheInternal.SaveTokenResponseAsync(AuthenticationRequestParameters requestParams, MsalTokenResponse response)
   at Microsoft.Identity.Client.Cache.CacheSessionManager.SaveTokenResponseAsync(MsalTokenResponse tokenResponse)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.CacheTokenResponseAndCreateAuthenticationResultAsync(MsalTokenResponse msalTokenResponse)
   at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.ApiConfig.Executors.PublicClientExecutor.ExecuteAsync(AcquireTokenCommonParameters commonParameters, AcquireTokenInteractiveParameters interactiveParameters, CancellationToken cancellationToken)
```

**Comment by PureWeen** [comment]
@rolfbjarne @dalexsoto thoughts?

**Comment by rolfbjarne** [comment]
Codesigning/entitlement issues can sometimes be rather tricky to diagnose, because they sometimes depend on configuration in your Apple Developer account. So would it be possible to get two [binary build logs](https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#binary-build-logs): one for a working build (with manual provisioning) and one for a failing build (with automatic provisioning)? Thanks!

**Comment by espenrl** [comment]
In the end it was my bad. I had a typo in the filename of `Entitlements.plist`. When I renamed it to the expected default filename it was all good of course.
