### ISSUE TITLE
Resources/Images subfolder problem.

### ISSUE THREAD

**Issue by Qws** [dotnet/maui#11661]
### Description

I have an image in `Resources/Images/manga/`

To access this image in XAML or C#, I specify the filename and extension, so `"maria.png"` is enough for me. I don't need to specify the subfolder (manga). If I try to specify the subfolder (manga) the image disappears.

So, this doesn't work:
```
<Image
    Source="manga/maria.png"/>
```

This works:
```
<Image
    Source="maria.png" />
```
The problem is, what if I want to add another maria.png, in another subfolder.

How can I properly differentiate it if I can't specify the subfolder?

I actually tried having 2 MauiImages with the same name (maria.png) and both in different subfolders. But the app won't build and gives me an error (see: relevant log output).

### Steps to Reproduce

1. In project tree, inside the `Resources/Images` folder, create a new subfolder.
2. Insert an image in that subfolder.
3. Right click the image, click on `properties`.
4. Set the build action to `MauiImage`.
5. Add image control in Xaml page, set the source to newly added MauiImage.
6. Realize you cannot specify the folder. (And if you add another image with the same name in another subdirectory, it can't build.)

### Link to public reproduction project repository

https://github.com/Qws/ImageLoadingExampleMaui/tree/master/ImageLoadingExampleMaui

### Version with bug

6.0.486

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 11 21H2

### Did you find any workaround?

By not making subdirectories inside Resources/Images folder, because it serves no purpose from code point of view...

### Relevant log output

```shell
When I try to build project with 2 images in different subfolder with same name, it abort the build and gives me this error:

Severity	Code	Description	Project	File	Line	Suppression State
Error	MAUI0000	System.IO.IOException: The process cannot access the file 'C:\Users\qws\source\repos\ImageLoadingExampleMaui\ImageLoadingExampleMaui\obj\Debug\net6.0-windows10.0.19041.0\win10-x64\resizetizer\r\maria.scale-100.png' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at Microsoft.Maui.Resizetizer.Resizer.CopyFile(DpiPath dpi, String inputsFile) in D:\a\_work\1\s\src\SingleProject\Resizetizer\src\Resizer.cs:line 53
   at Microsoft.Maui.Resizetizer.ResizetizeImages.ProcessImageCopy(ResizeImageInfo img, DpiPath originalScaleDpi, ConcurrentBag`1 resizedImages) in D:\a\_work\1\s\src\SingleProject\Resizetizer\src\ResizetizeImages.cs:line 197
   at Microsoft.Maui.Resizetizer.ResizetizeImages.<>c__DisplayClass26_0.<ExecuteAsync>b__0(ResizeImageInfo img) in D:\a\_work\1\s\src\SingleProject\Resizetizer\src\ResizetizeImages.cs:line 86
   at Microsoft.Maui.Resizetizer.AsyncTaskExtensions.<>c__DisplayClass0_0`1.<ParallelForEach>b__0(TSource s) in D:\a\_work\1\s\src\SingleProject\Resizetizer\src\AsyncTaskExtensions.cs:line 21	ImageLoadingExampleMaui	C:\Program Files\dotnet\packs\Microsoft.Maui.Resizetizer.Sdk\6.0.541\targets\Microsoft.Maui.Resizetizer.targets	531
```

**Comment by mattleibow** [comment]
This is unfortunately a limitation of some platforms - namely Android.

Android only supports a flat list and their recommendation is to use "merged names": `folder_subfolder_image.svg`


> Alternative resource directories cannot be nested. For example, you cannot have res/drawable/drawable-en/.
> https://developer.android.com/guide/topics/resources/providing-resources#QualifierRules
