### ISSUE TITLE
java.lang.SecurityException when using share on Android

### ISSUE THREAD

**Issue by rogerbriggen** [dotnet/maui#11683]
### Description

If I use 
````
await Share.Default.RequestAsync(new ShareFileRequest
        {
            Title = title,
            File = new ShareFile(file)
        });
````
on Android 11, it works but I have
[DatabaseUtils] Writing exception to parcel
[DatabaseUtils] java.lang.SecurityException: Permission Denial: reading microsoft.maui.essentials.fileProvider uri content://ch.xxx.xxx.Dev.fileProvider/external_cache/2203693cc04e0be7f4f024d5f9499e13/72acc14fbadb44d080599064d47b561a/xxx_log_Dev_20221127.txt from pid=17846, uid=1000 requires the provider be exported, or grantUriPermission()
[DatabaseUtils] 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:841)
[DatabaseUtils] 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:703)
[DatabaseUtils] 	at android.content.ContentProvider$Transport.query(ContentProvider.java:242)
[DatabaseUtils] 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:107)
[DatabaseUtils] 	at android.os.Binder.execTransactInternal(Binder.java:1221)
[DatabaseUtils] 	at android.os.Binder.execTransact(Binder.java:1163)
in the log

### Steps to Reproduce

1. Create a Maui Android app
2. Create a button and add the following code:
await Share.Default.RequestAsync(new ShareFileRequest
        {
            Title = title,
            File = new ShareFile(file)
        });

### Link to public reproduction project repository

-

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11 on a real phone

### Did you find any workaround?

-

### Relevant log output

```shell
[DatabaseUtils] Writing exception to parcel
[DatabaseUtils] java.lang.SecurityException: Permission Denial: reading microsoft.maui.essentials.fileProvider uri content://ch.securiton.SecuriSmokeGoApp.Dev.fileProvider/external_cache/2203693cc04e0be7f4f024d5f9499e13/72acc14fbadb44d080599064d47b561a/goapp_log_Dev_20221127.txt from pid=17846, uid=1000 requires the provider be exported, or grantUriPermission()
[DatabaseUtils] 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:841)
[DatabaseUtils] 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:703)
[DatabaseUtils] 	at android.content.ContentProvider$Transport.query(ContentProvider.java:242)
[DatabaseUtils] 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:107)
[DatabaseUtils] 	at android.os.Binder.execTransactInternal(Binder.java:1221)
[DatabaseUtils] 	at android.os.Binder.execTransact(Binder.java:1163)
```

**Comment by petermauger** [comment]
I've been able to utilise sharing for files in Android. I'm using:
```
await Share.RequestAsync(...)
```
instead of 
```
await Share.Default.RequestAsync(...)
```
Maybe give that a try? Otherwise try out some different locations to try and share the file from. I think mine are being successful from the internal cache folders for some reason (`FileSystem.CacheDirectory`)

**Comment by petermauger** [comment]
Oh, and while I'm here, `Browser.OpenUri()` has the same issue (security exception->crash). Workaround for that for anyone that stumbles here is:
```
    private string _url;
    public WebPage()
    {
        InitializeComponent();
        webView.HandlerChanged += WebView_HandlerChanged;
    }

    private void WebView_HandlerChanged(object sender, EventArgs e)
    {
        EnableAndroidFileView();
        // Only set the source once the handler is configured
        webView.Source = new UrlWebViewSource() { Url = _url };
    }

    private bool EnableAndroidFileView()
    {
#if ANDROID
        var handler = webView.Handler;
        var platformView = handler?.PlatformView;
        if (platformView is Android.Webkit.WebView aWebView && aWebView.Settings.AllowFileAccess == false)
        {
            aWebView.Settings.AllowFileAccess = true;
            aWebView.Settings.AllowFileAccessFromFileURLs = true;
            return true;
        }
#endif
        return false;
    }
```

**Comment by bulletis** [comment]
> I've been able to utilise sharing for files in Android. I'm using:
> 
> ```
> await Share.RequestAsync(...)
> ```
> 
> instead of
> 
> ```
> await Share.Default.RequestAsync(...)
> ```
> 
> Maybe give that a try? Otherwise try out some different locations to try and share the file from. I think mine are being successful from the internal cache folders for some reason (`FileSystem.CacheDirectory`)

Not work for me. I have tried to share file from internal folder and external folder.
