### ISSUE TITLE
[Scenario Days 02 Dec] Crash navigating between Shell tabs

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#11820]
### Description

Crash navigating between Shell tabs.

`Unable to activate instance of type Microsoft.Maui.Controls.Platform.Compatibility.ShellSearchViewAdapter+CustomFilter from native handle 0x7fff3399d7a8 (key_handle 0x7e97264).`

### Steps to Reproduce

1. Download or sync https://github.com/jsuarezruiz/scenariodays-120222/tree/main/src/ScenarioDays.Sample2
2. Launch the App on Android.
3. Change between tabs.

### Link to public reproduction project repository

https://github.com/jsuarezruiz/scenariodays-120222/tree/main/src/ScenarioDays.Sample2

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 13

### Relevant log output

```shell
at Java.Interop.TypeManager.CreateInstance(IntPtr handle, JniHandleOwnership transfer, Type targetType) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Java.Interop/TypeManager.cs:line 319
   at Java.Lang.Object.GetObject(IntPtr handle, JniHandleOwnership transfer, Type type) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Java.Lang/Object.cs:line 304
   at Java.Lang.Object._GetObject[Filter](IntPtr handle, JniHandleOwnership transfer) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Java.Lang/Object.cs:line 290
   at Java.Lang.Object.GetObject[Filter](IntPtr handle, JniHandleOwnership transfer) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Java.Lang/Object.cs:line 281
   at Java.Lang.Object.GetObject[Filter](IntPtr jnienv, IntPtr handle, JniHandleOwnership transfer) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Java.Lang/Object.cs:line 275
   at Android.Widget.Filter.n_PublishResults_Ljava_lang_CharSequence_Landroid_widget_Filter_FilterResults_(IntPtr jnienv, IntPtr native__this, IntPtr native_constraint, IntPtr native_results) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net7.0/android-33/mcw/Android.Widget.Filter.cs:line 414
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPLL_V(_JniMarshal_PPLL_V callback, IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 187
```

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with 17.6 Preview (17.6 build 1539). Not repro on android with sample project.
[scenariodays.zip](https://github.com/dotnet/maui/files/11632915/scenariodays.zip)
![11820](https://github.com/dotnet/maui/assets/77434865/34912e40-e646-4869-8d61-4f9dd8f175db)
