### ISSUE TITLE
Navigation to ContentView results in NullReferenceException

### ISSUE THREAD

**Issue by bakerhillpins** [dotnet/maui#11836]
### Description

There are no protections on what you register as a transient in MAUI as long as it's a class. So it's possible to mistakenly create your UI inside a `Microsoft.Maui.Controls.ContentView` rather than a `Microsoft.Maui.Controls.ContentPage`, register those "Views" and routes and try to navigate to it.  

It's one of those really simple mistakes that's created by simply choosing the wrong XAML template in the IDE.

![image](https://user-images.githubusercontent.com/5980709/205388992-9d4db2b6-eaf1-4863-b91f-b7a0225b33fe.png)

The result is a NullReferenceException in the `ShellNavigationManager`

```
   at Microsoft.Maui.Controls.ShellNavigationManager.ApplyQueryAttributes(Element element, ShellRouteParameters query, Boolean isLastItem, Boolean isPopping)
   at Microsoft.Maui.Controls.ShellSection.GetOrCreateFromRoute(String route, ShellRouteParameters queryData, IServiceProvider services, Boolean isLast, Boolean isPopping)
   at Microsoft.Maui.Controls.ShellSection.<GoToAsync>d__74.MoveNext()
   at Microsoft.Maui.Controls.ShellNavigationManager.<GoToAsync>d__14.MoveNext()
   at MauiBugz.ViewModels.MainPageViewModel.<OnBugPressed>d__7.MoveNext() in D:\Repos\Dumpster\Issues\Maui\MauiBugz\MauiBugz\ViewModels\MainPageViewModel.cs:line 28
```

To my knowledge this isn't supported, however, it would be nice to fail more gracefully as this was actually quite a head scratcher for a while. 

### Steps to Reproduce

1. Clone Repo,
2. Select the Windows runtime as this actually provides access to the exception call stack.
3. Click on the "Issue XXX" button and it will crash.

### Link to public reproduction project repository

s

### Version with bug

6.0 Release Candidate 2 or older

### Last version that worked well

6.0 Release Candidate 2 or older

### Affected platforms

iOS, Android, Windows, macOS, Other (Tizen, Linux, etc. not supported by Microsoft directly)

### Affected platform versions

All

### Did you find any workaround?

There really shouldn't be a workaround, but the system should fail more gracefully.

### Relevant log output

```shell
at Microsoft.Maui.Controls.ShellNavigationManager.ApplyQueryAttributes(Element element, ShellRouteParameters query, Boolean isLastItem, Boolean isPopping)
   at Microsoft.Maui.Controls.ShellSection.GetOrCreateFromRoute(String route, ShellRouteParameters queryData, IServiceProvider services, Boolean isLast, Boolean isPopping)
   at Microsoft.Maui.Controls.ShellSection.<GoToAsync>d__74.MoveNext()
   at Microsoft.Maui.Controls.ShellNavigationManager.<GoToAsync>d__14.MoveNext()
   at MauiBugz.ViewModels.MainPageViewModel.<OnBugPressed>d__7.MoveNext() in D:\Repos\Dumpster\Issues\Maui\MauiBugz\MauiBugz\ViewModels\MainPageViewModel.cs:line 28
```

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio 17.7.0 Preview 1.0. Can repro with sample project.
[Issues-NetMauiIssue11836.zip](https://github.com/dotnet/maui/files/11648176/Issues-NetMauiIssue11836.zip)
![11836 A](https://github.com/dotnet/maui/assets/77434865/b953773b-73a6-452a-b89b-8d3bf50f4d55)
![11836](https://github.com/dotnet/maui/assets/77434865/75281092-f05e-4695-8693-a7adcd0e1376)
