### ISSUE TITLE
Android Release mode build doesn't work

### ISSUE THREAD

**Issue by XamerDev** [dotnet/maui#11901]
### Description

Hello, after upgrade to the newest version I'm unable to build android app in release mode. I can't publish repo of this app, what can I do now? 

Build fails with errors:

`Błąd	NETSDK1144	Optymalizacja zestawów pod kątem rozmiaru nie powiodła się. Optymalizacja może zostać wyłączona przez ustawienie właściwości PublishTrimmed na wartość false.	DA	C:\Program Files\dotnet\sdk\7.0.100\Sdks\Microsoft.NET.ILLink.Tasks\build\Microsoft.NET.ILLink.targets	86	`

and:

`Błąd	IL1011	Failed to write 'obj\Release\net7.0-android\android-x86\linked\SkiaSharp.Views.Android.dll'.	DA	C:\Users\**\source\repos\DA\ILLink	1	`

### Steps to Reproduce

1. Build app in release mode

### Link to public reproduction project repository

I cant publish this repo

### Version with bug

7.0 (current)

### Last version that worked well

6.0.424

### Affected platforms

Android

### Affected platform versions

Android all

### Relevant log output

```
1>ILLink : error IL1011: Failed to write 'obj\Release\net7.0-android\android-arm64\linked\SkiaSharp.Views.Android.dll'.
1>Fatal error in IL Linker
1>Unhandled exception. Mono.Linker.LinkerFatalErrorException: ILLink: error IL1011: Failed to write 'obj\Release\net7.0-android\android-arm64\linked\SkiaSharp.Views.Android.dll'.
1> ---> System.ArgumentException: Member 'System.Int32 SKCanvasView_ignorePixelScaling' is declared in another module and needs to be imported
1>   at Mono.Cecil.MetadataBuilder.LookupToken(IMetadataTokenProvider provider)
1>   at Mono.Cecil.Cil.CodeWriter.WriteOperand(Instruction instruction)
1>   at Mono.Cecil.Cil.CodeWriter.WriteInstructions()
1>   at Mono.Cecil.Cil.CodeWriter.WriteResolvedMethodBody(MethodDefinition method)
1>   at Mono.Cecil.Cil.CodeWriter.WriteMethodBody(MethodDefinition method)
1>   at Mono.Cecil.MetadataBuilder.AddMethod(MethodDefinition method)
1>   at Mono.Cecil.MetadataBuilder.AddMethods(TypeDefinition type)
1>   at Mono.Cecil.MetadataBuilder.AddType(TypeDefinition type)
1>   at Mono.Cecil.MetadataBuilder.AddTypes()
1>   at Mono.Cecil.MetadataBuilder.BuildTypes()
1>   at Mono.Cecil.MetadataBuilder.BuildModule()
1>   at Mono.Cecil.MetadataBuilder.BuildMetadata()
1>   at Mono.Cecil.ModuleWriter.<>c.<BuildMetadata>b__2_0(MetadataBuilder builder, MetadataReader _)
1>   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read)
1>   at Mono.Cecil.ModuleWriter.BuildMetadata(ModuleDefinition module, MetadataBuilder metadata)
1>   at Mono.Cecil.ModuleWriter.Write(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
1>   at Mono.Cecil.ModuleWriter.WriteModule(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
1>   at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)
1>   at Mono.Cecil.AssemblyDefinition.Write(String fileName, WriterParameters parameters)
1>   at Mono.Linker.Steps.OutputStep.WriteAssembly(AssemblyDefinition assembly, String directory, WriterParameters writerParameters)
1>   --- End of inner exception stack trace ---
1>   at Mono.Linker.Steps.OutputStep.WriteAssembly(AssemblyDefinition assembly, String directory, WriterParameters writerParameters)
1>   at Mono.Linker.Steps.OutputStep.WriteAssembly(AssemblyDefinition assembly, String directory)
1>   at Mono.Linker.Steps.OutputStep.OutputAssembly(AssemblyDefinition assembly)
1>   at Mono.Linker.Steps.OutputStep.ProcessAssembly(AssemblyDefinition assembly)
1>   at Mono.Linker.Steps.BaseStep.Process(LinkContext context)
1>   at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
1>   at Mono.Linker.Pipeline.Process(LinkContext context)
1>   at Mono.Linker.Driver.Run(ILogger customLogger)
1>   at Mono.Linker.Driver.Main(String[] args)
```

**Comment by BenBtg** [comment]
I'm working with a customer experiencing this same issue. Looking for a solution/workaround.

**Comment by mattleibow** [comment]
I also just did a release build of this in my sample project:
1. File | New | Maui app
2. Add SkiaSharp
3. Add a canvas view to the UI
4. Run as Release on my emulator

At this point, I need a repro or a binlog at least. 

Can you reproduce this in a new maui template app?

**Comment by mattleibow** [comment]
I also just realized I am running with the latest internal bits of the `7.0.101` SDK and runtime. @jonathanpeppers  when did the fix/optimization get turned on by default? Any known issues?

**Comment by jonathanpeppers** [comment]
It was turned off right after GA shipped and we discovered issues:

https://github.com/dotnet/maui/pull/11096

**Comment by mattleibow** [comment]
Unable to reproduce with 7.0.101: https://github.com/mattleibow/maui-bug-repros/tree/repro-11901

**Comment by mattleibow** [comment]
Unable to reproduce with 7.0.100 and a global.json:

```json
{
  "sdk": {
    "version": "7.0.100"
  }
}
```

**Comment by mattleibow** [comment]
We need a repro project because I can't reproduce the issue. What happens if you build my repository I linked to?  https://github.com/mattleibow/maui-bug-repros/tree/repro-11901

Can you try the CLI? (see repo readme)

**Comment by mattleibow** [comment]
Also, try adding `<AndroidLinkResources>false</AndroidLinkResources>` to your project and see if that changes anything.

**Comment by XamerDev** [comment]
I added this and now it works
thanks @mattleibow

**Comment by XamerDev** [comment]
hmm I have some problem with running app on device after succesfull build (release mode).
can somebody check it too? I have some different configuration for release/debug modes and I'm not quite sure if it is my fault or maui
App immediately close after splashscreen. Without any errors :/

**Comment by mattleibow** [comment]
> I added this and now it works thanks


Were you able to test with my sample? https://github.com/mattleibow/maui-bug-repros/tree/repro-11901

I was not able to reproduce any errors.

Also, please open an new issue for this one and provide the information in the bug template:

> I have some problem with running app on device after succesfull build

**Comment by XamerDev** [comment]
@mattleibow  I just downloaded your repo and the same problem occurs

```
1>ILLink : error IL1011: Failed to write 'obj\Release\net7.0-android\android-x64\linked\SkiaSharp.Views.Android.dll'.
1>Fatal error in IL Linker
1>Unhandled exception. Mono.Linker.LinkerFatalErrorException: ILLink: error IL1011: Failed to write 'obj\Release\net7.0-android\android-x64\linked\SkiaSharp.Views.Android.dll'.
1> ---> System.ArgumentException: Member 'System.Int32 SKCanvasView_ignorePixelScaling' is declared in another module and needs to be imported
1>   at Mono.Cecil.MetadataBuilder.LookupToken(IMetadataTokenProvider provider)
1>   at Mono.Cecil.Cil.CodeWriter.WriteOperand(Instruction instruction)
1>   at Mono.Cecil.Cil.CodeWriter.WriteInstructions()
1>   at Mono.Cecil.Cil.CodeWriter.WriteResolvedMethodBody(MethodDefinition method)
1>   at Mono.Cecil.Cil.CodeWriter.WriteMethodBody(MethodDefinition method)
1>   at Mono.Cecil.MetadataBuilder.AddMethod(MethodDefinition method)
1>   at Mono.Cecil.MetadataBuilder.AddMethods(TypeDefinition type)
1>   at Mono.Cecil.MetadataBuilder.AddType(TypeDefinition type)
1>   at Mono.Cecil.MetadataBuilder.AddTypes()
1>   at Mono.Cecil.MetadataBuilder.BuildTypes()
1>   at Mono.Cecil.MetadataBuilder.BuildModule()
1>   at Mono.Cecil.MetadataBuilder.BuildMetadata()
1>   at Mono.Cecil.ModuleWriter.<>c.<BuildMetadata>b__2_0(MetadataBuilder builder, MetadataReader _)
1>   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read)
1>   at Mono.Cecil.ModuleWriter.BuildMetadata(ModuleDefinition module, MetadataBuilder metadata)
1>   at Mono.Cecil.ModuleWriter.Write(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
1>   at Mono.Cecil.ModuleWriter.WriteModule(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
1>   at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)
1>   at Mono.Cecil.AssemblyDefinition.Write(String fileName, WriterParameters parameters)
1>   at Mono.Linker.Steps.OutputStep.WriteAssembly(AssemblyDefinition assembly, String directory, WriterParameters writerParameters)
1>   --- End of inner exception stack trace ---
1>   at Mono.Linker.Steps.OutputStep.WriteAssembly(AssemblyDefinition assembly, String directory, WriterParameters writerParameters)
1>   at Mono.Linker.Steps.OutputStep.WriteAssembly(AssemblyDefinition assembly, String directory)
1>   at Mono.Linker.Steps.OutputStep.OutputAssembly(AssemblyDefinition assembly)
1>   at Mono.Linker.Steps.OutputStep.ProcessAssembly(AssemblyDefinition assembly)
1>   at Mono.Linker.Steps.BaseStep.Process(LinkContext context)
1>   at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
1>   at Mono.Linker.Pipeline.Process(LinkContext context)
1>   at Mono.Linker.Driver.Run(ILogger customLogger)
1>   at Mono.Linker.Driver.Main(String[] args)
1>C:\Program Files\dotnet\sdk\7.0.100\Sdks\Microsoft.NET.ILLink.Tasks\build\Microsoft.NET.ILLink.targets(86,5): error NETSDK1144: Optymalizacja zestawów pod kątem rozmiaru nie powiodła się. Optymalizacja może zostać wyłączona przez ustawienie właściwości PublishTrimmed na wartość false.
1>Kompilowanie projektu „MauiAppli.csproj” wykonane — NIEPOWODZENIE.
1>ILLink : error IL1011: Failed to write 'obj\Release\net7.0-android\android-arm\linked\SkiaSharp.Views.Android.dll'.
1>Fatal error in IL Linker
1>Unhandled exception. Mono.Linker.LinkerFatalErrorException: ILLink: error IL1011: Failed to write 'obj\Release\net7.0-android\android-arm\linked\SkiaSharp.Views.Android.dll'.
1> ---> System.ArgumentException: Member 'System.Int32 SKCanvasView_ignorePixelScaling' is declared in another module and needs to be imported
1>   at Mono.Cecil.MetadataBuilder.LookupToken(IMetadataTokenProvider provider)
1>   at Mono.Cecil.Cil.CodeWriter.WriteOperand(Instruction instruction)
1>   at Mono.Cecil.Cil.CodeWriter.WriteInstructions()
1>   at Mono.Cecil.Cil.CodeWriter.WriteResolvedMethodBody(MethodDefinition method)
1>   at Mono.Cecil.Cil.CodeWriter.WriteMethodBody(MethodDefinition method)
1>   at Mono.Cecil.MetadataBuilder.AddMethod(MethodDefinition method)
1>   at Mono.Cecil.MetadataBuilder.AddMethods(TypeDefinition type)
1>   at Mono.Cecil.MetadataBuilder.AddType(TypeDefinition type)
1>   at Mono.Cecil.MetadataBuilder.AddTypes()
1>   at Mono.Cecil.MetadataBuilder.BuildTypes()
1>   at Mono.Cecil.MetadataBuilder.BuildModule()
1>   at Mono.Cecil.MetadataBuilder.BuildMetadata()
1>   at Mono.Cecil.ModuleWriter.<>c.<BuildMetadata>b__2_0(MetadataBuilder builder, MetadataReader _)
1>   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read)
1>   at Mono.Cecil.ModuleWriter.BuildMetadata(ModuleDefinition module, MetadataBuilder metadata)
1>   at Mono.Cecil.ModuleWriter.Write(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
1>   at Mono.Cecil.ModuleWriter.WriteModule(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
1>   at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)
1>   at Mono.Cecil.AssemblyDefinition.Write(String fileName, WriterParameters parameters)
1>   at Mono.Linker.Steps.OutputStep.WriteAssembly(AssemblyDefinition assembly, String directory, WriterParameters writerParameters)
1>   --- End of inner exception stack trace ---
1>   at Mono.Linker.Steps.OutputStep.WriteAssembly(AssemblyDefinition assembly, String directory, WriterParameters writerParameters)
1>   at Mono.Linker.Steps.OutputStep.WriteAssembly(AssemblyDefinition assembly, String directory)
1>   at Mono.Linker.Steps.OutputStep.OutputAssembly(AssemblyDefinition assembly)
1>   at Mono.Linker.Steps.OutputStep.ProcessAssembly(AssemblyDefinition assembly)
1>   at Mono.Linker.Steps.BaseStep.Process(LinkContext context)
1>   at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
1>   at Mono.Linker.Pipeline.Process(LinkContext context)
1>   at Mono.Linker.Driver.Run(ILogger customLogger)
1>   at Mono.Linker.Driver.Main(String[] args)
1>ILLink : error IL1011: Failed to write 'obj\Release\net7.0-android\android-arm64\linked\SkiaSharp.Views.Android.dll'.
1>Fatal error in IL Linker
1>Unhandled exception. Mono.Linker.LinkerFatalErrorException: ILLink: error IL1011: Failed to write 'obj\Release\net7.0-android\android-arm64\linked\SkiaSharp.Views.Android.dll'.
1> ---> System.ArgumentException: Member 'System.Int32 SKCanvasView_ignorePixelScaling' is declared in another module and needs to be imported
1>   at Mono.Cecil.MetadataBuilder.LookupToken(IMetadataTokenProvider provider)
1>   at Mono.Cecil.Cil.CodeWriter.WriteOperand(Instruction instruction)
1>   at Mono.Cecil.Cil.CodeWriter.WriteInstructions()
1>   at Mono.Cecil.Cil.CodeWriter.WriteResolvedMethodBody(MethodDefinition method)
1>   at Mono.Cecil.Cil.CodeWriter.WriteMethodBody(MethodDefinition method)
1>   at Mono.Cecil.MetadataBuilder.AddMethod(MethodDefinition method)
1>   at Mono.Cecil.MetadataBuilder.AddMethods(TypeDefinition type)
1>   at Mono.Cecil.MetadataBuilder.AddType(TypeDefinition type)
1>   at Mono.Cecil.MetadataBuilder.AddTypes()
1>   at Mono.Cecil.MetadataBuilder.BuildTypes()
1>   at Mono.Cecil.MetadataBuilder.BuildModule()
1>   at Mono.Cecil.MetadataBuilder.BuildMetadata()
1>   at Mono.Cecil.ModuleWriter.<>c.<BuildMetadata>b__2_0(MetadataBuilder builder, MetadataReader _)
1>   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read)
1>   at Mono.Cecil.ModuleWriter.BuildMetadata(ModuleDefinition module, MetadataBuilder metadata)
1>   at Mono.Cecil.ModuleWriter.Write(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
1>   at Mono.Cecil.ModuleWriter.WriteModule(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
1>   at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)
1>   at Mono.Cecil.AssemblyDefinition.Write(String fileName, WriterParameters parameters)
1>   at Mono.Linker.Steps.OutputStep.WriteAssembly(AssemblyDefinition assembly, String directory, WriterParameters writerParameters)
1>   --- End of inner exception stack trace ---
1>   at Mono.Linker.Steps.OutputStep.WriteAssembly(AssemblyDefinition assembly, String directory, WriterParameters writerParameters)
1>   at Mono.Linker.Steps.OutputStep.WriteAssembly(AssemblyDefinition assembly, String directory)
1>   at Mono.Linker.Steps.OutputStep.OutputAssembly(AssemblyDefinition assembly)
1>   at Mono.Linker.Steps.OutputStep.ProcessAssembly(AssemblyDefinition assembly)
1>   at Mono.Linker.Steps.BaseStep.Process(LinkContext context)
1>   at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
1>   at Mono.Linker.Pipeline.Process(LinkContext context)
1>   at Mono.Linker.Driver.Run(ILogger customLogger)
1>   at Mono.Linker.Driver.Main(String[] args)
1>C:\Program Files\dotnet\sdk\7.0.100\Sdks\Microsoft.NET.ILLink.Tasks\build\Microsoft.NET.ILLink.targets(86,5): error NETSDK1144: Optymalizacja zestawów pod kątem rozmiaru nie powiodła się. Optymalizacja może zostać wyłączona przez ustawienie właściwości PublishTrimmed na wartość false.
1>Kompilowanie projektu „MauiAppli.csproj” wykonane — NIEPOWODZENIE.
1>ILLink : error IL1011: Failed to write 'obj\Release\net7.0-android\android-x86\linked\SkiaSharp.Views.Android.dll'.
1>Fatal error in IL Linker
1>Unhandled exception. Mono.Linker.LinkerFatalErrorException: ILLink: error IL1011: Failed to write 'obj\Release\net7.0-android\android-x86\linked\SkiaSharp.Views.Android.dll'.
1> ---> System.ArgumentException: Member 'System.Int32 SKCanvasView_ignorePixelScaling' is declared in another module and needs to be imported
1>   at Mono.Cecil.MetadataBuilder.LookupToken(IMetadataTokenProvider provider)
1>   at Mono.Cecil.Cil.CodeWriter.WriteOperand(Instruction instruction)
1>   at Mono.Cecil.Cil.CodeWriter.WriteInstructions()
1>   at Mono.Cecil.Cil.CodeWriter.WriteResolvedMethodBody(MethodDefinition method)
1>   at Mono.Cecil.Cil.CodeWriter.WriteMethodBody(MethodDefinition method)
1>   at Mono.Cecil.MetadataBuilder.AddMethod(MethodDefinition method)
1>   at Mono.Cecil.MetadataBuilder.AddMethods(TypeDefinition type)
1>   at Mono.Cecil.MetadataBuilder.AddType(TypeDefinition type)
1>   at Mono.Cecil.MetadataBuilder.AddTypes()
1>   at Mono.Cecil.MetadataBuilder.BuildTypes()
1>   at Mono.Cecil.MetadataBuilder.BuildModule()
1>   at Mono.Cecil.MetadataBuilder.BuildMetadata()
1>   at Mono.Cecil.ModuleWriter.<>c.<BuildMetadata>b__2_0(MetadataBuilder builder, MetadataReader _)
1>   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read)
1>   at Mono.Cecil.ModuleWriter.BuildMetadata(ModuleDefinition module, MetadataBuilder metadata)
1>   at Mono.Cecil.ModuleWriter.Write(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
1>   at Mono.Cecil.ModuleWriter.WriteModule(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
1>   at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)
1>   at Mono.Cecil.AssemblyDefinition.Write(String fileName, WriterParameters parameters)
1>   at Mono.Linker.Steps.OutputStep.WriteAssembly(AssemblyDefinition assembly, String directory, WriterParameters writerParameters)
1>   --- End of inner exception stack trace ---
1>   at Mono.Linker.Steps.OutputStep.WriteAssembly(AssemblyDefinition assembly, String directory, WriterParameters writerParameters)
1>   at Mono.Linker.Steps.OutputStep.WriteAssembly(AssemblyDefinition assembly, String directory)
1>   at Mono.Linker.Steps.OutputStep.OutputAssembly(AssemblyDefinition assembly)
1>   at Mono.Linker.Steps.OutputStep.ProcessAssembly(AssemblyDefinition assembly)
1>   at Mono.Linker.Steps.BaseStep.Process(LinkContext context)
1>   at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
1>   at Mono.Linker.Pipeline.Process(LinkContext context)
1>   at Mono.Linker.Driver.Run(ILogger customLogger)
1>   at Mono.Linker.Driver.Main(String[] args)
1>C:\Program Files\dotnet\sdk\7.0.100\Sdks\Microsoft.NET.ILLink.Tasks\build\Microsoft.NET.ILLink.targets(86,5): error NETSDK1144: Optymalizacja zestawów pod kątem rozmiaru nie powiodła się. Optymalizacja może zostać wyłączona przez ustawienie właściwości PublishTrimmed na wartość false.
1>Kompilowanie projektu „MauiAppli.csproj” wykonane — NIEPOWODZENIE.
1>C:\Program Files\dotnet\sdk\7.0.100\Sdks\Microsoft.NET.ILLink.Tasks\build\Microsoft.NET.ILLink.targets(86,5): error NETSDK1144: Optymalizacja zestawów pod kątem rozmiaru nie powiodła się. Optymalizacja może zostać wyłączona przez ustawienie właściwości PublishTrimmed na wartość false.
1>Kompilowanie projektu „MauiAppli.csproj” wykonane — NIEPOWODZENIE.
1>Kompilowanie projektu „MauiAppli.csproj” wykonane — NIEPOWODZENIE.
```

**Comment by mattleibow** [comment]
Can you clean the directory and run a build from the command line and attach the binlog? Or attach it if you have it still. I want to compare things and see why you have an error and I do not.

**Comment by XamerDev** [comment]
hope it's a proper file 
[msbuild.zip](https://github.com/dotnet/maui/files/10186531/msbuild.zip)

**Comment by janseris** [comment]
Try PublishTrimmed false XML tag in csproj

**Comment by mattleibow** [comment]
This should fix it:

```
<AndroidLinkResources>false</AndroidLinkResources>
```

**Comment by mattleibow** [comment]
OK, based on some further testing and checking binlogs, we have confirmed it was the new linker step that was added in GA. This was disabled for the upcoming service release in https://github.com/dotnet/maui/pull/11096 as a result of https://github.com/dotnet/maui/issues/11069.

The solution for now is to use this in your csproj:

```xml
<AndroidLinkResources>false</AndroidLinkResources>
```

The next servicing release of .NET MAUI will have this disabled already.

**Comment by BenBtg** [comment]
Just a small point to add to this. A customer I'm working with found that the above solution only worked after they also removed 
```<TrimMode>copyused</TrimMode>```

Not sure why that would be, but thought I should add for completeness.

**Comment by bradencohen** [comment]
> OK, based on some further testing and checking binlogs, we have confirmed it was the new linker step that was added in GA. This was disabled for the upcoming service release in #11096 as a result of #11069.
> 
> The solution for now is to use this in your csproj:
> 
> ```
> <AndroidLinkResources>false</AndroidLinkResources>
> ```
> 
> The next servicing release of .NET MAUI will have this disabled already.

Will this always need to be disabled? It makes the building process take 5x the time it used to.

**Comment by janseris** [comment]
> The next servicing release of .NET MAUI will have this disabled already.

Does it mean that instead of fixing, the problem will be hidden?

**Comment by mattleibow** [comment]
> Just a small point to add to this. A customer I'm working with found that the above solution only worked after they also removed 
> ```<TrimMode>copyused</TrimMode>```
> 
> Not sure why that would be, but thought I should add for completeness.

I believe this option is invalid or broken in .net 7 and should not be used.

**Comment by mattleibow** [comment]
> Does it mean that instead of fixing, the problem will be hidden?
> 

Yes and no. In net 7 we were trying a new optimization and our testing seemed to work. However we apparently missed something so disabled it. This is a brand new feature of net7 so it will not be worse than net6. 

For Net8 we rewrote this entirely in a brand new way that we don't even need this code.
