### ISSUE TITLE
Maui Resizetizer Error - Unable to allocate pixels for the bitmap when using an SVG image

### ISSUE THREAD

**Issue by RNSR23** [dotnet/maui#12109]
### Description

We are trying to add in an SVG image into our maui app. When I try to add this image into the project and run the build, the following error appears "Unable to allocate pixels for the bitmap" and the build fails. The build continues to fail until the image is removed and the bin/obj folders have been deleted. When troubleshooting, I replaced the .net bot with this image in a new maui app to isolate the issue and was able to recreate it. The image is a standard SVG from what we can see so not sure why this is occurring. The image is referenced in XAML as PNG as instructed. 

I have attached a copy of the image. It is a orange warning triangle. I have found a workaround which is to add the image into the maui app as a PNG image. It works fine however there is a downside to the image not being scalable.

![warning](https://user-images.githubusercontent.com/120584650/207650084-839b7f9c-930e-4d2d-b14d-4fe3b6e54a8d.svg)

### Steps to Reproduce

1. Create new maui project in visual studio 2022.
2. Drag and drop SVG image into the Resources/Images folder
3. Inside the Main Page XAML, replace the Image source to new image: Source="warning.png"
4. Save file and run build on Android Emulator.
5. Build fails.

### Link to public reproduction project repository

https://github.com/RNSR23/TestIconApp.git

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

Pixel 5 - API33 Android 13.0 Emulator

### Did you find any workaround?

Yes, the workaround is to use the same image in PNG format rather than SVG. It works fine however there is a downside to the image not being scalable.

### Relevant log output

```shell
Severity	Code	Description	Project	File	Line	Suppression State
Error	MAUI0000	System.Exception: Unable to allocate pixels for the bitmap.
   at SkiaSharp.SKBitmap..ctor(SKImageInfo info, Int32 rowBytes) in D:\a\1\s\binding\Binding\SKBitmap.cs:line 86
   at Microsoft.Maui.Resizetizer.SkiaSharpTools.Resize(DpiPath dpi, String destination, Double additionalScale, Boolean dpiSizeIsAbsolute) in D:\a\_work\1\s\src\SingleProject\Resizetizer\src\SkiaSharpTools.cs:line 61
   at Microsoft.Maui.Resizetizer.Resizer.Rasterize(DpiPath dpi, String destination) in D:\a\_work\1\s\src\SingleProject\Resizetizer\src\Resizer.cs:line 92
   at Microsoft.Maui.Resizetizer.Resizer.Resize(DpiPath dpi, String inputsFile) in D:\a\_work\1\s\src\SingleProject\Resizetizer\src\Resizer.cs:line 85
   at Microsoft.Maui.Resizetizer.ResizetizeImages.ProcessImageResize(ResizeImageInfo img, DpiPath[] dpis, ConcurrentBag`1 resizedImages) in D:\a\_work\1\s\src\SingleProject\Resizetizer\src\ResizetizeImages.cs:line 184
   at Microsoft.Maui.Resizetizer.ResizetizeImages.<>c__DisplayClass26_0.<ExecuteAsync>b__0(ResizeImageInfo img) in D:\a\_work\1\s\src\SingleProject\Resizetizer\src\ResizetizeImages.cs:line 86
   at Microsoft.Maui.Resizetizer.AsyncTaskExtensions.<>c__DisplayClass0_0`1.<ParallelForEach>b__0(TSource s) in D:\a\_work\1\s\src\SingleProject\Resizetizer\src\AsyncTaskExtensions.cs:line 21	TestIconApp	C:\Program Files\dotnet\packs\Microsoft.Maui.Resizetizer.Sdk\7.0.49\targets\Microsoft.Maui.Resizetizer.targets	531
```

**Comment by jsuarezruiz** [comment]
Could you attach a small sample to see how did you include the SVG etc?

**Comment by RNSR23** [comment]
Created a sample project,  link added to the **Link to public reproduction project repository** section above

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 1.0. Repro on Windows 11 and Android 13.0-API33 with below Project:
[TestIconApp.zip](https://github.com/dotnet/maui/files/11730073/TestIconApp.zip)

![image](https://github.com/dotnet/maui/assets/97647558/4bc3d01e-504f-4fc9-b7c6-f14be7b1e4de)

**Comment by moljac** [comment]
Repro sample (net7.0 and net8.0):

[TestIconApp-net7.0-net8.0.zip](https://github.com/dotnet/maui/files/12332858/TestIconApp-net7.0-net8.0.zip)

**Comment by Xilmirius** [comment]
I'm having the same problem with a "icons.svg" which contains FontAwesome sprites icons

**Comment by Xilmirius** [comment]
Yes sure! Here is the original file
![solid](https://github.com/dotnet/maui/assets/42950845/274176a3-f6c5-4bd4-96e3-532fa5defa4f)

and here is the doc to implement them
https://fontawesome.com/docs/web/add-icons/svg-sprites
