### ISSUE TITLE
App crashes on startup when R8 shrinker is set in Maui - Release mode

### ISSUE THREAD

**Issue by Banurega** [dotnet/maui#12330]
### Description

Application crashes in startup when I set the  **R8 shrinker in release mode and use the secure storage** in application.

android.runtime.JavaProxyThrowable: System.AggregateException: AggregateException_ctor_DefaultMessage (no "Landroidx/security/crypto/EncryptedSharedPreferences$PrefKeyEncryptionScheme;" field "AES256_SIV" in class "Landroidx/security/crypto/EncryptedSharedPreferences$PrefKeyEncryptionScheme;" or its superclasses)
 ---> Java.Lang.Error: no "Landroidx/security/crypto/EncryptedSharedPreferences$PrefKeyEncryptionScheme;" field "AES256_SIV" in class "Landroidx/security/crypto/EncryptedSharedPreferences$PrefKeyEncryptionScheme;" or its superclasses
   at Java.Interop.JniEnvironment.StaticFields.GetStaticFieldID(JniObjectReference , String , String )
   at Java.Interop.JniType.GetStaticField(String , String )
   at Java.Interop.JniPeerMembers.JniStaticFields.GetFieldInfo(String )
   at Java.Interop.JniPeerMembers.JniStaticFields.GetObjectValue(String )
   at AndroidX.Security.Crypto.EncryptedSharedPreferences.PrefKeyEncryptionScheme.get_Aes256Siv()
   at Microsoft.Maui.Storage.SecureStorageImplementation.GetEncryptedSharedPreferences()
   at Microsoft.Maui.Storage.SecureStorageImplementation.<>c__DisplayClass6_0.<PlatformGetAsync>b__0()
   at System.Threading.Tasks.Task`1[[System.String, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__273_0(Object )

### Steps to Reproduce

1.Create a Maui app for net7.0-android/net6.0-android.
2.Enable R8 for Release configuration.
3.Set sample values in secure storage in App.xaml.cs file
3.Build the app for Release configuration.
4.Check the device log
[MauiApp2.zip](https://github.com/dotnet/maui/files/10318204/MauiApp2.zip)
[Logcat.txt](https://github.com/dotnet/maui/files/10318205/Logcat.txt)

### Link to public reproduction project repository

https://github.com/Banurega/MauiSampleApp

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11 and up, VS2022

**Comment by sgjesse** [comment]
Most likely you need additional keep rules for the crypto code. Take a look at https://developer.android.com/studio/build/shrink-code (that is for Android Studio, but the same applies for any Java code).

**Comment by rachelkang** [comment]
Let us know if the advice here helps:

https://github.com/dotnet/runtime/issues/79910#issuecomment-1363180624
