### ISSUE TITLE
Getting Java.IO.FileNotFoundException on calling httpClient.PostAsync in MAUI app - Android

### ISSUE THREAD

**Issue by amittapelly11** [dotnet/maui#12391]
### Description

I'm getting the below exception when trying to call httpclient.PostAsync. 
The API will return the user defined exception which we can able to caught in Xamarin Forms app but not in MAUI app
where we have migrated from Xamarin Forms app to MAUI app.

{System.Net.WebException: **Requested Url**
 ---> Java.IO.FileNotFoundException: **Requested Url**
   at Java.Interop.JniEnvironment.InstanceMethods.CallObjectMethod(JniObjectReference instance, JniMethodInfo method, JniArgumentValue* args) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniEnvironment.g.cs:line 11524
   at Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualObjectMethod(String encodedMember, IJavaPeerable self, JniArgumentValue* parameters) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:line 389
   at Java.Net.URLConnection.get_InputStream() in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net6.0/android-31/mcw/Java.Net.URLConnection.cs:line 743
   at Xamarin.Android.Net.AndroidMessageHandler.DoProcessRequest(HttpRequestMessage request, URL javaUrl, HttpURLConnection httpConnection, CancellationToken cancellationToken, RequestRedirectionState redirectState) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Xamarin.Android.Net/AndroidMessageHandler.cs:line 560
   at Xamarin.Android.Net.AndroidMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Xamarin.Android.Net/AndroidMessageHandler.cs:line 375
  --- End of managed Java.IO.FileNotFoundException stack trace ---
java.io.FileNotFoundException: **Requested Url**
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:255)

  --- End of managed Java.IO.FileNotFoundException stack trace ---
java.io.FileNotFoundException: **Requested Url**
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:255)

   --- End of inner exception stack trace ---
   at Xamarin.Android.Net.AndroidMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Xamarin.Android.Net/AndroidMessageHandler.cs:line 389
   at SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)

### Steps to Reproduce

This is the code we are using to Post to API

 protected async Task<TResp> PostFunc<TArgs, TResp>(string uriString, TArgs args)
        {
            var uri = new Uri(_baseAddress + uriString);
            var jsonreq = JsonConvert.SerializeObject(args);
            var reqContent = new StringContent(jsonreq, Encoding.UTF8, "application/json");

            try
            {
                var response = await _client.PostAsync(uri, reqContent);
                if (response.IsSuccessStatusCode)
                {
                    var respContent = await response.Content.ReadAsStringAsync();

                    return JsonConvert.DeserializeObject<TResp>(respContent);
                }
                else
                    throw ExceptionFromErrorResponse(response);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

### Link to public reproduction project repository

No 

### Version with bug

6.0.486

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11 and up

**Comment by vhugogarcia** [comment]
@amittapelly11  Could you please upgrade your project to use .NET 7 `<TargetFrameworks>net7.0-android</TargetFrameworks>` ?

And also make sure to install the updated MAUI workloads:
<img width="503" alt="image" src="https://user-images.githubusercontent.com/1047398/210387636-466592f0-1dd7-48df-8e98-0d69443036ca.png">

I'm using basically the same code in my project and I don't have any issues using HttpClient.PostAsync in Android or iOS, the only difference is that I'm using .NET 7 and .NET MAUI workloads up to date.

Let us know the results

**Comment by vhugogarcia** [comment]
> @vhugogarcia, I have tried with .net 7 still getting same issue. With .net 6, the implementation working with iOS but not working with Android.

@amittapelly11 if you could provide a repository where you could reproduce the issue would be great! please
