### ISSUE TITLE
MoveToRegion exception

### ISSUE THREAD

**Issue by johmau85** [dotnet/maui#12527]
### Description

MoveToRegion exception occurs when navigating from a CollectionView to a Page with Map control using TapGestureRecognizer.

Issue doesn't occur if navigation is triggered by SelectedItem unless a custom selection style is added.

### Exception occurs
(main branch in reproduction repository. Please add your Google API KEY)

CollectionView XAML:
```xaml
<CollectionView ItemsSource="{Binding Cities}"
                SelectionMode="None">
    <CollectionView.ItemTemplate>
        <DataTemplate x:DataType="models:City">
            <Frame Margin="5"
                   Padding="5">
                <Frame.GestureRecognizers>
                    <TapGestureRecognizer Command="{Binding Source={RelativeSource AncestorType={x:Type viewmodels:MainPageViewModel}}, Path=GoToDetailsCommand}"
                                          CommandParameter="{Binding .}"/>
                </Frame.GestureRecognizers>
                <Grid ColumnDefinitions="*,2*"
                      RowDefinitions="3*,2*,2*">
                    <Label Grid.Row="0"
                            Grid.ColumnSpan="2"
                            Text="{Binding Name}"
                            FontSize="Medium"/>
                    <Label Grid.Row="1"
                            Grid.Column="0"
                            Text="Latitude:"/>
                    <Label Grid.Row="1"
                            Grid.Column="1"
                            Text="{Binding Latitude}"/>
                    <Label Grid.Row="2"
                            Grid.Column="0"
                            Text="Longitude:"/>
                    <Label Grid.Row="2"
                            Grid.Column="1"
                            Text="{Binding Longitude}"/>
                </Grid>
            </Frame>
        </DataTemplate>
    </CollectionView.ItemTemplate>
</CollectionView>
```

Navigation command:
```dotnet
[RelayCommand]
private async Task GoToDetails(City city)
{
    if (city == null)
        return;

    await Shell.Current.GoToAsync(nameof(MapPage), true, new Dictionary<string, object>
    {
        {"City", city }
    });
}
```

Map Page:
```xaml
<maps:Map x:Name="Map"/>
```

Exception:
```bash
Microsoft.Maui.Maps.Handlers.MapHandler: Warning: MoveToRegion exception

Java.Lang.IllegalStateException: Error using newLatLngBounds(LatLngBounds, int): Map size can't be 0. Most likely, layout has not yet occured for the map view.  Either wait until layout has occurred or use newLatLngBounds(LatLngBounds, int, int, int) which allows you to specify the map's dimensions.
   at Java.Interop.JniEnvironment.InstanceMethods.CallNonvirtualVoidMethod(JniObjectReference instance, JniObjectReference type, JniMethodInfo method, JniArgumentValue* args) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/obj/Release/net7.0/JniEnvironment.g.cs:line 12324
   at Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeNonvirtualVoidMethod(String encodedMember, IJavaPeerable self, JniArgumentValue* parameters) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:line 93
   at Android.Gms.Maps.GoogleMap.MoveCamera(CameraUpdate update) in /Users/runner/work/1/s/generated/com.google.android.gms.play-services-maps/obj/Release/net6.0-android31.0/generated/src/Android.Gms.Maps.GoogleMap.cs:line 3881
   at Microsoft.Maui.Maps.Handlers.MapHandler.MoveToRegion(MapSpan span, Boolean animate) in D:\a\_work\1\s\src\Core\maps\src\Handlers\Map\MapHandler.Android.cs:line 362
  --- End of managed Java.Lang.IllegalStateException stack trace ---
com.google.maps.api.android.lib6.common.apiexception.c: Error using newLatLngBounds(LatLngBounds, int): Map size can't be 0. Most likely, layout has not yet occured for the map view.  Either wait until layout has occurred or use newLatLngBounds(LatLngBounds, int, int, int) which allows you to specify the map's dimensions.
	at com.google.maps.api.android.lib6.common.m.b(:com.google.android.gms.dynamite_mapsdynamite@201817048@20.18.17 (040400-0):6)
	at com.google.maps.api.android.lib6.gmm6.api.c.a(:com.google.android.gms.dynamite_mapsdynamite@201817048@20.18.17 (040400-0):36)
	at com.google.maps.api.android.lib6.impl.y.a(:com.google.android.gms.dynamite_mapsdynamite@201817048@20.18.17 (040400-0):0)
	at com.google.maps.api.android.lib6.gmm6.api.c.a(:com.google.android.gms.dynamite_mapsdynamite@201817048@20.18.17 (040400-0):47)
	at com.google.maps.api.android.lib6.impl.bi.a(:com.google.android.gms.dynamite_mapsdynamite@201817048@20.18.17 (040400-0):250)
	at com.google.android.gms.maps.internal.i.a(:com.google.android.gms.dynamite_mapsdynamite@201817048@20.18.17 (040400-0):174)
	at cy.onTransact(:com.google.android.gms.dynamite_mapsdynamite@201817048@20.18.17 (040400-0):4)
	at android.os.Binder.transact(Binder.java:1043)
	at com.google.android.gms.internal.maps.zza.zzc(com.google.android.gms:play-services-maps@@18.1.0:2)
	at com.google.android.gms.maps.internal.zzg.moveCamera(com.google.android.gms:play-services-maps@@18.1.0:3)
	at com.google.android.gms.maps.GoogleMap.moveCamera(com.google.android.gms:play-services-maps@@18.1.0:2)
	at crc64a5df8ade113ad624.MapCallbackHandler.n_onMapReady(Native Method)
	at crc64a5df8ade113ad624.MapCallbackHandler.onMapReady(MapCallbackHandler.java:41)
	at com.google.android.gms.maps.zzaf.zzb(com.google.android.gms:play-services-maps@@18.1.0:1)
	at com.google.android.gms.maps.internal.zzar.zza(com.google.android.gms:play-services-maps@@18.1.0:6)
	at com.google.android.gms.internal.maps.zzb.onTransact(com.google.android.gms:play-services-maps@@18.1.0:3)
	at android.os.Binder.transact(Binder.java:1043)
	at cx.b(:com.google.android.gms.dynamite_mapsdynamite@201817048@20.18.17 (040400-0):2)
	at com.google.maps.api.android.lib6.impl.be.run(:com.google.android.gms.dynamite_mapsdynamite@201817048@20.18.17 (040400-0):2)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

  --- End of managed Java.Lang.IllegalStateException stack trace ---
com.google.maps.api.android.lib6.common.apiexception.c: Error using newLatLngBounds(LatLngBounds, int): Map size can't be 0. Most likely, layout has not yet occured for the map view.  Either wait until layout has occurred or use newLatLngBounds(LatLngBounds, int, int, int) which allows you to specify the map's dimensions.
	at com.google.maps.api.android.lib6.common.m.b(:com.google.android.gms.dynamite_mapsdynamite@201817048@20.18.17 (040400-0):6)
	at com.google.maps.api.android.lib6.gmm6.api.c.a(:com.google.android.gms.dynamite_mapsdynamite@201817048@20.18.17 (040400-0):36)
	at com.google.maps.api.android.lib6.impl.y.a(:com.google.android.gms.dynamite_mapsdynamite@201817048@20.18.17 (040400-0):0)
	at com.google.maps.api.android.lib6.gmm6.api.c.a(:com.google.android.gms.dynamite_mapsdynamite@201817048@20.18.17 (040400-0):47)
	at com.google.maps.api.android.lib6.impl.bi.a(:com.google.android.gms.dynamite_mapsdynamite@201817048@20.18.17 (040400-0):250)
	at com.google.android.gms.maps.internal.i.a(:com.google.android.gms.dynamite_mapsdynamite@201817048@20.18.17 (040400-0):174)
	at cy.onTransact(:com.google.android.gms.dynamite_mapsdynamite@201817048@20.18.17 (040400-0):4)
	at android.os.Binder.transact(Binder.java:1043)
	at com.google.android.gms.internal.maps.zza.zzc(com.google.android.gms:play-services-maps@@18.1.0:2)
	at com.google.android.gms.maps.internal.zzg.moveCamera(com.google.android.gms:play-services-maps@@18.1.0:3)
	at com.google.android.gms.maps.GoogleMap.moveCamera(com.google.android.gms:play-services-maps@@18.1.0:2)
	at crc64a5df8ade113ad624.MapCallbackHandler.n_onMapReady(Native Method)
	at crc64a5df8ade113ad624.MapCallbackHandler.onMapReady(MapCallbackHandler.java:41)
	at com.google.android.gms.maps.zzaf.zzb(com.google.android.gms:play-services-maps@@18.1.0:1)
	at com.google.android.gms.maps.internal.zzar.zza(com.google.android.gms:play-services-maps@@18.1.0:6)
	at com.google.android.gms.internal.maps.zzb.onTransact(com.google.android.gms:play-services-maps@@18.1.0:3)
	at android.os.Binder.transact(Binder.java:1043)
	at cx.b(:com.google.android.gms.dynamite_mapsdynamite@201817048@20.18.17 (040400-0):2)
	at com.google.maps.api.android.lib6.impl.be.run(:com.google.android.gms.dynamite_mapsdynamite@201817048@20.18.17 (040400-0):2)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

### No exception occurs
(working branch in reproduction repository. Please add your Google API KEY)

CollectionView XAML:
```xaml
            <CollectionView ItemsSource="{Binding Cities}"
                            SelectionMode="Single"
                            SelectedItem="{Binding SelectedCity}">
                <CollectionView.ItemTemplate>
                    <DataTemplate x:DataType="models:City">
                        <Border Margin="5"
                               Padding="5">
                            <!--Frame.GestureRecognizers>
                                <TapGestureRecognizer Command="{Binding Source={RelativeSource AncestorType={x:Type viewmodels:MainPageViewModel}}, Path=GoToDetailsCommand}"
                                                      CommandParameter="{Binding .}"/>
                            </Frame.GestureRecognizers-->
                            <Grid ColumnDefinitions="*,2*"
                                  RowDefinitions="3*,2*,2*">
                                <Label Grid.Row="0"
                                        Grid.ColumnSpan="2"
                                        Text="{Binding Name}"
                                        FontSize="Medium"/>
                                <Label Grid.Row="1"
                                        Grid.Column="0"
                                        Text="Latitude:"/>
                                <Label Grid.Row="1"
                                        Grid.Column="1"
                                        Text="{Binding Latitude}"/>
                                <Label Grid.Row="2"
                                        Grid.Column="0"
                                        Text="Longitude:"/>
                                <Label Grid.Row="2"
                                        Grid.Column="1"
                                        Text="{Binding Longitude}"/>
                            </Grid>
                        </Border>
                    </DataTemplate>
                </CollectionView.ItemTemplate>
            </CollectionView>
```

ViewModel source code:
```dotnet
    [ObservableProperty]
    private City selectedCity = null;

    async partial void OnSelectedCityChanged(City value)
    {
        await GoToDetails(value);
        SelectedCity = null;
    }


    [RelayCommand]
    private async Task GoToDetails(City city)
    {
        if (city == null)
            return;

        await Shell.Current.GoToAsync(nameof(MapPage), true, new Dictionary<string, object>
        {
            {"City", city }
        });
    }
```

### Exception occurs again if setter is added.

CollectionView XAML:
```xaml
<ContentPage.Resources>
    <Style TargetType="Border">
        <Setter Property="VisualStateManager.VisualStateGroups">
            <VisualStateGroupList>
                <VisualStateGroup x:Name="CommonStates">
                    <VisualState x:Name="Normal" />
                    <VisualState x:Name="Selected">
                        <VisualState.Setters>
                            <Setter Property="BackgroundColor"
                                    Value="LightSkyBlue" />
                        </VisualState.Setters>
                    </VisualState>
                </VisualStateGroup>
            </VisualStateGroupList>
        </Setter>
    </Style>
</ContentPage.Resources>
<RefreshView Command="{Binding GetCitiesCommand}"
             IsRefreshing="{Binding IsRefreshing}">
    <ContentView>
        <CollectionView ItemsSource="{Binding Cities}"
                        SelectionMode="Single"
                        SelectedItem="{Binding SelectedCity}">
            <CollectionView.ItemTemplate>
                <DataTemplate x:DataType="models:City">
                    <Border Margin="5"
                           Padding="5">
                        <!--Frame.GestureRecognizers>
                            <TapGestureRecognizer Command="{Binding Source={RelativeSource AncestorType={x:Type viewmodels:MainPageViewModel}}, Path=GoToDetailsCommand}"
                                                  CommandParameter="{Binding .}"/>
                        </Frame.GestureRecognizers-->
                        <Grid ColumnDefinitions="*,2*"
                              RowDefinitions="3*,2*,2*">
                            <Label Grid.Row="0"
                                    Grid.ColumnSpan="2"
                                    Text="{Binding Name}"
                                    FontSize="Medium"/>
                            <Label Grid.Row="1"
                                    Grid.Column="0"
                                    Text="Latitude:"/>
                            <Label Grid.Row="1"
                                    Grid.Column="1"
                                    Text="{Binding Latitude}"/>
                            <Label Grid.Row="2"
                                    Grid.Column="0"
                                    Text="Longitude:"/>
                            <Label Grid.Row="2"
                                    Grid.Column="1"
                                    Text="{Binding Longitude}"/>
                        </Grid>
                    </Border>
                </DataTemplate>
            </CollectionView.ItemTemplate>
        </CollectionView>
    </ContentView>
</RefreshView>
```

### Steps to Reproduce

1. Create a page with a CollectionView
2. Use a TapGestureRecognizer to initiate navigation to a Page containing a Map control.
3. The NavigationCommand will lead to "Microsoft.Maui.Maps.Handlers.MapHandler: Warning: MoveToRegion exception" 

### Link to public reproduction project repository

https://github.com/johmau85/MoveToRegionException.git

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 2.0. Repro on Android 13.0-API33 with below Project:
[MoveToRegionException.zip](https://github.com/dotnet/maui/files/11754575/MoveToRegionException.zip)

**Comment by cdavidyoung** [comment]
@johmau85, thanks for reporting this.  I have been having the same problem on Android and it causes the screen to be blank when I navigate to this page.  To be clear, I don't have a TapGestureRecognizer on the Map itself but rather on an image and buttons.

**Comment by cdavidyoung** [comment]
@johmau85, I have a little more information that might be helpful.  In my case, in addition to this exception, the screen comes up blank.  To be specific, when I navigate to the screen that has the Map it comes up blank and this exception appears in the Output.

Now, it does not always come up blank.  The first time I navigate to this page the screen comes up normally (including the Map) and there is no exception.  I can return and then navigate again to this page and it will again come up normally.  However, if while on this page I do some stuff involving pushing buttons (TapGestureRecognizer) and then return and navigate to the page again, the screen will come up blank.  I can recover from this by rotating the screen.  Then everything works fine until I execute another TapGestureRecognizer on the affected page.

**Comment by js0867** [comment]
The same issue can be replicated simply by having the map control in a page that is navigated to via shell navigation as follow (repro steps):

1. Create blank MAUI app (I used .net 8) in VS Code
2. Add MAUI Map Control nuget package & setup Manifest.xml for Google Map API Key & permission (following this [direction](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/map?view=net-maui-8.0).
3. Add 3 ContentPages into the project (PageOne.xaml, PageTwo.xaml, MapPage.xaml)
4. Add PageOne.xaml and PageTwo.xaml as TabBar ShellContent inside AppShell.xaml
```

 <?xml version="1.0" encoding="UTF-8" ?>
<Shell
    x:Class="MauiApp1.AppShell"
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:local="clr-namespace:MauiApp1"
    Shell.FlyoutBehavior="Disabled"
    Title="MauiApp1">

    <ShellContent
        Title="Home"
        ContentTemplate="{DataTemplate local:MainPage}"
        Route="MainPage" />

    <TabBar>
        <Tab Title="Other">
            <ShellContent Title="One" ContentTemplate="{DataTemplate local:PageOne}" Route="one" />
        </Tab>
        <Tab Title="Another">
            <ShellContent Title="Two" ContentTemplate="{DataTemplate local:PageTwo}" Route="two" />
        </Tab>
    </TabBar>
</Shell>
```

One PageOne.xaml, add a button:
```
<?xml version="1.0" encoding="utf-8" ?>

<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiApp1.PageOne"
             Title="AnotherPage">

    <StackLayout>
        <Button Text="Go To Map"
                VerticalOptions="Center"
                HorizontalOptions="Center"
                Clicked="OnButtonClicked" />
    </StackLayout>
</ContentPage>
```


PageOne.xaml.cs:
```
async void OnButtonClicked(object sender, EventArgs args)
    {
        await Shell.Current.GoToAsync("mappage");
    }
```

MapPage.xaml:
```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:maps="clr-namespace:Microsoft.Maui.Controls.Maps;assembly=Microsoft.Maui.Controls.Maps"
             x:Class="MauiApp1.MapPage"
             Title="MapPage">
    <VerticalStackLayout >
        <maps:Map MapType="Street" />
    </VerticalStackLayout>
</ContentPage>
```

Run in debug mode, which will show MainPage.xaml. Then click "One" on the bottom tab-bar, which will show PageOne with the button. Clicking the button will navigate to MapPage. When MapPage shows, you can see the debug log showing the error as below.

[0:] Microsoft.Maui.Maps.Handlers.MapHandler: Warning: MoveToRegion exception

Java.Lang.IllegalStateException: Error using newLatLngBounds(LatLngBounds, int): Map size can't be 0. Most likely, layout has not yet occurred for the map view.  Either wait until layout has occurred or use newLatLngBounds(LatLngBounds, int, int, int) which allows you to specify the map's dimensions.
   at Java.Interop.JniEnvironment.InstanceMethods.CallNonvirtualVoidMethod(JniObjectReference instance, JniObjectReference type, JniMethodInfo method, JniArgumentValue* args) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/obj/Release/net7.0/JniEnvironment.g.cs:line 20830
   at Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeNonvirtualVoidMethod(String encodedMember, IJavaPeerable self, JniArgumentValue* parameters) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:line 93
   at Android.Gms.Maps.GoogleMap.MoveCamera(CameraUpdate update) in C:\a\_work\1\s\generated\com.google.android.gms.play-services-maps\obj\Release\net6.0-android\generated\src\Android.Gms.Maps.GoogleMap.cs:line 3881
   at Microsoft.Maui.Maps.Handlers.MapHandler.MoveToRegion(MapSpan span, Boolean animate) in D:\a\_work\1\s\src\Core\maps\src\Handlers\Map\MapHandler.Android.cs:line 362
  --- End of managed Java.Lang.IllegalStateException stack trace ---
com.google.maps.api.android.lib6.common.apiexception.c: Error using newLatLngBounds(LatLngBounds, int): Map size can't be 0. Most likely, layout has not yet occurred for the map view.  Either wait until layout has occurred or use newLatLngBounds(LatLngBounds, int, int, int) which allows you to specify the map's dimensions.
	at com.google.maps.api.android.lib6.common.m.h(:com.google.android.gms.dynamite_mapsdynamite@231818047@23.18.18 (190800-0):0)
	at com.google.maps.api.android.lib6.gmm6.api.c.l(:com.google.android.gms.dynamite_mapsdynamite@231818047@23.18.18 (190800-0):1)
	at com.google.maps.api.android.lib6.impl.ae.a(:com.google.android.gms.dynamite_mapsdynamite@231818047@23.18.18 (190800-0):0)
	at com.google.maps.api.android.lib6.gmm6.api.c.z(:com.google.android.gms.dynamite_mapsdynamite@231818047@23.18.18 (190800-0):3)
	at com.google.maps.api.android.lib6.impl.bk.q(:com.google.android.gms.dynamite_mapsdynamite@231818047@23.18.18 (190800-0):1)
	at com.google.android.gms.maps.internal.i.bb(:com.google.android.gms.dynamite_mapsdynamite@231818047@23.18.18 (190800-0):268)
	at ff.onTransact(:com.google.android.gms.dynamite_mapsdynamite@231818047@23.18.18 (190800-0):4)
	at android.os.Binder.transact(Binder.java:1183)
	at com.google.android.gms.internal.maps.zza.zzc(com.google.android.gms:play-services-maps@@18.1.0:2)
	at com.google.android.gms.maps.internal.zzg.moveCamera(com.google.android.gms:play-services-maps@@18.1.0:3)
	at com.google.android.gms.maps.GoogleMap.moveCamera(com.google.android.gms:play-services-maps@@18.1.0:2)
	at crc64a5df8ade113ad624.MapCallbackHandler.n_onMapReady(Native Method)
	at crc64a5df8ade113ad624.MapCallbackHandler.onMapReady(MapCallbackHandler.java:41)
	at com.google.android.gms.maps.zzaf.zzb(com.google.android.gms:play-services-maps@@18.1.0:1)
	at com.google.android.gms.maps.internal.zzar.zza(com.google.android.gms:play-services-maps@@18.1.0:6)
	at com.google.android.gms.internal.maps.zzb.onTransact(com.google.android.gms:play-services-maps@@18.1.0:3)
	at android.os.Binder.transact(Binder.java:1183)
	at fe.c(:com.google.android.gms.dynamite_mapsdynamite@231818047@23.18.18 (190800-0):2)
	at com.google.maps.api.android.lib6.impl.bg.run(:com.google.android.gms.dynamite_mapsdynamite@231818047@23.18.18 (190800-0):2)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8177)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)

**Comment by TamilarasanSF4853** [comment]
This issue has been verified in Visual Studio Code 1.103.1 MAUI version 9.0.100. It doesn't reproduced on the Android platform. I have attached the video for your reference.

https://github.com/user-attachments/assets/48930447-6b1a-413e-9c1a-fa884a7b725b
