### ISSUE TITLE
[Bug] Cannot use ContentView

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#1263]
### Description

```xaml
<AbsoluteLayout>
        <BoxView Color="Black" AbsoluteLayout.LayoutBounds="1,0.5,100,100" 
                 AbsoluteLayout.LayoutFlags="PositionProportional"/>

        <BoxView Color="Black" AbsoluteLayout.LayoutBounds="0,0.5,100,100" 
                 AbsoluteLayout.LayoutFlags="PositionProportional"/>

        <BoxView Color="Black" AbsoluteLayout.LayoutBounds="0.5,0,100,100" 
                 AbsoluteLayout.LayoutFlags="PositionProportional"/>

        <BoxView Color="Black" AbsoluteLayout.LayoutBounds="0.5,1,100,100" 
                 AbsoluteLayout.LayoutFlags="PositionProportional"/>

        <ContentView
                 AbsoluteLayout.LayoutBounds="0.5,0.5,100,100" 
                 AbsoluteLayout.LayoutFlags="PositionProportional">
                    <BoxView Color="Red" />
        </ContentView>

...
```

When trying to use a `ContentView` I get this crash:

```
Unhandled Exception:
System.InvalidCastException: Specified cast is not valid.
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.ILayout, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.LayoutView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IView view) in Microsoft.Maui.dll:token 0x6000540+0x60
   at Microsoft.Maui.Handlers.LayoutHandler.SetVirtualView(IView view) in Microsoft.Maui.dll:token 0x6000497+0x0
   at Microsoft.Maui.Controls.VisualElement.SetHandler(IViewHandler newHandler) in Microsoft.Maui.Controls.dll:token 0x60008dd+0x6e
   at Microsoft.Maui.Controls.VisualElement.set_Handler(IViewHandler value) in Microsoft.Maui.Controls.dll:token 0x60008bc+0x0
   at Microsoft.Maui.HandlerExtensions.ToNative(IView view, IMauiContext context) in Microsoft.Maui.dll:token 0x600016d+0x65
   at Microsoft.Maui.Handlers.LayoutHandler.SetVirtualView(IView view) in Microsoft.Maui.dll:token 0x6000497+0xe1
   at Microsoft.Maui.Controls.VisualElement.SetHandler(IViewHandler newHandler) in Microsoft.Maui.Controls.dll:token 0x60008dd+0x6e
   at Microsoft.Maui.Controls.VisualElement.set_Handler(IViewHandler value) in Microsoft.Maui.Controls.dll:token 0x60008bc+0x0
   at Microsoft.Maui.HandlerExtensions.ToNative(IView view, IMauiContext context) in Microsoft.Maui.dll:token 0x600016d+0x65
   at Microsoft.Maui.Handlers.PageHandler.UpdateContent() in Microsoft.Maui.dll:token 0x60004a1+0x91
   at Microsoft.Maui.Handlers.PageHandler.MapContent(PageHandler handler, IPage page) in Microsoft.Maui.dll:token 0x60004a3+0x0
   at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass21_0[[Microsoft.Maui.IPage, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.PageHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IViewHandler r, IFrameworkElement v) in Microsoft.Maui.dll:token 0x60005bd+0xa
   at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IViewHandler viewHandler, IFrameworkElement virtualView) in Microsoft.Maui.dll:token 0x60002c5+0x10
   at Microsoft.Maui.PropertyMapper.UpdateProperties(IViewHandler viewHandler, IFrameworkElement virtualView) in Microsoft.Maui.dll:token 0x60002c7+0x19
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IPage, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.PageView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IView view) in Microsoft.Maui.dll:token 0x6000540+0x150
   at Microsoft.Maui.Handlers.PageHandler.SetVirtualView(IView view) in Microsoft.Maui.dll:token 0x60004a0+0x0
   at Microsoft.Maui.Controls.VisualElement.SetHandler(IViewHandler newHandler) in Microsoft.Maui.Controls.dll:token 0x60008dd+0x6e
   at Microsoft.Maui.Controls.VisualElement.set_Handler(IViewHandler value) in Microsoft.Maui.Controls.dll:token 0x60008bc+0x0
   at Microsoft.Maui.HandlerExtensions.ToNative(IView view, IMauiContext context) in Microsoft.Maui.dll:token 0x600016d+0x65
   at Microsoft.Maui.HandlerExtensions.ToUIViewController(IView view, IMauiContext context) in Microsoft.Maui.dll:token 0x600016c+0x0
   at Microsoft.Maui.MauiUIApplicationDelegate`1[[MyFive.Startup, MyFive, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].FinishedLaunching(UIApplication application, NSDictionary launchOptions) in Microsoft.Maui.dll:token 0x60001bb+0x59
--- End of stack trace from previous location ---
   at UIKit.UIApplication.Main(String[] args, IntPtr principal, IntPtr delegate) in Xamarin.MacCatalyst.dll:token 0x600e7a7+0x5
   at UIKit.UIApplication.Main(String[] args, String principalClassName, String delegateClassName) in Xamarin.MacCatalyst.dll:token 0x600e7a4+0xe
   at MyFive.Program.Main(String[] args) in /Users/dmo/work/demos/MyFive/MyFive/MacCatalyst/Program.cs:line 12
2021-06-11 09:35:54.005 MyFive[69285:2275347] Unhandled managed exception: Specified cast is not valid. (System.InvalidCastException)
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.ILayout, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.LayoutView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IView view) in Microsoft.Maui.dll:token 0x6000540+0x60
   at Microsoft.Maui.Handlers.LayoutHandler.SetVirtualView(IView view) in Microsoft.Maui.dll:token 0x6000497+0x0
   at Microsoft.Maui.Controls.VisualElement.SetHandler(IViewHandler newHandler) in Microsoft.Maui.Controls.dll:token 0x60008dd+0x6e
   at Microsoft.Maui.Controls.VisualElement.set_Handler(IViewHandler value) in Microsoft.Maui.Controls.dll:token 0x60008bc+0x0
   at Microsoft.Maui.HandlerExtensions.ToNative(IView view, IMauiContext context) in Microsoft.Maui.dll:token 0x600016d+0x65
   at Microsoft.Maui.Handlers.LayoutHandler.SetVirtualView(IView view) in Microsoft.Maui.dll:token 0x6000497+0xe1
   at Microsoft.Maui.Controls.VisualElement.SetHandler(IViewHandler newHandler) in Microsoft.Maui.Controls.dll:token 0x60008dd+0x6e
   at Microsoft.Maui.Controls.VisualElement.set_Handler(IViewHandler value) in Microsoft.Maui.Controls.dll:token 0x60008bc+0x0
   at Microsoft.Maui.HandlerExtensions.ToNative(IView view, IMauiContext context) in Microsoft.Maui.dll:token 0x600016d+0x65
   at Microsoft.Maui.Handlers.PageHandler.UpdateContent() in Microsoft.Maui.dll:token 0x60004a1+0x91
   at Microsoft.Maui.Handlers.PageHandler.MapContent(PageHandler handler, IPage page) in Microsoft.Maui.dll:token 0x60004a3+0x0
   at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass21_0[[Microsoft.Maui.IPage, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.PageHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IViewHandler r, IFrameworkElement v) in Microsoft.Maui.dll:token 0x60005bd+0xa
   at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IViewHandler viewHandler, IFrameworkElement virtualView) in Microsoft.Maui.dll:token 0x60002c5+0x10
   at Microsoft.Maui.PropertyMapper.UpdateProperties(IViewHandler viewHandler, IFrameworkElement virtualView) in Microsoft.Maui.dll:token 0x60002c7+0x19
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IPage, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.PageView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IView view) in Microsoft.Maui.dll:token 0x6000540+0x150
   at Microsoft.Maui.Handlers.PageHandler.SetVirtualView(IView view) in Microsoft.Maui.dll:token 0x60004a0+0x0
   at Microsoft.Maui.Controls.VisualElement.SetHandler(IViewHandler newHandler) in Microsoft.Maui.Controls.dll:token 0x60008dd+0x6e
   at Microsoft.Maui.Controls.VisualElement.set_Handler(IViewHandler value) in Microsoft.Maui.Controls.dll:token 0x60008bc+0x0
   at Microsoft.Maui.HandlerExtensions.ToNative(IView view, IMauiContext context) in Microsoft.Maui.dll:token 0x600016d+0x65
   at Microsoft.Maui.HandlerExtensions.ToUIViewController(IView view, IMauiContext context) in Microsoft.Maui.dll:token 0x600016c+0x0
   at Microsoft.Maui.MauiUIApplicationDelegate`1[[MyFive.Startup, MyFive, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].FinishedLaunching(UIApplication application, NSDictionary launchOptions) in Microsoft.Maui.dll:token 0x60001bb+0x59
--- End of stack trace from previous location ---
   at UIKit.UIApplication.Main(String[] args, IntPtr principal, IntPtr delegate) in Xamarin.MacCatalyst.dll:token 0x600e7a7+0x5
   at UIKit.UIApplication.Main(String[] args, String principalClassName, String delegateClassName) in Xamarin.MacCatalyst.dll:token 0x600e7a4+0xe
   at MyFive.Program.Main(String[] args) in /Users/dmo/work/demos/MyFive/MyFive/MacCatalyst/Program.cs:line 12
```

### Basic Information

- Version with issue: ci-main.4.4144

### Reproduction Link

[Archive.zip](https://github.com/dotnet/maui/files/6639203/Archive.zip)

**Comment by PureWeen** [comment]
https://github.com/dotnet/maui/issues/1302
