### ISSUE TITLE
Illegal Clip value did not throw exceptions at compile time and DEBUG mode

### ISSUE THREAD

**Issue by 1357310795** [dotnet/maui#12900]
### Description

Set VisualElement.Clip to an illegal value like "ilovemaui" in xaml, the compilation will not fail, and even running at DEBUG mode didn't crash the application. But when we run the application directly, it crashes!

### Steps to Reproduce

1. File - New - .NET MAUI App
2. Add a new page like "NewPage1.xaml"
3. Add Clip="ilovemaui" to any Element of NewPage1.xaml
4. Run the Application, navigate to NewPage1
5. Try in DEBUG mode and directly running

### Link to public reproduction project repository

https://github.com/Worunatto/MauiAppXamlParseException

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

Android 12, Windows 10

### Did you find any workaround?

No. The only thing I can do is writing legal values of properties in xaml.

### Relevant log output

```shell
The log on Android

01-25 19:58:21.716 24334 24334 E AndroidRuntime: FATAL EXCEPTION: main
01-25 19:58:21.716 24334 24334 E AndroidRuntime: Process: com.companyname.mauiappxamlparseexception, PID: 24334
01-25 19:58:21.716 24334 24334 E AndroidRuntime: android.runtime.JavaProxyThrowable: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
01-25 19:58:21.716 24334 24334 E AndroidRuntime:  ---> Microsoft.Maui.Controls.Xaml.XamlParseException: Position 11:21. Type converter failed: UnexpectedToken "RoundRectangle 14" into 0
01-25 19:58:21.716 24334 24334 E AndroidRuntime:  ---> System.FormatException: UnexpectedToken "RoundRectangle 14" into 0
01-25 19:58:21.716 24334 24334 E AndroidRuntime:    at Microsoft.Maui.Controls.Shapes.PathFigureCollectionConverter.ThrowBadToken()
01-25 19:58:21.716 24334 24334 E AndroidRuntime:    at Microsoft.Maui.Controls.Shapes.PathFigureCollectionConverter.ParseToPathFigureCollection(PathFigureCollection pathFigureCollection, String pathString, Int32 startIndex)
01-25 19:58:21.716 24334 24334 E AndroidRuntime:    at Microsoft.Maui.Controls.Shapes.PathFigureCollectionConverter.ParseStringToPathFigureCollection(PathFigureCollection pathFigureCollection, String pathString)
01-25 19:58:21.716 24334 24334 E AndroidRuntime:    at Microsoft.Maui.Controls.Shapes.PathGeometryConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
01-25 19:58:21.716 24334 24334 E AndroidRuntime:    at System.ComponentModel.TypeConverter.ConvertFromString(ITypeDescriptorContext context, CultureInfo culture, String text)
01-25 19:58:21.716 24334 24334 E AndroidRuntime:    at System.ComponentModel.TypeConverter.ConvertFromInvariantString(String text)
01-25 19:58:21.716 24334 24334 E AndroidRuntime:    at Microsoft.Maui.Controls.Xaml.TypeConversionExtensions.ConvertTo(Object value, Type toType, Func`1 getConverter, IServiceProvider serviceProvider, Exception& exception)
01-25 19:58:21.716 24334 24334 E AndroidRuntime:    --- End of inner exception stack trace ---
01-25 19:58:21.716 24334 24334 E AndroidRuntime:    at Microsoft.Maui.Controls.Xaml.ApplyPropertiesVisitor.SetPropertyValue(Object xamlelement, XmlName propertyName, Object value, Object rootElement, INode node, HydrationContext context, IXmlLineInfo lineInfo)
01-25 19:58:21.716 24334 24334 E AndroidRuntime:    at Microsoft.Maui.Controls.Xaml.ApplyPropertiesVisitor.Visit(ValueNode node, INode parentNode)
01-25 19:58:21.716 24334 24334 E AndroidRuntime:    at Microsoft.Maui.Controls.Xaml.ValueNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
01-25 19:58:21.716 24334 24334 E AndroidRuntime:    at Microsoft.Maui.Controls.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
01-25 19:58:21.716 24334 24334 E AndroidRuntime:    at Microsoft.Maui.Controls.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
01-25 19:58:21.716 24334 24334 E AndroidRuntime:    at Microsoft.Maui.Controls.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
01-25 19:58:21.716 24334 24334 E AndroidRuntime:    at Microsoft.Maui.Controls.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
01-25 19:58:21.716 24334 24334 E AndroidRuntime:    at Microsoft.Maui.Controls.Xaml.RootNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
01-25 19:58:21.716 24334 24334 E AndroidRuntime:    at Microsoft.Maui.Controls.Xaml.XamlLoader.Visit(RootNode rootnode, HydrationContext visitorContext, Boolean useDesignProperties)
01-25 19:58:21.716 24334 24334 E AndroidRuntime:    at Microsoft.Maui.Controls.Xaml.XamlLoader.Load(Object view, String xaml, Assembly rootAssembly, Boolean useDesignProperties)
01-25 19:58:21.716 24334 24334 E AndroidRuntime:    at Microsoft.Maui.Controls.Xaml.XamlLoader.Load(Object view, String xaml, Boolean useDesignProperties)
01-25 19:58:21.716 24334 24334 E AndroidRuntime:    at Microsoft.Maui.Controls.Xaml.XamlLoader.Load(Object view, Type callingType)
01-25 19:58:21.716 24334 24334 E AndroidRuntime:    at Microsoft.Maui.Controls.Xaml.Extensions.LoadFromXaml[NewPage1](NewPage1 view, Type callingType)
01-25 19:58:21.716 24334 24334 E AndroidRuntime:    at MauiAppXamlParseException.NewPage1.InitializeComponent()
01-25 19:58:21.716 24334 24334 E AndroidRuntime:    at MauiAppXamlParseException.NewPage1..ctor()
01-25 19:58:21.716 24334 24334 E AndroidRuntime:    at System.Reflection.ConstructorInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)
01-25 19:58:21.716 24334 24334 E AndroidRuntime:    --- End of inner exception stack trace ---
```
```

**Comment by PureWeen** [comment]
@etvorun @StephaneDelcroix thoughts?

**Comment by jinxinjuan** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 2.0. Not  repro on windows with sample project. 
[MauiAppXamlParseException](https://github.com/Worunatto/MauiAppXamlParseException)
