### ISSUE TITLE
AVFoundation Migration to .NET 7 Maui

### ISSUE THREAD

**Issue by alaskanrogue** [dotnet/maui#12969]
@jfversluis I wasn't referring to "Plugin,Maui.Audio" Nuget directly. I have it working with AzureCognitiveServices on Windows. 

What I was trying to do is implement a backup speech service using MauiCognitiveServices in case AzureCognitiveServices goes down. After upgrading to .NET 7, MauiCognitiveServices began failing when deployed to iOS trying to use the assembly.

```
[0:] An error occurred: 'Could not initialize an instance of the type 'AVFoundation.AVAudioPlayer': the native 'initWithData:error:' method returned nil.
It is possible to ignore this condition by setting ObjCRuntime.Class.ThrowOnInitFailure to false.'. Callstack: '   at Foundation.NSObject.InitializeHandle(NativeHandle handle, String initSelector)
   at AVFoundation.AVAudioPlayer..ctor(NSData data, IntPtr outError)
   at AVFoundation.AVAudioPlayer.FromData(NSData data)
   at Plugin.Maui.Audio.AudioPlayer..ctor(Stream audioStream)
   at Plugin.Maui.Audio.AudioManager.CreatePlayer(Stream audioStream)
   at Sentry.SentryAudioManager..ctor() in C:\Projects\Sentry\Sentry\Control\SentryAudioManager.cs:line 38
   at Sentry.Startup..ctor() in C:\Projects\Sentry\Sentry\Startup.cs:line 23
   at Sentry.MainPage.OnAppearing() in C:\Projects\Sentry\Sentry\MainPage.xaml.cs:line 47
   at Microsoft.Maui.Controls.Page.SendAppearing()
   at Microsoft.Maui.Controls.Window.SendWindowAppearing()
   at Microsoft.Maui.Controls.Window.FinishedAddingWindowToApplication(Application application)
   at Microsoft.Maui.Controls.Application.AddWindow(Window window)
   at Microsoft.Maui.Controls.Application.Microsoft.Maui.IApplication.CreateWindow(IActivationState activationState)
   at Microsoft.Maui.Platform.ApplicationExtensions.CreatePlatformWindow(IApplication application, UIWindowScene windowScene, NSDictionary[] states)
   at Microsoft.Maui.Platform.ApplicationExtensions.CreatePlatformWindow(IUIApplicationDelegate platformApplication, IApplication application, UIApplication uiApplication, NSDictionary launchOptions)
   at Microsoft.Maui.MauiUIApplicationDelegate.FinishedLaunching(UIApplication application, NSDictionary launchOptions)
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName)
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)
   at Sentry.Program.Main(String[] args) in C:\Projects\Sentry\Sentry\Platforms\iOS\Program.cs:line 12
   at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)'
The app has been terminated.
```

The calling code is:

```
                if (!App.audioOff)
                {
                    byte[] buffer = new byte[] { 0x00 };
                    MemoryStream narrative = new MemoryStream(buffer);

                    audioManager = new AudioManager();
                    audioPlayer = audioManager.CreatePlayer(narrative);
                    stopSpeaking = false;
                 }

```

_Originally posted by @alaskanrogue in https://github.com/dotnet/maui/issues/12176#issuecomment-1357592919_

**Comment by alaskanrogue** [comment]
Having seen the announcement that the previous issue has been resolved, I loaded the new version of "Microsoft.CognitiveServices.Speech", v1.250, and tested it. The issue has remained. It doesn't seem to be any different.

```
[0:] An error occurred: 'Could not initialize an instance of the type 'AVFoundation.AVAudioPlayer': the native 'initWithData:error:' method returned nil.
It is possible to ignore this condition by setting ObjCRuntime.Class.ThrowOnInitFailure to false.'. Callstack: '   at Foundation.NSObject.InitializeHandle(NativeHandle handle, String initSelector)
   at AVFoundation.AVAudioPlayer..ctor(NSData data, IntPtr outError)
   at AVFoundation.AVAudioPlayer.FromData(NSData data)
   at Plugin.Maui.Audio.AudioPlayer..ctor(Stream audioStream)
   at Plugin.Maui.Audio.AudioManager.CreatePlayer(Stream audioStream)
   at Sentry.SentryAudioManager..ctor() in C:\Projects\Sentry\Sentry\Control\SentryAudioManager.cs:line 38
   at Sentry.Startup..ctor() in C:\Projects\Sentry\Sentry\Startup.cs:line 23
   at Sentry.MainPage.OnAppearing() in C:\Projects\Sentry\Sentry\MainPage.xaml.cs:line 47
   at Microsoft.Maui.Controls.Page.SendAppearing()
   at Microsoft.Maui.Controls.Window.SendWindowAppearing()
   at Microsoft.Maui.Controls.Window.FinishedAddingWindowToApplication(Application application)
   at Microsoft.Maui.Controls.Application.AddWindow(Window window)
   at Microsoft.Maui.Controls.Application.Microsoft.Maui.IApplication.CreateWindow(IActivationState activationState)
   at Microsoft.Maui.Platform.ApplicationExtensions.CreatePlatformWindow(IApplication application, UIWindowScene windowScene, NSDictionary[] states)
   at Microsoft.Maui.Platform.ApplicationExtensions.CreatePlatformWindow(IUIApplicationDelegate platformApplication, IApplication application, UIApplication uiApplication, NSDictionary launchOptions)
   at Microsoft.Maui.MauiUIApplicationDelegate.FinishedLaunching(UIApplication application, NSDictionary launchOptions)
   at Sentry.AppDelegate.FinishedLaunching(UIApplication application, NSDictionary launchOptions) in C:\Projects\Sentry\Sentry\Platforms\iOS\AppDelegate.cs:line 24
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName)
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)
   at Sentry.Program.Main(String[] args) in C:\Projects\Sentry\Sentry\Platforms\iOS\Program.cs:line 12
   at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)'
The app has been terminated.
```
Is the resolution in that NuGet?

**Comment by mattleibow** [comment]
@rolfbjarne any ideas?

**Comment by mattleibow** [comment]
Actually, looking at the stack trace it appears the exception is coming from within the plugin. I would suggest opening this issue there so the author can have a look.

It can also potentially mean that because your data is invalid? so there manager can't create the player. However, the exception also looks like it was unexpected so maybe there is some binding annotation issue @dalexsoto?

**Comment by rolfbjarne** [comment]
> at AVFoundation.AVAudioPlayer..ctor(NSData data, IntPtr outError)
>    at AVFoundation.AVAudioPlayer.FromData(NSData data)
>    at Plugin.Maui.Audio.AudioPlayer..ctor(Stream audioStream)

My guess is that the input data is invalid, so the AVAudioPlayer couldn't be created.

You can call the AVAudioPlayer.FromData overload that takes an `out NSError` to see if the returned error gives more information: https://learn.microsoft.com/en-us/dotnet/api/avfoundation.avaudioplayer.fromdata?view=xamarin-mac-sdk-14

**Comment by alaskanrogue** [comment]
Given my discovery this morning that MAUI as of this week now supports Text-to-Speak across languages and Media playing across the platforms, I am going to try and move back to that API. Keeping my fingers crossed. Will update you.

**Comment by mattleibow** [comment]
Let us know how it goes!

**Comment by alaskanrogue** [comment]
I have almost completed the transition to MAUI speech with the exception of it may have generated a different issue in the iOS executable. I have yet to test the speech translation capabilities on any platform because of the efforts trying to resolve other reported issues.
