### ISSUE TITLE
Alerts do not display from ctor or OnAppearing when not in a NavPage/Shell

### ISSUE THREAD

**Issue by mattleibow** [dotnet/maui#12970]
### Description

Seems that the alerts are fired correctly and then added to the `_pendingActions`. However, the `FlushPendingActions` method only fires when the `NavigatedTo` even is invoked - and this only happens when in a nav page or in shell.

### Steps to Reproduce

1. In the sandbox app
2. Use this code in the MauiProgram.cs:
```cs
	class App : Application
	{
		protected override Window CreateWindow(IActivationState activationState) =>
			new Window(new MainPage());
	}
```
3. Use this code in the MainPage.xaml.cs:
```cs
	protected override void OnAppearing()
	{
		base.OnAppearing();
		DisplayAlert("A", "B", "C");
	}
```

### Link to public reproduction project repository

maui repo

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS, Other (Tizen, Linux, etc. not supported by Microsoft directly)

### Affected platform versions

All version as this is xplat code

**Comment by mattleibow** [comment]
@PureWeen not sure the overall navigation / alerts plan, but saw this while trying to create tests for https://github.com/dotnet/maui/pull/12910

**Comment by jsuarezruiz** [comment]
Same or similar to https://github.com/dotnet/maui/issues/12739

**Comment by ShariatPanah** [comment]
any update on this guys? i have the same problem

**Comment by jeremy-visionaid** [comment]
Yup, I just hit this one too.

**Comment by jeremy-visionaid** [comment]
@mattleibow I find this to be even worse than the title... 

On Windows, OnNavigatedTo actually fires in my app, but the alert is still not displayed. If you try to work around it by adding an (insufficient) delay by using a timer or a Task.Delay, then it can cause a crash (8.0.0-rc.1.9171):

```
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr) in WinRT\ExceptionHelpers.cs:line 103
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr) in WinRT\ExceptionHelpers.cs:line 105
   at ABI.Microsoft.UI.Xaml.Controls.IContentDialogMethods.ShowAsync(IObjectReference _obj) in ABI.Microsoft.UI.Xaml.Controls\IContentDialogMethods.cs:line 51
   at Microsoft.UI.Xaml.Controls.ContentDialog.ShowAsync() in Microsoft.UI.Xaml.Controls\ContentDialog.cs:line 527
   at Microsoft.Maui.Controls.Platform.AlertManager.AlertRequestHelper.<ShowAlert>d__14.MoveNext() in Microsoft.Maui.Controls.Platform\AlertManager.cs:line 209
   at Microsoft.Maui.Controls.Platform.AlertManager.AlertRequestHelper.<OnAlertRequested>d__11.MoveNext() in Microsoft.Maui.Controls.Platform\AlertManager.cs:line 94
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 1914
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
```

So, seems like there's a pretty big problem is how to know how when it's valid to display an alert... I can put in a delay of a second, and that works OK on my machine (anything much shorter is unreliable) - but I don't know if it's sufficient for other cases.

**Comment by homeyf** [comment]
Verified this issue with Visual Studio Enterprise 17.8.0 Preview 2.0. Can repro on windows platform with sample code.

**Comment by Mark-NC001** [comment]
This is quite a big issue for me, as I have Try...Catches in OnAppearing that call DisplayAlert to let the user know of issues.

**Comment by jeremy-visionaid** [comment]
@Mark-NC001 Coud you queue it on the dispatcher as a workaround? I was able to reorganize to avoid the problem deterministaically via `Loaded`, but in my initial attempt I found I needed quite a long delay before it worked (maybe 2-3 seconds on the first `OnAppearing` invocation)

**Comment by kubaflo** [comment]
Hi, @Mark-NC001 try this as a workaround
```c#
	protected override void OnAppearing()
	{
		base.OnAppearing();
		DisplayAlertOnAppearing("Hello","Message","Ok");
	}

	void DisplayAlertOnAppearing(string title, string message, string cancel) 
	{
		Loaded += OnLoaded;
		void OnLoaded(object sender, EventArgs e)
		{
			DisplayAlert(title, message, cancel);
			Loaded -= OnLoaded;
		}
	}
```

**Comment by Mark-NC001** [comment]
@kubaflo and @jeremy-visionaid thanks for the info. In the end I've made a new function that I call from within OnAppearing, waiting until it's done. I'm preparing myself for the many reasons why I shouldn't do this.....!

```
public static async Task EnsurePageLoaded(Page page, int intervalMilliseconds = 100, int maxWaitMilliseconds = 6000)
{
		if (page == null) throw new ArgumentNullException(nameof(page));

		int maxWaited = 0;

		while (!page.IsLoaded)
		{
			if (maxWaited > maxWaitMilliseconds)
				throw new InvalidOperationException("Waited " + maxWaited + " milliseconds, but page still not loaded!");

			maxWaited += intervalMilliseconds;
			await Task.Delay(intervalMilliseconds);
		}
}
```
Also, it's not just DisplayAlerts that aren't working - I'm also using dependency injection:
Application.Current.MainPage.Handler.MauiContext.Services.GetService<xxxxxx>()
and Handler appears to be null, until the page has loaded.

**Comment by jeremy-visionaid** [comment]
Still an issue in v10.0.90

**Comment by kubaflo** [comment]
Thanks @jeremy-visionaid — confirmed still reproducing on 10.0.90, recorded.

This stays open; there's no version-check label outstanding and nothing further is needed from you.

> Disclosure: this comment was generated by AI.
