### ISSUE TITLE
MSB4018	WinAppSdkGenerateAppxPackageRecipe .NET Maui compile error

### ISSUE THREAD

**Issue by mach-9** [dotnet/maui#13117]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/run
Operating System: windows

When compiling my .NET Maui project after creating it, I receive the error message below: I have not added any code, brand new out of the box. I'm using VS 2022(windows 10 pro), made sure I have .NET Maui in VS installer, googled it, but couldn't really find anything. I added the MSIX NuGet package with no success. Any help would be much appreciated.

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4018	The "WinAppSdkGenerateAppxPackageRecipe" task failed unexpectedly.
System.ComponentModel.Win32Exception (0x80004005): The specified module could not be found
   at Microsoft.Build.Msix.MrmSupportLibrary.Load(String mrmSupportLibraryPath)
   at Microsoft.Build.Msix.MrmSupportLibraryResourceIndexMap..ctor(String mrmSupportLibraryPath, String projectDir)
   at Microsoft.Build.Msix.ResourceIndexMap.Create(String mrmSupportLibraryPath, Boolean useResourceIndexerApi, String projectDir, ITaskItem[] indexedPayloadFiles)
   at Microsoft.Build.Msix.Recipe.WinAppSdkGenerateAppxPackageRecipe.ExecuteImplementation()
   at Microsoft.Build.Msix.AppxPackagingTaskHelper.Execute(String file)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Build.Msix.AppxPackagingTaskHelper.Execute(String file)
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	MauiApp3	C:\Users\_Admin\.nuget\packages\microsoft.windowsappsdk\1.2.221109.1\buildTransitive\Microsoft.Build.Msix.Packaging.targets	1591

**Comment by bdizzleog** [comment]
Also encountering this problem randomly when I was publishing my MAUI app to the Microsoft Store in Visual Studio. AppCert.exe was not found, after installing it I received these errors (unsure if related). I am now unable to debug my project for Windows.


```
Error	APPX0002	Task 'WinAppSdkGenerateAppxPackageRecipe' failed. The specified module could not be found
	Flextra.App	C:\Users\brand\.nuget\packages\microsoft.windowsappsdk\1.2.221209.1\buildTransitive\Microsoft.Build.Msix.Packaging.targets	1591	
```

```
Error	MSB4018	The "WinAppSdkGenerateAppxPackageRecipe" task failed unexpectedly.
System.ComponentModel.Win32Exception (0x80004005): The specified module could not be found
   at Microsoft.Build.Msix.MrmSupportLibrary.Load(String mrmSupportLibraryPath)
   at Microsoft.Build.Msix.MrmSupportLibraryResourceIndexMap..ctor(String mrmSupportLibraryPath, String projectDir)
   at Microsoft.Build.Msix.ResourceIndexMap.Create(String mrmSupportLibraryPath, Boolean useResourceIndexerApi, String projectDir, ITaskItem[] indexedPayloadFiles)
   at Microsoft.Build.Msix.Recipe.WinAppSdkGenerateAppxPackageRecipe.ExecuteImplementation()
   at Microsoft.Build.Msix.AppxPackagingTaskHelper.Execute(String file)
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	Flextra.App	C:\Users\brand\.nuget\packages\microsoft.windowsappsdk\1.2.221209.1\buildTransitive\Microsoft.Build.Msix.Packaging.targets	1591	
```

Deleting obj/bin folders in the project does _not_ remedy the issue.

**Comment by MatiasBordoy** [comment]
Same error here, just creating MAUI project and trying to build the first time. In a fresh VS2022 install...

**Comment by samsengupta** [comment]
I am also facing the same issue on a clean unmodified newly created MAUI project, with or without Blazor, with either net 6.0 or net 7.0.

Works fine on a different machine with fresh Windows 10 with clean VS2022 install.

Steps described in the first section of https://learn.microsoft.com/en-us/dotnet/maui/troubleshooting to clean prior SDK and MAUI workload installations did not help.

Can't find any additional clues in more detailed build logs than error message reported above about which mrm support library module it cannot find:

.nuget\packages\microsoft.windowsappsdk\1.2.221209.1\buildTransitive\Microsoft.Build.Msix.Packaging.targets(1591,5): error APPX0002: Task 'WinAppSdkGenerateAppxPackageRecipe' failed. The specified module could not be found
.nuget\packages\microsoft.windowsappsdk\1.2.221209.1\buildTransitive\Microsoft.Build.Msix.Packaging.targets(1591,5): error APPX0002:
.nuget\packages\microsoft.windowsappsdk\1.2.221209.1\buildTransitive\Microsoft.Build.Msix.Packaging.targets(1591,5): error MSB4018: The "WinAppSdkGenerateAppxPackageRecipe" task failed unexpectedly.
.nuget\packages\microsoft.windowsappsdk\1.2.221209.1\buildTransitive\Microsoft.Build.Msix.Packaging.targets(1591,5): error MSB4018: System.ComponentModel.Win32Exception (0x80004005): The specified module could not be found
.nuget\packages\microsoft.windowsappsdk\1.2.221209.1\buildTransitive\Microsoft.Build.Msix.Packaging.targets(1591,5): error MSB4018:    at Microsoft.Build.Msix.MrmSupportLibrary.Load(String mrmSupportLibraryPath)

**Comment by samsengupta** [comment]
Since this error was reported on line 1591 of .nuget\packages\microsoft.windowsappsdk\1.1.5\buildTransitive\Microsoft.Build.Msix.Packaging.targets, that indicated an appx/msix packaging issue, which is handled by the UWP workload, so I tried installing the UWP workload in Visual Studio 2022, and this fixed the problem for me.

Note that on the fresh Windows 10, Visual Studio 2022 install, it worked without needing the UWP workload installed at all, so it seems like whatever was stale in the repro machine was freshened up by the UWP workload install.
