### ISSUE TITLE
Failed to download the Developer Disk image for iOS 16.1

### ISSUE THREAD

**Issue by ddobric** [dotnet/maui#13135]
### Description

When trying to debug the app by using HotRestart (No Mac) the deployment fails with the following error saved to the logfile.:

> Downloading Developer Disk Image for iOS version 16.1..

The error dialogue in VS:
![image](https://user-images.githubusercontent.com/1756871/216971180-481ca1ca-1cca-4cc8-8269-4938a6eb7a9e.png)

### Steps to Reproduce

1. Connect the Physical Device to the dev machine running VS 2022 v17.4.4
2. Run the app in the debugger (F5).

### Link to public reproduction project repository

tbd

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16.1

### Did you find any workaround?

No

### Relevant log output

```shell
> Xamarin.Messaging.IDB.Local.DeployAppMessageHandler Error: 0 : An error occurred while trying to deploy the app 'Imager.**.app'. Details: There was a problem while starting a session on the device {0}
> Xamarin.iOS.Windows.WindowsiOSException: There was a problem while starting a session on the device {0}
>    at Xamarin.iOS.Windows.AppleDeviceExtensions.StartSession(AppleDevice nativeDevice) in D:\a\_work\1\s\src\Tools\Xamarin.iOS.Windows.Client\Extensions\AppleDeviceExtensions.cs:line 90
>    at Xamarin.iOS.Windows.AppleDeviceExtensions.ExecuteWithSession(AppleDevice nativeDevice, Action action) in D:\a\_work\1\s\src\Tools\Xamarin.iOS.Windows.Client\Extensions\AppleDeviceExtensions.cs:line 14
>    at Xamarin.iOS.Windows.Installer.ApplicationSession.Deploy(String appRootFolder, String appBundleId, String appName) in D:\a\_work\1\s\src\Tools\Xamarin.iOS.Windows.Client\Installer\ApplicationSession.cs:line 94
>    at Xamarin.iOS.Windows.HotRestartClient.Deploy(AppleDevice nativeDevice, String appBundleId, String appBundleName, Boolean& incremental) in D:\a\_work\1\s\src\Tools\Xamarin.iOS.Windows.Client\HotRestartClient.cs:line 250
>    at Xamarin.Messaging.IDB.Local.DeployAppMessageHandler.<ExecuteAsync>d__5.MoveNext() in D:\a\_work\1\s\src\Messaging\Xamarin.Messaging.IDB.Local\Handlers\DeployAppMessageHandler.cs:line 41: 02/06/2023 12:14:45Z
>     DateTime=2023-02-06T12:14:45.5912664Z: 02/06/2023 12:14:45Z
> Xamarin.Messaging.IDB.Local.DeveloperDiskImageService Information: 0 : Downloading Developer Disk Image for iOS version 16.1...: 02/06/2023 12:14:45Z
>     DateTime=2023-02-06T12:14:45.9795252Z: 02/06/2023 12:14:45Z
> Xamarin.VisualStudio.Progress.ProgressReportService Information: 0 : Syncing certificates for "..." team...: 02/06/2023 12:14:46Z
>     DateTime=2023-02-06T12:14:46.1692975Z: 02/06/2023 12:14:46Z
> Xamarin.VisualStudio.Progress.ProgressReportService Information: 0 : !Syncing certificates for "..." team...: 02/06/2023 12:14:46Z
>     DateTime=2023-02-06T12:14:46.1692975Z: 02/06/2023 12:14:46Z
> Xamarin.VisualStudio.Progress.ProgressReportService Information: 0 : Fetching all certificates...: 02/06/2023 12:14:46Z
>     DateTime=2023-02-06T12:14:46.1692975Z: 02/06/2023 12:14:46Z
> Xamarin.VisualStudio.Progress.ProgressReportService Information: 0 : !Fetching all certificates...: 02/06/2023 12:14:46Z
>     DateTime=2023-02-06T12:14:46.1692975Z: 02/06/2023 12:14:46Z
> Xamarin.Messaging.IDB.Local.DeveloperDiskImageService Error: 0 : Failed to download the Developer Disk image for iOS 16.1
> System.IO.FileNotFoundException: Could not load file or assembly 'DeveloperDiskImageDownloader, Version=1.0.0.0, Culture=neutral, PublicKeyToken=e33b67d3bb5581e4' or one of its dependencies. The system cannot find the file specified.
> File name: 'DeveloperDiskImageDownloader, Version=1.0.0.0, Culture=neutral, PublicKeyToken=e33b67d3bb5581e4'
>    at Xamarin.Messaging.IDB.Local.DeveloperDiskImageService.<>c.<.ctor>b__12_0(String mapFile, String outputPath, String version, String cookies)
>    at Xamarin.Messaging.IDB.Local.DeveloperDiskImageService.<>c__DisplayClass22_0.<<DownloadImageAsync>b__0>d.MoveNext() in D:\a\_work\1\s\src\Messaging\Xamarin.Messaging.IDB.Local\DeveloperDiskImageService.cs:line 130
```

**Comment by ddobric** [comment]
This issue can be followed [here](https://developercommunity.visualstudio.com/t/Failed-to-download-the-Developer-Disk-im/10271966?port=1025&fsid=de2fb074-fe3d-45b2-898e-70fb8fe0fd0f&ref=native&refTime=1675701633221&refUserId=eb9c0486-fc5a-4a7a-910d-8edb24791eec).
