### ISSUE TITLE
DllNotFoundException is thrown when calling a library in Android Emulator

### ISSUE THREAD

**Issue by UkeHa** [dotnet/maui#13241]
### Description

When i add a library like magick.net the app stops working as soon as the given dll is being accessed. This problem affects the Android version (tested in emulator) as well as the iOS Version (tested on a local device). The Windows version runs as expected.

In my example i try to create a new instance of MagickImage like this `using MagickImage image = new(data);`

### Steps to Reproduce

1. Click button  "Click me!"
2. Select Image (a heic test file is included in the project, but any other image file will suffice)
3. Observe the bug 🐞 in the entry

expected behaviour:
the dll is found and used to initiate the object correctly

actual behaviour:
the project runs into an DllNotFoundException

### Link to public reproduction project repository

https://github.com/UkeHa/DLLUsageDemo

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, I was *not* able test on other platforms

### Affected platform versions

iOS, Android 13

### Did you find any workaround?

No.

### Relevant log output

```shell
System.TypeInitializationException: The type initializer for 'NativeMagickSettings' threw an exception.
 ---> System.DllNotFoundException: Magick.Native-Q16-x64.dll
   at ImageMagick.Environment.NativeEnvironment.Initialize() in /_/src/Magick.NET/Native/Helpers/Environment.cs:line 65
   at ImageMagick.Environment.Initialize() in /_/src/Magick.NET/Helpers/Environment.cs:line 21
   at ImageMagick.MagickSettings.NativeMagickSettings..cctor() in /_/src/Magick.NET/Native/Settings/MagickSettings.cs:line 321
   --- End of inner exception stack trace ---
   at ImageMagick.MagickSettings..ctor() in /_/src/Magick.NET/Settings/MagickSettings.cs:line 33
   at ImageMagick.MagickImage..ctor() in /_/src/Magick.NET/MagickImage.cs:line 41
   at ImageMagick.MagickImage..ctor(Byte[] data) in /_/src/Magick.NET/MagickImage.cs:line 51
   at DllUsageDemo.ViewModels.MainViewModel.SelectImage() in E:\sources\DllUsageDemo\DllUsageDemo\ViewModels\MainViewModel.cs:line 29
```

**Comment by drasticactions** [comment]
If you read the [Magick.NET](https://github.com/dlemstra/Magick.NET) docs, you need a native library for it to work, and they have them built for Windows, Linux, and macOS. Not iOS, nor Android.

Ref: https://github.com/dlemstra/Magick.NET/issues/1225

**Comment by UkeHa** [comment]
Fair enough, i assumed anycpu Linux build would work under androdi.

I can also reproduce this error on iOS with SkiaSharp.

{System.DllNotFoundException: @rpath/libSkiaSharp.framework/libSkiaSharp
   at SkiaSharp.SKMemoryStream..ctor()
   at SkiaSharp.SKMemoryStream..ctor(Byte[] data)

Perhaps this is a duplicate of xamarin/xamarin-macios/issues/17418 though.

**Comment by drasticactions** [comment]
Your issue with Magick.NET is specific to the library you're running. It will not work regardless of if you're running it in a MAUI UI app, or a .NET Android or iOS app that doesn't use MAUI. If they have Imagemagik built for the platform, it will work. I would take it up with them.
