### ISSUE TITLE
[Windows] MAUI app crashes when XAML Hot Reloading ShellContent within Shell.xaml

### ISSUE THREAD

**Issue by spadapet** [dotnet/maui#13775]
### Description

I want to be able to edit the default AppShell.xaml's content (in the Shell element) using XAML Hot Reload. But any changes I make in Shell are either not visible or crash the app. This bug is for the crash.

### Steps to Reproduce

**REPRO:**

1. Create new MAUI app from template in VS:
    * ![image](https://user-images.githubusercontent.com/2523431/223854798-92defcfe-1a96-4730-9b03-ecb971ebc23e.png)
2. I chose .NET 7:
    * ![image](https://user-images.githubusercontent.com/2523431/223854870-9af56ddf-b73d-4c54-a5a7-031a60a36158.png)
3. F5 to build and debug "Windows Machine"
    * Make sure that XAML Hot Reload is still enabled in VS
4. Open AppShell.xaml in VS after debugging starts
5. Delete the ShellContent tag
6. Hit undo to bring ShellContent back

**RESULT:**
App breaks into the debugger because of an unhandled exception. The exception is:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Maui.Controls.Handlers.ShellSectionHandler.SetVirtualView(IElement view)
   at Microsoft.Maui.Controls.Handlers.ShellItemHandler.UpdateCurrentItem()
   at Microsoft.Maui.Controls.Handlers.ShellItemHandler.MapCurrentItem(ShellItemHandler handler, ShellItem item)
   at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0.<Add>b__0(IElementHandler h, IElement v)
   at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IElementHandler viewHandler, IElement virtualView)
   at Microsoft.Maui.PropertyMapper.UpdateProperties(IElementHandler viewHandler, IElement virtualView)
   at Microsoft.Maui.Handlers.ElementHandler.SetVirtualView(IElement view)
   at Microsoft.Maui.Controls.Handlers.ShellItemHandler.SetVirtualView(IElement view)
   at Microsoft.Maui.Controls.Platform.ShellView.CreateShellItemView()
   at Microsoft.Maui.Controls.Platform.ShellView.SwitchShellItem(ShellItem newItem, Boolean animate)
   at Microsoft.Maui.Controls.Handlers.ShellHandler.MapCurrentItem(ShellHandler handler, Shell view)
   at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0.<Add>b__0(IElementHandler h, IElement v)
   at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IElementHandler viewHandler, IElement virtualView)
   at Microsoft.Maui.PropertyMapper.UpdateProperty(IElementHandler viewHandler, IElement virtualView, String property)
   at Microsoft.Maui.Handlers.ElementHandler.UpdateValue(String property)
   at Microsoft.Maui.Controls.Element.OnPropertyChanged(String propertyName)
   at Microsoft.Maui.Controls.Shell.OnPropertyChanged(String propertyName)
   at Microsoft.Maui.Controls.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, Boolean silent)
   at Microsoft.Maui.Controls.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes)
   at Microsoft.Maui.Controls.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes)
   at Microsoft.Maui.Controls.Element.SetValueFromRenderer(BindableProperty property, Object value)
   at Microsoft.Maui.Controls.ShellNavigationManager.GoToAsync(ShellNavigationParameters shellNavigationParameters, ShellNavigationRequest navigationRequest)
   at Microsoft.Maui.Controls.Shell.<Initialize>g__SetCurrentItem|172_1()
   at Microsoft.Maui.Controls.Shell.<Initialize>b__172_0(Object s, NotifyCollectionChangedEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
```

**EXPECT:**
* First of all, when I deleted the ShellContent, I wouldn't expect it to still be visible in the running app, but it is
* Second, don't crash the app with a NullReferenceException

### Link to public reproduction project repository

N/A, use default template

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

net7.0-windows10.0.19041.0

### Did you find any workaround?

Have to just stop debugging and edit the XAML before build+debug again. Or use the Android emulator since this hot reloading seems to work well on Android, just Windows crashes.

**Comment by jonathanpeppers** [comment]
This should fix it: https://github.com/dotnet/maui/pull/15220

Waiting for CI to see if this will fail on other platforms.
