### ISSUE TITLE
exception throw for 'Microsoft.Maui.Controls.Shapes.Shape"

### ISSUE THREAD

**Issue by philm001** [dotnet/maui#13823]
### Description

I am seeing the same error as this issue:

#11333

I need to build with NET7 for the mediaElement tag to work. I also need to support iOS 15 up to the latest (16.2 at the time of this writing.)  Can provide any info that is needed. 

I am seeing this error when I run iOS simulator for 15.0, 15,4 and even 16

Like the issue linked here, I will be including a copy of my project file along with a build log
[RelevantFIles.zip](https://github.com/dotnet/maui/files/10943525/RelevantFIles.zip)

### Steps to Reproduce

Just build it

### Link to public reproduction project repository

N/A

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15 and 16

### Did you find any workaround?

Nope

### Relevant log output

```shell
Loaded assembly: /Users/jason/Library/Developer/CoreSimulator/Devices/75D60431-9192-4544-8EE9-6D7F612A7471/data/Containers/Bundle/Application/C6FF8F08-0356-477C-B543-34E244171BB0/The_Juice.app/Microsoft.iOS.dll [External]
Loaded assembly: /Users/jason/Library/Developer/CoreSimulator/Devices/75D60431-9192-4544-8EE9-6D7F612A7471/data/Containers/Bundle/Application/C6FF8F08-0356-477C-B543-34E244171BB0/The_Juice.app/System.Runtime.dll [External]
Loaded assembly: /Users/jason/Library/Developer/CoreSimulator/Devices/75D60431-9192-4544-8EE9-6D7F612A7471/data/Containers/Bundle/Application/C6FF8F08-0356-477C-B543-34E244171BB0/The_Juice.app/System.Collections.dll [External]
Loaded assembly: /Users/jason/Library/Developer/CoreSimulator/Devices/75D60431-9192-4544-8EE9-6D7F612A7471/data/Containers/Bundle/Application/C6FF8F08-0356-477C-B543-34E244171BB0/The_Juice.app/System.Runtime.InteropServices.dll [External]
Loaded assembly: /Users/jason/Library/Developer/CoreSimulator/Devices/75D60431-9192-4544-8EE9-6D7F612A7471/data/Containers/Bundle/Application/C6FF8F08-0356-477C-B543-34E244171BB0/The_Juice.app/System.Threading.Thread.dll [External]
Loaded assembly: /Users/jason/Library/Developer/CoreSimulator/Devices/75D60431-9192-4544-8EE9-6D7F612A7471/data/Containers/Bundle/Application/C6FF8F08-0356-477C-B543-34E244171BB0/The_Juice.app/System.Threading.dll [External]
Loaded assembly: /Users/jason/Library/Developer/CoreSimulator/Devices/75D60431-9192-4544-8EE9-6D7F612A7471/data/Containers/Bundle/Application/C6FF8F08-0356-477C-B543-34E244171BB0/The_Juice.app/The_Juice.dll
Loaded assembly: /Users/jason/Library/Developer/CoreSimulator/Devices/75D60431-9192-4544-8EE9-6D7F612A7471/data/Containers/Bundle/Application/C6FF8F08-0356-477C-B543-34E244171BB0/The_Juice.app/Microsoft.Maui.Controls.dll [External]
Loaded assembly: /Users/jason/Library/Developer/CoreSimulator/Devices/75D60431-9192-4544-8EE9-6D7F612A7471/data/Containers/Bundle/Application/C6FF8F08-0356-477C-B543-34E244171BB0/The_Juice.app/System.ObjectModel.dll [External]
Loaded assembly: /Users/jason/Library/Developer/CoreSimulator/Devices/75D60431-9192-4544-8EE9-6D7F612A7471/data/Containers/Bundle/Application/C6FF8F08-0356-477C-B543-34E244171BB0/The_Juice.app/Microsoft.Maui.dll [External]
Loaded assembly: /Users/jason/Library/Developer/CoreSimulator/Devices/75D60431-9192-4544-8EE9-6D7F612A7471/data/Containers/Bundle/Application/C6FF8F08-0356-477C-B543-34E244171BB0/The_Juice.app/Microsoft.Maui.Controls.Xaml.dll [External]
Loaded assembly: /Users/jason/Library/Developer/CoreSimulator/Devices/75D60431-9192-4544-8EE9-6D7F612A7471/data/Containers/Bundle/Application/C6FF8F08-0356-477C-B543-34E244171BB0/The_Juice.app/System.ComponentModel.dll [External]
Loaded assembly: /Users/jason/Library/Developer/CoreSimulator/Devices/75D60431-9192-4544-8EE9-6D7F612A7471/data/Containers/Bundle/Application/C6FF8F08-0356-477C-B543-34E244171BB0/The_Juice.app/System.Private.Uri.dll [External]
Loaded assembly: /Users/jason/Library/Developer/CoreSimulator/Devices/75D60431-9192-4544-8EE9-6D7F612A7471/data/Containers/Bundle/Application/C6FF8F08-0356-477C-B543-34E244171BB0/The_Juice.app/Microsoft.Maui.Graphics.dll [External]
Loaded assembly: /Users/jason/Library/Developer/CoreSimulator/Devices/75D60431-9192-4544-8EE9-6D7F612A7471/data/Containers/Bundle/Application/C6FF8F08-0356-477C-B543-34E244171BB0/The_Juice.app/System.Numerics.Vectors.dll [External]
Loaded assembly: /Users/jason/Library/Developer/CoreSimulator/Devices/75D60431-9192-4544-8EE9-6D7F612A7471/data/Containers/Bundle/Application/C6FF8F08-0356-477C-B543-34E244171BB0/The_Juice.app/System.Xml.ReaderWriter.dll [External]
Loaded assembly: /Users/jason/Library/Developer/CoreSimulator/Devices/75D60431-9192-4544-8EE9-6D7F612A7471/data/Containers/Bundle/Application/C6FF8F08-0356-477C-B543-34E244171BB0/The_Juice.app/System.Private.Xml.dll [External]
Loaded assembly: /Users/jason/Library/Developer/CoreSimulator/Devices/75D60431-9192-4544-8EE9-6D7F612A7471/data/Containers/Bundle/Application/C6FF8F08-0356-477C-B543-34E244171BB0/The_Juice.app/System.Memory.dll [External]
Loaded assembly: /Users/jason/Library/Developer/CoreSimulator/Devices/75D60431-9192-4544-8EE9-6D7F612A7471/data/Containers/Bundle/Application/C6FF8F08-0356-477C-B543-34E244171BB0/The_Juice.app/System.Diagnostics.TraceSource.dll [External]
Loaded assembly: /Users/jason/Library/Developer/CoreSimulator/Devices/75D60431-9192-4544-8EE9-6D7F612A7471/data/Containers/Bundle/Application/C6FF8F08-0356-477C-B543-34E244171BB0/The_Juice.app/System.Collections.NonGeneric.dll [External]
Loaded assembly: /Users/jason/Library/Developer/CoreSimulator/Devices/75D60431-9192-4544-8EE9-6D7F612A7471/data/Containers/Bundle/Application/C6FF8F08-0356-477C-B543-34E244171BB0/The_Juice.app/System.Collections.Specialized.dll [External]
Loaded assembly: /Users/jason/Library/Developer/CoreSimulator/Devices/75D60431-9192-4544-8EE9-6D7F612A7471/data/Containers/Bundle/Application/C6FF8F08-0356-477C-B543-34E244171BB0/The_Juice.app/System.ComponentModel.Primitives.dll [External]
Loaded assembly: /Users/jason/Library/Developer/CoreSimulator/Devices/75D60431-9192-4544-8EE9-6D7F612A7471/data/Containers/Bundle/Application/C6FF8F08-0356-477C-B543-34E244171BB0/The_Juice.app/System.Text.RegularExpressions.dll [External]
Loaded assembly: /Users/jason/Library/Developer/CoreSimulator/Devices/75D60431-9192-4544-8EE9-6D7F612A7471/data/Containers/Bundle/Application/C6FF8F08-0356-477C-B543-34E244171BB0/The_Juice.app/System.Reflection.Emit.ILGeneration.dll [External]
Loaded assembly: /Users/jason/Library/Developer/CoreSimulator/Devices/75D60431-9192-4544-8EE9-6D7F612A7471/data/Containers/Bundle/Application/C6FF8F08-0356-477C-B543-34E244171BB0/The_Juice.app/System.Collections.Concurrent.dll [External]
Loaded assembly: /Users/jason/Library/Developer/CoreSimulator/Devices/75D60431-9192-4544-8EE9-6D7F612A7471/data/Containers/Bundle/Application/C6FF8F08-0356-477C-B543-34E244171BB0/The_Juice.app/System.Reflection.Emit.Lightweight.dll [External]
Loaded assembly: /Users/jason/Library/Developer/CoreSimulator/Devices/75D60431-9192-4544-8EE9-6D7F612A7471/data/Containers/Bundle/Application/C6FF8F08-0356-477C-B543-34E244171BB0/The_Juice.app/System.Reflection.Primitives.dll [External]
Loaded assembly: /Users/jason/Library/Developer/CoreSimulator/Devices/75D60431-9192-4544-8EE9-6D7F612A7471/data/Containers/Bundle/Application/C6FF8F08-0356-477C-B543-34E244171BB0/The_Juice.app/System.Net.Primitives.dll [External]
Loaded assembly: /Users/jason/Library/Developer/CoreSimulator/Devices/75D60431-9192-4544-8EE9-6D7F612A7471/data/Containers/Bundle/Application/C6FF8F08-0356-477C-B543-34E244171BB0/The_Juice.app/System.Diagnostics.Tracing.dll [External]
Loaded assembly: /Users/jason/Library/Developer/CoreSimulator/Devices/75D60431-9192-4544-8EE9-6D7F612A7471/data/Containers/Bundle/Application/C6FF8F08-0356-477C-B543-34E244171BB0/The_Juice.app/Microsoft.Win32.Primitives.dll [External]
Loaded assembly: /Users/jason/Library/Developer/CoreSimulator/Devices/75D60431-9192-4544-8EE9-6D7F612A7471/data/Containers/Bundle/Application/C6FF8F08-0356-477C-B543-34E244171BB0/The_Juice.app/System.Net.Http.dll [External]
Loaded assembly: /Users/jason/Library/Developer/CoreSimulator/Devices/75D60431-9192-4544-8EE9-6D7F612A7471/data/Containers/Bundle/Application/C6FF8F08-0356-477C-B543-34E244171BB0/The_Juice.app/System.Net.Security.dll [External]
Loaded assembly: /Users/jason/Library/Developer/CoreSimulator/Devices/75D60431-9192-4544-8EE9-6D7F612A7471/data/Containers/Bundle/Application/C6FF8F08-0356-477C-B543-34E244171BB0/The_Juice.app/System.Security.Cryptography.dll [External]
Loaded assembly: /Users/jason/Library/Developer/CoreSimulator/Devices/75D60431-9192-4544-8EE9-6D7F612A7471/data/Containers/Bundle/Application/C6FF8F08-0356-477C-B543-34E244171BB0/The_Juice.app/System.Formats.Asn1.dll [External]
Loaded assembly: /Users/jason/Library/Developer/CoreSimulator/Devices/75D60431-9192-4544-8EE9-6D7F612A7471/data/Containers/Bundle/Application/C6FF8F08-0356-477C-B543-34E244171BB0/The_Juice.app/System.Text.Encoding.Extensions.dll [External]
Loaded assembly: /Users/jason/Library/Developer/CoreSimulator/Devices/75D60431-9192-4544-8EE9-6D7F612A7471/data/Containers/Bundle/Application/C6FF8F08-0356-477C-B543-34E244171BB0/The_Juice.app/System.Runtime.Numerics.dll [External]
Loaded assembly: /Users/jason/Library/Developer/CoreSimulator/Devices/75D60431-9192-4544-8EE9-6D7F612A7471/data/Containers/Bundle/Application/C6FF8F08-0356-477C-B543-34E244171BB0/The_Juice.app/System.Net.Sockets.dll [External]
Loaded assembly: /Users/jason/Library/Developer/CoreSimulator/Devices/75D60431-9192-4544-8EE9-6D7F612A7471/data/Containers/Bundle/Application/C6FF8F08-0356-477C-B543-34E244171BB0/The_Juice.app/System.Net.NameResolution.dll [External]
Loaded assembly: /Users/jason/Library/Developer/CoreSimulator/Devices/75D60431-9192-4544-8EE9-6D7F612A7471/data/Containers/Bundle/Application/C6FF8F08-0356-477C-B543-34E244171BB0/The_Juice.app/System.Threading.ThreadPool.dll [External]
Loaded assembly: /Users/jason/Library/Developer/CoreSimulator/Devices/75D60431-9192-4544-8EE9-6D7F612A7471/data/Containers/Bundle/Application/C6FF8F08-0356-477C-B543-34E244171BB0/The_Juice.app/System.Security.Claims.dll [External]
Loaded assembly: /Users/jason/Library/Developer/CoreSimulator/Devices/75D60431-9192-4544-8EE9-6D7F612A7471/data/Containers/Bundle/Application/C6FF8F08-0356-477C-B543-34E244171BB0/The_Juice.app/System.Linq.dll [External]
Loaded assembly: /Users/jason/Library/Developer/CoreSimulator/Devices/75D60431-9192-4544-8EE9-6D7F612A7471/data/Containers/Bundle/Application/C6FF8F08-0356-477C-B543-34E244171BB0/The_Juice.app/System.Diagnostics.DiagnosticSource.dll [External]
Loaded assembly: /Users/jason/Library/Developer/CoreSimulator/Devices/75D60431-9192-4544-8EE9-6D7F612A7471/data/Containers/Bundle/Application/C6FF8F08-0356-477C-B543-34E244171BB0/The_Juice.app/System.Net.Quic.dll [External]
Loaded assembly: /Users/jason/Library/Developer/CoreSimulator/Devices/75D60431-9192-4544-8EE9-6D7F612A7471/data/Containers/Bundle/Application/C6FF8F08-0356-477C-B543-34E244171BB0/The_Juice.app/System.IO.Compression.dll [External]
Loaded assembly: /Users/jason/Library/Developer/CoreSimulator/Devices/75D60431-9192-4544-8EE9-6D7F612A7471/data/Containers/Bundle/Application/C6FF8F08-0356-477C-B543-34E244171BB0/The_Juice.app/System.IO.Compression.Brotli.dll [External]
Loaded assembly: /Users/jason/Library/Developer/CoreSimulator/Devices/75D60431-9192-4544-8EE9-6D7F612A7471/data/Containers/Bundle/Application/C6FF8F08-0356-477C-B543-34E244171BB0/The_Juice.app/System.Threading.Channels.dll [External]
Loaded assembly: /Users/jason/Library/Developer/CoreSimulator/Devices/75D60431-9192-4544-8EE9-6D7F612A7471/data/Containers/Bundle/Application/C6FF8F08-0356-477C-B543-34E244171BB0/The_Juice.app/System.Net.NetworkInformation.dll [External]
Loaded assembly: /Users/jason/Library/Developer/CoreSimulator/Devices/75D60431-9192-4544-8EE9-6D7F612A7471/data/Containers/Bundle/Application/C6FF8F08-0356-477C-B543-34E244171BB0/The_Juice.app/System.Reflection.Emit.dll [External]
Loaded assembly: /Users/jason/Library/Developer/CoreSimulator/Devices/75D60431-9192-4544-8EE9-6D7F612A7471/data/Containers/Bundle/Application/C6FF8F08-0356-477C-B543-34E244171BB0/The_Juice.app/System.Runtime.Loader.dll [External]
Loaded assembly: /Users/jason/Library/Developer/CoreSimulator/Devices/75D60431-9192-4544-8EE9-6D7F612A7471/data/Containers/Bundle/Application/C6FF8F08-0356-477C-B543-34E244171BB0/The_Juice.app/System.Linq.Expressions.dll [External]
Loaded assembly: /Users/jason/Library/Developer/CoreSimulator/Devices/75D60431-9192-4544-8EE9-6D7F612A7471/data/Containers/Bundle/Application/C6FF8F08-0356-477C-B543-34E244171BB0/The_Juice.app/System.ComponentModel.TypeConverter.dll [External]
Loaded assembly: /Users/jason/Library/Developer/CoreSimulator/Devices/75D60431-9192-4544-8EE9-6D7F612A7471/data/Containers/Bundle/Application/C6FF8F08-0356-477C-B543-34E244171BB0/The_Juice.app/System.Drawing.Primitives.dll [External]
Loaded assembly: /Users/jason/Library/Developer/CoreSimulator/Devices/75D60431-9192-4544-8EE9-6D7F612A7471/data/Containers/Bundle/Application/C6FF8F08-0356-477C-B543-34E244171BB0/The_Juice.app/System.Runtime.Serialization.Formatters.dll [External]
Loaded assembly: /Users/jason/Library/Developer/CoreSimulator/Devices/75D60431-9192-4544-8EE9-6D7F612A7471/data/Containers/Bundle/Application/C6FF8F08-0356-477C-B543-34E244171BB0/The_Juice.app/System.Resources.Writer.dll [External]
Loaded assembly: /Users/jason/Library/Developer/CoreSimulator/Devices/75D60431-9192-4544-8EE9-6D7F612A7471/data/Containers/Bundle/Application/C6FF8F08-0356-477C-B543-34E244171BB0/The_Juice.app/System.Xml.XDocument.dll [External]
Loaded assembly: /Users/jason/Library/Developer/CoreSimulator/Devices/75D60431-9192-4544-8EE9-6D7F612A7471/data/Containers/Bundle/Application/C6FF8F08-0356-477C-B543-34E244171BB0/The_Juice.app/System.Private.Xml.Linq.dll [External]
Loaded assembly: /Users/jason/Library/Developer/CoreSimulator/Devices/75D60431-9192-4544-8EE9-6D7F612A7471/data/Containers/Bundle/Application/C6FF8F08-0356-477C-B543-34E244171BB0/The_Juice.app/Microsoft.Extensions.Logging.Abstractions.dll [External]
Loaded assembly: /Users/jason/Library/Developer/CoreSimulator/Devices/75D60431-9192-4544-8EE9-6D7F612A7471/data/Containers/Bundle/Application/C6FF8F08-0356-477C-B543-34E244171BB0/The_Juice.app/Microsoft.Extensions.DependencyInjection.Abstractions.dll [External]
Loaded assembly: /Users/jason/Library/Developer/CoreSimulator/Devices/75D60431-9192-4544-8EE9-6D7F612A7471/data/Containers/Bundle/Application/C6FF8F08-0356-477C-B543-34E244171BB0/The_Juice.app/Microsoft.Maui.Essentials.dll [External]
Loaded assembly: /Users/jason/Library/Developer/CoreSimulator/Devices/75D60431-9192-4544-8EE9-6D7F612A7471/data/Containers/Bundle/Application/C6FF8F08-0356-477C-B543-34E244171BB0/The_Juice.app/System.Console.dll [External]
Loaded assembly: /Users/jason/Library/Developer/CoreSimulator/Devices/75D60431-9192-4544-8EE9-6D7F612A7471/data/Containers/Bundle/Application/C6FF8F08-0356-477C-B543-34E244171BB0/The_Juice.app/Microsoft.Extensions.Configuration.Abstractions.dll [External]
Loaded assembly: /Users/jason/Library/Developer/CoreSimulator/Devices/75D60431-9192-4544-8EE9-6D7F612A7471/data/Containers/Bundle/Application/C6FF8F08-0356-477C-B543-34E244171BB0/The_Juice.app/Microsoft.Extensions.Primitives.dll [External]
Loaded assembly: /Users/jason/Library/Developer/CoreSimulator/Devices/75D60431-9192-4544-8EE9-6D7F612A7471/data/Containers/Bundle/Application/C6FF8F08-0356-477C-B543-34E244171BB0/The_Juice.app/Microsoft.Extensions.Configuration.dll [External]
Loaded assembly: /Users/jason/Library/Developer/CoreSimulator/Devices/75D60431-9192-4544-8EE9-6D7F612A7471/data/Containers/Bundle/Application/C6FF8F08-0356-477C-B543-34E244171BB0/The_Juice.app/Microsoft.Extensions.Logging.dll [External]
Loaded assembly: /Users/jason/Library/Developer/CoreSimulator/Devices/75D60431-9192-4544-8EE9-6D7F612A7471/data/Containers/Bundle/Application/C6FF8F08-0356-477C-B543-34E244171BB0/The_Juice.app/Microsoft.Extensions.Options.dll [External]
Loaded assembly: /Users/jason/Library/Developer/CoreSimulator/Devices/75D60431-9192-4544-8EE9-6D7F612A7471/data/Containers/Bundle/Application/C6FF8F08-0356-477C-B543-34E244171BB0/The_Juice.app/Microsoft.Extensions.DependencyInjection.dll [External]
Loaded assembly: /Users/jason/Library/Developer/CoreSimulator/Devices/75D60431-9192-4544-8EE9-6D7F612A7471/data/Containers/Bundle/Application/C6FF8F08-0356-477C-B543-34E244171BB0/The_Juice.app/CommunityToolkit.Maui.MediaElement.dll [External]
2023-03-10 10:22:34.783962-0500 The_Juice[25629:680214] Could not register the assembly 'Microsoft.Maui.Controls': System.TypeLoadException: Could not resolve type with token 010000b9 from typeref (expected class 'Microsoft.Maui.Graphics.Platform.PlatformGraphicsView' in assembly 'Microsoft.Maui.Graphics, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null')
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at Registrar.DynamicRegistrar.CollectTypes(Assembly assembly)
   at Registrar.Registrar.RegisterAssembly(Assembly assembly)
2023-03-10 10:22:34.790368-0500 The_Juice[25629:680214] Could not register the assembly 'Microsoft.Maui': System.TypeLoadException: Could not resolve type with token 010000b9 from typeref (expected class 'Microsoft.Maui.Graphics.Platform.PlatformGraphicsView' in assembly 'Microsoft.Maui.Graphics, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null')
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at Registrar.DynamicRegistrar.CollectTypes(Assembly assembly)
   at Registrar.Registrar.RegisterAssembly(Assembly assembly)
Resolved pending breakpoint for 'The_Juice.Program.Main(System.String[])' to C:\Users\user\source\repos\The_Juice_Maui\The_Juice\Platforms\iOS\Program.cs:10 [0x00000].
Loaded assembly: data-0x7fb8c2af0000 [External]
Loaded assembly: data-0x7fb8c2ab3000 [External]
Loaded assembly: /Users/jason/Library/Developer/CoreSimulator/Devices/75D60431-9192-4544-8EE9-6D7F612A7471/data/Containers/Bundle/Application/C6FF8F08-0356-477C-B543-34E244171BB0/The_Juice.app/netstandard.dll [External]
Resolved pending breakpoint for 'Xamarin.HotReload.HotReloadAgent.BreakpointSendToIde(System.String)' to D:\a\_work\1\s\HotReload\Source\Xamarin.HotReload.Agent\HotReloadAgent.cs:423 [0x00000].
Loaded assembly: /Users/jason/Library/Developer/CoreSimulator/Devices/75D60431-9192-4544-8EE9-6D7F612A7471/data/Containers/Bundle/Application/C6FF8F08-0356-477C-B543-34E244171BB0/The_Juice.app/System.Text.Json.dll [External]
Loaded assembly: /Users/jason/Library/Developer/CoreSimulator/Devices/75D60431-9192-4544-8EE9-6D7F612A7471/data/Containers/Bundle/Application/C6FF8F08-0356-477C-B543-34E244171BB0/The_Juice.app/System.Text.Encodings.Web.dll [External]
Resolved pending breakpoint for 'Xamarin.HotReload.HotReloadAgent.BreakpointCheckpoint()' to D:\a\_work\1\s\HotReload\Source\Xamarin.HotReload.Agent\HotReloadAgent.cs:418 [0x00000].
2023-03-10 10:22:36.117424-0500 The_Juice[25629:680214] SecTaskLoadEntitlements failed error=22 cs_flags=200, pid=25629
2023-03-10 10:22:36.119809-0500 The_Juice[25629:680214] SecTaskCopyDebugDescription: The_Juice[25629]/0#-1 LF=0
2023-03-10 10:22:36.207082-0500 The_Juice[25629:680214] SecTaskLoadEntitlements failed error=22 cs_flags=200, pid=25629
2023-03-10 10:22:36.207645-0500 The_Juice[25629:680214] SecTaskCopyDebugDescription: The_Juice[25629]/0#-1 LF=0
**System.TypeInitializationException:** 'The type initializer for 'Microsoft.Maui.Controls.Shapes.Shape' threw an exception.'
```

**Comment by philm001** [comment]
ANy update on this?

**Comment by philm001** [comment]
Hello?

**Comment by philm001** [comment]
I thought about downgrading to .Net 6 but I have a media element that requires .Net 7

**Comment by philm001** [comment]
Was that helpful?

**Comment by philm001** [comment]
Any update on this? Still waiting....

**Comment by samhouts** [comment]
This individual had a similar error message, but it went away either after upgrade or after creating a new project and (theoretically) resolving whatever corruption was in the previous project. https://github.com/dotnet/maui/issues/13379#issuecomment-1436059251

**Comment by philm001** [comment]
Thank you, I will take a look at it.

**Comment by mattleibow** [comment]
Is this issue still happening?

Looking at the stack trace I wonder if something was sticking around with hot reload or hot restart so the assemblies were out of sync with some dlls. Or maybe there was an API change in .NET 7 when compared to .NET 6.

**Comment by philm001** [comment]
Hey guys sorry, for not updating, I will have to check and get back you soon

**Comment by philm001** [comment]
Hello all,

I am currently setting up my environment again as I had a few changes. I tried building it and this error did not appear. Not sure why . I did get a few other ones that I am currently investigating but for now, I am going to close this issue. Unless it comes back up again and then will re-open
