### ISSUE TITLE
MAUI Cannot Interact With HID SmartCards on MacOS

### ISSUE THREAD

**Issue by igalfsg** [dotnet/maui#13855]
### Description

When Trying to interact with a SmartCard over USB, I get the following exception in MAUI MacOS (I have tested it on windows and it works and on Mac it works on a regular .NET console app)
```

Operation is not supported on this platform.
   at Yubico.Core.Devices.Hid.HidDeviceListener.Create()
   at Yubico.YubiKey.YubiKeyDeviceListener..ctor()
   at Yubico.YubiKey.YubiKeyDeviceListener.<>c.<.cctor>b__36_0()
   at System.Lazy`1[[Yubico.YubiKey.YubiKeyDeviceListener, Yubico.YubiKey, Version=1.6.1.0, Culture=neutral, PublicKeyToken=fdb9ca4403bc032c]].ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1[[Yubico.YubiKey.YubiKeyDeviceListener, Yubico.YubiKey, Version=1.6.1.0, Culture=neutral, PublicKeyToken=fdb9ca4403bc032c]].ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1[[Yubico.YubiKey.YubiKeyDeviceListener, Yubico.YubiKey, Version=1.6.1.0, Culture=neutral, PublicKeyToken=fdb9ca4403bc032c]].CreateValue()
   at System.Lazy`1[[Yubico.YubiKey.YubiKeyDeviceListener, Yubico.YubiKey, Version=1.6.1.0, Culture=neutral, PublicKeyToken=fdb9ca4403bc032c]].get_Value()
   at Yubico.YubiKey.YubiKeyDeviceListener.get_Instance()
   at Yubico.YubiKey.YubiKeyDevice.FindByTransport(Transport transport)
   at Yubico.YubiKey.YubiKeyDevice.FindAll()
   at EZSmartCard.Services.SmartCardService.GetConnectedSCSerialNumbers() in /Users/igalflegmann/Documents/SSHMan/SSHManWeb/EZSmartCard/Services/SmartCardService.cs:line 166
   at EZSmartCard.Components.RegularAuthSCEnrollmentComponent.GetSCSerialNumberAsync() in /Users/igalflegmann/Documents/SSHMan/SSHManWeb/EZSmartCard/Components/RegularAuthSCEnrollmentComponent.razor.cs:line 130
   at EZSmartCard.Components.RegularAuthSCEnrollmentComponent.GetAvailableDomainsAsync() in /Users/igalflegmann/Documents/SSHMan/SSHManWeb/EZSmartCard/Components/RegularAuthSCEnrollmentComponent.razor.cs:line 57
   at EZSmartCard.Components.RegularAuthSCEnrollmentComponent.OnInitializedAsync() in /Users/igalflegmann/Documents/SSHMan/SSHManWeb/EZSmartCard/Components/RegularAuthSCEnrollmentComponent.razor.cs:line 42
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

Is this a known Issue? if so is there a way to interact with HID devices with MAUI by writing native code or something?

### Steps to Reproduce

1.  Run this project on Windows, Then Run on MAC

### Link to public reproduction project repository

https://github.com/igalfsg/MAUIHID

### Version with bug

7.0 (current)

### Last version that worked well

6.0.312

### Affected platforms

macOS

### Affected platform versions

MacOS

**Comment by igalfsg** [comment]
just added a demo repo https://github.com/igalfsg/MAUIHID

**Comment by drasticactions** [comment]
@igalfsg Yubico.YubiKey doesn't work on Mac Catalyst (Which is what MAUI uses for its MacOS platform layer). I've created a reproduction project for it here: https://github.com/drasticactions/MauiRepros/tree/main/MacOSYubi

Under Catalyst, it throws an exception saying the platform is not supported. It's the same error you would get under iOS.

<img width="969" alt="スクリーンショット 2023-03-13 18 03 12" src="https://user-images.githubusercontent.com/898335/224655954-6bb55bbf-0807-465b-b716-80a9951dd517.png">

It works for macOS AppKit apps, and the console (since that's platform-independent)

IMO this isn't a MAUI bug, you should talk to the library owners instead (https://github.com/Yubico/Yubico.NET.SDK/)

**Comment by igalfsg** [comment]
Thanks @drasticactions :)
