### ISSUE TITLE
Microsoft.CognitiveServices.Speech Crash on iOS

### ISSUE THREAD

**Issue by Suprndm** [dotnet/maui#13878]
### Description

I've installed Microsoft.CognitiveServices.Speech package 1.26.0, to speak some sentences on my MAUI app.

on Windows and Android, works. on iOS in crashes.

On the line : SpeechConfig.FromSubscription(subscriptionKey, subscriptionRegion);

### Steps to Reproduce

1. Add nuget package Microsoft.CognitiveServices.Speech
2. Call var config = SpeechConfig.FromSubscription(subscriptionKey, subscriptionRegion);

### Link to public reproduction project repository

https://github.com/Suprndm/speech-crash-maui-ios

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 16.0

### Did you find any workaround?

Not yet

### Relevant log output

```shell
An error occurred: '__Internal'. Callstack: '   at Microsoft.CognitiveServices.Speech.SpeechConfig.FromSubscription(String subscriptionKey, String region)
[...]
 at Foundation.NSAsyncSynchronizationContextDispatcher.Apply()
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName)
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)
   at Learning.WindowsApp.Program.Main(String[] args) in ************\Learning.WindowsApp\Platforms\iOS\Program.cs:line 13
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)'
The app has been terminated.
```
```

**Comment by drasticactions** [comment]
@Suprndm Can you check out this project and run "SpeechApple" with your tokens here? https://github.com/drasticactions/MauiRepros/blob/main/SpeechApple/AppDelegate.cs#L34-L35

I couldn't repro your exception in your project nor mine with tokens I created, and going by that stacktrace I have a feeling the issue is with the library rather than anything contained in this repository.
