### ISSUE TITLE
TableView blows up on iOS/Catalyst when using SceneDelegate

### ISSUE THREAD

**Issue by drasticactions** [dotnet/maui#13948]
### Description

When you use a SceneDelegate to enable multiple iOS and Catalyst windows, TableView will throw NREs. 

https://github.com/dotnet/maui/blob/639816d2113a37dd7da0d6a9f0b6d54cbef2fcdf/src/Compatibility/Core/src/iOS/Renderers/TableViewRenderer.cs#LL131C3-L131C3

UIScreen.MainScreen is used, which can work for a single instance application, but will fail if you enable the SceneDelegate.

### Steps to Reproduce

1. Run the Attached TableView example on Catalyst, and open a new window.

### Link to public reproduction project repository

https://github.com/drasticactions/MauiRepros/tree/main/TableViewCatalyst

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

All

### Did you find any workaround?

Don't use the SceneDelegate, but this breaks multiple window support.

### Relevant log output

```shell
Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Maui.Controls.Handlers.Compatibility.TableViewRenderer.UpdateNativeWidget()
   at Microsoft.Maui.Controls.Handlers.Compatibility.VisualElementRenderer`1[[Microsoft.Maui.Controls.TableView, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnSizeChanged(Object sender, EventArgs e)
   at Microsoft.Maui.Controls.VisualElement.UpdateBoundsComponents(Rect bounds)
   at Microsoft.Maui.Controls.VisualElement.set_Frame(Rect value)
   at Microsoft.Maui.Controls.VisualElement.ArrangeOverride(Rect bounds)
   at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IView.Arrange(Rect bounds)
   at Microsoft.Maui.Controls.Compatibility.Layout.LayoutChildIntoBoundingRegion(VisualElement child, Rect region)
   at Microsoft.Maui.Controls.Page.LayoutChildren(Double x, Double y, Double width, Double height)
   at Microsoft.Maui.Controls.Page.UpdateChildrenLayout()
   at Microsoft.Maui.Controls.Page.OnSizeAllocated(Double width, Double height)
   at Microsoft.Maui.Controls.VisualElement.SizeAllocated(Double width, Double height)
   at Microsoft.Maui.Controls.VisualElement.UpdateBoundsComponents(Rect bounds)
   at Microsoft.Maui.Controls.VisualElement.set_Frame(Rect value)
   at Microsoft.Maui.Controls.ContentPage.Microsoft.Maui.IContentView.CrossPlatformArrange(Rect bounds)
   at Microsoft.Maui.Platform.ContentView.LayoutSubviews()
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName)
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)
   at TableViewCatalyst.Program.Main(String[] args) in /Users/drasticactions/Developer/Work/MauiRepros/TableViewCatalyst/Platforms/MacCatalyst/Program.cs:line 13
```

**Comment by ooikengsiang** [comment]
@drasticactions Your repo doesn't include any SceneDelegate or call to create multi-windows.

**Comment by homeyf** [comment]
Verified this issue with Visual Studio Enterprise 17.6.7 (build 417). Not repro on iOS platform.
![image](https://github.com/dotnet/maui/assets/82450723/4f8e2b2d-b07d-4003-920d-7a6ddcb580e6)
