### ISSUE TITLE
Android.Util.AndroidRuntimeException: Only the original thread that created a view hierarchy can touch its views.

### ISSUE THREAD

**Issue by SorenBech2** [dotnet/maui#14128]
### Description

An app that based on a selection made through a picker list, displays the object information - including the object image – of the selected object. 

Picking an item for the 2nd time the image does not show and the below error message is generated. (The error does not occur when code is compiled to windows which leads to a suspicion of a bug in the Android generated code.)
For full description please see below. 
[Maui Databinding issue.docx](https://github.com/dotnet/maui/files/11040323/Maui.Databinding.issue.docx)

### Steps to Reproduce

Debug the code in the repository (link below).

Picking an item for the 2nd time the image does not show and the below error message is generated.

OBS: To reproduce you need to pick a subject and then pick a different subject from the picker list.

When a 3rd subject is selected everything works fine (as well as for the 4th, 5th, and so on) The error only occur for the 2nd selection! (In a few tests, this error occurs after 3 selections not 2, but predominantly after 2 selections).
It is unclear to me which code executed in another thread but the UI thread creates the error. I have included a check on the thread which indicated the code is executed in the UI thread - as well as tried to include the code in a MainThread.BeginInvokeOnMainThread without any impact on the error.

### Link to public reproduction project repository

https://github.com/SorenBech2/DataBindingTest

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12.1 - API 32 & 13.0 API 33

### Did you find any workaround?

No workaround found. Tried to include the code in a MainThread.BeginInvokeOnMainThread without any impact on the error.

### Relevant log output

```shell
[0:] Microsoft.Maui.StreamImageSourceService: Warning: Unable to load image stream.

Android.Util.AndroidRuntimeException: Only the original thread that created a view hierarchy can touch its views.
   at Java.Interop.JniEnvironment.StaticMethods.CallStaticVoidMethod(JniObjectReference type, JniMethodInfo method, JniArgumentValue* args) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/obj/Release/net7.0/JniEnvironment.g.cs:line 13250
   at Java.Interop.JniPeerMembers.JniStaticMethods.InvokeVoidMethod(String encodedMember, JniArgumentValue* parameters) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniStaticMethods.cs:line 97
   at Microsoft.Maui.PlatformInterop.LoadImageFromStream(ImageView imageView, Stream inputStream, IImageLoaderCallback callback) in D:\a\_work\1\s\src\Core\src\obj\Release
et7.0-android\generated\src\Microsoft.Maui.PlatformInterop.cs:line 443
   at Microsoft.Maui.StreamImageSourceService.LoadDrawableAsync(IImageSource imageSource, ImageView imageView, CancellationToken cancellationToken) in D:\a\_work\1\s\src\Core\src\ImageSources\StreamImageSourceService\StreamImageSourceService.Android.cs:line 28
  --- End of managed Android.Util.AndroidRuntimeException stack trace ---
android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
	at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:9461)
	at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:1825)
	at android.view.View.requestLayout(View.java:25757)
	at android.view.View.requestLayout(View.java:25757)
	at android.view.View.requestLayout(View.java:25757)
	at android.view.View.requestLayout(View.java:25757)
	at android.view.View.requestLayout(View.java:25757)
	at android.view.View.requestLayout(View.java:25757)
	at android.view.View.requestLayout(View.java:25757)
	at androidx.drawerlayout.widget.DrawerLayout.requestLayout(DrawerLayout.java:1353)
	at android.view.View.requestLayout(View.java:25757)
	at android.view.View.requestLayout(View.java:25757)
	at android.view.View.requestLayout(View.java:25757)
	at android.view.View.requestLayout(View.java:25757)
	at android.view.View.requestLayout(View.java:25757)
	at android.view.View.requestLayout(View.java:25757)
	at androidx.recyclerview.widget.RecyclerView.requestLayout(RecyclerView.java:4586)
	at android.view.View.requestLayout(View.java:25757)
	at android.view.View.requestLayout(View.java:25757)
	at android.view.View.requestLayout(View.java:25757)
	at android.view.View.requestLayout(View.java:25757)
	at androidx.core.widget.NestedScrollView.requestLayout(NestedScrollView.java:2075)
	at android.view.View.requestLayout(View.java:25757)
	at android.view.View.requestLayout(View.java:25757)
	at android.view.View.requestLayout(View.java:25757)
	at android.widget.ImageView.setImageDrawable(ImageView.java:601)
	at androidx.appcompat.widget.AppCompatImageView.setImageDrawable(AppCompatImageView.java:112)
	at com.microsoft.maui.glide.MauiCustomViewTarget.onResourceCleared(MauiCustomViewTarget.java:30)
	at com.bumptech.glide.request.target.CustomViewTarget.onLoadCleared(CustomViewTarget.java:210)
	at com.bumptech.glide.request.SingleRequest.clear(SingleRequest.java:337)
	at com.bumptech.glide.request.ErrorRequestCoordinator.clear(ErrorRequestCoordinator.java:48)
	at com.bumptech.glide.manager.RequestTracker.clearAndRemove(RequestTracker.java:70)
	at com.bumptech.glide.RequestManager.untrack(RequestManager.java:660)
	at com.bumptech.glide.Glide.removeFromManagers(Glide.java:913)
	at com.bumptech.glide.RequestManager.untrackOrDelegate(RequestManager.java:647)
	at com.bumptech.glide.RequestManager.clear(RequestManager.java:624)
	at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:811)
	at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:780)
	at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:771)
	at com.microsoft.maui.PlatformInterop.prepare(PlatformInterop.java:229)
	at com.microsoft.maui.PlatformInterop.loadInto(PlatformInterop.java:234)
	at com.microsoft.maui.PlatformInterop.loadImageFromStream(PlatformInterop.java:265)

  --- End of managed Android.Util.AndroidRuntimeException stack trace ---
android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
	at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:9461)
	at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:1825)
	at android.view.View.requestLayout(View.java:25757)
	at android.view.View.requestLayout(View.java:25757)
	at android.view.View.requestLayout(View.java:25757)
	at android.view.View.requestLayout(View.java:25757)
	at android.view.View.requestLayout(View.java:25757)
	at android.view.View.requestLayout(View.java:25757)
	at android.view.View.requestLayout(View.java:25757)
	at androidx.drawerlayout.widget.DrawerLayout.requestLayout(DrawerLayout.java:1353)
	at android.view.View.requestLayout(View.java:25757)
	at android.view.View.requestLayout(View.java:25757)
	at android.view.View.requestLayout(View.java:25757)
	at android.view.View.requestLayout(View.java:25757)
	at android.view.View.requestLayout(View.java:25757)
	at android.view.View.requestLayout(View.java:25757)
	at androidx.recyclerview.widget.RecyclerView.requestLayout(RecyclerView.java:4586)
	at android.view.View.requestLayout(View.java:25757)
	at android.view.View.requestLayout(View.java:25757)
	at android.view.View.requestLayout(View.java:25757)
	at android.view.View.requestLayout(View.java:25757)
	at androidx.core.widget.NestedScrollView.requestLayout(NestedScrollView.java:2075)
	at android.view.View.requestLayout(View.java:25757)
	at android.view.View.requestLayout(View.java:25757)
	at android.view.View.requestLayout(View.java:25757)
	at android.widget.ImageView.setImageDrawable(ImageView.java:601)
	at androidx.appcompat.widget.AppCompatImageView.setImageDrawable(AppCompatImageView.java:112)
	at com.microsoft.maui.glide.MauiCustomViewTarget.onResourceCleared(MauiCustomViewTarget.java:30)
	at com.bumptech.glide.request.target.CustomViewTarget.onLoadCleared(CustomViewTarget.java:210)
	at com.bumptech.glide.request.SingleRequest.clear(SingleRequest.java:337)
	at com.bumptech.glide.request.ErrorRequestCoordinator.clear(ErrorRequestCoordinator.java:48)
	at com.bumptech.glide.manager.RequestTracker.clearAndRemove(RequestTracker.java:70)
	at com.bumptech.glide.RequestManager.untrack(RequestManager.java:660)
	at com.bumptech.glide.Glide.removeFromManagers(Glide.java:913)
	at com.bumptech.glide.RequestManager.untrackOrDelegate(RequestManager.java:647)
	at com.bumptech.glide.RequestManager.clear(RequestManager.java:624)
	at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:811)
	at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:780)
	at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:771)
	at com.microsoft.maui.PlatformInterop.prepare(PlatformInterop.java:229)
	at com.microsoft.maui.PlatformInterop.loadInto(PlatformInterop.java:234)
	at com.microsoft.maui.PlatformInterop.loadImageFromStream(PlatformInterop.java:265)
```

**Comment by jstedfast** [comment]
Reproduced and definitely seems to be similar to the issue I've been working on fixing.

Will test with my fix momentarily.

**Comment by jstedfast** [comment]
First I need to figure out how to write a unit test and then I have to get my patch reviewed/accepted/merged and then a release has to be made (which I believe is done on a fixed schedule and I'm not sure what that schedule is - I'm new to the team and am temporarily helping them out).

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 1.0. Not repro on android platform with sample project.
[DataBinding.zip](https://github.com/dotnet/maui/files/11783785/DataBinding.zip)
![14128](https://github.com/dotnet/maui/assets/77434865/a8414a32-abb3-4c61-9fb8-8362bb1a06cb)

**Comment by SorenBech2** [comment]
Thank for your reply to this issue. The issue has not been resolved using the latest version of Visual Studio
Microsoft Visual Studio Community 2022 (64-bit) – Current Version 17.6.5

Selecting an image minimum TWICE in the attached test app
(SorenBech2/DataBindingTest (github.com)<https://github.com/SorenBech2/DataBindingTest> (same app/code as initially attached)
yields the below message.

android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
       at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:11586)
       at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:2648)
       at android.view.View.requestLayout(View.java:27612)
       at android.view.View.requestLayout(View.java:27612)
       at android.view.View.requestLayout(View.java:27612)
       at android.view.View.requestLayout(View.java:27612)
       at android.view.View.requestLayout(View.java:27612)
       at android.view.View.requestLayout(View.java:27612)
       at android.view.View.requestLayout(View.java:27612)
       at androidx.drawerlayout.widget.DrawerLayout.requestLayout(DrawerLayout.java:1353)
       at android.view.View.requestLayout(View.java:27612)
       at android.view.View.requestLayout(View.java:27612)
       at android.view.View.requestLayout(View.java:27612)
       at android.view.View.requestLayout(View.java:27612)
       at android.view.View.requestLayout(View.java:27612)
       at android.view.View.requestLayout(View.java:27612)
       at androidx.recyclerview.widget.RecyclerView.requestLayout(RecyclerView.java:4586)
       at android.view.View.requestLayout(View.java:27612)
       at android.view.View.requestLayout(View.java:27612)
       at android.view.View.requestLayout(View.java:27612)
       at android.view.View.requestLayout(View.java:27612)
       at androidx.core.widget.NestedScrollView.requestLayout(NestedScrollView.java:2075)
       at android.view.View.requestLayout(View.java:27612)
       at android.view.View.requestLayout(View.java:27612)
       at android.view.View.requestLayout(View.java:27612)
       at android.widget.ImageView.setImageDrawable(ImageView.java:602)
       at androidx.appcompat.widget.AppCompatImageView.setImageDrawable(AppCompatImageView.java:112)
       at com.microsoft.maui.glide.MauiCustomViewTarget.onResourceCleared(MauiCustomViewTarget.java:30)
       at com.bumptech.glide.request.target.CustomViewTarget.onLoadCleared(CustomViewTarget.java:210)
       at com.bumptech.glide.request.SingleRequest.clear(SingleRequest.java:337)
       at com.bumptech.glide.request.ErrorRequestCoordinator.clear(ErrorRequestCoordinator.java:48)
       at com.bumptech.glide.manager.RequestTracker.clearAndRemove(RequestTracker.java:70)
       at com.bumptech.glide.RequestManager.untrack(RequestManager.java:660)
       at com.bumptech.glide.RequestManager.untrackOrDelegate(RequestManager.java:628)
       at com.bumptech.glide.RequestManager.clear(RequestManager.java:624)
       at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:811)
       at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:780)
       at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:771)
       at com.microsoft.maui.PlatformInterop.prepare(PlatformInterop.java:229)
       at com.microsoft.maui.PlatformInterop.loadInto(PlatformInterop.java:234)
       at com.microsoft.maui.PlatformInterop.loadImageFromStream(PlatformInterop.java:265)

Med venlig hilsen / Best regards

Søren Bech
Sigridsvej 17B
DK-2900 Hellerup
+45 4076 5050
***@***.***
