### ISSUE TITLE
Blazor Hybrid Windows: Window was already activated when minimize and restore from taskbar

### ISSUE THREAD

**Issue by samhouts** [dotnet/maui#14142]
### Description

I have a Blazor Hybrid app, debugging in Windows. I'm running against maui main.

 If I minimize the app and then try to restore it again by clicking on the icon in the taskbar, I get an instacrash:

```
System.InvalidOperationException
  HResult=0x80131509
  Message=Window was already activated
  Source=Microsoft.Maui.Controls
  StackTrace:
   at Microsoft.Maui.Controls.Window.Microsoft.Maui.IWindow.Activated() in C:\src\github\maui\src\Controls\src\Core\HandlerImpl\Window\Window.Impl.cs:line 491
   at Microsoft.Maui.LifecycleEvents.AppHostBuilderExtensions.<>c.<OnConfigureLifeCycle>b__2_2(Window window, WindowActivatedEventArgs args) in C:\src\github\maui\src\Core\src\Hosting\LifecycleEvents\AppHostBuilderExtensions.Windows.cs:line 32
   at Microsoft.Maui.MauiWinUIWindow.<>c__DisplayClass7_0.<OnActivated>b__1(OnActivated del) in C:\src\github\maui\src\Core\src\Platform\Windows\MauiWinUIWindow.cs:line 51
   at Microsoft.Maui.LifecycleEvents.LifecycleEventServiceExtensions.InvokeLifecycleEvents[TDelegate](IServiceProvider services, Action`1 action) in C:\src\github\maui\src\Core\src\LifecycleEvents\LifecycleEventServiceExtensions.cs:line 31
   at Microsoft.Maui.MauiWinUIWindow.OnActivated(Object sender, WindowActivatedEventArgs args) in C:\src\github\maui\src\Core\src\Platform\Windows\MauiWinUIWindow.cs:line 51
   at ABI.Windows.Foundation.TypedEventHandler`2.Do_Abi_Invoke[TSenderAbi,TResultAbi](Void* thisPtr, TSenderAbi sender, TResultAbi args)
```

### Steps to Reproduce

1. File > New MAUI Blazor
2. Run in Windows
3. Minimize
4. Restore
5. 💥

### Link to public reproduction project repository

try vigilant guide

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

7.0 (current)

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

windows10.0.19041.0

**Comment by samhouts** [comment]
Related? https://github.com/dotnet/maui/pull/14138

**Comment by rachelkang** [comment]
@samhouts is this only happening with the Blazor hybrid template? Or are you running into this issue with any of the other templates?

**Comment by samhouts** [comment]
weeeelllll my other templates disappeared, so I haven't checked yet. the joys of targeting main.... 😅

**Comment by PureWeen** [comment]
@samhouts this is actually an issue with WinAppSDK (can't find the original issue) 

WinUI calls Activated twice when you maximize, and we aren't debouncing that second call. 

I forgot about this when I added this exception :-)

**Comment by PureWeen** [comment]
@samhouts  here it is
https://github.com/microsoft/microsoft-ui-xaml/issues/7343

**Comment by samhouts** [comment]
Aha! So we need to touch up https://github.com/dotnet/maui/pull/13025. Thanks!!

I found a bug I found a bug 💃💃
