### ISSUE TITLE
Android crash when tapping button rendered outside of container

### ISSUE THREAD

**Issue by hartez** [dotnet/maui#14317]
This is a weird one. On Android, using this layout, click the far left of the "Crash" button - the application will crash.

```xaml
       <Grid WidthRequest="100" HorizontalOptions="Start" RowDefinitions="Auto,*,150" ColumnDefinitions="Auto,*,150" >
        <Button Grid.Column="1"
               Grid.Row="1"
               Text="Crash"
               HeightRequest="200"
               HorizontalOptions="Center" />

        <Button Grid.Column="0"
                Grid.Row="0"
                Text="Click me" />
    </Grid>
```

Stack Trace:

```
**Java.Lang.NullPointerException:** 'Loading...'

[monodroid-assembly] Shared library 'liblog' not loaded, p/invoke '__android_log_print' may fail
[MonoDroid] UNHANDLED EXCEPTION:
[MonoDroid] Java.Lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.Bitmap.setHasAlpha(boolean)' on a null object reference
[MonoDroid] 
[MonoDroid]   --- End of managed Java.Lang.NullPointerException stack trace ---
[MonoDroid] java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.Bitmap.setHasAlpha(boolean)' on a null object reference
[MonoDroid] 	at android.graphics.Bitmap.createBitmap(Bitmap.java:883)
[MonoDroid] 	at android.graphics.Bitmap.createBitmap(Bitmap.java:856)
[MonoDroid] 	at android.graphics.Bitmap.createBitmap(Bitmap.java:823)
[MonoDroid] 	at android.graphics.drawable.RippleDrawable.updateMaskShaderIfNeeded(RippleDrawable.java:769)
[MonoDroid] 	at android.graphics.drawable.RippleDrawable.drawBackgroundAndRipples(RippleDrawable.java:853)
[MonoDroid] 	at android.graphics.drawable.RippleDrawable.draw(RippleDrawable.java:693)
[MonoDroid] 	at android.view.View.getDrawableRenderNode(View.java:17428)
[MonoDroid] 	at android.view.View.drawBackground(View.java:17364)
[MonoDroid] 	at android.view.View.draw(View.java:17176)
[MonoDroid] 	at android.view.View.updateDisplayListIfDirty(View.java:16167)
[MonoDroid] 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
[MonoDroid] 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
[MonoDroid] 	at android.view.View.updateDisplayListIfDirty(View.java:16130)
[MonoDroid] 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
[MonoDroid] 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
[MonoDroid] 	at android.view.View.updateDisplayListIfDirty(View.java:16130)
[MonoDroid] 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
[MonoDroid] 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
[MonoDroid] 	at android.view.View.updateDisplayListIfDirty(View.java:16130)
[MonoDroid] 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
[MonoDroid] 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
[MonoDroid] 	at android.view.View.updateDisplayListIfDirty(View.java:16130)
[MonoDroid] 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
[MonoDroid] 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
[MonoDroid] 	at android.view.View.updateDisplayListIfDirty(View.java:16130)
[MonoDroid] 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
[MonoDroid] 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
[MonoDroid] 	at android.view.View.updateDisplayListIfDirty(View.java:16130)
[MonoDroid] 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
[MonoDroid] 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
[MonoDroid] 	at android.view.View.updateDisplayListIfDirty(View.java:16130)
[MonoDroid] 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
[MonoDroid] 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
[MonoDroid] 	at android.view.View.updateDisplayListIfDirty(View.java:16130)
[MonoDroid] 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
[MonoDroid] 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
[MonoDroid] 	at android.view.View.updateDisplayListIfDirty(View.java:16130)
[MonoDroid] 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
[MonoDroid] 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
[MonoDroid] 	at android.view.View.updateDisplayListIfDirty(View.java:16130)
[MonoDroid] 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
[MonoDroid] 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
[MonoDroid] 	at android.view.View.updateDisplayListIfDirty(View.java:16130)
[MonoDroid] 	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:648)
[MonoDroid] 	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:654)
[MonoDroid] 	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:762)
[MonoDroid] 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2800)
[MonoDroid] 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2608)
[MonoDroid] 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2215)
[MonoDroid] 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
[MonoDroid] 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6337)
[MonoDroid] 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
[MonoDroid] 	at android.view.Choreographer.doCallbacks(Choreographer.java:686)
[MonoDroid] 	at android.view.Choreographer.doFrame(Choreographer.java:621)
[MonoDroid] 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
[MonoDroid] 	at android.os.Handler.handleCallback(Handler.java:751)
[MonoDroid] 	at android.os.Handler.dispatchMessage(Handler.java:95)
[MonoDroid] 	at android.os.Looper.loop(Looper.java:154)
[MonoDroid] 	at android.app.ActivityThread.main(ActivityThread.java:6119)
[MonoDroid] 	at java.lang.reflect.Method.invoke(Native Method)
[MonoDroid] 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
[MonoDroid] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
[MonoDroid] 
[MonoDroid]   --- End of managed Java.Lang.NullPointerException stack trace ---
[MonoDroid] java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.Bitmap.setHasAlpha(boolean)' on a null object reference
[MonoDroid] 	at android.graphics.Bitmap.createBitmap(Bitmap.java:883)
[MonoDroid] 	at android.graphics.Bitmap.createBitmap(Bitmap.java:856)
[MonoDroid] 	at android.graphics.Bitmap.createBitmap(Bitmap.java:823)
[MonoDroid] 	at android.graphics.drawable.RippleDrawable.updateMaskShaderIfNeeded(RippleDrawable.java:769)
[MonoDroid] 	at android.graphics.drawable.RippleDrawable.drawBackgroundAndRipples(RippleDrawable.java:853)
[MonoDroid] 	at android.graphics.drawable.RippleDrawable.draw(RippleDrawable.java:693)
[MonoDroid] 	at android.view.View.getDrawableRenderNode(View.java:17428)
[MonoDroid] 	at android.view.View.drawBackground(View.java:17364)
[MonoDroid] 	at android.view.View.draw(View.java:17176)
[MonoDroid] 	at android.view.View.updateDisplayListIfDirty(View.java:16167)
[MonoDroid] 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
[MonoDroid] 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
[MonoDroid] 	at android.view.View.updateDisplayListIfDirty(View.java:16130)
[MonoDroid] 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
[MonoDroid] 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
[MonoDroid] 	at android.view.View.updateDisplayListIfDirty(View.java:16130)
[MonoDroid] 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
[MonoDroid] 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
[MonoDroid] 	at android.view.View.updateDisplayListIfDirty(View.java:16130)
[MonoDroid] 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
[MonoDroid] 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
[MonoDroid] 	at android.view.View.updateDisplayListIfDirty(View.java:16130)
[MonoDroid] 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
[MonoDroid] 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
[MonoDroid] 	at android.view.View.updateDisplayListIfDirty(View.java:16130)
[MonoDroid] 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
[MonoDroid] 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
[MonoDroid] 	at android.view.View.updateDisplayListIfDirty(View.java:16130)
[MonoDroid] 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
[MonoDroid] 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
[MonoDroid] 	at android.view.View.updateDisplayListIfDirty(View.java:16130)
[MonoDroid] 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
[MonoDroid] 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
[MonoDroid] 	at android.view.View.updateDisplayListIfDirty(View.java:16130)
[MonoDroid] 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
[MonoDroid] 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
[MonoDroid] 	at android.view.View.updateDisplayListIfDirty(View.java:16130)
[MonoDroid] 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
[MonoDroid] 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
[MonoDroid] 	at android.view.View.updateDisplayListIfDirty(View.java:16130)
[MonoDroid] 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
[MonoDroid] 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
[MonoDroid] 	at android.view.View.updateDisplayListIfDirty(View.java:16130)
[MonoDroid] 	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:648)
[MonoDroid] 	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:654)
[MonoDroid] 	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:762)
[MonoDroid] 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2800)
[MonoDroid] 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2608)
[MonoDroid] 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2215)
[MonoDroid] 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
[MonoDroid] 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6337)
[MonoDroid] 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
[MonoDroid] 	at android.view.Choreographer.doCallbacks(Choreographer.java:686)
[MonoDroid] 	at android.view.Choreographer.doFrame(Choreographer.java:621)
[MonoDroid] 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
[MonoDroid] 	at android.os.Handler.handleCallback(Handler.java:751)
[MonoDroid] 	at android.os.Handler.dispatchMessage(Handler.java:95)
[MonoDroid] 	at android.os.Looper.loop(Looper.java:154)
[MonoDroid] 	at android.app.ActivityThread.main(ActivityThread.java:6119)
[MonoDroid] 	at java.lang.reflect.Method.invoke(Native Method)
[MonoDroid] 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
[MonoDroid] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
[MonoDroid] 
[AndroidRuntime] FATAL EXCEPTION: main
[AndroidRuntime] Process: com.microsoft.maui.sandbox, PID: 11185
[AndroidRuntime] java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.Bitmap.setHasAlpha(boolean)' on a null object reference
[AndroidRuntime] 	at android.graphics.Bitmap.createBitmap(Bitmap.java:883)
[AndroidRuntime] 	at android.graphics.Bitmap.createBitmap(Bitmap.java:856)
[AndroidRuntime] 	at android.graphics.Bitmap.createBitmap(Bitmap.java:823)
[AndroidRuntime] 	at android.graphics.drawable.RippleDrawable.updateMaskShaderIfNeeded(RippleDrawable.java:769)
[AndroidRuntime] 	at android.graphics.drawable.RippleDrawable.drawBackgroundAndRipples(RippleDrawable.java:853)
[AndroidRuntime] 	at android.graphics.drawable.RippleDrawable.draw(RippleDrawable.java:693)
[AndroidRuntime] 	at android.view.View.getDrawableRenderNode(View.java:17428)
[AndroidRuntime] 	at android.view.View.drawBackground(View.java:17364)
[AndroidRuntime] 	at android.view.View.draw(View.java:17176)
[AndroidRuntime] 	at android.view.View.updateDisplayListIfDirty(View.java:16167)
[AndroidRuntime] 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
[AndroidRuntime] 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
[AndroidRuntime] 	at android.view.View.updateDisplayListIfDirty(View.java:16130)
[AndroidRuntime] 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
[AndroidRuntime] 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
[AndroidRuntime] 	at android.view.View.updateDisplayListIfDirty(View.java:16130)
[AndroidRuntime] 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
[AndroidRuntime] 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
[AndroidRuntime] 	at android.view.View.updateDisplayListIfDirty(View.java:16130)
[AndroidRuntime] 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
[AndroidRuntime] 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
[AndroidRuntime] 	at android.view.View.updateDisplayListIfDirty(View.java:16130)
[AndroidRuntime] 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
[AndroidRuntime] 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
[AndroidRuntime] 	at android.view.View.updateDisplayListIfDirty(View.java:16130)
[AndroidRuntime] 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
[AndroidRuntime] 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
[AndroidRuntime] 	at android.view.View.updateDisplayListIfDirty(View.java:16130)
[AndroidRuntime] 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
[AndroidRuntime] 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
[AndroidRuntime] 	at android.view.View.updateDisplayListIfDirty(View.java:16130)
[AndroidRuntime] 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
[AndroidRuntime] 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
[AndroidRuntime] 	at android.view.View.updateDisplayListIfDirty(View.java:16130)
[AndroidRuntime] 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
[AndroidRuntime] 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
[AndroidRuntime] 	at android.view.View.updateDisplayListIfDirty(View.java:16130)
[AndroidRuntime] 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
[AndroidRuntime] 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
[AndroidRuntime] 	at android.view.View.updateDisplayListIfDirty(View.java:16130)
[AndroidRuntime] 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
[AndroidRuntime] 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
[AndroidRuntime] 	at android.view.View.updateDisplayListIfDirty(View.java:16130)
[AndroidRuntime] 	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:648)
[AndroidRuntime] 	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:654)
[AndroidRuntime] 	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:762)
[AndroidRuntime] 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2800)
[AndroidRuntime] 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2608)
[AndroidRuntime] 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2215)
[AndroidRuntime] 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
[AndroidRuntime] 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6337)
[AndroidRuntime] 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
[AndroidRuntime] 	at android.view.Choreographer.doCallbacks(Choreographer.java:686)
[AndroidRuntime] 	at android.view.Choreographer.doFrame(Choreographer.java:621)
[AndroidRuntime] 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
[AndroidRuntime] 	at android.os.Handler.handleCallback(Handler.java:751)
[AndroidRuntime] 	at android.os.Handler.dispatchMessage(Handler.java:95)
[AndroidRuntime] 	at android.os.Looper.loop(Looper.java:154)
[AndroidRuntime] 	at android.app.ActivityThread.main(ActivityThread.java:6119)
[AndroidRuntime] 	at java.lang.reflect.Method.invoke(Native Method)
[AndroidRuntime] 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
[AndroidRuntime] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by Chloelong123** [comment]
Verified this issue with Visual Studio Enterprise 17.7.0 Preview 6.0. Not repro on template Android Application.
![image](https://github.com/dotnet/maui/assets/109071485/ccd1f213-7073-4cab-9999-1ade19841414)
