### ISSUE TITLE
.Net Maui 7 self signed certificates not work 

### ISSUE THREAD

**Issue by maza70** [dotnet/maui#14555]
### Description

I migrate a xamarin project to maui 7.0.81 now i can't accept self singed certificates with the HttpClientHandler.
The ServerCertificateCustomValidationCallback is not called if the ssl certificate is untrusted.
I use the HttpClient to make a webdav call like (propfind), for this i must set the  <UseNativeHttpHandler>false</UseNativeHttpHandler>.  If i set <UseNativeHttpHandler>true</UseNativeHttpHandler> then the PROPFIND method is not working but self signed certificates.

I write a sample project that shows the problem: https://github.com/maza70/MauiApp-Test-SSL 
```


  //PROPFIND works only on android when in project <UseNativeHttpHandler>false</UseNativeHttpHandler>
        try
        {
            var webdavUrl = new Uri("https://ubuntu/remote.php/dav/files/zpush");
            HttpClientHandler handler = new HttpClientHandler();
            handler.ServerCertificateCustomValidationCallback = (message, cert, chain, errors) =>
            {
                //no callback to accept self signed cetrificates
                return true;
            };

            //Create a propfind request on a webdav server
            var passwordCache = new CredentialCache();
            passwordCache.Add(webdavUrl, "Basic", new NetworkCredential("zpush", "zpush"));
            handler.Credentials = passwordCache;
            handler.UseDefaultCredentials = false;
            var webclient = new HttpClient(handler, true);
            var request = new HttpRequestMessage(new HttpMethod("PROPFIND"), webdavUrl);
            var response = await webclient.SendAsync(request, HttpCompletionOption.ResponseContentRead).ConfigureAwait(false); ;

            if (response != null)
            {
                count++;
            }
        }
        catch (Exception ex)
        {
            //on self singed certificates exeption throws 
            /*
            System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
            ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
            ---> Interop+AndroidCrypto+SslException: Exception of type 'Interop+AndroidCrypto+SslException' was thrown.
            --- End of inner exception stack trace ---
            at System.Net.Security.SslStream.<ForceAuthenticationAsync>d__146`1[[System.Net.Security.AsyncReadWriteAdapter, System.Net.Security, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext()
            at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
            --- End of inner exception stack trace ---
            at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
            at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
            at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
            at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
            at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.<WaitWithCancellationAsync>d__1[[System.Net.Http.HttpConnection, System.Net.Http, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext()
            at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.<WaitForConnectionAsync>d__5[[System.Net.Http.HttpConnection, System.Net.Http, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext()
            at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
            at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
            at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
            at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
            at MauiApp_Test_SSL.MainPage.OnCounterClicked(Object sender, EventArgs e) in S:\no_backup\C#-Tests\MauiApp-Test-SSL\MauiApp-Test-SSL\MainPage.xaml.cs:line 39
             */

            count++;
        }
```

### Steps to Reproduce

1. checkout https://github.com/maza70/MauiApp-Test-SSL 
4. run a webdav server with a self signed certifcate
5. run the app on android 
6. SSL Exception throws and the callback ServerCertificateCustomValidationCallback not called 

### Link to public reproduction project repository

https://github.com/maza70/MauiApp-Test-SSL

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

testet under Android 11 and Android 13

### Did you find any workaround?

unfortunately no have been looking for months

### Relevant log output

```shell
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
            ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
            ---> Interop+AndroidCrypto+SslException: Exception of type 'Interop+AndroidCrypto+SslException' was thrown.
            --- End of inner exception stack trace ---
            at System.Net.Security.SslStream.<ForceAuthenticationAsync>d__146`1[[System.Net.Security.AsyncReadWriteAdapter, System.Net.Security, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext()
            at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
            --- End of inner exception stack trace ---
            at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
            at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
            at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
            at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
            at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.<WaitWithCancellationAsync>d__1[[System.Net.Http.HttpConnection, System.Net.Http, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext()
            at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.<WaitForConnectionAsync>d__5[[System.Net.Http.HttpConnection, System.Net.Http, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext()
            at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
            at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
            at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
            at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
            at MauiApp_Test_SSL.MainPage.OnCounterClicked(Object sender, EventArgs e) in S:\no_backup\C#-Tests\MauiApp-Test-SSL\MauiApp-Test-SSL\MainPage.xaml.cs:line 39
```

**Comment by drasticactions** [comment]
Can you make an example trying this in a .NET Android app (`dotnet new android`) that doesn't use MAUI? This doesn't seem like something that would be caused by the MAUI UI Code in this repo.

**Comment by drasticactions** [comment]
@maza70 Thank you!

@jonathanpeppers Would you know the next steps here? Is this a configuration issue? SDK? Something else?
