### ISSUE TITLE
[Android] RuntimeException: Canvas: trying to draw too large bitmap

### ISSUE THREAD

**Issue by greg84** [dotnet/maui#14604]
### Description

Crash on certain Android devices when image is large.

This worked fine on Xamarin Forms, because the image could be placed directly in the `drawable-xxhdpi` folder, which prevented it from being resized. However, in MAUI it doesn't seem possible to place images in that folder directly?

It seems like the MAUIImage BaseSize attribute might help solve this, but it's not clear how to use it from this documentation: https://learn.microsoft.com/en-us/dotnet/maui/user-interface/images/images?view=net-maui-7.0

### Steps to Reproduce

PNG image is 1800x4000 and 4.31 megs.

Put <Image> on MAUI page.

Run the device on a Galaxy J5 Prime (720x1280 display, 2Gb RAM).

The application crashes with this error on Android when the image is displayed:

````
Java.Lang.RuntimeException: Canvas: trying to draw too large(115200000bytes) bitmap.
   at Java.Interop.JniEnvironment.InstanceMethods.CallNonvirtualVoidMethod(JniObjectReference instance, JniObjectReference type, JniMethodInfo method, JniArgumentValue* args) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/obj/Release/net7.0/JniEnvironment.g.cs:line 12324
   at Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualVoidMethod(String encodedMember, IJavaPeerable self, JniArgumentValue* parameters) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:line 75
   at Android.Views.View.DispatchDraw(Canvas canvas) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net7.0/android-33/mcw/Android.Views.View.cs:line 14916
   at Microsoft.Maui.Platform.ContentViewGroup.DispatchDraw(Canvas canvas) in D:\a\_work\1\s\src\Core\src\Platform\Android\ContentViewGroup.cs:line 49
   at Android.Views.View.n_DispatchDraw_Landroid_graphics_Canvas_(IntPtr jnienv, IntPtr native__this, IntPtr native_canvas) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net7.0/android-33/mcw/Android.Views.View.cs:line 14904
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPL_V(_JniMarshal_PPL_V callback, IntPtr jnienv, IntPtr klazz, IntPtr p0) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 121
  --- End of managed Java.Lang.RuntimeException stack trace ---
java.lang.RuntimeException: Canvas: trying to draw too large(115200000bytes) bitmap.
	at android.view.DisplayListCanvas.throwIfCannotDraw(DisplayListCanvas.java:229)
	at android.view.RecordingCanvas.drawBitmap(RecordingCanvas.java:97)
	at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:529)
	at android.widget.ImageView.onDraw(ImageView.java:1367)
	at android.view.View.draw(View.java:20369)
	at android.view.View.updateDisplayListIfDirty(View.java:19314)
	at android.view.View.draw(View.java:20092)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
	at android.view.View.updateDisplayListIfDirty(View.java:19305)
	at android.view.View.draw(View.java:20092)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
	at android.view.View.updateDisplayListIfDirty(View.java:19305)
	at android.view.View.draw(View.java:20092)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
	at android.view.View.updateDisplayListIfDirty(View.java:19305)
	at android.view.View.draw(View.java:20092)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
	at crc6452ffdc5b34af3a0f.ContentViewGroup.n_dispatchDraw(Native Method)
	at crc6452ffdc5b34af3a0f.ContentViewGroup.dispatchDraw(ContentViewGroup.java:59)
	at android.view.View.draw(View.java:20372)
	at android.view.View.updateDisplayListIfDirty(View.java:19314)
	at android.view.View.draw(View.java:20092)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
	at android.view.View.updateDisplayListIfDirty(View.java:19305)
	at android.view.View.draw(View.java:20092)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
	at android.view.View.updateDisplayListIfDirty(View.java:19305)
	at android.view.View.draw(View.java:20092)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
	at androidx.recyclerview.widget.RecyclerView.drawChild(RecyclerView.java:5204)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
	at android.view.View.draw(View.java:20372)
	at androidx.recyclerview.widget.RecyclerView.draw(RecyclerView.java:4603)
	at android.view.View.updateDisplayListIfDirty(View.java:19314)
	at android.view.View.draw(View.java:20092)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
	at android.view.View.updateDisplayListIfDirty(View.java:19305)
	at android.view.View.draw(View.java:20092)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1312)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
	at android.view.View.updateDisplayListIfDirty(View.java:19305)
	at android.view.View.draw(View.java:20092)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
	at android.view.View.updateDisplayListIfDirty(View.java:19305)
	at android.view.View.draw(View.java:20092)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
	at android.view.View.updateDisplayListIfDirty(View.java:19305)
	at android.view.View.draw(View.java:20092)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
	at android.view.View.updateDisplayListIfDirty(View.java:19305)
	at android.view.View.draw(View.java:20092)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
	at androidx.drawerlayout.widget.DrawerLayout.drawChild(DrawerLayout.java:1478)
	at crc640ec207abc449b2ca.ShellFlyoutRenderer.n_drawChild(Native Method)
	at crc640ec207abc449b2ca.ShellFlyoutRenderer.drawChild(ShellFlyoutRenderer.java:57)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
	at android.view.View.updateDisplayListIfDirty(View.java:19305)
	at android.view.View.draw(View.java:20092)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
	at android.view.View.updateDisplayListIfDirty(View.java:19305)
	at android.view.View.draw(View.java:20092)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
	at android.view.View.updateDisplayListIfDirty(View.java:19305)
	at android.view.View.draw(View.java:20092)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
	at android.view.View.updateDisplayListIfDirty(View.java:19305)
	at android.view.View.draw(View.java:20092)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
	at android.view.View.updateDisplayListIfDirty(View.java:19305)
	at android.view.View.draw(View.java:20092)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
	at android.view.View.updateDisplayListIfDirty(View.java:19305)
	at android.view.View.draw(View.java:20092)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
	at android.view.View.draw(View.java:20372)
	at com.android.internal.policy.DecorView.draw(DecorView.java:974)
	at android.view.View.updateDisplayListIfDirty(View.java:19314)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:686)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:692)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:800)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3501)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3288)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2823)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1785)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7833)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
	at android.view.Choreographer.doCallbacks(Choreographer.java:723)
	at android.view.Choreographer.doFrame(Choreographer.java:658)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6942)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

  --- End of managed Java.Lang.RuntimeException stack trace ---
java.lang.RuntimeException: Canvas: trying to draw too large(115200000bytes) bitmap.
	at android.view.DisplayListCanvas.throwIfCannotDraw(DisplayListCanvas.java:229)
	at android.view.RecordingCanvas.drawBitmap(RecordingCanvas.java:97)
	at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:529)
	at android.widget.ImageView.onDraw(ImageView.java:1367)
	at android.view.View.draw(View.java:20369)
	at android.view.View.updateDisplayListIfDirty(View.java:19314)
	at android.view.View.draw(View.java:20092)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
	at android.view.View.updateDisplayListIfDirty(View.java:19305)
	at android.view.View.draw(View.java:20092)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
	at android.view.View.updateDisplayListIfDirty(View.java:19305)
	at android.view.View.draw(View.java:20092)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
	at android.view.View.updateDisplayListIfDirty(View.java:19305)
	at android.view.View.draw(View.java:20092)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
	at crc6452ffdc5b34af3a0f.ContentViewGroup.n_dispatchDraw(Native Method)
	at crc6452ffdc5b34af3a0f.ContentViewGroup.dispatchDraw(ContentViewGroup.java:59)
	at android.view.View.draw(View.java:20372)
	at android.view.View.updateDisplayListIfDirty(View.java:19314)
	at android.view.View.draw(View.java:20092)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
	at android.view.View.updateDisplayListIfDirty(View.java:19305)
	at android.view.View.draw(View.java:20092)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
	at android.view.View.updateDisplayListIfDirty(View.java:19305)
	at android.view.View.draw(View.java:20092)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
	at androidx.recyclerview.widget.RecyclerView.drawChild(RecyclerView.java:5204)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
	at android.view.View.draw(View.java:20372)
	at androidx.recyclerview.widget.RecyclerView.draw(RecyclerView.java:4603)
	at android.view.View.updateDisplayListIfDirty(View.java:19314)
	at android.view.View.draw(View.java:20092)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
	at android.view.View.updateDisplayListIfDirty(View.java:19305)
	at android.view.View.draw(View.java:20092)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1312)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
	at android.view.View.updateDisplayListIfDirty(View.java:19305)
	at android.view.View.draw(View.java:20092)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
	at android.view.View.updateDisplayListIfDirty(View.java:19305)
	at android.view.View.draw(View.java:20092)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
	at android.view.View.updateDisplayListIfDirty(View.java:19305)
	at android.view.View.draw(View.java:20092)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
	at android.view.View.updateDisplayListIfDirty(View.java:19305)
	at android.view.View.draw(View.java:20092)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
	at androidx.drawerlayout.widget.DrawerLayout.drawChild(DrawerLayout.java:1478)
	at crc640ec207abc449b2ca.ShellFlyoutRenderer.n_drawChild(Native Method)
	at crc640ec207abc449b2ca.ShellFlyoutRenderer.drawChild(ShellFlyoutRenderer.java:57)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
	at android.view.View.updateDisplayListIfDirty(View.java:19305)
	at android.view.View.draw(View.java:20092)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
	at android.view.View.updateDisplayListIfDirty(View.java:19305)
	at android.view.View.draw(View.java:20092)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
	at android.view.View.updateDisplayListIfDirty(View.java:19305)
	at android.view.View.draw(View.java:20092)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
	at android.view.View.updateDisplayListIfDirty(View.java:19305)
	at android.view.View.draw(View.java:20092)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
	at android.view.View.updateDisplayListIfDirty(View.java:19305)
	at android.view.View.draw(View.java:20092)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
	at android.view.View.updateDisplayListIfDirty(View.java:19305)
	at android.view.View.draw(View.java:20092)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
	at android.view.View.draw(View.java:20372)
	at com.android.internal.policy.DecorView.draw(DecorView.java:974)
	at android.view.View.updateDisplayListIfDirty(View.java:19314)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:686)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:692)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:800)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3501)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3288)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2823)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1785)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7833)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
	at android.view.Choreographer.doCallbacks(Choreographer.java:723)
	at android.view.Choreographer.doFrame(Choreographer.java:658)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6942)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
````

### Link to public reproduction project repository

See steps to reproduce

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

All

### Did you find any workaround?

Not found a workaround yet.

**Comment by nll** [comment]
My guess from reading information from the [precursor](https://github.com/Redth/ResizetizerNT#resize-rules) library, and given that `xxhdpi` is 3.0 scale, that putting `BaseSize="600,1333"` would resolve that particular crash on that device.

**Comment by greg84** [comment]
Thanks @nll - that fixed it! I will close this issue.
