### ISSUE TITLE
System.PlatformNotSupportedException: Algorithm 'RC2' is not supported on this platform.

### ISSUE THREAD

**Issue by SepuWeb** [dotnet/maui#14632]
### Description

I'm trying to convert my Xamarin App into new .NET MAUI.

This works in Xamarin:

string path = Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData) + "/cert_with_key.pfx";
byte[] rawData= File.ReadAllBytes(path);
X509Certificate2 cert = new X509Certificate2(rawData, privKeyPSW); ----->this throw the following error

{System.Security.Cryptography.CryptographicException: The certificate data cannot be read with the provided password, the password may be incorrect.
 ---> System.PlatformNotSupportedException: Algorithm 'RC2' is not supported on this platform.

### Steps to Reproduce

1. Create a File > New .NET MAUI App
2. Create a pfx file with this name cert_with_key.pfx in application folder with a password
3. And use the code in the description
4. Excute on Android Device

### Link to public reproduction project repository

no

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android from 10 

### Did you find any workaround?

No

### Relevant log output

```shell
{System.Security.Cryptography.CryptographicException: The certificate data cannot be read with the provided password, the password may be incorrect.
 ---> System.PlatformNotSupportedException: Algorithm 'RC2' is not supported on this platform.
   at System.Security.Cryptography.PasswordBasedEncryption.CreateRC2()
   at System.Security.Cryptography.PasswordBasedEncryption.Decrypt(AlgorithmIdentifierAsn& algorithmIdentifier, ReadOnlySpan`1 password, ReadOnlySpan`1 passwordBytes, ReadOnlySpan`1 encryptedData, Span`1 destination)
   at System.Security.Cryptography.X509Certificates.UnixPkcs12Reader.DecryptSafeContents(ReadOnlySpan`1 password, ContentInfoAsn& safeContentsAsn)
   at System.Security.Cryptography.X509Certificates.UnixPkcs12Reader.DecryptAndProcessSafeContents(ReadOnlySpan`1 password, CertBagAsn[]& certBags, AttributeAsn[][]& certBagAttrs, Int32& certBagIdx, SafeBagAsn[]& keyBags, Int32& keyBagIdx)
   at System.Security.Cryptography.X509Certificates.UnixPkcs12Reader.Decrypt(ReadOnlySpan`1 password, ReadOnlyMemory`1 authSafeContents)
   at System.Security.Cryptography.X509Certificates.UnixPkcs12Reader.VerifyAndDecrypt(ReadOnlySpan`1 password, ReadOnlyMemory`1 authSafeContents)
   at System.Security.Cryptography.X509Certificates.UnixPkcs12Reader.Decrypt(SafePasswordHandle password, Boolean ephemeralSpecified)
   --- End of inner exception stack trace ---
   at System.Security.Cryptography.X509Certificates.UnixPkcs12Reader.Decrypt(SafePasswordHandle password, Boolean ephemeralSpecified)
   at System.Security.Cryptography.X509Certificates.AndroidCertificatePal.ReadPkcs12(ReadOnlySpan`1 rawData, SafePasswordHandle password, Boolean ephemeralSpecified)
   at System.Security.Cryptography.X509Certificates.AndroidCertificatePal.FromBlob(ReadOnlySpan`1 rawData, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.CertificatePal.FromBlob(ReadOnlySpan`1 rawData, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(Byte[] rawData, String password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(Byte[] rawData, String password)
   at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(Byte[] rawData, String password)
```

**Comment by Redth** [comment]
@steveisok @akoeplinger could you have a look please?

**Comment by steveisok** [comment]
@SepuWeb, we made the decision to integrate directly w/ Android API's rather than rely on OpenSSL.  Unfortunately, RC2 is not supported on Android as reflected in the message you are getting. My recommendation would be to use AES as that is supported.

**Comment by SepuWeb** [comment]
Thank you for your replies. Why same code works in Xamarin? I tested it in Xamarin with many version of Android without problems. Instead in MAUI return this error, on the same device, with Android 10 and Android 13.
Are we sure the problem is really Android?

**Comment by steveisok** [comment]
The same code works in Xamarin because the underlying dependencies are different.  BoringSSL is used where we don't rely on Android API's as we do in .NET.

**Comment by SepuWeb** [comment]
Ok.
In Android API documentation I found this:

https://developer.android.com/reference/javax/crypto/spec/RC2ParameterSpec

"This class specifies the parameters used with the [RC2](http://www.ietf.org/rfc/rfc2268.txt) algorithm."

How can I convert my code to use AES? I think that this information would be inserte in the manual:
https://learn.microsoft.com/en-us/dotnet/maui/migration/forms-projects?source=recommendations&view=net-maui-7.0

**Comment by steveisok** [comment]
Interesting. I'll reopen and have us look into it further.  Thanks for the link.
