### ISSUE TITLE
Android x:Boolean Exception Only In Release Referencing Class Library as PackageReference

### ISSUE THREAD

**Issue by TheMattWalker** [dotnet/maui#14790]
### Description

I am running into a Microsoft.Maui.Controls.Xaml.XamlParseException and crash at startup only on Release.
I have 2 MAUI projects both referencing a .NET MAUI Class Library, one is referencing the class library as a PackageReference the other is referencing it as a ProjectReference.

In my class library I'm using a ResourceDictionary with this:
```
<Setter.Value>
    <OnPlatform x:TypeArguments="x:Boolean"> 
        <On Platform="iOS,Android" Value="True"/>
    </OnPlatform>
</Setter.Value>
```

The MAUI project referencing the MAUI Class Library as PackageReference is getting the following exception only in Release. If I remove the 2 setters using "x:Boolean" I no longer get the following exception. I also do not get the exception in the project that references the class library as ProjectReference in Release.

Could be related to #14546 and #14301??

### Steps to Reproduce

1) Create MAUI Class Library with ResourceDictionary that contains "x:Boolean" for example:
```
<Style x:Key="Test" TargetType="{x:Type Picker}">
        <Setter Property="UsePopup">
            <Setter.Value>
                    <OnPlatform x:TypeArguments="x:Boolean">
                        <On Platform="Android" Value="true"/>
                    </OnPlatform>
             </Setter.Value>
        </Setter>
</Style>
```
 
2) Build class library, nuget pack class library.
 
3) Create MAUI project that references the class library as PackageReference and Initializes the ResourceDictionary.

4) Build MAUI project in Release. Run app.

### Link to public reproduction project repository

None

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 13

### Did you find any workaround?

No but if I remove the setter using "x:Boolean" I no longer get the exception.

### Relevant log output

```shell
04-26 17:12:38.194 23686 23686 I MonoDroid: android.runtime.JavaProxyThrowable: Microsoft.Maui.Controls.Xaml.XamlParseException: Position 935:18. Type Boolean not found in xmlns http://schemas.microsoft.com/winfx/2009/xaml
04-26 17:12:38.194 23686 23686 I MonoDroid: at Microsoft.Maui.Controls.Xaml.CreateValuesVisitor.Visit(ElementNode node, INode parentNode)
04-26 17:12:38.194 23686 23686 I MonoDroid: at Microsoft.Maui.Controls.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
04-26 17:12:38.194 23686 23686 I MonoDroid: at Microsoft.Maui.Controls.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
04-26 17:12:38.194 23686 23686 I MonoDroid: at Microsoft.Maui.Controls.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
04-26 17:12:38.194 23686 23686 I MonoDroid: at Microsoft.Maui.Controls.Xaml.RootNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
04-26 17:12:38.194 23686 23686 I MonoDroid: at Microsoft.Maui.Controls.Xaml.XamlLoader.Visit(RootNode rootnode, HydrationContext visitorContext, Boolean useDesignProperties)
04-26 17:12:38.194 23686 23686 I MonoDroid: at Microsoft.Maui.Controls.Xaml.XamlLoader.Load(Object view, String xaml, Assembly rootAssembly, Boolean useDesignProperties)
04-26 17:12:38.194 23686 23686 I MonoDroid: at Microsoft.Maui.Controls.Xaml.XamlLoader.Load(Object view, String xaml, Boolean useDesignProperties)
04-26 17:12:38.194 23686 23686 I MonoDroid: at Microsoft.Maui.Controls.Xaml.XamlLoader.Load(Object view, Type callingType)
04-26 17:12:38.194 23686 23686 I MonoDroid: at Microsoft.Maui.Controls.Xaml.Extensions.LoadFromXaml[StyleResources](StyleResources view, Type callingType)
04-26 17:12:38.194 23686 23686 I MonoDroid: at MyClassLibrary.GlobalResources.StyleResources.InitializeComponent()
04-26 17:12:38.194 23686 23686 I MonoDroid: at MyClassLibrary.GlobalResources.StyleResources..ctor(ResourceDictionary colorResources)
04-26 17:12:38.194 23686 23686 I MonoDroid: at MyClassLibrary.Themes.Default.DefaultThemeResources..ctor()
04-26 17:12:38.194 23686 23686 I MonoDroid: at MyClassLibrary.ApplyTheme(Theme theme)
04-26 17:12:38.194 23686 23686 I MonoDroid: at MyClassLibrary.set_CurrentTheme(Theme value)
04-26 17:12:38.194 23686 23686 I MonoDroid: at MyClassLibrary.Init(Theme startingTheme)
04-26 17:12:38.194 23686 23686 I MonoDroid: at MyMauiApp..ctor()
04-26 17:12:38.194 23686 23686 I MonoDroid: at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags , Binder , Object[] , CultureInfo )
04-26 17:12:38.194 23686 23686 I MonoDroid: at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite , RuntimeResolverContext )
04-26 17:12:38.194 23686 23686 I MonoDroid: at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSiteMain(ServiceCallSite , RuntimeResolverContext )
04-26 17:12:38.194 23686 23686 I MonoDroid: at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite , RuntimeResolverContext )
04-26 17:12:38.194 23686 23686 I MonoDroid: at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSite(ServiceCallSite , RuntimeResolverContext )
04-26 17:12:38.194 23686 23686 I MonoDroid: at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
04-26 17:12:38.194 23686 23686 I MonoDroid: at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type )
04-26 17:12:38.194 23686 23686 I MonoDroid: at System.Collections.Concurrent.ConcurrentDictionary2[[System.Type, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Func2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope, Microsoft.Extensions.DependencyInjection, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].GetOrAdd(Type , Func2 )
04-26 17:12:38.194 23686 23686 I MonoDroid: at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type , ServiceProviderEngineScope )
04-26 17:12:38.194 23686 23686 I MonoDroid: at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type )
04-26 17:12:38.194 23686 23686 I MonoDroid: at Microsoft.Maui.MauiContext.WrappedServiceProvider.GetService(Type serviceType)
04-26 17:12:38.194 23686 23686 I MonoDroid: at Microsoft.Maui.MauiContext.WrappedServiceProvider.GetService(Type serviceType)
04-26 17:12:38.194 23686 23686 I MonoDroid: at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider , Type )
04-26 17:12:38.194 23686 23686 I MonoDroid: at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[IApplication](https://github.com/dotnet/maui/issues/IServiceProvider)
04-26 17:12:38.194 23686 23686 I MonoDroid: at Microsoft.Maui.MauiApplication.OnCreate()
04-26 17:12:38.194 23686 23686 I MonoDroid: at Android.App.Application.n_OnCreate(IntPtr , IntPtr )
04-26 17:12:38.194 23686 23686 I MonoDroid: at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(_JniMarshal_PP_V , IntPtr , IntPtr )
04-26 17:12:38.194 23686 23686 I MonoDroid: at crc6488302ad6e9e4df1a.MauiApplication.n_onCreate(Native Method)
04-26 17:12:38.194 23686 23686 I MonoDroid: at crc6488302ad6e9e4df1a.MauiApplication.onCreate(MauiApplication.java:28)
04-26 17:12:38.194 23686 23686 I MonoDroid: at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1266)
04-26 17:12:38.194 23686 23686 I MonoDroid: at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7632)
04-26 17:12:38.194 23686 23686 I MonoDroid: at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
04-26 17:12:38.194 23686 23686 I MonoDroid: at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2402)
04-26 17:12:38.194 23686 23686 I MonoDroid: at android.os.Handler.dispatchMessage(Handler.java:106)
04-26 17:12:38.194 23686 23686 I MonoDroid: at android.os.Looper.loopOnce(Looper.java:226)
04-26 17:12:38.194 23686 23686 I MonoDroid: at android.os.Looper.loop(Looper.java:313)
04-26 17:12:38.194 23686 23686 I MonoDroid: at android.app.ActivityThread.main(ActivityThread.java:8775)
04-26 17:12:38.194 23686 23686 I MonoDroid: at java.lang.reflect.Method.invoke(Native Method)
04-26 17:12:38.194 23686 23686 I MonoDroid: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
04-26 17:12:38.194 23686 23686 I MonoDroid: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

**Comment by jonathanpeppers** [comment]
It looks like there is a lot of setup for this one... Can you share a project with:

> Link to public reproduction project repository

I'm not sure we'd easily follow the instructions.

**Comment by TheMattWalker** [comment]
> It looks like there is a lot of setup for this one... Can you share a project with:
> 
> > Link to public reproduction project repository
> 
> I'm not sure we'd easily follow the instructions.

Can't really setup a single project for it. You have to build a class library then nuget pack it and push it to a feed then reference it as a PackageReference from a nuget feed. I can't set that all up with a single project to share. 

Using a single project referencing the class library as a ProjectReference does not produce the exception.

**Comment by TheMattWalker** [comment]
I don't have a sample project setup but could possibly set one up if there is a public nuget feed we can use to push/pull test nuget packages.
