### ISSUE TITLE
Crash on show dialog after back from background

### ISSUE THREAD

**Issue by luwed** [dotnet/maui#15024]
### Description

Hi,

I noticed crash on show dialog after back from background.

I've done initiali research. In debug I got following exception:

```
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Microsoft.Maui.Controls.MessagingCenter.Subscription.InvokeCallback(Object sender, Object args) in D:\a\_work\1\s\src\Controls\src\Core\MessagingCenter.cs:line 97
   at Microsoft.Maui.Controls.MessagingCenter.InnerSend(String message, Type senderType, Type argType, Object sender, Object args) in D:\a\_work\1\s\src\Controls\src\Core\MessagingCenter.cs:line 220
   at Microsoft.Maui.Controls.MessagingCenter.Microsoft.Maui.Controls.IMessagingCenter.Send[Page,AlertArguments](Page sender, String message, AlertArguments args) in D:\a\_work\1\s\src\Controls\src\Core\MessagingCenter.cs:line 118
   at Microsoft.Maui.Controls.MessagingCenter.Send[Page,AlertArguments](Page sender, String message, AlertArguments args) in D:\a\_work\1\s\src\Controls\src\Core\MessagingCenter.cs:line 111
   at Microsoft.Maui.Controls.Page.DisplayAlert(String title, String message, String accept, String cancel, FlowDirection flowDirection) in D:\a\_work\1\s\src\Controls\src\Core\Page.cs:line 240
   at Microsoft.Maui.Controls.Page.DisplayAlert(String title, String message, String accept, String cancel) in D:\a\_work\1\s\src\Controls\src\Core\Page.cs:line 216
   at MauiProject.MainPage.<OnDialogBtnClicked>b__2_0() in /private/var/lwf/Projects-private/maui-stuff/MauiProject/MauiProject/MainPage.xaml.cs:line 15
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Android.App.SyncContext.<>c__DisplayClass2_0.<Post>b__0() in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.App/SyncContext.cs:line 36
   at Java.Lang.Thread.RunnableImplementor.Run() in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Java.Lang/Thread.cs:line 36
   at Java.Lang.IRunnableInvoker.n_Run(IntPtr jnienv, IntPtr native__this) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net7.0/android-33/mcw/Java.Lang.IRunnable.cs:line 84
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(_JniMarshal_PP_V callback, IntPtr jnienv, IntPtr klazz) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 22
```

Looking at Maui code I noticed that AlertSignalName message is used to display alert. It was helpful to find out that Subscriptions list in AlertManager contains AlertRequestHelper objects (AlertRequestHelper is added to Subscriptions in OnPageHandlerChanged and removed in OnPageHandlerChanging).
Looking at the window object in its Created event handler I noticed that Subscriptions list can contain AlertRequestHelper objects with Activities that have been already destroyed (AlertManager.Unsubscribe should be called while destroying window?) and the exception is thrown  because destroyed Activity is used to display Alert.

### Steps to Reproduce

Repro steps:
1. Create Maui app
2. Define MainPage in App.xaml.cs as:
		var rootPage = new MainPage();
		MainPage = new NavigationPage(rootPage);
3. Add button to MainPage.xaml with following code in Click handler:
        MainThread.BeginInvokeOnMainThread(async () => await DisplayAlert("Title", "Message", string.Empty, "Cancel"));
4. Run app on Android 11
5. Move app to background using Back key
6. Return to the app
7. Tap on button

Actual result:
    App crashes

Expected result:
    App does not crash.

### Link to public reproduction project repository

https://github.com/luwed/maui-stuff/tree/dialog-crash-after-back-and-and-return-to-app

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

### Did you find any workaround?

Implement own DisplayAlert.

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 2.0. Repro on **Android 11.0-API30**, not repro on Android 13.0-API33 with below Project:
[MauiProject.zip](https://github.com/dotnet/maui/files/11998267/MauiProject.zip)

![image](https://github.com/dotnet/maui/assets/97647558/43ae2365-d396-4a6f-9709-638c90814cdd)

**Comment by japarson** [comment]
Hi @luwed, are you able to reproduce this issue with the latest version of MAUI? I was not able to with latest MAUI on Android 11:
![no_repro](https://github.com/dotnet/maui/assets/59936622/67c37bcc-b72d-4f0b-8cd1-0ab8842fea04)
