### ISSUE TITLE
[regression/7.0.49] Deep Link for Android with .Net Maui error - Error when navigate other page

### ISSUE THREAD

**Issue by bikotoru** [dotnet/maui#15192]
### Description

I'm trying to use Deep Link for Android in Maui, but when I open my application from the link newapp://result, it opens either the home page or the last page that was open in my application. And when I try to navigate to another page, the application crashes. This happens whether I use appshell navigation or navigate using Push. This is how my activity is configured: [IntentFilter(new[] { Intent.ActionView },

### Steps to Reproduce

1. Open application normally
2.- Test side navigation
3.- Test navigation using the Navigate button
4.- Everything works perfect

Problem:

1.- Open application using link demoapp://result
2.- Touch the Navigate button
3.- The error occurs

### Link to public reproduction project repository

https://github.com/bikotoru/problem-intent-maui/tree/main

### Version with bug

7.0.49

### Last version that worked well

6.0

### Affected platforms

Android

### Affected platform versions

Android 13

### Relevant log output

[0:] Microsoft.Maui.Controls.Shell: Warning: Failed to Navigate Back

System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.Collections.Generic.Dictionary`2[[Microsoft.Maui.Controls.Element, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Controls.Platform.Compatibility.IShellObservableFragment, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].FindValue(Element key)
   at System.Collections.Generic.Dictionary`2[[Microsoft.Maui.Controls.Element, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Controls.Platform.Compatibility.IShellObservableFragment, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].ContainsKey(Element key)
   at Microsoft.Maui.Controls.Platform.Compatibility.ShellItemRendererBase.HandleFragmentUpdate(ShellNavigationSource navSource, ShellSection shellSection, Page page, Boolean animated) in D:\a\_work\1\s\src\Controls\src\Core\Compatibility\Handlers\Shell\Android\ShellItemRendererBase.cs:line 143
   at Microsoft.Maui.Controls.Platform.Compatibility.ShellItemRendererBase.OnNavigationRequested(Object sender, NavigationRequestedEventArgs e) in D:\a\_work\1\s\src\Controls\src\Core\Compatibility\Handlers\Shell\Android\ShellItemRendererBase.cs:line 316
   at Microsoft.Maui.Controls.ShellSection.InvokeNavigationRequest(NavigationRequestedEventArgs args) in D:\a\_work\1\s\src\Controls\src\Core\Shell\ShellSection.cs:line 717
   at Microsoft.Maui.Controls.ShellSection.OnPopAsync(Boolean animated) in D:\a\_work\1\s\src\Controls\src\Core\Shell\ShellSection.cs:line 781
   at Microsoft.Maui.Controls.ShellSection.GoToAsync(ShellNavigationRequest request, ShellRouteParameters queryData, IServiceProvider services, Nullable`1 animate, Boolean isRelativePopping) in D:\a\_work\1\s\src\Controls\src\Core\Shell\ShellSection.cs:line 500
   at Microsoft.Maui.Dispatching.DispatcherExtensions.<>c__DisplayClass3_0.<<DispatchAsync>b__0>d.MoveNext() in D:\a\_work\1\s\src\Core\src\Dispatching\DispatcherExtensions.cs:line 88
--- End of stack trace from previous location ---
   at Microsoft.Maui.Dispatching.DispatcherExtensions.<>c__DisplayClass2_0`1.<<DispatchAsync>b__0>d[[System.Boolean, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext() in D:\a\_work\1\s\src\Core\src\Dispatching\DispatcherExtensions.cs:line 67
--- End of stack trace from previous location ---
   at Microsoft.Maui.Controls.ShellNavigationManager.GoToAsync(ShellNavigationParameters shellNavigationParameters, ShellNavigationRequest navigationRequest) in D:\a\_work\1\s\src\Controls\src\Core\Shell\ShellNavigationManager.cs:line 188
   at Microsoft.Maui.Controls.ShellSection.NavigationImpl.OnPopAsync(Boolean animated) in D:\a\_work\1\s\src\Controls\src\Core\Shell\ShellSection.cs:line 1056
   at Microsoft.Maui.Controls.Platform.Compatibility.ShellToolbarTracker.OnNavigateBack() in D:\a\_work\1\s\src\Controls\src\Core\Compatibility\Handlers\Shell\Android\ShellToolbarTracker.cs:line 229
[Dialog] mIsDeviceDefault = false, mIsSamsungBasicInteraction = false, isMetaDataInActivity = false

**Comment by mavispuford** [comment]
I also get the same thing when deeplinking to my app.  Any navigation causes a crash after it opens.  In my case, if I break on all exceptions, it looks like `ShellContext` is null in `ShellItemRendererbase.cs`:

![image](https://github.com/dotnet/maui/assets/2214272/23475187-3fd8-4c83-8d82-a7aad088d05b)

Here's my log output:

```
[mobilediffusion] Explicit concurrent copying GC freed 137717(11MB) AllocSpace objects, 2(40KB) LOS objects, 76% free, 7375KB/31MB, paused 65us,37us total 34.849ms
[mono-rt] [ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object.
[mono-rt]    at Microsoft.Maui.Controls.Platform.Compatibility.ShellItemRendererBase.GetOrCreateFragmentForTab(ShellSection shellSection) in D:\a\_work\1\s\src\Controls\src\Core\Compatibility\Handlers\Shell\Android\ShellItemRendererBase.cs:line 133
[mono-rt]    at Microsoft.Maui.Controls.Platform.Compatibility.ShellItemRendererBase.HandleFragmentUpdate(ShellNavigationSource navSource, ShellSection shellSection, Page page, Boolean animated) in D:\a\_work\1\s\src\Controls\src\Core\Compatibility\Handlers\Shell\Android\ShellItemRendererBase.cs:line 145
[mono-rt]    at Microsoft.Maui.Controls.Platform.Compatibility.ShellItemRendererBase.OnShellSectionChanged() in D:\a\_work\1\s\src\Controls\src\Core\Compatibility\Handlers\Shell\Android\ShellItemRendererBase.cs:line 306
[mono-rt]    at Microsoft.Maui.Controls.Platform.Compatibility.ShellItemRenderer.OnShellSectionChanged() in D:\a\_work\1\s\src\Controls\src\Core\Compatibility\Handlers\Shell\Android\ShellItemRenderer.cs:line 272
[mono-rt]    at Microsoft.Maui.Controls.Platform.Compatibility.ShellItemRendererBase.set_ShellSection(ShellSection value) in D:\a\_work\1\s\src\Controls\src\Core\Compatibility\Handlers\Shell\Android\ShellItemRendererBase.cs:line 58
[mono-rt]    at Microsoft.Maui.Controls.Platform.Compatibility.ShellItemRendererBase.OnShellItemPropertyChanged(Object sender, PropertyChangedEventArgs e) in D:\a\_work\1\s\src\Controls\src\Core\Compatibility\Handlers\Shell\Android\ShellItemRendererBase.cs:line 322
[mono-rt]    at Microsoft.Maui.Controls.BindableObject.OnPropertyChanged(String propertyName) in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 281
[mono-rt]    at Microsoft.Maui.Controls.Element.OnPropertyChanged(String propertyName) in D:\a\_work\1\s\src\Controls\src\Core\Element.cs:line 381
[mono-rt]    at Microsoft.Maui.Controls.BaseShellItem.OnPropertyChanged(String propertyName) in D:\a\_work\1\s\src\Controls\src\Core\Shell\BaseShellItem.cs:line 231
[mono-rt]    at Microsoft.Maui.Controls.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, Boolean silent) in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 533
[mono-rt]    at Microsoft.Maui.Controls.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes) in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 469
[mono-rt]    at Microsoft.Maui.Controls.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes) in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 401
[mono-rt]    at Microsoft.Maui.Controls.Element.SetValueFromRenderer(BindableProperty property, Object value) in D:\a\_work\1\s\src\Controls\src\Core\Element.cs:line 261
[mono-rt]    at Microsoft.Maui.Controls.ShellNavigationManager.GoToAsync(ShellNavigationParameters shellNavigationParameters, ShellNavigationRequest navigationRequest) in D:\a\_work\1\s\src\Controls\src\Core\Shell\ShellNavigationManager.cs:line 141
[mono-rt]    at MobileDiffusion.ViewModels.MainPageViewModel.LoadSharedImage(String imageUri, String contentType) in C:\Users\blake\source\repos\MobileDiffusion\MobileDiffusion\ViewModels\MainPageViewModel.cs:line 524
[mono-rt]    at MobileDiffusion.ViewModels.MainPageViewModel.ApplyQueryAttributes(IDictionary`2 query) in C:\Users\blake\source\repos\MobileDiffusion\MobileDiffusion\ViewModels\MainPageViewModel.cs:line 487
[mono-rt]    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
[mono-rt]    at Android.App.SyncContext.<>c__DisplayClass2_0.<Post>b__0() in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.App/SyncContext.cs:line 36
[mono-rt]    at Java.Lang.Thread.RunnableImplementor.Run() in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Java.Lang/Thread.cs:line 36
[mono-rt]    at Java.Lang.IRunnableInvoker.n_Run(IntPtr jnienv, IntPtr native__this) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net7.0/android-33/mcw/Java.Lang.IRunnable.cs:line 84
[mono-rt]    at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(_JniMarshal_PP_V callback, IntPtr jnienv, IntPtr klazz) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 22
```

**Comment by bcgottschall** [comment]
I ran in into the same issue when MainActivity.OnNewIntent is triggered from a deep link and attempts to navigate in Shell.  This only happened if the app was already open.  On navigation ShellItemRenderer.ShellSection is null.

The resolution I found was to set LaunchMode = LaunchMode.SingleTask on the Activity's ActivityAttribute.

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.9.0 Preview 3. Not repro on android platforms with sample project.
[bikotoru/problem-intent-maui (github.com)](https://github.com/bikotoru/problem-intent-maui/tree/main)

**Comment by zLordZachy** [comment]
I´m getting the same exception in net maui 8.0.7 - Android 
Devices:
OnePlus8Pro - Android 11
`
Microsoft.Maui.Controls.Platform.Compatibility.ShellFlyoutTemplatedContentRenderer.HeaderContainer.UpdateMinimumHeight()
Microsoft.Maui.Controls.Platform.Compatibility.ShellFlyoutTemplatedContentRenderer.HeaderContainer.OnMeasure(Int32 widthMeasureSpec, Int32 heightMeasureSpec)
Android.Views.View.n_OnMeasure_II(IntPtr jnienv, IntPtr native__this, Int32 widthMeasureSpec, Int32 heightMeasureSpec)
Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPII_V(_JniMarshal_PPII_V callback, IntPtr jnienv, IntPtr klazz, Int32 p0, Int32 p1)
`

**Comment by BagavathiPerumal** [comment]
The issue is not reproduced with the latest Maui NuGet version (9.0.110) on Android platform.

https://github.com/user-attachments/assets/9db19fa3-c566-468a-8095-32471780dec2
