### ISSUE TITLE
[Bug] Some GC tests stopped working after switching to net6

### ISSUE THREAD

**Issue by mattleibow** [dotnet/maui#1524]
```

 Handler count is 1


  Failed ElementIsGarbageCollectedAfterItsRemoved [37 ms]
  Error Message:
     Expected: False
  But was:  True

  Stack Trace:
     at Microsoft.Maui.Controls.Core.UnitTests.MapTests.ElementIsGarbageCollectedAfterItsRemoved() in D:\a\1\s\src\Controls\tests\Core.UnitTests\MapTests.cs:line 387

  Failed SubscriberCollectableAfterUnsubscribeEvenIfHeldByClosure [18 ms]
  Error Message:
     Expected: False
  But was:  True

  Stack Trace:
     at Microsoft.Maui.Controls.Core.UnitTests.MessagingCenterTests.SubscriberCollectableAfterUnsubscribeEvenIfHeldByClosure() in D:\a\1\s\src\Controls\tests\Core.UnitTests\MessagingCenterTests.cs:line 284

```

**Comment by v-longmin** [comment]
Thank you so much for your bug report! Unfortunately, we cannot reproduce your issue with the information above, could you provide a sample project and screenshots or more details that we can reproduce your issue? That should greatly speed up the process, thanks!

**Comment by hartez** [comment]
The repro is the set of unit tests that have an Ignore attribute linking to this issue.

**Comment by jfversluis** [comment]
From what I can tell only WeakToWeak is still disabled. Tried to reenable it, but still fails.
