### ISSUE TITLE
[Bug] Issues while deploying MAUI start up app

### ISSUE THREAD

**Issue by MuneeshKumarG** [dotnet/maui#1541]
HI Team,

I have installed Windows 10 20H2 version in my system. And Visual Studio Professional 2019 and  Visual Studio Professional 2019 preview. Followed the below link for MAUI setup. 

https://docs.microsoft.com/en-us/dotnet/maui/get-started/installation.

I have installed .Net MAUI preview 5. And ensured maui-check. All looks great. 

I can able to create new project in MAUI and it builds succesfully. But when try to deploy in device, it shows below error. 

**Severity	Code	Description	Project	File	Line	Suppression State
Error		ADB0020: Mono.AndroidTools.IncompatibleCpuAbiExceptiopn: The package does not support the CPU architecture of this device.
   at Mono.AndroidTools.Internal.AdbOutputParsing.CheckInstallSuccess(String output, String packageName) in /Users/builder/azdo/_work/1/s/xamarin-android/external/monodroid/tools/msbuild/external/androidtools/Mono.AndroidTools/Internal/AdbOutputParsing.cs:line 342
   at Mono.AndroidTools.AndroidDevice.<>c__DisplayClass100_0.<InstallPackage>b__0(Task`1 t) in /Users/builder/azdo/_work/1/s/xamarin-android/external/monodroid/tools/msbuild/external/androidtools/Mono.AndroidTools/AndroidDevice.cs:line 803
   at System.Threading.Tasks.ContinuationTaskFromResultTask`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AndroidDeviceExtensions.<PushAndInstallPackageAsync>d__12.MoveNext() in /Users/builder/azdo/_work/1/s/xamarin-android/external/monodroid/tools/msbuild/external/androidtools/Xamarin.AndroidTools/Devices/AndroidDeviceExtensions.cs:line 206
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at AndroidDeviceExtensions.<PushAndInstallPackageAsync>d__12.MoveNext() in /Users/builder/azdo/_work/1/s/xamarin-android/external/monodroid/tools/msbuild/external/androidtools/Xamarin.AndroidTools/Devices/AndroidDeviceExtensions.cs:line 223
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.Android.Tasks.FastDeploy.<InstallPackage>d__101.MoveNext() in /Users/builder/azdo/_work/1/s/xamarin-android/external/monodroid/tools/msbuild/Tasks/FastDeploy.cs:line 338
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Xamarin.Android.Tasks.FastDeploy.<InstallPackage>d__101.MoveNext() in /Users/builder/azdo/_work/1/s/xamarin-android/external/monodroid/tools/msbuild/Tasks/FastDeploy.cs:line 355
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Xamarin.Android.Tasks.FastDeploy.<RunTaskAsync>d__96.MoveNext() in /Users/builder/azdo/_work/1/s/xamarin-android/external/monodroid/tools/msbuild/Tasks/FastDeploy.cs:line 212		 	0**	

I try to resolve these problem, but no luck. Please help me. 

Device : Samsung SM-A605G (Android 10 - API 29). 

Its urgent.

**Comment by derekpapworth** [comment]
Hi @MuneeshKumarG 

I'm having a similar issue with clean install of and following documented instructions which appears to be related and which is described in more detail in a discussion post by @plattski as ..

"I have VS 2019, version 16.11.0 Preview 2. I installed Maui 5 Preview, and ran maui-check until it was happy.

When I generate a Maui project using the VS workload, it doesn't compile. There are a number of error messages, all complaining "Unable to find package X". When I look at the full text of the error message, they are all similar to this:

Error NU1102 Unable to find package Microsoft.iOS.Runtime.iossimulator-x64 with version (= 14.5.100-preview.5.881)

Found 3 version(s) in nuget.org [ Nearest version: 14.5.100-preview.5.894 ]
Found 0 version(s) in Microsoft Visual Studio Offline Packages MauiApp1 C:\Users\rollt\Source\Repos\MauiApp1\MauiApp1\MauiApp1\MauiApp1.csproj 1
"

I'm getting exactly the same issues as above (seemingly looking for .881 but only finding .894 etc, for 12 runtime errors in my case) and I've uninstalled and cleaned  and then re-installed 2 or 3 times with still the same issues.

Anyone any ideas?

Thanks Derek

**Comment by MuneeshKumarG** [comment]
@derekpapworth : I have reinstalled system OS and configured all. Now compilation errors resolved. But deplyment errors still occuring.

**Comment by AndrewBryanScott** [comment]
if you add, the following to the .csproj under the propertygroup it will get past the cpu arch, and run the app on an actual device.

<RuntimeIdentifiers Condition="$(TargetFramework.Contains('-android'))">android-arm;android-arm64;android-x86;android-x64</RuntimeIdentifiers>
