### ISSUE TITLE
Improve the InvalidCastException Messages

### ISSUE THREAD

**Issue by fde-lmag** [dotnet/maui#15545]
### Description

When debugging a MAUI Project and a InvalidCastException is thrown, there is no way of knowing, what the cause is.
The InvalidCastException could be enhanced by including the Element, Binding, Property, Converter, source type, target type and source value of the occurance.

### Public API Changes

Microsoft.Maui.Controls.Xaml.ApplyPropertiesVisitor.SetPropertyValue
HydrationContext.ExceptionHandler
ResourceLoader.Exceptionhandler
?

### Intended Use-Case

Fixing Invalid Cast Exceptions

**Comment by Eilon** [comment]
@fde-lmag - it could be helpful if you can provide a specific example where you get an exception so that we can be sure we're investigating the right issue.

**Comment by fde-lmag** [comment]
lol
if i would know where the error lies
i could, but since the exception i see is not pointing me in any direction
i cant, that's the reason why i think the exception message needs to be updated to include more information
this is the exception stack trace i see
``` 
  at Microsoft.Maui.Controls.Xaml.ApplyPropertiesVisitor.SetPropertyValue(Object xamlelement, XmlName propertyName, Object value, Object rootElement, INode node, HydrationContext context, IXmlLineInfo lineInfo) in D:\a\_work\1\s\src\Controls\src\Xaml\ApplyPropertiesVisitor.cs:line 379
   at Microsoft.Maui.Controls.Xaml.ApplyPropertiesVisitor.Visit(ElementNode node, INode parentNode) in D:\a\_work\1\s\src\Controls\src\Xaml\ApplyPropertiesVisitor.cs:line 156
   at Microsoft.Maui.Controls.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode) in D:\a\_work\1\s\src\Controls\src\Xaml\XamlNode.cs:line 159
   at Microsoft.Maui.Controls.Xaml.RootNode.Accept(IXamlNodeVisitor visitor, INode parentNode) in D:\a\_work\1\s\src\Controls\src\Xaml\XamlNode.cs:line 212
   at Microsoft.Maui.Controls.Xaml.XamlLoader.Visit(RootNode rootnode, HydrationContext visitorContext, Boolean useDesignProperties) in D:\a\_work\1\s\src\Controls\src\Xaml\XamlLoader.cs:line 210
   at Microsoft.Maui.Controls.Xaml.XamlLoader.Load(Object view, String xaml, Assembly rootAssembly, Boolean useDesignProperties) in D:\a\_work\1\s\src\Controls\src\Xaml\XamlLoader.cs:line 78
   at Microsoft.Maui.Controls.Xaml.XamlLoader.Load(Object view, String xaml, Boolean useDesignProperties) in D:\a\_work\1\s\src\Controls\src\Xaml\XamlLoader.cs:line 53
   at Microsoft.Maui.Controls.Xaml.XamlLoader.Load(Object view, Type callingType) in D:\a\_work\1\s\src\Controls\src\Xaml\XamlLoader.cs:line 49
   at Microsoft.Maui.Controls.Xaml.Extensions.LoadFromXaml[MainPage](MainPage view, Type callingType) in D:\a\_work\1\s\src\Controls\src\Xaml\ViewExtensions.cs:line 37
   at ***.Views.MainPage.InitializeComponent() in ...
```
