### ISSUE TITLE
[Bug] CreateWindow with empty NavigationPage cause crash on Android

### ISSUE THREAD

**Issue by vfongmala** [dotnet/maui#1566]
### Steps to Reproduce

1. on `App.xaml.cs`
```
protected override IWindow CreateWindow(IActivationState activationState)
{
	  Microsoft.Maui.Controls.Compatibility.Forms.Init(activationState);
	  
	  this.On<Microsoft.Maui.Controls.PlatformConfiguration.Windows>()
		  .SetImageDirectory("Assets");
	  
	  return new Microsoft.Maui.Controls.Window(new NavigationPage());
}
```
2. on `Startup.cs`
Note: cannot use `UseMauiControlsHandlers()` anymore.
```
public class Startup : IStartup
{
	  public void Configure(IAppHostBuilder appBuilder)
	  {
		    appBuilder
			    .UseMauiApp<App>()
			    // .UseMauiControlsHandlers()
			    .UseMauiServiceProviderFactory(true)
			    .ConfigureServices(services =>
			    {
					...
				});
	  }
}
```
3. 

### Expected Behavior
Should be able to see blank screen.

### Actual Behavior
App crashed after splash screen.
```
android.runtime.JavaProxyThrowable: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
       at System.Collections.Generic.List`1[[System.Int32, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].get_Item(Int32 index) in System.Private.CoreLib.dll:token 0x6005ed0+0x9
       at Microsoft.Maui.Controls.Handlers.NavigationPageHandler.ConnectHandler(View nativeView) in Microsoft.Maui.Controls.dll:token 0x60019c9+0x143
       at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.Controls.NavigationPage, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Android.Views.View, Mono.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065]].SetVirtualView(IView view) in Microsoft.Maui.dll:token 0x60005ac+0xd6
       at Microsoft.Maui.Controls.VisualElement.SetHandler(IViewHandler newHandler) in Microsoft.Maui.Controls.dll:token 0x60008d5+0x6e
       at Microsoft.Maui.Controls.VisualElement.set_Handler(IViewHandler value) in Microsoft.Maui.Controls.dll:token 0x60008b4+0x0
       at Microsoft.Maui.HandlerExtensions.ToNative(IView view, IMauiContext context) in Microsoft.Maui.dll:token 0x600017f+0x7e
       at Microsoft.Maui.MauiAppCompatActivity.OnCreate(Bundle savedInstanceState) in Microsoft.Maui.dll:token 0x6000195+0xc0
       at DummyHID.MainActivity.OnCreate(Bundle savedInstanceState) in DummyHID.dll:token 0x6000091+0x1
       at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_(IntPtr jnienv, IntPtr native__this, IntPtr native_savedInstanceState) in Mono.Android.dll:token 0x60150af+0xf
        at crc6466b141205c78a362.MainActivity.n_onCreate(Native Method)
        at crc6466b141205c78a362.MainActivity.onCreate(MainActivity.java:38)
        at android.app.Activity.performCreate(Activity.java:7994)
        at android.app.Activity.performCreate(Activity.java:7978)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3404)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7664)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

### Basic Information

- Version with issue: 6.0.100-preview.5.21302.13
- Last known good version: - 
- IDE: Visual Studio Code on Mac
- Platform Target Frameworks: 
  - Android: 25

**Comment by vfongmala** [comment]
Is there anyone having the same issue?

**Comment by vfongmala** [comment]
Fixed in Preview 6. Since CreateWindow is removed
