### ISSUE TITLE
A NullReferenceException is thrown on Android in the GridLayoutManager when calling InvalidateLayout

### ISSUE THREAD

**Issue by marchev-prgs** [dotnet/maui#15729]
### Description

A NRE is called when InvalidateLayout is invoked on a ContentView that has a Grid in its template, and a child element in a ContentView. 

### Steps to Reproduce

1. Get the repo from the link (https://github.com/telerik/ms-samples/tree/main/Maui/ExceptionInGridLayoutManagerAndroid)
2. Go to the project in the Maui/ExceptionInGridLayoutManagerAndroid folder
3. Run it on Android

Actual: An exception is thrown.
Expected: For the app to load with no errors

![Screenshot_1687187775](https://github.com/dotnet/maui/assets/91615935/aadc2b6e-1436-41cd-8bfd-c0592dc0e8aa)

Here is the exception message and stack trace:

Object reference not set to an instance of an object.

   at Microsoft.Maui.Layouts.GridLayoutManager.ArrangeChildren(Rect bounds) in D:\a\_work\1\s\src\Core\src\Layouts\GridLayoutManager.cs:line 44
   at Microsoft.Maui.Controls.Layout.CrossPlatformArrange(Rect bounds) in D:\a\_work\1\s\src\Controls\src\Core\Layout\Layout.cs:line 287
   at Microsoft.Maui.Platform.LayoutViewGroup.OnLayout(Boolean changed, Int32 l, Int32 t, Int32 r, Int32 b) in D:\a\_work\1\s\src\Core\src\Platform\Android\LayoutViewGroup.cs:line 96
   at Android.Views.ViewGroup.n_OnLayout_ZIIII(IntPtr jnienv, IntPtr native__this, Boolean changed, Int32 l, Int32 t, Int32 r, Int32 b) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net7.0/android-33/mcw/Android.Views.ViewGroup.cs:line 3655
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPZIIII_V(_JniMarshal_PPZIIII_V callback, IntPtr jnienv, IntPtr klazz, Boolean p0, Int32 p1, Int32 p2, Int32 p3, Int32 p4) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 429

### Link to public reproduction project repository

https://github.com/telerik/ms-samples/tree/main/Maui/ExceptionInGridLayoutManagerAndroid

### Version with bug

7.0.86

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android

### Did you find any workaround?

N/A

**Comment by jsuarezruiz** [comment]
We need to validate it but worked on previous version, could be a regression.

**Comment by marcoablanco** [comment]
It still happens in a layout structure like this
(i can't show an enterprise code, it's pseudocode)
```
<Grid Rows"50,200,*">
<Scroll row=2>
<VerticalStack>
<many controls and stacks with more controls />
<Grid "Move scroll from here cause crash" />
<Grid "Move scroll from here cause crash" />
</VerticalStack>
</Scroll>
</Grid>
```

Workloads version:

Installed Workload Id      Manifest Version       Installation Source
---------------------------------------------------------------------------------------------------
android                    33.0.68/7.0.100        SDK 7.0.300, VS 17.6.33815.320, VS 17.6.33815.320
ios                        16.4.7067/7.0.100      SDK 7.0.300, VS 17.6.33815.320, VS 17.6.33815.320
maccatalyst                16.4.7067/7.0.100      SDK 7.0.300, VS 17.6.33815.320, VS 17.6.33815.320
wasm-tools                 7.0.7/7.0.100          SDK 7.0.300, VS 17.6.33815.320
maui-windows               7.0.86/7.0.100         VS 17.6.33815.320, VS 17.6.33815.320
maui-ios                   7.0.86/7.0.100         VS 17.6.33815.320, VS 17.6.33815.320
maui-android               7.0.86/7.0.100         VS 17.6.33815.320, VS 17.6.33815.320
maui-maccatalyst           7.0.86/7.0.100         VS 17.6.33815.320, VS 17.6.33815.320`

StackTrace: 
```
  at Microsoft.Maui.Layouts.GridLayoutManager.ArrangeChildren(Rect bounds) in D:\a\_work\1\s\src\Core\src\Layouts\GridLayoutManager.cs:line 44
   at Microsoft.Maui.Controls.Layout.CrossPlatformArrange(Rect bounds) in D:\a\_work\1\s\src\Controls\src\Core\Layout\Layout.cs:line 287
   at Microsoft.Maui.Platform.LayoutViewGroup.OnLayout(Boolean changed, Int32 l, Int32 t, Int32 r, Int32 b) in D:\a\_work\1\s\src\Core\src\Platform\Android\LayoutViewGroup.cs:line 96
   at Android.Views.ViewGroup.n_OnLayout_ZIIII(IntPtr jnienv, IntPtr native__this, Boolean changed, Int32 l, Int32 t, Int32 r, Int32 b) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net7.0/android-33/mcw/Android.Views.ViewGroup.cs:line 3655
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPZIIII_V(_JniMarshal_PPZIIII_V callback, IntPtr jnienv, IntPtr klazz, Boolean p0, Int32 p1, Int32 p2, Int32 p3, Int32 p4) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 429
```

**Comment by samhouts** [comment]
I can't reproduce this on 7.0.92.

**Comment by marchev-prgs** [comment]
Hi, I just tested with 7.0.92 and with 8.0.0-preview.7.8842 and in both case the issue is fixed! Thanks!

**Comment by samhouts** [comment]
Hooray!!! Thank you!!!
