### ISSUE TITLE
XAML Hot Reload not working for Android after Visual Studio Update to 17.6.4

### ISSUE THREAD

**Issue by hassanraf** [dotnet/maui#15842]
### Description

For Android , XAML Hot Reload fails to initialize after I upgraded to Visual Studio 17.6.4 from 17.6.2.
It was working fine on the previous version. It still works fine when debugging on Windows but not on Android. I did not check iOS

### Steps to Reproduce

- Create a new .net MAUI Application
- Connect with Android Device in debug mode
- XAML Hot Reload fails to initialize

Following is the output from XAML Hot Reload Window:

[10:29:44]  (MauiApp1) .NET Project references .NET MAUI.
[10:29:44]  (MauiApp1) Starting Hot Reload session...
[10:29:53]  XAML Hot Reload initializing...
[10:30:00]  Caught exception in AgentStatusChangedHandler at 317: Xamarin.HotReload.DebuggerTimeoutException: Failed to Inject Assembly ---> Mono.Debugging.Evaluation.TimeOutException: Timed out.
   at Mono.Debugging.Evaluation.AsyncOperationManager.Invoke(AsyncOperation methodCall, Int32 timeout) in D:\a\_work\1\s\External\debugger-libs\Mono.Debugging\Mono.Debugging.Evaluation\AsyncOperationManager.cs:line 68
   at Mono.Debugging.Soft.SoftEvaluationContext.RuntimeInvoke(MethodMirror method, Object target, Value[] values, Boolean enableOutArgs, Value[]& outArgs) in D:\a\_work\1\s\External\debugger-libs\Mono.Debugging.Soft\SoftEvaluationContext.cs:line 200
   at Mono.Debugging.Soft.SoftDebuggerAdaptor.RuntimeInvoke(EvaluationContext ctx, Object targetType, Object target, String methodName, Object[] genericTypeArgs, Object[] argTypes, Object[] argValues, Boolean enableOutArgs, Object[]& outArgs) in D:\a\_work\1\s\External\debugger-libs\Mono.Debugging.Soft\SoftDebuggerAdaptor.cs:line 2352
   at Mono.Debugging.Soft.SoftDebuggerAdaptor.RuntimeInvoke(EvaluationContext ctx, Object targetType, Object target, String methodName, Object[] genericTypeArgs, Object[] argTypes, Object[] argValues) in D:\a\_work\1\s\External\debugger-libs\Mono.Debugging.Soft\SoftDebuggerAdaptor.cs:line 2281
   at Xamarin.HotReload.DebuggerExtensions.InjectAndLoadAssembly(SoftEvaluationContext context, IProject project, String assemblyPath) in D:\a\_work\1\s\HotReload\Source\Xamarin.HotReload.Bridge\DebuggerExtensions.cs:line 60
   --- End of inner exception stack trace ---
   at Xamarin.HotReload.DebuggerExtensions.InjectAndLoadAssembly(SoftEvaluationContext context, IProject project, String assemblyPath) in D:\a\_work\1\s\HotReload\Source\Xamarin.HotReload.Bridge\DebuggerExtensions.cs:line 71
   at Xamarin.HotReload.HotReloadBridge.<InitializeAgentAsync>d__58.MoveNext() in D:\a\_work\1\s\HotReload\Source\Xamarin.HotReload.Bridge\HotReloadBridge.cs:line 168
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.HotReload.HotReloadBridge.<<Debugger_TargetHitBreakpoint>b__64_0>d.MoveNext() in D:\a\_work\1\s\HotReload\Source\Xamarin.HotReload.Bridge\HotReloadBridge.cs:line 417
   at Xamarin.HotReload.DebuggerExtensions.InjectAndLoadAssembly(SoftEvaluationContext context, IProject project, String assemblyPath) in D:\a\_work\1\s\HotReload\Source\Xamarin.HotReload.Bridge\DebuggerExtensions.cs:line 71
   at Xamarin.HotReload.HotReloadBridge.<InitializeAgentAsync>d__58.MoveNext() in D:\a\_work\1\s\HotReload\Source\Xamarin.HotReload.Bridge\HotReloadBridge.cs:line 168
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.HotReload.HotReloadBridge.<<Debugger_TargetHitBreakpoint>b__64_0>d.MoveNext() in D:\a\_work\1\s\HotReload\Source\Xamarin.HotReload.Bridge\HotReloadBridge.cs:line 417
[10:30:00]  XAML Hot Reload encountered a problem and failed to start. Use Help -> Report a Problem if the issues persists.
[10:30:00]  Stopping All Hot Reload sessions due to Failed ...
[10:30:00]  (MauiApp1) Stopping a Hot Reload session due to Failed ...
[10:30:00]  Stopped Hot Reload session.
[10:30:00]  (MauiApp1) Caught exception in Debugger_TargetHitBreakpoint at 422: Xamarin.HotReload.DebuggerTimeoutException: Failed to Inject Assembly ---> Mono.Debugging.Evaluation.TimeOutException: Timed out.
   at Mono.Debugging.Evaluation.AsyncOperationManager.Invoke(AsyncOperation methodCall, Int32 timeout) in D:\a\_work\1\s\External\debugger-libs\Mono.Debugging\Mono.Debugging.Evaluation\AsyncOperationManager.cs:line 68
   at Mono.Debugging.Soft.SoftEvaluationContext.RuntimeInvoke(MethodMirror method, Object target, Value[] values, Boolean enableOutArgs, Value[]& outArgs) in D:\a\_work\1\s\External\debugger-libs\Mono.Debugging.Soft\SoftEvaluationContext.cs:line 200
   at Mono.Debugging.Soft.SoftDebuggerAdaptor.RuntimeInvoke(EvaluationContext ctx, Object targetType, Object target, String methodName, Object[] genericTypeArgs, Object[] argTypes, Object[] argValues, Boolean enableOutArgs, Object[]& outArgs) in D:\a\_work\1\s\External\debugger-libs\Mono.Debugging.Soft\SoftDebuggerAdaptor.cs:line 2352
   at Mono.Debugging.Soft.SoftDebuggerAdaptor.RuntimeInvoke(EvaluationContext ctx, Object targetType, Object target, String methodName, Object[] genericTypeArgs, Object[] argTypes, Object[] argValues) in D:\a\_work\1\s\External\debugger-libs\Mono.Debugging.Soft\SoftDebuggerAdaptor.cs:line 2281
   at Xamarin.HotReload.DebuggerExtensions.InjectAndLoadAssembly(SoftEvaluationContext context, IProject project, String assemblyPath) in D:\a\_work\1\s\HotReload\Source\Xamarin.HotReload.Bridge\DebuggerExtensions.cs:line 60
   --- End of inner exception stack trace ---
   at Xamarin.HotReload.DebuggerExtensions.InjectAndLoadAssembly(SoftEvaluationContext context, IProject project, String assemblyPath) in D:\a\_work\1\s\HotReload\Source\Xamarin.HotReload.Bridge\DebuggerExtensions.cs:line 71
   at Xamarin.HotReload.HotReloadBridge.<InitializeAgentAsync>d__58.MoveNext() in D:\a\_work\1\s\HotReload\Source\Xamarin.HotReload.Bridge\HotReloadBridge.cs:line 168
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.HotReload.HotReloadBridge.<<Debugger_TargetHitBreakpoint>b__64_0>d.MoveNext() in D:\a\_work\1\s\HotReload\Source\Xamarin.HotReload.Bridge\HotReloadBridge.cs:line 417
   at Xamarin.HotReload.DebuggerExtensions.InjectAndLoadAssembly(SoftEvaluationContext context, IProject project, String assemblyPath) in D:\a\_work\1\s\HotReload\Source\Xamarin.HotReload.Bridge\DebuggerExtensions.cs:line 71
   at Xamarin.HotReload.HotReloadBridge.<InitializeAgentAsync>d__58.MoveNext() in D:\a\_work\1\s\HotReload\Source\Xamarin.HotReload.Bridge\HotReloadBridge.cs:line 168
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.HotReload.HotReloadBridge.<<Debugger_TargetHitBreakpoint>b__64_0>d.MoveNext() in D:\a\_work\1\s\HotReload\Source\Xamarin.HotReload.Bridge\HotReloadBridge.cs:line 417
[10:30:05]  (MauiApp1) .NET Project references .NET MAUI.

### Link to public reproduction project repository

https://github.com/hassanraf/MauiApp1

### Version with bug

Unknown/Other

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Latest Android Version and SDK

**Comment by drasticactions** [comment]
@hassanraf To the best of my knowledge, there were no code changes in XAML Hot Reload itself between those two versions of Visual Studio, which suggests to me an underlying dependency change within VS (Which XAML Hot Reload depends on) could be at fault.

Does general debugging in Android work for you? Can you set a breakpoint within the application and have it hit?

**Comment by hassanraf** [comment]
Thanks for your reply @drasticactions , yes general debugging works. It might have been 17.6.1 that I upgraded from ( sorry I can't recall the base version exactly). are you able to reproduce the issue at your end using a new Maui project?

Many Thanks

**Comment by drasticactions** [comment]
I cannot, in 17.6 nor 17.7. But I do know there were issues with 17.6 versions of visual studio recently where the debugger libraries were problematic, and since that's how XAML Hot Reload communicates, that since you have timeouts with the soft debugger, that would lead me to think that's the issue. As the bot says above, I would file this to vsfeedback to have more diagnostics data. This is not a MAUI issue, it's a Visual Studio one.

**Comment by spadapet** [comment]
@hassanraf is hot reload for Android device still broken for you with the latest 17.7 release and .NET 8 preview?

**Comment by BretJohnson** [comment]
@hassanraf - I tested with VS 17.7 and Android Hot Reload (with an emulator) and that simple test worked for me. If you can still reproduce any issues here with VS 17.7 (or newer) please let us know. Thanks.
