### ISSUE TITLE
Entry fields do not work correctly if bound to a numeric property from a ViewModel

### ISSUE THREAD

**Issue by asifshakir** [dotnet/maui#15846]
### Description

If you bind an Entry field to a numeric property in a View Model and then type a value into it and then try to blank out the value, the bound property will not get set to a zero or a null value, rather it will retain the value of the first typed digit.

### Steps to Reproduce

1. Create a new Project -> File -> New -> MAUI Project
2. Add a View Model class -> MainViewModel.cs
3. Add a numeric property to the view model as an Observable Property -> Counter
4. Bind the view model to the MainView page
5. Bind the Counter property to a Label
6. Bind the Counter property to an Entry field with a Numeric Keyboard
7. Type a value in the Counter Field
8. Try to delete all values in the Field using backspace

Expected: The bound property "Counter" should become null or zero
Actual: The bound property will retain the value of the first typed digit

### Link to public reproduction project repository

https://github.com/asifshakir/MauiEntryFieldBug

### Version with bug

7.0.49

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 11

### Did you find any workaround?

We are currently using a string property in the View Model when binding it to a Page and then we convert the string value back to a number when submitting it to the API.

**Comment by Xyncgas** [comment]
Supposed it's fixable, can null value be what you want, or 0
Maybe it is doing nothing, when failing to parse empty text to a number, so the default should be setting to 0 or null rather than doing nothing

**Comment by asifshakir** [comment]
The bound numeric property should have the value null if the underlying type is nullable and zero for non-nullable types. 

Currently, it retains the first typed number i.e. if I type 911 and I press the backspace button the final value in the bound property field would be 9 although the screen shows that everything has been cleared out.

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 5.0. Repro on Windows 11 .NET 8, Android 13.0-API33 and iOS 16.4 with below Project:
[MauiToolkitTest.zip](https://github.com/dotnet/maui/files/12192200/MauiToolkitTest.zip)

![image](https://github.com/dotnet/maui/assets/97647558/b86dcb29-f549-4c77-bb33-682169f333c5)
![image](https://github.com/dotnet/maui/assets/97647558/68fd3643-6304-4f92-ac92-45898c0601ee)
![image](https://github.com/dotnet/maui/assets/97647558/6f8efe15-1cd4-4f0d-a06b-c9b926a435cf)

**Comment by Adan0s** [comment]
This problem still exists in .NET 8 RC2

**Comment by marcfabregatb** [comment]
having the same issue too. I have workaround it converting the value into a string, and then converting it back to decimal. But it is a nasty solution

**Comment by Xyncgas** [comment]
That's object oriented programming for you

**Comment by MJSanfelippo** [comment]
Any updates on this one? The workaround is gross and it seems pretty basic.

**Comment by BTSoft308** [comment]
Roba da torta

**Comment by V-Brandi** [comment]
Microsoft… wait a little longer to fix your bugs! 🤣

**Comment by kramer-e** [comment]
You can also add a converter to convert the empty string '' back to null or 0.

    public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
    {
        if (value is string stringValue && stringValue == string.Empty)
        {
            return 0;
        }

        return value;
    }

**Comment by willcorum** [comment]
Here's what I did. I created an int field and an associated string field (which is bound to the entry control), then use the onchange event of the string property to update the int property. This has the advantage of not breaking the NotifyCanExecuteChangedFor wiring so the save button on my form still flips back and forth from enabled to disabled via the CanExecute attribute on the associated RelayCommand.

```
        [ObservableProperty]
        [NotifyCanExecuteChangedFor(nameof(SaveCommand))]
        int? myNumber;

        [ObservableProperty]
        [NotifyCanExecuteChangedFor(nameof(SaveCommand))]
        string myNumberString;

        partial void OnMyNumberStringChanged(string value)
        {
            int.TryParse(value, out int v);
            MyNumber = v;
        }

```

**Comment by MJSanfelippo** [comment]
> Here's what I did. I created an int field and an associated string field (which is bound to the entry control), then use the onchange event of the string property to update the int property. This has the advantage of not breaking the NotifyCanExecuteChangedFor wiring so the save button on my form still flips back and forth from enabled to disabled via the CanExecute attribute on the associated RelayCommand.
> 
> ```
>         [ObservableProperty]
>         [NotifyCanExecuteChangedFor(nameof(SaveCommand))]
>         int? myNumber;
> 
>         [ObservableProperty]
>         [NotifyCanExecuteChangedFor(nameof(SaveCommand))]
>         string myNumberString;
> 
>         partial void OnMyNumberStringChanged(string value)
>         {
>             int.TryParse(value, out int v);
>             MyNumber = v;
>         }
> 
> ```
> 

Nice solution. It would be great if we didn't have to do that.

**Comment by mattleibow** [comment]
I tested on WPF and they go into an error state - aka match MAUI today:

```xaml
<TextBox Text="{Binding Value, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}" />
```

![image](https://github.com/dotnet/maui/assets/1096616/d4acdbf9-4263-44f9-ab49-21dee4d51b88)

```
System.Windows.Data Error: 7 : ConvertBack cannot convert value '' (type 'String'). BindingExpression:Path=Value; DataItem='MainWindow' (Name=''); target element is 'TextBox' (Name=''); target property is 'Text' (type 'String') FormatException:'System.FormatException: The input string '' was not in a correct format.
   at System.Number.ThrowFormatException[TChar](ReadOnlySpan`1 value)
   at System.String.System.IConvertible.ToInt32(IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at System.Windows.Data.BindingExpression.ConvertBackHelper(IValueConverter converter, Object value, Type sourceType, Object parameter, CultureInfo culture)'
```

And WPF is worse than MAUI because binding to a double does not allow me to even type `0.` so no decimal values allowed in WPF.

**Comment by mattleibow** [comment]
This is harder to fix because of all the corner cases - like this: you can't type negative numbers. Already I am suspicious of our special handing of decimals. I wonder if your culture used different symbols will maui still work? WPF chose not to do anything.


https://github.com/dotnet/maui/assets/42434498/e5817fb4-75f1-49b1-93b0-a0fd5ec77413

**Comment by CodingOctocat** [comment]
@mattleibow I think the current behavior is the most generic, the user should bind to vm.StringNumber and handle the data in the setter.

```cs
public string StringNumber
{
    get => _stringNumber;
    set
    {
        if (SetProperty(ref _stringNumber, value))
        {
            // convert to double
            // notify other properties
            // ...
        }
    }
}
```

**Comment by 999Jacky** [comment]
Can use a custom binding converter
I think this is best workaround 

``` c#
public class EntryToNullableIntConverter: IValueConverter {

        public object? Convert(object? value, Type targetType, object? parameter, CultureInfo culture) {
            return (int?) value;
        }
        public object? ConvertBack(object? value, Type targetType, object? parameter, CultureInfo culture) {
            if (value == null) {
                return null;
            }
            var isOk = int.TryParse(value.ToString(), out var num);
            if (!isOk) {
                return null;
            }
            return (int?) num;
        }
    }
```

**Comment by cmoya212** [comment]
> I tested on WPF and they go into an error state - aka match MAUI today:
> 
> <TextBox Text="{Binding Value, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}" />
> ![image](https://github.com/dotnet/maui/assets/1096616/d4acdbf9-4263-44f9-ab49-21dee4d51b88)
> 
> ```
> System.Windows.Data Error: 7 : ConvertBack cannot convert value '' (type 'String'). BindingExpression:Path=Value; DataItem='MainWindow' (Name=''); target element is 'TextBox' (Name=''); target property is 'Text' (type 'String') FormatException:'System.FormatException: The input string '' was not in a correct format.
>    at System.Number.ThrowFormatException[TChar](ReadOnlySpan`1 value)
>    at System.String.System.IConvertible.ToInt32(IFormatProvider provider)
>    at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
>    at System.Windows.Data.BindingExpression.ConvertBackHelper(IValueConverter converter, Object value, Type sourceType, Object parameter, CultureInfo culture)'
> ```
> 
> And WPF is worse than MAUI because binding to a double does not allow me to even type `0.` so no decimal values allowed in WPF.

Just as somewhat of a sidenote: WinForms 2-way binding seems to behave _exactly_ the same way as WPF including the no-decimal thing.
