### ISSUE TITLE
Crash when using a Flyout page with a footer on Android: Java.Lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.

### ISSUE THREAD

**Issue by brunck** [dotnet/maui#16043]
### Description

Starting a .NET MAUI app on Android with a "standard" Flyout (non-Shell) page as the main page with a footer set along with other various controls crashes on startup.
Couldn't test on iOS at this time due to .NET iOS apps not building for me via Windows due to an already-reported issue.

Also broken on .NET 7. Same setup worked in Xamarin.Forms 5.

### Steps to Reproduce

1. .NET MAUI application that uses a Flyout page as the main page (use the sample repository)
2. Run on Android

Expected: a blank page shows up with the name of the page as the title (seems to be the default behavior)

Actual: Crash with provided stack trace.

### Link to public reproduction project repository

https://github.com/brunck/reproductions/tree/master/AndroidFlyoutCrashRepro/TestMauiAndroid

### Version with bug

8.0.0-preview.5.8529

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12 and up

### Did you find any workaround?

Commenting-out the line `listView.Footer = footerLayout;` gets past it. Must be something to do with what's being put into the footer.

### Relevant log output

```shell
Java.Lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.   at Java.Interop.JniEnvironment.InstanceMethods.CallNonvirtualVoidMethod(JniObjectReference instance, JniObjectReference type, JniMethodInfo method, JniArgumentValue* args) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/obj/Release/net7.0/JniEnvironment.g.cs:line 12324   at Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualVoidMethod(String encodedMember, IJavaPeerable self, JniArgumentValue* parameters) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:line 75   at Android.Views.ViewGroup.AddView(View child) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net8.0/android-33/mcw/Android.Views.ViewGroup.cs:line 2147   at Microsoft.Maui.Handlers.LayoutHandler.SetVirtualView(IView view) in D:\a\_work\1\s\src\Core\src\Handlers\Layout\LayoutHandler.Android.cs:line 43   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.ILayout, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.LayoutViewGroup, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IElement view) in D:\a\_work\1\s\src\Core\src\Handlers\View\ViewHandlerOfT.cs:line 56   at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler) in D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\Element\Element.Impl.cs:line 70   at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value) in D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\Element\Element.Impl.cs:line 20   at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.set_Handler(IElementHandler value) in D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\VisualElement\VisualElement.Impl.cs:line 305   at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context) in D:\a\_work\1\s\src\Core\src\Platform\ElementExtensions.cs:line 96   at Microsoft.Maui.Platform.ElementExtensions.ToPlatform(IElement view, IMauiContext context) in D:\a\_work\1\s\src\Core\src\Platform\ElementExtensions.cs:line 127   at Microsoft.Maui.Controls.Handlers.Compatibility.ListViewRenderer.UpdateFooter() in D:\a\_work\1\s\src\Controls\src\Core\Compatibility\Handlers\ListView\Android\ListViewRenderer.cs:line 420   at Microsoft.Maui.Controls.Handlers.Compatibility.ListViewRenderer.OnElementChanged(ElementChangedEventArgs`1 e) in D:\a\_work\1\s\src\Controls\src\Core\Compatibility\Handlers\ListView\Android\ListViewRenderer.cs:line 174   at Microsoft.Maui.Controls.Handlers.Compatibility.VisualElementRenderer`1[[Microsoft.Maui.Controls.ListView, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IElement view, IPlatformViewHandler nativeViewHandler, Action`1 onElementChanged, ListView& currentVirtualView, IPropertyMapper& _mapper, IPropertyMapper _defaultMapper, Boolean autoPackage) in D:\a\_work\1\s\src\Controls\src\Core\Compatibility\Handlers\VisualElementRenderer.cs:line 252   at Microsoft.Maui.Controls.Handlers.Compatibility.VisualElementRenderer`1[[Microsoft.Maui.Controls.ListView, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].Microsoft.Maui.IElementHandler.SetVirtualView(IElement view) in D:\a\_work\1\s\src\Controls\src\Core\Compatibility\Handlers\VisualElementRenderer.cs:line 287   at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler) in D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\Element\Element.Impl.cs:line 70   at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value) in D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\Element\Element.Impl.cs:line 20   at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.set_Handler(IElementHandler value) in D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\VisualElement\VisualElement.Impl.cs:line 305   at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context) in D:\a\_work\1\s\src\Core\src\Platform\ElementExtensions.cs:line 96   at Microsoft.Maui.Platform.ElementExtensions.ToPlatform(IElement view, IMauiContext context) in D:\a\_work\1\s\src\Core\src\Platform\ElementExtensions.cs:line 127   at Microsoft.Maui.Handlers.LayoutHandler.SetVirtualView(IView view) in D:\a\_work\1\s\src\Core\src\Handlers\Layout\LayoutHandler.Android.cs:line 43   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.ILayout, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.LayoutViewGroup, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IElement view) in D:\a\_work\1\s\src\Core\src\Handlers\View\ViewHandlerOfT.cs:line 56   at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler) in D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\Element\Element.Impl.cs:line 70   at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value) in D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\Element\Element.Impl.cs:line 20   at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.set_Handler(IElementHandler value) in D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\VisualElement\VisualElement.Impl.cs:line 305   at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context) in D:\a\_work\1\s\src\Core\src\Platform\ElementExtensions.cs:line 96   at Microsoft.Maui.Platform.ElementExtensions.ToPlatform(IElement view, IMauiContext context) in D:\a\_work\1\s\src\Core\src\Platform\ElementExtensions.cs:line 127   at Microsoft.Maui.Handlers.ContentViewHandler.UpdateContent(IContentViewHandler handler) in D:\a\_work\1\s\src\Core\src\Handlers\ContentView\ContentViewHandler.Android.cs:line 44   at Microsoft.Maui.Handlers.ContentViewHandler.MapContent(IContentViewHandler handler, IContentView page) in D:\a\_work\1\s\src\Core\src\Handlers\ContentView\ContentViewHandler.Android.cs:line 49   at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0[[Microsoft.Maui.IContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.IContentViewHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v) in D:\a\_work\1\s\src\Core\src\PropertyMapper.cs:line 172   at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IElementHandler viewHandler, IElement virtualView) in D:\a\_work\1\s\src\Core\src\PropertyMapper.cs:line 47   at Microsoft.Maui.PropertyMapper.UpdateProperties(IElementHandler viewHandler, IElement virtualView) in D:\a\_work\1\s\src\Core\src\PropertyMapper.cs:line 82   at Microsoft.Maui.Handlers.ElementHandler.SetVirtualView(IElement view) in D:\a\_work\1\s\src\Core\src\Handlers\Element\ElementHandler.cs:line 79   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.ContentViewGroup, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IView view) in D:\a\_work\1\s\src\Core\src\Handlers\View\ViewHandlerOfT.cs:line 53   at Microsoft.Maui.Handlers.ContentViewHandler.SetVirtualView(IView view) in D:\a\_work\1\s\src\Core\src\Handlers\ContentView\ContentViewHandler.Android.cs:line 27   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.ContentViewGroup, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IElement view) in D:\a\_work\1\s\src\Core\src\Handlers\View\ViewHandlerOfT.cs:line 56   at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler) in D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\Element\Element.Impl.cs:line 70   at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value) in D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\Element\Element.Impl.cs:line 20   at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.set_Handler(IElementHandler value) in D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\VisualElement\VisualElement.Impl.cs:line 305   at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context) in D:\a\_work\1\s\src\Core\src\Platform\ElementExtensions.cs:line 96   at Microsoft.Maui.Platform.ElementExtensions.ToPlatform(IElement view, IMauiContext context) in D:\a\_work\1\s\src\Core\src\Platform\ElementExtensions.cs:line 127   at Microsoft.Maui.Handlers.FlyoutViewHandler.UpdateFlyout() in D:\a\_work\1\s\src\Core\src\Handlers\FlyoutView\FlyoutViewHandler.Android.cs:line 101   at Microsoft.Maui.Handlers.FlyoutViewHandler.MapFlyout(IFlyoutViewHandler handler, IFlyoutView flyoutView) in D:\a\_work\1\s\src\Core\src\Handlers\FlyoutView\FlyoutViewHandler.Android.cs:line 293   at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0[[Microsoft.Maui.IFlyoutView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.IFlyoutViewHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v) in D:\a\_work\1\s\src\Core\src\PropertyMapper.cs:line 172   at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IElementHandler viewHandler, IElement virtualView) in D:\a\_work\1\s\src\Core\src\PropertyMapper.cs:line 47   at Microsoft.Maui.PropertyMapper.UpdateProperties(IElementHandler viewHandler, IElement virtualView) in D:\a\_work\1\s\src\Core\src\PropertyMapper.cs:line 82   at Microsoft.Maui.Handlers.ElementHandler.SetVirtualView(IElement view) in D:\a\_work\1\s\src\Core\src\Handlers\Element\ElementHandler.cs:line 79   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IFlyoutView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Android.Views.View, Mono.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065]].SetVirtualView(IView view) in D:\a\_work\1\s\src\Core\src\Handlers\View\ViewHandlerOfT.cs:line 53   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IFlyoutView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Android.Views.View, Mono.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065]].SetVirtualView(IElement view) in D:\a\_work\1\s\src\Core\src\Handlers\View\ViewHandlerOfT.cs:line 56   at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler) in D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\Element\Element.Impl.cs:line 70   at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value) in D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\Element\Element.Impl.cs:line 20   at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.set_Handler(IElementHandler value) in D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\VisualElement\VisualElement.Impl.cs:line 305   at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context) in D:\a\_work\1\s\src\Core\src\Platform\ElementExtensions.cs:line 96   at Microsoft.Maui.Platform.ElementExtensions.ToPlatform(IElement view, IMauiContext context) in D:\a\_work\1\s\src\Core\src\Platform\ElementExtensions.cs:line 127   at Microsoft.Maui.Platform.ContainerView.SetView(IElement view, Boolean forceRefresh) in D:\a\_work\1\s\src\Core\src\Platform\Android\ContainerView.cs:line 76   at Microsoft.Maui.Platform.ContainerView.set_CurrentView(IElement value) in D:\a\_work\1\s\src\Core\src\Platform\Android\ContainerView.cs:line 55   at Microsoft.Maui.Platform.ElementExtensions.ToContainerView(IElement view, IMauiContext context) in D:\a\_work\1\s\src\Core\src\Platform\Android\ElementExtensions.cs:line 11   at Microsoft.Maui.Platform.NavigationRootManager.Connect(IView view, IMauiContext mauiContext) in D:\a\_work\1\s\src\Core\src\Platform\Android\Navigation\NavigationRootManager.cs:line 56   at Microsoft.Maui.Handlers.WindowHandler.CreateRootViewFromContent(IWindowHandler handler, IWindow window) in D:\a\_work\1\s\src\Core\src\Handlers\Window\WindowHandler.Android.cs:line 91   at Microsoft.Maui.Handlers.WindowHandler.MapContent(IWindowHandler handler, IWindow window) in D:\a\_work\1\s\src\Core\src\Handlers\Window\WindowHandler.Android.cs:line 27   at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0[[Microsoft.Maui.IWindow, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.IWindowHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v) in D:\a\_work\1\s\src\Core\src\PropertyMapper.cs:line 172   at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IElementHandler viewHandler, IElement virtualView) in D:\a\_work\1\s\src\Core\src\PropertyMapper.cs:line 47   at Microsoft.Maui.PropertyMapper.UpdateProperties(IElementHandler viewHandler, IElement virtualView) in D:\a\_work\1\s\src\Core\src\PropertyMapper.cs:line 82   at Microsoft.Maui.Handlers.ElementHandler.SetVirtualView(IElement view) in D:\a\_work\1\s\src\Core\src\Handlers\Element\ElementHandler.cs:line 79   at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler) in D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\Element\Element.Impl.cs:line 70   at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value) in D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\Element\Element.Impl.cs:line 20   at Microsoft.Maui.Platform.ElementExtensions.SetHandler(Context nativeElement, IElement element, IMauiContext context) in D:\a\_work\1\s\src\Core\src\Platform\ElementExtensions.cs:line 156   at Microsoft.Maui.Platform.ElementExtensions.SetWindowHandler(Activity platformWindow, IWindow window, IMauiContext context) in D:\a\_work\1\s\src\Core\src\Platform\ElementExtensions.cs:line 166   at Microsoft.Maui.Platform.ApplicationExtensions.CreatePlatformWindow(Activity activity, IApplication application, Bundle savedInstanceState) in D:\a\_work\1\s\src\Core\src\Platform\Android\ApplicationExtensions.cs:line 48   at Microsoft.Maui.MauiAppCompatActivity.OnCreate(Bundle savedInstanceState) in D:\a\_work\1\s\src\Core\src\Platform\Android\MauiAppCompatActivity.cs:line 32   at MigrateXamForms.Droid.MainActivity.OnCreate(Bundle savedInstanceState) in C:\Users\brunck\source\repos\TestMauiAndroid\MigrateXamForms.Android\MainActivity.cs:line 13   at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_(IntPtr jnienv, IntPtr native__this, IntPtr native_savedInstanceState) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net8.0/android-33/mcw/Android.App.Activity.cs:line 2867   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPL_V(_JniMarshal_PPL_V callback, IntPtr jnienv, IntPtr klazz, IntPtr p0) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 121  --- End of managed Java.Lang.IllegalStateException stack trace ---java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.	at android.view.ViewGroup.addViewInner(ViewGroup.java:6065)	at android.view.ViewGroup.addView(ViewGroup.java:5884)	at android.view.ViewGroup.addView(ViewGroup.java:5824)	at android.view.ViewGroup.addView(ViewGroup.java:5796)	at crc647352de5cfa5d59ef.MainActivity.n_onCreate(Native Method)	at crc647352de5cfa5d59ef.MainActivity.onCreate(MainActivity.java:39)	at android.app.Activity.performCreate(Activity.java:8198)	at android.app.Activity.performCreate(Activity.java:8182)	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3765)	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3968)	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)	at android.os.Handler.dispatchMessage(Handler.java:106)	at android.os.Looper.loop(Looper.java:246)	at android.app.ActivityThread.main(ActivityThread.java:8512)	at java.lang.reflect.Method.invoke(Native Method)	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)  --- End of managed Java.Lang.IllegalStateException stack trace ---java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.	at android.view.ViewGroup.addViewInner(ViewGroup.java:6065)	at android.view.ViewGroup.addView(ViewGroup.java:5884)	at android.view.ViewGroup.addView(ViewGroup.java:5824)	at android.view.ViewGroup.addView(ViewGroup.java:5796)	at crc647352de5cfa5d59ef.MainActivity.n_onCreate(Native Method)	at crc647352de5cfa5d59ef.MainActivity.onCreate(MainActivity.java:39)	at android.app.Activity.performCreate(Activity.java:8198)	at android.app.Activity.performCreate(Activity.java:8182)	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3765)	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3968)	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)	at android.os.Handler.dispatchMessage(Handler.java:106)	at android.os.Looper.loop(Looper.java:246)	at android.app.ActivityThread.main(ActivityThread.java:8512)	at java.lang.reflect.Method.invoke(Native Method)	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

**Comment by QianaJiao** [comment]
Verified this issue with Visual Studio Enterprise 17.9.0 Preview 4. Can repro on Windows platform with sample project.
https://github.com/brunck/reproductions/tree/master/AndroidFlyoutCrashRepro/TestMauiAndroid

**Comment by bnSonic** [comment]
Oh dear … 

Same Problem with just a ListView

This one gives the crash (Child already has a parent)
Crash only happens on Android - it works fine on iOS!

```
<ContentPage ...>
    <ContentView 
        BackgroundColor="{DynamicResource BaseBackgroundColor}"
        Padding="0, 0, 0, 0"
        >
        <Grid IgnoreSafeArea="True">

            <Border 
                BackgroundColor="{DynamicResource BaseBackgroundColor}"
                StrokeShape="RoundRectangle 0">

                <ListView 
                    x:Name="ListView1" 
                    Grid.Row="0"
                    ItemTemplate="{StaticResource BaustelleTemplateSelector}"
                    BackgroundColor="Transparent"
                    HasUnevenRows="True"
                    SeparatorVisibility="None"
                    ItemsSource="{Binding Items}"
                    >
                    <ListView.Footer>
                        <BoxView HeightRequest="50" BackgroundColor="{DynamicResource DataBackgroundColor}"/>
                    </ListView.Footer>

                </ListView>
            </Border>

        </Grid>

    </ContentView>

</ContentPage>
```

And this one works (No Footer)
```
...
                <ListView 
                    x:Name="ListView1" 
                    Grid.Row="0"
                    ItemTemplate="{StaticResource BaustelleTemplateSelector}"
                    BackgroundColor="Transparent"
                    HasUnevenRows="True"
                    SeparatorVisibility="None"
                    ItemsSource="{Binding Items}"
                    >

                </ListView>

...
```

Any known workaround? 
I need the ListView to have a little bit of extra space at the bottom because of the Fullscreen scroll view 

(maybe I have to extend the logic of the Items and the TemplateSelector to add a "Spacer-Item" at the end - but I'm hoping for a better solution or a fix)

**Comment by brunck** [comment]
Nope. We had to cease using the footer for this and use a label underneath the ListView instead.

**Comment by bnSonic** [comment]
If you found this issue via a search - just for your information:
This MAY happen with the `ListViewHeaderTemplate` too 

I got two crash-logs like 

```
The specified child already has a parent. You must call removeView() on the child's parent first.
 
StackTrace:
  at Java.Interop.JniEnvironment.InstanceMethods.CallNonvirtualVoidMethod(JniObjectReference , JniObjectReference , JniMethodInfo , JniArgumentValue* )
  at Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualVoidMethod(String , IJavaPeerable , JniArgumentValue* )
  at Android.Views.ViewGroup.AddView(View , Int32 )
  at Microsoft.Maui.Controls.Handlers.Compatibility.ListViewAdapter.GetView(Int32 position, View convertView, ViewGroup parent)
  at Android.Widget.BaseAdapter.n_GetView_ILandroid_view_View_Landroid_view_ViewGroup_(IntPtr jnienv, IntPtr native__this, Int32 position, IntPtr native_convertView, IntPtr native_parent)
  at Android.Runtime.DynamicMethodNameCounter.10(IntPtr , IntPtr , Int32 , IntPtr , IntPtr )
 --- End of managed Java.Lang.IllegalStateException stack trace ---
java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
           at android.view.ViewGroup.addViewInner(ViewGroup.java:5291)
           at android.view.ViewGroup.addView(ViewGroup.java:5120)
           at android.view.ViewGroup.addView(ViewGroup.java:5060)
           at crc64e1fb321c08285b90.ListViewAdapter.n_getView(Native Method)
           at crc64e1fb321c08285b90.ListViewAdapter.getView(ListViewAdapter.java:93)
           at android.widget.HeaderViewListAdapter.getView(HeaderViewListAdapter.java:224)
           at android.widget.AbsListView.obtainView(AbsListView.java:2479)
           at android.widget.ListView.makeAndAddView(ListView.java:2065)
           at android.widget.ListView.fillDown(ListView.java:791)
           at android.widget.ListView.fillFromTop(ListView.java:853)
           at android.widget.ListView.layoutChildren(ListView.java:1836)
           at android.widget.AbsListView.onLayout(AbsListView.java:2276)
           at android.view.View.layout(View.java:25816)
           at android.view.ViewGroup.layout(ViewGroup.java:6462)
...
```

Both containing the `android.widget.HeaderViewListAdapter.getView(HeaderViewListAdapter.java:224)` Line and I'm using a Header Template in that List.

This crash doesn't happen every time. I fact, I have no idea why and when it happens. But getting two crashes from one tester alone ist enough for me to think about a different solution for this.

And beware: ListView is going to be deprecated in .net10 and from what I've read I'm pretty sure, no one will look at ListView issues anymore. The Maui Team is full steam ahead on CollectionView - and if they can fix the ground laying layout problems inside the collectionView I'm happy to switch :) … but currently I can't :( because of issues with CollectionView in almost every list I need to present
