### ISSUE TITLE
TabbedPage disappears if the UI is kill with a foreground service started

### ISSUE THREAD

**Issue by pierre-galaup** [dotnet/maui#16087]
### Description

Hello

I'm having a major problem migrating a XAMARIN FORMS application to MAUI.

I have a background service on Android (ForegroundService) running.
When I kill the UI of my application and relaunch the app (via notification or icon), the TabbedPage of my application has disappeared.

I have a FlyoutPage, which contains a TabbedPage.

I've attached a simple repo to reproduce the bug.
I started from this issue which seems to be related: https://github.com/dotnet/maui/issues/10318 which I have completed.

If you navigate after the TabbedPage has disappeared, you inevitably come across an exception, which I'm attaching to this ticket's log output.

### Steps to Reproduce

1. Download the code from my reproduction repo
2. Deploy the app on an Android device
3. Grant permissions
4. Sometimes you have to relaunch the app after giving permissions the first time.
5. Wait for service to launch (permanent notification)
6. Kill the UI/activity
7. Relaunch the application and see that the TabbedPage at the bottom has disappeared.

### Link to public reproduction project repository

https://github.com/pierre-galaup/repro-maui-tabbedpage-service

### Version with bug

7.0.86

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android MAUI .net 6 and 7

### Did you find any workaround?

No

### Relevant log output

```shell
Java.Lang.IllegalStateException: FragmentManager has been destroyed
  at Java.Interop.JniEnvironment.InstanceMethods.CallIntMethod(JniObjectReference instance, JniMethodInfo method, JniArgumentValue* args) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/obj/Release/net7.0/JniEnvironment.g.cs:line 11725
  at Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeAbstractInt32Method(String encodedMember, IJavaPeerable self, JniArgumentValue* parameters) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:line 492
  at AndroidX.Fragment.App.BackStackRecord.Commit()
  at Microsoft.Maui.Controls.Handlers.TabbedPageManager.SetTabLayout() in D:\a\_work\1\s\src\Controls\src\Core\Platform\Android\TabbedPageManager.cs:line 251
  at Microsoft.Maui.Controls.Handlers.TabbedPageManager.OnTabbedPageAppearing(Object sender, EventArgs e) in D:\a\_work\1\s\src\Controls\src\Core\Platform\Android\TabbedPageManager.cs:line 209
  at Microsoft.Maui.Controls.Page.SendAppearing() in D:\a\_work\1\s\src\Controls\src\Core\Page.cs:line 494
  at Microsoft.Maui.Controls.Page.SendAppearing() in D:\a\_work\1\s\src\Controls\src\Core\Page.cs:line 497
  at Microsoft.Maui.Controls.FlyoutPage.OnAppearing() in D:\a\_work\1\s\src\Controls\src\Core\FlyoutPage.cs:line 207
  at Microsoft.Maui.Controls.Page.SendAppearing() in D:\a\_work\1\s\src\Controls\src\Core\Page.cs:line 493
  at Microsoft.Maui.Controls.Internals.NavigationModel.PopModal() in D:\a\_work\1\s\src\Controls\src\Core\NavigationModel.cs:line 117
  at Microsoft.Maui.Controls.Platform.ModalNavigationManager.PopModalAsync(Boolean animated) in D:\a\_work\1\s\src\Controls\src\Core\Platform\ModalNavigationManager\ModalNavigationManager.Android.cs:line 64
  at Microsoft.Maui.Controls.Window.NavigationImpl.OnPopModal(Boolean animated) in D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\Window\Window.Impl.cs:line 693
  at MyApp.Infrastructure.NavigationUtilities.SafeGoBackAsyncImpl(INavigationService navigationService, IMainThread mainThread, INavigationParameters parameters, Boolean animated) in E:\Sources\MyApp\Infrastructure\NavigationUtilities.cs:line 214
--- End of managed Java.Lang.IllegalStateException stack trace ---

java.lang.IllegalStateException: FragmentManager has been destroyed
  at androidx.fragment.app.FragmentManager.enqueueAction(FragmentManager.java:1644)
  at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:341)
  at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:306)
  at crc64338477404e88479c.InnerGestureListener.n_onSingleTapUp(Native Method)
  at crc64338477404e88479c.InnerGestureListener.onSingleTapUp(InnerGestureListener.java:80)
  at android.view.GestureDetector.onTouchEvent(GestureDetector.java:752)
  at mono.android.view.View_OnTouchListenerImplementor.n_onTouch(Native Method)
  at mono.android.view.View_OnTouchListenerImplementor.onTouch(View_OnTouchListenerImplementor.java:31)
  at android.view.View.dispatchTouchEvent(View.java:15046)
  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3115)
  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2788)
  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
  at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:500)
  at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1912)
  at android.app.Activity.dispatchTouchEvent(Activity.java:4299)
  at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:70)
  at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:458)
  at android.view.View.dispatchPointerEvent(View.java:15309)
  at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6778)
  at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6578)
  at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6034)
  at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6091)
  at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6057)
  at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6222)
  at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6065)
  at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6279)
  at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6038)
  at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6091)
  at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6057)
  at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6065)
  at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6038)
  at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9206)
  at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9157)
  at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9126)
  at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9329)
  at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:267)
  at android.os.MessageQueue.nativePollOnce(Native Method)
  at android.os.MessageQueue.next(MessageQueue.java:335)
  at android.os.Looper.loopOnce(Looper.java:161)
  at android.os.Looper.loop(Looper.java:288)
  at android.app.ActivityThread.main(ActivityThread.java:7918)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
                              
--- End of managed Java.Lang.IllegalStateException stack trace ---
java.lang.IllegalStateException: FragmentManager has been destroyed
  at androidx.fragment.app.FragmentManager.enqueueAction(FragmentManager.java:1644)
  at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:341)
  at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:306)
  at crc64338477404e88479c.InnerGestureListener.n_onSingleTapUp(Native Method)
  at crc64338477404e88479c.InnerGestureListener.onSingleTapUp(InnerGestureListener.java:80)
  at android.view.GestureDetector.onTouchEvent(GestureDetector.java:752)
  at mono.android.view.View_OnTouchListenerImplementor.n_onTouch(Native Method)
  at mono.android.view.View_OnTouchListenerImplementor.onTouch(View_OnTouchListenerImplementor.java:31)
  at android.view.View.dispatchTouchEvent(View.java:15046)
  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3115)
  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2788)
  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
  at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:500)
  at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1912)
  at android.app.Activity.dispatchTouchEvent(Activity.java:4299)
  at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:70)
  at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:458)
  at android.view.View.dispatchPointerEvent(View.java:15309)
  at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6778)
  at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6578)
  at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6034)
  at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6091)
  at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6057)
  at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6222)
  at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6065)
  at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6279)
  at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6038)
  at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6091)
  at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6057)
  at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6065)
  at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6038)
  at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9206)
  at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9157)
  at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9126)
  at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9329)
  at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:267)
  at android.os.MessageQueue.nativePollOnce(Native Method)
  at android.os.MessageQueue.next(MessageQueue.java:335)
  at android.os.Looper.loopOnce(Looper.java:161)
  at android.os.Looper.loop(Looper.java:288)
  at android.app.ActivityThread.main(ActivityThread.java:7918)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by AnnYang01** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 6.0 in Android 13.0-API33. This issue didn't repro on .NET 8.0 with below Project:
[MauiApp10.zip](https://github.com/dotnet/maui/files/12248664/MauiApp10.zip)
Screenshot: TabbedPage still appears if the UI is kill with a foreground service started
![TabbedPage](https://github.com/dotnet/maui/assets/131441429/419d3d24-9dbf-4a00-b0a1-de5f96034f3f)

**Comment by pierre-galaup** [comment]
Hello @AnnYang01,

In the repo you linked to (or the video), you don't have a Foreground Service with permanent notification. (cf my repro repo: [https://github.com/pierre-galaup/repro-maui-tabbedpage-service/blob/master/MauiApp1/Platforms/Android/NotificationBarService.cs](https://github.com/pierre-galaup/repro-maui-tabbedpage-service/blob/master/MauiApp1/Platforms/Android/NotificationBarService.cs))

The bug I have only happens if the Foreground Service is running.

**Comment by PureWeen** [comment]
Can you test with the latest nightly build? 
https://github.com/dotnet/maui/wiki/Nightly-Builds

**Comment by PaulNiemiec** [comment]
In the sample app I noticed that top bar is missing after launching app from sticky notification
