### ISSUE TITLE
Blank .NET MAUI App crashes on iOS 12 device with .NET 8 preview 6

### ISSUE THREAD

**Issue by jmezach** [dotnet/maui#16097]
### Description

After the release of preview 6 we wanted to check if our app would work on iOS 12, which didn't work in preview 5 due to #15673. Although that issue appears to be fixed, we now have a new issue where the same project crashes at startup with the following exception:

```
Unhandled Exception:
ObjCRuntime.ObjCException: Objective-C exception thrown.  Name: NSInvalidArgumentException Reason: -[CALayer setCornerCurve:]: unrecognized selector sent to instance 0x281a82960
Native stack trace:
	0   CoreFoundation                      0x0000000185efb198 <redacted> + 252
	1   libobjc.A.dylib                     0x00000001850d39f8 objc_exception_throw + 56
	2   CoreFoundation                      0x0000000185e179bc <redacted> + 0
	3   CoreFoundation                      0x0000000185f009c8 <redacted> + 1408
	4   CoreFoundation                      0x0000000185f0265c _CF_forwarding_prep_0 + 92
	5   MauiApp1                            0x000000010106a0c4 xamarin_get_original_working_directory_path + 8648
	6   MauiApp1                            0x000000010136a230 AppleCryptoNative_X509ImportCollection + 2766616
	7   MauiApp1                            0x0000000101368ebc AppleCryptoNative_X509ImportCollection + 2761636
	8   MauiApp1                            0x000000010135e1f0 AppleCryptoNative_X509ImportCollection + 2717400
	9   MauiApp1                            0x000000010135bf30 AppleCryptoNative_X509ImportCollection + 2708504
	10  MauiApp1                            0x000000010132d144 AppleCryptoNative_X509ImportCollection + 2516524
	11  MauiApp1                            0x00000001012d8c3c AppleCryptoNative_X509ImportCollection + 2171172
	12  MauiApp1                            0x00000001012db96c AppleCryptoNative_X509ImportCollection + 2182740
	13  MauiApp1                            0x000000010139cd94 AppleCryptoNative_X509ImportCollection + 2974332
	14  MauiApp1                            0x00000001013c74a4 AppleCryptoNative_X509ImportCollection + 3148172
	15  UIKitCore                           0x00000001b232a224 <redacted> + 1012
	16  UIKitCore                           0x00000001b229a664 <redacted> + 76
	17  UIKitCore                           0x00000001b229a96c <redacted> + 172
	18  UIKitCore                           0x00000001b229b8a8 <redacted> + 1112
	19  UIKitCore                           0x00000001b229cb3c <redacted> + 164
	20  UIKitCore                           0x00000001b227fd4c <redacted> + 224
	21  UIKitCore                           0x00000001b2d6b170 <redacted> + 1292
	22  QuartzCore                          0x000000018a439c60 <redacted> + 184
	23  QuartzCore                          0x000000018a43ec08 <redacted> + 332
	24  QuartzCore                          0x000000018a3a13e4 <redacted> + 348
	25  QuartzCore                          0x000000018a3cf620 <redacted> + 640
	26  UIKitCore                           0x00000001b28ec85c <redacted> + 124
	27  CoreFoundation                      0x0000000185e8cd6c <redacted> + 20
	28  CoreFoundation                      0x0000000185e8c670 <redacted> + 272
	29  CoreFoundation                      0x0000000185e876d4 <redacted> + 1024
	30  CoreFoundation                      0x0000000185e86fb4 CFRunLoopRunSpecific + 436
	31  GraphicsServices                    0x000000018808979c GSEventRunModal + 104
	32  UIKitCore                           0x00000001b28d3c38 UIApplicationMain + 212
	33  MauiApp1                            0x000000010103c5f4 xamarin_UIApplicationMain + 60
	34  MauiApp1                            0x000000010136a2a4 AppleCryptoNative_X509ImportCollection + 2766732
	35  MauiApp1                            0x0000000101368ebc AppleCryptoNative_X509ImportCollection + 2761636
	36  MauiApp1                            0x000000010135e1f0 AppleCryptoNative_X509ImportCollection + 2717400
	37  MauiApp1                            0x000000010135bf30 AppleCryptoNative_X509ImportCollection + 2708504
	38  MauiApp1                            0x000000010132d144 AppleCryptoNative_X509ImportCollection + 2516524
	39  MauiApp1                            0x00000001012d7e4c AppleCryptoNative_X509ImportCollection + 2167604
	40  MauiApp1                            0x00000001012decd4 AppleCryptoNative_X509ImportCollection + 2195900
	41  MauiApp1                            0x0000000101332424 AppleCryptoNative_X509ImportCollection + 2537740
	42  MauiApp1                            0x000000010106900c xamarin_get_original_working_directory_path + 4368
	43  MauiApp1                            0x0000000101397568 AppleCryptoNative_X509ImportCollection + 2951760
	44  libdyld.dylib                       0x000000018594a8e0 <redacted> + 4

   at ObjCRuntime.Runtime.ThrowException(IntPtr gchandle)
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName)
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)
   at MauiApp1.Program.Main(String[] args) in /Users/jmezach/Code/demos/MauiApp1/Platforms/iOS/Program.cs:line 13
```

### Steps to Reproduce

1. Run dotnet new maui -o MauiApp1
2. Run dotnet build -t:Run -f net8.0-ios -p:RuntimeIdentifier=ios-arm64 -p:_DeviceName=<device-id-of-ios-device-with-12.5.5>
3. App crashes with the exception shown above

### Link to public reproduction project repository

https://github.com/jmezach/MauiApp8CrashRepro

### Version with bug

Unknown/Other

### Last version that worked well

7.0.86

### Affected platforms

iOS

### Affected platform versions

12.5.7

**Comment by jmezach** [comment]
This issue could be caused by the fact that in the `ContentView` constructor on iOS an API is used that is only available on iOS 13 or higher. Specifically [this line of code](https://github.com/dotnet/maui/blob/e0431b74a61377da21e54fc8ab264678866787a6/src/Core/src/Platform/iOS/ContentView.cs#L17C24-L17C48) in the constructor of `ContentView` uses [this API](https://developer.apple.com/documentation/quartzcore/calayercornercurve/3152600-continuous) which according to that doc is only available on iOS 13+.

**Comment by jfversluis** [comment]
Introduced by #10964 @jsuarezruiz can we add a iOS version check?

**Comment by jsuarezruiz** [comment]
> Introduced by #10964 @jsuarezruiz can we add a iOS version check?

Right! https://github.com/dotnet/maui/pull/16101
