### ISSUE TITLE
.NET 8.0 Preview 5/6 - Unable to edit project properties

### ISSUE THREAD

**Issue by Stedy59** [dotnet/maui#16092]
### Description

Attempting to view project properties produces an error.

### Steps to Reproduce

1. Create a new .net Maui project
2. Right click on the project in the Solution Explorer
3. Select "Properties"

### Link to public reproduction project repository

n/a - just create a new project

### Version with bug

8.0.0-preview.5.8529

### Last version that worked well

7.0.86

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

Default platform versions provided by new project template

### Did you find any workaround?

no

### Relevant log output

```shell
`=====================
7/11/2023 6:42:29 PM
Recoverable
System.ArgumentException: Expected 4 values for property AndroidRule::AndroidPackageFormat, but got 2.
Parameter name: values
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.PropertyPages.Designer.Property.Update(ImmutableArray`1 values)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.PropertyPages.Designer.Property..ctor(PropertyMetadata metadata, ImmutableArray`1 values, PropertyContext context, ImmutableHashSet`1 varyByDimensions)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.PropertyPages.Designer.PropertyContextFactoryBase.ToProperty(IUIPropertySnapshot property, Page page, Category category, Int32 order, PropertyContext propertyContext, IPropertyEditorRegistry propertyEditorRegistry)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.PropertyPages.Designer.ProjectPropertyDataAccess.Observer.<HandleDataAsync>g__CreateProperties|14_5(<>c__DisplayClass14_0& )
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.PropertyPages.Designer.ProjectPropertyDataAccess.Observer.<HandleDataAsync>g__ProcessInitialData|14_1(<>c__DisplayClass14_0& )
===================`
```

**Comment by Stedy59** [comment]
Reported to Visual Studio team...

[https://developercommunity.visualstudio.com/t/Unable-to-edit-project-properties/10413944](https://developercommunity.visualstudio.com/t/Unable-to-edit-project-properties/10413944)
