### ISSUE TITLE
Android "No compatible code running on the thread" and crash after hit continue

### ISSUE THREAD

**Issue by Rabosa616** [dotnet/maui#16189]
### Description

After I created a new project with Dotnet Maui 8 preview 6 I get the following error on Android when I try to debug the event ItemSelected on a ListView control
![image](https://github.com/dotnet/maui/assets/12774781/034ca461-4265-4a84-8a2e-80e3ee3af008)

![image](https://github.com/dotnet/maui/assets/12774781/c5bdde18-9e69-4d13-bb80-92c27d3b6502)

Visual Studio Version:
![image](https://github.com/dotnet/maui/assets/12774781/6ba1c310-7593-4ec2-9c5a-c57337359a35)
![image](https://github.com/dotnet/maui/assets/12774781/04c80d60-4c6d-400a-bd24-82a425ed329d)
![image](https://github.com/dotnet/maui/assets/12774781/8b3cbb04-464b-4645-af1e-fa47e8585968)
![image](https://github.com/dotnet/maui/assets/12774781/0ba5b5df-7729-464c-bfe3-5b3223e34afe)

### Steps to Reproduce

1. Create a new Dotnet Maui application with donet 8 preview 6
2. Add a listview into the "MainPage.xaml" like follows:
![image](https://github.com/dotnet/maui/assets/12774781/0248faa2-b880-4107-971e-525116d6d6ad)
3. Create the event ListView_ItemSelected like follows and add a break point
![image](https://github.com/dotnet/maui/assets/12774781/c5bdde18-9e69-4d13-bb80-92c27d3b6502)
4. Hit F5 to run the app in the android emulator
5. Click on one element of the item list
![image](https://github.com/dotnet/maui/assets/12774781/aeac880e-040c-425d-b6e9-afcb3f9ade43)
Then an error shown in Visual Studio:
![image](https://github.com/dotnet/maui/assets/12774781/347fe47b-c044-4d03-a671-15f8f10b3b40)

### Link to public reproduction project repository

https://github.com/Rabosa616/MauiAndroidBug

### Version with bug

Unknown/Other

### Last version that worked well

7.0.49

### Affected platforms

Android

### Affected platform versions

Android 12.1 , Android 13

### Relevant log output

```shell
monodroid.log:
MonoDroidLog: Information: 0: [I:]:                     Found Xamarin.Android 13.2.0.13
MonoDroidLog: Information: 0: [I:sdk]:                  Runtime path: C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Xamarin\Android
MonoDroidLog: Information: 0: [I:sdk]:                  Framework path: C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\MonoAndroid\v1.0
MonoDroidLog: Information: 0: [I:]:                     Looking for Android NDK...
MonoDroidLog: Information: 0: [I:]:                     Looking for Android SDK...
MonoDroidLog: Information: 0: [I:]:                     Tracking android devices started
MonoDroidLog: Warning: 0: [W:]:                     Adb connection refused
MonoDroidLog: Information: 0: [I:]:                     Starting Adb server (adb start-server)
MonoDroidLog: Information: 0: [I:]:                     Adb start-server operation completed
MonoDroidLog: Information: 0: [I:]:                     Got new device list from adb with 0 devices
MonoDroidLog: Information: 0: [I:]:                     Looking for Android SDK...
MonoDroidLog: Information: 0: [I:]:                     Got new device list from adb with 1 devices
MonoDroidLog: Information: 0: [I:]:                     Got new device list from adb with 1 devices
MonoDroidLog: Error: 0: [E:RunShellCommand]:      emulator-5554 logcat -v time failed: Mono.AndroidTools.AdbException: Unable to read data from the transport connection: A blocking operation was interrupted by a call to WSACancelBlockingCall. ---> System.IO.IOException: Unable to read data from the transport connection: A blocking operation was interrupted by a call to WSACancelBlockingCall. ---> System.Net.Sockets.SocketException: A blocking operation was interrupted by a call to WSACancelBlockingCall
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.IO.StreamReader.ReadBuffer()
   at System.IO.StreamReader.ReadLine()
   at Mono.AndroidTools.Adb.AdbClient.ReadLineWhile(Action`1 output, Func`1 predicate) in D:\a\_work\1\s\External\androidtools\Mono.AndroidTools\Adb\AdbClient.cs:line 585
   --- End of inner exception stack trace ---
   at Mono.AndroidTools.Adb.AdbClient.ReadLineWhile(Action`1 output, Func`1 predicate) in D:\a\_work\1\s\External\androidtools\Mono.AndroidTools\Adb\AdbClient.cs:line 592
   at Mono.AndroidTools.AndroidDevice.<>c__DisplayClass119_0.<RunShellCommandAsync>b__0() in D:\a\_work\1\s\External\androidtools\Mono.AndroidTools\AndroidDevice.cs:line 1021
MonoDroidLog: Error: 0: [E:RunShellCommand]:      emulator-5554 logcat -v time "dalvikvm:S" "ActivityThread:S" "mkestner:S" "MonoDroid-Debugger:S" failed: Mono.AndroidTools.AdbException: Unable to read data from the transport connection: A blocking operation was interrupted by a call to WSACancelBlockingCall. ---> System.IO.IOException: Unable to read data from the transport connection: A blocking operation was interrupted by a call to WSACancelBlockingCall. ---> System.Net.Sockets.SocketException: A blocking operation was interrupted by a call to WSACancelBlockingCall
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.IO.StreamReader.ReadBuffer()
   at System.IO.StreamReader.ReadLine()
   at Mono.AndroidTools.Adb.AdbClient.ReadLineWhile(Action`1 output, Func`1 predicate) in D:\a\_work\1\s\External\androidtools\Mono.AndroidTools\Adb\AdbClient.cs:line 585
   --- End of inner exception stack trace ---
   at Mono.AndroidTools.Adb.AdbClient.ReadLineWhile(Action`1 output, Func`1 predicate) in D:\a\_work\1\s\External\androidtools\Mono.AndroidTools\Adb\AdbClient.cs:line 592
   at Mono.AndroidTools.AndroidDevice.<>c__DisplayClass119_0.<RunShellCommandAsync>b__0() in D:\a\_work\1\s\External\androidtools\Mono.AndroidTools\AndroidDevice.cs:line 1021
```

**Comment by moljac** [comment]
I cannot repro. No crashes at all.

Tried net8.0 (previews 4, 5 and 6)

Adding several logcats and bugreport zip archives.

[bugreport-sdk_gphone64_x86_64-SE1A.220826.006.A1-2023-07-18-09-45-03.zip](https://github.com/dotnet/maui/files/12077627/bugreport-sdk_gphone64_x86_64-SE1A.220826.006.A1-2023-07-18-09-45-03.zip)
[log_2023-07-18T09-44-52.txt](https://github.com/dotnet/maui/files/12077628/log_2023-07-18T09-44-52.txt)
[log_2023-07-17T13-47-54.txt](https://github.com/dotnet/maui/files/12077629/log_2023-07-17T13-47-54.txt)
[bugreport-sdk_gphone_x86_64-TE1A.220922.025-2023-07-17-13-42-42.zip](https://github.com/dotnet/maui/files/12077630/bugreport-sdk_gphone_x86_64-TE1A.220922.025-2023-07-17-13-42-42.zip)
[log_2023-07-17T13-42-41.txt](https://github.com/dotnet/maui/files/12077631/log_2023-07-17T13-42-41.txt)

**Comment by moljac** [comment]
@Rabosa616 

Please, can you try:

1. restart adb
   ```
    adb kill-server
    adb start-server
    adb devices   
   ```
2. turning off firewall and/or antivirus software
?

**Comment by Rabosa616** [comment]
Hi @moljac 
There is no antivirus on that machine, and the firewall is turned off
Hereby I've attached a video showing the whole process:
https://we.tl/t-IGA4jZEaWe

I did your steps, I've cleaned all temporals, also I've cleaned all bin and obj folders and rebuild and removed the app from the emulator. I've also created a brand new emulator and always with the same results

**Comment by moljac** [comment]
Citation:

> That is probably a debugger issue not Fast deployment, so that would mean the IDE team needs to take a look. 

> Since they are already debugging, Fast deployment is already over. The IDE does use the AdbClient as well for various operations.

**Comment by Rabosa616** [comment]
@moljac  from where is this Citation?
Any issue in the VS IDE to follow?
