### ISSUE TITLE
Exception "this element is not in a namescope" when using Setter with TargetName for VisualState = Normal

### ISSUE THREAD

**Issue by tgudelj** [dotnet/maui#16208]
### Description

When using Setter with TargetName inside VisualStateManager a runtime exception is thrown:
```
System.InvalidOperationException' occurred in Microsoft.Maui.Controls.Xaml.dll but was not handled in user code
this element is not in a namescope
```
After a bit of trial and error it seems that error manifests only when using setter inside VisualStateGroup with name "Normal".

What am I doing wrong?

### Steps to Reproduce

1) Create new MAUI app
2) add a simple layout to the MainPage

```xaml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="TestMauiCustomCtl.MainPage">

    <HorizontalStackLayout x:Name="ItemHorizontalStack" HorizontalOptions="Center" VerticalOptions="Center" Padding="20">
          <Label  x:Name="ItemLabel"
                      Text="This is the label inside"
                      FontSize="18" />
          <VisualStateManager.VisualStateGroups>
              <VisualStateGroupList>
                  <VisualStateGroup x:Name="CommonStates">
                      <VisualState x:Name="Normal">
                          <VisualState.Setters>
                              <Setter Property="BackgroundColor" Value="Red" />
                              <!--<Setter TargetName="ItemLabel" Property="Label.BackgroundColor" Value="Green" />-->
                          </VisualState.Setters>
                      </VisualState>
  
                      <VisualState x:Name="PointerOver">
                          <VisualState.Setters>
                              <Setter Property="BackgroundColor" Value="Yellow" />
                              <Setter TargetName="ItemLabel" Property="Label.BackgroundColor" Value="Black" />
                          </VisualState.Setters>
                      </VisualState>
                  </VisualStateGroup>
              </VisualStateGroupList>
          </VisualStateManager.VisualStateGroups>
    </HorizontalStackLayout>

</ContentPage>
```
3) Run the app, no exceptions noted
4) Uncomment the setter
5) Run the app and Exception is thrown

### Link to public reproduction project repository

https://github.com/tgudelj/mauibugrepro

### Version with bug

7.0.86

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

net7.0-windows10.0.19041.0

### Did you find any workaround?

Obvious one is do not use setters with TargetName inside 
<VisualState x:Name="Normal">

### Relevant log output

```shell
Exception thrown: 'System.InvalidOperationException' in Microsoft.Maui.Controls.Xaml.dll
An exception of type 'System.InvalidOperationException' occurred in Microsoft.Maui.Controls.Xaml.dll but was not handled in user code
this element is not in a namescope
```

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.8.0 Preview 1.0. Repro on Windows 11(8.0.100-preview.6.23330.14), not repro on Android 13.0-API33 and iOS 16.4 with below Project:

[TestMauiCustomCtl.zip](https://github.com/dotnet/maui/files/12299234/TestMauiCustomCtl.zip)

**Comment by tgudelj** [comment]
Update: Visual Studio Community 17.7.3 bug manifests on Windows and Android when build is set to Release

**Comment by nnn149** [comment]
``` xaml
   <DataTemplate x:Key="itemsTemplate" x:DataType="vo:QualityInspectionVo">
  
       <Grid>
           <Border
               x:Name="border"
               Margin="5"
               Padding="5"
               Stroke="Black">
               <Border.StrokeShape>
                   <RoundRectangle CornerRadius="5" />
               </Border.StrokeShape>
               <Grid>
                   <!--<Label FontAttributes="Bold" Text="{Binding Scantime, StringFormat='Time:{0:HH:mm}'}" />-->
               </Grid>
           </Border>
       </Grid>
   </DataTemplate>


      <Style TargetType="Grid">
          <Setter Property="VisualStateManager.VisualStateGroups">
              <VisualStateGroupList>
                  <VisualStateGroup x:Name="CommonStates">
                      <VisualState x:Name="Normal">
                          <VisualState.Setters>
                              <Setter TargetName="border" Property="Border.BackgroundColor" Value="White" />
                          </VisualState.Setters>
                      </VisualState>
                      <VisualState x:Name="Selected">
                          <VisualState.Setters>
                              <Setter TargetName="border" Property="Border.BackgroundColor" Value="LightSkyBlue" />
                          </VisualState.Setters>
                      </VisualState>
                  </VisualStateGroup>
              </VisualStateGroupList>
          </Setter>
      </Style>

       <CollectionView
           EmptyView="No items to display"
           ItemTemplate="{StaticResource itemsTemplate}"
           SelectionMode="Single" />
````


I tested my program on Android and it crashed (in release mode), but it worked fine in debug mode. If I delete `<VisualState x:Name="Normal">`, it won't crash. The crash log is `4619  4619 E AndroidRuntime: android.runtime.JavaProxyThrowable: Microsoft.Maui.Controls.Xaml.XamlParseException: Cannot resolve 'border' as Setter Target for 'Microsoft.Maui.Controls.Grid'.`

**Comment by XamlTest** [comment]
@nnn149 Verified on Android Release mode, application crashes, but no exception or error can be caught.

**Comment by tgudelj** [comment]
Issue seems to still be present in .net 8

**Comment by vitalbit** [comment]
Also faced with this issue in .NET 8. It throws Exception for Windows application, but works fine on Android for me.

**Comment by mavispuford** [comment]
Same thing happens to us in Android and iOS.

```
Installed Workload Id      Manifest Version       Installation Source
------------------------------------------------------------------------------------
android                    34.0.52/8.0.100        VS 17.9.34723.18, VS 17.9.34321.82
maui-windows               8.0.7/8.0.100          VS 17.9.34723.18, VS 17.9.34321.82
maccatalyst                17.2.8004/8.0.100      VS 17.9.34723.18, VS 17.9.34321.82
ios                        17.2.8004/8.0.100      VS 17.9.34723.18, VS 17.9.34321.82
```

**Comment by Shujee** [comment]
Facing this on Windows build in debug mode. I'm using VS2022 (17.9.6) with .NET 8. Is there a workaround for it?

**Comment by gerdus** [comment]
Here is the stack trace I get. 
(Android, Release Mode only)
```
System.InvalidOperationException: this element is not in a namescope
   at Microsoft.Maui.Controls.Element.FindByName(String name)
   at Microsoft.Maui.Controls.Setter.UnApply(BindableObject target, SetterSpecificity specificity)
   at Microsoft.Maui.Controls.TriggerBase.OnConditionChanged(BindableObject bindable, Boolean oldValue, Boolean newValue)
   at Microsoft.Maui.Controls.PropertyCondition.OnStatePropertyChanged(BindableObject bindable, Object oldValue, Object newValue)
   at Microsoft.Maui.Controls.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, SetterSpecificity specificity, Boolean silent)
   at Microsoft.Maui.Controls.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes, SetterSpecificity specificity)
   at Microsoft.Maui.Controls.BindableObject.SetValue(BindableProperty property, Object value)
   at Microsoft.Maui.Controls.PropertyCondition.OnAttachedObjectPropertyChanged(Object sender, PropertyChangedEventArgs e)
   at Microsoft.Maui.Controls.BindableObject.OnPropertyChanged(String propertyName)
   at Microsoft.Maui.Controls.Element.OnPropertyChanged(String propertyName)
   at Microsoft.Maui.Controls.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, SetterSpecificity specificity, Boolean silent)
   at Microsoft.Maui.Controls.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes, SetterSpecificity specificity)
   at Microsoft.Maui.Controls.Internals.TypedBinding`2[[SIAppSrc.Pages.Quote.QuoteSelectCreatePage, SIAppSrc, Version=1.8928.32.0, Culture=neutral, PublicKeyToken=null],[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ApplyCore(Object sourceObject, BindableObject target, BindableProperty property, Boolean fromTarget, SetterSpecificity specificity)
   at Microsoft.Maui.Controls.Internals.TypedBinding`2[[SIAppSrc.Pages.Quote.QuoteSelectCreatePage, SIAppSrc, Version=1.8928.32.0, Culture=neutral, PublicKeyToken=null],[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Apply(Object context, BindableObject bindObj, BindableProperty targetProperty, Boolean fromBindingContextChanged, SetterSpecificity specificity)
   at Microsoft.Maui.Controls.BindableObject.ApplyBindings(Boolean skipBindingContext, Boolean fromBindingContextChanged)
   at Microsoft.Maui.Controls.BindableObject.SetInheritedBindingContext(BindableObject bindable, Object value)
   at Microsoft.Maui.Controls.Element.SetChildInheritedBindingContext(Element child, Object context)
   at Microsoft.Maui.Controls.Element.<OnBindingContextChanged>b__93_0(BindableObject child, Object bc)
   at Microsoft.Maui.Controls.BindableObjectExtensions.PropagateBindingContext[Element](BindableObject self, IEnumerable`1 children, Action`2 setChildBindingContext)
   at Microsoft.Maui.Controls.Element.OnBindingContextChanged()
   at Microsoft.Maui.Controls.VisualElement.OnBindingContextChanged()
   at Microsoft.Maui.Controls.View.OnBindingContextChanged()
   at Microsoft.Maui.Controls.BindableObject.SetInheritedBindingContext(BindableObject bindable, Object value)
   at Microsoft.Maui.Controls.Element.SetChildInheritedBindingContext(Element child, Object context)
   at Microsoft.Maui.Controls.Element.<OnBindingContextChanged>b__93_0(BindableObject child, Object bc)
   at Microsoft.Maui.Controls.BindableObjectExtensions.PropagateBindingContext[Element](BindableObject self, IEnumerable`1 children, Action`2 setChildBindingContext)
   at Microsoft.Maui.Controls.Element.OnBindingContextChanged()
   at Microsoft.Maui.Controls.VisualElement.OnBindingContextChanged()
   at Microsoft.Maui.Controls.View.OnBindingContextChanged()
   at Microsoft.Maui.Controls.BindableObject.SetInheritedBindingContext(BindableObject bindable, Object value)
   at Microsoft.Maui.Controls.Element.SetParent(Element value)
   at Microsoft.Maui.Controls.Element.OnChildRemoved(Element child, Int32 oldLogicalIndex)
   at Microsoft.Maui.Controls.VisualElement.OnChildRemoved(Element child, Int32 oldLogicalIndex)
   at Microsoft.Maui.Controls.Element.RemoveLogicalChild(Element element, Int32 index)
   at Microsoft.Maui.Controls.Element.RemoveLogicalChild(Element element)
   at Microsoft.Maui.Controls.Layout.Clear()
   at CommunityToolkit.Maui.Layouts.StateContainerController.SwitchToState(String state)
   at CommunityToolkit.Maui.Layouts.StateContainer.ChangeState(BindableObject bindable, String state)
   at CommunityToolkit.Maui.Layouts.StateContainer.OnCurrentStateChanging(BindableObject bindable, Object oldValue, Object newValue)
   at Microsoft.Maui.Controls.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, SetterSpecificity specificity, Boolean silent)
   at Microsoft.Maui.Controls.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes, SetterSpecificity specificity)
   at Microsoft.Maui.Controls.Internals.TypedBinding`2[[SIAppSrc.Pages.Quote.QuoteSelectCreatePage, SIAppSrc, Version=1.8928.32.0, Culture=neutral, PublicKeyToken=null],[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ApplyCore(Object sourceObject, BindableObject target, BindableProperty property, Boolean fromTarget, SetterSpecificity specificity)
   at Microsoft.Maui.Controls.Internals.TypedBinding`2[[SIAppSrc.Pages.Quote.QuoteSelectCreatePage, SIAppSrc, Version=1.8928.32.0, Culture=neutral, PublicKeyToken=null],[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Apply(Boolean fromTarget)
   at Microsoft.Maui.Controls.Internals.TypedBinding`2.PropertyChangedProxy[[SIAppSrc.Pages.Quote.QuoteSelectCreatePage, SIAppSrc, Version=1.8928.32.0, Culture=neutral, PublicKeyToken=null],[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<OnPropertyChanged>b__16_0()
   at Microsoft.Maui.Controls.DispatcherExtensions.DispatchIfRequired(IDispatcher dispatcher, Action action)
   at Microsoft.Maui.Controls.Internals.TypedBinding`2.PropertyChangedProxy[[SIAppSrc.Pages.Quote.QuoteSelectCreatePage, SIAppSrc, Version=1.8928.32.0, Culture=neutral, PublicKeyToken=null],[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].OnPropertyChanged(Object sender, PropertyChangedEventArgs e)
   at Microsoft.Maui.Controls.BindingExpression.WeakPropertyChangedProxy.OnPropertyChanged(Object sender, PropertyChangedEventArgs e)
   at Microsoft.Maui.Controls.BindableObject.OnPropertyChanged(String propertyName)
   at Microsoft.Maui.Controls.Element.OnPropertyChanged(String propertyName)
   at SIAppSrc.Pages.Quote.QuoteSelectCreatePage.set_State(String value)
   at SIAppSrc.Pages.Quote.QuoteSelectCreatePage.CustomerNext_Clicked(Object sender, EventArgs e)
```

**Comment by malsabi** [comment]
I'm having this issue as well when using TargetName in Release mode it crashes in Windows.

**Comment by hansmbakker** [comment]
I'm getting it when doing a XAML Hot Reload on save ( = full page reload) during debugging on Android. At runtime or compile time there is no problem.

**Comment by nixkuroi** [comment]
This is also happening when trying to do FindByName for children under a control that has a behavior assigned to it.  It's like the element that you get in the binding inside the behavior is completely detached from both parents and children.

**Comment by StephaneDelcroix** [comment]
> There is this PR: #22854. Perhaps @StephaneDelcroix can say if that PR can fix this issue as well.

I'll write a unit test, that's the only valid metric

**Comment by StephaneDelcroix** [comment]
#22854 does fixes this. 

I still don't get why there are 2 setters for the same property in the VSM.

While waiting for this to be merged, the recommended workaround on the other issue is to move the VSM at a higher level
