### ISSUE TITLE
SearchHandler crashes on ItemSource change in iOS

### ISSUE THREAD

**Issue by edgiardina** [dotnet/maui#16297]
### Description

When I create a SearchHandler to use in iOS, it crashes when I update the ItemsSource when the query changes

![image](https://github.com/dotnet/maui/assets/3627193/28336446-bb84-4b46-9b5b-c169249a27d9)

### Steps to Reproduce

1. Create a File -> New Maui Project
2. Insert a SearchHandler like in the sample project
3. Load Sample Data
4. Start typing. In the example sample, it should reach out to the json file to load data after 3 characters. It will fail. I've seen this happen with real API calls as well. API calls and JSON loading works in Android.
5. Witness a NullRefException (log shows stacktrace)

### Link to public reproduction project repository

https://github.com/edgiardina/MauiBug_SearchHandler_iOSCrash.App

### Version with bug

7.0.86

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

Tested on iOS 16.4 Simulator(s)

### Did you find any workaround?

No. Removing the template doesn't work either b(trying to use DisplayMemberName)

### Relevant log output

```shell
Object reference not set to an instance of an object.
   at Microsoft.Maui.Controls.ViewExtensions.GetParentsPath(Element self)+MoveNext()
   at Microsoft.Maui.Controls.ViewExtensions.FindMauiContext(Element element, Boolean fallbackToAppMauiContext)
   at Microsoft.Maui.Controls.Platform.Compatibility.UIContainerCell..ctor(String cellId, View view, Shell shell, Object context)
   at Microsoft.Maui.Controls.Platform.Compatibility.UIContainerCell..ctor(String cellId, View view)
   at Microsoft.Maui.Controls.Platform.Compatibility.ShellSearchResultsRenderer.GetCell(UITableView tableView, NSIndexPath indexPath)
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName)
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)
   at MauiBug_SearchHandler_iOSCrash.Program.Main(String[] args) in C:\Users\ed_gi\source\repos\MauiBug_SearchHandler_iOSCrash\MauiBug_SearchHandler_iOSCrash\Platforms\iOS\Program.cs:line 13
```

**Comment by jsuarezruiz** [comment]
Seems the same as https://github.com/dotnet/maui/issues/14442 and will be fixed by https://github.com/dotnet/maui/pull/14634

**Comment by mattleibow** [comment]
Duplicate of https://github.com/dotnet/maui/issues/14442

**Comment by edgiardina** [comment]
This has seen no movement. It's high priority yet has not been verified or triaged.

**Comment by HarishwaranVijayakumar** [comment]
This issue is not reproduced in the latest MAUI version (10.0.60). I have attached a video for reference

https://github.com/user-attachments/assets/28cc0f15-420f-4e87-9e94-339d0cb1b212

**Comment by jfversluis** [comment]
Stale by now, and no response to our request to use the latest version. I'm going to be optimistic and assume this is fixed in recent versions. Please let us know if this is something that still impacts you.

**Comment by edgiardina** [comment]
Confirmed fixed in .NET 10 / MAUI 10.0.0. 👍

I took the original repro (which targeted `net7.0-ios`), retargeted it to `net10.0-ios`, and ran it against the current MAUI 10.0.0 workload on Xcode 26.1. Typing into the `SearchHandler` now populates `ItemsSource` and renders the results template without crashing — the original `ShellSearchResultsRenderer.GetCell` → `UIContainerCell..ctor` → `FindMauiContext` NRE no longer occurs.

Tested on:
- iOS 17.2 (iPhone 15 Pro simulator)
- iOS 26.1 (iPhone 17 Pro simulator)

I also stress-tested the ItemsSource-change path that originally triggered the crash: repeatedly changing the query (list → null → list), scrolling the results, and selecting a result — all stable.

Good to close from my side. Thanks!
