### ISSUE TITLE
[regression/8.0.0-preview.6.8686] [WinUI] CollectionView throws an exception after adding a second item

### ISSUE THREAD

**Issue by marchev-prgs** [dotnet/maui#16320]
### Description

(repro project is in link)

I have a CollectionView in a Grid with row definition auto. 

    <Grid>
        <Grid RowDefinitions="Auto, *">
            <CollectionView x:Name="cv1" BackgroundColor="LightSalmon">
                <CollectionView.ItemsLayout>
                    <LinearItemsLayout Orientation="Horizontal" />
                </CollectionView.ItemsLayout>
            </CollectionView>
            <Label Text="A Label under the CollectionView" Grid.Row="1" />
        </Grid>
        <Button Text="add" Clicked="ButtonAdd_Clicked" HorizontalOptions="End" VerticalOptions="Start" />
    </Grid>

The CollectionView is initially displayed properly, but after I add a second item into it, via click of a button - an exception is thrown:

message:
Exception = {"Value does not fall within the expected range."}

stack trace:
at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Microsoft.UI.Xaml.IFrameworkElementOverridesMethods.ArrangeOverride(IObjectReference _obj, Size finalSize)
   at Microsoft.UI.Xaml.FrameworkElement.ArrangeOverride(Size finalSize)
   at Microsoft.Maui.Controls.Platform.FormsGridView.ArrangeOverride(Size finalSize)
   at Microsoft.UI.Xaml.FrameworkElement.Microsoft.UI.Xaml.IFrameworkElementOverrides.ArrangeOverride(Size finalSize)
   at ABI.Microsoft.UI.Xaml.IFrameworkElementOverrides.Do_Abi_ArrangeOverride_1(IntPtr thisPtr, Size finalSize, Size* result)
--- End of stack trace from previous location ---
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Microsoft.UI.Xaml.IUIElementMethods.Arrange(IObjectReference _obj, Rect finalRect)
   at Microsoft.UI.Xaml.UIElement.Arrange(Rect finalRect)
   at Microsoft.Maui.ViewHandlerExtensions.PlatformArrangeHandler(IViewHandler viewHandler, Rect rect)
   at Microsoft.Maui.Handlers.ViewHandler`2.PlatformArrange(Rect rect)
   at Microsoft.Maui.Controls.VisualElement.ArrangeOverride(Rect bounds)
   at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IView.Arrange(Rect bounds)
   at Microsoft.Maui.Layouts.GridLayoutManager.ArrangeChildren(Rect bounds)
   at Microsoft.Maui.Controls.Layout.CrossPlatformArrange(Rect bounds)
   at Microsoft.Maui.Platform.MauiPanel.CrossPlatformArrange(Rect bounds)
   at Microsoft.Maui.Platform.MauiPanel.ArrangeOverride(Size finalSize)
   at Microsoft.Maui.Platform.LayoutPanel.ArrangeOverride(Size finalSize)
   at Microsoft.UI.Xaml.FrameworkElement.Microsoft.UI.Xaml.IFrameworkElementOverrides.ArrangeOverride(Size finalSize)
   at ABI.Microsoft.UI.Xaml.IFrameworkElementOverrides.Do_Abi_ArrangeOverride_1(IntPtr thisPtr, Size finalSize, Size* result)

![cv_exc_1](https://github.com/dotnet/maui/assets/91615935/99051def-970a-457f-96da-52612b3511e0)

Interestingly we tested this on two different machies with the same maui versions and one of the does not throw an exception, but results in an invalid layout:
![cv_exc_2](https://github.com/dotnet/maui/assets/91615935/c510241b-9a9f-44c5-8165-8610beb0927d)

I placed this code inside the button click handler:
double collectionViewHeight = this.cv1.DesiredSize.Height;
And I can see that the size of the CollectionView is very very large:
collectionViewHeight = 954437184

### Steps to Reproduce

1. Get the repo from the provided link
2. Run the app in WinUI
3. Click the Add button in the upper right corner

Expected: Two items should be displayed in the CollectionView.
Actual: An exception is thrown.

### Link to public reproduction project repository

https://github.com/telerik/ms-samples/tree/main/Maui/CollectionViewThrowsAnException

### Version with bug

Unknown/Other

### Last version that worked well

7.0.86

### Affected platforms

Windows

### Affected platform versions

8.0.0-preview.6.8686

### Did you find any workaround?

N/A

**Comment by jsuarezruiz** [comment]
![image](https://github.com/dotnet/maui/assets/6755973/e37ed34d-92a8-4fae-b982-3a2a4bec0ee5)

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.8.0 Preview 1.0. Repro on Windows 11(8.0.100-preview.6.23330.14), not repro on Android 13.0-API33 and iOS 16.4 with below Project:
[CollectionViewThrowsAnException.zip](https://github.com/dotnet/maui/files/12310389/CollectionViewThrowsAnException.zip)
