### ISSUE TITLE
[net8][Windows] `WidthRequest="0"`  in `Grid` crashes the app

### ISSUE THREAD

**Issue by nor0x** [dotnet/maui#16475]
### Description

I tried to upgrade my app from .net7.0 to .net8 (8.0.100-preview.6.23330.14 - is missing in the version selection here in the issue template) and discovered a breaking change. I have added the following `Grid` element to outer `Grid` of a File -> New .NET MAUI App:

```
<Grid WidthRequest="0" BackgroundColor="MediumSeaGreen">
    <Border BackgroundColor="Green">
        <Label Text="Hello World" />
    </Border>
</Grid>
```

this code would work just fine on .net7 but in .net8 leads to the following Exception on Windows :
```
   at Windows.Foundation.Size..ctor(Single width, Single height)
   at Windows.Foundation.Size..ctor(Double width, Double height)
   at Microsoft.Maui.Platform.SizeExtensions.ToPlatform(Size size) in Microsoft.Maui.Platform\SizeExtensions.cs:line 10
   at Microsoft.Maui.Platform.MauiPanel.ArrangeOverride(Size finalSize) in Microsoft.Maui.Platform\MauiPanel.cs:line 39
   at Microsoft.Maui.Platform.ContentPanel.ArrangeOverride(Size finalSize) in Microsoft.Maui.Platform\ContentPanel.cs:line 39
   at Microsoft.UI.Xaml.FrameworkElement.Microsoft.UI.Xaml.IFrameworkElementOverrides.ArrangeOverride(Size finalSize)
   at ABI.Microsoft.UI.Xaml.IFrameworkElementOverrides.Do_Abi_ArrangeOverride_1(IntPtr thisPtr, Size finalSize, Size* result)
--- End of stack trace from previous location ---
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Microsoft.UI.Xaml.IFrameworkElementOverridesMethods.ArrangeOverride(IObjectReference _obj, Size finalSize)
   at Microsoft.UI.Xaml.FrameworkElement.ArrangeOverride(Size finalSize)
   at Microsoft.UI.Xaml.FrameworkElement.Microsoft.UI.Xaml.IFrameworkElementOverrides.ArrangeOverride(Size finalSize)
   at ABI.Microsoft.UI.Xaml.IFrameworkElementOverrides.Do_Abi_ArrangeOverride_1(IntPtr thisPtr, Size finalSize, Size* result)
--- End of stack trace from previous location ---
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Microsoft.UI.Xaml.IUIElementMethods.Arrange(IObjectReference _obj, Rect finalRect)
   at Microsoft.UI.Xaml.UIElement.Arrange(Rect finalRect)
   at Microsoft.Maui.ViewHandlerExtensions.PlatformArrangeHandler(IViewHandler viewHandler, Rect rect) in Microsoft.Maui\ViewHandlerExtensions.cs:line 62
   at Microsoft.Maui.Handlers.ViewHandler`2.PlatformArrange(Rect rect) in Microsoft.Maui.Handlers\ViewHandler.cs:line 545
   at Microsoft.Maui.Controls.VisualElement.ArrangeOverride(Rect bounds) in Microsoft.Maui.Controls\VisualElement.cs:line 2007
   at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IView.Arrange(Rect bounds) in Microsoft.Maui.Controls\VisualElement.cs:line 2000
   at Microsoft.Maui.Layouts.VerticalStackLayoutManager.ArrangeChildren(Rect bounds) in Microsoft.Maui.Layouts\VerticalStackLayoutManager.cs:line 51
   at Microsoft.Maui.Controls.Layout.CrossPlatformArrange(Rect bounds) in Microsoft.Maui.Controls\Layout.cs:line 302
   at Microsoft.Maui.Platform.MauiPanel.CrossPlatformArrange(Rect bounds) in Microsoft.Maui.Platform\MauiPanel.cs:line 19
   at Microsoft.Maui.Platform.MauiPanel.ArrangeOverride(Size finalSize) in Microsoft.Maui.Platform\MauiPanel.cs:line 39
   at Microsoft.Maui.Platform.LayoutPanel.ArrangeOverride(Size finalSize) in Microsoft.Maui.Platform\LayoutPanel.cs:line 16
   at Microsoft.UI.Xaml.FrameworkElement.Microsoft.UI.Xaml.IFrameworkElementOverrides.ArrangeOverride(Size finalSize)
   at ABI.Microsoft.UI.Xaml.IFrameworkElementOverrides.Do_Abi_ArrangeOverride_1(IntPtr thisPtr, Size finalSize, Size* result)
--- End of stack trace from previous location ---
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Microsoft.UI.Xaml.IUIElementMethods.Arrange(IObjectReference _obj, Rect finalRect)
   at Microsoft.UI.Xaml.UIElement.Arrange(Rect finalRect)
   at Microsoft.Maui.ViewHandlerExtensions.PlatformArrangeHandler(IViewHandler viewHandler, Rect rect) in Microsoft.Maui\ViewHandlerExtensions.cs:line 62
   at Microsoft.Maui.Handlers.ViewHandler`2.PlatformArrange(Rect rect) in Microsoft.Maui.Handlers\ViewHandler.cs:line 545
   at Microsoft.Maui.Controls.VisualElement.ArrangeOverride(Rect bounds) in Microsoft.Maui.Controls\VisualElement.cs:line 2007
   at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IView.Arrange(Rect bounds) in Microsoft.Maui.Controls\VisualElement.cs:line 2000
   at Microsoft.Maui.Layouts.GridLayoutManager.ArrangeChildren(Rect bounds) in Microsoft.Maui.Layouts\GridLayoutManager.cs:line 1070
   at Microsoft.Maui.Controls.Layout.CrossPlatformArrange(Rect bounds) in Microsoft.Maui.Controls\Layout.cs:line 302
   at Microsoft.Maui.Platform.MauiPanel.CrossPlatformArrange(Rect bounds) in Microsoft.Maui.Platform\MauiPanel.cs:line 19
   at Microsoft.Maui.Platform.MauiPanel.ArrangeOverride(Size finalSize) in Microsoft.Maui.Platform\MauiPanel.cs:line 39
   at Microsoft.Maui.Platform.LayoutPanel.ArrangeOverride(Size finalSize) in Microsoft.Maui.Platform\LayoutPanel.cs:line 16
   at Microsoft.UI.Xaml.FrameworkElement.Microsoft.UI.Xaml.IFrameworkElementOverrides.ArrangeOverride(Size finalSize)
   at ABI.Microsoft.UI.Xaml.IFrameworkElementOverrides.Do_Abi_ArrangeOverride_1(IntPtr thisPtr, Size finalSize, Size* result)
--- End of stack trace from previous location ---
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Microsoft.UI.Xaml.IUIElementMethods.Arrange(IObjectReference _obj, Rect finalRect)
   at Microsoft.UI.Xaml.UIElement.Arrange(Rect finalRect)
   at Microsoft.Maui.ViewHandlerExtensions.PlatformArrangeHandler(IViewHandler viewHandler, Rect rect) in Microsoft.Maui\ViewHandlerExtensions.cs:line 62
   at Microsoft.Maui.Handlers.ViewHandler`2.PlatformArrange(Rect rect) in Microsoft.Maui.Handlers\ViewHandler.cs:line 545
   at Microsoft.Maui.Controls.VisualElement.ArrangeOverride(Rect bounds) in Microsoft.Maui.Controls\VisualElement.cs:line 2007
   at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IView.Arrange(Rect bounds) in Microsoft.Maui.Controls\VisualElement.cs:line 2000
   at Microsoft.Maui.Layouts.GridLayoutManager.ArrangeChildren(Rect bounds) in Microsoft.Maui.Layouts\GridLayoutManager.cs:line 1070
   at Microsoft.Maui.Controls.Layout.CrossPlatformArrange(Rect bounds) in Microsoft.Maui.Controls\Layout.cs:line 302
   at Microsoft.Maui.Platform.MauiPanel.CrossPlatformArrange(Rect bounds) in Microsoft.Maui.Platform\MauiPanel.cs:line 19
   at Microsoft.Maui.Platform.MauiPanel.ArrangeOverride(Size finalSize) in Microsoft.Maui.Platform\MauiPanel.cs:line 39
   at Microsoft.Maui.Platform.LayoutPanel.ArrangeOverride(Size finalSize) in Microsoft.Maui.Platform\LayoutPanel.cs:line 16
   at Microsoft.UI.Xaml.FrameworkElement.Microsoft.UI.Xaml.IFrameworkElementOverrides.ArrangeOverride(Size finalSize)
   at ABI.Microsoft.UI.Xaml.IFrameworkElementOverrides.Do_Abi_ArrangeOverride_1(IntPtr thisPtr, Size finalSize, Size* result)
--- End of stack trace from previous location ---
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Microsoft.UI.Xaml.IUIElementMethods.Arrange(IObjectReference _obj, Rect finalRect)
   at Microsoft.UI.Xaml.UIElement.Arrange(Rect finalRect)
   at Microsoft.Maui.ViewHandlerExtensions.PlatformArrangeHandler(IViewHandler viewHandler, Rect rect) in Microsoft.Maui\ViewHandlerExtensions.cs:line 62
   at Microsoft.Maui.Handlers.ViewHandler`2.PlatformArrange(Rect rect) in Microsoft.Maui.Handlers\ViewHandler.cs:line 545
   at Microsoft.Maui.Controls.VisualElement.ArrangeOverride(Rect bounds) in Microsoft.Maui.Controls\VisualElement.cs:line 2007
   at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IView.Arrange(Rect bounds) in Microsoft.Maui.Controls\VisualElement.cs:line 2000
   at Microsoft.Maui.Controls.Compatibility.Layout.LayoutChildIntoBoundingRegion(VisualElement child, Rect region) in Microsoft.Maui.Controls.Compatibility\Layout.cs:line 296
   at Microsoft.Maui.Controls.Page.LayoutChildren(Double x, Double y, Double width, Double height) in Microsoft.Maui.Controls\Page.cs:line 386
   at Microsoft.Maui.Controls.Page.UpdateChildrenLayout() in Microsoft.Maui.Controls\Page.cs:line 478
   at Microsoft.Maui.Controls.Page.OnSizeAllocated(Double width, Double height) in Microsoft.Maui.Controls\Page.cs:line 455
   at Microsoft.Maui.Controls.VisualElement.SizeAllocated(Double width, Double height) in Microsoft.Maui.Controls\VisualElement.cs:line 1633
   at Microsoft.Maui.Controls.VisualElement.UpdateBoundsComponents(Rect bounds) in Microsoft.Maui.Controls\VisualElement.cs:line 1977
   at Microsoft.Maui.Controls.VisualElement.set_Frame(Rect value) in Microsoft.Maui.Controls\VisualElement.cs:line 1027
   at Microsoft.Maui.Controls.ContentPage.Microsoft.Maui.ICrossPlatformLayout.CrossPlatformArrange(Rect bounds) in Microsoft.Maui.Controls\ContentPage.cs:line 79
   at Microsoft.Maui.Platform.MauiPanel.CrossPlatformArrange(Rect bounds) in Microsoft.Maui.Platform\MauiPanel.cs:line 19
   at Microsoft.Maui.Platform.MauiPanel.ArrangeOverride(Size finalSize) in Microsoft.Maui.Platform\MauiPanel.cs:line 39
   at Microsoft.Maui.Platform.ContentPanel.ArrangeOverride(Size finalSize) in Microsoft.Maui.Platform\ContentPanel.cs:line 39
   at Microsoft.UI.Xaml.FrameworkElement.Microsoft.UI.Xaml.IFrameworkElementOverrides.ArrangeOverride(Size finalSize)
   at ABI.Microsoft.UI.Xaml.IFrameworkElementOverrides.Do_Abi_ArrangeOverride_1(IntPtr thisPtr, Size finalSize, Size* result)
--- End of stack trace from previous location ---
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Microsoft.UI.Xaml.IFrameworkElementOverridesMethods.ArrangeOverride(IObjectReference _obj, Size finalSize)
   at Microsoft.UI.Xaml.FrameworkElement.ArrangeOverride(Size finalSize)
   at Microsoft.UI.Xaml.FrameworkElement.Microsoft.UI.Xaml.IFrameworkElementOverrides.ArrangeOverride(Size finalSize)
   at ABI.Microsoft.UI.Xaml.IFrameworkElementOverrides.Do_Abi_ArrangeOverride_1(IntPtr thisPtr, Size finalSize, Size* result)
--- End of stack trace from previous location ---
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Microsoft.UI.Xaml.IFrameworkElementOverridesMethods.ArrangeOverride(IObjectReference _obj, Size finalSize)
   at Microsoft.UI.Xaml.FrameworkElement.ArrangeOverride(Size finalSize)
   at Microsoft.UI.Xaml.FrameworkElement.Microsoft.UI.Xaml.IFrameworkElementOverrides.ArrangeOverride(Size finalSize)
   at ABI.Microsoft.UI.Xaml.IFrameworkElementOverrides.Do_Abi_ArrangeOverride_1(IntPtr thisPtr, Size finalSize, Size* result)
--- End of stack trace from previous location ---
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Microsoft.UI.Xaml.IFrameworkElementOverridesMethods.ArrangeOverride(IObjectReference _obj, Size finalSize)
   at Microsoft.UI.Xaml.FrameworkElement.ArrangeOverride(Size finalSize)
   at Microsoft.UI.Xaml.FrameworkElement.Microsoft.UI.Xaml.IFrameworkElementOverrides.ArrangeOverride(Size finalSize)
   at ABI.Microsoft.UI.Xaml.IFrameworkElementOverrides.Do_Abi_ArrangeOverride_1(IntPtr thisPtr, Size finalSize, Size* result)
--- End of stack trace from previous location ---
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Microsoft.UI.Xaml.IUIElementMethods.Arrange(IObjectReference _obj, Rect finalRect)
   at Microsoft.UI.Xaml.UIElement.Arrange(Rect finalRect)
   at Microsoft.Maui.Platform.WindowRootViewContainer.ArrangeOverride(Size finalSize) in Microsoft.Maui.Platform\WindowRootViewContainer.cs:line 37
   at Microsoft.UI.Xaml.FrameworkElement.Microsoft.UI.Xaml.IFrameworkElementOverrides.ArrangeOverride(Size finalSize)
   at ABI.Microsoft.UI.Xaml.IFrameworkElementOverrides.Do_Abi_ArrangeOverride_1(IntPtr thisPtr, Size finalSize, Size* result)
```

this currently blocks me from upgrading my application

### Steps to Reproduce

Add `Grid` with `WidthRequest="0"` and some Border and Label content to a blank .NET MAUI app

### Link to public reproduction project repository

https://github.com/nor0x/MauiFails

### Version with bug

8.0.0-preview.5.8529

### Last version that worked well

7.0.86

### Affected platforms

Windows

### Affected platform versions

windows10.0.19041.0

**Comment by jsuarezruiz** [comment]
Cannot reproduce the issue with .NET 8 Preview 7.
![image](https://github.com/dotnet/maui/assets/6755973/52a727f2-e064-4ed1-8142-5adddb5bd0f5)

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.8.0 Preview 1.0. This issue does not repro on Windows 11(8.0.100-preview.7.23376.3) with below Project:
[16475.zip](https://github.com/dotnet/maui/files/12354365/16475.zip)
