### ISSUE TITLE
[regression/8.0.0-preview.3.8149] Crash when using NavigationPage.TitleView (Java.Lang.IllegalStateException: The specified child already has a parent)

### ISSUE THREAD

**Issue by tranb3r** [dotnet/maui#16499]
### Description

When using NavigationPage.TitleView, an app crashes when being launched again after it has been killed by the system.
Here is the exception: `Java.Lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.`

### Steps to Reproduce

1. in android settings, developer options, enable "don't keep activites"
2. launch test app, then tap on home button: app goes to background, and is killed by system
3. launch app again, it crashes

### Link to public reproduction project repository

[Repro](https://github.com/tranb3r/Issues/tree/main/MauiAppDontKeepActivities)

### Version with bug

[8.0.0-preview.3.8149](https://github.com/dotnet/maui/releases/tag/8.0.0-preview.3.8149)

### Last version that worked well

[8.0.0-preview.2.7871](https://github.com/dotnet/maui/releases/tag/8.0.0-preview.2.7871)

### Affected platforms

Android

### Did you find any workaround?

No

### Relevant log output

```shell
Java.Lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
   at Java.Interop.JniEnvironment.InstanceMethods.CallVoidMethod(JniObjectReference , JniMethodInfo , JniArgumentValue* )
   at Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualVoidMethod(String , IJavaPeerable , JniArgumentValue* )
   at Android.Views.ViewGroup.AddView(View )
   at Microsoft.Maui.Controls.Toolbar.UpdateTitleView()
   at Microsoft.Maui.Controls.Toolbar.MapTitleView(IToolbarHandler , Toolbar )
   at Microsoft.Maui.Controls.Toolbar.MapTitleView(ToolbarHandler arg1, Toolbar arg2)
   at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0[[Microsoft.Maui.Controls.Toolbar, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.ToolbarHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v)
   at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String , IElementHandler , IElement )
   at Microsoft.Maui.PropertyMapper.UpdateProperties(IElementHandler , IElement )
   at Microsoft.Maui.Handlers.ElementHandler.SetVirtualView(IElement )
   at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement , IMauiContext )
   at Microsoft.Maui.Platform.ElementExtensions.ToPlatform(IElement , IMauiContext )
   at Microsoft.Maui.Handlers.ViewHandler.MapToolbar(IElementHandler , IToolbarElement )
   at Microsoft.Maui.Handlers.WindowHandler.MapToolbar(IWindowHandler handler, IWindow view)
   at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0[[Microsoft.Maui.IWindow, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.IWindowHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v)
   at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String , IElementHandler , IElement )
   at Microsoft.Maui.PropertyMapper.UpdateProperties(IElementHandler , IElement )
   at Microsoft.Maui.Handlers.ElementHandler.SetVirtualView(IElement )
   at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler )
   at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value)
   at Microsoft.Maui.Platform.ElementExtensions.SetHandler(Context , IElement , IMauiContext )
   at Microsoft.Maui.Platform.ElementExtensions.SetWindowHandler(Activity , IWindow , IMauiContext )
   at Microsoft.Maui.Platform.ApplicationExtensions.CreatePlatformWindow(Activity , IApplication , Bundle )
   at Microsoft.Maui.MauiAppCompatActivity.OnCreate(Bundle )
   at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_(IntPtr jnienv, IntPtr native__this, IntPtr native_savedInstanceState)
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPL_V(_JniMarshal_PPL_V callback, IntPtr jnienv, IntPtr klazz, IntPtr p0)
  --- End of managed Java.Lang.IllegalStateException stack trace ---

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.xxx.app/crc64d002a6d246c183e1.mm}: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3644)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3781)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2306)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7918)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

Caused by java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
       at android.view.ViewGroup.addViewInner(ViewGroup.java:5248)
       at android.view.ViewGroup.addView(ViewGroup.java:5077)
       at android.view.ViewGroup.addView(ViewGroup.java:5017)
       at android.view.ViewGroup.addView(ViewGroup.java:4989)
       at crc6488302ad6e9e4df1a.MauiAppCompatActivity.n_onCreate(MauiAppCompatActivity.java)
       at crc6488302ad6e9e4df1a.MauiAppCompatActivity.onCreate(MauiAppCompatActivity.java:48)
       at android.app.Activity.performCreate(Activity.java:8342)
       at android.app.Activity.performCreate(Activity.java:8321)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1417)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3625)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3781)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2306)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7918)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by tranb3r** [comment]
Here is a repro: https://github.com/tranb3r/Issues/tree/main/MauiAppDontKeepActivities

**Comment by jsuarezruiz** [comment]
Cannot reproduce the issue with preview 7 or in the current net8 development branch. Maybe I am missing something?
![issue-16499](https://github.com/dotnet/maui/assets/6755973/61c12779-2169-4c66-970e-b78317784211)

**Comment by tranb3r** [comment]
I've just tested my sample app with net8-pre7 and I can still reproduce the issue.
@jsuarezruiz Are you running my sample app? 
In your screen capture, it seems like the app title and splashscreen are different. Maybe some other difference could explain the exception?

**Comment by samhouts** [comment]
Confirmed that this was a regression between https://github.com/dotnet/maui/compare/8.0.0-preview.2.7871...8.0.0-preview.3.8149. 

Not sure which PR is the culprit. https://github.com/dotnet/maui/pull/13879 is the most sus to me.

**Comment by samhouts** [comment]
Also, still repros in pre7.

**Comment by tranb3r** [comment]
Any update? Thanks

**Comment by tranb3r** [comment]
Still happening in RC1.
