### ISSUE TITLE
MAUI: Xamarin.Android.Aapt2.targets(156,3): error : The file exists

### ISSUE THREAD

**Issue by Igor-ZA** [dotnet/maui#16513]
### Description

3>Done building project "MobileTodo.csproj".
3>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\33.0.68\tools\Xamarin.Android.Aapt2.targets(156,3): error : The file exists.
3>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\33.0.68\tools\Xamarin.Android.Aapt2.targets(156,3): error : 
3>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\33.0.68\tools\Xamarin.Android.Aapt2.targets(156,3): error :    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
3>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\33.0.68\tools\Xamarin.Android.Aapt2.targets(156,3): error :    at System.IO.Path.InternalGetTempFileName(Boolean checkHost)
3>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\33.0.68\tools\Xamarin.Android.Aapt2.targets(156,3): error :    at Xamarin.Android.Tasks.Aapt2Link.GetTempFile()
3>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\33.0.68\tools\Xamarin.Android.Aapt2.targets(156,3): error :    at Xamarin.Android.Tasks.Aapt2Link.<RunTaskAsync>d__116.MoveNext()
3>Done building project "MobileTodo.csproj" -- FAILED.

### Steps to Reproduce

1. Create a File > New .NET MAUI Blazor App
2. Build
3.  C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\33.0.68\tools\Xamarin.Android.Aapt2.targets(156,3): error : The file exists.

![devenv_9hPHrGLoTr](https://github.com/dotnet/maui/assets/56849652/499329ed-ff9a-4c46-86c8-3e930ec5e53c)

Installed Workload Id      Manifest Version       Installation Source
---------------------------------------------------------------------
maui                       7.0.92/7.0.100         SDK 7.0.300
tvos                       16.4.7089/7.0.100      VS 17.6.33829.357
macos                      13.3.7089/7.0.100      VS 17.6.33829.357
maui-windows               7.0.92/7.0.100         VS 17.6.33829.357
maccatalyst                16.4.7089/7.0.100      VS 17.6.33829.357
maui-ios                   7.0.92/7.0.100         VS 17.6.33829.357
ios                        16.4.7089/7.0.100      VS 17.6.33829.357
maui-android               7.0.92/7.0.100         VS 17.6.33829.357
maui-maccatalyst           7.0.92/7.0.100         VS 17.6.33829.357
android                    33.0.68/7.0.100        VS 17.6.33829.357
wasm-tools                 7.0.9/7.0.100          VS 17.6.33829.357

### Version with bug

7.0.49

### Last version that worked well

7.0.49

### Affected platforms

Android

**Comment by Igor-ZA** [comment]
Hi
The Temp folder is full, deleting it solved the problem.
