### ISSUE TITLE
After upgrading to Visual Studio 2022 Preview to 17.8.0 Empty MAUI App does not compile

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [dotnet/maui#16652]
### Description

If you try to compile an empty MAUI app on command line with `dotnet build -t:Run -f:net8.0-windows10.0.19041.0` it throws an error. See below:

```
  Unhandled exception. System.TypeInitializationException: The type initializer for '<Module>' threw an exception.
   ---> System.TypeInitializationException: The type initializer for 'WinRT.ActivationFactory`1' threw an exception.
   ---> System.Runtime.InteropServices.COMException (0x80040154): Class not registered (0x80040154 (REGDB_E_CLASSNOTREG
  ))
     at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
     at WinRT.BaseActivationFactory..ctor(String typeNamespace, String typeFullName)
     at WinRT.ActivationFactory`1..ctor()
     at WinRT.ActivationFactory`1..cctor()
     --- End of inner exception stack trace ---
     at WinRT.ActivationFactory`1.ActivateInstance[I]()
     at Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentInitializeOptions..ctor()
     at Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentManagerCS.AutoInitialize.get_Options() in C:\Use
  rs\tommi\.nuget\packages\microsoft.windowsappsdk\1.3.230602002\include\DeploymentManagerAutoInitializer.cs:line 44
     at Microsoft.Windows.ApplicationModel.WindowsAppRuntime.DeploymentManagerCS.AutoInitialize.AccessWindowsAppSDK() i
  n C:\Users\tommi\.nuget\packages\microsoft.windowsappsdk\1.3.230602002\include\DeploymentManagerAutoInitializer.cs:li
  ne 30
     at .cctor()
     --- End of inner exception stack trace ---
C:\Program Files\dotnet\sdk\8.0.100-preview.7.23376.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(1021,5):
 error MSB3073: The command "C:\hmp\Test\MauiApp4\bin\Debug\net8.0-windows10.0.19041.0\win10-x64\MauiApp4.exe " exited
with code -532462766. [C:\hmp\Test\MauiApp4\MauiApp4.csproj::TargetFramework=net8.0-windows10.0.19041.0]

Build FAILED.
```

Using Visual Studio 2022 Preview 17.8.0 and `dotnet build` from the command line.

### Steps to Reproduce

1. `dotnet maui new -f:net8.0 -n:MauiApp4`
2. `dotnet build -t:Run -f:net8.0-windows10.0.19041.0`

### Version with bug

Unknown/Other

### Is this a regression from previous behavior? In other words, did this work before an update and now does not?

- [X] Yes, this used to work
- [ ] No, this is something new
- [ ] Not sure, did not test other versions

### Last version that worked well

8.0.0-preview.7.8842

### Affected platforms

Windows

**Comment by mattleibow** [comment]
I am not sure you can launch Windows app from the command line using `-t:Run`. WinUI does not yet support this.

https://github.com/microsoft/WindowsAppSDK/issues/2922

If you want to launch from the command line, you have to make the app be an unpackaged app: https://blog.verslu.is/maui/dotnet-maui-windows-unpackaged-apps/
