### ISSUE TITLE
CORS policy: No 'Access-Control-Allow-Origin'  - triggering application crash

### ISSUE THREAD

**Issue by mgungorchamp** [dotnet/maui#16677]
### Description

I am using Webview - it gave me this crash at the output.  Seems it's related to CORS policy but I could not find how to give permission to the .Net MAUI app.    This is the Android version of the app. 

[chromium] [INFO:CONSOLE(0)] "Access to XMLHttpRequest at 'https://api.rlcdn.com/api/identity/envelope?pid=1258' from origin 'https://weather.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.", source: about:srcdoc (0)
[cr_ChildProcessConn] onServiceDisconnected (crash or killed by oom): pid=10174 bindings:W  S
[chromium] [ERROR:aw_browser_terminator.cc(156)] Renderer process (10174) crash detected (code 5).
[chromium] [FATAL:crashpad_client_linux.cc(732)] Render process (10174)'s crash wasn't handled by all associated  webviews, triggering application crash.
[libc] Fatal signal 5 (SIGTRAP), code 1 (TRAP_BRKPT), fault addr 0xcc9e58be in tid 10036 (board.infoboard), pid 10036 (board.infoboard)

### Steps to Reproduce

Just run the application several hours, this crash can come or might not come, no control over it. 

### Link to public reproduction project repository

https://github.com/mgungorchamp/InfoBoard/tree/SoloPage-Analytics

### Version with bug

7.0.92

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Did you find any workaround?

Not yet

### Relevant log output

```shell
[chromium] [INFO:CONSOLE(0)] "Access to XMLHttpRequest at 'https://api.rlcdn.com/api/identity/envelope?pid=1258' from origin 'https://weather.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.", source: about:srcdoc (0)
[cr_ChildProcessConn] onServiceDisconnected (crash or killed by oom): pid=10174 bindings:W  S
[chromium] [ERROR:aw_browser_terminator.cc(156)] Renderer process (10174) crash detected (code 5).
[chromium] [FATAL:crashpad_client_linux.cc(732)] Render process (10174)'s crash wasn't handled by all associated  webviews, triggering application crash.
[libc] Fatal signal 5 (SIGTRAP), code 1 (TRAP_BRKPT), fault addr 0xcc9e58be in tid 10036 (board.infoboard), pid 10036 (board.infoboard)
```

**Comment by moljac** [comment]
Try setting Android native `WebSettings.AllowUniversalAccessFromFileURLs` property to `true`.

https://learn.microsoft.com/en-us/dotnet/api/android.webkit.websettings.allowuniversalaccessfromfileurls?view=xamarin-android-sdk-13

**Comment by mgungorchamp** [comment]
One more crash report - this is happening after running almost 24 hours and showing different websites

[0:] Navigating to Web Media #: https://fast.com/
[cr_ChildProcessConn] onServiceDisconnected (crash or killed by oom): pid=24147 bindings:W  S
[chromium] [ERROR:aw_browser_terminator.cc(156)] Renderer process (24147) crash detected (code 7).
[chromium] [FATAL:crashpad_client_linux.cc(732)] Render process (24147)'s crash wasn't handled by all associated  webviews, triggering application crash.
[libc] Fatal signal 7 (SIGBUS), code 0 (SI_USER) in tid 23933 (board.infoboard), pid 23933 (board.infoboard)

**Comment by mgungorchamp** [comment]
Another fatal caused by chromium 

[0:] Navigating to Web Media #: weather.com
[chromium] [INFO:CONSOLE(9)] "fun-hooks: referenced 'adpod' but it was never created", source: https://micro.rubiconproject.com/prebid/dynamic/10738.js (9)
[chromium] [INFO:CONSOLE(9)] "fun-hooks: referenced 'adpod' but it was never created", source: https://micro.rubiconproject.com/prebid/dynamic/10738.js (9)
[chromium] [INFO:CONSOLE(10)] "[GPT] Attempted to load GPT multiple times.", source: https://securepubads.g.doubleclick.net/pagead/managed/js/gpt/m202308030102/pubads_impl.js (10)
[chromium] [INFO:CONSOLE(10)] "[GPT] Using deprecated googletag.encryptedSignalProviders. Please use googletag.secureSignalProviders instead.", source: https://securepubads.g.doubleclick.net/pagead/managed/js/gpt/m202308030102/pubads_impl.js (10)
[chromium] [INFO:CONSOLE(10)] "[GPT] Cannot find targeting attribute "crt_pb" for "/7646/tablet_weather_us/local_forecasts/10_day".", source: https://securepubads.g.doubleclick.net/pagead/managed/js/gpt/m202308030102/pubads_impl.js (10)
[chromium] [INFO:CONSOLE(10)] "[GPT] Cannot find targeting attribute "crt_bidid" for "/7646/tablet_weather_us/local_forecasts/10_day".", source: https://securepubads.g.doubleclick.net/pagead/managed/js/gpt/m202308030102/pubads_impl.js (10)
[chromium] [INFO:CONSOLE(10)] "[GPT] Cannot find targeting attribute "crt_pb" for "/7646/tablet_weather_us/local_forecasts/10_day".", source: https://securepubads.g.doubleclick.net/pagead/managed/js/gpt/m202308030102/pubads_impl.js (10)
[chromium] [INFO:CONSOLE(10)] "[GPT] Cannot find targeting attribute "crt_bidid" for "/7646/tablet_weather_us/local_forecasts/10_day".", source: https://securepubads.g.doubleclick.net/pagead/managed/js/gpt/m202308030102/pubads_impl.js (10)
[chromium] [INFO:CONSOLE(10)] "[GPT] Cannot find targeting attribute "crt_deal" for "/7646/tablet_weather_us/local_forecasts/10_day".", source: https://securepubads.g.doubleclick.net/pagead/managed/js/gpt/m202308030102/pubads_impl.js (10)
[chromium] [INFO:CONSOLE(37)] "invalid tracking pixel from cid: 6162793669_138440152679", source:  (37)
[chatty] uid=10083(com.guzelboard.infoboard) identical 1 line
[chromium] [INFO:CONSOLE(37)] "invalid tracking pixel from cid: 6162793669_138440152679", source:  (37)
[chromium] [INFO:CONSOLE(10)] "[GPT] Cannot find targeting attribute "crt_pb" for "/7646/tablet_weather_us/local_forecasts/10_day".", source: https://securepubads.g.doubleclick.net/pagead/managed/js/gpt/m202308030102/pubads_impl.js (10)
[chromium] [INFO:CONSOLE(10)] "[GPT] Cannot find targeting attribute "crt_bidid" for "/7646/tablet_weather_us/local_forecasts/10_day".", source: https://securepubads.g.doubleclick.net/pagead/managed/js/gpt/m202308030102/pubads_impl.js (10)
[chromium] [INFO:CONSOLE(10)] "[GPT] Cannot find targeting attribute "crt_pb" for "/7646/tablet_weather_us/local_forecasts/10_day".", source: https://securepubads.g.doubleclick.net/pagead/managed/js/gpt/m202308030102/pubads_impl.js (10)
[chromium] [INFO:CONSOLE(10)] "[GPT] Cannot find targeting attribute "crt_bidid" for "/7646/tablet_weather_us/local_forecasts/10_day".", source: https://securepubads.g.doubleclick.net/pagead/managed/js/gpt/m202308030102/pubads_impl.js (10)
[chromium] [INFO:CONSOLE(10)] "[GPT] Cannot find targeting attribute "crt_pb" for "/7646/tablet_weather_us/local_forecasts/10_day".", source: https://securepubads.g.doubleclick.net/pagead/managed/js/gpt/m202308030102/pubads_impl.js (10)
[chromium] [INFO:CONSOLE(10)] "[GPT] Cannot find targeting attribute "crt_bidid" for "/7646/tablet_weather_us/local_forecasts/10_day".", source: https://securepubads.g.doubleclick.net/pagead/managed/js/gpt/m202308030102/pubads_impl.js (10)
[chromium] [INFO:CONSOLE(10)] "[GPT] Cannot find targeting attribute "crt_pb" for "/7646/tablet_weather_us/local_forecasts/10_day".", source: https://securepubads.g.doubleclick.net/pagead/managed/js/gpt/m202308030102/pubads_impl.js (10)
[chromium] [INFO:CONSOLE(10)] "[GPT] Cannot find targeting attribute "crt_bidid" for "/7646/tablet_weather_us/local_forecasts/10_day".", source: https://securepubads.g.doubleclick.net/pagead/managed/js/gpt/m202308030102/pubads_impl.js (10)
[chromium] [INFO:CONSOLE(10)] "[GPT] Cannot find targeting attribute "crt_pb" for "/7646/tablet_weather_us/local_forecasts/10_day".", source: https://securepubads.g.doubleclick.net/pagead/managed/js/gpt/m202308030102/pubads_impl.js (10)
[chromium] [INFO:CONSOLE(10)] "[GPT] Cannot find targeting attribute "crt_bidid" for "/7646/tablet_weather_us/local_forecasts/10_day".", source: https://securepubads.g.doubleclick.net/pagead/managed/js/gpt/m202308030102/pubads_impl.js (10)
[chromium] [INFO:CONSOLE(10)] "[GPT] Cannot find targeting attribute "crt_pb" for "/7646/tablet_weather_us/local_forecasts/10_day".", source: https://securepubads.g.doubleclick.net/pagead/managed/js/gpt/m202308030102/pubads_impl.js (10)
[chromium] [INFO:CONSOLE(10)] "[GPT] Cannot find targeting attribute "crt_bidid" for "/7646/tablet_weather_us/local_forecasts/10_day".", source: https://securepubads.g.doubleclick.net/pagead/managed/js/gpt/m202308030102/pubads_impl.js (10)
[chromium] [INFO:CONSOLE(10)] "[GPT] Cannot find targeting attribute "crt_pb" for "/7646/tablet_weather_us/local_forecasts/10_day".", source: https://securepubads.g.doubleclick.net/pagead/managed/js/gpt/m202308030102/pubads_impl.js (10)
[chromium] [INFO:CONSOLE(60)] "https://weather.com/forecast/allergy/l/3eba364c7c30f55f7fa0315970b5522150836a50e0530864fefa8d392cbbb95c", source:  (60)
[chromium] [INFO:CONSOLE(64)] "http", source:  (64)
[chromium] [INFO:CONSOLE(78)] "Submitted payload to account -- 747624766027, sqs queue -- events_web_creative successfully", source: https://weather.com/weather/tenday/l/Burlington+VT?canonicalCityId=8f174ec9663fe5a91f4ac9edd85718b50e6980567bd851a0ce16fb96857b6c83 (78)
[chatty] uid=10083(com.guzelboard.infoboard) identical 2 lines
[chromium] [INFO:CONSOLE(78)] "Submitted payload to account -- 747624766027, sqs queue -- events_web_creative successfully", source: https://weather.com/weather/tenday/l/Burlington+VT?canonicalCityId=8f174ec9663fe5a91f4ac9edd85718b50e6980567bd851a0ce16fb96857b6c83 (78)
[cr_ChildProcessConn] onServiceDisconnected (crash or killed by oom): pid=1384 bindings:W  S
[chromium] [ERROR:aw_browser_terminator.cc(156)] Renderer process (1384) crash detected (code -1).
[chromium] [ERROR:aw_browser_terminator.cc(112)] Render process (1384) kill (OOM or update) wasn't handed by all associated webviews, killing application.

**Comment by mgungorchamp** [comment]
FYI - Related to this
https://bugs.chromium.org/p/chromium/issues/detail?id=1472576#c4

**Comment by mgungorchamp** [comment]
127|kara:/data/data/com.guzelboard.infoboard/cache $ logcat -v threadtime -d > test.txt
 
127|kara:/data/data/com.guzelboard.infoboard/cache $ ls
InfoBoardLogs WebView image_manager_disk_cache test.txt
kara:/data/data/com.guzelboard.infoboard/cache $ cat test.txt
--------- beginning of crash
08-07 11:58:51.285  5164  5164 E AndroidRuntime: FATAL EXCEPTION: main
08-07 11:58:51.285  5164  5164 E AndroidRuntime: Process: com.yablio.sendfilestotv, PID: 5164
08-07 11:58:51.285  5164  5164 E AndroidRuntime: java.lang.RuntimeException: Unable to start receiver com.yablio.sendfilestotv.util.StartReceiver: java.lang.IllegalStateException: Not allowed to start service Intent { act=com.yablio.sendfilestotv.START_LISTENING cmp=com.yablio.sendfilestotv/.transfer.TransferService }: app is in background uid UidRecord{6fec42e u0a202 RCVR idle change:uncached procs:1 seq(0,0,0)}
08-07 11:58:51.285  5164  5164 E AndroidRuntime:        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3434)
08-07 11:58:51.285  5164  5164 E AndroidRuntime:        at android.app.ActivityThread.access$1300(ActivityThread.java:208)
08-07 11:58:51.285  5164  5164 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1685)
08-07 11:58:51.285  5164  5164 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
08-07 11:58:51.285  5164  5164 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:211)
08-07 11:58:51.285  5164  5164 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6769)
08-07 11:58:51.285  5164  5164 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
08-07 11:58:51.285  5164  5164 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
08-07 11:58:51.285  5164  5164 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
08-07 11:58:51.285  5164  5164 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { act=com.yablio.sendfilestotv.START_LISTENING cmp=com.yablio.sendfilestotv/.transfer.TransferService }: app is in background uid UidRecord{6fec42e u0a202 RCVR idle change:uncached procs:1 seq(0,0,0)}
08-07 11:58:51.285  5164  5164 E AndroidRuntime:        at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1621)
08-07 11:58:51.285  5164  5164 E AndroidRuntime:        at android.app.ContextImpl.startService(ContextImpl.java:1576)
08-07 11:58:51.285  5164  5164 E AndroidRuntime:        at android.content.ContextWrapper.startService(ContextWrapper.java:664)
08-07 11:58:51.285  5164  5164 E AndroidRuntime:        at android.content.ContextWrapper.startService(ContextWrapper.java:664)
08-07 11:58:51.285  5164  5164 E AndroidRuntime:        at com.yablio.sendfilestotv.transfer.TransferService.a(Unknown Source:31)
08-07 11:58:51.285  5164  5164 E AndroidRuntime:        at com.yablio.sendfilestotv.util.StartReceiver.onReceive(Unknown Source:14)
08-07 11:58:51.285  5164  5164 E AndroidRuntime:        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3425)
08-07 11:58:51.285  5164  5164 E AndroidRuntime:        ... 8 more
08-07 14:43:52.570 11085 11166 F libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xc4002550 in tid 11166 (.NET ThreadPool), pid 11085 (board.infoboard)

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.9.0 Preview 5. Can repro on Android platform with sample project.
https://github.com/mgungorchamp/InfoBoard/tree/SoloPage-Analytics
