### ISSUE TITLE
[regression/7.0] MAUI Buttons IsVisible=true don't display them after upd. Image element many times on Android

### ISSUE THREAD

**Issue by e-shevchuk** [dotnet/maui#16718]
### Description

I have a `ContentPage` with a few `Button`s and `Image` element. I hide some buttons, display about 50 different images by updating the bound `byte[]` prop in a ViewModel, and set each hidden button `IsVisible` back to `true`, but the buttons don't re-appear. If I press the Android `Home` button and immediately come back to the app where I left, I see the buttons I was trying to display all where they should be.

Additional info:

1. If I don't update the image, or update it just a few times, the buttons hiding/showing works as it should.
2. The images are ~400x400 px and we need to show them with frame rate about 7-15 per second. When I reduce image update rate to less than 0.8 updates/sec the app works as expected.

##### Prerequisites:

- Page (`.xaml`-based) bound to the ViewModel
  - A few buttons (`Ok`, `Cancel`, `Repeat`, `Selector`)
  - `Image`
- `CommunityToolkit.Mvvm` `[ObservableObject]`-based ViewModel
- An array of 10 slightly different images, approximately 400x400 px, represented by their `byte[]` values

##### Steps:

1. Show/Hide buttons in a different order a few times by updating the properties of the `ViewModel` with the `[ObservableProperty]` attribute, bound to the `IsVisible` property of the corresponding buttons.
2. Hide all the buttons except `Cancel`.
3. Display all the images in the `Image` element consecutively one after another, 50 times with a delay of 100 ms (50 Image.Source updates in total within ~5 seconds).
4. Set the properties bound to `IsVisible` of the buttons to `true`.

##### Expected Result:

- All the buttons are displayed.

##### Actual Result:

- Only `Cancel` is visible; other buttons are not, even though `HorizontalStackLayout.HorizontalOptions` is set to `Center`, and the `Cancel` button is shifted to the side as if the other buttons occupy space on the layout but are not visible. If a user switches to another app and immediately back, or opens and closes another window, all the buttons become visible after that.

### Link to public reproduction project repository

https://gitlab.com/e-shevchuk/imagebuttonissuerepro

### Version with bug

7.0.86

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

6.0

### Affected platforms

Android

### Affected platform versions

Android 33

### Did you find any workaround?

Unfortunately, no

### Relevant log output

```shell
19:35:04:594	[0:] CapturePage.CapturePage():. Current thread: 1. UI thread: 1
19:35:04:665	[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Primitives.dll
19:35:04:726	Loaded assembly: /data/data/com.companyname.app/files/.__override__/Microsoft.Extensions.Primitives.dll [External]
19:35:04:782	[0:] Microsoft.Maui.Controls.Xaml.Diagnostics.BindingDiagnostics: Warning: 'CaptureSectionVisible' property not found on 'App.CaptureViewModel', target property: 'Microsoft.Maui.Controls.VerticalStackLayout.IsVisible'
19:35:04:782	[monodroid-assembly] open_from_bundles: failed to load assembly System.Diagnostics.TraceSource.dll
19:35:04:782	Loaded assembly: /data/data/com.companyname.app/files/.__override__/System.Diagnostics.TraceSource.dll [External]
19:35:04:845	[0:] CapturePage.DisplayImages():. Current thread: 12. UI thread: 1
19:35:04:957	[OnBackInvokedCallback] OnBackInvokedCallback is not enabled for the application.
19:35:04:957	[OnBackInvokedCallback] Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
19:35:05:349	[CustomViewTarget] Glide treats LayoutParams.WRAP_CONTENT as a request for an image the size of this device's screen dimensions. If you want to load the original image and are ok with the corresponding memory cost and OOMs (depending on the input size), use .override(Target.SIZE_ORIGINAL). Otherwise, use LayoutParams.MATCH_PARENT, set layout_width and layout_height to fixed dimension, or use .override() with fixed dimensions.
19:35:05:408	[OnBackInvokedCallback] OnBackInvokedCallback is not enabled for the application.
19:35:05:408	[OnBackInvokedCallback] Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
19:35:05:408	[CustomViewTarget] Glide treats LayoutParams.WRAP_CONTENT as a request for an image the size of this device's screen dimensions. If you want to load the original image and are ok with the corresponding memory cost and OOMs (depending on the input size), use .override(Target.SIZE_ORIGINAL). Otherwise, use LayoutParams.MATCH_PARENT, set layout_width and layout_height to fixed dimension, or use .override() with fixed dimensions.
19:35:05:536	[CustomViewTarget] Glide treats LayoutParams.WRAP_CONTENT as a request for an image the size of this device's screen dimensions. If you want to load the original image and are ok with the corresponding memory cost and OOMs (depending on the input size), use .override(Target.SIZE_ORIGINAL). Otherwise, use LayoutParams.MATCH_PARENT, set layout_width and layout_height to fixed dimension, or use .override() with fixed dimensions.
19:35:05:536	[CustomViewTarget] Glide treats LayoutParams.WRAP_CONTENT as a request for an image the size of this device's screen dimensions. If you want to load the original image and are ok with the corresponding memory cost and OOMs (depending on the input size), use .override(Target.SIZE_ORIGINAL). Otherwise, use LayoutParams.MATCH_PARENT, set layout_width and layout_height to fixed dimension, or use .override() with fixed dimensions.
19:35:05:536	[CustomViewTarget] Glide treats LayoutParams.WRAP_CONTENT as a request for an image the size of this device's screen dimensions. If you want to load the original image and are ok with the corresponding memory cost and OOMs (depending on the input size), use .override(Target.SIZE_ORIGINAL). Otherwise, use LayoutParams.MATCH_PARENT, set layout_width and layout_height to fixed dimension, or use .override() with fixed dimensions.
19:35:05:536	[companyname.app] Suspending all threads took: 10.944ms
19:35:05:536	[CustomViewTarget] Glide treats LayoutParams.WRAP_CONTENT as a request for an image the size of this device's screen dimensions. If you want to load the original image and are ok with the corresponding memory cost and OOMs (depending on the input size), use .override(Target.SIZE_ORIGINAL). Otherwise, use LayoutParams.MATCH_PARENT, set layout_width and layout_height to fixed dimension, or use .override() with fixed dimensions.
19:35:05:536	[companyname.app] Background young concurrent copying GC freed 29156(3049KB) AllocSpace objects, 0(0B) LOS objects, 15% free, 6517KB/7732KB, paused 2.307ms,11.183ms total 60.330ms
19:35:05:595	[EGL_emulation] app_time_stats: avg=8.91ms min=2.36ms max=37.99ms count=49
19:35:05:595	Thread started:  #12
19:35:05:658	[CustomViewTarget] Glide treats LayoutParams.WRAP_CONTENT as a request for an image the size of this device's screen dimensions. If you want to load the original image and are ok with the corresponding memory cost and OOMs (depending on the input size), use .override(Target.SIZE_ORIGINAL). Otherwise, use LayoutParams.MATCH_PARENT, set layout_width and layout_height to fixed dimension, or use .override() with fixed dimensions.
19:35:05:658	Thread started:  #13
19:35:05:720	[CustomViewTarget] Glide treats LayoutParams.WRAP_CONTENT as a request for an image the size of this device's screen dimensions. If you want to load the original image and are ok with the corresponding memory cost and OOMs (depending on the input size), use .override(Target.SIZE_ORIGINAL). Otherwise, use LayoutParams.MATCH_PARENT, set layout_width and layout_height to fixed dimension, or use .override() with fixed dimensions.
19:35:05:771	[companyname.app] NativeAlloc concurrent copying GC freed 15064(1687KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 5566KB/10MB, paused 7.154ms,131us total 80.885ms
19:35:05:771	Thread started:  #14
19:35:05:830	[CustomViewTarget] Glide treats LayoutParams.WRAP_CONTENT as a request for an image the size of this device's screen dimensions. If you want to load the original image and are ok with the corresponding memory cost and OOMs (depending on the input size), use .override(Target.SIZE_ORIGINAL). Otherwise, use LayoutParams.MATCH_PARENT, set layout_width and layout_height to fixed dimension, or use .override() with fixed dimensions.
19:35:05:830	Thread started:  #15
19:35:05:929	[CustomViewTarget] Glide treats LayoutParams.WRAP_CONTENT as a request for an image the size of this device's screen dimensions. If you want to load the original image and are ok with the corresponding memory cost and OOMs (depending on the input size), use .override(Target.SIZE_ORIGINAL). Otherwise, use LayoutParams.MATCH_PARENT, set layout_width and layout_height to fixed dimension, or use .override() with fixed dimensions.
19:35:06:221	[0:] Microsoft.Maui.StreamImageSourceService: Warning: Unable to load image stream.
19:35:06:221	
19:35:06:221	Android.Util.AndroidRuntimeException: Only the original thread that created a view hierarchy can touch its views.
19:35:06:221	   at Java.Interop.JniEnvironment.StaticMethods.CallStaticVoidMethod(JniObjectReference type, JniMethodInfo method, JniArgumentValue* args) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/obj/Release/net7.0/JniEnvironment.g.cs:line 13250
19:35:06:221	   at Java.Interop.JniPeerMembers.JniStaticMethods.InvokeVoidMethod(String encodedMember, JniArgumentValue* parameters) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniStaticMethods.cs:line 97
19:35:06:221	   at Microsoft.Maui.PlatformInterop.LoadImageFromStream(ImageView imageView, Stream inputStream, IImageLoaderCallback callback) in D:\a\_work\1\s\src\Core\src\obj\Release
19:35:06:221	et7.0-android\generated\src\Microsoft.Maui.PlatformInterop.cs:line 443
19:35:06:221	   at Microsoft.Maui.StreamImageSourceService.LoadDrawableAsync(IImageSource imageSource, ImageView imageView, CancellationToken cancellationToken) in D:\a\_work\1\s\src\Core\src\ImageSources\StreamImageSourceService\StreamImageSourceService.Android.cs:line 28
19:35:06:221	  --- End of managed Android.Util.AndroidRuntimeException stack trace ---
19:35:06:221	android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
19:35:06:221		at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:9758)
19:35:06:221		at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:1959)
19:35:06:221		at android.view.View.requestLayout(View.java:26281)
19:35:06:221		at android.view.View.requestLayout(View.java:26281)
19:35:06:221		at android.view.View.requestLayout(View.java:26281)
19:35:06:221		at android.view.View.requestLayout(View.java:26281)
19:35:06:221		at android.view.View.requestLayout(View.java:26281)
19:35:06:221		at android.view.View.requestLayout(View.java:26281)
19:35:06:221		at androidx.core.widget.NestedScrollView.requestLayout(NestedScrollView.java:2075)
19:35:06:221		at android.view.View.requestLayout(View.java:26281)
19:35:06:221		at android.view.View.requestLayout(View.java:26281)
19:35:06:221		at android.view.View.requestLayout(View.java:26281)
19:35:06:221		at android.view.View.requestLayout(View.java:26281)
19:35:06:221		at android.widget.ImageView.setImageDrawable(ImageView.java:602)
19:35:06:221		at androidx.appcompat.widget.AppCompatImageView.setImageDrawable(AppCompatImageView.java:112)
19:35:06:221		at com.microsoft.maui.glide.MauiCustomViewTarget.onResourceCleared(MauiCustomViewTarget.java:30)
19:35:06:221		at com.bumptech.glide.request.target.CustomViewTarget.onLoadCleared(CustomViewTarget.java:210)
19:35:06:221		at com.bumptech.glide.request.SingleRequest.clear(SingleRequest.java:337)
19:35:06:221		at com.bumptech.glide.request.ErrorRequestCoordinator.clear(ErrorRequestCoordinator.java:48)
19:35:06:221		at com.bumptech.glide.manager.RequestTracker.clearAndRemove(RequestTracker.java:70)
19:35:06:221		at com.bumptech.glide.RequestManager.untrack(RequestManager.java:660)
19:35:06:221		at com.bumptech.glide.RequestManager.untrackOrDelegate(RequestManager.java:628)
19:35:06:221		at com.bumptech.glide.RequestManager.clear(RequestManager.java:624)
19:35:06:221		at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:811)
19:35:06:221		at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:780)
19:35:06:221		at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:771)
19:35:06:221		at com.microsoft.maui.PlatformInterop.prepare(PlatformInterop.java:229)
19:35:06:221		at com.microsoft.maui.PlatformInterop.loadInto(PlatformInterop.java:234)
19:35:06:221		at com.microsoft.maui.PlatformInterop.loadImageFromStream(PlatformInterop.java:265)
19:35:06:221	
19:35:06:221	  --- End of managed Android.Util.AndroidRuntimeException stack trace ---
19:35:06:221	android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
19:35:06:221		at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:9758)
19:35:06:221		at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:1959)
19:35:06:221		at android.view.View.requestLayout(View.java:26281)
19:35:06:221		at android.view.View.requestLayout(View.java:26281)
19:35:06:221		at android.view.View.requestLayout(View.java:26281)
19:35:06:221		at android.view.View.requestLayout(View.java:26281)
19:35:06:221		at android.view.View.requestLayout(View.java:26281)
19:35:06:221		at android.view.View.requestLayout(View.java:26281)
19:35:06:221		at androidx.core.widget.NestedScrollView.requestLayout(NestedScrollView.java:2075)
19:35:06:221		at android.view.View.requestLayout(View.java:26281)
19:35:06:221		at android.view.View.requestLayout(View.java:26281)
19:35:06:221		at android.view.View.requestLayout(View.java:26281)
19:35:06:221		at android.view.View.requestLayout(View.java:26281)
19:35:06:221		at android.widget.ImageView.setImageDrawable(ImageView.java:602)
19:35:06:221		at androidx.appcompat.widget.AppCompatImageView.setImageDrawable(AppCompatImageView.java:112)
19:35:06:221		at com.microsoft.maui.glide.MauiCustomViewTarget.onResourceCleared(MauiCustomViewTarget.java:30)
19:35:06:221		at com.bumptech.glide.request.target.CustomViewTarget.onLoadCleared(CustomViewTarget.java:210)
19:35:06:221		at com.bumptech.glide.request.SingleRequest.clear(SingleRequest.java:337)
19:35:06:221		at com.bumptech.glide.request.ErrorRequestCoordinator.clear(ErrorRequestCoordinator.java:48)
19:35:06:221		at com.bumptech.glide.manager.RequestTracker.clearAndRemove(RequestTracker.java:70)
19:35:06:221		at com.bumptech.glide.RequestManager.untrack(RequestManager.java:660)
19:35:06:221		at com.bumptech.glide.RequestManager.untrackOrDelegate(RequestManager.java:628)
19:35:06:221		at com.bumptech.glide.RequestManager.clear(RequestManager.java:624)
19:35:06:221		at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:811)
19:35:06:221		at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:780)
19:35:06:221		at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:771)
19:35:06:221		at com.microsoft.maui.PlatformInterop.prepare(PlatformInterop.java:229)
19:35:06:221		at com.microsoft.maui.PlatformInterop.loadInto(PlatformInterop.java:234)
19:35:06:221		at com.microsoft.maui.PlatformInterop.loadImageFromStream(PlatformInterop.java:265)
```

**Comment by PureWeen** [comment]
Duplicate of #15826
