### ISSUE TITLE
[regression/8.0.0-preview.7.8842] - Shared ResourceDictionary Styles prevents app from building in android

### ISSUE THREAD

**Issue by gabsamples6** [dotnet/maui#16908]
### Description

In my real world projects  I have a shared class library where all the styles are located so that this project can be shared but many apps.

this bugs prevents me from moving to .net 8 . Courtesy to @AndreasReitberger I have attached his project that I converted to .net 8  produces the same error I encounter in my real world app and it uses the same approach as him
Link to .net 7 project that works [https://github.com/AndreasReitberger/SharedMauiXamlStyles](url)
Link to the same project converted to .net 8 by me  https://github.com/gabsamples6/SharedMauiXamlStylesLibrary

below is why workload list
![image](https://github.com/dotnet/maui/assets/109357537/68face73-53fa-4c3d-b9cb-8a786b681dc0)

I hope this can be looked up quickly . Many thanks

### Steps to Reproduce

you can recreate this in 2 ways

1. Go to https://github.com/AndreasReitberger/SharedMauiXamlStyles
2. Download the project
3. Search and replace .net7.0 with .net8.0 (3 projects) 2 mins - even quicker with notepad++ 
4. Run the project android using latest VS 2022 preview 7
5. see android crashing at start up

with type converter failed.

Option 2
see my attached link below where I performed the above

### Link to public reproduction project repository

https://github.com/gabsamples6/SharedMauiXamlStylesLibrary

### Version with bug

8.0.0-preview.7.8842

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.92

### Affected platforms

iOS, Android

### Affected platform versions

Version 17.8.0 Preview 1.0 -android

### Did you find any workaround?

No  - I could not try in iOS where I get other issues that prevent launching but I did not want to clutter this bug with other issue.

### Relevant log output

```shell
Microsoft.Maui.Controls.Xaml.XamlParseException
  Message=Position 8:29. Type converter failed: Exception has been thrown by the target of an invocation.
  Source=Microsoft.Maui.Controls.Xaml
  StackTrace:
   at Microsoft.Maui.Controls.Xaml.CreateValuesVisitor.Visit(ElementNode node, INode parentNode) in D:\a\_work\1\s\src\Controls\src\Xaml\CreateValuesVisitor.cs:line 106
   at Microsoft.Maui.Controls.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode) in D:\a\_work\1\s\src\Controls\src\Xaml\XamlNode.cs:line 159
   at Microsoft.Maui.Controls.Xaml.ListNode.Accept(IXamlNodeVisitor visitor, INode parentNode) in D:\a\_work\1\s\src\Controls\src\Xaml\XamlNode.cs:line 236
   at Microsoft.Maui.Controls.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode) in D:\a\_work\1\s\src\Controls\src\Xaml\XamlNode.cs:line 153
   at Microsoft.Maui.Controls.Xaml.RootNode.Accept(IXamlNodeVisitor visitor, INode parentNode) in D:\a\_work\1\s\src\Controls\src\Xaml\XamlNode.cs:line 210
   at Microsoft.Maui.Controls.Xaml.XamlLoader.Visit(RootNode rootnode, HydrationContext visitorContext, Boolean useDesignProperties) in D:\a\_work\1\s\src\Controls\src\Xaml\XamlLoader.cs:line 207
   at Microsoft.Maui.Controls.Xaml.XamlLoader.Load(Object view, String xaml, Assembly rootAssembly, Boolean useDesignProperties) in D:\a\_work\1\s\src\Controls\src\Xaml\XamlLoader.cs:line 78
   at Microsoft.Maui.Controls.Xaml.XamlLoader.Load(Object view, String xaml, Boolean useDesignProperties) in D:\a\_work\1\s\src\Controls\src\Xaml\XamlLoader.cs:line 53
   at Microsoft.Maui.Controls.Xaml.XamlLoader.Load(Object view, Type callingType) in D:\a\_work\1\s\src\Controls\src\Xaml\XamlLoader.cs:line 49
   at Microsoft.Maui.Controls.Xaml.Extensions.LoadFromXaml[App](App view, Type callingType) in D:\a\_work\1\s\src\Controls\src\Xaml\ViewExtensions.cs:line 37
   at SharedMauiXamlStylesLibrary.SampleApp.App.InitializeComponent() in D:\Dev\Mobile\MAUI\Styles\SharedMauiV8\src\SharedMauiXamlStylesLibrary.SampleApp\Microsoft.Maui.Controls.SourceGen\Microsoft.Maui.Controls.SourceGen.CodeBehindGenerator\App.xaml.sg.cs:line 22
   at SharedMauiXamlStylesLibrary.SampleApp.App..ctor() in D:\Dev\Mobile\MAUI\Styles\SharedMauiV8\src\SharedMauiXamlStylesLibrary.SampleApp\App.xaml.cs:line 13
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Constructor(Object obj, IntPtr* args)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSiteMain(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSite(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
   at System.Collections.Concurrent.ConcurrentDictionary`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceIdentifier, Microsoft.Extensions.DependencyInjection, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Func`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope, Microsoft.Extensions.DependencyInjection, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].GetOrAdd(ServiceIdentifier key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Maui.MauiContext.WrappedServiceProvider.GetService(Type serviceType) in D:\a\_work\1\s\src\Core\src\MauiContext.cs:line 68
   at Microsoft.Maui.MauiContext.WrappedServiceProvider.GetService(Type serviceType) in D:\a\_work\1\s\src\Core\src\MauiContext.cs:line 68
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[IApplication](IServiceProvider provider)
   at Microsoft.Maui.MauiApplication.OnCreate() in D:\a\_work\1\s\src\Core\src\Platform\Android\MauiApplication.cs:line 37
   at Android.App.Application.n_OnCreate(IntPtr jnienv, IntPtr native__this) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net8.0/android-34/mcw/Android.App.Application.cs:line 1086
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(_JniMarshal_PP_V callback, IntPtr jnienv, IntPtr klazz) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 22
```

**Comment by samhouts** [comment]
Paging @StephaneDelcroix !

**Comment by gabsamples6** [comment]
@samhouts @StephaneDelcroix  hi is there any remote chance of being fixed in the next release - To us is a showstopper we cannot move to .net 8 . Many thanks

**Comment by pjcollins** [comment]
I do see this crash using .NET 8.0 Preview 7, however I wasn't able to reproduce this on either Android or iOS using https://github.com/gabsamples6/SharedMauiXamlStylesLibrary and the latest from the net8.0 maui branch. The app launches without issue and I am able to navigate to the Button and TabView pages as well:

<img width="512" alt="Screenshot 2023-08-28 at 4 42 22 PM" src="https://github.com/dotnet/maui/assets/2000163/47519520-2307-424f-9d14-76d0cb51af42">

Hopefully the upcoming .NET 8.0 RC 1 release will unblock you.

**Comment by gabsamples6** [comment]
@pjcollins hi - glad to see that is already been fixed - Did you use the nightly build?

I have not done it before - would be able to tell me how you tested against branch so that I can test myself too against my actual real project? 
What do I need to change to reference the nightly build packages?

many thanks

**Comment by samhouts** [comment]
@gabsamples6 Take a look at https://github.com/dotnet/maui/wiki/Nightly-Builds! Thanks!
