### ISSUE TITLE
Some images are not shown on Windows

### ISSUE THREAD

**Issue by tsjdev-apps** [dotnet/maui#17054]
### Description

If I want to display an image directly from an URL, it will sometimes not shown on Windows. There are image URLs which are working aswell on Windows, but other images are not working. 

On Android everything works.

### Steps to Reproduce

1. Create a new .NET MAUI project
2. Add an `Image` tag to your XAML page
3. Insert as source a URL, like https://openweathermap.org/img/wn/10d@2x.png
4. Start the .NET MAUI app on Windows
5. The image is not shown

### Link to public reproduction project repository

https://github.com/tsjdev-apps/maui-issue-images

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.19041.0

### Did you find any workaround?

-

### Relevant log output

```shell
Microsoft.Maui.Controls.UriImageSource: Warning: Error getting stream for https://openweathermap.org/img/wn/10d@2x.png

System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed because the remote party sent a TLS alert: 'ProtocolVersion'.
 ---> System.ComponentModel.Win32Exception (0x80090326): The message received was unexpected or badly formatted.
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Microsoft.Maui.Controls.StreamWrapper.GetStreamAsync(Uri uri, CancellationToken cancellationToken, HttpClient client)
   at Microsoft.Maui.Controls.UriImageSource.DownloadStreamAsync(Uri uri, CancellationToken cancellationToken)
```

**Comment by lothrop** [comment]
One idea: The site you specified does not support TLS 1.2, only 1.3. Can you check with other sites? Use https://www.ssllabs.com/ssltest/ to check the server.

**Comment by mattleibow** [comment]
I tested this now with .NET 8 and it worked fine for me.

**Comment by mattleibow** [comment]
And I just tested on net7 and it works...

![image](https://github.com/dotnet/maui/assets/1096616/b3d4fb77-5c1e-4870-aa0e-0971696c4da0)

**Comment by mattleibow** [comment]
This is the host OS, so I will close this since .NET MAUI does not influence the running OS.
