### ISSUE TITLE
[Bug] Connection refused when calling ASP.NET Core API endpoints from .NET MAUI Blazor App

### ISSUE THREAD

**Issue by TanvirArjel** [dotnet/maui#1707]
The ASP.NET Core Web API app is up and running. Making requests to the API endpoints from Blazor Web Assembly works perfectly fine. Whenever making request from the **.NET MAUI Blazor App** it's throwing the following exception:

```C#
[DOTNET] System.Net.Http.HttpRequestException: Connection refused (localhost:44363)
[DOTNET]  ---> System.Net.Sockets.SocketException (111): Connection refused
[DOTNET]    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken 
[DOTNET] cancellationToken) in System.Net.Sockets.dll:token 0x60002b9+0x1f
[DOTNET]    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token) in System.Net.Sockets.dll:token 0x60002b3+0x26
[DOTNET]    at Syst
[DOTNET] em.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken) in System.Net.Sockets.dll:token 0x600029c+0xa4
[DOTNET]    at System.Net.Http.HttpConnectionP
[DOTNET] ool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken) in System.Net.Http.dll:token 0x6000700+0x1b4
[DOTNET]    --- End of inner exception stack trace ---
[DOTNET]    at System.Net.Http.HttpC
[DOTNET] onnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken) in System.Net.Http.dll:token 0x6000700+0x298
[DOTNET]    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpReque
[DOTNET] stMessage request, Boolean async, CancellationToken cancellationToken) in System.Net.Http.dll:token 0x60006ff+0x14d
[DOTNET]    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellati
[DOTNET] onToken) in System.Net.Http.dll:token 0x6000701+0x8f
[DOTNET]    at System.Net.Http.HttpConnectionPool.SendUsingHttp11Async(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken) in System.Net.Http.dll:token 0x60006f1
[DOTNET] +0x15d
[DOTNET]    at System.Net.Http.HttpConnectionPool.DetermineVersionAndSendAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken) in System.Net.Http.dll:token 0x60006f2+0x224
[DOTNET]    at System.Net.Http.HttpConne
[DOTNET] ctionPool.SendAndProcessAltSvcAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken) in System.Net.Http.dll:token 0x60006f3+0x8e
[DOTNET] ssage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken) in System.Net.Http.dll:token 0x60006f4+0x99
[DOTNET]    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequ07-16 12:39:49.024 I/DOTNET  (16085):    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationT
[DOTNET] oken) in System.Net.Http.dll:token 0x6000787+0x94
[DOTNET]    at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in Microsoft.Extensions.Http.dll:token 0x60000c3+0xd7
[DOTNET]    at MauiB
[DOTNET] lazor.Shared.Common.AuthorizationDelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in D:\GitHub\CleanArchitecture\src\ClientApps\MauiBlazor.Shared\Common\AuthorizationDelegatingHandler.cs:line 43
[DOTNET]    at Microsoft.E
[DOTNET] xtensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in Microsoft.Extensions.Http.dll:token 0x60000c8+0xef
[DOTNET] ge request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken) in System.Net.Http.dll:token 0x600022f+0x1b7
[DOTNET] lazor.Shared.Common.AuthorizationDelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in D:\GitHub\CleanArchitecture\src\ClientApps\MauiBlazor.Shared\Common\Authoriz07-16 12:39:49.025 I/DOTNET  (16085):    at MauiBlazor.Share
[DOTNET] d.Services.UserService.LoginAsync(LoginModel loginModel) in D:\GitHub\CleanArchitecture\src\ClientApps\MauiBlazor.Shared\Services\UserService.cs:line 132
[DOTNET]    at MauiBlazorApp.Components.IdentityComponents.LoginComponent.HandleValidSubmitAsync() in D:\GitHub
[DOTNET] \CleanArchitecture\src\ClientApps\MauiBlazorApp\MauiBlazorApp\Components\IdentityComponents\LoginComponent.razor.cs:line 51
```

There is no CORS issue because the API app is allowing any origin as follows:

```C#
services.AddCors(options =>
{
    options.AddPolicy(myAllowSpecificOrigins, builder =>
    {
        builder
        .AllowAnyHeader()
        .AllowAnyMethod()
        .AllowCredentials()
        .SetIsOriginAllowed(_ => true);
    });
});
```

**Please help me how can I overcome the issue so that I can make requests to the ASP.NET Core REST endpoints from .NET MAUI Blazor app successfully. Thanks in advance.**

**Comment by Eilon** [comment]
Hi @TanvirArjel can you share more info about this setup? Is it all on Windows, with .NET MAUI targeting WinUI, and the ASP.NET Core server is running locally on the same Windows machine?

**Comment by TanvirArjel** [comment]
@Eilon Here is the complete repo: https://github.com/TanvirArjel/CleanArchitecture

**Comment by Eilon** [comment]
BTW CORS shouldn't matter here because CORS applies only to _browsers_ making calls to a remote server. In this case it's a .NET Core app making a call, so CORS isn't a factor one way or another.

**Comment by Eilon** [comment]
The first thing that I can think of is some issue related to HTTP vs. HTTPS. Is everything consistently using HTTPS in this scenario?

**Comment by TanvirArjel** [comment]
@Eilon

> Is everything consistently using HTTPS in this scenario?

I think so. It would be great if you run the repository on your machine and test.

**Comment by Eilon** [comment]
@TanvirArjel in that case it will likely take a while for me to get to this because it could involve a lot of investigation. Ideally we have minimal repro projects for this so there are fewer possible problems.

**Comment by TanvirArjel** [comment]
@Eilon Okay! I shall provide a minimal repo soon.

**Comment by TanvirArjel** [comment]
@Eilon Here is the minimal repo to reproduce the issue: https://github.com/TanvirArjel/MauiDemo. After running both API and MAUI Blazor app in debug mode, please click on the FetchData menu and see the debug output.

This has been an irritating issue as this blocked my MAUI learning. Please let me know the update.

Thanks in advance.

**Comment by TanvirArjel** [comment]
@Eilon Could you please give me an update on this issue?

Thank you.

**Comment by Eilon** [comment]
Hi @TanvirArjel I updated your project to be compatible with preview7/RC1 and it seems to work just fine for me. First I started the ASP.NET Core server so that the API would run on port 44393 (using HTTPS), then I deployed the WinUI project and ran it from the Start Menu (there's a bug right now in VS where you can't run the WinUI app directly), and it was able to do the HttpClient call to get the weather forecast.

![image](https://user-images.githubusercontent.com/202643/130122374-4dd7824e-edbd-4f5c-b571-548b8b11146d.png)

You can see the changes I made to the app here: https://github.com/TanvirArjel/MauiDemo/pull/1

(I only changed things that changed in MAUI/Blazor/WinUI, I didn't change any app code.)

**Comment by TanvirArjel** [comment]
@Eilon Great to hear that. I shall test the same project and get back to you.

Thank you again.

**Comment by Eilon** [comment]
Do you know if you have the ASP.NET Core HTTPS developer certificate installed?

Check out this post from Scott Hanselman: https://www.hanselman.com/blog/developing-locally-with-aspnet-core-under-https-ssl-and-selfsigned-certs

You might need to run this command line tool: `dotnet dev-certs https --trust`

**Comment by TanvirArjel** [comment]
@Eilon I am getting the following error when running the MauiBlazorApp of the demo project after merging your update.

![image](https://user-images.githubusercontent.com/14342773/130182867-e7161db3-beda-4fdc-8b51-b4d1091b3d2a.png)

Here is the result of `maui-check` which shows everything is fine:

![image](https://user-images.githubusercontent.com/14342773/130182997-78d1be3a-08dc-455a-bf98-2f6701d71fdb.png)

**Comment by TanvirArjel** [comment]
@Eilon I see have only tested with MAUI Blazor Windows UI and **you did not check with MAUI Blazor Android** app. For windows UI its working fine but for the **MAUI Blazor Android it's not working and throwing the same error**:

![image](https://user-images.githubusercontent.com/14342773/130186470-e1956a30-cf84-489b-a17b-5b05c93fc24d.png)

**Comment by TanvirArjel** [comment]
@Eilon Please keep me updated after testing on your machine. This is a very crucial issue which blocked my MAUI development.

**Comment by Eilon** [comment]
Oh, I see. There's probably something that needs to be done in Android to make the cert trusted. The cert trust is done on the _client_, so when you run the command line tool, that makes Windows trust it. But Android is using a different cert store.

**Comment by Eilon** [comment]
OK I found the doc that discusses how to do this: https://docs.microsoft.com/xamarin/cross-platform/deploy-test/connect-to-local-web-services#bypass-the-certificate-security-check

You can do one of these:
1. Use HTTP (instead of HTTPS) during dev and local debugging, so there's no HTTPS certificate needed at all
2. Follow the steps in that doc to skip cert checking on HTTPS in your Android and iOS apps
3. Use an HTTPS cert that is already trusted (I think LetsEncrypt might work for this?)

**Comment by TanvirArjel** [comment]
@Eilon Thank you so much. Could you please update the demo project with option #2.

Thanks in advance.

**Comment by TanvirArjel** [comment]
@Eilon Is there any documentation on how to use LetsEncrypt in MAUI?

**Comment by Eilon** [comment]
The docs I pointed to include code samples for how to do option 2. If that doesn't work, please let me know.

I'm not sure of docs for LetsEncrypt, but it's a matter of using a LetsEncrypt cert in the ASP.NET Core app for SSL. Then the Android app I _think_ would automatically trust it, because the CA for LetsEncrypt is I think already trusted in Android. (This is far outside my area of expertise, so I'm not 100% on this.)

**Comment by TanvirArjel** [comment]
@Eilon Here is the test result:

>1. Use HTTP (instead of HTTPS) during dev and local debugging, so there's no HTTPS certificate needed at all

I have tried. Only works for Windows Ui but does not work for mobile apps and shows the same error.

> 2. Follow the steps in that doc to skip cert checking on HTTPS in your Android and iOS apps

I have tried as follows:

```C#
services.AddHttpClient("WeatherApi", c =>
{
    c.BaseAddress = new Uri("https://localhost:44393/");
    c.DefaultRequestHeaders.Add("Accept", "application/json");
    c.DefaultRequestHeaders.Add("User-Agent", "HttpClientFactory-Sample");
}).ConfigurePrimaryHttpMessageHandler(x => new HttpClientHandler()
{
    ServerCertificateCustomValidationCallback = (message, cert, chain, errors) =>
    {
        if (cert.Issuer.Equals("CN=localhost"))
        {
            return true;
        }

        return errors == System.Net.Security.SslPolicyErrors.None;
    }
});
```

only works for Windows Ui but does not work for mobile apps and shows the following error:

```C#
[chromium] [INFO:CONSOLE(1)] "Operation is not supported on this platform.
[chromium]    at System.Net.Http.HttpClientHandler.set_ServerCertificateCustomValidationCallback(Func`5 value) in System.Net.Http.dll:token 0x6000252+0x0
[chromium]    at MauiBlazorApp.Startup.<>c.<Configure>b__0_3(IServiceProvider x) in D:\MauiDemo\MauiBlazorApp\MauiBlazorApp\Startup.cs:line 37
[chromium]    at Microsoft.Extensions.DependencyInjection.HttpClientBuilderExtensions.<>c__DisplayClass6_0.<ConfigurePrimaryHttpMessageHandler>b__1(HttpMessageHandlerBuilder b) in Microsoft.Extensions.Http.dll:token 0x60000e6+0xd
[chromium]    at Microsoft.Extensions.Http.DefaultHttpClientFactory.<>c__DisplayClass17_0.<CreateHandlerEntry>g__Configure|0(HttpMessageHandlerBuilder b) in Microsoft.Extensions.Http.dll:token 0x6000110+0x15
[chromium]    at Microsoft.Extensions.Http.LoggingHttpMessageHandlerBuilderFilter.<>c__DisplayClass3_0.<Configure>b__0(HttpMessageHandlerBuilder builder) in Microsoft.Extensions.Http.dll:token 0x600011b+0x0
[chromium]    at Microsoft.Extensions.Http.DefaultHttpClientFactory.CreateHandlerEntry(String name) in Microsoft.Extensions.Http.dll:token 0x6000088+0xc0
[chromium]    at Microsoft.Extensions.Http.DefaultHttpClientFactory.<>c__DisplayClass14_0.<.ctor>b__1() in Microsoft.Extensions.Http.dll:token 0x600010e+0x0
[chromium]    at System.Lazy`1[[Microsoft.Extensions.Http.ActiveHandlerTrackingEntry, Microsoft.Extensions.Http, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].ViaFactory(LazyThreadSafetyMode mode) in System.Private.CoreLib.dll:token 0x600125c+0x43
[chromium]    at System.Lazy`1[[Microsoft.Extensions.Http.ActiveHandlerTrackingEntry, Microsoft.Extensions.Http, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor) in System.Private.CoreLib.dll:token 0x600125d+0x22
[chromium]    at System.Lazy`1[[Microsoft.Extensions.Http.ActiveHandlerTrackingEntry, Microsoft.Extensions.Http, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].CreateValue() in System.Private.CoreLib.dll:token 0x6001262+0x74
[chromium]    at System.Lazy`1[[Microsoft.Extensions.Http.ActiveHandlerTrackingEntry, Microsoft.Extensions.Http, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].get_Value() in System.Private.CoreLib.dll:token 0x6001268+0xa
[chromium]    at Microsoft.Extensions.Http.DefaultHttpClientFactory.CreateHandler(String name) in Microsoft.Extensions.Http.dll:token 0x6000087+0x20
[chromium]    at Microsoft.Extensions.Http.DefaultHttpClientFactory.CreateClient(String name) in Microsoft.Extensions.Http.dll:token 0x6000086+0xe
[chromium]    at MauiBlazorApp.Data.WeatherForecastService..ctor(IHttpClientFactory httpClientFactory) in D:\MauiDemo\MauiBlazorApp\MauiBlazorApp\Data\WeatherForecastService.cs:line 14
[chromium]    at System.Reflection.RuntimeConstructorInfo.InternalInvoke(Object obj, Object[] parameters, Boolean wrapExceptions) in System.Private.CoreLib.dll:token 0x6004f5b+0x20
[chromium]    at System.Reflection.RuntimeConstructorInfo.DoInvoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in System.Private.CoreLib.dll:token 0x6004f5a+0x86
[chromium]    at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in System.Private.CoreLib.dll:token 0x6004f5c+0x0
[chromium]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context) in Microsoft.Extensions.DependencyInjection.dll:token 0x600008d+0x45
[chromium]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSiteMain(ServiceCallSite callSite, RuntimeResolverContext argument) in Microsoft.Extensions.DependencyInjection.dll:token 0x60000a6+0x3f
[chromium]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context) in Microsoft.Extensions.DependencyInjection.dll:token 0x600008e+0x61
[chromium]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSite(ServiceCallSite callSite, RuntimeResolverContext argument) in Microsoft.Extensions.DependencyInjection.dll:token 0x60000a5+0x4e
[chromium]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope) in Microsoft.Extensions.DependencyInjection.dll:token 0x600008b+0x26
[chromium]    at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType) in Microsoft.Extensions.DependencyInjection.dll:token 0x6000068+0x4b
[chromium]    at System.Collections.Concurrent.ConcurrentDictionary`2[[System.Type, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Func`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope, Microsoft.Extensions.DependencyInjection, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].GetOrAdd(Type key, Func`2 valueFactory) in System.Collections.Concurrent.dll:token 0x60000d2+0x4f
[chromium]    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope) in Microsoft.Extensions.DependencyInjection.dll:token 0x6000066+0xd
[chromium]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType) in Microsoft.Extensions.DependencyInjection.dll:token 0x600010b+0x13
[chromium]    at Microsoft.AspNetCore.Components.ComponentFactory.<>c__DisplayClass7_0.<CreateInitializer>g__Initialize|1(IServiceProvider serviceProvider, IComponent component) in Microsoft.AspNetCore.Components.dll:token 0x60003c5+0x18
[chromium]    at Microsoft.AspNetCore.Components.ComponentFactory.PerformPropertyInjection(IServiceProvider serviceProvider, IComponent instance) in Microsoft.AspNetCore.Components.dll:token 0x60000ac+0x2d
[chromium]    at Microsoft.AspNetCore.Components.ComponentFactory.InstantiateComponent(IServiceProvider serviceProvider, Type componentType) in Microsoft.AspNetCore.Components.dll:token 0x60000ab+0x2b
[chromium]    at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateComponent(Type componentType) in Microsoft.AspNetCore.Components.dll:token 0x6000268+0x0
[chromium]    at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateChildComponentOnFrame(RenderTreeFrame& frame, Int32 parentComponentId) in Microsoft.AspNetCore.Components.dll:token 0x6000274+0x69
[chromium]    at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(DiffContext& diffContext, Int32 frameIndex) in Microsoft.AspNetCore.Components.dll:token 0x60002a3+0x29
[chromium]    at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& diffContext, Int32 frameIndex) in Microsoft.AspNetCore.Components.dll:token 0x60002a2+0x49
[chromium]    at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex) in Microsoft.AspNetCore.Components.dll:token 0x600029e+0x74
[chromium]    at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForFramesWithSameSequence(DiffContext& diffContext, Int32 oldFrameIndex, Int32 newFrameIndex) in Microsoft.AspNetCore.Components.dll:token 0x600029c+0x21c
[chromium]    at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl) in Microsoft.AspNetCore.Components.dll:token 0x6000294+0x22b
[chromium]    at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForFramesWithSameSequence(DiffContext& diffContext, Int32 oldFrameIndex, Int32 newFrameIndex) in Microsoft.AspNetCore.Components.dll:token 0x600029c+0x1d1
[chromium]    at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl) in Microsoft.AspNetCore.Components.dll:token 0x6000294+0x22b
[chromium]    at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForFramesWithSameSequence(DiffContext& diffContext, Int32 oldFrameIndex, Int32 newFrameIndex) in Microsoft.AspNetCore.Components.dll:token 0x600029c+0x197
[chromium]    at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl) in Microsoft.AspNetCore.Components.dll:token 0x6000294+0x22b
[chromium]    at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForFramesWithSameSequence(DiffContext& diffContext, Int32 oldFrameIndex, Int32 newFrameIndex) in Microsoft.AspNetCore.Components.dll:token 0x600029c+0x197
[chromium]    at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl) in Microsoft.AspNetCore.Components.dll:token 0x6000294+0x22b
[chromium]    at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree) in Microsoft.AspNetCore.Components.dll:token 0x6000292+0x25
[chromium]    at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException) in Microsoft.AspNetCore.Components.dll:token 0x600030a+0x7e
[chromium]    at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry) in Microsoft.AspNetCore.Components.dll:token 0x6000282+0x13
[chromium]    at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue() in Microsoft.AspNetCore.Components.dll:token 0x600027e+0x6d", source: https://0.0.0.0/_framework/blazor.webview.js (1)
```

**Comment by TanvirArjel** [comment]
@Eilon Did you take a look at this?

Thanks in advance.

**Comment by AmSmart** [comment]
I don't have the VS2022 preview installed and I don't plan to install it soon, hence I can't really run MAUI apps yet. Since you're getting a 400, I'd advise you to debug it on the Server Side (Weather App), find out the content of the request was sent from the Android app that led to a server-side error. That'll give more clarity to discovering the bug. 

Happy Coding!

**Comment by Eilon** [comment]
@TanvirArjel if you set up verbose logging on the ASP.NET Core app, can you see the request coming in from the Android emulator? As @AmSmart says, the fact that it's an HTTP 400 implies that the server is receiving the HTTP request, but thinks that the client sent a bad request. If you can see from the server what it thinks the request is or what's wrong with it, that could lead us to the answer.

**Comment by TanvirArjel** [comment]
@Eilon I shall give try once .NET 6.0 RC-1 is released. .NET 6.0 preview 7 has so many issues.

**Comment by Eilon** [comment]
Sounds good, it should be out very soon!

**Comment by TanvirArjel** [comment]
@Eilon, I have tested again after updating to .NET 6.0 RC 1. The same old error. I have enabled log level to `Trace` for the API app but does not show anything.

I am requesting you run this (https://github.com/TanvirArjel/MauiDemo) minimal repo on your machine and identify the issue.

**Note: Request to the API app from every other source like POSTMAN, Fiddler, Windows App works perfectly fine but don't work from the MAUI android app.**

I am pretty sure this is related to the IIS Express and android emulator config issue.

**Comment by Eilon** [comment]
I can reproduce this locally but it's even weirder the more I looked into it.

Here's my setup:

1. ASP.NET Core Web API that is configured for SSL using the HTTP local dev cert
   * 100% default ASP.NET Core Web API listening on `https://localhost:7201/WeatherForecast`
2. .NET MAUI project (nothing to do with Blazor) that runs on Windows, Android, etc.
3. And for comparison, I also created a default Xamarin Android app and added NuGet package `<PackageReference Include="System.Net.Http"><Version>4.3.4</Version></PackageReference>`

In (2) and (3) I added the following code in some event handler (e.g. button click, etc.):

```c#
#if ANDROID
		HttpClientHandler handler = new HttpClientHandler();
		handler.ServerCertificateCustomValidationCallback = (message, cert, chain, errors) =>
		{
			if (cert.Issuer.Equals("CN=localhost"))
				return true;
			return errors == System.Net.Security.SslPolicyErrors.None;
		};
		var h = new HttpClient(handler);
		var r = await h.GetAsync("https://10.0.2.2:7201/WeatherForecast");
#endif
```

And in .NET MAUI I used the same code for Windows, but instead of `10.0.2.2` on Android (used to connect to the emulator host), I used `localhost`, because it's running on the same machine.

On .NET MAUI **Windows** and Xamarin Android, the `ServerCertificateCustomValidationCallback` was called, and correctly matched the issuer, and returned `true` to bypass SSL checks.

On .NET MAUI **Android**, the `ServerCertificateCustomValidationCallback` was not called _at all_ and you get a Java error `CertPathValidatorException: Trust anchor for certification path not found.'` (which makes sense, given that the SSL check was not bypassed).

I have no idea why `ServerCertificateCustomValidationCallback` was not called in .NET MAUI **Android** because it's supposedly supported there per issues such as https://github.com/xamarin/xamarin-android/issues/3682 and https://github.com/dotnet/runtime/issues/57537.

**Comment by Eilon** [comment]
@jonathanpeppers - any thoughts on where this bug should go? Per my previous comment, I suspect maybe to https://github.com/xamarin/xamarin-android ?

**Comment by jonathanpeppers** [comment]
If you use `AndroidMessageHandler` in .NET 6 instead of `HttpClientHandler`, does the problem go away? I believe this is the preferred handler that properly implements SSL on Android. If you use the empty constructor for `HttpClient`, it should also use `AndroidMessageHandler`.

If a fix is needed for `HttpClientHandler`, we can probably move this to dotnet/runtime?

**Comment by Eilon** [comment]
With this code:

```		HttpClientHandler handler = new HttpClientHandler();
		handler.ServerCertificateCustomValidationCallback = (message, cert, chain, errors) =>
		{
			if (cert.Issuer.Equals("CN=localhost"))
				return true;
			return errors == System.Net.Security.SslPolicyErrors.None;
		};
		var h = new HttpClient(handler);
```

I get `CertPathValidatorException: Trust anchor for certification path not found.`.

With this code:

```c#
		var handler = new Xamarin.Android.Net.AndroidMessageHandler();
		handler.ServerCertificateCustomValidationCallback = (message, cert, chain, errors) =>
		{
			if (cert.Issuer.Equals("CN=localhost"))
				return true;
			return errors == System.Net.Security.SslPolicyErrors.None;
		};
		var h = new HttpClient(handler);
		var r = await h.GetAsync("https://10.0.2.2:7201/WeatherForecast");
```

I get the same `CertPathValidatorException: Trust anchor for certification path not found.`.

I don't believe I can use the parameterless `HttpClient` because to use an "untrusted" SSL cert (e.g. the local HTTP dev cert) I have to wire up the event handler to skip cert validation.
