### ISSUE TITLE
.Net C# Maui 6 Release Mode Crash  "ZIndex"

### ISSUE THREAD

**Issue by krirkGenerwiz0137** [dotnet/maui#17245]
### Description

Debug Mode is Work OK.
Release Mode is Crash    ZIndex 
Example code 

Frame ZIndex="9" BackgroundColor="White" BorderColor="Transparent" CornerRadius="10" HasShadow="True" Margin="12,-70,12,0" Padding="0" HeightRequest="170"
                
and What ZIndex work fine in Maui ?          
i try to use ZIndex 1-10  and in not happen.

### Steps to Reproduce

<Frame ZIndex="9" Grid.Row="2" Grid.ColumnSpan="2" BackgroundColor="Transparent" BorderColor="Transparent" CornerRadius="10" Padding="10,5,10,5" >
</Frame>

Run in Debug Good 
Run in Release Crash 

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Did you find any workaround?

android.runtime.JavaProxyThrowable: System.Reflection.TargetInvocationException: Arg_TargetInvocationException
 ---> System.FieldAccessException: Field `Microsoft.Maui.Controls.VisualElement:ZIndexProperty' is inaccessible from method `APPL.Views.HomePage:InitializeComponent ()'

   at APPL.Views.HomePage..ctor()
   at System.Reflection.RuntimeConstructorInfo.InternalInvoke(Object , Object[] , Boolean )
   Exception_EndOfInnerExceptionStack
   at System.Reflection.RuntimeConstructorInfo.InternalInvoke(Object , Object[] , Boolean )
   at System.RuntimeType.CreateInstanceMono(Boolean , Boolean )
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean , Boolean )
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at Microsoft.Maui.Controls.ShellContent.<>c__DisplayClass19_0.<Microsoft.Maui.Controls.IShellContentController.GetOrCreateContent>b__0()
   at Microsoft.Maui.Controls.ElementTemplate.CreateContent()
   at Microsoft.Maui.Controls.Internals.DataTemplateExtensions.CreateContent(DataTemplate self, Object item, BindableObject container)
   at Microsoft.Maui.Controls.ShellContent.Microsoft.Maui.Controls.IShellContentController.GetOrCreateContent()
   at Microsoft.Maui.Controls.Platform.Compatibility.ShellSectionRenderer.OnCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState)
   at AndroidX.Fragment.App.Fragment.n_OnCreateView_Landroid_view_LayoutInflater_Landroid_view_ViewGroup_Landroid_os_Bundle_(IntPtr , IntPtr , IntPtr , IntPtr , IntPtr )
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPLLL_L(_JniMarshal_PPLLL_L , IntPtr , IntPtr , IntPtr , IntPtr , IntPtr )
 at crc640ec207abc449b2ca.ShellSectionRenderer.n_onCreateView(Native Method)
 at crc640ec207abc449b2ca.ShellSectionRenderer.onCreateView(ShellSectionRenderer.java:42)
 at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2995)
 at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:523)
 at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
 at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1840)
 at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1764)
 at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1701)
 at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2849)
 at androidx.fragment.app.FragmentManager.dispatchViewCreated(FragmentManager.java:2777)
 at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3020)
 at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:551)
 at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
 at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1840)
 at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1764)
 at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1701)
 at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:488)
 at android.os.Handler.handleCallback(Handler.java:942)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loopOnce(Looper.java:211)
 at android.os.Looper.loop(Looper.java:300)
 at android.app.ActivityThread.main(ActivityThread.java:8296)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

### Relevant log output

```shell
android.runtime.JavaProxyThrowable: System.Reflection.TargetInvocationException: Arg_TargetInvocationException
 ---> System.FieldAccessException: Field `Microsoft.Maui.Controls.VisualElement:ZIndexProperty' is inaccessible from method `APPL.Views.HomePage:InitializeComponent ()'

   at APPL.Views.HomePage..ctor()
   at System.Reflection.RuntimeConstructorInfo.InternalInvoke(Object , Object[] , Boolean )
   Exception_EndOfInnerExceptionStack
   at System.Reflection.RuntimeConstructorInfo.InternalInvoke(Object , Object[] , Boolean )
   at System.RuntimeType.CreateInstanceMono(Boolean , Boolean )
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean , Boolean )
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at Microsoft.Maui.Controls.ShellContent.<>c__DisplayClass19_0.<Microsoft.Maui.Controls.IShellContentController.GetOrCreateContent>b__0()
   at Microsoft.Maui.Controls.ElementTemplate.CreateContent()
   at Microsoft.Maui.Controls.Internals.DataTemplateExtensions.CreateContent(DataTemplate self, Object item, BindableObject container)
   at Microsoft.Maui.Controls.ShellContent.Microsoft.Maui.Controls.IShellContentController.GetOrCreateContent()
   at Microsoft.Maui.Controls.Platform.Compatibility.ShellSectionRenderer.OnCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState)
   at AndroidX.Fragment.App.Fragment.n_OnCreateView_Landroid_view_LayoutInflater_Landroid_view_ViewGroup_Landroid_os_Bundle_(IntPtr , IntPtr , IntPtr , IntPtr , IntPtr )
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPLLL_L(_JniMarshal_PPLLL_L , IntPtr , IntPtr , IntPtr , IntPtr , IntPtr )
 at crc640ec207abc449b2ca.ShellSectionRenderer.n_onCreateView(Native Method)
 at crc640ec207abc449b2ca.ShellSectionRenderer.onCreateView(ShellSectionRenderer.java:42)
 at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2995)
 at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:523)
 at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
 at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1840)
 at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1764)
 at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1701)
 at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2849)
 at androidx.fragment.app.FragmentManager.dispatchViewCreated(FragmentManager.java:2777)
 at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3020)
 at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:551)
 at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
 at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1840)
 at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1764)
 at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1701)
 at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:488)
 at android.os.Handler.handleCallback(Handler.java:942)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loopOnce(Looper.java:211)
 at android.os.Looper.loop(Looper.java:300)
 at android.app.ActivityThread.main(ActivityThread.java:8296)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
```

**Comment by drasticactions** [comment]
Does that happen when running on net7.0 or the net8.0 previews? Also, do you have an example project showing this?
