### ISSUE TITLE
[Bug] vs2022 Debug throw Font not found /data/data/com.companyname.SampleApp/cache/OpenSans-Regular.ttf

### ISSUE THREAD

**Issue by jingliancui** [dotnet/maui#1727]
### Description
Use VS2022 preview debug the maui p6 app,it will throw exception said  
`Font not found /data/data/com.companyname.SampleApp/cache/OpenSans-Regular.ttf`

### Steps to Reproduce

1. cli new a project `dotnet new maui -n SampleApp`
2. open the .sln file with VS2022
3. Debug the project to the device.

### Expected Behavior
app run 

### Actual Behavior
app crash

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
```
Microsoft Visual Studio Community 2022 Preview
Version 17.0.0 Preview 2.0
VisualStudio.17.Preview/17.0.0-pre.2.0+31512.422
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Community

Azure App Service Tools v3.0.0   17.0.303.37752
Azure App Service Tools v3.0.0

C# Tools   4.0.0-2.21362.3+5f7ddf6f02d40036fdbf823cd9910027da277acd
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Mono Debugging for Visual Studio   17.0.4 (62dd685)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   6.0.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Visual Basic Tools   4.0.0-2.21362.3+5f7ddf6f02d40036fdbf823cd9910027da277acd
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.0.0-beta.21352.5+3af67cd8ffd73b2dc443e1e24dc0cf28f7e1c608
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   17.0.0.68 (main@8be0e08)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.0.0.19 (remotes/origin/38ad4805f43a9ae53ab6f12d9cd60d08750c49bd@38ad4805f)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   17.0.2 (6fd52a2)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.3.99.54 (main/0e5e06f)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: c633fe9
    Java.Interop: xamarin/java.interop/main@a5ed891
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.35.4@85460d3
    Xamarin.Android Tools: xamarin/xamarin-android-tools/main@683f375


Xamarin.iOS and Xamarin.Mac SDK   14.99.0.2 (dd5f9f7b6)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

### Exception info
```
[mono-rt] 	at android.os.Handler.dispatchMessage(Handler.jav07-17 16:23:08.857 F/mono-rt (15890): java.lang.RuntimeException: Font not found /data/data/com.companyname.SampleApp/cache/OpenSans-Regular.ttf
[mono-rt] 	at android.graphics.Typeface.createFromFile(Typeface.java:217)
[mono-rt] 	at crc6488302ad6e9e4df1a.MauiAppCompatActivity.n_onCreate(Native Method)
[mono-rt] 	at crc6488302ad6e9e4df1a.MauiAppCompatActivity.onCreate(MauiAppCompatActivity.java:46)
[mono-rt] 	at android.app.Activity.performCreate(Activity.java:6034)
[mono-rt] 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1111)
[mono-rt] 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2442)
[mono-rt] 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2551)
[mono-rt] 	at android.app.ActivityThread.access$1000(ActivityThread.java:169)
[mono-rt] 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1432)
[mono-rt] 	at android.os.Handler.dispatchMessage(Handler.java:111)
[mono-rt] 	at android.os.Looper.loop(Looper.java:194)
[mono-rt] 	at android.app.ActivityThread.main(ActivityThread.java:5581)
[mono-rt] 	at java.lang.reflect.Method.invoke(Native Method)
[mono-rt] 	at java.lang.reflect.Method.invoke(Method.java:372)
[mono-rt] 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:968)
[mono-rt] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:763)
[mono-rt] 

```

**Comment by Redth** [comment]
We believe this is fixed in upcoming preview release.

If you find it still to be an issue, please file a new bug.
