### ISSUE TITLE
Apply bindings once for ItemTemplate

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#17349]
### Description

The process of setting the BindingContext on cells of any list element goes as follows

```C#
createdCell.BindingContext = item
collectionView?.AddLogicalChild(_visualElement);
```

We do it in this order so that the BC of collectionViewdoesn't propagate to the createdCell, but this causes the bindings to all get applied twice due to this code.

[maui/src/Controls/src/Core/Element/Element.cs at d4d86c2f224cfde2f35cb12e61ef76190cc8ce3f · dotnet/maui (github.com)](https://github.com/dotnet/maui/blob/d4d86c2f224cfde2f35cb12e61ef76190cc8ce3f/src/Controls/src/Core/Element/Element.cs#L527)

 
is there a way to handle this flow so that the bindings only get applied once?
Can we Add the logical child and set the binding all as one atomic operation? We have a lot of places in code that have this particular workflow so it would be ideal if we would just standardize this workflow. 

### reproduction

`CollectionViewGalleries.OnlineImages` in our controls gallery

There is an issue with the current implementation of `ItemsContentControl.Realize()` which ends up applying bindings twice when creating an item. Normally that would go unnoticed, but it has a major drawback in combination with `UriImageSource`. It starts fetching the image using `HttpClient` and then cancels the request, because a second request is started. That cancellation shows up as exceptions in the debug output, and the UI is noticeably sluggish. Exceptions are an expensive feature (mostly due to traversing the stack and building a stack trace).

### Debug log for sample application
Copied notes from [here](https://github.com/dotnet/maui/pull/10999)
I've added a page in the sample application do demonstrate the exceptions being thrown. The page contains a CollectionView with 5 items and the following ItemTemplate.

``` xml
<DataTemplate x:DataType="collectionviewgalleries:OnlineImageInfo">
     <Image HeightRequest="200" WidthRequest="200"  Source="{Binding Uri}" />
</DataTemplate>
```

```
Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in System.Private.CoreLib.dll
Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in System.Private.CoreLib.dll
Microsoft.Maui.Controls.UriImageSource: Warning: Error getting stream for https://news.microsoft.com/wp-content/uploads/prod/2022/07/hexagon_print.gif

System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Microsoft.Maui.Controls.StreamWrapper.GetStreamAsync(Uri uri, CancellationToken cancellationToken, HttpClient client)
   at Microsoft.Maui.Controls.UriImageSource.DownloadStreamAsync(Uri uri, CancellationToken cancellationToken)
Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in System.Private.CoreLib.dll
Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in System.Private.CoreLib.dll
Microsoft.Maui.Controls.UriImageSource: Warning: Error getting stream for https://news.microsoft.com/wp-content/uploads/prod/2022/07/collaboration-controls-in-power-platform_print.gif

System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Microsoft.Maui.Controls.StreamWrapper.GetStreamAsync(Uri uri, CancellationToken cancellationToken, HttpClient client)
   at Microsoft.Maui.Controls.UriImageSource.DownloadStreamAsync(Uri uri, CancellationToken cancellationToken)
Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in System.Private.CoreLib.dll
Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in System.Private.CoreLib.dll
Microsoft.Maui.Controls.UriImageSource: Warning: Error getting stream for https://news.microsoft.com/wp-content/uploads/prod/2022/07/Updatesin-Teams.png

System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Microsoft.Maui.Controls.StreamWrapper.GetStreamAsync(Uri uri, CancellationToken cancellationToken, HttpClient client)
   at Microsoft.Maui.Controls.UriImageSource.DownloadStreamAsync(Uri uri, CancellationToken cancellationToken)
Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in System.Private.CoreLib.dll
Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in System.Private.CoreLib.dll
Microsoft.Maui.Controls.UriImageSource: Warning: Error getting stream for https://news.microsoft.com/wp-content/uploads/prod/2022/07/Expanded-Reactions.png

System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Microsoft.Maui.Controls.StreamWrapper.GetStreamAsync(Uri uri, CancellationToken cancellationToken, HttpClient client)
   at Microsoft.Maui.Controls.UriImageSource.DownloadStreamAsync(Uri uri, CancellationToken cancellationToken)
Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in System.Private.CoreLib.dll
Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in System.Private.CoreLib.dll
Microsoft.Maui.Controls.UriImageSource: Warning: Error getting stream for https://news.microsoft.com/wp-content/uploads/prod/2022/04/Companion-Devices.jpg

System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Microsoft.Maui.Controls.StreamWrapper.GetStreamAsync(Uri uri, CancellationToken cancellationToken, HttpClient client)
   at Microsoft.Maui.Controls.UriImageSource.DownloadStreamAsync(Uri uri, CancellationToken cancellationToken)
Exception thrown: 'System.InvalidOperationException' in Microsoft.Maui.dll
Microsoft.Maui.UriImageSourceService: Warning: Unable to load image URI 'https://news.microsoft.com/wp-content/uploads/prod/2022/07/hexagon_print.gif'.

System.InvalidOperationException: Unable to load image stream.
   at Microsoft.Maui.UriImageSourceService.GetImageSourceAsync(IUriImageSource imageSource, Single scale, CancellationToken cancellationToken)
Exception thrown: 'System.InvalidOperationException' in Microsoft.Maui.dll
Exception thrown: 'System.InvalidOperationException' in System.Private.CoreLib.dll
Exception thrown: 'System.InvalidOperationException' in Microsoft.Maui.dll
Microsoft.Maui.UriImageSourceService: Warning: Unable to load image URI 'https://news.microsoft.com/wp-content/uploads/prod/2022/07/collaboration-controls-in-power-platform_print.gif'.

System.InvalidOperationException: Unable to load image stream.
   at Microsoft.Maui.UriImageSourceService.GetImageSourceAsync(IUriImageSource imageSource, Single scale, CancellationToken cancellationToken)
Exception thrown: 'System.InvalidOperationException' in Microsoft.Maui.dll
Exception thrown: 'System.InvalidOperationException' in System.Private.CoreLib.dll
Exception thrown: 'System.InvalidOperationException' in Microsoft.Maui.dll
Microsoft.Maui.UriImageSourceService: Warning: Unable to load image URI 'https://news.microsoft.com/wp-content/uploads/prod/2022/07/Updatesin-Teams.png'.

System.InvalidOperationException: Unable to load image stream.
   at Microsoft.Maui.UriImageSourceService.GetImageSourceAsync(IUriImageSource imageSource, Single scale, CancellationToken cancellationToken)
Exception thrown: 'System.InvalidOperationException' in Microsoft.Maui.dll
Exception thrown: 'System.InvalidOperationException' in System.Private.CoreLib.dll
Exception thrown: 'System.InvalidOperationException' in Microsoft.Maui.dll
Microsoft.Maui.UriImageSourceService: Warning: Unable to load image URI 'https://news.microsoft.com/wp-content/uploads/prod/2022/07/Expanded-Reactions.png'.

System.InvalidOperationException: Unable to load image stream.
   at Microsoft.Maui.UriImageSourceService.GetImageSourceAsync(IUriImageSource imageSource, Single scale, CancellationToken cancellationToken)
Exception thrown: 'System.InvalidOperationException' in Microsoft.Maui.dll
Exception thrown: 'System.InvalidOperationException' in System.Private.CoreLib.dll
Exception thrown: 'System.InvalidOperationException' in Microsoft.Maui.dll
Microsoft.Maui.UriImageSourceService: Warning: Unable to load image URI 'https://news.microsoft.com/wp-content/uploads/prod/2022/04/Companion-Devices.jpg'.

System.InvalidOperationException: Unable to load image stream.
   at Microsoft.Maui.UriImageSourceService.GetImageSourceAsync(IUriImageSource imageSource, Single scale, CancellationToken cancellationToken)
Exception thrown: 'System.InvalidOperationException' in Microsoft.Maui.dll
Exception thrown: 'System.InvalidOperationException' in System.Private.CoreLib.dll
```

### Code fix

Callstack first call to ImageHandler.MapSource()
![image](https://user-images.githubusercontent.com/4621581/198885402-feaffbd7-9a7a-4676-b426-f72e946b0665.png)

Callstack second call to ImageHandler.MapSource() which cancel the first one
![image](https://user-images.githubusercontent.com/4621581/198885422-1c872ab1-b4eb-4f79-a2b1-070aa3a8396f.png)

Image request cancellation is handled in `ImageSourceServiceResultManager.BeginLoad()` and above is the two different code paths that trigger `BeginLoad()`, both originating from `ItemsContentControl.Realize()`. `ViewExtensions.ToHandler()` and `ItemsView.AddLogicalChild` will both apply bindings. The code fix is as simple as setting the `BindingContext` after those two calls.

> NOTE: The sample application page has no value after verification of this issue, and should be removed before merge.

**Comment by Vroomer** [comment]
@PureWeen Does this mean that Bindings take twice more time to get resolved? Because in that case it would have huge performance implication for more complex ItemTemplates.

**Comment by PureWeen** [comment]
Hard to say, we actively measure areas of performance issues and then address them. If you have a scenario that's performing slowly and looks related to this then post a repro

You can also measure via
https://github.com/dotnet/maui/wiki/Profiling-.NET-MAUI-Apps#feature-xyz-was-faster-in-xamarinforms
