### ISSUE TITLE
Not able to add a frame in grid via c# code.

### ISSUE THREAD

**Issue by PrayagMisal** [dotnet/maui#17346]
### Description

I'm kind of experimenting with grid and frame. It is kind of schedular control. I'm trying to add customized frame and it works only 1 or 2 times after that if I try then I receive below error....

**Message**
index=59 count=57

**Stack trace**
   at Java.Interop.JniEnvironment.InstanceMethods.CallNonvirtualVoidMethod(JniObjectReference instance, JniObjectReference type, JniMethodInfo method, JniArgumentValue* args) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/obj/Release/net7.0/JniEnvironment.g.cs:line 12324
   at Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualVoidMethod(String encodedMember, IJavaPeerable self, JniArgumentValue* parameters) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:line 75
   at Android.Views.ViewGroup.AddView(View child, Int32 index) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net7.0/android-33/mcw/Android.Views.ViewGroup.cs:line 2065
   at Microsoft.Maui.Handlers.LayoutHandler.Add(IView child) in D:\a\_work\1\s\src\Core\src\Handlers\Layout\LayoutHandler.Android.cs:line 54
   at Microsoft.Maui.Handlers.LayoutHandler.MapAdd(ILayoutHandler handler, ILayout layout, Object arg) in D:\a\_work\1\s\src\Core\src\Handlers\Layout\LayoutHandler.cs:line 69
   at Microsoft.Maui.CommandMapper`2.<>c__DisplayClass6_0[[Microsoft.Maui.ILayout, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.ILayoutHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v, Object o) in D:\a\_work\1\s\src\Core\src\CommandMapper.cs:line 92
   at Microsoft.Maui.CommandMapper.InvokeCore(String key, IElementHandler viewHandler, IElement virtualView, Object args) in D:\a\_work\1\s\src\Core\src\CommandMapper.cs:line 33
   at Microsoft.Maui.CommandMapper.Invoke(IElementHandler viewHandler, IElement virtualView, String property, Object args) in D:\a\_work\1\s\src\Core\src\CommandMapper.cs:line 51
   at Microsoft.Maui.Handlers.ElementHandler.Invoke(String command, Object args) in D:\a\_work\1\s\src\Core\src\Handlers\Element\ElementHandler.cs:line 95
   at Microsoft.Maui.Controls.Layout.NotifyHandler(String action, Int32 index, IView view) in D:\a\_work\1\s\src\Controls\src\Core\Layout\Layout.cs:line 266
   at Microsoft.Maui.Controls.Layout.OnAdd(Int32 index, IView view) in D:\a\_work\1\s\src\Controls\src\Core\Layout\Layout.cs:line 213
   at Microsoft.Maui.Controls.Grid.OnAdd(Int32 index, IView view) in D:\a\_work\1\s\src\Controls\src\Core\Layout\Grid.cs:line 280
   at Microsoft.Maui.Controls.Layout.Add(IView child) in D:\a\_work\1\s\src\Controls\src\Core\Layout\Layout.cs:line 138
   at CustomSchedularControl.Controls.CustomSchedular.CustomSchedularControl.AdjustSchedularItem(SchedularItemModel schedularItemModel) in C:\Xamarin_Development\CustomSchedularControl\Controls\CustomSchedular\CustomSchedularControl.xaml.cs:line 225
  --- End of managed Java.Lang.IndexOutOfBoundsException stack trace ---
java.lang.IndexOutOfBoundsException: index=59 count=57
	at android.view.ViewGroup.addInArray(ViewGroup.java:5376)
	at android.view.ViewGroup.addViewInner(ViewGroup.java:5269)
	at android.view.ViewGroup.addView(ViewGroup.java:5076)
	at android.view.ViewGroup.addView(ViewGroup.java:5016)
	at crc64fcf28c0e24b4cc31.ButtonHandler_ButtonClickListener.n_onClick(Native Method)
	at crc64fcf28c0e24b4cc31.ButtonHandler_ButtonClickListener.onClick(ButtonHandler_ButtonClickListener.java:31)
	at android.view.View.performClick(View.java:7455)
	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1219)
	at android.view.View.performClickInternal(View.java:7432)
	at android.view.View.access$3700(View.java:835)
	at android.view.View$PerformClick.run(View.java:28810)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7842)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

Sample can be find in below link:
https://github.com/PrayagMisal/CustomSchedularControl

File : CusomSchedularControl/Controls/CustomSchedular/CustomSchedularControl.xaml.cs
Line number : 231 (In the catch block of AdjustSchedularItem method)

### Steps to Reproduce

1) Run the app demo page will appear.
2) Tap on 'Open schedular page' button. Home page with custom created schedular control will appear with two buttons at bottom **Add** and **Remove**
3) Tap on **Add** button. A popup will appear to add a schedular item.
4) Fill up all required fields.
5) Tap on add button 

By following above steps 2-3 times issue can be reproduced.

### Link to public reproduction project repository

https://github.com/PrayagMisal/CustomSchedularControl

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12.1

**Comment by PrayagMisal** [comment]
There was exception in another function, it was getting called periodically...
Exception was in **AddCurrentTimeLine** method.
