### ISSUE TITLE
[regression/8.0.0-preview.7.8842] `ArgumentException` on OnPropertyChanged

### ISSUE THREAD

**Issue by daltzctr** [dotnet/maui#17357]
### Description

Going from .NET 8 Preview 6 -> RC 1 I've observed the following issue on **one** of my ViewModels. 

I have a `IsBlinking` property that calls `OnPropertyChanged` from [.NET Community Toolkit](https://github.com/CommunityToolkit/dotnet) MVVM. Whenever `OnPropertyChanged` gets called, it throws the following stacktrace.

```
 System.ArgumentException: An item with the same key has already been added. Key: Microsoft.Maui.Controls.SetterSpecificity (Parameter 'key')
   at System.Collections.Generic.SortedList`2.Add(TKey key, TValue value)
   at Microsoft.Maui.Controls.BindableObject.SetBinding(BindableProperty targetProperty, BindingBase binding, SetterSpecificity specificity)
   at Microsoft.Maui.Controls.Setter.Apply(BindableObject target, SetterSpecificity specificity)
   at Microsoft.Maui.Controls.TriggerBase.OnConditionChanged(BindableObject bindable, Boolean oldValue, Boolean newValue)
   at Microsoft.Maui.Controls.BindingCondition.OnBoundPropertyChanged(BindableObject bindable, Object oldValue, Object newValue)
   at Microsoft.Maui.Controls.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, SetterSpecificity specificity, Boolean silent)
   at Microsoft.Maui.Controls.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes, SetterSpecificity specificity)
   at Microsoft.Maui.Controls.BindingExpression.Apply(Boolean fromTarget)
   at Microsoft.Maui.Controls.BindingExpression.BindingExpressionPart.<PropertyChanged>b__50_0()
   at Microsoft.Maui.Controls.DispatcherExtensions.DispatchIfRequired(IDispatcher dispatcher, Action action)
   at Microsoft.Maui.Controls.BindingExpression.WeakPropertyChangedProxy.OnPropertyChanged(Object sender, PropertyChangedEventArgs e)
   at CommunityToolkit.Mvvm.ComponentModel.ObservableObject.OnPropertyChanged(String propertyName)
   ```
   
   Unfortunately, I can't easily reproduce this in a sample project, but the problem resolves itself when downgrading back to Preview 6. 

### Version with bug

[8.0.0-preview.7.8842](https://github.com/dotnet/maui/releases/tag/8.0.0-preview.7.8842)

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.0-preview.6.8686

### Affected platforms

Windows

### Did you find any workaround?

Wrap in try/catch?

**Comment by samhouts** [comment]
Unable to reproduce without a project, but the stack trace implicates https://github.com/dotnet/maui/issues/13818.

**Comment by StephaneDelcroix** [comment]
I think it happens when you apply a style for which one of the setter is a Binding. it's an easy fix, but harder to come up with a unit test
