### ISSUE TITLE
[regression/8.0.0] MAUI crashing on CarouselView render/remove, flyout menu

### ISSUE THREAD

**Issue by npostma** [dotnet/maui#17396]
### Description

I am currently in the process of porting my app to MAUI in .NET 8. This decision was primarily influenced by the fact that I've noticed several critical bug fixes in .NET 8 that have not been addressed or backported to .NET 7. However, despite a relatively smooth compilation process without any major issues, I've encountered significant challenges with app stability.

On iOS, the app crashes during the boot process, and on Android, it crashes when attempting to render a carousel. Additionally, when removing the carousel from the view, I encounter another crash when opening the flyout menu by clicking on the hamburger icon. This situation is quite perplexing, especially since the app was running smoothly without any crashes on the .NET 7 version.

I've attempted to investigate the root cause of these issues, but the callstack doesn't provide any information related to my project files; it only references framework files. My suspicion is that there might be an issue with the binding between views and view models or possibly with a custom control or helper within the application. Regrettably, I lack sufficient information to pinpoint the exact problem.

In summary, I'm actively working to resolve these issues and ensure a stable performance for my app in MAUI with .NET 8, but I'm currently faced with a lack of concrete clues regarding the source of the crashes.

Error (very generic, something needs to be initialized but its probably null)
```
System.NullReferenceException: 'Object reference not set to an instance of an object.'
```

Callstack

```
 	0xFFFFFFFFFFFFFFFF in Android.Runtime.RuntimeNativeMethods.monodroid_debugger_unhandled_exception	C#
 	0x1A in Android.Runtime.JNINativeWrapper._unhandled_exception at /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:13,5	C#
 	0x20 in Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPLI_V at /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:181,26	C#
 	0xCB in Microsoft.Maui.Controls.VisualStateManager.VisualStateGroupsPropertyChanged at D:\a\_work\1\s\src\Controls\src\Core\VisualStateManager.cs:49,4	C#
 	0xB0 in Microsoft.Maui.Controls.BindableObject.ClearValueCore at D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:139,5	C#
 	0x58 in Microsoft.Maui.Controls.BindableObject.ClearValue at D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:103,4	C#
 	0x59 in Microsoft.Maui.Controls.Setter.UnApply at D:\a\_work\1\s\src\Controls\src\Core\Setter.cs:100,4	C#
 	0x4E in Microsoft.Maui.Controls.Style.UnApplyCore at D:\a\_work\1\s\src\Controls\src\Core\Style.cs:191,5	C#
 	0x13 in Microsoft.Maui.Controls.Style.Microsoft.Maui.Controls.IStyle.UnApply at D:\a\_work\1\s\src\Controls\src\Core\Style.cs:115,4	C#
 	0x8D in Microsoft.Maui.Controls.MergedStyle.SetStyle at D:\a\_work\1\s\src\Controls\src\Core\MergedStyle.cs:193,6	C#
 	0xE in Microsoft.Maui.Controls.MergedStyle.set_ClassStyles at D:\a\_work\1\s\src\Controls\src\Core\MergedStyle.cs:87,10	C#
 	0x1D in Microsoft.Maui.Controls.MergedStyle.OnClassStyleChanged at D:\a\_work\1\s\src\Controls\src\Core\MergedStyle.cs:126,4	C#
 	0x1 in Microsoft.Maui.Controls.MergedStyle.<set_StyleClass>b__13_0 at D:\a\_work\1\s\src\Controls\src\Core\MergedStyle.cs:70,59	C#
 	0x18A in Microsoft.Maui.Controls.BindableObject.SetValueActual at D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:611,5	C#
 	0x162 in Microsoft.Maui.Controls.BindableObject.SetValueCore at D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:539,5	C#
 	0x6 in Microsoft.Maui.Controls.Element.OnResourceChanged at D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:815,7	C#
 	0x11A in Microsoft.Maui.Controls.Element.OnResourcesChanged at D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:671,6	C#
 	0x10D in Microsoft.Maui.Controls.VisualElement.OnParentResourcesChanged at D:\a\_work\1\s\src\Controls\src\Core\VisualElement\VisualElement.cs:1436,5	C#
 	0x13F in Microsoft.Maui.Controls.Element.SetParent at D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:355,5	C#
 	0x2 in Microsoft.Maui.Controls.Element.OnChildAdded at D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:525,4	C#
 	0x2 in Microsoft.Maui.Controls.ShellItem.OnChildAdded at D:\a\_work\1\s\src\Controls\src\Core\Shell\ShellItem.cs:252,4	C#
 	0x18 in Microsoft.Maui.Controls.Element.AddLogicalChild at D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:224,4	C#
 	0x97 in Microsoft.Maui.Controls.Platform.Compatibility.ShellFlyoutRecyclerAdapter.ElementViewHolder.set_Element at D:\a\_work\1\s\src\Controls\src\Core\Compatibility\Handlers\Shell\Android\ShellFlyoutRecyclerAdapter.cs:287,8	C#
 	0x30 in Microsoft.Maui.Controls.Platform.Compatibility.ShellFlyoutRecyclerAdapter.OnBindViewHolder at D:\a\_work\1\s\src\Controls\src\Core\Compatibility\Handlers\Shell\Android\ShellFlyoutRecyclerAdapter.cs:110,4	C#
 	0x12 in AndroidX.RecyclerView.Widget.RecyclerView.Adapter.n_OnBindViewHolder_Landroidx_recyclerview_widget_RecyclerView_ViewHolder_I at C:\a\_work\1\s\generated\androidx.recyclerview.recyclerview\obj\Release\net6.0-android\generated\src\AndroidX.RecyclerView.Widget.RecyclerView.cs:581,5	C#
 	0xB in Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPLI_V at /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:180,5	C#
 	0xF in Java.Interop.JniNativeMethods.CallNonvirtualVoidMethodA at /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/obj/Release/net7.0/JniEnvironment.g.cs:18296,4	C#
 	0x73 in Java.Interop.JniEnvironment.InstanceMethods.CallNonvirtualVoidMethod at /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/obj/Release/net7.0/JniEnvironment.g.cs:20825,4	C#
 	0x78 in Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualVoidMethod at /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:75,7	C#
 	0x80 in AndroidX.CoordinatorLayout.Widget.CoordinatorLayout.OnLayout at C:\a\_work\1\s\generated\androidx.coordinatorlayout.coordinatorlayout\obj\Release\net6.0-android\generated\src\AndroidX.CoordinatorLayout.Widget.CoordinatorLayout.cs:2704,5	C#
 	0x19 in Microsoft.Maui.Controls.Platform.Compatibility.ShellFlyoutLayout.OnLayout at D:\a\_work\1\s\src\Controls\src\Core\Compatibility\Handlers\Shell\Android\ShellFlyoutLayout.cs:34,4	C#
 	0x10 in AndroidX.CoordinatorLayout.Widget.CoordinatorLayout.n_OnLayout_ZIIII at C:\a\_work\1\s\generated\androidx.coordinatorlayout.coordinatorlayout\obj\Release\net6.0-android\generated\src\AndroidX.CoordinatorLayout.Widget.CoordinatorLayout.cs:2688,4	C#
 	0x11 in Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPZIIII_V at /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:444,5	C#
```

I am using the latest MAUI on Visual Studio 2022 community Preview

### Steps to Reproduce

I have no idea, because its a big app being ported from xamarin -> maui .net7 (many layout issues, memory stream issues, etc) -> maui .net8. And i am trying to gather as much information possible to figure this out.

### Version with bug

8.0.0-rc.1.9171

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI, Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Did you find any workaround?

Not yet  

### Relevant log output

```shell
**System.NullReferenceException:** 'Object reference not set to an instance of an object.'

[EGL_emulation] app_time_stats: avg=16.47ms min=3.87ms max=25.14ms count=61
[EGL_emulation] app_time_stats: avg=16.52ms min=1.95ms max=36.95ms count=60
[EGL_emulation] app_time_stats: avg=3.09ms min=2.46ms max=3.94ms count=61
[EGL_emulation] app_time_stats: avg=3.21ms min=1.29ms max=4.57ms count=60
[EGL_emulation] app_time_stats: avg=3.20ms min=2.67ms max=3.96ms count=61
[EGL_emulation] app_time_stats: avg=3.14ms min=2.41ms max=4.60ms count=61
[libc] Requested dump for tid 28225 (me.activeidmaui)
Thread finished: <Thread Pool> #5
Thread finished: <Thread Pool> #11
Thread finished: <Thread Pool> #2
Thread finished: <Thread Pool> #10
Thread started: <Thread Pool> #12
**System.NullReferenceException:** 'Loading...'

The thread 0x5 has exited with code 0 (0x0).
The thread 0xb has exited with code 0 (0x0).
The thread 0x2 has exited with code 0 (0x0).
The thread 0xa has exited with code 0 (0x0).
```

**Comment by npostma** [comment]
I have additional information concerning the iOS crash, and it appears to be similar to the Android crash. Unfortunately, it doesn't trigger a breakpoint, so I don't have access to the call stack in Visual Studio. However, I have included some logging in my console output (see below).

To clarify, I'm not certain whether the iOS and Android issues are identical. They do seem related, but if they are distinct problems, they may need to be addressed separately. If there's any way I can assist in resolving these issues, please don't hesitate to reach out to me!


```
2023-09-17 09:51:47.273918+0200 ActiveID_MAUI[33291:292965] System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Maui.Controls.VisualStateManager.VisualStateGroupsPropertyChanged(BindableObject bindable, Object oldValue, Object newValue)
2023-09-17 09:51:47.274049+0200 ActiveID_MAUI[33291:292965]    at Microsoft.Maui.Controls.BindableObject.ClearValueCore(BindableProperty property, SetterSpecificity specificity)
   at Microsoft.Maui.Controls.BindableObject.ClearValue(BindableProperty property, SetterSpecificity specificity)
2023-09-17 09:51:47.274209+0200 ActiveID_MAUI[33291:292965]    at Microsoft.Maui.Controls.Setter.UnApply(BindableObject target, SetterSpecificity specificity)
   at Microsoft.Maui.Controls.Style.UnApplyCore(BindableObject bindable, Style basedOn)
   at Microsoft.Maui.Controls.Style.Microsoft.Maui.Controls.IStyle.UnApply(BindableObject bindable)
2023-09-17 09:51:47.274326+0200 ActiveID_MAUI[33291:292965]    at Microsoft.Maui.Controls.MergedStyle.SetStyle(IStyle implicitStyle, IList`1 classStyles, IStyle style)
   at Microsoft.Maui.Controls.MergedStyle.set_ClassStyles(IList`1 value)
   at Microsoft.Maui.Controls.MergedStyle.OnClassStyleChanged()
2023-09-17 09:51:47.274423+0200 ActiveID_MAUI[33291:292965]    at Microsoft.Maui.Controls.MergedStyle.<set_StyleClass>b__13_0(BindableObject bindable, Object oldvalue, Object newvalue)
2023-09-17 09:51:47.274526+0200 ActiveID_MAUI[33291:292965]    at Microsoft.Maui.Controls.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, SetterSpecificity specificity, Boolean silent)
2023-09-17 09:51:47.274635+0200 ActiveID_MAUI[33291:292965]    at Microsoft.Maui.Controls.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes, SetterSpecificity specificity)
   at Microsoft.Maui.Controls.Element.OnResourceChanged(BindableProperty property, Object value, SetterSpecificity specificity)
   at Microsoft.Maui.Controls.Element.OnResourcesChanged(IEnumerable`1 values)
2023-09-17 09:51:47.274734+0200 ActiveID_MAUI[33291:292965]    at Microsoft.Maui.Controls.VisualElement.OnParentResourcesChanged(IEnumerable`1 values)
   at Microsoft.Maui.Controls.Element.SetParent(Element value)
   at Microsoft.Maui.Controls.Element.OnChildAdded(Element child)
   at Microsoft.Maui.Controls.ShellItem.OnChildAdded(Element child)
2023-09-17 09:51:47.274823+0200 ActiveID_MAUI[33291:292965]    at Microsoft.Maui.Controls.Element.AddLogicalChild(Element element)
   at Microsoft.Maui.Controls.Platform.Compatibility.UIContainerCell..ctor(String cellId, View view, Shell shell, Object context)
2023-09-17 09:51:47.274909+0200 ActiveID_MAUI[33291:292965]    at Microsoft.Maui.Controls.Platform.Compatibility.ShellTableViewSource.GetCell(UITableView tableView, NSIndexPath indexPath)
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName)
2023-09-17 09:51:47.274986+0200 ActiveID_MAUI[33291:292965]    at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)
   at ActiveID_MAUI.Program.Main(String[] args) in C:\src\sc_mc\ActiveID_MAUI\ActiveID_MAUI\Platforms\iOS\Program.cs:line 14
2023-09-17 09:51:49.776805+0200 ActiveID_MAUI[33291:292965] [client] Timed out waiting for the exit barrier block. activeSendTransactions=0
```

**Comment by StephaneDelcroix** [comment]
could you share a snippet of code/xaml triggering the issue ?

**Comment by StephaneDelcroix** [comment]
the stack trace point to 'newValue' being null in VisualStateGroupsPropertyChanged (as it comes after a ClearValue). What I don't get is that this code was barely changed, and VSGPropertyChanged always assumed newValue wasn't null. I'm going to propose a change to check for null value, and hope for the best as we don't have a small repro to test on

**Comment by npostma** [comment]
@StephaneDelcroix  `newValue` is not something in my code. The stacktrace and break point do not break in my code but in 'external code'  So its very (if not inposible?) for me to see what the source of this issue is. If  there is a visual studio setting that could provide more info let me know.

@PureWeen First `Do you modify shell at all during load` not really, i have one menu item that has an IsVisible binding.

I will share a redacted version of my AppShell.xaml

```xaml
<?xml version="1.0" encoding="UTF-8" ?>
<Shell
    x:Class="NAMESPACE.AppShell"
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:vm="clr-namespace:NAMESPACE.ViewModels"
    xmlns:local="clr-namespace:NAMESPACE"
    xmlns:view="clr-namespace:NAMESPACE.Views"
    xmlns:template="clr-namespace:NAMESPACE.Views.Template"
    xmlns:resources="clr-namespace:NAMESPACE.Resources"
    xmlns:controls="clr-namespace:NAMESPACE.Controls"
    x:Name="shell"
    FlyoutBackgroundColor="{StaticResource PrimaryBackground}"
    x:DataType="vm:ShellViewModel"
	FlyoutHeaderTemplate="{DataTemplate template:FlyoutHeaderTemplate}"
    >

    <Shell.BindingContext>
        <vm:ShellViewModel/>
    </Shell.BindingContext>

    <Shell.Resources>

        <ResourceDictionary>
            <Style x:Key="BaseStyle" TargetType="Element">
                <Setter Property="Shell.BackgroundColor" Value="{StaticResource PrimaryBackground}" />
                <Setter Property="Shell.ForegroundColor" Value="{StaticResource PrimaryForeground}" />
                <Setter Property="Shell.TitleColor" Value="White" />
                <Setter Property="Shell.DisabledColor" Value="{StaticResource SecondaryFaintedText}" />
                <Setter Property="Shell.UnselectedColor" Value="#95FFFFFF" />
                <Setter Property="Shell.TabBarBackgroundColor" Value="{StaticResource PrimaryBackground}" />
                <Setter Property="Shell.TabBarForegroundColor" Value="White"/>
                <Setter Property="Shell.TabBarUnselectedColor" Value="#95FFFFFF"/>
                <Setter Property="Shell.TabBarTitleColor" Value="White"/>
            </Style>
            <Style TargetType="TabBar" BasedOn="{StaticResource BaseStyle}" />
            <Style TargetType="FlyoutItem" BasedOn="{StaticResource BaseStyle}" />

            <!--
            Default Styles for all Flyout Items
            https://docs.microsoft.com/xamarin/xamarin-forms/app-fundamentals/shell/flyout#flyoutitem-and-menuitem-style-classes
            -->
            <Style Class="FlyoutItemLabelStyle" TargetType="Label">
                <Setter Property="TextColor" Value="White"></Setter>
            </Style>

            <Style Class="FlyoutItemLayoutStyle" TargetType="Layout" ApplyToDerivedTypes="True">
                <Setter Property="VisualStateManager.VisualStateGroups">
                    <VisualStateGroupList>
                        <VisualStateGroup x:Name="CommonStates">
                            <VisualState x:Name="Normal">
                                <VisualState.Setters>
                                    <Setter Property="BackgroundColor" Value="{StaticResource PrimaryBackground}" />
                                    <Setter TargetName="FlyoutItemLabel" Property="Label.TextColor" Value="{StaticResource PrimaryText}" />
                                </VisualState.Setters>
                            </VisualState>
                            <VisualState x:Name="Selected">
                                <VisualState.Setters>
                                    <Setter Property="BackgroundColor" Value="{StaticResource PrimaryBackgroundAccent}" />
                                </VisualState.Setters>
                            </VisualState>
                            <!--This state is bugged in xamarin and wont get activated when IsEnabled = false-->
                            <VisualState x:Name="Disabled">
                                <VisualState.Setters>
                                    <Setter Property="BackgroundColor" Value="{StaticResource PrimaryBackground}" />
                                    <Setter TargetName="FlyoutItemLabel" Property="Label.TextColor" Value="{StaticResource SecondaryFaintedText}" />
                                </VisualState.Setters>
                            </VisualState>
                        </VisualStateGroup>
                    </VisualStateGroupList>
                </Setter>
            </Style>

            <!--
            Custom Style you can apply to any Flyout Item
            -->
            <Style Class="MenuItemLayoutStyle" TargetType="Layout" ApplyToDerivedTypes="True">
                <Setter Property="VisualStateManager.VisualStateGroups">
                    <VisualStateGroupList>
                        <VisualStateGroup x:Name="CommonStates">
                            <VisualState x:Name="Normal">
                                <VisualState.Setters>
                                    <Setter TargetName="FlyoutItemLabel" Property="Label.TextColor" Value="{StaticResource PrimaryText}" />
                                </VisualState.Setters>
                            </VisualState>
                            <VisualState x:Name="Disabled">
                                <VisualState.Setters>
                                    <Setter Property="BackgroundColor" Value="{StaticResource PrimaryBackground}" />
                                    <Setter TargetName="FlyoutItemLabel" Property="Label.TextColor" Value="{StaticResource SecondaryFaintedText}" />
                                </VisualState.Setters>
                            </VisualState>
                        </VisualStateGroup>
                    </VisualStateGroupList>
                </Setter>
            </Style>

            <Style Class="MenuItemLDisabledStyle" TargetType="Layout" ApplyToDerivedTypes="True">
                <Setter Property="VisualStateManager.VisualStateGroups">
                    <VisualStateGroupList>
                        <VisualStateGroup x:Name="CommonStates">
                            <VisualState x:Name="Normal">
                                <VisualState.Setters>
                                    <Setter TargetName="FlyoutItemLabel" Property="Label.TextColor" Value="{StaticResource SecondaryFaintedText}" />
                                </VisualState.Setters>
                            </VisualState>
                            <VisualState x:Name="Disabled">
                                <VisualState.Setters>
                                    <Setter Property="BackgroundColor" Value="{StaticResource PrimaryBackground}" />
                                    <Setter TargetName="FlyoutItemLabel" Property="Label.TextColor" Value="{StaticResource SecondaryFaintedText}" />
                                </VisualState.Setters>
                            </VisualState>
                        </VisualStateGroup>
                    </VisualStateGroupList>
                </Setter>
            </Style>


        </ResourceDictionary>
    </Shell.Resources>

    <!-- This needs to be the first. The first TabBar OR FlyoutItem is the app's landing page -->
    <TabBar>
        <ShellContent Route="LandingPage" ContentTemplate="{DataTemplate view:LandingPage}"/>
    </TabBar>

    <FlyoutItem Title="{x:Static resources:Localization.SOMELABEL}">
        <!-- &#xf2c2; == LineAwseome id-card -->
        <!-- &#xf47f; == LineAwseomeSolid id-card-alt -->
        <FlyoutItem.Icon>
            <FontImageSource
            FontFamily="LaSolid"
            Glyph="&#xf47f;" 
            Color="White"
            Size="24"
            />
        </FlyoutItem.Icon>
        <ShellContent Route="MainPage" ContentTemplate="{DataTemplate view:MainPage}" />
    </FlyoutItem>

    <!--
        TabBar lets you define content that won't show up in a flyout menu. When this content is active
        the flyout menu won't be available. This is useful for creating areas of the application where 
        you don't want users to be able to navigate away from. If you would like to navigate to this 
        content you can do so by calling 
        await Shell.Current.GoToAsync("//LoginPage");
    -->
    <!-- Use tabbars here, these pages do not have the menu -->
    <TabBar>
        <ShellContent Route="LoginPage" ContentTemplate="{DataTemplate view:LoginPage}" />
    </TabBar>

    <TabBar>
        <ShellContent Route="SOMEROUTE" ContentTemplate="{DataTemplate view:SOMEPAGE}" />
    </TabBar>

    <TabBar>
        <ShellContent Route="SOMEROUTE" ContentTemplate="{DataTemplate view:SOMEPAGE}" />
    </TabBar>

    <TabBar>
        <ShellContent Route="SOMEROUTE" ContentTemplate="{DataTemplate view:SOMEPAGE}" />
    </TabBar>

    <FlyoutItem 
        Title="{x:Static resources:Localization.SOMELABEL}"										   
        >
        <!--&#xf2c2; == LineAwseome id-card 
         &#xf47f; == LineAwseomeSolid-->
        <FlyoutItem.Icon>
            <FontImageSource
            FontFamily="LaSolid"
            Glyph="&#xf058;" 
            Color="White"
            Size="24"
            />
        </FlyoutItem.Icon>

        <ShellContent Route="SOMEROUTE" ContentTemplate="{DataTemplate view:SOMEPAGE}" />
    </FlyoutItem>

    <FlyoutItem Title="{x:Static resources:Localization.SOMELABEL}">
        <!-- &#xf4fe; == LineAwseome -->
        <FlyoutItem.Icon>
            <FontImageSource
            FontFamily="LaSolid"
            Glyph="&#xf4fe;" 
            Color="White"
            Size="24"
            />
        </FlyoutItem.Icon>
        <ShellContent Route="SOMEROUTE" ContentTemplate="{DataTemplate view:SOMEPAGE}" />
    </FlyoutItem>

    <FlyoutItem Title="{x:Static resources:Localization.SOMELABEL}">
        <!-- &#xf013; == LineAwseome -->
        <FlyoutItem.Icon>
            <FontImageSource
            FontFamily="LaSolid"
            Glyph="&#xf013;" 
            Color="White"
            Size="24"
            />
        </FlyoutItem.Icon>
        <ShellContent Route="SOMEROUTE" ContentTemplate="{DataTemplate view:SOMEPAGE}" />
    </FlyoutItem>

    <FlyoutItem Title="{x:Static resources:Localization.SOMELABEL}">
        <!-- &#xf05a; == LineAwseomeSolid -->
        <FlyoutItem.Icon>
            <FontImageSource
            FontFamily="LaSolid"
            Glyph="&#xf05a;" 
            Color="White"
            Size="24"
            />
        </FlyoutItem.Icon>
        <ShellContent Route="SOMEROUTE" ContentTemplate="{DataTemplate view:SOMEPAGE}" />
    </FlyoutItem>

    <FlyoutItem Title="{x:Static resources:Localization.SOMELABEL}" IsVisible="{Binding ShowIfIsSomeItemVisible}">
        <FlyoutItem.Icon>
            <FontImageSource
            FontFamily="LaSolid"
            Glyph="&#xf0e0;" 
            Color="White"
            Size="24"
            />
        </FlyoutItem.Icon>
        <ShellContent Route="SOMEROUTE" ContentTemplate="{DataTemplate view:SOMEPAGE}" />
    </FlyoutItem>

    <!-- When the Flyout is visible, this item will serve as a menu option that you can associate with a click behavior.  -->
    <MenuItem Text="{x:Static resources:Localization.SOMELABEL}" StyleClass="MenuItemLayoutStyle" Clicked="OnSomeActionClicked">
        <MenuItem.IconImageSource>
            <FontImageSource
            FontFamily="LaSolid"
            Glyph="&#xf100;" 
            Color="White"
            Size="24"
            />
        </MenuItem.IconImageSource>
    </MenuItem>

    <!-- Keep this out of the tabbar, so we can slide in the menu -->
    <!--<ShellContent IsEnabled="False" Route="SOMEROUTE" ContentTemplate="{DataTemplate local:SOMEPAGE}" />-->
    <!--<ShellContent IsEnabled="False" Route="SOMEROUTE" ContentTemplate="{DataTemplate local:SOMEPAGE}" />-->
    <!--<ShellContent IsEnabled="False" Route="SOMEROUTE" ContentTemplate="{DataTemplate local:SOMEPAGE}" />-->

</Shell>
```

Colors.xaml
```xaml
<?xml version="1.0" encoding="UTF-8" ?>
<?xaml-comp compile="true" ?>
<ResourceDictionary 
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml">

    <Color x:Key="CompanyBlack">#000000</Color>
    <Color x:Key="CompanyWhite">#ffffff</Color>

    <Color x:Key="PrimaryBackground">#000000</Color>
    <Color x:Key="PrimaryBackgroundAccent">#000000</Color>
    <Color x:Key="SecondaryBackground">#000000</Color>
    <Color x:Key="PrimaryForeground">#000000</Color>
    <Color x:Key="AccentBackground">#000000</Color>
    <Color x:Key="SeparatorBackground">#000000</Color>

    <Color x:Key="PrimaryText">#000000</Color>
    <Color x:Key="SecondaryText">#000000</Color>
    <Color x:Key="HeaderText">#000000</Color>
    <Color x:Key="SecondaryFaintedText">#000000</Color>
    <Color x:Key="SecondaryLightenText">#000000</Color>
    <Color x:Key="AccentText">#000000</Color>
    <Color x:Key="AccentTextDisabled">#00000011</Color>
    <Color x:Key="ErrorText">#000000</Color>
    <Color x:Key="ErrorBackground">#000000</Color>
    <Color x:Key="ErrorTextDisabled">#000000</Color>
    <Color x:Key="WarningText">#000000</Color>
    <Color x:Key="WarningTextBackground">#000000</Color>
    <Color x:Key="WarningTextDisabled">#000000</Color>
    <Color x:Key="SuccessText">#000000</Color>
    <Color x:Key="SuccessTextBackground">#000000</Color>
    <Color x:Key="SuccessTextDisabled">#00000011</Color>
    <Color x:Key="Button">#000000</Color>
    <Color x:Key="Active">#000000</Color>
    <Color x:Key="Inactive">#000000</Color>
    <Color x:Key="ButtonDisabled">#000000</Color>

</ResourceDictionary>
```

**Comment by PureWeen** [comment]
@npostma 
>  i have one menu item that has an IsVisible binding. It would be nice to know what element is faulty or the name of the binding. So i could some step by step debugging (removing code)

if you remove this binding do you still get a crash?

**Comment by npostma** [comment]
@PureWeen in short: yes, it stil crashes after removing the IsVisible binding.

For android: Opening the app works. After login the page with the carousel is trying to load -> crash.
Then -> Removing the carousel in its whole from the view, only a grid is left, app does not crash. Then opening the flyout menu -> crash.

For iOS: Loading the app -> crash.

I looks like the same issue (same stack trace) but i do not think its one thing in my code.

**Comment by npostma** [comment]
@PureWeen @StephaneDelcroix I did some debugging by removing a lot of code en step by step re-adding the xml unit it crashes. My conclusions is that a lot of elements (95%) with a binding make the app crash. A simple example of this:

In the view i have an element:
```xaml
<Label Grid.Row="1"
    Text="{Binding Name}"
    HorizontalOptions="CenterAndExpand"
    VerticalOptions="Center" 
    Style="{DynamicResource SubTitle}"
/>
```

if i remove the `{Binding Name}` and change it to a default string, it works. In the viewmodel i have this:

```
public string Name=> activeUser?.Name ?? "";
```

So if there is a activeUser use name else use empty string. Changing this to `public string Name=> "";` fixes the specific crash.

Then i tested to keep activeUser `null`. No crash. So when activeUser transfers from null to a user object i get this error. 

Does this information help?  This code works fine in Xamarin, Maui .NET6 and .NET7

**Comment by PureWeen** [comment]
Where do these labels live?
```XAML
<Label Grid.Row="1"
    Text="{Binding Name}"
    HorizontalOptions="CenterAndExpand"
    VerticalOptions="Center" 
    Style="{DynamicResource SubTitle}"
/>
```

are they part of your flyout item templates?

**Comment by npostma** [comment]
@PureWeen Not applicable to the example provided above. These labels are situated within an extended class derived from ContentView. This ContentView is loaded within the constructor, subsequent to the InitializeComponent() call, within a class that itself extends a ContentPage.

Container code of the content page
```xaml
<Grid x:Name="viewContainer" Margin="0" Padding="0" ColumnSpacing="0" RowSpacing="0">
    <Grid.RowDefinitions>
        <RowDefinition Height="*" />
    </Grid.RowDefinitions>
    <Grid.ColumnDefinitions>
        <ColumnDefinition Width="*" />
    </Grid.ColumnDefinitions>
</Grid>
```

Constructor code from the ContentPage:
```c#
InitializeComponent();

MyView = new CardsCarouselIOS();
MyView .BindingContext = BindingContext;
viewContainer.Add(MyView);
```




![image](https://github.com/dotnet/maui/assets/1578820/5374d012-fed4-4658-9a52-5f04093ea9c6)

**Comment by npostma** [comment]
I can conclude that this is indeed fixed. I do not experience the crash in the main or in the net/8.0 branch! Tested for android.

**Comment by npostma** [comment]
Also fixed it for iOS!
