### ISSUE TITLE
[regression/8.0.0] Exception while using SetAppTheme extension

### ISSUE THREAD

**Issue by mikebaumannch** [dotnet/maui#17478]
### Description

If you add a binding based on the app theme with `SetAppTheme()` and the values passed as `light` and `dark` parameters need to be casted in order to match the property type (e.g: ImageSource.Source => pass a string instead of a imagesource, Border.Stroke => pass a color instead of a brush), there is an exception raised: `System.InvalidCastException: Specified cast is not valid.`

### Steps to Reproduce

1. Create a Border
2. Add an appThemeBinding for Border.StrokeProperty
3. Add a Color for light and dark (instead of a brush)

### Version with bug

8.0.0-rc.1.9171

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.49

### Affected platforms

iOS

### Did you find any workaround?

Use the casted value (but according the documentation this should work). 

### Relevant log output

```shell
System.InvalidCastException: Specified cast is not valid.
   at Microsoft.Maui.Controls.ImageElement.OnImageSourceChanged(BindableObject bindable, Object oldValue, Object newValue)
   at Microsoft.Maui.Controls.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, SetterSpecificity specificity, Boolean silent)
   at Microsoft.Maui.Controls.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes, SetterSpecificity specificity)
   at Microsoft.Maui.Controls.AppThemeBinding.<>c__DisplayClass9_0.<ApplyCore>g__Set|0()
   at Microsoft.Maui.Controls.AppThemeBinding.ApplyCore(Boolean dispatch)
   at Microsoft.Maui.Controls.AppThemeBinding.Apply(Object context, BindableObject bindObj, BindableProperty targetProperty, Boolean fromBindingContextChanged, SetterSpecificity specificity)
   at Microsoft.Maui.Controls.BindableObject.SetBinding(BindableProperty targetProperty, BindingBase binding, SetterSpecificity specificity)
   at Microsoft.Maui.Controls.BindableObject.SetBinding(BindableProperty targetProperty, BindingBase binding)
   at Microsoft.Maui.Controls.BindableObjectExtensions.SetAppTheme[Object](BindableObject self, BindableProperty targetProperty, Object light, Object dark)
```

**Comment by mikebaumannch** [comment]
`var border = new Border();`
`border.SetAppTheme(Border.StrokeProperty, Colors.Red, Colors.Black);` ->  This will cause the exception (specified cast ist not valid)

**Comment by StephaneDelcroix** [comment]
note that the conversion works fine if you define the AppThemeBinding in XAML

**Comment by StephaneDelcroix** [comment]
there's no bug here, make sure you se the values of the same type as the property
```
border.SetAppTheme(Border.StrokeProperty, Brush.Red, Brush.Black);
```

**Comment by StephaneDelcroix** [comment]
I don't recall this ever working, but I can be wrong. Will fix instead of trying to figure out if it's a regression or not
