### ISSUE TITLE
Blazor JS interop [Bug] 

### ISSUE THREAD

**Issue by jirisykora83** [dotnet/maui#1762]
### Description
Calling JS from C# in MAUI-Blazor app not work.

### Steps to Reproduce

1. RCL with JS interop wrapped to C# class
2. Call

### Expected Behavior

Work same as with browser. With browser same RCL work.

### Basic Information

- Version with issue:
- Last known good version:
- IDE: VS19.VS22
- Platform Target Frameworks: 
  - Android: emulator

`"Object reference not set to an instance of an object."`

```
   at Microsoft.AspNetCore.Components.WebView.Services.WebViewJSRuntime.BeginInvokeJS(Int64 taskId, String identifier, String argsJson, JSCallResultType resultType, Int64 targetInstanceId) in Microsoft.AspNetCore.Components.WebView.dll:token 0x6000113+0x0
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[IJSObjectReference](Int64 targetInstanceId, String identifier, CancellationToken cancellationToken, Object[] args) in Microsoft.JSInterop.dll:token 0x600003a+0x10a
   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16`1[[Microsoft.JSInterop.IJSObjectReference, Microsoft.JSInterop, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext() in Microsoft.JSInterop.dll:token 0x60000a8+0xf7
   at Obletsvet.Ui.Mobile.Components.SwipeMenu.InitAsync() in C:\Projects\Obletsvet\Obletsvet\src\Obletsvet.Ui.Mobile.Components\SwipeMenu.cs:line 35
   at Obletsvet.Ui.Mobile.Components.Shared.TopBar.OnAfterRenderAsync(Boolean firstRender) in C:\Projects\Obletsvet\Obletsvet\src\Obletsvet.Ui.Mobile.Components\Shared\TopBar.razor:line 97
```

Also notice #1245 and `ipcSender` looks like it is also not set in android

**Comment by jirisykora83** [comment]
Now i figure out its happen only when service (from default template `ExampleJsInterop`) is registered as Singleton. But still i expect it should work whatever it is registered as Scoped or Singleton.

**Comment by Eilon** [comment]
I think that the JS interop type in your app needs to be registered as Scoped and not Singleton (just like in Blazor Server).

But we should try to make this have a better experience.

**Comment by Matikas** [comment]
Hello, I have same issue but it doesn't look related to JSInterop anyhow. I have registered my class with Signalr HubConnection as singleton and when I try to connect to my hub - I get this error. When I register same class AsScoped it works:
![image](https://user-images.githubusercontent.com/7543185/158960036-26f06625-309c-4912-b3a3-91ebd3139757.png)

This is an issue for me because in my application I need to have this class as singleton

**Comment by Matikas** [comment]
Hello, I face same issue. When I register my class as scoped - it works, but if singleton - it doesnt. I get error when I am starting signalr connection but along with that I am providing access token which is stored in ILocalStorage. So before connecting when signalr client is trying to retrieve it - I get this error. So even if my class doesnt do JSInterop - some dependency does and raises issue.
This is a problem for me because I need this class to be singleton in my application.
![image](https://user-images.githubusercontent.com/7543185/158961399-82c6abba-b630-4622-9ab1-488f7844c127.png)

**Comment by Eilon** [comment]
> @Eilon is the following exception caused by the same issue or a different one:

@Eagle3386 that seems different. Can you log a new issue for that?

**Comment by Eagle3386** [comment]
> @Eagle3386 that seems different. Can you log a new issue for that?

I could, but I don't need as it wasn't a MAUI fault, but instead my oversight of a typo within the `DangerousAndroidMessageHandlerEmitter` class that's described in the workaround I've linked to previously.
To be precise, it was the `Register` method where I did
```cs
AppDomain.CurrentDomain.AssemblyResolve += (sender, args) =>
  assemblyName.Equals(args)
    ? (EmittedAssembly ??= Emit(handlerName, assemblyName))
    : null;
```
instead of
```cs
AppDomain.CurrentDomain.AssemblyResolve += (sender, args) =>
  assemblyName.Equals(args.Name)
    ? (EmittedAssembly ??= Emit(handlerName, assemblyName))
    : null;
```

So, the "simply" forgotten property `Name` within `.Equals()` resulted in a "string equals object" comparison that obviously had to fail. By adding the property name properly, I fixed my `null` reference immediately.

**Comment by MackinnonBuck** [comment]
If we enable scope validation, error like this will yield much more useful messages. Since we can't reasonably change the `IJSRuntime` to be registered as a singleton service in MAUI Blazor, let's use this issue to track enabling scope validation.
