### ISSUE TITLE
NRE in HideSoftInputOnTappedChangedManager.UpdateFocusForView

### ISSUE THREAD

**Issue by mypp74** [dotnet/maui#17681]
### Description

The problem appears after calling HideSoftInputAsync(CancellationToken.None) and then navigating back

### Steps to Reproduce

I was unable to create a simple scenario to reproduce the problem

### Version with bug

8.0.0-rc.1.9171

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Relevant log output

```shell
[mono-rt] [ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object.
[mono-rt]    at Microsoft.Maui.Controls.HideSoftInputOnTappedChangedManager.UpdateFocusForView(IView _view) in D:\a\_work\1\s\src\Controls\src\Core\ContentPage\HideSoftInputOnTappedChanged\HideSoftInputOnTappedChangedManager.Platform.cs:line 86
[mono-rt]    at Microsoft.Maui.Controls.HideSoftInputOnTappedChangedManager.SetupHideSoftInputOnTapped() in D:\a\_work\1\s\src\Controls\src\Core\ContentPage\HideSoftInputOnTappedChanged\HideSoftInputOnTappedChangedManager.Platform.cs:line 123
[mono-rt]    at Microsoft.Maui.Controls.HideSoftInputOnTappedChangedManager.UpdatePage(ContentPage page) in D:\a\_work\1\s\src\Controls\src\Core\ContentPage\HideSoftInputOnTappedChanged\HideSoftInputOnTappedChangedManager.Platform.cs:line 20
[mono-rt]    at Microsoft.Maui.Controls.ContentPage.UpdateHideSoftInputOnTapped() in D:\a\_work\1\s\src\Controls\src\Core\ContentPage\ContentPage.Mapper.cs:line 24
[mono-rt]    at Microsoft.Maui.Controls.ContentPage.<.ctor>b__8_0(Object _, NavigatedToEventArgs _) in D:\a\_work\1\s\src\Controls\src\Core\ContentPage\ContentPage.cs:line 39
[mono-rt]    at Microsoft.Maui.Controls.Page.SendNavigatedTo(NavigatedToEventArgs args) in D:\a\_work\1\s\src\Controls\src\Core\Page\Page.cs:line 660
[mono-rt]    at Microsoft.Maui.Controls.Shell.SendNavigated(ShellNavigatedEventArgs args) in D:\a\_work\1\s\src\Controls\src\Core\Shell\Shell.cs:line 1155
[mono-rt]    at Microsoft.Maui.Controls.Shell.<.ctor>b__157_0(Object _, ShellNavigatedEventArgs args) in D:\a\_work\1\s\src\Controls\src\Core\Shell\Shell.cs:line 793
[mono-rt]    at Microsoft.Maui.Controls.ShellNavigationManager.<>c__DisplayClass16_0.<HandleNavigated>g__FireNavigatedEvents|3(ShellNavigatedEventArgs a, Shell shell) in D:\a\_work\1\s\src\Controls\src\Core\Shell\ShellNavigationManager.cs:line 274
[mono-rt]    at Microsoft.Maui.Controls.ShellNavigationManager.<>c__DisplayClass16_0.<HandleNavigated>b__2() in D:\a\_work\1\s\src\Controls\src\Core\Shell\ShellNavigationManager.cs:line 264
[mono-rt]    at Microsoft.Maui.Controls.Page.OnAppearing(Action action) in D:\a\_work\1\s\src\Controls\src\Core\Page\Page.cs:line 439
[mono-rt]    at Microsoft.Maui.Controls.BaseShellItem.OnAppearing(Action action) in D:\a\_work\1\s\src\Controls\src\Core\Shell\BaseShellItem.cs:line 179
[mono-rt]    at Microsoft.Maui.Controls.ShellNavigationManager.HandleNavigated(ShellNavigatedEventArgs args) in D:\a\_work\1\s\src\Controls\src\Core\Shell\ShellNavigationManager.cs:line 262
[mono-rt]    at Microsoft.Maui.Controls.ShellNavigationManager.GoToAsync(ShellNavigationParameters shellNavigationParameters, ShellNavigationRequest navigationRequest) in D:\a\_work\1\s\src\Controls\src\Core\Shell\ShellNavigationManager.cs:line 209
[mono-rt]    at Dopnet.YourDive.UI.ViewModels.SpotsViewModel.SelectSpotAsync() in D:\YourDive\Dopnet.YourDive.UI.Logic\YourDive.UI.ViewModels\SpotsViewModel.cs:line 362
[mono-rt]    at Dopnet.Maui.CommandFactory.<>c__DisplayClass7_0.<<CreateCommand>b__0>d.MoveNext() in D:\YourDive\Dopnet.Maui\CommandFactory.cs:line 50
[mono-rt] --- End of stack trace from previous location ---
[mono-rt]    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
[mono-rt]    at Android.App.SyncContext.<>c__DisplayClass2_0.<Post>b__0() in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.App/SyncContext.cs:line 36
[mono-rt]    at Java.Lang.Thread.RunnableImplementor.Run() in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Java.Lang/Thread.cs:line 36
[mono-rt]    at Java.Lang.IRunnableInvoker.n_Run(IntPtr jnienv, IntPtr native__this) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net8.0/android-34/mcw/Java.Lang.IRunnable.cs:line 84
[mono-rt]    at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(_JniMarshal_PP_V callback, IntPtr jnienv, IntPtr klazz) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 26
[HostConnection] HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_YUV_Cache ANDROID_EMU_has_shared_slots_host_memory_allocator ANDROID_EMU_sync_buffer_data ANDROID_EMU_read_color_buffer_dma ANDROID_EMU_hwc_multi_configs GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_3_0
```

**Comment by mattleibow** [comment]
If it is line 86 then it seems `widow` is null:

src/Controls/src/Core/ContentPage/HideSoftInputOnTappedChanged/HideSoftInputOnTappedChangedManager.Platform.cs

<img width="488" alt="image" src="https://github.com/dotnet/maui/assets/1096616/4b21c3f1-f182-455d-8137-f153398b8485">

**Comment by PureWeen** [comment]
@mypp74 can you post your shell structure here? What route your on? And your code where you're calling HIdeSoftInput?

**Comment by mypp74** [comment]
![Sans titre](https://github.com/dotnet/maui/assets/127251964/5dde0382-9ae2-4f37-ab59-6268dde56597)

**Comment by mypp74** [comment]
![Sans titre2](https://github.com/dotnet/maui/assets/127251964/3607b08a-46bd-4085-8dff-52920f95d901)

**Comment by mypp74** [comment]
![Sans titre3](https://github.com/dotnet/maui/assets/127251964/af7fcf95-5321-4515-bfe3-45282bc89bf3)

**Comment by mypp74** [comment]
I hope this helps !

**Comment by PureWeen** [comment]
@mypp74 how are you navigating back? just via the backbutton?

**Comment by mypp74** [comment]
public Task GoBackToDiveEditionAsync(SpotInfo spot)
    {
        return GoToAsync($"..", new Dictionary<string, object>()
        {
            [nameof(DiveEditionViewModel.Spot)] = spot
        });
    }

**Comment by mypp74** [comment]
![Screenshot_1696048975](https://github.com/dotnet/maui/assets/127251964/a77f10de-7e90-41a8-a8f7-0f3f38f11fea)

I think that's the CarouselView. When I remove it, the problem disappears  (I just realized it)

**Comment by PureWeen** [comment]
@mypp74 thank you so much for testing out NET8, logging this issue, and working with me here.

Looks like it's an unfortunate ordering of events I didn't account for https://github.com/dotnet/maui/pull/17758

**Comment by mypp74** [comment]
@PureWeen Thank you very much for resolving the issue so quickly. Is it possible to have the fix in RC2?

I was very happy to collaborate with you! I follow the evolution of the MAUI project every day. This project is so exciting and promising. Great work from the MAUI team!
