### ISSUE TITLE
Blazor MAUI JS Isolation Not Working

### ISSUE THREAD

**Issue by Ali1Jamal** [dotnet/maui#17748]
### Description

I am trying to use JavaScript isolation in a Blazor MAUI project, but I am facing issues. i am run the application using android device, I can import the script from Index.html and see it in the sources tab using edge://inspect. However, when I try to import it from C# using IJSObjectReference, I get an error :
```
Failed to resolve module specifier 'js/Components/Pages/Index.js'
TypeError: Failed to resolve module specifier 'js/Components/Pages/Index.js'
    at https://0.0.0.0/_framework/blazor.webview.js:1:943
    at https://0.0.0.0/_framework/blazor.webview.js:1:3050
    at new Promise (<anonymous>)
    at g.beginInvokeJSFromDotNet (https://0.0.0.0/_framework/blazor.webview.js:1:3007)
    at External.__callback (https://0.0.0.0/_framework/blazor.webview.js:1:44897)
    at MessagePort.<anonymous> (<anonymous>:23:21)
   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16`1[[Microsoft.JSInterop.IJSObjectReference, Microsoft.JSInterop, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at RazorUI.Extensions.IJSExtensions.ComponentModule(IJSRuntime js, ComponentBase component)
   at RazorUI.Components.Pages.Index.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```
Even I used Razor Class Lib everything works fine with Blazor Web but everything bad happens in Blazor Maui

### Steps to Reproduce

just make simple blazor maui project with js isolation and see the problems.

### Version with bug

8.0.0-rc.1.9171

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12

### Relevant log output

```shell
Failed to resolve module specifier 'js/Components/Pages/Index.js'
TypeError: Failed to resolve module specifier 'js/Components/Pages/Index.js'
    at https://0.0.0.0/_framework/blazor.webview.js:1:943
    at https://0.0.0.0/_framework/blazor.webview.js:1:3050
    at new Promise (<anonymous>)
    at g.beginInvokeJSFromDotNet (https://0.0.0.0/_framework/blazor.webview.js:1:3007)
    at External.__callback (https://0.0.0.0/_framework/blazor.webview.js:1:44897)
    at MessagePort.<anonymous> (<anonymous>:23:21)
   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16`1[[Microsoft.JSInterop.IJSObjectReference, Microsoft.JSInterop, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at RazorUI.Extensions.IJSExtensions.ComponentModule(IJSRuntime js, ComponentBase component)
   at RazorUI.Components.Pages.Index.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

**Comment by Eilon** [comment]
Hi @Ali1Jamal can you provide a repro or code sample that shows exactly what scenario isn't working?

**Comment by Ali1Jamal** [comment]
@Eilon, I fixed it. I have read in some places that I need to put only `js/...etc` to make it work. I also tried it with `./js/...etc`, but the problem is if I exclude the 'js' folder from 'wwwroot', it will not work (but it works in the Blazor web). Now, I tried to rename the script from 'Index.razor.js' to 'Index.js' and removed the exclude , and now it's working.

i hope to see this issue also :
#17725
