### ISSUE TITLE
Regression: AppThemeBinding and VisualStates results in "An item with the same key has already been added"

### ISSUE THREAD

**Issue by XceedBoucherS** [dotnet/maui#17832]
### Description

Something that was working in NET7, which do not work anymore in NET8.
Related to https://github.com/dotnet/maui/issues/16960

Combining Binding on a Control, the same binding in the Control's Triggers and setting a VisualState with AppThemeBinding results in the error: 
"An item with the same key has already been added. Key: Microsoft.Maui.Controls.SetterSpecificity (Parameter 'key')"

and the stack trace:
   at System.Collections.Generic.SortedList`2.Add(TKey key, TValue value)
   at Microsoft.Maui.Controls.BindableObject.SetBinding(BindableProperty targetProperty, BindingBase binding, SetterSpecificity specificity)
   at Microsoft.Maui.Controls.Setter.Apply(BindableObject target, SetterSpecificity specificity)
   at Microsoft.Maui.Controls.VisualStateManager.GoToState(VisualElement visualElement, String name)
   at Microsoft.Maui.Controls.VisualElement.ChangeVisualState()
   at Microsoft.Maui.Controls.View.ChangeVisualState()
   at Microsoft.Maui.Controls.VisualElement.SetPointerOver(Boolean value, Boolean callChangeVisualState)
   at Microsoft.Maui.Controls.View.<CheckPointerOver>b__22_0(Boolean result)
   at Microsoft.Maui.Controls.PointerGestureRecognizer.<>c__DisplayClass61_0.<SetupForPointerOverVSM>b__0(Object s, PointerEventArgs e)
   at Microsoft.Maui.Controls.PointerGestureRecognizer.SendPointerEntered(View sender, Func`2 getPosition, PlatformPointerEventArgs platformArgs)
   at Microsoft.Maui.Controls.Platform.GesturePlatformManager.<>c__DisplayClass47_0.<OnPgrPointerEntered>b__0(View view, PointerGestureRecognizer recognizer)
   at Microsoft.Maui.Controls.Platform.GesturePlatformManager.HandlePgrPointerEvent(PointerRoutedEventArgs e, Action`2 SendPointerEvent)
   at Microsoft.Maui.Controls.Platform.GesturePlatformManager.OnPgrPointerEntered(Object sender, PointerRoutedEventArgs e)
   at ABI.Microsoft.UI.Xaml.Input.PointerEventHandler.Do_Abi_Invoke(IntPtr thisPtr, IntPtr sender, IntPtr e)

### Steps to Reproduce

Paste the following XAML in an empty project's MainPage.xaml:

` <CheckBox x:Name="_checkBox" />
 <Entry Text="ABC"
        WidthRequest="120"
        IsReadOnly="{Binding IsChecked, Source={x:Reference _checkBox}}">
   <VisualStateManager.VisualStateGroups>
     <VisualStateGroupList>
       <VisualStateGroup>
         <VisualState x:Name="Normal" />
         <VisualState x:Name="PointerOver">
           <VisualState.Setters>
             <Setter Property="Background"
                     Value="{AppThemeBinding Dark=Green, Light=Red}" />
           </VisualState.Setters>
         </VisualState>
       </VisualStateGroup>
     </VisualStateGroupList>
   </VisualStateManager.VisualStateGroups>
   <Entry.Triggers>
     <DataTrigger TargetType="{x:Type Entry}"
                  Binding="{Binding IsChecked, Source={x:Reference _checkBox}}"
                  Value="True">
       <Setter Property="Background"
               Value="Green" />
     </DataTrigger>
   </Entry.Triggers>
 </Entry>`

-Run the application.
-Mouse Over the Entry and then mouse out
-Check the CheckBox
-Mouse Over the Entry and then mouse out
-Mouse Over the Entry and exception is raised

### Version with bug

8.0.0-rc.1.9171

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.92

### Affected platforms

Windows

### Affected platform versions

net8.0-windows10.0.19041.0

### Did you find any workaround?

no

**Comment by samhouts** [comment]
@StephaneDelcroix I think we fixed something like this not long ago? Is this the same or different?

**Comment by StephaneDelcroix** [comment]
> @StephaneDelcroix I think we fixed something like this not long ago? Is this the same or different?

should be already fixed, but I'll write a test anyway

**Comment by StephaneDelcroix** [comment]
yep, fixed

**Comment by XceedBoucherS** [comment]
Hi,
Which version contains the fix ? 
Because running the posted xaml from this thread results in an exception with version  8.0.0-rc.1.9171.
Thank you
