### ISSUE TITLE
Application with multiple windows will not open on macOS after a crash

### ISSUE THREAD

**Issue by tstephansen** [dotnet/maui#17841]
### Description

I am currently working on a maui app that uses a second window. The app will not start after the app crashes or I stop debugging without first closing that second window and I am presented with the following exception message.

```
System.InvalidOperationException: VirtualView cannot be null here
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.AspNetCore.Components.WebView.Maui.IBlazorWebView, Microsoft.AspNetCore.Components.WebView.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[WebKit.WKWebView, Microsoft.MacCatalyst, Version=16.4.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065]].get_VirtualView()
   at Microsoft.AspNetCore.Components.WebView.Maui.BlazorWebViewHandler.UrlLoading(UrlLoadingEventArgs args)
   at Microsoft.AspNetCore.Components.WebView.Maui.IOSWebViewManager.WebViewNavigationDelegate.DecidePolicy(WKWebView webView, WKNavigationAction navigationAction, Action`1 decisionHandler)
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName)
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)
   at MauiApp1.Program.Main(String[] args) in /Users/tim/Git/MauiApp1/MauiApp1/Platforms/MacCatalyst/Program.cs:line 14
```

Is there a workaround for this? We use some unmanaged libraries and I'm not sure how to fix this for our customers if an exception is thrown there and our app crashes (ideally there wouldn't be any exceptions or crashes but we aren't there yet).

### Steps to Reproduce

1. Clone the repository and open the solution.
2. Start debugging and click the "Open Second Window" button.
3. Stop debugging to simulate a crash (this same issue also happens if the app crashes).
4. Open the software again and you will get the exception.

### Link to public reproduction project repository

git@github.com:tstephansen/MauiWindowBug.git

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

macOS 17

### Did you find any workaround?

I didn't find a workaround that will work for end users.

1. Remove the following lines from the Platforms/MacCatalyst/Info.plist file

   ```xml
    <key>UIApplicationSceneManifest</key>
    <dict>
        <key>UIApplicationSupportsMultipleScenes</key>
        <true/>
        <key>UISceneConfigurations</key>
        <dict>
            <key>UIWindowSceneSessionRoleApplication</key>
            <array>
                <dict>
                    <key>UISceneConfigurationName</key>
                    <string>__MAUI_DEFAULT_SCENE_CONFIGURATION__</string>
                    <key>UISceneDelegateClassName</key>
                    <string>SceneDelegate</string>
                </dict>
            </array>
        </dict>
    </dict>
   ```

2. Clean and Rebuild the software and debug it (a window probably won't open)
3. Stop debugging
4. Debug it again.
5. Stop debugging.
6. Add those lines back to the Info.plist file.
7. Clean and Rebuild
8. Debug again (the software should open again)

**Comment by tstephansen** [comment]
I found a workaround a few minutes ago. If you check the Saved Application State directory and delete the ones that correspond to the app then it launches no problem. I'm not sure if there is a _cleaner_ way to do this though.

```
var stateDirectoryOne = Path.Combine("/Users", Environment.UserName, "Library", "Saved Application State", "com.companyname.mauiapp1.savedState");
var stateDirectoryTwo = Path.Combine("/Users", Environment.UserName, "Library", "Saved Application State", "com.companyname.mauiapp1~iosmac.savedState");
if (Directory.Exists(stateDirectoryOne))
    Directory.Delete(stateDirectoryOne, true);
if (Directory.Exists(stateDirectoryTwo))
    Directory.Delete(stateDirectoryTwo, true);
UIApplication.Main(args, null, typeof(AppDelegate));
```

The reason the second page doesn't have a web view is it is only being used to fade opacity (we basically open a window over whatever the user is watching while using our software and make it fade from clear to black based on what the user's brainwaves are doing). Would it be better to add a web view to that window and fade the opacity through CSS animations instead?

**Comment by drasticactions** [comment]
What I was saying was that if you open two Windows with your sample, that second Window has a totally different page on it. When you reopen it with the given Application State, that second window is the same as your first, trying to load the MainPage. That's wrong, it should be the WebView window and the Second Page window.

**Comment by rolfbjarne** [comment]
> @rolfbjarne Does what I say sound plausible?

Yes, that sounds plausible, but I'm not really an expert in State Restoration.

> Are there ways to clear out the State Restoration without removing the app?

I think @tstephansen figured out a way in his last comment.

**Comment by torfluor** [comment]
Just a note on the Saved Application State directories. If you set `Preferences.Default.Set("NSQuitAlwaysKeepsWindows", false);`
in your application, the application directory in the Saved Application State directory will automatically be deleted when you exit the app properly. To me this indicated that it's safe to delete the directory on startup as your workaround suggest, but I'm not at all an expert, I'm just another programmer that had a similar issue.

**Comment by drasticactions** [comment]
> Just a note on the Saved Application State directories. If you set `Preferences.Default.Set("NSQuitAlwaysKeepsWindows", false);` in your application, the application directory in the Saved Application State directory will automatically be deleted when you exit the app properly. To me this indicates that it's safe to delete the directory on startup as your workaround suggest, but I'm not at all an expert, I'm just another programmer that had a similar issue.

I had zero idea that preference existed! I can't find it on Apple's site, but trying it and looking online that seems like it's the right thing to do here. That info is probably worth putting in the docs CC @davidbritch

**Comment by torfluor** [comment]
From my testing the NSQuitAlwaysKeepsWindows setting only has effect when the program is shut down properly. So adding a manual check and delete like @tstephansen suggested in his workaround in addition might be wise in regards to crashes

**Comment by tstephansen** [comment]
> From my testing the NSQuitAlwaysKeepsWindows setting only has effect when the program is shut down properly. So adding a manual check and delete like @tstephansen suggested in his workaround in addition might be wise in regards to crashes

We could work around that by writing an empty txt file or something (I'd probably use a registry key or a settings file if this was a Win32 app) when the program closes successfully and checking to see if that file exists (and removing it) when the app starts. If the file doesn't exist then we can check to see if the state directory exists and remove that. Otherwise, we can just let the app start as it normally would.

**Comment by QianaJiao** [comment]
Verified this issue still repro on 17.6.9(415) with the sample project: [tstephansen/MauiWindowBug: Example repo for reproducing a dotnet Maui exception (github.com)](https://github.com/tstephansen/MauiWindowBug)

**Comment by mkArtakMSFT** [comment]
Looking through the details there is nothing Blazor specific that is causing the problem here. The issue seems to be related to the state preservation which is handled by MAUI + OS.

**Comment by brianmed** [comment]
I just had a similar issue in Maui + MacCatalyst.

I added ApplePersistenceIgnoreState and no windows were restored at startup.

```csharp
public class Program
{
	static void Main(string[] args)
	{
		Preferences.Default.Set("NSQuitAlwaysKeepsWindows", false);
		Preferences.Default.Set("ApplePersistenceIgnoreState", true);

		UIApplication.Main(args, null, typeof(AppDelegate));
	}
}
```
