### ISSUE TITLE
[Android] `ImageButton` causes app unresponsiveness

### ISSUE THREAD

**Issue by jns300** [dotnet/maui#17868]
### Description

The linked code contains the two most imported classes: `CustomImageButton` and `MainPage`.
In the class `CustomImageButton` images to present are created programmatically and added to a local cache:
```csharp
public void UpdateImage()
{
    Source = GetImage(clickCount++ % imageData.Length);
}

private ImageSource GetImage(int imageIndex)
{
    if (imageData[imageIndex] != null)
    {
        return imageData[imageIndex];
    }
    SKColor color1 = SKColor.FromHsv(rand.Next(255), 255f, 255f);
    SKColor color2 = SKColor.FromHsv(rand.Next(255), 255f, 255f);
    using SKBitmap newBitmap = new SKBitmap(64, 64);
    int width = newBitmap.Width;
    int height = newBitmap.Height;
    for (int i = 0; i < width; i++)
    {
        for (int j = 0; j < height; j++)
        {
            var color = i / 8 % 2 == j / 8 % 2 ? color1 : color2;
            newBitmap.SetPixel(i, j, color);
        }
    }
    using (MemoryStream ms = BitmapToStream(newBitmap))
    {
        byte[] byteArray = ms.ToArray();
        var imageSource = ImageSource.FromStream(() => new MemoryStream(byteArray));
        imageData[imageIndex] = imageSource;
        return imageSource;
    }
}
```
The class `MainPage` contains a column with a few custom images and a button that, when clicked, calls the `UpdateImage` method for each custom image:
```csharp
private void OnButtonClicked(object sender, EventArgs e)
{
    UpdateImages();
}

private void UpdateImages()
{
    foreach (var item in images)
    {
        item.UpdateImage();
    }
}
```
After a few clicks `AndroidRuntimeException` is throw: "Only the original thread that created a view hierarchy can touch its views". However, the main page still works correctly and the images change when the button is clicked. The problem appears at the attempt of opening a new page. Then the splash theme shows up and the app permanently stops responding.
Below is the image with tree screenshots: the second page, the main page and the second page when the app became unresponsive.

![image](https://github.com/dotnet/maui/assets/18332092/6159243c-4322-4250-bb42-1c4c2a7d6737)

### Steps to Reproduce

    1. Download project from the linked repository.
    2. Start the app on an Android emulator and click a few times on the button on the main page.
    3. Open another page.

### Link to public reproduction project repository

https://github.com/jns300/Bugs/tree/main/ImageButtonUpdateIssue

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12

### Relevant log output

```shell
Android.Util.AndroidRuntimeException: Only the original thread that created a view hierarchy can touch its views.
   at Java.Interop.JniEnvironment.StaticMethods.CallStaticVoidMethod(JniObjectReference type, JniMethodInfo method, JniArgumentValue* args) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/obj/Release/net7.0/JniEnvironment.g.cs:line 13250
   at Java.Interop.JniPeerMembers.JniStaticMethods.InvokeVoidMethod(String encodedMember, JniArgumentValue* parameters) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniStaticMethods.cs:line 97
   at Microsoft.Maui.PlatformInterop.LoadImageFromStream(ImageView imageView, Stream inputStream, IImageLoaderCallback callback) in D:\a\_work\1\s\src\Core\src\obj\Release
et7.0-android\generated\src\Microsoft.Maui.PlatformInterop.cs:line 443
   at Microsoft.Maui.StreamImageSourceService.LoadDrawableAsync(IImageSource imageSource, ImageView imageView, CancellationToken cancellationToken) in D:\a\_work\1\s\src\Core\src\ImageSources\StreamImageSourceService\StreamImageSourceService.Android.cs:line 28
  --- End of managed Android.Util.AndroidRuntimeException stack trace ---
android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
	at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:9321)
	at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:1772)
	at android.view.View.requestLayout(View.java:25697)
	at android.view.View.requestLayout(View.java:25697)
	at android.view.View.requestLayout(View.java:25697)
	at android.view.View.requestLayout(View.java:25697)
	at android.view.View.requestLayout(View.java:25697)
	at android.view.View.requestLayout(View.java:25697)
	at android.view.View.requestLayout(View.java:25697)
	at androidx.drawerlayout.widget.DrawerLayout.requestLayout(DrawerLayout.java:1353)
	at android.view.View.requestLayout(View.java:25697)
	at android.view.View.requestLayout(View.java:25697)
	at android.view.View.requestLayout(View.java:25697)
	at android.view.View.requestLayout(View.java:25697)
	at android.view.View.requestLayout(View.java:25697)
	at android.view.View.requestLayout(View.java:25697)
	at androidx.recyclerview.widget.RecyclerView.requestLayout(RecyclerView.java:4586)
	at android.view.View.requestLayout(View.java:25697)
	at android.view.View.requestLayout(View.java:25697)
	at android.view.View.requestLayout(View.java:25697)
	at android.view.View.requestLayout(View.java:25697)
	at androidx.core.widget.NestedScrollView.requestLayout(NestedScrollView.java:2075)
	at android.view.View.requestLayout(View.java:25697)
	at android.view.View.requestLayout(View.java:25697)
	at android.view.View.requestLayout(View.java:25697)
	at android.widget.ImageView.setImageDrawable(ImageView.java:601)
	at androidx.appcompat.widget.AppCompatImageView.setImageDrawable(AppCompatImageView.java:112)
	at com.microsoft.maui.glide.MauiCustomViewTarget.onResourceCleared(MauiCustomViewTarget.java:30)
	at com.bumptech.glide.request.target.CustomViewTarget.onLoadCleared(CustomViewTarget.java:210)
	at com.bumptech.glide.request.SingleRequest.clear(SingleRequest.java:337)
	at com.bumptech.glide.request.ErrorRequestCoordinator.clear(ErrorRequestCoordinator.java:48)
	at com.bumptech.glide.manager.RequestTracker.clearAndRemove(RequestTracker.java:70)
	at com.bumptech.glide.RequestManager.untrack(RequestManager.java:660)
	at com.bumptech.glide.RequestManager.untrackOrDelegate(RequestManager.java:628)
	at com.bumptech.glide.RequestManager.clear(RequestManager.java:624)
	at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:811)
	at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:780)
	at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:771)
	at com.microsoft.maui.PlatformInterop.prepare(PlatformInterop.java:229)
	at com.microsoft.maui.PlatformInterop.loadInto(PlatformInterop.java:234)
	at com.microsoft.maui.PlatformInterop.loadImageFromStream(PlatformInterop.java:265)

  --- End of managed Android.Util.AndroidRuntimeException stack trace ---
android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
	at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:9321)
	at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:1772)
	at android.view.View.requestLayout(View.java:25697)
	at android.view.View.requestLayout(View.java:25697)
	at android.view.View.requestLayout(View.java:25697)
	at android.view.View.requestLayout(View.java:25697)
	at android.view.View.requestLayout(View.java:25697)
	at android.view.View.requestLayout(View.java:25697)
	at android.view.View.requestLayout(View.java:25697)
	at androidx.drawerlayout.widget.DrawerLayout.requestLayout(DrawerLayout.java:1353)
	at android.view.View.requestLayout(View.java:25697)
	at android.view.View.requestLayout(View.java:25697)
	at android.view.View.requestLayout(View.java:25697)
	at android.view.View.requestLayout(View.java:25697)
	at android.view.View.requestLayout(View.java:25697)
	at android.view.View.requestLayout(View.java:25697)
	at androidx.recyclerview.widget.RecyclerView.requestLayout(RecyclerView.java:4586)
	at android.view.View.requestLayout(View.java:25697)
	at android.view.View.requestLayout(View.java:25697)
	at android.view.View.requestLayout(View.java:25697)
	at android.view.View.requestLayout(View.java:25697)
	at androidx.core.widget.NestedScrollView.requestLayout(NestedScrollView.java:2075)
	at android.view.View.requestLayout(View.java:25697)
	at android.view.View.requestLayout(View.java:25697)
	at android.view.View.requestLayout(View.java:25697)
	at android.widget.ImageView.setImageDrawable(ImageView.java:601)
	at androidx.appcompat.widget.AppCompatImageView.setImageDrawable(AppCompatImageView.java:112)
	at com.microsoft.maui.glide.MauiCustomViewTarget.onResourceCleared(MauiCustomViewTarget.java:30)
	at com.bumptech.glide.request.target.CustomViewTarget.onLoadCleared(CustomViewTarget.java:210)
	at com.bumptech.glide.request.SingleRequest.clear(SingleRequest.java:337)
	at com.bumptech.glide.request.ErrorRequestCoordinator.clear(ErrorRequestCoordinator.java:48)
	at com.bumptech.glide.manager.RequestTracker.clearAndRemove(RequestTracker.java:70)
	at com.bumptech.glide.RequestManager.untrack(RequestManager.java:660)
	at com.bumptech.glide.RequestManager.untrackOrDelegate(RequestManager.java:628)
	at com.bumptech.glide.RequestManager.clear(RequestManager.java:624)
	at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:811)
	at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:780)
	at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:771)
	at com.microsoft.maui.PlatformInterop.prepare(PlatformInterop.java:229)
	at com.microsoft.maui.PlatformInterop.loadInto(PlatformInterop.java:234)
	at com.microsoft.maui.PlatformInterop.loadImageFromStream(PlatformInterop.java:265)
```

**Comment by jns300** [comment]
This issue does not repro on the latest .NET MAUI version (8.0.0-rc.2.9373).
