### ISSUE TITLE
[Windows] `CollectionView` throws NRE when value of `IsGrouped` property is changed to `false`

### ISSUE THREAD

**Issue by jns300** [dotnet/maui#17864]
### Description

On Windows, object of the class `CollectionView` throws `NullReferenceException` when items' model is changed from grouped list to flat list and value of the `IsGrouped` property is set to `false`.

Below is how `CollectionView` is configured is XAML:
```xml
<CollectionView Grid.Row="2" ItemsSource="{Binding Items}" IsGrouped="{Binding IsGrouped}">
    <CollectionView.GroupHeaderTemplate>
        <DataTemplate>
            <Label Margin="2" FontSize="Medium" Text="{Binding ItemText}" HorizontalOptions="Fill" TextColor="LightBlue"/>
        </DataTemplate>
    </CollectionView.GroupHeaderTemplate>
    <CollectionView.ItemTemplate>
        <DataTemplate>
            <Label Margin="15,2" Text="{Binding ItemText}" HorizontalOptions="Fill" TextColor="Gray"/>
        </DataTemplate>
    </CollectionView.ItemTemplate>
</CollectionView>
```
Object of the class `ItemListViewModel` is set to `BindingContext`.  When the checkbox (located above the `CollectionView`) is clicked a new value is set to the `IsGrouped` property from class `ItemListViewModel` and the items' list is recreated:
```csharp
private void Populate()
{
    try
    {
        ErrorMessage = String.Empty;
        items.Clear();
        if (isGrouped)
        {
            int groupIndex = 0;
            items.Add(GetGroup(groupIndex++, 2));
            items.Add(GetGroup(groupIndex++, 1));
            items.Add(GetGroup(groupIndex++, 3));
            items.Add(GetGroup(groupIndex++, 2));
        }
        else
        {
            int itemIndex = 0;
            items.Add(new ItemViewModel(itemIndex++));
            items.Add(new ItemViewModel(itemIndex++));
            items.Add(new ItemViewModel(itemIndex++));
        }
    }
    catch (Exception ex)
    {
        ErrorMessage = $"Model creation error: {ex}";
    }
}
public bool IsGrouped
{
    get => isGrouped;
    set
    {
        isGrouped = value;
        Populate();
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(IsGrouped)));
    }
}
```
When the `IsGrouped` property value is changed from `false` to `true`, no exception is thrown and the `CollectionView` is correctly updated.
The problem does not exist on Android.

The main page just after the startup:

![image](https://github.com/dotnet/maui/assets/18332092/c2c9b47a-c23d-4d3b-9f24-47e2930cee11)

The main page after the checkbox was unchecked:

![image](https://github.com/dotnet/maui/assets/18332092/31855e80-9352-42da-a07a-88ac135522af)

### Steps to Reproduce

    1. Download the code of the linked project and start the app.
    2. Uncheck the check box with label "Is Grouping Active".

### Link to public reproduction project repository

https://github.com/jns300/Bugs/tree/main/CollectionViewGroupingIssue

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 11

### Relevant log output

```shell
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Maui.Controls.Platform.ItemTemplateContextEnumerable.GetEnumerator()+MoveNext()
   at ABI.System.Collections.IEnumerable.ToAbiHelper.NonGenericToGenericEnumerator.MoveNext()
   at ABI.System.Collections.Generic.IEnumerator`1.ToAbiHelper._MoveNext()
   at ABI.System.Collections.Generic.IEnumerator`1.ToAbiHelper.get_HasCurrent()
   at ABI.Microsoft.UI.Xaml.Interop.IBindableIterator.Vftbl.Do_Abi_get_HasCurrent_1(IntPtr thisPtr, Byte* value)
--- End of stack trace from previous location ---
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.System.Collections.Specialized.NotifyCollectionChangedEventHandler.NativeDelegateWrapper.Invoke(Object sender, NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at Microsoft.Maui.Controls.Platform.GroupedItemTemplateCollection.Add(NotifyCollectionChangedEventArgs args)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at CollectionViewGroupingIssue.ViewModel.ItemListViewModel.Populate()
```

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.8.0 Preview 2.0(8.0.0-rc.1.9171). Repro on Windows 11, not repro on Android 13.0-API33.
Repo: [CollectionViewGroupingIssue.zip](https://github.com/dotnet/maui/files/12854094/CollectionViewGroupingIssue.zip)

iOS: Different error than Windows platform.
![Grouping](https://github.com/dotnet/maui/assets/97647558/8c470f79-24eb-4ce4-b478-10697ec27875)
