### ISSUE TITLE
Java.Lang.IllegalStateException when resuming the App from an Android Autofill Service

### ISSUE THREAD

**Issue by dinisvieira** [dotnet/maui#18121]
### Description

When using an android app that has an Autofill Service if we create an intent for "Autofilling" a field that opens the app again the app crashes on `base.OnCreate();`
This only seems to happen when using a "non-shell" implementation.

The Activity used for that Intent doesn't seem to matter. On the reproduction sample two different activities can be chosen for opening the app from the Autofill Service but they both crash on `base.OnCreate()`.

### Steps to Reproduce

- Clone attached public repo
- Run app
- Press "Click Me" button
- On the Autofill service screen choose "Test Fill Service"
- Without closing the app open a browser
- Open a site with a text input field and tap on that input to get focus and an option overlay should appear
- Click the option "Click to Crash!"
- App will crash on Activity base.OnCreate()

Doing the same steps with `MainPage = new AppShell()` doesn't crash the app.

### Link to public reproduction project repository

https://github.com/dinisvieira/autofill-service-crash-repro/tree/main

### Version with bug

8.0.0-rc.2.9373

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 10 and up (at least)

### Did you find any workaround?

Using `new AppShell()` doesn't crash but this is not an option for us. We are migrating an entire "non-shell" app from Xamarin Forms.

### Relevant log output

```shell
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
	at androidx.fragment.app.FragmentManager.checkStateLoss(FragmentManager.java:1632)
	at androidx.fragment.app.FragmentManager.enqueueAction(FragmentManager.java:1672)
	at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:341)
	at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:306)
	at com.autofill.test.MainActivity.n_onCreate(Native Method)
	at com.autofill.test.MainActivity.onCreate(MainActivity.java:45)
	at android.app.Activity.performCreate(Activity.java:8657)
	at android.app.Activity.performCreate(Activity.java:8636)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1417)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4165)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4340)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2584)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8810)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

**Comment by mattleibow** [comment]
May be related https://github.com/dotnet/maui/issues/18159

**Comment by DharunAR** [comment]
If this issue cannot be fixed immediately. Do we have any workaround for this issue? I am facing the similar problem which I have reported under https://github.com/dotnet/maui/issues/18159. 

This is blocking our development migration from Xamarin to MAUI.

**Comment by PureWeen** [comment]
Duplicate of #11501
