### ISSUE TITLE
[regression/8.0.0-rc.2.9373] MultiBinding Throwing Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by cgp1976** [dotnet/maui#18123]
### Description

I am getting the following error

   at Microsoft.Maui.Controls.MultiBinding.Apply(Object context, BindableObject targetObject, BindableProperty targetProperty, Boolean fromBindingContextChanged, SetterSpecificity specificity)
   at Microsoft.Maui.Controls.BindableObject.RemoveBinding(BindableProperty property, BindablePropertyContext context, SetterSpecificity specificity)
   at Microsoft.Maui.Controls.BindableObject.RemoveBinding(BindableProperty property, SetterSpecificity specificity)
   at Microsoft.Maui.Controls.Setter.UnApply(BindableObject target, SetterSpecificity specificity)
   at Microsoft.Maui.Controls.TriggerBase.OnConditionChanged(BindableObject bindable, Boolean oldValue, Boolean newValue)
   at Microsoft.Maui.Controls.BindingCondition.OnBoundPropertyChanged(BindableObject bindable, Object oldValue, Object newValue)
   at Microsoft.Maui.Controls.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, SetterSpecificity specificity, Boolean silent)
   at Microsoft.Maui.Controls.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes, SetterSpecificity specificity)
   at Microsoft.Maui.Controls.BindingExpression.ApplyCore(Object sourceObject, BindableObject target, BindableProperty property, Boolean fromTarget, SetterSpecificity specificity)
   at Microsoft.Maui.Controls.BindingExpression.Apply(Boolean fromTarget)
   at Microsoft.Maui.Controls.BindingExpression.BindingExpressionPart.<PropertyChanged>b__50_0()
   at Microsoft.Maui.Controls.DispatcherExtensions.DispatchIfRequired(IDispatcher dispatcher, Action action)
   at Microsoft.Maui.Controls.BindingExpression.BindingExpressionPart.PropertyChanged(Object sender, PropertyChangedEventArgs args)
   at Microsoft.Maui.Controls.BindingExpression.WeakPropertyChangedProxy.OnPropertyChanged(Object sender, PropertyChangedEventArgs e)
   at Microsoft.Maui.Controls.BindableObject.OnPropertyChanged(String propertyName)
   at MauiApp3333.ViewModel.set_Mode(String value) in XXXXXXXXXXXXXXXX\MauiApp3333\MauiApp3333\MainPage.xaml.cs:line 15

[MauiApp3333.zip](https://github.com/dotnet/maui/files/13035408/MauiApp3333.zip)

### Steps to Reproduce

1. Run the project
2. Click on Button Edit
3. Click on Button Cancel  <-- over here will throw the error

Expected Behavior

1. After Clicking Button Edit
2. Button Edit Text Change to Submit
3. Button Delete Text Change to Cancel

1. After Clicking Button Cancel
2. Button Cancel Text Change to Delete
3. Button Submit Text Change to Edit

### Version with bug

8.0.0-rc.2.9373

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.0-rc.1.9171

### Affected platforms

Windows

**Comment by jsuarezruiz** [comment]
cc @StephaneDelcroix

**Comment by samhouts** [comment]
Confirmed that this regressed in [8.0.0-rc.2.9373](https://github.com/dotnet/maui/releases/tag/8.0.0-rc.2.9373). https://github.com/dotnet/maui/pull/17230 is likely culprit, @StephaneDelcroix

**Comment by StephaneDelcroix** [comment]
I can repro in a unittest, not related to #17320
