### ISSUE TITLE
WebViewNavigationManager has not been initialized [Bug] 

### ISSUE THREAD

**Issue by jirisykora83** [dotnet/maui#1823]
Error when call `NavigationManager` `NavigateTo`.

```
[chromium] [INFO:CONSOLE(1)] "'WebViewNavigationManager' has not been initialized.
[chromium]    at Microsoft.AspNetCore.Components.NavigationManager.AssertInitialized() in Microsoft.AspNetCore.Components.dll:token 0x600015c+0x30
[chromium]    at Microsoft.AspNetCore.Components.NavigationManager.NavigateTo(String uri, Boolean forceLoad) in Microsoft.AspNetCore.Components.dll:token 0x6000154+0x0
[chromium]    at Obletsvet.Ui.Mobile.Components.Services.PageHistoryState.GoBack() in C:\Projects\Obletsvet\Obletsvet\src\Obletsvet.Ui.Mobile.Components\Services\PageHistoryState.cs:line 44
[chromium]    at Obletsvet.Ui.Mobile.Components.Shared.TopBar.<BuildRenderTree>b__0_0() in C:\Projects\Obletsvet\Obletsvet\src\Obletsvet.Ui.Mobile.Components\Shared\TopBar.razor:line 19
[chromium]    at Microsoft.AspNetCore.Components.EventCallbackWorkItem.InvokeAsync[Object](MulticastDelegate delegate, Object arg) in Microsoft.AspNetCore.Components.dll:token 0x6000117+0x33
[chromium]    at Microsoft.AspNetCore.Components.EventCallbackWorkItem.InvokeAsync(Object arg) in Microsoft.AspNetCore.Components.dll:token 0x6000116+0x0
[chromium]    at Microsoft.AspNetCore.Components.ComponentBase.Microsoft.AspNetCore.Components.IHandleEvent.HandleEventAsync(EventCallbackWorkItem callback, Object arg) in Microsoft.AspNetCore.Components.dll:token 0x60000a3+0x0
[chromium]    at Microsoft.AspNetCore.Components.EventCallback.InvokeAsync(Object arg) in Microsoft.AspNetCore.Components.dll:token 0x60000db+0x26
[chromium]    at Microsoft.AspNetCore.Components.RenderTree.Renderer.DispatchEventAsync(UInt64 eventHandlerId, EventFieldInfo fieldInfo, EventArgs eventArgs) in Microsoft.AspNetCore.Components.dll:token 0x600022c+0x5e", source: https://0.0.0.0/_framework/blazor.webview.js (1)
```

### Basic Information

- Version with issue:
- Platform Target Frameworks:
  - Android: 10

**Comment by jirisykora83** [comment]
Again it seems like `NavigationManager` cannot be use in singleton.
