### ISSUE TITLE
How can I run my Maui projects with the Maui source code fully open to me in Visual Studio so I can test/solve bugs I find in the Maui code?

### ISSUE THREAD

**Issue by jonmdev** [dotnet/maui#18270]
### Description

I would like to solve or at least try to solve many of the bugs I am finding. In the 1-3 hours it takes me to make a bug report, I could easily right click some functions, Go To Definition, and comment in/out Maui code in the underlying source to try to find the problem or at least see where things are coming from. If I am lucky, maybe I can find the issue.

For example, I would love to solve the Border drawing bug here: https://github.com/dotnet/maui/issues/17882

I don't mind doing the work. It is driving me crazy that my Borders cannot draw to the expected size as nothing looks right in my project as a result (just as an example).

On that example, Borders from what I can tell are drawn here in Android:

https://github.com/dotnet/maui/blob/00495958371b63152fa61e2afc47d6de6f570bd1/src/Compatibility/Core/src/Android/Renderers/BorderDrawable.cs

I would love to track through the Maui code above that and then the Android code and see if I can narrow it down. It might (if I'm lucky) take me a few hours but this will save me endless hours of misaligned projects and potentially a very long time for someone at Microsoft to get to it given the backlog is now >1000 items long. No offense to MS devs is intended by saying that - it is just clear things are piling up I am guessing due to understaffing by MS on the Maui project.

So how can I do this and help? 

Can I just download the source Maui code and put it in a folder inside a non-Maui project and have it work?

What exactly would I have to do? If I can set up a simple sandbox where I can access all the Maui code and run my bug projects in it, I can put the time in to find the fixes myself.

This is just a matter for me of finding the fastest route to a working codebase, but it would benefit Microsoft as well as I will be happily providing free labor to the project.

Thanks for any help.

### Version with bug

7.0.96

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

7.0.49

### Affected platforms

iOS, Android, Windows

**Comment by tmijieux** [comment]
i'm not maui developer but i think the way is to try to follow these guidelines the best you can:
https://github.com/dotnet/maui/blob/main/.github/DEVELOPMENT.md 

(disclaimer i have NOT tried this recently at all, i succeeded to do this a long time ago on xamarin.forms, but when i tried to do this more recently (still xamarin forms) , it turned out that the provisioning scripts only worked on the platforms where it was officially supported, and i was on linux at this time so i did not have any success last time ) 

that is to say first ensure you have latest preview release of VS with .NET 8, 
do the "Building the build task"
then open the appropriate solution for your platform , then you can see there are "sample" projects inside the maui solution(in this repo)  that are setup to work with the code "in tree" (like what you are suggesting)

so if you can get the first steps workings then, 
you should probably try add your project to the solution and setup ProjectReferences , Properties and Imports as in these samples:
https://github.com/dotnet/maui/blob/main/src/Controls/samples/Controls.Sample.Profiling/Maui.Controls.Sample.Profiling.csproj

**Comment by jonmdev** [comment]
Thanks @tmijieux

I tried cloning the maui repo from GitHub, then just opening a cmd prompt, going to the folder holding the .gitconfig and other files and running:

```
H:\[mylocalpath]>dotnet tool restore
Skipping NuGet package signature verification.
Skipping NuGet package signature verification.
Unhandled exception: System.AggregateException: One or more errors occurred. (microsoft.dotnet.xharness.cli::[*, ) is not found in NuGet feeds https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json, https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-public/nuget/v3/index.json, https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json, https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet7/nuget/v3/index.json, https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet8/nuget/v3/index.json, https://pkgs.dev.azure.com/xamarin/public/_packaging/SkiaSharp/nuget/v3/index.json, https://pkgs.dev.azure.com/dnceng/public/_packaging/benchmark-dotnet-prerelease/nuget/v3/index.json".)
 ---> Microsoft.DotNet.Cli.NuGetPackageDownloader.NuGetPackageNotFoundException: microsoft.dotnet.xharness.cli::[*, ) is not found in NuGet feeds https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json, https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-public/nuget/v3/index.json, https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json, https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet7/nuget/v3/index.json, https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet8/nuget/v3/index.json, https://pkgs.dev.azure.com/xamarin/public/_packaging/SkiaSharp/nuget/v3/index.json, https://pkgs.dev.azure.com/dnceng/public/_packaging/benchmark-dotnet-prerelease/nuget/v3/index.json".
   at Microsoft.DotNet.Cli.NuGetPackageDownloader.NuGetPackageDownloader.GetMatchingVersionInternalAsync(String packageIdentifier, IEnumerable`1 packageSources, VersionRange versionRange, CancellationToken cancellationToken)
   at Microsoft.DotNet.Cli.NuGetPackageDownloader.NuGetPackageDownloader.GetBestPackageVersionAsync(PackageId packageId, VersionRange versionRange, PackageSourceLocation packageSourceLocation)
   at Microsoft.DotNet.Cli.ToolPackage.ToolPackageDownloader.<>c__DisplayClass8_0.<InstallPackage>b__0()
   at Microsoft.DotNet.Cli.TransactionalAction.Run[T](Func`1 action, Action commit, Action rollback)
   at Microsoft.DotNet.Tools.Tool.Restore.ToolRestoreCommand.InstallPackages(ToolManifestPackage package, Nullable`1 configFile)
   at Microsoft.DotNet.Tools.Tool.Restore.ToolRestoreCommand.<>c__DisplayClass10_0.<Execute>b__0(ToolManifestPackage package)
   at System.Linq.Parallel.SelectQueryOperator`2.SelectQueryOperatorResults.GetElement(Int32 index)
   at System.Linq.Parallel.QueryResults`1.get_Item(Int32 index)
   at System.Linq.Parallel.PartitionedDataSource`1.ListContiguousIndexRangeEnumerator.MoveNext(T& currentElement, Int32& currentKey)
   at System.Linq.Parallel.StopAndGoSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
   at System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose)
   at System.Linq.Parallel.SpoolingTask.SpoolStopAndGo[TInputOutput,TIgnoreKey](QueryTaskGroupState groupState, PartitionedStream`2 partitions, SynchronousChannel`1[] channels, TaskScheduler taskScheduler)
   at System.Linq.Parallel.DefaultMergeHelper`2.System.Linq.Parallel.IMergeHelper<TInputOutput>.Execute()
   at System.Linq.Parallel.MergeExecutor`1.Execute()
   at System.Linq.Parallel.MergeExecutor`1.Execute[TKey](PartitionedStream`2 partitions, Boolean ignoreOutput, ParallelMergeOptions options, TaskScheduler taskScheduler, Boolean isOrdered, CancellationState cancellationState, Int32 queryId)
   at System.Linq.Parallel.PartitionedStreamMerger`1.Receive[TKey](PartitionedStream`2 partitionedStream)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.QueryOperator`1.ExecuteAndGetResultsAsArray()
   at System.Linq.ParallelEnumerable.ToArray[TSource](ParallelQuery`1 source)
   at Microsoft.DotNet.Tools.Tool.Restore.ToolRestoreCommand.Execute()
   at System.CommandLine.Invocation.InvocationPipeline.Invoke(ParseResult parseResult)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
```

Do you know if there is something else I should be doing? Or what this means?

Also, is it possible to literally just copy the maui folders into a new Maui project, then delete the dependencies from the csproj? I feel like that should work - then it would be referencing the copied files for all the classes needed, no?

**Comment by drasticactions** [comment]
You need to install [XHarness](https://github.com/dotnet/xharness), the packages are not in the default Nuget feeds.

Or, remove it from the dotnet-tools.json

https://github.com/dotnet/maui/blob/main/.config/dotnet-tools.json#L23-L28

Then, running 

```
dotnet tool restore
dotnet cake --target=VS --workloads=global
```

In the root directory should provision what's needed and VS (or your editor/IDE of choice) should appear.
