### ISSUE TITLE
[Docs] How to publish 

### ISSUE THREAD

**Issue by jirisykora83** [dotnet/maui#1831]
Is in current state a option to publish app in way that it is possible to upload to Google play (possibly also for ios). In best case via cli (for CI).

**Comment by jirisykora83** [comment]
1.

properties on Maui project with last VS22 preview (2.1) not work

```
Microsoft.Assumes+InternalErrorException: Unable to parse version "5.0" in visibility condition expression.
   at Microsoft.Assumes.Fail(String message)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.PropertyPages.Designer.Expressions.VisibilityConditionEvaluator.<>c__DisplayClass2_0.<.ctor>g__HasTargetFrameworkMonikerVersionOrGreater|6(String prefix, String minimumVersionString)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.PropertyPages.Designer.Expressions.Function`2.TryInvoke(Object[] args, Object& result)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.PropertyPages.Designer.Expressions.EvaluationEnvironment.<Evaluate>g__Eval|2_1(Object node, <>c__DisplayClass2_0& )
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.PropertyPages.Designer.Expressions.EvaluationEnvironment.Evaluate(String expression)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.PropertyPages.Designer.Expressions.VisibilityConditionEvaluator.UpdateConditionalVisibilities()
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.PropertyPages.Designer.PropertyContext.UpdateConditionalVisibilities()
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.PropertyPages.Designer.PropertyContext.<SetProperties>g__Initialize|32_0(Property property, <>c__DisplayClass32_0& )
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.PropertyPages.Designer.PropertyContext.SetProperties(ImmutableArray`1 properties)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.PropertyPages.Designer.ProjectPropertyDataAccess.Observer.<OnNext>g__ProcessInitialData|10_1(<>c__DisplayClass10_0& )
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.PropertyPages.Designer.ProjectPropertyDataAccess.Observer.OnNext(IQueryResults`1 projects)
   at Microsoft.VisualStudio.ProjectSystem.Query.QueryExecution.QuerySubscription`1.<RunQueryOnceAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.Query.QueryExecution.QuerySubscription`1.<>c__DisplayClass8_0.<<Start>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.PropertyPages.Designer.ProjectPropertyDataAccess.Observer.<InitializeAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.PropertyPages.Designer.ProjectPropertyDataAccess.Observer.<CreateAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.PropertyPages.Designer.ProjectPropertiesEditor.<>c__DisplayClass0_0.<<-ctor>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.PropertyPages.Designer.AsyncLoadContent.<>c__DisplayClass0_0.<<Initialize>b__0>d.MoveNext()
```

It is actually not possible change anything with UI.


2.
Default template do not publish 64bit version so it is not accepted by google play. On internet is lot of information like use `AndroidSupportedAbis` which is actually outdated so it not work. What must be set is `RuntimeIdentifiers`. Which is documented here `https://docs.microsoft.com/en-us/dotnet/core/rid-catalog` unfortunately there is single "android" world on that page.

Any way if myself or any one in future try to find it I leave it here:

Add: `<RuntimeIdentifiers Condition="$(TargetFramework.Contains('-android'))">android-arm;android-arm64;android-x86;android-x64</RuntimeIdentifiers>` to csproj

3. as non xamarin developer (what could be currently more poepel) a leave it here what I do to publish (android) app.

a) set `RuntimeIdentifiers`
b) change project to `Release` (build?)
c) Right click on Maui project - archive
![image](https://user-images.githubusercontent.com/7279825/127508819-231cda88-9c6c-4050-9179-c6faf2592bd3.png)
d) wait & distribute

At current state of tooling i do not know if I want to try something as `GitHub Actions`. But I think it should be in new Maui docs.

**Comment by jirisykora83** [comment]
Ok i do not change anything and this option is now missing whole dev experience with MAUI is tragicomedy :/

**Comment by vickyanand25005** [comment]
Hi, @jirisykora83 I am trying to publish the App on Android. I have selected the Android Local device but when I do archive it shows iOS. Can you tell me if you are able to Publish the app.

Thanks

**Comment by jirisykora83** [comment]
Hi @vickyanand25005 honestly i am not sure because I use windows and for now it was easiest for me just remove iOS target from `.csproj` because I currently do not want to use it. Also, from some reason sometimes it not shows "Archive..." at all and need to make series of Clean & Rebuild. Whole process really painful. And also, I cannot use VS2019 stable/preview to publish app because same sign key what i use in VS22 do not work in VS19 (same password same key). 

Sorry for that, I cannot to help you but based on last commits it seems like they finishing preview 7 so if you absolutely do not need to publish app now i recommend to wait +- one week. After that maybe someone from MAUI team can make some statement on this issue.

**Comment by jirisykora83** [comment]
Hi @vickyanand25005 honestly i am not sure because I use windows and for now it was easiest for me just remove iOS target from `.csproj` because I currently do not want to use it. Also, from some reason sometimes it not shows "Archive..." at all and need to make series of Clean & Rebuild. Whole process really painful. And also, I cannot use VS2019 stable/preview to publish app because same sign key what i use in VS22 do not work in VS19 (same password same key). 

Sorry for that, I cannot to help you but based on last commits it seems like they finishing preview 7 so if you absolutely do not need to publish app now i recommend to wait +- one week. After that maybe someone from MAUI team can make some statement ont this issue.

**Comment by jsuarezruiz** [comment]
cc @davidbritch

**Comment by ParsaGachkar** [comment]
Any update on this matter?

**Comment by davidbritch** [comment]
Hi @ParsaGachkar 

Afraid there won't be a doc on publishing until MAUI launches.

**Comment by brzezinol** [comment]
I found some workaround.
When you deploy Release config to emulator, in bin folfer you could find signed apk file.

**Comment by ParsaGachkar** [comment]
> I found some workaround.
> When you deploy Release config to emulator, in bin folfer you could find signed apk file.

Technically you could just use

```
dotnet publish -c Release -f net6.0-android
```

But I don't think the `.signed` apk file is ready to be published. There should be a proper procedure to get your apk signed with a proper keystore.

**Comment by ParsaGachkar** [comment]
Guys how to get a Fat Apk instead of an aab package?

**Comment by ryuuc** [comment]
@ParsaGachkar add `<AndroidPackageFormat>apk</AndroidPackageFormat>`  to your .csproj file.

**Comment by AmirImam** [comment]
> I found some workaround. When you deploy Release config to emulator, in bin folfer you could find signed apk file.
This signed APK file could not be installed on devices

**Comment by AmirImam** [comment]
> I found some workaround. When you deploy Release config to emulator, in bin folfer you could find signed apk file.

This signed APK file could not be installed on devices

**Comment by jfversluis** [comment]
I'm working on figuring out how to deal with this process at the time being at least until there is a proper UI for it.

First on I have is for Windows in #4329

I also did a writeup on iOS and Android here: https://stackoverflow.com/questions/70437037/net-6-publishing-android-application but these aren't complete yet

**Comment by jfversluis** [comment]
For Android is now here: #4377

**Comment by jfversluis** [comment]
iOS one is now here: #4397 

Closing this issue for now. The official docs will come when .NET MAUI goes GA. At this time we do not recommend publishing apps to stores with .NET MAUI as it's still in preview.

Closing this for now, creating the docs is on our list, with the mentioned issues you should be able to continue for the time being.

Thanks!
