### ISSUE TITLE
[Android,iOS] Real device crash on navigation

### ISSUE THREAD

**Issue by NXDMN** [dotnet/maui#18372]
### Description

Whenever app launch on real device, Android and iOS, sometimes navigate to some pages will result in crash, i get the following output in logcat. Can help me to check what this log means?

### Version with bug

8.0.0-rc.2.9373

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Did you find any workaround?

No

### Relevant log output

```shell
android.runtime.JavaProxyThrowable: [System.InvalidOperationException]: InvalidOperation_ConcurrentOperationsNotSupported
at System.ThrowHelper.ThrowInvalidOperationException_ConcurrentOperationsNotSupported(Unknown Source:0)
at System.Collections.Generic.Dictionary`2[[Microsoft.Maui.Controls.BindableProperty, Microsoft.Maui.Controls, Version=*******, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Controls.BindableObject+BindablePropertyContext, Microsoft.Maui.Controls, Version=*******, Culture=neutral, PublicKeyToken=null]].FindValue(Unknown Source:0)
at System.Collections.Generic.Dictionary`2[[Microsoft.Maui.Controls.BindableProperty, Microsoft.Maui.Controls, Version=*******, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Controls.BindableObject+BindablePropertyContext, Microsoft.Maui.Controls, Version=*******, Culture=neutral, PublicKeyToken=null]].TryGetValue(Unknown Source:0)
at Microsoft.Maui.Controls.BindableObject.GetValue(Unknown Source:0)
at Microsoft.Maui.Controls.VisualElement.PropagateBindingContextToStateTriggers(Unknown Source:0)
at Microsoft.Maui.Controls.VisualElement.OnBindingContextChanged(Unknown Source:0)
at Microsoft.Maui.Controls.View.OnBindingContextChanged(Unknown Source:0)
at Microsoft.Maui.Controls.Label.OnBindingContextChanged(Unknown Source:0)
at Microsoft.Maui.Controls.BindableObject.SetInheritedBindingContext(Unknown Source:0)
at Microsoft.Maui.Controls.Element.SetChildInheritedBindingContext(Unknown Source:0)
at Microsoft.Maui.Controls.Element.<OnBindingContextChanged>b__93_0(Unknown Source:0)
at Microsoft.Maui.Controls.BindableObjectExtensions.PropagateBindingContext(Unknown Source:0)
at Microsoft.Maui.Controls.Element.OnBindingContextChanged(Unknown Source:0)
at Microsoft.Maui.Controls.VisualElement.OnBindingContextChanged(Unknown Source:0)
at Microsoft.Maui.Controls.View.OnBindingContextChanged(Unknown Source:0)
at Microsoft.Maui.Controls.Grid.OnBindingContextChanged(Unknown Source:0)
at Microsoft.Maui.Controls.BindableObject.SetInheritedBindingContext(Unknown Source:0)
at Microsoft.Maui.Controls.Element.SetChildInheritedBindingContext(Unknown Source:0)
at Microsoft.Maui.Controls.Element.<OnBindingContextChanged>b__93_0(Unknown Source:0)
at Microsoft.Maui.Controls.BindableObjectExtensions.PropagateBindingContext(Unknown Source:0)
at Microsoft.Maui.Controls.Element.OnBindingContextChanged(Unknown Source:0)
at Microsoft.Maui.Controls.VisualElement.OnBindingContextChanged(Unknown Source:0)
at Microsoft.Maui.Controls.View.OnBindingContextChanged(Unknown Source:0)
at Microsoft.Maui.Controls.BindableObject.SetInheritedBindingContext(Unknown Source:0)
at Microsoft.Maui.Controls.ContentView.OnBindingContextChanged(Unknown Source:0)
at Microsoft.Maui.Controls.BindableObject.SetInheritedBindingContext(Unknown Source:0)
at Microsoft.Maui.Controls.Element.SetChildInheritedBindingContext(Unknown Source:0)
at Microsoft.Maui.Controls.Element.<OnBindingContextChanged>b__93_0(Unknown Source:0)
at Microsoft.Maui.Controls.BindableObjectExtensions.PropagateBindingContext(Unknown Source:0)
at Microsoft.Maui.Controls.Element.OnBindingContextChanged(Unknown Source:0)
at Microsoft.Maui.Controls.Cell.OnBindingContextChanged(Unknown Source:0)
at Microsoft.Maui.Controls.BindableObject.BindingContextPropertyChanged(Unknown Source:0)
at Microsoft.Maui.Controls.BindableObject.SetValueActual(Unknown Source:0)
at Microsoft.Maui.Controls.BindableObject.SetValueCore(Unknown Source:0)
at Microsoft.Maui.Controls.BindableObject.SetValue(Unknown Source:0)
at Microsoft.Maui.Controls.BindableObject.set_BindingContext(Unknown Source:0)
at Microsoft.Maui.Controls.Internals.TemplatedItemsList`2[[Microsoft.Maui.Controls.ItemsView`1[[Microsoft.Maui.Controls.Cell, Microsoft.Maui.Controls, Version=*******, Culture=neutral, PublicKeyToken=null]], Microsoft.Maui.Controls, Version=*******, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Controls.Cell, Microsoft.Maui.Controls, Version=*******, Culture=neutral, PublicKeyToken=null]].UpdateContent(Unknown Source:0)
at Microsoft.Maui.Controls.Internals.TemplatedItemsList`2[[Microsoft.Maui.Controls.ItemsView`1[[Microsoft.Maui.Controls.Cell, Microsoft.Maui.Controls, Version=*******, Culture=neutral, PublicKeyToken=null]], Microsoft.Maui.Controls, Version=*******, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Controls.Cell, Microsoft.Maui.Controls, Version=*******, Culture=neutral, PublicKeyToken=null]].ActivateContent(Unknown Source:0)
at Microsoft.Maui.Controls.Internals.TemplatedItemsList`2[[Microsoft.Maui.Controls.ItemsView`1[[Microsoft.Maui.Controls.Cell, Microsoft.Maui.Controls, Version=*******, Culture=neutral, PublicKeyToken=null]], Microsoft.Maui.Controls, Version=*******, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Controls.Cell, Microsoft.Maui.Controls, Version=*******, Culture=neutral, PublicKeyToken=null]].CreateContent(Unknown Source:0)
at Microsoft.Maui.Controls.Internals.TemplatedItemsList`2[[Microsoft.Maui.Controls.ItemsView`1[[Microsoft.Maui.Controls.Cell, Microsoft.Maui.Controls, Version=*******, Culture=neutral, PublicKeyToken=null]], Microsoft.Maui.Controls, Version=*******, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Controls.Cell, Microsoft.Maui.Controls, Version=*******, Culture=neutral, PublicKeyToken=null]].GetOrCreateContent(Unknown Source:0)
at Microsoft.Maui.Controls.Internals.TemplatedItemsList`2[[Microsoft.Maui.Controls.ItemsView`1[[Microsoft.Maui.Controls.Cell, Microsoft.Maui.Controls, Version=*******, Culture=neutral, PublicKeyToken=null]], Microsoft.Maui.Controls, Version=*******, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Controls.Cell, Microsoft.Maui.Controls, Version=*******, Culture=neutral, PublicKeyToken=null]].get_Item(Unknown Source:0)
at Microsoft.Maui.Controls.Handlers.Compatibility.ListViewAdapter.GetCellsFromPosition(Unknown Source:0)
at Microsoft.Maui.Controls.Handlers.Compatibility.ListViewAdapter.GetCellForPosition(Unknown Source:0)
at Microsoft.Maui.Controls.Handlers.Compatibility.ListViewAdapter.GetView(Unknown Source:0)
at Android.Widget.BaseAdapter.n_GetView_ILandroid_view_View_Landroid_view_ViewGroup_(Unknown Source:0)
at Android.Runtime.DynamicMethodNameCounter.23(Unknown Source:0)
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Unknown Source:0)
at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualVoidMethod(Unknown Source:0)
at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeNonvirtualVoidMethod(Unknown Source:0)
at Android.Views.ViewGroup.Layout(Unknown Source:0)
at Microsoft.Maui.Controls.Handlers.Compatibility.VisualElementRenderer`1[[Microsoft.Maui.Controls.ListView, Microsoft.Maui.Controls, Version=*******, Culture=neutral, PublicKeyToken=null]].OnLayout(Unknown Source:0)
at Microsoft.Maui.Controls.Handlers.Compatibility.ListViewRenderer.OnLayout(Unknown Source:0)
at Android.Views.ViewGroup.n_OnLayout_ZIIII(Unknown Source:0)
at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPZIIII_V(Unknown Source:0)
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Unknown Source:0)
at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualVoidMethod(Unknown Source:0)
at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeNonvirtualVoidMethod(Unknown Source:0)
at Android.Views.ViewGroup.Layout(Unknown Source:0)
at Microsoft.Maui.ViewHandlerExtensions.PlatformArrangeHandler(Unknown Source:0)
at Microsoft.Maui.Controls.Handlers.Compatibility.VisualElementRenderer`1[[Microsoft.Maui.Controls.ListView, Microsoft.Maui.Controls, Version=*******, Culture=neutral, PublicKeyToken=null]].Microsoft.Maui.IViewHandler.PlatformArrange(Unknown Source:0)
at Microsoft.Maui.Controls.VisualElement.ArrangeOverride(Unknown Source:0)
at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IView.Arrange(Unknown Source:0)
at Microsoft.Maui.Layouts.GridLayoutManager.ArrangeChildren(Unknown Source:0)
at Microsoft.Maui.Controls.Layout.CrossPlatformArrange(Unknown Source:0)
at Microsoft.Maui.Platform.LayoutViewGroup.CrossPlatformArrange(Unknown Source:0)
at Microsoft.Maui.Platform.LayoutViewGroup.OnLayout(Unknown Source:0)
at Android.Views.ViewGroup.n_OnLayout_ZIIII(Unknown Source:0)
at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPZIIII_V(Unknown Source:0)
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Unknown Source:0)
at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualVoidMethod(Unknown Source:0)
at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeNonvirtualVoidMethod(Unknown Source:0)
at Android.Views.ViewGroup.Layout(Unknown Source:0)
at Microsoft.Maui.ViewHandlerExtensions.PlatformArrangeHandler(Unknown Source:0)
at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.ILayout, Microsoft.Maui, Version=*******, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.LayoutViewGroup, Microsoft.Maui, Version=*******, Culture=neutral, PublicKeyToken=null]].PlatformArrange(Unknown Source:0)
at Microsoft.Maui.Controls.VisualElement.ArrangeOverride(Unknown Source:0)
at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IView.Arrange(Unknown Source:0)
at Microsoft.Maui.Layouts.GridLayoutManager.ArrangeChildren(Unknown Source:0)
at Microsoft.Maui.Controls.AndExpandLayoutManager.ArrangeChildren(Unknown Source:0)
at Microsoft.Maui.Controls.StackLayoutManager.ArrangeChildren(Unknown Source:0)
at Microsoft.Maui.Controls.Layout.CrossPlatformArrange(Unknown Source:0)
at Microsoft.Maui.Platform.LayoutViewGroup.CrossPlatformArrange(Unknown Source:0)
at Microsoft.Maui.Platform.LayoutViewGroup.OnLayout(Unknown Source:0)
at Android.Views.ViewGroup.n_OnLayout_ZIIII(Unknown Source:0)
at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPZIIII_V(Unknown Source:0)
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Unknown Source:0)
at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualVoidMethod(Unknown Source:0)
at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeNonvirtualVoidMethod(Unknown Source:0)
at Android.Views.ViewGroup.Layout(Unknown Source:0)
at Microsoft.Maui.ViewHandlerExtensions.PlatformArrangeHandler(Unknown Source:0)
at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.ILayout, Microsoft.Maui, Version=*******, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.LayoutViewGroup, Microsoft.Maui, Version=*******, Culture=neutral, PublicKeyToken=null]].PlatformArrange(Unknown Source:0)
at Microsoft.Maui.Controls.VisualElement.ArrangeOverride(Unknown Source:0)
at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IView.Arrange(Unknown Source:0)
at Microsoft.Maui.Layouts.GridLayoutManager.ArrangeChildren(Unknown Source:0)
at Microsoft.Maui.Controls.Layout.CrossPlatformArrange(Unknown Source:0)
at Microsoft.Maui.Platform.LayoutViewGroup.CrossPlatformArrange(Unknown Source:0)
at Microsoft.Maui.Platform.LayoutViewGroup.OnLayout(Unknown Source:0)
at Android.Views.ViewGroup.n_OnLayout_ZIIII(Unknown Source:0)
at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPZIIII_V(Unknown Source:0)
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Unknown Source:0)
at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualVoidMethod(Unknown Source:0)
at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeNonvirtualVoidMethod(Unknown Source:0)
at Android.Views.ViewGroup.Layout(Unknown Source:0)
at Microsoft.Maui.ViewHandlerExtensions.PlatformArrangeHandler(Unknown Source:0)
at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.ILayout, Microsoft.Maui, Version=*******, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.LayoutViewGroup, Microsoft.Maui, Version=*******, Culture=neutral, PublicKeyToken=null]].PlatformArrange(Unknown Source:0)
at Microsoft.Maui.Controls.VisualElement.ArrangeOverride(Unknown Source:0)
at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IView.Arrange(Unknown Source:0)
at Microsoft.Maui.Layouts.GridLayoutManager.ArrangeChildren(Unknown Source:0)
at Microsoft.Maui.Controls.AndExpandLayoutManager.ArrangeChildren(Unknown Source:0)
at Microsoft.Maui.Controls.StackLayoutManager.ArrangeChildren(Unknown Source:0)
at Microsoft.Maui.Controls.Layout.CrossPlatformArrange(Unknown Source:0)
at Microsoft.Maui.Platform.LayoutViewGroup.CrossPlatformArrange(Unknown Source:0)
at Microsoft.Maui.Platform.LayoutViewGroup.OnLayout(Unknown Source:0)
at Android.Views.ViewGroup.n_OnLayout_ZIIII(Unknown Source:0)
at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPZIIII_V(Unknown Source:0)
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Unknown Source:0)
at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualVoidMethod(Unknown Source:0)
at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeNonvirtualVoidMethod(Unknown Source:0)
at Android.Views.ViewGroup.Layout(Unknown Source:0)
at Microsoft.Maui.ViewHandlerExtensions.PlatformArrangeHandler(Unknown Source:0)
at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.ILayout, Microsoft.Maui, Version=*******, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.LayoutViewGroup, Microsoft.Maui, Version=*******, Culture=neutral, PublicKeyToken=null]].PlatformArrange(Unknown Source:0)
at Microsoft.Maui.Controls.VisualElement.ArrangeOverride(Unknown Source:0)
at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IView.Arrange(Unknown Source:0)
at Microsoft.Maui.Layouts.GridLayoutManager.ArrangeChildren(Unknown Source:0)
at Microsoft.Maui.Controls.Layout.CrossPlatformArrange(Unknown Source:0)
at Microsoft.Maui.Platform.LayoutViewGroup.CrossPlatformArrange(Unknown Source:0)
at Microsoft.Maui.Platform.LayoutViewGroup.OnLayout(Unknown Source:0)
at Android.Views.ViewGroup.n_OnLayout_ZIIII(Unknown Source:0)
at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPZIIII_V(Unknown Source:0)
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Unknown Source:0)
at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualVoidMethod(Unknown Source:0)
at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeNonvirtualVoidMethod(Unknown Source:0)
at Android.Views.ViewGroup.Layout(Unknown Source:0)
at Microsoft.Maui.ViewHandlerExtensions.PlatformArrangeHandler(Unknown Source:0)
at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.ILayout, Microsoft.Maui, Version=*******, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.LayoutViewGroup, Microsoft.Maui, Version=*******, Culture=neutral, PublicKeyToken=null]].PlatformArrange(Unknown Source:0)
at Microsoft.Maui.Controls.VisualElement.ArrangeOverride(Unknown Source:0)
at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IView.Arrange(Unknown Source:0)
at Microsoft.Maui.Layouts.GridLayoutManager.ArrangeChildren(Unknown Source:0)
at Microsoft.Maui.Controls.AndExpandLayoutManager.ArrangeChildren(Unknown Source:0)
at Microsoft.Maui.Controls.StackLayoutManager.ArrangeChildren(Unknown Source:0)
at Microsoft.Maui.Controls.Layout.CrossPlatformArrange(Unknown Source:0)
at Microsoft.Maui.Platform.LayoutViewGroup.CrossPlatformArrange(Unknown Source:0)
at Microsoft.Maui.Platform.LayoutViewGroup.OnLayout(Unknown Source:0)
at Android.Views.ViewGroup.n_OnLayout_ZIIII(Unknown Source:0)
at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPZIIII_V(Unknown Source:0)
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Unknown Source:0)
at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualVoidMethod(Unknown Source:0)
at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeNonvirtualVoidMethod(Unknown Source:0)
at Android.Views.ViewGroup.Layout(Unknown Source:0)
at Microsoft.Maui.ViewHandlerExtensions.PlatformArrangeHandler(Unknown Source:0)
at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.ILayout, Microsoft.Maui, Version=*******, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.LayoutViewGroup, Microsoft.Maui, Version=*******, Culture=neutral, PublicKeyToken=null]].PlatformArrange(Unknown Source:0)
at Microsoft.Maui.Controls.VisualElement.ArrangeOverride(Unknown Source:0)
at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IView.Arrange(Unknown Source:0)
at Microsoft.Maui.Layouts.LayoutExtensions.ArrangeContent(Unknown Source:0)
at Microsoft.Maui.Controls.ContentPage.Microsoft.Maui.ICrossPlatformLayout.CrossPlatformArrange(Unknown Source:0)
at Microsoft.Maui.Platform.ContentViewGroup.CrossPlatformArrange(Unknown Source:0)
at Microsoft.Maui.Platform.ContentViewGroup.OnLayout(Unknown Source:0)
at Android.Views.ViewGroup.n_OnLayout_ZIIII(Unknown Source:0)
at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPZIIII_V(Unknown Source:0)
at crc6452ffdc5b34af3a0f.ContentViewGroup.n_onLayout(Native Method)
at crc6452ffdc5b34af3a0f.ContentViewGroup.onLayout(ContentViewGroup.java:67)
at android.view.View.layout(View.java:24072)
at android.view.ViewGroup.layout(ViewGroup.java:6484)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
at android.view.View.layout(View.java:24072)
at android.view.ViewGroup.layout(ViewGroup.java:6484)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
at android.view.View.layout(View.java:24072)
at android.view.ViewGroup.layout(ViewGroup.java:6484)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
at android.view.View.layout(View.java:24072)
at android.view.ViewGroup.layout(ViewGroup.java:6484)
at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:149)
at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:43)
at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:2376)
at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:953)
at android.view.View.layout(View.java:24072)
at android.view.ViewGroup.layout(ViewGroup.java:6484)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
at android.view.View.layout(View.java:24072)
at android.view.ViewGroup.layout(ViewGroup.java:6484)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
at android.view.View.layout(View.java:24072)
at android.view.ViewGroup.layout(ViewGroup.java:6484)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
at android.view.View.layout(View.java:24072)
at android.view.ViewGroup.layout(ViewGroup.java:6484)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
at android.view.View.layout(View.java:24072)
at android.view.ViewGroup.layout(ViewGroup.java:6484)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
at com.android.internal.policy.DecorView.onLayout(DecorView.java:1025)
at android.view.View.layout(View.java:24072)
at android.view.ViewGroup.layout(ViewGroup.java:6484)
at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4316)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3687)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2543)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9633)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1472)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1480)
at android.view.Choreographer.doCallbacks(Choreographer.java:1103)
at android.view.Choreographer.doFrame(Choreographer.java:1008)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1455)
at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:223)
at android.os.Looper.loop(Looper.java:324)
at android.app.ActivityThread.main(ActivityThread.java:8385)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1059)
```

**Comment by drasticactions** [comment]
Could you please create a small reproduction project of how to re-create your issue? Judging by the log, it could be something set up in your views but without knowing what they are it's difficult to diagnose.
