### ISSUE TITLE
androidx.collection.ArrayMapKt is defined multiple times

### ISSUE THREAD

**Issue by sabrigo** [dotnet/maui#18665]
### Description

I am creating a mobile app using .NET MAUI 7.0.  This mobile app will use Google OneTap signin facility for android.  However, when imported this nuget library Xamarin.GooglePlayServices.Auth, I get the below error.

I have attached the github repo to reproduce at your end.

[https://github.com/sabrigo/googlesignin](url)

### Steps to Reproduce

1. Create a new .NET MAUI APP with .NET 7.0
2.  Include nuget package Xamarin.GooglePlayServices.Auth
3. Compile the solution.

### Link to public reproduction project repository

https://github.com/sabrigo/googlesignin

### Version with bug

7.0.101

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Relevant log output

```shell
Build started...
1>------ Build started: Project: GoogleSignIn, Configuration: Debug Any CPU ------
1>GoogleSignIn -> D:\GoogleSignIn\bin\Debug\net7.0-maccatalyst\maccatalyst-x64\GoogleSignIn.dll
1>GoogleSignIn -> D:\GoogleSignIn\bin\Debug\net7.0-ios\iossimulator-x64\GoogleSignIn.dll
1>GoogleSignIn -> D:\GoogleSignIn\bin\Debug\net7.0-android\GoogleSignIn.dll
1>GoogleSignIn -> D:\GoogleSignIn\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\GoogleSignIn.dll
1>MSBUILD : java.exe error JAVA0000: Error in C:\Users\username\.nuget\packages\xamarin.androidx.collection.jvm\1.3.0.1\buildTransitive\net6.0-android31.0\..\..\jar\androidx.collection.collection-jvm.jar:androidx/collection/ArrayMapKt.class:
1>MSBUILD : java.exe error JAVA0000: Type androidx.collection.ArrayMapKt is defined multiple times: C:\Users\username\.nuget\packages\xamarin.androidx.collection.jvm\1.3.0.1\buildTransitive\net6.0-android31.0\..\..\jar\androidx.collection.collection-jvm.jar:androidx/collection/ArrayMapKt.class, C:\Users\username\.nuget\packages\xamarin.androidx.collection.ktx\1.2.0.5\buildTransitive\net6.0-android31.0\..\..\jar\androidx.collection.collection-ktx.jar:androidx/collection/ArrayMapKt.class
1>MSBUILD : java.exe error JAVA0000: Compilation failed
1>MSBUILD : java.exe error JAVA0000: java.lang.RuntimeException: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: C:\Users\username\.nuget\packages\xamarin.androidx.collection.jvm\1.3.0.1\buildTransitive\net6.0-android31.0\..\..\jar\androidx.collection.collection-jvm.jar
1>MSBUILD : java.exe error JAVA0000: androidx/collection/ArrayMapKt.class
1>MSBUILD : java.exe error JAVA0000: 	at com.android.tools.r8.internal.Fj.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:98)
1>MSBUILD : java.exe error JAVA0000: 	at com.android.tools.r8.D8.main(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:4)
1>MSBUILD : java.exe error JAVA0000: Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: C:\Users\username\.nuget\packages\xamarin.androidx.collection.jvm\1.3.0.1\buildTransitive\net6.0-android31.0\..\..\jar\androidx.collection.collection-jvm.jar:androidx/collection/ArrayMapKt.class
1>MSBUILD : java.exe error JAVA0000: 	at Version.fakeStackEntry(Version_3.3.75.java:0)
1>MSBUILD : java.exe error JAVA0000: 	at com.android.tools.r8.internal.Fj.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:75)
1>MSBUILD : java.exe error JAVA0000: 	at com.android.tools.r8.internal.Fj.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:28)
1>MSBUILD : java.exe error JAVA0000: 	at com.android.tools.r8.internal.Fj.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:27)
1>MSBUILD : java.exe error JAVA0000: 	at com.android.tools.r8.internal.Fj.b(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:2)
1>MSBUILD : java.exe error JAVA0000: 	at com.android.tools.r8.D8.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:22)
1>MSBUILD : java.exe error JAVA0000: 	at com.android.tools.r8.D8.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:17)
1>MSBUILD : java.exe error JAVA0000: 	at com.android.tools.r8.internal.Fj.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:85)
1>MSBUILD : java.exe error JAVA0000: 	... 1 more
1>MSBUILD : java.exe error JAVA0000: Caused by: com.android.tools.r8.internal.f: Type androidx.collection.ArrayMapKt is defined multiple times: C:\Users\username\.nuget\packages\xamarin.androidx.collection.jvm\1.3.0.1\buildTransitive\net6.0-android31.0\..\..\jar\androidx.collection.collection-jvm.jar:androidx/collection/ArrayMapKt.class, C:\Users\username\.nuget\packages\xamarin.androidx.collection.ktx\1.2.0.5\buildTransitive\net6.0-android31.0\..\..\jar\androidx.collection.collection-ktx.jar:androidx/collection/ArrayMapKt.class
1>MSBUILD : java.exe error JAVA0000: 	at com.android.tools.r8.internal.JT.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:14)
1>MSBUILD : java.exe error JAVA0000: 	at com.android.tools.r8.internal.JT.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:22)
1>MSBUILD : java.exe error JAVA0000: 	at com.android.tools.r8.internal.HN.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:33)
1>MSBUILD : java.exe error JAVA0000: 	at com.android.tools.r8.internal.HN.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:10)
1>MSBUILD : java.exe error JAVA0000: 	at java.base/java.util.concurrent.ConcurrentHashMap.merge(ConcurrentHashMap.java:2048)
1>MSBUILD : java.exe error JAVA0000: 	at com.android.tools.r8.internal.HN.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:6)
1>MSBUILD : java.exe error JAVA0000: 	at com.android.tools.r8.graph.B2$a.e(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:4)
1>MSBUILD : java.exe error JAVA0000: 	at com.android.tools.r8.dex.b.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:110)
1>MSBUILD : java.exe error JAVA0000: 	at com.android.tools.r8.dex.b.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:28)
1>MSBUILD : java.exe error JAVA0000: 	at com.android.tools.r8.D8.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:25)
1>MSBUILD : java.exe error JAVA0000: 	at com.android.tools.r8.D8.d(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:606)
1>MSBUILD : java.exe error JAVA0000: 	at com.android.tools.r8.D8.c(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:1)
1>MSBUILD : java.exe error JAVA0000: 	at com.android.tools.r8.internal.Fj.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:24)
1>MSBUILD : java.exe error JAVA0000: 	... 5 more
1>MSBUILD : java.exe error JAVA0000:
1>Done building project "GoogleSignIn.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Build started at 10:37 AM and took 43.825 seconds ==========
```

**Comment by PureWeen** [comment]
@moljac thoughts?

**Comment by moljac** [comment]
> ### Is this a regression from previous behavior?
> Yes, this used to work in Xamarin.Forms

Oh yaeah and I was born in 1968 when XF used to work.

Try updating to latest nugets... 

And paste here `PackageReference`s

I saw that error somewhere but old butt like me cannot remember any-amore

**Comment by sabrigo** [comment]
the version of the library (Xamarin.GooglePlayServices.Auth) worked is 119.2.0.3 in XF

Below is the one in the new .net 7.0, where it isn't working

```
<ItemGroup Condition="'$(TargetFramework)' == 'net7.0-android'">
  <PackageReference Include="Xamarin.GooglePlayServices.Auth">
     <Version>120.7.0.1</Version>
  </PackageReference>
</ItemGroup>
```

**Comment by moljac** [comment]
> the version of the library (Xamarin.GooglePlayServices.Auth) worked is 119.2.0.3 in XF

It is much more complicated. Something is transitively pulling in older nugets. I did analysis and found one for now.

Can you try adding explicitly this nuget, please?

```
		<PackageReference Include="Xamarin.AndroidX.Fragment.Ktx">
			<Version>1.6.2</Version>
		</PackageReference>
```

It worked on my sample. 

If that helps please report it here (I need it for analysis and record) and close this issue please.

> 
> Below is the one in the new .net 7.0, where it isn't working

Yup. I was able to repro.

> 
> ```
> <ItemGroup Condition="'$(TargetFramework)' == 'net7.0-android'">
>   <PackageReference Include="Xamarin.GooglePlayServices.Auth">
>      <Version>120.7.0.1</Version>
>   </PackageReference>
> </ItemGroup>
> ```

**Comment by moljac** [comment]
@PureWeen 

One of the reasons is also

https://github.com/dotnet/maui/pull/18690

This PR fails on public DeviceTests -  xharness seems to crash.
 
AndroidX versions used by MAUI are behind pulling transitively older versions with types that were moved by google to new artifacts. 

| NuGet package                                    | MAUI       | Latest        |
|--------------------------------------------------|------------|---------------|
| Xamarin.AndroidX.AppCompat.AppCompatResources    | 1.6.1.4    | 1.6.1.6       |
| Xamarin.AndroidX.Browser                         | 1.5.0.2    | 1.6.0.2       |
| Xamarin.AndroidX.SwipeRefreshLayout              | 1.1.0.14   | 1.1.0.16      |
| Xamarin.AndroidX.Lifecycle.LiveData              | 2.6.1.3    | 2.6.2.2       |
| Xamarin.AndroidX.Navigation.UI                   | 2.6.0.1    | 2.7.5         |
| Xamarin.AndroidX.Navigation.Runtime              | 2.6.0.1    | 2.7.5         |
| Xamarin.AndroidX.Navigation.Common               | 2.6.0.1    | 2.7.5         |
| Xamarin.AndroidX.Navigation.Fragment             | 2.6.0.1    | 2.7.5         |
| Xamarin.AndroidX.MediaRouter                     | 1.4.0.2    | 1.6.0.1       |
| Xamarin.AndroidX.Palette                         | 1.0.0.19   | 1.0.0.21      |
| Xamarin.AndroidX.RecyclerView                    | 1.3.1      | 1.3.2         |
| Xamarin.Google.Android.Material                  | 1.9.0.2    | 1.10.0.1      |
| Xamarin.Google.Android.Material                  | 1.9.0.2    | 1.10.0.1      |
| Xamarin.AndroidX.Window.WindowJava               | 1.1.0.1    | 1.1.0.3       |

Important: for this error patch numbers are very important (so called alignment bumps)

**Comment by sabrigo** [comment]
@moljac  including this package worked.

```
		<PackageReference Include="Xamarin.AndroidX.Fragment.Ktx">
			<Version>1.6.2</Version>
		</PackageReference>
```

**Comment by SushmithaBanoji** [comment]
@moljac 

<PackageReference Include="Xamarin.AndroidX.Fragment.Ktx">
			<Version>1.6.2</Version>
		</PackageReference>
		
this did not worked for me. 

I get the below error

Severity	Code	Description	Project	File	Line
Error	JAVA0000	Error in C:\Users\SushmithaBanoji\.nuget\packages\xamarin.androidx.collection.jvm\1.3.0.1\buildTransitive\net6.0-android31.0\..\..\jar\androidx.collection.collection-jvm.jar:androidx/collection/ArrayMapKt.class:
Type androidx.collection.ArrayMapKt is defined multiple times: C:\Users\SushmithaBanoji\.nuget\packages\xamarin.androidx.collection.jvm\1.3.0.1\buildTransitive\net6.0-android31.0\..\..\jar\androidx.collection.collection-jvm.jar:androidx/collection/ArrayMapKt.class, C:\Users\SushmithaBanoji\.nuget\packages\xamarin.androidx.collection.ktx\1.2.0.5\buildTransitive\net6.0-android31.0\..\..\jar\androidx.collection.collection-ktx.jar:androidx/collection/ArrayMapKt.class
Compilation failed
java.lang.RuntimeException: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: C:\Users\SushmithaBanoji\.nuget\packages\xamarin.androidx.collection.jvm\1.3.0.1\buildTransitive\net6.0-android31.0\..\..\jar\androidx.collection.collection-jvm.jar
androidx/collection/ArrayMapKt.class
	at com.android.tools.r8.internal.Fj.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:98)
	at com.android.tools.r8.D8.main(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:4)
Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: C:\Users\SushmithaBanoji\.nuget\packages\xamarin.androidx.collection.jvm\1.3.0.1\buildTransitive\net6.0-android31.0\..\..\jar\androidx.collection.collection-jvm.jar:androidx/collection/ArrayMapKt.class
	at Version.fakeStackEntry(Version_3.3.75.java:0)
	at com.android.tools.r8.internal.Fj.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:75)
	at com.android.tools.r8.internal.Fj.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:28)
	at com.android.tools.r8.internal.Fj.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:27)
	at com.android.tools.r8.internal.Fj.b(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:2)
	at com.android.tools.r8.D8.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:22)
	at com.android.tools.r8.D8.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:17)
	at com.android.tools.r8.internal.Fj.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:85)
	... 1 more
Caused by: com.android.tools.r8.internal.f: Type androidx.collection.ArrayMapKt is defined multiple times: C:\Users\SushmithaBanoji\.nuget\packages\xamarin.androidx.collection.jvm\1.3.0.1\buildTransitive\net6.0-android31.0\..\..\jar\androidx.collection.collection-jvm.jar:androidx/collection/ArrayMapKt.class, C:\Users\SushmithaBanoji\.nuget\packages\xamarin.androidx.collection.ktx\1.2.0.5\buildTransitive\net6.0-android31.0\..\..\jar\androidx.collection.collection-ktx.jar:androidx/collection/ArrayMapKt.class
	at com.android.tools.r8.internal.JT.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:14)
	at com.android.tools.r8.internal.JT.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:22)
	at com.android.tools.r8.internal.HN.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:33)
	at com.android.tools.r8.internal.HN.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:10)
	at java.base/java.util.concurrent.ConcurrentHashMap.merge(ConcurrentHashMap.java:2048)
	at com.android.tools.r8.internal.HN.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:6)
	at com.android.tools.r8.graph.B2$a.e(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:4)
	at com.android.tools.r8.dex.b.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:110)
	at com.android.tools.r8.dex.b.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:28)
	at com.android.tools.r8.D8.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:25)
	at com.android.tools.r8.D8.d(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:606)
	at com.android.tools.r8.D8.c(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:1)
	at com.android.tools.r8.internal.Fj.a(R8_3.3.75_b7a6ff6b13548611571508fe72282c9167faa649161ca0013edfc92e19bd7e58:24)
	... 5 more
	
	i have installed the following packages
	
	<PackageReference Include="Xamarin.Firebase.Messaging">
	    <Version>123.3.1</Version>
	  </PackageReference>
	  <PackageReference Include="Xamarin.Google.Dagger">
	    <Version>2.48.1</Version>
	  </PackageReference>
	  <PackageReference Include="Xamarin.GooglePlayServices.Base">
	    <Version>118.2.0.4</Version>
	  </PackageReference>

**Comment by Mirksar** [comment]
@SushmithaBanoji 
For me it's working with these packages:

```
<PackageReference Include="Xamarin.Firebase.Messaging" Version="123.2.1.1" />
<PackageReference Include="Xamarin.AndroidX.Fragment.Ktx" Version="1.6.2"/>
```

**Comment by matteomonizza** [comment]
Adding <PackageReference Include="Xamarin.AndroidX.Fragment.Ktx" Version="1.6.2"/> worked fir me

**Comment by wakeboardfit** [comment]
> Adding "Xamarin.AndroidX.Fragment.Ktx" worked fir me

Thanks matteomonizza.  This also fixed my issues with upgrading our MAUI project to .net 8.

**Comment by zleao** [comment]
For me, this configuration did the trick (migrating to .Net 8)
```xml
<PackageReference Include="Xamarin.Firebase.Messaging">
	<Version>123.3.1</Version>
</PackageReference>
<PackageReference Include="Xamarin.AndroidX.Fragment.Ktx ">
	<Version>1.6.2.1</Version>
</PackageReference>
```

**Comment by dgerding** [comment]
Getting same error, I think.

Anything I can do to help report more?

Thanks.

Severity	Code	Description	Project	File	Line	Suppression State
Error	JAVA0000	.... nuget\packages\xamarin.androidx.collection.jvm\1.3.0.2\buildTransitive\net7.0-android33.0\..\..\jar\androidx.collection.collection-jvm.jar:androidx/collection/ArraySetKt.class:
Type androidx.collection.ArraySetKt is defined multiple times: 
 ....nuget\packages\xamarin.androidx.collection.jvm\1.3.0.2\buildTransitive\net7.0-android33.0\..\..\jar\androidx.collection.collection-jvm.jar:androidx/collection/ArraySetKt.class, C:\Users\David Gerding\.nuget\packages\xamarin.androidx.collection.ktx\1.2.0.9\buildTransitive\net6.0-android31.0\..\..\jar\androidx.collection.collection-ktx.jar:androidx/collection/ArraySetKt.class
Compilation failed
java.lang.RuntimeException: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: ....nuget\packages\xamarin.androidx.collection.jvm\1.3.0.2\buildTransitive\net7.0-android33.0\..\..\jar\androidx.collection.collection-jvm.jar
androidx/collection/ArraySetKt.class
	at com.android.tools.r8.utils.R0.a(R8_8.1.56_756d1f50f618dd1c39c000f11defb367a21e9e866e3401b884be16c0950f6f79:126)
	at com.android.tools.r8.D8.main(R8_8.1.56_756d1f50f618dd1c39c000f11defb367a21e9e866e3401b884be16c0950f6f79:5)
Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: ...nuget\packages\xamarin.androidx.collection.jvm\1.3.0.2\buildTransitive\net7.0-android33.0\..\..\jar\androidx.collection.collection-jvm.jar:androidx/collection/ArraySetKt.class
	at Version.fakeStackEntry(Version_8.1.56.java:0)
	at com.android.tools.r8.M.a(R8_8.1.56_756d1f50f618dd1c39c000f11defb367a21e9e866e3401b884be16c0950f6f79:5)
	at com.android.tools.r8.utils.R0.a(R8_8.1.56_756d1f50f618dd1c39c000f11defb367a21e9e866e3401b884be16c0950f6f79:81)
	at com.android.tools.r8.utils.R0.a(R8_8.1.56_756d1f50f618dd1c39c000f11defb367a21e9e866e3401b884be16c0950f6f79:32)
	at com.android.tools.r8.utils.R0.a(R8_8.1.56_756d1f50f618dd1c39c000f11defb367a21e9e866e3401b884be16c0950f6f79:31)
	at com.android.tools.r8.utils.R0.b(R8_8.1.56_756d1f50f618dd1c39c000f11defb367a21e9e866e3401b884be16c0950f6f79:2)
	at com.android.tools.r8.D8.a(R8_8.1.56_756d1f50f618dd1c39c000f11defb367a21e9e866e3401b884be16c0950f6f79:26)
	at com.android.tools.r8.D8.b(R8_8.1.56_756d1f50f618dd1c39c000f11defb367a21e9e866e3401b884be16c0950f6f79:13)
	at com.android.tools.r8.D8.a(R8_8.1.56_756d1f50f618dd1c39c000f11defb367a21e9e866e3401b884be16c0950f6f79:24)
	at com.android.tools.r8.utils.R0.a(R8_8.1.56_756d1f50f618dd1c39c000f11defb367a21e9e866e3401b884be16c0950f6f79:113)
	... 1 more
Caused by: com.android.tools.r8.utils.b: Type androidx.collection.ArraySetKt is defined multiple times: ...nuget\packages\xamarin.androidx.collection.jvm\1.3.0.2\buildTransitive\net7.0-android33.0\..\..\jar\androidx.collection.collection-jvm.jar:androidx/collection/ArraySetKt.class, C:\Users\David Gerding\.nuget\packages\xamarin.androidx.collection.ktx\1.2.0.9\buildTransitive\net6.0-android31.0\..\..\jar\androidx.collection.collection-ktx.jar:androidx/collection/ArraySetKt.class
	at com.android.tools.r8.utils.O2.a(R8_8.1.56_756d1f50f618dd1c39c000f11defb367a21e9e866e3401b884be16c0950f6f79:21)
	at com.android.tools.r8.utils.O2.a(R8_8.1.56_756d1f50f618dd1c39c000f11defb367a21e9e866e3401b884be16c0950f6f79:26)
	at com.android.tools.r8.utils.A2.a(R8_8.1.56_756d1f50f618dd1c39c000f11defb367a21e9e866e3401b884be16c0950f6f79:44)
	at com.android.tools.r8.utils.A2.a(R8_8.1.56_756d1f50f618dd1c39c000f11defb367a21e9e866e3401b884be16c0950f6f79:10)
	at java.base/java.util.concurrent.ConcurrentHashMap.merge(ConcurrentHashMap.java:2056)
	at com.android.tools.r8.utils.A2.a(R8_8.1.56_756d1f50f618dd1c39c000f11defb367a21e9e866e3401b884be16c0950f6f79:6)
	at com.android.tools.r8.graph.b4$a.e(R8_8.1.56_756d1f50f618dd1c39c000f11defb367a21e9e866e3401b884be16c0950f6f79:7)
	at com.android.tools.r8.dex.c.a(R8_8.1.56_756d1f50f618dd1c39c000f11defb367a21e9e866e3401b884be16c0950f6f79:58)
	at com.android.tools.r8.dex.c.a(R8_8.1.56_756d1f50f618dd1c39c000f11defb367a21e9e866e3401b884be16c0950f6f79:9)
	at com.android.tools.r8.dex.c.a(R8_8.1.56_756d1f50f618dd1c39c000f11defb367a21e9e866e3401b884be16c0950f6f79:8)
	at com.android.tools.r8.D8.a(R8_8.1.56_756d1f50f618dd1c39c000f11defb367a21e9e866e3401b884be16c0950f6f79:29)
	at com.android.tools.r8.D8.d(R8_8.1.56_756d1f50f618dd1c39c000f11defb367a21e9e866e3401b884be16c0950f6f79:17)
	at com.android.tools.r8.D8.c(R8_8.1.56_756d1f50f618dd1c39c000f11defb367a21e9e866e3401b884be16c0950f6f79:1)
	at com.android.tools.r8.utils.R0.a(R8_8.1.56_756d1f50f618dd1c39c000f11defb367a21e9e866e3401b884be16c0950f6f79:28)
	... 6 more

**Comment by iooovolts** [comment]
@zleao I tried your solution and I have loads of compile-time errors as shown below
![image](https://github.com/dotnet/maui/assets/24354331/b8c21a8c-73ff-433e-806c-151d45fd9f28)

**Comment by mfeingol** [comment]
Thanks, @mikelor. For some reason I forgot to check for updates. This appears to work:

```xml
  <ItemGroup Condition="'$(TargetFramework)' == 'net8.0-android34.0'">
    <PackageReference Include="Xamarin.GooglePlayServices.Location" Version="121.0.1.4" />
    <PackageReference Include="Xamarin.AndroidX.Activity" Version="1.8.1.1" />
    <PackageReference Include="Xamarin.AndroidX.Activity.Ktx" Version="1.8.1.1" />
    <PackageReference Include="Xamarin.AndroidX.Fragment.Ktx" Version="1.6.2.1" />
  </ItemGroup>
```

(The firebase reference isn't needed, at least in my case.)
