### ISSUE TITLE
MAUI Android Release

### ISSUE THREAD

**Issue by Igor-9309** [dotnet/maui#18768]
### Description

But I have discovered that my application runs successfully with EFCore-SQLite only in debug.
Whenever I publish for android then crash at startup.

EFCore version: 8.0.0
MAUI version: 8.0.3

```
android.runtime.JavaProxyThrowable: [System.ArgumentNullException]: ArgumentNull_Generic Arg_ParamName_Name, source
	at System.Linq.ThrowHelper.ThrowArgumentNullException(Unknown Source:0)
	at System.Linq.Enumerable.All(Unknown Source:0)
	at Microsoft.EntityFrameworkCore.Metadata.Conventions.ValueGenerationConvention.GetValueGenerated(Unknown Source:0)
	at Microsoft.EntityFrameworkCore.Metadata.Conventions.RelationalValueGenerationConvention.GetValueGenerated(Unknown Source:0)
	at Microsoft.EntityFrameworkCore.Metadata.Conventions.RelationalValueGenerationConvention.GetValueGenerated(Unknown Source:0)
	at Microsoft.EntityFrameworkCore.Metadata.Conventions.ValueGenerationConvention.ProcessEntityTypePrimaryKeyChanged(Unknown Source:0)
	at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher+ImmediateConventionScope.OnEntityTypePrimaryKeyChanged(Unknown Source:0)
	at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher+OnEntityTypePrimaryKeyChangedNode.Run(Unknown Source:0)
	at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher+DelayedConventionScope.Run(Unknown Source:0)
	at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher+ConventionBatch.Run(Unknown Source:0)
	at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher+ConventionBatch.Dispose(Unknown Source:0)
	at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher+ImmediateConventionScope.OnModelInitialized(Unknown Source:0)
	at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnModelInitialized(Unknown Source:0)
	at Microsoft.EntityFrameworkCore.Metadata.Internal.Model..ctor(Unknown Source:0)
	at Microsoft.EntityFrameworkCore.ModelBuilder..ctor(Unknown Source:0)
	at Microsoft.EntityFrameworkCore.ModelConfigurationBuilder.CreateModelBuilder(Unknown Source:0)
	at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(Unknown Source:0)
	at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(Unknown Source:0)
	at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel(Unknown Source:0)
	at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model(Unknown Source:0)
```

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.101

### Affected platforms

Android

**Comment by drasticactions** [comment]
If you try creating a .NET Android app without the MAUI UI Framework (`dotnet new android`) and perform the same functions, does it crash there?

In all likelihood, based on that stacktrace, this will most likely fail when running on .NET Android all together regardless of the UI Framework; this will either be an issue with EFCore, or the dotnet runtime.

**Comment by Igor-9309** [comment]
Hi @drasticactions 

The repository will contain minimal code and a test app here.
The test device is a Redmi Note 10 running Android 12.

https://github.com/Igor-9309/MauiApp9.git

**Comment by BioTurboNick** [comment]
This apparently is because EFCore doesn't yet support things like AOT compilation, and support for that may not come for a while. However, you can safely drop back to EFCore 7 while using MAUI 8.

**Comment by Igor-9309** [comment]
Hi @BioTurboNick 
I rewrote this, it disables AOT
Not working
```
  <!-- Publish -->
  <PropertyGroup Condition="$(TargetFramework.Contains('-android')) and '$(Configuration)' == 'Release'">
    <AndroidPackageFormat>apk</AndroidPackageFormat>
    <AndroidKeyStore>False</AndroidKeyStore>
    <RunAOTCompilation>False</RunAOTCompilation>
    <AndroidEnableProfiledAot>False</AndroidEnableProfiledAot>
  </PropertyGroup>
```

**Comment by mattleibow** [comment]
@jonathanpeppers thoughts?

**Comment by mattleibow** [comment]
@Igor-9309 could you attach a binlog so we can also make sure AOT is not enabled via some other method/property: https://github.com/xamarin/xamarin-macios/wiki/Diagnosis

**Comment by Igor-9309** [comment]
I added the Release option to generate logs.
https://github.com/Igor-9309/MauiApp9-NOAOT.git
dotnet build .\MauiApp9.sln /bl:out.binlog -p:Configuration=Release

[out.zip](https://github.com/dotnet/maui/files/13392881/out.zip)

**Comment by mattleibow** [comment]
I tested on the Debug build and I got this error:

```

Loaded assembly: /data/data/com.companyname.mauiapp9/files/.__override__/_Microsoft.Android.Resource.Designer.dll [External]
[mono-rt] [ERROR] FATAL UNHANDLED EXCEPTION: System.ArgumentException: Format of the initialization string does not conform to specification starting at index 0.
[mono-rt]    at System.Data.Common.DbConnectionOptions.GetKeyValuePair(String connectionString, Int32 currentPosition, StringBuilder buffer, Boolean useOdbcRules, String& keyname, String& keyvalue)
[mono-rt]    at System.Data.Common.DbConnectionOptions.ParseInternal(Dictionary`2 parsetable, String connectionString, Boolean buildChain, Dictionary`2 synonyms, Boolean firstKey)
[mono-rt]    at System.Data.Common.DbConnectionOptions..ctor(String connectionString, Dictionary`2 synonyms, Boolean useOdbcRules)
[mono-rt]    at System.Data.Common.DbConnectionStringBuilder.set_ConnectionString(String value)
[mono-rt]    at Microsoft.Data.Sqlite.SqliteConnectionStringBuilder..ctor(String connectionString)
[mono-rt]    at Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal.SqliteDatabaseCreator.Exists()
[mono-rt]    at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.EnsureCreated()
[mono-rt]    at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.EnsureCreated()
[mono-rt]    at MauiApp9.MainApplication.OnCreate() in /Users/matthew/Downloads/MauiApp9-main/MauiApp9/src/MauiApp9/Platforms/Android/MainApplication.cs:line 17
[mono-rt]    at Android.App.Application.n_OnCreate(IntPtr jnienv, IntPtr native__this) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net8.0/android-34/mcw/Android.App.Application.cs:line 1087
[mono-rt]    at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(_JniMarshal_PP_V callback, IntPtr jnienv, IntPtr klazz) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 26
```

Am I missing something?

**Comment by BurkusCat** [comment]
Getting the below error on .NET 8 MAUI Android release mode with `<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.0" />`. Not on app startup but when you first visit a page that calls the database.

<details>
  <summary>Error log</summary>
System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument )
System.Linq.Enumerable.All[IReadOnlyForeignKey](IEnumerable`1 source, Func`2 predicate)
Microsoft.EntityFrameworkCore.Metadata.Conventions.ValueGenerationConvention.GetValueGenerated(IReadOnlyProperty property)
Microsoft.EntityFrameworkCore.Metadata.Conventions.RelationalValueGenerationConvention.GetValueGenerated(IReadOnlyProperty property, StoreObjectIdentifier& storeObject)
Microsoft.EntityFrameworkCore.Metadata.Conventions.RelationalValueGenerationConvention.GetValueGenerated(IConventionProperty property)
Microsoft.EntityFrameworkCore.Metadata.Conventions.ValueGenerationConvention.ProcessEntityTypePrimaryKeyChanged(IConventionEntityTypeBuilder entityTypeBuilder, IConventionKey newPrimaryKey, IConventionKey previousPrimaryKey, IConventionContext`1 context)
Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnEntityTypePrimaryKeyChanged(IConventionEntityTypeBuilder entityTypeBuilder, IConventionKey newPrimaryKey, IConventionKey previousPrimaryKey)
Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnEntityTypePrimaryKeyChangedNode.Run(ConventionDispatcher dispatcher)
Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.DelayedConventionScope.Run(ConventionDispatcher dispatcher)
Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionBatch.Run()
Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionBatch.Dispose()
Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelInitialized(IConventionModelBuilder modelBuilder)
Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnModelInitialized(IConventionModelBuilder modelBuilder)
Microsoft.EntityFrameworkCore.Metadata.Internal.Model..ctor(ConventionSet conventions, ModelDependencies modelDependencies, ModelConfiguration modelConfiguration)
Microsoft.EntityFrameworkCore.ModelBuilder..ctor(ConventionSet conventions, ModelDependencies modelDependencies, ModelConfiguration modelConfiguration)
Microsoft.EntityFrameworkCore.ModelConfigurationBuilder.CreateModelBuilder(ModelDependencies modelDependencies)
Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, ModelDependencies modelDependencies)
Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, ModelCreationDependencies modelCreationDependencies, Boolean designTime)
Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel(Boolean designTime)
Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
Microsoft.EntityFrameworkCore.DbContext.get_Model()
Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1[[Catlists.Data.Models.SeedModel, Catlists.Data, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].get_EntityType()
Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1[[Catlists.Data.Models.SeedModel, Catlists.Data, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].CheckState()
Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1[[Catlists.Data.Models.SeedModel, Catlists.Data, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].get_EntityQueryable()
Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1[[Catlists.Data.Models.SeedModel, Catlists.Data, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].System.Collections.Generic.IEnumerable<TEntity>.GetEnumerator()
System.Linq.Enumerable.SelectEnumerableIterator`2[[Catlists.Data.Models.SeedModel, Catlists.Data, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Catlists.Game.Seed, Catlists, Version=1.22.1.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
System.Collections.Generic.EnumerableHelpers.ToArray[Seed](IEnumerable`1 , Int32& )
System.Linq.Buffer`1[[Catlists.Game.Seed, Catlists, Version=1.22.1.0, Culture=neutral, PublicKeyToken=null]]..ctor(IEnumerable`1 )
System.Linq.OrderedEnumerable`1.<GetEnumerator>d__4[[Catlists.Game.Seed, Catlists, Version=1.22.1.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
System.Collections.Generic.List`1[[Catlists.Game.Seed, Catlists, Version=1.22.1.0, Culture=neutral, PublicKeyToken=null]]..ctor(IEnumerable`1 )
System.Collections.ObjectModel.ObservableCollection`1[[Catlists.Game.Seed, Catlists, Version=1.22.1.0, Culture=neutral, PublicKeyToken=null]]..ctor(IEnumerable`1 )
Catlists.ViewModels.CustomGamesViewModel.OnNavigatedTo(NavigationParameters parameters)
Burkus.Mvvm.Maui.LifecycleEventUtility.TriggerOnNavigatedTo(Object bindingContext, NavigationParameters navigationParameters)
Burkus.Mvvm.Maui.NavigationService.<HandleNavigation>d__14`1[[Catlists.Pages.CustomGamesPage, Catlists, Version=1.22.1.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
Burkus.Mvvm.Maui.NavigationService.<Push>d__1`1[[Catlists.Pages.CustomGamesPage, Catlists, Version=1.22.1.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
Burkus.Mvvm.Maui.NavigationService.<Push>d__0`1[[Catlists.Pages.CustomGamesPage, Catlists, Version=1.22.1.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
Catlists.ViewModels.HomeViewModel.CustomGame()
CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task )
System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
Android.App.SyncContext.<>c__DisplayClass2_0.<Post>b__0()
Java.Lang.Thread.RunnableImplementor.Run()
Java.Lang.IRunnableInvoker.n_Run(IntPtr jnienv, IntPtr native__this)
Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(_JniMarshal_PP_V callback, IntPtr jnienv, IntPtr klazz)
```
</details>

Based on @BioTurboNick 's comment, I reverted back to `<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="7.0.13" />` which does resolve the problem. Hopefully we can get a fix for the latest version of the package.

**Comment by MatthiasNistl** [comment]
Got the same error after upgrading to .NET 8. As mentioned before by @Igor-9309 not while debugging, only after the App has been published to Android.
Downgrading back to `<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="7.0.14" />` solved the issue.

```
System.ArgumentNullException:
   at System.Linq.ThrowHelper.ThrowArgumentNullException (System.Linq, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
   at System.Linq.Enumerable.All (System.Linq, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.ValueGenerationConvention.GetValueGenerated (Microsoft.EntityFrameworkCore, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.RelationalValueGenerationConvention.GetValueGenerated (Microsoft.EntityFrameworkCore.Relational, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.RelationalValueGenerationConvention.GetValueGenerated (Microsoft.EntityFrameworkCore.Relational, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.ValueGenerationConvention.ProcessForeignKeyAdded (Microsoft.EntityFrameworkCore, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher+ImmediateConventionScope.OnForeignKeyAdded (Microsoft.EntityFrameworkCore, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher+OnForeignKeyAddedNode.Run (Microsoft.EntityFrameworkCore, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher+DelayedConventionScope.Run (Microsoft.EntityFrameworkCore, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher+ConventionBatch.Run (Microsoft.EntityFrameworkCore, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher+ConventionBatch.Dispose (Microsoft.EntityFrameworkCore, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher+ImmediateConventionScope.OnModelInitialized (Microsoft.EntityFrameworkCore, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnModelInitialized (Microsoft.EntityFrameworkCore, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Model..ctor (Microsoft.EntityFrameworkCore, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at Microsoft.EntityFrameworkCore.ModelBuilder..ctor (Microsoft.EntityFrameworkCore, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at Microsoft.EntityFrameworkCore.ModelConfigurationBuilder.CreateModelBuilder (Microsoft.EntityFrameworkCore, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel (Microsoft.EntityFrameworkCore, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel (Microsoft.EntityFrameworkCore, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel (Microsoft.EntityFrameworkCore, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
```

**Comment by Igor-9309** [comment]
Hi!

Yes, this is how it works, and from my side, the issue can be considered closed.

Thx

**Comment by BurkusCat** [comment]
> Hi!
> 
> Yes, this is how it works, and from my side, the issue can be considered closed.
> 
> Thx

I think the issue still exists in .NET 8. Reverting to the .NET 7 package is only a temporary workaround.

**Comment by BioTurboNick** [comment]
It's an EFCore issue though, not a MAUI issue. And they already have an issue.

Though if it's worth keeping this around to direct people, I suggest the title be changed to reflect the underlying problem.

**Comment by vallgrenerik** [comment]
I'm also facing this issue. 
I can confirm that using EF version 7.0.14 but still targeting .NET 8 works in release mode on Android.

**Comment by vallgrenerik** [comment]
What is the best option? Disable AOT or running EF in version 7.0.14? 😊

**Comment by jenscski** [comment]
Looks like someone already reported it to the EF Core team, https://github.com/dotnet/efcore/issues/32040

**Comment by wesleyscaldwell** [comment]
I'm sharing this here as it might help others. 
Once again, I'm not sure why or how this solved it. So it might cause other problems. But it allowed me to continue. 

I added this to the csproj and then it added the migration.

```<WindowsAppSdkDeploymentManagerInitialize>false</WindowsAppSdkDeploymentManagerInitialize>```

[https://github.com/dotnet/efcore/issues/32384#issuecomment-1822959876](url)

**Comment by malsabi** [comment]
Can someone explain to me why EF Core 7 works while EF Core 8 does not ? What's the difference ?

**Comment by fekberg** [comment]
I've got the same issue and downgrading to 7.0.14 was the only way I could get it working.

**Comment by lewing** [comment]
`dotnet/runtime` is probably the right place, it sounds like an efcore change in 8.0 that is hitting some problem in the mono  codegen. @steveisok can you take a look.
