### ISSUE TITLE
[regression/8.0.3]  Android - Cannot create instance of type, no Java peer type found

### ISSUE THREAD

**Issue by kernshen** [dotnet/maui#18819]
### Description

Encountered this while upgrading my project to .Net Maui 8.

The error occurs when you have a class library with a class that derives from a base class inheriting from Java.Lang.Object in another class library.

### Steps to Reproduce

1. Create a .NET Maui 8 class library with a base class inheriting from Java.Lang.Object
MauiLib1
- BaseClass
- DerivedClass1 : No error when creating an instance

2. Create a .NET Maui 8 mobile app with a derived class of the base class in step 1.
MauiApp1
- DerivedClass2  : No error when creating an instance

3. Create a .Net Maui 8 class library with a derived class of the base class in step 1.
MauiLib2
- DerivedClass3

4. Create an instance of all 3 derived class in mobile app in step 2.
Only System.NotSupportedException Message=Cannot create instance of type 'MauiLib2.DerivedClass3': no Java peer type found.

### Link to public reproduction project repository

https://github.com/kernshen/NoJavaPeer.git

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.49

### Affected platforms

Android

### Did you find any workaround?

Move derived class from class library to MauiApp project.

### Relevant log output

```shell
Only System.NotSupportedException Message=Cannot create instance of type 'MauiLib2.DerivedClass3': no Java peer type found.

 at Java.Interop.JniPeerMembers.JniInstanceMethods..ctor(Type declaringType) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods.cs:line 22
   at Java.Interop.JniPeerMembers.JniInstanceMethods.GetConstructorsForType(Type declaringType) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods.cs:line 77
   at Java.Interop.JniPeerMembers.JniInstanceMethods.StartCreateInstance(String constructorSignature, Type declaringType, JniArgumentValue* parameters) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods.cs:line 139
   at Java.Lang.Object..ctor() in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net8.0/android-34/mcw/Java.Lang.Object.cs:line 37
   at MauiLib1.BaseClass..ctor()
   at MauiLib2.DerivedClass..ctor() in C:\Project\Maui\MauiApp1\MauiLib2\Platforms\Android\DerivedClass.cs:line 7
   at MauiApp1.App..ctor(IServiceProvider serviceProvider) in C:\Project\Maui\MauiApp1\MauiApp1\App.xaml.cs:line 18
```

**Comment by drasticactions** [comment]
Could you try reproducing this in a .NET Android app without the MAUI UI tooling? (`dotnet new android`)

This feels like something that would fail regardless of the MAUI UI Framework, if it fails in a .NET Android app then this should probably be moved to [xamarin-android](https://github.com/xamarin/xamarin-android).

**Comment by kernshen** [comment]
@drasticactions, indeed it fails in a .NET Android app (added to [repos](https://github.com/kernshen/NoJavaPeer.git)).

**Comment by drasticactions** [comment]
@jonathanpeppers Do you feel this is a xamarin-android issue? Could we please move it there if it is?

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio 17.10.0 Preview 1. Can repro on Android platform with sample project.
![image](https://github.com/dotnet/maui/assets/77434865/9312b93a-0005-4f05-90c2-dcd8a8f62b63)
https://github.com/kernshen/NoJavaPeer.git
