### ISSUE TITLE
NRE in GridViewLayout.HandlePropertyChanged

### ISSUE THREAD

**Issue by mypp74** [dotnet/maui#18828]
### Description

Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Maui.Controls.Handlers.Items.GridViewLayout.HandlePropertyChanged(PropertyChangedEventArgs propertyChanged)
   at Microsoft.Maui.Controls.Handlers.Items.ItemsViewLayout.LayoutOnPropertyChanged(Object sender, PropertyChangedEventArgs propertyChanged)
   at Microsoft.Maui.Controls.BindableObject.OnPropertyChanged(String propertyName)
   at Microsoft.Maui.Controls.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, SetterSpecificity specificity, Boolean silent)
   at Microsoft.Maui.Controls.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes, SetterSpecificity specificity)
   at Microsoft.Maui.Controls.BindingExpression.ApplyCore(Object sourceO
bject, BindableObject target, BindableProperty property, Boolean fromTarget, SetterSpecificity specificity)
   at Microsoft.Maui.Controls.BindingExpression.Apply(Boolean fromTarget)
   at Microsoft.Maui.Controls.BindingExpression.BindingExpressionPart.<PropertyChanged>b__50_0()
   at Microsoft.Maui.Controls.DispatcherExtensions.DispatchIfRequired(IDispatcher dispatcher, Action action)
   at Microsoft.Maui.Controls.BindingExpression.BindingExpressionPart.PropertyChanged(Object sender, PropertyChangedEventArgs args)
   at Microsoft.Maui.Controls.BindingExpression.WeakPropertyChangedProxy.OnPropertyChanged(Object sender, PropertyChangedEventArgs e)
   at Microsoft.Maui.Controls.BindableObject.OnPropertyChanged(String propertyName)
   at Microsoft.Maui.Controls.Element.OnPropertyChanged(String propertyName)
   at Microsoft.Maui.Controls.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, SetterSpecificity spec
ificity, Boolean silent)
   at Microsoft.Maui.Controls.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes, SetterSpecificity specificity)
   at Microsoft.Maui.Controls.BindableObject.SetValue(BindablePropertyKey propertyKey, Object value)
   at Microsoft.Maui.Controls.VisualElement.set_Width(Double value)
   at Microsoft.Maui.Controls.VisualElement.UpdateBoundsComponents(Rect bounds)
   at Microsoft.Maui.Controls.VisualElement.set_Frame(Rect value)
   at Microsoft.Maui.Controls.ContentPage.Microsoft.Maui.ICrossPlatformLayout.CrossPlatformArrange(Rect bounds)
   at Microsoft.Maui.Platform.MauiView.CrossPlatformArrange(Rect bounds)
   at Microsoft.Maui.Platform.MauiView.LayoutSubviews()
   at Microsoft.Maui.Platform.ContentView.LayoutSubviews()
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIAppl
ication.cs:line 58
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 94
   at Dopnet.YourDive.Maui.Program.Main(String[] args) in D:\YourDive\Dopnet.YourDive.Maui\Platforms\iOS\Program.cs:line 13

### Steps to Reproduce

The problem occurs when clicking on one of the grid elements. The grid is composed of dynamically loaded images.

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iPhone 15 iOS 17.0 (simulator)

**Comment by drasticactions** [comment]
Without the context of what your collection view contains, it's hard to know what's causing that specific property to be null. If you could create a reproduction project to help us debug it, that would be great. Thanks!

**Comment by mypp74** [comment]
Hello, I reproduced the problem in a simple case. There is no need to click.

<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:app="clr-namespace:MauiApp2"
             x:Class="MauiApp2.MainPage"
             x:Name="Page">
    <ContentPage.Resources>
        <app:WidthToSpanConverter x:Key="WidthToSpan" />
    </ContentPage.Resources>
    <CollectionView>
        <CollectionView.ItemsLayout>
            <GridItemsLayout Orientation="Vertical"
                             Span="{Binding Source={x:Reference Page}, Path=Width, Converter={StaticResource WidthToSpan}}" />
        </CollectionView.ItemsLayout>
    </CollectionView>
</ContentPage>



using System.Globalization;

namespace MauiApp2
{
    public class WidthToSpanConverter : IValueConverter
    {
        public object? Convert(object? value, Type targetType, object? parameter, CultureInfo culture)
        {
            if (value is double width)
            {
                int result = (int)Math.Floor(width / 160d);
                return Math.Max(1, result);
            }
            else
            {
                return 1;
            }
        }

        public object? ConvertBack(object? value, Type targetType, object? parameter, CultureInfo culture)
        {
            throw new NotImplementedException();
        }
    }
}

**Comment by mypp74** [comment]
Hello, I reproduced the problem in a simple case. There is no need to click.

`<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:app="clr-namespace:MauiApp2"
             x:Class="MauiApp2.MainPage"
             x:Name="Page">
    <ContentPage.Resources>
        <app:WidthToSpanConverter x:Key="WidthToSpan" />
    </ContentPage.Resources>
    <CollectionView>
        <CollectionView.ItemsLayout>
            <GridItemsLayout Orientation="Vertical"
                             Span="{Binding Source={x:Reference Page}, Path=Width, Converter={StaticResource WidthToSpan}}" />
        </CollectionView.ItemsLayout>
    </CollectionView>
</ContentPage>`


`using System.Globalization;

namespace MauiApp2
{
    public class WidthToSpanConverter : IValueConverter
    {
        public object? Convert(object? value, Type targetType, object? parameter, CultureInfo culture)
        {
            if (value is double width)
            {
                int result = (int)Math.Floor(width / 160d);
                return Math.Max(1, result);
            }
            else
            {
                return 1;
            }
        }

        public object? ConvertBack(object? value, Type targetType, object? parameter, CultureInfo culture)
        {
            throw new NotImplementedException();
        }
    }
}`

**Comment by mypp74** [comment]
Hello, I reproduced the problem in a simple case. There is no need to click.

<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:app="clr-namespace:MauiApp2"
             x:Class="MauiApp2.MainPage"
             x:Name="Page">
    <ContentPage.Resources>
        <app:WidthToSpanConverter x:Key="WidthToSpan" />
    </ContentPage.Resources>
    <CollectionView>
        <CollectionView.ItemsLayout>
            <GridItemsLayout Orientation="Vertical"
                             Span="{Binding Source={x:Reference Page}, Path=Width, Converter={StaticResource WidthToSpan}}" />
        </CollectionView.ItemsLayout>
    </CollectionView>
</ContentPage>

using System.Globalization;

namespace MauiApp2
{
    public class WidthToSpanConverter : IValueConverter
    {
        public object? Convert(object? value, Type targetType, object? parameter, CultureInfo culture)
        {
            if (value is double width)
            {
                int result = (int)Math.Floor(width / 160d);
                return Math.Max(1, result);
            }
            else
            {
                return 1;
            }
        }

        public object? ConvertBack(object? value, Type targetType, object? parameter, CultureInfo culture)
        {
            throw new NotImplementedException();
        }
    }
}

**Comment by mypp74** [comment]
Hello, I reproduced the problem in a simple case. There is no need to click.
[MauiApp2.zip](https://github.com/dotnet/maui/files/13399960/MauiApp2.zip)

**Comment by kubaflo** [comment]
@mypp74 fix here https://github.com/dotnet/maui/pull/20492
