### ISSUE TITLE
[regression/8.0.0-preview.5.8529] Crash on scrolling collection view

### ISSUE THREAD

**Issue by MissedSte4k** [dotnet/maui#18834]
### Description

App just crashes with `Java.Lang.RuntimeException: 'Canvas: trying to use a recycled bitmap android.graphics.Bitmap@4b0165b'`
Seems like the same issue as [before](https://github.com/dotnet/maui/issues/11130). This should be solved [here](https://github.com/dotnet/maui/pull/12310), but in every 8.0.* revision it seems to still be crashing (and I've tried them all). 

Here is the call stack. It always seems to be the same. The very odd thing in it is the reference to net7.0/JniEnvironment.g.cs. As the version I'm runing the app is .net8 ¯\_(ツ)_/¯
![image](https://github.com/dotnet/maui/assets/36638029/7e7d8083-dd0d-4b11-b3fa-a6b6ee0bd785)
 

### Steps to Reproduce

1. open my repository in github (it has some redundant parts from testing over issues, but does the job)
2. run on android emulator
3. wait for a minute until it crashes (try to stay on the top of the page, so new images appear and push over images down)

Expected behavior: images open up and older images are pushed down

Actual behavior: images open up and older images are pushed down, but after about a minute you experience a crash with Java.Lang.RuntimeException: 'Canvas: trying to use a recycled bitmap android.graphics.Bitmap@4b0165b

P.S. for anyone that might launch the app on windows and see the insane behavior of DataTemplates - I already reported it [here](https://github.com/dotnet/maui/issues/8811), over a year back.

### Link to public reproduction project repository

https://github.com/MissedSte4k/MAUI-Canvas-trying-to-use-a-recycled-bitmap-crash-sample

### Version with bug

8.0.0-preview.5.8529

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.0-preview.4.8333

### Affected platforms

Android

### Did you find any workaround?

Nope. Tried everything referenced in issues that got solved in https://github.com/dotnet/maui/pull/12310, but to no avail.

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.9.0 Preview 1(8.0.3). Repro on Android 14.0-API34 with below Project:
[TestImages.zip](https://github.com/dotnet/maui/files/13610412/TestImages.zip)

![image](https://github.com/dotnet/maui/assets/97647558/1b155d45-ce6a-4a42-8246-b44ff3795577)

**Comment by Stefan171086** [comment]
@samhouts: what is the status on this issue? We experiencing the same crashes and this is preventing us releasing an urgent update to our customers! Please help. BR

**Comment by stoff99** [comment]
Same here,

we get the same crashes in our public app right now with couple of devices.
We have a simple screen to collect photos with the device camera and place this images into a horizontal scrolling collection view.

We see the same error as above: 
'Java.Interop.JniEnvironment.InstanceMethods.CallNonvirtualBooleanMethod(JniObjectReference , JniObjectReference , JniMethodInfo , JniArgumentValue* )
Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualBooleanMethod(String , IJavaPeerable , JniArgumentValue* )
Android.Views.ViewGroup.DrawChild(Canvas , View , Int64 )
Microsoft.Maui.Controls.Platform.Compatibility.ShellFlyoutRenderer.DrawChild(Canvas canvas, View child, Int64 drawingTime)
Android.Views.ViewGroup.n_DrawChild_Landroid_graphics_Canvas_Landroid_view_View_J(IntPtr jnienv, IntPtr native__this, IntPtr native_canvas, IntPtr native_child, Int64 drawingTime)
Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPLLJ_Z(_JniMarshal_PPLLJ_Z callback, IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, Int64 p2)
com.microsoft.maui.PlatformContentViewGroup.dispatchDraw PlatformContentViewGroup.java:47
android.view.View.draw View.java:25151
androidx.recyclerview.widget.RecyclerView.drawChild RecyclerView.java:5499
android.view.ViewGroup.dispatchDraw ViewGroup.java:4534
androidx.recyclerview.widget.RecyclerView.draw RecyclerView.java:4898
android.view.View.updateDisplayListIfDirty View.java:24007
androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild CoordinatorLayout.java:1312
android.view.ViewGroup.dispatchDraw ViewGroup.java:4534
androidx.drawerlayout.widget.DrawerLayout.drawChild DrawerLayout.java:1483
crc640ec207abc449b2ca.ShellFlyoutRenderer.n_drawChild(Native Method)
crc640ec207abc449b2ca.ShellFlyoutRenderer.drawChild ShellFlyoutRenderer.java:57
android.view.ViewGroup.dispatchDraw ViewGroup.java:4534'

**Comment by Simoo23** [comment]
Same issue with .NET 8.
I have a CollectionView with images, if you scroll the list the app will crash.

**Comment by Simoo23** [comment]
I found a workaround reading other conversations:
https://github.com/dotnet/maui/issues/9712#issuecomment-1397418581

I set these 2 properties for Image: 
HeightRequest
MinimumWidthRequest

```
<Image HeightRequest="140" MinimumWidthRequest="140" />
```

Maybe you can try to set MinimumHeightRequest instead of HeightRequest if you need (i didn't try this)

No crashes anymore

**Comment by jing8956** [comment]
When I replace the default `StreamImageSourceService` with the following code. Scroll through the CollectionView quickly and the program never crash again.

```csharp
public static class MauiProgram
{
    public static MauiApp CreateMauiApp()
    {
        var builder = MauiApp.CreateBuilder();
        builder
            .UseMauiApp<App>()
            .ConfigureFonts(fonts =>
            {
                fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
                fonts.AddFont("OpenSans-Semibold.ttf", "OpenSansSemibold");
            })
            .ConfigureImageSources(services =>
            {
                services.RemoveAll<IImageSourceService<IStreamImageSource>>();
                services.RemoveAll<IImageSourceService<StreamImageSource>>();
                services.AddService<IStreamImageSource>(_ => new CustomStreamImageSourceService());
                services.AddService<StreamImageSource>(_ => new CustomStreamImageSourceService());
            });

#if DEBUG
		builder.Logging.AddDebug();
#endif

        return builder.Build();
    }

#if ANDROID

    public class CustomStreamImageSourceService : StreamImageSourceService
    {
        public override async Task<IImageSourceServiceResult?> LoadDrawableAsync(IImageSource imageSource, ImageView imageView, CancellationToken cancellationToken = default)
        {
            var result = await base.GetDrawableAsync(imageSource, imageView.Context!, cancellationToken);
            // if (result?.Value is BitmapDrawable drawable && drawable.Bitmap?.IsRecycled == true)
            // {
            //     drawable.Bitmap.IsRecycled always false.
            // }
            imageView.SetImageDrawable(result?.Value);
            return result;
        }
    }

#endif

}
```

It might be `base.LoadDrawableAsync` passes the recycled bitmap to `imageView`, causing the program to crash.
(Machine translation was used)

**Comment by plppp2001** [comment]
I'm getting this error when I have an Image on my  CarouselView   .  This is a show stopper for me. 


![image](https://github.com/dotnet/maui/assets/45370058/fcfd03d7-993c-4aa9-a892-34cf30267565)

**Comment by switchyy** [comment]
I have the same issue with the latest VS version and .NET 8.
![image](https://github.com/dotnet/maui/assets/77116224/2479436a-86d3-4993-a51a-3f2e8cd06ea8)
I'm receiving the images through an API call from a FileManager, and the image is located inside grid, it crashed the app very rarely.
I can over more info if needed.

**Comment by lythix** [comment]
Chiming in here with my 2c worth of evidence. I'm getting same issue with dotnet 8.0 (8.0.3) and VS 2022 Version 17.9.5
(Android app)
 
```
2024-04-10 09:35:54.868 +08:00 [FTL] Java.Lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@fe28425
   at Java.Interop.JniEnvironment.InstanceMethods.CallNonvirtualBooleanMethod(JniObjectReference instance, JniObjectReference type, JniMethodInfo method, JniArgumentValue* args)
   at Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualBooleanMethod(String encodedMember, IJavaPeerable self, JniArgumentValue* parameters)
   at Android.Views.ViewGroup.DrawChild(Canvas canvas, View child, Int64 drawingTime)
   at Microsoft.Maui.Controls.Platform.Compatibility.ShellFlyoutRenderer.DrawChild(Canvas canvas, View child, Int64 drawingTime)
   at Android.Views.ViewGroup.n_DrawChild_Landroid_graphics_Canvas_Landroid_view_View_J(IntPtr jnienv, IntPtr native__this, IntPtr native_canvas, IntPtr native_child, Int64 drawingTime)
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPLLJ_Z(_JniMarshal_PPLLJ_Z callback, IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, Int64 p2)
 ``` 
 I'm rather glad I found my way to this issue, I thought I was doing something wrong.

**Comment by samhouts** [comment]
Confirmed that this regressed between 8.0.0-preview.4.8333 and 8.0.0-preview.5.8529. Before pre5, the scrolling performance was atrocious, so I assume this was a memory leak resolved by properly disposing of the images. However, that leads to this crash. 

Not sure exactly what the culprit was, but https://github.com/dotnet/maui/pull/14933, https://github.com/dotnet/maui/pull/12011, and https://github.com/dotnet/maui/pull/14109 seem most sus. 

Incidentally, I changed the Frame to a Border to see if it helped and with that, I see that the background color of the cell goes from white in pre4 to black in pre5, which seems to be related to https://github.com/dotnet/maui/pull/14933 and is probably another regression/behavior change.

**Comment by samhouts** [comment]
Oh, yep, the repro is using a DTS, so looks like https://github.com/dotnet/maui/pull/12011 is most likely. @Redth fyi

**Comment by H-A-Hristov** [comment]
I have seen this before.
Not specifying the Height and Width request, in your ImageViews, (using URLs of uploaded pictures with 1000x1600 for example as source) that are contained in your ListView, lead to the following problems:

In Android: 
You get random runtime crashes, when you scroll down the collection view.
In IOS:
You get empty collection view the first time you enter the page. Collection view with only first item loaded the second time you enter the page. And full collection view when you enter 3rd time in the page.

Setting WidthRequest=100, HeightRequest=100 is quick way to check if this applies to you.

**Comment by lythix** [comment]
Thanks for the reply!

> Setting WidthRequest=100, HeightRequest=100 is quick way to check if this applies to you.
> 
Meaning the crashing stops? I've wondered if perhaps I can set or bind the height/width request to a calculated value so it is provided (but still fills the available width/height but stops the crashes)

**Comment by H-A-Hristov** [comment]
> Meaning the crashing stops? I've wondered if perhaps I can set or bind the height/width request to a calculated value so it is provided (but still fills the available width/height but stops the crashes)

Not only the android crashing. The weird behavior on IOS also. 
You open "details" page, that contains CollectionView, that has ItemTeplate of DataTemplate of Image. 
Nothing else. And on the Image you have set "MaximumWidthRequest" and "MaximumHeightRequest", with aspect set to Fit.
Open details once - empty.
Second - only one image showing.
Third time - everything. 

Set specific measurements and both problems are gone.

To make matter worse - on the device I develop with most of the time, this problem could not be reproduced.
On one of the test devices, this problem was showing, but only if your list has set amount of items. 4 or 5 pages - no problem.
And the key to find this out was another test device, that was throwing this exception, the second you try to scroll.

I hope this saves you some time.

**Comment by Simoo23** [comment]
Any news on this? This issue is still presenting

**Comment by Simoo23** [comment]
> When I replace the default `StreamImageSourceService` with the following code. Scroll through the CollectionView quickly and the program never crash again.
> 
> ```cs
> public static class MauiProgram
> {
>     public static MauiApp CreateMauiApp()
>     {
>         var builder = MauiApp.CreateBuilder();
>         builder
>             .UseMauiApp<App>()
>             .ConfigureFonts(fonts =>
>             {
>                 fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
>                 fonts.AddFont("OpenSans-Semibold.ttf", "OpenSansSemibold");
>             })
>             .ConfigureImageSources(services =>
>             {
> #if ANDROID
>                 services.RemoveAll<IImageSourceService<IStreamImageSource>>();
>                 services.RemoveAll<IImageSourceService<StreamImageSource>>();
>                 services.AddService<IStreamImageSource>(_ => new CustomStreamImageSourceService());
>                 services.AddService<StreamImageSource>(_ => new CustomStreamImageSourceService());
> #endif
>             });
> 
> #if DEBUG
> 		builder.Logging.AddDebug();
> #endif
> 
>         return builder.Build();
>     }
> 
> #if ANDROID
> 
>     public class CustomStreamImageSourceService : StreamImageSourceService
>     {
>         public override async Task<IImageSourceServiceResult?> LoadDrawableAsync(IImageSource imageSource, ImageView imageView, CancellationToken cancellationToken = default)
>         {
>             var result = await base.GetDrawableAsync(imageSource, imageView.Context!, cancellationToken);
>             // if (result?.Value is BitmapDrawable drawable && drawable.Bitmap?.IsRecycled == true)
>             // {
>             //     drawable.Bitmap.IsRecycled always false.
>             // }
>             imageView.SetImageDrawable(result?.Value);
>             return result;
>         }
>     }
> 
> #endif
> 
> }
> ```
> 
> It might be `base.LoadDrawableAsync` passes a recycled bitmap to `imageView`, causing the program to crash. The same may be required for both `FileImageSource` and `UriImageSource`. (Machine translation was used)

From my tests this resolve the problem

**Comment by samhouts** [comment]
I ran into this one again on my own app when I decided to remove the `WidthRequest` from my images. Setting an explicit `WidthRequest` and `HeightRequest` is certainly the workaround.

**Comment by viktorszekeress** [comment]
@samhouts I've observed that `WidthRequest` technique works only under certain circumstances. I create a sample app to repro the issue.
App has a simple timer that periodically updates Image.Source. On my real devices (Galaxy A52s, Galaxy S22), it crashes with an update period of 70ms. There are 2 buttons to increase/decrease the delay.

Interestingly, if `Image.WidthRequest` is 500, then it crashes. If I change `WidthRequest` to 400 or lower, then it doesn't crash.

[MauiAppRecycledBitmap.zip](https://github.com/user-attachments/files/15800876/MauiAppRecycledBitmap.zip)

**Comment by Simoo23** [comment]
@viktorszekeress Did you try if this workaround work for you?

For me it seems to work

> When I replace the default `StreamImageSourceService` with the following code. Scroll through the CollectionView quickly and the program never crash again.
> 
> ```cs
> public static class MauiProgram
> {
>     public static MauiApp CreateMauiApp()
>     {
>         var builder = MauiApp.CreateBuilder();
>         builder
>             .UseMauiApp<App>()
>             .ConfigureFonts(fonts =>
>             {
>                 fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
>                 fonts.AddFont("OpenSans-Semibold.ttf", "OpenSansSemibold");
>             })
>             .ConfigureImageSources(services =>
>             {
> #if ANDROID
>                 services.RemoveAll<IImageSourceService<IStreamImageSource>>();
>                 services.RemoveAll<IImageSourceService<StreamImageSource>>();
>                 services.AddService<IStreamImageSource>(_ => new CustomStreamImageSourceService());
>                 services.AddService<StreamImageSource>(_ => new CustomStreamImageSourceService());
> #endif
>             });
> 
> #if DEBUG
> 		builder.Logging.AddDebug();
> #endif
> 
>         return builder.Build();
>     }
> 
> #if ANDROID
> 
>     public class CustomStreamImageSourceService : StreamImageSourceService
>     {
>         public override async Task<IImageSourceServiceResult?> LoadDrawableAsync(IImageSource imageSource, ImageView imageView, CancellationToken cancellationToken = default)
>         {
>             var result = await base.GetDrawableAsync(imageSource, imageView.Context!, cancellationToken);
>             // if (result?.Value is BitmapDrawable drawable && drawable.Bitmap?.IsRecycled == true)
>             // {
>             //     drawable.Bitmap.IsRecycled always false.
>             // }
>             imageView.SetImageDrawable(result?.Value);
>             return result;
>         }
>     }
> 
> #endif
> 
> }
> ```
> 
> It might be `base.LoadDrawableAsync` passes a recycled bitmap to `imageView`, causing the program to crash. The same may be required for both `FileImageSource` and `UriImageSource`. (Machine translation was used)

**Comment by Simoo23** [comment]
@viktorszekeress I tried to check the Ram usage too.

But how do you convert byte[] to Image and bind to Image component in MVVM without using ImageSource?

**Comment by viktorszekeress** [comment]
@Simoo23 Instead of using `Image` in XAML and binding `ImageSource`, I use `ContentView` and I bind `Content` to `byte[]`.

**Comment by plppp2001** [comment]
> @Simoo23 Instead of using `Image` in XAML and binding `ImageSource`, I use `ContentView` and I bind `Content` to `byte[]`.

Does this work flawlessly on both iOS and ANdroid?

Also, what if we need to bind the image from an HTTP URI link? Any ideas there?

**Comment by viktorszekeress** [comment]
> 
> Does this work flawlessly on both iOS and ANdroid?

I haven't tested it on iOS. The question is, do we need this workaround there?

> Also, what if we need to bind the image from an HTTP URI link? Any ideas there?

It's just a matter of converter (parameter) and how you construct the image.

**Comment by Simoo23** [comment]
Is not possibile to increase the priority of this bug? 
I think that this is a basic feature as we are talking of a simple list of images and this bug is opened from Nov 17, 2023.
We have some workarounds but they all have problems

**Comment by H-A-Hristov** [comment]
> Interestingly, if `Image.WidthRequest` is 500, then it crashes. If I change `WidthRequest` to 400 or lower, then it doesn't crash.

Are you sure about this? I cannot say about "width", but I am using "HeightRequest" of 500 and above, without this issue manifesting.

**Comment by KaoutharG** [comment]
Hi every one,
i have the same issue when scrolling a collection view: Java.Lang.RuntimeException: 'Canvas: trying to use a recycled bitmap android.graphics.Bitmap@a06a0c7' even after writing the code i found here: 
`using Microsoft.Extensions.DependencyInjection.Extensions;
#if ANDROID
using Android.Widget;
using Android.Graphics.Drawables;  // Pour BitmapDrawable
#endif
public static class MauiProgram
{
    public static IServiceProvider ServiceProvider;
    public static MauiApp CreateMauiApp()
    {
        var builder = MauiApp.CreateBuilder();
        builder
            .UseMauiApp<App>()
                .UseMauiCommunityToolkit()
                .ConfigureFonts(fonts =>
                {
                    fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
                    fonts.AddFont("OpenSans-Semibold.ttf", "OpenSansSemibold");
                    fonts.AddFont("Roboto-Meduim.ttf", "RobotoM");
                    fonts.AddFont("Roboto-Regular.ttf", "RobotoR");
                })
                .ConfigureImageSources(services =>
                {
#if ANDROID
                    services.RemoveAll<IImageSourceService<IStreamImageSource>>();
                    services.RemoveAll<IImageSourceService<StreamImageSource>>();
                    services.AddService<IStreamImageSource>(_ => new CustomStreamImageSourceService());
                    services.AddService<StreamImageSource>(_ => new CustomStreamImageSourceService());
#endif
#if DEBUG
            builder.Logging.AddDebug();
#endif
            //this lines for eviting this error: Java.Lang.RuntimeException: 'Canvas: trying to use a recycled bitmap android.graphics.Bitmap'

            var app = builder.Build();
            ServiceProvider = app.Services;
            return app;

        }
#if ANDROID

        public class CustomStreamImageSourceService : StreamImageSourceService
        {
            public override async Task<IImageSourceServiceResult?> LoadDrawableAsync(IImageSource imageSource, ImageView imageView, CancellationToken cancellationToken = default)
            {
                var result = await base.GetDrawableAsync(imageSource, imageView.Context!, cancellationToken);
                // if (result?.Value is BitmapDrawable drawable && drawable.Bitmap?.IsRecycled == true)
                // {
                //     drawable.Bitmap.IsRecycled always false.
                // }
                imageView.SetImageDrawable(result?.Value);
                return result;
            }
        }

#endif
    }`
i'm using image with width 160 only : like here : `<Image
    Grid.Row="0"
    Grid.ColumnSpan="2"
    Margin="0,0,0,0"
    Aspect="AspectFit"
    HeightRequest="120"
    HorizontalOptions="Center"
    Source="{Binding urlimage}"
    VerticalOptions="Start"
    WidthRequest="160" />` but it crashes. Can any one help me ? Thanks a lot.

**Comment by hiepis** [comment]
any update? same issue
using Maui.Controls 8.0.92
lastest .net SDK 8.0.403

**Comment by albilaga** [comment]
Still have this issue as well on Android using Maui 8.0.92 with .NET SDK 8.0.403 as well

**Comment by bhavanesh2001** [comment]
I had to create a completely new control for Android to solve this problem. I used `Glide` to render the image since our requirement was to load an image from a file path. Posting the basic implementation here in case it helps someone.

### Control

```c#
  public class CustomImage: View
  {
      public static readonly BindableProperty FilePathProperty =
         BindableProperty.Create(nameof(FilePath), typeof(string), typeof(CustomImage), default(string));

      public string FilePath
      {
          get => (string)GetValue(FilePathProperty);
          set => SetValue(FilePathProperty, value);
      }

  }
```
### Handler
```c#
 public class CustomImageHandler : ViewHandler<CustomImage, AppCompatImageView>
 {
     public static IPropertyMapper<CustomImage, CustomImageHandler> PropertyMapper = new PropertyMapper<CustomImage, CustomImageHandler>(ViewHandler.ViewMapper)
     {
         [nameof(CustomImage.FilePath)] = MapFilePath
     };

     public CustomImageHandler() : base(PropertyMapper, null)
     {
     }

     protected override AppCompatImageView CreatePlatformView()
     {
         var imageView = new AppCompatImageView(Context)
         {
             LayoutParameters = new Android.Views.ViewGroup.LayoutParams(
        Android.Views.ViewGroup.LayoutParams.WrapContent,
        Android.Views.ViewGroup.LayoutParams.WrapContent)
         };
         return imageView;
     }

     private static void MapFilePath(CustomImageHandler handler, CustomImage image)
     {
         if (handler.PlatformView != null && handler.VirtualView != null && !string.IsNullOrEmpty(handler.VirtualView.FilePath))
         {
             try
             {
                 var filePath = handler.VirtualView.FilePath;

                 Glide.With(handler.PlatformView.Context).Clear(handler.PlatformView);
                 Glide.With(handler.PlatformView.Context)
                     .Load(filePath)
                     .SetDiskCacheStrategy(Bumptech.Glide.Load.Engine.DiskCacheStrategy.None)
                     .Into(handler.PlatformView);
             }

             catch (Exception ex)
             {
                 System.Diagnostics.Debug.WriteLine($"Error loading image: {ex.Message}");
             }
         }
     }
 }
```
Since using `DiskCacheStrategy` was causing a flickering issue, I set it to `None`.

Of course, this control does not include all the features of a regular `Image` control, but you can easily modify it to implement any additional functionality you require.
