### ISSUE TITLE
[Windows] `PlatformImage.FromStream` crash

### ISSUE THREAD

**Issue by nor0x** [dotnet/maui#18954]
### Description

trying to get an image from the web as an IImage like this:

```
var imageUrl = "https://source.unsplash.com/random";
var stream = await new HttpClient().GetStreamAsync(imageUrl);
var img = PlatformImage.FromStream(stream);
```

crashes the app on Windows with the following Exception:

```
   at System.IO.WindowsRuntimeStreamExtensions.AsRandomAccessStream(Stream stream)
   at Microsoft.Maui.Graphics.Platform.PlatformImage.<>c__DisplayClass18_0.<<FromStream>b__0>d.MoveNext()
   at Microsoft.Maui.Graphics.Platform.AsyncPump.Run[T](Func`1 asyncMethod)
   at Microsoft.Maui.Graphics.Platform.PlatformImage.FromStream(Stream stream, ImageFormat format)
   at MyApp.Pages.MainPage.<OnMounted>d__6.MoveNext() in C:\dev\MyApp\MainPage.cs:line 64
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 1914
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
```

`Cannot use the specified Stream as a Windows Runtime IRandomAccessStream because this Stream does not support seeking.`

Works fine on Android

Repro:
[MauiApp1.zip](https://github.com/dotnet/maui/files/13440716/MauiApp1.zip)

### Steps to Reproduce

1. create maui app
2. use PlatformImage.FromStream
3. run on windows

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows

**Comment by cybernetically-robogrip** [comment]
@jsuarezruiz @nor0x 

We are having a similar issue with this line of code where we are getting the exception.

` Microsoft.Maui.Graphics.IImage img = PlatformImage.FromStream((Stream)asset, ImageFormat.Png);`
 
 We then later use the image and redraw the canvas with it
 
` canvas.DrawImage(iimg, 0, 0, iimg.Width, iimg.Height);`

This is an absolute nightmare for our large project built on top of MAUI. We are building a huge project on top of MAUI for the largest chip manufacturer, guys please help us resolve this ASAP

We cannot keep all of our images as embedded assets and share them across different projects in .NET, because the MAUI one crashes. The crash is random, it doesn't happen right away, it's happening when a button is built with a drawable and when the button drawable is completely re-drawn with a new image state for that particular mouse interaction. So build a button with hover, mouse down, mouse up etc. states, put 5 of these buttons in a row and move the mouse on top of this composition and sooner or later the crash is seen. This crashes faster if we keep clicking the buttons. I will create a sample project and post it here when I get a chance over this weekend.

**Comment by kevinxufei** [comment]
Verified this issue with Visual Studio 17.10.0 Preview 3 (8.0.20 & 8.0.0-rc.2.9530). Can not repro it with sample project

**Comment by nor0x** [comment]
@kevinxufei how did you test?

I just downloaded the repro project, updated to the latest maui nuget packages and I'm still able to reproduce this:
![image](https://github.com/dotnet/maui/assets/3210391/6112f6ab-f104-42c1-a903-40348c607454)

```js
   at System.IO.WindowsRuntimeStreamExtensions.AsRandomAccessStream(Stream stream)
   at Microsoft.Maui.Graphics.Platform.PlatformImage.<>c__DisplayClass18_0.<<FromStream>b__0>d.MoveNext()
   at Microsoft.Maui.Graphics.Platform.AsyncPump.Run[T](Func`1 asyncMethod)
   at Microsoft.Maui.Graphics.Platform.PlatformImage.FromStream(Stream stream, ImageFormat format)
   at MauiApp1.MainPage.<OnCounterClicked>d__2.MoveNext() in C:\dev\MauiApp1\MauiApp1\MainPage.xaml.cs:line 22
```

I'm on .NET 8 version `8.0.300-preview.24203.14` and I have referenced the following MAUI packages:

```xml
<PackageReference Include="Microsoft.Maui.Controls" Version="8.0.20" />
<PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="8.0.20" />
```

**Comment by nor0x** [comment]
updated my repro to 8.0.40. The exception is the same - is this something that even was adressed at all in a recent release @jsuarezruiz  ?
![image](https://github.com/dotnet/maui/assets/3210391/b28630e6-f8ba-4831-9893-471ea2bf0449)
