### ISSUE TITLE
[regression/8.0.3] [IOS] .NET 8.0 - Objective-C exception thrown.  Name: CALayerInvalidGeometry

### ISSUE THREAD

**Issue by dpozimski** [dotnet/maui#19120]
### Description

App randomly crashes with CALayerInvalidGeometry exception. Don't know what is the core of the reason. App is using ScrollView + StackLayout + ListView with checkbox.
I did not notice that kind of random crashes in last .NET 7 release.
Hope you will not close it...
It blocks my development because on macOS it forces me to upgrade .NET to run simulator.

### Steps to Reproduce

Don't know
Just a next bug after each major .NET release that causes random crashes.

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI, Yes, this used to work in Xamarin.Forms

### Last version that worked well

8.0.3

### Affected platforms

iOS

### Did you find any workaround?

rolling back to .NET 7

### Relevant log output

```shell
ObjCRuntime.ObjCException: Objective-C exception thrown.  Name: CALayerInvalidGeometry Reason: CALayer position contains NaN: [nan 0]. Layer: <CALayer:0x283fb99c0; position = CGPoint (0 0); bounds = CGRect (0 0; 0 0); delegate = <Microsoft_Maui_Platform_MauiCheckBox: 0x1468c63f0; baseClass = UIButton; frame = (0 0; 0 0); opaque = NO; tintColor = UIExtendedSRGBColorSpace 1 1 1 1; layer = <CALayer: 0x283fb99c0>>; sublayers = (<CALayer: 0x283fb99a0>); allowsGroupOpacity = YES; >
Native stack trace:
	0   CoreFoundation                      0x00000001ccbe8e44 42CCFC7B-FF32-3D25-8F01-CCB2AD843A8B + 40516
	1   libobjc.A.dylib                     0x00000001c5d778d8 objc_exception_throw + 60
	2   CoreFoundation                      0x00000001cccd8c28 42CCFC7B-FF32-3D25-8F01-CCB2AD843A8B + 1023016
	3   QuartzCore                          0x00000001ce2a9710 3F8EDDC2-623F-301F-BA1D-12976C8A60E9 + 161552
	4   QuartzCore                          0x00000001ce290c38 3F8EDDC2-623F-301F-BA1D-12976C8A60E9 + 60472
	5   UIKitCore                           0x00000001cedda4a8 CF21AD9C-EFBF-3961-A7C0-54BD30CEFEA9 + 156840
	6   MyApp                           0x0000000108e05188 xamarin_log + 7076
	7   MyApp                           0x0000000105ba8698 ucl_version_string + 13083476
	8   MyApp                           0x0000000108d58acc ucl_version_string + 65185672
	9   MyApp                           0x0000000109095738 AppleCryptoNative_X509ImportCertificate + 2269928
	10  MyApp                           0x00000001090423f4 AppleCryptoNative_X509ImportCertificate + 1929124
	11  MyApp                           0x0000000109045114 AppleCryptoNative_X509ImportCertificate + 1940676
	12  MyApp                           0x0000000109181c0c AppleCryptoNative_X509ImportCertificate + 3237820
	13  MyApp                           0x00000001091abbf8 AppleCryptoNative_X509ImportCertificate + 3409832
	14  UIKitCore                           0x00000001cedb84c8 CF21AD9C-EFBF-3961-A7C0-54BD30CEFEA9 + 17608
	15  QuartzCore                          0x00000001ce28b7fc 3F8EDDC2-623F-301F-BA1D-12976C8A60E9 + 38908
	16  QuartzCore                          0x00000001ce29eeb0 3F8EDDC2-623F-301F-BA1D-12976C8A60E9 + 118448
	17  QuartzCore                          0x00000001ce2b0234 3F8EDDC2-623F-301F-BA1D-12976C8A60E9 + 188980
	18  QuartzCore                          0x00000001ce2e5630 3F8EDDC2-623F-301F-BA1D-12976C8A60E9 + 407088
	19  QuartzCore                          0x00000001ce2ce8b4 3F8EDDC2-623F-301F-BA1D-12976C8A60E9 + 313524
	20  UIKitCore                           0x00000001cf2b80f4 CF21AD9C-EFBF-3961-A7C0-54BD30CEFEA9 + 5259508
	21  UIKitCore                           0x00000001cf4065b0 CF21AD9C-EFBF-3961-A7C0-54BD30CEFEA9 + 6628784
	22  UIKitCore                           0x00000001cfa55310 CF21AD9C-EFBF-3961-A7C0-54BD30CEFEA9 + 13243152
	23  UIKitCore                           0x00000001cfa544dc CF21AD9C-EFBF-3961-A7C0-54BD30CEFEA9 + 13239516
	24  CoreFoundation                      0x00000001cccb4f24 42CCFC7B-FF32-3D25-8F01-CCB2AD843A8B + 876324
	25  CoreFoundation                      0x00000001cccc12fc 42CCFC7B-FF32-3D25-8F01-CCB2AD843A8B + 926460
	26  CoreFoundation                      0x00000001ccc451c0 42CCFC7B-FF32-3D25-8F01-CCB2AD843A8B + 418240
	27  CoreFoundation                      0x00000001ccc5ab7c 42CCFC7B-FF32-3D25-8F01-CCB2AD843A8B + 506748
	28  CoreFoundation                      0x00000001ccc5feb0 CFRunLoopRunSpecific + 612
	29  GraphicsServices                    0x0000000206e55368 GSEventRunModal + 164
	30  UIKitCore                           0x00000001cf155668 CF21AD9C-EFBF-3961-A7C0-54BD30CEFEA9 + 3806824
	31  UIKitCore                           0x00000001cf1552cc UIApplicationMain + 340
	32  MyApp                           0x0000000108df97e0 xamarin_UIApplicationMain + 24
	33  MyApp                           0x0000000105b9f7a0 ucl_version_string + 13046876
	34  MyApp                           0x0000000108d2e094 ucl_version_string + 65011024
	35  MyApp                           0x0000000109095738 AppleCryptoNative_X509ImportCertificate + 2269928
	36  MyApp                           0x0000000109041604 AppleCryptoNative_X509ImportCertificate + 1925556
	37  MyApp                           0x0000000109047524 AppleCryptoNative_X509ImportCertificate + 1949908
	38  MyApp                           0x000000010909aae0 AppleCryptoNative_X509ImportCertificate + 2291344
	39  MyApp                           0x0000000108e04854 xamarin_log + 4720
	40  MyApp                           0x000000010917c808 AppleCryptoNative_X509ImportCertificate + 3216312
	41  dyld                                0x00000001eb558960 4B042F28-0D14-30EC-A1DE-3DBB10866AD7 + 88416

   at UIKit.UIView.set_Center(CGPoint )
   at Microsoft.Maui.ViewHandlerExtensions.PlatformArrangeHandler(IViewHandler viewHandler, Rect rect)
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.ICheckBox, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.MauiCheckBox, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].PlatformArrange(Rect rect)
   at Microsoft.Maui.Controls.VisualElement.ArrangeOverride(Rect bounds)
   at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IView.Arrange(Rect bounds)
   at Microsoft.Maui.Layouts.GridLayoutManager.ArrangeChildren(Rect bounds)
   at Microsoft.Maui.Controls.AndExpandLayoutManager.ArrangeChildren(Rect bounds)
   at Microsoft.Maui.Controls.StackLayoutManager.ArrangeChildren(Rect bounds)
   at Microsoft.Maui.Controls.Layout.CrossPlatformArrange(Rect bounds)
   at Microsoft.Maui.Platform.MauiView.CrossPlatformArrange(Rect bounds)
   at Microsoft.Maui.Platform.MauiView.LayoutSubviews()
--- End of stack trace from previous location ---
   at UIKit.UIApplication.UIApplicationMain(Int32 , String[] , IntPtr , IntPtr )
   at UIKit.UIApplication.Main(String[] , Type , Type )
   at MyApp.Platforms.iOS.Program.Main(String[] a)
```

**Comment by mattleibow** [comment]
This appears to be the error message: `CALayer position contains NaN: [nan 0]`
