### ISSUE TITLE
.NET MAUI app works both in debug and release mode on android but after publishing to apk. The app crashes on physical device.

### ISSUE THREAD

**Issue by JuliusBalaguer** [dotnet/maui#19210]
### Description

I have no idea what is the reason why the app crashes after publishing and signed it as apk and then installed it on physical device. It is working in both debug and release build.

I have this on my csproj 
```
<PropertyGroup>
  <AndroidLinkResources>True</AndroidLinkResources>
  <AndroidLinkMode>None</AndroidLinkMode>
  <UseInterpreter>True</UseInterpreter>
  <RunAOTCompilation>false</RunAOTCompilation>
  <AndroidEnableProfiledAot>false</AndroidEnableProfiledAot>
  <RuntimeIdentifiers Condition="$(TargetFramework.Contains('-android'))">android-arm;android-arm64;android-x86;android-x64</RuntimeIdentifiers>
</PropertyGroup>
```

The app is just stuck on splash screen and after a few seconds the app will crash.

In addition, I actually released this app on WINDOWS where it's working as intended but when releasing on android, I'm having this problem.

### Steps to Reproduce

1. Create New .NET MAUI App
2. Run it in debug and release mode (both build works fine)
3. Release and signed it as apk.
4. Install it on my physical device.

Outcome: App crashes

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 13

### Did you find any workaround?

Haven't find any workaround for this problem.

**Comment by drasticactions** [comment]
Without any information about your application (A stack trace, `binlog`, etc) there's not much anyone can do to help you here. We need more information. 

https://aka.ms/binlog

Could you try and create a `binlog` of your working debug build and failing release build? @jonathanpeppers Are there other things they could provide?

**Comment by jonathanpeppers** [comment]
I think we need to actually see the crash. It could be a C#, Java, or native crash, which all point to different problems, and so you'd check [adb logcat](https://docs.microsoft.com/en-us/xamarin/android/deploy-test/debugging/android-debug-log) output to see what happened. 

If you want to enable additional logging, you could do:
```sh
# enable more logging
adb shell setprop debug.mono.log default,debugger,assembly,mono_log_level=debug,mono_log_mask=all

# launch the app & cause it to crash

# next command saves the log
adb logcat -d > log.txt
```

And then share `log.txt` here, thanks! There should be some kind error message inside.

**Comment by ExLuzZziVo** [comment]
I have the same problem after updating my app to .net8.0 . Here is the output of logcat:
```
[ERROR] FATAL UNHANDLED EXCEPTION: Java.Lang.IllegalArgumentException: No destination with ID 5 is on the NavController's back stack. The current destination is FragmentNavigator$Destination(0x1) class=crc6452ffdc5b34af3a0f.NavigationViewFragment
                                                                                                       at Java.Interop.JniEnvironment.InstanceMethods.CallObjectMethod(JniObjectReference , JniMethodInfo , JniArgumentValue* )
                                                                                                       at Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualObjectMethod(String , IJavaPeerable , JniArgumentValue* )
                                                                                                       at AndroidX.Navigation.NavController.GetBackStackEntry(Int32 )
                                                                                                      --- End of managed Java.Lang.IllegalArgumentException stack trace ---
                                                                                                    java.lang.IllegalArgumentException: No destination with ID 5 is on the NavController's back stack. The current destination is FragmentNavigator$Destination(0x1) class=crc6452ffdc5b34af3a0f.NavigationViewFragment
                                                                                                    	at androidx.navigation.NavController.getBackStackEntry(NavController.kt:2411)
                                                                                                    	at crc6488302ad6e9e4df1a.MauiAppCompatActivity.n_onBackPressed(Native Method)
                                                                                                    	at crc6488302ad6e9e4df1a.MauiAppCompatActivity.onBackPressed(MauiAppCompatActivity.java:73)
                                                                                                    	at android.app.Activity.onKeyUp(Activity.java:3031)
                                                                                                    	at android.view.KeyEvent.dispatch(KeyEvent.java:2734)
                                                                                                    	at androidx.core.view.KeyEventDispatcher.activitySuperDispatchKeyEventPre28(KeyEventDispatcher.java:143)
                                                                                                    	at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:89)
                                                                                                    	at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:144)
                                                                                                    	at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:604)
                                                                                                    	at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:60)
                                                                                                    	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:3413)
                                                                                                    	at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:355)
                                                                                                    	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4901)
                                                                                                    	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4773)
                                                                                                    	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4309)
                                                                                                    	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4362)
                                                                                                    	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4328)
                                                                                                    	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4455)
                                                                                                    	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4336)
                                                                                                    	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4512)
                                                                                                    	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4309)
                                                                                                    	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4362)
                                                                                                    	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4328)
                                                                                                    	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4336)
                                                                                                    	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4309)
                                                                                                    	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4362)
                                                                                                    	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4328)
                                                                                                    	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4488)
                                                                                                    	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4655)
                                                                                                    	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2435)
                                                                                                    	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1998)
                                                                                                    	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1989)
                                                                                                    	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2412)
                                                                                                    	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
                                                                                                    	at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                                                    	at android.os.MessageQueue.next(MessageQueue.java:325)
                                                                                                    	at android.os.Looper.loop(Looper.java:142)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:6548)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:43
```
My publish settings:
```
<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net8.0-android|AnyCPU'">
        <EnableTrimAnalyzer>true</EnableTrimAnalyzer>
        <PublishTrimmed>true</PublishTrimmed>
        <TrimMode>partial</TrimMode>
        <EnableLLVM>True</EnableLLVM>
        <AndroidPackageFormat>apk</AndroidPackageFormat>
        <AndroidLinkTool>r8</AndroidLinkTool>
        <RunAOTCompilation>true</RunAOTCompilation>
        <AndroidStripILAfterAOT>false</AndroidStripILAfterAOT>
        <AndroidEnableProfiledAot>true</AndroidEnableProfiledAot>
        <AndroidCreatePackagePerAbi>false</AndroidCreatePackagePerAbi>
</PropertyGroup>
```

**Comment by jonathanpeppers** [comment]
@ExLuzZziVo can you file a new issue, it seems like there is a very low chance you have the same issue as @JuliusBalaguer, as we have no log or error message to know it's the same.

**Comment by JuliusBalaguer** [comment]
I really can't connect my physical device to my development machine so I think there's no way I can see the logs when the app crashes in my physical android device, hope you understand.

But here's what I did. I have this method and it works on emulator in both debug and release build so I'm pretty sure the I connected the database to the app successfully because I can see the data being populated in the app and to the database., After removing this method, I build the app and published it again as apk, and the app is now running on my physical device. So I think this method is the one that causing the crash in physical android device.

What should I do here? 

```
private void ValidateDeviceAndLoadEmployeeData()
        {
            string deviceUniqueID = string.Empty;

#if ANDROID
             deviceUniqueID = AndroidId;
#elif WINDOWS
            deviceUniqueID = MacAddress;
#endif

            var deviceID = App._dbcontext1.Table1
                .FirstOrDefault(s => s.UniqueID == deviceUniqueID);

            if (deviceID == null)
            {
                Application.Current.MainPage.DisplayAlert("Access Denied", "This device is not registered.", "OK");
                CanExecuteCommands = false;
                return;
            }

            CanExecuteCommands = true;

            var empNo = deviceID.EmpNo;

            if (empNo == null)
            {
                Application.Current.MainPage.DisplayAlert("Error", "Cannot find Employee No.", "OK");
                return;
            }

            // Fetch the employee's name from the Employee table
            var employee = App._dbContext2.EmployeeTable.FirstOrDefault(e => e.EmpNo == empNo);
            if (employee == null)
            {
                Application.Current.MainPage.DisplayAlert("Error", "Cannot find Employee.", "OK");
                return;
            }
            EmployeeName = $"{employee.FName} {employee.LName}";

            objlist = new ObservableCollection<Table3>(
                App._dbContext2.Table3
                    .Where(ob => ob.EmpNo == empNo && ob.Date.HasValue && ob.Date.Value.Date == DateTime.Today)
                    .ToList()
            );

            TimeInCommand = new Command(() => UpdateOnlineBio("I", empNo.Value), () => CanExecuteCommands);
            TimeOutCommand = new Command(() => UpdateOnlineBio("O", empNo.Value), () => CanExecuteCommands);
        }
```

**Comment by JuliusBalaguer** [comment]
I really can't connect my physical device to my development machine so I think there's no way I can see the logs when the app crashes in my physical android device, hope you understand.

But here's what I did. I have this method and it works on emulator in both debug and release build so I'm pretty sure the I connected the database to the app successfully because I can see the data being populated in the app and to the database., After removing this method, I build the app and published it again as apk, and the app is now running on my physical device. So I think this method is the one that causing the crash in physical android device.

What should I do here? 

```
private void ValidateDeviceAndLoadEmployeeData()
        {
            string deviceUniqueID = string.Empty;

#if ANDROID
             deviceUniqueID = AndroidId;
#elif WINDOWS
            deviceUniqueID = MacAddress;
#endif

            var deviceID = App._dbcontext1.Table1
                .FirstOrDefault(s => s.UniqueID == deviceUniqueID);

            if (deviceID == null)
            {
                Application.Current.MainPage.DisplayAlert("Access Denied", "This device is not registered.", "OK");
                CanExecuteCommands = false;
                return;
            }

            CanExecuteCommands = true;

            var empNo = deviceID.EmpNo;

            if (empNo == null)
            {
                Application.Current.MainPage.DisplayAlert("Error", "Cannot find Employee No.", "OK");
                return;
            }

            // Fetch the employee's name from the Employee table
            var employee = App._dbContext2.EmployeeTable.FirstOrDefault(e => e.EmpNo == empNo);
            if (employee == null)
            {
                Application.Current.MainPage.DisplayAlert("Error", "Cannot find Employee.", "OK");
                return;
            }
            EmployeeName = $"{employee.FName} {employee.LName}";

            objlist = new ObservableCollection<Table3>(
                App._dbContext2.Table3
                    .Where(ob => ob.EmpNo == empNo && ob.Date.HasValue && ob.Date.Value.Date == DateTime.Today)
                    .ToList()
            );

            TimeInCommand = new Command(() => UpdateMethod("I", empNo.Value), () => CanExecuteCommands);
            TimeOutCommand = new Command(() => UpdateMethod("O", empNo.Value), () => CanExecuteCommands);
        }
```
