### ISSUE TITLE
Android - Setting only SelectedTabColor on TabbedPage causes System.NullReferenceException

### ISSUE THREAD

**Issue by Asfiroth** [dotnet/maui#19299]
### Description

Setting `TabbedPage` property `SelectedTabColor`, either by code or XAML, causes `NullReferenceException` on Android when `UnselectedTabColor` is not present. 

On iOS it works properly.

### Steps to Reproduce

1. Create a TabbedPage.
2. Set the `SelectedTabColor` in either the XAML or in code for the TabbedPage

### Link to public reproduction project repository

https://github.com/Asfiroth/MauiTabbedPageIssue

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android API 33

### Relevant log output

```shell
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Maui.Graphics.Platform.GraphicsExtensions.AsColor(Color target) in D:\a\_work\1\s\src\Graphics\src\Graphics\Platforms\Android\GraphicsExtensions.cs:line 28
   at Microsoft.Maui.Platform.ColorExtensions.ToPlatform(Color self) in D:\a\_work\1\s\src\Core\src\Platform\Android\ColorExtensions.cs:line 14
   at Microsoft.Maui.Controls.Handlers.TabbedPageManager.GetItemIconTintColorState() in D:\a\_work\1\s\src\Controls\src\Core\Platform\Android\TabbedPageManager.cs:line 624
   at Microsoft.Maui.Controls.Handlers.TabbedPageManager.UpdateItemIconColor() in D:\a\_work\1\s\src\Controls\src\Core\Platform\Android\TabbedPageManager.cs:line 670
   at Microsoft.Maui.Controls.Handlers.TabbedPageManager.UpdateTabItemStyle() in D:\a\_work\1\s\src\Controls\src\Core\Platform\Android\TabbedPageManager.cs:line 702
   at Microsoft.Maui.Controls.TabbedPage.MapBarTextColor(ITabbedViewHandler handler, TabbedPage view) in D:\a\_work\1\s\src\Controls\src\Core\TabbedPage\TabbedPage.Android.cs:line 64
   at Microsoft.Maui.PropertyMapperExtensions.<>c__DisplayClass2_0`2[[Microsoft.Maui.Controls.TabbedPage, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.ITabbedViewHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<ReplaceMapping>b__0(ITabbedViewHandler h, TabbedPage v, Action`2 p) in D:\a\_work\1\s\src\Core\src\PropertyMapperExtensions.cs:line 66
   at Microsoft.Maui.PropertyMapperExtensions.<>c__DisplayClass1_0`2[[Microsoft.Maui.Controls.TabbedPage, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.ITabbedViewHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<ModifyMapping>g__newMethod|0(IElementHandler handler, IElement view) in D:\a\_work\1\s\src\Core\src\PropertyMapperExtensions.cs:line 46
   at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0[[Microsoft.Maui.ITabbedView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.ITabbedViewHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v) in D:\a\_work\1\s\src\Core\src\PropertyMapper.cs:line 172
   at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IElementHandler viewHandler, IElement virtualView) in D:\a\_work\1\s\src\Core\src\PropertyMapper.cs:line 47
   at Microsoft.Maui.PropertyMapper.UpdateProperties(IElementHandler viewHandler, IElement virtualView) in D:\a\_work\1\s\src\Core\src\PropertyMapper.cs:line 82
   at Microsoft.Maui.Handlers.ElementHandler.SetVirtualView(IElement view) in D:\a\_work\1\s\src\Core\src\Handlers\Element\ElementHandler.cs:line 79
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.ITabbedView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Android.Views.View, Mono.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065]].SetVirtualView(IView view) in D:\a\_work\1\s\src\Core\src\Handlers\View\ViewHandlerOfT.cs:line 53
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.ITabbedView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Android.Views.View, Mono.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065]].SetVirtualView(IElement view) in D:\a\_work\1\s\src\Core\src\Handlers\View\ViewHandlerOfT.cs:line 56
   at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler) in D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:line 921
   at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value) in D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:line 863
   at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.set_Handler(IElementHandler value) in D:\a\_work\1\s\src\Controls\src\Core\VisualElement\VisualElement.cs:line 2031
   at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context) in D:\a\_work\1\s\src\Core\src\Platform\ElementExtensions.cs:line 96
   at Microsoft.Maui.Platform.ElementExtensions.ToPlatform(IElement view, IMauiContext context) in D:\a\_work\1\s\src\Core\src\Platform\ElementExtensions.cs:line 127
   at Microsoft.Maui.Platform.ScopedFragment.OnCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) in D:\a\_work\1\s\src\Core\src\Platform\Android\Navigation\ScopedFragment.cs:line 32
   at AndroidX.Fragment.App.Fragment.n_OnCreateView_Landroid_view_LayoutInflater_Landroid_view_ViewGroup_Landroid_os_Bundle_(IntPtr jnienv, IntPtr native__this, IntPtr native_inflater, IntPtr native_container, IntPtr native_savedInstanceState) in C:\a\_work\1\s\generated\androidx.fragment.fragment\obj\Release\net6.0-android\generated\src\AndroidX.Fragment.App.Fragment.cs:line 2031
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPLLL_L(_JniMarshal_PPLLL_L callback, IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 367
```

**Comment by PureWeen** [comment]
Started a branch here

https://github.com/dotnet/maui/tree/fix_19299

The fix on this one should be pretty simple but I didn't like how the defaults were pulled so I started some work on that branch to pull them from the styles which should be more resilient long term as well.

**Comment by aritchie** [comment]
@PureWeen Any thoughts on how I could workaround this.  I've tried to create an override on the renderer to incorporate your fix, but I can't seem to get access to the resource links in your fix

**Comment by PureWeen** [comment]
> @PureWeen Any thoughts on how I could workaround this. I've tried to create an override on the renderer to incorporate your fix, but I can't seem to get access to the resource links in your fix

We should hopefully have a fix for this in SR3

in the meantime you should be able to add a mapper replacement to `TabbedViewHandler.Mapper` to replace `MapBarTextColor`

**Comment by stefandb1995** [comment]
@PureWeen Would you mind sending an example of the mapper replacement code? I tried the following but still getting the error

`            TabbedViewHandler.Mapper.ReplaceMapping<TabbedPage, ITabbedViewHandler>(TabbedPage.SelectedTabColorProperty.PropertyName, MapSelectedTabColor);`

Still new to the whole mapper thing so any help would be appreciated!

**Comment by PureWeen** [comment]
@stefandb1995 8.0.10 that released today should have this fixed
