### ISSUE TITLE
App crash when is started from another app.

### ISSUE THREAD

**Issue by prok155** [dotnet/maui#19374]
### Description

I have an app in google play store and when I launch it from the store, click home background and then click app icon, the app is crashing. I created 2 apps for you and you can easily reproduce this bug.

### Steps to Reproduce

1. Download NewMauiApp1 and NewMauiApp2.
2. Start NewMauiApp1
3. Click button which will start NewMauiApp2
4. Click home button on android device
5. Tap NewMauiApp2 app icon.
6. NewMauiApp2 should simply show up. Instead, we see the splash screen again and the application will probably crash (but sometimes it's not crashing).

### Link to public reproduction project repository

https://github.com/prok155/NewMauiApp1
https://github.com/prok155/NewMauiApp2
### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Relevant log output

Stacktrace from google play console:
```shell
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.companyname.newmauiapp2/crc64981dfae6ceaa18fa.MainActivity}: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3340)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3493)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2057)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7649)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:503)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by prok155** [comment]
When you will try to reproduce it, you should do it on a physical device, because on emulators NewMauiApp2 doesn't launch from NewMauiApp1 (PackageManager doesn't find a package, I don't know why).

**Comment by prok155** [comment]
Today I saw that when the app sends notifications, this bug also occurs. When I tap notification (which start the app), tap home button and tap app icon, behaviour is the same, I see the splash screen again and the application sometimes is crashing.

**Comment by PureWeen** [comment]
I'm guessing this is related to https://github.com/dotnet/maui/issues/11501

**Comment by faizifayiz** [comment]
When using on devices above android 10 version ..the launcher code is not working. .any solution?

**Comment by nor0x** [comment]
I am running into the same issue. I have set an IntentFilter to enable the app to be launched from the share dialog for plaintext
`[IntentFilter(new[] { Intent.ActionSend }, Categories = new[] { Intent.CategoryDefault }, DataMimeType = @"text/plain")]`

and it crashes in the `OnCreate` method. No manual MainPage swapping is happening in my app.

```
    protected override void OnCreate(Bundle savedInstanceState)
    {
        base.OnCreate(savedInstanceState);
        if(Intent.ActionSend.Equals(Intent.Action) && Intent.Type != null)
        ...
   }
```

anyone found a workaround?

**Comment by PureWeen** [comment]
@prok155  are you still hitting this on the latest 8.0.71 release?

I haven't been able to reproduce. It always opens for me. What API level is the device you are running on?

**Comment by prok155** [comment]
I don't know if this issue was fixed, I converted my app to flutter and I won't use Maui in the near future. 

I had this issue on real devices (not simulators), so if you can't reproduce it on real device with the latest version, you can close this issue.
