### ISSUE TITLE
Maui App won't compile

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#19401]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Maui-App-wont-compile/10537567)._

```
/usr/local/share/dotnet/packs/Microsoft.Maui.Resizetizer.Sdk/7.0.101/targets/Microsoft.Maui.Resizetizer.targets(9,9): Error MAUI0000: System.MissingMethodException: Method not found: 'SkiaSharp.SKTextBlob SkiaSharp.SKTextBlob.CreatePositioned(System.String, SkiaSharp.SKFont, System.ReadOnlySpan`1<SkiaSharp.SKPoint>)'.
   at Svg.Skia.SkiaModelExtensions.Draw(CanvasCommand canvasCommand, SKCanvas skCanvas)
   at Svg.Skia.SkiaModelExtensions.Draw(SKPicture picture, SKCanvas skCanvas) in /_/src/Svg.Skia/SkiaModelExtensions.cs:line 1054
   at Svg.Skia.SkiaModelExtensions.ToSKPicture(SKPicture picture) in /_/src/Svg.Skia/SkiaModelExtensions.cs:line 933
   at Svg.Skia.SKSvg.Load(String path) in /_/src/Svg.Skia/SKSvg.cs:line 70
   at Microsoft.Maui.Resizetizer.SkiaSharpSvgTools..ctor(String filename, Nullable`1 baseSize, Nullable`1 backgroundColor, Nullable`1 tintColor, ILogger logger) in D:\a\_work\1\s\src\SingleProject\Resizetizer\src\SkiaSharpSvgTools.cs:line 24
   at Microsoft.Maui.Resizetizer.SkiaSharpTools.Create(Boolean isVector, String filename, Nullable`1 baseSize, Nullable`1 backgroundColor, Nullable`1 tintColor, ILogger logger) in D:\a\_work\1\s\src\SingleProject\Resizetizer\src\SkiaSharpTools.cs:line 21
   at Microsoft.Maui.Resizetizer.SkiaSharpAppIconTools..ctor(ResizeImageInfo info, ILogger logger) in D:\a\_work\1\s\src\SingleProject\Resizetizer\src\SkiaSharpAppIconTools.cs:line 24
   at Microsoft.Maui.Resizetizer.ResizetizeImages.ProcessAppIcon(ResizeImageInfo img, ConcurrentBag`1 resizedImages) in D:\a\_work\1\s\src\SingleProject\Resizetizer\src\ResizetizeImages.cs:line 163
   at Microsoft.Maui.Resizetizer.ResizetizeImages.<>c__DisplayClass26_0.<ExecuteAsync>b__0(ResizeImageInfo img) in D:\a\_work\1\s\src\SingleProject\Resizetizer\src\ResizetizeImages.cs:line 56
   at Microsoft.Maui.Resizetizer.AsyncTaskExtensions.<>c__DisplayClass0_0`1.<ParallelForEach>b__0(TSource s) in D:\a\_work\1\s\src\SingleProject\Resizetizer\src\AsyncTaskExtensions.cs:line 21 (MAUI0000) (Psrm.Maui)
```

#### Feedback Bot on 12/10/2023, 05:38 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by PureWeen** [comment]
Can you also attach a binlog?
https://github.com/xamarin/xamarin-macios/wiki/Diagnosis

**Comment by jfxdev01** [comment]
I have the same problem

> _This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Maui-App-wont-compile/10537567)._
> 
> ```
> /usr/local/share/dotnet/packs/Microsoft.Maui.Resizetizer.Sdk/7.0.101/targets/Microsoft.Maui.Resizetizer.targets(9,9): Error MAUI0000: System.MissingMethodException: Method not found: 'SkiaSharp.SKTextBlob SkiaSharp.SKTextBlob.CreatePositioned(System.String, SkiaSharp.SKFont, System.ReadOnlySpan`1<SkiaSharp.SKPoint>)'.
>    at Svg.Skia.SkiaModelExtensions.Draw(CanvasCommand canvasCommand, SKCanvas skCanvas)
>    at Svg.Skia.SkiaModelExtensions.Draw(SKPicture picture, SKCanvas skCanvas) in /_/src/Svg.Skia/SkiaModelExtensions.cs:line 1054
>    at Svg.Skia.SkiaModelExtensions.ToSKPicture(SKPicture picture) in /_/src/Svg.Skia/SkiaModelExtensions.cs:line 933
>    at Svg.Skia.SKSvg.Load(String path) in /_/src/Svg.Skia/SKSvg.cs:line 70
>    at Microsoft.Maui.Resizetizer.SkiaSharpSvgTools..ctor(String filename, Nullable`1 baseSize, Nullable`1 backgroundColor, Nullable`1 tintColor, ILogger logger) in D:\a\_work\1\s\src\SingleProject\Resizetizer\src\SkiaSharpSvgTools.cs:line 24
>    at Microsoft.Maui.Resizetizer.SkiaSharpTools.Create(Boolean isVector, String filename, Nullable`1 baseSize, Nullable`1 backgroundColor, Nullable`1 tintColor, ILogger logger) in D:\a\_work\1\s\src\SingleProject\Resizetizer\src\SkiaSharpTools.cs:line 21
>    at Microsoft.Maui.Resizetizer.SkiaSharpAppIconTools..ctor(ResizeImageInfo info, ILogger logger) in D:\a\_work\1\s\src\SingleProject\Resizetizer\src\SkiaSharpAppIconTools.cs:line 24
>    at Microsoft.Maui.Resizetizer.ResizetizeImages.ProcessAppIcon(ResizeImageInfo img, ConcurrentBag`1 resizedImages) in D:\a\_work\1\s\src\SingleProject\Resizetizer\src\ResizetizeImages.cs:line 163
>    at Microsoft.Maui.Resizetizer.ResizetizeImages.<>c__DisplayClass26_0.<ExecuteAsync>b__0(ResizeImageInfo img) in D:\a\_work\1\s\src\SingleProject\Resizetizer\src\ResizetizeImages.cs:line 56
>    at Microsoft.Maui.Resizetizer.AsyncTaskExtensions.<>c__DisplayClass0_0`1.<ParallelForEach>b__0(TSource s) in D:\a\_work\1\s\src\SingleProject\Resizetizer\src\AsyncTaskExtensions.cs:line 21 (MAUI0000) (Psrm.Maui)
> ```
> 
> ### Original Comments
> #### Feedback Bot on 12/10/2023, 05:38 PM:
> (private comment, text removed)
> 
> ### Original Solutions
> (no solutions)
