### ISSUE TITLE
[UITEst] Windows Controls Unpackaged occasionally crashes with IndexOutOfRangeException

### ISSUE THREAD

**Issue by PureWeen** [dotnet/maui#19463]
### Description

Windows Controls Unpackaged occassionally fails with

```
2023-12-17T03:08:52.3297323Z System.IndexOutOfRangeException: Index was outside the bounds of the array.
2023-12-17T03:08:52.3299270Z    at Microsoft.Maui.TestUtils.DeviceTests.Runners.HeadlessRunner.ControlsHeadlessTestRunner.GetTestRunner(LogWriter logWriter) in D:\a\1\s\src\TestUtils\src\DeviceTests.Runners\HeadlessRunner\Windows\ControlsHeadlessTestRunner.cs:line 72
2023-12-17T03:08:52.3300533Z    at Microsoft.DotNet.XHarness.TestRunners.Common.ApplicationEntryPoint.InternalRunAsync(LogWriter logger)
2023-12-17T03:08:52.3301463Z    at Microsoft.DotNet.XHarness.TestRunners.Xunit.AndroidApplicationEntryPoint.RunAsync()
2023-12-17T03:08:52.3302930Z    at Microsoft.Maui.TestUtils.DeviceTests.Runners.HeadlessRunner.ControlsHeadlessTestRunner.RunTestsAsync() in D:\a\1\s\src\TestUtils\src\DeviceTests.Runners\HeadlessRunner\Windows\ControlsHeadlessTestRunner.cs:line 96
2023-12-17T03:08:53.3804057Z Waiting 1 additional second(s) for tests to finish...
```

https://dev.azure.com/xamarin/public/_build/results?buildId=103877&view=logs&j=722c0ef8-c95f-58b3-2e9e-70f3c11414f6&t=1339f918-75ec-5b22-60c5-4eba5e80492f

**Comment by jfversluis** [comment]
Hm interesting. I can see the first attempt for this is missing the Frame category. So it crashed running those tests? Can't really tell from the logs if that's the case. Do you have any other occurrences? Is it always that category?

**Comment by jfversluis** [comment]
Happened again here: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=8843927&view=logs&s=7090772a-ca02-5cb2-e85f-3e155fe0af09&j=722c0ef8-c95f-58b3-2e9e-70f3c11414f6
