### ISSUE TITLE
[graphics] PlatformCanvas.DrawImageCallback throws System.NullReferenceException when using ImagePaint on Mac/iOS

### ISSUE THREAD

**Issue by peterblazejewicz** [dotnet/maui#19642]
### Description

when using canvas from platform drawables, like in Maui 8.0 `GraphicsViewDemos`, whenever ImagePain is used on iOS/Mac (works on Android implementation), platform throws:
```console
Object reference not set to an instance of an object. (System.NullReferenceException)
   at Microsoft.Maui.Graphics.Platform.PlatformCanvas.DrawImageCallback(CGContext context)
   at CoreGraphics.CGPattern.DrawCallback(IntPtr voidptr, IntPtr cgcontextptr) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/CoreGraphics/CGPattern.cs:line 144
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 58
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 94
   at GraphicsViewDemos.Program.Main(String[] args) in /Users/blazejewicz/develop/maui-samples/8.0/UserInterface/Views/GraphicsViewDemos/GraphicsViewDemos/Platforms/MacCatalyst/Program.cs:line 13
```

so here:
https://github.com/dotnet/maui/blob/39440043ce9f69f0c8f275bc5a4dd083bdae1c7e/src/Graphics/src/Graphics/Platforms/MaciOS/PlatformCanvas.cs#L644
`_fillImage` is already released and null.

### Steps to Reproduce

1. Go to Maui samples
2. open `GraphicsViewDemos`
3. open `Image paint demo` page

Should render downsized bot image (as on Android), instead it crashes (image is drawn, but app crashes due to null pointer)

### Link to public reproduction project repository

https://github.com/dotnet/maui-samples/issues/336

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

Mac OS 14, iOS 15

### Did you find any workaround?

no

### Relevant log output

```shell
https://github.com/dotnet/maui-samples/issues/336#issuecomment-1873323734
```

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.9.0 Preview 4(8.0.3). Repro on iOS 17.2 and MacCatalyst, not repro on Android 14.0-API34 with below Project:
[GraphicsViewDemos.zip](https://github.com/dotnet/maui/files/14106809/GraphicsViewDemos.zip)

Windows: Image does not render.
![image](https://github.com/dotnet/maui/assets/97647558/be8e8c92-dd8a-4f35-a5cb-68bab7e34571)

**Comment by kbezzubov** [comment]
The changes made to the FillWithPattern method must also be made to the FillWithImage method. It also throws NRE.

**Comment by bill2004158** [comment]
I have got the same issue with MAUI 9.0.50.
it seems still not fixed yet.

**Comment by MartyIX** [comment]
> I have got the same issue with MAUI 9.0.50.
> it seems still not fixed yet.

There is this PR #28726 that fixes the issue. You can test the PR using https://github.com/dotnet/maui/wiki/Testing-PR-Builds.

**Comment by WoodlandsAggie** [comment]
Is this fix going to be released?  I'm using VS 17.14.23 along with .NET 9.  No problem on Windows platform, but iOS still crashes.

**Comment by WoodlandsAggie** [comment]
In the meantime, is there an alternative way to accomplish this for all platforms?
