### ISSUE TITLE
Caught exception in StartHotReloadAsync at 186: System.ArgumentNullException: Value cannot be null. (Parameter 'path1')

### ISSUE THREAD

**Issue by tugbadokumaci** [dotnet/maui#19699]
### Description

I have a solution. Under that, I have mobile, api and shared projects. When I run my api project and my mobile project at the same time, I get this error. hot reload does not work. This error does not appear when I run the mobile project alone.

### Steps to Reproduce

Run the QrCodeApp.Api and QrCodeApp.Mobile projects as multiple projects. You will immediately get this error.

### Link to public reproduction project repository

https://github.com/tugbadokumaci/qr-code-app

### Version with bug

7.0.101

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

### Relevant log output

```shell
Caught exception in StartHotReloadAsync at 186: System.ArgumentNullException: Value cannot be null. (Parameter 'path1')
   at System.ArgumentNullException.Throw(String paramName)
   at System.IO.Path.Combine(String path1, String path2)
   at MonoDevelop.Core.FilePath.Combine(FilePath path) in /Users/runner/work/1/s/main/src/core/MonoDevelop.Core/MonoDevelop.Core/FilePath.cs:line 312
   at Xamarin.ProjectSystem.Apple.Mobile.AppleMobileProjectState.GetCompiledOutputPathAsync(String configurationName, ExecutionTarget target) in /Users/runner/work/1/s/MonoDevelop.IPhone/MonoDevelop.IPhone/ProjectSystem/AppleMobileProjectState.cs:line 323
   at Xamarin.HotReload.VSMac.VSMacManager.GenerateVSMProjectFromSingleProjectAsync(DotNetProject project, SoftDebuggerSession debuggerSession, Boolean isDevice, SingleProjectConfiguration configuration) in /Users/runner/work/1/s/HotReload/Source/Xamarin.HotReload.VSMac/VSMacManager.cs:line 209
   at Xamarin.HotReload.VSMac.VSMacManager.StartHotReloadAsync(DotNetProject project, SoftDebuggerSession debuggerSession) in /Users/runner/work/1/s/HotReload/Source/Xamarin.HotReload.VSMac/VSMacManager.cs:line 177
   at System.ArgumentNullException.Throw(String paramName)
   at System.IO.Path.Combine(String path1, String path2)
   at MonoDevelop.Core.FilePath.Combine(FilePath path) in /Users/runner/work/1/s/main/src/core/MonoDevelop.Core/MonoDevelop.Core/FilePath.cs:line 312
   at Xamarin.ProjectSystem.Apple.Mobile.AppleMobileProjectState.GetCompiledOutputPathAsync(String configurationName, ExecutionTarget target) in /Users/runner/work/1/s/MonoDevelop.IPhone/MonoDevelop.IPhone/ProjectSystem/AppleMobileProjectState.cs:line 323
   at Xamarin.HotReload.VSMac.VSMacManager.GenerateVSMProjectFromSingleProjectAsync(DotNetProject project, SoftDebuggerSession debuggerSession, Boolean isDevice, SingleProjectConfiguration configuration) in /Users/runner/work/1/s/HotReload/Source/Xamarin.HotReload.VSMac/VSMacManager.cs:line 209
   at Xamarin.HotReload.VSMac.VSMacManager.StartHotReloadAsync(DotNetProject project, SoftDebuggerSession debuggerSession) in /Users/runner/work/1/s/HotReload/Source/Xamarin.HotReload.VSMac/VSMacManager.cs:line 177
```

**Comment by drasticactions** [comment]
Stepping through the code, I believe the underlying fault is a regression (or at least a change of functionality) with VS For Mac. If you set up multiple startup projects, and if one of those projects isn't a deployable mobile one, it would return an empty value for a path, so it would be ignored. Now it's throwing inside of VSMac itself.

Regardless, it's a Visual Studio issue, it can't be fixed in this repo.
