### ISSUE TITLE
iOS 12.4.4 - ENTRY control |  Arg_NullReferenceException | at TextFieldExtensions.GetClearButtonTintImage

### ISSUE THREAD

**Issue by SailDev** [dotnet/maui#19748]
### Description

For testing on devices with lower specs, i use an old IPad mini with iOS 12.4.4.

Using an Entry control causes the following Exception:

**Arg_NullReferenceException**

```
Stack Trace:
   at Microsoft.Maui.Platform.TextFieldExtensions.GetClearButtonTintImage(UIImage image, UIColor color)

   at Microsoft.Maui.Platform.TextFieldExtensions.UpdateClearButtonColor(UITextField textField, IEntry entry)
   at Microsoft.Maui.Platform.TextFieldExtensions.UpdateClearButtonVisibility(UITextField textField, IEntry entry)
   at Microsoft.Maui.Handlers.EntryHandler.MapClearButtonVisibility(IEntryHandler handler, IEntry entry)
   at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0[[Microsoft.Maui.IEntry, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.IEntryHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v)
   at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IElementHandler viewHandler, IElement virtualView)
   at Microsoft.Maui.PropertyMapper.UpdateProperties(IElementHandler viewHandler, IElement virtualView)
   at Microsoft.Maui.Handlers.ElementHandler.SetVirtualView(IElement view)
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IEntry, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.MauiTextField, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IView view)
   at Microsoft.Maui.Handlers.EntryHandler.SetVirtualView(IView view)
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IEntry, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.MauiTextField, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IElement view)
   at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler)
   at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.set_Handler(IElementHandler value)
   at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context)
   at Microsoft.Maui.Platform.ElementExtensions.ToPlatform(IElement view, IMauiContext context)
   at Microsoft.Maui.Handlers.ContentViewHandler.UpdateContent(IContentViewHandler handler)
. . .
```

### Steps to Reproduce

Use any Entry control

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 12.4.4 fails (iOS 16.2 is O.K)

### Did you find any workaround?

A quick workaround.

```
    public static void Fix19748(ref Entry entryField)
    {
        // Default for all systems
        entryField.ClearButtonVisibility = ClearButtonVisibility.WhileEditing;
        if (!OperatingSystem.IsIOS()) return;
        
        // Special behaviour for iOS < 16
        if (!OperatingSystem.IsIOSVersionAtLeast(16))
            entryField.ClearButtonVisibility = ClearButtonVisibility.Never;
    }
```

**Comment by omer-ays** [comment]
I have the same problem with IOS 12.5.7. Is there any solution?

**Comment by thomasgalliker** [comment]
Verified that this bug still exists in MauiVersion 8.0.61; iPhone 6 with iOS 12.5.7.

**Comment by PureWeen** [comment]
Does this happen on devices that are iOS13+ ?

**Comment by thomasgalliker** [comment]
@PureWeen no, as far as I know it only appears on <= iOS 12.

**Comment by jfversluis** [comment]
I can't seem to download a iOS 12 Simulator anymore. You mentioned this worked in a previous .NET MAUI version, so you know which one? Is this still an issue with the latest .NET 8 version?

**Comment by SailDev** [comment]
Just tested it with MAUI 8.0.80 in release and debug mode on a physical IPad mini with iOS 12.4.4
The problem still exists, but i can live with the workaround.
The issue could be closed.

**Comment by jfversluis** [comment]
Thanks for letting us know!
