### ISSUE TITLE
[Android] ShellContent Visibility change leads to KeyNotFoundException: Microsoft.Maui.Controls.SetterSpecificity

### ISSUE THREAD

**Issue by kklose23** [dotnet/maui#19762]
### Description

See repro steps and log output

### Steps to Reproduce

1. Create shell flyout items
2. Make an implicit label style with AppThemeBinding TextColor set
3. Make `FlyoutItemLabelStyle` class style with AppThemeBinding TextColor set
4. Run app and dynamically change `IsVisible` for a `ShellContent` item

### Link to public reproduction project repository

https://github.com/kklose23/shell-visibility-issue

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Did you find any workaround?

No

### Relevant log output

```shell
System.Collections.Generic.KeyNotFoundException: The given key 'Microsoft.Maui.Controls.SetterSpecificity' was not present in the dictionary.
   at System.Collections.Generic.SortedList`2[[Microsoft.Maui.Controls.SetterSpecificity, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Controls.BindingBase, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].get_Item(SetterSpecificity key)
   at Microsoft.Maui.Controls.BindableObject.RemoveBinding(BindableProperty property, BindablePropertyContext context, SetterSpecificity specificity) in D:\\a\\_work\\1\\s\\src\\Controls\\src\\Core\\BindableObject.cs:line 705
   at Microsoft.Maui.Controls.BindableObject.RemoveBinding(BindableProperty property, SetterSpecificity specificity) in D:\\a\\_work\\1\\s\\src\\Controls\\src\\Core\\BindableObject.cs:line 269
   at Microsoft.Maui.Controls.Setter.UnApply(BindableObject target, SetterSpecificity specificity) in D:\\a\\_work\\1\\s\\src\\Controls\\src\\Core\\Setter.cs:line 98
   at Microsoft.Maui.Controls.Style.UnApplyCore(BindableObject bindable, Style basedOn) in D:\\a\\_work\\1\\s\\src\\Controls\\src\\Core\\Style.cs:line 191
   at Microsoft.Maui.Controls.Style.Microsoft.Maui.Controls.IStyle.UnApply(BindableObject bindable) in D:\\a\\_work\\1\\s\\src\\Controls\\src\\Core\\Style.cs:line 115
   at Microsoft.Maui.Controls.MergedStyle.SetStyle(IStyle implicitStyle, IList`1 classStyles, IStyle style) in D:\\a\\_work\\1\\s\\src\\Controls\\src\\Core\\MergedStyle.cs:line 193
   at Microsoft.Maui.Controls.MergedStyle.set_ClassStyles(IList`1 value) in D:\\a\\_work\\1\\s\\src\\Controls\\src\\Core\\MergedStyle.cs:line 87
   at Microsoft.Maui.Controls.MergedStyle.OnClassStyleChanged() in D:\\a\\_work\\1\\s\\src\\Controls\\src\\Core\\MergedStyle.cs:line 126
   at Microsoft.Maui.Controls.MergedStyle.<set_StyleClass>b__13_0(BindableObject bindable, Object oldvalue, Object newvalue) in D:\\a\\_work\\1\\s\\src\\Controls\\src\\Core\\MergedStyle.cs:line 70
   at Microsoft.Maui.Controls.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, SetterSpecificity specificity, Boolean silent) in D:\\a\\_work\\1\\s\\src\\Controls\\src\\Core\\BindableObject.cs:line 633
   at Microsoft.Maui.Controls.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes, SetterSpecificity specificity) in D:\\a\\_work\\1\\s\\src\\Controls\\src\\Core\\BindableObject.cs:line 559
   at Microsoft.Maui.Controls.Element.OnResourceChanged(BindableProperty property, Object value, SetterSpecificity specificity) in D:\\a\\_work\\1\\s\\src\\Controls\\src\\Core\\Element\\Element.cs:line 815
   at Microsoft.Maui.Controls.Element.OnSetDynamicResource(BindableProperty property, String key, SetterSpecificity specificity) in D:\\a\\_work\\1\\s\\src\\Controls\\src\\Core\\Element\\Element.cs:line 688
   at Microsoft.Maui.Controls.MergedStyle.set_StyleClass(IList`1 value) in D:\\a\\_work\\1\\s\\src\\Controls\\src\\Core\\MergedStyle.cs:line 72
   at Microsoft.Maui.Controls.NavigableElement.set_class(IList`1 value) in D:\\a\\_work\\1\\s\\src\\Controls\\src\\Core\\Shell\\NavigableElement.cs:line 60
   at Microsoft.Maui.Controls.NavigableElement.set_StyleClass(IList`1 value) in D:\\a\\_work\\1\\s\\src\\Controls\\src\\Core\\Shell\\NavigableElement.cs:line 50
   at Microsoft.Maui.Controls.BaseShellItem.UpdateFlyoutItemStyles(Grid flyoutItemCell, IStyleSelectable source) in D:\\a\\_work\\1\\s\\src\\Controls\\src\\Core\\Shell\\BaseShellItem.cs:line 320
   at Microsoft.Maui.Controls.BaseShellItem.<>c__DisplayClass81_1.<CreateDefaultFlyoutItemCell>b__1(Object sender, EventArgs _) in D:\\a\\_work\\1\\s\\src\\Controls\\src\\Core\\Shell\\BaseShellItem.cs:line 515
   at Microsoft.Maui.Controls.BindableObject.OnBindingContextChanged() in D:\\a\\_work\\1\\s\\src\\Controls\\src\\Core\\BindableObject.cs:line 368
   at Microsoft.Maui.Controls.Element.OnBindingContextChanged() in D:\\a\\_work\\1\\s\\src\\Controls\\src\\Core\\Element\\Element.cs:line 517
   at Microsoft.Maui.Controls.VisualElement.OnBindingContextChanged() in D:\\a\\_work\\1\\s\\src\\Controls\\src\\Core\\VisualElement\\VisualElement.cs:line 1231
   at Microsoft.Maui.Controls.View.OnBindingContextChanged() in D:\\a\\_work\\1\\s\\src\\Controls\\src\\Core\\View\\View.cs:line 255
   at Microsoft.Maui.Controls.Grid.OnBindingContextChanged() in D:\\a\\_work\\1\\s\\src\\Controls\\src\\Core\\Layout\\Grid.cs:line 353
   at Microsoft.Maui.Controls.BindableObject.BindingContextPropertyChanged(BindableObject bindable, Object oldvalue, Object newvalue) in D:\\a\\_work\\1\\s\\src\\Controls\\src\\Core\\BindableObject.cs:line 674
   at Microsoft.Maui.Controls.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, SetterSpecificity specificity, Boolean silent) in D:\\a\\_work\\1\\s\\src\\Controls\\src\\Core\\BindableObject.cs:line 633
   at Microsoft.Maui.Controls.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes, SetterSpecificity specificity) in D:\\a\\_work\\1\\s\\src\\Controls\\src\\Core\\BindableObject.cs:line 559
   at Microsoft.Maui.Controls.BindableObject.SetValue(BindableProperty property, Object value) in D:\\a\\_work\\1\\s\\src\\Controls\\src\\Core\\BindableObject.cs:line 464
   at Microsoft.Maui.Controls.BindableObject.set_BindingContext(Object value) in D:\\a\\_work\\1\\s\\src\\Controls\\src\\Core\\BindableObject.cs:line 54
   at Microsoft.Maui.Controls.Platform.Compatibility.ShellFlyoutRecyclerAdapter.ElementViewHolder.set_Element(Element value) in D:\\a\\_work\\1\\s\\src\\Controls\\src\\Core\\Compatibility\\Handlers\\Shell\\Android\\ShellFlyoutRecyclerAdapter.cs:line 282
   at Microsoft.Maui.Controls.Platform.Compatibility.ShellFlyoutRecyclerAdapter.OnViewRecycled(Object holder) in D:\\a\\_work\\1\\s\\src\\Controls\\src\\Core\\Compatibility\\Handlers\\Shell\\Android\\ShellFlyoutRecyclerAdapter.cs:line 98
   at AndroidX.RecyclerView.Widget.RecyclerView.Adapter.n_OnViewRecycled_Landroidx_recyclerview_widget_RecyclerView_ViewHolder_(IntPtr jnienv, IntPtr native__this, IntPtr native_holder) in C:\\a\\_work\\1\\s\\generated\\androidx.recyclerview.recyclerview\\obj\\Release\
et6.0-android\\generated\\src\\AndroidX.RecyclerView.Widget.RecyclerView.cs:line 793
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPL_V(_JniMarshal_PPL_V callback, IntPtr jnienv, IntPtr klazz, IntPtr p0) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 125
   at Java.Interop.JniEnvironment.InstanceMethods.CallNonvirtualVoidMethod(JniObjectReference instance, JniObjectReference type, JniMethodInfo method, JniArgumentValue* args) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/obj/Release/net7.0/JniEnvironment.g.cs:line 20825
   at Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualVoidMethod(String encodedMember, IJavaPeerable self, JniArgumentValue* parameters) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:line 75
   at AndroidX.CoordinatorLayout.Widget.CoordinatorLayout.OnLayout(Boolean changed, Int32 l, Int32 t, Int32 r, Int32 b) in C:\\a\\_work\\1\\s\\generated\\androidx.coordinatorlayout.coordinatorlayout\\obj\\Release\
et6.0-android\\generated\\src\\AndroidX.CoordinatorLayout.Widget.CoordinatorLayout.cs:line 2704
   at Microsoft.Maui.Controls.Platform.Compatibility.ShellFlyoutLayout.OnLayout(Boolean changed, Int32 left, Int32 top, Int32 right, Int32 bottom) in D:\\a\\_work\\1\\s\\src\\Controls\\src\\Core\\Compatibility\\Handlers\\Shell\\Android\\ShellFlyoutLayout.cs:line 34
   at AndroidX.CoordinatorLayout.Widget.CoordinatorLayout.n_OnLayout_ZIIII(IntPtr jnienv, IntPtr native__this, Boolean changed, Int32 l, Int32 t, Int32 r, Int32 b) in C:\\a\\_work\\1\\s\\generated\\androidx.coordinatorlayout.coordinatorlayout\\obj\\Release\
et6.0-android\\generated\\src\\AndroidX.CoordinatorLayout.Widget.CoordinatorLayout.cs:line 2688
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPZIIII_V(_JniMarshal_PPZIIII_V callback, IntPtr jnienv, IntPtr klazz, Boolean p0, Int32 p1, Int32 p2, Int32 p3, Int32 p4) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 444
```

**Comment by arahmancsd** [comment]
This works in workload 8.0.100

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio 17.10.0 preview2 (8.0.14). Can repro on android platform with sample project. 
![image](https://github.com/dotnet/maui/assets/77434865/4bda91e1-4d8a-4a00-9a72-6d35327a9baa)

**Comment by KaraVehizen** [comment]
It turns out the issue came from styles.

I had this     

<Style Class="FlyoutItemLayoutStyle" TargetType="Layout" ApplyToDerivedTypes="True">
        <Setter Property="VisualStateManager.VisualStateGroups">
            <VisualStateGroupList>
                <VisualStateGroup x:Name="CommonStates">
                    <VisualState x:Name="Normal">
                        <VisualState.Setters>
                            <Setter Property="BackgroundColor"
                                    Value="{AppThemeBinding Dark={StaticResource BackgroundColorDark},
                        Light={StaticResource BackgroundColorLight}}" />
                        </VisualState.Setters>
                    </VisualState>
                    <VisualState x:Name="Selected">
                        <VisualState.Setters>
                            <Setter Property="BackgroundColor"
                                    Value="{AppThemeBinding Dark={StaticResource PrimaryBackgroundDark}, Light={StaticResource PrimaryBackgroundLight}}" />
                        </VisualState.Setters>
                    </VisualState>
                </VisualStateGroup>
            </VisualStateGroupList>
        </Setter>
    </Style>

i changed the class to "MenuItemLayoutStyle" and i no longer have the error :
    <Style Class="MenuItemLayoutStyle" TargetType="Layout" ApplyToDerivedTypes="True">
        <Setter Property="VisualStateManager.VisualStateGroups">
            <VisualStateGroupList>
                <VisualStateGroup x:Name="CommonStates">
                    <VisualState x:Name="Normal">
                        <VisualState.Setters>
                            <Setter Property="BackgroundColor"
                                    Value="{AppThemeBinding Dark={StaticResource BackgroundColorDark},
                        Light={StaticResource BackgroundColorLight}}" />
                        </VisualState.Setters>
                    </VisualState>
                    <VisualState x:Name="Selected">
                        <VisualState.Setters>
                            <Setter Property="BackgroundColor"
                                    Value="{AppThemeBinding Dark={StaticResource PrimaryBackgroundDark}, Light={StaticResource PrimaryBackgroundLight}}" />
                        </VisualState.Setters>
                    </VisualState>
                </VisualStateGroup>
            </VisualStateGroupList>
        </Setter>
    </Style>

**Comment by bilelmnasser** [comment]
any news on this, i have same problem trying to bind FlyoutItem.IsVisible in my AppShellViewModel throw this exception

**Comment by davidortinau** [comment]
Still an issue on nightly. Only option seems to be to remove the styles as reported.

**Comment by SokoFromNZ** [comment]
Waiting for a fix for this here too

**Comment by enny1170** [comment]
Same Problem here, Waiting for Fix.

**Comment by Miki42w** [comment]
I got the same issue but I have no idea what causes it

**Comment by LeonSweden** [comment]
Running Visual Studio 2022 17.10.3 and can reproduce this.
Workaround is to disable style FlyoutItemLayoutStyle as described above.

**Comment by IanWMartin** [comment]
Using shell with styles in a sub project, not using `FlyoutItemLayoutStyle` or `MenuItemLayoutStyle` This is preventing moving to .Net 8 from .Net 7, this will mean being unable release to Google Play which requires all apps to meet target API level 34 requirements before 31 Aug 2024.

**Comment by elwray** [comment]
I have the same issue. The error occurs when using Styles together with `AppThemeBinding`.

**Comment by RhomGit** [comment]
I had the same issue, removing AppThemeBinding worked for me also. Thanks (.NET 8)

<img width="563" alt="Image" src="https://github.com/user-attachments/assets/76f6b315-470f-4550-a8b1-7f6219a3da39" />

**Comment by BagavathiPerumal** [comment]
This issue is not reproduced in the latest Maui version(10.0.41). I have attached a video for reference.

https://github.com/user-attachments/assets/68ef4bf3-e337-4497-bb69-21ddb893a909
