### ISSUE TITLE
NullReferenceException in NavigationRenderer (iOS)

### ISSUE THREAD

**Issue by naaeef** [dotnet/maui#19781]
### Description

The NavigationRenderer for iOS can cause a NullReferenceException when opening a system dialog.

### Steps to Reproduce

1. Start reproduction sample
2. Click on the big blue button
3. Click on "Quick Look"
4. App is crashing

### Link to public reproduction project repository

https://github.com/naaeef/NavigationRendererReproductionSample

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Relevant log output

```shell
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Maui.Controls.Handlers.Compatibility.NavigationRenderer.SecondaryToolbar.LayoutToolbarItems(NFloat toolbarWidth, NFloat toolbarHeight, NFloat padding)
   at Microsoft.Maui.Controls.Handlers.Compatibility.NavigationRenderer.SecondaryToolbar.LayoutSubviews()
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 58
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 94
   at NavigationRendererRepro.Program.Main(String[] args) in /Users/snaef/Documents/workspaces/Test/NavigationRendererRepro/NavigationRendererRepro/Platforms/iOS/Program.cs:line 13
```

**Comment by naaeef** [comment]
If I use the code from https://stackoverflow.com/questions/34582728/how-to-find-current-uiviewcontroller-in-xamarin to get the UIViewController, it seems to work without exceptions.

**Comment by PramodMAUI** [comment]
Getting below exception in iOS app only:

{System.NullReferenceException: Object reference not set to an instance of an object. at Microsoft.Maui.Controls.Handlers.Compatibility.NavigationRenderer.ParentingViewController.WillMoveToParentViewController(UIViewController parent) at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 61 at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 96 at xxxxx.Mobile.Program.Main(String[] args

Scenario: When I manipulate the navigation stack while loading another page, the application crashes. For example, suppose I have Page1 and Page2 in the navigation stack, and I navigate to Page3 from Page2. While initializing the Page3 object, I remove Page2 from the navigation stack. After Page3 finishes loading, the application crashes.

I tried removal of page from navigation stack on Mainthread.

**Comment by ctmobiledev** [comment]
> Getting below exception in iOS app only:
> 
> {System.NullReferenceException: Object reference not set to an instance of an object. at Microsoft.Maui.Controls.Handlers.Compatibility.NavigationRenderer.ParentingViewController.WillMoveToParentViewController(UIViewController parent) at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 61 at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 96 at xxxxx.Mobile.Program.Main(String[] args
> 
> Scenario: When I manipulate the navigation stack while loading another page, the application crashes. For example, suppose I have Page1 and Page2 in the navigation stack, and I navigate to Page3 from Page2. While initializing the Page3 object, I remove Page2 from the navigation stack. After Page3 finishes loading, the application crashes.
> 
> I tried removal of page from navigation stack on Mainthread.


I just found your comment minutes ago, and it helped me resolve the same issue. I wound up getting around it with this:

```
            try
            {
                UIApplication.Main(args, null, typeof(AppDelegate));
            }
            catch (Exception ex) { 
                Debug.WriteLine(">>> Exception: " + ex.Message + "\n" + ex.StackTrace);
            }

```

Apparently, this instruction was a no-no for iOS:

`                Navigation.RemovePage(this);
`

**Comment by konradzuse** [comment]
I'm experiencing the same intermittent crash and stack trace, in my case I'm hiding the standard Back button, and implementing my our buttons in TitleView...

```
<core:BaseContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
                 xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
.....
                 NavigationPage.HasBackButton="False"
                 >
    <NavigationPage.TitleView>
        <StackLayout Orientation="Horizontal">
            <Button Style="{StaticResource NavigationBackButton}" Command="{Binding NavigateBackCommand}" />
            <Label Text="{Binding Header}" Style="{StaticResource NavigationTitle}" />
        </StackLayout>
    </NavigationPage.TitleView>
```

Null reference exception....

```
at Microsoft.Maui.Controls.Handlers.Compatibility.NavigationRenderer.SecondaryToolbar.LayoutToolbarItems(NFloat toolbarWidth, NFloat toolbarHeight, NFloat padding)
   at Microsoft.Maui.Controls.Handlers.Compatibility.NavigationRenderer.SecondaryToolbar.LayoutSubviews()
   at Microsoft.Maui.Controls.Handlers.Compatibility.NavigationRenderer.SecondaryToolbar.__Registrar_Callbacks__.callback_1235_Microsoft_Maui_Controls_Handlers_Compatibility_NavigationRenderer_SecondaryToolbar_LayoutSubviews(IntPtr pobj, IntPtr sel, IntPtr* exception_gchandle)
```

**Comment by konradzuse** [comment]
I can add that it's only crashing on older iPhones. e.g. iPhone XS max (iphone 11,6)

The stacktrace indicates an issue with the secondary toolbar items, but we removed all toolbar items with Order="Secondary" and the crash still occurs.

**Comment by BagavathiPerumal** [comment]
This issue has been verified in Visual Studio Code 1.104.0 with the latest MAUI version 9.0.110. It can be reproduced on the iOS platform.

Note: The url shared in the sample was not working so used some other url for testing.

https://github.com/user-attachments/assets/7961812c-d55f-453d-9c1e-428f64945016

**Comment by Shalini-Ashokan** [comment]
The deprecated UIApplication.SharedApplication.KeyWindow (iOS 13+) returned invalid or nil view controllers, causing QuickLook to throw a NullReferenceException. Use UIWindowScene APIs on iOS 13+ to resolve the active window and current view controller. 

https://github.com/user-attachments/assets/24b3b712-5f7c-47c5-9367-82e8c8230884


[NavigationRendererReproductionSample-main.zip](https://github.com/user-attachments/files/22771320/NavigationRendererReproductionSample-main.3.zip)
