### ISSUE TITLE
SVG Images from my nuget package not getting displayed and gives file not found exception. 

### ISSUE THREAD

**Issue by Divyesh-Bhatt** [dotnet/maui#19804]
### Description

I am developing a library project of custom controls for .Net MAUI and my controls uses SVG images. When I reference my library project in another project, the svg images I have in my library project are not showing up. 

It gives this exceptions in:
### Android exception:
```c#
[Glide] Load failed for [no_records] with dimensions [606x2154]
[Glide] class com.bumptech.glide.load.engine.GlideException: Failed to load resource
[Glide] There were 3 root causes:
[Glide] java.io.FileNotFoundException(/no_records: open failed: ENOENT (No such file or directory))
[Glide] java.io.FileNotFoundException(open failed: ENOENT (No such file or directory))
[Glide] java.io.FileNotFoundException(open failed: ENOENT (No such file or directory))
[Glide]  call GlideException#logRootCauses(String) for more detail
[Glide]   Cause (1 of 3): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class java.io.InputStream, LOCAL
[Glide] There was 1 root cause:
[Glide] java.io.FileNotFoundException(/no_records: open failed: ENOENT (No such file or directory))
[Glide]  call GlideException#logRootCauses(String) for more detail
```
### iOS exception:
```c#
Unable to load image file 'no_records'.
      System.InvalidOperationException: Unable to load image file.
Microsoft.Maui.FileImageSourceService: Warning: Unable to load image file 'no_records'.

System.InvalidOperationException: Unable to load image file.
   at Microsoft.Maui.FileImageSourceService.GetImageAsync(IFileImageSource imageSource, Single scale, CancellationToken cancellationToken)
2024-01-09 23:18:01.481191+0530 Tyler.Energov.Mobile.EH[24648:907392]          at Microsoft.Maui.FileImageSourceService.GetImageAsync(IFileImageSource imageSource, Single scale, CancellationToken cancellationToken)
2024-01-09 23:18:01.498051+0530 Tyler.Energov.Mobile.EH[24648:907392] warn: Microsoft.Maui.FileImageSourceService[0]
      Unable to load image file 'fyler_logo'.
      System.InvalidOperationException: Unable to load image file.
Microsoft.Maui.FileImageSourceService: Warning: Unable to load image file 'fyler_logo'.
```

I found this ticket #10019 so followed it. Now image get added to nuget in buildTrasitive folder, but its not showing up in the code where I'm using it. 
<img width="990" alt="Screenshot 2024-01-10 at 6 14 09 PM" src="https://github.com/dotnet/maui/assets/105337086/90865840-3756-4abc-8881-ce6b054bf50e">

### Steps to Reproduce

- Use Visual Studio to create a new .NET MAUI Class Library project and solution.
- Add a Resources folder to the project and add an Images Folder to the Resources folder.
- Add an SVG file to the Images folder added in the previous step. As noted [here](https://docs.microsoft.com/en-us/dotnet/maui/user-interface/images/images), the SVG file name must meet Android naming requirements.
- Set the SVG file's Build Action to MauiImage
- Build the solution.
- Add the nuget package in another demo project
- Try to reference the image and run the demo project.

### Version with bug

8.0.3

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

7.0.101

### Affected platforms

iOS, Android

### Affected platform versions

All

### Did you find any workaround?

Add no_records.svg file in the project where I want to use custom control using library project.

**Comment by GuidoNeele** [comment]
I used this https://github.com/dotnet/maui/issues/10019#issuecomment-1248032520 for svgs. See this repo for a sample https://github.com/awalker-dsg/MauiTestLib_10019/tree/add_targets_file/MauiTestLib_10019

**Comment by mattleibow** [comment]
I created this targets file that you can download and reference: https://github.com/mattleibow/PackagingMauiAssets/blob/main/MauiLibrary/PackMauiAssets.targets

The main cause of this issue is that the `dotnet pack` process does not know how to do anything with the maui assets, so just ignores them. Even if you add it to the package, you also need a targets file that brings them back into projects.

My linked targets file will make sure to generate all the required targets files as well.

We are still looking for a more reliable way to make this happen automatically.

**Comment by bronteq** [comment]
This bug also affects Windows platform.

I created a Maui library project with inside a custom control based on @Eilon HybridWebView; html/js code is inside Resources/Raw folder as suggested.
If the custom control is used in another Maui project which has a reference to the Maui library project, everything works fine.
If the custom control is used in another Maui project which uses the NuGet of the Maui library project, a 404 error page appears.

**Comment by bronteq** [comment]
@mattleibow targets file works and solves the issue for Windows platform, thank you! 🎉🎉🎉

**Comment by ArturWyszomirski** [comment]
@mattleibow this solution as well as the one from https://github.com/dotnet/maui/issues/10019 works well only if NuGet is used in a single project. When a project that consumes NuGet is set as a dependency of other project, it won't compile prompting error:
`One or more duplicate file names were detected.  All image output filenames must be unique: [...] C:\Users\User\.nuget\packages\microsoft.maui.resizetizer\8.0.91\buildTransitive\Microsoft.Maui.Resizetizer.After.targets 631`

**Comment by sk1llsh0t** [comment]
On Android, I can load a PNG from a shared library by using a targets file as described above. SVG files have an issue loading so i will be avoiding this for now.

Regarding fonts from a shared library, if they are referenced as an EmbeddedResource and then loaded using AddEmbeddedResourceFont, they will work. I still get this warning message though even though the font is loaded and displayed on the screen properly. I also use this method for fontawesome fonts as well.
```
Unable to load font '/data/user/0/com.companyname.exampleapp/cache/LatoItalic.ttf' from assets.|Java.Lang.RuntimeException: Font asset not found /data/user/0/com.companyname.exampleapp/cache/LatoItalic.ttf
```

Not sure why this warning is being shown when the fonts are working fine.

**Comment by maexsp** [comment]
To create a MAUI nuget package and include png, svg or ttf font(icon)-files you need ensure the files get into the nuget package packaged. You can open the nuget with a zip app and check if the generated debug/release YourNetProject.nuget contains E.g. the folder "buildTransitive\Resources\Fonts\....ttf"  or E.g. "buildTransitive\Resources\Images\....svg"

To achive this you need to include the svg or ttf like this in your YourNetProject.proj file:
```  
<ItemGroup>
  <MauiFont Include="Resources\Fonts\FontIcons.ttf" />
  <MauiImage Include="Resources\Images\addicon.svg"/>
</ItemGroup>

<ItemGroup>
  <None Include="Resources\Fonts\FontIcons.ttf" Pack="True" PackagePath="buildTransitive/Resources/Fonts" />
  <None Include="Resources\Images\addicon.svg" Pack="True" PackagePath="buildTransitive/Resources/Images" />
  <None Include="YourNetProject.props" Pack="True" PackagePath="buildTransitive" />
</ItemGroup>

```

And also add a props file to your project root (YourNetProject.props) with following definitions:
```  
<?xml version="1.0" encoding="utf-8"?>
<Project>
    <ItemGroup>
        <MauiFont Include="$(MSBuildThisFileDirectory)../buildTransitive/Resources/Fonts/FontIcons.ttf" Pack="True">
            <Link>Resources\Fonts\FontIcons.ttf</Link>
        </MauiFont>
        <MauiImage Include="$(MSBuildThisFileDirectory)../buildTransitive/Resources/Images/addicon.svg" Pack="True">
            <Link>Resources\Images\addicon.svg</Link>
        </MauiImage>
	</ItemGroup>
</Project>
```
This way you can consume the svg and also icons from the FontIcons.ttf within the nuget package (E.g. you have base controls or pages) and also in consumer MAUI projects of this nuget package you can use the icons and svg. 

Works for Debug/Release... iOS, Android and Windows ... and also if you reference "YourNetProject" directly via project references (or nuget).

BR
