### ISSUE TITLE
HeadContent not working with maui with blazor in release

### ISSUE THREAD

**Issue by WoodyJ007** [dotnet/maui#19822]
### Description

 <BlazorWebView x:Name="blazorWebView" HostPage="wwwroot/index.html">
        <BlazorWebView.RootComponents>
            <RootComponent Selector="head::after" ComponentType="{x:Type blazorweb:HeadOutlet}" />
            <RootComponent Selector="#app" ComponentType="{x:Type local:Main}" />
        </BlazorWebView.RootComponents>
    </BlazorWebView>
    
    this worked fine in 7.0 and  HeadContent would correctly be put at the bottom of the head.
    
    This was broken in 8.0 (head content was inserted at the top)
    https://github.com/dotnet/aspnetcore/issues/51391
    
    Apparently, it was fixed in 8.0.1 (but it's the same issue in Maui).
    
    Since 8.0.1 there is now a new error and Headoutlet throws an error when used in Android Release!
    
    <RootComponent Selector="head::after" ComponentType="{x:Type blazorweb:HeadOutlet}" />
    
    

rg_NoDefCTor, Microsoft.AspNetCore.Components.Web.HeadOutlet
   at System.RuntimeType.CreateInstanceMono(Boolean , Boolean )
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean , Boolean )
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at Microsoft.AspNetCore.Components.DefaultComponentActivator.CreateInstance(Type )
   at Microsoft.AspNetCore.Components.ComponentFactory.InstantiateComponent(IServiceProvider , Type , IComponentRenderMode , Nullable`1 )
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateComponent(Type )
   at Microsoft.AspNetCore.Components.RenderTree.WebRenderer.AddRootComponent(Type , String )
   at Microsoft.AspNetCore.Components.WebView.Services.WebViewRenderer.AddRootComponent(Type componentType, String domElementSelector)
   at Microsoft.AspNetCore.Components.WebView.WebViewManager.AttachToPageAsync(String baseUrl, String startUrl)
   at Microsoft.AspNetCore.Components.WebView.IpcReceiver.OnMessageReceivedAsync(PageContext pageContext, String message)
   at Microsoft.AspNetCore.Components.WebView.WebViewManager.<>c__DisplayClass18_0.<<MessageReceived>b__0>d.MoveNext()

### Steps to Reproduce

Create a maui app.  Use headoutet  head::afer on MainPage.xaml and headcontent in a shared MainLayout.razor  Debug to android will work fine.  Release build to android will throw the error and app fails to load.

### Version with bug

8.0.5

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.101

### Affected platforms

Android

### Affected platform versions

Android 13

### Relevant log output

```shell
rg_NoDefCTor, Microsoft.AspNetCore.Components.Web.HeadOutlet
   at System.RuntimeType.CreateInstanceMono(Boolean , Boolean )
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean , Boolean )
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at Microsoft.AspNetCore.Components.DefaultComponentActivator.CreateInstance(Type )
   at Microsoft.AspNetCore.Components.ComponentFactory.InstantiateComponent(IServiceProvider , Type , IComponentRenderMode , Nullable`1 )
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateComponent(Type )
   at Microsoft.AspNetCore.Components.RenderTree.WebRenderer.AddRootComponent(Type , String )
   at Microsoft.AspNetCore.Components.WebView.Services.WebViewRenderer.AddRootComponent(Type componentType, String domElementSelector)
   at Microsoft.AspNetCore.Components.WebView.WebViewManager.AttachToPageAsync(String baseUrl, String startUrl)
   at Microsoft.AspNetCore.Components.WebView.IpcReceiver.OnMessageReceivedAsync(PageContext pageContext, String message)
   at Microsoft.AspNetCore.Components.WebView.WebViewManager.<>c__DisplayClass18_0.<<MessageReceived>b__0>d.MoveNext()
```

**Comment by WoodyJ007** [comment]
For anyone having the same problems.  The error is removed by turning off trimming and AOT in release.  The workaround for the Head output and make it correctly append at the end of the head is by using the <Template> hack mentioned here https://github.com/dotnet/aspnetcore/issues/51391

**Comment by Eilon** [comment]
I built a repro app here: https://github.com/Eilon/maui19822headcontent

But couldn't reproduce the exact error. I was seeing the issue described by https://github.com/dotnet/aspnetcore/issues/51391, but I don't have that patch on this machine, so that's not surprising.

For my repro app:

1. I used essentially the same XAML to add the root component: https://github.com/Eilon/maui19822headcontent/blob/main/maui19822headcontent/MainPage.xaml#L10
2. The component I'm using emits a reference to a CSS file: https://github.com/Eilon/maui19822headcontent/blob/main/maui19822headcontent/MyHeadOutlet.razor
3. And I updated some content to 'prove' whether the CSS is loaded by trying to [apply a style](https://github.com/Eilon/maui19822headcontent/blob/main/maui19822headcontent/Components/Pages/Home.razor#L7-L9) defined in the [CSS](https://github.com/Eilon/maui19822headcontent/blob/main/maui19822headcontent/wwwroot/css/dyn5.css)

And when I ran on Android in Release mode:
![image](https://github.com/dotnet/maui/assets/202643/53239105-88d3-4bdb-937d-cb5c80e496f1)

It showed what I expected with the purple CSS:
![image](https://github.com/dotnet/maui/assets/202643/8894f488-5dc0-4a65-b218-b60b961be06f)

I then also tried moving the Razor Component I used for the HeadOutlet to a Razor Class Library (RCL) in case that affects what gets altered by AOT, but the behavior didn't change (that is, everything worked fine).

The error mentioned earlier is almost certainly due to AOT/trimming (as @WoodyJ007 also mentioned) because it's saying a type member doesn't exist, when clearly it should. There are various settings to adjust how AOT works, but for most scenarios it should 'just work'.

If someone can share a repro of this issue we can investigate further.

**Comment by WoodyJ007** [comment]
I added how to reproduce the issue on the repo (under issues)

**Comment by RoiChen001** [comment]
Can repro this issue on the latest 17.10 Preview 2.
![error](https://github.com/dotnet/maui/assets/143168639/a25bab15-898d-4ac5-9995-d68261791a2d)

**Comment by Eilon** [comment]
@RoiChen001 are you able to debug the release app? In Visual Studio open the Exception Settings window, and make sure that **Common Language Runtime Exceptions** is checked (actual checkmark, not just a square), and then debug the app (you can still use Release mode and run with the debugger). That should show what the exception is.

<img width="312" alt="image" src="https://github.com/dotnet/maui/assets/202643/023addb5-9c07-4756-b8c1-a4382ce9f602">

**Comment by RoiChen001** [comment]
@Eilon Sorry for the delay, I almost missed your message. As shown in the picture, I didn't see the exception being thrown.
![19822](https://github.com/dotnet/maui/assets/143168639/e71f18fe-f5ce-484e-806b-be302486e752)

**Comment by mkArtakMSFT** [comment]
@WoodyJ007 can you please confirm if this is still an issue with the latest 8.0.4 release and let us know? Thanks!

**Comment by WoodyJ007** [comment]
No, the issue is still not fixed.  Just tried it now.
![Sequence](https://github.com/dotnet/maui/assets/4989476/09dd43e2-3e2d-4445-b9fd-497dd4bdb7e6)

I put how to reproduce it on this thread ages ago.

https://github.com/Eilon/maui19822headcontent/issues/1

**Comment by TimPurdum** [comment]
I'm working on a Blazor RCL NuGet library that would like to make use of `<HeadContent />`. I was surprised not only to see an open bug in the MAUI implementation, but that `HeadOutlet` is not even part of the MAUI templates? Yet it is a default part of all the other Blazor templates, which means anyone who is writing shared code will run into the scenario I am, not knowing if `HeadOutlet` is available. Would be good to have consistency.
