### ISSUE TITLE
Deployment fails to arm64-v8a emulator 

### ISSUE THREAD

**Issue by ganikapudisham** [dotnet/maui#20053]
### Description

I have this MAUI project and it works fine for x64, x86 devices but fails on arm64-v8a.
I published this app on google play store and google did not approve the app because 
it crashes on arm64-v8a devices.

The project builds but fails to deploy without any error messages on local emulator devices,
so I published the app on play store for internal testing where it fails for arm64-v8a devices.

Just to confirm the problem is not with my code. 
I created a new default Maui app provided by VS2022.
When I run it on arm64-v8a device the deployment failed.

### Steps to Reproduce

Select Maui App template and run it on arm64-v8a device.

### Link to public reproduction project repository

https://github.com/ganikapudisham/maui-matri

### Version with bug

8.0.101

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

### Did you find any workaround?

No, because I have tried to run the Maui App project template provided by VS2022 on arm64-v8a device and it failed to deploy.

### Basic Information
Version with issue: .NET MAUI 8.0.3
IDE: Visual Studio 2022 17.8.5
Platform Target Frameworks:
Android: Min 21, target 34
Affected Devices: Google Pixel 5 (virtual) 1080x1920 Android 11 (SDK 30) arm64-v8a

### Failed on below Devices

google Pixel 7
1080x2400
Android 13 (SDK 33)
8,192 MB
arm64-v8a
en_US

google Pixel 5 64-bit only (Beta)
1080x2340
Android 14 (SDK 34)
-
arm64-v8a
en_US

google Pixel 6
1080x2400
Android 12 (SDK 31)
8,192 MB
arm64-v8a
en_GB

Google Pixel 2 (Arm) (virtual)
1080x1920
Android 13 (SDK 33)
-
arm64-v8a
en_GB

Google Pixel 2 (virtual)
1080x1920
Android 12 (SDK 31)
-
x86_64
en_GB
Google Pixel 2 (virtual)
1080x1920
Android 13 (SDK 33)
-
x86_64
en_IN
Generic Small Desktop (x86) (virtual)
1366x768
Android 12L (SDK 32)
-
x86_64
en_IN

Google Pixel 2 (virtual)
1080x1920
Android 9 (SDK 28)
-
x86
en_US

google Pixel 5
1080x2340
Android 11 (SDK 30)
8,192 MB
arm64-v8a
en_IN

motorola Motorola G20
720x1600
Android 11 (SDK 30)
4,096 MB
arm64-v8a
en_IN

### Relevant log output

```shell
01-20 19:21:43.203: D/DeviceStatisticsService(4460): chargerType=1 batteryLevel=80 totalBatteryCapacity=4192700
01-20 19:21:43.203: D/DeviceInfoHidlClient(4460): getPowerInfoSupportStatus()=-1
01-20 19:21:43.327: D/rlsservice(914): MonitorDisplayStatus client num 1, display status 1, sensor status 0
01-20 19:21:43.459: D/VSC(908): @ 4580.496: [WO] isFlat() nearest_rotation: 1, flat_angle: 40
01-20 19:21:43.459: D/VSC(908): @ 4580.496: [WO] orientation angle 90, orientation 1
01-20 19:21:43.496: I/.android.chrom(30472): Waiting for a blocking GC ProfileSaver
01-20 19:21:43.514: I/.android.chrom(30472): WaitForGcToComplete blocked ProfileSaver on ClassLinker for 18.838ms
01-20 19:21:43.671: D/BufferPoolAccessor2.0(927): evictor expired: 1, evicted: 0
01-20 19:21:43.703: D/ConnectivityService(1623): NetReassign [no changes]
01-20 19:21:43.788: D/DeviceStateHelper(6934): Audo mode: 0
01-20 19:21:43.791: D/DeviceStateHelper(6934): Audo mode: 0
01-20 19:21:44.259: I/.apps.wellbein(30629): Waiting for a blocking GC ProfileSaver
01-20 19:21:44.267: I/.apps.wellbein(30629): WaitForGcToComplete blocked ProfileSaver on ClassLinker for 8.288ms
01-20 19:21:44.303: I/.apps.wellbein(30629): WaitForGcToComplete blocked RunEmptyCheckpoint on ProfileSaver for 29.720ms
01-20 19:21:44.967: I/Finsky(27090): [1863] msp.run(357): Stats for Executor: BlockingExecutor osd@6ad9395[Running, pool size = 6, active threads = 0, queued tasks = 0, completed tasks = 84]
01-20 19:21:44.968: I/Finsky(27090): [1863] msp.run(357): Stats for Executor: LightweightExecutor osd@51d6caa[Running, pool size = 4, active threads = 0, queued tasks = 0, completed tasks = 725]
01-20 19:21:45.149: I/Finsky(27090): [1863] msp.run(357): Stats for Executor: bgExecutor osd@a1f409b[Running, pool size = 4, active threads = 0, queued tasks = 0, completed tasks = 1412]
01-20 19:21:45.458: D/VSC(908): @ 4582.495: [WO] isFlat() nearest_rotation: 1, flat_angle: 40
01-20 19:21:45.458: D/VSC(908): @ 4582.495: [WO] orientation angle 90, orientation 1
01-20 19:21:47.458: D/VSC(908): @ 4584.495: [WO] isFlat() nearest_rotation: 1, flat_angle: 40
01-20 19:21:47.458: D/VSC(908): @ 4584.495: [WO] orientation angle 90, orientation 1
01-20 19:21:47.856: D/AndroidRuntime(30733): >>>>>> START com.android.internal.os.RuntimeInit uid 2000 <<<<<<
01-20 19:21:47.858: E/libc(30733): Access denied finding property "persist.device_config.runtime_native_boot.profilebootclasspath"
01-20 19:21:47.859: E/libc(30733): Access denied finding property "persist.device_config.runtime_native_boot.enable_apex_image"
01-20 19:21:47.859: I/AndroidRuntime(30733): Using default boot image
01-20 19:21:47.859: E/libc(30733): Access denied finding property "persist.device_config.runtime_native_boot.disable_lock_profiling"
01-20 19:21:47.859: I/AndroidRuntime(30733): Leaving lock profiling enabled
01-20 19:21:47.859: E/libc(30733): Access denied finding property "persist.device_config.runtime_native_boot.enable_generational_cc"
01-20 19:21:47.857: W/app_process(30733): type=1400 audit(0.0:550): avc: denied { read } for name="u:object_r:device_config_runtime_native_boot_prop:s0" dev="tmpfs" ino=11442 scontext=u:r:shell:s0 tcontext=u:object_r:device_config_runtime_native_boot_prop:s0 tclass=file permissive=0 b/175106535
01-20 19:21:47.919: D/app_process(30733): Time zone APEX ICU file found: /apex/com.android.tzdata/etc/icu/icu_tzdata.dat
01-20 19:21:47.919: D/app_process(30733): I18n APEX ICU file found: /apex/com.android.i18n/etc/icu/icudt66l.dat
01-20 19:21:47.927: I/app_process(30733): The ClassLoaderContext is a special shared library.
01-20 19:21:47.939: W/app_process(30733): JNI RegisterNativeMethods: attempt to register 0 native methods for android.media.AudioAttributes
01-20 19:21:47.942: D/AndroidRuntime(30733): Calling main entry com.android.commands.am.Am
01-20 19:21:46.726: D/ConnectivityService(1623): NetReassign [no changes]
01-20 19:21:47.946: I/ActivityManager(1623): Force stopping com.google.android.apps.mtaas.loginutil appid=10261 user=0: start instr
01-20 19:21:47.947: D/CompatibilityChangeReporter(1623): Compat change id reported: 135634846; UID 10261; state: DISABLED
01-20 19:21:47.948: D/CompatibilityChangeReporter(1623): Compat change id reported: 135754954; UID 10261; state: DISABLED
01-20 19:21:47.948: D/CompatibilityChangeReporter(1623): Compat change id reported: 143937733; UID 10261; state: DISABLED
01-20 19:21:47.954: D/Zygote(877): Forked child process 30747
01-20 19:21:47.956: I/libc(30747): SetHeapTaggingLevel: tag level set to 0
01-20 19:21:47.963: I/ActivityManager(1623): Start proc 30747:com.google.android.apps.mtaas.loginutil/u0a261 for added application com.google.android.apps.mtaas.loginutil
01-20 19:21:47.966: E/mtaas.loginuti(30747): Not starting debugger since process cannot load the jdwp agent.
01-20 19:21:47.992: D/ApplicationLoaders(30747): Returning zygote-cached class loader: /system/framework/android.test.base.jar
01-20 19:21:47.996: I/mtaas.loginuti(30747): The ClassLoaderContext is a special shared library.
01-20 19:21:48.011: D/NetworkSecurityConfig(30747): No Network Security Config specified, using platform default
01-20 19:21:48.011: D/NetworkSecurityConfig(30747): No Network Security Config specified, using platform default
01-20 19:21:48.011: I/LoginUtil(30747): onCreate
01-20 19:21:48.012: I/LoginUtil(30747): onStart
01-20 19:21:48.013: D/LoginUtil(30747): Removing Account {name=LYHPOEWDMW35CZTMO4CQXFXLBQ-00@cloudtestlabaccounts.com, type=com.google}
01-20 19:21:48.015: D/CompatibilityChangeReporter(1623): Compat change id reported: 135634846; UID 10263; state: DISABLED
01-20 19:21:48.015: D/CompatibilityChangeReporter(1623): Compat change id reported: 135754954; UID 10263; state: DISABLED
01-20 19:21:48.015: D/CompatibilityChangeReporter(1623): Compat change id reported: 143937733; UID 10263; state: DISABLED
01-20 19:21:48.024: D/Zygote(877): Forked child process 30767
01-20 19:21:48.026: I/ActivityManager(1623): Start proc 30767:com.google.android.apps.auth.test.support/u0a263 for service {com.google.android.apps.auth.test.support/com.google.android.apps.auth.test.support.services.AccountService}
01-20 19:21:48.027: I/libc(30767): SetHeapTaggingLevel: tag level set to 0
01-20 19:21:48.035: E/th.test.suppor(30767): Not starting debugger since process cannot load the jdwp agent.
01-20 19:21:48.056: D/ApplicationLoaders(30767): Returning zygote-cached class loader: /system/framework/android.test.base.jar
01-20 19:21:48.058: I/th.test.suppor(30767): The ClassLoaderContext is a special shared library.
01-20 19:21:48.071: D/NetworkSecurityConfig(30767): Using Network Security Config from resource network_security_config debugBuild: false
01-20 19:21:48.081: D/CompatibilityChangeReporter(1623): Compat change id reported: 135634846; UID 10270; state: DISABLED
01-20 19:21:48.081: D/CompatibilityChangeReporter(1623): Compat change id reported: 135754954; UID 10270; state: ENABLED
01-20 19:21:48.082: D/CompatibilityChangeReporter(1623): Compat change id reported: 143937733; UID 10270; state: ENABLED
01-20 19:21:48.072: D/NetworkSecurityConfig(30767): Using Network Security Config from resource network_security_config debugBuild: false
01-20 19:21:48.093: D/Zygote(877): Forked child process 30787
01-20 19:21:48.096: I/ActivityManager(1623): Start proc 30787:androidx.test.services/u0a270 for content provider {androidx.test.services/androidx.test.services.storage.provider.TestArgsContentProvider}
01-20 19:21:48.099: I/x.test.service(30787): Late-enabling -Xcheck:jni
01-20 19:21:48.112: I/x.test.service(30787): Unquickening 12 vdex files!
01-20 19:21:48.120: I/adbd(4869): jdwp connection from 30787
01-20 19:21:48.188: D/NetworkSecurityConfig(30787): No Network Security Config specified, using platform default
01-20 19:21:48.188: D/NetworkSecurityConfig(30787): No Network Security Config specified, using platform default
01-20 19:21:48.244: W/TestConfiguration(30767): Unable to parse host and port.
01-20 19:21:48.244: W/TestConfiguration(30767): java.lang.NullPointerException
01-20 19:21:48.244: W/TestConfiguration(30767): 	at u.n(PG:1)
01-20 19:21:48.244: W/TestConfiguration(30767): 	at fb.c(PG:1)
01-20 19:21:48.244: W/TestConfiguration(30767): 	at ba.a(PG:1)
01-20 19:21:48.244: W/TestConfiguration(30767): 	at ag.a(PG:25)
01-20 19:21:48.244: W/TestConfiguration(30767): 	at cz.<init>(PG:2)
01-20 19:21:48.244: W/TestConfiguration(30767): 	at com.google.android.apps.auth.test.support.services.AccountService.onCreate(PG:1)
01-20 19:21:48.244: W/TestConfiguration(30767): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4186)
01-20 19:21:48.244: W/TestConfiguration(30767): 	at android.app.ActivityThread.access$1500(ActivityThread.java:237)
01-20 19:21:48.244: W/TestConfiguration(30767): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1932)
01-20 19:21:48.244: W/TestConfiguration(30767): 	at android.os.Handler.dispatchMessage(Handler.java:106)
01-20 19:21:48.244: W/TestConfiguration(30767): 	at android.os.Looper.loop(Looper.java:223)
01-20 19:21:48.244: W/TestConfiguration(30767): 	at android.app.ActivityThread.main(ActivityThread.java:7664)
01-20 19:21:48.244: W/TestConfiguration(30767): 	at java.lang.reflect.Method.invoke(Native Method)
01-20 19:21:48.244: W/TestConfiguration(30767): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
01-20 19:21:48.244: W/TestConfiguration(30767): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
01-20 19:21:48.246: I/TestConfiguration(30767): Parsing fst client id: null
01-20 19:21:48.246: W/TestConfiguration(30767): Unable to parse host and port.
01-20 19:21:48.246: W/TestConfiguration(30767): java.lang.NullPointerException
01-20 19:21:48.246: W/TestConfiguration(30767): 	at u.n(PG:1)
01-20 19:21:48.246: W/TestConfiguration(30767): 	at fb.c(PG:1)
01-20 19:21:48.246: W/TestConfiguration(30767): 	at ba.a(PG:1)
01-20 19:21:48.246: W/TestConfiguration(30767): 	at ag.a(PG:25)
01-20 19:21:48.246: W/TestConfiguration(30767): 	at cz.<init>(PG:5)
01-20 19:21:48.246: W/TestConfiguration(30767): 	at com.google.android.apps.auth.test.support.services.AccountService.onCreate(PG:1)
01-20 19:21:48.246: W/TestConfiguration(30767): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4186)
01-20 19:21:48.246: W/TestConfiguration(30767): 	at android.app.ActivityThread.access$1500(ActivityThread.java:237)
01-20 19:21:48.246: W/TestConfiguration(30767): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1932)
01-20 19:21:48.246: W/TestConfiguration(30767): 	at android.os.Handler.dispatchMessage(Handler.java:106)
01-20 19:21:48.246: W/TestConfiguration(30767): 	at android.os.Looper.loop(Looper.java:223)
01-20 19:21:48.246: W/TestConfiguration(30767): 	at android.app.ActivityThread.main(ActivityThread.java:7664)
01-20 19:21:48.246: W/TestConfiguration(30767): 	at java.lang.reflect.Method.invoke(Native Method)
01-20 19:21:48.246: W/TestConfiguration(30767): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
01-20 19:21:48.246: W/TestConfiguration(30767): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
01-20 19:21:48.246: I/TestConfiguration(30767): Parsing fst client id: null
01-20 19:21:48.283: I/RemoveAccountOperation(30767): Removing account: Account {name=LYHPOEWDMW35CZTMO4CQXFXLBQ-00@cloudtestlabaccounts.com, type=com.google}.
01-20 19:21:48.326: I/AccountManagerService(1623): the accounts changed, sending broadcast of android.accounts.LOGIN_ACCOUNTS_CHANGED
01-20 19:21:48.365: I/Icing(21416): updateResources: need to parse azjj{com.google.android.gm}
01-20 19:21:48.365: I/AccountHelper(30767): LYHPOEWDMW35CZTMO4CQXFXLBQ-00 is not present on the device. 
01-20 19:21:48.366: I/AccountService(30767): Execution time for remove account is 114 ms.
01-20 19:21:48.375: I/Icing(21416): updateResources: need to parse azjj{com.google.android.gms}
01-20 19:21:48.381: I/AbstractFileContentProvider(30787): file '/storage/emulated/0/googletest/test_exportproperties/properties.dat': found
01-20 19:21:48.382: D/CompatibilityChangeReporter(1623): Compat change id reported: 135634846; UID 10224; state: DISABLED
01-20 19:21:48.382: D/CompatibilityChangeReporter(1623): Compat change id reported: 135754954; UID 10224; state: ENABLED
01-20 19:21:48.383: D/CompatibilityChangeReporter(1623): Compat change id reported: 143937733; UID 10224; state: ENABLED
01-20 19:21:48.383: D/m(15731): setAvailableAccounts() 1 -> 0.
01-20 19:21:48.384: D/m(15731): setSelectedAndRecents(). selected is null: true, first recent is null: true, second recent is null: true.
01-20 19:21:48.391: I/ContactsProvider(23797): Accounts changed
01-20 19:21:48.393: D/Zygote(877): Forked child process 30814
01-20 19:21:48.394: I/ActivityManager(1623): Start proc 30814:com.google.android.apps.messaging/u0a224 for broadcast {com.google.android.apps.messaging/com.google.apps.tiktok.account.data.device.DeviceAccountsChangedReceiver_Receiver}
01-20 19:21:48.395: I/AbstractFileContentProvider(30787): file '/storage/emulated/0/googletest/test_exportproperties/properties.dat': found
01-20 19:21:48.399: I/ContactsProvider(23797): Accounts changed
01-20 19:21:48.401: E/.apps.messagin(30814): Not starting debugger since process cannot load the jdwp agent.
01-20 19:21:48.406: D/LoginUtil(30747): Instrumentation completed successfully
01-20 19:21:48.408: I/ActivityManager(1623): Force stopping com.google.android.apps.mtaas.loginutil appid=10261 user=0: finished inst
01-20 19:21:48.409: I/ActivityManager(1623): Killing 30747:com.google.android.apps.mtaas.loginutil/u0a261 (adj 0): stop com.google.android.apps.mtaas.loginutil due to finished inst
01-20 19:21:48.410: D/AndroidRuntime(30733): Shutting down VM
01-20 19:21:48.414: I/ActivityManager(1623): Killing 23826:com.google.android.gm/u0a196 (adj 975): empty #33
01-20 19:21:48.415: I/ActivityManager(1623): Killing 25573:com.google.android.dialer/u0a183 (adj 975): empty #34
01-20 19:21:48.420: I/.apps.messagin(30814): The ClassLoaderContext is a special shared library.
01-20 19:21:48.427: I/.apps.messagin(30814): The ClassLoaderContext is a special shared library.
01-20 19:21:48.428: D/nativeloader(30814): classloader namespace configured for unbundled product apk. library_path=/product/app/PrebuiltBugle/lib/arm64:/product/app/PrebuiltBugle/PrebuiltBugle.apk!/lib/arm64-v8a:/product/lib64:/system/product/lib64
01-20 19:21:48.430: I/Zygote(877): Process 30747 exited due to signal 9 (Killed)
01-20 19:21:48.440: D/NetworkSecurityConfig(30814): No Network Security Config specified, using platform default
01-20 19:21:48.441: D/NetworkSecurityConfig(30814): No Network Security Config specified, using platform default
01-20 19:21:48.449: I/MultiDex(30814): VM with version 2.1.0 has multidex support
01-20 19:21:48.449: I/MultiDex(30814): install
01-20 19:21:48.449: I/MultiDex(30814): VM has multidex support, MultiDex support library is disabled.
01-20 19:21:48.455: I/libprocessgroup(1623): Successfully killed process cgroup uid 10261 pid 30747 in 43ms
01-20 19:21:48.471: I/ContactsProvider(23797): Accounts changed
01-20 19:21:48.483: I/Zygote(877): Process 25573 exited due to signal 9 (Killed)
01-20 19:21:48.502: E/ActivityManager(1623): ProcessRecord{8eae383 23826:com.google.android.gm/u0a196} was killed by AM but isn't really dead
01-20 19:21:48.503: E/ActivityManager(1623): ProcessRecord{8eae383 23826:com.google.android.gm/u0a196} is attached to a previous process
01-20 19:21:48.503: E/ActivityManager(1623): Already have existing proc ProcessRecord{8eae383 23826:com.google.android.gm/u0a196} when adding ProcessRecord{7c4c41e 0:com.google.android.gm/u0a196}
01-20 19:21:48.503: I/DropBoxManagerService(1623): add tag=system_server_wtf isTagEnabled=true flags=0x2
01-20 19:21:48.504: D/CompatibilityChangeReporter(1623): Compat change id reported: 135634846; UID 10196; state: DISABLED
01-20 19:21:48.504: D/CompatibilityChangeReporter(1623): Compat change id reported: 135754954; UID 10196; state: ENABLED
01-20 19:21:48.504: E/ActivityManager(1623): ProcessRecord{8eae383 23826:com.google.android.gm/u0a196} refused to die, but we need to launch ProcessRecord{7c4c41e 0:com.google.android.gm/u0a196}
01-20 19:21:48.505: D/CompatibilityChangeReporter(1623): Compat change id reported: 143937733; UID 10196; state: ENABLED
01-20 19:21:48.507: I/Zygote(877): Process 23826 exited due to signal 9 (Killed)
01-20 19:21:48.508: I/DropBoxManagerService(1623): add tag=system_server_wtf isTagEnabled=true flags=0x2
01-20 19:21:48.513: D/Zygote(877): Forked child process 30836
01-20 19:21:48.517: I/libprocessgroup(1623): Successfully killed process cgroup uid 10196 pid 23826 in 61ms
01-20 19:21:48.517: I/libprocessgroup(1623): Successfully killed process cgroup uid 10183 pid 25573 in 0ms
01-20 19:21:48.517: I/libprocessgroup(1623): Successfully killed process cgroup uid 10196 pid 23826 in 0ms
01-20 19:21:48.510: I/chatty(1623): uid=1000(system) ActivityManager identical 1 line
01-20 19:21:48.512: I/DropBoxManagerService(1623): add tag=system_server_wtf isTagEnabled=true flags=0x2
01-20 19:21:48.519: I/ActivityManager(1623): Start proc 30836:com.google.android.gm/u0a196 for content provider {com.google.android.gm/com.android.exchange.provider.ExchangeDirectoryProvider}
01-20 19:21:48.521: E/ogle.android.g(30836): Not starting debugger since process cannot load the jdwp agent.
01-20 19:21:48.549: I/ogle.android.g(30836): The ClassLoaderContext is a special shared library.
01-20 19:21:48.544: I/WM-GreedyScheduler(15731): Ignoring schedule request in non-main process
01-20 19:21:48.558: I/ogle.android.g(30836): The ClassLoaderContext is a special shared library.
01-20 19:21:48.561: D/nativeloader(30836): classloader namespace configured for unbundled product apk. library_path=/product/app/PrebuiltGmail/lib/arm64:/product/lib64:/system/product/lib64
01-20 19:21:48.579: I/WM-GreedyScheduler(15731): Ignoring schedule request in a secondary process
01-20 19:21:48.591: D/NetworkSecurityConfig(30836): Using Network Security Config from resource network_security_config debugBuild: false
01-20 19:21:48.592: I/aphq(30814): SslGuard completed installation.
01-20 19:21:48.592: D/NetworkSecurityConfig(30836): Using Network Security Config from resource network_security_config debugBuild: false
01-20 19:21:48.594: I/WM-GreedyScheduler(15731): Ignoring schedule request in non-main process
01-20 19:21:48.605: W/BuglePhenotype(30814): Phenotype Flags not initialized
01-20 19:21:48.605: I/Bugle(30814): BugleApplicationBase: Bugle version: 7.1.084 (hickory_rc10_alldpi.arm64-v8a.phone)
01-20 19:21:48.611: I/WM-GreedyScheduler(15731): Ignoring schedule request in a secondary process
01-20 19:21:48.614: W/BuglePhenotype(30814): java.lang.IllegalStateException: Must call PhenotypeFlag.init() first
01-20 19:21:48.614: W/BuglePhenotype(30814): 	at aszc.l(PG:1)
01-20 19:21:48.614: W/BuglePhenotype(30814): 	at ansc.f(PG:4)
01-20 19:21:48.614: W/BuglePhenotype(30814): 	at pph.h(PG:1)
01-20 19:21:48.614: W/BuglePhenotype(30814): 	at ppn.g(PG:2)
01-20 19:21:48.614: W/BuglePhenotype(30814): 	at pph.i(PG:3)
01-20 19:21:48.614: W/BuglePhenotype(30814): 	at skp.run(Unknown Source:2)
01-20 19:21:48.614: W/BuglePhenotype(30814): 	at asje.run(PG:2)
01-20 19:21:48.614: W/BuglePhenotype(30814): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
01-20 19:21:48.614: W/BuglePhenotype(30814): 	at avte.c(PG:1)
01-20 19:21:48.614: W/BuglePhenotype(30814): 	at avsf.run(PG:4)
01-20 19:21:48.614: W/BuglePhenotype(30814): 	at avtf.run(PG:1)
01-20 19:21:48.614: W/BuglePhenotype(30814): 	at avsu.run(PG:1)
01-20 19:21:48.614: W/BuglePhenotype(30814): 	at avsv.run(PG:4)
01-20 19:21:48.614: W/BuglePhenotype(30814): 	at aria.run(PG:1)
01-20 19:21:48.614: W/BuglePhenotype(30814): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
01-20 19:21:48.614: W/BuglePhenotype(30814): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
01-20 19:21:48.614: W/BuglePhenotype(30814): 	at argf.run(Unknown Source:5)
01-20 19:21:48.614: W/BuglePhenotype(30814): 	at java.lang.Thread.run(Thread.java:923)
01-20 19:21:48.701: I/PeopleGalProvider(21416): Gal directories started.
01-20 19:21:48.702: I/PeopleGalProvider(21416): Method 1 completed.
01-20 19:21:48.702: I/PeopleGalProvider(21416): Method 1 finished successfully.
01-20 19:21:48.704: I/PeopleGalProvider(21416): Gal directories started.
01-20 19:21:48.704: I/PeopleGalProvider(21416): Method 1 completed.
01-20 19:21:48.704: I/PeopleGalProvider(21416): Method 1 finished successfully.
01-20 19:21:48.707: I/ContactDirectoryManager(23797): deleted 0 stale rows which don't have any relevant directory
01-20 19:21:48.707: I/ContactDirectoryManager(23797): Discovered 0 contact directories in 212ms
01-20 19:21:48.710: I/ContactDirectoryManager(23797): deleted 0 stale rows which don't have any relevant directory
01-20 19:21:48.710: D/BluetoothPbapService(3987):  onChange on contact uri 
01-20 19:21:48.710: I/ContactDirectoryManager(23797): Discovered 0 contact directories in 212ms
01-20 19:21:48.712: I/ActivityManager(1623): Killing 23556:com.google.android.apps.safetyhub/u0a181 (adj 925): empty #33
01-20 19:21:48.716: D/BluetoothPbapService(3987):  onChange on contact uri 
01-20 19:21:48.723: D/BluetoothPbapUtils(3987): primaryVersionCounter = 0, secondaryVersionCounter=0
01-20 19:21:48.728: W/ogle.android.g(30836): Accessing hidden field Ljava/util/Collections$SynchronizedCollection;->mutex:Ljava/lang/Object; (greylist-max-o, reflection, denied)
01-20 19:21:48.728: W/ogle.android.g(30836): Accessing hidden method Ljava/util/Collections$SynchronizedSet;-><init>(Ljava/util/Set;Ljava/lang/Object;)V (greylist-max-o, reflection, denied)
01-20 19:21:48.728: W/ogle.android.g(30836): Accessing hidden method Ljava/util/Collections$SynchronizedCollection;-><init>(Ljava/util/Collection;Ljava/lang/Object;)V (greylist-max-o, reflection, denied)
01-20 19:21:48.738: W/.apps.messagin(30814): Accessing hidden field Ljava/util/Collections$SynchronizedCollection;->mutex:Ljava/lang/Object; (greylist-max-o, reflection, denied)
01-20 19:21:48.738: W/.apps.messagin(30814): Accessing hidden method Ljava/util/Collections$SynchronizedSet;-><init>(Ljava/util/Set;Ljava/lang/Object;)V (greylist-max-o, reflection, denied)
01-20 19:21:48.738: W/.apps.messagin(30814): Accessing hidden method Ljava/util/Collections$SynchronizedCollection;-><init>(Ljava/util/Collection;Ljava/lang/Object;)V (greylist-max-o, reflection, denied)
01-20 19:21:48.757: I/Bugle(30814): Initializing EmojiCompat
01-20 19:21:48.766: I/Zygote(877): Process 23556 exited due to signal 9 (Killed)
01-20 19:21:48.772: W/GAV2(30836): Thread[main,5,main]: Need to call initialize() and be in fallback mode to start dispatch.
01-20 19:21:48.776: I/CarrierServices(30814): [1986] afaf.a: Initializing Carrier Services Library.
01-20 19:21:48.778: I/NetworkScheduler.Stats(20754): (REDACTED) Task %s/%s started execution. cause:%s exec_start_elapsed_seconds: %s
01-20 19:21:48.780: I/FontLog(20754): (REDACTED) Received query %s, URI %s
01-20 19:21:48.780: I/FontLog(20754): (REDACTED) Query [%s] resolved to %s
01-20 19:21:48.781: I/NetworkScheduler.Stats(20754): (REDACTED) Task %s/%s finished executing. cause:%s result: %s elapsed_millis: %s uptime_millis: %s exec_start_elapsed_seconds: %s
01-20 19:21:48.782: I/FontLog(20754): (REDACTED) Fetch %s end status %s
01-20 19:21:48.785: I/libprocessgroup(1623): Successfully killed process cgroup uid 10181 pid 23556 in 72ms
01-20 19:21:48.788: I/CarrierServices(30814): [1986] afim.l: Reinitialize CSLib Flags: com.google.android.ims.library
01-20 19:21:48.790: W/Gmail(30836): AccountUtils:For b/73513912, load account content://com.google.android.gm.sapi/account.-2137146394 from MailAppProvider. Is account valid result: 1.
01-20 19:21:48.792: W/Gmail(30836): AccountUtils:For b/73513912, load account content://com.google.android.gm.email.provider/account.-437561172?suppress_combined%3Dtrue from MailAppProvider. Is account valid result: 1.
01-20 19:21:48.803: D/CompatibilityChangeReporter(30836): Compat change id reported: 150939131; UID 10196; state: ENABLED
01-20 19:21:48.803: W/Auth(20754): [GaiaServicesFlagManager] Services not available! [CONTEXT service_id=343 ]
01-20 19:21:48.808: I/FontLog(20754): (REDACTED) Pulling font file for id = %d, cache size = %d
01-20 19:21:48.812: I/PhenotypeResourceReader(20754): unable to find any Phenotype resource metadata for com.google.android.gm
01-20 19:21:48.822: D/DeviceStateHelper(6934): Audo mode: 0
01-20 19:21:48.823: D/DeviceStateHelper(6934): Audo mode: 0
01-20 19:21:48.827: W/Auth(20754): [GaiaServicesFlagManager] Services not available! [CONTEXT service_id=343 ]
01-20 19:21:48.827: I/FontLog(20754): (REDACTED) Pulling font file for id = %d, cache size = %d
01-20 19:21:48.851: V/ClearcutMetricXmitter(30814): Transmission is done.
01-20 19:21:48.859: W/ActivityManager(1623): Unable to start service Intent { cmp=com.google.android.gm/com.android.email.service.AttachmentService } U=0: not found
01-20 19:21:48.864: I/NetworkScheduler.Stats(20754): (REDACTED) Task %s/%s started execution. cause:%s exec_start_elapsed_seconds: %s
01-20 19:21:48.865: W/CryptauthV2(21416): [ReEnrollmentChimeraService] Account doesn't exist on device
01-20 19:21:48.869: I/NetworkScheduler.Stats(20754): (REDACTED) Task %s/%s finished executing. cause:%s result: %s elapsed_millis: %s uptime_millis: %s exec_start_elapsed_seconds: %s


```

**Comment by ganikapudisham** [comment]
The log output is provided by Google play console after I published the app to playstore.

**Comment by PureWeen** [comment]
This issue was moved to xamarin/xamarin-android#8661
