### ISSUE TITLE
If Resources/Raw exceeds specific size, iOS deployment doesn't work 

### ISSUE THREAD

**Issue by AncientLust** [dotnet/maui#20201]
### Description

If Resources/Raw folder exceeds some size, iOS deployment fails with following error:

> 1>Deploy failed. The app 'Resources size issue repro.app' could not be deployed to the device 'Aliak’s iPhone'. Please check the logs for more details. You can open Xamarin logs from the Help menu.

I would really like to provide some specific values of size, but it seems to differ from project to project, have no idea why. In the original app it happens when Resources/Raw folder exceeds ~100MB. In the clean repro project, when size reaches about ~200 MB.

### Steps to Reproduce

Repro project is a clean new MAUI project. I only put three large size folders into Resources/Raw directory. Each approx 100 MB. And set TargetFrameworks to net8.0-ios only.

Fail pass: 
1. Open repro project.
2. Build it and deploy to physical iOS device. 
3. You should see deployment error as in "Relevant log output" below. 

Successful pass:
1. Open Resources\Raw folder and drop SomeBigSizeFile2 and SomeBigSizeFile3 folders.
2. Rebuild repro project and deploy to physical iOS device.
3. Deployment will be finished without any errors. 

### Link to public reproduction project repository

https://github.com/AncientLust/Resources-size-issue-repro.git

### Version with bug

8.0.6

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 17.2.1

### Did you find any workaround?

No. So far the only way is to keep resources folder below 100 MB.

### Relevant log output

```shell
1>------ Deploy started: Project: Resources size issue repro, Configuration: Debug Any CPU ------
1>Starting deploy 'Resourcessizeissuerepro' into the device 'Aliak’s iPhone'...
1>Deploying 'Resources size issue repro.app' into the device 'Aliak’s iPhone'...
1>Deploy failed. The app 'Resources size issue repro.app' could not be deployed to the device 'Aliak’s iPhone'. Please check the logs for more details. You can open Xamarin logs from the Help menu.
1>Deploy failed
========== Deploy: 0 succeeded, 1 failed, 0 skipped ==========
========== Deploy completed at 9:50 PM and took 19.621 seconds ==========

And Xamarin log:
Xamarin.iOS.Windows.HotRestartClient Error: 0 : Deploy Error: Could not write content to file 'PublicStaging/com.companyname.resources_size_issue_repro': 01/27/2024 20:36:36Z
    DateTime=2024-01-27T20:36:36.0610731Z: 01/27/2024 20:36:36Z
Xamarin.Messaging.IDB.Local.DeployAppMessageHandler Error: 0 : An error occurred while trying to deploy the app 'Resources size issue repro.app'. Details: Could not write content to file 'PublicStaging/com.companyname.resources_size_issue_repro'
Xamarin.iOS.Windows.WindowsiOSException: Could not write content to file 'PublicStaging/com.companyname.resources_size_issue_repro'
   at Xamarin.iOS.Windows.FileSystem.FileSession.ExecuteAfcAction(Func`1 action, String message, String errorMessage) in D:\a\_work\1\s\src\Tools\Xamarin.iOS.Windows.Client\FileSystem\FileSession.cs:line 261
   at Xamarin.iOS.Windows.FileSystem.FileSession.CreateFile(AfcClientHandle afcClient, String deviceFolder, String fileName, Byte[] buffer) in D:\a\_work\1\s\src\Tools\Xamarin.iOS.Windows.Client\FileSystem\FileSession.cs:line 246
   at Xamarin.iOS.Windows.FileSystem.FileSession.UploadFile(AfcClientHandle afcClient, String deviceFolder, String file, String targetFileName) in D:\a\_work\1\s\src\Tools\Xamarin.iOS.Windows.Client\FileSystem\FileSession.cs:line 213
   at Xamarin.iOS.Windows.FileSystem.FileSession.UploadFileToPublicStaging(String filePath, String targetFileName) in D:\a\_work\1\s\src\Tools\Xamarin.iOS.Windows.Client\FileSystem\FileSession.cs:line 40
   at Xamarin.iOS.Windows.AppleDeviceExtensions.ExecuteWithSession(AppleDevice nativeDevice, Action action) in D:\a\_work\1\s\src\Tools\Xamarin.iOS.Windows.Client\Extensions\AppleDeviceExtensions.cs:line 14
   at Xamarin.iOS.Windows.Installer.ApplicationSession.Deploy(String appRootFolder, String appBundleId, String appName) in D:\a\_work\1\s\src\Tools\Xamarin.iOS.Windows.Client\Installer\ApplicationSession.cs:line 94
   at Xamarin.iOS.Windows.HotRestartClient.Deploy(AppleDevice nativeDevice, String appBundleId, String appBundleName, Boolean& incremental) in D:\a\_work\1\s\src\Tools\Xamarin.iOS.Windows.Client\HotRestartClient.cs:line 250
   at Xamarin.Messaging.IDB.Local.DeployAppMessageHandler.<ExecuteAsync>d__5.MoveNext() in D:\a\_work\1\s\src\Messaging\Xamarin.Messaging.IDB.Local\Handlers\DeployAppMessageHandler.cs:line 43: 01/27/2024 20:36:36Z
    DateTime=2024-01-27T20:36:36.0640528Z: 01/27/2024 20:36:36Z
```

**Comment by drasticactions** [comment]
This works on a real Mac, and you're using Hot Restart on Windows, so my guess would be that this is an issue with that tooling, or should be looked at there first.

**Comment by AncientLust** [comment]
[Link to the VS Feedback issue](https://developercommunity.visualstudio.com/t/Deployment-to-iOS-doesnt-work-if-Resouc/10572744)
