### ISSUE TITLE
ListView + DataTemplateSelector + HasUnevenRows issue on iOS

### ISSUE THREAD

**Issue by jpiechowiak** [dotnet/maui#20261]
### Description

When you use `DataTemplateSelector` with `HasUnevenRows` you may occur error `Specified cast is invalid` on iOS.

I've found easy scenario to reproduce (see attached repository). 
You have to have at least two Data templates and at least one of them should have `Label` directly under `ViewCell`. In such case when you alter `ItemsSource` from second `DataTemplate` to this one, error will crash your application. 

### Steps to Reproduce

1. Run project on iOS from attached reproduction repository
2. Tap button couple times until you change from data template with image to data template with only label

### Link to public reproduction project repository

https://github.com/jpiechowiak/maui-dts-unevenrows-issue

### Version with bug

8.0.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

-

### Did you find any workaround?

In ViewCell which contains only label, wrap `Label` with container - for instance in `StackLayout`

**Comment by XamlTest** [comment]
Verified this on VS 17.10.0 Preview 1.0(8.0.6). Repro on iOS 17.2 and MacCatalyst, not repro on Windows 11 and Android 14.0-API34 with below Project:
[maui-dts-unevenrows-issue.zip](https://github.com/dotnet/maui/files/14556894/maui-dts-unevenrows-issue.zip)

**Comment by XamlTest** [comment]
<img width="407" alt="Screenshot 2024-03-11 at 5 59 34 PM" src="https://github.com/dotnet/maui/assets/97647558/7a9bddb1-6849-4ed8-9a4c-cbd6a52e1e78">

**Comment by ChristopherStephan** [comment]
We have a very similar issue in case there is ContentView set for the ViewCell. A workaround is either to set HasUnevenRows to False or to wrap the ContentView with a VerticalStackLayout.

`
<DataTemplate>
    <ViewCell>
       <CustomControl that is of type ContentView>
   </ViewCell>
</DataTemplate>
`

`System.InvalidCastException: Specified cast is not valid.
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.ContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].get_VirtualView()
   at Microsoft.Maui.Handlers.ContentViewHandler.CreatePlatformView()
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.ContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnCreatePlatformView()
   at Microsoft.Maui.Handlers.ViewHandler.OnCreatePlatformElement()
   at Microsoft.Maui.Handlers.ElementHandler.CreatePlatformElement()
   at Microsoft.Maui.Handlers.ElementHandler.SetVirtualView(IElement view)
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.ContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IView view)
   at Microsoft.Maui.Handlers.ContentViewHandler.SetVirtualView(IView view)
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.ContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IElement view)
   at Microsoft.Maui.Controls.Handlers.Compatibility.ListViewRenderer.UnevenListViewDataSource.CalculateHeightForCell(UITableView tableView, Cell cell)
   at Microsoft.Maui.Controls.Handlers.Compatibility.ListViewRenderer.UnevenListViewDataSource.GetEstimatedRowHeight(UITableView table)
   at Microsoft.Maui.Controls.Handlers.Compatibility.ListViewRenderer.UnevenListViewDataSource.UpdateEstimatedRowHeight(UITableView tableView)
   at Microsoft.Maui.Controls.Handlers.Compatibility.ListViewRenderer.ListViewDataSource.DetermineEstimatedRowHeight()
   at Microsoft.Maui.Controls.Handlers.Compatibility.FormsUITableViewController.ViewWillLayoutSubviews()
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 58
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 94
   at Sandbox.Program.Main(String[] args) in Program.cs:line 12`
