### ISSUE TITLE
[Bug] RadioButtonGroup properties not working in new .NET MAUI Layout (Worked with Preview 6)

### ISSUE THREAD

**Issue by egvijayanand** [dotnet/maui#2040]
### Description
RadioButtonGroup attached properties not working in .NET MAUI Layouts (Worked with Preview 6)

### Steps to Reproduce

1. Create a new .NET MAUI project and in one of the Xaml pages, add the [code snippet](#code-snippet) provided below
2. Project builds without any error but throws the below-mentioned error during runtime
3. Observed in Android and WinUI, haven't tried in iOS and Mac Catalyst due to infra constraint

**Error message:**

Unable to cast object of type 'Microsoft.Maui.Controls.StackLayout' to type 'Microsoft.Maui.Controls.Compatibility.Layout`1[Microsoft.Maui.Controls.View]'.

#### Code Snippet:

```xaml
<StackLayout Orientation="Horizontal" RadioButtonGroup.GroupName="modes">
	<BindableLayout.ItemsSource>
		<x:Array Type="{x:Type x:String}">
			<x:String>Add</x:String>
			<x:String>Subtract</x:String>
		</x:Array>
	</BindableLayout.ItemsSource>
	<BindableLayout.ItemTemplate>
		<DataTemplate x:DataType="{x:Type x:String}">
			<RadioButton Content="{Binding}" Value="{Binding}" />
		</DataTemplate>
	</BindableLayout.ItemTemplate>
</StackLayout>
```
**Stack Trace:**
```
Unable to cast object of type 'Microsoft.Maui.Controls.StackLayout' to type 'Microsoft.Maui.Controls.Compatibility.Layout`1[Microsoft.Maui.Controls.View]'.

System.InvalidCastException
  HResult=0x80004002
  Message=Unable to cast object of type 'Microsoft.Maui.Controls.StackLayout' to type 'Microsoft.Maui.Controls.Compatibility.Layout`1[Microsoft.Maui.Controls.View]'.
  Source=Microsoft.Maui.Controls.Xaml
  StackTrace:
   at Microsoft.Maui.Controls.Xaml.ApplyPropertiesVisitor.SetPropertyValue(Object xamlelement, XmlName propertyName, Object value, Object rootElement, INode node, HydrationContext context, IXmlLineInfo lineInfo)
   at Microsoft.Maui.Controls.Xaml.ApplyPropertiesVisitor.Visit(ValueNode node, INode parentNode)
   at Microsoft.Maui.Controls.Xaml.ValueNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
   at Microsoft.Maui.Controls.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
   at Microsoft.Maui.Controls.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
   at Microsoft.Maui.Controls.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
   at Microsoft.Maui.Controls.Xaml.RootNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
   at Microsoft.Maui.Controls.Xaml.XamlLoader.Visit(RootNode rootnode, HydrationContext visitorContext, Boolean useDesignProperties)
   at Microsoft.Maui.Controls.Xaml.XamlLoader.Load(Object view, String xaml, Assembly rootAssembly, Boolean useDesignProperties)
   at Microsoft.Maui.Controls.Xaml.XamlLoader.Load(Object view, String xaml, Boolean useDesignProperties)
   at Microsoft.Maui.Controls.Xaml.XamlLoader.Load(Object view, Type callingType)
   at Microsoft.Maui.Controls.Xaml.Extensions.LoadFromXaml[TXaml](TXaml view, Type callingType)
   at DateCalculator.Views.DatePage.InitializeComponent() in E:\Tasks\Mobile\Maui\Preview 7\DateCalculator\DateCalculator.WinUI\Microsoft.Maui.Controls.SourceGen\Microsoft.Maui.Controls.SourceGen.CodeBehindGenerator\Views_DatePage.xaml.sg.cs:line 13
   at DateCalculator.Views.DatePage..ctor() in E:\Tasks\Mobile\Maui\Preview 7\DateCalculator\DateCalculator.Maui\Views\DatePage.xaml.cs:line 7
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
```
### Expected Behavior
A radio button group to be displayed (two radio buttons in this case)

### Actual Behavior
Crashes the application by throwing a runtime error

### Basic Information

- Version with issue: **.NET 6 Preview 7** (6.0.100-preview.7.21379.14)
- Last known good version: **.NET 6 Preview 6** (Older layout)
- IDE: **VS2022** (17.0.0 Preview 2.1)
- Platform Target Frameworks: 
  - iOS:  
  - Android:  Target SDK API Level 30
  - UWP:   
  - WinUI: Target SDK `net6.0-windows10.0.19041` running on Windows 11 OS build 22000.120
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by egvijayanand** [comment]
Can't even add the group of Radio Buttons directly to the StackLayout, without any layout binding, ends up with the same error.

**Comment by shimingsg** [comment]
No errors and succeed to run on windows 10.0. 19041 and Android 11 now, but some issues with Layout see:
now on windows 
![image](https://user-images.githubusercontent.com/20982341/154620942-70261f36-85a9-4a49-a1e3-386e4b09eaa4.png)
on Android 11:
![image](https://user-images.githubusercontent.com/20982341/154621729-a27cea9f-93cf-4e02-a061-db42f334297e.png)
Repro project available in Maui Triage Teams channel:
https://microsoft.sharepoint.com/:u:/t/Mauitriage/ESvHTN7orU9AkPiACxPtf5kBseVg0c-0m-jkwjHZP6muRQ?e=6IgB4t

**Comment by davidortinau** [comment]
This issue is fixed. If there are additional layout issues related, please open a new issue.
