### ISSUE TITLE
[iOS] Double dash in Entry or Editor crashes the app if iOS device has Smart Punctuation turned on

### ISSUE THREAD

**Issue by MichaelShapiro** [dotnet/maui#20439]
### Description

I found a situation where landing on a page that hosts Entry (or Editor) with a Text property set to double dash will crash the app.

Given there is a page (PageN) somewhere in the app that hosts an Entry (or an Editor) with a Text property set to double dash  

```
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="DoubleDashCrash.DoubleDashCrashPage"
             Title="Double Dash Crash Page">

    <Editor
        Text="--"
        BackgroundColor="Yellow"
        VerticalOptions="Center" 
        HorizontalOptions="Center" />
    
</ContentPage>

```
Given there is another page (PageA) with an Entry (or Editor) that will be visited before PageN.

Here are steps that lead to a crash:

1. Visit PageA and simply TAP inside the Entry. No need to type anything, just TAP inside.
2. Visit PageN. The app crashes.

If you do NOT TAP then the app doesn't crash
If you reverse the above order and first visit the page with an Entry set to double dash then the app doesn't crash
If you turn OFF Smart Punctuation in the phone's Settings then the app doesn't crash
If you do not have double dash in the Text property of the PageN then the app doesn't crash

While investigating this strange behavior I found out that when the Smart Punctuation setting is turned on, iOS is attempting to convert two adjacent dashes `--`   into   a single character, so called "em dash" or a "long dash", ASCII code151. I suspect this might be the reason why the app crashes, however I was hoping that MAUI should be capable of recognizing this condition and handling it gracefully. 

Similar issue is described in #19954 but here, I believe, I found exact steps to reproduce this bug.

https://github.com/dotnet/maui/assets/36049508/4ca64693-0275-4981-8d61-8b8b3be8c578

### Steps to Reproduce

1. On the device go to  Settings > General > Keyboards. Turn "Smart Punctuation" to ON (it's the default anyway)
2. Open the repo, run the DoubleDashCrash project for iOS
3. On the Home page simply tap inside the Editor control.
4. Open Flyout menu, tap "Double Dash Crash". This should open another page with a single Entry box with Text property set to "--". 
5. The app will crash now

### Link to public reproduction project repository

https://github.com/MichaelShapiro/MauiBugs/tree/master/DoubleDashCrash

### Version with bug

8.0.6

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Did you find any workaround?

No

### Relevant log output

```shell
C:\WINDOWS\system32>dotnet workload list

Installed Workload Id      Manifest Version       Installation Source
---------------------------------------------------------------------
maccatalyst                17.2.8004/8.0.100      VS 17.8.34511.84
maui-windows               8.0.3/8.0.100          VS 17.8.34511.84
ios                        17.2.8004/8.0.100      VS 17.8.34511.84
android                    34.0.43/8.0.100        VS 17.8.34511.84
```

**Comment by MichaelShapiro** [comment]
> Can you test with the latest nightly build? https://github.com/dotnet/maui/wiki/Nightly-Builds

I'll try. Never installed any beta builds before. As long as I can safely go back to the official production version I will try.

**Comment by MichaelShapiro** [comment]
@PureWeen It's still happening with nightly `<MauiVersion>8.0.7-preview.9998</MauiVersion>`

Let me include the full error here:

```
$exception	{System.ArgumentNullException: Value cannot be null. (Parameter 'fromPosition')
   at ObjCRuntime.ThrowHelper.ThrowArgumentNullException(String argumentName) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/ThrowHelper.cs:line 28
   at ObjCRuntime.NativeObjectExtensions.GetNonNullHandle(INativeObject self, String argumentName) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/INativeObject.cs:line 42
   at UIKit.UITextView.GetTextRange(UITextPosition fromPosition, UITextPosition toPosition) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/build/dotnet/ios/generated-sources/UIKit/UITextView.g.cs:line 565
   at Microsoft.Maui.Platform.TextInputExtensions.SetTextRange(IUITextInput platformView, Int32 start, Int32 selectedTextLength)
   at Microsoft.Maui.Controls.Platform.TextExtensions.UpdateText(IUITextInput textInput, InputView inputView, Boolean isEditing)
   at Microsoft.Maui.Controls.Platform.TextExtensions.UpdateText(UITextView textView, InputView inputView)
   at Microsoft.Maui.Controls.Editor.MapText(IEditorHandler handler, Editor editor)
   at Microsoft.Maui.PropertyMapperExtensions.<>c__DisplayClass2_0`2[[Microsoft.Maui.Controls.Editor, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.IEditorHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<ReplaceMapping>b__0(IEditorHandler h, Editor v, Action`2 p)
   at Microsoft.Maui.PropertyMapperExtensions.<>c__DisplayClass1_0`2[[Microsoft.Maui.Controls.Editor, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.IEditorHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<ModifyMapping>g__newMethod|0(IElementHandler handler, IElement view)
   at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0[[Microsoft.Maui.IEditor, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.IEditorHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v)
   at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IElementHandler viewHandler, IElement virtualView)
   at Microsoft.Maui.PropertyMapper.UpdateProperties(IElementHandler viewHandler, IElement virtualView)
   at Microsoft.Maui.Handlers.ElementHandler.SetVirtualView(IElement view)
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IEditor, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.MauiTextView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IView view)
   at Microsoft.Maui.Handlers.EditorHandler.SetVirtualView(IView view)
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IEditor, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.MauiTextView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IElement view)
   at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler)
   at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value)
   at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.set_Handler(IElementHandler value)
   at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context)
   at Microsoft.Maui.Platform.ElementExtensions.ToPlatform(IElement view, IMauiContext context)
   at Microsoft.Maui.Handlers.ContentViewHandler.UpdateContent(IContentViewHandler handler)
   at Microsoft.Maui.Handlers.ContentViewHandler.MapContent(IContentViewHandler handler, IContentView page)
   at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0[[Microsoft.Maui.IContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.IContentViewHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v)
   at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IElementHandler viewHandler, IElement virtualView)
   at Microsoft.Maui.PropertyMapper.UpdateProperties(IElementHandler viewHandler, IElement virtualView)
   at Microsoft.Maui.Handlers.ElementHandler.SetVirtualView(IElement view)
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.ContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IView view)
   at Microsoft.Maui.Handlers.ContentViewHandler.SetVirtualView(IView view)
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.ContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IElement view)
   at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler)
   at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value)
   at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.set_Handler(IElementHandler value)
   at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context)
   at Microsoft.Maui.Platform.ViewExtensions.ToHandler(IView view, IMauiContext context)
   at Microsoft.Maui.Controls.Platform.Compatibility.ShellSectionRootRenderer.SetPageRenderer(Page page, ShellContent shellContent)
   at Microsoft.Maui.Controls.Platform.Compatibility.ShellSectionRootRenderer.LoadRenderers()
   at Microsoft.Maui.Controls.Platform.Compatibility.ShellSectionRootRenderer.ViewDidLoad()
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 58
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 94
   at DoubleDashCrash.Program.Main(String[] args) in C:\mshapiro\Projects\MauiBugs\DoubleDashCrash\Platforms\iOS\Program.cs:line 12}	System.ArgumentNullException
```

**Comment by kubaflo** [comment]
@PureWeen @MichaelShapiro a possible fix here :) https://github.com/dotnet/maui/pull/20584
