### ISSUE TITLE
WebAuthenticator VirtualView cannot be null

### ISSUE THREAD

**Issue by borrmann** [dotnet/maui#20667]
### Description

When using the WebAuthenticator multiple times for SocialSignIns, usually after the second attempt the app crashes both on iOS and Android. On Android I receive the error 'VirtualView cannot be null'

### Steps to Reproduce

1. Call  `await WebAuthenticator.Default.AuthenticateAsync([...])` multiple times on same View
2. Make sure first time fails
3. Wrap entire method into Try Catch Block
4. App crashes 

### Link to public reproduction project repository

*

### Version with bug

8.0.7 SR2

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Did you find any workaround?

no

### Relevant log output

```shell
[ERROR] FATAL UNHANDLED EXCEPTION: System.InvalidOperationException: VirtualView cannot be null here
[mono-rt]    at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.ContentViewGroup, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].get_VirtualView() in D:\a\_work\1\s\src\Core\src\Handlers\View\ViewHandlerOfT.cs:line 42
[mono-rt]    at Mopups.Platforms.Android.Renderers.PopupPageRenderer.OnLayout(Boolean changed, Int32 left, Int32 top, Int32 right, Int32 bottom)
[mono-rt]    at Android.Views.ViewGroup.n_OnLayout_ZIIII(IntPtr jnienv, IntPtr native__this, Boolean changed, Int32 l, Int32 t, Int32 r, Int32 b) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net8.0/android-34/mcw/Android.Views.ViewGroup.cs:line 3670
[mono-rt]    at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPZIIII_V(_JniMarshal_PPZIIII_V callback, IntPtr jnienv, IntPtr klazz, Boolean p0, Int32 p1, Int32 p2, Int32 p3, Int32 p4) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 444
```

**Comment by borrmann** [comment]
never mind, I realised it's my error message that uses [Mopups](https://github.com/LuckyDucko/Mopups/issues/91)
