### ISSUE TITLE
CarouselView - The specified child already has a parent. You must call removeView() on the child's parent first

### ISSUE THREAD

**Issue by Vannoctar2** [dotnet/maui#20852]
### Description

I defined a CarouselView with the use of left and right arrows. In my views, there are graphic elements (with SkiaSharp).

When I press the scroll arrows several times in a row and quickly, I get the following error:

MAUI Java.Lang.IllegalStateException: 'The specified child already has a parent. You must call removeView() on the child's parent first.'

### Steps to Reproduce

1 - Launch the application
2- click quickly and many times on the right or left arrow or click on "Toute" button.
3 - The application crash with the message "The specified child already has a parent. You must call removeView() on the child's parent first"

### Link to public reproduction project repository

https://github.com/Vannoctar2/ReportBugMaui

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 14 - API 34. Emulator and other devices.

### Did you find any workaround?

I didn't find a solution.

### Relevant log output

```shell
0xFFFFFFFFFFFFFFFF in Android.Runtime.RuntimeNativeMethods.monodroid_debugger_unhandled_exception	C#
 	0x1A in Android.Runtime.JNINativeWrapper._unhandled_exception at /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:13,5	C#
 	0x20 in Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPLI_V at /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:181,26	C#
 	0x17 in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw	C#
 	0x8C in Java.Interop.JniEnvironment.InstanceMethods.CallNonvirtualVoidMethod at /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/obj/Release/net7.0/JniEnvironment.g.cs:20830,5	C#
 	0x78 in Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualVoidMethod at /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:75,7	C#
 	0x38 in Android.Views.ViewGroup.AddView at /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net8.0/android-34/mcw/Android.Views.ViewGroup.cs:2148,5	C#
 	0x65 in Microsoft.Maui.Handlers.ContentViewHandler.UpdateContent at D:\a\_work\1\s\src\Core\src\Handlers\ContentView\ContentViewHandler.Android.cs:42,5	C#
 	0x1 in Microsoft.Maui.Handlers.ContentViewHandler.MapContent at D:\a\_work\1\s\src\Core\src\Handlers\ContentView\ContentViewHandler.Android.cs:47,4	C#
 	0x21 in Microsoft.Maui.PropertyMapper<Microsoft.Maui.IContentView,Microsoft.Maui.Handlers.IContentViewHandler>. at D:\a\_work\1\s\src\Core\src\PropertyMapper.cs:172,6	C#
 	0x17 in Microsoft.Maui.PropertyMapper.UpdatePropertyCore at D:\a\_work\1\s\src\Core\src\PropertyMapper.cs:47,4	C#
 	0x8 in Microsoft.Maui.PropertyMapper.UpdateProperty at D:\a\_work\1\s\src\Core\src\PropertyMapper.cs:72,4	C#
 	0x1C in Microsoft.Maui.Handlers.ElementHandler.UpdateValue at D:\a\_work\1\s\src\Core\src\Handlers\Element\ElementHandler.cs:87,4	C#
 	0x14 in Microsoft.Maui.Controls.Element.OnPropertyChanged at D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:573,4	C#
 	0x173 in Microsoft.Maui.Controls.BindableObject.SetValueActual at D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:641,5	C#
 	0x162 in Microsoft.Maui.Controls.BindableObject.SetValueCore at D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:569,5	C#
 	0x22F in Microsoft.Maui.Controls.BindingExpression.ApplyCore at D:\a\_work\1\s\src\Controls\src\Core\BindingExpression.cs:163,5	C#
 	0x7A in Microsoft.Maui.Controls.BindingExpression.Apply at D:\a\_work\1\s\src\Controls\src\Core\BindingExpression.cs:78,4	C#
 	0x79 in Microsoft.Maui.Controls.Binding.Apply at D:\a\_work\1\s\src\Controls\src\Core\Binding.cs:137,5	C#
 	0x6A in Microsoft.Maui.Controls.BindableObject.ApplyBindings at D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:664,5	C#
 	0xA in Microsoft.Maui.Controls.BindableObject.BindingContextPropertyChanged at D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:683,4	C#
 	0x186 in Microsoft.Maui.Controls.BindableObject.SetValueActual at D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:643,5	C#
 	0x162 in Microsoft.Maui.Controls.BindableObject.SetValueCore at D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:569,5	C#
 	0x5F in Microsoft.Maui.Controls.BindableObject.SetValue at D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:474,4	C#
 	0x7 in Microsoft.Maui.Controls.BindableObject.set_BindingContext at D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:54,11	C#
 	0x82 in Microsoft.Maui.Controls.Handlers.Items.TemplatedItemViewHolder.Bind at D:\a\_work\1\s\src\Controls\src\Core\Handlers\Items\Android\TemplatedItemViewHolder.cs:80,5	C#
 	0x17 in Microsoft.Maui.Controls.Handlers.Items.ItemsViewAdapter<Microsoft.Maui.Controls.CarouselView,Microsoft.Maui.Controls.Handlers.Items.IItemsViewSource>.BindTemplatedItemViewHolder at D:\a\_work\1\s\src\Controls\src\Core\Handlers\Items\Android\Adapters\ItemsViewAdapter.cs:154,4	C#
 	0x59 in Microsoft.Maui.Controls.Handlers.Items.CarouselViewAdapter<Microsoft.Maui.Controls.CarouselView,Microsoft.Maui.Controls.Handlers.Items.IItemsViewSource>.OnBindViewHolder at D:\a\_work\1\s\src\Controls\src\Core\Handlers\Items\Android\Adapters\CarouselViewAdapter.cs:44,6	C#
 	0x12 in AndroidX.RecyclerView.Widget.RecyclerView.Adapter.n_OnBindViewHolder_Landroidx_recyclerview_widget_RecyclerView_ViewHolder_I at C:\a\_work\1\s\generated\androidx.recyclerview.recyclerview\obj\Release\net6.0-android\generated\src\AndroidX.RecyclerView.Widget.RecyclerView.cs:581,5	C#
 	0xB in Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPLI_V at /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:180,5	C#


Heure	Nom de l'appareil	Type	PID	Balise	Message
02-26 22:39:04.463	pixel_5_-_api_34_1	Warning	552	WindowManager	android.os.DeadObjectException
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:584)
	at android.view.IWindow$Stub$Proxy.insetsControlChanged(IWindow.java:479)
	at com.android.server.wm.WindowState.notifyInsetsControlChanged(WindowState.java:3802)
	at com.android.server.wm.InsetsStateController.lambda$notifyPendingInsetsControlChanged$3(InsetsStateController.java:343)
	at com.android.server.wm.InsetsStateController.$r8$lambda$8yykPRG1GyNq_J17QvL9d5xANMc(InsetsStateController.java:0)
	at com.android.server.wm.InsetsStateController$$ExternalSyntheticLambda2.run(R8$$SyntheticClass:0)
	at com.android.server.wm.WindowAnimator.executeAfterPrepareSurfacesRunnables(WindowAnimator.java:294)
	at com.android.server.wm.RootWindowContainer.performSurfacePlacementNoTrace(RootWindowContainer.java:811)
	at com.android.server.wm.RootWindowContainer.performSurfacePlacement(RootWindowContainer.java:756)
	at com.android.server.wm.WindowSurfacePlacer.performSurfacePlacementLoop(WindowSurfacePlacer.java:177)
	at com.android.server.wm.WindowSurfacePlacer.performSurfacePlacement(WindowSurfacePlacer.java:126)
	at com.android.server.wm.WindowSurfacePlacer.performSurfacePlacement(WindowSurfacePlacer.java:115)
	at com.android.server.wm.WindowSurfacePlacer$Traverser.run(WindowSurfacePlacer.java:57)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.os.HandlerThread.run(HandlerThread.java:67)
	at com.android.server.ServiceThread.run(ServiceThread.java:46)
02-26 22:39:04.685	pixel_5_-_api_34_1	Warning	552	WindowManager	android.os.DeadObjectException
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:584)
	at android.view.IWindow$Stub$Proxy.dispatchAppVisibility(IWindow.java:546)
	at com.android.server.wm.WindowState.sendAppVisibilityToClients(WindowState.java:3271)
	at com.android.server.wm.WindowContainer.sendAppVisibilityToClients(WindowContainer.java:1221)
	at com.android.server.wm.WindowToken.setClientVisible(WindowToken.java:409)
	at com.android.server.wm.ActivityRecord.setClientVisible(ActivityRecord.java:6946)
	at com.android.server.wm.ActivityRecord.postApplyAnimation(ActivityRecord.java:5637)
	at com.android.server.wm.ActivityRecord.commitVisibility(ActivityRecord.java:5580)
	at com.android.server.wm.Transition.finishTransition(Transition.java:1151)
	at com.android.server.wm.TransitionController.finishTransition(TransitionController.java:868)
	at com.android.server.wm.WindowOrganizerController.finishTransition(WindowOrganizerController.java:396)
	at android.window.IWindowOrganizerController$Stub.onTransact(IWindowOrganizerController.java:286)
	at com.android.server.wm.WindowOrganizerController.onTransact(WindowOrganizerController.java:181)
	at android.os.Binder.execTransactInternal(Binder.java:1344)
	at android.os.Binder.execTransact(Binder.java:1275)

02-26 22:39:04.366	pixel_5_-_api_34_1	Warning	552	WindowManager	android.os.DeadObjectException
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:584)
	at android.view.IWindow$Stub$Proxy.insetsControlChanged(IWindow.java:479)
	at com.android.server.wm.WindowState.notifyInsetsControlChanged(WindowState.java:3802)
	at com.android.server.wm.InsetsStateController.lambda$notifyPendingInsetsControlChanged$3(InsetsStateController.java:343)
	at com.android.server.wm.InsetsStateController.$r8$lambda$8yykPRG1GyNq_J17QvL9d5xANMc(InsetsStateController.java:0)
	at com.android.server.wm.InsetsStateController$$ExternalSyntheticLambda2.run(R8$$SyntheticClass:0)
	at com.android.server.wm.WindowAnimator.executeAfterPrepareSurfacesRunnables(WindowAnimator.java:294)
	at com.android.server.wm.WindowAnimator.animate(WindowAnimator.java:202)
	at com.android.server.wm.WindowAnimator.lambda$new$1(WindowAnimator.java:99)
	at com.android.server.wm.WindowAnimator.$r8$lambda$aHNu1uhcqxihX5NZc4McDDQPAyw(WindowAnimator.java:0)
	at com.android.server.wm.WindowAnimator$$ExternalSyntheticLambda1.doFrame(R8$$SyntheticClass:0)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1337)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1348)
	at android.view.Choreographer.doCallbacks(Choreographer.java:952)
	at android.view.Choreographer.doFrame(Choreographer.java:878)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1322)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.os.HandlerThread.run(HandlerThread.java:67)
	at com.android.server.ServiceThread.run(ServiceThread.java:46)
```

**Comment by Vannoctar2** [comment]
It looks like the following problem:

https://github.com/dotnet/maui/issues/16577

I also posted a request for help here:

https://stackoverflow.com/questions/78046872/maui-wait-carouselview-scrolling-is-done-the-specified-child-already-has-a-pa

I'm using Microsoft Visual Studio Community version 2022 (64-bit) - Current
Version 17.9.1

Thanks

**Comment by jfversluis** [comment]
Potentially also related #16043

**Comment by Vannoctar2** [comment]
Hello. Do you know if a solution exist ? Thank you

**Comment by PureWeen** [comment]
@Vannoctar2 I think this is your issue
https://github.com/dotnet/maui/issues/21161


https://github.com/Vannoctar2/ReportBugMaui/blob/master/TestBug/Test/Models/GraphicModel.cs#L44

**Comment by Vannoctar2** [comment]
Okay. I can't instantiate a contentview? The problem appears when I change the view of the carouselview. But it doesn't appear all the time and not for the same view.

**Comment by Vannoctar2** [comment]
Thank you. I can't instantiate a contentview? The problem appears when I change the view of the carouselview. But it doesn't appear all the time and not for the same view.
