### ISSUE TITLE
[Bug] FilePicker throws System.InvalidOperationException: 'Window Not Found'

### ISSUE THREAD

**Issue by Chronostasys** [dotnet/maui#2102]
### Description
In maui preview7 on android, whenever call `FilePicker.PickAsync();` method the maui application will throw `System.InvalidOperationException: 'Window Not Found'` and crash. 

### Steps to Reproduce

1. create a new maui app using default maui templat
2. setup permissions and call platform init on android
3. add `await FilePicker.PickAsync();`  in button onclick event handler and start debug
4. click the button

### Expected Behavior
the filepicker shows up

### Actual Behavior
the filepicker shows up, then the app throws `System.InvalidOperationException: 'Window Not Found'` and crash.

### Basic Information

- Version with issue: maui preview7
- Last known good version: maui preview6
- IDE: VIsual Studio 2022 preview 3
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:android

### Screenshots
![image](https://user-images.githubusercontent.com/49905799/129444801-2cc7971e-57da-43fa-9ac0-f59adfa04806.png)

### Reproduction Link
https://github.com/Chronostasys/ButtonTest

**Comment by josephatkuvio** [comment]
I am seeing the same issue on Preview 7 on Android, in my case when attempting to open a custom tab via MSAL.NET. I've tried with the embedded browser as well, same issue, so it seems to be related to the launching of _any_ new activity, or more specifically, the default MAUI OnResume callbacks.  Here is a full stack trace upon crash. It appears that something in the MAUI OnResume handlers could be passing the wrong Window object up the chain? 

```
08-13 16:04:20.222 22816 22816 D AndroidRuntime: Shutting down VM
08-13 16:04:20.223 22816 22816 E AndroidRuntime: FATAL EXCEPTION: main
08-13 16:04:20.223 22816 22816 E AndroidRuntime: android.runtime.JavaProxyThrowable: System.InvalidOperationException: Window Not Found
08-13 16:04:20.223 22816 22816 E AndroidRuntime:    at Microsoft.Maui.ContextExtensions.GetWindow(Context context) in Microsoft.Maui.dll:token 0x60001ad+0x7f
08-13 16:04:20.223 22816 22816 E AndroidRuntime:    at Microsoft.Maui.LifecycleEvents.AppHostBuilderExtensions.<>c.<OnConfigureLifeCycle>b__1_2(Activity activity) in Microsoft.Maui.dll:token 0x6000996+0x0
08-13 16:04:20.223 22816 22816 E AndroidRuntime:    at Microsoft.Maui.MauiApplication.ActivityLifecycleCallbacks.<>c__DisplayClass2_0.<OnActivityResumed>b__0(OnResume del) in Microsoft.Maui.dll:token 0x6000ab6+0x0
08-13 16:04:20.223 22816 22816 E AndroidRuntime:    at Microsoft.Maui.LifecycleEvents.LifecycleEventServiceExtensions.InvokeLifecycleEvents[OnResume](IServiceProvider services, Action`1 action) in Microsoft.Maui.dll:token 0x60004d5+0x1d
08-13 16:04:20.223 22816 22816 E AndroidRuntime:    at Microsoft.Maui.MauiApplication.ActivityLifecycleCallbacks.OnActivityResumed(Activity activity) in Microsoft.Maui.dll:token 0x6000887+0x1b
08-13 16:04:20.223 22816 22816 E AndroidRuntime:    at Android.App.Application.IActivityLifecycleCallbacksInvoker.n_OnActivityResumed_Landroid_app_Activity_(IntPtr jnienv, IntPtr native__this, IntPtr native_activity) in Mono.Android.dll:token 0x602506c+0xf
08-13 16:04:20.223 22816 22816 E AndroidRuntime:        at crc6488302ad6e9e4df1a.MauiApplication_ActivityLifecycleCallbacks.n_onActivityResumed(Native Method)
08-13 16:04:20.223 22816 22816 E AndroidRuntime:        at crc6488302ad6e9e4df1a.MauiApplication_ActivityLifecycleCallbacks.onActivityResumed(MauiApplication_ActivityLifecycleCallbacks.java:74)
08-13 16:04:20.223 22816 22816 E AndroidRuntime:        at android.app.Application.dispatchActivityResumed(Application.java:436)
08-13 16:04:20.223 22816 22816 E AndroidRuntime:        at android.app.Activity.dispatchActivityResumed(Activity.java:1379)
08-13 16:04:20.223 22816 22816 E AndroidRuntime:        at android.app.Activity.onResume(Activity.java:1905)
08-13 16:04:20.223 22816 22816 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1456)
08-13 16:04:20.223 22816 22816 E AndroidRuntime:        at android.app.Activity.performResume(Activity.java:8135)
08-13 16:04:20.223 22816 22816 E AndroidRuntime:        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4434)
08-13 16:04:20.223 22816 22816 E AndroidRuntime:        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4476)
08-13 16:04:20.223 22816 22816 E AndroidRuntime:        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
08-13 16:04:20.223 22816 22816 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
08-13 16:04:20.223 22816 22816 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
08-13 16:04:20.223 22816 22816 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
08-13 16:04:20.223 22816 22816 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
08-13 16:04:20.223 22816 22816 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:223)
08-13 16:04:20.223 22816 22816 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7656)
08-13 16:04:20.223 22816 22816 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
08-13 16:04:20.223 22816 22816 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
08-13 16:04:20.223 22816 22816 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

At the moment the new activity is created, the following log code added to OnResume:

```
Android.Util.Log.Info("", "Activity is " + activity);
Android.Util.Log.Info("", "Window is " + activity.Window);
Android.Util.Log.Info("", "Context is " + activity.GetWindow());
```        
returns this:

```
08-15 13:54:11.991  4878  4878 I: Activity is crc647e7a282969979595.MainActivity@d9db2e9
08-15 13:54:11.998  4878  4878 I: Window is com.android.internal.policy.PhoneWindow@777de97
08-15 13:54:11.998  4878  4878 I: Context is Microsoft.Maui.Controls.Window
```

I do see new PR activity around CreateWindow in #2035 by @mattleibow, but it didn't make it into Preview 7, and seems to revolve around more of an app launch timing issue than anything.

**Comment by PaulSorauer-IPG** [comment]
+1 from me.

I'm getting the issue when trying to acquire a token using MSAL.NET in Microsoft.Identity.Client v.4.35.1 (which was working fine in Preview 6).

More details supplied in #2154 - https://github.com/dotnet/maui/issues/2154#issuecomment-901627671

Cheers,

Paul

**Comment by rabberbock** [comment]
Same here with WebAuthenticator

```
Time	Device Name	Type	PID	Tag	Message
08-20 12:57:40.885	Samsung SM-G991U	Error	31165	AndroidRuntime	android.runtime.JavaProxyThrowable: System.InvalidOperationException: Window Not Found
   at Microsoft.Maui.ContextExtensions.GetWindow(Context context) in Microsoft.Maui.dll:token 0x60001ad+0x7f
   at Microsoft.Maui.LifecycleEvents.AppHostBuilderExtensions.<>c.<OnConfigureLifeCycle>b__1_2(Activity activity) in Microsoft.Maui.dll:token 0x6000996+0x0
   at Microsoft.Maui.MauiApplication.ActivityLifecycleCallbacks.<>c__DisplayClass2_0.<OnActivityResumed>b__0(OnResume del) in Microsoft.Maui.dll:token 0x6000ab6+0x0
   at Microsoft.Maui.LifecycleEvents.LifecycleEventServiceExtensions.InvokeLifecycleEvents[OnResume](IServiceProvider services, Action`1 action) in Microsoft.Maui.dll:token 0x60004d5+0x1d
   at Microsoft.Maui.MauiApplication.ActivityLifecycleCallbacks.OnActivityResumed(Activity activity) in Microsoft.Maui.dll:token 0x6000887+0x1b
   at Android.App.Application.IActivityLifecycleCallbacksInvoker.n_OnActivityResumed_Landroid_app_Activity_(IntPtr jnienv, IntPtr native__this, IntPtr native_activity) in Mono.Android.dll:token 0x602506c+0xf
   at Java.Interop.JniEnvironment.InstanceMethods.CallNonvirtualVoidMethod(JniObjectReference instance, JniObjectReference type, JniMethodInfo method, JniArgumentValue* args) in Java.Interop.dll:token 0x600055b+0x8e
   at Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualVoidMethod(String encodedMember, IJavaPeerable self, JniArgumentValue* parameters) in Java.Interop.dll:token 0x60005ea+0x63
   at Android.App.Activity.OnResume() in Mono.Android.dll:token 0x6015187+0xa
   at Microsoft.Maui.Essentials.WebAuthenticatorIntermediateActivity.OnResume() in Microsoft.Maui.Essentials.dll:token 0x600041c+0x0
   at Android.App.Activity.n_OnResume(IntPtr jnienv, IntPtr native__this) in Mono.Android.dll:token 0x6015186+0x8
	at crc64192d9de59b079c6d.WebAuthenticatorIntermediateActivity.n_onResume(Native Method)
	at crc64192d9de59b079c6d.WebAuthenticatorIntermediateActivity.onResume(WebAuthenticatorIntermediateActivity.java:40)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1456)
	at android.app.Activity.performResume(Activity.java:8344)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4854)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4901)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8512)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

```

**Comment by mattleibow** [comment]
Having a look at that stack trace I think we fixed that shortly after releasing P7.
Previously we assumed there was always Window since you started from one. But in some cases, this was not true.

It should be fixed in RC1. You can test out the current CI builds using this Wiki: 
https://github.com/dotnet/maui/wiki/Installing-.NET-6

**Comment by Rowingwolf** [comment]
I believe I'm seeing the same issue when calling MediaPicker.CapturePhotoAsync().  I'll probably wait until RC1 is released.  I'm assuming it should be out in the next week or so.

Am surprised this one made it into the wild because it impacts such a wide range of calls.

**Comment by pwkiel** [comment]
> 

I too am experiencing issues with this still. I see its still being tracked open and that there is a link to a fix. Is that fix set to go live later this month when preview 11 comes out?
