### ISSUE TITLE
[testing] Xharness fails to run locally 

### ISSUE THREAD

**Issue by rmarinho** [dotnet/maui#21080]
### Description

I see some issues locally that I think we also see on the CI pipelines, where xharness can't start the application even in iOS 17.2 simulators and Xcode 15.2 

### Steps to Reproduce

Checkout the net9 branch. 

```shell
dotnet tool restore
dotnet cake --configuration=Release
dotnet cake -script eng/devices/ios.cake --project="/Users/ruimarinho/dotnet/maui/src/Controls/tests/DeviceTests/Controls.DeviceTests.csproj" --device=ios-simulator-64_17.2 --apiversion=17.2
```

### Affected platforms

iOS

```shell
========================================
Test
========================================
Setting environment variable: VSDebugger_ValidateDotnetDebugLibSignatures = '0'
Setting environment variable: DOTNET_INSTALL_DIR = '/Users/ruimarinho/dotnet/maui/eng/devices/bin/dotnet'
Setting environment variable: DOTNET_ROOT = '/Users/ruimarinho/dotnet/maui/eng/devices/bin/dotnet'
Setting environment variable: DOTNET_MSBUILD_SDK_RESOLVER_CLI_DIR = '/Users/ruimarinho/dotnet/maui/eng/devices/bin/dotnet'
Setting environment variable: DOTNET_MULTILEVEL_LOOKUP = '0'
Setting environment variable: MSBuildEnableWorkloadResolver = 'true'
Setting environment variable: PATH = '/Users/ruimarinho/dotnet/maui/eng/devices/bin/dotnet:/Users/ruimarinho/dotnet/maui/eng/devices/bin/dotnet:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/usr/local/MacGPG2/bin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/ruimarinho/.dotnet/tools:/Users/ruimarinho/Library/Developer/Xamarin/android-sdk-macosx/platform-tools:/Users/ruimarinho/Library/Developer/Xamarin/android-sdk-macosx/emulator:/Users/ruimarinho/.azureauth/0.8.4'
Test Device: ios-simulator-64_17.2
Test App: /Users/ruimarinho/dotnet/maui/src/Controls/tests/DeviceTests/bin/Debug/net9.0-ios/iossimulator-x64/Microsoft.Maui.Controls.DeviceTests.app
Test Results Directory: /Users/ruimarinho/dotnet/maui/src/Controls/tests/DeviceTests/bin/Debug/net9.0-ios/iossimulator-x64/Microsoft.Maui.Controls.DeviceTests.app-results
XCODE PATH: 
[9.0.0-prerelease.24119.1+8aa2a4cb80000ebb46ee61cd6ac29b2e63ebe87c] XHarness command issued: apple test --app=/Users/ruimarinho/dotnet/maui/src/Controls/tests/DeviceTests/bin/Debug/net9.0-ios/iossimulator-x64/Microsoft.Maui.Controls.DeviceTests.app --targets=ios-simulator-64_17.2 --output-directory=/Users/ruimarinho/dotnet/maui/src/Controls/tests/DeviceTests/bin/Debug/net9.0-ios/iossimulator-x64/Microsoft.Maui.Controls.DeviceTests.app-results --timeout=01:15:00 --launch-timeout=00:06:00 --verbosity=Debug
info: Preparing run for ios-simulator-64_17.2
warn: Lldb will be used since '~/.mtouch-launch-with-lldb' was found in the system but it was not created by xharness.
info: Looking for available ios-simulator-64_17.2 simulators..
dbug: Looking for available ios-simulator-64_17.2 simulators. Storing logs into list-ios-simulator-64_17.2-20240307_142136.log
info: Found simulator device 'iPhone Xs (iOS 17.2) - created by XHarness'
info: Getting app bundle information from '/Users/ruimarinho/dotnet/maui/src/Controls/tests/DeviceTests/bin/Debug/net9.0-ios/iossimulator-x64/Microsoft.Maui.Controls.DeviceTests.app'..
dbug: 
dbug: Running /usr/libexec/PlistBuddy -c "Print CFBundleName" /Users/ruimarinho/dotnet/maui/src/Controls/tests/DeviceTests/bin/Debug/net9.0-ios/iossimulator-x64/Microsoft.Maui.Controls.DeviceTests.app/Info.plist
dbug: Process PlistBuddy exited with 0
dbug: 
dbug: Running /usr/libexec/PlistBuddy -c "Print CFBundleIdentifier" /Users/ruimarinho/dotnet/maui/src/Controls/tests/DeviceTests/bin/Debug/net9.0-ios/iossimulator-x64/Microsoft.Maui.Controls.DeviceTests.app/Info.plist
dbug: Process PlistBuddy exited with 0
dbug: 
dbug: Running /usr/libexec/PlistBuddy -c "Print UIRequiredDeviceCapabilities" /Users/ruimarinho/dotnet/maui/src/Controls/tests/DeviceTests/bin/Debug/net9.0-ios/iossimulator-x64/Microsoft.Maui.Controls.DeviceTests.app/Info.plist
dbug: Process PlistBuddy exited with 0
dbug: 
dbug: Running /usr/libexec/PlistBuddy -c "Print CFBundleExecutable" /Users/ruimarinho/dotnet/maui/src/Controls/tests/DeviceTests/bin/Debug/net9.0-ios/iossimulator-x64/Microsoft.Maui.Controls.DeviceTests.app/Info.plist
dbug: Process PlistBuddy exited with 0
info: Uninstalling any previous instance of 'com.microsoft.maui.controls.devicetests' from 'iPhone Xs (iOS 17.2) - created by XHarness'
dbug: 
dbug: Running /Applications/Xcode.app/Contents/Developer/usr/bin/simctl uninstall 36A951BB-86CE-4C67-9FD0-9C768A785FD4 com.microsoft.maui.controls.devicetests
dbug: An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=405):
dbug: Unable to lookup in current state: Shutdown
dbug: Process simctl exited with 149
dbug: Preemptive uninstallation of application failed
info: Installing application 'Microsoft.Maui.Controls.DeviceTests' on 'iPhone Xs (iOS 17.2) - created by XHarness'
dbug: Installing '/Users/ruimarinho/dotnet/maui/src/Controls/tests/DeviceTests/bin/Debug/net9.0-ios/iossimulator-x64/Microsoft.Maui.Controls.DeviceTests.app' to 'iPhone Xs (iOS 17.2) - created by XHarness' (69,28 MB)
dbug: 
dbug: Running /Users/ruimarinho/.nuget/packages/microsoft.dotnet.xharness.cli/9.0.0-prerelease.24119.1/tools/net9.0/any/../../../runtimes/any/native/mlaunch/bin/mlaunch --sdkroot /Applications/Xcode.app --device=:v2:udid=36A951BB-86CE-4C67-9FD0-9C768A785FD4 --installsim /Users/ruimarinho/dotnet/maui/src/Controls/tests/DeviceTests/bin/Debug/net9.0-ios/iossimulator-x64/Microsoft.Maui.Controls.DeviceTests.app -v -v
dbug: Using Xcode 15.2 found in /Applications/Xcode.app
dbug: Xamarin.Hosting: Xamarin.Hosting
dbug: Xamarin.Hosting:     Version: f8f70b23a4 (refs/heads/main)
dbug: Xamarin.Hosting:     Xcode: /Applications/Xcode.app
dbug: Xamarin.Hosting:     Xcode Version: 15.2
dbug: Xamarin.Hosting:     Verbosity: 2
dbug: Xamarin.Hosting: Booting iPhone Xs (iOS 17.2) - created by XHarness...
dbug: Xamarin.Hosting: Booted iPhone Xs (iOS 17.2) - created by XHarness successfully.
dbug: Xamarin.Hosting: Installing on iOS 17.2 (21C62) - iPhone Xs by executing 'xcrun simctl install 36A951BB-86CE-4C67-9FD0-9C768A785FD4 /Users/ruimarinho/dotnet/maui/src/Controls/tests/DeviceTests/bin/Debug/net9.0-ios/iossimulator-x64/Microsoft.Maui.Controls.DeviceTests.app'
dbug: Xamarin.Hosting: Could not find any potentially troublesome weak load commands.
dbug: Xamarin.Hosting: The bundle id com.microsoft.maui.controls.devicetests was successfully installed.
dbug: Xamarin.Hosting: Shutdown iPhone Xs (iOS 17.2) - created by XHarness successfully.
dbug: Process mlaunch exited with 0
info: Application 'Microsoft.Maui.Controls.DeviceTests' was installed successfully on 'iPhone Xs (iOS 17.2) - created by XHarness'
info: Starting test run for com.microsoft.maui.controls.devicetests..
dbug: *** Executing 'Microsoft.Maui.Controls.DeviceTests' on ios-simulator-64_17.2 'iPhone Xs (iOS 17.2) - created by XHarness' ***
dbug: Test log server listening on: 0.0.0.0:50283
dbug: System log for the 'iPhone Xs (iOS 17.2) - created by XHarness' simulator is: /Users/ruimarinho/Library/Logs/CoreSimulator/36A951BB-86CE-4C67-9FD0-9C768A785FD4/system.log
dbug: Booting simulator 'iPhone Xs (iOS 17.2) - created by XHarness'
dbug: 
dbug: Running /Users/ruimarinho/.nuget/packages/microsoft.dotnet.xharness.cli/9.0.0-prerelease.24119.1/tools/net9.0/any/../../../runtimes/any/native/mlaunch/bin/mlaunch --sdkroot /Applications/Xcode.app --device=:v2:udid=36A951BB-86CE-4C67-9FD0-9C768A785FD4 --launchsimulator -v -v
dbug: Using Xcode 15.2 found in /Applications/Xcode.app
dbug: Xamarin.Hosting: Xamarin.Hosting
dbug: Xamarin.Hosting:     Version: f8f70b23a4 (refs/heads/main)
dbug: Xamarin.Hosting:     Xcode: /Applications/Xcode.app
dbug: Xamarin.Hosting:     Xcode Version: 15.2
dbug: Xamarin.Hosting:     Verbosity: 2
dbug: Xamarin.Hosting: Simulator watchdogs are not disabled for 'iOS 17.2 (21C62) - iPhone Xs'.
dbug: Xamarin.Hosting: Successfully disabled simulator watchdogs for 'iOS 17.2 (21C62) - iPhone Xs'.
dbug: Xamarin.Hosting: Launching simulator application 'com.apple.iphonesimulator'
dbug: Xamarin.Hosting: Ready notification 'com.apple.iphonesimulator.ready' received from the simulator.
dbug: Xamarin.Hosting: Booting iPhone Xs (iOS 17.2) - created by XHarness...
dbug: Xamarin.Hosting: Booted iPhone Xs (iOS 17.2) - created by XHarness successfully.
dbug: Xamarin.Hosting: Device 'iOS 17.2 (21C62) - iPhone Xs' booted.
dbug: Process mlaunch exited with 0
dbug: Simulator 'iPhone Xs (iOS 17.2) - created by XHarness' booted in 6 seconds
dbug: Scanning log stream for Microsoft.Maui.Controls.DeviceTests into '/Users/ruimarinho/dotnet/maui/src/Controls/tests/DeviceTests/bin/Debug/net9.0-ios/iossimulator-x64/Microsoft.Maui.Controls.DeviceTests.app-results/Microsoft.Maui.Controls.DeviceTests.log'..
dbug: 
dbug: Running /Applications/Xcode.app/Contents/Developer/usr/bin/simctl spawn 36A951BB-86CE-4C67-9FD0-9C768A785FD4 log stream --level=debug --color=none --style=compact --predicate "senderImagePath contains 'Microsoft.Maui.Controls.DeviceTests'"
dbug: Launching the app
dbug: 
dbug: Running /Users/ruimarinho/.nuget/packages/microsoft.dotnet.xharness.cli/9.0.0-prerelease.24119.1/tools/net9.0/any/../../../runtimes/any/native/mlaunch/bin/mlaunch --sdkroot /Applications/Xcode.app -setenv=NUNIT_AUTOEXIT=true -setenv=NUNIT_HOSTPORT=50283 -setenv=NUNIT_ENABLE_XML_OUTPUT=true -setenv=NUNIT_XML_VERSION=xUnit -setenv=NUNIT_HOSTNAME=127.0.0.1 --device=:v2:udid=36A951BB-86CE-4C67-9FD0-9C768A785FD4 --launchsimbundleid=com.microsoft.maui.controls.devicetests -v -v -v -v -v
dbug: Using Xcode 15.2 found in /Applications/Xcode.app
dbug: Xamarin.Hosting: Xamarin.Hosting
dbug: Xamarin.Hosting:     Version: f8f70b23a4 (refs/heads/main)
dbug: Xamarin.Hosting:     Xcode: /Applications/Xcode.app
dbug: Xamarin.Hosting:     Xcode Version: 15.2
dbug: Xamarin.Hosting:     Verbosity: 5
dbug: Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/SharedFrameworks/DVTFoundation.framework/Versions/A/DVTFoundation
dbug: Xamarin.Hosting: Loaded /Library/Developer/PrivateFrameworks/CoreSimulator.framework/CoreSimulator
dbug: Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/SharedFrameworks/DVTDeviceFoundation.framework/DVTDeviceFoundation
dbug: Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/SharedFrameworks/DTDeviceKitBase.framework/DTDeviceKitBase
dbug: Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/SharedFrameworks/DVTKit.framework/DVTKit
dbug: Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/SharedFrameworks/DTDeviceKit.framework/DTDeviceKit
dbug: Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/SharedFrameworks/DTXConnectionServices.framework/DTXConnectionServices
dbug: Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/SharedFrameworks/DVTSourceControl.framework/DVTSourceControl
dbug: Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/SharedFrameworks/DVTServices.framework/DVTServices
dbug: Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/SharedFrameworks/DVTPortal.framework/DVTPortal
dbug: Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/SharedFrameworks/DVTDocumentation.framework/DVTDocumentation
dbug: Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/SharedFrameworks/DVTAnalyticsClient.framework/DVTAnalyticsClient
dbug: Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/SharedFrameworks/XCServices.framework/XCServices
dbug: Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/SharedFrameworks/DVTAppStoreConnect.framework/DVTAppStoreConnect
dbug: Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/SharedFrameworks/ContentDelivery.framework/ContentDelivery
dbug: Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/SharedFrameworks/ContentDeliveryServices.framework/ContentDeliveryServices
dbug: Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/SharedFrameworks/Notarization.framework/Notarization
dbug: Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/SharedFrameworks/DVTITunesSoftwareServiceFoundation.framework/DVTITunesSoftwareServiceFoundation
dbug: Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/SharedFrameworks/DVTITunesSoftware.framework/DVTITunesSoftware
dbug: Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/SharedFrameworks/DVTProducts.framework/DVTProducts
dbug: Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/SharedFrameworks/DVTProductsUI.framework/DVTProductsUI
dbug: Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/SharedFrameworks/DVTCrashLogFoundation.framework/DVTCrashLogFoundation
dbug: Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/SharedFrameworks/DVTAnalytics.framework/DVTAnalytics
dbug: Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/SharedFrameworks/SourceKit.framework/SourceKit
dbug: Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/Frameworks/IDEFoundation.framework/IDEFoundation
dbug: Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/SharedFrameworks/IDEDistribution.framework/Versions/A/IDEDistribution
dbug: Xamarin.Hosting: Loaded /Applications/Xcode.app/Contents/SharedFrameworks/IDEProducts.framework/IDEProducts
dbug: Xamarin.Hosting: Simulator watchdogs are already disabled for 'iOS 17.2 (21C62) - iPhone Xs'.
dbug: Xamarin.Hosting: Device 'iOS 17.2 (21C62) - iPhone Xs' is already booted and the simulator is running.
dbug: Xamarin.Hosting: Launching on iOS 17.2 (21C62) - iPhone Xs by executing 'xcrun simctl launch --console --terminate-running-process 36A951BB-86CE-4C67-9FD0-9C768A785FD4 com.microsoft.maui.controls.devicetests' with environment:
dbug: SIMCTL_CHILD_NUNIT_AUTOEXIT=true
dbug: SIMCTL_CHILD_NUNIT_HOSTPORT=50283
dbug: SIMCTL_CHILD_NUNIT_ENABLE_XML_OUTPUT=true
dbug: SIMCTL_CHILD_NUNIT_XML_VERSION=xUnit
dbug: SIMCTL_CHILD_NUNIT_HOSTNAME=127.0.0.1
dbug: SIMCTL_CHILD_OS_ACTIVITY_DT_MODE=YES
dbug: SIMCTL_CHILD_NSUnbufferedIO=YES
dbug: DEVELOPER_DIR=/Applications/Xcode.app
dbug: NSUnbufferedIO=YES
dbug: xcrun simctl launch --console --terminate-running-process 36A951BB-86CE-4C67-9FD0-9C768A785FD4 com.microsoft.maui.controls.devicetests
dbug: An error was encountered processing the command (domain=FBSOpenApplicationServiceErrorDomain, code=1):
dbug: Simulator device failed to launch com.microsoft.maui.controls.devicetests.
dbug: The request was denied by service delegate (SBMainWorkspace) for reason: NotFound ("Application "com.microsoft.maui.controls.devicetests" is unknown to FrontBoard").
dbug: Underlying error (domain=FBSOpenApplicationServiceErrorDomain, code=1):
dbug: The request to open "com.microsoft.maui.controls.devicetests" failed.
dbug: The request was denied by service delegate (SBMainWorkspace) for reason: NotFound ("Application "com.microsoft.maui.controls.devicetests" is unknown to FrontBoard").
dbug: error HE0042: Could not launch the app 'com.microsoft.maui.controls.devicetests' on the device 'iOS 17.2 (21C62) - iPhone Xs': simctl returned exit code 1
dbug: at Xamarin.Hosting.Services.LaunchApplicationInSimulatorInternalAsyncSimCtl(SimulatorLaunchConfig) in /Users/builder/azdo/_work/2/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Hosting/Services.cs:line 1094
dbug: at Xamarin.Hosting.Services.LaunchApplicationInSimulatorAsync(SimulatorLaunchConfig) in /Users/builder/azdo/_work/2/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Hosting/Services.cs:line 1212
dbug: at Xamarin.Launcher.SimController.LaunchAsync(SimulatorLaunchConfig) in /Users/builder/azdo/_work/2/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Launcher/controller-simulator.cs:line 689
dbug: at Xamarin.Launcher.Driver.LaunchSimulatorAsync() in /Users/builder/azdo/_work/2/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Launcher/Main.cs:line 829
dbug: at Xamarin.Launcher.Driver.MainAsync() in /Users/builder/azdo/_work/2/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Launcher/Main.cs:line 506
dbug: at Xamarin.Utils.NSRunLoopExtensions.RunUntilTaskCompletion[T](NSRunLoop, Task`1) in /Users/builder/azdo/_work/2/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Utils/Extensions.cs:line 30
dbug: at Xamarin.Launcher.Driver.Main2(String[]) in /Users/builder/azdo/_work/2/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Launcher/Main.cs:line 436
dbug: at Xamarin.Launcher.Driver.Main(String[]) in /Users/builder/azdo/_work/2/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Launcher/Main.cs:line 123
dbug: Process mlaunch exited with 1
dbug: Test run failed
dbug: Could not find pid in mtouch output.
dbug: Test run started but crashed and no test results were reported
dbug: No crash reports, waiting 30 seconds for the crash report service...
dbug: Found 6 new crash report(s)
dbug: - Adding /Users/ruimarinho/Library/Logs/DiagnosticReports/findmylocated-2024-03-07-142421.000.ips
dbug: Successfully copied findmylocated-2024-03-07-142421.000.ips
dbug: - Adding /Users/ruimarinho/Library/Logs/DiagnosticReports/findmylocated-2024-03-07-142431.ips
dbug: Successfully copied findmylocated-2024-03-07-142431.ips
dbug: - Adding /Users/ruimarinho/Library/Logs/DiagnosticReports/findmylocated-2024-03-07-142421.ips
dbug: Successfully copied findmylocated-2024-03-07-142421.ips
dbug: - Adding /Users/ruimarinho/Library/Logs/DiagnosticReports/findmylocated-2024-03-07-142420.ips
dbug: Successfully copied findmylocated-2024-03-07-142420.ips
dbug: - Adding /Users/ruimarinho/Library/Logs/DiagnosticReports/findmylocated-2024-03-07-142450.ips
dbug: Successfully copied findmylocated-2024-03-07-142450.ips
dbug: - Adding /Users/ruimarinho/Library/Logs/DiagnosticReports/findmylocated-2024-03-07-142440.ips
dbug: Successfully copied findmylocated-2024-03-07-142440.ips
dbug: Test execution started
fail: Application test run crashed
      Failed to launch the application, please try again. If the problem persists, try rebooting MacOS
info: Uninstalling the application 'com.microsoft.maui.controls.devicetests' from 'iPhone Xs (iOS 17.2) - created by XHarness'
dbug: 
dbug: Running /Applications/Xcode.app/Contents/Developer/usr/bin/simctl uninstall 36A951BB-86CE-4C67-9FD0-9C768A785FD4 com.microsoft.maui.controls.devicetests
dbug: Process simctl exited with 0
info: Application 'com.microsoft.maui.controls.devicetests' was uninstalled successfully
XHarness exit code: 83 (APP_LAUNCH_FAILURE)
An error occurred when executing task 'Test'.

----------------------------------------
TearDown
----------------------------------------
Deleting XHarness simulator if exists...
Looking for simulator: XHarness ios version 17.2
Deleting XHarness simulator iPhone Xs (iOS 17.2) - created by XHarness (36A951BB-86CE-4C67-9FD0-9C768A785FD4)...
Error: Value cannot be null. (Parameter 'filePath')
```

**Comment by rmarinho** [comment]
Not a issue anymore
