### ISSUE TITLE
Simple ContentPropertyAttribute throws System.Reflection.TargetException

### ISSUE THREAD

**Issue by mrlacey** [dotnet/maui#21118]
### Description

Trying to make a simple control that sets `ContentProperty` but this results in an exception at runtime

```ascii
System.Reflection.TargetException
  HResult=0x80131603
  Message=Non-static method requires a target.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Reflection.MethodBase.ValidateInvokeTarget(Object target)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Microsoft.Maui.Controls.Xaml.ApplyPropertiesVisitor.TryAddValue(BindableObject bindable, BindableProperty property, Object value, IServiceProvider serviceProvider, Exception& exception)
   at Microsoft.Maui.Controls.Xaml.ApplyPropertiesVisitor.TrySetValue(Object element, BindableProperty property, Boolean attached, Object value, IXmlLineInfo lineInfo, IServiceProvider serviceProvider, Exception& exception)
   at Microsoft.Maui.Controls.Xaml.ApplyPropertiesVisitor.TrySetPropertyValue(Object element, XmlName propertyName, String xKey, Object value, Object rootElement, IXmlLineInfo lineInfo, IServiceProvider serviceProvider, Exception& xpe)
   at Microsoft.Maui.Controls.Xaml.ApplyPropertiesVisitor.SetPropertyValue(Object xamlelement, XmlName propertyName, Object value, Object rootElement, INode node, HydrationContext context, IXmlLineInfo lineInfo)
   at Microsoft.Maui.Controls.Xaml.ApplyPropertiesVisitor.Visit(ElementNode node, INode parentNode)
   at Microsoft.Maui.Controls.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
   at Microsoft.Maui.Controls.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
   at Microsoft.Maui.Controls.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
   at Microsoft.Maui.Controls.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
   at Microsoft.Maui.Controls.Xaml.RootNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
   at Microsoft.Maui.Controls.Xaml.XamlLoader.Visit(RootNode rootnode, HydrationContext visitorContext, Boolean useDesignProperties)
   at Microsoft.Maui.Controls.Xaml.XamlLoader.Load(Object view, String xaml, Assembly rootAssembly, Boolean useDesignProperties)
   at Microsoft.Maui.Controls.Xaml.XamlLoader.Load(Object view, String xaml, Boolean useDesignProperties)
   at Microsoft.Maui.Controls.Xaml.XamlLoader.Load(Object view, Type callingType)
   at Microsoft.Maui.Controls.Xaml.Extensions.LoadFromXaml[TXaml](TXaml view, Type callingType)
   at MauiContentPropertyIssueRepro.MainPage.InitializeComponent() in D:\source\MauiContentPropertyIssueRepro\MauiContentPropertyIssueRepro\Microsoft.Maui.Controls.SourceGen\Microsoft.Maui.Controls.SourceGen.CodeBehindGenerator\MainPage.xaml.sg.cs:line 26
   at MauiContentPropertyIssueRepro.MainPage..ctor() in D:\source\MauiContentPropertyIssueRepro\MauiContentPropertyIssueRepro\MainPage.xaml.cs:line 9
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
````

### Steps to Reproduce

1. Create a new project

2. Add this class:

```csharp
[ContentProperty(name: "Children")]
public class MyContainer : ContentView
{
    public VerticalStackLayout vsl;

    public MyContainer()
    {
        vsl = new VerticalStackLayout();

        base.Content = vsl; ;
    }

    public IList<IView> Children
    {
        get => (IList<IView>)GetValue(ChildrenProperty);
        set => SetValue(ChildrenProperty, value);
    }

    public static readonly BindableProperty ChildrenProperty =
BindableProperty.Create(nameof(Children), typeof(IList<IView>), typeof(MyContainer), null, propertyChanged: ChildrenChanged);

    private static void ChildrenChanged(BindableObject bindable, object oldValue, object newValue)
    {
        if (bindable is MyContainer b)
        {
            if (newValue is IView newView)
            {
                b.vsl.Children.Add(newView);
            }
        }
    }
}
```

3. Use it in a XAML file. Like this:

```xml
    <local:MyContainer>
        <Label>one</Label>
        <Label>two</Label>
    </local:MyContainer>
```

4. See it compiles ok.
5. Run the app: get exception.
6. Be sad

### Version with bug

7.0.101

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

7.0.101

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Did you find any workaround?

Nope. :(

**Comment by dotMorten** [comment]
A lot of this sample makes me go "uhm.....". First of all the Children property hides the baseclass children property. Second, it seems like you're making a Layout control, but you're not inheriting from Layout. Lastly the Children collection is null, so there's nothing to add the items to.
Having said that, here's a quick fix for just that last bit by just returning the Children of `vsl`, and your sample will run:

```

    [ContentProperty(name: "Children")]
    public class MyContainer : ContentView
    {
        public VerticalStackLayout vsl;

        public MyContainer()
        {
            vsl = new VerticalStackLayout();
            base.Content = vsl;
        }
        public IList<IView> Children => vsl.Children;
    }
```

**Comment by mrlacey** [comment]
Built and verified: the issue still reproduces on .NET 10 / MAUI 10.0.20.
