### ISSUE TITLE
ICanvas.FillRectangle is converting values to Single and fails

### ISSUE THREAD

**Issue by nick5454** [dotnet/maui#21222]
### Description

When calling iCanvas.FillRectangle from a custom GraphicsView the values are being converted to Single from a float and are failing. ICanvas.DrawRectangle works fine.

### Steps to Reproduce

1) Create a custom GraphicsView control
2) Set the Drawable to a new class
3) At runtime the x,y,width,height are converted to a Single and fails with values out of range
4) In the Drawable class change the call to DrawRectangle and it works fine

This is the class i'm using

```C#
internal class DrawCountryLand : IDrawable
{
    public void Draw(ICanvas canvas, RectF dirtyRect)
    {
        canvas.StrokeColor = Color.FromArgb("9f8700FF");
        canvas.StrokeSize = 6;
        canvas.FillRectangle(1f, 1f, 50f, 50f);
        
    }
}
```

Markup:

```XAML
<GraphicsView xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="COE.Controls.CountryControl"
              AbsoluteLayout.LayoutFlags="None"
              AbsoluteLayout.LayoutBounds="1,1, 2500, 2500"
       
              BackgroundColor="Beige"
              HorizontalOptions="FillAndExpand"
              VerticalOptions="FillAndExpand"
              >
            
</GraphicsView>
```

Code behind:
  ```C#
public CountryControl()
	{
InitializeComponent();
      Drawable = new DrawCountryLand();
	}
```

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.1.16299.15

### Did you find any workaround?

No, I also tried .net 7 and it fails.

### Relevant log output

```shell
'COE.exe' (CoreCLR: DefaultDomain): Loaded 'D:\Repos\COE\src\COE\COE\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\System.Private.CoreLib.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'COE.exe' (CoreCLR: clrhost): Loaded 'D:\Repos\COE\src\COE\COE\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\COE.dll'. Symbols loaded.
'COE.exe' (CoreCLR: clrhost): Loaded 'D:\Repos\COE\src\COE\COE\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\System.Runtime.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'COE.exe' (CoreCLR: clrhost): Loaded 'D:\Repos\COE\src\COE\COE\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\WinRT.Runtime.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'COE.exe' (CoreCLR: clrhost): Loaded 'D:\Repos\COE\src\COE\COE\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\System.Runtime.InteropServices.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'COE.exe' (CoreCLR: clrhost): Loaded 'D:\Repos\COE\src\COE\COE\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\System.Collections.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'COE.exe' (CoreCLR: clrhost): Loaded 'D:\Repos\COE\src\COE\COE\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\System.Collections.Concurrent.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'COE.exe' (CoreCLR: clrhost): Loaded 'D:\Repos\COE\src\COE\COE\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\System.Threading.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'COE.exe' (CoreCLR: clrhost): Loaded 'D:\Repos\COE\src\COE\COE\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\Microsoft.WinUI.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'COE.exe' (CoreCLR: clrhost): Loaded 'D:\Repos\COE\src\COE\COE\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\System.Runtime.CompilerServices.Unsafe.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'COE.exe' (CoreCLR: clrhost): Loaded 'D:\Repos\COE\src\COE\COE\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\System.Private.Uri.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'COE.exe' (CoreCLR: clrhost): Loaded 'D:\Repos\COE\src\COE\COE\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\System.ObjectModel.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'COE.exe' (CoreCLR: clrhost): Loaded 'D:\Repos\COE\src\COE\COE\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\System.ComponentModel.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'COE.exe' (CoreCLR: clrhost): Loaded 'D:\Repos\COE\src\COE\COE\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\System.Numerics.Vectors.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'COE.exe' (CoreCLR: clrhost): Loaded 'D:\Repos\COE\src\COE\COE\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\Microsoft.Windows.SDK.NET.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'COE.exe' (CoreCLR: clrhost): Loaded 'D:\Repos\COE\src\COE\COE\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\System.Security.Cryptography.Algorithms.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'COE.exe' (CoreCLR: clrhost): Loaded 'D:\Repos\COE\src\COE\COE\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\System.Security.Cryptography.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'COE.exe' (CoreCLR: clrhost): Loaded 'D:\Repos\COE\src\COE\COE\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\System.Linq.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'COE.exe' (CoreCLR: clrhost): Loaded 'D:\Repos\COE\src\COE\COE\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\System.Memory.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'COE.exe' (CoreCLR: clrhost): Loaded 'D:\Repos\COE\src\COE\COE\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\Microsoft.InteractiveExperiences.Projection.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'COE.exe' (CoreCLR: clrhost): Loaded 'D:\Repos\COE\src\COE\COE\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\Microsoft.Maui.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'COE.exe' (CoreCLR: clrhost): Loaded 'D:\Repos\COE\src\COE\COE\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\Microsoft.Windows.ApplicationModel.WindowsAppRuntime.Projection.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'COE.exe' (CoreCLR: clrhost): Loaded 'D:\Repos\COE\src\COE\COE\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\Microsoft.Maui.Controls.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'COE.exe' (CoreCLR: clrhost): Loaded 'D:\Repos\COE\src\COE\COE\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\Microsoft.Extensions.DependencyInjection.Abstractions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'COE.exe' (CoreCLR: clrhost): Loaded 'D:\Repos\COE\src\COE\COE\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\Microsoft.Maui.Essentials.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'COE.exe' (CoreCLR: clrhost): Loaded 'D:\Repos\COE\src\COE\COE\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\Microsoft.Maui.Controls.Xaml.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'COE.exe' (CoreCLR: clrhost): Loaded 'D:\Repos\COE\src\COE\COE\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\Microsoft.Extensions.Logging.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'COE.exe' (CoreCLR: clrhost): Loaded 'D:\Repos\COE\src\COE\COE\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\Microsoft.Extensions.Logging.Debug.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'COE.exe' (CoreCLR: clrhost): Loaded 'D:\Repos\COE\src\COE\COE\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\Microsoft.Extensions.Configuration.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'COE.exe' (CoreCLR: clrhost): Loaded 'D:\Repos\COE\src\COE\COE\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\Microsoft.Extensions.Configuration.Abstractions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'COE.exe' (CoreCLR: clrhost): Loaded 'D:\Repos\COE\src\COE\COE\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\Microsoft.Extensions.Primitives.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'COE.exe' (CoreCLR: clrhost): Loaded 'D:\Repos\COE\src\COE\COE\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\System.Xml.ReaderWriter.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'COE.exe' (CoreCLR: clrhost): Loaded 'D:\Repos\COE\src\COE\COE\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\System.Private.Xml.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'COE.exe' (CoreCLR: clrhost): Loaded 'D:\Repos\COE\src\COE\COE\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\Microsoft.Maui.Graphics.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'COE.exe' (CoreCLR: clrhost): Loaded 'D:\Repos\COE\src\COE\COE\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\System.Net.Primitives.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'COE.exe' (CoreCLR: clrhost): Loaded 'D:\Repos\COE\src\COE\COE\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\Microsoft.Extensions.Logging.Abstractions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'COE.exe' (CoreCLR: clrhost): Loaded 'D:\Repos\COE\src\COE\COE\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\System.ComponentModel.TypeConverter.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'COE.exe' (CoreCLR: clrhost): Loaded 'D:\Repos\COE\src\COE\COE\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\Microsoft.Maui.Graphics.Win2D.WinUI.Desktop.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'COE.exe' (CoreCLR: clrhost): Loaded 'D:\Repos\COE\src\COE\COE\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\Microsoft.Extensions.Options.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'COE.exe' (CoreCLR: clrhost): Loaded 'D:\Repos\COE\src\COE\COE\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\Microsoft.Extensions.DependencyInjection.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'COE.exe' (CoreCLR: clrhost): Loaded 'D:\Repos\COE\src\COE\COE\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\System.Diagnostics.Tracing.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'COE.exe' (CoreCLR: clrhost): Loaded 'D:\Repos\COE\src\COE\COE\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\System.Threading.ThreadPool.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'COE.exe' (CoreCLR: clrhost): Loaded 'D:\Repos\COE\src\COE\COE\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\System.Linq.Expressions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'COE.exe' (CoreCLR: clrhost): Loaded 'D:\Repos\COE\src\COE\COE\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\System.Reflection.Emit.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'COE.exe' (CoreCLR: clrhost): Loaded 'Snippets'. 
'COE.exe' (CoreCLR: clrhost): Loaded 'D:\Repos\COE\src\COE\COE\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\Microsoft.Maui.Controls.Compatibility.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'COE.exe' (CoreCLR: clrhost): Loaded 'D:\Repos\COE\src\COE\COE\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\System.Reflection.Emit.Lightweight.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'COE.exe' (CoreCLR: clrhost): Loaded 'D:\Repos\COE\src\COE\COE\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\System.Reflection.Emit.ILGeneration.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'COE.exe' (CoreCLR: clrhost): Loaded 'D:\Repos\COE\src\COE\COE\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\System.Reflection.Primitives.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'COE.exe' (CoreCLR: clrhost): Loaded 'D:\Repos\COE\src\COE\COE\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\System.Runtime.Loader.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'COE.exe' (CoreCLR: clrhost): Loaded 'D:\Repos\COE\src\COE\COE\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\System.Drawing.Primitives.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'COE.exe' (CoreCLR: clrhost): Loaded 'D:\Repos\COE\src\COE\COE\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\Microsoft.Graphics.Canvas.Interop.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Exception thrown: 'System.ArgumentException' in WinRT.Runtime.dll
WinRT information: Element not found.

An exception of type 'System.ArgumentException' occurred in WinRT.Runtime.dll but was not handled in user code
WinRT information: Element not found.

Value does not fall within the expected range.

'COE.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\PrivateAssemblies\Runtime\Microsoft.VisualStudio.Debugger.Runtime.NetCoreApp.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'COE.exe' (CoreCLR: clrhost): Loaded 'D:\Repos\COE\src\COE\COE\bin\Debug\net7.0-windows10.0.19041.0\win10-x64\AppX\netstandard.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
The program '[48812] COE.exe' has exited with code 4294967295 (0xffffffff).

StackTrace
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Microsoft.Graphics.Canvas.ICanvasDrawingSessionMethods.FillRectangle(IObjectReference _obj, Single x, Single y, Single w, Single h, ICanvasBrush brush)
   at Microsoft.Graphics.Canvas.CanvasDrawingSession.FillRectangle(Single x, Single y, Single w, Single h, ICanvasBrush brush)
   at Microsoft.Maui.Graphics.Win2D.W2DCanvas.<>c__DisplayClass53_0.<FillRectangle>b__0(CanvasDrawingSession s)
   at Microsoft.Maui.Graphics.Win2D.W2DCanvas.Draw(Action`1 drawingAction)
   at Microsoft.Maui.Graphics.Win2D.W2DCanvas.FillRectangle(Single x, Single y, Single width, Single height)
   at COE.DrawingComponents.DrawCountryLand.Draw(ICanvas canvas, RectF dirtyRect) in D:\Repos\COE\src\COE\COE\DrawingComponents\DrawCountryLand.cs:line 17
   at Microsoft.Maui.Graphics.Win2D.W2DGraphicsView.OnDraw(CanvasControl sender, CanvasDrawEventArgs args)
   at WinRT._EventSource_global__Windows_Foundation_TypedEventHandler_global__Microsoft_Graphics_Canvas_UI_Xaml_CanvasControl__global__Microsoft_Graphics_Canvas_UI_Xaml_CanvasDrawEventArgs_.EventState.<GetEventInvoke>b__1_0(CanvasControl sender, CanvasDrawEventArgs args)
   at ABI.Windows.Foundation.TypedEventHandler`2.Do_Abi_Invoke[TSenderAbi,TResultAbi](Void* thisPtr, TSenderAbi sender, TResultAbi args)
```

**Comment by PureWeen** [comment]
Can you test with the latest nightly build? 
https://github.com/dotnet/maui/wiki/Nightly-Builds

**Comment by nick5454** [comment]
> Can you test with the latest nightly build? https://github.com/dotnet/maui/wiki/Nightly-Builds

Sure, when I get off work tonight I will
