### ISSUE TITLE
[Windows] Controls.sample project crashes

### ISSUE THREAD

**Issue by MartyIX** [dotnet/maui#21324]
### Description

An exception in `src/Controls/samples/Controls.Sample` is thrown when the project is started.

### Steps to Reproduce

Following https://github.com/dotnet/maui/blob/main/.github/DEVELOPMENT.md#building-the-build-tasks, I did:

```powershell
dotnet tool restore
dotnet build ./Microsoft.Maui.BuildTasks.slnf
```

and then run `src/Controls/samples/Controls.Sample` in my MSVS and there is an exception thrown here https://github.com/dotnet/maui/blob/64deb0f4bd407023f99f353a39c6c6e6dbd24c97/src/Core/src/MauiContext.cs#L72.

Screenshot of the exception:

![image](https://github.com/dotnet/maui/assets/203266/b3c32f55-7047-4e43-ab54-553545f2e616)

Stacktrace:

```
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.ValidateResolution(ServiceCallSite callSite, IServiceScope scope, IServiceScope rootScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.OnResolve(ServiceCallSite callSite, IServiceScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Maui.MauiContext.WrappedServiceProvider.GetService(Type serviceType) in D:\maui\src\Core\src\MauiContext.cs:line 72
   at Microsoft.Maui.MauiContext.WrappedServiceProvider.GetService(Type serviceType) in D:\maui\src\Core\src\MauiContext.cs:line 72
   at Xamarin.HotReload.ServiceProvider.GetService[T](IServiceProvider provider)
   at Microsoft.Maui.Controls.HotReload.Forms.MauiHelpers.GetDispatcher(IElementHandler handler)
   at Microsoft.XamlHotReload.VisualTreeService.VisualTree.ApplicationWrapper.get_Dispatcher()
   at Microsoft.XamlHotReload.VisualTreeService.VisualTree.VisualTreeContextBase.GetDispatcherContext(IDispatcher dispatcher)
   at Microsoft.XamlHotReload.VisualTreeService.VisualTree.FormsVisualTreeContext.<>c__DisplayClass12_0.<SubscribeToVisualTreeChanges>b__0()
   at Microsoft.XamlHotReload.Utility.DispatcherExtensions.<>c__DisplayClass3_0.<InvokeAsync>b__0()
   at Microsoft.XamlHotReload.Utility.DispatcherExtensions.<>c__DisplayClass4_0`1.<InvokeAsync>b__1()
```

### Version with bug

Nightly / CI build (64deb0f4bd407023f99f353a39c6c6e6dbd24c97)

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

**Comment by drasticactions** [comment]
That's because of this: https://github.com/dotnet/maui/issues/21081

The Sample app enables Scope Validation for the service container, which breaks Hot Reload which calls for it to get the Dispatcher. This has been fixed internally in Visual Studio and should role out for the next preview. It's not a MAUI bug.
