### ISSUE TITLE
Unable to use Process.Start() in Mac Catalyst Universal application in Release configuration

### ISSUE THREAD

**Issue by Bodkens** [dotnet/maui#21378]
### Description

I have Mac Catalyst application that needs run another app with. I do this with `Process.Start()` It works fine in Debug mode, but when i do `dotnet publish` it does not work in Universal build of Release config. It return me this error below. I turned off sandbox mode. Is there another way and more correct way to start applications in Mac?

<img width="1031" alt="Снимок экрана 2024-03-22 в 01 06 18" src="https://github.com/dotnet/maui/assets/59771705/8e8b2d48-ac46-44aa-9124-9e94c3b3ceca">

My workload 

Installed Workload Id      Manifest Version      Installation Source
maui-maccatalyst           8.0.7/8.0.100         SDK 8.0.100        
maui-ios                   8.0.7/8.0.100         SDK 8.0.100        
maui-android               8.0.7/8.0.100         SDK 8.0.100        
maui                       8.0.7/8.0.100         SDK 8.0.100        

### Steps to Reproduce

1) Create example MAUI App
2) In Platform/Entitlements.plist set com.apple.security.app-sandbox to false
3) Edit MAUI example app to start another app, for example Weather(Weather can crush if we start it that way but main point that it detects and runs weather app)
```
public partial class MainPage : ContentPage
{
	int count = 0;

	public MainPage()
	{
		InitializeComponent();
	}

	private void OnCounterClicked(object sender, EventArgs e)
	{
		count++;
		try{
			Process.Start("/System/Applications/Weather.app/Contents/MacOS/Weather");
		}
		catch(Exception ex){
			this.DisplayAlert("Error", ex.Message, "Ok"); 
		}
```
4) Run and see that it works in debug
5) Create release configuration by `dotnet publish -f net8.0-maccatalyst -c Release -p:CreatePackage=false`
6) Run bin/Release/net8.0-maccatalyst and see that it returns Attempting to JIT compile method 'void System.Runtime.Serialization.SerializationGuard:<ThrowIfDeserializationInProgress>g__ThrowIfDeserializationInProgress|0_0 (System.Runtime.Serialization.SerializationInfo,string,int&)' while running in aot-only mode. See https://docs.microsoft.com/xamarin/ios/internals/limitations for more information.

### Version with bug

8.0.7 SR2

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

7.0.100

### Affected platforms

macOS

**Comment by drasticactions** [comment]
First, this is unrelated to the MAUI UI Framework; this involves the [SDK ](https://github.com/xamarin/xamarin-macios) and the runtime. If you reenable the Mono Interpreter (Edit your csproj, add `<UseInterpreter>true</UseInterpreter>') then it should allow that to start, but I'm not sure if `Process.Start` is meant to work in an AOT usecase. @rolfbjarne what do you think?

**Comment by Bodkens** [comment]
@drasticactions it crashes in case of `<UseInterpreter>true</UseInterpreter>` in Universal Release configuration

**Comment by rolfbjarne** [comment]
I can reproduce, this is the stack trace:

```
System.ExecutionEngineException: Attempting to JIT compile method 'void System.Runtime.Serialization.SerializationGuard:<ThrowIfDeserializationInProgress>g__ThrowIfDeserializationInProgress|0_0 (System.Runtime.Serialization.SerializationInfo,string,int&)' while running in aot-only mode. See https://docs.microsoft.com/xamarin/ios/internals/limitations for more information.

   at System.Runtime.Serialization.SerializationGuard.ThrowIfDeserializationInProgress(String , Int32& )
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo )
   at System.Diagnostics.Process.Start(String )
   at maui.MainPage.OnCounterClicked(Object sender, EventArgs e)
```

IMHO `Process.Start` should work with the AOT compiler, but that said it doesn't surprise me all that much that it doesn't, because `Process.Start` hasn't been available on platforms where the AOT compiler has existed (`Process.Start` doesn't work on iOS).

In any case, moving to dotnet/runtime, since that's where this should be fixed.
