### ISSUE TITLE
[IOS] KeyboardAutoScrollManager NullReferenceException when focussing Editor/Entry in modal bottom sheet

### ISSUE THREAD

**Issue by Axemasta** [dotnet/maui#21726]
### Description

When using [[The49.Maui.BottomSheet](https://github.com/the49ltd/The49.Maui.BottomSheet)](https://github.com/the49ltd/The49.Maui.BottomSheet) to display a `BottomSheet`, I have discovered a crash on iOS that is happening within the [`KeyboardAutoScrollManager.AdjustPosition`](https://github.com/dotnet/maui/blob/b183cae2982f7c318f796d202f5c811d4da0edd8/src/Core/src/Platform/iOS/KeyboardAutoManagerScroll.cs#L299) method.

![modal-crashing-bottomsheet](https://github.com/dotnet/maui/assets/33064621/a9c0ff7d-969a-439d-8881-0b0eea6ce672)

I understand this is caused by working with an external library, however a `NullReferenceException` being thrown internally by Maui clearly indicates an issue that could affect peoples apps in the wild.

### Steps to Reproduce

This issue only occurs when the page calling the `BottomSheet` is itself a modal page. If there is only 1 page on the navigation stack the controls work correctly & no crash.

- Add a page to the modal stack
- From that page display a bottom sheet
- On that bottom sheet add an `Editor`/`Entry`
- Focus the control

Expected:
The control is focussed, keyboard displayed and you can enter text

Actual:
The following crash happens:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Maui.Platform.KeyboardAutoManagerScroll.AdjustPosition()
   at Microsoft.Maui.Platform.KeyboardAutoManagerScroll.AdjustPositionDebounce()
   at Microsoft.Maui.Platform.KeyboardAutoManagerScroll.DidUITextBeginEditing(NSNotification notification)
   at ObjCRuntime.Runtime.ThrowException(IntPtr gchandle) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/Runtime.cs:line 2594
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 60
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 94
   at KeyboardAutoScrollRepro.Program.Main(String[] args) in /Users/axemasta/Documents/Dev/Projects/Maui/KeyboardAutoScrollRepro/KeyboardAutoScrollRepro/Platforms/iOS/Program.cs:line 13
2024-04-09 14:25:19.623589+0100 KeyboardAutoScrollRepro[88641:22091147] Unhandled managed exception: Object reference not set to an instance of an object. (System.NullReferenceException)
   at Microsoft.Maui.Platform.KeyboardAutoManagerScroll.AdjustPosition()
   at Microsoft.Maui.Platform.KeyboardAutoManagerScroll.AdjustPositionDebounce()
   at Microsoft.Maui.Platform.KeyboardAutoManagerScroll.DidUITextBeginEditing(NSNotification notification)
   at ObjCRuntime.Runtime.ThrowException(IntPtr gchandle) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/Runtime.cs:line 2594
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 60
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 94
   at KeyboardAutoScrollRepro.Program.Main(String[] args) in /Users/axemasta/Documents/Dev/Projects/Maui/KeyboardAutoScrollRepro/KeyboardAutoScrollRepro/Platforms/iOS/Program.cs:line 13
```

### Link to public reproduction project repository

https://github.com/Axemasta/KeyboardAutoScrollRepro

### Version with bug

8.0.14 SR3.1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 17.2

### Did you find any workaround?

This works when the presenting page is not modal:
![non-modal-working-bottomsheet](https://github.com/dotnet/maui/assets/33064621/77fa0724-a968-4a6b-b388-40237331f68c)

In this example I have set the `Application.MainPage` to the page responsible for showing the dialogs. As you can see the dialogs appear and the textfields can be interacted with.

**Comment by Larhei** [comment]
Coud be because of [this change](https://github.com/dotnet/maui/commit/e109469e9e5ee32f52dd2ef4e158858d14383b45#diff-2250dbb3cc715c7202da3d0ac1ae6d6764d7662bf8609a53e4be557ab5aeefa0).
the usage of view is not checked for null in this class even if declared as static UIView? View;

**Comment by Larhei** [comment]
Looked a bit deeper into this. In case of SearchHandler ContainerView.Window is null
resulting in a nullpointer when doing
`var intersectRect = CGRect.Intersect(KeyboardFrame, window.Frame);`

In outr Usecase we have a Shell with Tabs. On Tab Contains a Searchhandler, when navigating awaiy from tab to the other while Keyboard is showing and then navigating back to this tab the exception get triggered. Looks like it happens when focus is still in SearchHandler
![image](https://github.com/dotnet/maui/assets/47631685/e7721a4f-c326-4482-9a23-809bbcc96886)

**Comment by jaosnz-rep** [comment]
Can repro this issue at iOS platform on the MauiVersion(8.0.7 & 8.0.14).
