### ISSUE TITLE
The "XamlCTask" task failed unexpectedly.

### ISSUE THREAD

**Issue by Alex-Dobrynin** [dotnet/maui#21910]
### Description

If i have datatemplate and the root of it is customview like local:SomeCustomRootViewOfTheDataTemplate and if i have there some bindings using x:Bind from CompiledBindings.Maui nuget package I get next error during the build. If i change x:Bind to Binding it just successfully builds the app.

![image](https://github.com/dotnet/maui/assets/23138430/95f19dca-c29e-4b71-a509-0b8981f095a2)

[DataTemplateWithCustomRootView.zip](https://github.com/dotnet/maui/files/15024273/DataTemplateWithCustomRootView.zip)

this is really critical, as cannot be workarounded

### Steps to Reproduce

1. Try to build provided test project

### Version with bug

8.0.20 SR4

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Did you find any workaround?

nope

### Relevant log output

```shell
1>d:\Nuget\packages\microsoft.maui.controls.build.tasks\8.0.40-nightly.10515\buildTransitive\netstandard2.0\Microsoft.Maui.Controls.targets(158,3): error MSB4018: The "XamlCTask" task failed unexpectedly.
1>d:\Nuget\packages\microsoft.maui.controls.build.tasks\8.0.40-nightly.10515\buildTransitive\netstandard2.0\Microsoft.Maui.Controls.targets(158,3): error MSB4018: System.Xml.XmlException: 'tViewCell' is an unexpected token. Expecting white space. Line 103, position 117.
1>d:\Nuget\packages\microsoft.maui.controls.build.tasks\8.0.40-nightly.10515\buildTransitive\netstandard2.0\Microsoft.Maui.Controls.targets(158,3): error MSB4018:    at System.Xml.XmlTextReaderImpl.Throw(Exception e)
1>d:\Nuget\packages\microsoft.maui.controls.build.tasks\8.0.40-nightly.10515\buildTransitive\netstandard2.0\Microsoft.Maui.Controls.targets(158,3): error MSB4018:    at System.Xml.XmlTextReaderImpl.ParseAttributes()
1>d:\Nuget\packages\microsoft.maui.controls.build.tasks\8.0.40-nightly.10515\buildTransitive\netstandard2.0\Microsoft.Maui.Controls.targets(158,3): error MSB4018:    at System.Xml.XmlTextReaderImpl.ParseElement()
1>d:\Nuget\packages\microsoft.maui.controls.build.tasks\8.0.40-nightly.10515\buildTransitive\netstandard2.0\Microsoft.Maui.Controls.targets(158,3): error MSB4018:    at System.Xml.XmlTextReaderImpl.ParseElementContent()
1>d:\Nuget\packages\microsoft.maui.controls.build.tasks\8.0.40-nightly.10515\buildTransitive\netstandard2.0\Microsoft.Maui.Controls.targets(158,3): error MSB4018:    at Microsoft.Maui.Controls.Xaml.XamlParser.ParseXamlElementFor(IElementNode node, XmlReader reader) in D:\a\_work\1\s\src\Controls\src\Xaml\XamlParser.cs:line 61
1>d:\Nuget\packages\microsoft.maui.controls.build.tasks\8.0.40-nightly.10515\buildTransitive\netstandard2.0\Microsoft.Maui.Controls.targets(158,3): error MSB4018:    at Microsoft.Maui.Controls.Xaml.XamlParser.ReadNode(XmlReader reader, Boolean nested) in D:\a\_work\1\s\src\Controls\src\Xaml\XamlParser.cs:line 174
1>d:\Nuget\packages\microsoft.maui.controls.build.tasks\8.0.40-nightly.10515\buildTransitive\netstandard2.0\Microsoft.Maui.Controls.targets(158,3): error MSB4018:    at Microsoft.Maui.Controls.Xaml.XamlParser.ParseXamlElementFor(IElementNode node, XmlReader reader) in D:\a\_work\1\s\src\Controls\src\Xaml\XamlParser.cs:line 85
1>d:\Nuget\packages\microsoft.maui.controls.build.tasks\8.0.40-nightly.10515\buildTransitive\netstandard2.0\Microsoft.Maui.Controls.targets(158,3): error MSB4018:    at Microsoft.Maui.Controls.Xaml.XamlParser.ReadNode(XmlReader reader, Boolean nested) in D:\a\_work\1\s\src\Controls\src\Xaml\XamlParser.cs:line 174
1>d:\Nuget\packages\microsoft.maui.controls.build.tasks\8.0.40-nightly.10515\buildTransitive\netstandard2.0\Microsoft.Maui.Controls.targets(158,3): error MSB4018:    at Microsoft.Maui.Controls.Xaml.XamlParser.ParseXamlElementFor(IElementNode node, XmlReader reader) in D:\a\_work\1\s\src\Controls\src\Xaml\XamlParser.cs:line 114
1>d:\Nuget\packages\microsoft.maui.controls.build.tasks\8.0.40-nightly.10515\buildTransitive\netstandard2.0\Microsoft.Maui.Controls.targets(158,3): error MSB4018:    at Microsoft.Maui.Controls.Xaml.XamlParser.ReadNode(XmlReader reader, Boolean nested) in D:\a\_work\1\s\src\Controls\src\Xaml\XamlParser.cs:line 174
1>d:\Nuget\packages\microsoft.maui.controls.build.tasks\8.0.40-nightly.10515\buildTransitive\netstandard2.0\Microsoft.Maui.Controls.targets(158,3): error MSB4018:    at Microsoft.Maui.Controls.Xaml.XamlParser.ParseXamlElementFor(IElementNode node, XmlReader reader) in D:\a\_work\1\s\src\Controls\src\Xaml\XamlParser.cs:line 114
1>d:\Nuget\packages\microsoft.maui.controls.build.tasks\8.0.40-nightly.10515\buildTransitive\netstandard2.0\Microsoft.Maui.Controls.targets(158,3): error MSB4018:    at Microsoft.Maui.Controls.Xaml.XamlParser.ParseXaml(RootNode rootNode, XmlReader reader) in D:\a\_work\1\s\src\Controls\src\Xaml\XamlParser.cs:line 49
1>d:\Nuget\packages\microsoft.maui.controls.build.tasks\8.0.40-nightly.10515\buildTransitive\netstandard2.0\Microsoft.Maui.Controls.targets(158,3): error MSB4018:    at Microsoft.Maui.Controls.Build.Tasks.XamlTask.ParseXaml(Stream stream, TypeReference typeReference) in D:\a\_work\1\s\src\Controls\src\Build.Tasks\XamlTask.cs:line 59
1>d:\Nuget\packages\microsoft.maui.controls.build.tasks\8.0.40-nightly.10515\buildTransitive\netstandard2.0\Microsoft.Maui.Controls.targets(158,3): error MSB4018:    at Microsoft.Maui.Controls.Build.Tasks.XamlCTask.Execute(IList`1& thrownExceptions) in D:\a\_work\1\s\src\Controls\src\Build.Tasks\XamlCTask.cs:line 124
1>d:\Nuget\packages\microsoft.maui.controls.build.tasks\8.0.40-nightly.10515\buildTransitive\netstandard2.0\Microsoft.Maui.Controls.targets(158,3): error MSB4018:    at Microsoft.Maui.Controls.Build.Tasks.XamlTask.Execute() in D:\a\_work\1\s\src\Controls\src\Build.Tasks\XamlTask.cs:line 38
1>d:\Nuget\packages\microsoft.maui.controls.build.tasks\8.0.40-nightly.10515\buildTransitive\netstandard2.0\Microsoft.Maui.Controls.targets(158,3): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
1>d:\Nuget\packages\microsoft.maui.controls.build.tasks\8.0.40-nightly.10515\buildTransitive\netstandard2.0\Microsoft.Maui.Controls.targets(158,3): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
1>Done building project "***.csproj" -- FAILED.
```

**Comment by ninachen03** [comment]
Verified this issue with Visual Studio 17.10.0 Preview 4 (8.0.14 & 8.0.20).I can repro this issue.
![image](https://github.com/dotnet/maui/assets/128687574/986f0dda-bb9b-4827-9700-5bbd2c609e40)
