### ISSUE TITLE
[iOS] Error The Internet connection appears to be offline.

### ISSUE THREAD

**Issue by czuck** [dotnet/maui#21952]
### Description

This error has been reported but those reports have been closed and this is an issue in 8.0.20 but I can also recreate it with 8.0.14.
When my app is not previously installed on my phone, I consistently get this error when calling HttpClient.SendAsync(_requestMessage_).  I will do a full rebuild and debug and repeat that process until the request is successfully returned.  Once it works, it continues to work until I delete the app from the phone, at which point the issue reappears.  It happens with both Debug and Release builds.  I have tested doing a rebuild, if works (for the first time), I delete the app from the phone, re-deploy the same build and test and it does not work.  

{System.Net.Http.HttpRequestException: The Internet connection appears to be offline.
 ---> Foundation.NSErrorException: Error Domain=NSURLErrorDomain Code=-1009 "The Internet connection appears to be offline." UserInfo={_kCFStreamErrorCodeKey=50, NSUnderlyingError=0x3026e07e0 {Error Domain=kCFErrorDomainCFNetwork Code=-1009 "(null)" UserInfo={_NSURLErrorNWPathKey=unsatisfied (Local network prohibited), interface: en0[802.11], ipv4, uses wifi, _kCFStreamErrorCodeKey=50, _kCFStreamErrorDomainKey=1}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <4B22EF41-B5E1-4278-8A9B-DE62658BEFB6>.<7>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <4B22EF41-B5E1-4278-8A9B-DE62658BEFB6>.<7>"
), NSLocalizedDescription=The Internet connection appears to be offline., NSErrorFailingURLStringKey=http://192.168.x.xx/m/d/ApiSettings/GetApiVersionInfo, NSErrorFailingURLKey=http://192.168.x.xx/m/d/ApiSettings/GetApiVersionInfo, _kCFStreamErrorDomainKey=1}
   --- End of inner exception stack trace ---
   at System.Net.Http.NSUrlSessionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/Foundation/NSUrlSessionHandler.cs:line 544
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at JMoApp.Utilities.HttpUtilities.<GetResponseAsync>d__6`1[[JMoApp.Models.ApiVersionInfo, JMoApp, Version=2024.1.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext() in C:\Code\My App \Utilities\HttpUtilities.cs:line 180}

### Version with bug

8.0.20 SR4

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

17.4.1

### Did you find any workaround?

keep rebuilding and debugging.

**Comment by jfversluis** [comment]
Could you please add any relevant code that you are using here? Preferably a [reproduction project](https://github.com/dotnet/maui/blob/main/.github/repro.md)?

**Comment by czuck** [comment]
Trying to narrow down the issue, it only occurs if the url I'm sending the http request to is my local machine or local hyperV instance.  I'm using ip addresses for both connections, but I can use an ip to a non-secure server on the network and do not get the issue.  I do have NSAllowsArbitraryLoads set to true.  I do have a 'try again' button that executes the exact same http request, and the second time it will often return successfully.  This is also happening during the startup of my app.

**Comment by mjanzetic** [comment]
Hi, I'm not the OP but basically facing the same issue.
I've written a little sample project which can be found [here](https://github.com/mjanzetic/MauiRestClient/).
It's a REST API client which also uses HttpClient.SendAsync(requestMessage) to send a request to a URL of your choice.

I've tested this both on Android and iOS with physical devices.
On Android (10) my request is successful and answered with 204 Not Content (as expected):
![Android](https://github.com/dotnet/maui/assets/32412323/65f5de6c-178d-4b4d-b0f7-1a2b818666a1)

On iOS (17.4.1) the same request is failing with the same error as OP's:
![iOS](https://github.com/dotnet/maui/assets/32412323/fd2ee2af-9533-48f5-9ac5-6c34f441b7c7)

**Comment by mjanzetic** [comment]
I forgot to mention that my REST server runs on an internal network without any access to the Internet.
Maybe this helps.
