### ISSUE TITLE
Java.Lang.IllegalArgumentException: 'No view found for id

### ISSUE THREAD

**Issue by HhnitroInfo** [dotnet/maui#21975]
### Description

When ever I try to navigate from a Content page to a tabedpage the following exeption is trown 

Java.Lang.IllegalArgumentException: 'No view found for id 0x7f08014f (com.companyname.versatilfv:id/navigationlayout_toptabs) for fragment ViewFragment{f970177} (9dbae45c-56d5-4ded-af57-b9604f736f56 id=0x7f08014f)'

Error occurs on both 

Navigation.PushAsync(new AppCreateOrEditPedidos());
await Shell.Current.GoToAsync(nameof(AppPedidos));

but wierdly only on android, on windows works like a charm

### Version with bug

8.0.20 SR4

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

pixel 7 pro emulator, android 13 API 34

### Relevant log output

```shell
[AndroidRuntime] Shutting down VM
[AndroidRuntime] FATAL EXCEPTION: main
[AndroidRuntime] Process: com.companyname.versatilfv, PID: 23127
[AndroidRuntime] java.lang.IllegalArgumentException: No view found for id 0x7f08014f (com.companyname.versatilfv:id/navigationlayout_toptabs) for fragment ViewFragment{3f03e13} (d2ae77e8-f545-4213-9da0-b25ff4b8d0b6 id=0x7f08014f)
[AndroidRuntime] 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:547)
[AndroidRuntime] 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:272)
[AndroidRuntime] 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1943)
[AndroidRuntime] 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1845)
[AndroidRuntime] 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1782)
[AndroidRuntime] 	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:565)
[AndroidRuntime] 	at android.os.Handler.handleCallback(Handler.java:958)
[AndroidRuntime] 	at android.os.Handler.dispatchMessage(Handler.java:99)
[AndroidRuntime] 	at android.os.Looper.loopOnce(Looper.java:205)
[AndroidRuntime] 	at android.os.Looper.loop(Looper.java:294)
[AndroidRuntime] 	at android.app.ActivityThread.main(ActivityThread.java:8177)
[AndroidRuntime] 	at java.lang.reflect.Method.invoke(Native Method)
[AndroidRuntime] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
[AndroidRuntime] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
**Java.Lang.IllegalArgumentException:** 'No view found for id 0x7f08014f (com.companyname.versatilfv:id/navigationlayout_toptabs) for fragment ViewFragment{3f03e13} (d2ae77e8-f545-4213-9da0-b25ff4b8d0b6 id=0x7f08014f)'
```

**Comment by HhnitroInfo** [comment]
Closing the issue due to the inconsistenci in witch the bug occours, mooving to anotther method of utilizing maui
