### ISSUE TITLE
Android crash at startup with System.ArgumentNullException: ArgumentNull_Generic Arg_ParamName_Name, services on MauiApplication

### ISSUE THREAD

**Issue by DmitryNikiforovCoherent** [dotnet/maui#21973]
### Description

Can't reproduce, but see multiple analytics crashes on startup. It seems, during OnApplicationCreating event IPlatformApplication.Current.Services set to null(althought it filled before)

```
Microsoft.Maui.MauiContext..ctor(IServiceProvider services)
Microsoft.Maui.MauiContext..ctor(IServiceProvider services, Context context)
Microsoft.Maui.Controls.Compatibility.Hosting.AppHostBuilderExtensions.<>c.<OnConfigureLifeCycle>b__1_0(Application app)
Microsoft.Maui.MauiApplication.<OnCreate>b__2_0(OnApplicationCreating del)
Microsoft.Maui.LifecycleEvents.LifecycleEventServiceExtensions.InvokeLifecycleEvents[OnApplicationCreating](IServiceProvider services, Action`1 action)
Microsoft.Maui.MauiApplication.OnCreate()
PF.Forms.PlanetFitnessApplication.OnCreate()
Android.App.Application.n_OnCreate(IntPtr jnienv, IntPtr native__this)
```

### Steps to Reproduce

Appears immediately after launch(or, maybe, after app restart)

### Version with bug

8.0.20 SR4

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12-Android 14

### Did you find any workaround?

No

### Relevant log output

```shell
Have only stacktrace
Microsoft.Maui.MauiContext..ctor(IServiceProvider services)
Microsoft.Maui.MauiContext..ctor(IServiceProvider services, Context context)
Microsoft.Maui.Controls.Compatibility.Hosting.AppHostBuilderExtensions.<>c.<OnConfigureLifeCycle>b__1_0(Application app)
Microsoft.Maui.MauiApplication.<OnCreate>b__2_0(OnApplicationCreating del)
Microsoft.Maui.LifecycleEvents.LifecycleEventServiceExtensions.InvokeLifecycleEvents[OnApplicationCreating](IServiceProvider services, Action`1 action)
Microsoft.Maui.MauiApplication.OnCreate()
PF.Forms.PlanetFitnessApplication.OnCreate()
Android.App.Application.n_OnCreate(IntPtr jnienv, IntPtr native__this)
Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(_JniMarshal_PP_V callback, IntPtr jnienv, IntPtr klazz)
```

**Comment by jsuarezruiz** [comment]
Do you have more detailed logs?, are you using `ConfigureLifecycleEvents` on your MauiProgram?, could share more details?

**Comment by DmitryNikiforovCoherent** [comment]
> Do you have more detailed logs?, are you using `ConfigureLifecycleEvents` on your MauiProgram?, could share more details?

No, don't have any specific overrides. On MauiApplication only OnCreate and CreateMauiApp overridden,
MauiApp created with builder
`var builder = MauiApp.CreateBuilder();
        builder
            .UseMauiApp<App>()
            .UseSkiaSharp()
            .UseMauiCompatibility()
            .UseFFImageLoading()
            // For mysterious reasons without this the app crashes
            .ConfigureEffects(_ => {})
            .UseMauiCommunityToolkit()
            .UseCardsView()
            .UseBarcodeScanning()
            .UseBundleSettingsIfAvailable()
            .ConfigureMauiHandlers
...
builder.Services
            .AddSingleton 
...
var app = builder.Build();
        Dependencies.ServiceProvider = app.Services;
        return app;
`

**Comment by PureWeen** [comment]
Can you attach a logcat file with your crash?
https://learn.microsoft.com/en-us/xamarin/android/deploy-test/debugging/android-debug-log?tabs=windows

**Comment by PavloLukianets** [comment]
@PureWeen a while ago we also discovered that for some mysterious reasons ours **CompanyNameApplication.OnCreate()** gets triggered after some time when we close the app (by swiping up from recents). Hence, then the app goes and builds the App() .ctor, and we had some init logic there, so we had some crashes and moved that logic to **WindowCreated**. We didn't see this behavior on XF. I most likely think this may be the cause for this crash as well, since it's a silent one. It crashes when we don't have an Activity and no crash popup is displayed for a user

**Comment by PureWeen** [comment]
@PavloLukianets Can you set the launchmode on the android activity to single top?

**Comment by DmitryNikiforovCoherent** [comment]
> @PavloLukianets Can you set the launchmode on the android activity to single top?

@PureWeen  We've already have launchmode set to single task, so should work well with this

**Comment by PavloLukianets** [comment]
@PureWeen we cleaned up the logs, and are ready to present them for you, here you are: 
[MauiContext .ctor crash logs.txt](https://github.com/dotnet/maui/files/15160700/MauiContext.ctor.crash.logs.txt)

**Comment by PavloLukianets** [comment]
cc: @MichaelFrenkel

**Comment by PureWeen** [comment]
Not sure what would cause this on only some devices

Maybe there's an architecture you aren't publishing?

@jonathanpeppers @jonpryor  ?


```

2024-04-29 11:41:36.561 21831-21831 monodroid-assembly      com.companyname.MobileApp           W  open_from_bundles: failed to load assembly System.Net.Primitives.dll

2024-04-29 11:41:36.567 21831-21831 AppCenterXamarinCrashes com.companyname.MobileApp           E  Unhandled Exception from source=AndroidEnvironment
                                                                                                    System.BadImageFormatException: Method has zero rva
                                                                                                    File name: 'FFImageLoading.Maui'
                                                                                                       at Forms.MauiProgram.CreateMauiApp()
                                                                                                       at Forms.companynameApplication.CreateMauiApp()
                                                                                                       at Microsoft.Maui.MauiApplication.OnCreate()
                                                                                                       at Forms.companynameApplication.OnCreate()
                                                                                                       at Android.App.Application.n_OnCreate(IntPtr jnienv, IntPtr native__this)
                                                                                                       at 
```

**Comment by Manish-Pradhan-FP** [comment]
I see the same issue in Google Crashlytics. All the crashes seem to be happening in the Background.

Fatal Exception: android.runtime.JavaProxyThrowable: [System.ArgumentNullException]: ArgumentNull_Generic Arg_ParamName_Name, services
       at Microsoft.Maui.MauiContext..ctor()
       at Microsoft.Maui.MauiContext..ctor()
       at Microsoft.Maui.Controls.Compatibility.Hosting.AppHostBuilderExtensions+<>c.<OnConfigureLifeCycle>b__1_0()
       at Microsoft.Maui.MauiApplication.<OnCreate>b__2_0()
       at Microsoft.Maui.LifecycleEvents.LifecycleEventServiceExtensions.InvokeLifecycleEvents()
       at Microsoft.Maui.MauiApplication.OnCreate()
       at Android.App.Application.n_OnCreate()
       at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V()
       at crc6488302ad6e9e4df1a.MauiApplication.n_onCreate(MauiApplication.java)
       at crc6488302ad6e9e4df1a.MauiApplication.onCreate(MauiApplication.java:28)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1316)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7711)
       at android.app.ActivityThread.-$$Nest$mhandleBindApplication()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2478)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:230)
       at android.os.Looper.loop(Looper.java:319)
       at android.app.ActivityThread.main(ActivityThread.java:8919)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

Potential Causes:
Passing a null value to the services parameter of the Microsoft.Maui.MauiContext constructor.
The services parameter is not properly initialized or configured.

**Comment by jonathanpeppers** [comment]
Is there a case Android calls `Android.App.Application.OnCreate()` but doesn't create an `Activity`? Perhaps MAUI crashes in that case?

Xamarin.Forms didn't have a custom `Android.App.Application` unless a developer set one up themselves. So you wouldn't see the same problem there.

**Comment by MichaelFrenkel** [comment]
> Not sure what would cause this on only some devices
> 
> Maybe there's an architecture you aren't publishing?
> 
> @jonathanpeppers @jonpryor ?
> 
> ```
> 
> 2024-04-29 11:41:36.561 21831-21831 monodroid-assembly      com.companyname.MobileApp           W  open_from_bundles: failed to load assembly System.Net.Primitives.dll
> 
> 2024-04-29 11:41:36.567 21831-21831 AppCenterXamarinCrashes com.companyname.MobileApp           E  Unhandled Exception from source=AndroidEnvironment
>                                                                                                     System.BadImageFormatException: Method has zero rva
>                                                                                                     File name: 'FFImageLoading.Maui'
>                                                                                                        at Forms.MauiProgram.CreateMauiApp()
>                                                                                                        at Forms.companynameApplication.CreateMauiApp()
>                                                                                                        at Microsoft.Maui.MauiApplication.OnCreate()
>                                                                                                        at Forms.companynameApplication.OnCreate()
>                                                                                                        at Android.App.Application.n_OnCreate(IntPtr jnienv, IntPtr native__this)
>                                                                                                        at 
> ```

I don't think this is the case.
___

> Is there a case Android calls Android.App.Application.OnCreate() but doesn't create an Activity? Perhaps MAUI crashes in that case?

yeap, when the app is created by a background service, we've checked this case, no crashes here.

We reproduced the crash on our side, there are the steps:

- open an app
- move to the background
- open after 2 days

it crashes on first launch, if you open the app again, works as expected.
Still not clear for me what exactly happening here, still invetigating.

P.S. we checked the case (open after 2 days) on default MAUI sample app, no crashes. Maybe the issue on our side, not sure yet

**Comment by MichaelFrenkel** [comment]
@Manish-Pradhan-FP we also thought it was only happening in the background and not noticeable to a user, but our QA has reproduced the crash
if you have any thoughts/additional info would be glad to hear

**Comment by PavloLukianets** [comment]
@PureWeen @jonathanpeppers 
https://github.com/dotnet/maui/blob/5451aaf16b4fc4621a61885219c858efc3cd2bf6/src/Core/src/Platform/Android/MauiApplication.cs#L44
Is there any specific reason why there is no null check here, but later in a couple of lines there is a null check?
https://github.com/dotnet/maui/blob/5451aaf16b4fc4621a61885219c858efc3cd2bf6/src/Core/src/Platform/Android/MauiApplication.cs#L50

**Comment by PavloLukianets** [comment]
@MichaelFrenkel maybe let's create a pr to MAUI with adding a null check there and grab a custom MAUI build from Azure and send it to our QA just to see how the app will behave if we do it

**Comment by jonathanpeppers** [comment]
What is the code inside `at Forms.MauiProgram.CreateMauiApp()`? Inside `FFImageLoading.Maui.dll`?

Usually this error means that the class library is using a method that changed, etc. IL is invalid in some way:
```
System.BadImageFormatException: Method has zero rva
File name: 'FFImageLoading.Maui'
```
Is this from a NuGet package, can you share the version? I can open it in ILSpy to look.

**Comment by Manish-Pradhan-FP** [comment]
> @Manish-Pradhan-FP we also thought it was only happening in the background and not noticeable to a user, but our QA has reproduced the crash if you have any thoughts/additional info would be glad to hear

@MichaelFrenkel After reading @jonathanpeppers comment above, I searched if the we were calling OnCreate anywhere. I did manage to find it in the MainApplication.cs. We use the Map Plugin which seems to need this piece of code to avoid running into some other issues

`builder.ConfigureLifecycleEvents(lifecycle =>
{
    lifecycle.AddAndroid(android =>
    {
        android.OnCreate((activity, bundle) =>
        {
            CustomMapHandler.CustomBundle = bundle;
        });
    });
});`

We have now removed this piece of code and moved in into the main OnCreate method. The plan is to push these changes out today and see if the issue gets resolved. We havent been able to figure out much else other than this.

**Comment by jonathanpeppers** [comment]
Ok, so there are multiple issues in discussion here. `ConfigureLifecycleEvents()` seems completely different to the `BadImageFormatException`.

**Comment by PavloLukianets** [comment]
> What is the code inside `at Forms.MauiProgram.CreateMauiApp()`? Inside `FFImageLoading.Maui.dll`?
> 
> Usually this error means that the class library is using a method that changed, etc. IL is invalid in some way:
> 
> ```
> System.BadImageFormatException: Method has zero rva
> File name: 'FFImageLoading.Maui'
> ```
> 
> Is this from a NuGet package, can you share the version? I can open it in ILSpy to look.

here is the repo, we are calling UseFFImageLoading(): https://github.com/microspaze/FFImageLoading.Maui/blob/main/source/FFImageLoading.Maui/HostingExtensions.cs

**Comment by PavloLukianets** [comment]
> Ok, so there are multiple issues in discussion here. `ConfigureLifecycleEvents()` seems completely different to the `BadImageFormatException`.
 Yeah, that was the guess from @PureWeen, but we with @MichaelFrenkel think we have a problem not in FFimageLoading

**Comment by PavloLukianets** [comment]
@PureWeen @jfversluis can someone start the builds for us please? https://github.com/dotnet/maui/pull/22911 We want to see what happens to the app if we add this null check

**Comment by mattleibow** [comment]
Looking at the issue, this is happening in the Compatibility code: https://github.com/dotnet/maui/blob/a3c872dfbf6101a3fdaf449f0c09899774593b21/src/Compatibility/Core/src/AppHostBuilderExtensions.Android.cs#L22-L23

**Comment by mattleibow** [comment]
An app without services is a really broken app and noting will actually launch. 

In fact, this error is really weird because:

```
var mauiApp = CreateMauiApp();
var rootContext = new MauiContext(mauiApp.Services, this);
var applicationContext = rootContext.MakeApplicationScope(this);

_services = applicationContext.Services;

_services.InvokeLifecycleEvents<AndroidLifecycle.OnApplicationCreating>(del => del(this));
```

The `CreateMauiApp` should _always_ create a new services instance. This is where you are registering your app services.

But, this still gets more weird. The constructor of MauiApplication is setting `IPlatformApplication.Current = this` and by the time this event is fired, the services are set so `IPlatformApplication.Current.Services` should not be null.

So, at the point of firing this event, the app is created, Current = this and we are USING the services to fire the event. So, this is very strange.

One thing that comes to mind is that there is more than one app and somehow Current is being set to an old app where the services are set to null or something.

**Comment by Manish-Pradhan-FP** [comment]
No luck. The App still crashes randomly even after I removed the 1 place where I was calling OnCreate manually. This issue is causing us a lot of grief, bunch of bad reviews on the store already related to crashing. Is there any updates on this?

`          Fatal Exception: android.runtime.JavaProxyThrowable: [System.ArgumentNullException]: ArgumentNull_Generic Arg_ParamName_Name, services
       at Microsoft.Maui.MauiContext..ctor()
       at Microsoft.Maui.MauiContext..ctor()
       at Microsoft.Maui.Controls.Compatibility.Hosting.AppHostBuilderExtensions+<>c.<OnConfigureLifeCycle>b__1_0()
       at Microsoft.Maui.MauiApplication.<OnCreate>b__2_0()
       at Microsoft.Maui.LifecycleEvents.LifecycleEventServiceExtensions.InvokeLifecycleEvents()
       at Microsoft.Maui.MauiApplication.OnCreate()
       at Android.App.Application.n_OnCreate()
       at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V()
       at crc6488302ad6e9e4df1a.MauiApplication.n_onCreate(MauiApplication.java)
       at crc6488302ad6e9e4df1a.MauiApplication.onCreate(MauiApplication.java:28)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1335)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7581)
       at android.app.ActivityThread.-$$Nest$mhandleBindApplication()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2419)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:257)
       at android.os.Looper.loop(Looper.java:368)
       at android.app.ActivityThread.main(ActivityThread.java:8826)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
        `

**Comment by MichaelFrenkel** [comment]
@Manish-Pradhan-FP we've not figured out yet but one of our assumption is that `UseMauiCompatibility` - cause of the crash. Do you have this line in your code?

**Comment by Manish-Pradhan-FP** [comment]
@MichaelFrenkel We do not. @mattleibow @jonathanpeppers  @PureWeen Any updates on this?

**Comment by PavloLukianets** [comment]
> We do not

@Manish-Pradhan-FP while u don't have this line explicitly, this line may be in one of your nuget packages that you are using. Check those as well

**Comment by MichaelFrenkel** [comment]
we finally released an app without `UseMauiCompatibility`. `Fatal Exception: android.runtime.JavaProxyThrowable: [System.ArgumentNullException]: ArgumentNull_Generic Arg_ParamName_Name, services at Microsoft.Maui.MauiContext..ctor()` is gone

**Comment by sk1llsh0t** [comment]
Any update on this issue? We are seeing ArgumentNull_Generic Arg_ParamName_Name, services exception as well.
