### ISSUE TITLE
ListView shows two items on one line and crashes when clicking (windows)

### ISSUE THREAD

**Issue by adegeo** [dotnet/maui#21981]
### Description

The ListView control bound with a data set seems to create repeat the first item in the collection under the second. When that item is clicked, an unhandled exception is raised:

> This collection cannot work with indices larger than Int32.MaxValue - 1 (0x7FFFFFFF - 1). (Parameter 'index')

**Stack trace**
```
   at ABI.System.Collections.IList.ToAbiHelper.EnsureIndexInt32(UInt32 index, Int32 listCapacity)
   at ABI.System.Collections.IList.ToAbiHelper.GetAt(UInt32 index)
   at ABI.System.Collections.IList.Vftbl.Do_Abi_GetAt_0(IntPtr thisPtr, UInt32 index, IntPtr* result)
```

**Versions tested**
- VS 17.9.6
- VS 17.10.0 Preview 4

The project seems to work usually on the first run, or after you delete the bin/obj folders. Any other run after that causes the error to happen. However, I've noticed it happens on and off. I can run 3 times no corrupted list, then the next 4 times are the error, then it's back to working, etc.

<img width="200" alt="image" src="https://github.com/dotnet/maui/assets/67293991/7fee18c4-94ae-4600-82ce-2e4d53678620">

Here's a video of it in action

https://github.com/dotnet/maui/assets/67293991/f8736010-22e5-49a9-844b-bc2b8399016e

### Steps to Reproduce

```xaml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:vm="clr-namespace:MovieCatalog.ViewModels"
             xmlns:local="clr-namespace:MovieCatalog"
             x:Class="MovieCatalog.Views.MoviesListPage"
             x:DataType="vm:MovieListViewModel"
             Title="Movies"
             BindingContext="{x:Static local:App.MainViewModel}">
    <Grid Margin="10">
        <ListView ItemsSource="{Binding Movies}" ItemTapped="ListView_ItemTapped">
            <ListView.ItemTemplate>
                <DataTemplate>
                    <TextCell Text="{Binding Title}" x:DataType="vm:MovieViewModel">
                        <TextCell.ContextActions>
                            <MenuItem Text="Delete" IsDestructive="True" />
                        </TextCell.ContextActions>
                    </TextCell>
                </DataTemplate>
            </ListView.ItemTemplate>
        </ListView>
    </Grid>
</ContentPage>
```

### Link to public reproduction project repository

https://github.com/adegeo/mauibugs_1

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 11 23H2 22631.3447

### Did you find any workaround?

No

**Comment by kevinxufei** [comment]
Verified this issue with Visual Studio 17.10.0 Preview 4/17.9.6(8.0.20&8.0.3), Deploying to windows machine multiple times, can not repro this issue.

**Comment by adegeo** [comment]
Is there something I should do to try and get logs? I can repo this constantly. Also, half the time deploying windows I just get a blank window with no content, the same color as the title bar. That bug has been happening for at least a year.

**Comment by jfversluis** [comment]
ListView is deprecated for .NET 10, so we probably won't be working on this anymore. Please migrate to CollectionView and help us make that the solid approach for this. Thanks!
