### ISSUE TITLE
[Windows] Connectivity.ConnectivityChanged Exception

### ISSUE THREAD

**Issue by baaaaif** [dotnet/maui#21990]
### Description

Following up on 
https://github.com/dotnet/maui/pull/19261
and
https://github.com/dotnet/maui/pull/20757

i got a strange new exception.
Case is similar to https://github.com/dotnet/maui/issues/20690
Windows went to hibernate and lost company vpn connection.

I'm on Windows 11
![image](https://github.com/dotnet/maui/assets/703251/858baa8f-9f45-4125-a71e-7246d996bb9b)

and got this exception
```
UNHANDELED EXCEPTION IN audius.dashface.App:
Message:Aufruf wurde durch Messagefilter abgebrochen. (0x80010002 (RPC_E_CALL_CANCELED))
Stack:   at Microsoft.Maui.Networking.ConnectivityNativeHelper.INetworkListManager.GetNetworks(NLM_ENUM_NETWORK flags)
   at Microsoft.Maui.Networking.ConnectivityImplementation.get_NetworkAccess()
   at Microsoft.Maui.Networking.ConnectivityImplementation.SetCurrent()
   at Microsoft.Maui.Networking.ConnectivityImplementation.OnConnectivityChanged(ConnectivityChangedEventArgs e)
   at Microsoft.Maui.Networking.ConnectivityImplementation.OnConnectivityChanged(NetworkAccess access, IEnumerable`1 profiles)
   at Microsoft.Maui.Networking.ConnectivityImplementation.OnConnectivityChanged()
   at Microsoft.Maui.Networking.ConnectivityImplementation.NetworkStatusChanged(Object sender)
   at WinRT._EventSource_global__Windows_Networking_Connectivity_NetworkStatusChangedEventHandler.EventState.<GetEventInvoke>b__1_0(Object sender)
   at ABI.Windows.Networking.Connectivity.NetworkStatusChangedEventHandler.Do_Abi_Invoke(IntPtr thisPtr, IntPtr sender)
Inner Ex.:
```

this pointed out a second issue
https://github.com/dotnet/maui/blob/3f9472b637caed938f12df8947163421c6bae978/src/Essentials/src/Connectivity/Connectivity.uwp.cs#L24
`if (OperatingSystem.IsWindowsVersionAtLeast(11))`
is always false, because this OSVersion for Windows 11 is still 10

cc: @Foda 

### Version with bug

Nightly / CI build (Please specify exact version)

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 11, Build 22631. Maui 8.0.40-nightly.10539

**Comment by Foda** [comment]
Doh... because of course it's not 11. Good catch, thank you.
