### ISSUE TITLE
The UI element <Frame> causes a crash

### ISSUE THREAD

**Issue by ESO-ST** [dotnet/maui#22011]
### Description

When we have a Frame that contains a WebView, it causes a crash; tested with Mopups and MAUI's toolkit popup, the same crash takes place.

```
<?xml version="1.0" encoding="utf-8" ?>
<mopups:PopupPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
                  xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
                  xmlns:mopups="clr-namespace:Mopups.Pages;assembly=Mopups"
                  x:Class="WebViewCrashMidLoad.PopupPage2"
                  CloseWhenBackgroundIsClicked="false">

  <mopups:PopupPage.Content>

    <Frame>
      <VerticalStackLayout>
        <ScrollView>
          <VerticalStackLayout>
            <!--Title-->
            <HorizontalStackLayout>
              <Label Text="Name"
                     FontAttributes="Bold" />
              <Label Text="Event Time" />
            </HorizontalStackLayout>
            <WebView Source="dummy.pdf"
                     HeightRequest="650"
                     HorizontalOptions="FillAndExpand" />

            <!--Comments-->
            <Label x:Name="CommentsLabel"
                   FontAttributes="Bold" />
            <Label Text="Comments" />
          </VerticalStackLayout>
        </ScrollView>
        <!--Close Button-->
        <Button x:Name="CloseButton"
                Margin="20,20,20,20"
                Clicked="OnCloseClicked"
                VerticalOptions="End"
                HorizontalOptions="End" />
      </VerticalStackLayout>
    </Frame>

  </mopups:PopupPage.Content>

</mopups:PopupPage>
```

Here's the crash output

```
14:26:03:900	Unhandled Exception:
14:26:03:900	ObjCRuntime.ObjCException: Objective-C exception thrown.  Name: CALayerInvalidGeometry Reason: CALayer position contains NaN: [0 nan]. Layer: <CALayer:0x60000086d120; position = CGPoint (0 0); bounds = CGRect (0 0; 0 0); delegate = <Microsoft_Maui_Platform_MauiWKWebView: 0x1139a2000; frame = (0 0; 0 0); backgroundColor = UIExtendedGrayColorSpace 0 0; layer = <CALayer: 0x60000086d120>>; sublayers = (<CALayer: 0x600000870d60>); allowsGroupOpacity = YES; backgroundColor = <CGColor 0x600002148280> [<CGColorSpace 0x6000027c2580> (kCGColorSpaceICCBased; kCGColorSpaceModelMonochrome; Generic Gray Gamma 2.2 Profile; extended range)] ( 0 0 )>
14:26:03:900	Native stack trace:
14:26:03:900		0   CoreFoundation                      0x0000000180491128 __exceptionPreprocess + 172
14:26:03:900		1   libobjc.A.dylib                     0x000000018008412c objc_exception_throw + 56
14:26:03:900		2   CoreFoundation                      0x0000000180491038 -[NSException initWithCoder:] + 0
14:26:03:900		3   
14:26:03:901	QuartzCore                          0x0000000189fedd1c -[CALayer setPosition:] + 364
14:26:03:901		4   UIKitCore                           0x0000000184e35a84 -[UIView _backing_setPosition:] + 172
14:26:03:901		5   UIKitCore                           0x00000001857e8ccc -[UIView setCenter:] + 208
14:26:03:901		6   libxamarin-dotnet-debug.dylib       0x00000001066c0c9c xamarin_dyn_objc_msgSendSuper + 164
14:26:03:901		7   WebViewCrashMidLoad                 0x0000000104ff995c interp_to_native_trampoline + 156
14:26:03:901		8   libmonosgen-2.0.dylib               0x000000010723b58c ves_pinvoke_method + 584
14:26:03:901		9   libmonosgen-2.0.dylib               0x000000010722fd14 mono_interp_exec_method + 3000
14:26:03:901		10  libmonosgen-2.0.dylib               0x000000010722d810 interp_runtime_invoke + 244
14:26:03:901		11  libmonosgen-2.0.dylib               0x0000000107146a74 mono_jit_runtime_invoke + 1116
14:26:03:901		12  libmonosgen-2.0.dylib               0x00000001073019ac mono_runtime_invoke_checked + 148
14:26:03:901		13  libmonosgen-2.0.dylib               0x0000000107305a70 mono_runtime_invoke + 544
14:26:03:901		14  libxamarin-dotnet-debug.
14:26:03:901	dylib       0x00000001066b7d84 xamarin_invoke_trampoline + 5376
14:26:03:901		15  libxamarin-dotnet-debug.dylib       0x00000001066bfc80 xamarin_arch_trampoline + 148
14:26:03:901		16  libxamarin-dotnet-debug.dylib       0x00000001066c0a60 xamarin_arm64_common_trampoline + 64
14:26:03:901		17  UIKitCore                           0x0000000185806d78 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 1492
14:26:03:901		18  QuartzCore                          0x0000000189ffa5b0 _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 440
14:26:03:901		19  QuartzCore                          0x000000018a005368 _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 124
14:26:03:901		20  QuartzCore                          0x0000000189f20520 _ZN2CA7Context18commit_transactionEPNS_11TransactionEdPd + 460
14:26:03:901		21  QuartzCore                          0x0000000189f4fcc0 _ZN2CA11Transaction6commitEv + 652
14:26:03:901		22  QuartzCore                          0x0000000189f51194 _ZN2CA11Transaction25flush_as_runloop_observerEb + 68
14:26:03:901		23  CoreFoundation                      0x00000001803f0ec4 __CFRUNLOOP_IS_CALL
14:26:03:901	ING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 32
14:26:03:901		24  CoreFoundation                      0x00000001803eb8c8 __CFRunLoopDoObservers + 528
14:26:03:901		25  CoreFoundation                      0x00000001803ebd80 __CFRunLoopRun + 968
14:26:03:901		26  CoreFoundation                      0x00000001803eb5a4 CFRunLoopRunSpecific + 572
14:26:03:901		27  GraphicsServices                    0x000000018e9fbae4 GSEventRunModal + 160
14:26:03:901		28  UIKitCore                           0x00000001852f02e4 -[UIApplication _run] + 868
14:26:03:901		29  UIKitCore                           0x00000001852f3f5c UIApplicationMain + 124
14:26:03:901		30  libxamarin-dotnet-debug.dylib       0x000000010667bf44 xamarin_UIApplicationMain + 60
14:26:03:901		31  libmonosgen-2.0.dylib               0x000000010723c950 do_icall + 316
14:26:03:901		32  libmonosgen-2.0.dylib               0x000000010723b1f0 do_icall_wrapper + 356
14:26:03:901		33  libmonosgen-2.0.dylib               0x000000010722fc3c mono_interp_exec_method + 2784
14:26:03:901		34  libmonosgen-2.0.dylib               0x000000010722d810 interp_runtime_invoke + 244
14:26:03:901		35  libmonosgen-2.0.dylib           
14:26:03:901	    0x0000000107146a74 mono_jit_runtime_invoke + 1116
14:26:03:901		36  libmonosgen-2.0.dylib               0x00000001073019ac mono_runtime_invoke_checked + 148
14:26:03:901		37  libmonosgen-2.0.dylib               0x0000000107308f8c mono_runtime_exec_main_checked + 116
14:26:03:901		38  libmonosgen-2.0.dylib               0x000000010719ad3c mono_jit_exec + 364
14:26:03:901		39  libxamarin-dotnet-debug.dylib       0x00000001066bfb00 xamarin_main + 2320
14:26:03:901		40  WebViewCrashMidLoad                 0x00000001050dab44 main + 72
14:26:03:901		41  dyld                                0x0000000105645544 start_sim + 20
14:26:03:901		42  ???                                 0x00000001058160e0 0x0 + 4387332320
14:26:03:901		43  ???                                 0xfe4d000000000000 0x0 + 18324302458840416256
14:26:03:901	
14:26:03:901	   at UIKit.UIView.set_Center(CGPoint value) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/build/dotnet/ios/generated-sources/UIKit/UIView.g.cs:line 3158
14:26:03:901	   at Microsoft.Maui.ViewHandlerExtensions.PlatformArrangeHandler(IViewHandler viewHandler, Rect rect)
14:26:03:901	   at Microsoft.Maui.Handlers.ViewHandler`2[[M
14:26:03:902	icrosoft.Maui.IWebView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[WebKit.WKWebView, Microsoft.iOS, Version=17.2.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065]].PlatformArrange(Rect rect)
14:26:03:902	   at Microsoft.Maui.Controls.VisualElement.ArrangeOverride(Rect bounds)
14:26:03:902	   at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IView.Arrange(Rect bounds)
14:26:03:902	   at Microsoft.Maui.Layouts.VerticalStackLayoutManager.ArrangeChildren(Rect bounds)
14:26:03:902	   at Microsoft.Maui.Controls.Layout.CrossPlatformArrange(Rect bounds)
14:26:03:902	   at Microsoft.Maui.Platform.MauiView.CrossPlatformArrange(Rect bounds)
14:26:03:902	   at Microsoft.Maui.Platform.MauiView.LayoutSubviews()
14:26:03:902	   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 58
14:26:03:902	   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIA
14:26:03:902	pplication.cs:line 94
14:26:03:902	   at WebViewCrashMidLoad.Program.Main(String[] args) in C:\Users\name\source\repos\WebViewCrashMidLoad\WebViewCrashMidLoad\Platforms\iOS\Program.cs:line 13
14:26:03:902	Native stack trace:
14:26:03:902		0   CoreFoundation                      0x0000000180491128 __exceptionPreprocess + 172
14:26:03:902		1   libobjc.A.dylib                     0x000000018008412c objc_exception_throw + 56
14:26:03:902		2   CoreFoundation                      0x0000000180491038 -[NSException initWithCoder:] + 0
14:26:03:902		3   QuartzCore                          0x0000000189fedd1c -[CALayer setPosition:] + 364
14:26:03:902		4   UIKitCore                           0x0000000184e35a84 -[UIView _backing_setPosition:] + 172
14:26:03:902		5   UIKitCore                           0x00000001857e8ccc -[UIView setCenter:] + 208
14:26:03:902		6   libxamarin-dotnet-debug.dylib       0x00000001066c0c9c xamarin_dyn_objc_msgSendSuper + 164
14:26:03:902		7   WebViewCrashMidLoad                 0x0000000104ff995c interp_to_native_trampoline + 156
14:26:03:902		8   libmonosgen-2.0.dylib               0x000000010723b58c ves_pinvoke_method + 584
14:26:03:902		9   l
14:26:03:902	ibmonosgen-2.0.dylib               0x000000010722fd14 mono_interp_exec_method + 3000
14:26:03:902		10  libmonosgen-2.0.dylib               0x000000010722d810 interp_runtime_invoke + 244
14:26:03:902		11  libmonosgen-2.0.dylib               0x0000000107146a74 mono_jit_runtime_invoke + 1116
14:26:03:902		12  libmonosgen-2.0.dylib               0x00000001073019ac mono_runtime_invoke_checked + 148
14:26:03:902		13  libmonosgen-2.0.dylib               0x0000000107305a70 mono_runtime_invoke + 544
14:26:03:902		14  libxamarin-dotnet-debug.dylib       0x00000001066b7d84 xamarin_invoke_trampoline + 5376
14:26:03:902		15  libxamarin-dotnet-debug.dylib       0x00000001066bfc80 xamarin_arch_trampoline + 148
14:26:03:902		16  libxamarin-dotnet-debug.dylib       0x00000001066c0a60 xamarin_arm64_common_trampoline + 64
14:26:03:902		17  UIKitCore                           0x0000000185806d78 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 1492
14:26:03:902		18  QuartzCore                          0x0000000189ffa5b0 _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 440
14:26:03:902		19  QuartzCore                          0x000000018a005368 _ZN2CA
14:26:03:902	5Layer28layout_and_display_if_neededEPNS_11TransactionE + 124
14:26:03:902		20  QuartzCore                          0x0000000189f20520 _ZN2CA7Context18commit_transactionEPNS_11TransactionEdPd + 460
14:26:03:902		21  QuartzCore                          0x0000000189f4fcc0 _ZN2CA11Transaction6commitEv + 652
14:26:03:902		22  QuartzCore                          0x0000000189f51194 _ZN2CA11Transaction25flush_as_runloop_observerEb + 68
14:26:03:902		23  CoreFoundation                      0x00000001803f0ec4 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 32
14:26:03:902		24  CoreFoundation                      0x00000001803eb8c8 __CFRunLoopDoObservers + 528
14:26:03:902		25  CoreFoundation                      0x00000001803ebd80 __CFRunLoopRun + 968
14:26:03:902		26  CoreFoundation                      0x00000001803eb5a4 CFRunLoopRunSpecific + 572
14:26:03:902		27  GraphicsServices                    0x000000018e9fbae4 GSEventRunModal + 160
14:26:03:902		28  UIKitCore                           0x00000001852f02e4 -[UIApplication _run] + 868
14:26:03:902		29  UIKitCore                           0x00000001852f3f5c UIApplicationMai
14:26:03:902	n + 124
14:26:03:902		30  libxamarin-dotnet-debug.dylib       0x000000010667bf44 xamarin_UIApplicationMain + 60
14:26:03:902		31  libmonosgen-2.0.dylib               0x000000010723c950 do_icall + 316
14:26:03:902		32  libmonosgen-2.0.dylib               0x000000010723b1f0 do_icall_wrapper + 356
14:26:03:902		33  libmonosgen-2.0.dylib               0x000000010722fc3c mono_interp_exec_method + 2784
14:26:03:902		34  libmonosgen-2.0.dylib               0x000000010722d810 interp_runtime_invoke + 244
14:26:03:902		35  libmonosgen-2.0.dylib               0x0000000107146a74 mono_jit_runtime_invoke + 1116
14:26:03:902		36  libmonosgen-2.0.dylib               0x00000001073019ac mono_runtime_invoke_checked + 148
14:26:03:902		37  libmonosgen-2.0.dylib               0x0000000107308f8c mono_runtime_exec_main_checked + 116
14:26:03:902		38  libmonosgen-2.0.dylib               0x000000010719ad3c mono_jit_exec + 364
14:26:03:902		39  libxamarin-dotnet-debug.dylib       0x00000001066bfb00 xamarin_main + 2320
14:26:03:902		40  WebViewCrashMidLoad                 0x00000001050dab44 main + 72
14:26:03:902		41  dyld                                0x0000000105645544 start_sim + 20
14:26:03:902		
14:26:03:903	42  ???                                 0x00000001058160e0 0x0 + 4387332320
14:26:03:903		43  ???                                 0xfe4d000000000000 0x0 + 18324302458840416256
14:26:03:903	2024-04-23 19:26:02.451790+0100 WebViewCrashMidLoad[76759:7738908] Unhandled managed exception: Objective-C exception thrown.  Name: CALayerInvalidGeometry Reason: CALayer position contains NaN: [0 nan]. Layer: <CALayer:0x60000086d120; position = CGPoint (0 0); bounds = CGRect (0 0; 0 0); delegate = <Microsoft_Maui_Platform_MauiWKWebView: 0x1139a2000; frame = (0 0; 0 0); backgroundColor = UIExtendedGrayColorSpace 0 0; layer = <CALayer: 0x60000086d120>>; sublayers = (<CALayer: 0x600000870d60>); allowsGroupOpacity = YES; backgroundColor = <CGColor 0x600002148280> [<CGColorSpace 0x6000027c2580> (kCGColorSpaceICCBased; kCGColorSpaceModelMonochrome; Generic Gray Gamma 2.2 Profile; extended range)] ( 0 0 )>
14:26:03:903	Native stack trace:
14:26:03:903		0   CoreFoundation                      0x0000000180491128 __exceptionPreprocess + 172
14:26:03:903		1   libobjc.A.dylib                     0x000000018008412c objc_exception_throw + 56
14:26:03:903		2   CoreFoundation                      0x0000000180491038 -[NSException initWithCoder:] + 0
14:26:03:903		3   QuartzCore          
14:26:03:903	                0x0000000189fedd1c -[CALayer setPosition:] + 364
14:26:03:903		4   UIKitCore                           0x0000000184e35a84 -[UIView _backing_setPosition:] + 172
14:26:03:903		5   UIKitCore                           0x00000001857e8ccc -[UIView setCenter:] + 208
14:26:03:903		6   libxamarin-dotnet-debug.dylib       0x00000001066c0c9c xamarin_dyn_objc_msgSendSuper + 164
14:26:03:903		7   WebViewCrashMidLoad                 0x0000000104ff995c interp_to_native_trampoline + 156
14:26:03:903		8   libmonosgen-2.0.dylib               0x000000010723b58c ves_pinvoke_method + 584
14:26:03:903		9   libmonosgen-2.0.dylib               0x000000010722fd14 mono_interp_exec_method + 3000
14:26:03:903		10  libmonosgen-2.0.dylib               0x000000010722d810 interp_runtime_invoke + 244
14:26:03:903		11  libmonosgen-2.0.dylib               0x0000000107146a74 mono_jit_runtime_invoke + 1116
14:26:03:903		12  libmonosgen-2.0.dylib               0x00000001073019ac mono_runtime_invoke_checked + 148
14:26:03:903		13  libmonosgen-2.0.dylib               0x0000000107305a70 mono_runtime_invoke + 544
14:26:03:903		14  libxamarin-dotnet-debug.dylib       0x000000
14:26:03:903	01066b7d84 xamarin_invoke_trampoline + 5376
14:26:03:903		15  libxamarin-dotnet-debug.dylib       0x00000001066bfc80 xamarin_arch_trampoline + 148
14:26:03:903		16  libxamarin-dotnet-debug.dylib       0x00000001066c0a60 xamarin_arm64_common_trampoline + 64
14:26:03:903		17  UIKitCore                           0x0000000185806d78 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 1492
14:26:03:903		18  QuartzCore                          0x0000000189ffa5b0 _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 440
14:26:03:903		19  QuartzCore                          0x000000018a005368 _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 124
14:26:03:903		20  QuartzCore                          0x0000000189f20520 _ZN2CA7Context18commit_transactionEPNS_11TransactionEdPd + 460
14:26:03:903		21  QuartzCore                          0x0000000189f4fcc0 _ZN2CA11Transaction6commitEv + 652
14:26:03:903		22  QuartzCore                          0x0000000189f51194 _ZN2CA11Transaction25flush_as_runloop_observerEb + 68
14:26:03:903		23  CoreFoundation                      0x00000001803f0ec4 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERV
14:26:03:903	ER_CALLBACK_FUNCTION__ + 32
14:26:03:903		24  CoreFoundation                      0x00000001803eb8c8 __CFRunLoopDoObservers + 528
14:26:03:903		25  CoreFoundation                      0x00000001803ebd80 __CFRunLoopRun + 968
14:26:03:903		26  CoreFoundation                      0x00000001803eb5a4 CFRunLoopRunSpecific + 572
14:26:03:903		27  GraphicsServices                    0x000000018e9fbae4 GSEventRunModal + 160
14:26:03:903		28  UIKitCore                           0x00000001852f02e4 -[UIApplication _run] + 868
14:26:03:903		29  UIKitCore                           0x00000001852f3f5c UIApplicationMain + 124
14:26:03:903		30  libxamarin-dotnet-debug.dylib       0x000000010667bf44 xamarin_UIApplicationMain + 60
14:26:03:903		31  libmonosgen-2.0.dylib               0x000000010723c950 do_icall + 316
14:26:03:903		32  libmonosgen-2.0.dylib               0x000000010723b1f0 do_icall_wrapper + 356
14:26:03:903		33  libmonosgen-2.0.dylib               0x000000010722fc3c mono_interp_exec_method + 2784
14:26:03:903		34  libmonosgen-2.0.dylib               0x000000010722d810 interp_runtime_invoke + 244
14:26:03:903		35  libmonosgen-2.0.dylib               0x0000000107146a
14:26:03:905	74 mono_jit_runtime_invoke + 1116
14:26:03:905		36  libmonosgen-2.0.dylib               0x00000001073019ac mono_runtime_invoke_checked + 148
14:26:03:905		37  libmonosgen-2.0.dylib               0x0000000107308f8c mono_runtime_exec_main_checked + 116
14:26:03:905		38  libmonosgen-2.0.dylib               0x000000010719ad3c mono_jit_exec + 364
14:26:03:905		39  libxamarin-dotnet-debug.dylib       0x00000001066bfb00 xamarin_main + 2320
14:26:03:905		40  WebViewCrashMidLoad                 0x00000001050dab44 main + 72
14:26:03:905		41  dyld                                0x0000000105645544 start_sim + 20
14:26:03:905		42  ???                                 0x00000001058160e0 0x0 + 4387332320
14:26:03:905		43  ???                                 0xfe4d000000000000 0x0 + 18324302458840416256
14:26:03:905	 (ObjCRuntime.ObjCException)
14:26:03:905	   at UIKit.UIView.set_Center(CGPoint value) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/build/dotnet/ios/generated-sources/UIKit/UIView.g.cs:line 3158
14:26:03:905	   at Microsoft.Maui.ViewHandlerExtensions.PlatformArrangeHandler(IViewHandler viewHandler, Rect rect)
14:26:03:905	   at Microsoft.Maui.Handlers.ViewHand
14:26:03:905	ler`2[[Microsoft.Maui.IWebView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[WebKit.WKWebView, Microsoft.iOS, Version=17.2.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065]].PlatformArrange(Rect rect)
14:26:03:905	   at Microsoft.Maui.Controls.VisualElement.ArrangeOverride(Rect bounds)
14:26:03:905	   at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IView.Arrange(Rect bounds)
14:26:03:905	   at Microsoft.Maui.Layouts.VerticalStackLayoutManager.ArrangeChildren(Rect bounds)
14:26:03:905	   at Microsoft.Maui.Controls.Layout.CrossPlatformArrange(Rect bounds)
14:26:03:905	   at Microsoft.Maui.Platform.MauiView.CrossPlatformArrange(Rect bounds)
14:26:03:905	   at Microsoft.Maui.Platform.MauiView.LayoutSubviews()
14:26:03:905	   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 58
14:26:03:905	   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/U
14:26:03:905	IKit/UIApplication.cs:line 94
14:26:03:905	   at WebViewCrashMidLoad.Program.Main(String[] args) in C:\Users\name\source\repos\WebViewCrashMidLoad\WebViewCrashMidLoad\Platforms\iOS\Program.cs:line 13
```

### Steps to Reproduce

Press the "Click me" button

### Link to public reproduction project repository

https://github.com/ESO-ST/WebViewCrashMidLoad/tree/FrameCausesCrash

### Version with bug

8.0.20 SR4

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Did you find any workaround?

none

**Comment by RoiChen001** [comment]
Can repro this issue at iOS platform on the latest 17.10 Preview 5(8.0.14&8.0.21).
![Obj](https://github.com/dotnet/maui/assets/143168639/33df605f-722c-4e73-bf03-f52731e4ac78)

**Comment by PureWeen** [comment]
@ESO-ST can you use a border?
