### ISSUE TITLE
This issue has been automatically marked as stale because it has been marked as requiring author feedback to reproduce the issue but has not had any activity for **4 days**. It will be closed if no further activity occurs **within 3 days of this comment**. If it *is* closed, feel free to comment when you are able to provide the additional information and we will re-investigate.

### ISSUE THREAD

**Issue by iSeeLittleMore** [dotnet/maui#22030]
This issue has been automatically marked as stale because it has been marked as requiring author feedback to reproduce the issue but has not had any activity for **4 days**. It will be closed if no further activity occurs **within 3 days of this comment**. If it *is* closed, feel free to comment when you are able to provide the additional information and we will re-investigate.

_Originally posted by @ghost in https://github.com/dotnet/maui/issues/15919#issuecomment-1619941642_

Problem is still there.

> System.NullReferenceException: Object reference not set to an instance of an object.
>    at Microsoft.Maui.Platform.ColorExtensions.ToPlatform(Color color)
>    at Microsoft.Maui.Platform.ColorExtensions.ToCGColor(Color color)
>    at Microsoft.Maui.Graphics.PaintExtensions.GetCAGradientLayerColors(List`1 gradientStops)
>    at Microsoft.Maui.Graphics.PaintExtensions.CreateCALayer(LinearGradientPaint linearGradientPaint, CGRect frame)
>    at Microsoft.Maui.Graphics.PaintExtensions.ToCALayer(Paint paint, CGRect frame)
>    at Microsoft.Maui.Platform.ViewExtensions.UpdateBackground(UIView platformView, Paint paint, IButtonStroke stroke)
>    at Microsoft.Maui.Platform.ViewExtensions.UpdateBackground(UIView platformView, IView view)
>    at Microsoft.Maui.Handlers.ViewHandler.MapBackground(IViewHandler handler, IView view)
>    at Microsoft.Maui.Controls.Handlers.Compatibility.VisualElementRenderer`1[[Microsoft.Maui.Controls.Frame, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetBackground(Brush brush)
>    at Microsoft.Maui.Controls.Handlers.Compatibility.VisualElementRenderer`1[[Microsoft.Maui.Controls.Frame, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MapBackground(IPlatformViewHandler handler, Frame view)
>    at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0[[Microsoft.Maui.Controls.Frame, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.IPlatformViewHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v)
>    at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IElementHandler viewHandler, IElement virtualView)
>    at Microsoft.Maui.PropertyMapper.UpdateProperty(IElementHandler viewHandler, IElement virtualView, String property)
>    at Microsoft.Maui.Controls.Handlers.Compatibility.VisualElementRenderer`1[[Microsoft.Maui.Controls.Frame, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnElementPropertyChanged(Object sender, PropertyChangedEventArgs e)
>    at Microsoft.Maui.Controls.Handlers.Compatibility.FrameRenderer.OnElementPropertyChanged(Object sender, PropertyChangedEventArgs e)
>    at Microsoft.Maui.Controls.Handlers.Compatibility.VisualElementRenderer`1[[Microsoft.Maui.Controls.Frame, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].Microsoft.Maui.IElementHandler.UpdateValue(String property)
>    at Microsoft.Maui.Controls.Element.OnPropertyChanged(String propertyName)
>    at Microsoft.Maui.Controls.VisualElement.<NotifyBackgroundChanges>b__52_0(Object sender, EventArgs e)
>    at Microsoft.Maui.Controls.VisualElement.WeakBackgroundChangedProxy.OnBackgroundChanged(Object sender, EventArgs e)
>    at Microsoft.Maui.Controls.GradientBrush.Invalidate()
>    at Microsoft.Maui.Controls.GradientBrush.OnGradientStopPropertyChanged(Object sender, PropertyChangedEventArgs e)
>    at Microsoft.Maui.Controls.BindableObject.OnPropertyChanged(String propertyName)
>    at Microsoft.Maui.Controls.Element.OnPropertyChanged(String propertyName)
>    at Microsoft.Maui.Controls.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, SetterSpecificity specificity, Boolean silent)
>    at Microsoft.Maui.Controls.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes, SetterSpecificity specificity)
>    at Microsoft.Maui.Controls.BindingExpression.ApplyCore(Object sourceObject, BindableObject target, BindableProperty property, Boolean fromTarget, SetterSpecificity specificity)
>    at Microsoft.Maui.Controls.BindingExpression.Apply(Object sourceObject, BindableObject target, BindableProperty property, SetterSpecificity specificity)
>    at Microsoft.Maui.Controls.Binding.Apply(Object context, BindableObject bindObj, BindableProperty targetProperty, Boolean fromBindingContextChanged, SetterSpecificity specificity)
>    at Microsoft.Maui.Controls.BindableObject.ApplyBindings(Boolean skipBindingContext, Boolean fromBindingContextChanged)
>    at Microsoft.Maui.Controls.BindableObject.SetInheritedBindingContext(BindableObject bindable, Object value)
>    at Microsoft.Maui.Controls.GradientBrush.OnBindingContextChanged()
>    at Microsoft.Maui.Controls.BindableObject.SetInheritedBindingContext(BindableObject bindable, Object value)
>    at Microsoft.Maui.Controls.VisualElement.PropagateBindingContextToBrush()
>    at Microsoft.Maui.Controls.VisualElement.OnBindingContextChanged()
>    at Microsoft.Maui.Controls.View.OnBindingContextChanged()
>    at Microsoft.Maui.Controls.ContentView.OnBindingContextChanged()
>    at Microsoft.Maui.Controls.BindableObject.SetInheritedBindingContext(BindableObject bindable, Object value)
>    at Microsoft.Maui.Controls.Element.SetChildInheritedBindingContext(Element child, Object context)
>    at Microsoft.Maui.Controls.Element.<OnBindingContextChanged>b__89_0(BindableObject child, Object bc)
>    at Microsoft.Maui.Controls.BindableObjectExtensions.PropagateBindingContext[Element](BindableObject self, IEnumerable`1 children, Action`2 setChildBindingContext)
>    at Microsoft.Maui.Controls.Element.OnBindingContextChanged()
>    at Microsoft.Maui.Controls.VisualElement.OnBindingContextChanged()
>    at Microsoft.Maui.Controls.View.OnBindingContextChanged()
>    at Microsoft.Maui.Controls.BindableObject.BindingContextPropertyChanged(BindableObject bindable, Object oldvalue, Object newvalue)
>    at Microsoft.Maui.Controls.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, SetterSpecificity specificity, Boolean silent)
>    at Microsoft.Maui.Controls.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes, SetterSpecificity specificity)
>    at Microsoft.Maui.Controls.BindableObject.SetValue(BindableProperty property, Object value)
>    at Microsoft.Maui.Controls.BindableObject.set_BindingContext(Object value)
>    at Microsoft.Maui.Controls.Handlers.Items.TemplatedCell.Unbind()
>    at Microsoft.Maui.Controls.Handlers.Items.TemplatedCell.PrepareForReuse()
>    at UIKit.UICollectionView.DequeueReusableCell(NSString reuseIdentifier, NSIndexPath indexPath) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/build/dotnet/ios/generated-sources/UIKit/UICollectionView.g.cs:line 234
>    at UIKit.UICollectionView.DequeueReusableCell(String reuseIdentifier, NSIndexPath indexPath) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UICollectionView.cs:line 23
>    at Microsoft.Maui.Controls.Handlers.Items.CarouselViewLoopManager.GetCellAndCorrectIndex(UICollectionView collectionView, NSIndexPath indexPath, String reuseId)
>    at Microsoft.Maui.Controls.Handlers.Items.CarouselViewController.GetCell(UICollectionView collectionView, NSIndexPath indexPath)
>    at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 58
>    at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 94
>    at DriverHelper2.Program.Main(String[] args) in /Users/mac/RiderProjects/MAUI/DriverHelper v 2.0/DriverHelper v 2.0/Platforms/iOS/Program.cs:line 13

   
```  
<Frame.Background>
    <LinearGradientBrush StartPoint="0,2" EndPoint="1,1">
        <GradientStop Color="{Binding HEX}" Offset="0.2" />
        <GradientStop Color="MistyRose" Offset="0.6" />
        <GradientStop Color="White" Offset="1" />
    </LinearGradientBrush>
</Frame.Background>
```

On android device it is work, but iOS - crush.

**Comment by drasticactions** [comment]
Reopened https://github.com/dotnet/maui/issues/15919
