### ISSUE TITLE
CollectionView crashes on iOS and MacCatalyst when new items are added and it's in a view which isn't visible

### ISSUE THREAD

**Issue by KeithBoynton** [dotnet/maui#22072]
### Description

If a CollectionView resides inside a view that is set to IsVisible="False" and the CollectionView is in a Grid with a row definition of * then it crashes on iOS and MacCatalyst when items are added to the collection.
It works fine on Windows and Android.

### Steps to Reproduce

1. Clone the attached project
2. Run the solution on iOS or MacCatalyst
3. Wait a few seconds for some items to be added to the collection
4. Observe the crash
5. Run the solution in Windows or Android and wait a few seconds
6. Observe it works
7. On the MainPage.xaml set the IsVisible to True on View2
8. Run the solution on iOS or MacCatalyst
9. Wait a few seconds and observe it working
10. Or... revert the IsVisible back to False and change the row definition in View2.xaml from * to Auto
11. Run the solution on iOS or MacCatalyst and observe it working

### Link to public reproduction project repository

https://bitbucket.org/KeithBoynton/view-not-visible-crash/src/master/

### Version with bug

8.0.21 SR4.1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Did you find any workaround?

No workaround found

**Comment by RoiChen001** [comment]
Can repro this issue at iOS platform on the latest 17.10 Preview 5(8.0.21)

**Comment by KeithBoynton** [comment]
I've updated the reproduction project repository to .net 9 with the latest MAUI controls and this issue is still present.

This is a showstopper and is blocking completion of a migration from Xamarin Forms to MAUI so I'd like to try and fix this but would greatly appreciate some guidance on where I should look as I'm not that familiar with UIKit or why the invalidation context is null (if that is the actual problem). I do know that this code used to work but I'm not sure in which version, I suspect it may have been .net 7 but I can't downgrade that far to test it.

When it crashes on iOS or MacCatalyst then the same UIKit.UICollectionView.InsertItems method raises the following `ObjCRuntime.ObjCException: Name: NSInvalidArgumentException Reason: The invalidation context ((null)) sent to -[UICollectionViewFlowLayout invalidateLayoutWithContext:] is not an instance of type UICollectionViewFlowLayoutInvalidationContext or a subclass.`

Here's the stack trace :
```
	at UIKit.UICollectionView.InsertItems(NSIndexPath[] indexPaths) in /Users/builder/azdo/_work/9/s/xamarin-macios/src/build/dotnet/ios/generated-sources/UIKit/UICollectionView.g.cs:line 553
	at Microsoft.Maui.Controls.Handlers.Items.ObservableItemsSource.<>c__DisplayClass43_0.<Add>b__0(UICollectionView c)
	at Microsoft.Maui.Controls.Handlers.Items.ObservableItemsSource.Update(Action`1 update, NotifyCollectionChangedEventArgs args)
	at Microsoft.Maui.Controls.Handlers.Items.ObservableItemsSource.Add(NotifyCollectionChangedEventArgs args)
	at Microsoft.Maui.Controls.Handlers.Items.ObservableItemsSource.CollectionChanged(NotifyCollectionChangedEventArgs args)
	at Microsoft.Maui.Controls.Handlers.Items.ObservableItemsSource.CollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
	at System.Collections.ObjectModel.ObservableCollection`1[[System.String, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].OnCollectionChanged(NotifyCollectionChangedEventArgs e)
	at MvvmHelpers.ObservableRangeCollection`1[[System.String, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].RaiseChangeNotificationEvents(NotifyCollectionChangedAction action, List`1 changedItems, Int32 startingIndex)
	at MvvmHelpers.ObservableRangeCollection`1[[System.String, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].AddRange(IEnumerable`1 collection, NotifyCollectionChangedAction notificationMode)
	at ViewNotVisibleCrash.ViewModel2.<>c__DisplayClass1_0.<AppLogic_DataLoadedEvent>b__0() in /Users/XXX/Documents/maui-issue-examples/view-not-visible-crash/ViewNotVisibleCrash/ViewModel2.cs:line 14
	at Microsoft.Maui.ApplicationModel.MainThread.<>c__DisplayClass3_0.<InvokeOnMainThreadAsync>b__0()
```

The code on line 14 which triggers the crash is: `List.AddRange(data);`

Any help to guide me in the right direction so I can investigate this would be greatfully received...

**Comment by vishnumenon2684** [comment]
The issue is not reproducible in the latest .NET MAUI version 9.0.100 on iOS 18.0 and on Mac in CV2, but it can be reproduced on Mac in CV1.

https://github.com/user-attachments/assets/98b44c26-a89e-49f9-82b9-21c9c866d286

https://github.com/user-attachments/assets/4e3c05c7-1873-4a46-bb05-0e8def694557

https://github.com/user-attachments/assets/c7b38feb-86e9-4225-b38e-a0992fc1dedb

https://github.com/user-attachments/assets/fdb426e9-95c9-4f4d-b7ab-5d9e46b576b7

**Comment by KeithBoynton** [comment]
Hi @vishnumenon2684 thank you for the heads up. I've just tried this in my app where it has been crashing (rather than the repro project). I can confirm when using 9.0.100 and the v2 handler it no longer crashes on iOS or MacCatalyst. It is maybe worth noting that it was still crashing for me on iOS with the v1 handler in addition to MacCatalyst.
