### ISSUE TITLE
Crash: Window was already deactivated

### ISSUE THREAD

**Issue by aantropov** [dotnet/maui#22406]
### Description

Hello, I develop an editor for a game engine with MAUI (net8.0, Windows, x64), while the engine is made with C++, x64, and compiled into dynamic dll. By design MAUI application runs engine process (to show the sceneview) via Interop or directly (Process.Start).

The engine process creates a TOPMOST Win32 window, sets as parent MAUI window to handle the order of rendering. The following code shows how I get Win32 handle (and laterly pass it to engine process) in MAUI/C# application:

`IntPtr handle = ((MauiWinUIWindow)App.Current.Windows[0].Handler.PlatformView).WindowHandle;`

Everything works well, except the situation, when an engine process is closed (it doesn't make sense it closed by a crash or by a formal app 'quitting'). When the child window is destroyed, the MAUI application crashes on the change of window state (for example alt+tab, or 'childing' another window) with the following stack:

_**Window was already deactivated**_
```
   _at Microsoft.Maui.Controls.Window.Microsoft.Maui.IWindow.Deactivated()
   at Microsoft.Maui.LifecycleEvents.AppHostBuilderExtensions.<>c.<OnConfigureLifeCycle>b__2_2(Window window, WindowActivatedEventArgs args)
   at Microsoft.Maui.MauiWinUIWindow.<>c__DisplayClass8_0.<OnActivated>b__1(OnActivated del)
   at Microsoft.Maui.LifecycleEvents.LifecycleEventServiceExtensions.InvokeLifecycleEvents[TDelegate](IServiceProvider services, Action`1 action)
   at Microsoft.Maui.MauiWinUIWindow.OnActivated(Object sender, WindowActivatedEventArgs args)
   at WinRT._EventSource_global__Windows_Foundation_TypedEventHandler_object__global__Microsoft_UI_Xaml_WindowActivatedEventArgs_.EventState.<GetEventInvoke>b__1_0(Object sender, WindowActivatedEventArgs args)
   at ABI.Windows.Foundation.TypedEventHandler`2.Do_Abi_Invoke[TSenderAbi,TResultAbi](Void* thisPtr, TSenderAbi sender, TResultAbi args)_
```

### Steps to Reproduce

1. Create a C++, Win32 Application, which creates Win32 window with a random window name/registered class name and sets parent passed by a command linearg.
2. Create a MAUI application which takes window handle
`IntPtr handle = ((MauiWinUIWindow)App.Current.Windows[0].Handler.PlatformView).WindowHandle;`
and then runs a secondary process, passing the handle to it.
3. Close the child (C++) window.
4. Focus MAUI application and press Alt+Tab.
5. If crash doesn't persist, run the secondary process the second time.

### Steps to Reproduce in Reproduction project repository
1. Build C++ and C# apps.
2. Run MAUI App and Click on the button.

### Link to public reproduction project repository

[_No response_](https://github.com/aantropov/maui_crash_window_was_deactivated)

### Version with bug

8.0.21 SR4.1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows SDK 10.0.19041.0

### Did you find any workaround?

No. 

### Relevant log output

```shell
_**Window was already deactivated**_

   _at Microsoft.Maui.Controls.Window.Microsoft.Maui.IWindow.Deactivated()
   at Microsoft.Maui.LifecycleEvents.AppHostBuilderExtensions.<>c.<OnConfigureLifeCycle>b__2_2(Window window, WindowActivatedEventArgs args)
   at Microsoft.Maui.MauiWinUIWindow.<>c__DisplayClass8_0.<OnActivated>b__1(OnActivated del)
   at Microsoft.Maui.LifecycleEvents.LifecycleEventServiceExtensions.InvokeLifecycleEvents[TDelegate](IServiceProvider services, Action`1 action)
   at Microsoft.Maui.MauiWinUIWindow.OnActivated(Object sender, WindowActivatedEventArgs args)
   at WinRT._EventSource_global__Windows_Foundation_TypedEventHandler_object__global__Microsoft_UI_Xaml_WindowActivatedEventArgs_.EventState.<GetEventInvoke>b__1_0(Object sender, WindowActivatedEventArgs args)
   at ABI.Windows.Foundation.TypedEventHandler`2.Do_Abi_Invoke[TSenderAbi,TResultAbi](Void* thisPtr, TSenderAbi sender, TResultAbi args)_
```

**Comment by aantropov** [comment]
@PureWeen Added repro repo: https://github.com/aantropov/maui_crash_window_was_deactivated

**Comment by RoiChen001** [comment]
Can repro this issue at Windows platform on the latest 17.10 Preview 7(8.0.40).
![8 0 40](https://github.com/dotnet/maui/assets/143168639/c068fc78-f9bb-41f6-be14-48809fd9005c)
