### ISSUE TITLE
(1)NU1301 Error in MAUI Project: Unable to Retrieve Repository Signature Information for NuGet Source (2)MAUI App Crashes on Windows After Visual Studio 17.10.0 Update: Error Code 0x80070005

### ISSUE THREAD

**Issue by parth211prajapati** [dotnet/maui#22593]
### Description

Issue Description:
(1)nuget pakage error when installing
Encountering NU1301 Error and Dependency Requirement during MAUI Project Deployment

(2)This is Show when I click on Windows Machine For start The MAUI
MAUI apps crash on launch on Windows after Visual Studio update to 17.10.0(The program '[3392] Mauived.exe' has exited with code 2147942405 (0x80070005).

Description:
When deploying a MAUI project in Visual Studio 2022, an NU1301 error occurs during package restoration. Additionally, the deployment process reports a dependency requirement (DEP0840) for 'MicrosoftCorporationII.WinAppRuntime.Main.1.5_8wekyb3d8bbwe' and 'MicrosoftCorporationII.WinAppRuntime.Singleton_8wekyb3d8bbwe' with version >= '5001.70.1338.0'.

Environment:

Visual Studio: 2022, Version 17.10.0 Of VS
Platform: MAUI
Error Message1:
NU1301: Unable to get repository signature information for source 
https://api.nuget.org/v3-index/repository-signatures/5.0.0/index.json.  (This URL Proper work in Browser)

Error Message2:Severity	Code	Description	Project	File	Line	Suppression State
Error The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
The remote certificate is invalid according to the validation procedure.				

Warning:Severity	Code	Description	Project	File	Line	Suppression State
Warning		DEP0840: Project 'Mauived' requires packages 'MicrosoftCorporationII.WinAppRuntime.Main.1.5_8wekyb3d8bbwe' and 'MicrosoftCorporationII.WinAppRuntime.Singleton_8wekyb3d8bbwe' with version >= '5001.70.1338.0'. These packages should be installed on first run, if not please visit http://go.microsoft.com/fwlink/?linkid=2222757 for installation instructions.	Mauived			

This is Show when i click on Windows Machine For start The MAUI 
![e 2](https://github.com/dotnet/maui/assets/122508473/fa876e9a-b6b5-455a-980f-e638ec195b36)

This Nuget Pakage Problem
![1 E](https://github.com/dotnet/maui/assets/122508473/af80aea4-0995-4ad7-bd3b-65248fe2c4e0)

[nuget.org] Unable to load the service index for source https://api.nuget.org/v3/index.json.
  An error occurred while sending the request.
  The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
  The remote certificate is invalid according to the validation procedure.(This URL Perfect Work in Browser https://api.nuget.org/v3/index.json)

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Relevant log output

```shell
Here I Past Output For More Context 

Bulid
Creating a new clean layout...
Copying files: Total 38 mb to layout...
Checking whether required frameworks are installed...
Registering the application to run from layout...
DEP0840: Project 'Mauived' requires packages 'MicrosoftCorporationII.WinAppRuntime.Main.1.5_8wekyb3d8bbwe' and 'MicrosoftCorporationII.WinAppRuntime.Singleton_8wekyb3d8bbwe' with version >= '5001.70.1338.0'. These packages should be installed on first run, if not please visit http://go.microsoft.com/fwlink/?linkid=2222757 for installation instructions.
Deployment complete (0:00:03.071). Full package name: "com.companyname.mauived_1.0.0.1_x64__9zz4h110yvjzm"
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
========== Build completed at 11:50 and took 15.535 seconds ==========
========== Deploy: 1 succeeded, 0 failed, 0 skipped ==========
========== Deploy completed at 11:50 and took 15.535 seconds ==========


Debug:

'Mauived.exe' (CoreCLR: DefaultDomain): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.5\System.Private.CoreLib.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Mauived.exe' (CoreCLR: clrhost): Loaded 'C:\Users\parth\source\repos\Mauived\Mauived\bin\Debug\net8.0-windows10.0.19041.0\win10-x64\AppX\Mauived.dll'. Symbols loaded.
'Mauived.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.5\System.Runtime.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Mauived.exe' (CoreCLR: clrhost): Loaded 'C:\Users\parth\source\repos\Mauived\Mauived\bin\Debug\net8.0-windows10.0.19041.0\win10-x64\AppX\Microsoft.Windows.ApplicationModel.WindowsAppRuntime.Projection.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Mauived.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.5\System.Runtime.InteropServices.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Mauived.exe' (CoreCLR: clrhost): Loaded 'C:\Users\parth\source\repos\Mauived\Mauived\bin\Debug\net8.0-windows10.0.19041.0\win10-x64\AppX\WinRT.Runtime.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Mauived.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.5\System.Collections.Concurrent.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Mauived.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.5\System.Collections.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Mauived.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.5\System.Threading.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Mauived.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.5\System.Runtime.CompilerServices.Unsafe.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Mauived.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.5\System.Private.Uri.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Mauived.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.5\System.ObjectModel.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Mauived.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.5\System.ComponentModel.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Mauived.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.5\System.Numerics.Vectors.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
The program '[9708] Mauived.exe' has exited with code 2147942405 (0x80070005)


Deployment

Starting local deployment...
Deploy: START
DeployAsync: START
Reading package recipe file "C:\Users\parth\source\repos\Mauived\Mauived\bin\Debug\net8.0-windows10.0.19041.0\win10-x64\Mauived.build.appxrecipe"...
Deployment layout folder location: "C:\Users\parth\source\repos\Mauived\Mauived\bin\Debug\net8.0-windows10.0.19041.0\win10-x64\AppX"
Creating a new clean layout...
Copying files: Total 38 mb to layout...
Copying file "C:\Users\parth\source\repos\Mauived\Mauived\bin\Debug\net8.0-windows10.0.19041.0\win10-x64\resources.pri" to layout "resources.pri"...
Copying file "C:\Users\parth\source\repos\Mauived\Mauived\bin\Debug\net8.0-windows10.0.19041.0\win10-x64\Mauived.runtimeconfig.json" to layout "Mauived.runtimeconfig.json"...
Copying file "C:\Users\parth\.nuget\packages\microsoft.maui.controls.core\8.0.21\lib\net8.0-windows10.0.19041\Microsoft.Maui.Controls.pri" to layout "Microsoft.Maui.Controls.pri"...
Copying file "C:\Users\parth\.nuget\packages\microsoft.maui.core\8.0.21\lib\net8.0-windows10.0.19041\Microsoft.Maui.pri" to layout "Microsoft.Maui.pri"...
Copying file "C:\Users\parth\source\repos\Mauived\Mauived\bin\Debug\net8.0-windows10.0.19041.0\win10-x64\AppxManifest.xml" to layout "AppxManifest.xml"...
Checking whether required frameworks are installed...
Framework: Microsoft.WindowsAppRuntime.1.5/X86. Skipping installation because framework package architecture does not match target architecture X64 and app package architecture X64.
Framework: Microsoft.WindowsAppRuntime.1.5/X86. Skipping installation because framework package architecture does not match target architecture X64 and app package architecture X64.
Framework: Microsoft.WindowsAppRuntime.1.5/X64, app package version 5001.70.1338.0 is installed.
Framework: Microsoft.WindowsAppRuntime.1.5/ARM64. Skipping installation because framework package architecture does not match target architecture X64 and app package architecture X64.
Registering the application to run from layout...
Network loopback enabled for application: "com.companyname.mauived_1.0.0.1_x64__9zz4h110yvjzm"
	Maui = True
	WinUI = False
	XamarinForms = False
	Canceled = False
	PackageArchitecture = X64
	TargetOSArchitecture = X64
	IsOptionalProject = False
	SolutionConfiguration = Debug
	SolutionPlatform = AnyCPU
	Context.FileChanged = False
	Context.InOtherLocation = False
	Context.ManifestChanged = True
	Context.Registered = False
	Action.CleanReinstall = True
	Action.Register = False
	Action.UpdateLayout = False
DEP0840: Project 'Mauived' requires packages 'MicrosoftCorporationII.WinAppRuntime.Main.1.5_8wekyb3d8bbwe' and 'MicrosoftCorporationII.WinAppRuntime.Singleton_8wekyb3d8bbwe' with version >= '5001.70.1338.0'. These packages should be installed on first run, if not please visit http://go.microsoft.com/fwlink/?linkid=2222757 for installation instructions.
Deployment complete (0:00:03.071). Full package name: "com.companyname.mauived_1.0.0.1_x64__9zz4h110yvjzm"
	DeploymentSucceeded = True
	TimeToDeploy = 3071
	HasSharedCode = False
	Target.Id = 256
	ProjectGuid = {ce32cc4e-0aa1-438a-9f90-5d28f9eaebd6}
	Project.TargetPlatformVersion = 34.0
DeployAsync: END (Success, 0:00:03.189)
Deploy: END (Success, 0:00:03.27)


Pakage Manager
Restoring packages for C:\Users\parth\source\repos\Mauived\Mauived\Mauived.csproj...
NU1301: Unable to get repository signature information for source https://api.nuget.org/v3-index/repository-signatures/5.0.0/index.json.
NU1301: Unable to get repository signature information for source https://api.nuget.org/v3-index/repository-signatures/5.0.0/index.json.
NU1301: Unable to get repository signature information for source https://api.nuget.org/v3-index/repository-signatures/5.0.0/index.json.
NU1301: Unable to get repository signature information for source https://api.nuget.org/v3-index/repository-signatures/5.0.0/index.json.
System.Net.WebException: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel. ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
Time Elapsed: 00:00:09.1160792
========== Finished ==========

This show in Xamarin Diagnostics

[I:]:                     Found Xamarin.Android 13.2.2.0
[I:sdk]:                  Runtime path: C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Xamarin\Android
[I:sdk]:                  Framework path: C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\MonoAndroid\v1.0
[I:]:                     Looking for Android NDK...
[I:]:                     Looking for Android SDK...
[E:]:                     starting adb from 'C:\Program Files (x86)\Android\android-sdk\platform-tools\adb.EXE'...
[I:]:                     Tracking android devices started
[W:]:                     Adb connection refused
[I:]:                     Starting Adb server (adb start-server)
[I:]:                     Adb start-server operation completed
[I:]:                     Got new device list from adb with 0 devices
[W:]:                     AutoSdk cannot resolve dependencies: build-tools/34.0.0@34.0.0, platform-tools@34.0.5, cmdline-tools/11.0@11.0
[W:]:                     AutoSdk cannot resolve dependencies: platforms/android-34, build-tools/34.0.0@34.0.0, platform-tools@34.0.5, cmdline-tools/11.0@11.0
```

**Comment by jfversluis** [comment]
Additionally this problem was also already mentioned in #22489
