### ISSUE TITLE
Using Shell, more than 5 tabs works until navigating to another tab bar and back.

### ISSUE THREAD

**Issue by JRPMike** [dotnet/maui#22875]
### Description

I have an application that uses the Shell flyout and two tabbars. Both tabbars have more than 5 tabs. 

When I launch the application, it loads. I select an item to navigate to the first tabbar page. It works and the extra tabs are in the "more" item. I then navigate the the second tabbar page and it works as expected. 

I then navigate back to the first and get:
Java.Lang.IllegalArgumentException: 'Maximum number of items supported by BottomNavigationView is 5. Limit can be checked with BottomNavigationView#getMaxItemCount()'
The app then crashes.

### Steps to Reproduce

1. Run the solution on Android emulator in debug. 
2. Click "Go To A"
3. Click "Go To B"
4. Click "Go To A"
5. Should get the error and application crashes..

### Link to public reproduction project repository

https://github.com/JRPMike/MauiTabsIssueReproduction.git

### Version with bug

8.0.40 SR5

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 14.0

### Relevant log output

```shell
**Java.Lang.IllegalArgumentException:** 'Maximum number of items supported by BottomNavigationView is 5. Limit can be checked with BottomNavigationView#getMaxItemCount()'

[mono-rt] [ERROR] FATAL UNHANDLED EXCEPTION: Java.Lang.IllegalArgumentException: Maximum number of items supported by BottomNavigationView is 5. Limit can be checked with BottomNavigationView#getMaxItemCount()
[mono-rt]    at Java.Interop.JniEnvironment.InstanceMethods.CallObjectMethod(JniObjectReference instance, JniMethodInfo method, JniArgumentValue* args) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/obj/Release/net7.0/JniEnvironment.g.cs:line 19992
[mono-rt]    at Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualObjectMethod(String encodedMember, IJavaPeerable self, JniArgumentValue* parameters) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:line 867
[mono-rt]    at AndroidX.AppCompat.View.Menu.MenuBuilder.Add(Int32 group, Int32 id, Int32 categoryOrder, ICharSequence title) in C:\a\_work\1\s\generated\androidx.appcompat.appcompat\obj\Release
et6.0-android\generated\src\AndroidX.AppCompat.View.Menu.MenuBuilder.cs:line 810
[mono-rt]    at Android.Views.IMenuExtensions.Add(IMenu self, Int32 groupId, Int32 itemId, Int32 order, String title) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net8.0/android-34/mcw/Android.Views.IMenu.cs:line 187
[mono-rt]    at Microsoft.Maui.Controls.Platform.BottomNavigationViewUtils.SetupMenu(IMenu menu, Int32 maxBottomItems, List`1 items, Int32 currentIndex, BottomNavigationView bottomView, IMauiContext mauiContext) in D:\a\_work\1\s\src\Controls\src\Core\Platform\Android\BottomNavigationViewUtils.cs:line 107
[mono-rt]    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
[mono-rt]    at Android.App.SyncContext.<>c__DisplayClass2_0.<Post>b__0() in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.App/SyncContext.cs:line 36
[mono-rt]    at Java.Lang.Thread.RunnableImplementor.Run() in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Java.Lang/Thread.cs:line 36
[mono-rt]    at Java.Lang.IRunnableInvoker.n_Run(IntPtr jnienv, IntPtr native__this) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net8.0/android-34/mcw/Java.Lang.IRunnable.cs:line 84
[mono-rt]    at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(_JniMarshal_PP_V callback, IntPtr jnienv, IntPtr klazz) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 22
[mono-rt]   --- End of managed Java.Lang.IllegalArgumentException stack trace ---
[mono-rt] java.lang.IllegalArgumentException: Maximum number of items supported by BottomNavigationView is 5. Limit can be checked with BottomNavigationView#getMaxItemCount()
[mono-rt] 	at com.google.android.material.navigation.NavigationBarMenu.addInternal(NavigationBarMenu.java:67)
[mono-rt] 	at androidx.appcompat.view.menu.MenuBuilder.add(MenuBuilder.java:478)
[mono-rt] 	at crc640ec207abc449b2ca.ShellItemRenderer.n_onCreateView(Native Method)
[mono-rt] 	at crc640ec207abc449b2ca.ShellItemRenderer.onCreateView(ShellItemRenderer.java:42)
[mono-rt] 	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:3114)
[mono-rt] 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:557)
[mono-rt] 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:272)
[mono-rt] 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1943)
[mono-rt] 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1839)
[mono-rt] 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1782)
[mono-rt] 	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:565)
[mono-rt] 	at android.os.Handler.handleCallback(Handler.java:958)
[mono-rt] 	at android.os.Handler.dispatchMessage(Handler.java:99)
[mono-rt] 	at android.os.Looper.loopOnce(Looper.java:205)
[mono-rt] 	at android.os.Looper.loop(Looper.java:294)
[mono-rt] 	at android.app.ActivityThread.main(ActivityThread.java:8177)
[mono-rt] 	at java.lang.reflect.Method.invoke(Native Method)
[mono-rt] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
[mono-rt] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
[mono-rt]   --- End of managed Java.Lang.IllegalArgumentException stack trace ---
[mono-rt] java.lang.IllegalArgumentException: Maximum number of items supported by BottomNavigationView is 5. Limit can be checked with BottomNavigationView#getMaxItemCount()
[mono-rt] 	at com.google.android.material.navigation.NavigationBarMenu.addInternal(NavigationBarMenu.java:67)
[mono-rt] 	at androidx.appcompat.view.menu.MenuBuilder.add(MenuBuilder.java:478)
[mono-rt] 	at crc640ec207abc449b2ca.ShellItemRenderer.n_onCreateView(Native Method)
[mono-rt] 	at crc640ec207abc449b2ca.ShellItemRenderer.onCreateView(ShellItemRenderer.java:42)
[mono-rt] 	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:3114)
[mono-rt] 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:557)
[mono-rt] 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:272)
[mono-rt] 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1943)
[mono-rt] 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1839)
[mono-rt] 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1782)
[mono-rt] 	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:565)
[mono-rt] 	at android.os.Handler.handleCallback(Handler.java:958)
[mono-rt] 	at android.os.Handler.dispatchMessage(Handler.java:99)
[mono-rt] 	at android.os.Looper.loopOnce(Looper.java:205)
[mono-rt] 	at android.os.Looper.loop(Looper.java:294)
[mono-rt] 	at android.app.ActivityThread.main(ActivityThread.java:8177)
[mono-rt] 	at java.lang.reflect.Method.invoke(Native Method)
[mono-rt] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
[mono-rt] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
[mono-rt]
```

**Comment by PureWeen** [comment]
Can you test with the latest nightly build? 
https://github.com/dotnet/maui/wiki/Nightly-Builds

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio 17.11.0 Preview 1.1 (8.0.40 ). Can repro on Android platform with sample project. 
And not repro on latest nightly build & 8.0.60-ci.net8.24304.1.
![image](https://github.com/dotnet/maui/assets/77434865/97fb3f4b-d21d-49d4-8863-6e76f1f1cb38)
