### ISSUE TITLE
Microsoft.Maui.Controls.ImageSource.FromFile fails in iOS when image in subfolder

### ISSUE THREAD

**Issue by munkii** [dotnet/maui#22887]
### Description

We have some PNGs that we display via a ViewModel. The property on the ViewModel is an ImageSource

Most of the images live directly under Resources/Images but some are in a subfolder called "signal". All the images have the Build Action of MauiImage

In the ViewModel we load those images into the ImageSource like this:

`this.Image = Microsoft.Maui.Controls.ImageSource.FromFile("signal/red_hexagon1.png");`

In Android this works fine. In iOS it does not work and we see the following error message in the Output window

> [0:] Microsoft.Maui.FileImageSourceService: Warning: Unable to load image file 'Signal/red_hexagon.png'.
> 
> System.InvalidOperationException: Unable to load image file.
>    at Microsoft.Maui.FileImageSourceService.GetImageAsync(IFileImageSource imageSource, Single scale, CancellationToken cancellationToken)

If I move the image into root of "Resources/Images" the image loads fine.

This fails on both the Device (iOS 17.4.1) and Simulator (iPhone 15 iOS 17.4)

It works fine on Android

### Steps to Reproduce

Call Microsoft.Maui.Controls.ImageSource.FromFile on iOS with an Image in a sub folder of Resources/Images

### Version with bug

8.0.40 SR5

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 17.4.x

### Did you find any workaround?

Move image to the root.

### Relevant log output

```shell
[0:] Microsoft.Maui.FileImageSourceService: Warning: Unable to load image file 'Signal/red_hexagon.png'.

System.InvalidOperationException: Unable to load image file.
   at Microsoft.Maui.FileImageSourceService.GetImageAsync(IFileImageSource imageSource, Single scale, CancellationToken cancellationToken)
```

**Comment by munkii** [comment]
Thanks @github-actions :-)

This issue [Resources/Images subfolder problem](https://github.com/dotnet/maui/issues/11661) shows that whilst you can have images in a subfolder, referring to the subfolder name in iOS is not supported. The files are essentially only in those folders for solution organisation. 

They should be addressed by the filename not the "relativepath\filename" i.e.

`this.Image = Microsoft.Maui.Controls.ImageSource.FromFile("red_hexagon1.png");`

Works in Android and iOS (even with the file being "organised" in a subfolder called "Signal". 

This should be explained in the docs

**Comment by ninachen03** [comment]
This issue has been verified using Visual Studio 17.11.0 Preview 3 (8.0.61). Can repro it.

**Comment by jfversluis** [comment]
I think this is now also solved in recent versions of .NET 8. Please try again, if there is still an issue feel free to open something new. Ideally with a reproduction sample. That makes it easy to verify. Thanks!

**Comment by munkii** [comment]
The workaround which was dropping the folder name is what we are currently using. I upgraded to 8.0.90 and added the subfolder name back in and it stopped working so I guess it is not fixed. 

Still only an issue with iOS. I'll look at creating a repro later today

**Comment by munkii** [comment]
@jfversluis this bug is 100% still repro. Not sure why opening a new issue is valid as it is exactly the same issue. Here is a repro sample, https://github.com/munkii/MauiAppImageAssetsInSubFolders

If your process requires a new bug and you are not able to reopen this one then fine.

**Comment by jfversluis** [comment]
@munkii the repo is not public or doesn't exist

**Comment by munkii** [comment]
> [@munkii](https://github.com/munkii) the repo is not public or doesn't exist

Sorry, I am forever making that error

**Comment by ninachen03** [comment]
This issue has been verified using Visual Studio 17.12.0 Preview 2.1 (8.0.91). Can repro it.
![Image](https://github.com/user-attachments/assets/6d0b621c-6687-46cc-8b7e-ad93ea355d39)

**Comment by PauchardThomas** [comment]
Issue still present on net9.0-ios
