### ISSUE TITLE
In .NET 8 IOS platform getting exception while remove the child from the current layout.

### ISSUE THREAD

**Issue by MohanrajSF3559** [dotnet/maui#22951]
### Description

I have attached the sample. Same sample properly working in .NET 7. There is now change in our source level. But facing exception in .NET 8 in IOS alone. Same sample working fine in windows, Mac Android devices.

### Steps to Reproduce

1. Run the sample.
2. Click the crop icon from the bottom of the image editor control.
3. Click the crop option icon.
4. Click the crop image button.
5. You got a exception.

### Link to public reproduction project repository

https://github.com/MohanrajSF3559/ImageEditor-Mopup-Issue

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

8.0.0-preview.1.7762

### Affected platforms

iOS

### Affected platform versions

iOS 16.2

### Did you find any workaround?

NA

**Comment by drasticactions** [comment]
Your exception is

```
System.InvalidOperationException: MauiContext should have been set on parent.
   at Microsoft.Maui.Platform.ElementExtensions.ToPlatform(IElement view)
   at Microsoft.Maui.Handlers.LayoutHandler.Remove(IView child)
   at Microsoft.Maui.Handlers.LayoutHandler.MapRemove(ILayoutHandler handler, ILayout layout, Object arg)
   at Microsoft.Maui.CommandMapper`2.<>c__DisplayClass6_0[[Microsoft.Maui.ILayout, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.ILayoutHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v, Object o)
   at Microsoft.Maui.CommandMapper.InvokeCore(String key, IElementHandler viewHandler, IElement virtualView, Object args)
   at Microsoft.Maui.CommandMapper.Invoke(IElementHandler viewHandler, IElement virtualView, String property, Object args)
   at Microsoft.Maui.Handlers.ElementHandler.Invoke(String command, Object args)
   at Microsoft.Maui.Controls.Layout.NotifyHandler(String action, Int32 index, IView view)
   at Microsoft.Maui.Controls.Layout.OnRemove(Int32 index, IView view)
   at Microsoft.Maui.Controls.Layout.RemoveAt(Int32 index)
   at Microsoft.Maui.Controls.Layout.Remove(IView child)
   at Syncfusion.Maui.ImageEditor.ImageEditLayout.RemoveCropView()
   at Syncfusion.Maui.ImageEditor.ImageEditLayout.Syncfusion.Maui.ImageEditor.IToolbarActions.CancelEdit()
   at Syncfusion.Maui.ImageEditor.ToolbarLayout.HandleItemTapped(SfToolbarItem tappedItem, SfToolbarItem previousItem)
   at Syncfusion.Maui.ImageEditor.ToolbarLayout.OnToolbarItemTapped(Object sender, ToolbarTappedEventArgs e)
   at Syncfusion.Maui.Core.Internals.SfToolbar.Syncfusion.Maui.Core.Internals.IToolbar.InvokeTappedEvent(SfToolbarItem toolbarItem, SfToolbarItem previousToolbarItem)
   at Syncfusion.Maui.Core.Internals.SfToolbarLayout.Syncfusion.Maui.Core.Internals.ITapGestureListener.OnTap(TapEventArgs e)
   at Syncfusion.Maui.Core.Internals.GestureDetector.OnTapped(Point touchPoint, Int32 tapCount)
   at Syncfusion.Maui.Core.Internals.GestureDetector.UITapGestureExt.OnTap(GestureDetector gestureDetector)
   at Syncfusion.Maui.Core.Internals.GestureDetector.UITapGestureExt.<>c__DisplayClass1_0.<.ctor>b__0()
   at UIKit.UIGestureRecognizer.ParameterlessDispatch.Activated() in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIGestureRecognizer.cs:line 107
--- End of stack trace from previous location ---
   at ObjCRuntime.Runtime.ThrowException(IntPtr gchandle) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/Runtime.cs:line 2594
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 60
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 94
   at MauiMopupsSample.Program.Main(String[] args) in /Users/drasticactions/Developer/Work/ImageEditor-Mopup-Issue/MauiMopupsSample/MauiMopupsSample/MauiMopupsSample/Platforms/iOS/Program.cs:line 13
   ```

The important parts are

`System.InvalidOperationException: MauiContext should have been set on parent.`

and

`Syncfusion.Maui.Core.Internals.SfToolbar.Syncfusion.Maui.Core.Internals.IToolbar.InvokeTappedEvent(SfToolbarItem toolbarItem, SfToolbarItem previousToolbarItem)`

IMO, this seems like a Syncfusion issue. I would direct this to them first, as I think that's the issue's root.

@PureWeen @mattleibow what do you all think?

**Comment by ESO-ST** [comment]
I get the same exception when using Carousel in MAUI, it started in version 8.0.60, I tested it in v8.0.40 and it works fine there.

**Comment by ninachen03** [comment]
I can repro this issue on Visual Studio 17.11.0 Preview 2.1 (8.0.60 & 8.0.40)
![image](https://github.com/dotnet/maui/assets/128687574/dba4b865-0ac8-4767-b8c8-6ab1298b7546)

**Comment by PureWeen** [comment]
> Your exception is
> 
> ```
> System.InvalidOperationException: MauiContext should have been set on parent.
>    at Microsoft.Maui.Platform.ElementExtensions.ToPlatform(IElement view)
>    at Microsoft.Maui.Handlers.LayoutHandler.Remove(IView child)
>    at Microsoft.Maui.Handlers.LayoutHandler.MapRemove(ILayoutHandler handler, ILayout layout, Object arg)
>    at Microsoft.Maui.CommandMapper`2.<>c__DisplayClass6_0[[Microsoft.Maui.ILayout, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.ILayoutHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v, Object o)
>    at Microsoft.Maui.CommandMapper.InvokeCore(String key, IElementHandler viewHandler, IElement virtualView, Object args)
>    at Microsoft.Maui.CommandMapper.Invoke(IElementHandler viewHandler, IElement virtualView, String property, Object args)
>    at Microsoft.Maui.Handlers.ElementHandler.Invoke(String command, Object args)
>    at Microsoft.Maui.Controls.Layout.NotifyHandler(String action, Int32 index, IView view)
>    at Microsoft.Maui.Controls.Layout.OnRemove(Int32 index, IView view)
>    at Microsoft.Maui.Controls.Layout.RemoveAt(Int32 index)
>    at Microsoft.Maui.Controls.Layout.Remove(IView child)
>    at Syncfusion.Maui.ImageEditor.ImageEditLayout.RemoveCropView()
>    at Syncfusion.Maui.ImageEditor.ImageEditLayout.Syncfusion.Maui.ImageEditor.IToolbarActions.CancelEdit()
>    at Syncfusion.Maui.ImageEditor.ToolbarLayout.HandleItemTapped(SfToolbarItem tappedItem, SfToolbarItem previousItem)
>    at Syncfusion.Maui.ImageEditor.ToolbarLayout.OnToolbarItemTapped(Object sender, ToolbarTappedEventArgs e)
>    at Syncfusion.Maui.Core.Internals.SfToolbar.Syncfusion.Maui.Core.Internals.IToolbar.InvokeTappedEvent(SfToolbarItem toolbarItem, SfToolbarItem previousToolbarItem)
>    at Syncfusion.Maui.Core.Internals.SfToolbarLayout.Syncfusion.Maui.Core.Internals.ITapGestureListener.OnTap(TapEventArgs e)
>    at Syncfusion.Maui.Core.Internals.GestureDetector.OnTapped(Point touchPoint, Int32 tapCount)
>    at Syncfusion.Maui.Core.Internals.GestureDetector.UITapGestureExt.OnTap(GestureDetector gestureDetector)
>    at Syncfusion.Maui.Core.Internals.GestureDetector.UITapGestureExt.<>c__DisplayClass1_0.<.ctor>b__0()
>    at UIKit.UIGestureRecognizer.ParameterlessDispatch.Activated() in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIGestureRecognizer.cs:line 107
> --- End of stack trace from previous location ---
>    at ObjCRuntime.Runtime.ThrowException(IntPtr gchandle) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/Runtime.cs:line 2594
>    at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 60
>    at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 94
>    at MauiMopupsSample.Program.Main(String[] args) in /Users/drasticactions/Developer/Work/ImageEditor-Mopup-Issue/MauiMopupsSample/MauiMopupsSample/MauiMopupsSample/Platforms/iOS/Program.cs:line 13
> ```
> 
> The important parts are
> 
> `System.InvalidOperationException: MauiContext should have been set on parent.`
> 
> and
> 
> `Syncfusion.Maui.Core.Internals.SfToolbar.Syncfusion.Maui.Core.Internals.IToolbar.InvokeTappedEvent(SfToolbarItem toolbarItem, SfToolbarItem previousToolbarItem)`
> 
> IMO, this seems like a Syncfusion issue. I would direct this to them first, as I think that's the issue's root. If it is MAUI, they can circle back.
> 
> @PureWeen @mattleibow what do you all think?



> Your exception is
> 
> ```
> System.InvalidOperationException: MauiContext should have been set on parent.
>    at Microsoft.Maui.Platform.ElementExtensions.ToPlatform(IElement view)
>    at Microsoft.Maui.Handlers.LayoutHandler.Remove(IView child)
>    at Microsoft.Maui.Handlers.LayoutHandler.MapRemove(ILayoutHandler handler, ILayout layout, Object arg)
>    at Microsoft.Maui.CommandMapper`2.<>c__DisplayClass6_0[[Microsoft.Maui.ILayout, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.ILayoutHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v, Object o)
>    at Microsoft.Maui.CommandMapper.InvokeCore(String key, IElementHandler viewHandler, IElement virtualView, Object args)
>    at Microsoft.Maui.CommandMapper.Invoke(IElementHandler viewHandler, IElement virtualView, String property, Object args)
>    at Microsoft.Maui.Handlers.ElementHandler.Invoke(String command, Object args)
>    at Microsoft.Maui.Controls.Layout.NotifyHandler(String action, Int32 index, IView view)
>    at Microsoft.Maui.Controls.Layout.OnRemove(Int32 index, IView view)
>    at Microsoft.Maui.Controls.Layout.RemoveAt(Int32 index)
>    at Microsoft.Maui.Controls.Layout.Remove(IView child)
>    at Syncfusion.Maui.ImageEditor.ImageEditLayout.RemoveCropView()
>    at Syncfusion.Maui.ImageEditor.ImageEditLayout.Syncfusion.Maui.ImageEditor.IToolbarActions.CancelEdit()
>    at Syncfusion.Maui.ImageEditor.ToolbarLayout.HandleItemTapped(SfToolbarItem tappedItem, SfToolbarItem previousItem)
>    at Syncfusion.Maui.ImageEditor.ToolbarLayout.OnToolbarItemTapped(Object sender, ToolbarTappedEventArgs e)
>    at Syncfusion.Maui.Core.Internals.SfToolbar.Syncfusion.Maui.Core.Internals.IToolbar.InvokeTappedEvent(SfToolbarItem toolbarItem, SfToolbarItem previousToolbarItem)
>    at Syncfusion.Maui.Core.Internals.SfToolbarLayout.Syncfusion.Maui.Core.Internals.ITapGestureListener.OnTap(TapEventArgs e)
>    at Syncfusion.Maui.Core.Internals.GestureDetector.OnTapped(Point touchPoint, Int32 tapCount)
>    at Syncfusion.Maui.Core.Internals.GestureDetector.UITapGestureExt.OnTap(GestureDetector gestureDetector)
>    at Syncfusion.Maui.Core.Internals.GestureDetector.UITapGestureExt.<>c__DisplayClass1_0.<.ctor>b__0()
>    at UIKit.UIGestureRecognizer.ParameterlessDispatch.Activated() in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIGestureRecognizer.cs:line 107
> --- End of stack trace from previous location ---
>    at ObjCRuntime.Runtime.ThrowException(IntPtr gchandle) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/Runtime.cs:line 2594
>    at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 60
>    at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 94
>    at MauiMopupsSample.Program.Main(String[] args) in /Users/drasticactions/Developer/Work/ImageEditor-Mopup-Issue/MauiMopupsSample/MauiMopupsSample/MauiMopupsSample/Platforms/iOS/Program.cs:line 13
> ```
> 
> The important parts are
> 
> `System.InvalidOperationException: MauiContext should have been set on parent.`
> 
> and
> 
> `Syncfusion.Maui.Core.Internals.SfToolbar.Syncfusion.Maui.Core.Internals.IToolbar.InvokeTappedEvent(SfToolbarItem toolbarItem, SfToolbarItem previousToolbarItem)`
> 
> IMO, this seems like a Syncfusion issue. I would direct this to them first, as I think that's the issue's root. If it is MAUI, they can circle back.
> 
> @PureWeen @mattleibow what do you all think?

Yea, the error here is that a view is being removed from a layout that is no longer connected. 

We do get the index as part of the remove command

![image](https://github.com/dotnet/maui/assets/5375137/08755c7c-dbc1-48a4-a857-64180e4c1bc3)

so, in theory we could use the index vs the platform view to remove the view, but I do worry this just moves the exception down the pipeline. Because there shouldn't really be a path like this triggering.
