### ISSUE TITLE
App crashes when calling ItemsView.ScrollTo on unloaded CollectionView

### ISSUE THREAD

**Issue by spadapet** [dotnet/maui#23014]
### Description

Exceptions are thrown on all platforms when calling ScrollTo on an unloaded CollectionView (or probably any ItemsView). While it sounds odd to try and scroll an unloaded ItemsView, it can easily happen by accident if ScrollTo is called in an event handler. For example, here is a user project that triggers the bug in a SelectionChanged handler:

https://github.com/YBTopaz8/Dimmer-MAUI/blob/f5366d12d8a59a0d70ce80b201891a672d0cd13d/Dimmer/Views/Desktop/HomeD.xaml.cs#L32

SelectionChanged is triggered when removing CollectionView from its parent because the BindingContext changes. When MAUI Full Page Hot Reload in Visual Studio 17.10 reloads the XAML, it can also trigger this issue.

### Steps to Reproduce

**REPRO:**

1. Clone test repo:
    * https://github.com/spadapet/maui_bugs.git
    * Or just copy the test project's directory locally:
    * https://github.com/spadapet/maui_bugs/tree/main/ScrollToCrash
2. Open the test project solution file in Visual Studio 2022 17.10+
    * [ScrollToCrash/MauiApp10.sln](https://github.com/spadapet/maui_bugs/blob/main/ScrollToCrash/MauiApp10.sln)
3. F5 to build and debug the app on Windows
4. Click the button:
    ![image](https://github.com/dotnet/maui/assets/2523431/00c0e653-8a3b-43e9-9eeb-2a9398a94606)

**RESULT:**

App crashes with a NullReferenceException. On Windows, the [ItemsViewHandler.Windows.cs](https://github.com/dotnet/maui/blob/a0a4152938fb6b9d923d1701e40796b64ad080f8/src/Controls/src/Core/Handlers/Items/ItemsViewHandler.Windows.cs) file is still listening to scroll requests after CleanUpCollectionViewSource() is called.

On iOS or Android emulator, different exceptions are thrown.

Android:
![image](https://github.com/dotnet/maui/assets/2523431/29597c6f-7eee-4014-8f9f-c99c9ff1dc3a)

iOS:
An index out of range exception

### Link to public reproduction project repository

https://github.com/spadapet/maui_bugs.git

### Version with bug

8.0.3 GA

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Did you find any workaround?

Skip calling ItemsView.ScrollTo if the IsLoaded property is false.

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio 17.11.0 Preview 2.0 (8.0.40 & 8.0.21 & 8.0.3). Can repro this issue with sample project.

**Comment by MattiaVicari** [comment]
Hi,
with the v9.0.50 this issue is still present for Android:

`
**Java.Lang.IllegalArgumentException:** 'Invalid target position'

**Java.Lang.IllegalArgumentException:** 'Invalid target position'

[mono-rt] [ERROR] FATAL UNHANDLED EXCEPTION: Java.Lang.IllegalArgumentException: Invalid target position
[mono-rt]    at Java.Interop.JniEnvironment.InstanceMethods.CallNonvirtualVoidMethod(JniObjectReference instance, JniObjectReference type, JniMethodInfo method, JniArgumentValue* args) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/obj/Release/net8.0/JniEnvironment.g.cs:line 20831
[mono-rt]    at Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualVoidMethod(String encodedMember, IJavaPeerable self, JniArgumentValue* parameters) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:line 75
[mono-rt]    at AndroidX.RecyclerView.Widget.RecyclerView.SmoothScrollToPosition(Int32 position) in D:\a\_work\1\s\generated\androidx.recyclerview.recyclerview\obj\Release\net8.0-android\generated\src\AndroidX.RecyclerView.Widget.RecyclerView.cs:line 14877
[mono-rt]    at Microsoft.Maui.Controls.Handlers.Items.ScrollHelper.AnimateScrollToPosition(Int32 index, ScrollToPosition scrollToPosition) in /_/src/Controls/src/Core/Handlers/Items/Android/ScrollHelper.cs:line 52
[mono-rt]    at Microsoft.Maui.Controls.Handlers.Items.MauiRecyclerView`3[[Microsoft.Maui.Controls.ReorderableItemsView, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Controls.Handlers.Items.GroupableItemsViewAdapter`2[[Microsoft.Maui.Controls.ReorderableItemsView, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Controls.Handlers.Items.IGroupableItemsViewSource, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Controls.Handlers.Items.IGroupableItemsViewSource, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].ScrollTo(ScrollToRequestEventArgs args) in /_/src/Controls/src/Core/Handlers/Items/Android/MauiRecyclerView.cs:line 397
[mono-rt]    at Microsoft.Maui.Controls.Handlers.Items.MauiRecyclerView`3[[Microsoft.Maui.Controls.ReorderableItemsView, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Controls.Handlers.Items.GroupableItemsViewAdapter`2[[Microsoft.Maui.Controls.ReorderableItemsView, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Controls.Handlers.Items.IGroupableItemsViewSource, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Controls.Handlers.Items.IGroupableItemsViewSource, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].ScrollToRequested(Object sender, ScrollToRequestEventArgs args) in /_/src/Controls/src/Core/Handlers/Items/Android/MauiRecyclerView.cs:line 506
[mono-rt]    at Microsoft.Maui.Controls.ItemsView.OnScrollToRequested(ScrollToRequestEventArgs e) in /_/src/Controls/src/Core/Items/ItemsView.cs:line 212
[mono-rt]    at Microsoft.Maui.Controls.ItemsView.ScrollTo(Object item, Object group, ScrollToPosition position, Boolean animate) in /_/src/Controls/src/Core/Items/ItemsView.cs:line 167
[mono-rt]    at SviluppoMania.Views.PostListPage.<ViewModel_LoadFinished>b__7_0() in D:\Lavoro\App\SviluppoManiaMAUI\SviluppoMania\Views\PostListPage.xaml.cs:line 56
[mono-rt]    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
[mono-rt]    at Android.App.SyncContext.<>c__DisplayClass2_0.<Post>b__0() in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.App/SyncContext.cs:line 36
[mono-rt]    at Java.Lang.Thread.RunnableImplementor.Run() in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Java.Lang/Thread.cs:line 37
[mono-rt]    at Java.Lang.IRunnableInvoker.n_Run(IntPtr jnienv, IntPtr native__this) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net9.0/android-35/mcw/Java.Lang.IRunnable.cs:line 59
[mono-rt]    at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(_JniMarshal_PP_V callback, IntPtr jnienv, IntPtr klazz) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 22
[mono-rt]   --- End of managed Java.Lang.IllegalArgumentException stack trace ---
[mono-rt] java.lang.IllegalArgumentException: Invalid target position
[mono-rt] 	at androidx.recyclerview.widget.RecyclerView$SmoothScroller.start(RecyclerView.java:12749)
[mono-rt] 	at androidx.recyclerview.widget.RecyclerView$LayoutManager.startSmoothScroll(RecyclerView.java:9294)
[mono-rt] 	at androidx.recyclerview.widget.LinearLayoutManager.smoothScrollToPosition(LinearLayoutManager.java:525)
[mono-rt] 	at androidx.recyclerview.widget.RecyclerView.smoothScrollToPosition(RecyclerView.java:1930)
[mono-rt] 	at mono.java.lang.RunnableImplementor.n_run(Native Method)
[mono-rt] 	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:29)
[mono-rt] 	at android.os.Handler.handleCallback(Handler.java:959)
[mono-rt] 	at android.os.Handler.dispatchMessage(Handler.java:100)
[mono-rt] 	at android.os.Looper.loopOnce(Looper.java:232)
[mono-rt] 	at android.os.Looper.loop(Looper.java:317)
[mono-rt] 	at android.app.ActivityThread.main(ActivityThread.java:8705)
[mono-rt] 	at java.lang.reflect.Method.invoke(Native Method)
[mono-rt] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
[mono-rt] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
[mono-rt] 
[mono-rt]   --- End of managed Java.Lang.IllegalArgumentException stack trace ---
[mono-rt] java.lang.IllegalArgumentException: Invalid target position
[mono-rt] 	at androidx.recyclerview.widget.RecyclerView$SmoothScroller.start(RecyclerView.java:12749)
[mono-rt] 	at androidx.recyclerview.widget.RecyclerView$LayoutManager.startSmoothScroll(RecyclerView.java:9294)
[mono-rt] 	at androidx.recyclerview.widget.LinearLayoutManager.smoothScrollToPosition(LinearLayoutManager.java:525)
[mono-rt] 	at androidx.recyclerview.widget.RecyclerView.smoothScrollToPosition(RecyclerView.java:1930)
[mono-rt] 	at mono.java.lang.RunnableImplementor.n_run(Native Method)
[mono-rt] 	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:29)
[mono-rt] 	at android.os.Handler.handleCallback(Handler.java:959)
[mono-rt] 	at android.os.Handler.dispatchMessage(Handler.java:100)
[mono-rt] 	at android.os.Looper.loopOnce(Looper.java:232)
[mono-rt] 	at android.os.Looper.loop(Looper.java:317)
[mono-rt] 	at android.app.ActivityThread.main(ActivityThread.java:8705)
[mono-rt] 	at java.lang.reflect.Method.invoke(Native Method)
[mono-rt] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
[mono-rt] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
`
