### ISSUE TITLE
RadioButton with ControlTemplate crashes on Android in the release mode

### ISSUE THREAD

**Issue by holecekp** [dotnet/maui#23200]
### Description

If RadioButton uses a ControlTemplate, it works on Android in the debug mode. However, running the app in the release mode causes an instant crash when the page with the RadioButtons is displayed.

The crash is caused in the following following exception in MAUI:
```System.FormatException: Format_InvalidStringWithOffsetAndReason, ??????????????11, Format_ExpectedAsciiDigit"``` at RadioButton.ContentAsString(). I am 

I am including the full Logcat log (I needed to rename the extension of the file to ".json" because uploading ".logcat" files is not supported here.
[MauiRadioButtonCrash.json](https://github.com/user-attachments/files/15944020/MauiRadioButtonCrash.json)

I am including a repro project wich is a simple combination of a new MAUI app using the standard VS template and the XAML for radion buttons from the demo project linked from the official MAUI documantation on RadioButtons.

The issue is somehow similar to https://github.com/dotnet/maui/issues/22377, however in that issue the problem is for iOS only and it is caused by setting the control template for all RadioButtons from styles. There is a workaround - to set the ContentTemplate for each of the RadionButtons directly without a style. Howevere, this workaroud does not work for my issue so I assime they are different (this one is more severe because there is no workaround).

I have tried to update from MAUI 8.0.40 used in the default VS template to the latest 8.0.60 and it did not help. The app still crashes, just this time the same crash is reported in the FontManager.

### Steps to Reproduce

1. Clone the repository https://github.com/holecekp/MauiBugsRadioButton
2. Run the app on Android emulator in the debug mode. You can see that it works.
3. Switch to the Release mode and press Ctrl+F5 to run the app in the release mode. A splash screen is displayed for a fraction of second and then the app crashes.

### Link to public reproduction project repository

https://github.com/holecekp/MauiBugsRadioButton

### Version with bug

8.0.40 SR5

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Tested on Android 14 emulator

### Did you find any workaround?

No workaround. The only way is to use RadioButtons with a simple string without any ControlTemplate.

### Relevant log output

```shell
Logcat shows an exception:

android.runtime.JavaProxyThrowable: System.FormatException: Format_InvalidStringWithOffsetAndReason, ??????????????11, Format_ExpectedAsciiDigit"
              at System.Text.CompositeFormat.Parse(String )
at Microsoft.Extensions.Logging.LogValuesFormatter..ctor(String )                                                                                                       ...
at Microsoft.Maui.Controls.RadioButton.ContentAsString()
Microsoft.Maui.Controls.RadioButton.UpdateSemantics()                                                                                                      
at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IView.get_Semantics()
at Microsoft.Maui.Handlers.ViewHandler.MappingSemantics(IViewHandler handler, IView view)
at Microsoft.Maui.Handlers.ViewHandler.MapSemantics(IViewHandler handler, IView view)
...
```

**Comment by kevinxufei** [comment]
This issue was not repro on Visual Studio 17.11.0 Preview 2.1 (8.0.60 & 8.0.40 & 8.0.10) with sample project(Android14).

**Comment by holecekp** [comment]
Besides the stable version of VS 17.10.3, I have installed also the latest VS 17.11.0 Preview 2.1. It crashes on both of them. I have found out that it depends on the emulator, which I am using. Android 14 emulator (Pixel 5 based, x86_64) crashes in the release mode. Moreover, Android 12.1 emulator (Small Desktop, x86_64), and Android 9 emulator (Pixel 5 based, x86_64) crashes as well. However, if I launch the app on Android 11 emulator (pixel 7 emulator,  x86) it runs in the release mode without crashing.

I have deleted bin and obj folders, cleaned the solution, and reset the Android emulator to factory settihgs to rule out the possibility that there could be some remains of any other MAUI or Xamarin.Forms apps that would interfere. It did not help, it still crashed with the same exception.

My suspicion is that the issue depends on the procesor architecture (working on x86 but crashing on x86_64). Unfortunatelly, I have tested only on 4 emulators because it takes a lot of time to build and deploy Release version of the MAUI app.

**Comment by kevinxufei** [comment]
Unfortunately, I can't reproduce this problem in my side. Maybe this issue needs help from others.

**Comment by jfversluis** [comment]
@jonathanpeppers ?

**Comment by jonathanpeppers** [comment]
The app doesn't crash for me in `Release` mode on a Pixel 7.

From your stacktrace, it crashes on this line, right?
https://github.com/dotnet/maui/blob/14a080ebb595f929fc2282fd5a94b31b1f870225/src/Controls/src/Core/RadioButton/RadioButton.cs#L653

Since, it's printing a warning, you aren't supposed to put views in a `RadioButton`? I don't actually know.

I'm also confused by the log message, is it supposed to be using `$""` or is it using `string.Format()` syntax?

I don't think this problem has anything to do with Android.

I think I have more questions than answers, sorry!

**Comment by holecekp** [comment]
I did some more testing. Just to be sure, I have also updated to the latest MAUI 8.0.61 - no change. The problem seems to be related to x86_64 processor architecture. The app runs well on other processor architectures. Besides a x86_64 emulator (crashes), I have tested also on a x86 emulator (works) and on a Samsung physical phone with ARM64 (works).

I have also tried to turn off AOT and trimming to narrow down what could cause the problem:

1. If I use the standard VS template for new MAUI projects, the app instantly crashes on x86_64  emulator with the error that I have described before, but it runs on x86 emulator and ARM64 phone (the Debug version runs also on x86_64, only Release version have the issue).

2. I have turned off AOT. This time the app does not crash and the splashscreen appears, but notning else, the app ends up in an infinite loop. The same messages can be seen repeating in logcat. An interesting message is a warning that is repeated once a while:
`Unexpected CPU variant for x86: x86_64. Known variants: atom, sandybridge, silvermont, goldmont, goldmont-plus, tremont, kabylake, default`
Does it mean that MAUI does not support x86_64 Android devices at all?

Besides that the following error can be seen in logcat repeatidly:
```
FATAL UNHANDLED EXCEPTION: System.ArgumentException: ArgumentException_BufferNotFromPool Arg_ParamName_Name, array
at System.Buffers.SharedArrayPool`1[[System.Char, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Return(Char[] , Boolean )
at System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.ToStringAndClear()
at Android.Runtime.JavaProxyThrowable.Create(Exception )
...
at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(_JniMarshal_PP_V callback, IntPtr jnienv, IntPtr klazz)
```
Because DefaultInterpolatedStringHandler is mentioned, my guess is that there might be a problem with some kinds of string iterpolation.

This behavior is again only on x86_64 emulators. The x86 emulator and Samsung ARM64 physical device works.

3. Besides AOT, I have turned off trimming, too. This made no difference to the previous case - an infinite loop on x86_64; runs well on x86 and ARM64.

This showed me that it is important not only to test both Debug and Release versions but also different ABIs for the Release version. According to the devices catalog in the Google Play Console the most of the users of my Xamarin.Forms app uses ARM processors. Devices with X86_64 ABI comprise only 0,2 % of the install base. The vast majority of them are various chromebooks. The only X86_64 phone in the install base is OnePlus 10 Pro. So migrating from Xamarin.Forms to the current version of MAUI would probably make the app unusable for these users. Even if it is only a minority, it would be better if migrating to MAUI had no negative effect on any of the current users.

In the repro project, I am using XAML from the official MAUI sample for the RadioButtons (https://github.com/dotnet/maui-samples/blob/main/8.0/UserInterface/Views/RadioButtonDemos/RadioButtonDemos/Views/RadioButtonControlTemplatePage.xaml). I have just removed images to simplify it a bit. So it should be correct. Moreover, I am using RadioButtons with a ControlTemplate in the Xamarin.Forms version in the production for a long time without any problems.

**Comment by jonathanpeppers** [comment]
> Unexpected CPU variant for x86: x86_64. Known variants: atom, sandybridge, silvermont, goldmont, goldmont-plus, tremont, kabylake, default

This message doesn't mean anything, you can ignore it.

> MAUI does not support x86_64 Android devices at all?

No, the default emulator is x86_64. It is certainly supported, because no one could do development otherwise?

> I have also tried to turn off AOT and trimming

I'm not sure that is the problem here. Maybe don't do this yet?

What I was suggesting, is to try to avoid the `LogMessage()` call entirely:
```csharp
.LogWarning("Warning - {RuntimePlatform} does not support View as the {PropertyName} property of RadioButton; the return value of the ToString() method will be displayed instead.", DeviceInfo.Platform, ContentProperty.PropertyName); 
```
If you changed your `RadioButton` to use a `ControlTemplate`, do you get a different error now? Can you update the attached sample.

I can also test on an emulator; maybe I will see the crash myself there.

**Comment by holecekp** [comment]
Hello. I did some more testing and I have found out what exactly causes it. You were right that the app does not craash when  LogWarning is avoided.

The warning generated by the RadioButton is quite confusing because a View as a RadioButton.Content is supported scenario for Android if a ContronTemplate is used (which it is in the repro project). The line in the code where the app crashes uses the ToString() representation RadioButton.Content only for accessibility. A better way in this case would be a warning message that a RadioButton with a ControlTemplate might not by fully accessible in the current version of MAUI , or it would be even better not to generate this warning at all (especially in the release mode) because there is no reasonable way to avoid it and mention this drawback in the documentation instead.

It is quite demanding to find out where does the error message fired by LogWarning goes to. I have found out that it is sent to LoggerProviderDebugView in the Debug mode (this is arranged by "#if DEBUG" in the MauiProgram.cs in the defailt VS template). In the Release mode it however goes to MauiAppBuilder.NullLogger instead which does nothing and just ignores the message.

Before the NullLogger obtains the warning message so that it could throw it away a suprisingly lot of string manipulation is performed. The LogWarning method parses the message and replaces any names in the curly brackets with the number according to its order and remembers the names. So `"Warning - {RuntimePlatform} does not support View as the {PropertyName} property of RadioButton; the return value of the ToString() method will be displayed instead."` becomes `"Warning - {0} does not support View as the {1} property of RadioButton; the return value of the ToString() method will be displayed instead."`. This result is sent to CompositeFormat.Parse when .NET 8 or newer is used. The method expects numbers in the curly brackets and is not happy with what it gets and crashes.

After some more testing, I have found out that the issue is even more low-level. The problem is in the int.ToString() method. It works well in the Debug mode. It works well also in the Release mode on x86 emulator (the one that does not crash). But it returns a corrupted string in the Release mode on the x86_64 emulator (those where the RadioButtons crashes). There is a some kind of padding from unprintable characters before the string representation of the number. Because these characters before the number are not printed when they are for example in the Label.Text, it is hard to notice the problem. But it causes the crash, because the expressions in the curly brackets in the warning message should be replaced by their index and because of this flaw in the int.Parse method, there is someting like "{??????????????0}" instead of "{0}". I have no idea why is this happening.

I have logged the value of 2.ToString(), 12.ToString(), and 200.ToString() using the logcat messages. You can find the result in the x86_64 emulator in the image bellow. It can be seen that there are extra characters. The same code produces the correct texts in the Debug mode, or also in the release mode in x86 emulator.
![IntParse](https://github.com/dotnet/maui/assets/24872113/b0e87847-bd2d-4059-a579-b572b64b35fe)

To reproduce the problem, I have created a separate branch "5IntParse" in the repro project https://github.com/holecekp/MauiBugsRadioButton. The code in this branch just displays the result of ToString() for 2, 12, and 200 in the Labels (it is created so that it would not crash, just print the numbers). Then each of the ToString() results are compared to the expected string representation (for example 2.ToString() == "2"). The results can be seen below.

The expected result looks like this. There are three "OK" Labels showing that the texts equals with the expected value for all three numbers. This is the result from Release mode in the x86 emulator where there is no issue.
![release_x86](https://github.com/dotnet/maui/assets/24872113/9800ac61-2c9e-44d8-b332-420f003211c5)

However on the problematic x86_64 emulators where the RadioButtons crashes, the screen looks like this. The ToString() displays seemingly the correct values, but this is just because the additional incorrect characters before the numbers are invisible in the Label.Text. However, it can be seen that they do not compare to the expected values (2.ToString != "2") indicated by three "Incorrect!!!" messages.
![release_x86_64](https://github.com/dotnet/maui/assets/24872113/b38ff0d3-e14c-4eda-9614-57e0b4f62dcd)

Do you have any idea what could make int.Parse to behave so weird on some emulators? I have exported the properties of one of the problematic emulator in Android Studio in case that you would like to reproduce it using as similar emulator as possible. I thing however that the key difference is the "x86_64" processor architecture: 
[emulator properties.txt](https://github.com/user-attachments/files/16051072/emulator.properties.txt)

**Comment by jonathanpeppers** [comment]
@holecekp I think we move this issue to dotnet/runtime if the underlying problem is `int.Parse()`, thanks!
