### ISSUE TITLE
Copy font assets only works at second build

### ISSUE THREAD

**Issue by AlleSchonWeg** [dotnet/maui#23268]
### Description

I wondered, why me IconFont was not working in release mode. The font is in Resources\Fonts\ folder referenced in .csproj:

> 		
> 		<MauiFont Include="Resources\Fonts\*" />

I builded the app and deployed it to the simulator but no icon was shown. Hmm, in debug mode it works. So i looked in the obj folder. In Debug\net8.0-android\assets my ttf file was shown. In Release\net8.0-android\assets was no ttf file:
![image](https://github.com/dotnet/maui/assets/6727366/c3eb13ad-b87f-4e5f-a9af-40563487a707)
I started deleting obj/bin folders and rebuild. On the first build the assets folder keeps empty but with the second build the folder contains the ttf files and my icon font starts working in release mode:
![image](https://github.com/dotnet/maui/assets/6727366/3b88432e-2bb4-4fc4-89ac-a2a47f71859f)

The screenshots shows the default MAUI App with the included fonts. The behavior is the same.

### Steps to Reproduce

1. Create App from VS template
2. Delete obj/bin folders
3. Build Release and look at the assets folder --> folder emty
4. Build again. Folder not empty

### Version with bug

8.0.60 SR6

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

**Comment by AlleSchonWeg** [comment]
The same/similar happens in Debug config. I think the users don't notice this because in debug mode the app is usually already installed and the font files are already stored on the device. Or the user rebuild the app multiple times and then the assets are there.

**Comment by ninachen03** [comment]
I can repro this issue on the latest 17.11.0 Preview 2.1 (8.0.60 & 8.0.40)

**Comment by Stedy59** [comment]
I provided a similar issue/bug report on this months ago...

If you delete the "obj/bin" folders, and compile/deploy the application (debug OR release), it will ALWAYS leave some of your "resources" behind. Sometimes it is a font file, or two... Most of the time, it is the images... And rarely, a file from the "Assets" folder.

You have to compile, deploy, the compile again for it to "collect" all of your resources. It NEVER works on the first try after removing the "obj/bin" folders!

This happens on Android, and Windows...

**Comment by jfversluis** [comment]
@Stedy59 would you happen to have the issue number for that?

**Comment by Stedy59** [comment]
> @Stedy59 would you happen to have the issue number for that?

I looked and could not find the issue reported. I do remember commenting, such as I did here, on this issue months ago. 

The multiple compile/deploy regiment is required if you remove the "obj/bin" folders.

Also, on a side note... Since all of my "controls (15) / core" are in libraries, sometimes changes WILL NOT be included in subsequent builds unless I remove the "obj/bin" folders... I author custom code libraries for Zebra/Honeywell/Data Logic devices (Barcode scanners / RFID / etc.)

**Comment by MitchBomcanhao** [comment]
@Stedy59 was it this issue? https://github.com/dotnet/maui/issues/17149

**Comment by Stedy59** [comment]
> @Stedy59 was it [this](https://github.com/dotnet/maui/issues/17149) issue?

It is... Thank you for finding that! Hopefully they will address it this time around!

**Comment by MitchBomcanhao** [comment]
ok lets ping @jfversluis again as he was the one interested in it :)

**Comment by mattleibow** [comment]
@ninachen03 (or anyone really) are you able to get a binlog of the build not working properly?

I have been preparing for a demo all week and probably build like 20 brand new projects and they all just worked.

A binlog of a fail and a success will be most helpful.

**Comment by ninachen03** [comment]
It took me more than an hour, but unfortunately, I only managed to reproduce it once. I will continue to pay attention to this issue and add the log once I collect it.

**Comment by AlleSchonWeg** [comment]
@mattleibow 
I created two binlogs, but i don't want to upload it public.

**Comment by jfversluis** [comment]
@AlleSchonWeg find my email address on my GitHub profile and send it there or share a link to OneDrive if its too big to attach.

**Comment by algostax** [comment]
Microsoft Visual Studio 17.10.5
After removing obj/bin directories, rebuild & publish in IDE produces apk without fonts in assets directory.
After 2nd rebuild & publish these files are placed there finally (sometimes 3rd because random publish errors).
So - to be sure - I always compare apk content against the one with previous version, especially assets subdir :)

**Comment by AlleSchonWeg** [comment]
Hi @jfversluis or @mattleibow 
any news about this issue? I didn't receive any feedback after i send the binlogs.
Thx

**Comment by algostax** [comment]
Seems that using .Net CLI copies the fonts to assets on every publish in contrast to VS IDE
dotnet publish -f:net8.0-android34.0 -c:Release -p:AndroidPackageFormat=apk (...)

**Comment by janne-hmp** [comment]
The issue is most likely because Rebuild command launches design-time build in VS 2022 IDE, which leads to two same build processes running at the same time, causing random sharing violations. By contrast, Build command does not typically cause design-time build to run, hence things work on the second build. Or if you keep Visual Studio closed, and use `dotnet build` on command line things should work as well. Notably, if Visual Studio is open in the same configuration (e.g. Release) as where you run `dotnet build` with `no-incremental` parameter (meaning rebuild), the design-time build still starts and causes sharing violations with the `dotnet build` process. If you keep Visual Studio closed or in a different configuration (e.g. Debug) than what is used in `dotnet build`, the `dotnet build` command should always succeed correctly with all fonts included.

**Comment by cunhamauro** [comment]
The problem is still there.
And it is totally inconsistent, two times it did not load the resources (fonts and images), and at the third time it did...
The tip from @Stedy59 did it for me! Thank you very much!

**Comment by jfversluis** [comment]
People mention this might be related: https://github.com/dotnet/maui/issues/23364#issuecomment-2212495530

**Comment by dberroa** [comment]
I want to add in that I too am experiencing this and it's made it to a few of my actual published updates with users complaining all the font icons disappeared.

**Comment by alex3696** [comment]
This is really bad. 
In the unpacked Windows applications, you can manually copy fonts with icons.
In (APK) Android and (MSIX) Windows has to remove Bin, OBJ and rebuild many times again and again.
VS 17.13.2 
MAUI 9.0.40

**Comment by sjorsmiltenburg** [comment]
I don't know if it helps to know, but I believe this behaviour is not new for MAUI, and was also present in Xamarin Forms

**Comment by janne-hmp** [comment]
> I don't know if it helps to know, but I believe this behaviour is not new for MAUI, it is / was also present in Xamarin Forms.

Never seen this in Xamarin, but it’s been present in MAUI for a long time. It feels that this has lately (maybe over the last month, so perhaps MAUI 9.0.40 thing) gotten worse much on Windows at least with some MauiAsset directives failing in addition to MauiFont.

**Comment by RhomGit** [comment]
I have been pulling my hair out on this one for a while now, never figured out the cause.
Hopefully SR7 fixes it permanently,  thanks all.

**Comment by bcaceiro** [comment]
I face this issue so many times, using Visual Studio 2022 - haven't reproduced it in CLI since I don't use that much.

However, in my CI - haven't yet reproduced it

**Comment by AlleSchonWeg** [comment]
Is there a way to look in the aap or apk to verify that the font file is included before i upload it to play store?

**Comment by janne-hmp** [comment]
Sure, 7Zip for example opens aab and apk files. As far as I know, they are some sort of zip files.

**Comment by wagenheimer** [comment]
I’m still facing this issue on Visual Studio 2026 with Maui.

Dotnet 9.0.305 [C:\Program Files\dotnet\sdk]  
Dotnet 10.0.100-rc.1.25451.107 [C:\Program Files\dotnet\sdk]  

Cleaning or rebuilding the project sometimes resolves it, but it’s problematic. We typically test in Debug mode, switch to Release, and then generate builds. This issue has occurred multiple times, resulting in builds with icon problems being sent to clients.

**Comment by Stedy59** [comment]
> I’m still facing this issue on Visual Studio 2026 with Maui.
> 
> Dotnet 9.0.305 [C:\Program Files\dotnet\sdk] Dotnet 10.0.100-rc.1.25451.107 [C:\Program Files\dotnet\sdk]
> 
> Cleaning or rebuilding the project sometimes resolves it, but it’s problematic. We typically test in Debug mode, switch to Release, and then generate builds. This issue has occurred multiple times, resulting in builds with icon problems being sent to clients.

Every time I remove the bin/obj folders, I have to rebuild and deploy twice for all to be included.

**Comment by AlleSchonWeg** [comment]
To work around this i uninstall the app on simulator, then build the app in release mode and select Deploy in VS. If the deployed app has icons/fonts then i publish if not then delete, rebuild and deploy again until it works.

**Comment by AHComp** [comment]
Realy Microsoft ? We spend so much money for the VisualStudio license and this is the result ?
I migrate from xamarin and now this ?
It's 4 month ago the issue is reported and no fix ?

Version 17.14.16

**Comment by iamlawrencev** [comment]
We have noticed that rebuilding the project twice before publishing consistently resolves the issue. However, this does increase build times and requires our team to remember this extra step for certain projects.

Is there any update on a more permanent solution?

**Comment by dev-xam** [comment]
I also suffer from this kind of problem. I am developing MAUI .NET 9 mobile apps and got issue with not generated splash resources in Android release mode as described here: [https://github.com/dotnet/maui/issues/29097](url)
Quick solution is to rebuild solution twice before publish. Anyway - Maui develop team should think about solving this issue at Visual Studio level.

**Comment by Stedy59** [comment]
> Realy Microsoft ? We spend so much money for the VisualStudio license and this is the result ? I migrate from xamarin and now this ? It's 4 month ago the issue is reported and no fix ?
> 
> Version 17.14.16

It has been over one and a half years since I first reported this. And every time we bring focus to this issue, they keep kicking the can down the road... Now .Net11 planning???

Why not fix this foundational issue before building new "shinny widgets" that nobody desires?!?

@jfversluis @mattleibow @PureWeen @davidortinau

**Comment by mackayn** [comment]
> > Realy Microsoft ? We spend so much money for the VisualStudio license and this is the result ? I migrate from xamarin and now this ? It's 4 month ago the issue is reported and no fix ?
> > Version 17.14.16
> 
> It has been over one and a half years since I first reported this. And every time we bring focus to this issue, they keep kicking the can down the road... Now .Net11 planning???
> 
> Why not fix this foundational issue before building new "shinny widgets" that nobody desires?!?
> 
> [@jfversluis](https://github.com/jfversluis) [@mattleibow](https://github.com/mattleibow) [@PureWeen](https://github.com/PureWeen) [@davidortinau](https://github.com/davidortinau)

Well it's no better in .NET10, ported out .NET9 app over. iOS client and WinUI client are working fine but Android is a shitshow with fonts

```
Microsoft.Maui.FontManager: Warning: Unable to load font 'digital7monoitalic.ttf' from assets.

Java.Lang.RuntimeException: Font asset not found digital7monoitalic.ttf
   at Java.Interop.JniEnvironment.StaticMethods.CallStaticObjectMethod(JniObjectReference type, JniMethodInfo method, JniArgumentValue* args)
   at Java.Interop.JniPeerMembers.JniStaticMethods.InvokeObjectMethod(String encodedMember, JniArgumentValue* parameters)
   at Android.Graphics.Typeface.CreateFromAsset(AssetManager mgr, String path)
   at Microsoft.Maui.FontManager.LoadTypefaceFromAsset(String fontfamily, Boolean warning) in /_/src/Core/src/Fonts/FontManager.Android.cs:line 133
  --- End of managed Java.Lang.RuntimeException stack trace ---
java.lang.RuntimeException: Font asset not found digital7monoitalic.ttf
	at android.graphics.Typeface.createFromAsset(Typeface.java:1061)
	at crc6452ffdc5b34af3a0f.ContentViewGroup.n_onLayout(Native Method)
	at crc6452ffdc5b34af3a0f.ContentViewGroup.onLayout(ContentViewGroup.java:78)
	at android.view.View.layout(View.java:24421)
	at android.view.ViewGroup.layout(ViewGroup.java:6440)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24421)
	at android.view.ViewGroup.layout(ViewGroup.java:6440)
	at androidx.recyclerview.widget.RecyclerView$LayoutManager.layoutDecoratedWithMargins(RecyclerView.java:10523)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1780)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1682)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:747)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4737)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4459)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:5011)
	at android.view.View.layout(View.java:24421)
	at android.view.ViewGroup.layout(ViewGroup.java:6440)
	at androidx.viewpager2.widget.ViewPager2.onLayout(ViewPager2.java:535)
	at android.view.View.layout(View.java:24421)
	at android.view.ViewGroup.layout(ViewGroup.java:6440)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24421)
	at android.view.ViewGroup.layout(ViewGroup.java:6440)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24421)
	at android.view.ViewGroup.layout(ViewGroup.java:6440)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24421)
	at android.view.ViewGroup.layout(ViewGroup.java:6440)
	at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:149)
	at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:43)
	at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:2365)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:960)
	at android.view.View.layout(View.java:24421)
	at android.view.ViewGroup.layout(ViewGroup.java:6440)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24421)
	at android.view.ViewGroup.layout(ViewGroup.java:6440)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24421)
	at android.view.ViewGroup.layout(ViewGroup.java:6440)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24421)
	at android.view.ViewGroup.layout(ViewGroup.java:6440)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
	at android.view.View.layout(View.java:24421)
	at android.view.ViewGroup.layout(ViewGroup.java:6440)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:789)
	at android.view.View.layout(View.java:24421)
	at android.view.ViewGroup.layout(ViewGroup.java:6440)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4258)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3583)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2465)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9305)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1339)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1348)
	at android.view.Choreographer.doCallbacks(Choreographer.java:952)
	at android.view.Choreographer.doFrame(Choreographer.java:882)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1322)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8177)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)


```

**Comment by bcaceiro** [comment]
Can confirm - it is still happening with .net 10 + Visual Studio 2026. It's a hassle doing rebuilds / cleans for the dev loop

**Comment by mackayn** [comment]
> Can confirm - it is still happening with .net 10 + Visual Studio 2026. It's a hassle doing rebuilds / cleans for the dev loop

Same.

**Comment by rpatuelli** [comment]
Same issue for me, AOT and trimming disabled in Release mode, fontawesome icons are replaced by rectangles with a cross inside. I use .NET10 and all up to date MAUI libraries, VS 17.14.22. In Debug it seems working fine but the reason maybe as explained before.

**Comment by bcaceiro** [comment]
This is still an issue with latest MAUI version and workloads. It's really a hassle to clean and clean and then build to fix this.

**Comment by robertmaxted** [comment]
Debug works fine, Release is a nightmare. It's completely hit and miss as to whether the font files (ttf) will actually be present in the Release build. Any workarounds for this anyone?

**Comment by bcaceiro** [comment]
> Debug works fine, Release is a nightmare. It's completely hit and miss as to whether the font files (ttf) will actually be present in the Release build. Any workarounds for this anyone?

In my case is both debug and release - one thing is that I have multiple solutions in my project, and switching from A to B, is always a nightmare

**Comment by janne-hmp** [comment]
> Debug works fine, Release is a nightmare. It's completely hit and miss as to whether the font files (ttf) will actually be present in the Release build. Any workarounds for this anyone?

I used to have a similar issue, and had to change `MauiFont` to `MauiAsset` as per this workaround, which works on Android and Windows:

https://github.com/dotnet/maui/issues/23364#issuecomment-2212495530

Using this and deleting `bin` and `obj` folders before rebuild / publish, I have not experienced the issue anymore.

**Comment by robertmaxted** [comment]
> > Debug works fine, Release is a nightmare. It's completely hit and miss as to whether the font files (ttf) will actually be present in the Release build. Any workarounds for this anyone?
> 
> In my case is both debug and release - one thing is that I have multiple solutions in my project, and switching from A to B, is always a nightmare

Ahh, that's interesting. I have multiple projects in my solution and it's a 50/50 chance as to whether the fonts will actually be present! Hopefully Microsoft get a fix in for this soon. 🙏

**Comment by robertmaxted** [comment]
> > Debug works fine, Release is a nightmare. It's completely hit and miss as to whether the font files (ttf) will actually be present in the Release build. Any workarounds for this anyone?
> 
> I used to have a similar issue, and had to change `MauiFont` to `MauiAsset` as per this workaround, which works on Android and Windows:
> 
> https://github.com/dotnet/maui/issues/23364#issuecomment-2212495530
> 
> Using this and deleting `bin` and `obj` folders before rebuild / publish, I have not experienced the issue anymore.

I'll give that a try, thanks! 🤩

**Comment by MartyIX** [comment]
(There is now #33919 🤞)

**Comment by PureWeen** [comment]
if folks could test the nugets from
https://github.com/dotnet/maui/pull/33919

And see if it fixes that would be helpful!

**Comment by robertmaxted** [comment]
> if folks could test the nugets from [#33919](https://github.com/dotnet/maui/pull/33919)
> 
> And see if it fixes that would be helpful!

I certainly will on the next release mate 😊
