### ISSUE TITLE
Using Dispatcher.Dispatch to set MainPage throws NotImplementedException

### ISSUE THREAD

**Issue by idzson** [dotnet/maui#23449]
### Description

We have a custom navigation service and where we do our navigation on UI thread. Recently we decided to use Dispatcher.Dispatch() to do navigation on Ui thread. 
Everything works fine with one exception:
When setting MainPage application throws NotImplementedException: Either set MainPage or override CreateWindow.

Please see stack trace:
```
System.NotImplementedException: Either set MainPage or override CreateWindow.
   at Microsoft.Maui.Controls.Application.CreateWindow(IActivationState activationState)
   at Microsoft.Maui.Controls.Application.Microsoft.Maui.IApplication.CreateWindow(IActivationState activationState)
   at Microsoft.Maui.Platform.ApplicationExtensions.CreatePlatformWindow(IApplication application, UIWindowScene windowScene, NSDictionary[] states)
   at Microsoft.Maui.Platform.ApplicationExtensions.CreatePlatformWindow(IUIApplicationDelegate platformApplication, IApplication application, UIApplication uiApplication, NSDictionary launchOptions)
   at Microsoft.Maui.MauiUIApplicationDelegate.FinishedLaunching(UIApplication application, NSDictionary launchOptions)
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 58
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 94
   at MauiDispatcherTest.Program.Main(String[] args) in /Users/aid/Projects/MauiExperiments/DispatcherMauiTest/MauiDispatcherTest/Platforms/iOS/Program.cs:line 13
```

.NET workload version :
8.0.200-manifests.5638171e

### Steps to Reproduce

1. Create new MAUI project
2. Add dispatcher to set MainPage on App.xaml.cs like so:
`
public partial class App : Application
{
    public App()
    {
        InitializeComponent();

        Dispatcher.Dispatch(() =>
        {
            MainPage = new AppShell();
        });
    }
}`
3. Run application

### Link to public reproduction project repository

(https://github.com/idzson/DispatcherMauiTest)

### Version with bug

Nightly / CI build (Please specify exact version)

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android

### Did you find any workaround?

Workaround is using MainThread.BeginInvokeOnMainThread()

**Comment by ninachen03** [comment]
This issue has been verified using Visual Studio 17.11.0 Preview 2.1(8.0.61 & 8.0.3). Can repro it.
![image](https://github.com/dotnet/maui/assets/128687574/8722fff5-9273-4bdc-a8d8-0e7fc4b49bb1)

**Comment by PureWeen** [comment]
You have to give the system something to display when it first launches. 

The `CreateWindow` call inside App.xaml is being called from the platform because it needs something to show the user, so, you can't really delay setting the mainpage. 

the reason that `MainThread` works is because it's checking to see if you're on the `MainThread` and if it is then it just executes immediately

![image](https://github.com/dotnet/maui/assets/5375137/ad30ed0a-d168-4356-ae96-bdd3a9487032)

So, using `BeginInvokeOnMainThread` is no different then just not using `BeginInvokeOnMainThread` at all
