### ISSUE TITLE
Error with running a blank MAUI project

### ISSUE THREAD

**Issue by Kryst0fHaven** [dotnet/maui#23460]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/create
Operating System: windows 11

**MSB4018**
The "GenerateSplashAssets" task failed unexpectedly.
System.TypeInitializationException: The type initializer for 'SkiaSharp.SKImageInfo' threw an exception. ---> System.DllNotFoundException: Unable to load library 'libSkiaSharp'.
   at SkiaSharp.LibraryLoader.LoadLocalLibrary[T](String libraryName) in D:\a\1\s\binding\Binding.Shared\LibraryLoader.cs:line 38
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at SkiaSharp.SkiaApi.sk_colortype_get_default_8888() in D:\a\1\s\binding\Binding\SkiaApi.generated.cs:line 4404
   at SkiaSharp.SKImageInfo..cctor() in D:\a\1\s\binding\Binding\SKImageInfo.cs:line 46
   --- End of inner exception stack trace ---
   at Svg.Skia.SKSvgSettings..ctor() in /_/src/Svg.Skia/SKSvgSettings.cs:line 22
   at Svg.Skia.SKSvg..ctor() in /_/src/Svg.Skia/SKSvg.Model.cs:line 104
   at Microsoft.Maui.Resizetizer.SkiaSharpSvgTools..ctor(String filename, Nullable`1 baseSize, Nullable`1 backgroundColor, Nullable`1 tintColor, ILogger logger) in D:\a\_work\1\s\src\SingleProject\Resizetizer\src\SkiaSharpSvgTools.cs:line 23
   at Microsoft.Maui.Resizetizer.SkiaSharpTools.Create(Boolean isVector, String filename, Nullable`1 baseSize, Nullable`1 backgroundColor, Nullable`1 tintColor, ILogger logger) in D:\a\_work\1\s\src\SingleProject\Resizetizer\src\SkiaSharpTools.cs:line 21
   at Microsoft.Maui.Resizetizer.SkiaSharpAppIconTools..ctor(ResizeImageInfo info, ILogger logger) in D:\a\_work\1\s\src\SingleProject\Resizetizer\src\SkiaSharpAppIconTools.cs:line 11
   at Microsoft.Maui.Resizetizer.GenerateSplashAssets.Execute() in D:\a\_work\1\s\src\SingleProject\Resizetizer\src\GenerateSplashAssets.cs:line 27
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	MauiApp1 (net8.0-windows10.0.19041.0)	C:\Users\Vojtěch\.nuget\packages\microsoft.maui.resizetizer\8.0.40\buildTransitive\Microsoft.Maui.Resizetizer.After.targets	480

**Comment by jfversluis** [comment]
@mattleibow ?

**Comment by PureWeen** [comment]
@Kryst0fHaven can you attach a binlog?
https://github.com/dotnet/maui/wiki/Capturing-Binary-Logs

**Comment by Kryst0fHaven** [comment]
@PureWeen 
[MauiApp1_Debug_AnyCPU_net8.0-windows10.0.19041.0_Build_2024-07-13T23_54_31.6792538+02_00.zip](https://github.com/user-attachments/files/16203735/MauiApp1_Debug_AnyCPU_net8.0-windows10.0.19041.0_Build_2024-07-13T23_54_31.6792538%2B02_00.zip)

**Comment by Zhanglirong-Winnie** [comment]
This issue has been verified using Visual Studio 17.11.0 Preview 7.0(8.0.40 & 8.0.80). Not repro this issue.
