### ISSUE TITLE
MAUI Android System.InvalidOperationException: InvalidOperation_ConcurrentOperationsNotSupported

### ISSUE THREAD

**Issue by Elinares-82** [dotnet/maui#23479]
### Description

We ported our app to MAUI from XF but randomly we get the following error in Android and we are no able to find why.

System.Collections.Generic.Dictionary`2[[Microsoft.Maui.Controls.BindableProperty, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Controls.BindableObject.BindablePropertyContext, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].FindValue(BindableProperty )
System.Collections.Generic.Dictionary`2[[Microsoft.Maui.Controls.BindableProperty, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Controls.BindableObject.BindablePropertyContext, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].TryGetValue(BindableProperty key, BindablePropertyContext& value)
Microsoft.Maui.Controls.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes, SetterSpecificity specificity)
Microsoft.Maui.Controls.BindableObject.SetValue(BindableProperty property, Object value, SetterSpecificity specificity)
Microsoft.Maui.Controls.Setter.Apply(BindableObject target, SetterSpecificity specificity)
Microsoft.Maui.Controls.Style.ApplyCore(BindableObject bindable, Style basedOn, SetterSpecificity specificity)
Microsoft.Maui.Controls.Style.Microsoft.Maui.Controls.IStyle.Apply(BindableObject bindable, SetterSpecificity specificity)
Microsoft.Maui.Controls.MergedStyle.SetStyle(IStyle implicitStyle, IList`1 classStyles, IStyle style)
Microsoft.Maui.Controls.MergedStyle.set_Style(IStyle value)
Microsoft.Maui.Controls.NavigableElement.<>c.<.cctor>b__22_0(BindableObject bindable, Object oldvalue, Object newvalue)
Microsoft.Maui.Controls.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, SetterSpecificity specificity, Boolean silent)
Microsoft.Maui.Controls.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes, SetterSpecificity specificity)
Microsoft.Maui.Controls.BindableObject.SetValue(BindableProperty property, Object value)
Microsoft.Maui.Controls.NavigableElement.set_Style(Style value)
NeighborStore.Mobile.Shared.Views.CategoriesView.<InitializeComponent>_anonXamlCDataTemplate_4.LoadDataTemplate()
Microsoft.Maui.Controls.ElementTemplate.CreateContent()
Microsoft.Maui.Controls.Handlers.Items.TemplatedItemViewHolder.Bind(Object itemBindingContext, ItemsView itemsView, Action`1 reportMeasure, Nullable`1 size)
Microsoft.Maui.Controls.Handlers.Items.ItemsViewAdapter`2[[Microsoft.Maui.Controls.ReorderableItemsView, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Controls.Handlers.Items.IGroupableItemsViewSource, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].BindTemplatedItemViewHolder(TemplatedItemViewHolder templatedItemViewHolder, Object context)
Microsoft.Maui.Controls.Handlers.Items.StructuredItemsViewAdapter`2[[Microsoft.Maui.Controls.ReorderableItemsView, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Controls.Handlers.Items.IGroupableItemsViewSource, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].BindTemplatedItemViewHolder(TemplatedItemViewHolder templatedItemViewHolder, Object context)
Microsoft.Maui.Controls.Handlers.Items.ItemsViewAdapter`2[[Microsoft.Maui.Controls.ReorderableItemsView, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Controls.Handlers.Items.IGroupableItemsViewSource, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnBindViewHolder(ViewHolder holder, Int32 position)
Microsoft.Maui.Controls.Handlers.Items.StructuredItemsViewAdapter`2[[Microsoft.Maui.Controls.ReorderableItemsView, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Controls.Handlers.Items.IGroupableItemsViewSource, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnBindViewHolder(ViewHolder holder, Int32 position)
Microsoft.Maui.Controls.Handlers.Items.SelectableItemsViewAdapter`2[[Microsoft.Maui.Controls.ReorderableItemsView, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Controls.Handlers.Items.IGroupableItemsViewSource, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnBindViewHolder(ViewHolder holder, Int32 position)
Microsoft.Maui.Controls.Handlers.Items.GroupableItemsViewAdapter`2[[Microsoft.Maui.Controls.ReorderableItemsView, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Controls.Handlers.Items.IGroupableItemsViewSource, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnBindViewHolder(ViewHolder holder, Int32 position)
AndroidX.RecyclerView.Widget.RecyclerView.Adapter.n_OnBindViewHolder_Landroidx_recyclerview_widget_RecyclerView_ViewHolder_I(IntPtr jnienv, IntPtr native__this, IntPtr native_holder, Int32 position)
Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPLI_V(_JniMarshal_PPLI_V callback, IntPtr jnienv, IntPtr klazz, IntPtr p0, Int32 p1)

### Steps to Reproduce

Fill a CollectioncView and in the click on one of the items fill another CollectionView.

### Version with bug

8.0.61 SR6.1

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Did you find any workaround?

No, we tried change the way to load the data to the binded items property of the CollectionViews however this error is randomly.

### Relevant log output

```shell
System.Collections.Generic.Dictionary`2[[Microsoft.Maui.Controls.BindableProperty, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Controls.BindableObject.BindablePropertyContext, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].FindValue(BindableProperty )
System.Collections.Generic.Dictionary`2[[Microsoft.Maui.Controls.BindableProperty, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Controls.BindableObject.BindablePropertyContext, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].TryGetValue(BindableProperty key, BindablePropertyContext& value)
Microsoft.Maui.Controls.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes, SetterSpecificity specificity)
Microsoft.Maui.Controls.BindableObject.SetValue(BindableProperty property, Object value, SetterSpecificity specificity)
Microsoft.Maui.Controls.Setter.Apply(BindableObject target, SetterSpecificity specificity)
Microsoft.Maui.Controls.Style.ApplyCore(BindableObject bindable, Style basedOn, SetterSpecificity specificity)
Microsoft.Maui.Controls.Style.Microsoft.Maui.Controls.IStyle.Apply(BindableObject bindable, SetterSpecificity specificity)
Microsoft.Maui.Controls.MergedStyle.SetStyle(IStyle implicitStyle, IList`1 classStyles, IStyle style)
Microsoft.Maui.Controls.MergedStyle.set_Style(IStyle value)
Microsoft.Maui.Controls.NavigableElement.<>c.<.cctor>b__22_0(BindableObject bindable, Object oldvalue, Object newvalue)
Microsoft.Maui.Controls.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, SetterSpecificity specificity, Boolean silent)
Microsoft.Maui.Controls.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes, SetterSpecificity specificity)
Microsoft.Maui.Controls.BindableObject.SetValue(BindableProperty property, Object value)
Microsoft.Maui.Controls.NavigableElement.set_Style(Style value)
NeighborStore.Mobile.Shared.Views.CategoriesView.<InitializeComponent>_anonXamlCDataTemplate_4.LoadDataTemplate()
Microsoft.Maui.Controls.ElementTemplate.CreateContent()
Microsoft.Maui.Controls.Handlers.Items.TemplatedItemViewHolder.Bind(Object itemBindingContext, ItemsView itemsView, Action`1 reportMeasure, Nullable`1 size)
Microsoft.Maui.Controls.Handlers.Items.ItemsViewAdapter`2[[Microsoft.Maui.Controls.ReorderableItemsView, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Controls.Handlers.Items.IGroupableItemsViewSource, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].BindTemplatedItemViewHolder(TemplatedItemViewHolder templatedItemViewHolder, Object context)
Microsoft.Maui.Controls.Handlers.Items.StructuredItemsViewAdapter`2[[Microsoft.Maui.Controls.ReorderableItemsView, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Controls.Handlers.Items.IGroupableItemsViewSource, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].BindTemplatedItemViewHolder(TemplatedItemViewHolder templatedItemViewHolder, Object context)
Microsoft.Maui.Controls.Handlers.Items.ItemsViewAdapter`2[[Microsoft.Maui.Controls.ReorderableItemsView, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Controls.Handlers.Items.IGroupableItemsViewSource, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnBindViewHolder(ViewHolder holder, Int32 position)
Microsoft.Maui.Controls.Handlers.Items.StructuredItemsViewAdapter`2[[Microsoft.Maui.Controls.ReorderableItemsView, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Controls.Handlers.Items.IGroupableItemsViewSource, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnBindViewHolder(ViewHolder holder, Int32 position)
Microsoft.Maui.Controls.Handlers.Items.SelectableItemsViewAdapter`2[[Microsoft.Maui.Controls.ReorderableItemsView, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Controls.Handlers.Items.IGroupableItemsViewSource, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnBindViewHolder(ViewHolder holder, Int32 position)
Microsoft.Maui.Controls.Handlers.Items.GroupableItemsViewAdapter`2[[Microsoft.Maui.Controls.ReorderableItemsView, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Controls.Handlers.Items.IGroupableItemsViewSource, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnBindViewHolder(ViewHolder holder, Int32 position)
AndroidX.RecyclerView.Widget.RecyclerView.Adapter.n_OnBindViewHolder_Landroidx_recyclerview_widget_RecyclerView_ViewHolder_I(IntPtr jnienv, IntPtr native__this, IntPtr native_holder, Int32 position)
Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPLI_V(_JniMarshal_PPLI_V callback, IntPtr jnienv, IntPtr klazz, IntPtr p0, Int32 p1)
```

**Comment by PureWeen** [comment]
@StephaneDelcroix thoughts?

**Comment by Elinares-82** [comment]
> @StephaneDelcroix thoughts?

Hi Stephane,

No, the only issue related with mine is https://github.com/dotnet/maui/issues/18372, however, that issue was closed without a solution. This error that I'm reporting is randomly, the AppCenter get the error a display that information that I provided, something with a Dictionary when the properties are being binded and this just happens in Android.

**Comment by ysbakker** [comment]
I have a similar issue that occurs in the `GetValue()` method

```
   at System.Collections.Generic.Dictionary`2[[Microsoft.Maui.Controls.BindableProperty, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Controls.BindableObject.BindablePropertyContext, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].FindValue(BindableProperty key)
   at System.Collections.Generic.Dictionary`2[[Microsoft.Maui.Controls.BindableProperty, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Controls.BindableObject.BindablePropertyContext, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].TryGetValue(BindableProperty key, BindablePropertyContext& value)
   at Microsoft.Maui.Controls.BindableObject.GetValue(BindableProperty property) in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 159
   at Microsoft.Maui.Controls.BindableObject.get_BindingContext() in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 53
   at Microsoft.Maui.Controls.BindableObject.SetBinding(BindableProperty targetProperty, BindingBase binding, SetterSpecificity specificity) in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 322
   at Microsoft.Maui.Controls.Setter.Apply(BindableObject target, SetterSpecificity specificity) in D:\a\_work\1\s\src\Controls\src\Core\Setter.cs:line 75
   at Microsoft.Maui.Controls.TriggerBase.OnConditionChanged(BindableObject bindable, Boolean oldValue, Boolean newValue) in D:\a\_work\1\s\src\Controls\src\Core\Interactivity\TriggerBase.cs:line 112
   at Microsoft.Maui.Controls.BindingCondition.OnBoundPropertyChanged(BindableObject bindable, Object oldValue, Object newValue) in D:\a\_work\1\s\src\Controls\src\Core\Interactivity\BindingCondition.cs:line 99
   at Microsoft.Maui.Controls.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, SetterSpecificity specificity, Boolean silent) in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 633
   at Microsoft.Maui.Controls.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes, SetterSpecificity specificity) in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 559
   at Microsoft.Maui.Controls.BindingExpression.ApplyCore(Object sourceObject, BindableObject target, BindableProperty property, Boolean fromTarget, SetterSpecificity specificity) in D:\a\_work\1\s\src\Controls\src\Core\BindingExpression.cs:line 163
   at Microsoft.Maui.Controls.BindingExpression.Apply(Boolean fromTarget) in D:\a\_work\1\s\src\Controls\src\Core\BindingExpression.cs:line 58
   at Microsoft.Maui.Controls.BindingExpression.BindingExpressionPart.<PropertyChanged>b__50_0() in D:\a\_work\1\s\src\Controls\src\Core\BindingExpression.cs:line 742
   at Microsoft.Maui.Controls.DispatcherExtensions.DispatchIfRequired(IDispatcher dispatcher, Action action) in D:\a\_work\1\s\src\Controls\src\Core\DispatcherExtensions.cs:line 52
   at Microsoft.Maui.Controls.BindingExpression.BindingExpressionPart.PropertyChanged(Object sender, PropertyChangedEventArgs args) in D:\a\_work\1\s\src\Controls\src\Core\BindingExpression.cs:line 742
   at Microsoft.Maui.Controls.BindingExpression.WeakPropertyChangedProxy.OnPropertyChanged(Object sender, PropertyChangedEventArgs e) in D:\a\_work\1\s\src\Controls\src\Core\BindingExpression.cs:line 643
   at Microsoft.Maui.Controls.BindableObject.OnPropertyChanged(String propertyName) in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 382
   at Microsoft.Maui.Controls.Element.OnPropertyChanged(String propertyName) in D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:line 571
   at Microsoft.Maui.Controls.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, SetterSpecificity specificity, Boolean silent) in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 631
   at Microsoft.Maui.Controls.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes, SetterSpecificity specificity) in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 559
   at Microsoft.Maui.Controls.BindingExpression.ApplyCore(Object sourceObject, BindableObject target, BindableProperty property, Boolean fromTarget, SetterSpecificity specificity) in D:\a\_work\1\s\src\Controls\src\Core\BindingExpression.cs:line 163
   at Microsoft.Maui.Controls.BindingExpression.Apply(Boolean fromTarget) in D:\a\_work\1\s\src\Controls\src\Core\BindingExpression.cs:line 58
   at Microsoft.Maui.Controls.BindingExpression.BindingExpressionPart.<PropertyChanged>b__50_0() in D:\a\_work\1\s\src\Controls\src\Core\BindingExpression.cs:line 742
   at Microsoft.Maui.Controls.DispatcherExtensions.DispatchIfRequired(IDispatcher dispatcher, Action action) in D:\a\_work\1\s\src\Controls\src\Core\DispatcherExtensions.cs:line 52
   at Microsoft.Maui.Controls.BindingExpression.BindingExpressionPart.PropertyChanged(Object sender, PropertyChangedEventArgs args) in D:\a\_work\1\s\src\Controls\src\Core\BindingExpression.cs:line 742
   at Microsoft.Maui.Controls.BindingExpression.WeakPropertyChangedProxy.OnPropertyChanged(Object sender, PropertyChangedEventArgs e) in D:\a\_work\1\s\src\Controls\src\Core\BindingExpression.cs:line 643
   at Microsoft.Maui.Controls.BindableObject.OnPropertyChanged(String propertyName) in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 382
   at Microsoft.Maui.Controls.Element.OnPropertyChanged(String propertyName) in D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:line 571
   at Microsoft.Maui.Controls.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, SetterSpecificity specificity, Boolean silent) in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 631
   at Microsoft.Maui.Controls.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes, SetterSpecificity specificity) in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 559
   at Microsoft.Maui.Controls.BindingExpression.ApplyCore(Object sourceObject, BindableObject target, BindableProperty property, Boolean fromTarget, SetterSpecificity specificity) in D:\a\_work\1\s\src\Controls\src\Core\BindingExpression.cs:line 163
   at Microsoft.Maui.Controls.BindingExpression.Apply(Object sourceObject, BindableObject target, BindableProperty property, SetterSpecificity specificity) in D:\a\_work\1\s\src\Controls\src\Core\BindingExpression.cs:line 78
   at Microsoft.Maui.Controls.Binding.Apply(Object context, BindableObject bindObj, BindableProperty targetProperty, Boolean fromBindingContextChanged, SetterSpecificity specificity) in D:\a\_work\1\s\src\Controls\src\Core\Binding.cs:line 137
   at Microsoft.Maui.Controls.BindableObject.ApplyBindings(Boolean skipBindingContext, Boolean fromBindingContextChanged) in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 654
   at Microsoft.Maui.Controls.BindableObject.SetInheritedBindingContext(BindableObject bindable, Object value) in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 354
   at Microsoft.Maui.Controls.Element.SetChildInheritedBindingContext(Element child, Object context) in D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:line 695
   at Microsoft.Maui.Controls.Element.<OnBindingContextChanged>b__93_0(BindableObject child, Object bc) in D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:line 508
   at Microsoft.Maui.Controls.BindableObjectExtensions.PropagateBindingContext[Element](BindableObject self, IEnumerable`1 children, Action`2 setChildBindingContext) in D:\a\_work\1\s\src\Controls\src\Core\BindableObjectExtensions.cs:line 46
   at Microsoft.Maui.Controls.Element.OnBindingContextChanged() in D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:line 506
   at Microsoft.Maui.Controls.VisualElement.OnBindingContextChanged() in D:\a\_work\1\s\src\Controls\src\Core\VisualElement\VisualElement.cs:line 1231
   at Microsoft.Maui.Controls.View.OnBindingContextChanged() in D:\a\_work\1\s\src\Controls\src\Core\View\View.cs:line 255
   at Microsoft.Maui.Controls.BindableObject.SetInheritedBindingContext(BindableObject bindable, Object value) in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 355
   at Microsoft.Maui.Controls.Element.SetChildInheritedBindingContext(Element child, Object context) in D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:line 695
   at Microsoft.Maui.Controls.Element.<OnBindingContextChanged>b__93_0(BindableObject child, Object bc) in D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:line 508
   at Microsoft.Maui.Controls.BindableObjectExtensions.PropagateBindingContext[Element](BindableObject self, IEnumerable`1 children, Action`2 setChildBindingContext) in D:\a\_work\1\s\src\Controls\src\Core\BindableObjectExtensions.cs:line 46
   at Microsoft.Maui.Controls.Element.OnBindingContextChanged() in D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:line 506
   at Microsoft.Maui.Controls.VisualElement.OnBindingContextChanged() in D:\a\_work\1\s\src\Controls\src\Core\VisualElement\VisualElement.cs:line 1231
   at Microsoft.Maui.Controls.View.OnBindingContextChanged() in D:\a\_work\1\s\src\Controls\src\Core\View\View.cs:line 255
   at Microsoft.Maui.Controls.BindableObject.SetInheritedBindingContext(BindableObject bindable, Object value) in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 355
   at Microsoft.Maui.Controls.Element.SetChildInheritedBindingContext(Element child, Object context) in D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:line 695
   at Microsoft.Maui.Controls.Element.<OnBindingContextChanged>b__93_0(BindableObject child, Object bc) in D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:line 508
   at Microsoft.Maui.Controls.BindableObjectExtensions.PropagateBindingContext[Element](BindableObject self, IEnumerable`1 children, Action`2 setChildBindingContext) in D:\a\_work\1\s\src\Controls\src\Core\BindableObjectExtensions.cs:line 46
   at Microsoft.Maui.Controls.Element.OnBindingContextChanged() in D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:line 506
   at Microsoft.Maui.Controls.VisualElement.OnBindingContextChanged() in D:\a\_work\1\s\src\Controls\src\Core\VisualElement\VisualElement.cs:line 1231
   at Microsoft.Maui.Controls.View.OnBindingContextChanged() in D:\a\_work\1\s\src\Controls\src\Core\View\View.cs:line 255
   at Microsoft.Maui.Controls.BindableObject.SetInheritedBindingContext(BindableObject bindable, Object value) in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 355
   at Microsoft.Maui.Controls.Element.SetChildInheritedBindingContext(Element child, Object context) in D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:line 695
   at Microsoft.Maui.Controls.Element.SetParent(Element value) in D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:line 362
   at Microsoft.Maui.Controls.Element.OnChildAdded(Element child) in D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:line 525
   at Microsoft.Maui.Controls.VisualElement.OnChildAdded(Element child) in D:\a\_work\1\s\src\Controls\src\Core\VisualElement\VisualElement.cs:line 1236
   at Microsoft.Maui.Controls.Element.AddLogicalChild(Element element) in D:\a\_work\1\s\src\Controls\src\Core\Element\Element.cs:line 224
   at Microsoft.Maui.Controls.Handlers.Items.EmptyViewAdapter.OnBindViewHolder(ViewHolder holder, Int32 position) in D:\a\_work\1\s\src\Controls\src\Core\Handlers\Items\Android\Adapters\EmptyViewAdapter.cs:line 155
   at AndroidX.RecyclerView.Widget.RecyclerView.Adapter.n_OnBindViewHolder_Landroidx_recyclerview_widget_RecyclerView_ViewHolder_I(IntPtr jnienv, IntPtr native__this, IntPtr native_holder, Int32 position) in D:\a\_work\1\s\generated\androidx.recyclerview.recyclerview\obj\Release\net8.0-android\generated\src\AndroidX.RecyclerView.Widget.RecyclerView.cs:line 591
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPLI_V(_JniMarshal_PPLI_V callback, IntPtr jnienv, IntPtr klazz, IntPtr p0, Int32 p1) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 176
```

**Comment by Uridel** [comment]
We are noticing quiet a lot of these crashes in our app as well. Other than just putting a lock on any call that uses SetInheritedBindingContext i don't really see what to do here. Has there been any progress with regards to this issue?
