### ISSUE TITLE
Type binding Error with .NET 9 Preview 6

### ISSUE THREAD

**Issue by davidortinau** [dotnet/maui#23551]
### Description

Testing .NET Hot Reload and .NET 9 Preview 6 I'm getting these errors:

```
Exception has occurred: CLR/System.TypeLoadException
An unhandled exception of type 'System.TypeLoadException' occurred in Mono.Android.Runtime.dll: 'Could not resolve type with token 01000075 from typeref (expected class 'Microsoft.Maui.Controls.Generated.<GeneratedBindableObjectExtensions_g>F340249EF3F4705EB00F29166AE5B0DC4FEF24016399EDCA95F8D25AC35F9B242__GeneratedBindableObjectExtensions' in assembly '')'
   at Android.Runtime.RuntimeNativeMethods.monodroid_debugger_unhandled_exception(Exception e)
   at Android.Runtime.JNINativeWrapper._unhandled_exception(Exception e)
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(_JniMarshal_PP_V callback, IntPtr jnienv, IntPtr klazz)
   at SharpNine.FirstPage.Build() in /Users/davidortinau/work/SharpNine/FirstPage.cs:line 41
   at SharpNine.FirstPage.<.ctor>b__2_1()
   at Java.Lang.Thread.RunnableImplementor.Run()
   at Java.Lang.IRunnableInvoker.n_Run(IntPtr jnienv, IntPtr native__this)
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(_JniMarshal_PP_V callback, IntPtr jnienv, IntPtr klazz)
```

```
Exception has occurred: CLR/System.TypeLoadException
An unhandled exception of type 'System.TypeLoadException' occurred in Microsoft.iOS.dll: 'Could not resolve type with token 01000072 from typeref (expected class 'Microsoft.Maui.Controls.Generated.<GeneratedBindableObjectExtensions_g>F340249EF3F4705EB00F29166AE5B0DC4FEF24016399EDCA95F8D25AC35F9B242__GeneratedBindableObjectExtensions' in assembly '')'
   at ObjCRuntime.Runtime.ThrowException(IntPtr gchandle)
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName)
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)
   at SharpNine.Program.Main(String[] args) in /Users/davidortinau/work/SharpNine/Platforms/iOS/Program.cs:line 14
```

From changing anything in this method:

```csharp
void Build()
	{
		Content = new VerticalStackLayout
		{
			Spacing = 20,
			Margin = 20,
			Children = {
				(label = new Label {  
					Text = "Welcome to .NET MAUI!",
					FontSize = 64,
					TextColor = Colors.Blue
				}),
				(entry = new Entry { Placeholder = "Enter your name" }),
			}
		};

		label.SetBinding(Label.TextProperty, static (Entry e) => e.Text, source: entry);
	}
```

The binding functions as I expect. @simonrozsival I suspect this is related to the compiled bindings work.

Commenting out the binding allows .NET Hot Reload to succeed without error. Returning to a non-compiled binding works as well:

```sharp
label.SetBinding(Label.TextProperty, new Binding("Text", source: entry));
```

[SharpNine.zip](https://github.com/user-attachments/files/16169556/SharpNine.zip)

### Version with bug

9.0.0-preview.6.24327.7

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, macOS

**Comment by simonrozsival** [comment]
I wonder if we can do something about this on our end or if this is some limitation of source generators and hot reload. It seems to me that the type name of the source generated class changes with every roslyn compilation:

In one instance, the type name before the update (obtained by listing types in the assembly via reflection) was:
```
Microsoft.Maui.Controls.Generated.<GeneratedBindableObjectExtensions_g>F8EAA02179AB123506AE8CCA05556D5DDF2EA0B3D7CB088DAB38382B52A1722F6__GeneratedBindableObjectExtensions
```
And the exception message said:
```
Microsoft.Maui.Controls.Generated.<GeneratedBindableObjectExtensions_g>F66D27BD33A914CF7D49F79ED8311EF0A6D6053E8F683ECBDAD481FAF1B9ED440__GeneratedBindableObjectExtensions
```

The `UpdateApplicationEvent` delegate was called with two types (`obj`) and none of them was the `<GeneratedBindableObjectExtensions_g>XYZ_GeneratedBindableObjectExtensions`.

I'm not sure who on the Roslyn team or on the tooling team could help us diagnose this.

**Comment by simonrozsival** [comment]
The mangled names were caused by the class being `file` scoped. We changed it to `internal` in https://github.com/dotnet/maui/pull/23116 and this should resolve the issue in P7.
