### ISSUE TITLE
Workload 8.0.61 breaks Mono interpreter on MacCatalyst.

### ISSUE THREAD

**Issue by jdngray77** [dotnet/maui#23577]
### Description

This week, our build inexplicably broke. 

It started producing copies of our app which were not capable of talking to the server and instead produced runtime exceptions. See output below.

We identified the cause to be the Mono interpreter no longer functioning correctly, failing to handle dynamically generated code used in our web interface.

We understand that dynamically generated code has limitations on MacCatalyst, and so in accordance to the [docs](https://learn.microsoft.com/en-us/dotnet/maui/macios/interpreter?view=net-maui-8.0) we have always enabled the Mono interpreter with `<UseInterpreter>true</UseInterpreter>`.

We've tried downgrading to SDK version 8.0.302 with no effect, ~~and using  `<MtouchInterpreter>all</MtouchInterpreter>` in place of `UseInterpreter` also to no effect.~~

This seems to be a fault that was introduced with an update in the MAUI workload, from `8.0.40` at the start of this week (W/C 8th july 2024) to `8.0.61`.  

Downgrading with the use of a rollback file to `8.0.40` restores our build artefacts functionality : `dotnet workload install maui-maccatalyst --from-rollback-file https://maui.blob.core.windows.net/metadata/rollbacks/8.0.40.json`

### Steps to Reproduce

1. Checkout the repro below
2. Restore workload `8.0.61`
3. Clean & Build
4. Observe that when the button is clicked, `PlatformNotSupportedException` is written to the console.
5. Restore workload `8.0.40`
6. Clean & Build
7. Observe that when the button is clicked, dynamically generated code writes "Hello, Reflection.Emit!" to the console.

### Link to public reproduction project repository

https://github.com/jdngray77/MauiReproEmit

### Version with bug

8.0.61 SR6.1

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.40 SR5

### Affected platforms

macOS

### Affected platform versions

Sonoma 14.5 (23F79)

### Did you find any workaround?

Yes.

> Edit:
> 1) As per the comments; Replacing `<UseInterpreter>true</UseInterpreter>` with `<MtouchInterpreter>all</MtouchInterpreter>`

2) We can use a rollback file to restore an older MAUI workload, prior to the issue being introduced

`dotnet workload install maui-maccatalyst --from-rollback-file https://maui.blob.core.windows.net/metadata/rollbacks/8.0.40.json`

### Relevant log output

```shell
Exception Type: System.PlatformNotSupportedException
Exception Message: PlatformNotSupported_ReflectionEmit
Stack Trace:    at System.Reflection.Emit.AssemblyBuilder.ThrowDynamicCodeNotSupported()
   at System.Reflection.Emit.AssemblyBuilder.EnsureDynamicCodeSupported()
   at System.Reflection.Emit.RuntimeAssemblyBuilder..ctor(AssemblyName , AssemblyBuilderAccess )
   at System.Reflection.Emit.AssemblyBuilder.DefineDynamicAssembly(AssemblyName , AssemblyBuilderAccess )
   at System.Reflection.DispatchProxyGenerator.ProxyAssembly..ctor(AssemblyLoadContext )
   at System.Reflection.DispatchProxyGenerator.<>c.<CreateProxyInstance>b__6_0(AssemblyLoadContext x)
   at System.Runtime.CompilerServices.ConditionalWeakTable`2[[System.Runtime.Loader.AssemblyLoadContext, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Reflection.DispatchProxyGenerator.ProxyAssembly, System.Reflection.DispatchProxy, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].GetValueLocked(AssemblyLoadContext , CreateValueCallback )
   at System.Runtime.CompilerServices.ConditionalWeakTable`2[[System.Runtime.Loader.AssemblyLoadContext, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Reflection.DispatchProxyGenerator.ProxyAssembly, System.Reflection.DispatchProxy, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].GetValue(AssemblyLoadContext , CreateValueCallback )
   at System.Reflection.DispatchProxyGenerator.CreateProxyInstance(Type , Type , String , String )
   at System.Reflection.DispatchProxy.Create[WebServiceSoap,ServiceChannelProxy]()
   at System.ServiceModel.Channels.ServiceChannelProxy.CreateProxy[WebServiceSoap](MessageDirection direction, ServiceChannel serviceChannel)
   at System.ServiceModel.Channels.ServiceChannelFactory.CreateProxy[WebServiceSoap](MessageDirection direction, ServiceChannel serviceChannel)
   at System.ServiceModel.Channels.ServiceChannelFactory.CreateChannel[WebServiceSoap](EndpointAddress address, Uri via)
   at System.ServiceModel.ChannelFactory`1[[XXX.XXX.XXX.XXX.XXX, XXX.XXX.XXX.XXX, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null]].CreateChannel(EndpointAddress address, Uri via)
   at System.ServiceModel.ChannelFactory`1[[XXX.XXX.XXX.XXX.XXX, XXX.XXX.XXX.XXX, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null]].CreateChannel()
   at System.ServiceModel.ClientBase`1[[XXX.XXX.XXX.XXX.XXX, XXX.XXX.XXX.XXX, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null]].CreateChannel()
   at System.ServiceModel.ClientBase`1[[XXX.XXX.XXX.XXX.XXX, XXX.XXX.XXX.XXX, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null]].CreateChannelInternal()
   at System.ServiceModel.ClientBase`1[[XXX.XXX.XXX.XXX.XXX, XXX.XXX.XXX.XXX, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null]].get_Channel()
   ...
```
```

**Comment by timlajaunie** [comment]
We're experiencing the same with iOS targets.  The rollback workaround does not appear to be possible when workload 8.0.61 is installed by multiple sources, such as the SDK and Visual Studio in Windows.

**Comment by PureWeen** [comment]
@rolfbjarne  ?

**Comment by ninachen03** [comment]
This issue has been verified using Visual Studio 17.16.12 (build 410)(8.0.61). Can be reproduced
![image](https://github.com/user-attachments/assets/fa622553-42da-493a-a359-7f5a183a9cba)

**Comment by BrzVlad** [comment]
On the new version, the runtime config json explicitly sets `"System.Runtime.CompilerServices.RuntimeFeature.IsDynamicCodeSupported": false`. The previous, working version, was not declaring this property at all, so it was defaulting to true. I'm not familiar where exactly this configuration file is generated, but so far the issue seems to be within the build tasks.

**Comment by dalexsoto** [comment]
@kotlarmilos is this the result of https://github.com/xamarin/xamarin-macios/pull/20687 ?

**Comment by ivanpovazan** [comment]
@dalexsoto I think the problem is introduced with this change: https://github.com/xamarin/xamarin-macios/commit/a72bb30aca5f71b7c53d49570866d0c91a8a9a14 

`MtouchInterpreter` should inherit the value from `UseInterpreter` but the order of evaluation for `MtouchInterpreter` seems to be wrong. From the build log we can see that [Xamarin.Shared.Sdk.targets](https://github.com/xamarin/xamarin-macios/blob/d1ec7a793f46f615f5f08f0a60f4c6daa6a1b671/dotnet/targets/Xamarin.Shared.Sdk.targets#L146) gets imported before [Xamarin.Shared.props](https://github.com/xamarin/xamarin-macios/blob/d1ec7a793f46f615f5f08f0a60f4c6daa6a1b671/msbuild/Xamarin.Shared/Xamarin.Shared.props#L308). The former uses the value of `MtouchInterpreter` to determine `DynamicCodeSupport` setting. However, the inheritance is determined in the latter props file, which causes the wrong value for `DynamicCodeSupport` to be set.

<img width="799" alt="Screenshot 2024-07-16 at 18 45 57" src="https://github.com/user-attachments/assets/c97b7f01-2372-4f9d-bedf-83060eed1c50">

---
@jdngray77 could you please try again building/running your repro project by adjusting it in the following way:
```xml
<!-- <UseInterpreter>true</UseInterpreter> -->
<MtouchInterpreter>all</MtouchInterpreter>
```

I was able to execute your sample successfully with the mentioned change.

**Comment by edetoc** [comment]
@ivanpovazan  I just tried the workaround you mentionned above with the sample @jdngray77 provided. Tried it for iOS. I confirm this workaround works with MAUI workload 8.0.61.

**Comment by jdngray77** [comment]
@ivanpovazan Verified here also, `MTouchInterpreter` resolves dynamic code generation both the repro and in our production repo using workload `8.0.61`. Apologies; perhaps my testing with it before was too superficial to see results.

**Comment by giorgitedi** [comment]
I tried setting <MtouchInterpreter>all</MtouchInterpreter> and it also worked for us but previously we were using <MtouchInterpreter>-all</MtouchInterpreter> to AOT compile all assemblies.

What if we want to continue using AOT? because as described [here](https://learn.microsoft.com/en-us/dotnet/maui/macios/interpreter?view=net-maui-8.0) "App execution speed will be slower because interpreted code runs more slowly than AOT compiled code."

**Comment by ivanpovazan** [comment]
@PureWeen FYI: https://github.com/xamarin/xamarin-macios/pull/20912#issuecomment-2236507086
