### ISSUE TITLE
Android Crashes with "This window is already associated with an active Activity" when we use AppFlip

### ISSUE THREAD

**Issue by RobertHassfeld** [dotnet/maui#23645]
### Description

We used an OAuth-based App Flip linking to connect to GoogleHome in our App. [account-linking/app-flip-overview](https://developers.google.com/identity/account-linking/app-flip-overview)

Maybe this issue is related to: 
[MAUI Android build crashes when app is reopened from background. It throws the exception: 'Window was already created.](https://github.com/dotnet/maui/issues/18692)

[Add better exception if user opens second activity](https://github.com/dotnet/maui/pull/21492/files)

### Steps to Reproduce

Perform the following steps for testing:

1. Starts the [identity-appflip-tester-android tool](https://github.com/googlesamples/identity-appflip-tester-android)
2. Add the following parameter to the string.xml file

- Package Name: com.companyname.appflip
- Intent Filter Action Name: com.app.appflip
- Client ID: 123
- Fingerprint of Signing Certificate: Your own device signature

3. Start the AppFlip application
4. Open the Android Tester Tool
5. Click on "Try to flip"
6. The flip will open the AppFlip application and crash
7. Open the Android Tester Tool again
8. Click again on "Try to flip"
9. This time the AppFlip application should open in the Android Tester Tool

### Link to public reproduction project repository

https://github.com/RobertHassfeld/AppFlip/tree/main

### Version with bug

8.0.40 SR5

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12, 13, 14

### Did you find any workaround?

No workaround found.

### Relevant log output

```shell
[ERROR] FATAL UNHANDLED EXCEPTION: System.InvalidOperationException: This window is already associated with an active Activity (AppFlip.MainActivity). Please override CreateWindow on AppFlip.App to add support for multiple activities https://aka.ms/maui-docs-create-windowor set the LaunchMode to SingleTop on AppFlip.AppFlipActivity.
at Microsoft.Maui.Platform.ApplicationExtensions.CreatePlatformWindow(Activity activity, IApplication application, Bundle savedInstanceState) in D:\a\_work\1\s\src\Core\src\Platform\Android\ApplicationExtensions.cs:line 52
at Microsoft.Maui.MauiAppCompatActivity.OnCreate(Bundle savedInstanceState) in D:\a\_work\1\s\src\Core\src\Platform\Android\MauiAppCompatActivity.cs:line 35
at AppFlip.AppFlipActivity.OnCreate(Bundle savedInstanceState) in /Users/rhassfeld/Projekte/TestApps/AppFlip/AppFlip/Platforms/Android/AppFlipActivity.cs:line 35
at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_(IntPtr jnienv, IntPtr native__this, IntPtr native_savedInstanceState) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net8.0/android-34/mcw/Android.App.Activity.cs:line 3082
at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPL_V(_JniMarshal_PPL_V callback, IntPtr jnienv, IntPtr klazz, IntPtr p0) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 125
```

**Comment by RobertHassfeld** [comment]
Further information. The CreateWindow function does not work because OnCreate is called with bundle = null and then CreateWindow is triggered. All necessary information is available in the CreateWindow method, but then the OnCreate method throws this exception and all information in the Intent is removed.

**Comment by PureWeen** [comment]
you need to remove this line

https://github.com/RobertHassfeld/AppFlip/blob/main/AppFlip/App.xaml.cs#L9

and instantiate your window inside createwindow

 return new Window(new AppShell())

**Comment by RobertHassfeld** [comment]
Thank you for the solution. It works in my test project. Unfortunately, it has a big impact on our project. So we have to change the whole initialization process of the app.
