### ISSUE TITLE
CollectionView DisconnectHandler SelectionMode=Multiple Windows exception

### ISSUE THREAD

**Issue by siem300** [dotnet/maui#23649]
### Description

In our apps we have an issue with the DisconnectHandler of the CollectionView. When we call the DisconnectHandler method for the CollectionView when the SelectionMode is set to Multiple the apps throw an exception.

Exception:
 {"PlatformView cannot be null here"}

The handler changes the selecteditems while it is being disconnected and this results in a change where the PlatformView is needed.

This issue only occurs on Windows. Android and iOS work as intended.

### Steps to Reproduce

1. Start the attached reproduction project
2. Select either 'Navigate as modal' or 'Navigate'
3. Select one or more of the test strings
4. Select the 'Navigate back' button
5. App throws an exception but doesn't crash (in our case other code doesn't get executed because of this)

### Link to public reproduction project repository

https://github.com/siem300/Maui-CollectionViewDisconnectHandlerWindows

### Version with bug

8.0.60 SR6

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Did you find any workaround?

A possible workaround is setting the selectionmode to none. The problem with this is that our page doesn't know which controls it is disconnecting so we have to type check them.

### Relevant log output

```shell
at Microsoft.Maui.Handlers.ViewHandler`2.get_PlatformView()
   at Microsoft.Maui.Controls.Handlers.Items.ItemsViewHandler`1.get_ListViewBase()
   at Microsoft.Maui.Controls.Handlers.Items.SelectableItemsViewHandler`1.UpdateVirtualSelection()
   at Microsoft.Maui.Controls.Handlers.Items.SelectableItemsViewHandler`1.PlatformSelectionChanged(Object sender, SelectionChangedEventArgs args)
   at WinRT._EventSource_global__Microsoft_UI_Xaml_Controls_SelectionChangedEventHandler.EventState.<GetEventInvoke>b__1_0(Object sender, SelectionChangedEventArgs e)
   at ABI.Microsoft.UI.Xaml.Controls.SelectionChangedEventHandler.Do_Abi_Invoke(IntPtr thisPtr, IntPtr sender, IntPtr e)
--- End of stack trace from previous location ---
```

**Comment by RoiChen001** [comment]
I can repro this issue at Windows platform on the latest 17.11.0 Preview 4.0 (8.0.60&8.0.40).
