### ISSUE TITLE
[WINDOWS, 9.0 Preview 6] AppShell.Navigated throws System.ArgumentException in Microsoft.Maui.FontManager

### ISSUE THREAD

**Issue by janne-hmp** [dotnet/maui#23678]
### Description

We see in Windows app the following handled exception: `System.ArgumentException`: The parameter is incorrect. `Assets/Fonts/Lato.ttf` is not a valid absolute URI. It is thrown by `WinRTUriRuntimeClassFactory.CreateUriForMarshaling(string uri)`, and logged by `Microsoft.Maui.FontManager`. I do not have a Fonts directory under Assets (but rather under Resources).

It happens in `AppShell.Navigated` that has been called by `AppShell.Appearing`.

That font seems to be some sort of a default font. I tried adding it to `Resources\Fonts`, but it did not seem to help with the exception.

### Steps to Reproduce

1. Start GnollHackM on Windows.
2. SentrySDK logs the exception.

### Link to public reproduction project repository

https://github.com/hyvanmielenpelit/GnollHack

### Version with bug

9.0.0-preview.6.24327.7

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 11

### Did you find any workaround?

The exception is handled, so this only seems to produce unnecessary logging. It might cause some problems elsewhere potentially.

### Relevant log output

```
exception
System.ArgumentException: The parameter is incorrect.

Assets/Fonts/Lato.otf is not a valid absolute URI.
Error
13:57:57
Microsoft.Maui.FontManager
Error loading font 'Assets/Fonts/Lato.ttf'.

{
exception_message: 
The parameter is incorrect.

Assets/Fonts/Lato.ttf is not a valid absolute URI.
}
Error
13:57:57
navigation
AppShell.Navigated

{
from: ,
Source: ShellItemChanged,
to: //MainPage
}
Info
13:57:57
navigation
App.PageAppearing

{
Page: MainPage
}
Info
13:57:57
navigation
App.PageAppearing

{
Page: AppShell
}
Info
13:57:56
ui.lifecycle
AppShell.Appearing
Info
13:57:56
```

**Comment by janne-hmp** [comment]
The problem seems to be that `Assets/Fonts/Lato.ttf` is not an **absolute** URI, not so much that the file does not exist.

**Comment by PureWeen** [comment]
@janne-hmp are you not seeing this issue on net8?

**Comment by janne-hmp** [comment]
> @janne-hmp are you not seeing this issue on net8?

Not sure, since our app is built using .NET 9, since SkiaSharp did not work properly in .NET 9 MAUI (at least for our app). .NET 9 in turn worked well.

**Comment by QianaJiao** [comment]
I can repro this issue at Windows platform on the latest main 17.12.0 Preview 2.0 (MAUI Version: 9.0.0-preview.6.24327.7 & 9.0.0-preview.5.24307.10). 
![image](https://github.com/user-attachments/assets/bbe696dc-8250-41e6-afb8-0d3d450bdbd7)

**Comment by beeradmoore** [comment]
I am also getting this issue, but I am on MAUI 8.0.80. Same code runs fine on Windows.

```
System.ArgumentException: The parameter is incorrect.

Assets/Fonts/ProximaNovaSemiBold.otf is not a valid absolute URI.
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.System.WinRTUriRuntimeClassFactory.CreateUriForMarshaling(String uri)
   at ABI.System.Uri.CreateMarshaler2(Uri value)
   at Microsoft.Graphics.Canvas.Text.CanvasFontSet._ICanvasFontSetFactory.Create(Uri uri)
   at Microsoft.Graphics.Canvas.Text.CanvasFontSet..ctor(Uri uri)
   at Microsoft.Maui.FontManager.FindFontFamilyName(String fontFile)
```

**Comment by nicop85** [comment]
Facing the same problem here. I'm working with MAUI 8.0.72.
I tried to change the font alias to the same used for the .ttf file name, but it didn't work for me.
