### ISSUE TITLE
Raygun4Maui throws ArgumentNullException in both Android/iOS Release build 

### ISSUE THREAD

**Issue by minglu** [dotnet/maui#23964]
### Description

I am using Raygun4Maui for crashing reporting, it works fine under debug mode but throws ArgumentNullException in Release mode. I created the support ticket on Raygun side as well, but I wonder if linker/trimmer causes the issue. 

Here is my iOS release setting in csproj (default for Android)

```
	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net8.0-ios|AnyCPU'">
		<CreatePackage>false</CreatePackage>
		<EnableAssemblyILStripping>false</EnableAssemblyILStripping>
		<UseInterpreter>true</UseInterpreter>
		<NoSymbolStrip>true</NoSymbolStrip>
		<RuntimeIdentifier>ios-arm64</RuntimeIdentifier>
		<CodesignProvision>Automatic</CodesignProvision>
		<CodesignKey>iPhone Dist</CodesignKey>
	</PropertyGroup>
	<PropertyGroup>
		<CodesignEntitlements Condition="$(TargetFramework.EndsWith('-ios'))">Platforms\iOS\Entitlement.plist</CodesignEntitlements>
	</PropertyGroup>
	<ItemGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">
		<BundleResource Include="Platforms\iOS\PrivacyInfo.xcprivacy" LogicalName="PrivacyInfo.xcprivacy" />
	</ItemGroup>
	<ItemGroup>
		<TrimmerRootAssembly Include="System.Collections.Immutable" RootMode="library" />
	</ItemGroup>
```

### Version with bug

8.0.70 SR7

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, I was *not* able test on other platforms

### Did you find any workaround?

iOS: 
```
<MtouchLink>None</MtouchLink>
```

### Relevant log output

```shell
Android:
[DOTNET] Android Unhandled Exception: System.ArgumentNullException: ArgumentNull_Generic Arg_ParamName_Name, key
[DOTNET]    at System.Collections.Generic.Dictionary 2[[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Mindscape.Raygun4Net.Diagnostics.PEDebugInformation, Mindscape.Raygun4Net.NetCore.Common, Version=11.0.0.0, Culture=neutral, PublicKeyToken=d595e487e4f9f950]].TryInsert(String key, PEDebugInformation value, InsertionBehavior behavior)
[DOTNET]    at System.Collections.Generic.Dictionary 2[[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Mindscape.Raygun4Net.Diagnostics.PEDebugInformation, Mindscape.Raygun4Net.NetCore.Common, Version=11.0.0.0, Culture=neutral, PublicKeyToken=d595e487e4f9f950]].Add(String key, PEDebugInformation value)
[DOTNET]    at System.Linq.Enumerable.ToDictionary[PEDebugInformation,String](IEnumerable 1 source, Func 2 keySelector, IEqualityComparer 1 comparer)
[DOTNET]    at System.Linq.Enumerable.ToDictionary[PEDebugInformation,String](IEnumerable 1 source, Func 2 keySelector)
[DOTNET]    at Mindscape.Raygun4Net.RaygunErrorMessageBuilder.GetDebugInfoForStackFrames(IEnumerable 1 frames)
[DOTNET]    at Mindscape.Raygun4Net.RaygunErrorMessageBuilder.Build(Exception exception)
[DOTNET]    at Mindscape.Raygun4Net.RaygunMessageBuilder.SetExceptionDetails(Exception exception)
[DOTNET]    at Mindscape.Raygun4Net.RaygunClientBase.BuildMessage(Exception exception, IList 1 tags, IDictionary userCustomData, RaygunIdentifierMessage userInfo, Action 1 customiseMessage)
[DOTNET]    at Raygun4Maui.RaygunMauiClient.SendInBackground(Exception exception, IList 1 tags, IDictionary userCustomData, RaygunIdentifierMessage userInfo)


iOS:
iOS Unhandled Exception: System.ArgumentNullException: ArgumentNullGeneric ArgParamName_Name, key at System.Linq.Enumerable.ToDictionary[PEDebugInformation,String](IEnumerable1 source, Func2 keySelector) at Mindscape.Raygun4Net.RaygunErrorMessageBuilder.GetDebugInfoForStackFrames(IEnumerable1 frames) at Mindscape.Raygun4Net.RaygunErrorMessageBuilder.Build(Exception exception) at Mindscape.Raygun4Net.RaygunMessageBuilder.SetExceptionDetails(Exception exception) at Mindscape.Raygun4Net.RaygunClientBase.BuildMessage(Exception exception, IList1 tags, IDictionary userCustomData, RaygunIdentifierMessage userInfo, Action1 customiseMessage) at Raygun4Maui.RaygunMauiClient.SendInBackground(Exception exception, IList1 tags, IDictionary userCustomData, RaygunIdentifierMessage userInfo) at App.ViewModel.LoginViewModel.SignInAsync() at ObjCRuntime.Runtime.ThrowException(IntPtr gchandle) at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName) at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)
```

**Comment by velocitysystems** [comment]
I would suggest raising an issue with Raygun team directly.
https://github.com/MindscapeHQ

**Comment by jfversluis** [comment]
I would indeed assume that this is something on the Raygun side where they need to make their library safe for trimming. If they think otherwise, please feel free to open an issue with all the details so we can look on our side.
