### ISSUE TITLE
AOT+Trimming crashes app on some Android devices

### ISSUE THREAD

**Issue by MartinLichtblau** [dotnet/maui#24088]
### Description

Our app crashes in Release on some phones.
With AOT + Trimming false it works. But since we need a responsive app we also need AOT (which requires trimming, if I am not mistaken). The error was introduced through our own nuget, however, we cannot pinpoint the responsible code lines. 

Did anyone face this error before or know how to find the responsible code? My best guess is that some dependencies get incorrectly resolved, because some of our code uses reflection.

### Version with bug

8.0.40 SR5

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Did you find any workaround?

With AOT + Trimming = false it works, but then the app is too slow.

### Relevant log output

```shell
2024-08-07 10:08:54.970 27712-27712 <no-tag>                com.ourapp  W  Can't find custom attr constructor image: de/ourapp.Models.resources.dll mtoken: 0x0a000005 due to: Could not resolve type with token 01000005 from typeref (expected class 'System.Reflection.AssemblyFileVersionAttribute' in assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089') assembly:mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 type:System.Reflection.AssemblyFileVersionAttribute member:(null)
2024-08-07 10:08:55.020 27712-27712 AndroidRuntime          com.ourapp  E  FATAL EXCEPTION: main
Process: com.ourapp, PID: 27712
android.runtime.JavaProxyThrowable: System.TypeLoadException: Could not resolve type with token 01000005 from typeref (expected class 'System.Reflection.AssemblyFileVersionAttribute' in assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
   at System.Reflection.CustomAttribute.GetCustomAttributesBase(ICustomAttributeProvider , Type , Boolean )
   at System.Reflection.CustomAttribute.GetCustomAttributes(ICustomAttributeProvider , Type , Boolean )
   at System.Reflection.RuntimeAssembly.GetCustomAttributes(Type , Boolean )
   at Microsoft.Maui.Platform.ReflectionExtensions.GetCustomAttributesSafe(Assembly assembly, Type attrType)
   at Microsoft.Maui.Controls.Internals.Registrar.RegisterAll(Assembly[] assemblies, Assembly defaultRendererAssembly, Type[] attrTypes, InitializationFlags flags, Action`1 viewRegistered, IFontRegistrar fontRegistrar)
   at Microsoft.Maui.Controls.Internals.Registrar.RegisterAll(Type[] attrTypes, InitializationFlags flags, IFontRegistrar fontRegistrar)
   at Microsoft.Maui.Controls.Internals.Registrar.RegisterAll(Type[] attrTypes, IFontRegistrar fontRegistrar)
   at Microsoft.Maui.Controls.Compatibility.Forms.RegisterCompatRenderers(IMauiContext , Nullable`1 )
   at Microsoft.Maui.Controls.Compatibility.Forms.SetupInit(IMauiContext , Assembly , Nullable`1 )
   at Microsoft.Maui.Controls.Compatibility.Forms.Init(IMauiContext , Nullable`1 )
   at Microsoft.Maui.Controls.Compatibility.Forms.Init(IActivationState , Nullable`1 )
   at Microsoft.Maui.Controls.Compatibility.Hosting.AppHostBuilderExtensions.<>c.<OnConfigureLifeCycle>b__1_1(IMauiContext mauiContext)
   at Microsoft.Maui.Platform.ApplicationExtensions.<>c__DisplayClass1_0.<CreatePlatformWindow>b__0(OnMauiContextCreated del)
   at Microsoft.Maui.LifecycleEvents.LifecycleEventServiceExtensions.InvokeLifecycleEvents[OnMauiContextCreated](IServiceProvider services, Action`1 action)
   at Microsoft.Maui.Platform.ApplicationExtensions.CreatePlatformWindow(Activity activity, IApplication application, Bundle savedInstanceState)
   at Microsoft.Maui.MauiAppCompatActivity.OnCreate(Bundle savedInstanceState)
   at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_(IntPtr jnienv, IntPtr native__this, IntPtr native_savedInstanceState)
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPL_V(_JniMarshal_PPL_V callback, IntPtr jnienv, IntPtr klazz, IntPtr p0)
	at crc6488302ad6e9e4df1a.MauiAppCompatActivity.n_onCreate(Native Method)
	at crc6488302ad6e9e4df1a.MauiAppCompatActivity.onCreate(MauiAppCompatActivity.java:49)
	at android.app.Activity.performCreate(Activity.java:7825)
	at android.app.Activity.performCreate(Activity.java:7814)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3246)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3410)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2017)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7397)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
2024-08-07 10:08:55.027 27712-27712 MonoDroid               com.ourapp  I  android.runtime.JavaProxyThrowable: System.TypeLoadException: Could not resolve type with token 01000005 from typeref (expected class 'System.Reflection.AssemblyFileVersionAttribute' in assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
2024-08-07 10:08:55.027 27712-27712 MonoDroid               com.ourapp  I  android.runtime.JavaProxyThrowable: System.TypeLoadException: Could not resolve type with token 01000005 from typeref (expected class 'System.Reflection.AssemblyFileVersionAttribute' in assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
```

**Comment by vitek-karas** [comment]
This is the interesting bit:
```
System.TypeLoadException: Could not resolve type with token 01000005 from typeref (expected class 'System.Reflection.AssemblyFileVersionAttribute' in assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
```

The first thing to check is that this seems to indicate you have an assembly which is compiled for .NET Framework - while it might work, it can be problematic and it's definitely not recommended to use that in .NET 8 app.
