### ISSUE TITLE
iOS animated border

### ISSUE THREAD

**Issue by IeuanWalker** [dotnet/maui#24104]
### Description

Border control on iOS animates in. This was reported previously (#18204) and has closed, with the tag "fixed-in-8.0.70".
I am using 8.0.71 and am still experiencing the issue.

Here is a video of the issue, and then showing the linked workaround working - 

https://github.com/user-attachments/assets/a7fe4bdd-2650-4886-8dd9-cd98e4c3aae0

### Version with bug

8.0.71 SR7.1

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Did you find any workaround?

Workaround - https://github.com/dotnet/maui/issues/18204#issuecomment-1900122924

**Comment by albyrock87** [comment]
@IeuanWalker the fix introduced in SR7 is done by me (also the author of the workaround you linked).

I tested it with this: https://github.com/dotnet/maui/blob/main/src/Controls/tests/TestCases.HostApp/Issues/Issue18204.xaml

It was working so I see two options here:
- the test code I used does not cover what you're doing (in such case we need an "how to reproduce" example from you)
- something else introduced in SR7 after my PR broke my fix

**Comment by albyrock87** [comment]
@IeuanWalker my fix is still working, which means there's something not covered by the fix.

Looking at your videos I see many buttons which I suppose are the same component, based on `Border`.
Now what I see is that `Enter my details row` is working fine, while `Continue to the home screen` is not.

May you tell us what differentiate those buttons, it may be related to `VerticalOptions` or `HorizontalOptions` or parent/ancestor layouts.

What would be interest to have is the layout of the page which contains `Continue to the home screen`.

**Comment by IeuanWalker** [comment]
@albyrock87 ill see if i can produce a repo project monday.

As far as im aware all the things u can see getting animated in the vid is where the IsVisible property is initially false

**Comment by albyrock87** [comment]
@IeuanWalker this is what I'm trying now, and still works fine:

```xml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="Maui.Controls.Sample.Issues.Issue18204"
             Title="Issue18204">

    <Grid RowDefinitions="*,Auto" Padding="24">
      <Border
        Grid.Row="1"
        HorizontalOptions="Center"
        IsVisible="False"
        x:Name="TheBorder"
        BackgroundColor="LightBlue"
        Shadow="{Shadow Brush=Black, Offset='0,2', Radius=2, Opacity=0.20}"
        StrokeShape="{RoundRectangle CornerRadius=20}">
        <Button x:Name="TheButton" Clicked="ButtonClicked" BackgroundColor="LightGreen" WidthRequest="200" Text="Hello world" />
      </Border>
    </Grid>
</ContentPage>
```

```csharp
public partial class Issue18204 : ContentPage
{
	public Issue18204()
	{
		InitializeComponent();
	}

	protected override async void OnAppearing()
	{
		base.OnAppearing();
		await Task.Delay(2000);
		((View)TheButton.Parent).IsVisible = true;
	}

	private void ButtonClicked(object sender, EventArgs e)
	{
		var button = (Button)sender;
		button.CancelAnimations();
		var targetHeight = button.HeightRequest switch
		{
			200 => 500,
			500 => 200,
			_ => 500
		};
		button.Animate("Height", new Animation(v => button.HeightRequest = v, button.Height, targetHeight, Easing.Linear));
	}
}
```

**Comment by IeuanWalker** [comment]
@albyrock87 here is the repo - https://github.com/IeuanWalker/maui-animated-border-repo

And here is another video showing the issue - 

https://github.com/user-attachments/assets/cc65096a-803b-460d-80b8-5ddf81aa9eb5

I've upgraded MAUI to `8.0.80` and still have the issue.

- The inputs are just normal entry control wrapped with a border
      -  https://github.com/IeuanWalker/maui-animated-border-repo/blob/8791d63a02ecefe82422aa7dfc385bb0aac0e512/src/App/Controls/Inputs/Entry.xaml#L24C12-L24C40
      - And the visibility is just bound to the toggle - https://github.com/IeuanWalker/maui-animated-border-repo/blob/8791d63a02ecefe82422aa7dfc385bb0aac0e512/src/App/Routes/InputRepoPage.xaml#L33C23-L33C97
- The button is a custom control I built
      - https://github.com/IeuanWalker/Maui.StateButton
      - The control is just built on top of the border control, so your same workaround works for that too 
      - All the repo does is toggle the visibility after 1s - https://github.com/IeuanWalker/maui-animated-border-repo/blob/8791d63a02ecefe82422aa7dfc385bb0aac0e512/src/App/Routes/ButtonRepoPage.xaml.cs#L14



You can uncomment the handler override in MauiProgam.cs, the actual override is here - https://github.com/IeuanWalker/maui-animated-border-repo/blob/master/src/App/Controls/HandleOverrides/BorderHandler.ios.cs

**Comment by albyrock87** [comment]
May you try using NuGet packages from my PR?
https://dev.azure.com/xamarin/6fd3d886-57a5-4e31-8db7-52a1b47c07a8/_apis/build/builds/122164/artifacts?artifactName=nuget&api-version=7.1&%24format=zip

**Comment by IeuanWalker** [comment]
@albyrock87 i've tried the nugets in the linked zip file, for some reason the app is crashing as soon as I navigate from the homepage - 

```
2024-08-23 10:34:15.507117+0100 App[6734:37092] 
Unhandled Exception:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Maui.Controls.Xaml.BindingExtension.Microsoft.Maui.Controls.Xaml.IMarkupExtension<Microsoft.Maui.Controls.BindingBase>.ProvideValue(IServiceProvider serviceProvider)
   at Breadcrumb.Breadcrumb.InitializeComponent() in /_/Scr/Microsoft.Maui.Controls.SourceGen/Microsoft.Maui.Controls.SourceGen.CodeBehindGenerator/Breadcrumb.xaml.sg.cs:line 33
   at Breadcrumb.Breadcrumb..ctor() in /_/Scr/Breadcrumb.xaml.cs:line 142
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Constructor(Object obj, IntPtr* args)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags in
vokeAttr)
   at System.RuntimeType.CreateInstanceMono(Boolean nonPublic, Boolean wrapExceptions)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at Microsoft.Maui.Controls.Xaml.CreateValuesVisitor.Visit(ElementNode node, INode parentNode)
   at Microsoft.Maui.Controls.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
   at Microsoft.Maui.Controls.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
   at Microsoft.Maui.Controls.Xaml.RootNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
   at Microsoft.Maui.Controls.Xaml.XamlLoader.Visit(RootNode rootnode, HydrationContext visitorContext, Boolean useDesignProperties)
   at Microsoft.Maui.Controls.Xaml.XamlLoader.Load(Object view, String xaml, Assembly rootAssembly, Bo
olean useDesignProperties)
   at Microsoft.Maui.Controls.Xaml.XamlLoader.Load(Object view, String xaml, Boolean useDesignProperties)
   at Microsoft.Maui.Controls.Xaml.XamlLoader.Load(Object view, Type callingType)
   at Microsoft.Maui.Controls.Xaml.Extensions.LoadFromXaml[BasePageNonScrollable](BasePageNonScrollable view, Type callingType)
   at App.BaseLayouts.BasePageNonScrollable.InitializeComponent() in D:\WS\Azure-CardiffCouncilICT\App\src\App\obj\Debug
et8.0-ios\iossimulator-arm64\Microsoft.Maui.Controls.SourceGen\Microsoft.Maui.Controls.SourceGen.CodeBehindGenerator\BaseLayouts_BasePageNonScrollable.xaml.sg.cs:line 50
   at App.BaseLayouts.BasePageNonScrollable..ctor() in D:\WS\Azure-CardiffCouncilICT\App\src\App\BaseLayouts\BasePageNonScrollable.xaml.cs:line 74
   at App.Routes.WasteManagement.FlyTipping.MapPage..ctor(IGeoLocationFeature geolocationFeature, IDialogFeature dialogFeature, IAddressSearchFeature addressSearchFeature, INavigationPopupFeature navigationPopupFeature, IOptions`1 appSettings
, ReportViewModel viewModel) in D:\WS\Azure-CardiffCouncilICT\App\src\App\Routes\WasteManagement\FlyTipping\Pages\MapPage.xaml.cs:line 31
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Constructor(Object obj, IntPtr* args)
   at System.Reflection.MethodBaseInvoker.InvokeWithManyArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=8.0.0.
0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSiteMain(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSite(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeServiceProviderEngine.<>c__DisplayClass4_0.<RealizeSe
rvice>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[MapPage](IServiceProvider provider)
   at Maui.Plugins.PageResolver.Resolver.Resolve[MapPage]() in D:\WS\Azure-CardiffCouncilICT\App\src\OpenSourceProjects\PageResolver\src\Maui.Plugins.PageResolver\Resolver.cs:line 77
   at Maui.Plugins.PageResolver.NavigationExtensions.<PushAsync>d__0`1[[App.Routes.WasteManagement.FlyTipping.MapPage, App, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext() in D:\WS\Azure-CardiffCouncilICT\App\src\Op
enSourceProjects\PageResolver\src\Maui.Plugins.PageResolver\NavigationExtensions.cs:line 21
   at App.Routes.HomePage.BtnFlyTipping_Clicked(Object sender, EventArgs e) in D:\WS\Azure-CardiffCouncilICT\App\src\App\Routes\HomePage.xaml.cs:line 305
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Foundation.NSAsyncSynchronizationContextDispatcher.Apply() in /Users/builder/azdo/_work/1/s/xamarin-macios/src/Foundation/NSAction.cs:line 179
--- End of stack trace from previous location ---
   at ObjCRuntime.Runtime.ThrowException(IntPtr gchandle) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/Runtime.cs:line 2708
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 64
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplicati
on.cs:line 96
   at App.Platforms.iOS.Program.Main(String[] args) in D:\WS\Azure-CardiffCouncilICT\App\src\App\Platforms\iOS\Program.cs:line 7
2024-08-23 10:34:15.512422+0100 App[6734:37092] Unhandled managed exception: Exception has been thrown by the target of an invocation. (System.Reflection.TargetInvocationException)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   at System.RuntimeType.CreateInstanceMono(Boolean nonPublic, Boolean wrapExceptions)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at Microsoft.Maui.Controls.Xaml.CreateValuesVisitor.Visit(ElementNode node, INode parentNode)
   at Microsoft.Maui.Controls.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
   at Microsoft.Maui.Controls.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
   at Microsoft.Maui.Controls.Xaml.RootNode.Accept(IXamlNodeVis
itor visitor, INode parentNode)
   at Microsoft.Maui.Controls.Xaml.XamlLoader.Visit(RootNode rootnode, HydrationContext visitorContext, Boolean useDesignProperties)
   at Microsoft.Maui.Controls.Xaml.XamlLoader.Load(Object view, String xaml, Assembly rootAssembly, Boolean useDesignProperties)
   at Microsoft.Maui.Controls.Xaml.XamlLoader.Load(Object view, String xaml, Boolean useDesignProperties)
   at Microsoft.Maui.Controls.Xaml.XamlLoader.Load(Object view, Type callingType)
   at Microsoft.Maui.Controls.Xaml.Extensions.LoadFromXaml[BasePageNonScrollable](BasePageNonScrollable view, Type callingType)
   at App.BaseLayouts.BasePageNonScrollable.InitializeComponent() in D:\WS\Azure-CardiffCouncilICT\App\src\App\obj\Debug
et8.0-ios\iossimulator-arm64\Microsoft.Maui.Controls.SourceGen\Microsoft.Maui.Controls.SourceGen.CodeBehindGenerator\BaseLayouts_BasePageNonScrollable.xaml.sg.cs:line 50
   at App.BaseLayouts.BasePageNonScrollable..ctor() in D:\WS\Azure-CardiffCouncilICT\App\src\App\BaseLayouts\BasePageNonSc
rollable.xaml.cs:line 74
   at App.Routes.WasteManagement.FlyTipping.MapPage..ctor(IGeoLocationFeature geolocationFeature, IDialogFeature dialogFeature, IAddressSearchFeature addressSearchFeature, INavigationPopupFeature navigationPopupFeature, IOptions`1 appSettings, ReportViewModel viewModel) in D:\WS\Azure-CardiffCouncilICT\App\src\App\Routes\WasteManagement\FlyTipping\Pages\MapPage.xaml.cs:line 31
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Constructor(Object obj, IntPtr* args)
   at System.Reflection.MethodBaseInvoker.InvokeWithManyArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceL
ookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSiteMain(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSite(ServiceCallSite callSite, RuntimeResolverContext argument)
   at M
icrosoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeServiceProviderEngine.<>c__DisplayClass4_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[MapPage](IServiceProvider provider)
   at Maui.Plugins.PageResolver.Resolver.Resolve[MapPage]() in D:\WS\Azure-CardiffCouncilICT\App\src\OpenSourceProjects\PageResolver\src\Maui.Plugins.
PageResolver\Resolver.cs:line 77
   at Maui.Plugins.PageResolver.NavigationExtensions.<PushAsync>d__0`1[[App.Routes.WasteManagement.FlyTipping.MapPage, App, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext() in D:\WS\Azure-CardiffCouncilICT\App\src\OpenSourceProjects\PageResolver\src\Maui.Plugins.PageResolver\NavigationExtensions.cs:line 21
   at App.Routes.HomePage.BtnFlyTipping_Clicked(Object sender, EventArgs e) in D:\WS\Azure-CardiffCouncilICT\App\src\App\Routes\HomePage.xaml.cs:line 305
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Foundation.NSAsyncSynchronizationContextDispatcher.Apply() in /Users/builder/azdo/_work/1/s/xamarin-macios/src/Foundation/NSAction.cs:line 179
--- End of stack trace from previous location ---
   at ObjCRuntime.Runtime.ThrowException(IntPtr gchandle) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/Runtime.cs:line 2708
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName
, IntPtr delegateClassName) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 64
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 96
   at App.Platforms.iOS.Program.Main(String[] args) in D:\WS\Azure-CardiffCouncilICT\App\src\App\Platforms\iOS\Program.cs:line 7
Object reference not set to an instance of an object. (System.NullReferenceException)
   at Microsoft.Maui.Controls.Xaml.BindingExtension.Microsoft.Maui.Controls.Xaml.IMarkupExtension<Microsoft.Maui.Controls.BindingBase>.ProvideValue(IServiceProvider serviceProvider)
   at Breadcrumb.Breadcrumb.InitializeComponent() in /_/Scr/Microsoft.Maui.Controls.SourceGen/Microsoft.Maui.Controls.SourceGen.CodeBehindGenerator/Breadcrumb.xaml.sg.cs:line 33
   at Breadcrumb.Breadcrumb..ctor() in /_/Scr/Breadcrumb.xaml.cs:line 142
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Constructor(Object obj, IntPtr* ar
gs)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)

=================================================================
	Native Crash Reporting
=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Native stacktrace:
=================================================================
	0x107d941dc - /Users/ieuanwalker/Library/Developer/CoreSimulator/Devices/5D74EE57-0343-43DC-A66E-53CF699576CF/data/Containers/Bundle/Application/0CDD0F3D-EE7E-4499-926D-C0EC6A1D3979/App.app/libmonosgen-2.0.dylib : mono_dump_native_crash_info
	0x107d443c8 - /Users/ieuanwalker/Library/Developer/CoreSimulator/Devices/5D74EE57-0343-43DC-A66E-53CF699576CF/data/Containers/Bundle/Application/0CDD0F3D-EE7E-4499-926D-C0EC6A1D3979/App.app/libmonosgen-2.0.dylib : mono_handle_native_crash
	0x107f12bd4 - /Users/ieuanwalker/Library/Developer/CoreSimulator/Devices/5D74EE57-0343-43DC-A66E-53CF699576CF/data/Containers/Bundle/Application/0CDD0F3D-EE7E-4499-926D-C0EC6A1D3979/App.app/libmonosgen-2.0.dylib : sigabrt_signal_handler.cold.1
	0x107d93a9c - /Users/ieuanwalker/Library/Developer/CoreSimulator/Devices/5D74EE57-0343-43DC-A66E-53CF699576CF/data/Containers/Bundle/Application/0CDD0F3D-EE7E-4499-926D-C0EC6A1D3979/App.app/libmonosgen-2.0.dylib : mono_runtime_setup_stat_profiler
	0x105ab77e0 - /usr/lib/system/libsystem_platform.dylib : _sigtramp
	0x105c9f124 - /usr/lib/system/libsystem_pthread.dylib : pthread_kill
	0x1801655c0 - /Library/Developer/CoreSimulator/Volumes/iOS_21F79/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 17.5.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/libsystem_c.dylib : abort
	0x106bfac08 - /Users/ieuanwalker/Library/Developer/CoreSimulator/Devices/5D74EE57-0343-43DC-A66E-53CF699576CF/data/Containers/Bundle/Application/0CDD0F3D-EE7E-4499-926D-C0EC6A1D3979/App.app/libxamarin-dotnet-debug.dylib : xamarin_find_protocol_wrapper_type
	0x107e213b4 - /Users/ieuanwalker/Library/Developer/CoreSimulator/Devices/5D74EE57-0343-43DC-A66E-53CF699576CF/data/Containers/Bundle/Application/0CDD0F3D-EE7E-4499-926D-C0EC6A1D3979/App.app/libmonosgen-2.0.dylib : mono_invoke_unhandled_exception_hook
	0x107d02ea0 - /Users/ieuanwalker/Library/Developer/CoreSimulator/Devices/5D74EE57-0343-43DC-A66E-53CF699576CF/data/Containers/Bundle/Application/0CDD0F3D-EE7E-4499-926D-C0EC6A1D3979/App.app/libmonosgen-2.0.dylib : mono_jit_exec
	0x106c0fa38 - /Users/ieuanwalker/Library/Developer/CoreSimulator/Devices/5D74EE57-0343-43DC-A66E-53CF699576CF/data/Containers/Bundle/Application/0CDD0F3D-EE7E-4499-926D-C0EC6A1D3979/App.app/libxamarin-dotnet-debug.dylib : xamarin_main
	0x104f61560 - /Users/ieuanwalker/Library/Developer/CoreSimulator/Devices/5D74EE57-0343-43DC-A66E-53CF699576CF/data/Containers/Bundle/Application/0CDD0F3D-EE7E-4499-926D-C0EC6A1D3979/App.app/App : main
	0x105b91544 - Unknown
	0x105cf6154 - Unknown
	0x3c21000000000000 - Unknown
```

Works fine with the latest release on nuget

**Comment by albyrock87** [comment]
@IeuanWalker May you try with with the latest 8.x nightly build?
This crash seems completely unrelated to my changes.

**Comment by IeuanWalker** [comment]
@albyrock87 Ye sure, you got a link to the nightly build?

**Comment by albyrock87** [comment]
@IeuanWalker https://github.com/dotnet/maui/wiki/Nightly-Builds
