### ISSUE TITLE
Exception on MAUI after Update

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#24185]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Exception-on-MAUI-after-Update/10699329)._

---
[regression]
{System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
---> UIKit.UIKitThreadAccessException: UIKit Consistency error: you are calling a UIKit method that can only be invoked from the UI thread.
   at UIKit.UIApplication.EnsureUIThread() in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 111
   at UIKit.UIAlertController.Create(String title, String message, UIAlertControllerStyle preferredStyle) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/build/dotnet/ios/generated-sources/UIKit/UIAlertController.g.cs:line 147
   at Microsoft.Maui.Controls.Platform.AlertManager.AlertRequestHelper.PresentActionSheet(Page sender, ActionSheetArguments arguments)
   at Microsoft.Maui.Controls.Platform.AlertManager.AlertRequestHelper.OnActionSheetRequested(Page sender, ActionSheetArguments arguments)
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Microsoft.Maui.Controls.MessagingCenter.Subscription.InvokeCallback(Object sender, Object args)
   at Microsoft.Maui.Controls.MessagingCenter.InnerSend(String message, Type senderType, Type argType, Object sender, Object args)
   at Microsoft.Maui.Controls.MessagingCenter.Microsoft.Maui.Controls.IMessagingCenter.Send[Page,ActionSheetArguments](Page sender, String message, ActionSheetArguments args)
   at Microsoft.Maui.Controls.MessagingCenter.Send[Page,ActionSheetArguments](Page sender, String message, ActionSheetArguments args)
   at Microsoft.Maui.Controls.Page.DisplayActionSheet(String title, String cancel, String destruction, FlowDirection flowDirection, String[] buttons)
   at Microsoft.Maui.Controls.Page.DisplayActionSheet(String title, String cancel, String destruction, String[] buttons)
   at BC.MobileClient.PickLists.EBScanViewModel.ProcessBarcode(Barcode barcode) in C:\Dev\BlisterCenter\BlisterCenter.MobileClient\PickLists\EBScanViewModel.cs:line 216}

---
#### Feedback Bot on 7/9/2024, 06:33 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by Zhanglirong-Winnie** [comment]
Could you provide steps to reproduce and a sample project for us to investigate further? 
Looking forward to your reply!
