### ISSUE TITLE
[9.0 Preview 7, Android and Windows] XamlC fails in Debug with _MauiForceXamlCForDebug but works in Release

### ISSUE THREAD

**Issue by janne-hmp** [dotnet/maui#24282]
### Description

Starting in Preview 7, when building with Visual Studio 2022 17.12.0 for Android or Windows, with `<_MauiForceXamlCForDebug>true</_MauiForceXamlCForDebug>`, XamlC fails (XamlCTask failed) when the project is being built in Debug, but works in Release. When I comment `_MauiForceXamlCForDebug` out, the project builds successfully. 

I would note the following:
- Preview 6 worked fine for all platforms for both Release and Debug with `<_MauiForceXamlCForDebug>true</_MauiForceXamlCForDebug>`
- iOS in Preview 7 work fine in Debug with `<_MauiForceXamlCForDebug>true</_MauiForceXamlCForDebug>`. 
- The build fails when using the exact same source code that works in Preview 6
- The build fails even when I remove all the warnings caused by, e.g. MainPage and Frame becoming obsolete, in Preview 7 (e.g., by changing Frames to Borders etc.)
- MAUI default app builds fine for all platforms in Preview 7 with `<_MauiForceXamlCForDebug>true</_MauiForceXamlCForDebug>` in both Release and Debug. It is difficult to know what my game's problem is, as it does not specify which XAML file causes the problem and why.

Binlogs:
[GnollHackM_Debug_AnyCPU_net9.0-android_Build_2024-08-16T18_25_44.2272374+03_00.binlog.zip](https://github.com/user-attachments/files/16638739/GnollHackM_Debug_AnyCPU_net9.0-android_Build_2024-08-16T18_25_44.2272374%2B03_00.binlog.zip)
[GnollHackM_Debug_AnyCPU_net9.0-windows10.0.19041.0_Build_2024-08-16T18_24_41.6697375+03_00.binlog.zip](https://github.com/user-attachments/files/16638745/GnollHackM_Debug_AnyCPU_net9.0-windows10.0.19041.0_Build_2024-08-16T18_24_41.6697375%2B03_00.binlog.zip)

### Steps to Reproduce

1. Try to build GnollHackM in Debug using .NET MAUI 9.0 Preview 7 for Android or Windows
2. The build fails with XamlC failing (the build works in Release and for iOS in Debug and Release)

### Link to public reproduction project repository

https://github.com/hyvanmielenpelit/GnollHack

### Version with bug

9.0.0-preview.7.24407.4

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

9.0.0-preview.6.24327.7

### Affected platforms

Android, Windows

### Affected platform versions

Android 14, Windows 10.0.22631

### Did you find any workaround?

No, you have to build in Release or use Preview 6 for Debug. Or not use Debug and test for XamlC compilation separately in Release. Or you have to just use iOS.

### Relevant log output

```shell
...
2>Target "XamlC" in file "C:\Users\janne\.nuget\packages\microsoft.maui.controls.build.tasks\9.0.0-preview.7.24407.4\buildTransitive\netstandard2.0\Microsoft.Maui.Controls.targets":
2>  Building target "XamlC" completely.
2>  Input file "obj\Debug\net9.0-android\GnollHackM.dll" is newer than output file "obj\Debug\net9.0-android\XamlC.stamp".
2>  Set Property: _MauiXamlCValidateOnly=
2>  Set Property: _MauiXamlCNoWarn=1701;1702;CS1573;CS1591;1701;1702;2008
2>  Set Property: _MauiXamlCNoWarn=1701;1702;CS1573;CS1591;1701;1702;2008;XC0022;XC0023
2>  Set Property: _MauiXamlCGenerateFullPaths=true
2>  Set Property: _MauiXamlCFullPathPrefix=C:\hmp\GnollHack\win\win32\xpl\GnollHackM
2>  Assembly loaded during TaskRun: Microsoft.Maui.Controls.Build.Tasks, Version=9.0.24.40704, Culture=neutral, PublicKeyToken=798c2ba514f889d3 (location: C:\Users\janne\.nuget\packages\microsoft.maui.controls.build.tasks\9.0.0-preview.7.24407.4\buildTransitive\netstandard2.0\Microsoft.Maui.Controls.Build.Tasks.dll, MVID: ba5adc0a-7f79-4c27-bd78-6242cbaba89d, AppDomain: [Default])
2>  Using "XamlCTask" task from assembly "C:\Users\janne\.nuget\packages\microsoft.maui.controls.build.tasks\9.0.0-preview.7.24407.4\buildTransitive\netstandard2.0\Microsoft.Maui.Controls.Build.Tasks.dll".
2>  Task "XamlCTask"
2>    Task Parameter:NoWarn=1701;1702;CS1573;CS1591;1701;1702;2008;XC0022;XC0023
2>    Task Parameter:FullPathPrefix=C:\hmp\GnollHack\win\win32\xpl\GnollHackM
2>    Task Parameter:WarningLevel=9
2>    Task Parameter:DefaultCompile=True
2>    Task Parameter:
2>        ReferencePath=
2>            obj\Debug\net9.0-android\_Microsoft.Android.Resource.Designer.dll
2>            C:\Users\janne\.nuget\packages\azure.core\1.40.0\lib\net6.0\Azure.Core.dll
2>            C:\Users\janne\.nuget\packages\azure.identity\1.12.0\lib\netstandard2.0\Azure.Identity.dll
2>            C:\Users\janne\.nuget\packages\azure.storage.blobs\12.13.1\lib\netstandard2.1\Azure.Storage.Blobs.dll
2>            C:\Users\janne\.nuget\packages\azure.storage.common\12.12.0\lib\netstandard2.0\Azure.Storage.Common.dll
2>            C:\Users\janne\.nuget\packages\googlegson\2.11.0.1\lib\net8.0-android34.0\GoogleGson.dll
2>            C:\Program Files\dotnet\packs\Microsoft.Android.Ref.35\35.0.0-preview.7.41\ref\net9.0\Java.Interop.dll
2>            C:\Users\janne\.nuget\packages\xamarin.google.code.findbugs.jsr305\3.0.2.11\lib\net7.0-android33.0\Jsr305Binding.dll
2>            C:\Users\janne\.nuget\packages\k4os.compression.lz4\1.3.5\lib\net6.0\K4os.Compression.LZ4.dll
2>            C:\Users\janne\.nuget\packages\microsoft.bcl.asyncinterfaces\1.1.1\ref\netstandard2.1\Microsoft.Bcl.AsyncInterfaces.dll
2>            C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\9.0.0-preview.7.24405.7\ref\net9.0\Microsoft.CSharp.dll
2>            C:\Users\janne\.nuget\packages\microsoft.extensions.configuration.abstractions\9.0.0-preview.7.24405.7\lib\net9.0\Microsoft.Extensions.Configuration.Abstractions.dll
2>            C:\Users\janne\.nuget\packages\microsoft.extensions.configuration.binder\8.0.0\lib\net8.0\Microsoft.Extensions.Configuration.Binder.dll
2>            C:\Users\janne\.nuget\packages\microsoft.extensions.configuration\9.0.0-preview.7.24405.7\lib\net9.0\Microsoft.Extensions.Configuration.dll
2>            C:\Users\janne\.nuget\packages\microsoft.extensions.dependencyinjection.abstractions\9.0.0-preview.7.24405.7\lib\net9.0\Microsoft.Extensions.DependencyInjection.Abstractions.dll
2>            C:\Users\janne\.nuget\packages\microsoft.extensions.dependencyinjection\9.0.0-preview.7.24405.7\lib\net9.0\Microsoft.Extensions.DependencyInjection.dll
2>            C:\Users\janne\.nuget\packages\microsoft.extensions.diagnostics.abstractions\8.0.0\lib\net8.0\Microsoft.Extensions.Diagnostics.Abstractions.dll
...
2>      Adding searchpath C:\Users\janne\.nuget\packages\microsoft.extensions.logging\9.0.0-preview.7.24405.7\lib\net9.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\microsoft.extensions.options.configurationextensions\8.0.0\lib\net8.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\microsoft.extensions.options\9.0.0-preview.7.24405.7\lib\net9.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\microsoft.extensions.primitives\9.0.0-preview.7.24405.7\lib\net9.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\microsoft.identity.client\4.61.3\lib\net6.0-android31.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\microsoft.identity.client.extensions.msal\4.61.3\lib\net6.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\microsoft.identitymodel.abstractions\6.35.0\lib\net6.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\microsoft.maui.controls.compatibility\9.0.0-preview.7.24407.4\lib\net9.0-android35.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\microsoft.maui.controls.core\9.0.0-preview.7.24407.4\lib\net9.0-android35.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\microsoft.maui.controls.xaml\9.0.0-preview.7.24407.4\lib\net9.0-android35.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\microsoft.maui.core\9.0.0-preview.7.24407.4\lib\net9.0-android35.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\microsoft.maui.essentials\9.0.0-preview.7.24407.4\lib\net9.0-android35.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\microsoft.maui.graphics\9.0.0-preview.7.24407.4\lib\net9.0-android35.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\newtonsoft.json\13.0.3\lib\net6.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\sentry.android.assemblyreader\4.9.0\lib\net6.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\sentry.bindings.android\4.9.0\lib\net7.0-android33.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\sentry\4.9.0\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\sentry.extensions.logging\4.9.0\lib\net8.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\sentry.maui\4.9.0\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\skiasharp\3.0.0-preview.4.1\ref\net7.0-android33.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\skiasharp.views\3.0.0-preview.4.1\lib\net7.0-android33.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\skiasharp.views.maui.controls\3.0.0-preview.4.1\lib\net7.0-android33.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\skiasharp.views.maui.core\3.0.0-preview.4.1\lib\net7.0-android33.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\system.clientmodel\1.0.0\lib\net6.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\system.io.hashing\6.0.0\lib\net6.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\system.memory.data\1.0.2\lib\netstandard2.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.android.glide.annotations\4.16.0.5\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.android.glide.disklrucache\4.16.0.5\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.android.glide\4.16.0.5\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.android.glide.gifdecoder\4.16.0.5\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.androidx.activity\1.9.0.4\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.androidx.activity.ktx\1.9.0.4\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.androidx.annotation\1.8.0.1\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.androidx.annotation.experimental\1.4.1.4\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.androidx.annotation.jvm\1.8.0.1\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.androidx.appcompat.appcompatresources\1.7.0.1\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.androidx.appcompat\1.7.0.1\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.androidx.arch.core.common\2.2.0.11\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.androidx.arch.core.runtime\2.2.0.11\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.androidx.browser\1.8.0.4\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.androidx.cardview\1.0.0.29\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.androidx.collection\1.4.0.6\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.androidx.collection.jvm\1.4.0.5\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.androidx.collection.ktx\1.4.0.5\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.androidx.concurrent.futures\1.2.0.1\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.androidx.constraintlayout.core\1.0.4.14\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.androidx.constraintlayout\2.1.4.14\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.androidx.coordinatorlayout\1.2.0.15\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.androidx.core.core.ktx\1.13.1.3\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.androidx.core\1.13.1.3\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.androidx.cursoradapter\1.0.0.27\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.androidx.customview\1.1.0.26\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.androidx.customview.poolingcontainer\1.0.0.13\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.androidx.documentfile\1.0.1.27\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.androidx.drawerlayout\1.2.0.11\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.androidx.dynamicanimation\1.0.0.27\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.androidx.emoji2\1.4.0.8\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.androidx.emoji2.viewshelper\1.4.0.8\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.androidx.exifinterface\1.3.7.4\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.androidx.fragment\1.8.1.1\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.androidx.fragment.ktx\1.8.1.1\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.androidx.interpolator\1.0.0.27\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.androidx.legacy.support.core.utils\1.0.0.27\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.androidx.lifecycle.common\2.8.3.1\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.androidx.lifecycle.common.jvm\2.8.3.1\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.androidx.lifecycle.livedata.core\2.8.3.1\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.androidx.lifecycle.livedata.core.ktx\2.8.3.1\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.androidx.lifecycle.livedata\2.8.3.1\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.androidx.lifecycle.process\2.8.3.1\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.androidx.lifecycle.runtime.android\2.8.3.1\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.androidx.lifecycle.runtime\2.8.3.1\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.androidx.lifecycle.runtime.ktx.android\2.8.3.1\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.androidx.lifecycle.runtime.ktx\2.8.3.1\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.androidx.lifecycle.viewmodel.android\2.8.3.1\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.androidx.lifecycle.viewmodel\2.8.3.1\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.androidx.lifecycle.viewmodel.ktx\2.8.3.1\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.androidx.lifecycle.viewmodelsavedstate\2.8.3.1\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.androidx.loader\1.1.0.27\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.androidx.localbroadcastmanager\1.1.0.15\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.androidx.navigation.common\2.7.7.5\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.androidx.navigation.fragment\2.7.7.5\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.androidx.navigation.runtime\2.7.7.5\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.androidx.navigation.ui\2.7.7.5\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.androidx.print\1.0.0.27\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.androidx.profileinstaller.profileinstaller\1.3.1.10\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.androidx.recyclerview\1.3.2.6\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.androidx.resourceinspection.annotation\1.0.1.15\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.androidx.savedstate\1.2.1.11\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.androidx.savedstate.savedstate.ktx\1.2.1.11\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.androidx.security.securitycrypto\1.1.0.2-alpha06\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.androidx.slidingpanelayout\1.2.0.15\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.androidx.startup.startupruntime\1.1.1.15\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.androidx.swiperefreshlayout\1.1.0.22\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.androidx.tracing.tracing\1.2.0.5\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.androidx.transition\1.5.0.3\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.androidx.vectordrawable.animated\1.2.0.1\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.androidx.vectordrawable\1.2.0.1\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.androidx.versionedparcelable\1.2.0.5\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.androidx.viewpager\1.0.0.27\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.androidx.viewpager2\1.1.0.1\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.androidx.window\1.3.0.1\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.androidx.window.extensions.core.core\1.0.0.9\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.google.android.material\1.11.0.1\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.google.android.play.core\1.10.3.13\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.google.crypto.tink.android\1.14.0.1\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.google.errorprone.annotations\2.27.1\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.google.guava.listenablefuture\1.0.0.22\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.jetbrains.annotations\24.1.0.6\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.kotlin.stdlib\2.0.0.1\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.kotlinx.atomicfu\0.25.0.1\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.kotlinx.atomicfu.jvm\0.25.0.1\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.kotlinx.coroutines.android\1.8.1.1\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.kotlinx.coroutines.core\1.8.1.1\lib\net8.0-android34.0
2>      Adding searchpath C:\Users\janne\.nuget\packages\xamarin.kotlinx.coroutines.core.jvm\1.8.1.1\lib\net8.0-android34.0
2>    C:\Users\janne\.nuget\packages\microsoft.maui.controls.build.tasks\9.0.0-preview.7.24407.4\buildTransitive\netstandard2.0\Microsoft.Maui.Controls.targets(171,3): error MSB4018: The "XamlCTask" task failed unexpectedly.
2>    C:\Users\janne\.nuget\packages\microsoft.maui.controls.build.tasks\9.0.0-preview.7.24407.4\buildTransitive\netstandard2.0\Microsoft.Maui.Controls.targets(171,3): error MSB4018: Mono.Cecil.Cil.SymbolsNotFoundException: No symbol found for file: C:\hmp\GnollHack\win\win32\xpl\GnollHackM\obj\Debug\net9.0-android\GnollHackM.dll
2>    C:\Users\janne\.nuget\packages\microsoft.maui.controls.build.tasks\9.0.0-preview.7.24407.4\buildTransitive\netstandard2.0\Microsoft.Maui.Controls.targets(171,3): error MSB4018:    at Mono.Cecil.Cil.DefaultSymbolReaderProvider.GetSymbolReader(ModuleDefinition module, String fileName) in C:\src\cecil\Mono.Cecil.Cil\Symbols.cs:line 951
2>    C:\Users\janne\.nuget\packages\microsoft.maui.controls.build.tasks\9.0.0-preview.7.24407.4\buildTransitive\netstandard2.0\Microsoft.Maui.Controls.targets(171,3): error MSB4018:    at Mono.Cecil.ModuleReader.ReadSymbols(ModuleDefinition module, ReaderParameters parameters) in C:\src\cecil\Mono.Cecil\AssemblyReader.cs:line 100
2>    C:\Users\janne\.nuget\packages\microsoft.maui.controls.build.tasks\9.0.0-preview.7.24407.4\buildTransitive\netstandard2.0\Microsoft.Maui.Controls.targets(171,3): error MSB4018:    at Mono.Cecil.ModuleReader.CreateModule(Image image, ReaderParameters parameters) in C:\src\cecil\Mono.Cecil\AssemblyReader.cs:line 84
2>    C:\Users\janne\.nuget\packages\microsoft.maui.controls.build.tasks\9.0.0-preview.7.24407.4\buildTransitive\netstandard2.0\Microsoft.Maui.Controls.targets(171,3): error MSB4018:    at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters) in C:\src\cecil\Mono.Cecil\ModuleDefinition.cs:line 1113
2>    C:\Users\janne\.nuget\packages\microsoft.maui.controls.build.tasks\9.0.0-preview.7.24407.4\buildTransitive\netstandard2.0\Microsoft.Maui.Controls.targets(171,3): error MSB4018:    at Microsoft.Maui.Controls.Build.Tasks.XamlCTask.Execute(IList`1& thrownExceptions) in /_/src/Controls/src/Build.Tasks/XamlCTask.cs:line 192
2>    C:\Users\janne\.nuget\packages\microsoft.maui.controls.build.tasks\9.0.0-preview.7.24407.4\buildTransitive\netstandard2.0\Microsoft.Maui.Controls.targets(171,3): error MSB4018:    at Microsoft.Maui.Controls.Build.Tasks.XamlTask.Execute() in /_/src/Controls/src/Build.Tasks/XamlTask.cs:line 38
2>    C:\Users\janne\.nuget\packages\microsoft.maui.controls.build.tasks\9.0.0-preview.7.24407.4\buildTransitive\netstandard2.0\Microsoft.Maui.Controls.targets(171,3): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Execute()
2>    C:\Users\janne\.nuget\packages\microsoft.maui.controls.build.tasks\9.0.0-preview.7.24407.4\buildTransitive\netstandard2.0\Microsoft.Maui.Controls.targets(171,3): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
2>  Done executing task "XamlCTask" -- FAILED.
2>Done building target "XamlC" in project "GnollHackM.csproj" -- FAILED.
...
```

**Comment by QianaJiao** [comment]
Verified this issue with the provided repo:

It works fine on 17.12.0 Preview 1.0 (.NET SDK: 9.0.100-preview.6.24328.19, MAUI Version: 9.0.0-preview.6.24327.7).
I also change the Maui version to` <PackageReference Include="Microsoft.Maui.Controls" Version="9.0.0-preview.7.24408.5" />`. It can be build with no errors.

And in 17.12.0 Preview 2.0 [35212.213.main] (.NET SDK: 9.0.100-preview.7.24407.12, MAUI Version: 9.0.0-preview.7.24408.5). 
In debug target, the build will fail with the error MSB4018: The "XamlCTask" task failed unexpectedly. In Release mode, it builds successfully.
If I downgrade the MAUI version to ` <PackageReference Include="Microsoft.Maui.Controls" Version="9.0.0-preview.6.24327.7" />`, it still failed. 

Maybe it's not regression for MAUI, it's regression for .NET SDK?
I'm not sure. I'd like to mark as regression first.

**Comment by jonathanpeppers** [comment]
Your project has `<DebugType>full</DebugType>`:

https://github.com/hyvanmielenpelit/GnollHack/blob/cbafd1c4f28236c9cea1ac6f96f3d6ab595ce8cf/win/win32/xpl/GnollHackM/GnollHackM.csproj#L87C3-L87C30

This would produce non-portable `.pdb` files, the old Windows symbol format. This likely won't work on .NET 5+ anyway, and for sure will not work on platforms running with Mono.

What happens if you just remove this line?

**Comment by janne-hmp** [comment]
Great, thanks, it indeed works now. Not sure where I had taken that `DebugType` line from. My sense is that it might have worked in Preview 6, but it is also possible that I was trying to find a solution to some other bug, and found it on StackOverflow as a potential solution to whatever I was working on.
