### ISSUE TITLE
[Windows] Nullpointer from ListView.ScrollTo

### ISSUE THREAD

**Issue by Larhei** [dotnet/maui#24347]
### Description

When adding an item to an Observable Collection in my ViewModel and than try to scroll to it, i´m getting a Nullpointer from the ListViewRenderer from time to time. To illustrate the issue i wrote some code that does not make sense in real world but it illustrates the issue. Looks like a race condition to me. The item is in the Itemssource on maui side... but not in the native side of things. But this is just a guess. On Android it is not crashing, but logcat is giving also nullpointer logs.

### Steps to Reproduce

1. Checkout Repos on Windows
2. Run on Windows

### Link to public reproduction project repository

https://github.com/Larhei/Maui-Issues/tree/main/ScrollToNullPointer

### Version with bug

8.0.80 SR8

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

net8.0-windows10.0.19041.0

### Did you find any workaround?

Addind a delay between adding to the collection and call to ScrollTo stops the Nullpointer from happening. But in case UI-Thread is busy this could lead again to this nullpointer i guess.  

### Relevant log output

```shell
at Microsoft.Maui.Controls.Handlers.Compatibility.ListViewRenderer.<>c__DisplayClass42_1.<<ScrollTo>b__2>d.MoveNext()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
```

**Comment by jaosnz-rep** [comment]
I can repro this issue at Windows platform on the latest 17.12.0 Preview 1.0(8.0.80 & 8.0.72).

**Comment by jfversluis** [comment]
ListView is deprecated for .NET 10, so we probably won't be working on this anymore. Please migrate to CollectionView and help us make that the solid approach for this. Thanks!
