### ISSUE TITLE
Shadow Offset Style breaks Android in Release mode

### ISSUE THREAD

**Issue by rodolfo-sousa** [dotnet/maui#24601]
### Description

I have this style in one style file:
`<Graphics:Point x:Key="ShadowOffset">5,5</Graphics:Point>`
and have this style in another style file:
`
<Setter Property="Shadow">
    <Setter.Value>
        <Shadow Brush="{AppThemeBinding Light={StaticResource Brush_ShadowLight}, Dark={StaticResource Brush_ShadowDark}}"
                Offset="{StaticResource ShadowOffset}"
                Radius="{StaticResource ShadowRadius}"
                Opacity="{StaticResource ShadowOpacity}"/>
    </Setter.Value>
</Setter>
`
work fine in WinUI, Android and iOS in Debug mode.
But when building the Android in Release mode the app crash when InitializeComponent() is called in App().

### Version with bug

8.0.82 SR8.2

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

### Did you find any workaround?

Yes.
Had to direct specify the Offset value in the style:
`
        <Setter Property="Shadow">
            <Setter.Value>
                <Shadow Brush="{AppThemeBinding Light={StaticResource Brush_ShadowLight}, Dark={StaticResource Brush_ShadowDark}}"
                        Offset="5,5"
                        Radius="{StaticResource ShadowRadius}"
                        Opacity="{StaticResource ShadowOpacity}"/>
            </Setter.Value>
        </Setter>
`

### Relevant log output

```shell
Time	Device Name	Type	PID	Tag	Message
09-04 21:27:52.587	Pixel_3_API_30	Info	24705	DOTNET	JavaProxyThrowable: translation threw an exception: Java.Lang.NullPointerException: Declaring class is null
   at Java.Interop.JniEnvironment.InstanceMethods.CallNonvirtualVoidMethod(JniObjectReference instance, JniObjectReference type, JniMethodInfo method, JniArgumentValue* args)
   at Java.Interop.JniPeerMembers.JniInstanceMethods.FinishCreateInstance(String constructorSignature, IJavaPeerable self, JniArgumentValue* parameters)
   at Java.Lang.StackTraceElement..ctor(String declaringClass, String methodName, String fileName, Int32 lineNumber)
   at Android.Runtime.JavaProxyThrowable.TranslateStackTrace()
   at Android.Runtime.JavaProxyThrowable.Create(Exception innerException)
  --- End of managed Java.Lang.NullPointerException stack trace ---
09-04 21:27:52.590	Pixel_3_API_30	Info	24705	DOTNET	java.lang.NullPointerException: Declaring class is null
	at java.util.Objects.requireNonNull(Objects.java:245)
	at java.lang.StackTraceElement.<init>(StackTraceElement.java:71)
	at crc6488302ad6e9e4df1a.MauiApplication.n_onCreate(Native Method)
	at crc6488302ad6e9e4df1a.MauiApplication.onCreate(MauiApplication.java:28)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6712)
	at android.app.ActivityThread.access$1300(ActivityThread.java:237)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
09-04 21:27:52.590	Pixel_3_API_30	Info	24705	DOTNET	java.lang.NullPointerException: Declaring class is null
	at java.util.Objects.requireNonNull(Objects.java:245)
	at java.lang.StackTraceElement.<init>(StackTraceElement.java:71)
	at crc6488302ad6e9e4df1a.MauiApplication.n_onCreate(Native Method)
	at crc6488302ad6e9e4df1a.MauiApplication.onCreate(MauiApplication.java:28)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6712)
	at android.app.ActivityThread.access$1300(ActivityThread.java:237)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
  --- End of managed Java.Lang.NullPointerException stack trace ---
```

**Comment by ninachen03** [comment]
Could you provide us with a sample project so we can investigate it further? Looking forward to your reply!
