### ISSUE TITLE
Certificate pinning is now working in MAUI Android application

### ISSUE THREAD

**Issue by Joshna-Lingala** [dotnet/maui#24626]
### Description

We are receiving below exception for MAUI Android application, but it is working fine in iOS. This is working fine in lower environments like Staging (Windows 2019) and UAT (Windows 2019) but this issue is occurring only in Production server (Windows 2022).

**Exception :**

System.Net.Http.HttpRequestException: An error occurred while sending the request.
---> System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer.
---> System.Net.Sockets.SocketException (104): Connection reset by peer
   at System.Net.Sockets.Socket.Receive(Span`1 buffer, SocketFlags socketFlags)
   at System.Net.Sockets.NetworkStream.Read(Span`1 buffer)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Span`1 buffer)
   at System.Net.Security.SyncReadWriteAdapter.ReadAsync(Stream stream, Memory`1 buffer, CancellationToken cancellationToken)
   at System.Net.Security.SslStream.<EnsureFullTlsFrameAsync>d__157`1[[System.Net.Security.SyncReadWriteAdapter, System.Net.Security, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext()
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1[[System.Int32, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Runtime.CompilerServices.IAsyncStateMachine, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Security.SslStream.<ReadAsyncInternal>d__159`1[[System.Net.Security.SyncReadWriteAdapter, System.Net.Security, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext()
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1[[System.Int32, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Runtime.CompilerServices.IAsyncStateMachine, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Security.SslStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.Read(Span`1 buffer)
   at System.Net.Http.HttpConnection.InitialFillAsync(Boolean async)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.SocketsHttpHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageInvoker.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.Send(HttpRequestMessage request)

### Steps to Reproduce

1. Clone application from the below repository.
2. Run the application.
3. Click on button.
4. Above shared exception occurs. 

### Link to public reproduction project repository

https://github.com/Joshna-Lingala/CertPinningIssue

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

**Comment by jaosnz-rep** [comment]
I can repro this issue at Android platform on the latest 17.12.0 Preview 1.0(8.0.82 & 8.0.80).

**Comment by drasticactions** [comment]
@Joshna-Lingala Your issue is a runtime one, and I think it's because you're using net7.0-android, there were changes handling certificates in newer dotnet runtimes (CC @simonrozsival) and this may be the issues you're hitting. 

https://github.com/Joshna-Lingala/CertPinningIssue/blob/main/MauiApp1/MauiApp1.csproj#L4

`net7.0` is unsupported, can you try upgrading this to .NET 8.0 or 9.0?

**Comment by Joshna-Lingala** [comment]
@drasticactions  
Yes, I have created new .NET8 and .NET9.0 applications and added same lines of code in both. Still, the same exception is occurring as mentioned in https://github.com/dotnet/maui/issues/24626#issue-2510252554 

I have updated the repository with 3 folders of NET7 (which is .NET7 application), NET8 (which is a .NET8 application) and NET9 (which is a .NET9 application).
