### ISSUE TITLE
[Android] Cannot open MainActivity via Intent when the app is in the background

### ISSUE THREAD

**Issue by aqua-ix** [dotnet/maui#24733]
### Description

When the MAUI Android app is in the background, attempting to launch MainActivity via an Intent from another app results in the following exception, preventing the activity from starting: 

```
[System.InvalidOperationException]: This window is already associated with an active Activity (MauiPlayground.MainActivity). Please override CreateWindow on MauiPlayground.App to add support for multiple activities https://aka.ms/maui-docs-create-window or set the LaunchMode to SingleTop on MauiPlayground.MainActivity.
```

`LaunchMode.SingleTop` is specified for MainActivity as shown in the following: 

```cs
[Activity(Name = "com.companyname.mauiplayground.MainActivity",
        Theme = "@style/Maui.SplashTheme",
        Exported = true,
        LaunchMode = LaunchMode.SingleTop,
        MainLauncher = true,
        ConfigurationChanges = ConfigChanges.ScreenSize | ConfigChanges.Orientation | ConfigChanges.UiMode |
                               ConfigChanges.ScreenLayout | ConfigChanges.SmallestScreenSize | ConfigChanges.Density)]
    public class MainActivity : MauiAppCompatActivity
```

The explanation about overriding CreateWindow applies to the case when trying to open another Activity within the app, and I believe it is not relevant to the current case.

Related to:
- #18692
- #24423

### Steps to Reproduce

1. Open MAUI app.
   - Sample Project: https://github.com/aqua-ix/MauiPlayground
2. Leave the MAUI app in the background.
3. Send the intent without no flags.
   - I made test tool: https://github.com/aqua-ix/IntentTestTool

### Link to public reproduction project repository

https://github.com/aqua-ix/MauiPlayground

### Version with bug

9.0.0-rc.1.24453.9

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Did you find any workaround?

If `FLAG_ACTIVITY_NEW_TASK` is added to the Intent, the backgrounded MAUI app opens successfully.

### Relevant log output

```shell
AndroidRuntime                      FATAL EXCEPTION: main
                                    Process: com.example.app, PID: 16624
                                    android.runtime.JavaProxyThrowable: [System.InvalidOperationException]: This window is already associated with an active Activity (MauiPlayground.MainActivity). Please override CreateWindow on MauiPlayground.App to add support for multiple activities https://aka.ms/maui-docs-create-window or set the LaunchMode to SingleTop on MauiPlayground.MainActivity.
                                    	at Microsoft.Maui.Platform.ApplicationExtensions.CreatePlatformWindow(Unknown Source:0)
                                    	at Microsoft.Maui.MauiAppCompatActivity.OnCreate(Unknown Source:0)
                                    	at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_(Unknown Source:0)
                                    	at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPL_V(Unknown Source:0)
                                    	at crc6488302ad6e9e4df1a.MauiAppCompatActivity.n_onCreate(Native Method)
                                    	at crc6488302ad6e9e4df1a.MauiAppCompatActivity.onCreate(MauiAppCompatActivity.java:49)
                                    	at android.app.Activity.performCreate(Activity.java:9002)
                                    	at android.app.Activity.performCreate(Activity.java:8980)
                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1526)
                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4030)
                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4235)
                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:112)
                                    	at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:174)
                                    	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:109)
                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:81)
                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2636)
                                    	at android.os.Handler.dispatchMessage(Handler.java:107)
                                    	at android.os.Looper.loopOnce(Looper.java:232)
                                    	at android.os.Looper.loop(Looper.java:317)
                                    	at android.app.ActivityThread.main(ActivityThread.java:8705)
                                    	at java.lang.reflect.Method.invoke(Native Method)
                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
```

**Comment by BootDat** [comment]
Adding  `LaunchMode = LaunchMode.SingleInstance` to Activity fixed it for me.

**Comment by aqua-ix** [comment]
> Adding `LaunchMode = LaunchMode.SingleInstance` to Activity fixed it for me.

Indeed, adding `LaunchMode = LaunchMode.SingleInstance` seems to make it work as expected. However, since `SingleInstance` is an unusual setting for typical Android apps, I am concerned that it might cause unexpected side effects.

On the other hand, if adding `LaunchMode = LaunchMode.SingleInstance` to the Activity is the correct approach for the architecture of MAUI Android, I would like to propose to the MAUI development team that they revise the content of the `System.InvalidOperationException` error message that includes "set the LaunchMode to SingleTop."

**Comment by thomasgalliker** [comment]
I researched a bit on this topic and I found out, that SingleInstance is a very bad choice if you want to use app links. I think the best option would be SingleTask as it reuses the existing activity once an app link is launched. But SingleTask also causes the described error "This window is already associated with an active Activity".

Can anyone from the maui team @mattleibow or @samhouts give a direction on how to solve this? Is it a bug or are we just using a wrong LaunchMode?

**Comment by aqua-ix** [comment]
This still reproduces on the latest version

### Environment

- .NET SDK: 11.0.100-preview.6.26359.118
- .NET MAUI workload: 11.0.0-preview.6.26360.8
- Android workload: 37.0.0-preview.6.59
- Target framework: `net11.0-android`
- Device: Pixel 8, Android 16 (API 36)

I updated the reproduction project to `net11.0-android`: https://github.com/aqua-ix/MauiPlayground

### Result

The steps are unchanged (launch the app → send it to the background → send an explicit Intent with no flags from another app), and the same exception is still thrown:

```
FATAL EXCEPTION: main
Process: com.example.app, PID: 25441
android.runtime.JavaProxyThrowable: [System.InvalidOperationException]: This window is already associated with an active Activity (MauiPlayground.MainActivity). Please override CreateWindow on MauiPlayground.App to add support for multiple activities https://aka.ms/maui-docs-create-window or set the LaunchMode to SingleTop on MauiPlayground.MainActivity.
	at Microsoft.Maui.Platform.ApplicationExtensions.CreatePlatformWindow + 0x13a(Unknown Source)
	at Microsoft.Maui.MauiAppCompatActivity.OnCreate + 0x4b(Unknown Source)
	at Android.App.Activity.__n_OnCreate_Landroid_os_Bundle_ + 0x0(Unknown Source)
	at Java.Interop.JniMarshal.SafeInvokeAction + 0x10(Unknown Source)
	at crc6488302ad6e9e4df1a.MauiAppCompatActivity.n_onCreate(Native Method)
	at crc6488302ad6e9e4df1a.MauiAppCompatActivity.onCreate(MauiAppCompatActivity.java:52)
	at android.app.Activity.performCreate(Activity.java:9290)
	at android.app.Activity.performCreate(Activity.java:9268)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1543)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4503)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4723)
	...
```

**Comment by beeradmoore** [comment]
I am curious if this is related to #38020. Where "send an explicit Intent with no flags from another app" is just me launching the app from my launcher.

@aqua-ix, if you press home instead of back to send the app to the background does the issue go away?

**Comment by aqua-ix** [comment]
@beeradmoore I tested both cases and there's a clear difference between Home and Back.

**Setup:** Launch the MAUI app (this repro project) → send it to background → from a separate app ([IntentTestTool](https://github.com/aqua-ix/IntentTestTool)) send an explicit Intent with no flags targeting `MainActivity`.

**Home (press Home to background the app):**
The Activity/Window is only paused, not destroyed. Sending the Intent still crashes:
```
FATAL EXCEPTION: main
[System.InvalidOperationException]: This window is already associated with an active Activity (MauiPlayground.MainActivity)...
```

**Back (press Back to background the app):**
The Activity is actually finished (task shows `numActivities=0`, `isRunning=false`), only the process stays alive. Sending the Intent in this state launches the Activity normally — **no crash**:
```
ActivityTaskManager: Displayed com.example.app/.MainActivity for user 0: +93ms
```

So the crash is reproducible only when the app is backgrounded via Home (Activity still alive), not via Back (Activity finished, only the process survives).
