### ISSUE TITLE
.NET 9: Runtime crashes when utilizing legacy libraries.

### ISSUE THREAD

**Issue by daltzctr** [dotnet/maui#24740]
### Description

MAUI class libraries that utilize the following features
- Obsoleted controls such as `Frame`
- Obsoleted APIs such as `Device`
- Missing datatypes (previously this would fall back to reflection based bindings)
- `x:DataType={x:Object}` which would previously fall back to reflection based bindings.

Will runtime crash when used in a consumer project. The consumer project has no warnings about any incompatibilities and will just crash.

Some examples of offending libraries are
- https://github.com/roubachof/Sharpnado.Tabs (utilizes `Border` and `Device`)
- https://github.com/akgulebubekir/Maui.DataGrid (version 4.0.4 or less) (missing datatypes and usage of `x:DataType={x:Object}`

**Proposal:**
I am not sure of the technical challenges on this, but it would be nice to either mark .NET 8 MAUI libraries with warnings as possibly incompatible, or detect incompatibilities in referenced libraries and throw a compile time error. This is no workaround and library maintainers *must* fix the issues by fixing the obsoleted references and ensure they are datatyping everything (replace `x:DataType={x:Object}` with `x:DataType={x:Null}` to explicitly opt in to reflection based bindings as a short term workaround.

### Steps to Reproduce

1. Create a new MAUI project
2. Include the Maui.DataGrid (https://github.com/akgulebubekir/Maui.DataGrid) nuget
3. Add a reference to datagrid in XAML, no need to add itemsource
4. Build. 
    - Observe no warnings at compile time
5. Run the application. It will throw an exception that points to some Xaml activator and in Android, points to the datagrid library.

### Version with bug

9.0.0-rc.1.24453.9

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.82 SR8.2

### Affected platforms

iOS, Android

### Did you find any workaround?

No. The only workaround has been to fix the references upstream.

**Comment by jonathanpeppers** [comment]
@daltzctr can you share the stack trace of some of these crashes?

Do we know if this change was in RC 1, it was merged only 2 weeks ago, so perhaps not:
* https://github.com/dotnet/maui/pull/24238

The idea is it should restore a lot of previous behavior from .NET 8.

**Comment by jonathanpeppers** [comment]
No, I don't see it in RC 1:
* https://github.com/dotnet/maui/commits/release/9.0.1xx-rc1?author=simonrozsival

**Comment by daltzctr** [comment]
@jonathanpeppers 

Sharpnado (obsolete references, so not datatype related)
```
Unhandled managed exception: Exception has been thrown by the target of an invocation. (System.Reflection.TargetInvocationException)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   at System.RuntimeType.CreateInstanceMono(Boolean nonPublic, Boolean wrapExceptions)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at Microsoft.Maui.Controls.Xaml.CreateValuesVisitor.Visit(ElementNode node, INode parentNode)
   at Microsoft.Maui.Controls.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
   at Microsoft.Maui.Controls.Xaml.ApplyPropertiesVisitor.<>c__DisplayClass43_0.<SetTemplate>b__0()
   at Microsoft.Maui.Controls.ElementTemplate.CreateContent()
at Sharpnado.Tabs.TabHostView.CreateTabItem(Object item)
   at Sharpnado.Tabs.TabHostView.InitializeItems()
   at Sharpnado.Tabs.TabHostView.UpdateItemsSource()
   at Sharpnado.Tabs.TabHostView.OnPropertyChanged(String propertyName)
   at Microsoft.Maui.Controls.BindableObject.OnBindablePropertySet(BindableProperty property, Object original, Object value, Boolean didChange, Boolean willFirePropertyChanged)
```

Maui.DataGrid (`x:Object` and missing DataTypes)
```
[0:] [13:46:57 FTL] Inner Exception: 
 System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Maui.Controls.Xaml.BindingExtension.<Microsoft.Maui.Controls.Xaml.IMarkupExtension<Microsoft.Maui.Controls.BindingBase>.ProvideValue>g__CreateBinding|40_0(<>c__DisplayClass40_0& ) in /_/src/Controls/src/Xaml/MarkupExtensions/BindingExtension.cs:line 46
   at Microsoft.Maui.Controls.Xaml.BindingExtension.Microsoft.Maui.Controls.Xaml.IMarkupExtension<Microsoft.Maui.Controls.BindingBase>.ProvideValue(IServiceProvider serviceProvider) in /_/src/Controls/src/Xaml/MarkupExtensions/BindingExtension.cs:line 27
   at Maui.DataGrid.DataGrid.InitializeComponent() in D:\Maui.DataGrid\Maui.DataGrid\Microsoft.Maui.Controls.SourceGen\Microsoft.Maui.Controls.SourceGen.CodeBehindGenerator\DataGrid.xaml.sg.cs:line 53
   at Maui.DataGrid.DataGrid..ctor() in D:\Maui.DataGrid\Maui.DataGrid\DataGrid.xaml.cs:line 46
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Constructor(Object obj, IntPtr* args)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

**Comment by jonathanpeppers** [comment]
@daltzctr this should hopefully fix `Maui.DataGrid`:

* https://github.com/dotnet/maui/pull/24756

For `Sharpnado.Tabs` that could be a different issue, do you have a sample showing the problem?

**Comment by jonathanpeppers** [comment]
I believe this also would fix Sharpnado.Tabs, checking `InitializeComponent()` of `BottomTabItem`, I see the same issue:

![image](https://github.com/user-attachments/assets/d8a10a96-2415-40e7-aad6-93b76ca5f825)

But if @daltzctr has a sample, I could test for sure. Closing, thanks!
