### ISSUE TITLE
Works in debug and exception in release mode with Sql Server SMO in IOS

### ISSUE THREAD

**Issue by last-Programmer** [dotnet/maui#24861]
### Description

I am using Sql Server SMO nuget package with .net MAUI and when i use Microsoft.SqlServer.Management.Smo.Table.Script to script a table it throws up exception  like this

Script failed for Table 'dbo.Test'. 
   at Microsoft.SqlServer.Management.Smo.SqlSmoObject.EnumScriptImpl(ScriptingPreferences sp)
   at Microsoft.SqlServer.Management.Smo.SqlSmoObject.ScriptImpl(ScriptingPreferences sp)
   at Microsoft.SqlServer.Management.Smo.SqlSmoObject.ScriptImpl()
   at Microsoft.SqlServer.Management.Smo.TableViewTableTypeBase.Script()
   at MakeProg.Wrapper.Sql.Table.GetScript(String table, String schema, String database)
TypeInitialization_Type, Microsoft.SqlServer.Management.Smo.TypeConverters
   at Microsoft.SqlServer.Management.Smo.ScriptMaker.Script(SqlSmoObject[] objects, ISmoScriptWriter writer)
   at Microsoft.SqlServer.Management.Smo.ScriptMaker.Script(SqlSmoObject[] objects)
   at Microsoft.SqlServer.Management.Smo.SqlSmoObject.EnumScriptImplWorker(ScriptingPreferences sp)
   at Microsoft.SqlServer.Management.Smo.SqlSmoObject.EnumScriptImpl(ScriptingPreferences sp)
Arg_TargetInvocationException
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.ConstructorInfo.Invoke(Object[] parameters)
   at System.ComponentModel.ReflectTypeDescriptionProvider.CreateInstance(Type objectType, Type callingType)
   at System.ComponentModel.ReflectTypeDescriptionProvider.ReflectedTypeData.GetConverter(Object instance, Boolean verifyIsRegisteredType)
   at System.ComponentModel.ReflectTypeDescriptionProvider.GetConverter(Type type, Object instance)
   at System.ComponentModel.TypeDescriptor.DefaultTypeDescriptor.GetConverter()
   at System.ComponentModel.TypeDescriptor.GetConverter(Type type)
   at Microsoft.SqlServer.Management.Sdk.Sfc.SmoManagementUtil.GetTypeConverter(Type t)
   at Microsoft.SqlServer.Management.Smo.TypeConverters..cctor()
EnumInvalidValue
   at System.ComponentModel.EnumConverter..ctor(Type type)
   at Microsoft.SqlServer.Management.Sdk.Sfc.LocalizableEnumConverter..ctor(Type type)
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Constructor(Object obj, IntPtr* args)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)

### Steps to Reproduce

Create a new .net maui app and install Sql Server SMO and connect to sql server and try to script a table using Microsoft.SqlServer.Management.Smo.Table.Script and run in android or IOS simulator in relase mode and you can see that it threws up exception. This was not happening in .net 8. i upgraded my project to .net9 and .net 9 maui rc and this started happening.

### Version with bug

9.0.0-rc.1.24453.9

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.90 SR9

### Affected platforms

iOS, Android

### Affected platform versions

All

### Did you find any workaround?

No As Such

### Relevant log output

```shell
Script failed for Table 'dbo.Test'. 
   at Microsoft.SqlServer.Management.Smo.SqlSmoObject.EnumScriptImpl(ScriptingPreferences sp)
   at Microsoft.SqlServer.Management.Smo.SqlSmoObject.ScriptImpl(ScriptingPreferences sp)
   at Microsoft.SqlServer.Management.Smo.SqlSmoObject.ScriptImpl()
   at Microsoft.SqlServer.Management.Smo.TableViewTableTypeBase.Script()
   at MakeProg.Wrapper.Sql.Table.GetScript(String table, String schema, String database)
TypeInitialization_Type, Microsoft.SqlServer.Management.Smo.TypeConverters
   at Microsoft.SqlServer.Management.Smo.ScriptMaker.Script(SqlSmoObject[] objects, ISmoScriptWriter writer)
   at Microsoft.SqlServer.Management.Smo.ScriptMaker.Script(SqlSmoObject[] objects)
   at Microsoft.SqlServer.Management.Smo.SqlSmoObject.EnumScriptImplWorker(ScriptingPreferences sp)
   at Microsoft.SqlServer.Management.Smo.SqlSmoObject.EnumScriptImpl(ScriptingPreferences sp)
Arg_TargetInvocationException
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.ConstructorInfo.Invoke(Object[] parameters)
   at System.ComponentModel.ReflectTypeDescriptionProvider.CreateInstance(Type objectType, Type callingType)
   at System.ComponentModel.ReflectTypeDescriptionProvider.ReflectedTypeData.GetConverter(Object instance, Boolean verifyIsRegisteredType)
   at System.ComponentModel.ReflectTypeDescriptionProvider.GetConverter(Type type, Object instance)
   at System.ComponentModel.TypeDescriptor.DefaultTypeDescriptor.GetConverter()
   at System.ComponentModel.TypeDescriptor.GetConverter(Type type)
   at Microsoft.SqlServer.Management.Sdk.Sfc.SmoManagementUtil.GetTypeConverter(Type t)
   at Microsoft.SqlServer.Management.Smo.TypeConverters..cctor()
EnumInvalidValue
   at System.ComponentModel.EnumConverter..ctor(Type type)
   at Microsoft.SqlServer.Management.Sdk.Sfc.LocalizableEnumConverter..ctor(Type type)
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Constructor(Object obj, IntPtr* args)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
```

**Comment by last-Programmer** [comment]
setting UseIntrepreter true in ios solves the problem.

But in android the problem remains in the release mode.

**Comment by PureWeen** [comment]
@jonathanpeppers  thoughts?

**Comment by jonathanpeppers** [comment]
The stack trace doesn't show what the actual problem was, what failed inside `EnumScriptImpl()`? Does `Microsoft.SqlServer.Smo.dll` work on non-Windows platforms _at all_?

I can't find the source code for `SqlSmoObject`, so I can't see what platforms they expect to work. Normally, I would look here: https://source.dot.net/

**Comment by last-Programmer** [comment]
@jonathanpeppers in android and ios it works in debug config. when i run it in release config i get the exception. in ios when i use UseIntrepter as true it works in release config too. but in android i get the exception in release config.

This is working fine in .net 8. i have this problem with .net 9 rc.

**Comment by last-Programmer** [comment]
> Have you tried disabling trimming (on Android) or rooting some assemblies?

i tried this

  <PropertyGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android' and '$(Configuration)' == 'Release'">
        <PublishTrimmed>false</PublishTrimmed>
        <RunAOTCompilation>false</RunAOTCompilation>
    </PropertyGroup>

and it does not work. if there any othe things to try with androd please let me kn ow. thanks.

**Comment by jonathanpeppers** [comment]
@last-Programmer do you know where the appropriate place to file bugs for `Microsoft.SqlServer.Smo.dll`?

I don't know what the library is used for, or what it is. It is certainly not an issue in the dotnet/maui repo. We could move it to dotnet/runtime, but it's not the right place _either_.

**Comment by last-Programmer** [comment]
@jonathanpeppers It is used for managing sql server via .net code. it workes in .net8 maui android ios application and not it is not working with .net 9 maui application in ios and android. it should be something to do with .net 9 sdk that compiles for ios and android and something to do with aot or trimming. i am not sure. if you thinkg this can be moved to .net 9 sdk repo. if you could please do so. thanks
