### ISSUE TITLE
IOS Binding Library - the native class hasn't been loaded.

### ISSUE THREAD

**Issue by adarshchiniwar-smartq** [dotnet/maui#24881]
Hi,
We are trying to integratre Epson Ios SDK into our .NET MAUI App,
I have sucessfully created IOS binding library and using it in .NET maui project,
While creating the instance of a class i am getting below error
{System.Exception: Could not create an native instance of the type 'EpsonIosFramework.Epos2Printer': the native class hasn't been loaded.
It is possible to ignore this condition by setting ObjCRuntime.Class.ThrowOnInitFailure to false.
   at Foundation.NSObject.InitializeObject(Boolean alloced) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/Foundation/NSObject2.cs:line 382
   at Foundation.NSObject..ctor(NSObjectFlag x) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/Foundation/NSObject2.cs:line 221
   at EpsonIosFramework.Epos2CommonPrinter..ctor(NSObjectFlag t)
   at EpsonIosFramework.Epos2Printer..ctor(Int32 printerSeries, Int32 lang)
   at EpsonMaui.MainPage.ConnectToPrinter() in C:\Users\Adarsh.Chiniwar\source\repos\EpsonMaui\EpsonMaui\MainPage.xaml.cs:line 40}
Please help me resolve this issue.

Github repos
Maui Project - https://github.com/adarshchiniwar-smartq/EpsonMaui
IOS Binding Library - https://github.com/adarshchiniwar-smartq/EpsonIosFramework

Please help us resolve this issue

Thanks,
Adarsh

**Comment by drasticactions** [comment]
Binding questions and issues should go to [xamarin-macios](https://github.com/xamarin/xamarin-macios), which maintains this tooling.

@rolfbjarne Would you have any advice for this user?

**Comment by rolfbjarne** [comment]
@adarshchiniwar-smartq please get an [MSBuild binlog](https://github.com/xamarin/xamarin-macios/wiki/Diagnosis#binary-build-logs) that shows the error.

**Comment by rolfbjarne** [comment]
This issue was moved to xamarin/xamarin-macios#21302
