### ISSUE TITLE
ContentPage Property InputTransparent = true, causes blank page

### ISSUE THREAD

**Issue by xrysanwlh** [dotnet/maui#25007]
### Description

When setting ContentPage property InputTransparent to true, the page appears blank.

 **Is that the expected behavior?** 

Migrating from Xamarin Forms and InputTransparent property seems to have change behavior. What changed?

### Steps to Reproduce

1. Create a new .NET MAUI app
2. Add a button which sets content page's InputTransparent property to true, when clicked:

```cs
public partial class MainPage : ContentPage
{
    public MainPage()
    {
        InitializeComponent();
    }

    private void OnButtonClicked(object sender, EventArgs e)
    {
        this.InputTransparent = true;
    }
}
```

3. The page turns blank, and all the elements disappeared 

### Link to public reproduction project repository

https://github.com/xrysanwlh/MAUIInputTransparent

### Version with bug

9.0.0-rc.1.24453.9

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

**Comment by xrysanwlh** [comment]
[[](url)](https://github.com/xrysanwlh/MAUIInputTransparent)

**Comment by beeradmoore** [comment]
Came to file the same report. Created another repro here - [beeradmoore/maui-issue-InputTransparentAndroidCrash](https://github.com/beeradmoore/maui-issue-InputTransparentAndroidCrash).

My app has 4 buttons:
- InputTransparent=True (relay command)
- InputTransparent=True (async relay command)
- IsEnabled = false (relay command)
- IsEnabled = false (async relay command)

I initially thought the problem was with doing things in an async method which is why I have 4 tests. It was not related to async, or commands as I was able to replicate similar to @xrysanwlh repro that using an click action also causes it.

Adding more info to this:
- It does not impact iOS.
- Starting the page with `InputTransparent="True"` being set does not cause the issue to change. Only happens when changing it after the page is shown.
- Setting it to the root content view does not cause the issue, but it may cause the background issue.

This no longer causes a blank page, this now is a crash. @mattleibow I wonder if the issue is related to #17389 based the stacktrace below and how setting `InputTransparent=true` is somehow causing a call to `Android.Views.ViewGroup.AddView(`

```
Java.Lang.IllegalStateException: Views added to a FragmentContainerView must be associated with a Fragment. View crc6452ffdc5b34af3a0f.WrapperView{cc6307e V.E...... ......I. 0,0-0,0} is not associated with a Fragment.
   at Java.Interop.JniEnvironment.InstanceMethods.CallVoidMethod(JniObjectReference instance, JniMethodInfo method, JniArgumentValue* args) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/obj/Release/net8.0/JniEnvironment.g.cs:line 20371
   at Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualVoidMethod(String encodedMember, IJavaPeerable self, JniArgumentValue* parameters) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:line 66
   at Android.Views.ViewGroup.AddView(View child, Int32 index) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net9.0/android-35/mcw/Android.Views.ViewGroup.cs:line 2098
   at Microsoft.Maui.Platform.WrapperView.SetupContainer(View platformView, Context context, View containerView, Action`1 setWrapperView) in /_/src/Core/src/Platform/Android/WrapperView.cs:line 299
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.ContentViewGroup, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetupContainer() in /_/src/Core/src/Handlers/View/ViewHandlerOfT.Android.cs:line 21
   at Microsoft.Maui.Handlers.ViewHandler.set_HasContainer(Boolean value) in /_/src/Core/src/Handlers/View/ViewHandler.cs:line 121
   at Microsoft.Maui.Handlers.ViewHandler.MapContainerView(IViewHandler handler, IView view) in /_/src/Core/src/Handlers/View/ViewHandler.cs:line 421
   at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0[[Microsoft.Maui.IView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.IViewHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v) in /_/src/Core/src/PropertyMapper.cs:line 172
   at Microsoft.Maui.PropertyMapperExtensions.<>c__DisplayClass4_0`2[[Microsoft.Maui.Controls.VisualElement, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.IViewHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<AppendToMapping>b__0(IElementHandler handler, IElement view, Action`2 action) in /_/src/Core/src/PropertyMapperExtensions.cs:line 102
   at Microsoft.Maui.PropertyMapperExtensions.<>c__DisplayClass0_0`2[[Microsoft.Maui.IElement, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.IElementHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<ModifyMapping>g__newMethod|0(IElementHandler handler, IElement view) in /_/src/Core/src/PropertyMapperExtensions.cs:line 23
   at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0[[Microsoft.Maui.IView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.IViewHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v) in /_/src/Core/src/PropertyMapper.cs:line 172
   at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IElementHandler viewHandler, IElement virtualView) in /_/src/Core/src/PropertyMapper.cs:line 47
   at Microsoft.Maui.PropertyMapper.UpdateProperty(IElementHandler viewHandler, IElement virtualView, String property) in /_/src/Core/src/PropertyMapper.cs:line 72
   at Microsoft.Maui.Handlers.ElementHandler.UpdateValue(String property) in /_/src/Core/src/Handlers/Element/ElementHandler.cs:line 87
   at Microsoft.Maui.Handlers.ViewHandler.MapInputTransparent(IViewHandler handler, IView view) in /_/src/Core/src/Handlers/View/ViewHandler.cs:line 498
   at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0[[Microsoft.Maui.IView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.IViewHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v) in /_/src/Core/src/PropertyMapper.cs:line 172
   at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IElementHandler viewHandler, IElement virtualView) in /_/src/Core/src/PropertyMapper.cs:line 47
   at Microsoft.Maui.PropertyMapper.UpdateProperty(IElementHandler viewHandler, IElement virtualView, String property) in /_/src/Core/src/PropertyMapper.cs:line 72
   at Microsoft.Maui.Handlers.ElementHandler.UpdateValue(String property) in /_/src/Core/src/Handlers/Element/ElementHandler.cs:line 87
   at Microsoft.Maui.Controls.Element.UpdateHandlerValue(String property, Boolean valueChanged) in /_/src/Controls/src/Core/Element/Element.cs:line 686
   at Microsoft.Maui.Controls.VisualElement.UpdateHandlerValue(String property, Boolean valueChanged) in /_/src/Controls/src/Core/VisualElement/VisualElement.cs:line 2019
   at Microsoft.Maui.Controls.Element.OnBindablePropertySet(BindableProperty property, Object original, Object value, Boolean changed, Boolean willFirePropertyChanged) in /_/src/Controls/src/Core/Element/Element.cs:line 644
   at Microsoft.Maui.Controls.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, SetterSpecificity specificity, Boolean silent) in /_/src/Controls/src/Core/BindableObject.cs:line 663
   at Microsoft.Maui.Controls.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes, SetterSpecificity specificity) in /_/src/Controls/src/Core/BindableObject.cs:line 591
   at Microsoft.Maui.Controls.BindingExpression.ApplyCore(Object sourceObject, BindableObject target, BindableProperty property, Boolean fromTarget, SetterSpecificity specificity) in /_/src/Controls/src/Core/BindingExpression.cs:line 179
   at Microsoft.Maui.Controls.BindingExpression.Apply(Boolean fromTarget) in /_/src/Controls/src/Core/BindingExpression.cs:line 60
   at Microsoft.Maui.Controls.BindingExpression.BindingExpressionPart.<PropertyChanged>b__50_0() in /_/src/Controls/src/Core/BindingExpression.cs:line 712
   at Microsoft.Maui.Controls.DispatcherExtensions.DispatchIfRequired(IDispatcher dispatcher, Action action) in /_/src/Controls/src/Core/DispatcherExtensions.cs:line 59
   at Microsoft.Maui.Controls.BindingExpression.BindingExpressionPart.PropertyChanged(Object sender, PropertyChangedEventArgs args) in /_/src/Controls/src/Core/BindingExpression.cs:line 712
   at Microsoft.Maui.Controls.BindingExpression.WeakPropertyChangedProxy.OnPropertyChanged(Object sender, PropertyChangedEventArgs e) in /_/src/Controls/src/Core/BindingExpression.cs:line 613
   at CommunityToolkit.Mvvm.ComponentModel.ObservableObject.OnPropertyChanged(PropertyChangedEventArgs e) in /_/src/CommunityToolkit.Mvvm/ComponentModel/ObservableObject.cs:line 48
   at InputTransparentAndroidCrash.MainPageModel.set_PageInputTransparent(Boolean value) in /Users/beeradmoore/git/beeradmoore/maui-issue-InputTransparentAndroidCrash/InputTransparentAndroidCrash/InputTransparentAndroidCrash/obj/Debug/net9.0-android/CommunityToolkit.Mvvm.SourceGenerators/CommunityToolkit.Mvvm.SourceGenerators.ObservablePropertyGenerator/InputTransparentAndroidCrash.MainPageModel.g.cs:line 46
   at InputTransparentAndroidCrash.MainPageModel.InputTransparentTrueTapped() in /Users/beeradmoore/git/beeradmoore/maui-issue-InputTransparentAndroidCrash/InputTransparentAndroidCrash/InputTransparentAndroidCrash/MainPageModel.cs:line 30
   at CommunityToolkit.Mvvm.Input.RelayCommand.Execute(Object parameter) in /_/src/CommunityToolkit.Mvvm/Input/RelayCommand.cs:line 77
   at Microsoft.Maui.Controls.ButtonElement.ElementClicked(VisualElement visualElement, IButtonElement ButtonElementManager) in /_/src/Controls/src/Core/Button/ButtonElement.cs:line 39
   at Microsoft.Maui.Controls.Button.SendClicked() in /_/src/Controls/src/Core/Button/Button.cs:line 250
   at Microsoft.Maui.Controls.Button.Microsoft.Maui.IButton.Clicked() in /_/src/Controls/src/Core/Button/Button.cs:line 484
   at Microsoft.Maui.Handlers.ButtonHandler.OnClick(IButton button, View v) in /_/src/Core/src/Handlers/Button/ButtonHandler.Android.cs:line 151
   at Microsoft.Maui.Handlers.ButtonHandler.ButtonClickListener.OnClick(View v) in /_/src/Core/src/Handlers/Button/ButtonHandler.Android.cs:line 172
   at Android.Views.View.IOnClickListenerInvoker.n_OnClick_Landroid_view_View_(IntPtr jnienv, IntPtr native__this, IntPtr native_v) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net9.0/android-35/mcw/Android.Views.View.cs:line 2339
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPL_V(_JniMarshal_PPL_V callback, IntPtr jnienv, IntPtr klazz, IntPtr p0) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 121
  --- End of managed Java.Lang.IllegalStateException stack trace ---
java.lang.IllegalStateException: Views added to a FragmentContainerView must be associated with a Fragment. View crc6452ffdc5b34af3a0f.WrapperView{cc6307e V.E...... ......I. 0,0-0,0} is not associated with a Fragment.
	at androidx.fragment.app.FragmentContainerView.addView(FragmentContainerView.kt:263)
	at android.view.ViewGroup.addView(ViewGroup.java:5044)
	at crc64fcf28c0e24b4cc31.ButtonHandler_ButtonClickListener.n_onClick(Native Method)
	at crc64fcf28c0e24b4cc31.ButtonHandler_ButtonClickListener.onClick(ButtonHandler_ButtonClickListener.java:29)
	at android.view.View.performClick(View.java:8033)
	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1218)
	at android.view.View.performClickInternal(View.java:8010)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:31336)
	at android.os.Handler.handleCallback(Handler.java:991)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8787)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:871)

  --- End of managed Java.Lang.IllegalStateException stack trace ---
java.lang.IllegalStateException: Views added to a FragmentContainerView must be associated with a Fragment. View crc6452ffdc5b34af3a0f.WrapperView{cc6307e V.E...... ......I. 0,0-0,0} is not associated with a Fragment.
	at androidx.fragment.app.FragmentContainerView.addView(FragmentContainerView.kt:263)
	at android.view.ViewGroup.addView(ViewGroup.java:5044)
	at crc64fcf28c0e24b4cc31.ButtonHandler_ButtonClickListener.n_onClick(Native Method)
	at crc64fcf28c0e24b4cc31.ButtonHandler_ButtonClickListener.onClick(ButtonHandler_ButtonClickListener.java:29)
	at android.view.View.performClick(View.java:8033)
	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1218)
	at android.view.View.performClickInternal(View.java:8010)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:31336)
	at android.os.Handler.handleCallback(Handler.java:991)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8787)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:871)
```

**Comment by beeradmoore** [comment]
I have updated my reproduction project here with 10.0.90 - [beeradmoore/maui-issue-InputTransparentAndroidCrash](https://github.com/beeradmoore/maui-issue-InputTransparentAndroidCrash).

Opening and clicking the second row of buttons (`InputTransparent=True`) causes the app to crash on Android with

```
java.lang.IllegalStateException: Views added to a FragmentContainerView must be associated with a Fragment. View crc6452ffdc5b34af3a0f.WrapperView{5bf372e V.E...... ......I. 0,0-0,0} is not associated with a Fragment.
	at androidx.fragment.app.FragmentContainerView.addView(FragmentContainerView.kt:263)
	at android.view.ViewGroup.addView(ViewGroup.java:5058)
	at crc64fcf28c0e24b4cc31.ButtonHandler_ButtonClickListener.n_onClick(Native Method)
	at crc64fcf28c0e24b4cc31.ButtonHandler_ButtonClickListener.onClick(ButtonHandler_ButtonClickListener.java:29)
	at android.view.View.performClick(View.java:8083)
	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1218)
	at android.view.View.performClickInternal(View.java:8060)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:31549)
	at android.os.Handler.handleCallback(Handler.java:995)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loopOnce(Looper.java:248)
	at android.os.Looper.loop(Looper.java:338)
	at android.app.ActivityThread.main(ActivityThread.java:9067)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:593)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:932)
```

This does not crash on iOS.

**Comment by kubaflo** [comment]
Thanks @beeradmoore — confirmed on 10.0.90 with an updated repro (https://github.com/beeradmoore/maui-issue-InputTransparentAndroidCrash) and a clear Android-only crash:

`java.lang.IllegalStateException: Views added to a FragmentContainerView must be associated with a Fragment`, thrown from `FragmentContainerView.addView` when the `InputTransparent=True` buttons are used. It does not crash on iOS.

I've removed the `s/try-latest-version` label since that question is now answered. This stays open.

> Disclosure: this comment was generated by AI.
