### ISSUE TITLE
CollectionView throws java.lang.IllegalStateException on Android when using RemainingItemsThresholdReachedCommand

### ISSUE THREAD

**Issue by jmichas** [dotnet/maui#25010]
### Description

Please view this old bug from Xam Forms.
https://github.com/xamarin/Xamarin.Forms/issues/10825 

This is still an issue and the work around described works in MAUI.
Couldn't this be fixed at the CollectionView control level?

### Version with bug

8.0.71 SR7.1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

**Comment by devanathan-vaithiyanathan** [comment]
This issue does not reproduce in the maui version (9.0.12) with VSCode 1.94.2 and Android Pixel 8 API 35 (Android 15).

<video src="https://github.com/user-attachments/assets/4360e6b7-6822-44a0-82d2-1a264881b5d5" width="320" height="240" controls></video>

**Comment by FaithfulDev** [comment]
I'm seeing this issue on Android Pixel 7 API 35 (Android 15) using dotnet 9.0.302.

@devanathan-vaithiyanathan Just to clarify. I don't know how it was in the past, but now, the exception does not break the UI, it just causes lots of java.lang.IllegalStateException to appear in the output window.

```
[RecyclerView] Cannot call this method in a scroll callback. Scroll callbacks mightbe run during a measure & layout pass where you cannot change theRecyclerView data. Any method call that might change the structureof the RecyclerView or the adapter contents should be postponed tothe next frame.
[RecyclerView] java.lang.IllegalStateException:  crc645d80431ce5f73f11.MauiRecyclerView_3{fab1bfd VFEDHV... ......ID 0,0-985,2041}, adapter:crc645d80431ce5f73f11.ReorderableItemsViewAdapter_2@49bb21c, layout:androidx.recyclerview.widget.LinearLayoutManager@55ffe6d, context:android.view.ContextThemeWrapper@d7ff054
[RecyclerView] 	at androidx.recyclerview.widget.RecyclerView.assertNotInLayoutOrScroll(RecyclerView.java:3597)
[RecyclerView] 	at androidx.recyclerview.widget.RecyclerView$RecyclerViewDataObserver.onItemRangeInserted(RecyclerView.java:6175)
[RecyclerView] 	at androidx.recyclerview.widget.RecyclerView$AdapterDataObservable.notifyItemRangeInserted(RecyclerView.java:13411)
[RecyclerView] 	at androidx.recyclerview.widget.RecyclerView$Adapter.notifyItemRangeInserted(RecyclerView.java:8338)
[RecyclerView] 	at crc645d80431ce5f73f11.RecyclerViewScrollListener_2.n_onScrolled(Native Method)
[RecyclerView] 	at crc645d80431ce5f73f11.RecyclerViewScrollListener_2.onScrolled(RecyclerViewScrollListener_2.java:28)
[RecyclerView] 	at androidx.recyclerview.widget.RecyclerView.dispatchOnScrolled(RecyclerView.java:5780)
[RecyclerView] 	at androidx.recyclerview.widget.RecyclerView.scrollByInternal(RecyclerView.java:2297)
[RecyclerView] 	at androidx.recyclerview.widget.RecyclerView.onTouchEvent(RecyclerView.java:3958)
[RecyclerView] 	at android.view.View.performOnTouchCallback(View.java:16447)
[RecyclerView] 	at android.view.View.dispatchTouchEvent(View.java:16404)
[RecyclerView] 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3116)
[RecyclerView] 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2789)
[RecyclerView] 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3122)
[RecyclerView] 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2803)
[RecyclerView] 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3122)
[RecyclerView] 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2803)
[RecyclerView] 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3122)
[RecyclerView] 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2803)
[RecyclerView] 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3122)
[RecyclerView] 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2803)
[RecyclerView] 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3122)
[RecyclerView] 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2803)
[RecyclerView] 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3122)
[RecyclerView] 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2803)
[RecyclerView] 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3122)
[RecyclerView] 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2803)
[RecyclerView] 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3122)
[RecyclerView] 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2803)
[RecyclerView] 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3122)
[RecyclerView] 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2803)
[RecyclerView] 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3122)
[RecyclerView] 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2803)
[RecyclerView] 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3122)
[RecyclerView] 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2803)
[RecyclerView] 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3122)
[RecyclerView] 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2803)
[RecyclerView] 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3122)
[RecyclerView] 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2803)
[RecyclerView] 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3122)
[RecyclerView] 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2803)
[RecyclerView] 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3122)
[RecyclerView] 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2803)
[RecyclerView] 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3122)
[RecyclerView] 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2803)
[RecyclerView] 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3122)
[RecyclerView] 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2803)
[RecyclerView] 	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:458)
[RecyclerView] 	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1980)
[RecyclerView] 	at android.app.Activity.dispatchTouchEvent(Activity.java:4533)
[RecyclerView] 	at crc6488302ad6e9e4df1a.MauiAppCompatActivity.n_dispatchTouchEvent(Native Method)
[RecyclerView] 	at crc6488302ad6e9e4df1a.MauiAppCompatActivity.dispatchTouchEvent(MauiAppCompatActivity.java:53)
[RecyclerView] 	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
[RecyclerView] 	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:416)
[RecyclerView] 	at android.view.View.dispatchPointerEvent(View.java:16729)
[RecyclerView] 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:7947)
[RecyclerView] 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7710)
[RecyclerView] 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7106)
[RecyclerView] 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7163)
[RecyclerView] 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:7129)
[RecyclerView] 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7295)
[RecyclerView] 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:7137)
[RecyclerView] 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:7352)
[RecyclerView] 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7110)
[RecyclerView] 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7163)
[RecyclerView] 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:7129)
[RecyclerView] 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:7137)
[RecyclerView] 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7110)
[RecyclerView] 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:10214)
[RecyclerView] 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:10165)
[RecyclerView] 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:10134)
[RecyclerView] 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:10356)
[RecyclerView] 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:295)
[RecyclerView] 	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
[RecyclerView] 	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:259)
[RecyclerView] 	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:10313)
[RecyclerView] 	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:10449)
[RecyclerView] 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1406)
[RecyclerView] 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1415)
[RecyclerView] 	at android.view.Choreographer.doCallbacks(Choreographer.java:1015)
[RecyclerView] 	at android.view.Choreographer.doFrame(Choreographer.java:938)
[RecyclerView] 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1389)
[RecyclerView] 	at android.os.Handler.handleCallback(Handler.java:959)
[RecyclerView] 	at android.os.Handler.dispatchMessage(Handler.java:100)
[RecyclerView] 	at android.os.Looper.loopOnce(Looper.java:232)
[RecyclerView] 	at android.os.Looper.loop(Looper.java:317)
[RecyclerView] 	at android.app.ActivityThread.main(ActivityThread.java:8705)
[RecyclerView] 	at java.lang.reflect.Method.invoke(Native Method)
[RecyclerView] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
[RecyclerView] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
```
