### ISSUE TITLE
[Android] Unable to find the default constructor on type Microsoft.Maui.Platform.NavigationRootManager+ElementBasedFragment

### ISSUE THREAD

**Issue by Domik234** [dotnet/maui#25106]
### Description

We are receiving hundreds of these on production app but I was not able to reproduce on our devices directly. For now this thread is made as problem log.
```
Exception : android.runtime.JavaProxyThrowable	[System.NotSupportedException]
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3939)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:4096)
  at android.app.servertransaction.LaunchActivityItem.execute (LaunchActivityItem.java:103)
  at android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:135)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:95)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2441)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loopOnce (Looper.java:233)
  at android.os.Looper.loop (Looper.java:334)
  at android.app.ActivityThread.main (ActivityThread.java:8396)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:582)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1068)
Caused by androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment crc6452ffdc5b34af3a0f.NavigationRootManager_ElementBasedFragment: calling Fragment constructor caused an exception
  at androidx.fragment.app.Fragment.instantiate (Fragment.java:690)
  at androidx.fragment.app.FragmentContainer.instantiate (FragmentContainer.java:57)
  at androidx.fragment.app.FragmentManager$3.instantiate (FragmentManager.java:525)
  at androidx.fragment.app.FragmentState.instantiate (FragmentState.java:84)
  at androidx.fragment.app.FragmentStateManager.<init> (FragmentStateManager.java:91)
  at androidx.fragment.app.FragmentManager.restoreSaveStateInternal (FragmentManager.java:2562)
  at androidx.fragment.app.FragmentManager.attachController (FragmentManager.java:2722)
  at androidx.fragment.app.FragmentController.attachHost (FragmentController.java:117)
  at androidx.fragment.app.FragmentActivity.lambda$init$3$androidx-fragment-app-FragmentActivity (FragmentActivity.java:139)
  at androidx.fragment.app.FragmentActivity$$ExternalSyntheticLambda3.onContextAvailable
  at androidx.activity.contextaware.ContextAwareHelper.dispatchOnContextAvailable (ContextAwareHelper.kt:84)
  at androidx.activity.ComponentActivity.onCreate (ComponentActivity.java:358)
  at androidx.fragment.app.FragmentActivity.onCreate (FragmentActivity.java:216)
  at crc6485471912988313e7.MainActivity.n_onCreate
  at crc6485471912988313e7.MainActivity.onCreate (MainActivity.java:42)
  at android.app.Activity.performCreate (Activity.java:8369)
  at android.app.Activity.performCreate (Activity.java:8347)
  at android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1379)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3912)
Caused by java.lang.reflect.InvocationTargetException:
  at java.lang.reflect.Constructor.newInstance0
  at java.lang.reflect.Constructor.newInstance (Constructor.java:343)
  at androidx.fragment.app.Fragment.instantiate (Fragment.java:672)
Caused by android.runtime.JavaProxyThrowable: [System.NotSupportedException]: Unable to find the default constructor on type Microsoft.Maui.Platform.NavigationRootManager+ElementBasedFragment.  Please provide the missing constructor.
  at Java.Interop.TypeManager.n_Activate
  at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPLLLL_V
  at mono.android.TypeManager.n_activate
  at mono.android.TypeManager.Activate (TypeManager.java:7)
  at crc6452ffdc5b34af3a0f.NavigationRootManager_ElementBasedFragment.<init> (NavigationRootManager_ElementBasedFragment.java:23)
```

Some screenshots from Google Play Console (30th Sept was migration date from XF to MAUI):
![image](https://github.com/user-attachments/assets/ec967fec-b20d-432b-b24f-dab56d265517)
![image](https://github.com/user-attachments/assets/e3a28af6-259f-4607-b995-bff2c4e7a13d)

### Version with bug

8.0.91 SR9.1

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

**Comment by Zhanglirong-Winnie** [comment]
Hi, @Domik234 
Could you provide us with a sample project so we can investigate it further? Looking forward to your reply!

**Comment by Domik234** [comment]
I didn't find the case when it happens. I thought that Crashlytics will help but the result there is the same as the original at start.

For now I am adding some more infos (older logs from logcat). Issue will be closed until some more infos.

(Maybe related? [[.NET 8] Android crash at xamarin::android::Helpers::abort_application](https://github.com/dotnet/android/issues/8673))

adb logcat | findstr mono
```
09-12 11:07:32.714 11561 11561 E AndroidRuntime:        at mono.android.TypeManager.n_activate(Native Method)
09-12 11:07:32.714 11561 11561 E AndroidRuntime:        at mono.android.TypeManager.Activate(TypeManager.java:7)
09-13 16:05:20.468 11249 11249 F DEBUG   :       #01 pc 000000000002680c  /data/app/com.application.one_test-TbeKp6JNxTcd4lKfOHvf-Q==/lib/arm64/libmonodroid.so (xamarin::android::Helpers::abort_application()+8) (BuildId: 184c010f647c8b8b79444ebce19c6cc7884036a1)
09-13 16:05:20.468 11249 11249 F DEBUG   :       #02 pc 0000000000041edc  /data/app/com.application.one_test-TbeKp6JNxTcd4lKfOHvf-Q==/lib/arm64/libmonodroid.so (xamarin::android::internal::MonodroidRuntime::mono_log_handler(char const*, char const*, char const*, int, void*)+144) (BuildId: 184c010f647c8b8b79444ebce19c6cc7884036a1)
09-13 16:05:20.468 11249 11249 F DEBUG   :       #03 pc 00000000001d7464  /data/app/com.application.one_test-TbeKp6JNxTcd4lKfOHvf-Q==/lib/arm64/libmonosgen-2.0.so (BuildId: eb24a52f2dd44e052b62836d7c0d12115d335fb9)
09-13 16:05:20.468 11249 11249 F DEBUG   :       #04 pc 00000000001d7590  /data/app/com.application.one_test-TbeKp6JNxTcd4lKfOHvf-Q==/lib/arm64/libmonosgen-2.0.so (BuildId: eb24a52f2dd44e052b62836d7c0d12115d335fb9)
09-13 16:05:20.468 11249 11249 F DEBUG   :       #05 pc 00000000001d75d4  /data/app/com.application.one_test-TbeKp6JNxTcd4lKfOHvf-Q==/lib/arm64/libmonosgen-2.0.so (BuildId: eb24a52f2dd44e052b62836d7c0d12115d335fb9)
09-13 16:05:20.468 11249 11249 F DEBUG   :       #06 pc 00000000001fedb4  /data/app/com.application.one_test-TbeKp6JNxTcd4lKfOHvf-Q==/lib/arm64/libmonosgen-2.0.so (BuildId: eb24a52f2dd44e052b62836d7c0d12115d335fb9)
09-13 16:05:20.468 11249 11249 F DEBUG   :       #07 pc 00000000001f9f1c  /data/app/com.application.one_test-TbeKp6JNxTcd4lKfOHvf-Q==/lib/arm64/libmonosgen-2.0.so (mono_init+268) (BuildId: eb24a52f2dd44e052b62836d7c0d12115d335fb9)
09-13 16:05:20.468 11249 11249 F DEBUG   :       #08 pc 00000000000c45f8  /data/app/com.application.one_test-TbeKp6JNxTcd4lKfOHvf-Q==/lib/arm64/libmonosgen-2.0.so (BuildId: eb24a52f2dd44e052b62836d7c0d12115d335fb9)
09-13 16:05:20.468 11249 11249 F DEBUG   :       #09 pc 0000000000119614  /data/app/com.application.one_test-TbeKp6JNxTcd4lKfOHvf-Q==/lib/arm64/libmonosgen-2.0.so (mono_jit_init_version+16) (BuildId: eb24a52f2dd44e052b62836d7c0d12115d335fb9)
09-13 16:05:20.468 11249 11249 F DEBUG   :       #10 pc 00000000000298ec  /data/app/com.application.one_test-TbeKp6JNxTcd4lKfOHvf-Q==/lib/arm64/libmonodroid.so (xamarin::android::internal::MonodroidRuntime::create_domain(_JNIEnv*, xamarin::android::jstring_array_wrapper&, bool, bool)+216) (BuildId: 184c010f647c8b8b79444ebce19c6cc7884036a1)
09-13 16:05:20.468 11249 11249 F DEBUG   :       #11 pc 000000000002d6b0  /data/app/com.application.one_test-TbeKp6JNxTcd4lKfOHvf-Q==/lib/arm64/libmonodroid.so (xamarin::android::internal::MonodroidRuntime::create_and_initialize_domain(_JNIEnv*, _jclass*, xamarin::android::jstring_array_wrapper&, xamarin::android::jstring_array_wrapper&, _jobjectArray*, xamarin::android::jstring_array_wrapper&, _jobject*, bool, bool, bool)+52) (BuildId: 184c010f647c8b8b79444ebce19c6cc7884036a1)
09-13 16:05:20.468 11249 11249 F DEBUG   :       #12 pc 0000000000031250  /data/app/com.application.one_test-TbeKp6JNxTcd4lKfOHvf-Q==/lib/arm64/libmonodroid.so (xamarin::android::internal::MonodroidRuntime::Java_mono_android_Runtime_initInternal(_JNIEnv*, _jclass*, _jstring*, _jobjectArray*, _jstring*, _jobjectArray*, int, _jobject*, _jobjectArray*, int, unsigned char, unsigned char)+4184) (BuildId: 184c010f647c8b8b79444ebce19c6cc7884036a1)
09-13 16:05:20.468 11249 11249 F DEBUG   :       #13 pc 0000000000034734  /data/app/com.application.one_test-TbeKp6JNxTcd4lKfOHvf-Q==/lib/arm64/libmonodroid.so (Java_mono_android_Runtime_initInternal+88) (BuildId: 184c010f647c8b8b79444ebce19c6cc7884036a1)
09-13 16:05:20.468 11249 11249 F DEBUG   :       #21 pc 000000000051896e  [anon:dalvik-classes.dex extracted in memory from /data/app/com.application.one_test-TbeKp6JNxTcd4lKfOHvf-Q==/base.apk] (mono.MonoPackageManager.LoadApplication+422)
09-13 16:05:20.468 11249 11249 F DEBUG   :       #24 pc 0000000000518ace  [anon:dalvik-classes.dex extracted in memory from /data/app/com.application.one_test-TbeKp6JNxTcd4lKfOHvf-Q==/base.apk] (mono.MonoRuntimeProvider.attachInfo+74)
09-30 10:05:54.640 14650 14650 E AndroidRuntime:        at mono.android.TypeManager.n_activate(Native Method)
09-30 10:05:54.640 14650 14650 E AndroidRuntime:        at mono.android.TypeManager.Activate(TypeManager.java:7)
09-30 14:22:15.261  6786  6786 E AndroidRuntime:        at mono.android.TypeManager.n_activate(Native Method)
09-30 14:22:15.261  6786  6786 E AndroidRuntime:        at mono.android.TypeManager.Activate(TypeManager.java:7)
09-30 14:29:58.845 14769 14769 E AndroidRuntime:        at mono.android.TypeManager.n_activate(Native Method)
09-30 14:29:58.845 14769 14769 E AndroidRuntime:        at mono.android.TypeManager.Activate(TypeManager.java:7)
09-30 14:39:23.118 18655 18655 E AndroidRuntime:        at mono.android.TypeManager.n_activate(Native Method)
09-30 14:39:23.118 18655 18655 E AndroidRuntime:        at mono.android.TypeManager.Activate(TypeManager.java:7)
09-30 14:39:37.867 19113 19113 E AndroidRuntime:        at mono.android.TypeManager.n_activate(Native Method)
09-30 14:39:37.867 19113 19113 E AndroidRuntime:        at mono.android.TypeManager.Activate(TypeManager.java:7)
09-30 14:40:36.540 19352 19352 E AndroidRuntime:        at mono.android.TypeManager.n_activate(Native Method)
09-30 14:40:36.540 19352 19352 E AndroidRuntime:        at mono.android.TypeManager.Activate(TypeManager.java:7)
09-30 14:40:46.177 19662 19662 E AndroidRuntime:        at mono.android.TypeManager.n_activate(Native Method)
09-30 14:40:46.177 19662 19662 E AndroidRuntime:        at mono.android.TypeManager.Activate(TypeManager.java:7)
09-30 14:41:23.874 19858 19858 E AndroidRuntime:        at mono.android.TypeManager.n_activate(Native Method)
09-30 14:41:23.874 19858 19858 E AndroidRuntime:        at mono.android.TypeManager.Activate(TypeManager.java:7)
09-30 14:43:57.453 20095 20095 E AndroidRuntime:        at mono.android.TypeManager.n_activate(Native Method)
09-30 14:43:57.453 20095 20095 E AndroidRuntime:        at mono.android.TypeManager.Activate(TypeManager.java:7)
10-07 14:19:29.120 26719 26719 F DEBUG   :       #01 pc 000000000001f360  /data/app/com.application.two_test-IPXQnbn3py8MfGWmnPM47w==/lib/arm64/libmonodroid.so (xamarin::android::Helpers::abort_application()+8) (BuildId: 807de66943560632b34b419d7ba5a50611f204eb)
10-07 14:19:29.120 26719 26719 F DEBUG   :       #02 pc 0000000000035660  /data/app/com.application.two_test-IPXQnbn3py8MfGWmnPM47w==/lib/arm64/libmonodroid.so (xamarin::android::internal::MonodroidRuntime::mono_log_handler(char const*, char const*, char const*, int, void*)+144) (BuildId: 807de66943560632b34b419d7ba5a50611f204eb)
10-07 14:19:29.120 26719 26719 F DEBUG   :       #03 pc 00000000001d7464  /data/app/com.application.two_test-IPXQnbn3py8MfGWmnPM47w==/lib/arm64/libmonosgen-2.0.so (BuildId: eb24a52f2dd44e052b62836d7c0d12115d335fb9)
10-07 14:19:29.120 26719 26719 F DEBUG   :       #04 pc 00000000001d7590  /data/app/com.application.two_test-IPXQnbn3py8MfGWmnPM47w==/lib/arm64/libmonosgen-2.0.so (BuildId: eb24a52f2dd44e052b62836d7c0d12115d335fb9)
10-07 14:19:29.120 26719 26719 F DEBUG   :       #05 pc 00000000001d75d4  /data/app/com.application.two_test-IPXQnbn3py8MfGWmnPM47w==/lib/arm64/libmonosgen-2.0.so (BuildId: eb24a52f2dd44e052b62836d7c0d12115d335fb9)
10-07 14:19:29.120 26719 26719 F DEBUG   :       #06 pc 000000000013f2b4  /data/app/com.application.two_test-IPXQnbn3py8MfGWmnPM47w==/lib/arm64/libmonosgen-2.0.so (BuildId: eb24a52f2dd44e052b62836d7c0d12115d335fb9)
10-07 14:19:29.120 26719 26719 F DEBUG   :       #07 pc 00000000001527a0  /data/app/com.application.two_test-IPXQnbn3py8MfGWmnPM47w==/lib/arm64/libmonosgen-2.0.so (BuildId: eb24a52f2dd44e052b62836d7c0d12115d335fb9)
10-07 14:19:51.845 26984 26984 F DEBUG   :       #01 pc 000000000001f360  /data/app/com.application.two_test-IPXQnbn3py8MfGWmnPM47w==/lib/arm64/libmonodroid.so (xamarin::android::Helpers::abort_application()+8) (BuildId: 807de66943560632b34b419d7ba5a50611f204eb)
10-07 14:19:51.845 26984 26984 F DEBUG   :       #02 pc 0000000000035660  /data/app/com.application.two_test-IPXQnbn3py8MfGWmnPM47w==/lib/arm64/libmonodroid.so (xamarin::android::internal::MonodroidRuntime::mono_log_handler(char const*, char const*, char const*, int, void*)+144) (BuildId: 807de66943560632b34b419d7ba5a50611f204eb)
10-07 14:19:51.845 26984 26984 F DEBUG   :       #03 pc 00000000001d7464  /data/app/com.application.two_test-IPXQnbn3py8MfGWmnPM47w==/lib/arm64/libmonosgen-2.0.so (BuildId: eb24a52f2dd44e052b62836d7c0d12115d335fb9)
10-07 14:19:51.845 26984 26984 F DEBUG   :       #04 pc 00000000001d7590  /data/app/com.application.two_test-IPXQnbn3py8MfGWmnPM47w==/lib/arm64/libmonosgen-2.0.so (BuildId: eb24a52f2dd44e052b62836d7c0d12115d335fb9)
10-07 14:19:51.845 26984 26984 F DEBUG   :       #05 pc 00000000001d75d4  /data/app/com.application.two_test-IPXQnbn3py8MfGWmnPM47w==/lib/arm64/libmonosgen-2.0.so (BuildId: eb24a52f2dd44e052b62836d7c0d12115d335fb9)
10-07 14:19:51.845 26984 26984 F DEBUG   :       #06 pc 000000000013f2b4  /data/app/com.application.two_test-IPXQnbn3py8MfGWmnPM47w==/lib/arm64/libmonosgen-2.0.so (BuildId: eb24a52f2dd44e052b62836d7c0d12115d335fb9)
10-07 14:19:51.845 26984 26984 F DEBUG   :       #07 pc 00000000001527a0  /data/app/com.application.two_test-IPXQnbn3py8MfGWmnPM47w==/lib/arm64/libmonosgen-2.0.so (BuildId: eb24a52f2dd44e052b62836d7c0d12115d335fb9)
10-07 14:37:43.255 28415 28415 F DEBUG   :       #01 pc 000000000001f360  /data/app/com.application.two_test-rRJKar9qOmMQSO-BKS6vVg==/lib/arm64/libmonodroid.so (xamarin::android::Helpers::abort_application()+8) (BuildId: 807de66943560632b34b419d7ba5a50611f204eb)
10-07 14:37:43.255 28415 28415 F DEBUG   :       #02 pc 0000000000035660  /data/app/com.application.two_test-rRJKar9qOmMQSO-BKS6vVg==/lib/arm64/libmonodroid.so (xamarin::android::internal::MonodroidRuntime::mono_log_handler(char const*, char const*, char const*, int, void*)+144) (BuildId: 807de66943560632b34b419d7ba5a50611f204eb)
10-07 14:37:43.255 28415 28415 F DEBUG   :       #03 pc 00000000001d7464  /data/app/com.application.two_test-rRJKar9qOmMQSO-BKS6vVg==/lib/arm64/libmonosgen-2.0.so (BuildId: eb24a52f2dd44e052b62836d7c0d12115d335fb9)
10-07 14:37:43.255 28415 28415 F DEBUG   :       #04 pc 00000000001d7590  /data/app/com.application.two_test-rRJKar9qOmMQSO-BKS6vVg==/lib/arm64/libmonosgen-2.0.so (BuildId: eb24a52f2dd44e052b62836d7c0d12115d335fb9)
10-07 14:37:43.256 28415 28415 F DEBUG   :       #05 pc 00000000001d75d4  /data/app/com.application.two_test-rRJKar9qOmMQSO-BKS6vVg==/lib/arm64/libmonosgen-2.0.so (BuildId: eb24a52f2dd44e052b62836d7c0d12115d335fb9)
10-07 14:37:43.256 28415 28415 F DEBUG   :       #06 pc 000000000013f2b4  /data/app/com.application.two_test-rRJKar9qOmMQSO-BKS6vVg==/lib/arm64/libmonosgen-2.0.so (BuildId: eb24a52f2dd44e052b62836d7c0d12115d335fb9)
10-07 14:37:43.256 28415 28415 F DEBUG   :       #07 pc 00000000001527a0  /data/app/com.application.two_test-rRJKar9qOmMQSO-BKS6vVg==/lib/arm64/libmonosgen-2.0.so (BuildId: eb24a52f2dd44e052b62836d7c0d12115d335fb9)
11-05 10:07:37.303  2322  2322 W linker  : Warning: "/data/app/com.google.android.trichromelibrary_672308633-k7uzify8hfJ4a5tZ2xubzw==/base.apk!/lib/arm64-v8a/libmonochrome_64.so" unused DT entry: unknown processor-specific (type 0x70000001 arg 0x0) (ignoring)
```
