### ISSUE TITLE
Microsoft.Maui.Handlers.ButtonHandler' threw an exception. On Release Build - App Launch

### ISSUE THREAD

**Issue by LeoJHarris** [dotnet/maui#25142]
### Description

Appears to be same as https://github.com/dotnet/maui/issues/23954 which was closed for no apparent reason. Was this fixed?

### Version with bug

8.0.91 SR9.1

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 14

### Did you find any workaround?

No

### Relevant log output

```shell
Time	Device Name	Type	PID	Tag	Message
10-09 12:59:54.144		Error	14733	AndroidRuntime	android.runtime.JavaProxyThrowable: [System.TypeInitializationException]: The type initializer for 'Microsoft.Maui.Handlers.ButtonHandler' threw an exception.
	at Microsoft.Maui.Controls.Hosting.AppHostBuilderExtensions.RemapForControls(Unknown Source:0)
	at Microsoft.Maui.Controls.Hosting.AppHostBuilderExtensions.SetupDefaults(Unknown Source:0)
	at Microsoft.Maui.Controls.Hosting.AppHostBuilderExtensions.UseMauiPrimaryApp(Unknown Source:0)
	at Microsoft.Maui.Controls.Hosting.AppHostBuilderExtensions.UseMauiApp(Unknown Source:0)
	at SampleApp.MauiProgram.CreateMauiApp(Unknown Source:0)
	at SampleApp.MainApplication.CreateMauiApp(Unknown Source:0)
	at Microsoft.Maui.MauiApplication.OnCreate(Unknown Source:0)
	at Android.App.Application.n_OnCreate(Unknown Source:0)
	at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(Unknown Source:0)
	at crc6488302ad6e9e4df1a.MauiApplication.n_onCreate(Native Method)
	at crc6488302ad6e9e4df1a.MauiApplication.onCreate(MauiApplication.java:28)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1316)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7711)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2478)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
```
```

**Comment by ninachen03** [comment]
Could you provide us with a sample project so we can investigate it further? Looking forward to your reply!

**Comment by nixkuroi** [comment]
This happened to me today out of nowhere.   The project was working fine.  I decided to add some new functionality that wasn't wired up, but required adding Microsoft.Maui.Graphics.Skia nuget package.  I added the 9.0x rc.  The first attempt to run it on a device resulted in:  

: 'The type initializer for 'Microsoft.Maui.Handlers.ButtonHandler' threw an exception.'

I removed Microsoft.Maui.Graphics.Skia and added back the stable 8.0.9.1 version and that worked.  

My guess is that this is a .net 9.0 compat issue.

**Comment by LeoJHarris** [comment]
@nixkuroi we dont use Skia anywhere and still have the issue

**Comment by LeoJHarris** [comment]
Same issue in `Microsoft.Maui.Controls` version 8.0.92, app crashes immediately in Release mode, this is blocking and we cannot get a release build.

**Comment by LeoJHarris** [comment]
Any update or am I the only one having this issue?

**Comment by Skarzag** [comment]
Hi ! I'm having the exact same issue in release mode, hopefuly i tested the production release before releasing it to the public !

**Comment by LeoJHarris** [comment]
@Skarzag its completely blocking us from an Android release atm, fortunately the final Xamarin.Android build we release is still sitting stable on the play store but should we need to get an urgent fix for whatever reason we are completely stuck and that includes iOS with the latest apple authentication issue.

We use the following NuGets packages

``` csproj
<!-- begins shared packages -->
<ItemGroup>
	<PackageReference Include="Microsoft.AppCenter" Version="5.0.6" />
	<PackageReference Include="Microsoft.AppCenter.Analytics" Version="5.0.6" />
	<PackageReference Include="Microsoft.AppCenter.Crashes" Version="5.0.6" />
	<PackageReference Include="Microsoft.Extensions.Http.Resilience" Version="8.10.0" />
	<PackageReference Include="Microsoft.Extensions.Logging.Console" Version="8.0.1" />
	<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="8.0.1" />
	<PackageReference Update="Microsoft.Maui.Controls" Version="8.0.92" />
	<PackageReference Update="Microsoft.Maui.Controls.Compatibility" Version="8.0.92" />
	<PackageReference Include="CommunityToolkit.Maui" Version="9.1.0" />
	<PackageReference Include="CommunityToolkit.Maui.MediaElement" Version="4.1.2" />
	<PackageReference Include="CommunityToolkit.Mvvm" Version="8.3.2" />
	<PackageReference Include="EzPasswordValidator" Version="2.1.0" />
	<PackageReference Include="GeoTimeZone" Version="5.3.0" />
	<PackageReference Include="LocalizationResourceManager.Maui" Version="1.3.0-alpha.1" />
	<PackageReference Include="Microsoft.Extensions.Http.Polly" Version="8.0.10" />
	<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
	<PackageReference Include="Onion.Maui.GoogleMaps" Version="6.0.1" />
	<PackageReference Include="Oscore.Maui.Biometric" Version="1.0.1" />
	<PackageReference Include="Plugin.LocalNotification" Version="11.1.4" />
	<PackageReference Include="Plugin.StoreReview" Version="6.2.0" />
	<PackageReference Include="Prism.DryIoc.Maui" Version="9.0.537" />
	<PackageReference Include="Prism.Maui.Rx" Version="9.0.537" />
	<PackageReference Include="Sharpnado.Tabs.Maui" Version="3.2.1" />
	<PackageReference Include="YoutubeExplode" Version="6.4.3" />
	<PackageReference Include="ZXing.Net.Maui.Controls" Version="0.4.0" />
</ItemGroup>
<!--ends shared packages-->

<!--begins android packages-->
<ItemGroup Condition="'$(TargetFramework)' == 'net8.0-android34.0'">
	<PackageReference Include="Xamarin.AndroidX.Collection">
		<Version>1.4.4</Version>
	</PackageReference>
	<PackageReference Include="Xamarin.AndroidX.Collection.Ktx">
		<Version>1.4.4</Version>
	</PackageReference>
	<PackageReference Include="Xamarin.AndroidX.Fragment.Ktx">
		<Version>1.8.4</Version>
	</PackageReference>
	<PackageReference Include="Xamarin.AndroidX.Lifecycle.Common">
		<Version>2.8.6</Version>
	</PackageReference>
	<PackageReference Include="Xamarin.AndroidX.Lifecycle.Runtime">
		<Version>2.8.6</Version>
	</PackageReference>
	<PackageReference Include="Xamarin.Firebase.Core">
		<Version>121.1.1.11</Version>
	</PackageReference>
	<PackageReference Include="Xamarin.Firebase.Crashlytics">
		<Version>119.2.1</Version>
	</PackageReference>
	<PackageReference Include="Xamarin.Firebase.Messaging">
		<Version>124.0.3</Version>
	</PackageReference>
	<PackageReference Include="Xamarin.GooglePlayServices.Auth.Api.Phone">
		<Version>118.1.0.2</Version>
	</PackageReference>
</ItemGroup>
<!--ends android packages-->
```

**Comment by Skarzag** [comment]
Just found what was our problem : This doesn't happen on iOS so i focused on Android and...
I've deactivated R8 tool in the app project and everything is back to normal.

`<!--DISABLED BECAUSE IT CRASH AT STARTUP ON ANDROID RELEASE <AndroidLinkTool>r8</AndroidLinkTool>-->`

**Comment by LeoJHarris** [comment]
@Skarzag suggestions also resolved it for me, I've just disabled both D8 & r8 but I did suspect something like this earlier and I tried playing around with the proguard.cfg file without any luck to prevent necessary classes and methods are not removed or obfuscated by ProGuard.

@PureWeen @samhouts @jonathanpeppers  any ideas or do we just disable this for the time being?

**Comment by jonathanpeppers** [comment]
If you can get the [`adb logcat`](https://docs.microsoft.com/xamarin/android/deploy-test/debugging/android-debug-log) output, it will show the Java class that `r8` removed in the error. You should then be able to add a ProGuard rule to preserve the Java class.

`AndroidLinkMode=r8` is a more advanced feature that is not on by default, because most apps require a few rules in order to work.

**Comment by LeoJHarris** [comment]
@jonathanpeppers I am just searching through the the logcat now, is there a particular `tag` to look for or message when searching information on the Java class that `r8` removed?

**Comment by jonathanpeppers** [comment]
Usually, it's a crash and your app closes, and there is a Java stacktrace of the missing type.

**Comment by LeoJHarris** [comment]
@jonathanpeppers The java stacktrace from logcat:

```
10-31 09:09:01.982 31702 31702 I MonoDroid: Android.Runtime.JavaProxyThrowable: Exception of type 'Android.Runtime.JavaProxyThrowable' was thrown.
10-31 09:09:01.982 31702 31702 I MonoDroid:
10-31 09:09:01.982 31702 31702 I MonoDroid:   --- End of managed Android.Runtime.JavaProxyThrowable stack trace ---
10-31 09:09:01.982 31702 31702 I MonoDroid: android.runtime.JavaProxyThrowable: [System.TypeInitializationException]: The type initializer for 'Microsoft.Maui.Handlers.ButtonHandler' threw an exception.
10-31 09:09:01.982 31702 31702 I MonoDroid:     at Microsoft.Maui.Controls.Hosting.AppHostBuilderExtensions.RemapForControls(Unknown Source:0)
10-31 09:09:01.982 31702 31702 I MonoDroid:     at Microsoft.Maui.Controls.Hosting.AppHostBuilderExtensions.SetupDefaults(Unknown Source:0)
10-31 09:09:01.982 31702 31702 I MonoDroid:     at Microsoft.Maui.Controls.Hosting.AppHostBuilderExtensions.UseMauiPrimaryApp(Unknown Source:0)
10-31 09:09:01.982 31702 31702 I MonoDroid:     at Microsoft.Maui.Controls.Hosting.AppHostBuilderExtensions.UseMauiApp(Unknown Source:0)
10-31 09:09:01.982 31702 31702 I MonoDroid:     at SampleApp.MauiProgram.CreateMauiApp(Unknown Source:0)
10-31 09:09:01.982 31702 31702 I MonoDroid:     at SampleApp.MainApplication.CreateMauiApp(Unknown Source:0)
10-31 09:09:01.982 31702 31702 I MonoDroid:     at Microsoft.Maui.MauiApplication.OnCreate(Unknown Source:0)
10-31 09:09:01.982 31702 31702 I MonoDroid:     at Android.App.Application.n_OnCreate(Unknown Source:0)
10-31 09:09:01.982 31702 31702 I MonoDroid:     at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(Unknown Source:0)
10-31 09:09:01.982 31702 31702 I MonoDroid:     at crc6488302ad6e9e4df1a.MauiApplication.n_onCreate(Native Method)
10-31 09:09:01.982 31702 31702 I MonoDroid:     at crc6488302ad6e9e4df1a.MauiApplication.onCreate(MauiApplication.java:28)
10-31 09:09:01.982 31702 31702 I MonoDroid:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1316)
10-31 09:09:01.982 31702 31702 I MonoDroid:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7711)
10-31 09:09:01.982 31702 31702 I MonoDroid:     at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
10-31 09:09:01.982 31702 31702 I MonoDroid:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2478)
10-31 09:09:01.982 31702 31702 I MonoDroid:     at android.os.Handler.dispatchMessage(Handler.java:106)
10-31 09:09:01.982 31702 31702 I MonoDroid:     at android.os.Looper.loopOnce(Looper.java:230)
10-31 09:09:01.982 31702 31702 I MonoDroid:     at android.os.Looper.loop(Looper.java:319)
10-31 09:09:01.982 31702 31702 I MonoDroid:     at android.app.ActivityThread.main(ActivityThread.java:8919)
10-31 09:09:01.982 31702 31702 I MonoDroid:     at java.lang.reflect.Method.invoke(Native Method)
10-31 09:09:01.982 31702 31702 I MonoDroid:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
10-31 09:09:01.982 31702 31702 I MonoDroid:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
10-31 09:09:01.982 31702 31702 I MonoDroid:
10-31 09:09:01.982 31702 31702 I MonoDroid:   --- End of managed Android.Runtime.JavaProxyThrowable stack trace ---
10-31 09:09:01.982 31702 31702 I MonoDroid: android.runtime.JavaProxyThrowable: [System.TypeInitializationException]: The type initializer for 'Microsoft.Maui.Handlers.ButtonHandler' threw an exception.
10-31 09:09:01.982 31702 31702 I MonoDroid:     at Microsoft.Maui.Controls.Hosting.AppHostBuilderExtensions.RemapForControls(Unknown Source:0)
10-31 09:09:01.982 31702 31702 I MonoDroid:     at Microsoft.Maui.Controls.Hosting.AppHostBuilderExtensions.SetupDefaults(Unknown Source:0)
10-31 09:09:01.982 31702 31702 I MonoDroid:     at Microsoft.Maui.Controls.Hosting.AppHostBuilderExtensions.UseMauiPrimaryApp(Unknown Source:0)
10-31 09:09:01.982 31702 31702 I MonoDroid:     at Microsoft.Maui.Controls.Hosting.AppHostBuilderExtensions.UseMauiApp(Unknown Source:0)
10-31 09:09:01.982 31702 31702 I MonoDroid:     at SampleApp.MauiProgram.CreateMauiApp(Unknown Source:0)
10-31 09:09:01.982 31702 31702 I MonoDroid:     at SampleApp.MainApplication.CreateMauiApp(Unknown Source:0)
10-31 09:09:01.982 31702 31702 I MonoDroid:     at Microsoft.Maui.MauiApplication.OnCreate(Unknown Source:0)
10-31 09:09:01.982 31702 31702 I MonoDroid:     at Android.App.Application.n_OnCreate(Unknown Source:0)
10-31 09:09:01.982 31702 31702 I MonoDroid:     at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(Unknown Source:0)
10-31 09:09:01.982 31702 31702 I MonoDroid:     at crc6488302ad6e9e4df1a.MauiApplication.n_onCreate(Native Method)
10-31 09:09:01.982 31702 31702 I MonoDroid:     at crc6488302ad6e9e4df1a.MauiApplication.onCreate(MauiApplication.java:28)
10-31 09:09:01.982 31702 31702 I MonoDroid:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1316)
10-31 09:09:01.982 31702 31702 I MonoDroid:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7711)
10-31 09:09:01.982 31702 31702 I MonoDroid:     at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
10-31 09:09:01.982 31702 31702 I MonoDroid:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2478)
10-31 09:09:01.982 31702 31702 I MonoDroid:     at android.os.Handler.dispatchMessage(Handler.java:106)
10-31 09:09:01.982 31702 31702 I MonoDroid:     at android.os.Looper.loopOnce(Looper.java:230)
10-31 09:09:01.982 31702 31702 I MonoDroid:     at android.os.Looper.loop(Looper.java:319)
10-31 09:09:01.982 31702 31702 I MonoDroid:     at android.app.ActivityThread.main(ActivityThread.java:8919)
10-31 09:09:01.982 31702 31702 I MonoDroid:     at java.lang.reflect.Method.invoke(Native Method)
10-31 09:09:01.982 31702 31702 I MonoDroid:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
10-31 09:09:01.982 31702 31702 I MonoDroid:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
10-31 09:09:01.982 31702 31702 I MonoDroid:
```

I trying the following rules

```
# Keep the ButtonHandler class and its methods
-keep class Microsoft.Maui.Handlers.ButtonHandler { *; }

# Keep all classes that extend ButtonHandler
-keep class * extends Microsoft.Maui.Handlers.ButtonHandler { *; }

# Keep all methods in the Microsoft.Maui.Handlers package
-keep class Microsoft.Maui.Handlers.** { *; }
}
```

**Comment by LeoJHarris** [comment]
@jonathanpeppers just checking as well, I have added my `proguard.cfg` to our MAUI app but we dont have the old `ProGuardConfiguration` build action anymore, I assume we can leave this as 'None'?

**Comment by jonathanpeppers** [comment]
It looks to me like the inner exception is lost: `The type initializer for 'Microsoft.Maui.Handlers.ButtonHandler' threw an exception.` It doesn't say what the exception was. Hard to know if this is an `r8` issue at all, without seeing the underlying exception. Does a `new ButtonHandler()` call somewhere in the app, show the full error?

`ProguardConfiguration` is the item group you use:

* https://github.com/dotnet/android/blob/ea6734fa342687deaf5616449cf5c074978d4205/src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.AvailableItems.targets#L28

This should still be in `@(AvailableItemName)` and show in Visual Studio, but I don't know what it would do in multi-targeted MAUI projects.

**Comment by LeoJHarris** [comment]
@jonathanpeppers we don't have any references or calls to `new ButtonHandler()` and neither do we even have any ButtonHandlers setup. 

You would like me to add `new ButtonHandler()` somewhere in the app and rerun the app with logcat? If so where should I put the line of code?

**Comment by LeoJHarris** [comment]
> `ProguardConfiguration` is the item group you use:
> 
> * https://github.com/dotnet/android/blob/ea6734fa342687deaf5616449cf5c074978d4205/src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.AvailableItems.targets#L28
> 
> This should still be in `@(AvailableItemName)` and show in Visual Studio, but I don't know what it would do in multi-targeted MAUI projects.

I have setup as follows in .csproj so don't think this is an issue with actually including the proguard:

```csproj
<ItemGroup Condition="'$(TargetFramework)' == 'net8.0-android34.0'">
	<ProguardConfiguration Include="Platforms\Android\proguard.cfg" />
</ItemGroup>
```

**Comment by jonathanpeppers** [comment]
> You would like me to add new ButtonHandler() somewhere in the app and rerun the app with logcat? If so where should I put the line of code?

My suggestion was to put it somewhere before the app crashes, to see if you get the inner exception message. Sometimes, if System.Reflection is the caller, and you get `TypeLoadException`, you lose the inner exception.

**Comment by LeoJHarris** [comment]
@jonathanpeppers correct me if wrong but I have tried in the `MainActivity` `OnCreated` method but the crash already seemed to be happening. I tried the `MAUIApplication` from the Android project

```csharp
protected override MauiApp CreateMauiApp()
{
    Log.Debug("ButtonHandler", "Before ButtonHandler called");
    new ButtonHandler();
    Log.Debug("ButtonHandler", "After ButtonHandler called");

    return MauiProgram.CreateMauiApp();
}
```

The logs seem to be the same:

```
10-31 10:26:21.390 16362 16362 D ButtonHandler: Before ButtonHandler called
10-31 10:26:21.391 16362 16413 E lservices.SampleApp: No package ID 77 found for resource ID 0x770b000f.
10-31 10:26:21.391 16362 16413 E lservices.SampleApp: No package ID 77 found for resource ID 0x770b000f.
10-31 10:26:21.393 16362 16413 I FA      : App measurement initialized, version: 108007
10-31 10:26:21.393 16362 16413 I FA      : To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
10-31 10:26:21.393 16362 16413 I FA      : To enable faster debug mode event logging run:
10-31 10:26:21.393 16362 16413 I FA      :   adb shell setprop debug.firebase.analytics.app ########
10-31 10:26:21.429  4679  4679 D BoundBrokerSvc: onBind: Intent { act=com.google.android.gms.measurement.START pkg=com.google.android.gms }
10-31 10:26:21.429  4679  4679 D BoundBrokerSvc: Loading bound service for intent: Intent { act=com.google.android.gms.measurement.START pkg=com.google.android.gms }
10-31 10:26:21.435 16362 16362 D AndroidRuntime: Shutting down VM
10-31 10:26:21.435 16362 16362 E AndroidRuntime: FATAL EXCEPTION: main
10-31 10:26:21.435 16362 16362 E AndroidRuntime: Process: ########, PID: 16362
10-31 10:26:21.435 16362 16362 E AndroidRuntime: android.runtime.JavaProxyThrowable: [System.TypeInitializationException]: The type initializer for 'Microsoft.Maui.Handlers.ButtonHandler' threw an exception.
10-31 10:26:21.435 16362 16362 E AndroidRuntime:        at SampleApp.MainApplication.CreateMauiApp(Unknown Source:0)
10-31 10:26:21.435 16362 16362 E AndroidRuntime:        at Microsoft.Maui.MauiApplication.OnCreate(Unknown Source:0)
10-31 10:26:21.435 16362 16362 E AndroidRuntime:        at Android.App.Application.n_OnCreate(Unknown Source:0)
10-31 10:26:21.435 16362 16362 E AndroidRuntime:        at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(Unknown Source:0)
10-31 10:26:21.435 16362 16362 E AndroidRuntime:        at crc6488302ad6e9e4df1a.MauiApplication.n_onCreate(Native Method)
10-31 10:26:21.435 16362 16362 E AndroidRuntime:        at crc6488302ad6e9e4df1a.MauiApplication.onCreate(MauiApplication.java:28)
10-31 10:26:21.435 16362 16362 E AndroidRuntime:        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1316)
10-31 10:26:21.435 16362 16362 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7711)
10-31 10:26:21.435 16362 16362 E AndroidRuntime:        at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
10-31 10:26:21.435 16362 16362 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2478)
10-31 10:26:21.435 16362 16362 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
10-31 10:26:21.435 16362 16362 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:230)
10-31 10:26:21.435 16362 16362 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:319)
10-31 10:26:21.435 16362 16362 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8919)
10-31 10:26:21.435 16362 16362 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
10-31 10:26:21.435 16362 16362 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
10-31 10:26:21.435 16362 16362 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
```

**Comment by jonathanpeppers** [comment]
With a `catch` block, is there an `InnerException`? I would log both `exc.ToString()` and `exc.InnerException` to see if there is any more information.

**Comment by LeoJHarris** [comment]
After adding the following proguard rule I got me past the above issue.

```
-keep class com.microsoft.maui.PlatformInterop { *; }
```

However it seems like I have a few missing proguard rules that have not been included but resolving these case by case now.

**Comment by LeoJHarris** [comment]
After adding the following proguard rule I got past the above issue.

```
-keep class com.microsoft.maui.PlatformInterop { *; }
```

Resolving the above then raised a few more missing rules though they appeared specific to my project such as the following:

```
-keep class com.microsoft.appcenter.AppCenter { *; }
-keep class com.microsoft.appcenter.analytics.Analytics { *; }
-keep class com.microsoft.appcenter.crashes.Crashes { *; }
```

As a side note from the build output, does the following have any cause for concern?

```
obj\Release\net8.0-android34.0\android-arm64\proguard\proguard_project_references.cfg : warning XA4304: ProGuard configuration file 'obj\Release\net8.0-android34.0\android-arm64\proguard\proguard_project_references.cfg' was not found.
```

**Comment by jonathanpeppers** [comment]
> -keep class com.microsoft.maui.PlatformInterop { *; }

For this rule, we should automatically add it to .NET MAUI. I can look into that.

> obj\Release\net8.0-android34.0\android-arm64\proguard\proguard_project_references.cfg : warning XA4304: ProGuard configuration file 'obj\Release\net8.0-android34.0\android-arm64\proguard\proguard_project_references.cfg' was not found.

This warning should be fixed in .NET 9:
* https://github.com/dotnet/android/pull/8641

**Comment by jonathanpeppers** [comment]
They don't have default wildcards for proguard files:

https://github.com/dotnet/maui/blob/f6424476e57c1c25cc587f164b90bceb1681cd37/src/Controls/src/Build.Tasks/nuget/buildTransitive/netstandard2.0/Microsoft.Maui.Controls.Globs.props#L43-L55

So, you probably need `<ItemGroup><ProguardConfiguration Include="...`.

The Android set is here, but MAUI overwrites them with `EnableDefaultAndroidItems=false`:

* https://github.com/dotnet/android/blob/6394773fad5108b0d7b4e6f087dc3e6ea997401a/src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/Sdk/AutoImport.props#L60-L62

**Comment by brunck** [comment]
Is there a way to do `-printusage usage.txt`? It doesn't seem to output anything when I try it.

**Comment by jonathanpeppers** [comment]
Generally r8 has no idea if C# calls a Java method, so it will remove them otherwise. It doesn't think anyone called it from Java.

**Comment by Jakar510** [comment]
I'm also getting this issue with `Java.Lang.ClassNotFoundException: Didn't find class "com.microsoft.maui.PlatformInterop" on path: DexPathList`

**Comment by LeoJHarris** [comment]
@jonathanpeppers @mattleibow I've looped back to this issue, was determined to get r8 & d8 enabled on our app which it is now after adding a few more rules but looks like another core MAUI component missing with the required proguard rule to fix it:

-keep class com.microsoft.maui.PlatformFontSpan { *; }

**Comment by LeoJHarris** [comment]
@jonathanpeppers @mattleibow 

Crash occurred as per below with missing proguard rules I added to resolve it.

```
Time	Device Name	Type	PID	Tag	Message
04-09 11:37:38.196	Device	Error	20629	AndroidRuntime	java.lang.AbstractMethodError: abstract method "void android.view.ViewGroup.onLayout(boolean, int, int, int, int)"
	at crc6452ffdc5b34af3a0f.WrapperView.n_onLayout(Native Method)
	at crc6452ffdc5b34af3a0f.WrapperView.onLayout(WrapperView.java:32)
	at android.view.View.layout(View.java:25771)
	at android.view.ViewGroup.layout(ViewGroup.java:6822)
	at crc6452ffdc5b34af3a0f.LayoutViewGroup.n_onLayout(Native Method)
....
```


```proguard
-keepclassmembers class crc6452ffdc5b34af3a0f.WrapperView {
    protected void onLayout(boolean, int, int, int, int);
}
-keepclassmembers class crc6452ffdc5b34af3a0f.LayoutViewGroup {
    protected void onLayout(boolean, int, int, int, int);
}
-keepclassmembers class crc6452ffdc5b34af3a0f.ContentViewGroup {
    protected void onLayout(boolean, int, int, int, int);
}
-keepclassmembers class crc6452ffdc5b34af3a0f.MauiScrollView {
    protected void onLayout(boolean, int, int, int, int);
}
```

**Comment by AlleSchonWeg** [comment]
HI @jonathanpeppers ,
i have the same error using r8. What is the recommendation for MAUI Android apps? Disable r8 or click everything in the app to find missing classes?

Thank you.

**Comment by jonathanpeppers** [comment]
Yes, R8 is optional and not the default, which is why the experience isn't great here. You could start with a very broad proguard file, that keeps public members, but would still be able to shrink some of the Java code size.

Ideally one day R8 would just be default, and some custom build steps would write _all_ the required proguard rules used by C# code. We've not had the time to implement this yet.

**Comment by SunnyWar** [comment]
This got me today also. It took quite a bit of work to discover r8 as the problem...huge time sink.
