### ISSUE TITLE
Unable to load library libSkiaSharp

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#25208]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Unable-to-load-library-libSkiaSharp/10761558)._

---
[severity:It's more difficult to complete my work]
I have installed MAUI in VS 2022 (.NET NAUI App) and when I run the build, I have this error 
Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	MAUI0000	System.DllNotFoundException: Unable to load library 'libSkiaSharp'.
   at SkiaSharp.LibraryLoader.LoadLocalLibrary[T](String libraryName) in /mnt/vss/_work/1/s/binding/Binding.Shared/LibraryLoader.cs:line 38
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at SkiaSharp.SkiaApi.sk_compatpaint_new() in /mnt/vss/_work/1/s/binding/Binding/SkiaApi.generated.cs:line 13110
   at SkiaSharp.SKPaint..ctor() in /mnt/vss/_work/1/s/binding/Binding/SKPaint.cs:line 25
   at Microsoft.Maui.Resizetizer.SkiaSharpTools..ctor(String filename, Nullable`1 baseSize, Nullable`1 backgroundColor, Nullable`1 tintColor, ILogger logger) in /_/src/SingleProject/Resizetizer/src/SkiaSharpTools.cs:line 39
   at Microsoft.Maui.Resizetizer.SkiaSharpSvgTools..ctor(String filename, Nullable`1 baseSize, Nullable`1 backgroundColor, Nullable`1 tintColor, ILogger logger) in /_/src/SingleProject/Resizetizer/src/SkiaSharpSvgTools.cs:line 20
   at Microsoft.Maui.Resizetizer.SkiaSharpTools.Create(Boolean isVector, String filename, Nullable`1 baseSize, Nullable`1 backgroundColor, Nullable`1 tintColor, ILogger logger) in /_/src/SingleProject/Resizetizer/src/SkiaSharpTools.cs:line 21
   at Microsoft.Maui.Resizetizer.Resizer.get_Tools() in /_/src/SingleProject/Resizetizer/src/Resizer.cs:line 28
   at Microsoft.Maui.Resizetizer.Resizer.Resize(DpiPath dpi, String inputsFile) in /_/src/SingleProject/Resizetizer/src/Resizer.cs:line 105
   at Microsoft.Maui.Resizetizer.GenerateSplashAndroidResources.WriteImages(Resizer resizer) in /_/src/SingleProject/Resizetizer/src/GenerateSplashAndroidResources.cs:line 72
   at Microsoft.Maui.Resizetizer.GenerateSplashAndroidResources.Execute() in /_/src/SingleProject/Resizetizer/src/GenerateSplashAndroidResources.cs:line 47	MyWorkHoursCSharpMAUI (net8.0-android)	C:\Users\MUHAMMED DÖNMEZ\.nuget\packages\microsoft.maui.resizetizer\8.0.91\buildTransitive\Microsoft.Maui.Resizetizer.After.targets	421	

I installed  SkiaSharp packages 

![pakage skia.png](https://aka.ms/dc/image?name=B0658a0ab384b4e28881db054a8dd8e2a638637583979485037_pakage_skia.png&tid=0658a0ab384b4e28881db054a8dd8e2a638637583979485037)

I can nor resolve this problem also after thet when buld a project the VS close immedietly and restart again (Only in MAUI project0
 I uninstalled MAUI anr reinstall it agian but I have the same problem 

Can I find the solution for this 
Thanks in advace 
Regards...

---
#### Feedback Bot on 10/7/2024, 08:28 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

**Comment by ninachen03** [comment]
This issue has been verified using Visual Studio 17.12.0 Preview 2.1(8.0.91). Whether SkiaSharp package is installed or not I cannot repro this issue.
![Image](https://github.com/user-attachments/assets/a18d7083-81ce-4de5-b00f-06ee629c6ecf)
