### ISSUE TITLE
Inconsistent Debugging with MultiValueConverterExtension crash

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#25212]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Inconsistent-Debugging-with-MultiValueCo/10730350)._

---
\[severity:It’s more difficult to complete my work\]  
The MultiValueConverterExtension from CommunityToolkit.Maui crashes on my iPad - you don’t even need to actually use it, just add a resource to a page. However I am reporting this as a problem with Visual Studio, because if I try to debug the project to see why it crashes, it won’t crash! Obviously I can’t give an end user software that only works when running the debugger, and I can’t troubleshoot issues if they behave differently between running the debugger and running normally.

This is very easily reproduced, at least on my machine.

---
#### Feedback Bot on 8/25/2024, 06:36 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Rolf Kvinge [MSFT] on 9/3/2024, 07:33 AM: 

<p>Could you please attach a complete test project we can use to reproduce the issue?</p>
<p><strong>Why do we ask for more info?</strong><br>
We try to reproduce all issues reported with the information provided in the description and comments. When we can’t reproduce the issue, we ask you for more information so we can resolve the issue as quickly and efficiently as possible.<br>
In our <a target='_blank' href="https://aka.ms/vsfeedbackguidelines/#writing-a-good-bug-report-or-feature-suggestion">guidelines</a>, you can get tips on how to provide clear and simple reproducible steps.</p>

#### Brad V. Bellomo on 9/3/2024, 08:53 AM: 

<p>A test project was included in my original post.  Did you not receive it?  Is it somehow incomplete?</p>

#### Brad V. Bellomo on 9/3/2024, 10:13 AM: 

<p><a target='_blank' href="https://aka.ms/dc/file?name=B44c91a241f4d4158af1674d7623f0889638609803843515245_MauiApp1.zip&amp;tid=44c91a241f4d4158af1674d7623f0889638609803843515245">MauiApp1.zip</a></p>

#### Rolf Kvinge [MSFT] on 9/3/2024, 09:05 AM: 

<blockquote>
<p>A test project was included in my original post. Did you not receive it? Is it somehow incomplete?</p>
</blockquote>
<p>It doesn’t look like it attached correctly, can you try again?</p>

#### Feedback Bot on 9/10/2024, 02:12 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

**Comment by samhouts** [comment]
From @rolfbjarne 

``` Specified cast is not valid. (System.InvalidCastException)
   at Microsoft.Maui.Controls.Xaml.ApplyPropertiesVisitor.ProvideValue(Object& value, ElementNode node, Object source, XmlName propertyName)
   at Microsoft.Maui.Controls.Xaml.ApplyPropertiesVisitor.Visit(ElementNode node, INode parentNode)
   at Microsoft.Maui.Controls.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
   at Microsoft.Maui.Controls.Xaml.FillResourceDictionariesVisitor.Visit(ElementNode node, INode parentNode)
   at Microsoft.Maui.Controls.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
   at Microsoft.Maui.Controls.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
   at Microsoft.Maui.Controls.Xaml.RootNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
   at Microsoft.Maui.Controls.Xaml.XamlLoader.Visit(RootNode rootnode, HydrationContext visitorContext, Boolean useDesignProperties)
   at Microsoft.Maui.Controls.Xaml.XamlLoader.Load(Object view, String xaml, Assembly rootAssembly, Boolean useDesignProperties)
   at Microsoft.Maui.Controls.Xaml.XamlLoader.Load(Object view, String xaml, Boolean useDesignProperties)
   at Microsoft.Maui.Controls.Xaml.XamlLoader.Load(Object view, Type callingType)
   at Microsoft.Maui.Controls.Xaml.Extensions.LoadFromXaml[MainPage](MainPage view, Type callingType)
   at MauiApp1.MainPage.InitializeComponent() in /Users/rolf/Downloads/B44c91a241f4d4158af1674d7623f0889638609803843515245_MauiApp1/MauiApp1/obj/Debug/net8.0-ios/ios-arm64/Microsoft.Maui.Controls.SourceGen/Microsoft.Maui.Controls.SourceGen.CodeBehindGenerator/MainPage.xaml.sg.cs:line 26
   at MauiApp1.MainPage..ctor() in /Users/rolf/Downloads/B44c91a241f4d4158af1674d7623f0889638609803843515245_MauiApp1/MauiApp1/MainPage.xaml.cs:line 9
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Constructor(Object obj, IntPtr* args)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object , BindingFlags )
```

paging @StephaneDelcroix

**Comment by ninachen03** [comment]
This issue has been verified using Visual Studio 17.12.0 Preview 2.1(8.0.91 & 8.0.82). Can repro this issue at iOS platform.
![Image](https://github.com/user-attachments/assets/6757e675-603e-4c8e-bd78-685ad7109e37)

**Comment by StephaneDelcroix** [comment]
> From [@rolfbjarne](https://github.com/rolfbjarne)
> 
> ```
>    at Microsoft.Maui.Controls.Xaml.ApplyPropertiesVisitor.ProvideValue(Object& value, ElementNode node, Object source, XmlName propertyName)
>    at Microsoft.Maui.Controls.Xaml.ApplyPropertiesVisitor.Visit(ElementNode node, INode parentNode)
>    at Microsoft.Maui.Controls.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
>    at Microsoft.Maui.Controls.Xaml.FillResourceDictionariesVisitor.Visit(ElementNode node, INode parentNode)
>    at Microsoft.Maui.Controls.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
>    at Microsoft.Maui.Controls.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
>    at Microsoft.Maui.Controls.Xaml.RootNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
>    at Microsoft.Maui.Controls.Xaml.XamlLoader.Visit(RootNode rootnode, HydrationContext visitorContext, Boolean useDesignProperties)
>    at Microsoft.Maui.Controls.Xaml.XamlLoader.Load(Object view, String xaml, Assembly rootAssembly, Boolean useDesignProperties)
>    at Microsoft.Maui.Controls.Xaml.XamlLoader.Load(Object view, String xaml, Boolean useDesignProperties)
>    at Microsoft.Maui.Controls.Xaml.XamlLoader.Load(Object view, Type callingType)
>    at Microsoft.Maui.Controls.Xaml.Extensions.LoadFromXaml[MainPage](MainPage view, Type callingType)
>    at MauiApp1.MainPage.InitializeComponent() in /Users/rolf/Downloads/B44c91a241f4d4158af1674d7623f0889638609803843515245_MauiApp1/MauiApp1/obj/Debug/net8.0-ios/ios-arm64/Microsoft.Maui.Controls.SourceGen/Microsoft.Maui.Controls.SourceGen.CodeBehindGenerator/MainPage.xaml.sg.cs:line 26
>    at MauiApp1.MainPage..ctor() in /Users/rolf/Downloads/B44c91a241f4d4158af1674d7623f0889638609803843515245_MauiApp1/MauiApp1/MainPage.xaml.cs:line 9
>    at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Constructor(Object obj, IntPtr* args)
>    at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object , BindingFlags )
> ```
> 
> paging [@StephaneDelcroix](https://github.com/StephaneDelcroix)

that's the trace, what's the exception ? will try to repro that

**Comment by jfversluis** [comment]
Might be worth trying to update to the latest version of the Toolkit which should be fully AOT compatible

**Comment by StephaneDelcroix** [comment]
unable to reproduce this on net 8.0.403
