### ISSUE TITLE
The specified child already has a parent. You must call removeView() on the child's parent first

### ISSUE THREAD

**Issue by Migoked** [dotnet/maui#25277]
### Description

I have an exception on android when I try to diplay a control inside a contentview. 

Works fine on iOS.
Works also fine if I display a Label instead of an Entry.

**My Page**

```
`<?xml version="1.0" encoding="utf-8" ?>
<ContentPage x:Class="Portwin.Accueil.Views.TestPage"
             xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:pagecontrols="clr-namespace:Portwin.StatiControls.StatiPage"
             Title="TestPage">

    <pagecontrols:TitleView>

        <Entry />

    </pagecontrols:TitleView>

</ContentPage>`
```

**My contentview "TitleView"** 

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentView x:Class="Portwin.StatiControls.StatiPage.TitleView" xmlns="http://schemas.microsoft.com/dotnet/2021/maui" xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" HeightRequest="45">

    <ContentView.ControlTemplate>
        <ControlTemplate>
            <Grid ColumnDefinitions="*" RowDefinitions="*">

                <ContentPresenter Grid.Row="0" Grid.Column="0" />
            </Grid>
        </ControlTemplate>
    </ContentView.ControlTemplate>
</ContentView>
```

**Exception**

```
**Java.Lang.IllegalStateException:** 'The specified child already has a parent. You must call removeView() on the child's parent first.'

[DOTNET] AppDomain
[mono-rt] [ERROR] FATAL UNHANDLED EXCEPTION: Java.Lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
[mono-rt]    at Java.Interop.JniEnvironment.InstanceMethods.CallNonvirtualVoidMethod(JniObjectReference instance, JniObjectReference type, JniMethodInfo method, JniArgumentValue* args) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/obj/Release/net7.0/JniEnvironment.g.cs:line 20830
[mono-rt]    at Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualVoidMethod(String encodedMember, IJavaPeerable self, JniArgumentValue* parameters) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:line 75
[mono-rt]    at Android.Views.ViewGroup.AddView(View child) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net8.0/android-34/mcw/Android.Views.ViewGroup.cs:line 2148
...
```

**Workload**

```
android                                   34.0.138/8.0.100          SDK 8.0.300, VS 17.10.34916.146
ios                                       17.5.8020/8.0.100         SDK 8.0.300, VS 17.10.34916.146
maccatalyst                               17.5.8020/8.0.100         SDK 8.0.300, VS 17.10.34916.146
maui                                      8.0.82/8.0.100            SDK 8.0.300
maui-windows                              8.0.82/8.0.100            SDK 8.0.300, VS 17.10.34916.146
```

### Version with bug

8.0.82 SR8.2

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Did you find any workaround?

No

### Relevant log output

**Java.Lang.IllegalStateException:** 'The specified child already has a parent. You must call removeView() on the child's parent first.'

[DOTNET] AppDomain
[mono-rt] [ERROR] FATAL UNHANDLED EXCEPTION: Java.Lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
[mono-rt]    at Java.Interop.JniEnvironment.InstanceMethods.CallNonvirtualVoidMethod(JniObjectReference instance, JniObjectReference type, JniMethodInfo method, JniArgumentValue* args) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/obj/Release/net7.0/JniEnvironment.g.cs:line 20830
[mono-rt]    at Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualVoidMethod(String encodedMember, IJavaPeerable self, JniArgumentValue* parameters) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:line 75
[mono-rt]    at Android.Views.ViewGroup.AddView(View child) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net8.0/android-34/mcw/Android.Views.ViewGroup.cs:line 2148
[mono-rt]    at Microsoft.Maui.Handlers.ContentViewHandler.UpdateContent(IContentViewHandler handler) in /_/src/Core/src/Handlers/ContentView/ContentViewHandler.Android.cs:line 42
[mono-rt]    at Microsoft.Maui.Handlers.ContentViewHandler.MapContent(IContentViewHandler handler, IContentView page) in /_/src/Core/src/Handlers/ContentView/ContentViewHandler.Android.cs:line 47
[mono-rt]    at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0[[Microsoft.Maui.IContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.IContentViewHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v) in /_/src/Core/src/PropertyMapper.cs:line 172
[mono-rt]    at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IElementHandler viewHandler, IElement virtualView) in /_/src/Core/src/PropertyMapper.cs:line 47
[mono-rt]    at Microsoft.Maui.PropertyMapper.UpdateProperties(IElementHandler viewHandler, IElement virtualView) in /_/src/Core/src/PropertyMapper.cs:line 82
[mono-rt]    at Microsoft.Maui.Handlers.ElementHandler.SetVirtualView(IElement view) in /_/src/Core/src/Handlers/Element/ElementHandler.cs:line 79
[mono-rt]    at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.ContentViewGroup, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IView view) in /_/src/Core/src/Handlers/View/ViewHandlerOfT.cs:line 53
[mono-rt]    at Microsoft.Maui.Handlers.ContentViewHandler.SetVirtualView(IView view) in /_/src/Core/src/Handlers/ContentView/ContentViewHandler.Android.cs:line 26
[mono-rt]    at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.ContentViewGroup, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IElement view) in /_/src/Core/src/Handlers/View/ViewHandlerOfT.cs:line 56
[mono-rt]    at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler) in /_/src/Controls/src/Core/Element/Element.cs:line 986
[mono-rt]    at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value) in /_/src/Controls/src/Core/Element/Element.cs:line 928
[mono-rt]    at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.set_Handler(IElementHandler value) in /_/src/Controls/src/Core/VisualElement/VisualElement.cs:line 2101
[mono-rt]    at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context) in /_/src/Core/src/Platform/ElementExtensions.cs:line 96
[mono-rt]    at Microsoft.Maui.Platform.ElementExtensions.ToPlatform(IElement view, IMauiContext context) in /_/src/Core/src/Platform/ElementExtensions.cs:line 127
[mono-rt]    at Microsoft.Maui.Handlers.LayoutHandler.SetVirtualView(IView view) in /_/src/Core/src/Handlers/Layout/LayoutHandler.Android.cs:line 41
[mono-rt]    at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.ILayout, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.LayoutViewGroup, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IElement view) in /_/src/Core/src/Handlers/View/ViewHandlerOfT.cs:line 56
[mono-rt]    at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler) in /_/src/Controls/src/Core/Element/Element.cs:line 986
[mono-rt]    at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value) in /_/src/Controls/src/Core/Element/Element.cs:line 928
[mono-rt]    at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.set_Handler(IElementHandler value) in /_/src/Controls/src/Core/VisualElement/VisualElement.cs:line 2101
[mono-rt]    at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context) in /_/src/Core/src/Platform/ElementExtensions.cs:line 96
[mono-rt]    at Microsoft.Maui.Platform.ElementExtensions.ToPlatform(IElement view, IMauiContext context) in /_/src/Core/src/Platform/ElementExtensions.cs:line 127
[mono-rt]    at Microsoft.Maui.Handlers.ContentViewHandler.UpdateContent(IContentViewHandler handler) in /_/src/Core/src/Handlers/ContentView/ContentViewHandler.Android.cs:line 42
[mono-rt]    at Microsoft.Maui.Handlers.ContentViewHandler.MapContent(IContentViewHandler handler, IContentView page) in /_/src/Core/src/Handlers/ContentView/ContentViewHandler.Android.cs:line 47
[mono-rt]    at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0[[Microsoft.Maui.IContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.IContentViewHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v) in /_/src/Core/src/PropertyMapper.cs:line 172
[mono-rt]    at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IElementHandler viewHandler, IElement virtualView) in /_/src/Core/src/PropertyMapper.cs:line 47
[mono-rt]    at Microsoft.Maui.PropertyMapper.UpdateProperties(IElementHandler viewHandler, IElement virtualView) in /_/src/Core/src/PropertyMapper.cs:line 82
[mono-rt]    at Microsoft.Maui.Handlers.ElementHandler.SetVirtualView(IElement view) in /_/src/Core/src/Handlers/Element/ElementHandler.cs:line 79
[mono-rt]    at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.ContentViewGroup, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IView view) in /_/src/Core/src/Handlers/View/ViewHandlerOfT.cs:line 53
[mono-rt]    at Microsoft.Maui.Handlers.ContentViewHandler.SetVirtualView(IView view) in /_/src/Core/src/Handlers/ContentView/ContentViewHandler.Android.cs:line 26
[mono-rt]    at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.ContentViewGroup, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IElement view) in /_/src/Core/src/Handlers/View/ViewHandlerOfT.cs:line 56
[mono-rt]    at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler) in /_/src/Controls/src/Core/Element/Element.cs:line 986
[mono-rt]    at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value) in /_/src/Controls/src/Core/Element/Element.cs:line 928
[mono-rt]    at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.set_Handler(IElementHandler value) in /_/src/Controls/src/Core/VisualElement/VisualElement.cs:line 2101
[mono-rt]    at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context) in /_/src/Core/src/Platform/ElementExtensions.cs:line 96
[mono-rt]    at Microsoft.Maui.Platform.ElementExtensions.ToPlatform(IElement view, IMauiContext context) in /_/src/Core/src/Platform/ElementExtensions.cs:line 127
[mono-rt]    at Microsoft.Maui.Handlers.ContentViewHandler.UpdateContent(IContentViewHandler handler) in /_/src/Core/src/Handlers/ContentView/ContentViewHandler.Android.cs:line 42
[mono-rt]    at Microsoft.Maui.Handlers.ContentViewHandler.MapContent(IContentViewHandler handler, IContentView page) in /_/src/Core/src/Handlers/ContentView/ContentViewHandler.Android.cs:line 47
[mono-rt]    at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0[[Microsoft.Maui.IContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.IContentViewHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v) in /_/src/Core/src/PropertyMapper.cs:line 172
[mono-rt]    at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IElementHandler viewHandler, IElement virtualView) in /_/src/Core/src/PropertyMapper.cs:line 47
[mono-rt]    at Microsoft.Maui.PropertyMapper.UpdateProperties(IElementHandler viewHandler, IElement virtualView) in /_/src/Core/src/PropertyMapper.cs:line 82
[mono-rt]    at Microsoft.Maui.Handlers.ElementHandler.SetVirtualView(IElement view) in /_/src/Core/src/Handlers/Element/ElementHandler.cs:line 79
[mono-rt]    at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.ContentViewGroup, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IView view) in /_/src/Core/src/Handlers/View/ViewHandlerOfT.cs:line 53
[mono-rt]    at Microsoft.Maui.Handlers.ContentViewHandler.SetVirtualView(IView view) in /_/src/Core/src/Handlers/ContentView/ContentViewHandler.Android.cs:line 26
[mono-rt]    at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.ContentViewGroup, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IElement view) in /_/src/Core/src/Handlers/View/ViewHandlerOfT.cs:line 56
[mono-rt]    at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler) in /_/src/Controls/src/Core/Element/Element.cs:line 986
[mono-rt]    at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value) in /_/src/Controls/src/Core/Element/Element.cs:line 928
[mono-rt]    at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.set_Handler(IElementHandler value) in /_/src/Controls/src/Core/VisualElement/VisualElement.cs:line 2101
[mono-rt]    at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context) in /_/src/Core/src/Platform/ElementExtensions.cs:line 96
[mono-rt]    at Microsoft.Maui.Platform.ElementExtensions.ToPlatform(IElement view, IMauiContext context) in /_/src/Core/src/Platform/ElementExtensions.cs:line 127
[mono-rt]    at Microsoft.Maui.Platform.MauiContextExtensions.ToPlatform(IView view, IMauiContext fragmentMauiContext, Context context, LayoutInflater layoutInflater, FragmentManager childFragmentManager) in /_/src/Core/src/Platform/Android/MauiContextExtensions.cs:line 96
[mono-rt]    at Microsoft.Maui.Platform.NavigationViewFragment.OnCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) in /_/src/Core/src/Platform/Android/Navigation/NavigationViewFragment.cs:line 56
[mono-rt]    at AndroidX.Fragment.App.Fragment.n_OnCreateView_Landroid_view_LayoutInflater_Landroid_view_ViewGroup_Landroid_os_Bundle_(IntPtr jnienv, IntPtr native__this, IntPtr native_inflater, IntPtr native_container, IntPtr native_savedInstanceState) in C:\a\_work\1\s\generated\androidx.fragment.fragment\obj\Release
et6.0-android\generated\src\AndroidX.Fragment.App.Fragment.cs:line 2031
[mono-rt]    at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPLLL_L(_JniMarshal_PPLLL_L callback, IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 363
[mono-rt]   --- End of managed Java.Lang.IllegalStateException stack trace ---
[mono-rt] java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
[mono-rt] 	at android.view.ViewGroup.addViewInner(ViewGroup.java:5275)
[mono-rt] 	at android.view.ViewGroup.addView(ViewGroup.java:5104)
[mono-rt] 	at android.view.ViewGroup.addView(ViewGroup.java:5044)
[mono-rt] 	at android.view.ViewGroup.addView(ViewGroup.java:5016)
[mono-rt] 	at crc6452ffdc5b34af3a0f.NavigationViewFragment.n_onCreateView(Native Method)
[mono-rt] 	at crc6452ffdc5b34af3a0f.NavigationViewFragment.onCreateView(NavigationViewFragment.java:42)
[mono-rt] 	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:3114)
[mono-rt] 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:557)
[mono-rt] 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:272)
[mono-rt] 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1943)
[mono-rt] 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1845)
[mono-rt] 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1782)
[mono-rt] 	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3042)
[mono-rt] 	at androidx.fragment.app.FragmentManager.dispatchViewCreated(FragmentManager.java:2945)
[mono-rt] 	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3148)
[mono-rt] 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:588)
[mono-rt] 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:272)
[mono-rt] 	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:114)
[mono-rt] 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1455)
[mono-rt] 	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3034)
[mono-rt] 	at androidx.fragment.app.FragmentManager.dispatchViewCreated(FragmentManager.java:2945)
[mono-rt] 	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3148)
[mono-rt] 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:588)
[mono-rt] 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:272)
[mono-rt] 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1943)
[mono-rt] 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1845)
[mono-rt] 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1782)
[mono-rt] 	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3042)
[mono-rt] 	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2952)
[mono-rt] 	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:263)
[mono-rt] 	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:350)
[mono-rt] 	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:251)
[mono-rt] 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1582)
[mono-rt] 	at android.app.Activity.performStart(Activity.java:8628)
[mono-rt] 	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3807)
[mono-rt] 	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:225)
[mono-rt] 	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:205)
[mono-rt] 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:177)
[mono-rt] 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:98)
[mono-rt] 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
[mono-rt] 	at android.os.Handler.dispatchMessage(Handler.java:106)
[mono-rt] 	at android.os.Looper.loopOnce(Looper.java:205)
[mono-rt] 	at android.os.Looper.loop(Looper.java:294)
[mono-rt] 	at android.app.ActivityThread.main(ActivityThread.java:8177)
[mono-rt] 	at java.lang.reflect.Method.invoke(Native Method)
[mono-rt] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
[mono-rt] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
[mono-rt] 
[mono-rt]   --- End of managed Java.Lang.IllegalStateException stack trace ---
[mono-rt] java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
[mono-rt] 	at android.view.ViewGroup.addViewInner(ViewGroup.java:5275)
[mono-rt] 	at android.view.ViewGroup.addView(ViewGroup.java:5104)
[mono-rt] 	at android.view.ViewGroup.addView(ViewGroup.java:5044)
[mono-rt] 	at android.view.ViewGroup.addView(ViewGroup.java:5016)
[mono-rt] 	at crc6452ffdc5b34af3a0f.NavigationViewFragment.n_onCreateView(Native Method)
[mono-rt] 	at crc6452ffdc5b34af3a0f.NavigationViewFragment.onCreateView(NavigationViewFragment.java:42)
[mono-rt] 	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:3114)
[mono-rt] 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:557)
[mono-rt] 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:272)
[mono-rt] 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1943)
[mono-rt] 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1845)
[mono-rt] 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1782)
[mono-rt] 	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3042)
[mono-rt] 	at androidx.fragment.app.FragmentManager.dispatchViewCreated(FragmentManager.java:2945)
[mono-rt] 	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3148)
[mono-rt] 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:588)
[mono-rt] 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:272)
[mono-rt] 	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:114)
[mono-rt] 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1455)
[mono-rt] 	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3034)
[mono-rt] 	at androidx.fragment.app.FragmentManager.dispatchViewCreated(FragmentManager.java:2945)
[mono-rt] 	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3148)
[mono-rt] 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:588)
[mono-rt] 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:272)
[mono-rt] 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1943)
[mono-rt] 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1845)
[mono-rt] 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1782)
[mono-rt] 	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3042)
[mono-rt] 	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2952)
[mono-rt] 	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:263)
[mono-rt] 	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:350)
[mono-rt] 	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:251)
[mono-rt] 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1582)
[mono-rt] 	at android.app.Activity.performStart(Activity.java:8628)
[mono-rt] 	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3807)
[mono-rt] 	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:225)
[mono-rt] 	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:205)
[mono-rt] 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:177)
[mono-rt] 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:98)
[mono-rt] 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
[mono-rt] 	at android.os.Handler.dispatchMessage(Handler.java:106)
[mono-rt] 	at android.os.Looper.loopOnce(Looper.java:205)
[mono-rt] 	at android.os.Looper.loop(Looper.java:294)
[mono-rt] 	at android.app.ActivityThread.main(ActivityThread.java:8177)
[mono-rt] 	at java.lang.reflect.Method.invoke(Native Method)
[mono-rt] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
[mono-rt] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
[mono-rt]

**Comment by Migoked** [comment]
Fake alert, i was using specific handlers for Entry.
