### ISSUE TITLE
Add check for `Shell` so if users try to push to it or not set it as the root we throw a more helpful exception

### ISSUE THREAD

**Issue by algjohnston** [dotnet/maui#25423]
### Description

Crashes on Android 14. I also tested on Windows, but that involved a bit more code than is in the example project, and there was no crash.

Here is the version info:
```
Installed Workload Id      Manifest Version       Installation Source
---------------------------------------------------------------------
maui-windows               8.0.72/8.0.100         VS 17.11.35303.130 
maccatalyst                17.5.8030/8.0.100      VS 17.11.35303.130 
ios                        17.5.8030/8.0.100      VS 17.11.35303.130 
android                    34.0.113/8.0.100       VS 17.11.35303.130 
```

### Steps to Reproduce

To create the bug:
1. Set the App's MainPage to a NavigationPage hosting a ContentPage. 
`        MainPage = new NavigationPage(new MainPage());
`
2. Navigate to a Shell
`
Navigation.PushAsync(new AppShell());
`

That's all. To trigger the bug, click the button to navigate to the AppShell and then click the back button in the NavigationBar to go back to the MainPage. The MainPage will briefly show and then the app will crash.

### Link to public reproduction project repository

https://github.com/algjohnston/NestedShellNavigationBug

### Version with bug

Unknown/Other

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 14

### Did you find any workaround?

No

### Relevant log output

android.runtime.JavaProxyThrowable: [System.NullReferenceException]: Object reference not set to an instance of an object.
at Microsoft.Maui.Controls.Platform.Compatibility.ShellToolbarTracker.Dispose(Unknown Source:0)
at Java.Lang.Object.Java.Interop.IJavaPeerable.Disposed(Unknown Source:0)
at Java.Interop.JniRuntime+JniValueManager.DisposePeer(Unknown Source:0)
at Java.Lang.Object.Dispose(Unknown Source:0)
at Microsoft.Maui.Controls.Platform.Compatibility.ShellSectionRenderer.Destroy(Unknown Source:0)
at Microsoft.Maui.Controls.Platform.Compatibility.ShellSectionRenderer.OnDestroy(Unknown Source:0)
at AndroidX.Fragment.App.Fragment.n_OnDestroy(Unknown Source:0)
at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(Unknown Source:0)
at crc640ec207abc449b2ca.ShellSectionRenderer.n_onDestroy(Native Method)
at crc640ec207abc449b2ca.ShellSectionRenderer.onDestroy(ShellSectionRenderer.java:52)
at androidx.fragment.app.Fragment.performDestroy(Fragment.java:3376)
at androidx.fragment.app.FragmentStateManager.destroy(FragmentStateManager.java:811)
at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:346)
at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:114)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1455)
at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3034)
at androidx.fragment.app.FragmentManager.dispatchDestroy(FragmentManager.java:2988)
at androidx.fragment.app.Fragment.performDestroy(Fragment.java:3371)
at androidx.fragment.app.FragmentStateManager.destroy(FragmentStateManager.java:811)
at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:346)
at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:114)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1455)
at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3034)
at androidx.fragment.app.FragmentManager.dispatchDestroy(FragmentManager.java:2988)
at androidx.fragment.app.Fragment.performDestroy(Fragment.java:3371)
at androidx.fragment.app.FragmentStateManager.destroy(FragmentStateManager.java:811)
at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:346)
at androidx.fragment.app.SpecialEffectsController$FragmentStateManagerOperation.complete(SpecialEffectsController.kt:664)
at androidx.fragment.app.SpecialEffectsController$Operation.completeSpecialEffect(SpecialEffectsController.kt:587)
at androidx.fragment.app.DefaultSpecialEffectsController$SpecialEffectsInfo.completeSpecialEffect(DefaultSpecialEffectsController.kt:774)
at androidx.fragment.app.DefaultSpecialEffectsController$startAnimations$3.onAnimationEnd$lambda$0(DefaultSpecialEffectsController.kt:273)
at androidx.fragment.app.DefaultSpecialEffectsController$startAnimations$3.$r8$lambda$e4JYQPCwrudQZpKmEdhGp1_4AOE(Unknown Source:0)
at androidx.fragment.app.DefaultSpecialEffectsController$startAnimations$3$$ExternalSyntheticLambda0.run(Unknown Source:6)
at android.os.Handler.handleCallback(Handler.java:959)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loopOnce(Looper.java:232)
at android.os.Looper.loop(Looper.java:317)
at android.app.ActivityThread.main(ActivityThread.java:8592)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)

**Comment by PureWeen** [comment]
`Shell` has to be the root of your app you can't push to it

I've modified the title of this issue to add a better experience
