### ISSUE TITLE
[Bug] Cannot run iOS simulator on MacBook Pro Big Sur

### ISSUE THREAD

**Issue by jpfcruz** [dotnet/maui#2554]
### Description
Cannot run iOS simulator on MacBook Pro Big Sur

![image](https://user-images.githubusercontent.com/86266622/133702545-ee0f226a-7514-4b01-9bfe-536f92991a5b.png)
 
### Steps to Reproduce

1. Install MAUI required software & verify using `maui-check`
```
🚑 .NET MAUI Check v0.8.6.0 💉
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
This tool will attempt to evaluate your .NET MAUI development environment.
If problems are detected, this tool may offer the option to try and fix them for you, or suggest a way to fix them yourself.

Thanks for choosing .NET MAUI!
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
⏳ Synchronizing configuration... ok
⏳ Scheduling appointments... ok

🔎 OpenJDK 11.0 Checkup...
  ✔ 11.0.10 (/Library/Java/JavaVirtualMachines/microsoft-11.jdk/Contents/Home/bin/..)
  – 1.8.0-25 (/Users/jfavrod/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25)

🔎 Visual Studio 8.10.0 Checkup...
  ✔ Visual Studio for Mac (8.10.9.3)

🔎 Android SDK Checkup...
  ✔ emulator (30.8.4)
  ✔ build-tools;31.0.0 (31.0.0)
  ✔ platforms;android-31 (1)
  ✔ system-images;android-31;google_apis;x86_64 (8)
  ✔ platform-tools (31.0.3)
  ✔ cmdline-tools;3.0 (3.0)

🔎 Android Emulator Checkup...
  ✔ Emulator: Pixel_2_API_29 found.

🔎 XCode 13 Beta 5 Checkup...
  ✔ Xcode.app (13 Beta 5)

🔎 .NET SDK Checkup...
  – 3.1.411 - /usr/local/share/dotnet/sdk/3.1.411
  – 3.1.412 - /usr/local/share/dotnet/sdk/3.1.412
  – 3.1.413 - /usr/local/share/dotnet/sdk/3.1.413
  – 5.0.301 - /usr/local/share/dotnet/sdk/5.0.301
  – 5.0.302 - /usr/local/share/dotnet/sdk/5.0.302
  – 5.0.400 - /usr/local/share/dotnet/sdk/5.0.400
  – 5.0.401 - /usr/local/share/dotnet/sdk/5.0.401
  – 6.0.100-preview.7.21379.14 - /usr/local/share/dotnet/sdk/6.0.100-preview.7.21379.14
  ✔ 6.0.100-rc.1.21458.32 - /usr/local/share/dotnet/sdk/6.0.100-rc.1.21458.32

🔎 .NET SDK - Workload Deduplication Checkup...

🔎 .NET SDK - EnableWorkloadResolver.sentinel Checkup...

🔎 .NET SDK - Workloads (6.0.100-rc.1.21458.32) Checkup...
  ✔ android-aot (Microsoft.NET.Sdk.Android.Manifest-6.0.100 : 31.0.100-rc.1.12) installed.
  ✔ ios (Microsoft.NET.Sdk.iOS.Manifest-6.0.100 : 15.0.100-rc.1.1534) installed.
  ✔ maccatalyst (Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.100 : 15.0.100-rc.1.1534) installed.
  ✔ tvos (Microsoft.NET.Sdk.tvOS.Manifest-6.0.100 : 15.0.100-rc.1.1534) installed.
  ✔ macos (Microsoft.NET.Sdk.macOS.Manifest-6.0.100 : 12.0.100-rc.1.1534) installed.
  ✔ maui (Microsoft.NET.Sdk.Maui.Manifest-6.0.100 : 6.0.100-rc.1.1608) installed.
  ✔ wasm-tools (microsoft.net.workload.mono.toolchain.manifest-6.0.100 : 6.0.0-rc.1.21451.13) installed.
  ✔ microsoft-net-sdk-emscripten (microsoft.net.workload.emscripten.manifest-6.0.100 : 6.0.0-rc.1.21430.3) installed.
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

✔ Congratulations, everything looks great!
```

2. Scaffold new app
```
dotnet new maui
```

3. Successfully start app using maccatalyst
```
dotnet build MauiPoc.csproj -t:Run -f net6.0-maccatalyst
```

4. Close maccatalyst and try to run with ios
```
dotnet build MauiPoc.csproj -t:Run -f net6.0-ios
```

### Expected Behavior
iOS simulator launches with app running.

### Actual Behavior
Error message:

```
Microsoft (R) Build Engine version 17.0.0-preview-21458-01+2c5510013 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  Detected signing identity:
          
    Bundle Id: com.companyname.MauiPoc
    App Id: com.companyname.MauiPoc
  Tool /usr/bin/xcrun execution finished (exit code = 255).
          
Exception: System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ThrowWithoutLineInfo(String res)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlReader.ReadToDescendant(String name)
   at Xamarin.MacDev.PropertyListFormat.XmlFormat.StartReading(Stream input) in /Users/builder/azdo/_work/1/s/xamarin-macios/external/Xamarin.MacDev/Xamarin.MacDev/PListObject.cs:line 1879
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/15.0.100-rc.1.1534/tools/msbuild/iOS/Xamarin.Shared.targets(396,3): error : /usr/bin/xcrun exited with code 255 [/Users/jfavrod/dev/learn/MauiPoc/MauiPoc.csproj]
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/15.0.100-rc.1.1534/tools/msbuild/iOS/Xamarin.Shared.targets(396,3): error :          [/Users/jfavrod/dev/learn/MauiPoc/MauiPoc.csproj]
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/15.0.100-rc.1.1534/tools/msbuild/iOS/Xamarin.Shared.targets(396,3): error : ibtool exited with code 255 [/Users/jfavrod/dev/learn/MauiPoc/MauiPoc.csproj]
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/15.0.100-rc.1.1534/tools/msbuild/iOS/Xamarin.Shared.targets(396,3): error :          [/Users/jfavrod/dev/learn/MauiPoc/MauiPoc.csproj]
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/15.0.100-rc.1.1534/tools/msbuild/iOS/Xamarin.Shared.targets(396,3): error : Failed to load ibtool log file `obj/Debug/net6.0-ios/iossimulator-x64/ibtool-manifests/LaunchScreen.nib`: Failed to parse PList data type:  [/Users/jfavrod/dev/learn/MauiPoc/MauiPoc.csproj]
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/15.0.100-rc.1.1534/tools/msbuild/iOS/Xamarin.Shared.targets(396,3): error :          [/Users/jfavrod/dev/learn/MauiPoc/MauiPoc.csproj]

Build FAILED.

/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/15.0.100-rc.1.1534/tools/msbuild/iOS/Xamarin.Shared.targets(396,3): error : /usr/bin/xcrun exited with code 255 [/Users/jfavrod/dev/learn/MauiPoc/MauiPoc.csproj]
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/15.0.100-rc.1.1534/tools/msbuild/iOS/Xamarin.Shared.targets(396,3): error :          [/Users/jfavrod/dev/learn/MauiPoc/MauiPoc.csproj]
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/15.0.100-rc.1.1534/tools/msbuild/iOS/Xamarin.Shared.targets(396,3): error : ibtool exited with code 255 [/Users/jfavrod/dev/learn/MauiPoc/MauiPoc.csproj]
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/15.0.100-rc.1.1534/tools/msbuild/iOS/Xamarin.Shared.targets(396,3): error :          [/Users/jfavrod/dev/learn/MauiPoc/MauiPoc.csproj]
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/15.0.100-rc.1.1534/tools/msbuild/iOS/Xamarin.Shared.targets(396,3): error : Failed to load ibtool log file `obj/Debug/net6.0-ios/iossimulator-x64/ibtool-manifests/LaunchScreen.nib`: Failed to parse PList data type:  [/Users/jfavrod/dev/learn/MauiPoc/MauiPoc.csproj]
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/15.0.100-rc.1.1534/tools/msbuild/iOS/Xamarin.Shared.targets(396,3): error :          [/Users/jfavrod/dev/learn/MauiPoc/MauiPoc.csproj]
    0 Warning(s)
    3 Error(s)

Time Elapsed 00:00:03.01
```

### Basic Information
.NET 6 & XCode 13-beta fresh installations
Visual Studio '22 fresh install (have not used)
Jvm 11 fresh install

**Comment by jfversluis** [comment]
New versions have come out since. I'm going assume (hope?) that this has been fixed with all the updates of both Xcode and the products on our side. If you're still experiencing this, feel free to ping us or open a new issue. Thank you!
