### ISSUE TITLE
ListView: table cells turn black randomly

### ISSUE THREAD

**Issue by markuspalme** [dotnet/maui#25656]
### Description

The table cells in a `ListView`which is bound to an `ObservableCollection` turn black randomly after a reload:

![Image](https://github.com/user-attachments/assets/1273cb73-0802-4a12-97b2-c534ad185887)

This is the full XAML for the `ListView`:

```
<ListView
                x:Name="expenseRegistrationsListView"
                Grid.Row="1"
                Grid.Column="0"
                IsRefreshing="{Binding Loading}"
                IsPullToRefreshEnabled="true"
                HasUnevenRows="True"
                ItemsSource="{Binding ExpenseRegistrations}"
                RefreshCommand="{Binding LoadCommand}"
            >
                <ListView.Behaviors>
                    <behaviors:ListViewSelectedItemBehavior
                        Command="{Binding ItemSelectedCommand}"
                        Converter="{StaticResource SelectedItemConverter}"
                     />
                </ListView.Behaviors>
                <ListView.ItemTemplate>
                    <DataTemplate x:DataType="viewmodel:ExpenseRegistrationCellViewModel">
                        <ViewCell x:Name="expenseRegistrationCell">
                            <Grid HorizontalOptions="Fill" Margin="25,5,10,0">
                                <Grid.RowDefinitions>
                                    <RowDefinition Height="*" />
                                    <RowDefinition Height="*" />
                                </Grid.RowDefinitions>

                                <Grid.ColumnDefinitions>
                                    <ColumnDefinition Width="*"/>
                                    <ColumnDefinition Width="60"/>
                                    <ColumnDefinition Width="60"/>
                                </Grid.ColumnDefinitions>

                                <Label Text="{Binding ProjectName}" FontSize="14" Grid.Row="0" Grid.Column="0" TextColor="{DynamicResource TextPrimaryColor}" />
                                <Label Text="{Binding Unit}" HorizontalTextAlignment="End" FontSize="14" Grid.Row="0" Grid.Column="1" TextColor="{DynamicResource TextPrimaryColor}" />
                                <Label Text="{Binding Quantity}" HorizontalTextAlignment="End" FontSize="14" Grid.Row="0" Grid.Column="2" TextColor="{DynamicResource TextPrimaryColor}" />
                                <Label Text="{Binding ArticleName}" FontSize="12" Grid.Row="1" Grid.Column="0" TextColor="{DynamicResource TextPrimaryColor}" />
                            </Grid>

                            <ViewCell.ContextActions>
                                <MenuItem
                                    BindingContext="{Binding Source={x:Reference expenseRegistrationsListView}, Path=BindingContext}"
                                    Command="{Binding Source={RelativeSource AncestorType={x:Type viewmodel:ExpenseRegistrationViewModel}}, Path= CopyExpenseRegistrationCommand}"
                                    CommandParameter="{Binding Source={x:Reference expenseRegistrationCell}, Path=BindingContext}"
                                    Text="Kopieren"
                                    IsDestructive="false"
                                />
                                <MenuItem
                                    BindingContext="{Binding Source={x:Reference expenseRegistrationsListView}, Path=BindingContext}"
                                    Command="{Binding Source={RelativeSource AncestorType={x:Type viewmodel:ExpenseRegistrationViewModel}}, Path= DeleteExpenseRegistrationCommand}"
                                    CommandParameter="{Binding Source={x:Reference expenseRegistrationCell}, Path=BindingContext}"
                                    Text="Löschen"
                                    IsDestructive="true"
                                />
                            </ViewCell.ContextActions>
                        </ViewCell>
                    </DataTemplate>
                </ListView.ItemTemplate>
            </ListView>
```

There are no warning about failed bindings in the debug output.

Any ideas what could cause this?

### Version with bug

8.0.40 SR5

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 18

**Comment by markuspalme** [comment]
The issue also reproduces with the data template being simplified to

```
<Label Text="{Binding ProjectName}" FontSize="14" Grid.Row="0" Grid.Column="0" TextColor="{DynamicResource TextPrimaryColor}" />
```

**Comment by jaosnz-rep** [comment]
@markuspalme Could you provide us with a sample project so we can investigate it further? Looking forward to your reply!

**Comment by mattleibow** [comment]
Do you still have this issue if you try a CollectionView? What happens in a BindableLayout?

**Comment by markuspalme** [comment]
Here is an isolated reproduction project:

https://github.com/markuspalme/maui25656

To reproduce the issue, add some rows using the "New" button and then delete a row using the context actions:

![Image](https://github.com/user-attachments/assets/1d833338-5439-4801-98ad-0b28382e8892)

**Comment by markuspalme** [comment]
> Do you still have this issue if you try a CollectionView? What happens in a BindableLayout?

When I use a `CollectionView` like this:

```
<CollectionView
    x:Name="timeRegistrationsListView"
    ItemsSource="{Binding Rows}"
>
    <CollectionView.ItemTemplate>
        <DataTemplate x:DataType="viewmodel:RowModel">
            <TextCell x:Name="timeRegistrationCell" Text="{Binding Text}">
                <TextCell.ContextActions>
                    <MenuItem
                        BindingContext="{Binding Source={x:Reference timeRegistrationsListView}, Path=BindingContext}"
                        Command="{Binding Source={RelativeSource AncestorType={x:Type viewmodel:TimeRegistrationViewModel}}, Path= DeleteCommand}"
                        CommandParameter="{Binding Source={x:Reference timeRegistrationCell}, Path=BindingContext}"
                        Text="Delete"
                        IsDestructive="true"
                    />
                </TextCell.ContextActions>
            </TextCell>
        </DataTemplate>
    </CollectionView.ItemTemplate>
</CollectionView>
```

I get this exception:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Maui.Controls.Handlers.Items.TemplatedCell.Bind(DataTemplate template, Object bindingContext, ItemsView itemsView)
   at Microsoft.Maui.Controls.Handlers.Items.ItemsViewController`1[[Microsoft.Maui.Controls.ReorderableItemsView, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].UpdateTemplatedCell(TemplatedCell cell, NSIndexPath indexPath)
   at Microsoft.Maui.Controls.Handlers.Items.ItemsViewController`1[[Microsoft.Maui.Controls.ReorderableItemsView, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].CreateMeasurementCell(NSIndexPath indexPath)
   at Microsoft.Maui.Controls.Handlers.Items.ItemsViewController`1[[Microsoft.Maui.Controls.ReorderableItemsView, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].GetPrototypeForIndexPath(NSIndexPath indexPath)
   at Microsoft.Maui.Controls.Handlers.Items.ItemsViewController`1[[Microsoft.Maui.Controls.ReorderableItemsView, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].GetPrototype()
   at Microsoft.Maui.Controls.Handlers.Items.ItemsViewLayout.DetermineCellSize()
   at Microsoft.Maui.Controls.Handlers.Items.ListViewLayout.ConstrainTo(CGSize size)
   at Microsoft.Maui.Controls.Handlers.Items.ItemsViewController`1[[Microsoft.Maui.Controls.ReorderableItemsView, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].CheckForEmptySource()
   at Microsoft.Maui.Controls.Handlers.Items.ItemsViewController`1[[Microsoft.Maui.Controls.ReorderableItemsView, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].NumberOfSections(UICollectionView collectionView)
```

When Is use a `BindableLayout` like this...

```
 <StackLayout BindableLayout.ItemsSource="{Binding Rows}"
             Orientation="Horizontal"
             x:Name="timeRegistrationsListView"
>
    <BindableLayout.ItemTemplate>
        <DataTemplate x:DataType="viewmodel:RowModel">
            <TextCell x:Name="timeRegistrationCell" Text="{Binding Text}">
                <TextCell.ContextActions>
                    <MenuItem
                        BindingContext="{Binding Source={x:Reference timeRegistrationsListView}, Path=BindingContext}"
                        Command="{Binding Source={RelativeSource AncestorType={x:Type viewmodel:TimeRegistrationViewModel}}, Path= DeleteCommand}"
                        CommandParameter="{Binding Source={x:Reference timeRegistrationCell}, Path=BindingContext}"
                        Text="Delete"
                        IsDestructive="true"
                    />
                </TextCell.ContextActions>
            </TextCell>
        </DataTemplate>
    </BindableLayout.ItemTemplate>
</StackLayout>
```

I get this exception:

```
System.InvalidCastException: Specified cast is not valid.
   at Microsoft.Maui.Controls.BindableLayoutController.CreateItemView(Object item, DataTemplate dataTemplate)
   at Microsoft.Maui.Controls.BindableLayoutController.CreateItemView(Object item, IBindableLayout layout)
   at Microsoft.Maui.Controls.BindableLayoutController.<>c__DisplayClass40_0.<ItemsSourceCollectionChanged>b__0(Object item, Int32 index, Boolean _)
   at Microsoft.Maui.Controls.Internals.NotifyCollectionChangedEventArgsExtensions.Apply(NotifyCollectionChangedEventArgs self, Action`3 insert, Action`2 removeAt, Action reset)
   at Microsoft.Maui.Controls.BindableLayoutController.ItemsSourceCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at Microsoft.Maui.Controls.WeakNotifyCollectionChangedProxy.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1[[TestApp.Maui.ViewModels.RowModel, TestApp.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1[[TestApp.Maui.ViewModels.RowModel, TestApp.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnCollectionChanged(NotifyCollectionChangedAction action, Object item, Int32 index)
   at System.Collections.ObjectModel.ObservableCollection`1[[TestApp.Maui.ViewModels.RowModel, TestApp.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].InsertItem(Int32 index, RowModel item)
   at System.Collections.ObjectModel.Collection`1[[TestApp.Maui.ViewModels.RowModel, TestApp.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].Add(RowModel item)
   at TestApp.Maui.ViewModels.TimeRegistrationViewModel.Load() in /Users/markus/Source/Maui25656/TestApp/ViewModels/TimeRegistrationViewModel.cs:line 48
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Foundation.NSAsyncSynchronizationContextDispatcher.Apply() in /Users/builder/azdo/_work/1/s/xamarin-macios/src/Foundation/NSAction.cs:line 179

```

**Comment by jaosnz-rep** [comment]
I can repro this issue at iOS platform on the latest 17.13.0 Preview 1.0(8.0.93 & 8.0.92 & 8.0.40).

**Comment by mattleibow** [comment]
Ah, yeah. You can't use the cells in anything other than ListView.

Can you try using just a label in CollectionView and BindableLayout?

**Comment by markuspalme** [comment]
@mattleibow I can't reproduce it with a `CollectionView`, see branch `collectionview` in my test repo.

https://github.com/markuspalme/maui25656/tree/collectionview

**Comment by markuspalme** [comment]
Still a major blocker.

Is this a duplicate of https://github.com/dotnet/maui/issues/11598?

**Comment by markuspalme** [comment]
Is there anything I can do to help resolve this issue?

**Comment by keegan-gehrig** [comment]
Is this issue being looked at or prioritized within the MAUI framework at all? I'm experiencing the same issues described on this ticket and I'm using the latest .NET 9 SR for MAUI that was just released a couple of days ago. It seems like it happens specifically to ViewCells that have Context Actions defined on them. If I remove the context action, then I don't see the cells disappear randomly after a reload. So, there must be an issue with how context actions are defined and used within the framework, which is frustrating, because I need to use them in my app. I have not yet found any workarounds to this either.

**Comment by markuspalme** [comment]
@keegan-gehrig My guess is that this issue is not prioritized because the `ListView` is deprecatd: https://github.com/dotnet/maui/issues/28699

**Comment by jfversluis** [comment]
ListView is deprecated for .NET 10, so we probably won't be working on this anymore. Please migrate to CollectionView and help us make that the solid approach for this. Thanks!

**Comment by jfversluis** [comment]
> Is there anything I can do to help resolve this issue?

If you are still experiencing this and can figure out a fix I will be happy to look at a PR if you provide one still :)

**Comment by markuspalme** [comment]
@jfversluis thanks but no thanks. Issues like this drove me away from maui.

**Comment by jfversluis** [comment]
@markuspalme sorry to hear that! I hope you found something that suits your needs!
