### ISSUE TITLE
SSlStream Authentication failing in .NET MAUI Android app whereas same is working in Xamarin.forms

### ISSUE THREAD

**Issue by VenkataReddyDesiReddy** [dotnet/maui#25687]
### Description

I have connected to Controller via WiFi from .NET MAUI Android app and TLS is enabled in connected Controller.

From .NET MAUI Android project, I am trying to authenticate SSLStream with below code
SslStream _secureStream = new SslStream( new TcpClient().GetStream(), false, new RemoteCertificateValidationCallback(ValidateServerCertificate), null);
_secureStream.AuthenticateAsClient(serverName); //serverName is certificate name here

While authenticating it is throwing exception as below
{System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> Interop+AndroidCrypto+SslException: Exception of type 'Interop+AndroidCrypto+SslException' was thrown.
   at Interop.AndroidCrypto.SSLStreamSetTargetHost(SafeSslHandle sslHandle, String targetHost)
   at System.Net.SafeDeleteSslContext.InitializeSslContext(SafeSslHandle handle, SslAuthenticationOptions authOptions)
   at System.Net.SafeDeleteSslContext..ctor(SslAuthenticationOptions authOptions)
   at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteSslContext& context, ReadOnlySpan`1 inputBuffer, Byte[]& outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.<ForceAuthenticationAsync>d__150`1[[System.Net.Security.SyncReadWriteAdapter, System.Net.Security, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext()
   at System.Net.Security.SslStream.AuthenticateAsClient(SslClientAuthenticationOptions sslClientAuthenticationOptions)
   at System.Net.Security.SslStream.AuthenticateAsClient(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation)
   at System.Net.Security.SslStream.AuthenticateAsClient(String targetHost)
   at ContainerLINKPro.Platforms.Android.DependencyServices.TcpSocketConnection.ConnectAsync(String address, Int32 port, Boolean secure) in C:\Projects\AWS Projects\ContainerLINKPro\Platforms\Android\DependencyServices\TcpSocketConnection.cs:line 82}
   

### Version with bug

9.0.0-rc.2.24503.2

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android all versions

**Comment by Zhanglirong-Winnie** [comment]
Can you provide us with a sample project and detailed reproduction steps so we can investigate it further? Looking forward to your reply!

**Comment by VenkataReddyDesiReddy** [comment]
@Zhanglirong-Winnie I can't provide exact reproduction steps because I am connecting to company specific hardware device(controller) which you can't find. But I will explain issue briefly below.

1. From .NET MAUI app, I have connected to Hardware device through Wi-Fi.
2. After WI-Fi connection established authenticating certificate in Hardware device as below

TcpClient _backingTcpClient = new TcpClient();

await _backingTcpClient.ConnectAsync(ipaddress, port);

Once TLSEnabled in Hardware device(controller)

SslStream _secureStream = new SslStream(_backingTcpClient.GetStream(), false, new RemoteCertificateValidationCallback(ValidateServerCertificate), null);

**_secureStream.AuthenticateAsClient("certificate name in hardware device(controller)");**

The line _secureStream.AuthenticateAsClient throwing exception as below which is working in Xamarin.forms

{System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
---> Interop+AndroidCrypto+SslException: Exception of type 'Interop+AndroidCrypto+SslException' was thrown.
at Interop.AndroidCrypto.SSLStreamSetTargetHost(SafeSslHandle sslHandle, String targetHost)
at System.Net.SafeDeleteSslContext.InitializeSslContext(SafeSslHandle handle, SslAuthenticationOptions authOptions)
at System.Net.SafeDeleteSslContext..ctor(SslAuthenticationOptions authOptions)
at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteSslContext& context, ReadOnlySpan1 inputBuffer, Byte[]& outputBuffer, SslAuthenticationOptions sslAuthenticationOptions) --- End of inner exception stack trace --- at System.Net.Security.SslStream.<ForceAuthenticationAsync>d__1501[[System.Net.Security.SyncReadWriteAdapter, System.Net.Security, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext()
at System.Net.Security.SslStream.AuthenticateAsClient(SslClientAuthenticationOptions sslClientAuthenticationOptions)
at System.Net.Security.SslStream.AuthenticateAsClient(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation)
at System.Net.Security.SslStream.AuthenticateAsClient(String targetHost)

**Comment by drasticactions** [comment]
@VenkataReddyDesiReddy Your issue is unrelated to the MAUI UI framework; it's a [runtime](https://github.com/dotnet/runtime) issue, and no one on this team can fix it.

@simonrozsival would you know more about this?
