### ISSUE TITLE
CollectionVew on Android Consumes Gestures

### ISSUE THREAD

**Issue by david-maw** [dotnet/maui#25758]
### Description

The setup is a CollectionView inside a grid. The grid has gesture recognizers defined, the CollectionView does not.

Tapping on the page triggers the tap gesture recognizer unless you tap within the CollectionView in which case the tap is ignored on Android and Windows. 

### Steps to Reproduce

Clone the repository, build and run the app. You should see:

![Image](https://github.com/user-attachments/assets/cce6e01e-ecfa-4e00-8701-5aea2f8f14b7)

Tap on the page and the tap will be reported unless you tap within the CollectionView.   

### Link to public reproduction project repository

https://github.com/david-maw/SimpleCollectionView-missing-gestures.git

### Version with bug

9.0.0-rc.2.24503.2

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, Android, I was *not* able test on other platforms

### Affected platform versions

Windows 11, Android 14

### Did you find any workaround?

Sort of....

You can attach a GestureRecognizer to the CollectionView but doing so will inhibit native CollectionView scrolling on Android so you then must implement your own scrolling logic (there is an example in the test case, just commented out). If it were not for the fact that the GestureRecognizer inhibits scrolling on Android, I'd have just assumed this was a feature.

### Relevant log output

```shell

```

**Comment by ninachen03** [comment]
This issue has been verified using Visual Studio 17.12.0 Preview 5(9.0.0-rc.2.24503.2 & 8.0.92). Can repro this issue at android platform

**Comment by mattleibow** [comment]
I think this is correct behaviour. If you have a collection view and tap it, I would assume you want the taps to be handled by the collection view. Passing the tap through would break the collection view as you would no longer be able to select or scroll.

I am thinking this may also happen with a list of labels in a scroll view. The scrolling controls have to handle the touches in order to be able to detect if you want to scroll or not.

**Comment by david-maw** [comment]
I did test Windows, but the results were strangely inconsistent, sometimes taps were passed through, sometimes not and because I have not figured out why and when I focused on Android (which is what I really cared about anyway). The windows UI is different in that scrolling is initiated by a scroll wheel on a mouse rather than a gesture on the control itself (though I don't know how it behaves on a touch screen).

I could more easily live with an "as designed" answer if it were not for #10213 which in the more general case means putting any gesture recognizer on the CollectionView disables gesture-based scrolling. This is about handling gestures the CollectionView does not use. In practice it is mostly gestures in the open space after a partially filled CollectionView, gestures on the items might well be intercepted by the items themselves.

Passing through a Tap might inhibit selection, but if the tapped item intercepts the tap anyway it'll never reach the CollectionView and might well be coded to select (and, in my case, deselect) that item when tapped. Still, I agree that "should we pass through the tap" is tricky, maybe the answer is the moral equivalent of `InputTransparent `but only for the tap gesture.

All that said, you can. for example, have a tap gesture recognizer on an item in a CollectionView without disabling the native scrolling on the CollectionView. You can even have a SwipeGetureRecognizer but swipe Up and Down will be passed to the CollectionView and used for scrolling, only left and right do anything.

**Comment by david-maw** [comment]
It still happens on .NET 10.

On Android, taps on the CollectionView are ignored (though they can be used to select an item).

On Windows, Taps on the CollectionView are passed through to the underlying Grid (although they may select an item in addition to being passed through).

NET 11 Preview 7 threw an exception when I tapped an item in the CollectionView. The exception message was: "Unexpected type for enumerator" with this call stack:

```
   at ABI.System.Collections.Generic.IEnumerableMethods`1.GetEnumerator(IObjectReference obj)
   at ABI.Microsoft.UI.Xaml.Data.ICollectionViewImpl.GetEnumerator()
   at Microsoft.Maui.Controls.Handlers.Items2.CollectionViewHandler2.FindItemIndexInSource(ICollectionView itemList, Object targetItem)
   at Microsoft.Maui.Controls.Handlers.Items2.CollectionViewHandler2.UpdatePlatformSelection()
   at Microsoft.Maui.Controls.Handlers.Items2.CollectionViewHandler2.MapSelectedItem(CollectionViewHandler2 handler, SelectableItemsView itemsView)
   at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0.<Add>b__0(IElementHandler h, IElement v)
   at Microsoft.Maui.PropertyMapper.TryUpdatePropertyCore(String key, IElementHandler viewHandler, IElement virtualView)
   at Microsoft.Maui.PropertyMapper.UpdateProperty(IElementHandler viewHandler, IElement virtualView, String property)
   at Microsoft.Maui.Handlers.ElementHandler.UpdateValue(String property)
   at Microsoft.Maui.Controls.Element.UpdateHandlerValue(String property, Boolean valueChanged)
   at Microsoft.Maui.Controls.VisualElement.UpdateHandlerValue(String property, Boolean valueChanged)
   at Microsoft.Maui.Controls.Element.OnBindablePropertySet(BindableProperty property, Object original, Object value, Boolean changed, Boolean willFirePropertyChanged)
   at Microsoft.Maui.Controls.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, SetterSpecificity specificity, Boolean silent)
   at Microsoft.Maui.Controls.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes, SetterSpecificity specificity)
   at Microsoft.Maui.Controls.BindableObject.SetValue(BindableProperty property, Object value)
   at Microsoft.Maui.Controls.SelectableItemsView.set_SelectedItem(Object value)
   at Microsoft.Maui.Controls.Handlers.Items2.CollectionViewHandler2.UpdateVirtualSingleSelection()
   at Microsoft.Maui.Controls.Handlers.Items2.CollectionViewHandler2.UpdateVirtualSelection()
   at Microsoft.Maui.Controls.Handlers.Items2.CollectionViewHandler2.PlatformSelectionChanged(ItemsView sender, ItemsViewSelectionChangedEventArgs args)
   at WinRT._EventSource_global__Windows_Foundation_TypedEventHandler_global__Microsoft_UI_Xaml_Controls_ItemsView__global__Microsoft_UI_Xaml_Controls_ItemsViewSelectionChangedEventArgs_.EventState.<GetEventInvoke>b__1_0(ItemsView sender, ItemsViewSelectionChangedEventArgs args)
   at WinRT.GenericTypeInstantiations.Windows_Foundation_TypedEventHandler_2_Microsoft_UI_Xaml_Controls_ItemsView__Microsoft_UI_Xaml_Controls_ItemsViewSelectionChangedEventArgs.Do_Abi_Invoke(IntPtr thisPtr, IntPtr sender, IntPtr args)```

**Comment by kubaflo** [comment]
Thanks @david-maw — recorded, and this stays open.

Current state from your retest:

- **.NET 10** — Android: taps on the `CollectionView` are ignored (selection still works). Windows: taps pass through to the underlying `Grid`, sometimes *in addition to* selecting an item.
- **.NET 11 Preview 7 (Windows)** — tapping an item now throws `Unexpected type for enumerator` out of `CollectionViewHandler2.FindItemIndexInSource` via `UpdatePlatformSelection`.

That last one looks like a distinct regression in the `Items2` handler rather than the original gesture-consumption bug, so it may deserve its own issue to stop the two being closed as one. I'll leave that call to you — either way the stack trace is captured here now.

> Disclosure: this comment was generated by AI.

**Comment by david-maw** [comment]
The .NET 11 problem was caused by using an older pinned Windows SDK projection version (10.0.19041.41), the project has been updated to remove the WindowsSdkPackageVersion pin and allow the SDK to select a newer version automatically. Thanks @SuthiYuvaraj.

No idea why the pin was in there in the first place but taking it out corrected the problem with .NET 11. I've merged in the change to the sample repository so now the main branch uses .NET11 preview 7. The original problem where Windows passes through taps, but Android does not is still there in .NET 11.
