### ISSUE TITLE
Microsoft.Maui.Controls.Maps crash when IsShowingUser = true in Release mode (iOS, NET 9 rc2)

### ISSUE THREAD

**Issue by MichelePannacciTerex** [dotnet/maui#25762]
### Description

I'm expercienced a crash in the map control in Release mode on real device only if IsShowingUser = true while zooming/pinching on the map.

`Unhandled managed exception: Arg_InvalidCastException (System.InvalidCastException)`

Tried both Microsoft.Maui.Controls.Maps version 9.0.0-rc.2.24503.2 and the latest ones 8.0.92 and  8.0.93 but all of them has the same problem. This used to work using .NET 8, at least on iOS 17.x.

### Steps to Reproduce

Attached a simple project, apparently no special things to do other than set IsShowingUser = true to reproduce the error.
This on real device.

P.S. in the .csproj you have to adjust the CodesignKey.

[TestMap.zip](https://github.com/user-attachments/files/17692368/TestMap.zip)

### Version with bug

9.0.0-rc.2.24503.2

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 18, iOS 18.1 NET 9 rc2

### Did you find any workaround?

Not really a workaround but just adding a Circle to the map and polling the position my self.

### Relevant log output

```shell
------------------------------------------------------------------------------
You may only use the Microsoft Visual Studio .NET/C/C++ Debugger (vsdbg) with
Visual Studio Code, Visual Studio or Visual Studio for Mac software to help you
develop and test your applications.
------------------------------------------------------------------------------
2024-11-10 17:59:57.531 mlaunch[63638:5188301] Requested but did not find extension point with identifier Xcode.IDEDebugger.VariablesViewQuickLookProvider for extension Xcode.IDEDebugger.SpriteKitQuickLookProvider of plug-in com.apple.IDESpriteKitParticleEditor
2024-11-10 17:59:57.532 mlaunch[63638:5188301] Requested but did not find extension point with identifier Xcode.IDEDebugger.VariablesViewQuickLookProvider for extension Xcode.SpriteKit.GKStateMachineQuickLookProvider of plug-in com.apple.IDESpriteKitParticleEditor
2024-11-10 17:59:57.541 mlaunch[63638:5188301] Requested but did not find extension point with identifier Xcode.IDEPlaygroundsKit.PlaygroundBottomBarExecutionAdaptor for extension Xcode.IDEPlaygroundEditor.IDEPlaygroundBottomBarExecutionAdaptor of plug-in com.apple.dt.IDEPlaygroundEditorPlugin
2024-11-10 17:59:57.542 mlaunch[63638:5188301] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.ViewDescriber for extension Xcode.DebuggerFoundation.watchOSSimulator.ViewDescriber of plug-in com.apple.dt.IDEWatchSupportUI
2024-11-10 17:59:57.542 mlaunch[63638:5188301] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.DataSourceConnection for extension Xcode.DebuggerFoundation.watchOSSimulator.DataSourceConnectionTargetHub of plug-in com.apple.dt.IDEWatchSupportUI
2024-11-10 17:59:57.542 mlaunch[63638:5188301] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.ViewDescriber for extension Xcode.DebuggerFoundation.watchOS.ViewDescriber of plug-in com.apple.dt.IDEWatchSupportUI
2024-11-10 17:59:57.542 mlaunch[63638:5188301] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.InfoEditorType for extension Xcode.Xcode3ProjectSupport.InfoEditorType.WatchOS.Bundle of plug-in com.apple.dt.IDEWatchSupportUI
2024-11-10 17:59:57.542 mlaunch[63638:5188301] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.InfoEditorSlice for extension Xcode.Xcode3ProjectSupport.InfoEditorSlice.WatchOS.BundleInfo of plug-in com.apple.dt.IDEWatchSupportUI
2024-11-10 17:59:57.542 mlaunch[63638:5188301] Requested but did not find extension point with identifier Xcode.Xcode3UI.Xcode3SupportedDestinations for extension IDEWatchSupportUI:IDEWatchSupportUI.plugindata/plug-in[1]/extension[11] of plug-in com.apple.dt.IDEWatchSupportUI
2024-11-10 17:59:57.542 mlaunch[63638:5188301] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.DataSourceConnection for extension Xcode.DebuggerFoundation.watchOS.DataSourceConnectionTargetHub of plug-in com.apple.dt.IDEWatchSupportUI
2024-11-10 17:59:57.542 mlaunch[63638:5188301] Requested but did not find extension point with identifier Xcode.IDEiOSSupportCore.iOSDeviceLocatorMapping for extension Xcode.IDEiOSSupportCore.iOSDeviceLocatorMapping.driverkit of plug-in com.apple.dt.IDEDriverKitSupportCore
2024-11-10 17:59:57.542 mlaunch[63638:5188301] Requested but did not find extension point with identifier Xcode.Xcode3UI.Xcode3SupportedDestinations for extension IDEDriverKitSupportUI:IDEDriverKitSupportUI.plugindata/plug-in[1]/extension[2] of plug-in com.apple.dt.IDEDriverKitSupportUI
2024-11-10 17:59:57.542 mlaunch[63638:5188301] Requested but did not find extension point with identifier Xcode.Xcode3UI.Xcode3SupportedDestinations for extension IDEOSXSupportUI:IDEOSXSupportUI.plugindata/plug-in[1]/extension[5] of plug-in com.apple.dt.IDEOSXSupportUI
2024-11-10 17:59:57.543 mlaunch[63638:5188301] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.InfoEditorType for extension Xcode.Xcode3ProjectSupport.InfoEditorType.Reality.Framework of plug-in com.apple.dt.IDEVisionSupportUI
2024-11-10 17:59:57.543 mlaunch[63638:5188301] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.InfoEditorType for extension Xcode.Xcode3ProjectSupport.InfoEditorType.Reality.Bundle of plug-in com.apple.dt.IDEVisionSupportUI
2024-11-10 17:59:57.543 mlaunch[63638:5188301] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.InfoEditorType for extension Xcode.Xcode3ProjectSupport.InfoEditorType.Reality.Application of plug-in com.apple.dt.IDEVisionSupportUI
2024-11-10 17:59:57.543 mlaunch[63638:5188301] Requested but did not find extension point with identifier Xcode.Xcode3UI.Xcode3SupportedDestinations for extension IDEVisionSupportUI:IDEVisionSupportUI.plugindata/plug-in[1]/extension[5] of plug-in com.apple.dt.IDEVisionSupportUI
2024-11-10 17:59:57.543 mlaunch[63638:5188301] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.DeviceIconProvider for extension Xcode.DebuggerFoundation.DeviceIconProvider.AppleTV of plug-in com.apple.dt.IDEAppleTVSupportUI
2024-11-10 17:59:57.543 mlaunch[63638:5188301] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.DataSourceConnection for extension Xcode.DebuggerFoundation.tvOS.DataSourceConnectionTargetHub of plug-in com.apple.dt.IDEAppleTVSupportUI
2024-11-10 17:59:57.543 mlaunch[63638:5188301] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.ViewDescriber for extension Xcode.DebuggerFoundation.ATVSimulator.ViewDescriber of plug-in com.apple.dt.IDEAppleTVSupportUI
2024-11-10 17:59:57.543 mlaunch[63638:5188301] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.InfoEditorSlice for extension Xcode.Xcode3ProjectSupport.InfoEditorSlice.appletvos.BundleTargetInfo of plug-in com.apple.dt.IDEAppleTVSupportUI
2024-11-10 17:59:57.543 mlaunch[63638:5188301] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.InfoEditorType for extension Xcode.Xcode3ProjectSupport.InfoEditorType.appletvos.Bundle of plug-in com.apple.dt.IDEAppleTVSupportUI
2024-11-10 17:59:57.543 mlaunch[63638:5188301] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.DataSourceConnection for extension Xcode.DebuggerFoundation.tvOSSimulator.DataSourceConnectionTargetHub of plug-in com.apple.dt.IDEAppleTVSupportUI
2024-11-10 17:59:57.543 mlaunch[63638:5188301] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.ViewDescriber for extension Xcode.DebuggerFoundation.ATV.ViewDescriber of plug-in com.apple.dt.IDEAppleTVSupportUI
2024-11-10 17:59:57.543 mlaunch[63638:5188301] Requested but did not find extension point with identifier Xcode.Xcode3UI.Xcode3SupportedDestinations for extension IDEAppleTVSupportUI:IDEAppleTVSupportUI.plugindata/plug-in[1]/extension[11] of plug-in com.apple.dt.IDEAppleTVSupportUI
2024-11-10 18:00:03.379 mlaunch[63670:5188691] Requested but did not find extension point with identifier Xcode.IDEDebugger.VariablesViewQuickLookProvider for extension Xcode.IDEDebugger.SpriteKitQuickLookProvider of plug-in com.apple.IDESpriteKitParticleEditor
2024-11-10 18:00:03.380 mlaunch[63670:5188691] Requested but did not find extension point with identifier Xcode.IDEDebugger.VariablesViewQuickLookProvider for extension Xcode.SpriteKit.GKStateMachineQuickLookProvider of plug-in com.apple.IDESpriteKitParticleEditor
2024-11-10 18:00:03.387 mlaunch[63670:5188691] Requested but did not find extension point with identifier Xcode.IDEPlaygroundsKit.PlaygroundBottomBarExecutionAdaptor for extension Xcode.IDEPlaygroundEditor.IDEPlaygroundBottomBarExecutionAdaptor of plug-in com.apple.dt.IDEPlaygroundEditorPlugin
2024-11-10 18:00:03.388 mlaunch[63670:5188691] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.InfoEditorType for extension Xcode.Xcode3ProjectSupport.InfoEditorType.WatchOS.Bundle of plug-in com.apple.dt.IDEWatchSupportUI
2024-11-10 18:00:03.388 mlaunch[63670:5188691] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.InfoEditorSlice for extension Xcode.Xcode3ProjectSupport.InfoEditorSlice.WatchOS.BundleInfo of plug-in com.apple.dt.IDEWatchSupportUI
2024-11-10 18:00:03.388 mlaunch[63670:5188691] Requested but did not find extension point with identifier Xcode.Xcode3UI.Xcode3SupportedDestinations for extension IDEWatchSupportUI:IDEWatchSupportUI.plugindata/plug-in[1]/extension[11] of plug-in com.apple.dt.IDEWatchSupportUI
2024-11-10 18:00:03.388 mlaunch[63670:5188691] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.DataSourceConnection for extension Xcode.DebuggerFoundation.watchOS.DataSourceConnectionTargetHub of plug-in com.apple.dt.IDEWatchSupportUI
2024-11-10 18:00:03.388 mlaunch[63670:5188691] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.ViewDescriber for extension Xcode.DebuggerFoundation.watchOSSimulator.ViewDescriber of plug-in com.apple.dt.IDEWatchSupportUI
2024-11-10 18:00:03.388 mlaunch[63670:5188691] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.DataSourceConnection for extension Xcode.DebuggerFoundation.watchOSSimulator.DataSourceConnectionTargetHub of plug-in com.apple.dt.IDEWatchSupportUI
2024-11-10 18:00:03.388 mlaunch[63670:5188691] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.ViewDescriber for extension Xcode.DebuggerFoundation.watchOS.ViewDescriber of plug-in com.apple.dt.IDEWatchSupportUI
2024-11-10 18:00:03.388 mlaunch[63670:5188691] Requested but did not find extension point with identifier Xcode.IDEiOSSupportCore.iOSDeviceLocatorMapping for extension Xcode.IDEiOSSupportCore.iOSDeviceLocatorMapping.driverkit of plug-in com.apple.dt.IDEDriverKitSupportCore
2024-11-10 18:00:03.388 mlaunch[63670:5188691] Requested but did not find extension point with identifier Xcode.Xcode3UI.Xcode3SupportedDestinations for extension IDEDriverKitSupportUI:IDEDriverKitSupportUI.plugindata/plug-in[1]/extension[2] of plug-in com.apple.dt.IDEDriverKitSupportUI
2024-11-10 18:00:03.389 mlaunch[63670:5188691] Requested but did not find extension point with identifier Xcode.Xcode3UI.Xcode3SupportedDestinations for extension IDEOSXSupportUI:IDEOSXSupportUI.plugindata/plug-in[1]/extension[5] of plug-in com.apple.dt.IDEOSXSupportUI
2024-11-10 18:00:03.389 mlaunch[63670:5188691] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.InfoEditorType for extension Xcode.Xcode3ProjectSupport.InfoEditorType.Reality.Framework of plug-in com.apple.dt.IDEVisionSupportUI
2024-11-10 18:00:03.389 mlaunch[63670:5188691] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.InfoEditorType for extension Xcode.Xcode3ProjectSupport.InfoEditorType.Reality.Bundle of plug-in com.apple.dt.IDEVisionSupportUI
2024-11-10 18:00:03.389 mlaunch[63670:5188691] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.InfoEditorType for extension Xcode.Xcode3ProjectSupport.InfoEditorType.Reality.Application of plug-in com.apple.dt.IDEVisionSupportUI
2024-11-10 18:00:03.389 mlaunch[63670:5188691] Requested but did not find extension point with identifier Xcode.Xcode3UI.Xcode3SupportedDestinations for extension IDEVisionSupportUI:IDEVisionSupportUI.plugindata/plug-in[1]/extension[5] of plug-in com.apple.dt.IDEVisionSupportUI
2024-11-10 18:00:03.390 mlaunch[63670:5188691] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.InfoEditorType for extension Xcode.Xcode3ProjectSupport.InfoEditorType.appletvos.Bundle of plug-in com.apple.dt.IDEAppleTVSupportUI
2024-11-10 18:00:03.390 mlaunch[63670:5188691] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.ViewDescriber for extension Xcode.DebuggerFoundation.ATV.ViewDescriber of plug-in com.apple.dt.IDEAppleTVSupportUI
2024-11-10 18:00:03.390 mlaunch[63670:5188691] Requested but did not find extension point with identifier Xcode.Xcode3UI.Xcode3SupportedDestinations for extension IDEAppleTVSupportUI:IDEAppleTVSupportUI.plugindata/plug-in[1]/extension[11] of plug-in com.apple.dt.IDEAppleTVSupportUI
2024-11-10 18:00:03.390 mlaunch[63670:5188691] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.DeviceIconProvider for extension Xcode.DebuggerFoundation.DeviceIconProvider.AppleTV of plug-in com.apple.dt.IDEAppleTVSupportUI
2024-11-10 18:00:03.390 mlaunch[63670:5188691] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.DataSourceConnection for extension Xcode.DebuggerFoundation.tvOS.DataSourceConnectionTargetHub of plug-in com.apple.dt.IDEAppleTVSupportUI
2024-11-10 18:00:03.390 mlaunch[63670:5188691] Requested but did not find extension point with identifier Xcode.Xcode3ProjectSupport.InfoEditorSlice for extension Xcode.Xcode3ProjectSupport.InfoEditorSlice.appletvos.BundleTargetInfo of plug-in com.apple.dt.IDEAppleTVSupportUI
2024-11-10 18:00:03.390 mlaunch[63670:5188691] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.ViewDescriber for extension Xcode.DebuggerFoundation.ATVSimulator.ViewDescriber of plug-in com.apple.dt.IDEAppleTVSupportUI
2024-11-10 18:00:03.390 mlaunch[63670:5188691] Requested but did not find extension point with identifier Xcode.DebuggerFoundation.DataSourceConnection for extension Xcode.DebuggerFoundation.tvOSSimulator.DataSourceConnectionTargetHub of plug-in com.apple.dt.IDEAppleTVSupportUI
xcrun devicectl -j /var/folders/rt/nnn7mv9n5653227kn0w3rkxc0000gq/T/tmpqv5Pnh.tmp device process launch --terminate-existing --device 00008101-000645893A79A01E --console com.mydomain.TestMap
2024-11-10 18:00:03.944 TestMap[9176:2472092] You've implemented -[<UIApplicationDelegate> application:performFetchWithCompletionHandler:], but you still need to add "fetch" to the list of your supported UIBackgroundModes in your Info.plist.
2024-11-10 18:00:04.208 TestMap[9176:2472092] CAMetalLayer ignoring invalid setDrawableSize width=0.000000 height=0.000000
=================================================================
	Native Crash Reporting
2024-11-10 18:00:17.862 TestMap[9176:2472092] Unhandled managed exception: Arg_InvalidCastException (System.InvalidCastException)
=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries
used by your application.
   at MapKit.MKMapView._MKMapViewDelegate.__Registrar_Callbacks__.callback_788_MapKit_MKMapView__MKMapViewDelegate_GetViewForAnnotation(IntPtr pobj, IntPtr sel, IntPtr p0, IntPtr p1, IntPtr* exception_gchandle)
=================================================================
--- End of stack trace from previous location ---
=================================================================
   at ObjCRuntime.Runtime.ThrowException(IntPtr )
	Native stacktrace:
   at UIKit.UIApplication.UIApplicationMain(Int32 , String[] , IntPtr , IntPtr )
=================================================================
   at UIKit.UIApplication.Main(String[] , Type , Type )
   at TestMap.Program.Main(String[] args)
	0x102484a38 - /private/var/containers/Bundle/Application/CE518CA2-5CE9-4820-A0EE-B6785BC3C7D0/TestMap.app/TestMap : mono_dump_native_crash_info
	0x10246f214 - /private/var/containers/Bundle/Application/CE518CA2-5CE9-4820-A0EE-B6785BC3C7D0/TestMap.app/TestMap : mono_handle_native_crash
	0x1024f08f0 - /private/var/containers/Bundle/Application/CE518CA2-5CE9-4820-A0EE-B6785BC3C7D0/TestMap.app/TestMap : sigabrt_signal_handler.cold.1
	0x10248434c - /private/var/containers/Bundle/Application/CE518CA2-5CE9-4820-A0EE-B6785BC3C7D0/TestMap.app/TestMap : mono_runtime_setup_stat_profiler
	0x216dbcafc - /usr/lib/system/libsystem_platform.dylib : <redacted>
	0x216f86ef8 - /usr/lib/system/libsystem_pthread.dylib : pthread_kill
	0x19690bad8 - /usr/lib/system/libsystem_c.dylib : abort
	0x102325c48 - /private/var/containers/Bundle/Application/CE518CA2-5CE9-4820-A0EE-B6785BC3C7D0/TestMap.app/TestMap : _ZL12log_callbackPKcS0_S0_iPv
	0x1023bc808 - /private/var/containers/Bundle/Application/CE518CA2-5CE9-4820-A0EE-B6785BC3C7D0/TestMap.app/TestMap : mono_invoke_unhandled_exception_hook
	0x102459b6c - /private/var/containers/Bundle/Application/CE518CA2-5CE9-4820-A0EE-B6785BC3C7D0/TestMap.app/TestMap : mono_jit_exec
	0x10232e09c - /private/var/containers/Bundle/Application/CE518CA2-5CE9-4820-A0EE-B6785BC3C7D0/TestMap.app/TestMap : xamarin_main
	0x1024cb544 - /private/var/containers/Bundle/Application/CE518CA2-5CE9-4820-A0EE-B6785BC3C7D0/TestMap.app/TestMap : main
	0x1b453aec8 - /usr/lib/dyld : <redacted>
=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x1def191d4):0x1def191c4  ff 0f 5f d6 c0 03 5f d6 10 29 80 d2 01 10 00 d4  .._..._..)......
0x1def191d4  03 01 00 54 7f 23 03 d5 fd 7b bf a9 fd 03 00 91  ...T.#...{......
0x1def191e4  31 ec ff 97 bf 03 00 91 fd 7b c1 a8 ff 0f 5f d6  1........{...._.
0x1def191f4  c0 03 5f d6 10 27 80 d2 01 10 00 d4 03 01 00 54  .._..'.........T
=================================================================
	Managed Stacktrace:
=================================================================

=================================================================
18:00:03  Acquired tunnel connection to device.
18:00:03  Enabling developer disk image services.
18:00:03  Acquired usage assertion.
Launched application with com.mydomain.TestMap bundle identifier.
Waiting for the application to terminate...
App terminated due to signal 6.
error MT1045: Failed to execute 'devicectl': 'devicectl -j /var/folders/rt/nnn7mv9n5653227kn0w3rkxc0000gq/T/tmpqv5Pnh.tmp device process launch --terminate-existing --device 00008101-000645893A79A01E --console com.mydomain.TestMap' returned the exit code 1.
error MT1046: Additional output: xcrun devicectl -j /var/folders/rt/nnn7mv9n5653227kn0w3rkxc0000gq/T/tmpqv5Pnh.tmp device process launch --terminate-existing --device 00008101-000645893A79A01E --console com.mydomain.TestMap
error MT1046: Additional output: 2024-11-10 18:00:03.944 TestMap[9176:2472092] You've implemented -[<UIApplicationDelegate> application:performFetchWithCompletionHandler:], but you still need to add "fetch" to the list of your supported UIBackgroundModes in your Info.plist.
error MT1046: Additional output: 2024-11-10 18:00:04.208 TestMap[9176:2472092] CAMetalLayer ignoring invalid setDrawableSize width=0.000000 height=0.000000
error MT1046: Additional output:
error MT1046: Additional output: =================================================================
error MT1046: Additional output: 	Native Crash Reporting
error MT1046: Additional output: 2024-11-10 18:00:17.862 TestMap[9176:2472092] Unhandled managed exception: Arg_InvalidCastException (System.InvalidCastException)
error MT1046: Additional output: =================================================================
error MT1046: Additional output: Got a SIGABRT while executing native code. This usually indicates
error MT1046: Additional output: a fatal error in the mono runtime or one of the native libraries
error MT1046: Additional output: used by your application.
error MT1046: Additional output:    at MapKit.MKMapView._MKMapViewDelegate.__Registrar_Callbacks__.callback_788_MapKit_MKMapView__MKMapViewDelegate_GetViewForAnnotation(IntPtr pobj, IntPtr sel, IntPtr p0, IntPtr p1, IntPtr* exception_gchandle)
error MT1046: Additional output: =================================================================
error MT1046: Additional output:
error MT1046: Additional output: --- End of stack trace from previous location ---
error MT1046: Additional output: =================================================================
error MT1046: Additional output:    at ObjCRuntime.Runtime.ThrowException(IntPtr )
error MT1046: Additional output: 	Native stacktrace:
error MT1046: Additional output:    at UIKit.UIApplication.UIApplicationMain(Int32 , String[] , IntPtr , IntPtr )
error MT1046: Additional output: =================================================================
error MT1046: Additional output:    at UIKit.UIApplication.Main(String[] , Type , Type )
error MT1046: Additional output:    at TestMap.Program.Main(String[] args)
error MT1046: Additional output: 	0x102484a38 - /private/var/containers/Bundle/Application/CE518CA2-5CE9-4820-A0EE-B6785BC3C7D0/TestMap.app/TestMap : mono_dump_native_crash_info
error MT1046: Additional output: 	0x10246f214 - /private/var/containers/Bundle/Application/CE518CA2-5CE9-4820-A0EE-B6785BC3C7D0/TestMap.app/TestMap : mono_handle_native_crash
error MT1046: Additional output: 	0x1024f08f0 - /private/var/containers/Bundle/Application/CE518CA2-5CE9-4820-A0EE-B6785BC3C7D0/TestMap.app/TestMap : sigabrt_signal_handler.cold.1
error MT1046: Additional output: 	0x10248434c - /private/var/containers/Bundle/Application/CE518CA2-5CE9-4820-A0EE-B6785BC3C7D0/TestMap.app/TestMap : mono_runtime_setup_stat_profiler
error MT1046: Additional output: 	0x216dbcafc - /usr/lib/system/libsystem_platform.dylib : <redacted>
error MT1046: Additional output: 	0x216f86ef8 - /usr/lib/system/libsystem_pthread.dylib : pthread_kill
error MT1046: Additional output: 	0x19690bad8 - /usr/lib/system/libsystem_c.dylib : abort
error MT1046: Additional output: 	0x102325c48 - /private/var/containers/Bundle/Application/CE518CA2-5CE9-4820-A0EE-B6785BC3C7D0/TestMap.app/TestMap : _ZL12log_callbackPKcS0_S0_iPv
error MT1046: Additional output: 	0x1023bc808 - /private/var/containers/Bundle/Application/CE518CA2-5CE9-4820-A0EE-B6785BC3C7D0/TestMap.app/TestMap : mono_invoke_unhandled_exception_hook
error MT1046: Additional output: 	0x102459b6c - /private/var/containers/Bundle/Application/CE518CA2-5CE9-4820-A0EE-B6785BC3C7D0/TestMap.app/TestMap : mono_jit_exec
error MT1046: Additional output: 	0x10232e09c - /private/var/containers/Bundle/Application/CE518CA2-5CE9-4820-A0EE-B6785BC3C7D0/TestMap.app/TestMap : xamarin_main
error MT1046: Additional output: 	0x1024cb544 - /private/var/containers/Bundle/Application/CE518CA2-5CE9-4820-A0EE-B6785BC3C7D0/TestMap.app/TestMap : main
error MT1046: Additional output: 	0x1b453aec8 - /usr/lib/dyld : <redacted>
error MT1046: Additional output:
error MT1046: Additional output: =================================================================
error MT1046: Additional output: 	Basic Fault Address Reporting
error MT1046: Additional output: =================================================================
error MT1046: Additional output: Memory around native instruction pointer (0x1def191d4):0x1def191c4  ff 0f 5f d6 c0 03 5f d6 10 29 80 d2 01 10 00 d4  .._..._..)......
error MT1046: Additional output: 0x1def191d4  03 01 00 54 7f 23 03 d5 fd 7b bf a9 fd 03 00 91  ...T.#...{......
error MT1046: Additional output: 0x1def191e4  31 ec ff 97 bf 03 00 91 fd 7b c1 a8 ff 0f 5f d6  1........{...._.
error MT1046: Additional output: 0x1def191f4  c0 03 5f d6 10 27 80 d2 01 10 00 d4 03 01 00 54  .._..'.........T
error MT1046: Additional output:
error MT1046: Additional output: =================================================================
error MT1046: Additional output: 	Managed Stacktrace:
error MT1046: Additional output: =================================================================

error MT1046: Additional output: =================================================================
error MT1046: Additional output: 18:00:03  Acquired tunnel connection to device.
error MT1046: Additional output: 18:00:03  Enabling developer disk image services.
error MT1046: Additional output: 18:00:03  Acquired usage assertion.
error MT1046: Additional output: Launched application with com.mydomain.TestMap bundle identifier.
error MT1046: Additional output: Waiting for the application to terminate...
error MT1046: Additional output: App terminated due to signal 6.
```

**Comment by mattleibow** [comment]
Is this just Release mode or also in Debug?

**Comment by MichelePannacciTerex** [comment]
> Is this just Release mode or also in Debug?

Hi, just tried and it crash also in Debug mode. In release the issue appear immediate while in debug you have to play zooming into the map a little more, not sure why. anyway yes.

**Comment by QwertyMC** [comment]
I am also seeing this issue where map loads fine until your location comes into view on the map, then the crash occurs.  Setting IsShowingUser = False, stops the issue but clearly not a valid workaround.

**Comment by MichelePannacciTerex** [comment]
After update to the new 9.0.10 i can see a new output:

`2024-11-14 23:15:05.757499+0100 MES[55492:3612663] [CoreLocation] __delegate_identifier__:Performance Diagnostics__:::____message__: This method can cause UI unresponsiveness if invoked on the main thread. Instead, consider waiting for the `-locationManagerDidChangeAuthorization:` callback and checking `authorizationStatus` first.`

That in Release in the simulator. I'm going to check it on real device and report back

**Comment by kaniosm** [comment]
I'm facing a similar issue (see here: https://github.com/dotnet/maui/issues/26000).
I can see the below, in the both MauiMKMapView and the legacy renderer, which makes me believe that the user location cannot be cast to IMKAnnotation under certain circumstances. 

// https://bugzilla.xamarin.com/show_bug.cgi?id=26416
var userLocationAnnotation = Runtime.GetNSObject(annotation.Handle) as MKUserLocation;

**Comment by rolfbjarne** [comment]
This issue was moved to xamarin/xamarin-macios#21759

**Comment by mikeparker104** [comment]
Workaround: https://github.com/xamarin/xamarin-macios/issues/21759#issuecomment-2520066591
