### ISSUE TITLE
Can't install on device w/ 9.0.100 but 9.0.0-rc.2 works

### ISSUE THREAD

**Issue by derekoakley** [dotnet/maui#25860]
### Description

I have been able to deploy my maui app to my device fine w/ .net 9.0.0-rc.2 but after updating to 9.0.100 I receive the following error:

`error MT1006: Could not install the application ... One of the identified items was in an invalid format..`

### Version with bug

9.0.0 GA

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

9.0.0-rc.2.24503.2

### Affected platforms

iOS

### Affected platform versions

iOS18.1

### Did you find any workaround?

Rolling back to 9.0.0-rc.2 fixes the issue and can deploy to device again.

### Relevant log output

```shell

```

**Comment by tecomunico** [comment]
Unfortunately, it’s no longer compatible with the Mac version. Every time Microsoft updates or releases a new SDK, it’s a major issue with tons of errors. It’s like when a machine boots with Windows—it always gives blue screens, saying there’s an update. I’ve had enough; I’m throwing in the towel. I’m going to join the Flutter community for development. Bye

**Comment by mapsouza** [comment]
same problem here. 


I formatted my MacBook because this problem and installed:
- .net 9 SDK
- rider
- VSCode with extensions

First test it's worked fine. Now after deleting bin/obj and trying to build in Rider, first the app is deployed to device and I receive this error without debug started:

error MT0000: Unexpected error - Please file a bug report at https://github.com/xamarin/xamarin-macios/issues/new
System.FormatException: One of the identified items was in an invalid format.
   at System.Text.Json.ThrowHelper.ThrowFormatException()
   at System.Text.Json.JsonElement.GetInt64()
   at Xamarin.Hosting.JsonExtensions.GetInt64Property(Nullable`1, String[] ) in /Users/builder/azdo/_work/2/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Hosting/JsonExtensions.cs:line 44
   at Xamarin.Hosting.DeviceCtlDevice..ctor(JsonElement) in /Users/builder/azdo/_work/2/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Hosting/DeviceCtlDevice.cs:line 44
   at Xamarin.Hosting.DeviceDiscovery.FindDeviceWithDeviceCtlAsync(Func`2) in /Users/builder/azdo/_work/2/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Hosting/DeviceDiscovery.cs:line 55
   at Xamarin.Hosting.DeviceDiscovery.FindDeviceAsync(Func`2) in /Users/builder/azdo/_work/2/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Hosting/DeviceDiscovery.cs:line 39
   at Xamarin.Hosting.DeviceDiscovery.FindDeviceAsync(String, Boolean , Boolean , Boolean ) in /Users/builder/azdo/_work/2/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Hosting/DeviceDiscovery.cs:line 111
   at Xamarin.Launcher.Driver.LaunchOrDebugAsync(Action) in /Users/builder/azdo/_work/2/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Launcher/Main.cs:line 551
   at Xamarin.Launcher.Driver.MainAsync() in /Users/builder/azdo/_work/2/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Launcher/Main.cs:line 498
   at Xamarin.Utils.NSRunLoopExtensions.RunUntilTaskCompletion[T](NSRunLoop, Task`1) in /Users/builder/azdo/_work/2/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Utils/Extensions.cs:line 30
   at Xamarin.Launcher.Driver.Main2(String[]) in /Users/builder/azdo/_work/2/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Launcher/Main.cs:line 443
   at Xamarin.Launcher.Driver.Main(String[]) in /Users/builder/azdo/_work/2/s/tools/mlaunch/Xamarin.Hosting/Xamarin.Launcher/Main.cs:line 130
Failed to connect: Failed to establish connection to debugger agent

After that, every time I tried, I got the error:

Failed to install application on device iPhone Marcel: error MT1006: Could not install the application '/Users/user/Nameapp.app' on the device 'iPhone': One of the identified items was in an invalid format..

**Comment by blacksnow1** [comment]
Same here

**Comment by jfversluis** [comment]
@rolfbjarne @dalexsoto ?

@derekoakley can you share the specific version numbers of tools and SDKs you are using?

**Comment by Saccomani** [comment]
same issue here..

is showing
`maui error MT1006: Could not install the application on the device One of the identified items was in an invalid format..`

then I try to debug on device, and crash in test flight

![Image](https://github.com/user-attachments/assets/3cb397f3-1e17-4ac0-8fe8-76cc069d00d8)

**Comment by rolfbjarne** [comment]
This issue was moved to xamarin/xamarin-macios#21639
