### ISSUE TITLE
[Bug] Memory stream is closed inside MauiAppBuilder 

### ISSUE THREAD

**Issue by EliaCools** [dotnet/maui#2592]
### Description
When configuring the host configuration from MauiProgram.cs, using the dotnet Core Generic Host. 
The exception "Stream was not readable" is thrown.

This bug appears when adding a MemoryStream to the configurationBuilder.

Below is an image of the locals from the de Microsoft.Maui.MauiAppBuilder, as you can see it tries to read the Memory Stream twice. Throwing a System.ObjectDisposedException the second time.

![MauiAppBugLocal png](https://user-images.githubusercontent.com/74154010/133975590-e8f5902d-62e8-43d2-beb0-7c9e4b8ce9f1.jpg)

### Steps to Reproduce
I have added a reproduction link. For now it is added as a google drive link as I had trouble inserting the .zip file directly.
Sorry for the inconvenience.

### Expected Behavior
Configure the host configuration using the Memory Stream.

### Actual Behavior
MauiAppBuilder throws  System.ArgumentException: 'Stream was not readable.'

### Basic Information

- Version with issue: .NET MAUI Preview 8
- Last known good version: .NET MAUI Preview 7
- IDE: Visual Studio 2022 Preview 4
- Affected Devices:  Android 11.0 - API 30

### Reproduction Link
https://drive.google.com/file/d/1m2nfYmfDV2guJLfPAtlMJJupTHU57YH1/view?usp=sharing

**Comment by Eilon** [comment]
Hi @EliaCools , thank you for the bug report, this is certainly unexpected. Would you be able to post your repro app as a GitHub repo? We're not able to open other types of attachments.

**Comment by Eilon** [comment]
Or, could you show what code you wrote to do this:

> This bug appears when adding a MemoryStream to the configurationBuilder.

**Comment by EliaCools** [comment]
Hello @Eilon Thank you for responding. I have made a repository for the bug reproduction. https://github.com/EliaCools/HostConfigBugReproduction/tree/main

**Comment by Eilon** [comment]
OK I can confirm this repros for me. Will investigate.

**Comment by Eilon** [comment]
The provided JSON stream is read once immediately when calling `configurationBuilder.AddJsonStream(stream)`, which leaves the stream's position at the end of the stream. Then when `MauiAppBuilder.Build()` is called, the internal ConfigurationBuilder tries to read the stream again, but it can't, because it's already at the end of the stream.

Interestingly, I tried the exact code in an ASP.NET Core app and I got the same results. So it seems that either for some bizarre reason this isn't _supposed_ to work (seems unlikely!), or there's a common bug either because we copied a bug, or the bug is in a shared type (e.g. something from MS.Extensions).

Maui / WinUI stack trace:

```
System.Text.Json.JsonReaderException
  HResult=0x80131500
  Message=The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. LineNumber: 0 | BytePositionInLine: 0.
  Source=System.Text.Json
  StackTrace:
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.JsonDocument.Parse(ReadOnlySpan`1 utf8JsonSpan, JsonReaderOptions readerOptions, MetadataDb& database, StackRowStack& stack)
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 utf8Json, JsonReaderOptions readerOptions, Byte[] extraRentedArrayPoolBytes, PooledByteBufferWriter extraPooledByteBufferWriter)
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 json, JsonDocumentOptions options)
   at System.Text.Json.JsonDocument.Parse(String json, JsonDocumentOptions options)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationFileParser.ParseStream(Stream input)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationFileParser.Parse(Stream input)
   at Microsoft.Extensions.Configuration.Json.JsonStreamConfigurationProvider.Load(Stream stream)
   at Microsoft.Extensions.Configuration.StreamConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Microsoft.Extensions.Hosting.HostBuilder.BuildHostConfiguration()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Microsoft.Maui.MauiAppBuilder.Build()
   at TestMaui.MauiProgram.CreateMauiApp() in C:\GitHub\maui\src\Templates\TestMaui\MauiProgram.cs:line 114

  This exception was originally thrown at this call stack:
    System.Text.Json.ThrowHelper.ThrowJsonReaderException(ref System.Text.Json.Utf8JsonReader, System.Text.Json.ExceptionResource, byte, System.ReadOnlySpan<byte>)
    System.Text.Json.Utf8JsonReader.Read()
    System.Text.Json.JsonDocument.Parse(System.ReadOnlySpan<byte>, System.Text.Json.JsonReaderOptions, ref System.Text.Json.JsonDocument.MetadataDb, ref System.Text.Json.JsonDocument.StackRowStack)
    System.Text.Json.JsonDocument.Parse(System.ReadOnlyMemory<byte>, System.Text.Json.JsonReaderOptions, byte[], System.Text.Json.PooledByteBufferWriter)
    System.Text.Json.JsonDocument.Parse(System.ReadOnlyMemory<char>, System.Text.Json.JsonDocumentOptions)
    System.Text.Json.JsonDocument.Parse(string, System.Text.Json.JsonDocumentOptions)
    Microsoft.Extensions.Configuration.Json.JsonConfigurationFileParser.ParseStream(System.IO.Stream)
    Microsoft.Extensions.Configuration.Json.JsonConfigurationFileParser.Parse(System.IO.Stream)
    Microsoft.Extensions.Configuration.Json.JsonStreamConfigurationProvider.Load(System.IO.Stream)
    Microsoft.Extensions.Configuration.StreamConfigurationProvider.Load()
    ...
    [Call Stack Truncated]
```

ASP.NET Core stack trace:

```
System.Text.Json.JsonReaderException
  HResult=0x80131500
  Message=The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. LineNumber: 0 | BytePositionInLine: 0.
  Source=System.Text.Json
  StackTrace:
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.JsonDocument.Parse(ReadOnlySpan`1 utf8JsonSpan, JsonReaderOptions readerOptions, MetadataDb& database, StackRowStack& stack)
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 utf8Json, JsonReaderOptions readerOptions, Byte[] extraRentedArrayPoolBytes, PooledByteBufferWriter extraPooledByteBufferWriter)
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 json, JsonDocumentOptions options)
   at System.Text.Json.JsonDocument.Parse(String json, JsonDocumentOptions options)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationFileParser.ParseStream(Stream input)
   at Microsoft.Extensions.Configuration.Json.JsonStreamConfigurationProvider.Load(Stream stream)
   at Microsoft.Extensions.Configuration.StreamConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Microsoft.Extensions.Hosting.HostBuilder.BuildAppConfiguration()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Microsoft.AspNetCore.Builder.WebApplicationBuilder.Build()
   at Program.<Main>$(String[] args) in C:\GitHub\maui\src\Templates\WebApplication1\Program.cs:line 12

  This exception was originally thrown at this call stack:
    System.Text.Json.ThrowHelper.ThrowJsonReaderException(ref System.Text.Json.Utf8JsonReader, System.Text.Json.ExceptionResource, byte, System.ReadOnlySpan<byte>)
    System.Text.Json.Utf8JsonReader.Read()
    System.Text.Json.JsonDocument.Parse(System.ReadOnlySpan<byte>, System.Text.Json.JsonReaderOptions, ref System.Text.Json.JsonDocument.MetadataDb, ref System.Text.Json.JsonDocument.StackRowStack)
    System.Text.Json.JsonDocument.Parse(System.ReadOnlyMemory<byte>, System.Text.Json.JsonReaderOptions, byte[], System.Text.Json.PooledByteBufferWriter)
    System.Text.Json.JsonDocument.Parse(System.ReadOnlyMemory<char>, System.Text.Json.JsonDocumentOptions)
    System.Text.Json.JsonDocument.Parse(string, System.Text.Json.JsonDocumentOptions)
    Microsoft.Extensions.Configuration.Json.JsonConfigurationFileParser.ParseStream(System.IO.Stream)
    Microsoft.Extensions.Configuration.Json.JsonStreamConfigurationProvider.Load(System.IO.Stream)
    Microsoft.Extensions.Configuration.StreamConfigurationProvider.Load()
    Microsoft.Extensions.Configuration.ConfigurationRoot.ConfigurationRoot(System.Collections.Generic.IList<Microsoft.Extensions.Configuration.IConfigurationProvider>)
    ...
    [Call Stack Truncated]
```

And for an even simpler repro, in either a MAUI app's `MauiProgram.cs` or an ASP.NET Core app's `Program.cs` you can just add this code prior to `builder.Build()` being called:

```c#
builder.Host.ConfigureHostConfiguration(configurationBuilder =>
{
	var jsonConfig = "{ 'foo': 'bar' }";
	var ms = new MemoryStream();
	var sw = new StreamWriter(ms);
	sw.WriteLine(jsonConfig);
	ms.Position = 0;
	configurationBuilder.AddJsonStream(ms);
});
```

@halter73 / @davidfowl - does anything seem invalid about this scenario, or maybe there's a bug somewhere in Hosting, or how ASP.NET/MAUI use Hosting?

**Comment by davidfowl** [comment]
It's a bug in the new `ConfigurationManager` it seems. Here's an even simpler repro:

This fails:

```C#
var cm = new ConfigurationManager();
var jsonConfig = "{ 'foo': 'bar' }";
var ms = new MemoryStream();
var sw = new StreamWriter(ms);
sw.WriteLine(jsonConfig);
ms.Position = 0;
cm.AddJsonStream(ms);
```

This works:

```C#
var cb = new ConfigurationBuilder();
var jsonConfig = "{ 'foo': 'bar' }";
var ms = new MemoryStream();
var sw = new StreamWriter(ms);
sw.WriteLine(jsonConfig);
ms.Position = 0;
cb.AddJsonStream(ms);
```

We'll need to fix this in dotnet/runtime. Should we transfer the issue?

cc @ericstj @eerhardt for visibility

**Comment by ericstj** [comment]
>  Should we transfer the issue?

Seems so.  I don't have permission to do so, can you?  @halter73 were you planning to fix this?
