### ISSUE TITLE
[MAUI]  error NETSDK1082 & error 'XAPRAS7004 will happen when solution name with "()" or solution in directories with “()”

### ISSUE THREAD

**Issue by ninachen03** [dotnet/maui#26092]
### Description

Error NETSDK1082 & error 'XAPRAS7004 will happen when solution name with "()" or solution in directories with “()”

### Steps to Reproduce

1. Created Maui project named with () EG: MauiApp(test)
2. Observed the error List. Show error in error list , please see below.
![Image](https://github.com/user-attachments/assets/2f729a9d-133f-4d2e-a5ae-abc33c983d26)
 NETSDK1082 :There was no runtime pack for Microsoft.NETCore.App available for the specified RuntimeIdentifier 'iossimulator-x64'.
 NETSDK1082 :There was no runtime pack for Microsoft.NETCore.App available for the specified RuntimeIdentifier 'maccatalyst-x64'.
3. Build the project will add an XAPRAS7004 error
![Image](https://github.com/user-attachments/assets/399f9c31-a0fc-4131-8477-0acec7beecef)
 XAPRAS7004:System.ArgumentException: must not be null or empty
Parameter name: abi
   at Xamarin.Android.Tasks.ProcessAssemblies.SetAssemblyAbiMetadata(String abi, ITaskItem assembly, ITaskItem symbol) in /Users/runner/work/1/s/xamarin-android/src/Xamarin.Android.Build.Tasks/Tasks/ProcessAssemblies.cs:line 99
   at Xamarin.Android.Tasks.ProcessAssemblies.SetMetadataForAssemblies(List`1 output, Dictionary`2 symbols) in /Users/runner/work/1/s/xamarin-android/src/Xamarin.Android.Build.Tasks/Tasks/ProcessAssemblies.cs:line 124
   at Xamarin.Android.Tasks.ProcessAssemblies.RunTask() in /Users/runner/work/1/s/xamarin-android/src/Xamarin.Android.Build.Tasks/Tasks/ProcessAssemblies.cs:line 62
   at Microsoft.Android.Build.Tasks.AndroidTask.Execute() in /Users/runner/work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/AndroidTask.cs:line 25

### Version with bug

17.13.0 Preview 2.0 [35524.33.main]

### Is this a regression from previous behavior?

This error has nothing to do with maui control, it seems to be related to VS, and only occurs in maui projects.
Not repro in build Version 17.13.0 Preview 1.0 & 17.12.0

### Last version that worked well

This error has nothing to do with maui control, it seems to be related to VS, and only occurs in maui projects.
Not repro in build Version 17.13.0 Preview 1.0 & 17.12.0

### Affected platforms

iOS, Android, macOS, Windows

**Comment by jfversluis** [comment]
Looking at the errors this is more something in .NET for Android and/or .NET for iOS that seem to have issues with this. Easy workaround: don't use special characters in your project names or paths 😄
