### ISSUE TITLE
HttpClient GET Api is failing with {System.IO.IOException: Connection reset  ---> Java.Net.SocketException: Connection reset error in .NET MAUI Android

### ISSUE THREAD

**Issue by VenkataReddyDesiReddy** [dotnet/maui#26147]
### Description

HttpClient GET API is failing in .NET MAUI(.NET 8.0) which is working in Xamarin.Forms
Below is the sample code for your reference:

```csharp
CancellationTokenSource cancellationToken = new CancellationTokenSource(60000);
using (FileStream _fileStream = new FileStream(filePath, FileMode.Open))
{
    using (StreamContent _streamContent = new StreamContent(_fileStream))
    {
        HttpRequestMessage requestMessage = new HttpRequestMessage(HttpMethod.Get, Uri_UpgradeStart);
        _streamContent.Headers.ContentLength = Int32.Parse(fileInfo.FileSize);
        requestMessage.Content = _streamContent;
        **var responseMessage = httpClient.SendAsync(requestMessage, HttpCompletionOption.ResponseHeadersRead, cancellationToken.Token).ConfigureAwait(false);**
        if (responseMessage.StatusCode == HttpStatusCode.OK)
        {
            System.Diagnostics.Debug.WriteLine("Uploading upgrade success");
        }
        _fileStream.Close();
        _streamContent.Dispose();
    }
}
```
The line **var responseMessage = httpClient.SendAsync(requestMessage, HttpCompletionOption.ResponseHeadersRead, cancellationToken.Token).ConfigureAwait(false);** is throwing exception 

```csharp
**{System.IO.IOException: Connection reset
 ---> Java.Net.SocketException: Connection reset**
   at Java.Interop.JniEnvironment.InstanceMethods.CallVoidMethod(JniObjectReference instance, JniMethodInfo method, JniArgumentValue* args) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/obj/Release/net7.0/JniEnvironment.g.cs:line 20370
   at Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualVoidMethod(String encodedMember, IJavaPeerable self, JniArgumentValue* parameters) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:line 66
   at Java.IO.OutputStream.Write(Byte[] b, Int32 off, Int32 len) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net8.0/android-34/mcw/Java.IO.OutputStream.cs:line 163
   at Android.Runtime.OutputStreamInvoker.Write(Byte[] buffer, Int32 offset, Int32 count) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/OutputStreamInvoker.cs:line 108
  --- End of managed Java.Net.SocketException stack trace ---
java.net.SocketException: Connection reset
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:121)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:161)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLOutputStream.writeToSocket(ConscryptEngineSocket.java:762)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLOutputStream.writeInternal(ConscryptEngineSocket.java:736)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLOutputStream.write(ConscryptEngineSocket.java:699)
	at com.android.okhttp.okio.Okio$1.write(Okio.java:78)
	at com.android.okhttp.okio.AsyncTimeout$1.write(AsyncTimeout.java:157)
	at com.android.okhttp.okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:177)
	at com.android.okhttp.okio.RealBufferedSink.write(RealBufferedSink.java:47)
	at com.android.okhttp.internal.http.Http1xStream$FixedLengthSink.write(Http1xStream.java:290)
	at com.android.okhttp.okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:177)
	at com.android.okhttp.okio.RealBufferedSink$1.write(RealBufferedSink.java:199)
```

### Version with bug

8.0.100 SR10

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Relevant log output

```shell

```

**Comment by simonrozsival** [comment]
@VenkataReddyDesiReddy would it be possible to share a standalone repro project that makes requests against some public server so I can repro this on my side? It will be hard to do without having access to your server.

It seems suspicious that you are sending content to your server in a GET request. I'm not sure if that is supported.

One thing you might try is to use the managed HTTP handler. To try this, just add this snippet to your project file:
```xml
<PropertyGroup>
    <UseNativeHttpHandler>false</UseNativeHttpHandler>
</PropertyGroup>
```
