### ISSUE TITLE
CarouselView iOS crash when swiping to 2nd carousel page - Index was out of range / System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by RobbiewOnline** [dotnet/maui#26171]
### Description

The Carousel View works no problem on Android, but unfortunately it crashes on iOS (only tried debug) with the stack trace that follows the screenshot.

Note that my logging confirms that the model has 2 questions (`questions:2`) and the screenshot confirms that both questions are rendered on screen.

Everything is fine until I try to scroll the 2nd carousel entity (question) into view, then I get an error about an index being out of bounds.

![Carousel View has two pages](https://github.com/user-attachments/assets/f29619c0-d426-4b61-a346-deda05f26129)

The initial point of the crash outputs this.

```
Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index') (System.ArgumentOutOfRangeException)
```

This works on Android, and since I can visually see two pages in the carousel and my logs indicate that there are two entries in the Questions model, then I don't see why it's nagging about the index being out of range.

### Steps to Reproduce

I may be able to create a repro, but in the meantime running an iOS project with the following XAML causes it to barf

```
<?xml version="1.0" encoding="utf-8" ?>
<toolkit:Popup
    xmlns:toolkit="http://schemas.microsoft.com/dotnet/2022/maui/toolkit"
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:local="clr-namespace:MyTeamSafe"
    xmlns:converters="clr-namespace:MyTeamSafe.Converters" 
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    x:Class="MyTeamSafe.Views.QuestionsPopup"
    xmlns:controls="clr-namespace:MyTeamSafe.Controls"
    xmlns:sliders="clr-namespace:Syncfusion.Maui.Sliders;assembly=Syncfusion.Maui.Sliders"
    Color="White"
    CanBeDismissedByTappingOutsideOfPopup="false">

    <Grid ColumnDefinitions="*" RowDefinitions="*,auto,auto">

        <CarouselView Grid.Row="0" 
            x:Name="QuestionCarousel" ItemsSource="{Binding Questions}" Loop="False" 
                      HorizontalScrollBarVisibility="Never" 
                      IsSwipeEnabled="true"
                      PeekAreaInsets="24"
                      IndicatorView="indicatorView"
                      PositionChangedCommand="{Binding PositionChangedCommand}"
                      PositionChangedCommandParameter="{Binding Source={RelativeSource Self}, Path=Position}">
            <CarouselView.ItemTemplate>
                <DataTemplate>
                    <Grid ColumnDefinitions="*" RowDefinitions="*,*">
                        <VerticalStackLayout Grid.Row="0">
                                <Label Text="Anonymous" Style="{x:DynamicResource LabelPageHeadingStyle}" HorizontalTextAlignment="Center" IsVisible="{Binding IsAnonymous}"></Label>

                                <Label Text="{Binding Title}" Style="{x:DynamicResource LabelSubHeadingTextStyle}"
                                       HorizontalOptions="Center" HorizontalTextAlignment="Center"
                                       VerticalOptions="Center" />
                                <Label Text="{Binding Desc}" Style="{x:DynamicResource BodyTextStyle}"
                                       FontAttributes="Italic"
                                       HorizontalOptions="Center"/>
                        </VerticalStackLayout>

                        <VerticalStackLayout Grid.Row="1">
                            <Label Text="{Binding Value}" IsVisible="{Binding CaptureValue}"
                                    FontAttributes="Bold"
                                    HorizontalOptions="Center"/>
                            
                            <!-- HeightRequest="60" -->
                            <sliders:SfSlider x:Name="rangeslider"  
                                                        Orientation="Horizontal" 
                                                        Maximum="{Binding MaxRange}" Minimum="{Binding MinRange}"                                                       
                                                    Interval="1"                                                    
                                                        MinorTicksPerInterval="1" 
                                                        ShowLabels="true"
                                                        ShowTicks="true"
                                                        Value="{Binding Value}"
                                                        IsVisible="{Binding CaptureValue}">

                                <sliders:SfSlider.ThumbStyle>
                                    <sliders:SliderThumbStyle Fill="#FF59BB7B" />
                                </sliders:SfSlider.ThumbStyle>

                                <sliders:SfSlider.TrackStyle>
                                    <sliders:SliderTrackStyle ActiveFill="#FF59BB7B" InactiveFill="#FFC1F7D4" />
                                </sliders:SfSlider.TrackStyle>

                                <sliders:SfSlider.ThumbOverlayStyle>
                                    <sliders:SliderThumbOverlayStyle Fill="#FF59BB7B"/>
                                </sliders:SfSlider.ThumbOverlayStyle>#66ADA260

                            </sliders:SfSlider>                            

                            <Editor BackgroundColor="LightGrey" TextColor="Black" 
                                MaxLength="100" HeightRequest="100"
                                Margin="0,6,10,0"
                                FontSize="Small" 
                                Keyboard="Chat" IsVisible="{Binding CaptureNote}" Placeholder="Type a brief note here" 
                                Text="{Binding Note}"/>

                        </VerticalStackLayout>

                    </Grid>

                </DataTemplate>
            </CarouselView.ItemTemplate>

        </CarouselView>
        <IndicatorView Grid.Row="1" x:Name="indicatorView" 
                   IndicatorColor="#505159"
                   SelectedIndicatorColor="#398557" 
                   HorizontalOptions="Center" />

        <StackLayout Grid.Row="2" Orientation="Horizontal" Margin="12,0,12,0">
            <Button Style="{x:DynamicResource StandardButtonStyle}" Text="Cancel" TextColor="Red" HorizontalOptions="Start" Command="{Binding QuestionsPopupCancelCommand}"/>
            <StackLayout Orientation="Horizontal" HorizontalOptions="CenterAndExpand">
                <Button Style="{x:DynamicResource StandardButtonStyle}" Text="&lt;" IsVisible="{Binding IsWindows}" Command="{Binding PreviousQuestionCommand}" IsEnabled="{Binding PreviousQuestionEnabled}"/>
                <Button Style="{x:DynamicResource StandardButtonStyle}" Text="&gt;" IsVisible="{Binding IsWindows}" Command="{Binding NextQuestionCommand}" IsEnabled="{Binding NextQuestionEnabled}"/>
            </StackLayout>
            <Button Style="{x:DynamicResource StandardButtonStyle}" Text="Submit" TextColor="Green" HorizontalOptions="End" Command="{Binding QuestionsPopupSubmitCommand}" IsEnabled="{Binding SubmitAnswersIsEnabled}"/>
        </StackLayout>
    </Grid>

</toolkit:Popup>
```

The code-behind is simple

```
using MyTeamSafe.Services;
using MyTeamSafe.ViewModels;
using CommunityToolkit.Maui.Views;

namespace MyTeamSafe.Views
{
    [XamlCompilation(XamlCompilationOptions.Compile)]
    public partial class QuestionsPopup : Popup
    {
        private StorageService StorageService;
        public QuestionsPopup(LoneWorkingViewModel loneWorkingViewModel, StorageService storageService)
        {
            // Set the size of the popup to 80% of the device width and height
            double proposedHeight = 0.6 * (DeviceDisplay.MainDisplayInfo.Height / DeviceDisplay.MainDisplayInfo.Density);
  
            this.Size = new Size(
                0.8 * (DeviceDisplay.MainDisplayInfo.Width / DeviceDisplay.MainDisplayInfo.Density),
                proposedHeight
            );

            Logger.LogWithoutStorage(this,$"QuestionsPopup() initializeComponent questions:{loneWorkingViewModel.Questions.Count} - start");
            InitializeComponent();
            Logger.LogWithoutStorage(this,"QuestionsPopup() initializeComponent - done");

            BindingContext = loneWorkingViewModel;
            this.StorageService = storageService;

            loneWorkingViewModel.QuestionCarousel = QuestionCarousel;
        }

        public async Task Close() {
            var cts = new CancellationTokenSource(TimeSpan.FromSeconds(5));
            await CloseAsync(token: cts.Token);
        }

    }
}
```

And for completeness here's the `Question` model

```
using System;
using MyTeamSafe.Models.Base;
using Newtonsoft.Json;

namespace MyTeamSafe.Models.Entities.Questions
{
    public class Question : BaseBindableObject
    {
        public Question()
        {
        }

        private Id _Id;
        [JsonProperty(PropertyName = "_id")]
        public Id Id{
            get { return _Id; }
            set { SetField(ref _Id, value); }
        }

        private Id _CompanyId;
        [JsonProperty(PropertyName = "companyId")]
        public Id CompanyId{
            get { return _CompanyId; }
            set { SetField(ref _CompanyId, value); }
        }

        private Id _GroupId;
        [JsonProperty(PropertyName = "groupId")]
        public Id GroupId{
            get { return _GroupId; }
            set { SetField(ref _GroupId, value); }
        }

        private string _Title;
        [JsonProperty(PropertyName = "title")]
        public string Title{
            get { return _Title; }
            set { SetField(ref _Title, value); }
        }

        private string _Desc;
        [JsonProperty(PropertyName = "desc")]
        public string Desc{
            get { return _Desc; }
            set { SetField(ref _Desc, value); }
        }

        private string _Style;
        [JsonProperty(PropertyName = "style")]
        public string Style{
            get { return _Style; }
            set { SetField(ref _Style, value); }
        }

        private int _MinRange;
        [JsonProperty(PropertyName = "minRange")]
        public int MinRange{
            get { return _MinRange; }
            set { SetField(ref _MinRange, value); updateValue(); }
        }

        private int _MaxRange;
        [JsonProperty(PropertyName = "maxRange")]
        public int MaxRange{
            get { return _MaxRange; }
            set { SetField(ref _MaxRange, value); updateValue(); }
        }

        private MongoDate _StartDate;
        [JsonProperty(PropertyName = "startDate")]
        public MongoDate StartDate
        {
            get { return _StartDate; }
            set { SetField(ref _StartDate, value); }
        }

        private MongoDate _EndDate;
        [JsonProperty(PropertyName = "endDate")]
        public MongoDate EndDate
        {
            get { return _EndDate; }
            set { SetField(ref _EndDate, value); }
        }

        private bool _Deleted;
        [JsonProperty(PropertyName = "deleted")]
        public bool Deleted{
            get { return _Deleted; }
            set { SetField(ref _Deleted, value); }
        }

        private long _FrequencyMins;
        [JsonProperty(PropertyName = "frequencyMins")]
        public long FrequencyMins{
            get { return _FrequencyMins; }
            set { SetField(ref _FrequencyMins, value); }
        }

        private int _Value;
        [JsonProperty(PropertyName = "value")]
        public int Value
        {
            get { return _Value; }
            set { SetField(ref _Value, value); }
        }

        private bool _CaptureNote;
        [JsonProperty(PropertyName = "captureNote")]
        public bool CaptureNote{
            get { return _CaptureNote; }
            set { SetField(ref _CaptureNote, value); }
        }

        private string _Note;
        [JsonProperty(PropertyName = "note")]
        public string Note
        {
            get { return _Note; }
            set { SetField(ref _Note, value); }
        }

        private bool _CaptureValue;
        [JsonIgnore]
        public bool CaptureValue
        {
            get { return _CaptureValue; }
            set { SetField(ref _CaptureValue, value); }
        }

        private bool _IsAnonymous;
        [JsonProperty(PropertyName = "anonymous")]
        public bool IsAnonymous{
            get { return _IsAnonymous; }
            set { SetField(ref _IsAnonymous, value); }
        } 

        private void updateValue()
        {
            CaptureValue = false;
            if (Value == 0)
            {
                if (MinRange != 0 && MaxRange != 0)
                {
                    // Set it in the middle
                    Value = MaxRange / 2;
                    CaptureValue = true;
                }
            }

            
        }

    }
}
```

### Version with bug

9.0.0 GA

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 18.2 (22C5142a)

### Did you find any workaround?

Not yet!

### Relevant log output

```shell
[0:] MTS 2024-11-27T16:56:26Z UI 1 - QuestionsPopup - QuestionsPopup() initializeComponent questions:2 - start

[0:] MTS 2024-11-27T16:56:26Z UI 1 - QuestionsPopup - QuestionsPopup() initializeComponent - done

2024-11-27 16:56:26.374 MyTeamSafeMaui[4352:1603682] REGISTER CELL ID: Microsoft.Maui.Controls.TemplatedCell2.Vertical.104

.
.

2024-11-27 16:56:52.530 MyTeamSafeMaui[4352:1603682] Unhandled managed exception: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index') (System.ArgumentOutOfRangeException)

   at System.Collections.Generic.List`1[[MyTeamSafe.Models.Entities.Questions.Question, MyTeamSafeMaui, Version=3.1.9.0, Culture=neutral, PublicKeyToken=null]].get_Item(Int32 index)

   at System.Collections.ObjectModel.Collection`1[[MyTeamSafe.Models.Entities.Questions.Question, MyTeamSafeMaui, Version=3.1.9.0, Culture=neutral, PublicKeyToken=null]].System.Collections.IList.get_Item(Int32 index)

   at Microsoft.Maui.Controls.Handlers.Items.ObservableItemsSource.ElementAt(Int32 index)

   at Microsoft.Maui.Controls.Handlers.Items.ObservableItemsSource.get_Item(Int32 index)

   at Microsoft.Maui.Controls.Handlers.Items.ObservableItemsSource.get_Item(NSIndexPath indexPath)

   at Microsoft.Maui.Controls.Handlers.Items2.ItemsViewController2`1[[Microsoft.Maui.Controls.CarouselView, Microsoft.Mau

i.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].DetermineCellReuseId(NSIndexPath indexPath)

   at Microsoft.Maui.Controls.Handlers.Items2.CarouselViewController2.DetermineCellReuseId(NSIndexPath indexPath)

   at Microsoft.Maui.Controls.Handlers.Items2.ItemsViewController2`1[[Microsoft.Maui.Controls.CarouselView, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].GetCell(UICollectionView collectionView, NSIndexPath indexPath)

   at Microsoft.Maui.Controls.Handlers.Items2.CarouselViewController2.GetCell(UICollectionView collectionView, NSIndexPath indexPath)

   at Microsoft.Maui.Controls.Handlers.Items2.CarouselViewController2.__Registrar_Callbacks__.callback_239_Microsoft_Maui_Controls_Handlers_Items2_CarouselViewController2_GetCell(IntPtr pobj, IntPtr sel, IntPtr p0, IntPtr p1, IntPtr* exception_gchandle)

--- End of stack trace from previous location ---

   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr de

legateClassName) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 61

   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 96

   at MyTeamSafe.Program.Main(String[] args) in /Users/rob/GitHub/hillingar-myteamsafe-appv2/app/Platforms/iOS/Program.cs:line 13



=================================================================

    Native Crash Reporting

=================================================================

Got a SIGABRT while executing native code. This usually indicates

a fatal error in the mono runtime or one of the native libraries

used by your application.

=================================================================



=================================================================

    Native stacktrace:

=================================================================

    0x103f14c38 - /private/var/containers/Bundle/Application/4CDC0835-0A8D-4F95-A322-4A8680443D30/MyTeamSafeMaui.app/MyTeamSafeMaui : mono_dump_native_crash_info

    0x103eff214 - /private/var/containers/Bundle/Application/4CDC0835-0A8D-4F95-A322-4A8680443D30/MyTeamSafeMaui.app/MyTeamSafeMaui : mono_handle_native_crash

    0x1040495e4 - /private/var/containers/Bundle/Application/4CDC0835-0A8D-4F95-A322-4A8680443D30/MyTeamSafeMaui.app/MyTeamSafeMaui : sigabrt_signal_handler.cold.1

    0x103f1454c - /private/var/containers/Bundle/Application/4CDC0835-0A8D-4F95-A322

-4A8680443D30/MyTeamSafeMaui.app/MyTeamSafeMaui : mono_runtime_setup_stat_profiler

    0x21440fca8 - /usr/lib/system/libsystem_platform.dylib : <redacted>

    0x2144bf59c - /usr/lib/system/libsystem_pthread.dylib : pthread_kill

    0x1916ebb08 - /usr/lib/system/libsystem_c.dylib : abort

    0x103cebdc8 - /private/var/containers/Bundle/Application/4CDC0835-0A8D-4F95-A322-4A8680443D30/MyTeamSafeMaui.app/MyTeamSafeMaui : xamarin_find_protocol_wrapper_type

    0x103e47570 - /private/var/containers/Bundle/Application/4CDC0835-0A8D-4F95-A322-4A8680443D30/MyTeamSafeMaui.app/MyTeamSafeMaui : mono_invoke_unhandled_exception_hook

    0x103ee97ec - /private/var/containers/Bundle/Application/4CDC0835-0A8D-4F95-A322-4A8680443D30/MyTeamSafeMaui.app/MyTeamSafeMaui : mono_jit_exec

    0x103cff22c - /private/var/containers/Bundle/Application/4CDC0835-0A8D-4F95-A322-4A8680443D30/MyTeamSafeMaui.app/MyTeamSafeMaui : xamarin_main

    0x103f5d360 - /private/var/containers/Bundle/Application/4CDC0835-0A8D-4F95-A322-4A8680443D30/MyTeamSafeMaui.app/MyTeamSafeMaui : main

    0x1afb1ade8 - /usr/lib/dyld : <redacted>



=================================================================

    Basic Fault Address Reporting

=================================================================

Memory around native instruction pointer (0x1daec52d4):0x1daec52c4 ff 0f 5f d6 c0 03 5f d6 10 29 80 d2 01 10 00 d4 .._..._..)......

0x1daec52d4 03 01 00 54 7f 23 03 d5 fd 7b bf a9 fd 03 00 91 ...T.#...{......

0x1daec52e4

 31 ec ff 97 bf 03 00 91 fd 7b c1 a8 ff 0f 5f d6 1........{...._.

0x1daec52f4 c0 03 5f d6 10 27 80 d2 01 10 00 d4 03 01 00 54 .._..'.........T



=================================================================

    Managed Stacktrace:

=================================================================

=================================================================

Stopping iOS process...

iOS Process was stopped.
```

**Comment by RobbiewOnline** [comment]
So far I've been able to rule out elements within the CarouselView as it's now reduced to only this and still crashes

```
<?xml version="1.0" encoding="utf-8" ?>
<toolkit:Popup
    xmlns:toolkit="http://schemas.microsoft.com/dotnet/2022/maui/toolkit"
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:local="clr-namespace:MyTeamSafe"
    xmlns:converters="clr-namespace:MyTeamSafe.Converters" 
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    x:Class="MyTeamSafe.Views.QuestionsPopup"
    xmlns:controls="clr-namespace:MyTeamSafe.Controls"
    xmlns:vm="clr-namespace:MyTeamSafe.ViewModels"
    xmlns:sliders="clr-namespace:Syncfusion.Maui.Sliders;assembly=Syncfusion.Maui.Sliders"
    Color="White"
    CanBeDismissedByTappingOutsideOfPopup="false">

        <CarouselView Grid.Row="0" 
            x:Name="QuestionCarousel" ItemsSource="{Binding Questions}" Loop="False" 
                      HorizontalScrollBarVisibility="Never" 
                      IsSwipeEnabled="true"
                      x:DataType="vm:LoneWorkingViewModel">
            <CarouselView.ItemTemplate>
                <DataTemplate>
                    <Label Text="HELLO WORLD"/>
                </DataTemplate>
            </CarouselView.ItemTemplate>

        </CarouselView>
</toolkit:Popup>
```

However changing the LoneWorkingViewModel property

```
        private RangeObservableCollection<Question> _Questions = new RangeObservableCollection<Question>();
        public RangeObservableCollection<Question> Questions
        {
            get { return _Questions; }
            set { SetField(ref _Questions, value); }
        }
```

To this works...

```
        private List<Question> _Questions = new List<Question>();
        public List<Question> Questions
        {
            get { return _Questions; }
            set { SetField(ref _Questions, value); }
        }
```

Where RangeObservableCollection is

```
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Text;
using Microsoft.Maui.Controls; // Namespace for BindingBase
using Microsoft.Maui.ApplicationModel;
using System.Collections; // Add this using directive

namespace MyTeamSafe.Models.Base
{
    /// <summary>
    /// A thread-safe observable collection that supports ranged additions.
    /// </summary>
    public class RangeObservableCollection<T> : ObservableCollection<T>
    {
        private readonly object _syncRoot = new object();
        private bool _suppressNotification = false;

        public RangeObservableCollection()
        {
            // Enable collection synchronization for thread safety
            BindingBase.EnableCollectionSynchronization(this, _syncRoot, ObservableCollectionCallback);
        }

        private void ObservableCollectionCallback(IEnumerable collection, object context, Action accessMethod, bool writeAccess)
        {
            lock (context)
            {
                accessMethod?.Invoke();
            }
        }

        protected override void OnCollectionChanged(NotifyCollectionChangedEventArgs e)
        {
            if (!_suppressNotification)
            {
                MainThread.BeginInvokeOnMainThread(() =>
                {
                    base.OnCollectionChanged(e);
                });
            }
        }

        // Override the Clear method so that it's also threadsafe & safe for concurrency
        protected override void ClearItems()
        {
            lock (_syncRoot)
            {
                base.ClearItems();
            }

            MainThread.BeginInvokeOnMainThread(() =>
            {
                OnCollectionChanged(new NotifyCollectionChangedEventArgs(NotifyCollectionChangedAction.Reset));
            });
        }

        public void AddRange(IEnumerable<T> items, bool clearFirst = false)
        {
            if (items == null)
                throw new ArgumentNullException(nameof(items));

            lock (_syncRoot)
            {
                if (clearFirst) {
                    Clear();
                }

                _suppressNotification = true;
                foreach (var item in items)
                {
                    base.Add(item);
                }
                _suppressNotification = false;
            }

            // Raise a single reset notification on the UI thread
            MainThread.BeginInvokeOnMainThread(() =>
            {
                OnCollectionChanged(new NotifyCollectionChangedEventArgs(NotifyCollectionChangedAction.Reset));
            });
        }

        public void FireCollectionChanged()
        {
            MainThread.BeginInvokeOnMainThread(() =>
            {
                OnCollectionChanged(new NotifyCollectionChangedEventArgs(NotifyCollectionChangedAction.Reset));
            });
        }

        public override string ToString()
        {
            lock (_syncRoot)
            {
                StringBuilder sb = new StringBuilder();
                sb.Append("[RangeObservableCollection");

                foreach (var item in Items)
                {
                    sb.Append(item.ToString());
                }

                sb.Append("]");
                return sb.ToString();
            }
        }
    }
}

```

Which hasn't changed really since the Xamarin.Forms days, but I wanted to update the ticket as I can probably work around this.

**Comment by arosanti** [comment]
I think the issue is accessing the last item in the observable collection is causing the crash. I am having the same issue and my collection has 6-7 object and it only crashes once I swipe to the final object.

**Comment by RobbiewOnline** [comment]
> I think the issue is accessing the last item in the observable collection is causing the crash.

Ah, interesting observation.

What sort of list are you using to back the data source for the carousel?

I ask because now I've switched to a List rather than my RangeObservableList it's working without issue.

I hate moving away from my own implementation that has been working for 5+ years, but in this case it was trivial to change, but nervous if you're still seeing the crash with List or similar.

**Comment by arosanti** [comment]
> > I think the issue is accessing the last item in the observable collection is causing the crash.
> 
> Ah, interesting observation.
> 
> What sort of list are you using to back the data source for the carousel?
> 
> I ask because now I've switched to a List rather than my RangeObservableList it's working without issue.
> 
> I hate moving away from my own implementation that has been working for 5+ years, but in this case it was trivial to change, but nervous if you're still seeing the crash with List or similar.

We're using a basic ObservableCollection. I tested adding an extra object to the end of the collection and when I swipped to the object that was crashing this time it worked fine and the new extra object I added crashed once I swiped to it so it's definitely only crashing on the last indexed object of an ObservableCollection.

It is also with the new handler for the carousel view. I switched back to the old handler and had no issue.

**Comment by ninachen03** [comment]
Could you provide a sample project for us to investigate it further?
Looking forward to your reply!

**Comment by arosanti** [comment]
I believe this is the same issue and looks like its getting fixed. Can someone verify? https://github.com/dotnet/maui/issues/26863

**Comment by mattleibow** [comment]
@arosanti looks to be the same. I'll close this as a duplicate for now as that has a repro sample attached as well as the PR.

**Comment by mattleibow** [comment]
Duplicate of https://github.com/dotnet/maui/issues/26863

**Comment by mattleibow** [comment]
If someone feels this is not a duplicate, feel free to reopen!
