### ISSUE TITLE
NavigationPage navigation on Android without Shell yields java.lang.IllegalArgumentException: No destination with ID 2 is on the NavController's back stack. The current destination is Destination(0x1) class=crc6452ffdc5b34af3a0f.NavigationViewFragment

### ISSUE THREAD

**Issue by TwoRedCells** [dotnet/maui#26375]
### Description

I discovered this because an app I'm developing is logging first-chance exceptions and every time I popped a page from the navigation stack I would get a long exception with call stack in the output window.

```
[0:] Java.Lang.IllegalArgumentException: No destination with ID 2 is on the NavController's back stack. The current destination is Destination(0x1) class=crc6452ffdc5b34af3a0f.NavigationViewFragment

  --- End of managed Java.Lang.IllegalArgumentException stack trace ---
java.lang.IllegalArgumentException: No destination with ID 2 is on the NavController's back stack. The current destination is Destination(0x1) class=crc6452ffdc5b34af3a0f.NavigationViewFragment
	at androidx.navigation.NavController.getBackStackEntry(NavController.kt:2411)
	at crc6488302ad6e9e4df1a.MauiAppCompatActivity.n_onBackPressed(Native Method)
	at crc6488302ad6e9e4df1a.MauiAppCompatActivity.onBackPressed(MauiAppCompatActivity.java:73)
	at android.app.Activity.onKeyUp(Activity.java:3879)
	at android.view.KeyEvent.dispatch(KeyEvent.java:2886)
	at android.app.Activity.dispatchKeyEvent(Activity.java:4204)
	at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.java:126)
	at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:86)
	at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:144)
	at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:604)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:60)
	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:3413)
	at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:404)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:6523)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6384)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5862)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5919)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5885)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6050)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5893)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6107)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5866)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5919)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5885)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5893)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5866)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5919)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5885)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6083)
	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:6245)
	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:3158)
	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2722)
	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2713)
	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:3135)
	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:154)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loopOnce(Looper.java:161)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7881)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:568)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

  --- End of managed Java.Lang.IllegalArgumentException stack trace ---
java.lang.IllegalArgumentException: No destination with ID 2 is on the NavController's back stack. The current destination is Destination(0x1) class=crc6452ffdc5b34af3a0f.NavigationViewFragment
	at androidx.navigation.NavController.getBackStackEntry(NavController.kt:2411)
	at crc6488302ad6e9e4df1a.MauiAppCompatActivity.n_onBackPressed(Native Method)
	at crc6488302ad6e9e4df1a.MauiAppCompatActivity.onBackPressed(MauiAppCompatActivity.java:73)
	at android.app.Activity.onKeyUp(Activity.java:3879)
	at android.view.KeyEvent.dispatch(KeyEvent.java:2886)
	at android.app.Activity.dispatchKeyEvent(Activity.java:4204)
	at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.java:126)
	at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:86)
	at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:144)
	at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:604)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:60)
	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:3413)
	at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:404)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:6523)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6384)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5862)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5919)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5885)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6050)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5893)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6107)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5866)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5919)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5885)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5893)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5866)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5919)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5885)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6083)
	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:6245)
	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:3158)
	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2722)
	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2713)
	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:3135)
	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:154)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loopOnce(Looper.java:161)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7881)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:568)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
```

It took me a while to realize this was in fact a first-chance exception, not my app crashing. Nonetheless, without understanding MAUI internals, this appears to be an exception that should be caught; or better, the root cause resolved.

### Steps to Reproduce

1. Create a new MAUI app in 8.0 or 9.0 and target Android.
2. Delete `AppShell.xaml` and `AppShell.xaml.cs`.
3. Create a page to navigate to e.g. `SecondPage`.
4. Add a button on `MainPage` with a `Clicked` event that executes `await Navigation.PushAsync(new SecondPage());`
5. Update `App.xaml.cs`:

```        public App()
        {
            InitializeComponent();
            AppDomain.CurrentDomain.FirstChanceException += CurrentDomain_FirstChanceException;
            AppDomain.CurrentDomain.UnhandledException += CurrentDomain_UnhandledException;
            MainPage = new NavigationPage(new MainPage());

        }

        private void CurrentDomain_UnhandledException(object sender, UnhandledExceptionEventArgs e)
        {
            throw new NotImplementedException();
        }

        private async void CurrentDomain_FirstChanceException(object sender, System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs e)
        {
            Debug.WriteLine(e.Exception.ToString());
        }
    }
```
6. Execute the app. Click the button to go to `SecondPage`.
7. Tap the `Back` button

A call stack like above will appear in the Output pane.

### Link to public reproduction project repository

https://github.com/TwoRedCells/BrokenNavigationDemo

### Version with bug

9.0.0 GA

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Affected platforms

Android

### Did you find any workaround?

Ignore the exception.

### Relevant log output

```shell

```

**Comment by Zhanglirong-Winnie** [comment]
This issue has been verified using Visual Studio 17.13 Preview 1 (9.0.10 & 9.0.0 & 8.0.100 ). Not repro this issue on Android platform. I used the sample project you provided, and created a new project myself to reproduce according to your steps. The problem did not recur the first time or several times afterwards.
