### ISSUE TITLE
Blazor Hybrid and Web app with Identity

### ISSUE THREAD

**Issue by enrico-rossini-tracebit** [dotnet/maui#26407]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I like to create applications using razor Hybrid and Web app template. I can't understand why it is not possible to have in the wizard for the creation, the option to select if the authentication is required. If it is required with the *Individual Authentication*, the pages will be added automatically. This is working for the Blazor Web App. 

Why is this option removed for this kind of apps? Is there a reason? If I want to copy from another Blazor project the pages generated with the scaffolding process, is it OK? Is there any reason because I shouldn't do that?

### Describe the solution you'd like

I'd like to have an option to add the *Individual Authentication* like in the other Blazor or ASP.NET Core templates.

**Comment by jfversluis** [comment]
@Eilon @BethMassi ?

**Comment by BethMassi** [comment]
Hi @enrico-rossini-tracebit thanks for the feature suggestion! We definitely want to address this. The new .NET MAUI Blazor Hybrid and Web template for .NET 9 only addresses the client side of the application and sets up the projects for sharing UI. We're working on documentation and guidance and we'll look at how we can incorporate this into a future release.

**Comment by erossini** [comment]
Thank you so much @BethMassi. If I add the Identity area from another Blazor application, could it be a problem? Is there any potential issues? What do you recommend?

Thank you in advance,
Enrico

**Comment by BethMassi** [comment]
Currently the Identity UI that is generated for a Blazor Web app is specific to the server and can't easily be shared on the client. You can expose the identity endpoints as Web APIs and call them from the MAUI client though. General guidance is here: https://learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/security/?view=aspnetcore-8.0&pivots=maui 

Perhaps @halter73 has a recommendation?

**Comment by BethMassi** [comment]
@erossini here's a sample I created for this scenario. Can you check it out and let me know if it works for you? 
https://github.com/BethMassi/MauiHybridAuth/

**Comment by danroth27** [comment]
Related user request: https://github.com/dotnet/aspnetcore/issues/40764#issuecomment-1507085426

**Comment by danroth27** [comment]
Related comment from @ascott18:

https://github.com/dotnet/aspnetcore/issues/40764#issuecomment-1781629719

> Blazor Hybrid (MAUI) is basically not supported. It works if you write your own AuthenticationStateProvider/IRemoteAuthenticationService<>/IAccessTokenProvider implementation, but that takes quite a bit of work and also feels "dirty" to be using classes and components namespaced in Microsoft.AspNetCore.Components.WebAssembly in a non-WebAssembly app.

**Comment by erossini** [comment]
Hi @BethMassi ! Sorry for the radio silence; I was working on a different project. I'm restarting the project with Blazor hybrid again. Happy to check the project you linked.

**Comment by BethMassi** [comment]
@erossini we also published official docs and sample here: https://learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/security/maui-blazor-web-identity

**Comment by o-leary** [comment]
> [@erossini](https://github.com/erossini) we also published official docs and sample here: https://learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/security/maui-blazor-web-identity

This is an awesomely helpful sample project! Apologies if I need to create a new issue, but I'm attempting to use it with Entra ID. I get as far as redirecting back to the web app and get an error. Are there additional steps I've missed? Do I need to add database records for a new provider or create some additional handler class? Thank you!

Project file
`<PackageReference Include="Microsoft.AspNetCore.Authentication.MicrosoftAccount" Version="9.0.5" />`

Program.cs
`builder.Services.AddAuthentication(options =>
{
    // Ensure that unauthenticated clients redirect to the login page rather than receive a 401 by default.
    options.DefaultChallengeScheme = IdentityConstants.ApplicationScheme;
}).AddMicrosoftAccount(microsoftOptions =>
{
    microsoftOptions.ClientId = builder.Configuration["Authentication:Microsoft:ClientId"];
    microsoftOptions.ClientSecret = builder.Configuration["Authentication:Microsoft:ClientSecret"];
    microsoftOptions.AuthorizationEndpoint = $"https://login.microsoftonline.com/{microsoftTenantId}/oauth2/authorize";
    microsoftOptions.TokenEndpoint = $"https://login.microsoftonline.com/{microsoftTenantId}/oauth2/v2.0/token";
    microsoftOptions.CallbackPath = "/signin-oidc";
});`

Currently the Microsoft option appears and does redirect, but registering an External login for a user or logging in via "Microsoft" redirects to a blank page and outputs the following error:

`info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (0ms) [Parameters=[@__p_0='?' (Size = 36)], CommandType='Text', CommandTimeout='30']
      SELECT "a"."Id", "a"."AccessFailedCount", "a"."ConcurrencyStamp", "a"."Email", "a"."EmailConfirmed", "a"."LockoutEnabled", "a"."LockoutEnd", "a"."NormalizedEmail", "a"."NormalizedUserName", "a"."PasswordHash", "a"."PhoneNumber", "a"."PhoneNumberConfirmed", "a"."SecurityStamp", "a"."TwoFactorEnabled", "a"."UserName"
      FROM "AspNetUsers" AS "a"
      WHERE "a"."Id" = @__p_0
      LIMIT 1
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (0ms) [Parameters=[@__userId_0='?' (Size = 36)], CommandType='Text', CommandTimeout='30']
      SELECT "a"."LoginProvider", "a"."ProviderKey", "a"."ProviderDisplayName"
      FROM "AspNetUserLogins" AS "a"
      WHERE "a"."UserId" = @__userId_0
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.InvalidOperationException: StatusCode cannot be set because the response has already started.
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ThrowResponseAlreadyStartedException(String value)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.set_StatusCode(Int32 value)
         at Microsoft.AspNetCore.Http.DefaultHttpResponse.Redirect(String location, Boolean permanent)
         at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
warn: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[2]
      The response has already started, the error page middleware will not be executed.
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HNCJJLHE8S85", Request id "0HNCJJLHE8S85:00000003": An unhandled exception was thrown by the application.
      System.InvalidOperationException: StatusCode cannot be set because the response has already started.
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ThrowResponseAlreadyStartedException(String value)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.set_StatusCode(Int32 value)
         at Microsoft.AspNetCore.Http.DefaultHttpResponse.Redirect(String location, Boolean permanent)
         at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
         at Microsoft.WebTools.BrowserLink.Net.BrowserLinkMiddleware.InvokeAsync(HttpContext context)
         at Microsoft.AspNetCore.Watch.BrowserRefresh.BrowserRefreshMiddleware.InvokeAsync(HttpContext context)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)`

**Comment by o-leary** [comment]
> [@erossini](https://github.com/erossini) we also published official docs and sample here: https://learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/security/maui-blazor-web-identity

Awesome sample, very helpful! Just noting for fellow travellers there is some mixed documentation for Entra Id as an external provider and using .AddMicrosoftIdentityWebApp instead of .AddMicrosoftAccount will solve all your problems, see: 
https://github.com/dotnet/aspnetcore/issues/61017#issuecomment-2737485691

And example in same thread:
https://github.com/dotnet/aspnetcore/issues/61017#issuecomment-2777937373

**Comment by BethMassi** [comment]
@mattleibow are we good with the .NET 10 version of this sample?
