### ISSUE TITLE
Windows: Embedded Fonts doesn't work in Unpackaged apps

### ISSUE THREAD

**Issue by dotMorten** [dotnet/maui#26441]
### Description

If you add register font using 
`.ConfigureFonts(fonts => fonts.AddEmbeddedResourceFont(typeof(MyAssembly).Assembly, "myfont.ttf", "myfont");`
fonts will not work if the app is unpackaged. The output window is full of warnings about it, and nothing renders on the screen.

Most likely related to @mattleibow's PR: #22646 which attempted to fix this, and likely a similar fix is needed for embedded fonts.

I've observed this behavior with both .NET 8 and .NET 9, but with unpackaged now being the default it is A LOT more visible

### Steps to Reproduce

1. Add a font as embedded resource
2. Register the font in startup using `AddEmbeddedResourceFont`
3. Reference the font in `FontImageSource` in the xaml.
4. Run the app packaged and observe the font works.
5. Repeat for unpackaged and see that nothing renders.

### Version with bug

9.0.12 SR1.2

### Is this a regression from previous behavior?

No, this is something new

### Affected platforms

Windows

### Did you find any workaround?

No

### Relevant log output

```shell
Exception thrown: 'System.InvalidOperationException' in WinRT.Runtime.dll
Microsoft.Maui.FontRegistrar: Warning: Unable to load font 'myfont'.

System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|38_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Windows.Storage.IApplicationDataStaticsMethods.get_Current(IObjectReference _obj)
   at Windows.Storage.ApplicationData.get_Current()
   at Microsoft.Maui.EmbeddedFontLoader.LoadFont(EmbeddedFont font)
   at Microsoft.Maui.FontRegistrar.LoadEmbeddedFont(String cacheKey, String filename, String alias, Stream stream)
   at Microsoft.Maui.FontRegistrar.GetFont(String font)
Exception thrown: 'System.InvalidOperationException' in WinRT.Runtime.dll
Exception thrown: 'System.InvalidOperationException' in System.Private.Uri.dll
Microsoft.Maui.FontManager: Error: Error loading font 'Assets/Fonts/myfont.ttf'.

System.InvalidOperationException: This operation is not supported for a relative URI.
   at System.Uri.get_AbsolutePath()
   at Microsoft.Maui.FontManager.FindFontFamilyName(String fontFile)
Exception thrown: 'System.InvalidOperationException' in System.Private.Uri.dll
Microsoft.Maui.FontManager: Error: Error loading font 'Assets/Fonts/myfont.otf'.

System.InvalidOperationException: This operation is not supported for a relative URI.
   at System.Uri.get_AbsolutePath()
   at Microsoft.Maui.FontManager.FindFontFamilyName(String fontFile)
Exception thrown: 'System.InvalidOperationException' in System.Private.Uri.dll
Microsoft.Maui.FontImageSourceService: Warning: Unable to generate font image ''.

System.InvalidOperationException: This operation is not supported for a relative URI.
   at System.Uri.get_AbsolutePath()
   at Microsoft.Maui.FontImageSourceService.GetFontSource(IFontImageSource imageSource)
   at Microsoft.Maui.FontImageSourceService.RenderImageSource(IFontImageSource imageSource, Single scale)
   at Microsoft.Maui.FontImageSourceService.GetImageSourceAsync(IFontImageSource imageSource, Single scale, CancellationToken cancellationToken)
Exception thrown: 'System.InvalidOperationException' in Microsoft.Maui.dll
Exception thrown: 'System.InvalidOperationException' in System.Private.Uri.dll
Microsoft.Maui.FontImageSourceService: Warning: Unable to generate font image ''.

System.InvalidOperationException: This operation is not supported for a relative URI.
   at System.Uri.get_AbsolutePath()
   at Microsoft.Maui.FontImageSourceService.GetFontSource(IFontImageSource imageSource)
   at Microsoft.Maui.FontImageSourceService.RenderImageSource(IFontImageSource imageSource, Single scale)
   at Microsoft.Maui.FontImageSourceService.GetImageSourceAsync(IFontImageSource imageSource, Single scale, CancellationToken cancellationToken)
Exception thrown: 'System.InvalidOperationException' in Microsoft.Maui.dll
Exception thrown: 'System.InvalidOperationException' in System.Private.Uri.dll
Microsoft.Maui.FontImageSourceService: Warning: Unable to generate font image ''.

System.InvalidOperationException: This operation is not supported for a relative URI.
   at System.Uri.get_AbsolutePath()
   at Microsoft.Maui.FontImageSourceService.GetFontSource(IFontImageSource imageSource)
   at Microsoft.Maui.FontImageSourceService.RenderImageSource(IFontImageSource imageSource, Single scale)
   at Microsoft.Maui.FontImageSourceService.GetImageSourceAsync(IFontImageSource imageSource, Single scale, CancellationToken cancellationToken)
Exception thrown: 'System.InvalidOperationException' in Microsoft.Maui.dll
Exception thrown: 'System.InvalidOperationException' in System.Private.Uri.dll
Microsoft.Maui.FontImageSourceService: Warning: Unable to generate font image ''.

System.InvalidOperationException: This operation is not supported for a relative URI.
   at System.Uri.get_AbsolutePath()
   at Microsoft.Maui.FontImageSourceService.GetFontSource(IFontImageSource imageSource)
   at Microsoft.Maui.FontImageSourceService.RenderImageSource(IFontImageSource imageSource, Single scale)
   at Microsoft.Maui.FontImageSourceService.GetImageSourceAsync(IFontImageSource imageSource, Single scale, CancellationToken cancellationToken)
Exception thrown: 'System.InvalidOperationException' in Microsoft.Maui.dll
```

**Comment by mattleibow** [comment]
lol past me knew this was a thing (and a winui bug) 

![Image](https://github.com/user-attachments/assets/e655f76c-575f-43d1-a5e8-184b8936c38a)

**Comment by LanceMcCarthy** [comment]
Thank you!
