### ISSUE TITLE
Issue on Windows - Exception thrown: 'System.NullReferenceException' in Microsoft.Maui.Controls.dll

### ISSUE THREAD

**Issue by Auto72** [dotnet/maui#26498]
### Description

I converted a .NET MAUI project from .NET 8.0 to .NET 9.0 and I have an issue on Windows now.

I reproduced the issue on this repository:
https://github.com/Auto72/MauiApp9

Run the App on Windows.

Navigate to MauiPage1 by clicking the Button on the first page. 
Navigate back. 
Navigate again to MauiPage1 by clicking the Button on the first page. 
Click the Clear button.

You get the error:
Exception thrown: 'System.NullReferenceException' in Microsoft.Maui.Controls.dll Object reference not set to an instance of an object.

If you go over the variable, you can see it is not null. The try/catch block doesn't catch this error.

In Android and iOS it works fine.
In .NET 8.0 it used to work fine in Android, iOS and Windows.

![Image](https://github.com/user-attachments/assets/b30923a0-b8e4-447a-9852-5b5d37a3720b)

### Steps to Reproduce

Run the App on Windows.

Navigate to MauiPage1 by clicking the Button on the first page. 
Navigate back. 
Navigate again to MauiPage1 by clicking the Button on the first page. 
Click the Clear button.

You get the error:
Exception thrown: 'System.NullReferenceException' in Microsoft.Maui.Controls.dll Object reference not set to an instance of an object.

### Link to public reproduction project repository

https://github.com/Auto72/MauiApp9

### Version with bug

9.0.12 SR1.2

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.100 SR10

### Affected platforms

Windows

### Affected platform versions

Windows 11

### Did you find any workaround?

No workaround found.

### Relevant log output

```shell
Exception thrown: 'System.NullReferenceException' in Microsoft.Maui.Controls.dll
Object reference not set to an instance of an object.
```

**Comment by jfversluis** [comment]
Full stack trace:

```
   at Microsoft.Maui.Controls.Handlers.Compatibility.ListViewRenderer.ClearSizeEstimate()
   at Microsoft.Maui.Controls.Handlers.Compatibility.ListViewRenderer.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at Microsoft.Maui.Controls.Internals.TemplatedItemsList`2.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at Microsoft.Maui.Controls.Internals.TemplatedItemsList`2.OnProxyCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at Microsoft.Maui.Controls.ListProxy.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at Microsoft.Maui.Controls.ListProxy.<>c__DisplayClass36_0.<OnCollectionChanged>b__0()
   at Microsoft.Maui.Controls.DispatcherExtensions.DispatchIfRequired(IDispatcher dispatcher, Action action)
   at Microsoft.Maui.Controls.ListProxy.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at Microsoft.Maui.Controls.WeakNotifyCollectionChangedProxy.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at MauiApp1.MauiPage1.ButtonClear_Clicked(Object sender, EventArgs e) in C:\Users\joverslu\Desktop\MauiApp9-master\MauiApp1\MauiPage1.xaml.cs:line 38
```

**Comment by ninachen03** [comment]
This issue has been verified using Visual Studio 17.13.0 Preview 2.0 (9.0.21 ). Can repro on Windows platform.  not repro on  8.0.100
![Image](https://github.com/user-attachments/assets/dde54daf-9370-4fb2-a7d1-e9e33a9849d8)

**Comment by Jean-RobertLaffineur** [comment]
I've got the same issue when moving a page's content from one Window to another.
In your reproduction project, changing:
```
_mauiPage1 ??= new MauiPage1();
```
into:
```
_mauiPage1 = new MauiPage1();
```

...gets rid of the exception.

**Comment by Jean-RobertLaffineur** [comment]
@Auto72,

I got your point; I was only trying to give some advise on finding the root cause of the issue.

I came to the same conclusion: get rid of `ListView` controls in favor of the `CollectionView`.

**Comment by freemstr** [comment]
Workaround if you cant get onto 9.0.50 due to https://github.com/dotnet/maui/issues/28450 or any other .50 regression:
while (ItemsCollection.Any())
{
try
{
ItemsCollection.RemoveAt(0);
}
catch(Exception ex) {
_ = ex;
}
}
