### ISSUE TITLE
BlazorWebView DisposeAsync implementation Disposes the WebView on the wrong thread

### ISSUE THREAD

**Issue by Davidvanluijk** [dotnet/maui#26746]
### Description

We are using BlazorWpfView from a WPF Window. When calling DisposeAsync an exception occurs of an COM object not supporting the cast. There are multiple variations of this issue found by people if I google around a bit, some suggest the thread on which the dispose is being executed is the issue. This seems to be the issue in BlazorWpfView as well: the DisposeAsyncCore implementation of that class first disposes _webviewManager with ConfigureAwait(**false**), after which on a different thread than the UI thread _webview is disposed. If I dispose, from our own code, WebView before disposing the BlazorWebView I do not get the COM exception, but as _webviewManager should be disposed first a lot of other errors occur. WebViewManager is not accessible and I cannot dispose it from our own code, so I can't test any further then this.

```
System.InvalidCastException: Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{4D00C0D1-9434-4EB6-8078-8697A560334F}' failed due to the following error: No such interface supported (0x80004002 (E_NOINTERFACE)).
   at System.StubHelpers.StubHelpers.GetCOMIPFromRCW(Object objSrc, IntPtr pCPCMD, IntPtr& ppTarget, Boolean& pfNeedsRelease)
   at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller.get_CoreWebView2()
   at Microsoft.Web.WebView2.Core.CoreWebView2Controller.get_CoreWebView2()
   at Microsoft.Web.WebView2.Wpf.WebView2Base.Uninitialize(Boolean browserCrashed)
   at Microsoft.Web.WebView2.Wpf.WebView2Base.Dispose()
   at Microsoft.Web.WebView2.Wpf.WebView2.Dispose(Boolean disposing)
   at System.Windows.Interop.HwndHost.Dispose()
   at Microsoft.AspNetCore.Components.WebView.Wpf.BlazorWebView.DisposeAsyncCore()
```

### Steps to Reproduce

The window is created like this (from a viewmodel AsyncRelayCommand handler):
        private async Task Open()
        {
            var window = new MyWindow();
            window.ShowDialog();
            await window.DisposeAsync().ConfigureAwait(true);
        }

```
<Window x:Class="MyWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:wpf="http://schemas.microsoft.com/winfx/2006/xaml/presentation/blazor"
        Width="1280" Height="1024" Left="0" Top="0"
        ResizeMode="NoResize" ShowInTaskbar="True"
        WindowStartupLocation="Manual" WindowStyle="None"
        mc:Ignorable="d" Title="Document management">
    <Grid>
        <wpf:BlazorWebView x:Name="BlazorWebView"/>
    </Grid>
</Window>
```
Code behind:
```
public partial class MyWindow : IAsyncDisposable
{
    public MyWindow ()
    {
        InitializeComponent();

        BlazorWebView.BlazorWebViewInitializing += InitializingWebView;
        BlazorWebView.Services = InstanceContainer.Instance.GetInstance<IServiceProvider>();
        BlazorWebView.RootComponents.Add(new RootComponent
        {
            Selector = "#app",
            ComponentType = typeof(Routes),
            Parameters = new Dictionary<string, object>
            {
                { nameof(Routes.InitialPage), "/InitialPage" },
                { nameof(Routes.CloseHandler), new Action(Close) },
            },
        });
        BlazorWebView.HostPage = "wwwroot/index.html";
    }

    private void InitializingWebView(object sender, BlazorWebViewInitializingEventArgs e)
    {
        var location = Assembly.GetEntryAssembly()!.Location;
        e.BrowserExecutableFolder = Path.Combine(Path.GetDirectoryName(location)!, "WebView2");
    }
    
    public async ValueTask DisposeAsync()
    {
        await BlazorWebView.DisposeAsync().ConfigureAwait(true);
        GC.SuppressFinalize(this);
    }
}
```

### Version with bug

8.0.100 SR10

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Relevant log output

```shell

```

**Comment by javiercn** [comment]
@Davidvanluijk thanks for contacting us.

This change seems to have been introduced https://github.com/dotnet/maui/pull/1864

I do not believe we should be calling `.ConfigureAwait(false)` on this logic unless someone has a **really** good answer for why it is correct.

This is essentially taking the callback out of the UI thread, which it shouldn't.

**Comment by Kebechet** [comment]
why is it postponed till .NET10 and not in patch for NET9 ?

**Comment by ScarletKuro** [comment]
I'm concerned this hasn’t been resolved yet.
`.ConfigureAwait(false)` prevents resuming on the original synchronization context, which means `_webview.Dispose()` may run on a different thread. Since WebView2 is thread-affine, it should be disposed on the same thread it was created on.

**Comment by wgala-tomra** [comment]
I am also facing this issue. 
Given the application is hybrid of many Blazor Views and WPF controls, is there a way to safely Dispose BlazorWebView? We have hybrid application where we have some views in Blazor and some of them still in WPF as we are in transition to full Blazor (takes time).
We instantiate WPF or Blazor views depending on VM type of current ViewModel presented, and also disposing previous one. So basically navigation should strip down previous Blazor View, since it needs to be disposed. We have some connection between View/VM in order to do that, but that's not the point.
Fortunately it seems that DisposeAsyncCore is virtual so it's behavior can be overwritten, although I am not sure if that's safe way as internal fields aren't set to null by such approach (as currently in the implementation of DisposeAsyncCore).

**Comment by ScarletKuro** [comment]
@wgala-tomra you can inherit `BlazorWebView` and override dispose, you will need to use reflection like above. While it fixes the potential problem of disposing on a wrong thread, the real problem is this https://github.com/dotnet/maui/issues/34855
I transition from WPF to Blazor as well, and some views are wpf some are blazor, it's multi window that can open and close and you might get an in flight IPC from Blazor when you closed your blazor WebView and it will go into AppDomain’s `UnhandledException`. See also https://github.com/dotnet/maui/issues/34855?issue=dotnet%7Caspnetcore%7C66255

**Comment by groogiam** [comment]
This just got me as well. I was able to work around it via the reflective private field access.
