### ISSUE TITLE
AddHostObjectToScript does not work in MAUI app (at least for WINDOWS).

### ISSUE THREAD

**Issue by eveselov** [dotnet/maui#26848]
### Description

I am struggling with adding HostObject to jscript for WebView in MAUI app (for WINDOWS). I created a simplest MAUI app from scratch to avoid any special aspects of my own code, It's now the simplest possible:

MainPage.xaml:
```xaml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiApp1.MainPage">

    <ScrollView>
        <VerticalStackLayout
            <WebView
                x:Name="HtmlWebView"
                HeightRequest="500"
                WidthRequest="300" />

            <Button
                x:Name="CounterBtn"
                Text="Click me" 
                Clicked="OnCounterClicked"
                HorizontalOptions="Fill" />
        </VerticalStackLayout>
    </ScrollView>

</ContentPage>
```
MainPage.xaml.cs:
```cs
namespace MauiApp1 {
    public partial class MainPage : ContentPage {
        public MainPage() {
            this.InitializeComponent();
        }

        private void OnCounterClicked(object sender, EventArgs e) {
            this.HtmlWebView.Source = new HtmlWebViewSource {
                Html = "<html><body><h1>Hello!</h1><button onclick='alert(\"Test\"); window.host.HelloWorld()'>Click Me</button></body></html>"
            };
        }
    }
}
```
MauiProgram.cs:
```cs
namespace MauiApp1 {
    public static class MauiProgram {
        public static MauiApp CreateMauiApp() {
            var builder = MauiApp.CreateBuilder();
            builder = builder
                .UseMauiApp<App>();
#if WINDOWS
            builder = builder.ConfigureMauiHandlers(handlers => {
                handlers.AddHandler(typeof(WebView), typeof(MauiApp1.Platforms.Windows.CustomWebViewHandler));
            });
#endif

            return builder.Build();
        }
    }
}
```
JavaScriptHost.cs (in Platforms/Windows):
```cs
using Microsoft.Maui.Handlers;
using Microsoft.UI.Xaml.Controls;
using System.Diagnostics;

namespace MauiApp1.Platforms.Windows {
    public class CustomWebViewHandler : WebViewHandler {
        protected override async void ConnectHandler(WebView2 platformView) {
            base.ConnectHandler(platformView);
            try {
                if (platformView.CoreWebView2 == null) {
                    await platformView.EnsureCoreWebView2Async();
                    if (platformView.CoreWebView2 == null) {
                        Debug.WriteLine("WebView2 initialization failed");
                        return;
                    }
                }
                platformView.CoreWebView2.AddHostObjectToScript("host", new JavaScriptHost());
                Debug.WriteLine("WebView2 initialized");
            } catch (Exception ex) {
                Debug.WriteLine($"WebView2 initialization failed: {ex}");
            }
        }
    }

    public class JavaScriptHost {
        public JavaScriptHost() {
            Debug.WriteLine("JavaScriptHost created");
        }

        public void HelloWorld() {
            Debug.WriteLine("Call from jscript received");
        }
    }
}
```
 Whatever I am trying to do with this, I am having the same SystemError error in this call:

```cs
platformView.CoreWebView2.AddHostObjectToScript("host", new JavaScriptHost());
```
### Steps to Reproduce

1. Create a new MAUI app
2. Replace the content of MainPage.xaml, MainPage.xaml.cs, MauiProgram.cs
3. Add JavaScriptHost.cs under Platforms/Windows
4. Run the app
5. Set breakpoint in JavaScriptHost.cs on platformView.CoreWebView2.AddHostObjectToScript("host", new JavaScriptHost());
6. Click "Click Me" button

Result:  exception thrown from AddHostObjectToScript

### Version with bug

9.0.21 SR2.1

### Is this a regression from previous behavior?

No, this is something new

### Affected platforms

Windows

### Affected platform versions

WINDOWS

### Did you find any workaround?

I have to use "post" from jscript to pass information from WebView to C#

### Relevant log output

```shell

```

**Comment by jfversluis** [comment]
> Result: exception thrown from AddHostObjectToScript

What exception? Do you have some details?

**Comment by ninachen03** [comment]
I want to confirm the exception information. I run it normally, but I can see the following information in the output
WebView2 initialization failed: System.Runtime.InteropServices.COMException (0x8007139F)
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|38_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Microsoft.Web.WebView2.Core.ICoreWebView2Methods.AddHostObjectToScript(IObjectReference _obj, String name, Object rawObject)
   at Microsoft.Web.WebView2.Core.CoreWebView2.AddHostObjectToScript(String name, Object rawObject)
   at MauiApp1.Platforms.Windows.CustomWebViewHandler.ConnectHandler(WebView2 platformView) in C:\Users\v-dongmc\Downloads\MauiApp1\MauiApp1\MauiApp1\Platforms\Windows\JavaScriptHost.cs:line 23
'MauiApp1.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\9.0.0\Microsoft.Win32.Registry.dll'.

**Comment by mattleibow** [comment]
Not saying this isn't a bug, but this is what the HybridWebView was going to do for you. Maybe give that a try.

For the exception, is there any additional details in the exception if you add a breakpoint in the catch block? `COMException` is super vague. But also, as ina and gerald ask, what error are you currently getting @eveselov ?
