### ISSUE TITLE
Crash when CustomControl Property use StaticResource

### ISSUE THREAD

**Issue by albilaga** [dotnet/maui#26881]
### Description

I have some CustomControl like this 
```cs
public class CustomButton : ContentView
{
	//other code
	private ButtonConfiguration? _containedButtonConfiguration;
	public ButtonConfiguration? ButtonConfig
	{
		get => _containedButtonConfiguration;
		set
		{
			_containedButtonConfiguration = value;
			Draw();
		}
	}

	public CustomButton()
	{
		HorizontalOptions = VerticalOptions = LayoutOptions.Start;
	}
}
```

and `ButtonConfiguration` is something like this
```cs
[AcceptEmptyServiceProvider]
public abstract class ButtonConfiguration : IMarkupExtension<ButtonConfiguration>
{
	public abstract ButtonConfiguration BasedOn { set; }

	public abstract View ComposeView();
	public ButtonConfiguration ProvideValue(IServiceProvider serviceProvider)
	{
		return this;
	}

	object IMarkupExtension.ProvideValue(IServiceProvider serviceProvider)
	{
		return ProvideValue(serviceProvider);
	}

	public abstract void ApplyGestureHandler(View parentView, GestureRecognizer customGestureRecognizer);
}
```

and some ButtonConfiguration is like this
```cs
public class IconButtonConfiguration : ButtonConfiguration
{
	public Color? Color { get; set; }
	public string? IconGlyph { get; set; } = string.Empty;
	public double IconSize { get; set; } = 14;
}
```
and when I set style in `App.xaml`
```xml
<ResourceDictionary>
            <system:Double x:Key="LargeIconButtonFontSize">24</system:Double>
            <config:IconButtonConfiguration
                x:Key="DefaultIconButtonConfig"
                IconSize="{StaticResource LargeIconButtonFontSize}"
                SpacingEnabled="True"
                Color="Black" />
        </ResourceDictionary>
```
this will cause crash when in Release (both on Android and iOS). Debug working fine. But if I set like this
```xml
<ResourceDictionary>
            <system:Double x:Key="LargeIconButtonFontSize">24</system:Double>
            <config:IconButtonConfiguration
                x:Key="DefaultIconButtonConfig"
                IconSize="18"
                SpacingEnabled="True"
                Color="Black" />
        </ResourceDictionary>
```
it is working fine in Release. Not really sure what is the cause of this

### Steps to Reproduce

1. Clone https://github.com/albilaga/mauitest
2. Run android or iOS project in Release. This will crash

### Link to public reproduction project repository

https://github.com/albilaga/mauitest

### Version with bug

9.0.21 SR2.1

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.100 SR10

### Affected platforms

iOS, Android

### Affected platform versions

iOS and Android

### Did you find any workaround?

Hard code the value instead of using StaticResource but this mean then when refactoring need to be careful

### Relevant log output

```shell

```

**Comment by ninachen03** [comment]
I want to confirm the error message with you. do you have any error after crash, below is mine.
<img width="682" alt="Image" src="https://github.com/user-attachments/assets/50dc580c-355e-44c5-83e2-b5ce2e778d88" />

**Comment by albilaga** [comment]
this is the stacktrace I got
```
mauitest.iOS[46554:892704] You've implemented -[<UIApplicationDelegate> application:performFetchWithCompletionHandler:], but you still need to add "fetch" to the list of your supported UIBackgroundModes in your Info.plist.
mauitest.iOS[46554:892704] *** Terminating app due to uncaught exception 'System.ExecutionEngineException', reason: 'Attempting to JIT compile method 'void mauitest.App:InitializeComponent ()' while running in aot-only mode. See https://learn.microsoft.com/xamarin/ios/internals/limitations for more information.
 (System.ExecutionEngineException)
   at mauitest.App..ctor()
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Constructor(Object obj, IntPtr* args)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.E
*** Terminating app due to uncaught exception 'System.ExecutionEngineException', reason: 'Attempting to JIT compile method 'void mauitest.App:InitializeComponent ()' while running in aot-only mode. See https://learn.microsoft.com/xamarin/ios/internals/limitations for more information.
 (System.ExecutionEngineException)
   at mauitest.App..ctor()
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Constructor(Object obj, IntPtr* args)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=9.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSiteMain(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=9.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSite(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
   at System.Collections.Concurrent.ConcurrentDictionary`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceIdentifier, Microsoft.Extensions.DependencyInjection, Version=9.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[Microsoft.Extensions.DependencyInjection.ServiceProvider.ServiceAccessor, Microsoft.Extensions.DependencyInjection, Version=9.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].GetOrAdd(ServiceIdentifier key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Maui.MauiContext.WrappedServiceProvider.GetService(Type serviceType)
   at Microsoft.Maui.MauiContext.WrappedServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[IApplication](IServiceProvider provider)
   at Microsoft.Maui.MauiUIApplicationDelegate.FinishedLaunching(UIApplication application, NSDictionary launchOptions)
   at mauitest.iOS.AppDelegate.FinishedLaunching(UIApplication app, NSDictionary options)
'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001804b910c __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x0000000180092da8 objc_exception_throw + 72
	2   libxamarin-dotnet.dylib             0x000000011a43ec90 xamarin_unhandled_exception_handler + 0
	3   libxamarin-dotnet.dylib             0x000000011a445b44 xamarin_invoke_trampoline + 744
	4   libxamarin-dotnet.dylib             0x000000011a448724 xamarin_arch_trampoline + 68
	5   libxamarin-dotnet.dylib             0x000000011a448d68 xamarin_arm64_common_trampoline + 64
	6   UIKitCore                           0x0000000185b2e30c -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 312
	7   UIKitCore                           0x0000000185b2f804 -[UIApplication _callInitializationDelegatesWithActions:forCanvas:payload:fromOriginatingProcess:] + 2936
	8   UIKitCore                           0x0000000185b34984 -[UIApplication _runWithMainScene:transitionContext:completion:] + 976
	9   UIKitCore                           0x00000001851405c0 -[_UISceneLifecycleMultiplexer completeApplicationLaunchWithFBSScene:transitionContext:] + 104
	10  UIKitCore                           0x00000001856e1f80 _UIScenePerformActionsWithLifecycleActionMask + 96
	11  UIKitCore                           0x0000000185140ebc __101-[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:]_block_invoke + 192
	12  UIKitCore                           0x0000000185140a30 -[_UISceneLifecycleMultiplexer _performBlock:withApplicationOfDeactivationReasons:fromReasons:] + 208
	13  UIKitCore                           0x0000000185140d10 -[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:] + 576
	14  UIKitCore                           0x000000018514071c -[_UISceneLifecycleMultiplexer uiScene:transitionedFromState:withTransitionContext:] + 244
	15  UIKitCore                           0x000000018514b758 __186-[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:]_blo	16  UIKitCore                           0x00000001855d20f0 +[BSAnimationSettings(UIKit) tryAnimatingWithSettings:fromCurrentState:actions:completion:] + 656
	17  UIKitCore                           0x00000001856f9e0c _UISceneSettingsDiffActionPerformChangesWithTransitionContextAndCompletion + 196
	18  UIKitCore                           0x000000018514b464 -[_UIWindowSceneFBSSceneTransitionContextDrivenLifecycleSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:] + 288
	19  UIKitCore                           0x0000000184f80b60 __64-[UIScene scene:didUpdateWithDiff:transitionContext:completion:]_block_invoke.201 + 608
	20  UIKitCore                           0x0000000184f7f908 -[UIScene _emitSceneSettingsUpdateResponseForCompletion:afterSceneUpdateWork:] + 200
	21  UIKitCore                           0x0000000184f807e4 -[UIScene scene:didUpdateWithDiff:transitionContext:completion:] + 220
	22  UIKitCore                           0x0000000185b33628 -[UIApplication workspace:didCreateScene:withTransitionContext:completion:] + 432
	23  UIKitCore                           0x00000001855fbc68 -[UIApplicationSceneClientAgent scene:didInitializeWithEvent:completion:] + 260
	24  FrontBoardServices                  0x0000000187ad5740 __95-[FBSScene _callOutQueue_didCreateWithTransitionContext:alternativeCreationCallout:completion:]_block_invoke + 260
	25  FrontBoardServices                  0x0000000187ad5b00 -[FBSScene _callOutQueue_coalesceClientSettingsUpdates:] + 60
	26  FrontBoardServices                  0x0000000187ad55c0 -[FBSScene _callOutQueue_didCreateWithTransitionContext:alternativeCreationCallout:completion:] + 408
	27  FrontBoardServices                  0x0000000187b029e0 __93-[FBSWorkspaceScenesClient _callOutQueue_sendDidCreateForScene:transitionContext:completion:]_block_invoke.156 + 216
	28  FrontBoardServices                  0x0000000187ae2074 -[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:] + 160
	29  FrontBoardServices                  0x0000000187b00eb0 -[FBSWorkspaceScenesClient _callOutQueue_sendDidCreateForScene:transitionContext:completion:] + 388
	30  libdispatch.dylib                   0x000000018017cc08 _dispatch_client_callout + 16
	31  libdispatch.dylib                   0x0000000180180b2c _dispatch_block_invoke_direct + 376
	3
2025-01-02 18:20:47.747562+0700 mauitest.iOS[46554:892704] 
Unhandled Exception:
System.ExecutionEngineException: Attempting to JIT compile method 'void mauitest.App:InitializeComponent ()' while running in aot-only mode. See https://learn.microsoft.com/xamarin/ios/internals/limitations for more information.

   at mauitest.App..ctor()
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Constructor(Object obj, IntPtr* args)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=9.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSiteMain(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=9.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSite(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
   at System.Collections.Concurrent.ConcurrentDictionary`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceIdentifier, Microsoft.Extensions.DependencyInjection, Version=9.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[Microsoft.Extensions.DependencyInjection.ServiceProvider.ServiceAccessor, Microsoft.Extensions.DependencyInjection, Version=9.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].GetOrAdd(ServiceIdentifier key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Maui.MauiContext.WrappedServiceProvider.GetService(Type serviceType)
   at Microsoft.Maui.MauiContext.WrappedServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[IApplication](IServiceProvider provider)
   at Microsoft.Maui.MauiUIApplicationDelegate.FinishedLaunching(UIApplication application, NSDictionary launchOptions)
   at mauitest.iOS.AppDelegate.FinishedLaunching(UIApplication app, NSDictionary options)
2025-01-02 18:20:47.747677+0700 mauitest.iOS[46554:892704] Received unhandled Objective-C exception that was marshalled from a managed exception: Attempting to JIT compile method 'void mauitest.App:InitializeComponent ()' while running in aot-only mode. See https://learn.microsoft.com/xamarin/ios/internals/limitations for more information.
 (System.ExecutionEngineException)
   at mauitest.App..ctor()
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Constructor(Object obj, IntPtr* args)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=9.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSiteMain(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=9.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSite(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
   at System.Collections.Concurrent.ConcurrentDictionary`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceIdentifier, Microsoft.Extensions.DependencyInjection, Version=9.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[Microsoft.Extensions.DependencyInjection.ServiceProvider.ServiceAccessor, Microsoft.Extensions.DependencyInjection, Version=9.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].GetOrAdd(ServiceIdentifier key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Maui.MauiContext.WrappedServiceProvider.GetService(Type serviceType)
   at Microsoft.Maui.MauiContext.WrappedServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[IApplication](IServiceProvider provider)
   at Microsoft.Maui.MauiUIApplicationDelegate.FinishedLaunching(UIApplication application, NSDictionary launchOptions)
   at mauitest.iOS.AppDelegate.FinishedLaunching(UIApplication app, NSDictionary options)

=================================================================
	Native Crash Reporting
=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Native stacktrace:
=================================================================
	0x11a820a28 - /Users/albilaga/Library/Developer/CoreSimulator/Devices/CECA68BD-57D2-41A6-9658-858A944D2E0A/data/Containers/Bundle/Application/C8097D6D-6712-4B1A-9711-5815D4FD4228/mauitest.iOS.app/libmonosgen-2.0.dylib : mono_dump_native_crash_info
	0x11a7cc134 - /Users/albilaga/Library/Developer/CoreSimulator/Devices/CECA68BD-57D2-41A6-9658-858A944D2E0A/data/Containers/Bundle/Application/C8097D6D-6712-4B1A-9711-5815D4FD4228/mauitest.iOS.app/libmonosgen-2.0.dylib : mono_handle_native_crash
	0x11a9a39e8 - /Users/albilaga/Library/Developer/CoreSimulator/Devices/CECA68BD-57D2-41A6-9658-858A944D2E0A/data/Containers/Bundle/Application/C8097D6D-6712-4B1A-9711-5815D4FD4228/mauitest.iOS.app/libmonosgen-2.0.dylib : sigabrt_signal_handler.cold.1
	0x11a8203a0 - /Users/albilaga/Library/Developer/CoreSimulator/Devices/CECA68BD-57D2-41A6-9658-858A944D2E0A/data/Containers/Bundle/Application/C8097D6D-6712-4B1A-9711-5815D4FD4228/mauitest.iOS.app/libmonosgen-2.0.dylib : mono_runtime_setup_stat_profiler
	0x11a1143c0 - /usr/lib/system/libsystem_platform.dylib : _sigtramp
	0x11a313408 - /usr/lib/system/libsystem_pthread.dylib : pthread_kill
	0x1801704ec - /Library/Developer/CoreSimulator/Volumes/iOS_22C150/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 18.2.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/libsystem_c.dylib : abort
	0x11a43f21c - /Users/albilaga/Library/Developer/CoreSimulator/Devices/CECA68BD-57D2-41A6-9658-858A944D2E0A/data/Containers/Bundle/Application/C8097D6D-6712-4B1A-9711-5815D4FD4228/mauitest.iOS.app/libxamarin-dotnet.dylib : xamarin_get_app_bundle_path
	0x1804b94a0 - /Library/Developer/CoreSimulator/Volumes/iOS_22C150/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 18.2.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : __handleUncaughtException
	0x18006f8a0 - /Library/Developer/CoreSimulator/Volumes/iOS_22C150/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 18.2.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libobjc.A.dylib : _ZL15_objc_terminatev
	0x1802ac4d8 - /Library/Developer/CoreSimulator/Volumes/iOS_22C150/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 18.2.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libc++abi.dylib : _ZSt11__terminatePFvvE
	0x1802ac488 - /Library/Developer/CoreSimulator/Volumes/iOS_22C150/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 18.2.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libc++abi.dylib : _ZSt9terminatev
	0x18017cc1c - /Library/Developer/CoreSimulator/Volumes/iOS_22C150/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 18.2.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/libdispatch.dylib : _dispatch_client_callout
	0x180180b2c - /Library/Developer/CoreSimulator/Volumes/iOS_22C150/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 18.2.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/libdispatch.dylib : _dispatch_block_invoke_direct
	0x187b257f4 - /Library/Developer/CoreSimulator/Volumes/iOS_22C150/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 18.2.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/FrontBoardServices.framework/FrontBoardServices : __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__
	0x187b256d0 - /Library/Developer/CoreSimulator/Volumes/iOS_22C150/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 18.2.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/FrontBoardServices.framework/FrontBoardServices : -[FBSMainRunLoopSerialQueue _targetQueue_performNextIfPossible]
	0x187b25828 - /Library/Developer/CoreSimulator/Volumes/iOS_22C150/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 18.2.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/FrontBoardServices.framework/FrontBoardServices : -[FBSMainRunLoopSerialQueue _performNextFromRunLoopSource]
	0x18041d294 - /Library/Developer/CoreSimulator/Volumes/iOS_22C150/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 18.2.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
	0x18041d1dc - /Library/Developer/CoreSimulator/Volumes/iOS_22C150/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 18.2.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : __CFRunLoopDoSource0
	0x18041c99c - /Library/Developer/CoreSimulator/Volumes/iOS_22C150/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 18.2.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : __CFRunLoopDoSources0
	0x180416e84 - /Library/Developer/CoreSimulator/Volumes/iOS_22C150/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 18.2.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : __CFRunLoopRun
	0x1804166f4 - /Library/Developer/CoreSimulator/Volumes/iOS_22C150/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 18.2.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : CFRunLoopRunSpecific
	0x1905e5b10 - /Library/Developer/CoreSimulator/Volumes/iOS_22C150/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 18.2.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/GraphicsServices.framework/GraphicsServices : GSEventRunModal
	0x185b319dc - /Library/Developer/CoreSimulator/Volumes/iOS_22C150/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 18.2.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIApplication _run]
	0x185b35bd4 - /Library/Developer/CoreSimulator/Volumes/iOS_22C150/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 18.2.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : UIApplicationMain
	0x11a434040 - /Users/albilaga/Library/Developer/CoreSimulator/Devices/CECA68BD-57D2-41A6-9658-858A944D2E0A/data/Containers/Bundle/Application/C8097D6D-6712-4B1A-9711-5815D4FD4228/mauitest.iOS.app/libxamarin-dotnet.dylib : xamarin_UIApplicationMain
	0x105f5adb0 - /Users/albilaga/Library/Developer/CoreSimulator/Devices/CECA68BD-57D2-41A6-9658-858A944D2E0A/data/Containers/Bundle/Application/C8097D6D-6712-4B1A-9711-5815D4FD4228/mauitest.iOS.app/mauitest.iOS : wrapper_managed_to_native_UIKit_UIApplication_xamarin_UIApplicationMain_int_intptr_intptr_intptr_intptr_
	0x10b48dca8 - /Users/albilaga/Library/Developer/CoreSimulator/Devices/CECA68BD-57D2-41A6-9658-858A944D2E0A/data/Containers/Bundle/Application/C8097D6D-6712-4B1A-9711-5815D4FD4228/mauitest.iOS.app/mauitest.iOS : Microsoft_iOS_UIKit_UIApplication_UIApplicationMain_int_string___intptr_intptr
	0x10798af20 - /Users/albilaga/Library/Developer/CoreSimulator/Devices/CECA68BD-57D2-41A6-9658-858A944D2E0A/data/Containers/Bundle/Application/C8097D6D-6712-4B1A-9711-5815D4FD4228/mauitest.iOS.app/mauitest.iOS : mauitest_iOS_mauitest_iOS_Program_Main_string__
	0x11a735328 - /Users/albilaga/Library/Developer/CoreSimulator/Devices/CECA68BD-57D2-41A6-9658-858A944D2E0A/data/Containers/Bundle/Application/C8097D6D-6712-4B1A-9711-5815D4FD4228/mauitest.iOS.app/libmonosgen-2.0.dylib : mono_jit_runtime_invoke
	0x11a9046ec - /Users/albilaga/Library/Developer/CoreSimulator/Devices/CECA68BD-57D2-41A6-9658-858A944D2E0A/data/Containers/Bundle/Application/C8097D6D-6712-4B1A-9711-5815D4FD4228/mauitest.iOS.app/libmonosgen-2.0.dylib : mono_runtime_invoke_checked
	0x11a90be88 - /Users/albilaga/Library/Developer/CoreSimulator/Devices/CECA68BD-57D2-41A6-9658-858A944D2E0A/data/Containers/Bundle/Application/C8097D6D-6712-4B1A-9711-5815D4FD4228/mauitest.iOS.app/libmonosgen-2.0.dylib : mono_runtime_exec_main_checked
	0x11a78abf0 - /Users/albilaga/Library/Developer/CoreSimulator/Devices/CECA68BD-57D2-41A6-9658-858A944D2E0A/data/Containers/Bundle/Application/C8097D6D-6712-4B1A-9711-5815D4FD4228/mauitest.iOS.app/libmonosgen-2.0.dylib : mono_jit_exec
	0x11a448678 - /Users/albilaga/Library/Developer/CoreSimulator/Devices/CECA68BD-57D2-41A6-9658-858A944D2E0A/data/Containers/Bundle/Application/C8097D6D-6712-4B1A-9711-5815D4FD4228/mauitest.iOS.app/libxamarin-dotnet.dylib : xamarin_main
	0x10c09c878 - /Users/albilaga/Library/Developer/CoreSimulator/Devices/CECA68BD-57D2-41A6-9658-858A944D2E0A/data/Containers/Bundle/Application/C8097D6D-6712-4B1A-9711-5815D4FD4228/mauitest.iOS.app/mauitest.iOS : main
	0x119e5d410 - Unknown
	0x119f2e274 - Unknown

=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x11a5d9108):0x11a5d90f8  c0 03 5f d6 c0 03 5f d6 10 29 80 d2 01 10 00 d4  .._..._..)......
0x11a5d9108  e3 00 00 54 fd 7b bf a9 fd 03 00 91 ee e2 ff 97  ...T.{..........
0x11a5d9118  bf 03 00 91 fd 7b c1 a8 c0 03 5f d6 c0 03 5f d6  .....{...._..._.
0x11a5d9128  70 0a 80 d2 01 10 00 d4 e3 00 00 54 fd 7b bf a9  p..........T.{..

=================================================================
	Managed Stacktrace:
=================================================================
	  at <unknown> <0xffffffff>
	  at UIKit.UIApplication:xamarin_UIApplicationMain <0x00007>
	  at UIKit.UIApplication:UIApplicationMain <0x000d3>
	  at UIKit.UIApplication:Main <0x00117>
	  at mauitest.iOS.Program:Main <0x00037>
	  at System.Object:runtime_invoke_dynamic <0x00127>
=================================================================
```
