### ISSUE TITLE
Custom Font Loading Issues with .NET 9 Maui Hybrid

### ISSUE THREAD

**Issue by JohnSL** [dotnet/maui#26889]
### Description

I have a new .NET 9 MAUI Hybrid application I've been working on. I decided to try using some custom fonts following the instructions here: https://learn.microsoft.com/en-us/dotnet/maui/user-interface/fonts?view=net-maui-9.0. However, I've been having issues where they mostly work on Android and mostly don't work on Windows (details below in the **Actual Behavior** section). 

## My Setup

Here is what I have:

1. I added the font files to the `Resources\Fonts` folder, which already had the `OpenSans-Regular.ttf` file.
1. I verified that they all had the Build Action set to `MauiFont` in the **Properties** window.
1. I tried setting **Copy always** as well
1. The `csproj` file has the following:

   ```xml
   <MauiImage Include="Resources\Images\*" />
   ```

1. I have the following in `MauiProgram.cs`:

   ```csharp
   .ConfigureFonts(fonts =>
   {
       fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
       fonts.AddFont("DS-DIGI.TTF", "DsDigital");
       fonts.AddFont("Segment7Standard.otf", "Segment7");
   });
   ```

1. I couldn't get the fonts to work in Blazer code, so I replaced the `BlazorWebView` in `MainPage.xaml` with the following:

   ```xaml
   <VerticalStackLayout>
       <Label Text=" Testing123 Segment7" FontFamily="Segment7" FontSize="30"/>
       <Label Text=" Testing123 Segment7Standard" FontFamily="Segment7Standard" FontSize="30"/>
       <Label Text=" Testing123 DS-DIGI" FontFamily="DS-DIGI" FontSize="30"/>
       <Label Text=" Testing123 DsDigital" FontFamily="DsDigital" FontSize="30"/>
   </VerticalStackLayout>

   ```

## Actual Behavior

Here is the odd part. One Windows, only the last example (`DsDigital`) works. But on Android, The first, second, and fourth work, but the third (`DS-DIGI`) doesn't work. By not work, I mean they show what looks like a standard sans-serif font.

For Windows, I do have the DS-DIGI font installed, so I tried installing Segment7Standard as well, but that didn't make a difference.

## Debug Logs

When I look at the debug logs, I see error messages on both Windows and Android about issuing loading the font files. Here is an example of what I see for **Android**:

```
[0:] Microsoft.Maui.FontManager: Warning: Unable to load font 'Segment7Standard' from assets.

Java.Lang.RuntimeException: Font asset not found Segment7Standard
...
```

And on **Windows**:

```
Microsoft.Maui.FontManager: Error: Error loading font 'Assets/Fonts/DS-DIGI.ttf'.

System.InvalidOperationException: This operation is not supported for a relative URI.
   at System.Uri.get_AbsolutePath()
   at Microsoft.Maui.FontManager.FindFontFamilyName(String fontFile)
Microsoft.Maui.FontManager: Error: Error loading font 'Assets/Fonts/DS-DIGI.otf'.
```

### Version with bug

9.0.0 GA

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, Android

### Affected platform versions

Windows SDK 10.0.19041.0, Android 24

### Did you find any workaround?

No.

### Relevant log output

```shell
Relevant logs for Android:

[0:] Microsoft.Maui.FontManager: Warning: Unable to load font 'Segment7Standard' from assets.

Java.Lang.RuntimeException: Font asset not found Segment7Standard
   at Java.Interop.JniEnvironment.StaticMethods.CallStaticObjectMethod(JniObjectReference type, JniMethodInfo method, JniArgumentValue* args) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/obj/Release/net8.0/JniEnvironment.g.cs:line 21453
   at Java.Interop.JniPeerMembers.JniStaticMethods.InvokeObjectMethod(String encodedMember, JniArgumentValue* parameters) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniStaticMethods.cs:line 165
   at Android.Graphics.Typeface.CreateFromAsset(AssetManager mgr, String path) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net9.0/android-35/mcw/Android.Graphics.Typeface.cs:line 637
   at Microsoft.Maui.FontManager.LoadTypefaceFromAsset(String fontfamily, Boolean warning) in /_/src/Core/src/Fonts/FontManager.Android.cs:line 132
  --- End of managed Java.Lang.RuntimeException stack trace ---
java.lang.RuntimeException: Font asset not found Segment7Standard
	at android.graphics.Typeface.createFromAsset(Typeface.java:965)
	at crc6452ffdc5b34af3a0f.ScopedFragment.n_onCreateView(Native Method)
	at crc6452ffdc5b34af3a0f.ScopedFragment.onCreateView(ScopedFragment.java:45)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:3119)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:577)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:286)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2164)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2065)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3277)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3187)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:263)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:350)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:251)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
	at android.app.Activity.performStart(Activity.java:8052)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3457)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7660)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

  --- End of managed Java.Lang.RuntimeException stack trace ---
java.lang.RuntimeException: Font asset not found Segment7Standard
	at android.graphics.Typeface.createFromAsset(Typeface.java:965)
	at crc6452ffdc5b34af3a0f.ScopedFragment.n_onCreateView(Native Method)
	at crc6452ffdc5b34af3a0f.ScopedFragment.onCreateView(ScopedFragment.java:45)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:3119)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:577)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:286)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2164)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2065)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3277)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3187)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:263)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:350)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:251)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
	at android.app.Activity.performStart(Activity.java:8052)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3457)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7660)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
[0:] Microsoft.Maui.FontManager: Warning: Unable to load font 'DS-DIGI' from assets.

Java.Lang.RuntimeException: Font asset not found DS-DIGI
   at Java.Interop.JniEnvironment.StaticMethods.CallStaticObjectMethod(JniObjectReference type, JniMethodInfo method, JniArgumentValue* args) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/obj/Release/net8.0/JniEnvironment.g.cs:line 21453
   at Java.Interop.JniPeerMembers.JniStaticMethods.InvokeObjectMethod(String encodedMember, JniArgumentValue* parameters) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniStaticMethods.cs:line 165
   at Android.Graphics.Typeface.CreateFromAsset(AssetManager mgr, String path) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net9.0/android-35/mcw/Android.Graphics.Typeface.cs:line 637
   at Microsoft.Maui.FontManager.LoadTypefaceFromAsset(String fontfamily, Boolean warning) in /_/src/Core/src/Fonts/FontManager.Android.cs:line 132
  --- End of managed Java.Lang.RuntimeException stack trace ---
java.lang.RuntimeException: Font asset not found DS-DIGI
	at android.graphics.Typeface.createFromAsset(Typeface.java:965)
	at crc6452ffdc5b34af3a0f.ScopedFragment.n_onCreateView(Native Method)
	at crc6452ffdc5b34af3a0f.ScopedFragment.onCreateView(ScopedFragment.java:45)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:3119)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:577)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:286)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2164)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2065)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3277)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3187)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:263)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:350)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:251)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
	at android.app.Activity.performStart(Activity.java:8052)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3457)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7660)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

  --- End of managed Java.Lang.RuntimeException stack trace ---
java.lang.RuntimeException: Font asset not found DS-DIGI
	at android.graphics.Typeface.createFromAsset(Typeface.java:965)
	at crc6452ffdc5b34af3a0f.ScopedFragment.n_onCreateView(Native Method)
	at crc6452ffdc5b34af3a0f.ScopedFragment.onCreateView(ScopedFragment.java:45)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:3119)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:577)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:286)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2164)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2065)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3277)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3187)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:263)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:350)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:251)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
	at android.app.Activity.performStart(Activity.java:8052)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3457)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7660)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)



Relevant logs for Windows:

'IMControllerMaui.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\9.0.0\System.Collections.Immutable.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Microsoft.Maui.FontManager: Error: Error loading font 'Assets/Fonts/DS-DIGI.ttf'.

System.InvalidOperationException: This operation is not supported for a relative URI.
   at System.Uri.get_AbsolutePath()
   at Microsoft.Maui.FontManager.FindFontFamilyName(String fontFile)
Microsoft.Maui.FontManager: Error: Error loading font 'Assets/Fonts/DS-DIGI.otf'.

System.InvalidOperationException: This operation is not supported for a relative URI.
   at System.Uri.get_AbsolutePath()
   at Microsoft.Maui.FontManager.FindFontFamilyName(String fontFile)
'IMControllerMaui.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\9.0.0\Microsoft.Win32.Registry.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
```

**Comment by Zhanglirong-Winnie** [comment]
Could you provide us with a sample project so we can investigate it further? 
Looking forward to your reply!

**Comment by mattleibow** [comment]
Can you attach the sample that you have made so I can have a look?

**Comment by mattleibow** [comment]
I would think the fonts may not work in the webviews such as blazor and hybrid because even though the font is in the app, the webview does not look at the app's fonts. We may need to add a feature that somehow maps the font file in the app package to something you would set in CSS.

But, fonts in XAML should load.
