### ISSUE TITLE
[Bug] Dismissing iOS Modal Form Page causes NRE

### ISSUE THREAD

**Issue by drasticactions** [dotnet/maui#2948]
MAUI build 6.0.101-preview.10.1858

https://user-images.githubusercontent.com/898335/137349805-fcd47bf9-6e11-4f89-9fb1-1597b619d374.mp4

 If you use the iOS Form Modal Page and dismiss it, you get an NRE.

```
   at Microsoft.Maui.Controls.Platform.ModalWrapper.DidDismiss(UIPresentationController presentationController)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__127_0(Object state)
   at Foundation.NSAsyncSynchronizationContextDispatcher.Apply()
--- End of stack trace from previous location ---
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)
   at MauiVirtManager.Program.Main(String[] args) in C:\Users\t_mil\source\repos\Work\Hackathon\MauiVirtManager\MauiVirtManager\Platforms\iOS\Program.cs:line 12
```

**Comment by kristinx0211** [comment]
@drasticactions can you share the repro project for this issue.

**Comment by v-longmin** [comment]
@drasticactions Could you share the repro project for this issue, thanks?

**Comment by J-Swift** [comment]
You can repro this on the modal page of the Control.Sample app

**Comment by Redth** [comment]
Still repro's for a FlyoutPage (but not regular page or navigation page) on main.
