### ISSUE TITLE
[Bug] Shell BackgroundColor in UWP, MAC and iOS

### ISSUE THREAD

**Issue by juanlao** [dotnet/maui#3029]
### Description
Shell BackgroundColor property has some issues.

### Steps to Reproduce in windows
1. In the sample project set the BackgroundColor property from ShellPage.xaml to red
2. Run

### Expected Behavior
App with the shell background color in red.

### Actual Behavior
Null reference exception is raised with the stack trace:   
   at Microsoft.Maui.ColorExtensions.ToWindowsColor(Color color)
   at Microsoft.Maui.Controls.Platform.ShellItemView.UpdateAppearance(ShellAppearance appearance)
   at Microsoft.Maui.Controls.Platform.ShellItemView.Microsoft.Maui.Controls.IAppearanceObserver.OnAppearanceChanged(ShellAppearance appearance)
   at Microsoft.Maui.Controls.Shell.Microsoft.Maui.Controls.IShellController.AddAppearanceObserver(IAppearanceObserver observer, Element pivot)
   at Microsoft.Maui.Controls.Platform.ShellItemView.SetShellContext(ShellView context)
   at Microsoft.Maui.Controls.Platform.ShellView.SetElement(VisualElement element)
   at Microsoft.Maui.Controls.Handlers.ShellHandler.SetVirtualView(IView view)
   at Microsoft.Maui.Handlers.ViewHandler`2.SetVirtualView(IElement view)
   at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler)
   at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value)
   at Microsoft.Maui.HandlerExtensions.ToNative(IElement view, IMauiContext context)
   at Microsoft.Maui.WindowManager.Connect(IWindow window)
   at Microsoft.Maui.Handlers.WindowHandler.MapContent(WindowHandler handler, IWindow window)
   at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0.<Add>b__0(IElementHandler h, IElement v)
   at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IElementHandler viewHandler, IElement virtualView)
   at Microsoft.Maui.PropertyMapper.UpdateProperties(IElementHandler viewHandler, IElement virtualView)
   at Microsoft.Maui.Handlers.ElementHandler.SetVirtualView(IElement view)
   at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler)
   at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value)
   at Microsoft.Maui.HandlerExtensions.SetWindow(Window nativeWindow, IWindow window, IMauiContext context)
   at Microsoft.Maui.MauiWinUIApplication.CreateNativeWindow(LaunchActivatedEventArgs args)
   at Microsoft.Maui.MauiWinUIApplication.OnLaunched(LaunchActivatedEventArgs args)
   at ShellBackground.WinUI.App.OnLaunched(LaunchActivatedEventArgs args) in C:\Users\jlao\source\repos\ShellBackground\ShellBackground\Platforms\Windows\App.xaml.cs:line 29

### Basic Information

- Version with issue: 6.0.101-preview.9.1843
- IDE: Microsoft Visual Studio Enterprise 2022 Preview (64-bit)
Version 17.0.0 Preview 5.0

### Mac and iOS
Runing the same code on mac and running in mac and ios does not raise an exception but the BackgroundColor property seems to have no effect.

For mac and iOS maui-check says that is all ok: 
![image](https://user-images.githubusercontent.com/603023/137925670-3bbe38a3-2a0f-43bb-acf7-26341bbb0334.png)

Am I wrong? or can I have some issue with the upgrade to preview 9 in Mac?

### Screenshots

Android: 
![image](https://user-images.githubusercontent.com/603023/137925056-764f25c3-dd14-4e7a-a62b-92c6fcf9196d.png)

iOS:
![image](https://user-images.githubusercontent.com/603023/137925142-607b5084-fc09-409c-9794-e562fce62921.png)

Mac:
![image](https://user-images.githubusercontent.com/603023/137925198-98f33576-552b-474d-821f-80f75e6d21c6.png)

### Reproduction Sample

[ShellBackground.zip](https://github.com/dotnet/maui/files/7373760/ShellBackground.zip)

**Comment by PureWeen** [comment]
The crash seems to be fixed so here's a duplicate

https://github.com/dotnet/maui/issues/3077
