### ISSUE TITLE
[Bug] CollectionView Crash on Android using a custom header

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#3162]
### Description

Have a CollectionView with a header using a custom control using ContentView and a tap gesture. After tap, try to navigate to another page. 

Crash:

```
**System.Reflection.TargetInvocationException:** 'Exception has been thrown by the target of an invocation.'

[etConf2021.Mau] java_vm_ext.cc:545] JNI DETECTED ERROR IN APPLICATION: JNI CallObjectMethodA called with pending exception android.runtime.JavaProxyThrowable: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
[etConf2021.Mau] java_vm_ext.cc:545]  ---> Java.Lang.IllegalStateException: Cannot call this method while RecyclerView is computing a layout or scrolling crc645d80431ce5f73f11.MauiRecyclerView_3{c1944b4 VFED..... ......I. 0,0-0,0}, adapter:crc645d80431ce5f73f11.GroupableItemsViewAdapter_2@dd20076, layout:androidx.recyclerview.widget.GridLayoutManager@19f9b9b, context:crc64b93ba739210fe662.MainActivity@d772531
[etConf2021.Mau] java_vm_ext.cc:545]    at Java.Interop.JniEnvironment.InstanceMethods.CallNonvirtualVoidMethod(JniObjectReference instance, JniObjectReference type, JniMethodInfo method, JniArgumentValue* args) in /Users/builder/azdo/_work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniEnvironment.g.cs:line 12083
[etConf2021.Mau] java_vm_ext.cc:545]    at Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeNonvirtualVoidMethod(String encodedMember, IJavaPeerable self, JniArgumentValue* parameters) in /Users/builder/azdo/_work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:line 46
[etConf2021.Mau] java_vm_ext.cc:545]    at AndroidX.RecyclerView.Widget.RecyclerView.Adapter.NotifyDataSetChanged() in D:\a\1\s\generated\androidx.recyclerview.recyclerview\obj\Release
et6.0-android30.0\generated\src\AndroidX.RecyclerView.Widget.RecyclerView.cs:line 406
[etConf2021.Mau] java_vm_ext.cc:545]    at Microsoft.Maui.Controls.Handlers.Items.AdapterNotifier.NotifyDataSetChanged() in D:\a\1\s\src\Controls\src\Core\Handlers\Items\Android\Adapters\AdapterNotifier.cs:line 17
[etConf2021.Mau] java_vm_ext.cc:545]    at Microsoft.Maui.Controls.Handlers.Items.ObservableGroupedSource.Reload() in D:\a\1\s\src\Controls\src\Core\Handlers\Items\Android\ItemsSources\ObservableGroupedSource.cs:line 271
[etConf2021.Mau] java_vm_ext.cc:545]    at Microsoft.Maui.Controls.Handlers.Items.ObservableGroupedSource.CollectionChanged(NotifyCollectionChangedEventArgs args) in D:\a\1\s\src\Controls\src\Core\Handlers\Items\Android\ItemsSources\ObservableGroupedSource.cs:line 261
[etConf2021.Mau] java_vm_ext.cc:545]    at Microsoft.Maui.Controls.Handlers.Items.ObservableGroupedSource.CollectionChanged(Object sender, NotifyCollectionChangedEventArgs args) in D:\a\1\s\src\Controls\src\Core\Handlers\Items\Android\ItemsSources\ObservableGroupedSource.cs:line 240
[etConf2021.Mau] java_vm_ext.cc:545]    at System.Collections.ObjectModel.ObservableCollection`1[[Microsoft.NetConf2021.Maui.Models.ShowGroup, Microsoft.NetConf2021.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnCollectionChanged(NotifyCollectionChangedEventArgs e)
[etConf2021.Mau] java_vm_ext.cc:545]    at MvvmHelpers.ObservableRangeCollection`1[[Microsoft.NetConf2021.Maui.Models.ShowGroup, Microsoft.NetConf2021.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].RaiseChangeNotificationEvents(NotifyCollectionChangedAction action, List`1 changedItems, Int32 startingIndex) in /_/MvvmHelpers/ObservableRangeCollection.cs:line 160
[etConf2021.Mau] java_vm_ext.cc:545]    at MvvmHelpers.ObservableRangeCollection`1[[Microsoft.NetConf2021.Maui.Models.ShowGroup, Microsoft.NetConf2021.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].ReplaceRange(IEnumerable`1 collection) in /_/MvvmHelpers/ObservableRangeCollection.cs:line 140
[etConf2021.Mau] java_vm_ext.cc:545]    at Microsoft.NetConf2021.Maui.ViewModels.DiscoverViewModel.UpdatePodcasts(IEnumerable`1 listPodcasts) in F:\NET-New-Podcast-Client\src\Mobile\ViewModels\DiscoverViewModel.cs:line 95
[etConf2021.Mau] java_vm_ext.cc:545]    at Microsoft.NetConf2021.Maui.ViewModels.DiscoverViewModel.ApplyFilter(String searchText) in F:\NET-New-Podcast-Client\src\Mobile\ViewModels\DiscoverViewModel.cs:line 118
[etConf2021.Mau] java_vm_ext.cc:545]    at Microsoft.NetConf2021.Maui.ViewModels.DiscoverViewModel.OnSearchCommand() in F:\NET-New-Podcast-Client\src\Mobile\ViewModels\DiscoverViewModel.cs:line 105
[etConf2021.Mau] java_vm_ext.cc:545]    at MvvmHelpers.Commands.Command.<>c__DisplayClass4_0.<.ctor>b__0(Object o) in /_/MvvmHelpers/Commands/Command.cs:line 74
[etConf2021.Mau] java_vm_ext.cc:545]    at MvvmHelpers.Commands.Command.Execute(Object parameter) in /_/MvvmHelpers/Commands/Command.cs:line 124
[etConf2021.Mau] java_vm_ext.cc:545]    at Microsoft.NetConf2021.Maui.ViewModels.DiscoverViewModel.set_Text(String value) in F:\NET-New-Podcast-Client\src\Mobile\ViewModels\DiscoverViewModel.cs:line 30
[etConf2021.Mau] java_vm_ext.cc:545]    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[etConf2021.Mau] java_vm_ext.cc:545]   --- End of managed Java.Lang.IllegalStateException stack trace ---
[etConf2021.Mau] java_vm_ext.cc:545] java.lang.IllegalStateException: Cannot call this method while RecyclerView is computing a layout or scrolling crc645d80431ce5f73f11.MauiRecyclerView_3{c1944b4 VFED..... ......I. 0,0-0,0}, adapter:crc645d80431ce5f73f11.GroupableItemsViewAdapter_2@dd20076, layout:androidx.recyclerview.widget.GridLayoutManager@19f9b9b, context:crc64b93ba739210fe662.MainActivity@d772531
[etConf2021.Mau] java_vm_ext.cc:545] 	at androidx.recyclerview.widget.RecyclerView.assertNotInLayoutOrScroll(RecyclerView.java:3185)
[etConf2021.Mau] java_vm_ext.cc:545] 	at androidx.recyclerview.widget.RecyclerView$RecyclerViewDataObserver.onChanged(RecyclerView.java:5701)
[etConf2021.Mau] java_vm_ext.cc:545] 	at androidx.recyclerview.widget.RecyclerView$AdapterDataObservable.notifyChanged(RecyclerView.java:12653)
[etConf2021.Mau] java_vm_ext.cc:545] 	at androidx.recyclerview.widget.RecyclerView$Adapter.notifyDataSetChanged(RecyclerView.java:7584)
[etConf2021.Mau] java_vm_ext.cc:545] 	at crc645d80431ce5f73f11.GroupableItemsViewAdapter_2.n_onCreateViewHolder(Native Method)
[etConf2021.Mau] java_vm_ext.cc:545] 	at crc645d80431ce5f73f11.GroupableItemsViewAdapter_2.onCreateViewHolder(GroupableItemsViewAdapter_2.java:39)
[etConf2021.Mau] java_vm_ext.cc:545] 	at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:7295)
[etConf2021.Mau] java_vm_ext.cc:545] 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6416)
[etConf2021.Mau] java_vm_ext.cc:545] 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6300)
[etConf2021.Mau] java_vm_ext.cc:545] 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6296)
[etConf2021.Mau] java_vm_ext.cc:545] 	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2330)
[etConf2021.Mau] java_vm_ext.cc:545] 	at androidx.recyclerview.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:572)
[etConf2021.Mau] java_vm_ext.cc:545] 	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
[etConf2021.Mau] java_vm_ext.cc:545] 	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:668)
[etConf2021.Mau] java_vm_ext.cc:545] 	at androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
[etConf2021.Mau] java_vm_ext.cc:545] 	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4309)
[etConf2021.Mau] java_vm_ext.cc:545] 	at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3686)
[etConf2021.Mau] java_vm_ext.cc:545] 	at android.view.View.measure(View.java:23169)
[etConf2021.Mau] java_vm_ext.cc:545] 	at crc64fcf28c0e24b4cc31.LayoutViewGroup.n_onMeasure(Native Method)
[etConf2021.Mau] java_vm_ext.cc:545] 	at crc64fcf28c0e24b4cc31.LayoutViewGroup.onMeasure(LayoutViewGroup.java:54)
[etConf2021.Mau] java_vm_ext.cc:545] 	at android.view.View.measure(View.java:23169)
[etConf2021.Mau] java_vm_ext.cc:545] 	at crc64fcf28c0e24b4cc31.ContentViewGroup.n_onMeasure(Native Method)
[etConf2021.Mau] java_vm_ext.cc:545] 	at crc64fcf28c0e24b4cc31.ContentViewGroup.onMeasure(ContentViewGroup.java:54)
[etConf2021.Mau] java_vm_ext.cc:545] 	at android.view.View.measure(View.java:23169)
[etConf2021.Mau] java_vm_ext.cc:545] 	at crc64338477404e88479c.ShellPageContainer.n_onMeasure(Native Method)
[etConf2021.Mau] java_vm_ext.cc:545] 	at crc64338477404e88479c.ShellPageContainer.onMeasure(ShellPageContainer.java:62)
[etConf2021.Mau] java_vm_ext.cc:545] 	at android.view.View.measure(View.java:23169)
[etConf2021.Mau] java_vm_ext.cc:545] 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6749)
[etConf2021.Mau] java_vm_ext.cc:545] 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
[etConf2021.Mau] java_vm_ext.cc:545] 	at android.view.View.measure(View.java:23169)
[etConf2021.Mau] java_vm_ext.cc:545] 	at androidx.recyclerview.widget.RecyclerView$LayoutManager.measureChildWithMargins(RecyclerView.java:9681)
[etConf2021.Mau] java_vm_ext.cc:545] 	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1657)
[etConf2021.Mau] java_vm_ext.cc:545] 	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
[etConf2021.Mau] java_vm_ext.cc:545] 	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:668)
[etConf2021.Mau] java_vm_ext.cc:545] 	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4309)
[etConf2021.Mau] java_vm_ext.cc:545] 	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4012)
[etConf2021.Mau] java_vm_ext.cc:545] 	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4578)
[etConf2021.Mau] java_vm_ext.cc:545] 	at android.view.View.layout(View.java:20672)
[etConf2021.Mau] java_vm_ext.cc:545] 	at android.view.ViewGroup.layout(ViewGroup.java:6194)
[etConf2021.Mau] java_vm_ext.cc:545] 	at androidx.viewpager2.widget.ViewPager2.onLayout(ViewPager2.java:527)
[etConf2021.Mau] java_vm_ext.cc:545] 	at android.view.View.layout(View.java:20672)
[etConf2021.Mau] java_vm_ext.cc:545] 	at android.view.ViewGroup.layout(ViewGroup.java:6194)
[etConf2021.Mau] java_vm_ext.cc:545] 	at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:148)
[etConf2021.Mau] java_vm_ext.cc:545] 	at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:43)
[etConf2021.Mau] java_vm_ext.cc:545] 	at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:2003)
[etConf2021.Mau] java_vm_ext.cc:545] 	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:918)
[etConf2021.Mau] java_vm_ext.cc:545] 	at android.view.View.layout(View.java:20672)
[etConf2021.Mau] java_vm_ext.cc:545]    at Java.Interop.JniEnvironment.InstanceMethods.CallNonvirtualVoidMethod(JniObjectReference instance, JniObjectReference type, JniMethodInfo method, JniArgumentValue* args) in /Users/builder/azdo/_work/1/s/xamarin-android/extern10-28 16:36:07.495 F/etConf2021.Mau( 4657): java_vm_ext.cc:545] 	at android.view.ViewGroup.layout(ViewGroup.java:6194)
[etConf2021.Mau] java_vm_ext.cc:545] 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
[etConf2021.Mau] java_vm_ext.cc:545] 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
[etConf2021.Mau] java_vm_ext.cc:545]    at System.Collections.ObjectModel.ObservableCollection`1[[Microsoft.NetConf2021.Maui.Models.ShowGroup, Microsoft.NetConf2021.Maui, Version=110-28 16:36:07.495 F/etConf2021.Mau( 4657): java_vm_ext.cc:545] 	at android.view.ViewGroup.layout(ViewGroup.java:6194)
[etConf2021.Mau] java_vm_ext.cc:545] 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
[etConf2021.Mau] java_vm_ext.cc:545] 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
[etConf2021.Mau] java_vm_ext.cc:545] 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
[etConf2021.Mau] java_vm_ext.cc:545] 	at android.view.View.layout(View.java:20672)
[etConf2021.Mau] java_vm_ext.cc:545] 	at android.view.ViewGroup.layout(ViewGroup.java:6194)
[etConf2021.Mau] java_vm_ext.cc:545] 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
[etConf2021.Mau] java_vm_ext.cc:545] 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
[etConf2021.Mau] java_vm_ext.cc:545] 	at android.view.View.layout(View.java:20672)
[etConf2021.Mau] java_vm_ext.cc:545] 	at android.view.ViewGroup.layout(ViewGroup.java:6194)
[etConf2021.Mau] java_vm_ext.cc:545] 	at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1263)
[etConf2021.Mau] java_vm_ext.cc:545] 	at android.view.View.layout(View.java:20672)
[etConf2021.Mau] java_vm_ext.cc:545] 	at android.view.ViewGroup.layout(ViewGroup.java:6194)
[etConf2021.Mau] java_vm_ext.cc:545] 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
[etConf2021.Mau] java_vm_ext.cc:545] 	at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1801)
[etConf2021.Mau] java_vm_ext.cc:545] 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1567)
[etConf2021.Mau] java_vm_ext.cc:545] 	at android.view.View.layout(View.java:20672)
[etConf2021.Mau] java_vm_ext.cc:545] 	at android.view.ViewGroup.layout(ViewGroup.java:6194)
[etConf2021.Mau] java_vm_ext.cc:545] 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
[etConf2021.Mau] java_vm_ext.cc:545] 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
[etConf2021.Mau] java_vm_ext.cc:545] 	at android.view.View.layout(View.java:20672)
[etConf2021.Mau] java_vm_ext.cc:545] 	at android.view.ViewGroup.layout(ViewGroup.java:6194)
[etConf2021.Mau] java_vm_ext.cc:545] 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
[etConf2021.Mau] java_vm_ext.cc:545] 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
[etConf2021.Mau] java_vm_ext.cc:545] 	at android.view.View.layout(View.java:20672)
[etConf2021.Mau] java_vm_ext.cc:545] 	at android.view.ViewGroup.layout(ViewGroup.java:6194)
[etConf2021.Mau] java_vm_ext.cc:545] 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
[etConf2021.Mau] java_vm_ext.cc:545] 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
[etConf2021.Mau] java_vm_ext.cc:545] 	at android.view.View.layout(View.java:20672)
[etConf2021.Mau] java_vm_ext.cc:545] 	at android.view.ViewGroup.layout(ViewGroup.java:6194)
[etConf2021.Mau] java_vm_ext.cc:545] 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
[etConf2021.Mau] java_vm_ext.cc:545] 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
[etConf2021.Mau] java_vm_ext.cc:545] 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
[etConf2021.Mau] java_vm_ext.cc:545] 	at android.view.View.layout(View.java:20672)
[etConf2021.Mau] java_vm_ext.cc:545] 	at android.view.ViewGroup.layout(ViewGroup.java:6194)
[etConf2021.Mau] java_vm_ext.cc:545] 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
[etConf2021.Mau] java_vm_ext.cc:545] 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
[etConf2021.Mau] java_vm_ext.cc:545] 	at com.android.internal.policy.DecorView.onLayout(DecorView.java:753)
[etConf2021.Mau] java_vm_ext.cc:545] 	at android.view.View.layout(View.java:20672)
[etConf2021.Mau] java_vm_ext.cc:545] 	at android.view.ViewGroup.layout(ViewGroup.java:6194)
[etConf2021.Mau] java_vm_ext.cc:545] 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2792)
[etConf2021.Mau] java_vm_ext.cc:545] 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2319)
[etConf2021.Mau] java_vm_ext.cc:545] 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1460)
[etConf2021.Mau] java_vm_ext.cc:545] 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7183)
[etConf2021.Mau] java_vm_ext.cc:545] 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
[etConf2021.Mau] java_vm_ext.cc:545] 	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
[etConf2021.Mau] java_vm_ext.cc:545] 	at android.view.Choreographer.doFrame(Choreographer.java:696)
[etConf2021.Mau] java_vm_ext.cc:545] 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
[etConf2021.Mau] java_vm_ext.cc:545] 	at android.os.Handler.handleCallback(Handler.java:873)
[etConf2021.Mau] java_vm_ext.cc:545] 	at android.os.Handler.dispatchMessage(Handler.java:99)
[etConf2021.Mau] java_vm_ext.cc:545] 	at android.os.Looper.loop(Looper.java:193)
[etConf2021.Mau] java_vm_ext.cc:545] 	at android.app.ActivityThread.main(ActivityThread.java:6669)
[etConf2021.Mau] java_vm_ext.cc:545] 	at java.lang.reflect.Method.invoke(Native Method)
[etConf2021.Mau] java_vm_ext.cc:545] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
[etConf2021.Mau] java_vm_ext.cc:545] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
[etConf2021.Mau] java_vm_ext.cc:545] 
[etConf2021.Mau] java_vm_ext.cc:545]   --- End of managed Java.Lang.IllegalStateException stack trace ---
```
To try and validate the issue, use the internal podcasts sample.

**Comment by hartez** [comment]
This has nothing to do with custom headers. This is happening because the app is trying to do an update notification on the RecyclerView's adapter from a background thread. 

The methods in the stack trace no longer match the code in the app's main branch, so I'm guessing this has been fixed in the application. But if not, my guess is that the UpdatePodcasts() method should be ensuring that it's called on the main thread using Dispatcher.BeginInvoke.
