### ISSUE TITLE
System.MissingMethodException

### ISSUE THREAD

**Issue by HobDev** [dotnet/maui#3500]
### Description

I am debugging on Windows 11. When the app starts the following issue hits:
**Method**
```
protected override void OnLaunched(LaunchActivatedEventArgs args)
        {
            base.OnLaunched(args);
            Microsoft.Maui.Essentials.Platform.OnLaunched(args);
        }
```
**Exception**
System.MissingMethodException: 'Cannot dynamically create an instance of type [DISample.MainPage]. Reason: No parameterless constructor defined.'
**Source**
Source=System.Private.CoreLib
The app is using shell. I app deploy if I add the parameterless constructor in the Page. But than I can't `inject ViewModel` in the page constructor.  The `viewmodel` is registered in the   MauiProgram.cs as `builder.Services`.

### Steps to Reproduce

Register ViewModel in MauiProgram.cs as `builder.Services.AddTransient<YourViewModel>();` . Inject the ViewModel in yourpage.  Now Debug the app on  android emulator or simulator

### Version with bug

Preview 10 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows and Android. Not tested on iOS

### Affected platform versions

Windows SDK  10.0.19041.0  and Android Emulator. Not tested on iOS

### Did you find any workaround?

No

### Relevant log output

```shell
**StackTrace:**
   at System.RuntimeType.ActivatorCache..ctor(RuntimeType rt)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type)
   at Microsoft.Maui.Controls.ElementTemplate.<>c__DisplayClass4_0.<.ctor>b__0()
   at Microsoft.Maui.Controls.ElementTemplate.CreateContent()
   at Microsoft.Maui.Controls.Internals.DataTemplateExtensions.CreateContent(DataTemplate self, Object item, BindableObject container)
   at Microsoft.Maui.Controls.ShellContent.Microsoft.Maui.Controls.IShellContentController.GetOrCreateContent()
   at Microsoft.Maui.Controls.Platform.ShellSectionView.NavigateToShellSection(ShellSection section)
   at Microsoft.Maui.Controls.Platform.ShellItemView.OnShellSectionChanged(ShellSection oldSection, ShellSection newSection)
   at Microsoft.Maui.Controls.Platform.ShellItemView.set_ShellSection(ShellSection value)
   at Microsoft.Maui.Controls.Platform.ShellItemView.NavigateToShellItem(ShellItem newItem, Boolean animate)
   at Microsoft.Maui.Controls.Platform.ShellView.SwitchShellItem(ShellItem newItem, Boolean animate)
   at Microsoft.Maui.Controls.Platform.ShellView.OnElementSet(Shell shell)
   at Microsoft.Maui.Controls.Platform.ShellView.SetElement(VisualElement element)
   at Microsoft.Maui.Controls.Handlers.ShellHandler.SetVirtualView(IView view)
   at Microsoft.Maui.Handlers.ViewHandler`2.SetVirtualView(IElement view)
   at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler)
   at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value)
   at Microsoft.Maui.HandlerExtensions.ToNative(IElement view, IMauiContext context)
   at Microsoft.Maui.Controls.Window.MapContent(WindowHandler handler, IWindow view)
   at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IElementHandler viewHandler, IElement virtualView)
   at Microsoft.Maui.PropertyMapper.UpdateProperties(IElementHandler viewHandler, IElement virtualView)
   at Microsoft.Maui.Handlers.ElementHandler.SetVirtualView(IElement view)
   at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler)
   at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value)
   at Microsoft.Maui.HandlerExtensions.SetHandler(IWinRTObject nativeElement, IElement element, IMauiContext context)
   at Microsoft.Maui.HandlerExtensions.SetWindowHandler(Window nativeWindow, IWindow window, IMauiContext context)
   at Microsoft.Maui.Platform.ApplicationExtensions.CreateNativeWindow(Application nativeApplication, IApplication application, LaunchActivatedEventArgs args)
   at Microsoft.Maui.MauiWinUIApplication.OnLaunched(LaunchActivatedEventArgs args)
   at Gwal.WinUI.App.OnLaunched(LaunchActivatedEventArgs args) in C:\Users\spara\source\repos\Gwal\Gwal\Platforms\Windows\App.xaml.cs:line 29
   at Microsoft.UI.Xaml.Application.Microsoft.UI.Xaml.IApplicationOverrides.OnLaunched(LaunchActivatedEventArgs args)
   at ABI.Microsoft.UI.Xaml.IApplicationOverrides.Do_Abi_OnLaunched_0(IntPtr thisPtr, IntPtr args)
```

**Comment by HobDev** [comment]
[Link](https://github.com/HobDev/DISamlel) to the Repro Project

**Comment by devmikew** [comment]
The message says:
 System.MissingMethodException: 'Cannot dynamically create an instance of type '{Thenamespace.thepage}'. Reason: No parameterless constructor defined.


I can't find Thenamespace.thepage in the linked project.

Please provide the actual code in the link. Otherwise it is too difficult to provide any support.

**Comment by HobDev** [comment]
> I can't find Thenamespace.thepage in the linked project.

The linked project have `DISample.MainPage`. updated the issue with correct names.

**Comment by devmikew** [comment]
Ok, thanks.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by devmikew** [comment]
It seems that DI isn't working correctly. The missing method is probably the empty constructor for MainPage. So add:

 public MainPage()
        {
            InitializeComponent();
        }
 and see if that constructor gets called by setting a breakpoint in it.

Also, I cant see where you are setting the main page, eg, normally in the App constructor you should be :

		public App()
		{
			InitializeComponent();

			MainPage = new MainPage();
		}
Unless you are setting the main page in App.Xaml.cs with the following:
<Application.MainPage>
        <Shell >
etc

in this case there is no code behind for the page's constructor, it might be this constructor it cant find.

If you want to use a Shell layout then your main page should be a Shell and not a content page and set MainPage like above.

**Comment by HobDev** [comment]
@devmikew  Learn Xamrin.Forms first. Do some development. Than try to contribute to the Community.

**Comment by PureWeen** [comment]
Most likely resolved by
https://github.com/dotnet/maui/pull/3375

If you're still having this issue in P12 we can re-open
