### ISSUE TITLE
Null Reference Exception thrown if HotReload enabled

### ISSUE THREAD

**Issue by BenBtg** [dotnet/maui#3628]
### Description

Working on migrating existing Xamarin Forms samples hit the folllowing issue when HotReload was enabled

App would launch but Null Reference exception is thrown as soon and one of the page is navigated to.

Repro on this branch
https://github.com/alexkblount/maui-samples/tree/ben/ShapesDemo

### Steps to Reproduce

Enabled XAML HotReload

Launch app

Navigate to a page

Null Reference thrown with no call stack or code breakpoint

![image](https://user-images.githubusercontent.com/70525/144479351-7a3cbd5e-20fb-4d25-a923-48a3decca6bb.png)

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

### Did you find any workaround?

Yes, disable XAML HotReload in VS2022 Settings

### Relevant log output

```Forwarding debugger port 8860
Detecting existing process
> am start -a "android.intent.action.MAIN" -c "android.intent.category.LAUNCHER" -n "com.companyname.ShapesDemos/crc64c860ddb2246284b2.MainActivity"
> Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.companyname.ShapesDemos/crc64c860ddb2246284b2.MainActivity }
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/ShapesDemos.dll
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/Mono.Android.dll [External]
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/System.Runtime.dll [External]
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/Java.Interop.dll [External]
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/System.Collections.dll [External]
Resolved pending breakpoint for 'Android.Runtime.JNIEnv.RegisterJniNatives(System.IntPtr, System.Int32, System.IntPtr, System.IntPtr, System.Int32)' to /Users/builder/azdo/_work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNIEnv.cs:124 [0x00000].
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/System.Threading.dll [External]
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/System.Runtime.InteropServices.dll [External]
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/System.Threading.Thread.dll [External]
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/System.Diagnostics.StackTrace.dll [External]
Loaded assembly: data-0x73c15c4c80 [External]
Loaded assembly: data-0x73c15de500 [External]
[ame.ShapesDemo] Late-enabling -Xcheck:jni
[ame.ShapesDemo] The ClassLoaderContext is a special shared library.
[Embryo] preload com.companyname.ShapesDemos, 9ms, hwui=true, layout=false, decor=false
[OpenGLRenderer] Skia GL Pipeline
Loaded assembly: data-0x73be20d2c0 [External]
[Perf] Connecting to perf service.
[debug-app-helper] Checking if libmonodroid was unpacked to /data/app/com.companyname.ShapesDemos-VF4nu8OtLu7A5NosPNBzVg==/lib/arm64/libmonodroid.so
[debug-app-helper] Native libs extracted to /data/app/com.companyname.ShapesDemos-VF4nu8OtLu7A5NosPNBzVg==/lib/arm64, assuming application/android:extractNativeLibs == true
[debug-app-helper] Setting up for DSO lookup in app data directories
[debug-app-helper] Added filesystem DSO lookup location: /data/app/com.companyname.ShapesDemos-VF4nu8OtLu7A5NosPNBzVg==/lib/arm64
[debug-app-helper] Using runtime path: /data/app/com.companyname.ShapesDemos-VF4nu8OtLu7A5NosPNBzVg==/lib/arm64
[debug-app-helper] checking directory: `/data/user/0/com.companyname.ShapesDemos/files/.__override__/lib`
[debug-app-helper] directory does not exist: `/data/user/0/com.companyname.ShapesDemos/files/.__override__/lib`
[debug-app-helper] Checking whether Mono runtime exists at: /data/user/0/com.companyname.ShapesDemos/files/.__override__/libmonosgen-2.0.so
[debug-app-helper] Checking whether Mono runtime exists at: /data/app/com.companyname.ShapesDemos-VF4nu8OtLu7A5NosPNBzVg==/lib/arm64/libmonosgen-2.0.so
[debug-app-helper] Mono runtime found at: /data/app/com.companyname.ShapesDemos-VF4nu8OtLu7A5NosPNBzVg==/lib/arm64/libmonosgen-2.0.so
[ame.ShapesDemo] Attempt to remove non-JNI local reference, dumping thread
[DOTNET] JNI_OnLoad: JNI_OnLoad in pal_jni.c
[DOTNET] GetOptionalMethod: optional method setApplicationProtocols ([Ljava/lang/String;)V was not found
[DOTNET] GetOptionalMethod: optional method getApplicationProtocol ()Ljava/lang/String; was not found
[monodroid] Creating public update directory: `/data/user/0/com.companyname.ShapesDemos/files/.__override__`
[ame.ShapesDemo] Attempt to remove non-JNI local reference, dumping thread
[monodroid-debug] Trying to initialize the debugger with options: --debugger-agent=transport=dt_socket,loglevel=0,address=127.0.0.1:8860,server=y,embedding=1
[monodroid-assembly] open_from_bundles: failed to load assembly ShapesDemos.dll
[monodroid-gc] GREF GC Threshold: 46080
[monodroid-assembly] open_from_bundles: failed to load assembly Mono.Android.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Runtime.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Java.Interop.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Collections.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Threading.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Runtime.InteropServices.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Threading.Thread.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Diagnostics.StackTrace.dll
[ame.ShapesDemo] Attempt to remove non-JNI local reference, dumping thread
[monodroid-assembly] open_from_bundles: failed to load assembly netstandard.dll
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/netstandard.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Linq.dll
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/System.Linq.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.VisualStudio.DesignTools.TapContract.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.VisualStudio.DesignTools.TapContract.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.HotReload.Contracts.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.HotReload.Contracts.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Collections.Concurrent.dll
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/System.Collections.Concurrent.dll [External]
Resolved pending breakpoint for 'Xamarin.HotReload.HotReloadAgent.BreakpointSendToIde(System.String)' to D:\a\_work\1\s\HotReload\Source\Xamarin.HotReload.Agent\HotReloadAgent.cs:403 [0x00000].
[monodroid-assembly] open_from_bundles: failed to load assembly System.ComponentModel.dll
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/System.ComponentModel.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Maui.Controls.dll
[monodroid-assembly] open_from_bundles: failed to load assembly mscorlib.dll
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/Microsoft.Maui.Controls.dll [External]
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/mscorlib.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.HotReload.Contracts.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.HotReload.Contracts.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.VisualStudio.DesignTools.TapContract.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.VisualStudio.DesignTools.TapContract.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.ObjectModel.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Maui.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Maui.Graphics.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Logging.Abstractions.dll
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/System.ObjectModel.dll [External]
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/Microsoft.Maui.dll [External]
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/Microsoft.Maui.Graphics.dll [External]
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/Microsoft.Extensions.Logging.Abstractions.dll [External]
Resolved pending breakpoint for 'Xamarin.HotReload.HotReloadAgent.BreakpointCheckpoint()' to D:\a\_work\1\s\HotReload\Source\Xamarin.HotReload.Agent\HotReloadAgent.cs:398 [0x00000].
[monodroid-assembly] open_from_bundles: failed to load assembly System.Reflection.Emit.Lightweight.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Reflection.Emit.ILGeneration.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Reflection.Primitives.dll
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/System.Reflection.Emit.Lightweight.dll [External]
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/System.Reflection.Emit.ILGeneration.dll [External]
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/System.Reflection.Primitives.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Maui.Essentials.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.Core.dll
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/Microsoft.Maui.Essentials.dll [External]
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/Xamarin.AndroidX.Core.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Hosting.Abstractions.dll
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/Microsoft.Extensions.Hosting.Abstractions.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.DependencyInjection.Abstractions.dll
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/Microsoft.Extensions.DependencyInjection.Abstractions.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Maui.Controls.Compatibility.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Hosting.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Logging.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Configuration.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Configuration.Abstractions.dll
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/Microsoft.Maui.Controls.Compatibility.dll [External]
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/Microsoft.Extensions.Hosting.dll [External]
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/Microsoft.Extensions.Logging.dll [External]
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/Microsoft.Extensions.Configuration.dll [External]
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/Microsoft.Extensions.Configuration.Abstractions.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.FileProviders.Physical.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.FileProviders.Abstractions.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Primitives.dll
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/Microsoft.Extensions.FileProviders.Physical.dll [External]
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/Microsoft.Extensions.FileProviders.Abstractions.dll [External]
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/Microsoft.Extensions.Primitives.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.DependencyInjection.dll
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/Microsoft.Extensions.DependencyInjection.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Configuration.FileExtensions.dll
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/Microsoft.Extensions.Configuration.FileExtensions.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Options.dll
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/Microsoft.Extensions.Options.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Logging.EventLog.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Logging.Configuration.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Logging.Debug.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Logging.Console.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Logging.EventSource.dll
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/Microsoft.Extensions.Logging.EventLog.dll [External]
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/Microsoft.Extensions.Logging.Configuration.dll [External]
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/Microsoft.Extensions.Logging.Debug.dll [External]
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/Microsoft.Extensions.Logging.Console.dll [External]
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/Microsoft.Extensions.Logging.EventSource.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Options.ConfigurationExtensions.dll
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/Microsoft.Extensions.Options.ConfigurationExtensions.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.AppCompat.dll
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/Xamarin.AndroidX.AppCompat.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.ComponentModel.TypeConverter.dll
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/System.ComponentModel.TypeConverter.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Private.Uri.dll
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/System.Private.Uri.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.Google.Android.Material.dll
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/Xamarin.Google.Android.Material.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Diagnostics.DiagnosticSource.dll
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/System.Diagnostics.DiagnosticSource.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Diagnostics.Tracing.dll
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/System.Diagnostics.Tracing.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Extensions.Configuration.Binder.dll
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/Microsoft.Extensions.Configuration.Binder.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.CoordinatorLayout.dll
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/Xamarin.AndroidX.CoordinatorLayout.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Linq.Expressions.dll
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/System.Linq.Expressions.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Maui.Controls.Xaml.dll
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/Microsoft.Maui.Controls.Xaml.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Xml.ReaderWriter.dll
[monodroid-assembly] open_from_bundles: failed to load assembly System.Private.Xml.dll
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/System.Xml.ReaderWriter.dll [External]
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/System.Private.Xml.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Text.Encoding.Extensions.dll
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/System.Text.Encoding.Extensions.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Memory.dll
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/System.Memory.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Text.RegularExpressions.dll
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/System.Text.RegularExpressions.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Runtime.CompilerServices.Unsafe.dll
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/System.Runtime.CompilerServices.Unsafe.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Runtime.Loader.dll
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/System.Runtime.Loader.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Numerics.Vectors.dll
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/System.Numerics.Vectors.dll [External]
Thread started:  #2
Thread started:  #3
Thread started:  #4
[monodroid-assembly] open_from_bundles: failed to load assembly en-GB/System.Private.CoreLib.resources.dll
[monodroid-assembly] open_from_bundles: failed to load assembly en-GB/System.Private.CoreLib.resources.dll
[monodroid-assembly] open_from_bundles: failed to load assembly en/System.Private.CoreLib.resources.dll
[monodroid-assembly] open_from_bundles: failed to load assembly en/System.Private.CoreLib.resources.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.CardView.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Maui.Controls.Compatibility.Android.FormsViewGroup.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.SwipeRefreshLayout.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.RecyclerView.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.ViewPager.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.Fragment.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.Activity.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.Lifecycle.ViewModel.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.Lifecycle.Common.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.SavedState.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.DrawerLayout.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.CustomView.dll
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/Xamarin.AndroidX.CardView.dll [External]
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/Microsoft.Maui.Controls.Compatibility.Android.FormsViewGroup.dll [External]
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/Xamarin.AndroidX.SwipeRefreshLayout.dll [External]
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/Xamarin.AndroidX.RecyclerView.dll [External]
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/Xamarin.AndroidX.ViewPager.dll [External]
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/Xamarin.AndroidX.Fragment.dll [External]
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/Xamarin.AndroidX.Activity.dll [External]
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/Xamarin.AndroidX.Lifecycle.ViewModel.dll [External]
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/Xamarin.AndroidX.Lifecycle.Common.dll [External]
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/Xamarin.AndroidX.SavedState.dll [External]
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/Xamarin.AndroidX.DrawerLayout.dll [External]
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/Xamarin.AndroidX.CustomView.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.ViewPager2.dll
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/Xamarin.AndroidX.ViewPager2.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.Loader.dll
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/Xamarin.AndroidX.Loader.dll [External]
[ame.ShapesDemo] Accessing hidden method Landroid/graphics/drawable/Drawable;->getOpticalInsets()Landroid/graphics/Insets; (light greylist, linking)
[ame.ShapesDemo] Accessing hidden field Landroid/graphics/Insets;->left:I (light greylist, linking)
[ame.ShapesDemo] Accessing hidden field Landroid/graphics/Insets;->right:I (light greylist, linking)
[ame.ShapesDemo] Accessing hidden field Landroid/graphics/Insets;->top:I (light greylist, linking)
[ame.ShapesDemo] Accessing hidden field Landroid/graphics/Insets;->bottom:I (light greylist, linking)
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.Navigation.Fragment.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.Navigation.Runtime.dll
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.Navigation.Common.dll
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/Xamarin.AndroidX.Navigation.Fragment.dll [External]
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/Xamarin.AndroidX.Navigation.Runtime.dll [External]
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/Xamarin.AndroidX.Navigation.Common.dll [External]
[ame.ShapesDemo] Accessing hidden method Landroid/view/View;->getAccessibilityDelegate()Landroid/view/View$AccessibilityDelegate; (light greylist, linking)
[ame.ShapesDemo] Accessing hidden field Landroid/view/View;->mAccessibilityDelegate:Landroid/view/View$AccessibilityDelegate; (light greylist, reflection)
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.Lifecycle.LiveData.Core.dll
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/Xamarin.AndroidX.Lifecycle.LiveData.Core.dll [External]
[ame.ShapesDemo] Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (light greylist, reflection)
[ame.ShapesDemo] Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (light greylist, reflection)
[monodroid-assembly] open_from_bundles: failed to load assembly Xamarin.AndroidX.Navigation.UI.dll
Loaded assembly: /data/data/com.companyname.ShapesDemos/files/.__override__/Xamarin.AndroidX.Navigation.UI.dll [External]
Thread started: <Thread Pool> #5
Thread started: .NET ThreadPool Gate #6
Thread started: <Thread Pool> #7
Thread started: .NET Timers #8
[Adreno] QUALCOMM build                   : 4c638fb, I557c585805
[Adreno] Build Date                       : 10/06/18
[Adreno] OpenGL ES Shader Compiler Version: EV031.25.03.01
[Adreno] Local Branch                     : 
[Adreno] Remote Branch                    : 
[Adreno] Remote Branch                    : 
[Adreno] Reconstruct Branch               : 
[Adreno] Build Config                     : S L 6.0.7 AArch64
[Adreno] PFP: 0x005ff112, ME: 0x005ff066
[ConfigStore] android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
[ConfigStore] android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
[OpenGLRenderer] Initialized EGL, version 1.4
[OpenGLRenderer] Swap behavior 2
[ame.ShapesDemo] Compiler allocated 4MB to compile void android.widget.TextView.<init>(android.content.Context, android.util.AttributeSet, int, int)
[ame.ShapesDemo] Explicit concurrent copying GC freed 24887(10MB) AllocSpace objects, 2(40KB) LOS objects, 85% free, 2MB/14MB, paused 96us total 11.120ms
**System.NullReferenceException:** 'Object reference not set to an instance of an object.'

Thread finished: <Thread Pool> #7
[mono-rt] [ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object.
[mono-rt]    at Xamarin.HotReload.Xaml.VisualTreeService.DiagnosticVisualTreeService.Dispose(Boolean isDisposing) in D:\a\_work\1\s\HotReload\Source\Xamarin.HotReload.Xaml\VisualTreeService\DiagnosticVisualTreeService.cs:line 75
[mono-rt]    at Xamarin.HotReload.Xaml.VisualTreeService.VisualTreeService.Finalize() in D:\a\_work\1\s\HotReload\Source\Xamarin.HotReload.Xaml\VisualTreeService\VisualTreeService.cs:line 138
[monodroid-assembly] open_from_bundles: failed to load assembly protobuf-net.dll
[monodroid-assembly] open_from_bundles: failed to load assembly protobuf-net.dll
[monodroid-assembly] open_from_bundles: failed to load assembly protobuf-net.Core.dll
The thread 0x7 has exited with code 0 (0x0).
```

**Comment by PureWeen** [comment]
@BenBtg Hot reload has gone through a few incompatible stages with Preview.11

This worked for me

1) Your `MainPage` isn't nested in a `NavigationPage` so AFAICT it's not going to navigate. 
2) can you try adding  <MauiVersion>6.0.101-nightly.2299</MauiVersion>  to your csproj file? 
3) I'm on the latest internal version of Visual Studio which should have all the lined up bits between hotreload and Maui Preview 11 that's coming out soon

**Comment by BenBtg** [comment]
> 
>     1. Your `MainPage` isn't nested in a `NavigationPage` so AFAICT it's not going to navigate.
> 

Sorry I forgot to push my fix for that particular issue. Pushed now.

**Comment by BenBtg** [comment]
> 2\. can you try adding  6.0.101-nightly.2299  to your csproj file?
@PureWeen 
Can you be a bit more specific? Where in the csproj?

**Comment by PureWeen** [comment]
> > 2. can you try adding  6.0.101-nightly.2299  to your csproj file?
> > @PureWeen
> > Can you be a bit more specific? Where in the csproj?

I just noticed the formatting made my explanation confusing :-/ 
I updated the text on my suggestion

**Comment by PureWeen** [comment]
@BenBtg is this still an issue?

**Comment by YuqinSong** [comment]
Not reproducible with Android 11. Null Reference exception isn't thrown as soon and one of the page is navigated to.
