### ISSUE TITLE
AbsoluteLayout.LayoutBounds crashes app when AutoSize is used

### ISSUE THREAD

**Issue by DeanFaizal** [dotnet/maui#3632]
### Description

AbsoluteLayout.LayoutBounds supports numeric values but crashes when AutoSize is used. For example this works:

                AbsoluteLayout.LayoutBounds="0, 0, 100, 100"       

But this will cause a crash:

                AbsoluteLayout.LayoutBounds="0, 0, AutoSize, AutoSize"       

### Steps to Reproduce

1. Create a new maui app with dotnet new maui -n AppName
2. Use this XAML for MainPage.xaml
3. `<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MauiAutoResizeTest.MainPage"
             BackgroundColor="{DynamicResource SecondaryColor}">

        <AbsoluteLayout>
            <Label 
                Text="Hello, World!" 
                AbsoluteLayout.LayoutBounds="0, 0, AutoSize, AutoSize"/>            
        </AbsoluteLayout>
</ContentPage>
`
4. Delete unnecessary code in MainPage.xaml.cs

### Version with bug

Preview 10 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android Pixel 4 API 30

### Did you find any workaround?

Don't use AutoSize. Use numeric values.

### Relevant log output

```shell
From a different app:

12-02 15:52:50.220  6630  6630 D AndroidRuntime: Shutting down VM
12-02 15:52:50.221  6630  6630 E AndroidRuntime: FATAL EXCEPTION: main
12-02 15:52:50.221  6630  6630 E AndroidRuntime: Process: com.companyname.BindableLayoutDemo, PID: 6630
12-02 15:52:50.221  6630  6630 E AndroidRuntime: android.runtime.JavaProxyThrowable: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
12-02 15:52:50.221  6630  6630 E AndroidRuntime:  ---> Microsoft.Maui.Controls.Xaml.XamlParseException: Position 86:21. Type converter failed: Cannot convert "1, 0, AutoSize, AutoSize" into Microsoft.Maui.Graphics.Rectangle
12-02 15:52:50.221  6630  6630 E AndroidRuntime:  ---> System.InvalidOperationException: Cannot convert "1, 0, AutoSize, AutoSize" into Microsoft.Maui.Graphics.Rectangle
12-02 15:52:50.221  6630  6630 E AndroidRuntime:    at Microsoft.Maui.Graphics.Converters.RectangleTypeConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
12-02 15:52:50.221  6630  6630 E AndroidRuntime:    at System.ComponentModel.TypeConverter.ConvertFromString(ITypeDescriptorContext context, CultureInfo culture, String text)
12-02 15:52:50.221  6630  6630 E AndroidRuntime:    at System.ComponentModel.TypeConverter.ConvertFromInvariantString(String text)
12-02 15:52:50.221  6630  6630 E AndroidRuntime:    at Microsoft.Maui.Controls.Xaml.TypeConversionExtensions.ConvertTo(Object value, Type toType, Func`1 getConverter, IServiceProvider serviceProvider, Exception& exception)
12-02 15:52:50.221  6630  6630 E AndroidRuntime:    --- End of inner exception stack trace ---
12-02 15:52:50.221  6630  6630 E AndroidRuntime:    at Microsoft.Maui.Controls.Xaml.ApplyPropertiesVisitor.SetPropertyValue(Object xamlelement, XmlName propertyName, Object value, Object rootElement, INode node, HydrationContext context, IXmlLineInfo lineInfo)
12-02 15:52:50.221  6630  6630 E AndroidRuntime:    at Microsoft.Maui.Controls.Xaml.ApplyPropertiesVisitor.Visit(ValueNode node, INode parentNode)
12-02 15:52:50.221  6630  6630 E AndroidRuntime:    at Microsoft.Maui.Controls.Xaml.ValueNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
12-02 15:52:50.221  6630  6630 E AndroidRuntime:    at Microsoft.Maui.Controls.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
12-02 15:52:50.221  6630  6630 E AndroidRuntime:    at Microsoft.Maui.Controls.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
12-02 15:52:50.221  6630  6630 E AndroidRuntime:    at Microsoft.Maui.Controls.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
12-02 15:52:50.221  6630  6630 E AndroidRuntime:    at Microsoft.Maui.Controls.Xaml.RootNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
12-02 15:52:50.221  6630  6630 E AndroidRuntime:    at Microsoft.Maui.Controls.Xaml.XamlLoader.Visit(RootNode rootnode, HydrationContext visitorContext, Boolean useDesignProperties)
12-02 15:52:50.221  6630  6630 E AndroidRuntime:    at Microsoft.Maui.Controls.Xaml.XamlLoader.Load(Object view, String xaml, Assembly rootAssembly, Boolean useDesignProperties)
12-02 15:52:50.221  6630  6630 E AndroidRuntime:    at Microsoft.Maui.Controls.Xaml.XamlLoader.Load(Object view, String xaml, Boolean useDesignProperties)
12-02 15:52:50.221  6630  6630 E AndroidRuntime:    at Microsoft.Maui.Controls.Xaml.XamlLoader.Load(Object view, Type callingType)
12-02 15:52:50.221  6630  6630 E AndroidRuntime:    at Microsoft.Maui.Controls.Xaml.Extensions.LoadFromXaml[UserProfilePage](UserProfilePage view, Type callingType)
12-02 15:52:50.221  6630  6630 E AndroidRuntime:    at BindableLayoutDemo.Views.UserProfilePage.InitializeComponent()
12-02 15:52:50.221  6630  6630 E AndroidRuntime:    at BindableLayoutDemo.Views.UserProfilePage..ctor()
12-02 15:52:50.221  6630  6630 E AndroidRuntime:    at System.Reflection.RuntimeConstructorInfo.InternalInvoke(Object obj, Object[] parameters, Boolean wrapExceptions)
12-02 15:52:50.221  6630  6630 E AndroidRuntime:    --- End of inner exception stack trace ---
12-02 15:52:50.221  6630  6630 E AndroidRuntime:    at System.Reflection.RuntimeConstructorInfo.InternalInvoke(Object obj, Object[] parameters, Boolean wrapExceptions)
12-02 15:52:50.221  6630  6630 E AndroidRuntime:    at System.RuntimeType.CreateInstanceMono(Boolean nonPublic, Boolean wrapExceptions)
12-02 15:52:50.221  6630  6630 E AndroidRuntime:    at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
12-02 15:52:50.221  6630  6630 E AndroidRuntime:    at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
12-02 15:52:50.221  6630  6630 E AndroidRuntime:    at System.Activator.CreateInstance(Type type, Boolean nonPublic)
12-02 15:52:50.221  6630  6630 E AndroidRuntime:    at System.Activator.CreateInstance(Type type)
12-02 15:52:50.221  6630  6630 E AndroidRuntime:    at BindableLayoutDemo.Views.MainPage.<.ctor>b__4_0(Type pageType)
12-02 15:52:50.221  6630  6630 E AndroidRuntime:    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__127_0(Object state)
12-02 15:52:50.221  6630  6630 E AndroidRuntime:    at Android.App.SyncContext.<>c__DisplayClass2_0.<Post>b__0()
12-02 15:52:50.221  6630  6630 E AndroidRuntime:    at Java.Lang.Thread.RunnableImplementor.Run()
12-02 15:52:50.221  6630  6630 E AndroidRuntime:    at Java.Lang.IRunnableInvoker.n_Run(IntPtr jnienv, IntPtr native__this)
12-02 15:52:50.221  6630  6630 E AndroidRuntime:        at mono.java.lang.RunnableImplementor.n_run(Native Method)
12-02 15:52:50.221  6630  6630 E AndroidRuntime:        at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
12-02 15:52:50.221  6630  6630 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:938)
12-02 15:52:50.221  6630  6630 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
12-02 15:52:50.221  6630  6630 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:223)
12-02 15:52:50.221  6630  6630 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7656)
12-02 15:52:50.221  6630  6630 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
12-02 15:52:50.223  6630  6630 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
12-02 15:52:50.223  6630  6630 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
12-02 15:52:50.224  6630  6630 W monodroid-assembly: Shared library 'liblog' not loaded, p/invoke '__android_log_print' may fail
12-02 15:52:50.226  6630  6630 I MonoDroid: UNHANDLED EXCEPTION:
12-02 15:52:50.230  6630  6630 I MonoDroid: Android.Runtime.JavaProxyThrowable: Exception of type 'Android.Runtime.JavaProxyThrowable' was thrown.
12-02 15:52:50.230  6630  6630 I MonoDroid:
12-02 15:52:50.230  6630  6630 I MonoDroid:   --- End of managed Android.Runtime.JavaProxyThrowable stack trace ---
12-02 15:52:50.230  6630  6630 I MonoDroid: android.runtime.JavaProxyThrowable: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
12-02 15:52:50.230  6630  6630 I MonoDroid:  ---> Microsoft.Maui.Controls.Xaml.XamlParseException: Position 86:21. Type converter failed: Cannot convert "1, 0, AutoSize, AutoSize" into Microsoft.Maui.Graphics.Rectangle
12-02 15:52:50.230  6630  6630 I MonoDroid:  ---> System.InvalidOperationException: Cannot convert "1, 0, AutoSize, AutoSize" into Microsoft.Maui.Graphics.Rectangle
12-02 15:52:50.231  6630  6630 I MonoDroid:    at Microsoft.Maui.Graphics.Converters.RectangleTypeConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
12-02 15:52:50.231  6630  6630 I MonoDroid:    at System.ComponentModel.TypeConverter.ConvertFromString(ITypeDescriptorContext context, CultureInfo culture, String text)
12-02 15:52:50.231  6630  6630 I MonoDroid:    at System.ComponentModel.TypeConverter.ConvertFromInvariantString(String text)
12-02 15:52:50.231  6630  6630 I MonoDroid:    at Microsoft.Maui.Controls.Xaml.TypeConversionExtensions.ConvertTo(Object value, Type toType, Func`1 getConverter, IServiceProvider serviceProvider, Exception& exception)
12-02 15:52:50.231  6630  6630 I MonoDroid:    --- End of inner exception stack trace ---
12-02 15:52:50.231  6630  6630 I MonoDroid:    at Microsoft.Maui.Controls.Xaml.ApplyPropertiesVisitor.SetPropertyValue(Object xamlelement, XmlName propertyName, Object value, Object rootElement, INode node, HydrationContext context, IXmlLineInfo lineInfo)
12-02 15:52:50.231  6630  6630 I MonoDroid:    at Microsoft.Maui.Controls.Xaml.ApplyPropertiesVisitor.Visit(ValueNode node, INode parentNode)
12-02 15:52:50.231  6630  6630 I MonoDroid:    at Microsoft.Maui.Controls.Xaml.ValueNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
12-02 15:52:50.231  6630  6630 I MonoDroid:    at Microsoft.Maui.Controls.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
12-02 15:52:50.231  6630  6630 I chatty  : uid=10177(com.companyname.BindableLayoutDemo) identical 1 line
12-02 15:52:50.231  6630  6630 I MonoDroid:    at Microsoft.Maui.Controls.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
12-02 15:52:50.231  6630  6630 I MonoDroid:    at Microsoft.Maui.Controls.Xaml.RootNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
12-02 15:52:50.231  6630  6630 I MonoDroid:    at Microsoft.Maui.Controls.Xaml.XamlLoader.Visit(RootNode rootnode, HydrationContext visitorContext, Boolean useDesignProperties)
12-02 15:52:50.231  6630  6630 I MonoDroid:    at Microsoft.Maui.Controls.Xaml.XamlLoader.Load(Object view, String xaml, Assembly rootAssembly, Boolean useDesignProperties)
12-02 15:52:50.231  6630  6630 I MonoDroid:    at Microsoft.Maui.Controls.Xaml.XamlLoader.Load(Object view, String xaml, Boolean useDesignProperties)
12-02 15:52:50.231  6630  6630 I MonoDroid:    at Microsoft.Maui.Controls.Xaml.XamlLoader.Load(Object view, Type callingType)
12-02 15:52:50.231  6630  6630 I MonoDroid:    at Microsoft.Maui.Controls.Xaml.Extensions.LoadFromXaml[UserProfilePage](UserProfilePage view, Type callingType)
12-02 15:52:50.231  6630  6630 I MonoDroid:    at BindableLayoutDemo.Views.UserProfilePage.InitializeComponent()
12-02 15:52:50.231  6630  6630 I MonoDroid:    at BindableLayoutDemo.Views.UserProfilePage..ctor()
12-02 15:52:50.231  6630  6630 I MonoDroid:    at System.Reflection.RuntimeConstructorInfo.InternalInvoke(Object obj, Object[] parameters, Boolean wrapExceptions)
12-02 15:52:50.231  6630  6630 I MonoDroid:    --- End of inner exception stack trace ---
12-02 15:52:50.231  6630  6630 I MonoDroid:    at System.Reflection.RuntimeConstructorInfo.InternalInvoke(Object obj, Object[] parameters, Boolean wrapExceptions)
12-02 15:52:50.231  6630  6630 I MonoDroid:    at System.RuntimeType.CreateInstanceMono(Boolean nonPublic, Boolean wrapExceptions)
12-02 15:52:50.231  6630  6630 I MonoDroid:    at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
12-02 15:52:50.231  6630  6630 I MonoDroid:    at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
12-02 15:52:50.231  6630  6630 I MonoDroid:    at System.Activator.CreateInstance(Type type, Boolean nonPublic)
12-02 15:52:50.231  6630  6630 I MonoDroid:    at System.Activator.CreateInstance(Type type)
12-02 15:52:50.231  6630  6630 I MonoDroid:    at BindableLayoutDemo.Views.MainPage.<.ctor>b__4_0(Type pageType)
12-02 15:52:50.231  6630  6630 I MonoDroid:    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__127_0(Object state)
12-02 15:52:50.231  6630  6630 I MonoDroid:    at Android.App.SyncContext.<>c__DisplayClass2_0.<Post>b__0()
12-02 15:52:50.231  6630  6630 I MonoDroid:    at Java.Lang.Thread.RunnableImplementor.Run()
12-02 15:52:50.231  6630  6630 I MonoDroid:    at Java.Lang.IRunnableInvoker.n_Run(IntPtr jnienv, IntPtr native__this)
12-02 15:52:50.231  6630  6630 I MonoDroid:     at mono.java.lang.RunnableImplementor.n_run(Native Method)
12-02 15:52:50.231  6630  6630 I MonoDroid:     at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
12-02 15:52:50.231  6630  6630 I MonoDroid:     at android.os.Handler.handleCallback(Handler.java:938)
12-02 15:52:50.231  6630  6630 I MonoDroid:     at android.os.Handler.dispatchMessage(Handler.java:99)
12-02 15:52:50.231  6630  6630 I MonoDroid:     at android.os.Looper.loop(Looper.java:223)
12-02 15:52:50.231  6630  6630 I MonoDroid:     at android.app.ActivityThread.main(ActivityThread.java:7656)
12-02 15:52:50.231  6630  6630 I MonoDroid:     at java.lang.reflect.Method.invoke(Native Method)
12-02 15:52:50.231  6630  6630 I MonoDroid:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
12-02 15:52:50.231  6630  6630 I MonoDroid:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
12-02 15:52:50.231  6630  6630 I MonoDroid:
12-02 15:52:50.231  6630  6630 I MonoDroid:   --- End of managed Android.Runtime.JavaProxyThrowable stack trace ---
12-02 15:52:50.231  6630  6630 I MonoDroid: android.runtime.JavaProxyThrowable: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
12-02 15:52:50.231  6630  6630 I MonoDroid:  ---> Microsoft.Maui.Controls.Xaml.XamlParseException: Position 86:21. Type converter failed: Cannot convert "1, 0, AutoSize, AutoSize" into Microsoft.Maui.Graphics.Rectangle
12-02 15:52:50.231  6630  6630 I MonoDroid:  ---> System.InvalidOperationException: Cannot convert "1, 0, AutoSize, AutoSize" into Microsoft.Maui.Graphics.Rectangle
12-02 15:52:50.231  6630  6630 I MonoDroid:    at Microsoft.Maui.Graphics.Converters.RectangleTypeConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
12-02 15:52:50.231  6630  6630 I MonoDroid:    at System.ComponentModel.TypeConverter.ConvertFromString(ITypeDescriptorContext context, CultureInfo culture, String text)
12-02 15:52:50.231  6630  6630 I MonoDroid:    at System.ComponentModel.TypeConverter.ConvertFromInvariantString(String text)
12-02 15:52:50.231  6630  6630 I MonoDroid:    at Microsoft.Maui.Controls.Xaml.TypeConversionExtensions.ConvertTo(Object value, Type toType, Func`1 getConverter, IServiceProvider serviceProvider, Exception& exception)
12-02 15:52:50.231  6630  6630 I MonoDroid:    --- End of inner exception stack trace ---
12-02 15:52:50.231  6630  6630 I MonoDroid:    at Microsoft.Maui.Controls.Xaml.ApplyPropertiesVisitor.SetPropertyValue(Object xamlelement, XmlName propertyName, Object value, Object rootElement, INode node, HydrationContext context, IXmlLineInfo lineInfo)
12-02 15:52:50.231  6630  6630 I MonoDroid:    at Microsoft.Maui.Controls.Xaml.ApplyPropertiesVisitor.Visit(ValueNode node, INode parentNode)
12-02 15:52:50.231  6630  6630 I MonoDroid:    at Microsoft.Maui.Controls.Xaml.ValueNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
12-02 15:52:50.231  6630  6630 I MonoDroid:    at Microsoft.Maui.Controls.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
12-02 15:52:50.231  6630  6630 I chatty  : uid=10177(com.companyname.BindableLayoutDemo) identical 1 line
12-02 15:52:50.231  6630  6630 I MonoDroid:    at Microsoft.Maui.Controls.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
12-02 15:52:50.231  6630  6630 I MonoDroid:    at Microsoft.Maui.Controls.Xaml.RootNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
12-02 15:52:50.231  6630  6630 I MonoDroid:    at Microsoft.Maui.Controls.Xaml.XamlLoader.Visit(RootNode rootnode, HydrationContext visitorContext, Boolean useDesignProperties)
12-02 15:52:50.231  6630  6630 I MonoDroid:    at Microsoft.Maui.Controls.Xaml.XamlLoader.Load(Object view, String xaml, Assembly rootAssembly, Boolean useDesignProperties)
12-02 15:52:50.231  6630  6630 I MonoDroid:    at Microsoft.Maui.Controls.Xaml.XamlLoader.Load(Object view, String xaml, Boolean useDesignProperties)
12-02 15:52:50.231  6630  6630 I MonoDroid:    at Microsoft.Maui.Controls.Xaml.XamlLoader.Load(Object view, Type callingType)
12-02 15:52:50.231  6630  6630 I MonoDroid:    at Microsoft.Maui.Controls.Xaml.Extensions.LoadFromXaml[UserProfilePage](UserProfilePage view, Type callingType)
12-02 15:52:50.231  6630  6630 I MonoDroid:    at BindableLayoutDemo.Views.UserProfilePage.InitializeComponent()
12-02 15:52:50.231  6630  6630 I MonoDroid:    at BindableLayoutDemo.Views.UserProfilePage..ctor()
12-02 15:52:50.231  6630  6630 I MonoDroid:    at System.Reflection.RuntimeConstructorInfo.InternalInvoke(Object obj, Object[] parameters, Boolean wrapExceptions)
12-02 15:52:50.231  6630  6630 I MonoDroid:    --- End of inner exception stack trace ---
12-02 15:52:50.231  6630  6630 I MonoDroid:    at System.Reflection.RuntimeConstructorInfo.InternalInvoke(Object obj, Object[] parameters, Boolean wrapExceptions)
12-02 15:52:50.231  6630  6630 I MonoDroid:    at System.RuntimeType.CreateInstanceMono(Boolean nonPublic, Boolean wrapExceptions)
12-02 15:52:50.231  6630  6630 I MonoDroid:    at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
12-02 15:52:50.231  6630  6630 I MonoDroid:    at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
12-02 15:52:50.231  6630  6630 I MonoDroid:    at System.Activator.CreateInstance(Type type, Boolean nonPublic)
12-02 15:52:50.231  6630  6630 I MonoDroid:    at System.Activator.CreateInstance(Type type)
12-02 15:52:50.231  6630  6630 I MonoDroid:    at BindableLayoutDemo.Views.MainPage.<.ctor>b__4_0(Type pageType)
12-02 15:52:50.231  6630  6630 I MonoDroid:    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__127_0(Object state)
12-02 15:52:50.231  6630  6630 I MonoDroid:    at Android.App.SyncContext.<>c__DisplayClass2_0.<Post>b__0()
12-02 15:52:50.231  6630  6630 I MonoDroid:    at Java.Lang.Thread.RunnableImplementor.Run()
12-02 15:52:50.231  6630  6630 I MonoDroid:    at Java.Lang.IRunnableInvoker.n_Run(IntPtr jnienv, IntPtr native__this)
12-02 15:52:50.231  6630  6630 I MonoDroid:     at mono.java.lang.RunnableImplementor.n_run(Native Method)
12-02 15:52:50.231  6630  6630 I MonoDroid:     at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
12-02 15:52:50.231  6630  6630 I MonoDroid:     at android.os.Handler.handleCallback(Handler.java:938)
12-02 15:52:50.231  6630  6630 I MonoDroid:     at android.os.Handler.dispatchMessage(Handler.java:99)
12-02 15:52:50.231  6630  6630 I MonoDroid:     at android.os.Looper.loop(Looper.java:223)
12-02 15:52:50.231  6630  6630 I MonoDroid:     at android.app.ActivityThread.main(ActivityThread.java:7656)
12-02 15:52:50.231  6630  6630 I MonoDroid:     at java.lang.reflect.Method.invoke(Native Method)
12-02 15:52:50.231  6630  6630 I MonoDroid:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
12-02 15:52:50.231  6630  6630 I MonoDroid:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
12-02 15:52:50.231  6630  6630 I MonoDroid:
12-02 15:52:50.234   528  2866 W ActivityTaskManager:   Force finishing activity com.companyname.BindableLayoutDemo/crc640bed7758a97237fc.MainActivity
```

**Comment by bwoebi** [comment]
Fwiw: AutoSize constant is equal to `-1` - i.e. `AbsoluteLayout.LayoutBounds="0, 0, -1, -1"` works as well.
