### ISSUE TITLE
Non-US characters in XAML file breaks compilation

### ISSUE THREAD

**Issue by pkar70** [dotnet/maui#3891]
### Description

I don't know if this is MAUI as such, but when I use non-US characters in XAML, I got
``` Error	MSB4018	The "XamlCTask" task failed unexpectedly. ```

And line causing this error is:
```         <Label HorizontalTextAlignment="Center" Margin="0,10,0,15" Text="Kaźń" FontSize="24"/> ```
same line 'collapsed' to ASCII compiles ok:
```         <Label HorizontalTextAlignment="Center" Margin="0,10,0,15" Text="Kazn" FontSize="24"/> ```

I checked file format, and it is UTF-8.

### Steps to Reproduce

Add line to MainPage.xaml

`<Label HorizontalTextAlignment="Center" Margin="0,10,0,15" Text="Kaźń" FontSize="24"/>

### Version with bug

Preview 10 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10.0.19044.1415

### Did you find any workaround?

No

### Relevant log output

```shell
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4018	The "XamlCTask" task failed unexpectedly.
System.Xml.XmlException: Invalid character in the given encoding. Line 18, position 94.

Server stack trace: 
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.InvalidCharRecovery(Int32& bytesCount, Int32& charsCount)
   at System.Xml.XmlTextReaderImpl.GetChars(Int32 maxCharsCount)
   at System.Xml.XmlTextReaderImpl.ReadData()
   at System.Xml.XmlTextReaderImpl.ParseAttributeValueSlow(Int32 curPos, Char quoteChar, NodeData attr)
   at System.Xml.XmlTextReaderImpl.ParseAttributes()
   at System.Xml.XmlTextReaderImpl.ParseElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at Microsoft.Maui.Controls.Xaml.XamlParser.ParseXamlElementFor(IElementNode node, XmlReader reader) in D:\a\1\s\src\Controls\src\Xaml\XamlParser.cs:line 59
   at Microsoft.Maui.Controls.Xaml.XamlParser.ReadNode(XmlReader reader, Boolean nested) in D:\a\1\s\src\Controls\src\Xaml\XamlParser.cs:line 172
   at Microsoft.Maui.Controls.Xaml.XamlParser.ParseXamlElementFor(IElementNode node, XmlReader reader) in D:\a\1\s\src\Controls\src\Xaml\XamlParser.cs:line 112
   at Microsoft.Maui.Controls.Xaml.XamlParser.ParseXaml(RootNode rootNode, XmlReader reader) in D:\a\1\s\src\Controls\src\Xaml\XamlParser.cs:line 47
   at Microsoft.Maui.Controls.Build.Tasks.XamlTask.ParseXaml(Stream stream, TypeReference typeReference) in D:\a\1\s\src\Controls\src\Build.Tasks\XamlTask.cs:line 60
   at Microsoft.Maui.Controls.Build.Tasks.XamlCTask.Execute(IList`1& thrownExceptions) in D:\a\1\s\src\Controls\src\Build.Tasks\XamlCTask.cs:line 175
   at Microsoft.Maui.Controls.Build.Tasks.XamlTask.Execute() in D:\a\1\s\src\Controls\src\Build.Tasks\XamlTask.cs:line 39
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Microsoft.Build.Framework.ITask.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	Anniversaries.Maui	C:\Users\pkar\.nuget\packages\microsoft.maui.controls.build.tasks\6.0.101-preview.10.2068\build\Microsoft.Maui.Controls.Build.Tasks.targets	150
```

**Comment by hartez** [comment]
> I checked file format, and it is UTF-8.

I wonder if the parser is respecting that. Maybe it's hard-coded to open the file in a different encoding?

**Comment by pkar70** [comment]
Such non-ASCII characters breaks compilation even within  tag :)

**Comment by StephaneDelcroix** [comment]
Does your file have the <?xml ?> header with the file encoding ?

**Comment by rmarinho** [comment]
fixed by #4851
