### ISSUE TITLE
UIWindow is not registered in the services for the MauiContext

### ISSUE THREAD

**Issue by Clancey** [dotnet/maui#3952]
### Description

When we create a UIWindow for a specific MauiContext we need to register it.

### Steps to Reproduce

Create a new Maui app, and on iOS present a new ViewController

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, macOS

### Affected platform versions

All Platforms

### Did you find any workaround?

Register the service automatically. But this doesn't work for multi window.
builder.Services.AddScoped(typeof(UIKit.UIWindow), (p) => UIKit.UIApplication.SharedApplication.KeyWindow);

### Relevant log output

```shell
System.InvalidOperationException: No service for type 'UIKit.UIWindow' has been registered.
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[UIWindow](IServiceProvider provider)
   at Microsoft.Maui.Platform.MauiContextExtensions.GetNativeWindow(IMauiContext mauiContext)
   at Microsoft.Maui.Platform.MauiContextExtensions.GetFlowDirection(IMauiContext mauiContext)
   at Microsoft.Maui.Platform.ViewExtensions.UpdateFlowDirection(UIView nativeView, IView view)
   at Microsoft.Maui.Handlers.ViewHandler.MapFlowDirection(IViewHandler handler, IView view)
   at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0[[Microsoft.Maui.IView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.IViewHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v)
   at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IElementHandler viewHandler, IElement virtualView)
   at Microsoft.Maui.PropertyMapper.UpdateProperties(IElementHandler viewHandler, IElement virtualView)
   at Microsoft.Maui.Handlers.ElementHandler.SetVirtualView(IElement view)
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.ILayout, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.LayoutView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IView view)
   at Microsoft.Maui.Handlers.LayoutHandler.SetVirtualView(IView view)
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.ILayout, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.LayoutView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IElement view)
   at Comet.View.SetViewHandler(IElementHandler handler)
   at Comet.View.Microsoft.Maui.IElement.set_Handler(IElementHandler value)
   at Microsoft.Maui.Platform.HandlerExtensions.ToHandler(IElement view, IMauiContext context)
   at Microsoft.Maui.Platform.HandlerExtensions.ToNative(IElement view, IMauiContext context)
   at Comet.iOS.CometView.SetView(IView view, Boolean forceRefresh)
   at Comet.iOS.CometView.set_CurrentView(IView value)
   at Comet.iOS.CometViewController.LoadView()
   at UIKit.UIViewController.PresentViewController(UIViewController viewControllerToPresent, Boolean animated, Action completionHandler)
```

**Comment by v-longmin** [comment]
@Clancey Could you share your repro project/solution, thanks?

**Comment by mattleibow** [comment]
This was fixed in a previous preview. It should now be be found with an explicit call to `services.GetService<UIWindow>` - but also it is obtainable from windows directly now. `myWindow.Handler.PlatformView`
