### ISSUE TITLE
Hot Restart Not Working for iOS on Windows with VS 2022 17.1.0 Preview 2

### ISSUE THREAD

**Issue by microspaze** [dotnet/maui#3975]
### Description

Use the default maui project template, run it to iphone device through USB.

```
[20:27:07]  (XMauiApp) Starting Hot Reload Session...
[20:27:25]  (XMauiApp) Xaml Changed for 'MainPage.xaml' in 'XMauiApp', sending to app...
[20:28:12]  (XMauiApp) Stopping a Hot Reload session due to ExplicitlyEnded ...
[20:28:12]  Stopped Hot Reload session.
[21:43:06]  (XMauiApp) .NET6 Project references MAUI.
[21:43:06]  (XMauiApp) Hot Reload got error getting user entry point, trying fallback: Mono.ArgumentNullOrEmptyException: Argument null or empty
Parameter name: fileName
   at Mono.Cecil.Mixin.CheckFileName(String fileName)
   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
   at Xamarin.HotReload.RunConfiguration.GetEntryPoint(ILogger logger) in D:\a\_work\1\s\HotReload\Source\Xamarin.HotReload.Bridge\RunConfiguration.cs:line 49
[21:43:06]  (XMauiApp) Starting Hot Reload Session...
[21:43:27]  (XMauiApp) Xaml Changed for 'MainPage.xaml' in 'XMauiApp', sending to app...
[21:44:39]  (XMauiApp) Xaml Changed for 'MainPage.xaml' in 'XMauiApp', sending to app...
```

BTW，it works fine to android device.

### Steps to Reproduce

1. Create a muai project by default vs template on windows
2. Debug run it to iOS device
3. Change the xaml file layout
4. View nothing changed on iOS device, got the error log
`[20:27:07]  (XMauiApp) Starting Hot Reload Session...
[20:27:25]  (XMauiApp) Xaml Changed for 'MainPage.xaml' in 'XMauiApp', sending to app...
[20:28:12]  (XMauiApp) Stopping a Hot Reload session due to ExplicitlyEnded ...
[20:28:12]  Stopped Hot Reload session.
[21:43:06]  (XMauiApp) .NET6 Project references MAUI.
[21:43:06]  (XMauiApp) Hot Reload got error getting user entry point, trying fallback: Mono.ArgumentNullOrEmptyException: Argument null or empty
Parameter name: fileName
   at Mono.Cecil.Mixin.CheckFileName(String fileName)
   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
   at Xamarin.HotReload.RunConfiguration.GetEntryPoint(ILogger logger) in D:\a\_work\1\s\HotReload\Source\Xamarin.HotReload.Bridge\RunConfiguration.cs:line 49
[21:43:06]  (XMauiApp) Starting Hot Reload Session...
[21:43:27]  (XMauiApp) Xaml Changed for 'MainPage.xaml' in 'XMauiApp', sending to app...
[21:44:39]  (XMauiApp) Xaml Changed for 'MainPage.xaml' in 'XMauiApp', sending to app...`

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15.2

**Comment by danardelean** [comment]
There is a comment in the MAUI Preview 11 post that states that it is recommended to fully uninstall VS 2022 Preview and install the Preview 2 from scratch This should make the Hot Reload work again

**Comment by microspaze** [comment]
> There is a comment in the MAUI Preview 11 post that states that it is recommended to fully uninstall VS 2022 Preview and install the Preview 2 from scratch This should make the Hot Reload work again

I have reinstall the vs 2022 preview, but not work.

**Comment by shimingsg** [comment]
verified not repro with vs 17.2.0 Preview 3.0 [32317.292.main] on iOS 15.2 Emulator
![3975](https://user-images.githubusercontent.com/20982341/158944759-4d5be463-df34-4f54-b911-214b7e5c958d.gif)
