### ISSUE TITLE
[Android] Not correctly rendering Paths

### ISSUE THREAD

**Issue by jsuarezruiz** [dotnet/maui#4052]
### Description

Not correctly rendering Paths
![image](https://user-images.githubusercontent.com/6755973/148925289-9a482368-2e0f-49be-84dd-eca6f24c1e32.png)

### Steps to Reproduce

1. Download [ShapesDemos.zip](https://github.com/dotnet/maui/files/7845673/ShapesDemos.zip)
2. Navigate to the "Path demos"

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

**Comment by jsuarezruiz** [comment]
Get some exceptions trying to render some Paths. For example, with the Clock sample:

```
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1[[Microsoft.Maui.Graphics.PointF, Microsoft.Maui.Graphics, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].get_Item(Int32 index)
   at Microsoft.Maui.Graphics.PathF.GetPointAsVector(List`1 curvePoints, Int32 index) in D:\a\1\s\src\Microsoft.Maui.Graphics\PathF.cs:line 1541
   at Microsoft.Maui.Graphics.PathF.FlattenCubicSegment(Int32 index, Double flatness, List`1 curvePoints, List`1 flattenedPoints) in D:\a\1\s\src\Microsoft.Maui.Graphics\PathF.cs:line 1485
   at Microsoft.Maui.Graphics.PathF.GetFlattenedPath(Single flatness, Boolean includeSubPaths) in D:\a\1\s\src\Microsoft.Maui.Graphics\PathF.cs:line 1423
   at Microsoft.Maui.Graphics.PathF.GetBoundsByFlattening(Single flatness) in D:\a\1\s\src\Microsoft.Maui.Graphics\PathF.cs:line 1359
   at Microsoft.Maui.Controls.Shapes.Shape.Microsoft.Maui.Graphics.IShape.PathForBounds(Rectangle viewBounds) in D:\a\1\s\src\Controls\src\Core\Shapes\Shape.cs:line 167
```

**Comment by shimingsg** [comment]
Verified repro with Android 11 and the above project.
