### ISSUE TITLE
ArgumentNullException in Resizetizer after adding svg images for splashscreen

### ISSUE THREAD

**Issue by tedekeroth** [dotnet/maui#4247]
### Description

THis error shows up after fiddling with adding svg files for a different splash screen:

```
Error	MAUI0000	System.ArgumentNullException: Value cannot be null.

Parameter name: s
   at System.IO.StringReader..ctor(String s)
   at Svg.ExCSS.StylesheetReader..ctor(String styleText) in D:\a\1\s\externals\SVG\Source\External\ExCSS\StylesheetReader.cs:line 26
   at Svg.ExCSS.Parser.Parse(String css) in D:\a\1\s\externals\SVG\Source\External\ExCSS\Parser.cs:line 56
   at Svg.SvgDocument.Open[T](XmlReader reader) in D:\a\1\s\externals\SVG\Source\SvgDocument.cs:line 481
   at Svg.SvgDocument.Open[T](String path, Dictionary`2 entities) in D:\a\1\s\externals\SVG\Source\SvgDocument.cs:line 322
   at Svg.Skia.SKSvg.Open(String path)
   at Svg.Skia.SKSvg.Load(String path)
   at Microsoft.Maui.Resizetizer.SkiaSharpSvgTools..ctor(String filename, Nullable`1 baseSize, Nullable`1 tintColor, ILogger logger) in D:\a\1\s\src\SingleProject\Resizetizer\src\SkiaSharpSvgTools.cs:line 26
   at Microsoft.Maui.Resizetizer.SkiaSharpTools.Create(Boolean isVector, String filename, Nullable`1 baseSize, Nullable`1 tintColor, ILogger logger) in D:\a\1\s\src\SingleProject\Resizetizer\src\SkiaSharpTools.cs:line 11
   at Microsoft.Maui.Resizetizer.Resizer.Resize(DpiPath dpi, String inputsFile) in D:\a\1\s\src\SingleProject\Resizetizer\src\Resizer.cs:line 96
   at Microsoft.Maui.Resizetizer.ResizetizeImages.ProcessImageResize(ResizeImageInfo img, DpiPath[] dpis, ConcurrentBag`1 resizedImages) in D:\a\1\s\src\SingleProject\Resizetizer\src\ResizetizeImages.cs:line 172
   at Microsoft.Maui.Resizetizer.ResizetizeImages.<>c__DisplayClass26_0.<ExecuteAsync>b__0(ResizeImageInfo img) in D:\a\1\s\src\SingleProject\Resizetizer\src\ResizetizeImages.cs:line 88
   at Microsoft.Maui.Resizetizer.AsyncTaskExtensions.<>c__DisplayClass0_0`1.<ParallelForEach>b__0(TSource s) in D:\a\1\s\src\SingleProject\Resizetizer\src\AsyncTaskExtensions.cs:line 21	MauiApp1	C:\Users\wagge\.nuget\packages\microsoft.maui.resizetizer.sdk\6.0.200-preview.12.2441\build\Microsoft.Maui.Resizetizer.Sdk.targets	463	

```

### Steps to Reproduce

0. Install VS Studio 2022 Preview 17.1.0 Preview 3.0
1. Install MAUI, latest
2. Create a new .NET Maui app (Preview)
3. Add one new svg file that you want to use as splash
4. Assign the Build Action MauiSplashScreen to the new svg you want to use. After I assign the new svg to MauiSplashScreen, the csproj file gets an auto change, where VS adds a two new ItemGroup, like this:
```
<ItemGroup>
	<MauiImage Remove="Resources\Images\test2.svg" />
</ItemGroup>

<ItemGroup>
	<None Remove="Resources\Images\test2.svg" />
</ItemGroup>
```
This looks strange to me.
5. Try to build => fails for me with
> APT2260	resource drawable/test2 (aka com.companyname.mauiapp1:drawable/test2) not found.	MauiApp1	D:\[SVN]\TestAndJunk\MauiApp1\MauiApp1\Resources\Resources\drawable\maui_splash_image.xml	2	
> 
> APT2061	failed linking file resources.	MauiApp1	C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\31.0.200-preview.12.2\tools\Xamarin.Android.Aapt2.targets	157	

6. I remove the two new ItemGroups, and save the csproj file => In the Properties list of the test2.svg, it no longer says "Build Action = MauiSplashScreen", but instead "MauiImage". However, the csproj file still reads:
```
<MauiSplashScreen Include="Resources\Images\test2.svg" />
```
![image](https://user-images.githubusercontent.com/10088477/150498566-bebac2fd-aac4-437e-9bab-d9335dce844f.png)

7. If I rebuild again, the error changes and now reads as the error above:
> MAUI0000	System.ArgumentNullException: Value cannot be null.

### Version with bug

Preview 12 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 10, Win 10 10.0.19042 Build 19042

### Did you find any workaround?

No.

### Relevant log output

```shell
Build started...
1>------ Build started: Project: MauiApp1, Configuration: Debug Any CPU ------
1>You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
1>C:\Users\wagge\.nuget\packages\microsoft.maui.resizetizer.sdk\6.0.200-preview.12.2441\build\Microsoft.Maui.Resizetizer.Sdk.targets(463,9): warning : MAUI0000
1>C:\Users\wagge\.nuget\packages\microsoft.maui.resizetizer.sdk\6.0.200-preview.12.2441\build\Microsoft.Maui.Resizetizer.Sdk.targets(463,9): error MAUI0000: System.ArgumentNullException: Value cannot be null.
1>C:\Users\wagge\.nuget\packages\microsoft.maui.resizetizer.sdk\6.0.200-preview.12.2441\build\Microsoft.Maui.Resizetizer.Sdk.targets(463,9): error MAUI0000: Parameter name: s
1>C:\Users\wagge\.nuget\packages\microsoft.maui.resizetizer.sdk\6.0.200-preview.12.2441\build\Microsoft.Maui.Resizetizer.Sdk.targets(463,9): error MAUI0000:    at System.IO.StringReader..ctor(String s)
1>C:\Users\wagge\.nuget\packages\microsoft.maui.resizetizer.sdk\6.0.200-preview.12.2441\build\Microsoft.Maui.Resizetizer.Sdk.targets(463,9): error MAUI0000:    at Svg.ExCSS.StylesheetReader..ctor(String styleText) in D:\a\1\s\externals\SVG\Source\External\ExCSS\StylesheetReader.cs:line 26
1>C:\Users\wagge\.nuget\packages\microsoft.maui.resizetizer.sdk\6.0.200-preview.12.2441\build\Microsoft.Maui.Resizetizer.Sdk.targets(463,9): error MAUI0000:    at Svg.ExCSS.Parser.Parse(String css) in D:\a\1\s\externals\SVG\Source\External\ExCSS\Parser.cs:line 56
1>C:\Users\wagge\.nuget\packages\microsoft.maui.resizetizer.sdk\6.0.200-preview.12.2441\build\Microsoft.Maui.Resizetizer.Sdk.targets(463,9): error MAUI0000:    at Svg.SvgDocument.Open[T](XmlReader reader) in D:\a\1\s\externals\SVG\Source\SvgDocument.cs:line 481
1>C:\Users\wagge\.nuget\packages\microsoft.maui.resizetizer.sdk\6.0.200-preview.12.2441\build\Microsoft.Maui.Resizetizer.Sdk.targets(463,9): error MAUI0000:    at Svg.SvgDocument.Open[T](String path, Dictionary`2 entities) in D:\a\1\s\externals\SVG\Source\SvgDocument.cs:line 322
1>C:\Users\wagge\.nuget\packages\microsoft.maui.resizetizer.sdk\6.0.200-preview.12.2441\build\Microsoft.Maui.Resizetizer.Sdk.targets(463,9): error MAUI0000:    at Svg.Skia.SKSvg.Open(String path)
1>C:\Users\wagge\.nuget\packages\microsoft.maui.resizetizer.sdk\6.0.200-preview.12.2441\build\Microsoft.Maui.Resizetizer.Sdk.targets(463,9): error MAUI0000:    at Svg.Skia.SKSvg.Load(String path)
1>C:\Users\wagge\.nuget\packages\microsoft.maui.resizetizer.sdk\6.0.200-preview.12.2441\build\Microsoft.Maui.Resizetizer.Sdk.targets(463,9): error MAUI0000:    at Microsoft.Maui.Resizetizer.SkiaSharpSvgTools..ctor(String filename, Nullable`1 baseSize, Nullable`1 tintColor, ILogger logger) in D:\a\1\s\src\SingleProject\Resizetizer\src\SkiaSharpSvgTools.cs:line 26
1>C:\Users\wagge\.nuget\packages\microsoft.maui.resizetizer.sdk\6.0.200-preview.12.2441\build\Microsoft.Maui.Resizetizer.Sdk.targets(463,9): error MAUI0000:    at Microsoft.Maui.Resizetizer.SkiaSharpTools.Create(Boolean isVector, String filename, Nullable`1 baseSize, Nullable`1 tintColor, ILogger logger) in D:\a\1\s\src\SingleProject\Resizetizer\src\SkiaSharpTools.cs:line 11
1>C:\Users\wagge\.nuget\packages\microsoft.maui.resizetizer.sdk\6.0.200-preview.12.2441\build\Microsoft.Maui.Resizetizer.Sdk.targets(463,9): error MAUI0000:    at Microsoft.Maui.Resizetizer.Resizer.Resize(DpiPath dpi, String inputsFile) in D:\a\1\s\src\SingleProject\Resizetizer\src\Resizer.cs:line 96
1>C:\Users\wagge\.nuget\packages\microsoft.maui.resizetizer.sdk\6.0.200-preview.12.2441\build\Microsoft.Maui.Resizetizer.Sdk.targets(463,9): error MAUI0000:    at Microsoft.Maui.Resizetizer.ResizetizeImages.ProcessImageResize(ResizeImageInfo img, DpiPath[] dpis, ConcurrentBag`1 resizedImages) in D:\a\1\s\src\SingleProject\Resizetizer\src\ResizetizeImages.cs:line 172
1>C:\Users\wagge\.nuget\packages\microsoft.maui.resizetizer.sdk\6.0.200-preview.12.2441\build\Microsoft.Maui.Resizetizer.Sdk.targets(463,9): error MAUI0000:    at Microsoft.Maui.Resizetizer.ResizetizeImages.<>c__DisplayClass26_0.<ExecuteAsync>b__0(ResizeImageInfo img) in D:\a\1\s\src\SingleProject\Resizetizer\src\ResizetizeImages.cs:line 88
1>C:\Users\wagge\.nuget\packages\microsoft.maui.resizetizer.sdk\6.0.200-preview.12.2441\build\Microsoft.Maui.Resizetizer.Sdk.targets(463,9): error MAUI0000:    at Microsoft.Maui.Resizetizer.AsyncTaskExtensions.<>c__DisplayClass0_0`1.<ParallelForEach>b__0(TSource s) in D:\a\1\s\src\SingleProject\Resizetizer\src\AsyncTaskExtensions.cs:line 21
1>Done building project "MauiApp1.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

**Comment by tedekeroth** [comment]
I made an update in the post above, to note that this problem also occurs when adding a normal PNG file.

**Comment by vannomad** [comment]
> 

Can you try making sure that in your region settings in windows, you are using "." instead of "," as a decimal point?

![image](https://user-images.githubusercontent.com/60275090/150950456-9da566dc-ff01-4a84-aa8a-ab5718523131.png)

**Comment by PaulChek** [comment]
> Can you try making sure that in your region settings in windows, you are using "." instead of "," as a decimal point?
I make sure of it but still same error

**Comment by mattleibow** [comment]
I believe there was an issue where moving/renaming/adding files in the solution explorer added weird thigs to the csproj that ended in nothing being set correctly. This should be fixed in preview 14, however, this will not help exiting projects in this bad state.

The solution is to remove all the weird/erroneous Maui* removes and updates.
