### ISSUE TITLE
xib files broken for .NET 6 IOS

### ISSUE THREAD

**Issue by jona-1993** [dotnet/maui#4834]
### Description

I have this exception when I load a xib file with: 

NSBundle.MainBundle.LoadNib ("test", this, null);

### Steps to Reproduce

1. Create a .NET 6 IOS project.
2. Add view controller (+ xib file). I named that "test"
3. Create a button with Xcode, I named this button "Testbt"
4. Call own xib file with : NSBundle.MainBundle.LoadNib ("test", this, null);
5. run app and crash

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15

### Relevant log output

```shell
Foundation.MonoTouchException: Objective-C exception thrown.  Name: NSUnknownKeyException Reason: [<AppDelegate 0x600000d502c0> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key Testbt.
Native stack trace:
	0   CoreFoundation                      0x00007fff203feba4 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff201a1be7 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff203fe845 -[NSException init] + 0
	3   Foundation                          0x00007fff20796332 -[NSObject(NSKeyValueCoding) setValue:forKey:] + 315
	4   UIKitCore                           0x00007fff24c1c820 -[UIRuntimeOutletConnection connect] + 109
	5   CoreFoundation                      0x00007fff203e92cd -[NSArray makeObjectsPerformSelector:] + 228
	6   UIKitCore                           0x00007fff24c125bc -[UINib instantiateWithOwner:options:] + 2185
	7   UIKitCore                           0x00007fff24c12eb6 -[NSBundle(UINSBundleAdditions) loadNibNamed:owner:options:] + 144
	8   libxamarin-dotnet-debug.dylib       0x000000010eca1679 xamarin_dyn_objc_msgSend + 217
	9   ???                                 0x0000000113c282da 0x0 + 4626481882

   at ObjCRuntime.Runtime.ThrowNSException(IntPtr ns_exception)
   at ObjCRuntime.Runtime.throw_ns_exception(IntPtr exc)
   at Foundation.NSBundle.LoadNib(String nibName, NSObject owner, NSDictionary options)
   at HelloiOS.AppDelegate.FinishedLaunching(UIApplication application, NSDictionary launchOptions) in /Users/jona1993/Desktop/net6-mobiles-samples-fresh/HelloiOS/AppDelegate.cs:line 21
--- End of stack trace from previous location ---
   at Foundation.NSBundle.LoadNib(String nibName, NSObject owner, NSDictionary options)
   at HelloiOS.AppDelegate.FinishedLaunching(UIApplication application, NSDictionary launchOptions) in /Users/jona1993/Desktop/net6-mobiles-samples-fresh/HelloiOS/AppDelegate.cs:line 21
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)
   at HelloiOS.Application.Main(String[] args) in /Users/jona1993/Desktop/net6-mobiles-samples-fresh/HelloiOS/Main.cs:line 12	0   CoreFoundation                      0x00007fff203feba4 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff201a1be7 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff203fe845 -[NSException init] + 0
	3   Foundation                          0x00007fff20796332 -[NSObject(NSKeyValueCoding) setValue:forKey:] + 315
	4   UIKitCore                           0x00007fff24c1c820 -[UIRuntimeOutletConnection connect] + 109
	5   CoreFoundation                      0x00007fff203e92cd -[NSArray makeObjectsPerformSelector:] + 228
	6   UIKitCore                           0x00007fff24c125bc -[UINib instantiateWithOwner:options:] + 2185
	7   UIKitCore                           0x00007fff24c12eb6 -[NSBundle(UINSBundleAdditions) loadNibNamed:owner:options:] + 144
	8   libxamarin-dotnet-debug.dylib       0x000000010eca1679 xamarin_dyn_objc_msgSend + 217
	9   ???                                 0x0000000113c282da 0x0 + 4626481882
```

**Comment by drasticactions** [comment]
This doesn't have anything to do with MAUI, it's [Xamarin-macios](https://github.com/xamarin/xamarin-macios)

I would file that there.
