### ISSUE TITLE
EXE files cannot be double-clicked to run

### ISSUE THREAD

**Issue by JusterZhu** [dotnet/maui#5327]
### Description

D:\git_community\MauiApp1\bin\Debug\net6.0-windows10.0.19041\win10-x64\MauiApp1.exe
D:\git_community\MauiApp1\bin\Debug\net6.0-windows10.0.19041\win10-x64\AppX\MauiApp1.exe

![image](https://user-images.githubusercontent.com/11714536/158538440-b8d769ba-cdea-4ff7-b89e-1c077a1199a2.png)

The exe files in the above two paths cannot be double-clicked to run , and it can't be started with Process .

### Steps to Reproduce

`using System.Diagnostics;

Process p = new Process();
p.StartInfo.FileName = "MauiApp1.exe";
p.StartInfo.Arguments = "http://www.baidu.com";
var isComplated = p.Start();
Console.WriteLine(isComplated);  //The result of running is true but no running .
Console.Read();`

### Version with bug

Preview 13 (current)

### Last version that worked well

Preview 13 (current)

### Affected platforms

Windows

### Affected platform versions

windows10.0.19041

**Comment by JusterZhu** [comment]
If it is convenient, I hope to answer this question .
https://techcommunity.microsoft.com/t5/app-development/net-maui-how-to-receive-process-parameters/m-p/3258459#M196

**Comment by jfversluis** [comment]
Is this a release build or a debug build?

**Comment by JusterZhu** [comment]
> Is this a release build or a debug build? And a regular .NET MAUI app or a Blazor one?

<1>debug build
<2>.NET MAUI

**Comment by jfversluis** [comment]
I think this might be fixed by #5377

**Comment by JusterZhu** [comment]
> I think this might be fixed by #5377

Not the same, nothing happens after double click. don't show window.

**Comment by mattleibow** [comment]
Is this an unpackaged app? 

https://github.com/dotnet/maui/issues/3166

Normal/default windows apps cannot be launched as they are not normal apps. Unpackaged apps are what you might be looking for.

**Comment by JusterZhu** [comment]
> Is this an unpackaged app?
> 
> #3166
> 
> Normal/default windows apps cannot be launched as they are not normal apps. Unpackaged apps are what you might be looking for.

yes, not packaged.

**Comment by shimingsg** [comment]
verified repro with vs 17.2.0 Preview 3.0 [32317.292.main] on windows, 
there is error event view:
```
Application: MauiApp5378.exe
CoreCLR Version: 6.0.222.6406
.NET Version: 6.0.2
Description: The process was terminated due to an unhandled exception.
Exception Info: System.DllNotFoundException: Unable to load DLL 'Microsoft.ui.xaml.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at MauiApp5378.WinUI.Program.XamlCheckProcessRequirements()
   at MauiApp5378.WinUI.Program.Main(String[] args) in C:\Users\Administrator\source\repos\MauiApp5378\MauiApp5378\obj\Debug\net6.0-windows10.0.19041\win10-x64\Platforms\Windows\App.g.i.cs:line 28
```

**Comment by JusterZhu** [comment]
> This should be supported now. Just some apis in Blazor and essentials is having a few issues.
> 
> However, based on the exception I think that the windows runtime is not installed.
> 
> Please make sure to follow the steps in the issue or in the official docs linked there.

Got it, I'll try it
