### ISSUE TITLE
[WinUI] DoPropertyChanged on a bound FormattedString property throws IMauiContext not found

### ISSUE THREAD

**Issue by JohnHDev** [dotnet/maui#5350]
### Description

Updated to VS2022 17.2.0 preview 2/Maui preview 14, an existing Maui solution that worked now throws the above exception on a bound FormattedString property.

Exception: System.InvalidOperationException
  HResult=0x80131509
  Message=IMauiContext not found.
  Source=Microsoft.Maui.Controls
  StackTrace:
   at Microsoft.Maui.Controls.ViewExtensions.RequireMauiContext(Element element, Boolean fallbackToAppMauiContext)
   at Microsoft.Maui.Controls.Platform.FormattedStringExtensions.UpdateInlines(TextBlock textBlock, FormattedString formattedString, Double defaultLineHeight, TextAlignment defaultHorizontalAlignment, Nullable`1 defaultFont, Color defaultColor, TextTransform defaultTextTransform)
   at Microsoft.Maui.Controls.Platform.FormattedStringExtensions.UpdateInlines(TextBlock textBlock, Label label)
   at Microsoft.Maui.Controls.Platform.TextBlockExtensions.UpdateText(TextBlock platformControl, Label label)
   at Microsoft.Maui.Controls.Label.MapText(LabelHandler handler, Label label)
   at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IElementHandler viewHandler, IElement virtualView)
   at Microsoft.Maui.PropertyMapper.UpdateProperty(IElementHandler viewHandler, IElement virtualView, String property)
   at Microsoft.Maui.Handlers.ElementHandler.UpdateValue(String property)
   at Microsoft.Maui.Controls.Element.OnPropertyChanged(String propertyName)
   at Microsoft.Maui.Controls.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, Boolean silent)
   at Microsoft.Maui.Controls.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes)
   at Microsoft.Maui.Controls.BindingExpression.ApplyCore(Object sourceObject, BindableObject target, BindableProperty property, Boolean fromTarget)
   at Microsoft.Maui.Controls.BindingExpression.Apply(Boolean fromTarget)
   at Microsoft.Maui.Controls.BindingExpression.BindingExpressionPart.<PropertyChanged>b__49_0()
   at Microsoft.Maui.Controls.DispatcherExtensions.DispatchIfRequired(IDispatcher dispatcher, Action action)
   at Microsoft.Maui.Controls.BindingExpression.BindingExpressionPart.PropertyChanged(Object sender, PropertyChangedEventArgs args)
   at Microsoft.Maui.Controls.BindingExpression.WeakPropertyChangedProxy.OnPropertyChanged(Object sender, PropertyChangedEventArgs e)
   at <snipped>

### Steps to Reproduce

Create a VM with FormattedString as a property that returns a new FormattedString with a number of spans, bind it to a label on a page.
Add a button that would trigger a DoPropertyChanged on the VM for that property.
Run on Windows
Tap the button

### Version with bug

Preview 14 (Current)

### Last version that worked well

Preview 13 (current)

### Affected platforms

Windows

### Affected platform versions

Windows, don't know which

### Did you find any workaround?

No

**Comment by Amir-Care** [comment]
Thank you so much for your bug report! Unfortunately, i cannot reproduce your issue with the information above, could you provide a sample project that i can reproduce your issue? That should greatly speed up the process, thanks!

**Comment by JohnHDev** [comment]
Replace the default MainPage class with these 2:

```
    public class MainPageViewModel : INotifyPropertyChanged
    {
        private string _title = "bla";
        public string Title
        {
            get => _title;
            set
            {
                _title = value;
                DoPropertyChanged(nameof(Title));
                DoPropertyChanged(nameof(FormattedTitle));
            }
        }

        public FormattedString FormattedTitle
        {
            get
            {
                var result = new FormattedString();
                result.Spans.Add(new Span() { Text = "a" });
                result.Spans.Add(new Span() { Text = _title });
                result.Spans.Add(new Span() { Text = "b" });

                return result;
            }
        }

        public event PropertyChangedEventHandler PropertyChanged;
        void DoPropertyChanged(string propertyName = null) => PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
    }

    public class MainPage: ContentPage
    {
        public MainPage()
        {
            var model = new MainPageViewModel();
            BindingContext = model;

            var stack = new VerticalStackLayout();
            var label1 = new Label();
            label1.SetBinding(Label.FormattedTextProperty, "FormattedTitle");
            stack.Add(label1);

            var button = new Button()
            {
                Text = "Tap"
            };

            button.Clicked += (s, e) => model.Title = model.Title + "1";
            stack.Add(button);

            Content = stack;
        }
    }
```

**Comment by Amir-Care** [comment]
Verified not repro with Version 17.2.0 Preview 2.0 [32208.484.main] on Windows

**Comment by JohnHDev** [comment]
@Amir-Care just to check, you said not repro, but added the verified tag. I presume you can reproduce the crash with the example code I supplied?
