### ISSUE TITLE
Essentials Email ComposeAsync Fails on WinUI with Attachment

### ISSUE THREAD

**Issue by Orgbrat** [dotnet/maui#5353]
### Description

Using the sample code from the Essentials Samples for EMail, when I execute the line "await Email.ComposeAsync(message);" Windows throws an error of "request is not supported. (0x80070032)" with an exception StackTrace of the following:

at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Windows.ApplicationModel.Email.IEmailManagerStaticsMethods.ShowComposeNewEmailAsync(IObjectReference _obj, EmailMessage message)
   at Microsoft.Maui.Essentials.Email.<PlatformComposeAsync>d__6.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at HealthManager.Services.EmailService.<SendEmail>d__1.MoveNext() in E:\Work - VS.NET 2022\Maui\HealthManager.Maui\src\HealthManager\Services\EmailService.cs:line 32

### Steps to Reproduce

Using the sample code from the Essentials Samples for EMail, when I execute the line "await Email.ComposeAsync(message);" Windows throws an error of "request is not supported. (0x80070032)"

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows SDK 10.0.19041

### Did you find any workaround?

NO

**Comment by v-longmin** [comment]
@Orgbrat Could you share your repro project/code, thanks?

**Comment by Orgbrat** [comment]
I have uploaded a sample project that fails exactly as my development project. I tried it on two different machines to make sure it was not just my development machine doing something crazy.  Maybe this will help...

[MauiRCTest1.zip](https://github.com/dotnet/maui/files/8500200/MauiRCTest1.zip)

Orgbrat
