### ISSUE TITLE
Navigation.PopModalAsync not working on iOS

### ISSUE THREAD

**Issue by J-Swift** [dotnet/maui#5517]
### Description

#3959 was closed but it was never fixed. Tested in p14

### Steps to Reproduce

Steps copied from original issue:

1. New Maui Project.
2. Create a ContentPage with a button that calls Navigation.PopModalAysnc on the button click.
3. Modify the MainPage to include a button that calls Navigation.PushModalAsync on the content pages created on step two.
4. Run the solution on iPhone local device.

Alternatively clone the sample repository https://github.com/PedroCigaw/MauiModalTest.git and run the sample on iOS.

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

All versions

### Did you find any workaround?

Dont use Modal pages

**Comment by jfversluis** [comment]
Still seems to reproduce. Stacktrace:

> Error: Object reference not set to an instance of an object.
   at Microsoft.Maui.Controls.Platform.ModalNavigationManager.get_RootViewController()
   at Microsoft.Maui.Controls.Platform.ModalNavigationManager.PopModalAsync(Boolean animated)
2022-03-23 15:59:23.634529+0100 MauiModalTest[77296:2525961]    at Microsoft.Maui.Controls.Window.NavigationImpl.OnPopModal(Boolean animated)
   at MauiModalTest.ModalPage.Button_Clicked(Object sender, EventArgs e) in /Users/jfversluis/Downloads/MauiModalTest-master/MauiModalTest/ModalPage.cs:line 35

**Comment by PureWeen** [comment]
Should be fixed by
https://github.com/dotnet/maui/pull/5566
