### ISSUE TITLE
ListView, TableView crashes on windows

### ISSUE THREAD

**Issue by buyaa-n** [dotnet/maui#5551]
### Description

When try to load a view having a `ListView` or `TabbedPane` crashes with error:
```log
System.Runtime.InteropServices.COMException
  HResult=0x80004005
  Message=Error HRESULT E_FAIL has been returned from a call to a COM component.
  Source=WinRT.Runtime
  StackTrace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Microsoft.UI.Xaml.IFrameworkElementOverrides.global::Microsoft.UI.Xaml.IFrameworkElementOverrides.MeasureOverride(Size availableSize)
   at Microsoft.UI.Xaml.FrameworkElement.MeasureOverride(Size availableSize)
   at ABI.Microsoft.UI.Xaml.IFrameworkElementOverrides.Do_Abi_MeasureOverride_0(IntPtr thisPtr, Size availableSize, Size* result)
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Microsoft.UI.Xaml.IUIElement.global::Microsoft.UI.Xaml.IUIElement.Measure(Size availableSize)
   at Microsoft.Maui.Controls.Handlers.Compatibility.VisualElementRenderer`2.MeasureOverride(Size availableSize) in E:\maui\maui\src\Controls\src\Core\Compatibility\Handlers\Windows\VisualElementRenderer.cs:line 61
   at ABI.Microsoft.UI.Xaml.IFrameworkElementOverrides.Do_Abi_MeasureOverride_0(IntPtr thisPtr, Size availableSize, Size* result)
```

### Steps to Reproduce

1. Run the SingleProject sample
2. Navigate to Compatibility -> ListView or Compatibility -> TableView
3. It crashes

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows

### Did you find any workaround?

No, just removed ListView part from the page to unblock myself

**Comment by VSadov** [comment]
I saw this as well when trying to reproduce an unrelated bug (#4050). 

```cs
        protected override WSize MeasureOverride(global::Windows.Foundation.Size availableSize)
        {
            if (Element == null || availableSize.Width * availableSize.Height == 0)
                return new WSize(0, 0);
            if (Control != null)
            {
                Control.Measure(availableSize);   <--- COMException E_FAIL here.
            }
```
