### ISSUE TITLE
Verify Blazor Hybrid on Android doesn't log exceptions by default

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/maui#5837]
In https://github.com/dotnet/maui/issues/5750, we've had a report about Android apps logging a stack trace like:

```
[System] Uncaught exception thrown by finalizer
[System] java.lang.IllegalStateException: Warning: Router objects should be explicitly closed when no longer required otherwise you may leak handles.
[System] 	at UM.finalize(chromium-TrichromeWebViewGoogle.apk-stable-410410686:4)
[System] 	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:291)
[System] 	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:278)
[System] 	at java.lang.Daemons$Daemon.run(Daemons.java:139)
[System] 	at java.lang.Thread.run(Thread.java:923)
[System] Caused by: java.lang.Exception: AutocloseableRouter allocated at:
[System] 	at UM.<init>(chromium-TrichromeWebViewGoogle.apk-stable-410410686:7)
[System] 	at EP.<init>(chromium-TrichromeWebViewGoogle.apk-stable-410410686:6)
[System] 	at org.chromium.content.browser.framehost.RenderFrameHostImpl.<init>(chromium-TrichromeWebViewGoogle.apk-stable-410410686:10)
[System] 	at org.chromium.content.browser.framehost.RenderFrameHostImpl.create(chromium-TrichromeWebViewGoogle.apk-stable-410410686:1)
[System] 	at J.N.MjidYpBx(Native Method)
```

We should verify that this doesn't apply to the default app, but rather is something specific to someone's browser application code. If BlazorWebView is actually leaking something by default we certainly want to fix that.

**Comment by TanayParikh** [comment]
Tried this out on a default blazor maui app. Opened app, navigated amongst pages, tried the `Counter` and then opened the external survey prompt URL. I did not see any exceptions via logcat. 

started logcat via:

```
adb shell
# logcat
```

per https://developer.android.com/studio/command-line/logcat#Syntax.

If this were a common exception I believe those actions would've produced the exception in the logcat log (I did see other random exceptions, but they didn't seem severe / related).

I'm closing this issue out, but please let me know if there's anything else we need to try out here. cc/ @Eilon

**Comment by Eilon** [comment]
I did File / New MAUI Blazor, and I did get the error in the log:

![image](https://user-images.githubusercontent.com/202643/161854491-3ab7d846-52cb-441c-972d-68f27d0971cf.png)

I'm not sure what adb shell / logcat shows by default, but the Device Log UI in VS pops up a VS Tab Window that has logs in it. Here's the text I copied out:

```
Time	Device Name	Type	PID	Tag	Message
04-05 14:40:38.062	pixel_5_-_api_30	Error	9911	System	Caused by: java.lang.Exception: AutocloseableRouter allocated at:
	at UM.<init>(chromium-TrichromeWebViewGoogle.apk-stable-410410686:7)
	at EP.<init>(chromium-TrichromeWebViewGoogle.apk-stable-410410686:6)
	at org.chromium.content.browser.framehost.RenderFrameHostImpl.<init>(chromium-TrichromeWebViewGoogle.apk-stable-410410686:10)
	at org.chromium.content.browser.framehost.RenderFrameHostImpl.create(chromium-TrichromeWebViewGoogle.apk-stable-410410686:1)
	at J.N.MjidYpBx(Native Method)
	at org.chromium.content.browser.webcontents.WebContentsImpl.r0(chromium-TrichromeWebViewGoogle.apk-stable-410410686:3)
	at K7.g(chromium-TrichromeWebViewGoogle.apk-stable-410410686:5)
	at com.android.webview.chromium.WebViewChromium.postMessageToMainFrame(chromium-TrichromeWebViewGoogle.apk-stable-410410686:4)
	at android.webkit.WebView.postWebMessage(WebView.java:1971)
	at crc64d693e2d9159537db.WebKitWebViewClient_JavaScriptValueCallback.n_onReceiveValue(Native Method)
	at crc64d693e2d9159537db.WebKitWebViewClient_JavaScriptValueCallback.onReceiveValue(WebKitWebViewClient_JavaScriptValueCallback.java:30)
	at X6.a(chromium-TrichromeWebViewGoogle.apk-stable-410410686:1)
	at org.chromium.android_webview.AwContents.w(chromium-TrichromeWebViewGoogle.apk-stable-410410686:1)
	at xr.run(Unknown Source:4)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loop(Looper.java:183)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

04-05 14:40:38.062	pixel_5_-_api_30	Error	9911	System	java.lang.IllegalStateException: Warning: Router objects should be explicitly closed when no longer required otherwise you may leak handles.
	at UM.finalize(chromium-TrichromeWebViewGoogle.apk-stable-410410686:4)
	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:291)
	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:278)
	at java.lang.Daemons$Daemon.run(Daemons.java:139)
	at java.lang.Thread.run(Thread.java:923)
```

**Comment by Eilon** [comment]
Here's the other way to get to it if you don't have the Android toolbar in VS enabled:

![image](https://user-images.githubusercontent.com/202643/161854745-2b07eae9-06e1-4d21-b1e2-58bdf6d76cb3.png)

**Comment by Eilon** [comment]
Note: I have no idea what this error means or whether it's bad, but it definitely shows up in a default MAUI Blazor app.

**Comment by TanayParikh** [comment]
Hmm that's odd, did you do anything special within the app, or just started it?

I wonder why it doesn't show up via shell -> logcat.

**Comment by TanayParikh** [comment]
Ahh, it may be because this is a `warning` and not an `error`. Potentially not logged by default depending on the default log level.

**Comment by Eilon** [comment]
It is of type "Error" in the log (see first screenshot).

**Comment by TanayParikh** [comment]
> Error	9911	System	java.lang.IllegalStateException: Warning:

**Comment by Eilon** [comment]
That "warning" text is I think just part of the exception message, not an actual category. The _type_ of the log message is definitely "error."

**Comment by TanayParikh** [comment]
https://github.com/dotnet/maui/blob/cfc3fab4b07db3c5aeabf20819efc7b140144215/src/BlazorWebView/src/Maui/Android/AndroidWebKitWebViewManager.cs#L57

and

https://github.com/dotnet/maui/blob/cfc3fab4b07db3c5aeabf20819efc7b140144215/src/BlazorWebView/src/Maui/Android/AndroidWebKitWebViewManager.cs#L76

seem to be the offending calls. Looking how we can close the "router" to avoid the leak.

**Comment by TanayParikh** [comment]
Getting back to this now, I'm still not able to repro (tried `maui-blazor` as well as the single project sample app). @Eilon did you do anything special in the app to trigger the exception or did you immediately run into it?

**Comment by Eilon** [comment]
100% completely default Blazor MAUI app. All I did was run it and have the log window open.

**Comment by Eilon** [comment]
Can meet to demonstrate and maybe figure out how to repro on your machine.

**Comment by TanayParikh** [comment]
(discussed offline). The issue is with Android 11 / API 30, it does **not** repro on 12 / 31.

<img width="561" alt="image" src="https://user-images.githubusercontent.com/14852843/162033727-0650999d-ba54-415b-b19d-818338cd34d9.png">

It repros on the maui Blazor test app, after a few clicks.

**Comment by TanayParikh** [comment]
Spent some more time on this issue, but I'm not seeing the root cause anywhere.

Based on https://github.com/flutter/flutter/issues/2509#issuecomment-204604837, the exception we're seeing indicates we're failing to dispose of a particular Android / Java object somewhere, however it's unclear what that actual object is.

Based on the stacktrace it's the `UM` class, which seems to be an optimized/anonymyzed class within Android / Chrome(?)

```
04-05 14:40:38.062	pixel_5_-_api_30	Error	9911	System	java.lang.IllegalStateException: Warning: Router objects should be explicitly closed when no longer required otherwise you may leak handles.
	at UM.finalize(chromium-TrichromeWebViewGoogle.apk-stable-410410686:4)
```
(from Eilon) vs, I get:

```
2022-04-06 14:53:54.400 11032-11048/com.microsoft.maui.mauiblazorwebview.devicetests E/System: java.lang.IllegalStateException: Warning: Router objects should be explicitly closed when no longer required otherwise you may leak handles.
        at TM.finalize(chromium-TrichromeWebViewGoogle.apk-stable-410410681:4)
```

(note UM.Finalize vs. TM.Finalize) hence why I believe it's an internal, optimized, anonymous class. On the flutter PR we were looking at (https://github.com/flutter/flutter/issues/2950 / https://github.com/flutter/engine/pull/2646, it was clear the issue was with `mojo`, but that's not the case here.

Elsewhere online, others are seeing the same, but there doesn't seem to be any solutions. This looks like a potentially broader issue.

- https://stackoverflow.com/questions/65426547/possible-memory-leak-in-webview-postwebmessage
- https://stackoverflow.com/questions/66226138/jetpack-compose-webview-fails-to-show-pages-randomly

Note, the issue cannot be reproduced in the latest Android 12 / Android API 31. This leaves the distinct possibility this is a bug within Android / Chrome itself (complaining about a non issue perhaps?).

Regardless, during my investigation I did find one area where we're failing to dispose / close an Android object. Created this PR to resolve that:
- https://developer.android.com/reference/android/webkit/WebView?hl=en#createWebMessageChannel()
- https://developer.android.com/reference/android/webkit/WebMessagePort#close()

**Comment by homeyf** [comment]
Verified this issue with Visual Studio Enterprise 17.8.0 Preview 1.0. Can repro on Android platform with template project.
