### ISSUE TITLE
App Crash From Multiple Theme Switches

### ISSUE THREAD

**Issue by mpkagel** [dotnet/maui#5848]
### The Issue

The problem here is that the `AppThemeBinding` works by subscribing to a global WeakEventManager. So any label/page/etc... that subscribes to this will theoretically be GC'd at some point but until that happens you're going to see events getting fired against the page that's no longer reachable. The exception in this issue is coming from the Labels on the ItemsPage. 

I've attached a simplified repro to show what's happening. 
- open repo
- set a break point inside the `AppendToMapping` if statement
- click the button that pushes a page
- click the back button
- change the theme
- the break point will now get hit for the label that's on the second page. 

[If you check the stack trace you'll see it's being generated from the WeakEventManager that's part of the AppThemeBinding](https://github.com/dotnet/maui/blob/92e876e4842443b50b5bf0d6a7edbea46de2e646/src/Controls/src/Core/AppThemeBinding.cs#L12)

[AppThemeBinding.zip](https://github.com/dotnet/maui/files/8445664/AppThemeBinding.zip)

I think in Forms we didn't hit this issue mainly becausewe were super aggressive about disposing of rendererswe added tons of if (View.IsAlive()) checks every where just in case a property changed event fired at a weird point in time

### Description

This is something that I ran across from changing style and theme multiple times on one page in Android.
Switching theme and going back to the same detail page multiple times causes the app to crash.
I've attached a sample project to try and demonstrate the issue.

[MauiFlyout.zip](https://github.com/dotnet/maui/files/8421697/MauiFlyout.zip)

### Steps to Reproduce

Steps for reproducing the bug in Android:
1. Open the flyout menu.
2. Click Browse.
3. Click on the first item to go to its detail page.
4. Click the back button.
5. Open the flyout menu.
6. Click About.
7. Click the switch to change the theme.
8. Repeat steps 1-7. Repeating these steps ~6-7 times causes the app to crash.

https://user-images.githubusercontent.com/29716444/161850326-18bd1ff8-b012-402a-b237-e97035b90f65.mp4

### Version with bug

Preview 14 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12

**Comment by Redth** [comment]
```

[mono-rt] [ERROR] FATAL UNHANDLED EXCEPTION: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
[mono-rt]  ---> System.ObjectDisposedException: Cannot access a disposed object.
[mono-rt] Object name: 'AndroidX.AppCompat.Widget.AppCompatTextView'.
[mono-rt]    at Java.Interop.JniPeerMembers.AssertSelf(IJavaPeerable self) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.cs:line 152
[mono-rt]    at Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualVoidMethod(String encodedMember, IJavaPeerable self, JniArgumentValue* parameters) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:line 24
[mono-rt]    at Android.Widget.TextView.SetTextColor(Color color) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net6.0/android-32/mcw/Android.Widget.TextView.cs:line 7265
[mono-rt]    at Microsoft.Maui.Platform.TextViewExtensions.UpdateTextColor(TextView textView, ITextStyle textStyle) in D:\a\_work\1\s\src\Core\src\Platform\Android\TextViewExtensions.cs:line 37
[mono-rt]    at Microsoft.Maui.Handlers.LabelHandler.MapTextColor(ILabelHandler handler, ILabel label) in D:\a\_work\1\s\src\Core\src\Handlers\Label\LabelHandler.Android.cs:line 47
[mono-rt]    at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0[[Microsoft.Maui.ILabel, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.ILabelHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v) in D:\a\_work\1\s\src\Core\src\PropertyMapper.cs:line 160
[mono-rt]    at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IElementHandler viewHandler, IElement virtualView) in D:\a\_work\1\s\src\Core\src\PropertyMapper.cs:line 35
[mono-rt]    at Microsoft.Maui.PropertyMapper.UpdateProperty(IElementHandler viewHandler, IElement virtualView, String property) in D:\a\_work\1\s\src\Core\src\PropertyMapper.cs:line 60
[mono-rt]    at Microsoft.Maui.Handlers.ElementHandler.UpdateValue(String property) in D:\a\_work\1\s\src\Core\src\Handlers\Element\ElementHandler.cs:line 82
[mono-rt]    at Microsoft.Maui.Controls.Element.OnPropertyChanged(String propertyName) in D:\a\_work\1\s\src\Controls\src\Core\Element.cs:line 383
[mono-rt]    at Microsoft.Maui.Controls.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, Boolean silent) in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 525
[mono-rt]    at Microsoft.Maui.Controls.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes) in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 461
[mono-rt]    at Microsoft.Maui.Controls.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes) in D:\a\_work\1\s\src\Controls\src\Core\BindableObject.cs:line 398
[mono-rt]    at Microsoft.Maui.Controls.AppThemeBinding.<>c__DisplayClass7_0.<ApplyCore>g__Set|0() in D:\a\_work\1\s\src\Controls\src\Core\AppThemeBinding.cs:line 54
[mono-rt]    at Microsoft.Maui.Controls.DispatcherExtensions.DispatchIfRequired(IDispatcher dispatcher, Action action) in D:\a\_work\1\s\src\Controls\src\Core\DispatcherExtensions.cs:line 53
[mono-rt]    at Microsoft.Maui.Controls.AppThemeBinding.ApplyCore(Boolean dispatch) in D:\a\_work\1\s\src\Controls\src\Core\AppThemeBinding.cs:line 50
[mono-rt]    at Microsoft.Maui.Controls.AppThemeBinding.<.ctor>b__2_0(Object o, AppThemeChangedEventArgs e) in D:\a\_work\1\s\src\Controls\src\Core\AppThemeBinding.cs:line 12
[mono-rt]    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[mono-rt]    --- End of inner exception stack trace ---
[mono-rt]    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[mono-rt]    at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
[mono-rt]    at Microsoft.Maui.WeakEventManager.HandleEvent(Object sender, Object args, String eventName) in D:\a\_work\1\s\src\Core\src\WeakEventManager.cs:line 78
[mono-rt]    at Microsoft.Maui.Controls.Application.TriggerThemeChangedActual() in D:\a\_work\1\s\src\Controls\src\Core\Application.cs:line 243
[mono-rt]    at Microsoft.Maui.Controls.Application.set_UserAppTheme(AppTheme value) in D:\a\_work\1\s\src\Controls\src\Core\Application.cs:line 173
[mono-rt]    at MauiFlyout.Services.AppThemeService.SetTheme(AppTheme theme) in C:\Users\jondi\Downloads\5848\MauiFlyout\MauiFlyout\Services\AppThemeService.cs:line 11
[mono-rt]    at MauiFlyout.ViewModels.AboutViewModel.ChangeUserAppTheme(Boolean activateDarkMode) in C:\Users\jondi\Downloads\5848\MauiFlyout\MauiFlyout\ViewModels\AboutViewModel.cs:line 43
[mono-rt]    at MauiFlyout.ViewModels.AboutViewModel.set_IsDarkModeEnabled(Boolean value) in C:\Users\jondi\Downloads\5848\MauiFlyout\MauiFlyout\ViewModels\AboutViewModel.cs:line 23
```
