### ISSUE TITLE
Unable to run Windows application

### ISSUE THREAD

**Issue by eerhardt** [dotnet/maui#5975]
### Description

I am unable to launch my Maui Windows application from the command line. With Android I can with `dotnet build -t:Run`. But this doesn't work with Windows. Note that `dotnet run -f net6.0-windows10.0.19041.0` also doesn't work.

cc @mattleibow 

### Steps to Reproduce

1. `dotnet new maui`
2. `dotnet build -t:Run -f net6.0-windows10.0.19041.0`

### Results

```
C:\git\maui\bin\dotnet\sdk\6.0.300-preview.22207.16\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(901,5): er
ror MSB3073: The command "C:\DotNetTest\MauiTest\bin\Debug\net6.0-windows10.0.19041.0\win10-x64\MauiTest.exe " exited w
ith code -532462766. [C:\DotNetTest\MauiTest\MauiTest.csproj]
```

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

All Windows

### Relevant log output

```shell
When attaching a Debugger to the process, I see:

System.DllNotFoundException
  HResult=0x80131524
  Message=Unable to load DLL 'Microsoft.ui.xaml.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)
  Source=MauiTest
  StackTrace:
   at MauiTest.WinUI.Program.XamlCheckProcessRequirements()
   at MauiTest.WinUI.Program.Main(String[] args) in C:\DotNetTest\MauiTest\obj\Debug\net6.0-windows10.0.19041.0\win10-x64\Platforms\Windows\App.g.i.cs:line 28
```

**Comment by v-longmin** [comment]
Verified the issue on 17.2.0 Preview 2.1 [32317.152.main], it's repro.

**Comment by jsuarezruiz** [comment]
Could be related with https://github.com/dotnet/maui/pull/5923? cc @mattleibow

**Comment by mattleibow** [comment]
Opened this discussion to be able to find out the way to do things: https://github.com/microsoft/WindowsAppSDK/discussions/2391

**Comment by mattleibow** [comment]
Might even be related to this discussion: https://github.com/microsoft/WindowsAppSDK/issues/55

Not sure if there is a way to launch MSIX apps via the CLI, but could be via unpackaged...

**Comment by mattjohnsonpint** [comment]
Same here.  Been doing everything on a Mac so far, where `dotnet build -t:Run -f net6.0-maccatalyst` (or -ios, -android, etc.) works fine.  Thought I'd try it out on Windows and ran into this issue.  It only works if I do a full VS2022 preview install and run from within VS.  Seems like it should work on the command line for consistent experience.

**Comment by geronimus** [comment]
Now that the .NET MAUI general availability release has happened, is there any timeline on resolving this issue?

Some [Microsoft material released last year](https://youtu.be/hoC5FIblKz8?t=457) indicated that it was perfectly feasible to develop .NET MAUI apps using only VS Code. (Which means you must be able to do it using only vi too... which is my goal... crazy though that may seem!)

To me, this means that there may be a work-around for this issue that the Microsoft insiders have access to. Perhaps it could be posted here as a viable alternative. That is, until the non-VS experience on Windows works out-of-the-box.

**Comment by mattleibow** [comment]
I also see that doing a `dotnet build -t:Run -f net6.0-windows10.0.19041.0` on a fresh project does not restore or build. I had to add a separate `dotnet build` as well in order for it to do something.

However, I was able to get something to run with unpackaged:

```
dotnet build /restore -f net6.0-windows10.0.19041.0  /p:WindowsPackageType=None
dotnet build -t:Run -f net6.0-windows10.0.19041.0  /p:WindowsPackageType=None
```

But we still also need to get `dotnet run` working with anything: 

```
The launch profile "(Default)" could not be applied.
A usable launch profile could not be located.
```

**Comment by mattleibow** [comment]
Moving the issue here as well: https://github.com/microsoft/WindowsAppSDK/issues/2922

**Comment by DrusTheAxe** [comment]
> Not sure if there is a way to launch MSIX apps via the CLI, but could be via unpackaged...

Activation via AUMID:

`shell:appsfolder\...aumid...` e.g. ShellExecute("shell:appsfolder\Microsoft.WindowsCalculator_8wekyb3d8bbwe!App") launches Calculator. Try it from the Win-R prompt.

Activation via Executable:

On Win11 if you run a packaged app's exe from its package directory Windows figures out it's a packaged app and runs it e.g. `CreateProcess(GetPackagePath(p) + "\foo.exe")` is equivalent to `ActivateApplication(fooApplicationUserModelId)`. This is sometimes referred to as PackagedCreateProcess.

NOTE: This requires the executable be declared for only 1 app in the package e.g. you can declare multiple `<Application>` in appxmanifest.xml (technically, 0-100) but `<Application Executable="foo.exe"...>` must be unique. If 2 `<Application>`s declare the same Executable Windows can't launch the app by running its exe. As you might guess, when running the packaged exe Windows does a xref against apps in the package using the exe so 2+ would be ambiguous.

Alternatively on 20H1+, if the executable has a Fusion manifest declaring `<msix...>` then you can CreateProcess() the app's exe. CreateProcess sees the manifested identity, does a lookup against packages registered to the user to find the application's details and voila! This is equivalent to PackagedCreateProcess, though it requires `<msix>` (on the upside, it predates PackagedCreateProcess so available further downlevel). See https://docs.microsoft.com/en-us/windows/win32/sbscs/application-manifests#msix. NOTE: The docs talk about sparse MSIX packages; that's a scenario where this is useful, but `<msix>` is a mechanism, doesn't care about WHY you use it - you can use `<msix>` whether or not you have a sparse package.

NOTE: Running an executable by typing it into a command line invokes CreateProcess (or ShellExecute, depending on the command prompt). These are options you can use to interactively launch MSIX packaged apps. Programmatically there's additional options.

**Comment by AvtsVivek** [comment]
I think the [issue I raised here on SO](https://stackoverflow.com/q/74271977/1977871) is similar.

**Comment by homeyf** [comment]
Verified this issue with Visual Studio 17.6.0 Preview 2.0. Repro on Windows application from command line.

**Comment by tilkinsc** [comment]
Still an issue in 2024 btw

**Comment by samhouts** [comment]
This is still blocked on https://github.com/microsoft/microsoft-ui-xaml/issues/7331 and other related issues. Thank you for your patience!

**Comment by ardalis** [comment]
Still an issue today.

**Comment by tilkinsc** [comment]
How do you actually build/run a maui app on windows then? I only use VSCode.

**Comment by sdheer** [comment]
i use the following for dotnet build
`dotnet build -f net8.0-windows10.0.19041.0 -c Debug -p:PublishReadyToRun=true -p:WindowsPackageType=None`
and for run/
`dotnet run -f net8.0-windows10.0.19041.0 -c Debug -p:PublishReadyToRun=true -p:WindowsPackageType=None`

**Comment by georgedobrin** [comment]
`dotnet run -f net8.0-windows10.0.19041.0 -c Debug -p:PublishReadyToRun=true -p:WindowsPackageType=None`

Works for me too, thanks @sdheer !

**Comment by kubaflo** [comment]
This remains blocked on microsoft-ui-xaml and the thread now includes a working command-line workaround. Closing here as externally owned/blocked.

**Comment by kubaflo** [comment]
Reopening — this issue should not have been closed.

It carries `s/verified` (a maintainer or partner reproduced it), `s/triaged` (it already went through triage). Those labels mean the report was already confirmed as a real product defect, so it is not eligible for backlog cleanup closure. Closure here requires specific fix evidence (a merged PR that closes it, or a `fixed-in-*` label), and there was none.

Sorry for the noise, and thanks to everyone who flagged it.

> Disclosure: this comment was generated by AI.
