### ISSUE TITLE
RC1 Compilation failed to complete

### ISSUE THREAD

**Issue by eddyjl077** [dotnet/maui#6022]
### Description

After VS Update to 2022 Preview 3

Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.300-rc.1.4\tools\Xamarin.Android.D8.targets(79,5): error : java.lang.RuntimeException: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: C:\Users\ADMIN\.nuget\packages\xamarin.google.guava.listenablefuture\1.0.0.5\buildTransitive\net6.0-android31.0\..\..\jar\guava-listenablefuture.jar : com/google/common/util/concurrent/ListenableFuture.class

### Steps to Reproduce

open old project with preview 14

### Version with bug

Release Candidate 1

### Last version that worked well

Preview 14 (current)

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

api 30.5554

### Did you find any workaround?

No

### Relevant log output

```shell
Exception in thread "main" java.lang.RuntimeException: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: C:\Users\ADMIN\.nuget\packages\xamarin.google.guava.listenablefuture\1.0.0.5\buildTransitive\net6.0-android31.0\..\..\jar\guava-listenablefuture.jar:com/google/common/util/concurrent/ListenableFuture.class
1>	at com.android.tools.r8.internal.oO0.a(SourceFile:92)
1>	at com.android.tools.r8.D8.main(D8.java:4)
1>Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: C:\Users\ADMIN\.nuget\packages\xamarin.google.guava.listenablefuture\1.0.0.5\buildTransitive\net6.0-android31.0\..\..\jar\guava-listenablefuture.jar:com/google/common/util/concurrent/ListenableFuture.class
1>	at Version.fakeStackEntry(Version_3.1.51.java:0)
1>	at com.android.tools.r8.internal.oO0.a(SourceFile:68)
1>	at com.android.tools.r8.internal.oO0.a(SourceFile:28)
1>	at com.android.tools.r8.internal.oO0.a(SourceFile:27)
1>	at com.android.tools.r8.internal.oO0.b(SourceFile:3)
1>	at com.android.tools.r8.D8.a(D8.java:17)
1>	at com.android.tools.r8.D8.a(D8.java:15)
1>	at com.android.tools.r8.internal.oO0.a(SourceFile:84)
1>	... 1 more
1>Caused by: com.android.tools.r8.internal.b: Type com.google.common.util.concurrent.ListenableFuture is defined multiple times: C:\Users\ADMIN\.nuget\packages\xamarin.google.guava.listenablefuture\1.0.0.5\buildTransitive\net6.0-android31.0\..\..\jar\guava-listenablefuture.jar:com/google/common/util/concurrent/ListenableFuture.class, obj\Debug\net6.0-android\lp\160\jl\libs\31DC00DFF80FA577.jar:com/google/common/util/concurrent/ListenableFuture.class
1>	at com.android.tools.r8.internal.il1.a(SourceFile:14)
1>	at com.android.tools.r8.internal.il1.a(SourceFile:22)
1>	at com.android.tools.r8.internal.lf1.b(SourceFile:6)
1>	at com.android.tools.r8.internal.lf1.a(SourceFile:23)
1>	at com.android.tools.r8.internal.lf1.a(SourceFile:10)
1>	at java.base/java.util.concurrent.ConcurrentHashMap.merge(ConcurrentHashMap.java:2048)
1>	at com.android.tools.r8.internal.lf1.a(SourceFile:6)
1>	at com.android.tools.r8.graph.r2$a.f(SourceFile:4)
1>	at com.android.tools.r8.dex.b.a(SourceFile:96)
1>	at com.android.tools.r8.dex.b.a(SourceFile:21)
1>	at com.android.tools.r8.D8.a(D8.java:21)
1>	at com.android.tools.r8.D8.d(D8.java:11)
1>	at com.android.tools.r8.D8.c(D8.java:1)
1>	at com.android.tools.r8.internal.oO0.a(SourceFile:24)
1>	... 5 more
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.300-rc.1.4\tools\Xamarin.Android.D8.targets(79,5): error : java.lang.RuntimeException: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: C:\Users\ADMIN\.nuget\packages\xamarin.google.guava.listenablefuture\1.0.0.5\buildTransitive\net6.0-android31.0\..\..\jar\guava-listenablefuture.jar : com/google/common/util/concurrent/ListenableFuture.class
1>
```

**Comment by codeaphex** [comment]
Had the same, probably "fixed" by removing dependencies referencing the old MAUI version, like the Community Toolkit.

**Comment by Mephisztoe** [comment]
There have been reports on problems such as this that also lead to the MAUI Community Toolkit (Preview 8) being the root cause. In fact, the team around the MCT just released Preview 9 which is not RC yet, but at least it's built against .NET MAUI RC1. So you may give this one a try.

**Comment by I4-PJ** [comment]
I had the same. Finally solved the issue with upgrading a former NET6 android project and its dependency to Maui.Essentials to MAUI Library project with using <UsingMauiEssentials>true</UsingMauiEssentials> in project file.

**Comment by BinaryAssault** [comment]
This was fixed for me after upgrading the MAUI community toolkit from pre8 to pre9

**Comment by jfversluis** [comment]
Please make sure to update to all the latest bits and follow the [migration guide](https://github.com/dotnet/maui/wiki/Migrating-to-RC1)

If it then still doesn't work, let us know!

**Comment by aherrick** [comment]
still seeing this with:

` <PackageReference Include="Xamarin.CommunityToolkit.MauiCompat" Version="2.0.1-preview1007" />`

**Comment by pfiggins** [comment]
Seeing the same issue with Plugin.InAppBilling. https://github.com/jamesmontemagno/InAppBillingPlugin/issues/462

Also seeing a completely different breaking issue with Xamarin.Firebase.Messaging. https://github.com/xamarin/GooglePlayServicesComponents/issues/595

@jfversluis Can you recommend any way to rollback VS to preview 2.1? Most of our dev team either updated to preview 3 or never had 2.1. We can only build our app on 2.1, so it's really killing us over here with no viable workaround in sight. I managed to find a hidden command to rollback the MAUI workload, but it's bombing as well. Leaving us dead in the water.

```
dotnet workload install android ios maccatalyst tvos macos maui wasm-tools --from-rollback-file https://maui.blob.core.windows.net/metadata/rollbacks/preview.14.json --no-cache

Workload(s) 'android ios' are already installed.
Updated advertising manifest microsoft.net.workload.emscripten.
Updated advertising manifest microsoft.net.sdk.tvos.
Updated advertising manifest microsoft.net.sdk.maui.
Updated advertising manifest microsoft.net.workload.mono.toolchain.
Updated advertising manifest microsoft.net.sdk.macos.
Updated advertising manifest microsoft.net.sdk.maccatalyst.
Updated advertising manifest microsoft.net.sdk.android.
Updated advertising manifest microsoft.net.sdk.ios.
Downloading microsoft.net.sdk.android.manifest-6.0.300.msi.x64 (31.0.200-preview.14.106)
Workload installation failed. Rolling back installed packs...
Downloading microsoft.net.sdk.android.manifest-6.0.300.msi.x64 (32.0.300-rc.1.4)
Downloading microsoft.net.sdk.ios.manifest-6.0.300.msi.x64 (15.4.100-rc.1.125)
Downloading microsoft.net.sdk.maccatalyst.manifest-6.0.300.msi.x64 (15.4.100-rc.1.125)
Downloading microsoft.net.sdk.macos.manifest-6.0.300.msi.x64 (12.3.100-rc.1.125)
Downloading microsoft.net.sdk.maui.manifest-6.0.300.msi.x64 (6.0.300-rc.1.5355)
Downloading microsoft.net.sdk.tvos.manifest-6.0.300.msi.x64 (15.4.100-rc.1.125)
Downloading microsoft.net.workload.mono.toolchain.manifest-6.0.300.msi.x64 (6.0.4)
Downloading microsoft.net.workload.emscripten.manifest-6.0.300.msi.x64 (6.0.4)
Workload installation failed: One or more errors occurred. (microsoft.net.sdk.android.manifest-6.0.300.msi.x64::31.0.200-preview.14.106 is not found in NuGet feeds https://api.nuget.org/v3/index.json".)
```

Appreciate any help you can provide!
