### ISSUE TITLE
Shell flyout item text sometimes blank

### ISSUE THREAD

**Issue by david-maw** [dotnet/maui#6033]
### Description

Under some circumstances flyout item text does not show.

### Steps to Reproduce

1. unzip the multipage project from [MultiPage-blankflyout.zip](https://github.com/dotnet/maui/files/8478221/MultiPage-blankflyout.zip)
2. Compile and run the project on Windows
3. Initially you should see this: ![multipage-startuppage](https://user-images.githubusercontent.com/12423046/163102776-58795002-5dbd-4314-916c-c5f3217b6254.jpg)
4. When the initial countdown is done it will switch to this:
![multipage-mainpage](https://user-images.githubusercontent.com/12423046/163102876-db29efc1-8584-4fb3-b1ed-8f55707795ac.jpg)
5. Then click on the hamburger icon to show the flyout, you should see a blank flyout, like this: ![multipage-blankflyout](https://user-images.githubusercontent.com/12423046/163102971-e570cdb1-bcbf-4f83-85a6-d309be7fbb0b.jpg)

This only happens if the StartupPage is used, if you take it and the TabBar out of AppShell.xaml the flyout text reappears.

It seems to be ok in Android.
 

### Version with bug

Release Candidate 1

### Last version that worked well

Preview 14 (current)

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

Windows 10

### Did you find any workaround?

No

**Comment by kristinx0211** [comment]
@david-maw it is not repro, it works on windows with vs 17.3.0 Preview 1.0 [32411.352.main]. please see the video to make sure if it is your expected result.
https://user-images.githubusercontent.com/99457000/163109771-1422eddc-ed6e-41ec-bcfb-f0c8f96a30de.mp4

**Comment by NogginBox** [comment]
I think I'm seeing this bug too.

When I catch handled exceptions I see this after clicking on one of the blank navigation items:

```
System.Runtime.InteropServices.COMException (0x88000FA8): 0x88000FA8
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Microsoft.UI.Xaml.Controls.INavigationView2.global::Microsoft.UI.Xaml.Controls.INavigationView2.set_PaneDisplayMode(NavigationViewPaneDisplayMode value)
   at Microsoft.UI.Xaml.Controls.NavigationView.set_PaneDisplayMode(NavigationViewPaneDisplayMode value)
   at Microsoft.Maui.Platform.NavigationViewExtensions.UpdateFlyoutBehavior(MauiNavigationView navigationView, IFlyoutView flyoutView)
   at Microsoft.Maui.Controls.Handlers.ShellHandler.MapFlyoutBehavior(ShellHandler handler, IFlyoutView flyoutView)
   at Microsoft.Maui.Controls.Shell.Microsoft.Maui.Controls.IShellController.AppearanceChanged(Element source, Boolean appearanceSet)
   at Microsoft.Maui.Controls.ShellSection.SendAppearanceChanged()
   at Microsoft.Maui.Controls.ShellSection.UpdateDisplayedPage()
   at Microsoft.Maui.Controls.ShellContent.set_ContentCache(Page value)
   at Microsoft.Maui.Controls.ShellContent.Microsoft.Maui.Controls.IShellContentController.GetOrCreateContent()
   at Microsoft.Maui.Controls.Handlers.ShellSectionHandler.SyncNavigationStack(Boolean animated)
   at Microsoft.Maui.Controls.Handlers.ShellSectionHandler.MapCurrentItem(ShellSectionHandler handler, ShellSection item)
   at Microsoft.Maui.PropertyMapper.UpdateProperties(IElementHandler viewHandler, IElement virtualView)
   at Microsoft.Maui.Controls.Handlers.ShellSectionHandler.SetVirtualView(IElement view)
   at Microsoft.Maui.Controls.Handlers.ShellItemHandler.MapCurrentItem(ShellItemHandler handler, ShellItem item)
   at Microsoft.Maui.PropertyMapper.UpdateProperties(IElementHandler viewHandler, IElement virtualView)
   at Microsoft.Maui.Controls.Handlers.ShellItemHandler.SetVirtualView(IElement view)
   at Microsoft.Maui.Controls.Platform.ShellView.CreateShellItemView()
   at Microsoft.Maui.Controls.Platform.ShellView.SwitchShellItem(ShellItem newItem, Boolean animate)
   at Microsoft.Maui.Controls.Handlers.ShellHandler.MapCurrentItem(ShellHandler handler, Shell view)
   at Microsoft.Maui.Controls.Element.OnPropertyChanged(String propertyName)
   at Microsoft.Maui.Controls.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, Boolean silent)
   at Microsoft.Maui.Controls.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes)
   at Microsoft.Maui.Controls.ShellNavigationManager.GoToAsync(ShellNavigationParameters shellNavigationParameters, ShellNavigationRequest navigationRequest)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

**Comment by KarlSearl** [comment]
I am also getting this since adding a login page within shell.

![image](https://user-images.githubusercontent.com/64684177/169324288-0a62f624-3249-485c-a1fa-969c827ea77a.png)

**Comment by KarlSearl** [comment]
forcing a refresh  ( added FlyoutWidhtafter the flyout is rendered) and hitting hot reload

![image](https://user-images.githubusercontent.com/64684177/169324691-741483c4-7d02-4275-a671-19ae110159a3.png)
