### ISSUE TITLE
[6.0.300-rc.1] iOS debugging/hot reload doesn't work. "XAML Hot Reload encountered a problem and failed to start."

### ISSUE THREAD

**Issue by lukaszkn** [dotnet/maui#6055]
### Description

Deployment to iOS device works as expected and app launches however not debugging/hot reload works in Visual Studio Version 17.2.0 Preview 3.0
"XAML Hot Reload encountered a problem and failed to start."

### Steps to Reproduce

1. Create sample .NET app
2. Set iPhone as target deployment
3. Start the project

Deployment to iOS device works as expected and app launches however not debugging/hot reload works in Visual Studio Version 17.2.0 Preview 3.0
"XAML Hot Reload encountered a problem and failed to start."

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Preview 12

### Affected platforms

iOS

### Affected platform versions

iOS 15

### Did you find any workaround?

No

### Relevant log output

```shell
[12:54:33]  Caught exception in AgentStatusChangedHandler at 385: Xamarin.HotReload.EntryPointException: MauiApp1: Hot Reload got error getting user entry point, iOS ---> Mono.ArgumentNullOrEmptyException: Argument null or empty
Parameter name: fileName
   at Mono.Cecil.Mixin.CheckFileName(String fileName)
   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
   at Xamarin.HotReload.RunConfiguration.GetEntryPoint() in D:\a\_work\1\s\HotReload\Source\Xamarin.HotReload.Bridge\RunConfiguration.cs:line 51
   --- End of inner exception stack trace ---
   at Xamarin.HotReload.RunConfiguration.GetEntryPoint() in D:\a\_work\1\s\HotReload\Source\Xamarin.HotReload.Bridge\RunConfiguration.cs:line 56
   at Xamarin.HotReload.HotReloadBridge.Start() in D:\a\_work\1\s\HotReload\Source\Xamarin.HotReload.Bridge\HotReloadBridge.cs:line 97
   at Xamarin.HotReload.RunConfiguration.GetEntryPoint() in D:\a\_work\1\s\HotReload\Source\Xamarin.HotReload.Bridge\RunConfiguration.cs:line 56
   at Xamarin.HotReload.HotReloadBridge.Start() in D:\a\_work\1\s\HotReload\Source\Xamarin.HotReload.Bridge\HotReloadBridge.cs:line 97
[12:54:33]  XAML Hot Reload encountered a problem and failed to start. Use Help -> Report a Problem if the issues persists.
[12:54:33]  Stopping All Hot Reload sessions due to Failed ...
[12:54:33]  (MauiApp1) Stopping a Hot Reload session due to Failed ...
[12:54:33]  Stopped Hot Reload session.
```

**Comment by drasticactions** [comment]
@lukaszkn

This is a MaciOS / Visual Studio tooling problem. XAML Hot Reload requires symbols to be available to bootstrap the hot reload process, and it couldn't find any. This issue would, most likely, also affect debugging in general in your application (as in, setting breakpoints and having them be hit).

I would file this as feedback for Visual Studio (https://developercommunity.visualstudio.com/home); this is not a MAUI issue.
