### ISSUE TITLE
[iOS] Type x:Double not found in xmlns http://schemas.microsoft.com/winfx/2009/xaml

### ISSUE THREAD

**Issue by mrswdev** [dotnet/maui#6070]
### Description

The issue described in #5531 still exists.

**PLEASE NOTE!**
- Deploying to an Iphone, connected as local device to a **Windows** computer, does work.
- Deploying to the same device via **Mac** build-host throws the error.

### Steps to Reproduce

See issue #5531

1. Open Visual Studio and create a new Maui app.
2. Add  <x:Double x:Key="some_value">50</x:Double> to Resources\Styles.xaml.
3. Add CodeSign infos to .csproj.
4. Connect device to Mac build-host.
5. Start debugging on **iOS Remote Device**.

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, I was *not* able test on other platforms

### Affected platform versions

iOS 15.3.1

**Comment by mrswdev** [comment]
Seems to be a linking problem.
The error does not occur, when Linker behavior is set to "Don't Link"

**Comment by evandigby** [comment]
> Seems to be a linking problem. The error does not occur, when Linker behavior is set to "Don't Link"

When I set to "Don't Link" (or anything other than "Link All" I get the following error:

```
1>ld: framework not found System
1>clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I am using RC1.

**Comment by KonyukhovSergey** [comment]
Hello, we are developing [DevExpress .NET MAUI controls](https://www.devexpress.com/maui/) and experienced the same issue. This issue has a High priority for us and we do not have a workaround. Thank you for your help.

**Comment by evandigby** [comment]
@KonyukhovSergey does setting "Don't Link" change anything for you?

If so, have you had a look at this, if the error is similar/the same? https://github.com/dotnet/maui/issues/4227#issuecomment-1108759032

**Comment by StephaneDelcroix** [comment]
one way to workaround this is to force compilation of Styles.xaml by adding the line

```xaml
<?xaml-comp compile="true" ?>
```

at the top of the file (but after the `<?xml />` one, if present)

**Comment by SailDev** [comment]
Not really.

Test results for a new RC2 Maui template.
Deployed to a physically connected IPhone via remote MacOS build host.

![Screenshot 2022-05-02 114710](https://user-images.githubusercontent.com/94922306/166217996-e944af0f-18cd-442f-9de3-bf983b294a67.png)

---

Don't Link = O.K.

---
**Link Framework SDKs Only = Error**

![Screenshot 2022-05-02 120005](https://user-images.githubusercontent.com/94922306/166217902-7368e6e4-c5b6-4dd3-8eff-718b0018d0ad.png)

---

**Link All = Different error**

![Screenshot 2022-05-02 115717](https://user-images.githubusercontent.com/94922306/166218080-b6bd810e-1490-4488-93de-a50080416a41.png)

**Comment by StephaneDelcroix** [comment]
@SailDev the reported messages are different from the OP. Do you have a stack trace ? is this a release build or a debug (XamlCompilation isn't turned on on Debug builds)

**Comment by StephaneDelcroix** [comment]
also, you probably can't "link all" a real application, as bindings, some xaml, ... would stop working

**Comment by SailDev** [comment]
Sorry for the confusion. I have 2 accounts, "mrswdev" and "SailDev" is one person.

One difference to the original post is RC2 vs. RC1.

All tests were done in Debug mode.

I will add results for Release mode.

The stack trace for "Link Framework SDK's Only" is:

```
$exception.StackTrace
at Microsoft.Maui.Controls.Xaml.ApplyPropertiesVisitor.SetPropertyValue(Object xamlelement, XmlName propertyName, Object value, Object rootElement, INode node, HydrationContext context, IXmlLineInfo lineInfo)
at Microsoft.Maui.Controls.Xaml.ApplyPropertiesVisitor.Visit(ValueNode node, INode parentNode)
at Microsoft.Maui.Controls.Xaml.ValueNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
at Microsoft.Maui.Controls.Xaml.FillResourceDictionariesVisitor.Visit(ValueNode node, INode parentNode)
at Microsoft.Maui.Controls.Xaml.ValueNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
at Microsoft.Maui.Controls.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
at Microsoft.Maui.Controls.Xaml.RootNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
at Microsoft.Maui.Controls.Xaml.XamlLoader.Visit(RootNode rootnode, HydrationContext visitorContext, Boolean useDesignProperties)
at Microsoft.Maui.Controls.Xaml.XamlLoader.Load(Object view, String xaml, Assembly rootAssembly, Boolean useDesignProperties)
at Microsoft.Maui.Controls.Xaml.XamlLoader.Load(Object view, String xaml, Boolean useDesignProperties)
at Microsoft.Maui.Controls.Xaml.XamlLoader.Load(Object view, Type callingType)
at Microsoft.Maui.Controls.Xaml.Extensions.LoadFromXaml[App](App view, Type callingType)
at MauiApp5.App.InitializeComponent() in E:\WORKSPACE\MauiApp5\MauiApp5\Microsoft.Maui.Controls.SourceGen\Microsoft.Maui.Controls.SourceGen.CodeBehindGenerator\App.xaml.sg.cs:line 22
at MauiApp5.App..ctor() in E:\WORKSPACE\MauiApp5\MauiApp5\App.xaml.cs:line 7
at System.Reflection.RuntimeConstructorInfo.InternalInvoke(Object , Object[] , Boolean )
at System.Reflection.RuntimeConstructorInfo.DoInvoke(Object , BindingFlags , Binder , Object[] , CultureInfo )
at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags , Binder , Object[] , CultureInfo )
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite , RuntimeResolverContext )
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSiteMain(ServiceCallSite , RuntimeResolverContext )
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite , RuntimeResolverContext )
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSite(ServiceCallSite , RuntimeResolverContext )
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite , ServiceProviderEngineScope )
at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type )
at System.Collections.Concurrent.ConcurrentDictionary`2[[System.Type, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Func`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope, Microsoft.Extensions.DependencyInjection, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].GetOrAdd(Type , Func`2 )
at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type , ServiceProviderEngineScope )
at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type )
at Microsoft.Maui.MauiContext.WrappedServiceProvider.GetService(Type serviceType)
at Microsoft.Maui.MauiContext.WrappedServiceProvider.GetService(Type serviceType)
at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider , Type )
at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[IApplication](IServiceProvider )
at Microsoft.Maui.MauiUIApplicationDelegate.FinishedLaunching(UIApplication application, NSDictionary launchOptions)
at UIKit.UIApplication.Main(String[] , Type , Type )
at MauiApp5.Program.Main(String[] args) in E:\WORKSPACE\MauiApp5\MauiApp5\Platforms\iOS\Program.cs:line 13


$exception.InnerException.StackTrace
at System.Reflection.RuntimeConstructorInfo.InternalInvoke(Object , Object[] , Boolean )
at System.RuntimeType.CreateInstanceMono(Boolean , Boolean )
at System.RuntimeType.CreateInstanceDefaultCtor(Boolean , Boolean )
at System.Activator.CreateInstance(Type , Boolean , Boolean )
at System.Activator.CreateInstance(Type , Boolean )
at System.Activator.CreateInstance(Type )
at Microsoft.Maui.Controls.ResourceDictionary.<>c.<SetAndLoadSource>b__7_0(Type key)
at System.Runtime.CompilerServices.ConditionalWeakTable`2[[System.Type, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Microsoft.Maui.Controls.ResourceDictionary, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].GetValueLocked(Type , CreateValueCallback )
at System.Runtime.CompilerServices.ConditionalWeakTable`2[[System.Type, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Microsoft.Maui.Controls.ResourceDictionary, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].GetValue(Type , CreateValueCallback )
at Microsoft.Maui.Controls.ResourceDictionary.SetAndLoadSource(Uri value, String resourcePath, Assembly assembly, IXmlLineInfo lineInfo)
at Microsoft.Maui.Controls.ResourceDictionary.RDSourceTypeConverter.Microsoft.Maui.Controls.IExtendedTypeConverter.ConvertFromInvariantString(String value, IServiceProvider serviceProvider)
at Microsoft.Maui.Controls.Xaml.TypeConversionExtensions.ConvertTo(Object value, Type toType, Func`1 getConverter, IServiceProvider serviceProvider, Exception& exception)

```

**Comment by SailDev** [comment]
Release mode seems to work.

To summarize:

1. Debug mode + Link Framework SDK's Only = Error
2. Debug mode + Link All = Error
3. Debug mode + Don't Link = **O.k.**
4. Release mode + Link Framework SDK's Only = **O.k.**
5. Release mode + Link All = **O.k.**
6. Release mode + Don't Link = _Could not finish test_

So your best options are 3. and 4. 
I am not sure, if 1. should work.

**Comment by JaneySprings** [comment]
Seems like x:String also affected by this issue.
<img width="504" alt="image" src="https://user-images.githubusercontent.com/48021947/166911931-35543dc1-0f7b-4d97-9c40-ada232cde106.png">

**Comment by StephaneDelcroix** [comment]
@SailDev so you get a workaround, don't link in Debug (which is the default, and what you want anyway probably). 1/ should technically work, I'll ask around

**Comment by cbaer-extron** [comment]
I have the same error for x:String.  Whether I have it in the Application Resource Dictionary, or in a Xaml Page local resource dictionary, I get the same error "XamlParseException". when launched in Debug mode on iOS.

**Comment by KonyukhovSergey** [comment]
@evandigby the "Don't Link" setting does not applicable for libraries. We must link our resources in the library package.

**Comment by vhugogarcia** [comment]
> Release mode seems to work.
> 
> To summarize:
> 
> 1. Debug mode + Link Framework SDK's Only = Error
> 2. Debug mode + Link All = Error
> 3. Debug mode + Don't Link = **O.k.**
> 4. Release mode + Link Framework SDK's Only = **O.k.**
> 5. Release mode + Link All = **O.k.**
> 6. Release mode + Don't Link = _Could not finish test_
> 
> So your best options are 3. and 4. I am not sure, if 1. should work.

Thanks for sharing those details as a workaround. However, how to do you set "Don't link" all or "Link All", directly on the csproj? I could not find documentation on how to do it. any insight is always welcome.

**Comment by RichardMarsh** [comment]
> ```
> <?xaml-comp compile="true" ?>
> ```

In my case, I have a .NET MAUI Style library which is project dependecy for my .NET MAUI app. 

For option 3, I set it on the app project, not on the library project and it then seems to resolve in debug mode. Not tested on Release mode yet.

**Comment by vhugogarcia** [comment]
OK, I have something to share.

I was getting this error when I was using .NET MAUI GA (final release) announced this month during the BUILD 2022. However, On my macOS I had install XCode 13.3, then I noticed the XCode 13.4 update was there on the App Store, I went ahead and update it fully, installing the XCode components, etc and and I was able to set Debug mode + Don't Link and it the app was able to run on a physical device.

I'm not saying it is the final solution, however, this worked for me at least for now. I wanted to share some insights I found during my process.

Thanks in advance.

**Comment by AntonKosenkoDX** [comment]
@StephaneDelcroix Hello! Any update on this issue?

**Comment by madmapper** [comment]
Still experiencing this issue using the latest version of MAUI and VS.

**Comment by SailDev** [comment]
Status Report

Yesterday night, i updated to Visual Studio for Mac 17.4 preview (build 715) and **everything** works as expected.

I have a very large and complex app in development and **for the first time since Nov. 2021**, i was able to compile and deploy on the Mac (M1) to a physical iOS device and as a Mac Catalyst app in debug mode, without having the very time consuming issues with the remote build from windows, every 5 minutes.

I made only a quick first test, but i could. not detect any obvious and frustrating errors as in the past. Even the layout and entry controls work, after switching between landscape and portrait orientation.

The only (for me big) issue is, that i can't enable the VsVim extension in VS, i really have to figure this out.

I don't know, i should be real happy, but i only feel very tired.
Wish me luck, i will test "Release" mode today.

**Comment by jrahma** [comment]
I have the same problem @JaneySprings mentioned with x:String. I am using Latest VS for Mac and Latest MAUI.

**Comment by decv86** [comment]
welcome in MAUI ...

**Comment by bangnguyen794** [comment]
<img width="1621" alt="Ảnh chụp Màn hình 2022-08-26 lúc 10 33 41" src="https://user-images.githubusercontent.com/17409119/186811974-9890d4b1-c35b-487f-8acf-452ba45c5d97.png">
I am having a similar problem.

**Comment by SailDev** [comment]
Still on Visual Studio for Mac 17.4 preview (build 715).
After i detected the same error in a new Maui app, i decided to check my main app again, which was a success days before. 
But, after deleting the bin + obj folders by hand, the error on a physical device is back.

**Comment by nCastle1** [comment]
I have the same issue (for x:String) with 17.4 build 715

**Comment by Redth** [comment]
Is anyone still seeing this issue on .NET 7 GA and VS 17.4.3?  We haven't been able to reproduce this, but there have been some fixes related to XAML parsing and type converters which may have helped take care of this one as well.

Please let us know if you're able to reproduce this one still!

**Comment by vhugogarcia** [comment]
> Is anyone still seeing this issue on .NET 7 GA and VS 17.4.3?  We haven't been able to reproduce this, but there have been some fixes related to XAML parsing and type converters which may have helped take care of this one as well.
> 
> 
> 
> Please let us know if you're able to reproduce this one still!

Thanks for the heads up 👍🏻

**Comment by mrswdev** [comment]
Works fine on a Mac, deploying in debug mode to a connected IPhone.

VS4Mac Version 17.5 Preview (17.5 build 437)
.NET SDK (Arm64) 7.0.100
.NET Runtime (Arm64) 7.0.0

Thank you very much for your support.

**Comment by samhouts** [comment]
Duplicate of #5531
