### ISSUE TITLE
.NET MAUI Blazor crashes when changing system font on Android device

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#6105]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/NET-MAUI-Blazor-crashes-when-changing-s/10011886)._

---
Hi! 
When I'm debugging a Blazor MAUI project and changing the system font of my Samsung Galaxy S20 FE 5G the app crashes.

Exception:

```
[mono-rt] [ERROR] FATAL UNHANDLED EXCEPTION: System.NotImplementedException: Either set MainPage or override CreateWindow.
[mono-rt]    at Microsoft.Maui.Controls.Application.CreateWindow(IActivationState activationState) in D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\Application.Impl.cs:line 126
[mono-rt]    at Microsoft.Maui.Controls.Application.Microsoft.Maui.IApplication.CreateWindow(IActivationState activationState) in D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\Application.Impl.cs:line 41
[mono-rt]    at Microsoft.Maui.Platform.ApplicationExtensions.CreatePlatformWindow(Activity activity, IApplication application, Bundle savedInstanceState) in D:\a\_work\1\s\src\Core\src\Platform\Android\ApplicationExtensions.cs:line 44
[mono-rt]    at Microsoft.Maui.MauiAppCompatActivity.OnCreate(Bundle savedInstanceState) in D:\a\_work\1\s\src\Core\src\Platform\Android\MauiAppCompatActivity.cs:line 32
[mono-rt]    at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_(IntPtr jnienv, IntPtr native__this, IntPtr native_savedInstanceState) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net6.0/android-32/mcw/Android.App.Activity.cs:line 2781
[mono-rt]    at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPL_V(_JniMarshal_PPL_V callback, IntPtr jnienv, IntPtr klazz, IntPtr p0) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 110
[BpBinder] onLastStrongRef automatically unlinking death recipients: 
```

---
#### Feedback Bot on 4/13/2022, 03:01 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by Eilon** [comment]
I'm guessing this is not Blazor-specific, because Blazor doesn't do anything with fonts, and Blazor stuff isn't in the stack trace either.

**Comment by vallgrenerik** [comment]
Hi! I'm the one who reported this.
I'm on vacation and cannot try a new MAUI project, sorry 😊
Have a nice weekend!
Excited to see upcoming release of MAUI 🧑‍💻
