### ISSUE TITLE
NullReferenceException when Resources/Images contains non-image

### ISSUE THREAD

**Issue by Michal-MK** [dotnet/maui#6166]
### Description

In my test project I created an `attributions.txt` file in the `Resources/Images/` folder. 

```
Error    MAUI0000    System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Maui.Resizetizer.SkiaSharpBitmapTools.GetOriginalSize() in D:\a\_work\1\s\src\SingleProject\Resizetizer\src\SkiaSharpBitmapTools.cs:line 29
   at Microsoft.Maui.Resizetizer.SkiaSharpTools.Resize(DpiPath dpi, String destination) in D:\a\_work\1\s\src\SingleProject\Resizetizer\src\SkiaSharpTools.cs:line 47
   at Microsoft.Maui.Resizetizer.Resizer.Resize(DpiPath dpi, String inputsFile) in D:\a\_work\1\s\src\SingleProject\Resizetizer\src\Resizer.cs:line 101
   at Microsoft.Maui.Resizetizer.ResizetizeImages.ProcessImageResize(ResizeImageInfo img, DpiPath[] dpis, ConcurrentBag`1 resizedImages) in D:\a\_work\1\s\src\SingleProject\Resizetizer\src\ResizetizeImages.cs:line 174
   at Microsoft.Maui.Resizetizer.ResizetizeImages.<>c__DisplayClass27_0.<ExecuteAsync>b__0(ResizeImageInfo img) in D:\a\_work\1\s\src\SingleProject\Resizetizer\src\ResizetizeImages.cs:line 90
   at Microsoft.Maui.Resizetizer.AsyncTaskExtensions.<>c__DisplayClass0_0`1.<ParallelForEach>b__0(TSource s) in D:\a\_work\1\s\src\SingleProject\Resizetizer\src\AsyncTaskExtensions.cs:line 21    ERecept-MAUI    C:\Program Files\dotnet\packs\Microsoft.Maui.Resizetizer.Sdk\6.0.200-preview.14.5099\targets\Microsoft.Maui.Resizetizer.targets    475   
```

I found that VS automatically adds the `MauiImage` build action to everything it adds to this folder. Including the `.txt`.

Probably related SO post: <https://stackoverflow.com/questions/70747813>

The error message should be more specific (file that caused it?) rather than a NRE.

### Steps to Reproduce

Put anything that is not an image into `Resources/Images/` and mark it as a `MauiImage` (build action)

### Version with bug

Preview 14

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 11

### Did you find any workaround?

Check that all contents of the `Resources/Images/` folder are "image-like" files

### Relevant log output

A blank warning pointing to a targets file
```shell
Warning		MAUI0000	ERecept-MAUI	C:\Program Files\dotnet\packs\Microsoft.Maui.Resizetizer.Sdk\6.0.200-preview.14.5099\targets\Microsoft.Maui.Resizetizer.targets	475	
```
and the error log above.

**Comment by XamlTest** [comment]
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 1.0 [32414.199.main]. Repro on Android . Sample Project: [6166.zip](https://github.com/dotnet/maui/files/8502822/6166.zip)

![image](https://user-images.githubusercontent.com/97647558/163739941-211b0175-dc2f-4044-8637-6926505263ca.png)

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.6.0 Preview 4.0. This issue does not repro on Android emulator (13.0-API 33) with below Project:
[6166.zip](https://github.com/dotnet/maui/files/11284741/6166.zip)
