### ISSUE TITLE
SwipeItems.CollectionChanged event sends wrong sender object

### ISSUE THREAD

**Issue by myroot** [dotnet/maui#6291]
### Description

SwipeItmes.CollectionChanged event was implemented with ObservableCollection

https://github.com/dotnet/maui/blob/f7f084e3b79d8068967ebc680f0207cfb61567bc/src/Controls/src/Core/SwipeItems.cs#L47-L51

in this case, sender will be ObservableCollection instead SwipeItems

### Steps to Reproduce

1. We can reproduce with `src\Controls\samples\Controls.Sample`
2. Controls > SwipeView > Add/Remove SwipeItems Gallery
3. Click `Add SwipeItem`

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

All

### Relevant log output

```shell
c#
E/STDERR  ( 4400): Unhandled exception. System.InvalidCastException: Unable to cast object of type 'System.Collections.ObjectModel.ObservableCollection`1[Microsoft.Maui.ISwipeItem]' to type 'Microsoft.Maui.Controls.SwipeItems'.
E/STDERR  ( 4400):    at Microsoft.Maui.Controls.SwipeView.<>c__DisplayClass55_0.<OnSwipeItemsChanged>g__SwipeItemsCollectionChanged|1(Object sender, NotifyCollectionChangedEventArgs e) in F:\maui-nui\src\Controls\src\Core\SwipeView.cs:line 107
E/STDERR  ( 4400):    at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e) in System.ObjectModel.dll:token 0x600006b+0x31
E/STDERR  ( 4400):    at System.Collections.ObjectModel.ObservableCollection`1.InsertItem(Int32 index, T item) in System.ObjectModel.dll:token 0x6000065+0x28
E/STDERR  ( 4400):    at System.Collections.ObjectModel.Collection`1.Add(T item) in System.Private.CoreLib.dll:token 0x6006980+0xd
E/STDERR  ( 4400):    at Microsoft.Maui.Controls.SwipeItems.Add(ISwipeItem item) in F:\maui-nui\src\Controls\src\Core\SwipeItems.cs:line 68
E/STDERR  ( 4400):    at Maui.Controls.Sample.Pages.SwipeViewGalleries.AddRemoveSwipeItemsGallery.<>c__DisplayClass0_0.<.ctor>b__1(Object sender, EventArgs e) in F:\maui-nui\src\Controls\samples\Controls.Sample\Pages\Controls\SwipeViewGalleries\AddRemoveSwipeItemsGallery.cs:line 104
E/STDERR  ( 4400):    at Microsoft.Maui.Controls.Button.Microsoft.Maui.Controls.Internals.IButtonElement.PropagateUpClicked() in F:\maui-nui\src\Controls\src\Core\Button.cs:line 196
E/STDERR  ( 4400):    at Microsoft.Maui.Controls.ButtonElement.ElementClicked(VisualElement visualElement, IButtonElement ButtonElementManager) in F:\maui-nui\src\Controls\src\Core\ButtonElement.cs:line 61
E/STDERR  ( 4400):    at Microsoft.Maui.Controls.Button.SendClicked() in F:\maui-nui\src\Controls\src\Core\Button.cs:line 179

```
```

**Comment by myroot** [comment]
I think, sender must be an owner of event, in this case sender must be `SwipeItems` instead ObservableCollection
