### ISSUE TITLE
WebAuthenticator in Android not working

### ISSUE THREAD

**Issue by PhilippRoessner** [dotnet/maui#6534]
### Description

When subclassing the WebAuthenticatorCallbackActivity, I get a lot of errors like "The type or namespace name '....' could not be found(are you missing a using directive or an assembly reference?)

![image](https://user-images.githubusercontent.com/6959716/165497044-70698dbb-dd81-4251-bf72-e5cb25dd5f3b.png)

### Steps to Reproduce

1. Create a new MAUI App
2. Follow instructions for WebAuthenticator for Android https://docs.microsoft.com/en-us/xamarin/essentials/web-authenticator?tabs=ios#using-webauthenticator
3. run

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

12

### Did you find any workaround?

no

**Comment by PhilippRoessner** [comment]
@Redth thanks, I tried that but it's still not working with the same errors. What would be the namespace for the class attributes?

**Comment by shurkin** [comment]
I have the same issue

**Comment by shurkin** [comment]
Hi @PhilippRoessner, 

I found the solution. You have to add 

Exported = true in Activity attribute.

```
[Activity(NoHistory = true, LaunchMode = LaunchMode.SingleTop, Exported = true)]
[IntentFilter(new[] { Intent.ActionView }, Categories = new[] { Intent.CategoryDefault, Intent.CategoryBrowsable }, DataScheme = "yourscheme")]
public class WebAuthenticationCallbackActivity : WebAuthenticatorCallbackActivity
{
}```

**Comment by PhilippRoessner** [comment]
@shurkin YES! Thanks, it's working now :-)

**Comment by Joren-Thijs-KasparSolutions** [comment]
I still get this error using RC2. I just switched to copying the strings as literals
![image](https://user-images.githubusercontent.com/93926934/166307324-b53f3e2f-d57e-4258-b017-dae661daedb0.png)

**Comment by Joren-Thijs-KasparSolutions** [comment]
That being said it's still not working for me. i still get an error when trying to login:
```
System.InvalidOperationException: You must subclass the `WebAuthenticatorCallbackActivity` and create an IntentFilter for it which matches your `callbackUrl`.
   at Microsoft.Maui.Authentication.WebAuthenticatorImplementation.AuthenticateAsync(WebAuthenticatorOptions webAuthenticatorOptions) in D:\a\_work\1\s\src\Essentials\src\WebAuthenticator\WebAuthenticator.android.cs:line 63
   at App.Features.Login.WebAuthenticatorBrowser.InvokeAsync(BrowserOptions options, CancellationToken cancellationToken)
```

I don't understand do I need to link the activity somewhere on startup? why can I not find any docs on this?
