### ISSUE TITLE
building untrimmed application on Android on Release ends with Exception 'Unable to find Java.Lang.AbstractMethodError constructor'

### ISSUE THREAD

**Issue by janseris** [dotnet/maui#6569]
### Description

```
Error	XALNS7000	System.Exception: Unable to find Java.Lang.AbstractMethodError constructor in Mono.Android assembly
   at MonoDroid.Tuner.FixAbstractMethodsStep.get_AbstractMethodErrorConstructor()
   at MonoDroid.Tuner.FixAbstractMethodsStep.AddNewExceptionMethod(TypeDefinition type, MethodDefinition method)
   at MonoDroid.Tuner.FixAbstractMethodsStep.FixAbstractMethods(TypeDefinition type)
   at MonoDroid.Tuner.FixAbstractMethodsStep.FixAbstractMethods(AssemblyDefinition assembly)
   at Xamarin.Android.Tasks.LinkAssembliesNoShrink.RunTask()
   at Microsoft.Android.Build.Tasks.AndroidTask.Execute() in /Users/runner/work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/AndroidTask.cs:line 17	MauiApp2	C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.300-rc.3.33\tools\Xamarin.Android.Common.targets	1391	
```

caused by:

```
<DebugSymbols>True</DebugSymbols>
<PublishTrimmed>False</PublishTrimmed>
<RunAOTCompilation>False</RunAOTCompilation>
```

### Steps to Reproduce

create MAUI Blazor app
build Release

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11 (API 30)

**Comment by v-longmin** [comment]
Verified not repro on Android 12.0 with VS 17.3.0 Preview 1.0 [32414.199.main]. Not repro with above code.

**Comment by soundaranbu** [comment]
Issue still exists in 
- MAUI Blazor RC3, 
- Visual Studio Version 17.3.0 Preview 1.0. 

Attaching sample project here
[MauiSqliteErrorSample.zip](https://github.com/dotnet/maui/files/8704965/MauiSqliteErrorSample.zip)
