### ISSUE TITLE
Android - random Release build error

### ISSUE THREAD

**Issue by janseris** [dotnet/maui#6573]
### Description

When messing up with these lines (add/remove some/all) in a MAUI Blazor `.csproj` file,
		 
<DebugSymbols>True</DebugSymbols> 
<PublishTrimmed>False</PublishTrimmed> 
<RunAOTCompilation>False</RunAOTCompilation> 

this error appeared and I could not reproduce it.

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	XAGJS7004	System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Xamarin.Android.Tasks.TypeMapGenerator.GenerateRelease(Boolean skipJniAddNativeMethodRegistrationAttributeScan, List`1 javaTypes, String outputDirectory, ApplicationConfigTaskState appConfState)
   at Xamarin.Android.Tasks.GenerateJavaStubs.WriteTypeMappings(List`1 types, TypeDefinitionCache cache)
   at Xamarin.Android.Tasks.GenerateJavaStubs.Run(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.GenerateJavaStubs.RunTask()
   at Microsoft.Android.Build.Tasks.AndroidTask.Execute() in /Users/runner/work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/AndroidTask.cs:line 17	Tempus.GUI.Mobile.Blazor	C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.300-rc.3.33\tools\Xamarin.Android.Common.targets	1441	
```

Similar but not the same as https://github.com/dotnet/maui/issues/6569

### Steps to Reproduce

maui blazor app
release

```

<DebugSymbols>True</DebugSymbols> 
<PublishTrimmed>False</PublishTrimmed> 
<RunAOTCompilation>False</RunAOTCompilation> 

```

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11 (API 30)

**Comment by v-longmin** [comment]
Verified not repro on Android 12.0 with VS 17.3.0 Preview 1.0 [32414.199.main]. Not repro with above code.
