### ISSUE TITLE
Random System.NullReferenceException .Net Maui app under macOS

### ISSUE THREAD

**Issue by paratype-fonts** [dotnet/maui#6645]
### Description

macOS, the lates .NET Maui and Visual Studio 2022 Preview as of 04/28/2022

A random System.NullReferenceException thrown when the app is running:

```c#
public class Program
{
	// This is the main entry point of the application.
	static void Main(string[] args)
	{
		// if you want to use a different Application Delegate class from "AppDelegate"
		// you can specify it here.
		UIApplication.Main(args, null, typeof(AppDelegate));
	}
}
```
 

System.NullReferenceException: Object reference not set to an instance of an object.
  at at Microsoft.Maui.ElementHandlerExtensions.ToPlatform(IElementHandler elementHandler)
  at at Microsoft.Maui.ViewHandlerExtensions.PlatformArrangeHandler(IViewHandler viewHandler, Rect rect)
  at at Microsoft.Maui.Controls.Handlers.Compatibility.ViewCellRenderer.ViewTableCell.LayoutSubviews()
  at at Microsoft.Maui.Controls.Handlers.Compatibility.CellTableViewCell.GetPlatformCell(UITableView tableView, Cell cell, Boolean recycleCells, String templateId)
  at at Microsoft.Maui.Controls.Handlers.Compatibility.ListViewRenderer.ListViewDataSource.GetCell(UITableView tableView, NSIndexPath indexPath)
  at at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)
  at Fontoscope.Program.Main(String[] args) in .../Platforms/MacCatalyst/Program.cs:13

### Steps to Reproduce

The crash happens with no correlation with any specific user action

### Version with bug

Release Candidate 1

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

Visual Studio Community 2022 for Mac Preview Version 17.0 Preview (17.0 build 8754)

### Did you find any workaround?

No

**Comment by drasticactions** [comment]
Did you hit this from a new template, or from an app your building?

Looking at the stack trace, my guess is that you have the Xamarin.Forms Compatibility stuff turned on and the error is in ListView. So this isn't a "random error" but a specific bug in the compatibility list view control. Could you maybe make a repro project?
