### ISSUE TITLE
Failed to connect to localhost/127.0.0.1:7020

### ISSUE THREAD

**Issue by nssidhu** [dotnet/maui#6705]
### Description

I have Blazor MAUI APP, which was upgraded to the latest release. This was working on earlier release.
It is also currently working when using Windows emulator but fails on Android emulator.

I am using Microsoft Visual Studio Enterprise 2022 (64-bit) - Preview
Version 17.2.0 Preview 5.0

### Steps to Reproduce

Create a MAUI Blazor Hybrid App.
In the same solution also create Web API App which has controller for Login, change Password etc.
Run them both together.

Attached Screen Recordings.

https://1drv.ms/v/s!AtHk7h6Srnk_h_Mzd8dMwY7jHqNjlg

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Preview 14

### Affected platforms

Android

### Affected platform versions

Android

### Did you find any workaround?

No

### Relevant log output

```shell
C:\Users\nssid>dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.300-preview.22204.3
 Commit:    4f23310c97

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.300-preview.22204.3\

Host (useful for support):
  Version: 6.0.3
  Commit:  c24d9a9c91

.NET SDKs installed:
  6.0.300-preview.22204.3 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

C:\Users\nssid>
=====================================================================================================


[monodroid-assembly] open_from_bundles: failed to load assembly System.Net.Http.Json.dll
Loaded assembly: /data/data/com.companyname.blazormaui/files/.__override__/System.Net.Http.Json.dll [External]
[Choreographer] Skipped 115 frames!  The application may be doing too much work on its main thread.
[OpenGLRenderer] Davey! duration=1944ms; Flags=0, IntendedVsync=2901382060943, Vsync=2903298727533, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=2903315119600, AnimationStart=2903315697100, PerformTraversalsStart=2903318783000, DrawStart=2903319673500, SyncQueued=2903320059500, SyncStart=2903320413000, IssueDrawCommandsStart=2903320444700, SwapBuffers=2903325196700, FrameCompleted=2903326825200, DequeueBufferDuration=157200, QueueBufferDuration=947200, GpuCompleted=0, 
[DOTNET] System.Net.WebException: Failed to connect to localhost/127.0.0.1:7020
[DOTNET]  ---> Java.Net.ConnectException: Failed to connect to localhost/127.0.0.1:7020
[DOTNET]    at Java.Interop.JniEnvironment.InstanceMethods.CallVoidMethod(JniObjectReference instance, JniMethodInfo method, JniArgumentValue* args) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniEnvironment.g.cs:line 11884
[DOTNET]    at Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeAbstractVoidMethod(String encodedMember, IJavaPeerable self, JniArgumentValue* parameters) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:line 17
[DOTNET]    at Javax.Net.Ssl.HttpsURLConnectionInvoker.Connect() in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net6.0/android-32/mcw/Javax.Net.Ssl.HttpsURLConnection.cs:line 433
[DOTNET]    at Xamarin.Android.Net.AndroidMessageHandler.<>c__DisplayClass125_0.<ConnectAsync>b__0() in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Xamarin.Android.Net/AndroidMessageHandler.cs:line 442
[DOTNET]    at System.Threading.Tasks.Task.InnerInvoke()
[DOTNET]    at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
[DOTNET]    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
[DOTNET] --- End of stack trace from previous location ---
[DOTNET]    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
[DOTNET]    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
[DOTNET] --- End of stack trace from previous location ---
[DOTNET]    at Xamarin.Android.Net.AndroidMessageHandler.DoProcessRequest(HttpRequestMessage request, URL javaUrl, HttpURLConnection httpConnection, CancellationToken cancellationToken, RequestRedirectionState redirectState) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Xamarin.Android.Net/AndroidMessageHandler.cs:line 494
[DOTNET]   --- End of managed Java.Net.ConnectException stack trace ---
[DOTNET] java.net.ConnectException: Failed to connect to localhost/127.0.0.1:7020
[DOTNET] 	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:147)
[DOTNET] 	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
[DOTNET] 	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
[DOTNET] 	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
[DOTNET] 	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
[DOTNET] 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
[DOTNET] 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
[DOTNET] 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
[DOTNET] 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
[DOTNET] 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:90)
[DOTNET] 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:30)
[DOTNET] 
[DOTNET]   --- End of managed Java.Net.ConnectException stack trace ---
[DOTNET] java.net.ConnectException: Failed to connect to localhost/127.0.0.1:7020
[DOTNET] 	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:147)
[DOTNET] 	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
[DOTNET] 	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
[DOTNET] 	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
[DOTNET] 	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
[DOTNET] 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
[DOTNET] 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
[DOTNET] 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
[DOTNET] 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
[DOTNET] 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:90)
[DOTNET] 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:30)
[DOTNET] 
[DOTNET]    --- End of inner exception stack trace ---
[DOTNET]    at Xamarin.Android.Net.AndroidMessageHandler.DoProcessRequest(HttpRequestMessage request, URL javaUrl, HttpURLConnection httpConnection, CancellationToken cancellationToken, RequestRedirectionState redirectState) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Xamarin.Android.Net/AndroidMessageHandler.cs:line 501
[DOTNET]    at Xamarin.Android.Net.AndroidMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Xamarin.Android.Net/AndroidMessageHandler.cs:line 367
[DOTNET]    at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
[DOTNET]    at BlazorMAUI.Services.ClientTokenHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in C:\Users
ssid\source\repos
ssidhu\BlazorHybridAppNew\BlazorMAUI\Services\ClientTokenHttpHandler.cs:line 27
[DOTNET]    at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
[DOTNET]    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
[DOTNET]    at Refit.RequestBuilderImplementation.<>c__DisplayClass14_0`2.<<BuildCancellableTaskFuncForMethod>b__0>d[[Refit.ApiResponse`1[[Models.LoginResponse, Models, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], Refit, Version=6.3.0.0, Culture=neutral, PublicKeyToken=2f9b1262776509f5],[Models.LoginResponse, Models, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext() in /_/Refit/RequestBuilderImplementation.cs:line 256
[DOTNET] --- End of stack trace from previous location ---
[DOTNET]    at BlazorMAUI.Services.LoginService.LoginRCL.ILoginService.Login(DTO_LoginUser LoginUser) in C:\Users
ssid\source\repos
ssidhu\BlazorHybridAppNew\BlazorMAUI\Services\LoginService.cs:line 213
Thread finished: <Thread Pool> #15
The thread 0xf has exited with code 0 (0x0).
```

**Comment by drasticactions** [comment]
@jonathanpeppers This is going to be a net6-android issue, right?

**Comment by nssidhu** [comment]
yes

**Comment by drasticactions** [comment]
What I mean is that this is a net6.0-android issue, what you're seeing is probably not MAUI specific. If you ran this code on an app without MAUI loaded, you'll hit the same issue.

**Comment by nssidhu** [comment]
Not sure what you mean by that.This use to work earlier, things went wrong after upgrade.Secondly, in MAUI when I change to window it works fine.

Sent from Yahoo Mail for iPhone


On Sunday, May 1, 2022, 10:06 AM, Tim Miller ***@***.***> wrote:




What I mean is that this is a net6.0-android issue, what you're seeing is probably not MAUI specific. If you ran this code on an app without MAUI loaded, you'll hit the same issue.

**Comment by drasticactions** [comment]
MAUI runs on the net6.0-android SDK (https://github.com/xamarin/xamarin-android). Eariler versions of MAUI used earlier versions of the Android SDK. So when you upgrade MAUI, you're also upgrading the Android SDK version you are building against. 

That's what I think the issue is. This is not MAUI specific (As in, code controlled in this repo) but an Android SDK one. 

Also, it works on Windows... because that's running on Windows. That's running on top of WinUI, which will not be hit by what is an Android issue.

**Comment by VladislavAntonyuk** [comment]
What is localhost:7020 (I suppose it is your web app)?
Is it accessible from the Android? If you open the link it browser, does it work?

**Comment by jfversluis** [comment]
I have a feeling this is what is going on. You mention that it works on a Windows emulator. That makes sense, because the server you are trying to reach (127.0.0.1) is running on that same Windows machine, therefore it will work.

However, if you will run it on another machine (including the Android emulator, this is seen as a different machine) you will need to use the "outside" IP address. 127.0.0.1 is an internal address that only works locally on the same machine. Find out what the IP address is of your machine that you can use from other machines on your network (likely something that starts with 192.168.*.* or 10.*.*.*) and use that, it should work then.

**Comment by jonathanpeppers** [comment]
@nssidhu you might be able to use `adb forward`, to get a port from your desktop machine where Android can access it:

https://developer.android.com/studio/command-line/adb#forwardports

Then I would test a browser like @VladislavAntonyuk suggests.

**Comment by salghazaly** [comment]
I have the same issue it's working fine in Blazor server App but not working for maui
