### ISSUE TITLE
Navigating via tabs and then scrolling in listview causes app to crash

### ISSUE THREAD

**Issue by jayveedee** [dotnet/maui#6822]
### Description

I have a app which uses AppShell to navigate with. On the "home screen" of the app, there are 3 Tabs and 1 Flyout that you can access. On one of those Tabs there is a listview that contains some dummydata that gets added and shown.

When going to the page first time, the data loads and you are able to scroll fine without any crashes. If you then navigate to the other Tabs and come back to scroll again, the app crashes almost always, if no crash happens just navigate again.

### The XAML of the page with listview
```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:viewmodels="clr-namespace:Totalview_Time_MAUI.Common.ViewModel.NavigationTabs"
             xmlns:models="clr-namespace:Totalview_Time_MAUI.Common.Model.TimeRegistration"
             xmlns:controls="clr-namespace:Totalview_Time_MAUI"
             x:Class="Totalview_Time_MAUI.Overview"
             Style="{StaticResource ContentPageDefault}">
    <ContentPage.BindingContext>
        <viewmodels:OverviewViewModel />
    </ContentPage.BindingContext>
    <ListView x:Name="listView"
              ItemsSource="{Binding TimeRegistrationsValue}"
              IsPullToRefreshEnabled="True"
              IsRefreshing="{Binding IsRefreshingValue, Mode=OneWay}"
              RefreshCommand="{Binding RefreshCommand}"
              BackgroundColor="Transparent"
              SeparatorVisibility="None"
              HasUnevenRows="True">
        <ListView.ItemTemplate>
            <DataTemplate x:DataType="models:Registration">
                <ViewCell>
                    <StackLayout Orientation="Vertical" HeightRequest="25">
                        <Label TextColor="{DynamicResource PrimaryColor}" Margin="40,0,40,0"
                               Text="{Binding CurrentDateTitle}"
                               FontSize="{DynamicResource smallFontSize}"
                               FontFamily="RobotoBoldItalic"
                               HorizontalOptions="End">
                        </Label>
                        <Grid BackgroundColor="White" Margin="40,0,40,0">
                            <Grid.RowDefinitions>
                                <RowDefinition Height="40"></RowDefinition>
                                <RowDefinition Height="5"></RowDefinition>
                            </Grid.RowDefinitions>
                            <Grid Padding="10,0,10,0">
                                <Grid.ColumnDefinitions>
                                    <ColumnDefinition Width="*" />
                                    <ColumnDefinition Width="*" />
                                </Grid.ColumnDefinitions>
                                <Label TextColor="{DynamicResource PrimaryTextColor}" Grid.Column="0"
                                       Text="{Binding CurrentDayTitle}"
                                       FontSize="{DynamicResource mediumFontSize}"
                                       FontFamily="Roboto"
                                       VerticalOptions="Center"
                                       HorizontalOptions="Start">
                                </Label>
                                <StackLayout Orientation="Horizontal" Grid.Column="1" HorizontalOptions="End">
                                    <Label TextColor="{DynamicResource PrimaryTextColor}"
                                           Text="{Binding NormalWorkHours}"
                                           FontSize="{DynamicResource mediumFontSize}"
                                           FontFamily="Roboto"
                                           VerticalOptions="Center"
                                           Margin="0,0,5,0"
                                           HorizontalOptions="End">
                                    </Label>
                                    <Label TextColor="{DynamicResource PrimaryTextColor}"
                                           Text="Hours"
                                           FontSize="{DynamicResource mediumFontSize}"
                                           FontFamily="Roboto"
                                           VerticalOptions="Center"
                                           HorizontalOptions="End">
                                    </Label>
                                </StackLayout>
                            </Grid>
                            <controls:RegistrationBarGrid RegistrationStates="{Binding States}" BackgroundColor="Red" Grid.Row="1"></controls:RegistrationBarGrid>
                        </Grid>
                    </StackLayout>
                </ViewCell>
            </DataTemplate>
        </ListView.ItemTemplate>
    </ListView>
</ContentPage>
```

### How the XAML looks visually together with the Tabs/Flyout
![image](https://user-images.githubusercontent.com/24821250/166729119-59c10d3b-7599-4aa1-af2f-c2e9bfbbd344.png)

### The View class of the page
```
using Totalview_Time_MAUI.Common.Services;
using Totalview_Time_MAUI.Common.ViewModel.NavigationTabs;

namespace Totalview_Time_MAUI;

public partial class Overview : ContentPage
{
	private readonly OverviewViewModel viewModel;
	public Overview()
	{
		InitializeComponent();

		viewModel = new OverviewViewModel();
		BindingContext = viewModel;

		AnalyticsService.Instance.TrackEvent(Event.Navigation, Category.PageSession, nameof(Overview));

		listView.ItemTapped += (object sender, ItemTappedEventArgs e) => {
			// don't do anything if we just de-selected the row.
			if (e.Item == null) return;

			if (sender is ListView lv) lv.SelectedItem = null;
		};
	}
}
```

### The ViewModel class of the page
```
using MvvmHelpers;
using System.Collections.ObjectModel;
using System.Windows.Input;
using Totalview_Time_MAUI.Common.Model.TimeRegistration;
using Totalview_Time_MAUI.Common.Services.TimeServerAPIService;
using Totalview_Time_MAUI.Common.Util;


namespace Totalview_Time_MAUI.Common.ViewModel.NavigationTabs;

internal partial class OverviewViewModel : BaseViewModel
{
    public ObservableCollection<Registration> TimeRegistrationsValue { get; set; }
    public bool IsRefreshingValue
    {
        get => isRefreshing;
        set => SetProperty(ref isRefreshing, value);
    }
    private bool isRefreshing;

    public ICommand RefreshCommand { get; set; }

    public OverviewViewModel()
    {
        RefreshCommand = new Command(OnRefreshCommand);
        TimeRegistrationsValue = new ObservableRangeCollection<Registration>();
        OnRefreshCommand();
    }

    public async void OnRefreshCommand()
    {
        isRefreshing = true;
        //timeRegistrationsValue = await TimeServerAPIService.Instance.GetTimeRegistrations();
        var list = DummyDataUtil.CreateTimeRegistrations();
        for (int i = 0; i < list.Count; i++)
        {
            TimeRegistrationsValue.Add(list[i]);
        }
        isRefreshing = false;
    }
}
```

### The BaseViewModel class
```
using CommunityToolkit.Mvvm.ComponentModel;

namespace Totalview_Time_MAUI.Common.ViewModel;

public partial class BaseViewModel : ObservableObject
{
    public BaseViewModel()
    {
        
    }
}
```

### Steps to Reproduce

1. Create a app with AppShell navigation
2. Add at least 2 Tabs, one of which has a page with a listview
3. Add some Data to it, enough to be able to scroll up and down
4. Scroll a bit up and down and then navigate to the other tab and back again
5. Repeat step 4 until the app crashes

### Version with bug

Release Candidate 2 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

### Did you find any workaround?

Nope. I tried using ObservableRangeCollection as well from the MVVM.Helpers library if it had something to do with that, but nothing changed.
EDIT: I guess navigating slowly between the Tabs works decently enough. As soon as you move quickly it crashes.

### Relevant log output

```shell
There are a hundred or more lines from which I cut of the log below. Seems like the IllegalStateException would be the cause of the runtime crash

[.Totalview_Tim] java_vm_ext.cc:577] JNI DETECTED ERROR IN APPLICATION: JNI CallObjectMethodA called with pending exception java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
[.Totalview_Tim] java_vm_ext.cc:577] (Throwable with no stack trace)
[.Totalview_Tim] java_vm_ext.cc:577] 
[.Totalview_Tim] java_vm_ext.cc:577]     in call to CallObjectMethodA
[.Totalview_Tim] java_vm_ext.cc:577]     from android.view.View crc64e1fb321c08285b90.ListViewAdapter.n_getView(int, android.view.View, android.view.ViewGroup)
[.Totalview_Tim] runtime.cc:655] Runtime aborting...
[.Totalview_Tim] runtime.cc:655] Dumping all threads without mutator lock held
[.Totalview_Tim] runtime.cc:655] All threads:
```

**Comment by PureWeen** [comment]
@jayveedee this is most likely fixed by the following PR
https://github.com/dotnet/maui/pull/6902

If you can attach a repro we can test.

**Comment by jayveedee** [comment]
@PureWeen I will try if I get the time for it next week.

**Comment by jayveedee** [comment]
@PureWeen Hey sorry for the delay, but here it is. I made a fresh MAUI project and added the minimum amount of code to reproduce the crash in this [repo](https://github.com/jayveedee/ListviewCrash)

**Comment by jayveedee** [comment]
@PureWeen I think this has not been completely fixed yet. I've encountered the same error when placing a ListView inside of a Frame. When doing so you are unable to scroll the list with items and if you quickly navigate to this page and try to scroll the list the application crashes with the same error as reported before.

```
[.Totalview_Tim] runtime.cc:669]   at crc64e1fb321c08285b90.ListViewAdapter.n_getView(Native method)
[.Totalview_Tim] runtime.cc:669]   at crc64e1fb321c08285b90.ListViewAdapter.getView(ListViewAdapter.java:100)
[.Totalview_Tim] runtime.cc:669]   at android.widget.HeaderViewListAdapter.getView(HeaderViewListAdapter.java:224)
[.Totalview_Tim] runtime.cc:669]   at android.widget.AbsListView.obtainView(AbsListView.java:2398)
[.Totalview_Tim] runtime.cc:669]   at android.widget.ListView.makeAndAddView(ListView.java:2067)
[.Totalview_Tim] runtime.cc:669]   at android.widget.ListView.fillDown(ListView.java:793)
[.Totalview_Tim] runtime.cc:669]   at android.widget.ListView.fillGap(ListView.java:756)
[.Totalview_Tim] runtime.cc:669]   at android.widget.AbsListView.trackMotionScroll(AbsListView.java:5370)
[.Totalview_Tim] runtime.cc:669]   at android.widget.ListView.trackMotionScroll(ListView.java:1984)
[.Totalview_Tim] runtime.cc:669]   at android.widget.AbsListView.scrollIfNeeded(AbsListView.java:3641)
[.Totalview_Tim] runtime.cc:669]   at android.widget.AbsListView.startScrollIfNeeded(AbsListView.java:3567)
[.Totalview_Tim] runtime.cc:669]   at android.widget.AbsListView.onTouchMove(AbsListView.java:4078)
[.Totalview_Tim] runtime.cc:669]   at android.widget.AbsListView.onTouchEvent(AbsListView.java:3914)
[.Totalview_Tim] runtime.cc:669]   at android.view.View.dispatchTouchEvent(View.java:14540)
[.Totalview_Tim] runtime.cc:669]   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3114)
[.Totalview_Tim] runtime.cc:669]   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2787)
[.Totalview_Tim] runtime.cc:669]   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
[.Totalview_Tim] runtime.cc:669]   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
[.Totalview_Tim] runtime.cc:669]   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
[.Totalview_Tim] runtime.cc:669]   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
[.Totalview_Tim] runtime.cc:669]   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
[.Totalview_Tim] runtime.cc:669]   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
[.Totalview_Tim] runtime.cc:669]   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
[.Totalview_Tim] runtime.cc:669]   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
[.Totalview_Tim] runtime.cc:669]   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
[.Totalview_Tim] runtime.cc:669]   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
[.Totalview_Tim] runtime.cc:669]   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
[.Totalview_Tim] runtime.cc:669]   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
[.Totalview_Tim] runtime.cc:669]   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
[.Totalview_Tim] runtime.cc:669]   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
[.Totalview_Tim] runtime.cc:669]   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
[.Totalview_Tim] runtime.cc:669]   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
[.Totalview_Tim] runtime.cc:669]   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
[.Totalview_Tim] runtime.cc:669]   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
[.Totalview_Tim] runtime.cc:669]   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
[.Totalview_Tim] runtime.cc:669]   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
[.Totalview_Tim] runtime.cc:669]   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
[.Totalview_Tim] runtime.cc:669]   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
[.Totalview_Tim] runtime.cc:669]   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
[.Totalview_Tim] runtime.cc:669]   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
[.Totalview_Tim] runtime.cc:669]   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
[.Totalview_Tim] runtime.cc:669]   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
[.Totalview_Tim] runtime.cc:669]   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
[.Totalview_Tim] runtime.cc:669]   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
[.Totalview_Tim] runtime.cc:669]   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
[.Totalview_Tim] runtime.cc:669]   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
[.Totalview_Tim] runtime.cc:669]   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
[.Totalview_Tim] runtime.cc:669]   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
[.Totalview_Tim] runtime.cc:669]   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
[.Totalview_Tim] runtime.cc:669]   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
[.Totalview_Tim] runtime.cc:669]   at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:502)
[.Totalview_Tim] runtime.cc:669]   at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1890)
[.Totalview_Tim] runtime.cc:669]   at android.app.Activity.dispatchTouchEvent(Activity.java:4196)
[.Totalview_Tim] runtime.cc:669]   at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
[.Totalview_Tim] runtime.cc:669]   at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:460)
[.Totalview_Tim] runtime.cc:669]   at android.view.View.dispatchPointerEvent(View.java:14799)
[.Totalview_Tim] runtime.cc:669]   at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6347)
[.Totalview_Tim] runtime.cc:669]   at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6148)
[.Totalview_Tim] runtime.cc:669]   at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5626)
[.Totalview_Tim] runtime.cc:669]   at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5683)
[.Totalview_Tim] runtime.cc:669]   at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5649)
[.Totalview_Tim] runtime.cc:669]   at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5814)
[.Totalview_Tim] runtime.cc:669]   at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5657)
[.Totalview_Tim] runtime.cc:669]   at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5871)
[.Totalview_Tim] runtime.cc:669]   at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5630)
[.Totalview_Tim] runtime.cc:669]   at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5683)
[.Totalview_Tim] runtime.cc:669]   at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5649)
[.Totalview_Tim] runtime.cc:669]   at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5657)
[.Totalview_Tim] runtime.cc:669]   at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5630)
[.Totalview_Tim] runtime.cc:669]   at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8562)
[.Totalview_Tim] runtime.cc:669]   at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8513)
[.Totalview_Tim] runtime.cc:669]   at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8482)
[.Totalview_Tim] runtime.cc:669]   at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8685)
[.Totalview_Tim] runtime.cc:669]   at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:259)
[.Totalview_Tim] runtime.cc:669]   at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native method)
[.Totalview_Tim] runtime.cc:669]   at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:239)
[.Totalview_Tim] runtime.cc:669]   at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:8642)
[.Totalview_Tim] runtime.cc:669]   at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:8771)
[.Totalview_Tim] runtime.cc:669]   at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1037)
[.Totalview_Tim] runtime.cc:669]   at android.view.Choreographer.doCallbacks(Choreographer.java:845)
[.Totalview_Tim] runtime.cc:669]   at android.view.Choreographer.doFrame(Choreographer.java:772)
[.Totalview_Tim] runtime.cc:669]   at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
[.Totalview_Tim] runtime.cc:669]   at android.os.Handler.handleCallback(Handler.java:938)
[.Totalview_Tim] runtime.cc:669]   at android.os.Handler.dispatchMessage(Handler.java:99)
[.Totalview_Tim] runtime.cc:669]   at android.os.Looper.loopOnce(Looper.java:201)
[.Totalview_Tim] runtime.cc:669]   at android.os.Looper.loop(Looper.java:288)
[.Totalview_Tim] runtime.cc:669]   at android.app.ActivityThread.main(ActivityThread.java:7839)
[.Totalview_Tim] runtime.cc:669]   at java.lang.reflect.Method.invoke(Native method)
[.Totalview_Tim] runtime.cc:669]   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
[.Totalview_Tim] runtime.cc:669]   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
[.Totalview_Tim] runtime.cc:669] Pending exception java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
[.Totalview_Tim] runtime.cc:669] (Throwable with no stack trace)
[.Totalview_Tim] runtime.cc:669] 
[.Totalview_Tim] runtime.cc:677] JNI DETECTED ERROR IN APPLICATION: JNI CallObjectMethodA called with pending exception java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
[.Totalview_Tim] runtime.cc:677] (Throwable with no stack trace)
[.Totalview_Tim] runtime.cc:677] 
[.Totalview_Tim] runtime.cc:677]     in call to CallObjectMethodA
[.Totalview_Tim] runtime.cc:677]     from android.view.View crc64e1fb321c08285b90.ListViewAdapter.n_getView(int, android.view.View, android.view.ViewGroup)
```
