### ISSUE TITLE
Automatic iOS Provisioning 

### ISSUE THREAD

**Issue by claybrooks** [dotnet/maui#7055]
### Description

When trying to automatically provision, an error is displayed and the process fails.  The logs indicate that the API for automatically creating a cert is no longer accessible.

### Steps to Reproduce

1. Create a new MAUI project
2. Run through the setup to automatically provision
3. After the step of selecting your team, an error displays saying "There was an error while trying to automatially provision the project, please check the logs".
4. The logs display an exception stating the web API for creating certs is no longer accessible

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS

### Relevant log output

```shell
Xamarin.Messaging.Client.MessagingClient Error: 0 : An error occurred on the receiver while executing a post for topic xvs/idb/auto-provision and client vs22568clay
Xamarin.Messaging.Exceptions.MessagingRemoteException: An error occurred on client IDBLocal while executing a reply for topic xvs/idb/auto-provision ---> System.NotSupportedException: The Apple Developer Portal web API for creating certificates is no longer supported. Please create your certificate manually.
   at Xamarin.MacDev.AppleSigning.CreateCertificate.<Run>d__9.MoveNext() in /Users/builder/azdo/_work/1/s/External/maciostools/Xamarin.MacDev.AppleSigning/ProvisioningTasks/CreateCertificate.cs:line 69
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.MacDev.AppleSigning.ResolveCertificate.<Run>d__13.MoveNext() in /Users/builder/azdo/_work/1/s/External/maciostools/Xamarin.MacDev.AppleSigning/ProvisioningTasks/ResolveCertificate.cs:line 90
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.Messaging.IDB.AppleProvisioningManager.<AutoProvisionAsync>d__22.MoveNext() in D:\a\_work\1\s\src\Messaging\Xamarin.Messaging.IDB.Local\AppleProvisioningManager.cs:line 419
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.Messaging.IDB.Local.AutoProvisionHandler.<ExecuteAsync>d__2.MoveNext() in D:\a\_work\1\s\src\Messaging\Xamarin.Messaging.IDB.Local\Handlers\AutoProvisionHandler.cs:line 17
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.Messaging.Client.RequestHandler`2.<HandleAsync>d__5.MoveNext() in D:\a\_work\1\s\src\Xamarin.Messaging.Client\Handlers\RequestHandler.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.Messaging.Client.MessageHandlerManager.<>c__DisplayClass16_1`2.<<RegisterHandlerAsync>b__2>d.MoveNext() in D:\a\_work\1\s\src\Xamarin.Messaging.Client\MessageHandlerManager.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.Messaging.Client.MessagingClient.<ReplyAsync>d__32`2.MoveNext() in D:\a\_work\1\s\src\Xamarin.Messaging.Client\MessagingClient.cs:line 0
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Xamarin.Messaging.Client.ApplicationMessageExtensions.<>c__DisplayClass10_0`1.<OfResponse>b__1(MqttApplicationMessage m) in D:\a\_work\1\s\src\Xamarin.Messaging.Client\Extensions\ApplicationMessageExtensions.cs:line 194
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value) in d:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\Select.cs:line 39
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Xamarin.Messaging.Client.MessagingClient.<PostAsync>d__21`2.MoveNext() in D:\a\_work\1\s\src\Xamarin.Messaging.Client\MessagingClient.cs:line 190: 05/11/2022 03:49:39Z
    DateTime=2022-05-11T03:49:39.1109881Z: 05/11/2022 03:49:39Z
Xamarin.Messaging.Client.PingHandler Information: 0 : vs22568clay received ping. Sending acknowledge...: 05/11/2022 03:49:39Z
    DateTime=2022-05-11T03:49:39.7926609Z: 05/11/2022 03:49:39Z
Xamarin.Messaging.Client.PingHandler Information: 0 : vs22568clay received ping. Sending acknowledge...: 05/11/2022 03:49:44Z
    DateTime=2022-05-11T03:49:44.8005696Z: 05/11/2022 03:49:44Z
Xamarin.VisualStudio.UnhandledExceptionsManager Error: 0 : An unhandled error occurred. Details: An attempt was made to transition a task to a final state when it had already completed.
```

**Comment by jfversluis** [comment]
There are known issues right now with the Apple certificates because of breaking changes on the Apple side. See: https://developercommunity.visualstudio.com/t/Cannot-load-Apple-certificates/1692185

Closing this for now, please track the linked ticket for updates. Sorry for the inconvenience
