### ISSUE TITLE
WindowsForms with BlazorWebView control throws error in evergreen runtime using version 6.0.300-rc.3.5667

### ISSUE THREAD

**Issue by HillPhelmuth** [dotnet/maui#7169]
### Description

In a Windows Forms app using the WebView2 BlazorWebView control, the following exception is thrown when the control loads:

System.Reflection.TargetInvocationException
  HResult=0x80131604
  Message=Exception has been thrown by the target of an invocation.
  Source=System.Private.CoreLib
  StackTrace:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
   at Interop.User32.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.Interop.Mso.IMsoComponentManager.FPushMessageLoop(UIntPtr dwComponentID, msoloop uReason, Void* pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(msoloop reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(msoloop reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at RC3BlazorWebViewWinFormsBug.Program.Main() in C:\Source\Repos\AdamRepos\RC3BlazorWebViewWinFormsBug\RC3BlazorWebViewWinFormsBug\Program.cs:line 14

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
NotImplementedException: Unable to cast to Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller4.
This may happen if you are using an interface not supported by the version of the WebView2 Runtime you are using.
For instance, if you are using an experimental interface from an older SDK that has been modified or removed in a newer runtime.
Or, if you are using a public interface from a newer SDK that wasn't implemented in an older runtime.
For more information about WebView2 versioning please visit the following: https://docs.microsoft.com/microsoft-edge/webview2/concepts/versioning

Inner Exception 2:
InvalidCastException: Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller4'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{97D418D5-A426-4E49-A151-E1A10F327D9E}' failed due to the following error: No such interface supported (0x80004002 (E_NOINTERFACE)).

### Steps to Reproduce

1.) Follow Steps in [Build a Windows Forms Blazor app](https://docs.microsoft.com/en-us/aspnet/core/blazor/hybrid/tutorials/windows-forms?view=aspnetcore-6.0) with the latest version of
[Microsoft.AspNetCore.Components.WebView.WindowsForms](https://nuget.org/packages/Microsoft.AspNetCore.Components.WebView.WindowsForms)
2.) Run the application

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Release Candidate 2

### Affected platforms

Windows

### Affected platform versions

Any Windows SDK

### Did you find any workaround?

Revert Microsoft.AspNetCore.Components.WebView.WindowsForms back to 6.0.300-rc.2.5513

**Comment by javiercn** [comment]
@HillPhelmuth thanks for contacting us.

I'm not able to reproduce the issue you are facing. Could you provide a minimal repro project that showcases the issue as a public github repository?

**Comment by HillPhelmuth** [comment]
@javiercn 

I believe this was a local issue related to my VS 2022 version. Once I updated to VS Pro 2022 LTSC 17.0.10 this morning, I'm no longer seeing this error.
