### ISSUE TITLE
RC3 iOS AppCenter Dependency on System.Windows.Forms 4.0.0 crashes App

### ISSUE THREAD

**Issue by Mephisztoe** [dotnet/maui#7175]
### Description

When trying to initialize AppCenter using .NET MAUI RC3 (iOS), the App crashes on Platforms/iOS/Program.cs with a System.IO.FileNotFoundException. 

The InnerException references _System.Windows.Forms_, Version 4.0.0.0 not being found.

I know that this exception didn't happen in earlier versions of .NET MAUI.

I am currently on _Microsoft.AppCenter_.[_Analytics_|_Crashes_] Version 4.5.1

![Exception](https://user-images.githubusercontent.com/5309613/168375068-b2bbc7fc-fabf-44d7-8ce4-f1cb2d8fdf63.png)

  

### Steps to Reproduce

- Create a .NET MAUI RC3 App
- Install AppCenter NuGet Packages
- Setup and Configure AppCenter
- Initialize AppCenter SDK in .NET MAUI App as described
- Run App on iOS device

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS

### Relevant log output

```shell
Here is the StackTrace of the InnerException:

 at Microsoft.AppCenter.AppCenter..ctor()
   at Microsoft.AppCenter.AppCenter.get_Instance()
   at Microsoft.AppCenter.AppCenter.PlatformStart(String appSecret, Type[] services)
   at Microsoft.AppCenter.AppCenter.Start(String appSecret, Type[] services)
   at SIT.Code.Extensions.ConfigServicesExtensions.RegisterAppCenter(MauiAppBuilder builder) in C:\Users\cjacob\source\repos\***\SIT\Code\Extensions\RegisterAppCenterExtension.cs:line 18
   at SIT.MauiProgram.CreateMauiApp() in C:\Users\cjacob\source\repos\***\SIT\MauiProgram.cs:line 10
   at SIT.AppDelegate.CreateMauiApp() in C:\Users\cjacob\source\repos\***\SIT\Platforms\iOS\AppDelegate.cs:line 12
   at Microsoft.Maui.MauiUIApplicationDelegate.WillFinishLaunching(UIApplication application, NSDictionary launchOptions)
   at UIKit.UIApplication.Main(String[] , Type , Type )
   at SIT.Program.Main(String[] args) in C:\Users\cjacob\source\repos\***\SIT\Platforms\iOS\Program.cs:line 13
```

**Comment by drasticactions** [comment]
If you try creating a new dotnet 6 iOS app without MAUI (`dotnet new ios`) and try referencing this library and using it, does it throw the same error?

**Comment by Mephisztoe** [comment]
@drasticactions actually not quite the same, but it also does not work. When doing dotnet new ios, make it build and deploy to a physical device and then Package-Install both AppCenter packages and fire up AppCenter, the app still crashes right away (on AppCenter.Start(...)).

The crash also originates within Microsoft.AppCenter.Utils.ApplicationLifecycleHelperDesktop:

![Exception_ios](https://user-images.githubusercontent.com/5309613/168425227-255924e7-228a-4466-b8a1-15d737373b22.png)

Here is the complete _Message_:

Attempting to JIT compile method 'void Microsoft.AppCenter.Utils.ApplicationLifecycleHelperDesktop:.cctor ()' while running in aot-only mode. See https://docs.microsoft.com/xamarin/ios/internals/limitations for more information.

**Comment by drasticactions** [comment]
I think you should reopen this issue with https://github.com/xamarin/xamarin-macios and see what they say. This feels like either a regression in the dotnet 6 Mac/iOS tooling (Remember that when you upgrade MAUI workloads, you're also upgrading the underlying platform SDKs as well) or something the AppCenter team needs to fix in their library.

Looking at the stack trace for the original issue and this one you posted, I don't think this can be fixed inside of this repo.
