### ISSUE TITLE
ShellApp fills the whole app on MacOS Monterey

### ISSUE THREAD

**Issue by jerryno6** [dotnet/maui#7360]
### Description

When we run ShellApp on MAC, the flyout page full fills the screen.
**The ShellApp works well on Windows.**

[source code, description, screen shots for the bug are in this repository](https://github.com/jerryno6/MAUI)

### Steps to Reproduce

1. Create a new MAUI app on Windows
2. Add a Shell Page
3. Update the source code to Display ShellPage when you open the app
4. Run the app on Mac Monterey (macbook pro 16", 2019 intel chip)
5. When the app shows up, the Flyout fills the whole screen. and it's difficult for you to close the Flyout page.

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

### Affected platform versions

.net6 maccatalyst

**Comment by VincentBu** [comment]
not repro with vs main build(32522.39.main)

**Comment by jerryno6** [comment]
This issue has been fixed in **Version 17.3 Preview** (17.3 build 198)

**Comment by jerryno6** [comment]
I'm using MacBook pro 2019 16" **macOS 12.6 (21G115)**
Latest Visual Studio Community 2022 for Mac Preview **Version 17.4 Preview (17.4 build 1552)**

In [this repository above](https://github.com/jerryno6/MAUI), branch `test/flyoutpage` 
It worked well on Windows, but MacOS. because it thrown an exception as below:
`   at Microsoft.Maui.Controls.Handlers.Compatibility.PhoneFlyoutPageRenderer.LayoutChildren(Boolean animated)
   at Microsoft.Maui.Controls.Handlers.Compatibility.PhoneFlyoutPageRenderer.set_Presented(Boolean value)
   at Microsoft.Maui.Controls.Handlers.Compatibility.PhoneFlyoutPageRenderer.SetElement(VisualElement element)
   at Microsoft.Maui.Controls.Handlers.Compatibility.PhoneFlyoutPageRenderer.Microsoft.Maui.IElementHandler.SetVirtualView(IElement view)
   at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler)
   at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value)
   at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.set_Handler(IElementHandler value)
   at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context)
   at Microsoft.Maui.Platform.ElementExtensions.ToPlatform(IElement view, IMauiContext context)
   at Microsoft.Maui.Platform.ElementExtensions.ToUIViewController(IElement view, IMauiContext context)
   at Microsoft.Maui.Handlers.WindowHandler.MapContent(IWindowHandler handler, IWindow window)
   at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0[[Microsoft.Maui.IWindow, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.IWindowHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v)
   at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IElementHandler viewHandler, IElement virtualView)
   at Microsoft.Maui.PropertyMapper.UpdateProperties(IElementHandler viewHandler, IElement virtualView)
   at Microsoft.Maui.Handlers.ElementHandler.SetVirtualView(IElement view)
   at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler)
   at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value)
   at Microsoft.Maui.Platform.ElementExtensions.SetHandler(INativeObject nativeElement, IElement element, IMauiContext context)
   at Microsoft.Maui.Platform.ElementExtensions.SetWindowHandler(UIWindow platformWindow, IWindow window, IMauiContext context)
   at Microsoft.Maui.Platform.ApplicationExtensions.CreatePlatformWindow(IApplication application, UIWindowScene windowScene, NSDictionary[] states)
   at Microsoft.Maui.Platform.ApplicationExtensions.CreatePlatformWindow(IUIApplicationDelegate platformApplication, IApplication application, UIApplication uiApplication, NSDictionary launchOptions)
   at Microsoft.Maui.MauiUIApplicationDelegate.FinishedLaunching(UIApplication application, NSDictionary launchOptions)
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)
   at MyMauiApp.Program.Main(String[] args) in /Users/vule/VuDocs/PROJECTS/Default/MAUI/MyMauiApp/Platforms/MacCatalyst/Program.cs:line 13`
