### ISSUE TITLE
ArgumentOutOfRangeException in Android shell when page becomes invisible

### ISSUE THREAD

**Issue by jskeet** [dotnet/maui#7417]
### Description

I have an app with dynamic shell content - pages become visible or invisible depending on the state of another system, via data binding.
This was fine in earlier versions, but in 6.0.300-rc.3 (which I assume is the version shipped with VS 2022 17.3.0 preview 1?) an exception is thrown when an active page becomes invisible.

### Steps to Reproduce

(Code is shown in more detail below)

1. Create a new MAUI app called ShellPageRemoved (to fit in with the code below)
2. Add a new file SimpleViewModel (content below) with a `Visible` property
3. Add a new ContentPage called Page2, containing a button that changes `SimpleViewModel.Visible`
4. Add Page2 to the shell, with a visibility based on `SimpleViewModel.Visible`
5. Set the `BindingContext` of the app to a `SimpleViewModel`
6. Start the app in the Android emulator or a real device (in the debugger)
7. Navigate to Page 2
8. Click the button to make the page disappear
9. Observe the exception

Code:

SimpleViewModel.cs:
```csharp
using System.ComponentModel;

namespace ShellPageRemoved;

public class SimpleViewModel : INotifyPropertyChanged
{
    public event PropertyChangedEventHandler PropertyChanged;

    public bool Visible { get; set; } = true;

    public void SetVisibleFalse()
    {
        Visible = false;
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(Visible)));
    }
}
```

Page2.xaml:
```xml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="ShellPageRemoved.Page2"
             Title="Page2">
    <StackLayout>
        <Button Text="Click me to make me disappear" Clicked="SetVisibleFalse" />
    </StackLayout>
</ContentPage>
```

Page.xaml.cs:
```csharp
namespace ShellPageRemoved;

public partial class Page2 : ContentPage
{
	public Page2()
	{
		InitializeComponent();
	}

    private void SetVisibleFalse(object sender, EventArgs e)
    {
		SimpleViewModel vm = (SimpleViewModel)BindingContext;
		vm.SetVisibleFalse();
    }
}
```

App.xaml.cs change (all other lines remain the same):

```csharp
MainPage = new AppShell { BindingContext = new SimpleViewModel() };
```

AppShell.xaml:
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<Shell
    x:Class="ShellPageRemoved.AppShell"
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:local="clr-namespace:ShellPageRemoved"
    Shell.FlyoutBehavior="Disabled">

    <TabBar>
        <ShellContent Title="Home" ContentTemplate="{DataTemplate local:MainPage}" />
        <ShellContent Title="Page 2" ContentTemplate="{DataTemplate local:Page2}" IsVisible="{Binding Visible}"/>
    </TabBar>
</Shell>
```

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Release Candidate 2

### Affected platforms

Android

### Affected platform versions

Only tried with "Android 11.0 - API 30" emulator and a Pixel 6

### Did you find any workaround?

Not yet. I *suspect* that if I remove the databinding from visibility and navigate away from the page before changing the visibility, it will be okay.

### Relevant log output

```shell
System.ArgumentOutOfRangeException
  Message=Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
[mono-rt] [ERROR] FATAL UNHANDLED EXCEPTION: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
[mono-rt]    at System.Collections.Generic.List`1[[Microsoft.Maui.Controls.ShellContent, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].get_Item(Int32 index)
[mono-rt]    at System.Collections.ObjectModel.Collection`1[[Microsoft.Maui.Controls.ShellContent, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].get_Item(Int32 index)
[mono-rt]    at System.Collections.ObjectModel.ReadOnlyCollection`1[[Microsoft.Maui.Controls.ShellContent, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].get_Item(Int32 index)
[mono-rt]    at Microsoft.Maui.Controls.Platform.Compatibility.ShellSectionRenderer.OnPageSelected(Int32 position) in D:\a\_work\1\s\src\Controls\src\Core\Compatibility\Handlers\Shell\Android\ShellSectionRenderer.cs:line 291
[mono-rt]    at Microsoft.Maui.Controls.Platform.Compatibility.ShellSectionRenderer.ViewPagerPageChanged.OnPageSelected(Int32 position) in D:\a\_work\1\s\src\Controls\src\Core\Compatibility\Handlers\Shell\Android\ShellSectionRenderer.cs:line 338
[mono-rt]    at AndroidX.ViewPager2.Widget.ViewPager2.OnPageChangeCallback.n_OnPageSelected_I(IntPtr jnienv, IntPtr native__this, Int32 position) in C:\a\_work\1\s\generated\androidx.viewpager2.viewpager2\obj\Release
et6.0-android\generated\src\AndroidX.ViewPager2.Widget.ViewPager2.cs:line 318
[mono-rt]    at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPI_V(_JniMarshal_PPI_V callback, IntPtr jnienv, IntPtr klazz, Int32 p0) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 55
```

**Comment by VincentBu** [comment]
repro with vs main build(32523.339.main).
