### ISSUE TITLE
$SolutionDir incorrectly maps to $ProjectDir when deploying to iOS (simulator)

### ISSUE THREAD

**Issue by Tyri0n** [dotnet/maui#7534]
### Description

I have a CommonSettings.targets file in the solution folder: C:\dev\vs2022\MauiApp\

The project folder is:  C:\dev\vs2022\MauiApp\MauiApp\

All builds fine but when deploying to iOS simulator fails with the below error that shows it's looking in the wrong folder for the CommonSettings.targets file.

Adding this to the project file...:

```xml
  <Import Project="$(SolutionDir)CommonSettings.targets" />

  <Target Name="TestMessage" AfterTargets="Build">
    <Message Text="========== SolutionDir is $(SolutionDir) ==========" Importance="high" />
    <Message Text="========== ProjectDir is $(ProjectDir) ==========" Importance="high" />
  </Target>    
```

... yields this output:

```
1>========== SolutionDir is C:\dev\vs2022\MauiApp\ ==========
1>========== ProjectDir is C:\dev\vs2022\MauiApp\MauiApp\ ==========
```

### Steps to Reproduce

1. Clone https://github.com/mattleibow/maui-bug-repros/tree/repro-maui-7534
2. Run on an iOS simulator via the build agent
3. Observe the build succeeds but the deploy fails (but says it is fine)

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

any

### Did you find any workaround?

Duplicating file in $ProjectDir or changing import and moving file to $ProjectDir works, but shouldn't have to.

### Relevant log output

```shell
There was an unhandled exception trying to deploy and run your application. 
Microsoft.Build.Exceptions.InvalidProjectFileException: The imported project **"C:\dev\vs2022\MauiApp\MauiApp\CommonSettings.targets"** was not found. Confirm that the expression in the Import declaration "CommonSettings.targets" is correct, and that the file exists on disk.  C:\dev\vs2022\MauiApp\MauiApp\MauiApp.csproj
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpression(String directoryOfImportingFile, ProjectImportElement importElement, String unescapedExpression, Boolean throwOnFileNotExistsError, List`1& imports)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpressionConditioned(String directoryOfImportingFile, ProjectImportElement importElement, List`1& projects, SdkResult& sdkResult, Boolean throwOnFileNotExistsError)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImports(String directoryOfImportingFile, ProjectImportElement importElement, SdkResult& sdkResult)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate()
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(IEvaluatorData`4 data, Project project, ProjectRootElement root, ProjectLoadSettings loadSettings, Int32 maxNodeCount, PropertyDictionary`1 environmentProperties, ILoggingService loggingService, IItemFactory`2 itemFactory, IToolsetProvider toolsetProvider, ProjectRootElementCacheBase projectRootElementCache, BuildEventContext buildEventContext, ISdkResolverService sdkResolverService, Int32 submissionId, EvaluationContext evaluationContext, Boolean interactive)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.ReevaluateIfNecessary(EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext, IDirectoryCacheFactory directoryCacheFactory)
   at Xamarin.VisualStudio.IOS.AssetCatalog.AssetCatalogManager.CreateBuildProject() in D:\a\_work\1\s\src\Core\VisualStudio.IOS.AssetCatalog\AssetCatalogManager.cs:line 587
   at Xamarin.VisualStudio.IOS.AssetCatalog.AssetCatalogManager.HasOnDemandResources() in D:\a\_work\1\s\src\Core\VisualStudio.IOS.AssetCatalog\AssetCatalogManager.cs:line 252
   at Xamarin.VisualStudio.IOS.MonoTouchRunSessionInfo.<InitializeInstanceAsync>d__5.MoveNext() in D:\a\_work\1\s\src\Core\VisualStudio.IOS\Debugging\MonoTouchRunSessionInfo.cs:line 66
```

**Comment by VincentBu** [comment]
not repro with maui main branch. currently, I don't have windows machine so I try this on my mac m1, here are the repro steps:
1. create a blank solution: `dotnet new sln -o mauiapp7534`
2. create a maui project under that sln: `dotnet new maui -o mauiapp`
3. add project to sln: `dotnet sln add mauiapp/mauiapp.csproj`
4. move Resources/Images to solution directory
5. edit .csproj:
```
<!-- Images -->
<MauiImage Include="$(SolutionDir)Images\*" />
<MauiImage Update="$(SolutionDir)Images\dotnet_bot.svg" BaseSize="168,208" />
```
6. build and run on ios simulator

**Comment by mattleibow** [comment]
Just updating the stack trace just in case:

```
Xamarin.VisualStudio.IOS.CommandHandlers.DebugCommandHandler Error: 0 : An error occurred while lauching Application for debugging
Microsoft.Build.Exceptions.InvalidProjectFileException: The imported project "C:\Projects\Testing\MauiApp69\MauiApp69\CommonSettings.targets" was not found. Confirm that the expression in the Import declaration "CommonSettings.targets" is correct, and that the file exists on disk.  C:\Projects\Testing\MauiApp69\MauiApp69\MauiApp69.csproj
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpression(String directoryOfImportingFile, ProjectImportElement importElement, String unescapedExpression, Boolean throwOnFileNotExistsError, List`1& imports)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpressionConditioned(String directoryOfImportingFile, ProjectImportElement importElement, List`1& projects, SdkResult& sdkResult)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImports(String directoryOfImportingFile, ProjectImportElement importElement, SdkResult& sdkResult)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate()
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(IEvaluatorData`4 data, Project project, ProjectRootElement root, ProjectLoadSettings loadSettings, Int32 maxNodeCount, PropertyDictionary`1 environmentProperties, ILoggingService loggingService, IItemFactory`2 itemFactory, IToolsetProvider toolsetProvider, ProjectRootElementCacheBase projectRootElementCache, BuildEventContext buildEventContext, ISdkResolverService sdkResolverService, Int32 submissionId, EvaluationContext evaluationContext, Boolean interactive)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.ReevaluateIfNecessary(EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.ProjectImpl.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext, IDirectoryCacheFactory directoryCacheFactory)
   at Xamarin.VisualStudio.IOS.AssetCatalog.AssetCatalogManager.CreateBuildProject() in D:\a\_work\1\s\src\Core\VisualStudio.IOS.AssetCatalog\AssetCatalogManager.cs:line 587
   at Xamarin.VisualStudio.IOS.AssetCatalog.AssetCatalogManager.HasOnDemandResources() in D:\a\_work\1\s\src\Core\VisualStudio.IOS.AssetCatalog\AssetCatalogManager.cs:line 252
   at Xamarin.VisualStudio.IOS.MonoTouchRunSessionInfo.<InitializeInstanceAsync>d__5.MoveNext() in D:\a\_work\1\s\src\Core\VisualStudio.IOS\Debugging\MonoTouchRunSessionInfo.cs:line 66
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.VisualStudio.IOS.MonoTouchRunSessionInfo.<CreateNewInstanceAsync>d__4.MoveNext() in D:\a\_work\1\s\src\Core\VisualStudio.IOS\Debugging\MonoTouchRunSessionInfo.cs:line 33
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.VisualStudio.IOS.CommandHandlers.RunCommandHandlerBase.<GetRunSessionInfoAsync>d__25.MoveNext() in D:\a\_work\1\s\src\Core\VisualStudio.IOS\CommandHandlers\RunCommandHandlerBase.cs:line 282
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.VisualStudio.IOS.CommandHandlers.DebugCommandHandler.<CreateDebuggerStartInfoAsync>d__8.MoveNext() in D:\a\_work\1\s\src\Core\VisualStudio.IOS\CommandHandlers\DebugCommandHandler.cs:line 158
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.VisualStudio.IOS.CommandHandlers.DebugCommandHandler.<DebugApplicationAsync>d__7.MoveNext() in D:\a\_work\1\s\src\Core\VisualStudio.IOS\CommandHandlers\DebugCommandHandler.cs:line 114: 01 16 2023 23:36:28Z
    DateTime=2023-01-16T23:36:28.2097397Z: 01 16 2023 23:36:28Z
```

**Comment by mattleibow** [comment]
Uploaded repro and some logs in the repo: https://github.com/mattleibow/maui-bug-repros/tree/repro-maui-7534

**Comment by Eilon** [comment]
@rolfbjarne - can you suggest where this issue should go? To VS Feedback, the Xamarin iOS repo, or elsewhere?

**Comment by rolfbjarne** [comment]
@Eilon 
The stack trace looks like it comes from VS, so that's where I believe it should go (especially since this seems like it only happens when _running_ from the IDE, not when just building from the IDE, nor when building from the command line).

**Comment by mattleibow** [comment]
Moved to https://developercommunity.visualstudio.com/t/SolutionDir-incorrectly-maps-to-Projec/10262832?port=1025&fsid=03b64e18-549d-4c70-b8e0-d712d047aa3d
