### ISSUE TITLE
[BUG IOS] Cancel prompt in WebView will crash the app

### ISSUE THREAD

**Issue by danielftz** [dotnet/maui#7541]
### Description

When cancelling a javascript input prompt from a WebView, the app will crash. 

### Steps to Reproduce

Create a brand new project, in mainpage.cs

```
public class MainPage : ContentPage
{
      public MainPage()
      {
	      Content = new WebView
	      {
		      Source = "https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_prompt",
	      };
      }
}
```

On the webpage, invoke javascript prompt by clicking on try, then click on cancel, then the app will crash

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

IOS 15

### Did you find any workaround?

NO

### Relevant log output

```shell
log: 

System.ArgumentNullException: Value cannot be null. (Parameter 'obj')
  at at ObjCRuntime.ThrowHelper.ThrowArgumentNullException(String argumentName)
  at at ObjCRuntime.Trampolines.NIDActionArity1V63.Invoke(String obj)
  at at Microsoft.Maui.Platform.MauiWebViewUIDelegate.<>c__DisplayClass4_0.<RunJavaScriptTextInputPanel>b__1(UIAlertController _)
  at at Microsoft.Maui.Platform.MauiWebViewUIDelegate.<>c__DisplayClass8_0.<PresentAlertController>b__2()
  at at Microsoft.Maui.Platform.MauiWebViewUIDelegate.<>c__DisplayClass7_0.<AddCancelAction>b__0(UIAlertAction _)
  at at ObjCRuntime.Trampolines.SDActionArity1V237.Invoke(IntPtr block, NativeHandle obj)
  at at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)
  at MyProj.Program.Main(String[] args) in /Volumes/Seagate/proj/MyProj/MyProj/Platforms/iOS/Program.cs:13
```
```

**Comment by VincentBu** [comment]
not repro with vs main build 32601.361.main
![image](https://user-images.githubusercontent.com/44959937/171568302-f3c2f07a-8b20-45be-9040-c9123df3ec14.png)
