### ISSUE TITLE
System.MissingMethodException: No parameterless constructor defined for type 'Microsoft.Maui.Controls.Handlers.Compatibility.FrameRenderer'

### ISSUE THREAD

**Issue by JohnHDev** [dotnet/maui#7566]
### Description

Exception thrown on Android when replacing the App.MainPage with a different page.

Consider the scenario where the ap has a welcome page to request permissions and app settings before displaying the real main page. Once the welcome page has been completed, setting the App MainPage throws the above error.

### Steps to Reproduce

Consider the scenario where the ap has a welcome page to request permissions and app settings before displaying the real main page. Once the welcome page has been completed, setting the App MainPage throws the above error.

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android Pie 9 API 28

### Relevant log output

```shell
System.MissingMethodException: No parameterless constructor defined for type 'Microsoft.Maui.Controls.Handlers.Compatibility.FrameRenderer'.
  at at System.RuntimeType.CreateInstanceMono(Boolean nonPublic, Boolean wrapExceptions)
  at at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
  at at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
  at at System.Activator.CreateInstance(Type type, Boolean nonPublic)
  at at System.Activator.CreateInstance(Type type)
  at Microsoft.Maui.Hosting.Internal.MauiFactory.CreateInstance(ServiceDescriptor item) in D:\a\_work\1\s\src\Core\src\Hosting\Internal\MauiFactory.cs:162
  at Microsoft.Maui.Hosting.Internal.MauiFactory.GetService(ServiceDescriptor descriptor) in D:\a\_work\1\s\src\Core\src\Hosting\Internal\MauiFactory.cs:130
  at Microsoft.Maui.Hosting.Internal.MauiFactory.GetService(Type serviceType, ServiceDescriptor single, IEnumerable`1 enumerable) in D:\a\_work\1\s\src\Core\src\Hosting\Internal\MauiFactory.cs:141
  at Microsoft.Maui.Hosting.Internal.MauiFactory.GetService(Type serviceType) in D:\a\_work\1\s\src\Core\src\Hosting\Internal\MauiFactory.cs:36
  at Microsoft.Maui.Hosting.Internal.MauiHandlersFactory.GetHandler(Type type) in D:\a\_work\1\s\src\Core\src\Hosting\Internal\MauiHandlersFactory.cs:30
  at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context) in D:\a\_work\1\s\src\Core\src\Platform\ElementExtensions.cs:81
```

**Comment by jsuarezruiz** [comment]
Could you attach a small sample where reproduce the issue?. Thanks!.

**Comment by JohnHDev** [comment]
I can't replicate in an example app, but still happens in my current app.
Investigating further, it isn't related to setting a new MainPage on the App. It is due to specific views on the page. I'll try and narrow I down now...
Wrapping the page in a NavigationPage resolves the issue, but shouldn't be needed.

**Comment by JohnHDev** [comment]
Well, this code replicates the issue in my app, but not in a new app:

            MainPage = new ContentPage()
            {
                Content = new Frame()
                {
                    BackgroundColor = Colors.Red,
                    HorizontalOptions = LayoutOptions.Fill,
                    VerticalOptions = LayoutOptions.Fill,
                }
            };

Still trying to see what else triggers this.
Incidentally, I see the call stack refers to Microsoft.Maui.Controls.Handlers.Compatibility.FrameRenderer. Is there a configuration option to say use the new handlers?

**Comment by Ombrelin** [comment]
Does your Page and ViewModel types are added to the DI ? I have this error when I forget to add them.

**Comment by JohnHDev** [comment]
> Do your Page and ViewModel types are added to the DI ? I have this error when I forget to add them.

In this example Im hardcoding the creation of the page, so no DI needed.

**Comment by PureWeen** [comment]
@JohnHDev does your app actually crash? or do you have first chance exceptions enabled so your debugger is just pausing?

Do you have a deeper stack?

It'd be nice to see what's right before this
`  at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context) in D:\a\_work\1\s\src\Core\src\Platform\ElementExtensions.cs:81`

**Comment by PaulAnderson02** [comment]
This issue occurs if you enable all the exceptions in the settings of your app
