### ISSUE TITLE
Error starting Android app: cannot locate symbol "mono_opt_aot_lazy_assembly_load"

### ISSUE THREAD

**Issue by Sandrocker** [dotnet/maui#7636]
### Description

Hi,

I'm trying to launch my app in Visual Studio on the connected Xiaomi M2006C3MNG (Android 10.0 - API 29). After the installation the following error message appears:

`java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "mono_opt_aot_lazy_assembly_load"`

Here all about my Visual Studio installation:

```
Microsoft Visual Studio Community 2022
Version 17.3.0 Preview 1.1
VisualStudio.17.Preview/17.3.0-pre.1.1+32519.111
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Community

Visual C++ 2022   00482-90000-00000-AA259
Microsoft Visual C++ 2022

.NET Core Debugging with WSL   1.0
.NET Core Debugging with WSL

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools 2019   17.3.122.33185
ASP.NET and Web Tools 2019

Azure App Service Tools v3.0.0   17.3.122.33185
Azure App Service Tools v3.0.0

Azure Data Lake Tools for Visual Studio   2.6.5000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   17.3.122.33185
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.5000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   4.3.0-1.22254.1+9919d7e7bd753404a5d2328e5e3fb2de635169f3
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Microsoft Azure Hive Query Language Service   2.6.5000.0
Language service for Hive query

Microsoft Azure Stream Analytics Language Service   2.6.5000.0
Language service for Azure Stream Analytics

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Mono Debugging for Visual Studio   17.3.11 (4f73250)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   6.3.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Razor (ASP.NET Core)   17.0.0.2222701+751db1ebea5e6a9ecc7fa57fe447180422afa610
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   17.0.62204.01010
Microsoft SQL Server Data Tools

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   17.0.10420.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.3.0-1.22254.1+9919d7e7bd753404a5d2328e5e3fb2de635169f3
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual C++ for Cross Platform Mobile Development (Android)   17.0.32505.426
Visual C++ for Cross Platform Mobile Development (Android)

Visual F# Tools   17.1.0-beta.22178.3+6da0245a7ce4bb8483b8d1f2993c8ecaea967ad9
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VSPackage Extension   1.0
VSPackage Visual Studio Extension Detailed Info

Xamarin   17.3.0.151 (d17-3-p1.1@5a59bfa)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.3.0.33 (remotes/origin/d17-3-1@9c0d11a29)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   17.2.15 (2e3b60e)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   12.3.99.58 (main/64b22fc)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: adf1bc4
    Java.Interop: xamarin/java.interop/release/6.0.3xx@2a882d2d
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.38.2@7b1e016
    Xamarin.Android Tools: xamarin/xamarin-android-tools/main@fc3c2ac


Xamarin.iOS and Xamarin.Mac SDK   15.11.0.183 (f8314a435)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

```
Here an output from uno-check:

```
  .NET SDK - Workloads (6.0.300) Checkup...
  - android (Microsoft.NET.Sdk.Android.Manifest-6.0.300 : 32.0.301) installed.
  - ios (Microsoft.NET.Sdk.iOS.Manifest-6.0.300 : 15.4.303) installed.
  - maccatalyst (Microsoft.NET.Sdk.MacCatalyst.Manifest-6.0.300 : 15.4.303) installed.
  - tvos (Microsoft.NET.Sdk.tvOS.Manifest-6.0.300 : 15.4.303) installed.
  - macos (Microsoft.NET.Sdk.macOS.Manifest-6.0.300 : 12.3.303) installed.
  - wasm-tools (microsoft.net.workload.mono.toolchain-6.0.300 : 6.0.5) installed.

```
Here the target frameworks and NuGet packages I use in the project:

```
<TargetFrameworks>net6.0-android;net6.0-ios;net6.0-maccatalyst</TargetFrameworks>

<ItemGroup>
  <PackageReference Include="IdentityModel.OidcClient" Version="5.0.0" />
  <PackageReference Include="Microsoft.AspNetCore.Authentication" Version="2.2.0" />
  <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" Version="6.0.4" />
  <PackageReference Include="Microsoft.Extensions.Http" Version="6.0.0" />
</ItemGroup>

```
Here the AndroidManifest.xml:

```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
	<uses-sdk android:minSdkVersion="21" android:targetSdkVersion="30" />
	<application android:allowBackup="true" android:icon="@mipmap/appicon" android:roundIcon="@mipmap/appicon_round" android:supportsRtl="true"></application>
	<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
  <queries>
    <intent>
      <action android:name="android.support.customtabs.action.CustomTabsService" />
    </intent>
  </queries>
</manifest>

```
### Steps to Reproduce

The error comes right after starting my app in Visual Studio.

### Version with bug

6.0 Release Candidate 3

### Last version that worked well

Release Candidate 1

### Affected platforms

Android

### Affected platform versions

Android 10

### Relevant log output

```shell
[DOTNET] JNI_OnLoad: JNI_OnLoad in pal_jni.c
[AndroidRuntime] Shutting down VM
[AndroidRuntime] FATAL EXCEPTION: main
[AndroidRuntime] Process: com.companyname.helpsimply.mobilehelper, PID: 17311
[AndroidRuntime] java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "mono_opt_aot_lazy_assembly_load" referenced by "/data/app/com.companyname.helpsimply.mobilehelper-kI4lfVR6ekcfd2Z7IkEZqg==/lib/arm/libmonodroid.so"...
[AndroidRuntime] 	at java.lang.Runtime.loadLibrary0(Runtime.java:1071)
[AndroidRuntime] 	at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
[AndroidRuntime] 	at java.lang.System.loadLibrary(System.java:1667)
[AndroidRuntime] 	at mono.MonoPackageManager.LoadApplication(MonoPackageManager.java:102)
[AndroidRuntime] 	at mono.MonoRuntimeProvider.attachInfo(MonoRuntimeProvider.java:35)
[AndroidRuntime] 	at android.app.ActivityThread.installProvider(ActivityThread.java:7188)
[AndroidRuntime] 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6671)
[AndroidRuntime] 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6588)
[AndroidRuntime] 	at android.app.ActivityThread.access$1500(ActivityThread.java:235)
[AndroidRuntime] 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1916)
[AndroidRuntime] 	at android.os.Handler.dispatchMessage(Handler.java:107)
[AndroidRuntime] 	at android.os.Looper.loop(Looper.java:225)
[AndroidRuntime] 	at android.app.ActivityThread.main(ActivityThread.java:7563)
[AndroidRuntime] 	at java.lang.reflect.Method.invoke(Native Method)
[AndroidRuntime] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
[AndroidRuntime] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:994)
```

**Comment by Sandrocker** [comment]
I haven't found a solution to the problem yet.

The behavior described already occurs to me when I create a new .NET MAUI Blazor app project and start it on an emulator (e.g. Pixel 5 API 30).

I tried the following:
- Uninstall and reinstall Visual Studio
- Repair Visual Studio
- Run ```dotnet workload install maui``` in command line

**Comment by VincentBu** [comment]
I verified it on my mac and can't repro on android simulator (api31), would you like to share a sample project?

**Comment by Sandrocker** [comment]
As I said, the error occurs when I create a new .NET MAUI Blazor-App project. As an example, I've now done this again and put it in a GitHub repository. I also set the bin and obj folders. Maybe this shows what the problem is. I tried to start the project with an Android emulator with API 31. I got the same error message again.

https://github.com/Sandrocker/FailingMauiBlazorApp.git

**Comment by Sandrocker** [comment]
I solved the problem. I uninstalled Visual Studio again. This time I ran the `InstallCleanup.exe` tool afterwards. Additionally I uninstalled the following programs:

- Windows Desktop Runtime
- Microsoft .NET SDK
- Microsoft ASP.NET Core - Shared Framework

After reinstalling Visual Studio 17.3.0 Preview 4.0 everything worked.
