### ISSUE TITLE
Not able to link .a iOS library

### ISSUE THREAD

**Issue by AlexeyBKuznetsov** [dotnet/maui#7670]
### Description

Not able to link .a iOS library via iOS Binding project

### Steps to Reproduce

1. Create iOS binding project
2. Add .a to the binding project
3. Create MAUI app project
4. Add iOS binding reference to the MAUI app
5. Setup additional linking flags as per https://docs.microsoft.com/en-us/xamarin/ios/platform/native-interop

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

15

### Did you find any workaround?

No
[IssueWithA.Log.zip](https://github.com/dotnet/maui/files/8817685/IssueWithA.Log.zip)
[IssueWithA.zip](https://github.com/dotnet/maui/files/8817686/IssueWithA.zip)

### Relevant log output

```shell
Attached solution to reproduce and the Visual Studio logs
```

**Comment by AlexeyBKuznetsov** [comment]
Also in logs I see '$(IsMacEnabled)' was evaluated as 'false' thought Mac is actually connected. Thanks

**Comment by drasticactions** [comment]
Are you able to link an iOS library to a dotnet 6 iOS app (Ex. `dotnet new ios`) without MAUI? This issue would seem more based on the Xamarin.iOS SDK and setting that up verses things done in this repo, but I could be missing something here. 

@rolfbjarne @dalexsoto  do you have any guidence?

**Comment by rolfbjarne** [comment]
@AlexeyBKuznetsov your .a file only contains arm64:

```shell
$ file libXcodeFat.a
libXcodeFat.a: Mach-O universal binary with 1 architecture: [arm64:current ar archive random librarycurrent ar archive random library]
libXcodeFat.a (for architecture arm64):	current ar archive random library
```

that won't work when building for iossimulator-x64.

**Comment by AlexeyBKuznetsov** [comment]
Hi Rolf Bjarne Kvinge, and greatly appreciate your help with the issue

Yes - I know, it is built for arm64 and would not work on the iossimulator-x64. My expectation is : the library should still be linked into the final application package and work on my iPad-Pro. Please correct me if I am wrong

Couple more things :
1. When I right-click on the iOSBinding project in Visual Studio 17.3.0 Preview 1.1 in the context menu I see "Add Native Reference" with two options "Add Native Framework Library" and "Add Native Static Library" - none of these options is working. So, I added my .a static library manually <NativeReference Include="libXcodeFat.a" Kind="Static"/>

2. According to the diagnostics log '$(IsMacEnabled)' was evaluated as 'false' thought Mac is actually connected. Why ? As a result, the task "ResolveNativeReferences" skipped, due to false condition; ('$(IsMacEnabled)' == 'true' And '$(IsBindingProject)' != 'true') was evaluated as ('false' == 'true' And '' != 'true').

Thanks

**Comment by rolfbjarne** [comment]
> My expectation is : the library should still be linked into the final application package and work on my iPad-Pro.

That's incorrect, you have to build separately for device (by using a different runtime identifier, in particular by adding `<RuntimeIdentifier>ios-arm64</RuntimeIdentifier>` to the csproj or by passing `/p:RuntimeIdentifier=ios-arm64` if building using the command line).

You can't use an app bundle built for the simulator on device.

> When I right-click on the iOSBinding project in Visual Studio 17.3.0 Preview 1.1 in the context menu I see "Add Native Reference" with two options "Add Native Framework Library" and "Add Native Static Library" - none of these options is working. So, I added my .a static library manually

That sounds like a problem in the IDE, please file it here: https://developercommunity.visualstudio.com/report?space=8&entry=problem

> According to the diagnostics log '(IsMacEnabled)' == 'true' And '$(IsBindingProject)' != 'true') was evaluated as ('false' == 'true' And '' != 'true').

That doesn't sound right either, although I'm a bit puzzled as to what could be the reason. Does it work for other iOS projects?

**Comment by rolfbjarne** [comment]
@AlexeyBKuznetsov I've tried a few things:

1. I tried build & running from the command line on macOS, and I ran into this exception at startup:

        Microsoft.iOS: Received unhandled ObjectiveC exception: Microsoft.Maui.Controls.Xaml.XamlParseException Position 9:37. Cannot assign property "Source": Property does not exist, or is not assignable, or mismatching type between value and property (Microsoft.Maui.Controls.Xaml.XamlParseException)
           at Microsoft.Maui.Controls.Xaml.ApplyPropertiesVisitor.SetPropertyValue(Object , XmlName , Object , Object , INode , HydrationContext , IXmlLineInfo )
           at Microsoft.Maui.Controls.Xaml.ApplyPropertiesVisitor.Visit(ValueNode , INode )
           at Microsoft.Maui.Controls.Xaml.ValueNode.Accept(IXamlNodeVisitor , INode )
           at Microsoft.Maui.Controls.Xaml.ElementNode.Accept(IXamlNodeVisitor , INode )
           at Microsoft.Maui.Controls.Xaml.FillResourceDictionariesVisitor.Visit(ElementNode , INode )
           at Microsoft.Maui.Controls.Xaml.ElementNode.Accept(IXamlNodeVisitor , INode )
           at Microsoft.Maui.Controls.Xaml.ListNode.Accept(IXamlNodeVisitor , INode )
           at Microsoft.Maui.Controls.Xaml.ElementNode.Accept(IXamlNodeVisitor , INode )
           at Microsoft.Maui.Controls.Xaml.RootNode.Accept(IXamlNodeVisitor , INode )
           at Microsoft.Maui.Controls.Xaml.XamlLoader.Visit(RootNode , HydrationContext , Boolean )
           at Microsoft.Maui.Controls.Xaml.XamlLoader.Load(Object , String , Assembly , Boolean )
           at Microsoft.Maui.Controls.Xaml.XamlLoader.Load(Object , String , Boolean )
           at Microsoft.Maui.Controls.Xaml.XamlLoader.Load(Object , Type )
           at Microsoft.Maui.Controls.Xaml.Extensions.LoadFromXaml[App](App , Type )
           at NativeTestMauiB.App.InitializeComponent() in /Users/rolf/test/IssueWithA1/IssueWithA1/NativeTestMauiB/Microsoft.Maui.Controls.SourceGen/Microsoft.Maui.Controls.SourceGen.CodeBehindGenerator/App.xaml.sg.cs:line 22
           at NativeTestMauiB.App..ctor() in /Users/rolf/test/IssueWithA1/IssueWithA1/NativeTestMauiB/App.xaml.cs:line 10
           at System.Reflection.RuntimeConstructorInfo.InternalInvoke(Object , Object[] , Boolean )
           at System.Reflection.RuntimeConstructorInfo.DoInvoke(Object , BindingFlags , Binder , Object[] , CultureInfo )
           at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags , Binder , Object[] , CultureInfo )
           at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite , RuntimeResolverContext )
           at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSiteMain(ServiceCallSite , RuntimeResolverContext )
           at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite , RuntimeResolverContext )
           at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSite(ServiceCallSite , RuntimeResolverContext )
           at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite , ServiceProviderEngineScope )
           at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type )
           at System.Collections.Concurrent.ConcurrentDictionary`2[[System.Type, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Func`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope, Microsoft.Extensions.DependencyInjection, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].GetOrAdd(Type , Func`2 )
           at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type , ServiceProviderEngineScope )
           at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type )
           at Microsoft.Maui.MauiContext.WrappedServiceProvider.GetService(Type )
           at Microsoft.Maui.MauiContext.WrappedServiceProvider.GetService(Type )
           at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider , Type )
           at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[IApplication](IServiceProvider )
           at Microsoft.Maui.MauiUIApplicationDelegate.FinishedLaunching(UIApplication , NSDictionary )

2. I added a call to the native P/Invoke in question, `NativeTestMaui.TestClass.NativeLibFunc();`, to before the exception above occurs. This works just fine (the app builds, runs on device, and the NativeLibFunc method is called).
3. I tried using VS for Mac, and I got the same behavior: the call to `NativeTestMaui.TestClass.NativeLibFunc();` works when I added it before the exception from point 1.
4. The conclusion is that this is a problem related to the connection between Windows and Mac (as you've pointed out, `IsMacEnabled=false`), and not really a problem linking an .a library into the app. However, this is not my area of expertise.

**Comment by rolfbjarne** [comment]
@drasticactions can you re-route this to the VSX team?

**Comment by AlexeyBKuznetsov** [comment]
Thanks Rolf,

I recompiled the app on Mac from the command line using "dotnet build -t:Run -f net6.0-ios /p:RuntimeIdentifier=ios-arm64" it was compiled with no issues / warnings and crashes at start (same as you reported above)

Also, when I am compiling from the Visual Studio for Mac, I see in logs : "Tool xcrun execution started with arguments: clang++ libBambooFat.a <long list of other libraries>" which doesn't report any issues / warnings. And, again app crashes at start. Though I don't see the exception output you put above

I think two issues needs to addressed here :
	1. First is in Visual Studio and I see you already re-routed issues there
	2. Second is the exception you published above

Thanks again

**Comment by rolfbjarne** [comment]
2. Yes, this should be for the MAUI team, since the exception occurs before hitting any code from the binding project, it's likely independent from the binding project, and you should be able to reproduce it even after removing the binding project (or not adding it in the repro steps). It's a very different issue though, and should be filed as such (because tracking more than one problem in a single issue ends up being very confusing for everyone involved).
