### ISSUE TITLE
SignalR Client with MessagePack Protocol fails on MAUI iOS.

### ISSUE THREAD

**Issue by gdar91** [dotnet/maui#7753]
### Description

When I try to use the SignalR client with the message pack protocol, it crashes on the MAUI iOS platform. However, it works on the windows machine.

### Steps to Reproduce

Make any SignalR Hub invocation, that passes and returns data as simple as a string, from the maui (maui-blazor) app SignalR client using the MessagePack protocol and try launching it on the iOS platform.

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15

### Did you find any workaround?

Have to use the Json Protocol before it's fixed.

### Relevant log output

```shell
[Error] Cannot box IsByRefLike type 'MessagePack.MessagePackWriter'
   at System.Delegate.CreateDelegate(Type type, Object firstArgument, MethodInfo method, Boolean throwOnBindFailure, Boolean allowClosed)
   at System.Delegate.CreateDelegate(Type type, Object firstArgument, MethodInfo method, Boolean throwOnBindFailure)
   at System.Delegate.CreateDelegate(Type type, Object firstArgument, MethodInfo method)
   at System.Reflection.Emit.DynamicMethod.CreateDelegate(Type delegateType, Object target)
   at System.Dynamic.Utils.DelegateHelpers.CreateObjectArrayDelegateRefEmit(Type delegateType, Func`2 handler)
   at System.Dynamic.Utils.DelegateHelpers.CreateObjectArrayDelegate(Type delegateType, Func`2 handler)
   at System.Linq.Expressions.Interpreter.LightLambda.MakeDelegate(Type delegateType)
   at System.Linq.Expressions.Interpreter.LightDelegateCreator.CreateDelegate(IStrongBox[] closure)
   at System.Linq.Expressions.Interpreter.LightDelegateCreator.CreateDelegate()
   at System.Linq.Expressions.Expression`1[[MessagePack.MessagePackSerializer.CompiledMethods.MessagePackWriterSerialize, MessagePack, Version=2.3.0.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be]].Compile()
   at System.Linq.Expressions.Expression`1[[MessagePack.MessagePackSerializer.CompiledMethods.MessagePackWriterSerialize, MessagePack, Version=2.3.0.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be]].Compile(Boolean preferInterpretation)
   at MessagePack.MessagePackSerializer.CompiledMethods..ctor(Type type)
   at MessagePack.MessagePackSerializer.<>c.<.cctor>b__45_0(Type t)
   at MessagePack.Internal.ThreadsafeTypeKeyHashTable`1[[MessagePack.MessagePackSerializer.CompiledMethods, MessagePack, Version=2.3.0.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be]].AddToBuckets(Entry[] buckets, Type newKey, Entry newEntryOrNull, Func`2 valueFactory, CompiledMethods& resultingValue)
   at MessagePack.Internal.ThreadsafeTypeKeyHashTable`1[[MessagePack.MessagePackSerializer.CompiledMethods, MessagePack, Version=2.3.0.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be]].TryAddInternal(Type key, Func`2 valueFactory, CompiledMethods& resultingValue)
   at MessagePack.Internal.ThreadsafeTypeKeyHashTable`1[[MessagePack.MessagePackSerializer.CompiledMethods, MessagePack, Version=2.3.0.0, Culture=neutral, PublicKeyToken=b4a0369545f0a1be]].GetOrAdd(Type key, Func`2 valueFactory)
   at MessagePack.MessagePackSerializer.GetOrAdd(Type type)
   at MessagePack.MessagePackSerializer.Serialize(Type type, MessagePackWriter& writer, Object obj, MessagePackSerializerOptions options)
   at Microsoft.AspNetCore.SignalR.Protocol.DefaultMessagePackHubProtocolWorker.Serialize(MessagePackWriter& writer, Type type, Object value)
   at Microsoft.AspNetCore.SignalR.Protocol.MessagePackHubProtocolWorker.WriteArgument(Object argument, MessagePackWriter& writer)
   at Microsoft.AspNetCore.SignalR.Protocol.MessagePackHubProtocolWorker.WriteInvocationMessage(InvocationMessage message, MessagePackWriter& writer)
   at Microsoft.AspNetCore.SignalR.Protocol.MessagePackHubProtocolWorker.WriteMessageCore(HubMessage message, MessagePackWriter& writer)
   at Microsoft.AspNetCore.SignalR.Protocol.MessagePackHubProtocolWorker.WriteMessage(HubMessage message, IBufferWriter`1 output)
   at Microsoft.AspNetCore.SignalR.Protocol.MessagePackHubProtocol.WriteMessage(HubMessage message, IBufferWriter`1 output)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.SendHubMessage(ConnectionState connectionState, HubMessage hubMessage, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.InvokeCore(ConnectionState connectionState, String methodName, InvocationRequest irq, Object[] args, String[] streams, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.InvokeCoreAsyncCore(String methodName, Type returnType, Object[] args, CancellationToken cancellationToken)
   at System.Threading.Tasks.ForceAsyncAwaiter`1[[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].GetResult()
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.InvokeCoreAsync(String methodName, Type returnType, Object[] args, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnectionExtensions.<InvokeCoreAsync>d__43`1[[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at Pages.Index.OnInitializedAsync() in *** Pages/Index.razor:line 54
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
	NotifyUnhandledException (blazor.webview.js:1:39721)
	(anonymous function) (blazor.webview.js:1:40643)
	(anonymous function) (user-script:1:4)
	forEach
	(anonymous function) (user-script:1:4)
	Global Code (0.0.0.0:1)
```

**Comment by drasticactions** [comment]
I'm fairly certain, looking at this stack trace, that this is not an MAUI (The UI Framework) issue, but either issue with AspNetCore's MessagePack library, or the net6 iOS Runtime it's running on. MAUI (The UI Framework) is not invoked here and I don't think is influencing this. If you were to move the Blazor Webview directly into a net6 iOS app without MAUI itself, it throws the same exception.

I'm moving this over to dotnet/aspnetcore.

**Comment by halter73** [comment]
> Cannot box IsByRefLike type 'MessagePack.MessagePackWriter'

It's SignalR's ​[MessagePack dependency](https://github.com/neuecc/MessagePack-CSharp) (when using [Protocols.MessagePack](https://www.nuget.org/packages/Microsoft.AspNetCore.SignalR.Protocols.MessagePack/)) that's trying to [compile delegates](https://github.com/neuecc/MessagePack-CSharp/blob/ffc18319670d49246db1abbd05c404a820280776/src/MessagePack.UnityClient/Assets/Scripts/MessagePack/MessagePackSerializer.NonGeneric.cs#L94-L96) taking a ​`ref struct MessagePackWriter`​. This works on Windows because the runtime can emit IL, but on iOS where it cannot, it's [forced to interpret](https://github.com/dotnet/runtime/blob/54cf23c8d0a26e3f2abdc5f87422e52ad93215c8/src/libraries/System.Linq.Expressions/src/System/Linq/Expressions/LambdaExpression.cs#L137-L148) the compiled delegate and box the `MessagePackWriter` in `CreateObjectArrayDelegate`.

I think we should try to transfer this issue to https://github.com/neuecc/MessagePack-CSharp. There's nothing SignalR can do. I don't think there's anything the runtime can do on iOS either. Correct me if I'm wrong @stephentoub.

**Comment by Eilon** [comment]
This issue was moved to neuecc/MessagePack-CSharp#1439
