### ISSUE TITLE
ListView not showing and/or throwing exception 

### ISSUE THREAD

**Issue by anpin** [dotnet/maui#7799]
### Description

I've got following exceptions in a project I'm working on, so I tried to create repro with similar layout, but it doesn't throw the exception, however it doesn't show `ListView` items either at least on Android. In the right brown `Frame` is `ListView` bound to the same collection as `CollectionView`, with different `DataTemplate`.
![Screenshot_20220606-214104](https://user-images.githubusercontent.com/6060545/172216836-a355571e-0300-4444-8929-262b6e971171.png)
 

### Steps to Reproduce

[maui-android-handler-activator-issue.zip](https://github.com/dotnet/maui/files/8846496/maui-android-handler-activator-issue.zip)
Unpack and build!

### Version with bug

6.0 Release Candidate 3

### Last version that worked well

Release Candidate 1

### Affected platforms

Android

### Affected platform versions

Android 9 

### Did you find any workaround?

no

### Relevant log output

```shell
[0:] [20:18:45 WRN] System.MissingMethodException: No parameterless constructor defined for type 'Microsoft.Maui.Controls.Handlers.Compatibility.ListViewRenderer'.
   at System.RuntimeType.CreateInstanceMono(Boolean nonPublic, Boolean wrapExceptions)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at Microsoft.Maui.Hosting.Internal.MauiFactory.CreateInstance(ServiceDescriptor item) in D:\a\_work\1\s\src\Core\src\Hosting\Internal\MauiFactory.cs:line 162
   at Microsoft.Maui.Hosting.Internal.MauiFactory.GetService(ServiceDescriptor descriptor) in D:\a\_work\1\s\src\Core\src\Hosting\Internal\MauiFactory.cs:line 130
   at Microsoft.Maui.Hosting.Internal.MauiFactory.GetService(Type serviceType, ServiceDescriptor single, IEnumerable`1 enumerable) in D:\a\_work\1\s\src\Core\src\Hosting\Internal\MauiFactory.cs:line 141
   at Microsoft.Maui.Hosting.Internal.MauiFactory.GetService(Type serviceType) in D:\a\_work\1\s\src\Core\src\Hosting\Internal\MauiFactory.cs:line 36
   at Microsoft.Maui.Hosting.Internal.MauiHandlersFactory.GetHandler(Type type) in D:\a\_work\1\s\src\Core\src\Hosting\Internal\MauiHandlersFactory.cs:line 30
   at Microsoft.Maui.Controls.Compatibility.Platform.Android.Platform.CreateRenderer(VisualElement element, Context context, FragmentManager fragmentManager, LayoutInflater layoutInflater) in D:\a\_work\1\s\src\Compatibility\Core\src\Android\AppCompat\Platform.cs:line 344
[0:] [20:18:45 WRN] System.MissingMethodException: No parameterless constructor defined for type 'Microsoft.Maui.Controls.Handlers.Compatibility.FrameRenderer'.
   at System.RuntimeType.CreateInstanceMono(Boolean nonPublic, Boolean wrapExceptions)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at Microsoft.Maui.Hosting.Internal.MauiFactory.CreateInstance(ServiceDescriptor item) in D:\a\_work\1\s\src\Core\src\Hosting\Internal\MauiFactory.cs:line 162
   at Microsoft.Maui.Hosting.Internal.MauiFactory.GetService(ServiceDescriptor descriptor) in D:\a\_work\1\s\src\Core\src\Hosting\Internal\MauiFactory.cs:line 130
   at Microsoft.Maui.Hosting.Internal.MauiFactory.GetService(Type serviceType, ServiceDescriptor single, IEnumerable`1 enumerable) in D:\a\_work\1\s\src\Core\src\Hosting\Internal\MauiFactory.cs:line 141
   at Microsoft.Maui.Hosting.Internal.MauiFactory.GetService(Type serviceType) in D:\a\_work\1\s\src\Core\src\Hosting\Internal\MauiFactory.cs:line 36
   at Microsoft.Maui.Hosting.Internal.MauiHandlersFactory.GetHandler(Type type) in D:\a\_work\1\s\src\Core\src\Hosting\Internal\MauiHandlersFactory.cs:line 30
   at Microsoft.Maui.Controls.Compatibility.Platform.Android.Platform.CreateRenderer(VisualElement element, Context context, FragmentManager fragmentManager, LayoutInflater layoutInflater) in D:\a\_work\1\s\src\Compatibility\Core\src\Android\AppCompat\Platform.cs:line 344
[0:] [20:18:45 WRN] System.MissingMethodException: No parameterless constructor defined for type 'Microsoft.Maui.Controls.Handlers.Compatibility.ListViewRenderer'.
   at System.RuntimeType.CreateInstanceMono(Boolean nonPublic, Boolean wrapExceptions)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at Microsoft.Maui.Hosting.Internal.MauiFactory.CreateInstance(ServiceDescriptor item) in D:\a\_work\1\s\src\Core\src\Hosting\Internal\MauiFactory.cs:line 162
   at Microsoft.Maui.Hosting.Internal.MauiFactory.GetService(ServiceDescriptor descriptor) in D:\a\_work\1\s\src\Core\src\Hosting\Internal\MauiFactory.cs:line 130
   at Microsoft.Maui.Hosting.Internal.MauiFactory.GetService(Type serviceType, ServiceDescriptor single, IEnumerable`1 enumerable) in D:\a\_work\1\s\src\Core\src\Hosting\Internal\MauiFactory.cs:line 141
   at Microsoft.Maui.Hosting.Internal.MauiFactory.GetService(Type serviceType) in D:\a\_work\1\s\src\Core\src\Hosting\Internal\MauiFactory.cs:line 36
   at Microsoft.Maui.Hosting.Internal.MauiHandlersFactory.GetHandler(Type type) in D:\a\_work\1\s\src\Core\src\Hosting\Internal\MauiHandlersFactory.cs:line 30
   at Microsoft.Maui.Controls.Compatibility.Platform.Android.Platform.CreateRenderer(VisualElement element, Context context, FragmentManager fragmentManager, LayoutInflater layoutInflater) in D:\a\_work\1\s\src\Compatibility\Core\src\Android\AppCompat\Platform.cs:line 344
```

**Comment by kristinx0211** [comment]
@anpin your repro project can‘t be unpacked. could you check for this and upload the correct one, thanks.

**Comment by anpin** [comment]
@kristinx0211 please try this [maui-android-handler-activator-issue.zip](https://github.com/dotnet/maui/files/8867895/maui-android-handler-activator-issue.zip)

**Comment by kristinx0211** [comment]
@anpin thanks for your update, I can repro this issue on android, ListView does not show, I'm not get the exception, on windows, the ListView is showing.
![image](https://user-images.githubusercontent.com/99457000/172810901-17f4cbe5-849e-40fe-9634-3ed6098c6d58.png)

**Comment by anpin** [comment]
Here I'm running on another Android device. Can you share your Android screen shoot not Windows? What is your SDK version?
![Screenshot_20220609-144535](https://user-images.githubusercontent.com/6060545/172829738-1d3f154d-3e55-4077-b239-3cb659ec09ab.jpg)

**Comment by anpin** [comment]
> on android 12: ![image](https://user-images.githubusercontent.com/99457000/172970264-3dd39685-d616-46de-93d0-c3b7b1c500b6.png) dotnet info: ![image](https://user-images.githubusercontent.com/99457000/172970317-12c2603d-1c09-444b-8b49-e23485b30e1a.png)

sorry I misread your original response, thought you said you can't reproduce it on Android

**Comment by anpin** [comment]
You can see original exception on Android if you configure logging as such 
in `csproj` use `<PackageReference Include="Microsoft.Extensions.Logging.Console" Version="6.0.0" />` and in `MauiProgram.cs` use that `builder.Services.AddLogging(l => l.AddConsole());`

Adjusted repro here -> [maui-android-handler-activator-issue.zip](https://github.com/dotnet/maui/files/8933113/maui-android-handler-activator-issue.zip)

**Comment by jbe2277** [comment]
I get the same exception when I want to migrate a Xamarin 5 project to MAUI. Unfortunately, this blocks me from migration to MAUI.

Used version: Visual Studio 2022 17.3.2

Starting on Android 12 results in the following exception:
```
System.MissingMethodException
  Message=No parameterless constructor defined for type 'Microsoft.Maui.Controls.Handlers.Compatibility.ListViewRenderer'.
```

**Comment by bnoffer** [comment]
We were suddenly seeing this exception on CollectionView while it was wrapped in a RelativeLayout from MAUI Compatibility. We ended up refactoring the particular page and removing the RelativeLayout.

**Comment by jenscski** [comment]
Same problem here, we have a big Xamarin Forms application that we need to convert to .NET MAUI, without the compatibility layer we have to refactor ever page before release on .NET MAUI, which is probably to big task

**Comment by smeagol75** [comment]
We are facing same problem after upgrading from Net 7 to Net 8.0.3, and the hole app is based on Relative Layouts, to be honest we are loosing time, effort and money dealing with Maui, the last thing we want to see is a compat library that stops working with a simple update.... :( I´ll try to find a workaround) Forms to Maui is really a pain.

**Comment by Vishnu473** [comment]
any update on the above exception that is getting for frame renderer as i was also facing same.

**Comment by joaodarocha1** [comment]
I had a similar issue with Frames

**System.MissingMethodException:** 'No parameterless constructor defined for type 'Microsoft.Maui.Controls.Handlers.Compatibility.FrameRenderer'.'

My workaround was to change the Frames to Borders

**Comment by EeKay** [comment]
any updates? Noticing this on a client's project that I'm upgrading. also using compatibility mode and RelativeLayout with a ListView

**Comment by EeKay** [comment]
I've resolved this by using a Grid implementation. Though, it might be good to reference this issue for people currently in the migration phase towards MAUI

**Comment by Mark-NC001** [comment]
Is there any news on this? I have a major project to convert from Xamarin.Forms, and am getting this on a very basic page that simply has a ListView as it's main content - if I can't get this page to work then I've no hope for the rest of the project!!!

**Comment by maexsp** [comment]
This also happens rarely/sometimes when the build output and cache gets wasted and somehow destroyed. E.g. during VS2022 debug session crash or instable VS2022, etc.

1. Shutdown all VS2022
2. remove or cleanup all bin/obj/.vs folders of your solution
3. clean all "Cache" folders in %appdata%\Local\Microsoft\VisualStudio\Roslyn
4. clean all "ComponentModelCache" folders in %appdata%\Local\Microsoft\VisualStudio
5. Build all again. Check yout VS2022 "Output" folder window if issue still exists.

I use a powershell script to make live easier :)

**Comment by rokmeglic71** [comment]
This still happens on .NET9 + latest MAUI 9.0.30.
Reading [](https://docs.telerik.com/devtools/maui/knowledge-base/maui-compatibility-net-telerik-nuget-filenotfoundexception) I thought it would help adding  <PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="$(MauiVersion)" />, but it does not help.

**Error:**
System.MissingMethodException: No parameterless constructor defined for type 'Microsoft.Maui.Controls.Handlers.Compatibility.ListViewRenderer'.

**Comment by rubiomiguel06** [comment]
So.. no one from Microsoft team is even taking a look into this. I have just found myself with this same issue. Any workarounds?

**Comment by rokmeglic71** [comment]
I posted the question yesterday, so it is an early bird🙏👍

I am happy I am not alone. One possible solution would be to cross post 
on GemBox PDF support forum?


2025-02-20 19:27, je Miguel Rubio napisal

**Comment by EeKay** [comment]
> So.. no one from Microsoft team is even taking a look into this. I have just found myself with this same issue. Any workarounds?

Nope. At MAUI Day in Koln last year, it was evident that they dropped support for this and removed the compatibility stuff since there are alternatives to do this (I used a grid control together, coded together with my AI buddy in Cursor AI). Took some trial and error but works like a charm.

But no, compatibility won't be working anymore for the latest MAUI versions

**Comment by jfversluis** [comment]
Both compatibility and ListView will be going away/obsoleted for .NET 10, so I don't think this will be worked on anymore. Thanks for all the input here!
