### ISSUE TITLE
Crash on function invoking, if function was created from lambda expression in a release mode (iOS)

### ISSUE THREAD

**Issue by MariyaGordeeva** [dotnet/maui#7815]
### Description

Please see following project to reproduce this issue: [test.zip](https://github.com/dotnet/maui/files/8853079/test.zip)
Same code works perfectly in Xamarin.Forms (iOS release).

### Steps to Reproduce

1. Open project folder in terminal
2. Run 'dotnet build -t:run -f:net6.0-ios -p:_DeviceName=insert_device_id_here /p:RuntimeIdentifier=ios-arm64 -c release'

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS 15

**Comment by MariyaGordeeva** [comment]
Yes, app crashes with the same exception 
> 
[TEST_IOS.zip](https://github.com/dotnet/maui/files/8855779/TEST_IOS.zip)

**Comment by jfversluis** [comment]
@dalexsoto @rolfbjarne Since it's happening on pure iOS as well I guess this is something for you?

**Comment by rolfbjarne** [comment]
Is there a stack trace / crash report? This might be either for xamarin/xamarin-macios or dotnet/runtime, depending on what's happening.

**Comment by AntonKosenkoDX** [comment]
Here it is:
```

2022-06-24 14:20:42.443 TEST_IOS[59568:4380379] System.ExecutionEngineException: Attempting to JIT compile method '(wrapper delegate-invoke) string <Module>:invoke_callvirt_string_object (object)' while running in aot-only mode. See https://docs.microsoft.com/xamarin/ios/internals/limitations for more information.
2022-06-24 14:20:42.443 TEST_IOS[59568:4380379]    at System.Linq.Expressions.Interpreter.FuncCallInstruction`2[[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Run(InterpretedFrame )
   at System.Linq.Expressions.Interpreter.Interpreter.Run(InterpretedFrame )
   at System.Linq.Expressions.Interpreter.LightLambda.Run(Object[] )
2022-06-24 14:20:42.443 TEST_IOS[59568:4380379]    at System.Linq.Expressions.Interpreter.CallInstruction.InterpretLambdaInvoke(LightLambda , Object[] )
2022-06-24 14:20:42.443 TEST_IOS[59568:4380379]    at System.Linq.Expressions.Interpreter.FuncCallInstruction`3[[System.Func`2[[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Run(InterpretedFrame )
   at System.Linq.Expressions.Interpreter.Interpreter.Run(InterpretedFrame )
2022-06-24 14:20:42.443 TEST_IOS[59568:4380379]    at System.Linq.Expressions.Interpreter.LightLambda.Run(Object[] )
   at System.Linq.Expressions.Interpreter.CallInstruction.InterpretLambdaInvoke(LightLambda , Object[] )
2022-06-24 14:20:42.443 TEST_IOS[59568:4380379]    at System.Linq.Expressions.Interpreter.FuncCallInstruction`4[[System.Func`3[[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Boolean, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Boolean, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Run(InterpretedFrame )
2022-06-24 14:20:42.443 TEST_IOS[59568:4380379]    at System.Linq.Expressions.Interpreter.Interpreter.Run(InterpretedFrame )
   at System.Linq.Expressions.Interpreter.LightLambda.Run(Object[] )
   at System.Dynamic.Utils.DelegateHelpers.FuncThunk1[Object[],Object](Func`2 handler, Object[] t1)
2022-06-24 14:20:42.443 TEST_IOS[59568:4380379]    at TEST_IOS.AppDelegate.EvaluateLambdableContainsFunction(Object[] args)
   at TEST_IOS.AppDelegate.FinishedLaunching(UIApplication application, NSDictionary launchOptions)

```
