### ISSUE TITLE
Binding NullReferenceException

### ISSUE THREAD

**Issue by SchreinerK** [dotnet/maui#7977]
### Description

```C#
label.SetBinding(Label.TextProperty, new Binding());
```
throws a weird NullReferenceException on a specific scenario, but works on other.
```
System.NullReferenceException: 'Object reference not set to an instance of an object.'
  at Microsoft.Maui.Controls.Binding.Apply(Object context, BindableObject bindObj, BindableProperty targetProperty, Boolean fromBindingContextChanged)
  at Microsoft.Maui.Controls.BindableObject.SetBinding(BindableProperty targetProperty, BindingBase binding, Boolean fromStyle)
  at Microsoft.Maui.Controls.BindableObject.SetBinding(BindableProperty targetProperty, BindingBase binding)
  at Issue220613_1.MainPage.SequenceErr() in D:\Develop\Local\KsWare\Maui\Issue220613_1\MainPage.xaml.cs:line 15
```
tested with Windows, but also with android emulator I got a less helpful exception.

### Steps to Reproduce

[get complete project](https://github.com/SchreinerK/Issue220613_1_Maui_Binding_NullReferenceException)
-or-
create a new MAUI app.
add to MainPage.xaml.cs:
```C#
var label = new Label();
label.SetBinding(Label.TextProperty, new Binding()); //<-- NullReferenceException
```

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

Windows10.0.19041.0

### Did you find any workaround?

use "." as path
```C#
var label = new Label();
label.SetBinding(Label.TextProperty, new Binding(".")); //<-- OK
...
```
-or-
change sequence
```C#
var label = new Label();
var contentView = new ContentView { 
    BindingContext = "C#",
    Content = label
};
label.SetBinding(Label.TextProperty, new Binding());	//<-- OK
```

**Comment by VincentBu** [comment]
repro with vs [32613.285.main]
