### ISSUE TITLE
InvalidOperationException: VisualStateGroup Names must be unique

### ISSUE THREAD

**Issue by yz2yz** [dotnet/maui#8003]
### Description

when i use VisualState, there are InvalidOperationException: VisualStateGroup Names must be unique at build time. like as:

            <Entry FontSize="18">
                <VisualStateManager.VisualStateGroups>
                    <VisualStateGroup x:Name="CommonStates">
                        <VisualState x:Name="Normal">
                            <VisualState.Setters>
                                <Setter Property="BackgroundColor" Value="Lime" />
                            </VisualState.Setters>
                        </VisualState>

                        <VisualState x:Name="Focused">
                            <VisualState.Setters>
                                <Setter Property="FontSize" Value="36" />
                            </VisualState.Setters>
                        </VisualState>

                        <VisualState x:Name="Disabled">
                            <VisualState.Setters>
                                <Setter Property="BackgroundColor" Value="Pink" />
                            </VisualState.Setters>
                        </VisualState>
                    </VisualStateGroup>
                </VisualStateManager.VisualStateGroups>
            </Entry>

### Steps to Reproduce

create a maui app
add an entry
add state group

### Version with bug

6.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, Windows

### Affected platform versions

Android 10、windows sdk 10.0.19041.0

### Did you find any workaround?

no workaround

### Relevant log output

```shell
System.Reflection.TargetInvocationException
  HResult=0x80131604
  Message=Exception has been thrown by the target of an invocation.
  Source=Microsoft.Maui.Controls.Xaml
  StackTrace:
   at Microsoft.Maui.Controls.Xaml.ApplyPropertiesVisitor.SetPropertyValue(Object xamlelement, XmlName propertyName, Object value, Object rootElement, INode node, HydrationContext context, IXmlLineInfo lineInfo)
   at Microsoft.Maui.Controls.Xaml.ApplyPropertiesVisitor.Visit(ElementNode node, INode parentNode)
   at Microsoft.Maui.Controls.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
   at Microsoft.Maui.Controls.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
   at Microsoft.Maui.Controls.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
   at Microsoft.Maui.Controls.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
   at Microsoft.Maui.Controls.Xaml.RootNode.Accept(IXamlNodeVisitor visitor, INode parentNode)
   at Microsoft.Maui.Controls.Xaml.XamlLoader.Visit(RootNode rootnode, HydrationContext visitorContext, Boolean useDesignProperties)
   at Microsoft.Maui.Controls.Xaml.XamlLoader.Load(Object view, String xaml, Assembly rootAssembly, Boolean useDesignProperties)
   at Microsoft.Maui.Controls.Xaml.XamlLoader.Load(Object view, String xaml, Boolean useDesignProperties)
   at Microsoft.Maui.Controls.Xaml.XamlLoader.Load(Object view, Type callingType)
   at Microsoft.Maui.Controls.Xaml.Extensions.LoadFromXaml[TXaml](TXaml view, Type callingType)
   at DataTrigger1.MainPage.InitializeComponent() in E:\z6\maui\learn1\DataTrigger1\DataTrigger1\Microsoft.Maui.Controls.SourceGen\Microsoft.Maui.Controls.SourceGen.CodeBehindGenerator\MainPage.xaml.sg.cs:line 26
   at DataTrigger1.MainPage..ctor() in E:\z6\maui\learn1\DataTrigger1\DataTrigger1\MainPage.xaml.cs:line 9
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
InvalidOperationException: VisualStateGroup Names must be unique
```

**Comment by VincentBu** [comment]
repro with vs [32613.285.main]

**Comment by MagicAndre1981** [comment]
I have the same issue when trying to port XF to MAUI.

**Comment by MagicAndre1981** [comment]
ok, I found in the [demos/Tests here in the repro](https://github.com/dotnet/maui/blob/0f73f014c11ac4bab633d72e1711b86ecb3978d5/src/Compatibility/ControlGallery/src/Core/GalleryPages/VisualStateManagerGalleries/EditorDisabledStatesGallery.xaml#L15), that all have `<VisualStateGroupList></VisualStateGroupList>` and adding this fixed it for me. 

So add it

```
<Entry FontSize="18">
            <VisualStateManager.VisualStateGroups>
              <VisualStateGroupList>
                <VisualStateGroup x:Name="CommonStates">
                    <VisualState x:Name="Normal">
                        <VisualState.Setters>
                            <Setter Property="BackgroundColor" Value="Lime" />
                        </VisualState.Setters>
                    </VisualState>

                    <VisualState x:Name="Focused">
                        <VisualState.Setters>
                            <Setter Property="FontSize" Value="36" />
                        </VisualState.Setters>
                    </VisualState>

                    <VisualState x:Name="Disabled">
                        <VisualState.Setters>
                            <Setter Property="BackgroundColor" Value="Pink" />
                        </VisualState.Setters>
                    </VisualState>
                </VisualStateGroup>
             </VisualStateGroupList
            </VisualStateManager.VisualStateGroups>
        </Entry>
```

and it works:

![maui_issue_8003](https://user-images.githubusercontent.com/8274816/178811205-2f52c3d7-edc9-4d75-896f-2d5086d9d43b.png)

I'm not sure why this is different compared to Xamarin.Forms 🤔 🤷‍♂️

**Comment by StephaneDelcroix** [comment]
This is all as it should. When not specifying the VisualGroupList explicitly, the XAML inflater will try to add to the existing one. The only difference with what you used to do in XF, is that a newly created app from template comes with a default style, including a style for entry.
