### ISSUE TITLE
[Android] 1. ToPlatformException: CollectionViewHandler incompatible 2. Button width incorrect。

### ISSUE THREAD

**Issue by danch15** [dotnet/maui#8039]
### Description

Microsoft Visual Studio Enterprise 2022 (64 bit) - Preview Version 17.3.0 Preview 2.0

Android APP:
Error 1: Microsoft.Maui.Platform.ToPlatformException: 'Microsoft.Maui.Controls.Handlers.Items.CollectionViewHandler found for Microsoft.Maui.Controls.CollectionView is incompatible'

Error 2: The button's width is not changed when the text is changed. 

### Steps to Reproduce

Reproduction project: https://github.com/danch15/MauiAndDevDemo

1.Create the MAUI project use the command "dotnet new maui", add xmal code into the MainPage.xaml: <CollectionView SelectionMode="Single" EmptyView="Empty"/>
Just like:  
...
<Button 
                x:Name="CounterBtn"
                Text="Click me"
                SemanticProperties.Hint="Counts the number of times you click"
                Clicked="OnCounterClicked"
                HorizontalOptions="Center" />

            <CollectionView SelectionMode="Single" EmptyView="Empty"/>

        </VerticalStackLayout>
    </ScrollView>
 
</ContentPage>

2. Run the demo in Android 7.1.2, then the exception shows in the VS: 
Microsoft.Maui.Platform.ToPlatformException: 'Microsoft.Maui.Controls.Handlers.Items.CollectionViewHandler found for Microsoft.Maui.Controls.CollectionView is incompatible'.

3. By the way, in the Android System 7.1.2, when you click the CounterBtn, the Button's width is not changed, but in Windows Machine is OK.

### Version with bug

6.0 (current)

### Last version that worked well

Release Candidate 3 (current)

### Affected platforms

Android

### Affected platform versions

Android 7.1.2 and Android Samsung NOTE 9 Cell Phone (Android 10)

### Did you find any workaround?

It seems like the CollectionView Control's SelectionMode and the EmptyView propertys can't use together in the maui 6.0.400 version.
In the Windows Machine, everything is OK. The maui old version I never catch the ToPlatformException too witch the same code.

### Relevant log output

```shell
Error 1:
Microsoft.Maui.Platform.ToPlatformException
  Message=Microsoft.Maui.Controls.Handlers.Items.CollectionViewHandler found for Microsoft.Maui.Controls.CollectionView is incompatible
  Source=Microsoft.Maui
  StackTrace:
   at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context) in D:\a\_work\1\s\src\Core\src\Platform\ElementExtensions.cs:line 113
   at Microsoft.Maui.Platform.ElementExtensions.ToPlatform(IElement view, IMauiContext context) in D:\a\_work\1\s\src\Core\src\Platform\ElementExtensions.cs:line 142
   at Microsoft.Maui.Handlers.LayoutHandler.SetVirtualView(IView view) in D:\a\_work\1\s\src\Core\src\Handlers\Layout\LayoutHandler.Android.cs:line 43
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.ILayout, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.LayoutViewGroup, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IElement view) in D:\a\_work\1\s\src\Core\src\Handlers\View\ViewHandlerOfT.cs:line 56
   at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler) in D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\Element\Element.Impl.cs:line 64
   at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value) in D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\Element\Element.Impl.cs:line 20
   at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.set_Handler(IElementHandler value) in D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\VisualElement\VisualElement.Impl.cs:line 299
   at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context) in D:\a\_work\1\s\src\Core\src\Platform\ElementExtensions.cs:line 105
   at Microsoft.Maui.Platform.ElementExtensions.ToPlatform(IElement view, IMauiContext context) in D:\a\_work\1\s\src\Core\src\Platform\ElementExtensions.cs:line 142
   at Microsoft.Maui.Platform.ScrollViewExtensions.UpdateContent(MauiScrollView scrollView, IView content, IMauiContext context) in D:\a\_work\1\s\src\Core\src\Platform\Android\ScrollViewExtensions.cs:line 36
   at Microsoft.Maui.Handlers.ScrollViewHandler.MapContent(IScrollViewHandler handler, IScrollView scrollView) in D:\a\_work\1\s\src\Core\src\Handlers\ScrollView\ScrollViewHandler.Android.cs:line 71
   at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0[[Microsoft.Maui.IScrollView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.IScrollViewHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v) in D:\a\_work\1\s\src\Core\src\PropertyMapper.cs:line 183
   at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IElementHandler viewHandler, IElement virtualView) in D:\a\_work\1\s\src\Core\src\PropertyMapper.cs:line 47
   at Microsoft.Maui.PropertyMapper.UpdateProperties(IElementHandler viewHandler, IElement virtualView) in D:\a\_work\1\s\src\Core\src\PropertyMapper.cs:line 82
   at Microsoft.Maui.Handlers.ElementHandler.SetVirtualView(IElement view) in D:\a\_work\1\s\src\Core\src\Handlers\Element\ElementHandler.cs:line 74
   at Microsoft.Maui.Handlers.ViewHandler.SetVirtualView(IElement element) in D:\a\_work\1\s\src\Core\src\Handlers\View\ViewHandler.cs:line 125
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IScrollView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.MauiScrollView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IView view) in D:\a\_work\1\s\src\Core\src\Handlers\View\ViewHandlerOfT.cs:line 53
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IScrollView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.MauiScrollView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IElement view) in D:\a\_work\1\s\src\Core\src\Handlers\View\ViewHandlerOfT.cs:line 56
   at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler) in D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\Element\Element.Impl.cs:line 64
   at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value) in D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\Element\Element.Impl.cs:line 20
   at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.set_Handler(IElementHandler value) in D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\VisualElement\VisualElement.Impl.cs:line 299
   at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context) in D:\a\_work\1\s\src\Core\src\Platform\ElementExtensions.cs:line 105
   at Microsoft.Maui.Platform.ElementExtensions.ToPlatform(IElement view, IMauiContext context) in D:\a\_work\1\s\src\Core\src\Platform\ElementExtensions.cs:line 142
   at Microsoft.Maui.Handlers.ContentViewHandler.UpdateContent(IContentViewHandler handler) in D:\a\_work\1\s\src\Core\src\Handlers\ContentView\ContentViewHandler.Android.cs:line 44
   at Microsoft.Maui.Handlers.ContentViewHandler.MapContent(IContentViewHandler handler, IContentView page) in D:\a\_work\1\s\src\Core\src\Handlers\ContentView\ContentViewHandler.Android.cs:line 49
   at Microsoft.Maui.PropertyMapper`2.<>c__DisplayClass5_0[[Microsoft.Maui.IContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Handlers.IContentViewHandler, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<Add>b__0(IElementHandler h, IElement v) in D:\a\_work\1\s\src\Core\src\PropertyMapper.cs:line 183
   at Microsoft.Maui.PropertyMapper.UpdatePropertyCore(String key, IElementHandler viewHandler, IElement virtualView) in D:\a\_work\1\s\src\Core\src\PropertyMapper.cs:line 47
   at Microsoft.Maui.PropertyMapper.UpdateProperties(IElementHandler viewHandler, IElement virtualView) in D:\a\_work\1\s\src\Core\src\PropertyMapper.cs:line 82
   at Microsoft.Maui.Handlers.ElementHandler.SetVirtualView(IElement view) in D:\a\_work\1\s\src\Core\src\Handlers\Element\ElementHandler.cs:line 74
   at Microsoft.Maui.Handlers.ViewHandler.SetVirtualView(IElement element) in D:\a\_work\1\s\src\Core\src\Handlers\View\ViewHandler.cs:line 125
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.ContentViewGroup, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IView view) in D:\a\_work\1\s\src\Core\src\Handlers\View\ViewHandlerOfT.cs:line 53
   at Microsoft.Maui.Handlers.ContentViewHandler.SetVirtualView(IView view) in D:\a\_work\1\s\src\Core\src\Handlers\ContentView\ContentViewHandler.Android.cs:line 27
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.ContentViewGroup, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].SetVirtualView(IElement view) in D:\a\_work\1\s\src\Core\src\Handlers\View\ViewHandlerOfT.cs:line 56
   at Microsoft.Maui.Controls.Element.SetHandler(IElementHandler newHandler) in D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\Element\Element.Impl.cs:line 64
   at Microsoft.Maui.Controls.Element.set_Handler(IElementHandler value) in D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\Element\Element.Impl.cs:line 20
   at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IElement.set_Handler(IElementHandler value) in D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\VisualElement\VisualElement.Impl.cs:line 299
   at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context) in D:\a\_work\1\s\src\Core\src\Platform\ElementExtensions.cs:line 105
   at Microsoft.Maui.Platform.ViewExtensions.ToHandler(IView view, IMauiContext context) in D:\a\_work\1\s\src\Core\src\Platform\ViewExtensions.cs:line 44
   at Microsoft.Maui.Controls.Platform.Compatibility.ShellFragmentContainer.OnCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) in D:\a\_work\1\s\src\Controls\src\Core\Compatibility\Handlers\Shell\Android\ShellFragmentContainer.cs:line 41
   at AndroidX.Fragment.App.Fragment.n_OnCreateView_Landroid_view_LayoutInflater_Landroid_view_ViewGroup_Landroid_os_Bundle_(IntPtr jnienv, IntPtr native__this, IntPtr native_inflater, IntPtr native_container, IntPtr native_savedInstanceState) in C:\a\_work\1\s\generated\androidx.fragment.fragment\obj\Release\net6.0-android\generated\src\AndroidX.Fragment.App.Fragment.cs:line 1999
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPLLL_L(_JniMarshal_PPLLL_L callback, IntPtr jnienv, IntPtr klazz, IntPtr p0, IntPtr p1, IntPtr p2) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 352
```

**Comment by jfversluis** [comment]
Thanks for the report @danch15! I see you've added reproduction steps, but the XAML you've added doesn't really seem valid. So not sure if anything went wrong there, but just to be sure could you double-check and update that? Ideally we would love to have a small reproduction project that shows this issue. That way we know sure we're not missing anything.

PS, please report one bug per issue, that will make it easier to track them separately :)

**Comment by danch15** [comment]
@jfversluis  The project is here: https://github.com/danch15/MauiAndDevDemo/blob/main/MAUI6.0.400.rar, just download and upzip it.

**Comment by singhwong** [comment]
When I updated to maui 6.4.0, I got the same exception.

**Comment by An0d** [comment]
> When I updated to maui 6.4.0, I got the same exception.

Same here :(

**Comment by shinnthant-lab** [comment]
Same issue when trying to follow this blog post.
**https://www.cayas.de/blog/dotnet-maui-custom-map-handler**

**Comment by KarlSearl** [comment]
Ive got this after updating .
![image](https://user-images.githubusercontent.com/64684177/174260984-13ef3f30-f7c0-4e44-a0fb-9f5d5293a952.png)

**Comment by jmdess** [comment]
Same exception here **### when** I put a CollectionView.EmptyView in my MainPage
(on Windows 10 21H2 EN version, VStudio 2022 17.3.0 Preview 2.0, in the process converting Xamarin.Forms Android to Maui application)

**Comment by shinnthant-lab** [comment]
Same exception with CarouselView
![image](https://user-images.githubusercontent.com/54578974/174626626-02b9fdf2-88a6-43c4-8238-b242de7d35c7.png)

**Comment by kristinx0211** [comment]
Same exception with vs 17.3.0 Preview 3.0 [32621.293.main].
![image](https://user-images.githubusercontent.com/99457000/174935812-e27a214e-712c-4c44-b00d-91cfdc19c18b.png)

**Comment by kojini** [comment]
Same exception with CarouselView. Specifying `CurrentItem` causes the exception. I don't use `EmptyView` in my CarouselView.

**Comment by acxsasx** [comment]
I was getting this error "Message=Microsoft.Maui.Controls.Handlers.Items.CollectionViewHandler found for Microsoft.Maui.Controls.CollectionView is incompatible"

`
                <CollectionView x:Name="Targets" BackgroundColor="OrangeRed" SelectionMode="Single"
                            ItemsSource="{Binding TargetSelections}"
                            EmptyView="Select an attacker..."
                            SelectedItem="{Binding TargetSelected}"
                            Grid.Row="8" Grid.RowSpan="3"
                            Grid.Column="0" Grid.ColumnSpan="2" >`

I removed EmptyView="Select an attacker..." and all was happy again.  Worked fine in Preview 1.1.

**Comment by XamerDev** [comment]
same here, so my list of products in meals cannot be empty maybe it's ok for maui, but I don't know if it will be too for my belly  :D
