### ISSUE TITLE
Using a compatibility renderer for button on iOS causes crash

### ISSUE THREAD

**Issue by RealGoodAnthony** [dotnet/maui#8153]
### Description

If you use a compatibility renderer for a custom button element, you will generate a crash on iOS when MAUI's view extensions attempt to calculate the desired size. For a simple repro, please see the following repository: https://github.com/RealGoodAnthony/ButtonRendererCrashRepro

### Steps to Reproduce

You may follow the steps below, or simply clone this repository to save yourself some time: https://github.com/RealGoodAnthony/ButtonRendererCrashRepro

1. Create a custom button element, ie:
```
public class AppButton : Button
{
}
```

2. Create an iOS compatibility renderer (in the Platforms/iOS directory, for example):
```
using Microsoft.Maui.Controls.Compatibility.Platform.iOS;

public class AppButtonRenderer : ButtonRenderer
{
}
```

3. Enable Forms compatibility mode and register your compatibility handler in the MauiProgram:
```
#if IOS
using ButtonRendererCrashRepro.Platforms.iOS;
#endif
using Microsoft.Maui.Controls.Compatibility.Hosting;

public static class MauiProgram
{
	public static MauiApp CreateMauiApp()
	{
		var builder = MauiApp.CreateBuilder();
		builder
			.UseMauiApp<App>()
			.UseMauiCompatibility()
			.ConfigureMauiHandlers(handlers =>
			{
#if IOS
					handlers.AddCompatibilityRenderer(
						typeof(AppButton),
						typeof(AppButtonRenderer));
#endif
			});

		return builder.Build();
	}
}
```

4. Use your `<AppButton />` in any XAML view.
5. Launch the app and observe the crash. The stack trace is available below.

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

iOS

### Affected platform versions

iOS

### Did you find any workaround?

No workaround available other than not using compatibility renderers.

### Relevant log output

```shell
System.ArgumentException: NaN is not a valid value for width
   at Microsoft.Maui.Graphics.Size..ctor(Double width, Double height)
   at Microsoft.Maui.ViewHandlerExtensions.GetDesiredSizeFromHandler(IViewHandler viewHandler, Double widthConstraint, Double heightConstraint)
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[UIKit.UIView, Microsoft.iOS, Version=15.4.300.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065]].GetDesiredSize(Double widthConstraint, Double heightConstraint)
   at Microsoft.Maui.Layouts.LayoutExtensions.ComputeDesiredSize(IView view, Double widthConstraint, Double heightConstraint)
   at Microsoft.Maui.Controls.VisualElement.MeasureOverride(Double widthConstraint, Double heightConstraint)
   at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IView.Measure(Double widthConstraint, Double heightConstraint)
   at Microsoft.Maui.Layouts.VerticalStackLayoutManager.Measure(Double widthConstraint, Double heightConstraint)
   at Microsoft.Maui.Controls.Layout.CrossPlatformMeasure(Double widthConstraint, Double heightConstraint)
   at Microsoft.Maui.Platform.LayoutView.SizeThatFits(CGSize size)
   at Microsoft.Maui.ViewHandlerExtensions.GetDesiredSizeFromHandler(IViewHandler viewHandler, Double widthConstraint, Double heightConstraint)
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.ILayout, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.LayoutView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].GetDesiredSize(Double widthConstraint, Double heightConstraint)
   at Microsoft.Maui.Layouts.LayoutExtensions.ComputeDesiredSize(IView view, Double widthConstraint, Double heightConstraint)
   at Microsoft.Maui.Controls.VisualElement.MeasureOverride(Double widthConstraint, Double heightConstraint)
   at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IView.Measure(Double widthConstraint, Double heightConstraint)
   at Microsoft.Maui.Controls.ScrollView.Microsoft.Maui.IContentView.CrossPlatformMeasure(Double widthConstraint, Double heightConstraint)
   at Microsoft.Maui.Handlers.ScrollViewHandler.GetDesiredSize(Double widthConstraint, Double heightConstraint)
   at Microsoft.Maui.Layouts.LayoutExtensions.ComputeDesiredSize(IView view, Double widthConstraint, Double heightConstraint)
   at Microsoft.Maui.Controls.ScrollView.MeasureOverride(Double widthConstraint, Double heightConstraint)
   at Microsoft.Maui.Controls.Compatibility.Layout.Microsoft.Maui.IView.Measure(Double widthConstraint, Double heightConstraint)
   at Microsoft.Maui.Layouts.LayoutExtensions.MeasureContent(IContentView contentView, Thickness inset, Double widthConstraint, Double heightConstraint)
   at Microsoft.Maui.Layouts.LayoutExtensions.MeasureContent(IContentView contentView, Double widthConstraint, Double heightConstraint)
   at Microsoft.Maui.Controls.ContentPage.Microsoft.Maui.IContentView.CrossPlatformMeasure(Double widthConstraint, Double heightConstraint)
   at Microsoft.Maui.Platform.ContentView.LayoutSubviews()
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)
   at ButtonRendererCrashRepro.Program.Main(String[] args) in Program.cs:line 13
```

**Comment by kristinx0211** [comment]
verified repro on IOS15.4 with vs 17.3.0 Preview 3.0 [32621.293.main].

**Comment by jsuarezruiz** [comment]
Cannot reproduce the issue using the current main branch or 6.0.525 workloads.

<img width="477" alt="Captura de Pantalla 2022-09-08 a las 12 21 49" src="https://user-images.githubusercontent.com/6755973/189098621-fecab897-c9d1-4e94-916f-5301c23e7480.png">

Could you try again with latest version?
