### ISSUE TITLE
[Android] Shell.Current.GoToAsync throws exception 'Current Root View cannot be null'

### ISSUE THREAD

**Issue by AndreasReitberger** [dotnet/maui#8159]
### Description

If I navigate to a modal page on Android (iOS not tested) I get an exception. Normal pages are working fine.

![image](https://user-images.githubusercontent.com/2952443/174469307-01f50b48-00e5-4e88-b050-57f560713239.png)

```cs
await DispatchManager.UpdateUIThreadSaveAsync(async () =>
{
    try
    {
        PreviousRoute = GetCurrentRoute();
        await Shell.Current.GoToAsync(target, animate);
    }
    catch (Exception exc)
    {
        EventManager.Instance.LogError(exc);
    }
});
```

View I wanted to show:

```xaml
<ContentPage
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    x:Class="KlipperRemoteControl.PrintServerManageJobListModalPage"
    
    xmlns:localization="clr-namespace:KlipperRemoteControl.Resources.Localization"
    xmlns:viewModels="clr-namespace:KlipperRemoteControl.ViewModels.Modals"
    
    xmlns:controls="clr-namespace:KlipperRemoteControl.Controls"
    xmlns:controlsShared="clr-namespace:AndreasReitberger.Shared.Controls;assembly=SharedMauiXamlStylesLibrary"
    xmlns:convertersShared="clr-namespace:AndreasReitberger.Shared.Core.Converters;assembly=SharedMauiCoreLibrary"
    
    Title="{x:Static localization:Strings.HeadlineJobList}"
    Style="{StaticResource ModalPageStyle}"
    x:DataType="viewModels:PrintServerManageJobListModalPageViewModel"
    >
    <ContentPage.BindingContext>
        <viewModels:PrintServerManageJobListModalPageViewModel x:Name="ViewModel" />
    </ContentPage.BindingContext>
</ContentPage>
```

Style:
```xaml
<Style x:Key="ModalPageStyle" TargetType="ContentPage" BasedOn="{StaticResource DefaultPageStyle}">
    <Setter Property="Shell.PresentationMode" Value="ModalAnimated" />
    <Setter Property="ios:Page.ModalPresentationStyle" Value="{OnIdiom Tablet=Automatic, Default=FormSheet}" />
</Style>
```

### Steps to Reproduce

1. Create a ModalPage with <`Setter Property="Shell.PresentationMode" Value="ModalAnimated" />`
2. Call it with  `await Shell.Current.GoToAsync(ModalPage, animate: true);` on Android
3. See the exception

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 11 (API 30)

### Relevant log output

```shell
at Microsoft.Maui.Controls.Platform.ModalNavigationManager.GetCurrentRootView() in D:\a\_work\1\s\src\Controls\src\Core\Platform\ModalNavigationManager\ModalNavigationManager.Android.cs:line 102
   at Microsoft.Maui.Controls.Platform.ModalNavigationManager.PushModalAsync(Page modal, Boolean animated) in D:\a\_work\1\s\src\Controls\src\Core\Platform\ModalNavigationManager\ModalNavigationManager.Android.cs:line 110
   at Microsoft.Maui.Controls.Window.NavigationImpl.OnPushModal(Page modal, Boolean animated) in D:\a\_work\1\s\src\Controls\src\Core\HandlerImpl\Window\Window.Impl.cs:line 541
   at Microsoft.Maui.Controls.Shell.NavigationImpl.OnPushModal(Page modal, Boolean animated) in D:\a\_work\1\s\src\Controls\src\Core\Shell\Shell.cs:line 1711
   at Microsoft.Maui.Controls.ShellSection.GoToAsync(ShellNavigationRequest request, ShellRouteParameters queryData, IServiceProvider services, Nullable`1 animate, Boolean isRelativePopping) in D:\a\_work\1\s\src\Controls\src\Core\Shell\ShellSection.cs:line 574
   at Microsoft.Maui.Controls.ShellNavigationManager.GoToAsync(ShellNavigationParameters shellNavigationParameters, ShellNavigationRequest navigationRequest) in D:\a\_work\1\s\src\Controls\src\Core\Shell\ShellNavigationManager.cs:line 196
   at KlipperRemoteControl.Models.NavigationManager.ShellNavigator.<>c__DisplayClass20_0.<<GoToAsync>b__0>d.MoveNext() in C:\KCR\maui\KlipperRemoteControl\KlipperRemoteControl\Models\NavigationManager\ShellNavigator.cs:line 117
```

**Comment by speschka** [comment]
I'm having what is probably the same problem.  I have code that looks like this:'

            FindWherePage fwp = new FindWherePage() { Listings = listings };
            await Navigation.PushModalAsync(fwp, true);

When I run this on an Android emulator, it throws an exception that says "Current Root View cannot be null".  When I try it on iOS, it works.  Android emulator is Pixel 5, API 30.  When I try it as just Navigation.PushAsync (i.e. NOT modal) it works fine on Android.

Steve
