### ISSUE TITLE
No parameterless constructor defined for type 'Microsoft.Maui.Controls.Handlers.Compatibility.FrameRenderer

### ISSUE THREAD

**Issue by PaulAndersonS** [dotnet/maui#8197]
### Description

Description
Exception thrown on Android when replacing the App.MainPage with a different page.

Consider the scenario where the ap has a welcome page to request permissions and app settings before displaying the real main page. Once the welcome page has been completed, setting the App MainPage throws the above error.

Steps to Reproduce
Consider the scenario where the ap has a welcome page to request permissions and app settings before displaying the real main page. Once the welcome page has been completed, setting the App MainPage throws the above error.

Version with bug
6.0 (current)

Last version that worked well
Unknown/Other

Affected platforms
Android

Affected platform versions
Android Pie 9 API 28

Did you find any workaround?
No response

Relevant log output
System.MissingMethodException: No parameterless constructor defined for type 'Microsoft.Maui.Controls.Handlers.Compatibility.FrameRenderer'.
  at at System.RuntimeType.CreateInstanceMono(Boolean nonPublic, Boolean wrapExceptions)
  at at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
  at at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
  at at System.Activator.CreateInstance(Type type, Boolean nonPublic)
  at at System.Activator.CreateInstance(Type type)
  at Microsoft.Maui.Hosting.Internal.MauiFactory.CreateInstance(ServiceDescriptor item) in D:\a\_work\1\s\src\Core\src\Hosting\Internal\MauiFactory.cs:162
  at Microsoft.Maui.Hosting.Internal.MauiFactory.GetService(ServiceDescriptor descriptor) in D:\a\_work\1\s\src\Core\src\Hosting\Internal\MauiFactory.cs:130
  at Microsoft.Maui.Hosting.Internal.MauiFactory.GetService(Type serviceType, ServiceDescriptor single, IEnumerable`1 enumerable) in D:\a\_work\1\s\src\Core\src\Hosting\Internal\MauiFactory.cs:141
  at Microsoft.Maui.Hosting.Internal.MauiFactory.GetService(Type serviceType) in D:\a\_work\1\s\src\Core\src\Hosting\Internal\MauiFactory.cs:36
  at Microsoft.Maui.Hosting.Internal.MauiHandlersFactory.GetHandler(Type type) in D:\a\_work\1\s\src\Core\src\Hosting\Internal\MauiHandlersFactory.cs:30
  at Microsoft.Maui.Platform.ElementExtensions.ToHandler(IElement view, IMauiContext context) in D:\a\_work\1\s\src\Core\

### Steps to Reproduce

- Create a sample with Frame control used in it.
- Enable all the exception settings in the VS.

### Version with bug

6.0.400 (current)

### Last version that worked well

6.0.312

### Affected platforms

Android

### Affected platform versions

ANDROID 12

**Comment by osnipezzini** [comment]
Same error here using Shell

**Comment by PureWeen** [comment]
I realize the exception is annoying but it's thrown and caught and then the app moves on. 
Shell throws the error because of font loading which has the same results. 

Is your app crashing? or if you continue the debug session does it continue running?
