### ISSUE TITLE
Exception in SslStream.AuthenticateAsClient in net6.0-android project, works in Xamarin.Android

### ISSUE THREAD

**Issue by AlexNik4** [dotnet/maui#8224]
### Description

Was migrating a Xamarin.Android project to .NET6.0-Android. I am experiencing the following exception when connecting to my server using custom certificates.

    "Authentication failed, see inner exception." 
       at System.Net.Security.SslStream.<ForceAuthenticationAsync>d__173`1[[System.Net.Security.SyncReadWriteAdapter, System.Net.Security, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext()
       at System.Net.Security.SslStream.AuthenticateAsClient(SslClientAuthenticationOptions sslClientAuthenticationOptions)
       at System.Net.Security.SslStream.AuthenticateAsClient(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation)
       at System.Net.Security.SslStream.AuthenticateAsClient(String targetHost)
       at AndroidApp1.MainActivity.OnCreate(Bundle savedInstanceState) in 
    C:\Users\Alex\source\repos\AndroidApp1\AndroidApp1\MainActivity.cs:line 23
InnerException:

     Exception of type 'Interop+AndroidCrypto+SslException' was thrown.

There are no other details in the exception or logs provided as to why authentication failed.

### Steps to Reproduce

I was able to replicate the issue in a brand new .NET6.0-Android app with the following sample client side code. Please note this exact same code snippet works in a brand new Xamarin.Android project on the exact same device. So it should not be a certificate import or device issue. The server is accepting TLS 1.2 and higher protocols.

            protected override void OnCreate(Bundle savedInstanceState)
		{
			base.OnCreate(savedInstanceState);
			SetContentView(Resource.Layout.activity_main);

			string hostname = "work";
			int port = 5280;

			var tcpClient = new TcpClient();
			IAsyncResult result = tcpClient.BeginConnect(hostname, port, null, null);
			var connected = result.AsyncWaitHandle.WaitOne(2000, true);
			if (connected)
			{
				tcpClient.EndConnect(result);
				var stream = new SslStream(tcpClient.GetStream(), false, ValidateServerCertificate, null);
				try
				{
					stream.AuthenticateAsClient(hostname);

					Console.WriteLine("Xamarin.Android Executes Here");
				}
				catch (Exception ex)
				{
					Console.WriteLine(".NET6.0-Android Executes Here");
				}
			}
		}

		private bool ValidateServerCertificate(object sender, X509Certificate certificate, X509Chain chain, SslPolicyErrors sslPolicyErrors)
		{
			return true;
		}

I have tried specifying the ssl protocols on the client and other authentication options with no change in result. I have also tried playing around with HttpClient Implementation setting to make sure it matches the Xamarin.Android project. Again no luck.

![image](https://user-images.githubusercontent.com/53029348/174948270-60739fb4-7633-40d5-a318-d2640da88d19.png)

Visual Studio 17.2.3
dotnet --version
6.0.300

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12, 11

**Comment by PureWeen** [comment]
Moved issue to xamarin android 
https://github.com/xamarin/xamarin-android/issues/7119
