### ISSUE TITLE
Google maps not working - Unable to retrieve flag snapshot for com.google.android.libraries.consentverifier

### ISSUE THREAD

**Issue by LukasKuchta** [dotnet/maui#8242]
### Description

I have IMapView and IMap handler + implementations for pltafrom. View is appear on the screen with google logo ana +,- buttons for zoom. But map is not visible. 

My key from google cloud platforms is added in manifest. 

xamarin google play services 118.0.2.1 installed 

Anyone who has map controll working ?

### Steps to Reproduce

Show maui control via handelr on the some screen. 

### Version with bug

6.0 Release Candidate 3

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12

### Did you find any workaround?
# update 17.08.2022
I tried this advice with new renderer https://developers.google.com/maps/documentation/android-sdk/renderer and it is medicine for my disease. It is working now.

### Relevant log output

```shell
[Google Maps Android API] Google Play services client version: 12451000
[Google Maps Android API] Google Play services package version: 222116044
[Google Maps Android API] Google Play services maps renderer version(legacy): 203115000
[MapsInitializer] loadedRenderer: LEGACY
[zzca] preferredRenderer: null
[Google Maps Android API] Google Play services package version: 222116044
[Google Maps Android API] Google Play services maps renderer version(legacy): 203115000
[ba] Successfully registered with Phenotype.
[DynamiteModule] Local module descriptor class for com.google.android.gms.googlecertificates not found.
[DynamiteModule] Considering local module com.google.android.gms.googlecertificates:0 and remote module com.google.android.gms.googlecertificates:7
[DynamiteModule] Selected remote version of com.google.android.gms.googlecertificates, version >= 7
[stamina.warrio] ClassLoaderContext type mismatch. expected=PCL, found=DLC (PCL[] | DLC[];PCL[/data/app/~~MCF9FVygUCKvL6mlK22o0A==/XYZ-9bwV2d4YKJW-AJj_GCrFzA==/base.apk*2904850321:/data/app/~~MCF9FVygUCKvL6mlK22o0A==/XYZ-9bwV2d4YKJW-AJj_GCrFzA==/base.apk!classes2.dex*3987612927]{PCL[/system/framework/org.apache.http.legacy.jar*3239720430]})
[SnapshotHandler] Unable to retrieve flag snapshot for com.google.android.libraries.consentverifier#XYZ, using defaults.
[SnapshotHandler] java.io.FileNotFoundException: /data/user/0/XYZ/files/phenotype/shared/com.google.android.libraries.consentverifier#XYZ.pb: open failed: ENOENT (No such file or directory)
[SnapshotHandler] 	at libcore.io.IoBridge.open(IoBridge.java:575)
[SnapshotHandler] 	at java.io.FileInputStream.<init>(FileInputStream.java:160)
[SnapshotHandler] 	at zv.d(:com.google.android.gms.dynamite_mapsdynamite@222116097@22.21.16 (190400-0):2)
[SnapshotHandler] 	at zq.d(:com.google.android.gms.dynamite_mapsdynamite@222116097@22.21.16 (190400-0):2)
[SnapshotHandler] 	at aak.b(:com.google.android.gms.dynamite_mapsdynamite@222116097@22.21.16 (190400-0):1)
[SnapshotHandler] 	at aaj.a(:com.google.android.gms.dynamite_mapsdynamite@222116097@22.21.16 (190400-0):1)
[SnapshotHandler] 	at zn.b(:com.google.android.gms.dynamite_mapsdynamite@222116097@22.21.16 (190400-0):0)
[SnapshotHandler] 	at xn.a(:com.google.android.gms.dynamite_mapsdynamite@222116097@22.21.16 (190400-0):3)
[SnapshotHandler] 	at xs.a(:com.google.android.gms.dynamite_mapsdynamite@222116097@22.21.16 (190400-0):2)
[SnapshotHandler] 	at yr.a(:com.google.android.gms.dynamite_mapsdynamite@222116097@22.21.16 (190400-0):14)
[SnapshotHandler] 	at avy.d(:com.google.android.gms.dynamite_mapsdynamite@222116097@22.21.16 (190400-0):0)
[SnapshotHandler] 	at fz.c(:com.google.android.gms.dynamite_mapsdynamite@222116097@22.21.16 (190400-0):26)
[SnapshotHandler] 	at fy.a(:com.google.android.gms.dynamite_mapsdynamite@222116097@22.21.16 (190400-0):71)
[SnapshotHandler] 	at fy.b(:com.google.android.gms.dynamite_mapsdynamite@222116097@22.21.16 (190400-0):0)
[SnapshotHandler] 	at iy.c(:com.google.android.gms.dynamite_mapsdynamite@222116097@22.21.16 (190400-0):1)
[SnapshotHandler] 	at ip.e(:com.google.android.gms.dynamite_mapsdynamite@222116097@22.21.16 (190400-0):1)
[SnapshotHandler] 	at jq.t(:com.google.android.gms.dynamite_mapsdynamite@222116097@22.21.16 (190400-0):2)
[SnapshotHandler] 	at jq.u(:com.google.android.gms.dynamite_mapsdynamite@222116097@22.21.16 (190400-0):1)
[SnapshotHandler] 	at jq.e(:com.google.android.gms.dynamite_mapsdynamite@222116097@22.21.16 (190400-0):2)
[SnapshotHandler] 	at ju.handleMessage(:com.google.android.gms.dynamite_mapsdynamite@222116097@22.21.16 (190400-0):69)
[SnapshotHandler] 	at android.os.Handler.dispatchMessage(Handler.java:102)
[SnapshotHandler] 	at android.os.Looper.loopOnce(Looper.java:201)
[SnapshotHandler] 	at android.os.Looper.loop(Looper.java:288)
[SnapshotHandler] 	at android.os.HandlerThread.run(HandlerThread.java:67)
[SnapshotHandler] Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
[SnapshotHandler] 	at libcore.io.Linux.open(Native Method)
[SnapshotHandler] 	at libcore.io.ForwardingOs.open(ForwardingOs.java:567)
[SnapshotHandler] 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:273)
[SnapshotHandler] 	at libcore.io.ForwardingOs.open(ForwardingOs.java:567)
[SnapshotHandler] 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7756)
[SnapshotHandler] 	at libcore.io.IoBridge.open(IoBridge.java:561)
[SnapshotHandler] 	... 23 more
[MobStoreFlagStore] Unable to update local snapshot for com.google.android.libraries.consentverifier#com.XYZ, may result in stale flags.
[MobStoreFlagStore] java.util.concurrent.ExecutionException: java.lang.SecurityException: GoogleCertificatesRslt: not allowed: pkg=XYZ, sha256=[...], atk=false, ver=222116044.true (go/gsrlt)
[MobStoreFlagStore] 	at ahr.s(:com.google.android.gms.dynamite_mapsdynamite@222116097@22.21.16 (190400-0):3)
[MobStoreFlagStore] 	at ahr.get(:com.google.android.gms.dynamite_mapsdynamite@222116097@22.21.16 (190400-0):2)
[MobStoreFlagStore] 	at ajb.g(:com.google.android.gms.dynamite_mapsdynamite@222116097@22.21.16 (190400-0):2)
[MobStoreFlagStore] 	at xs.d(:com.google.android.gms.dynamite_mapsdynamite@222116097@22.21.16 (190400-0):1)
[MobStoreFlagStore] 	at xu.run(:com.google.android.gms.dynamite_mapsdynamite@222116097@22.21.16 (190400-0):0)
[MobStoreFlagStore] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
[MobStoreFlagStore] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[MobStoreFlagStore] 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
[MobStoreFlagStore] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
[MobStoreFlagStore] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
[MobStoreFlagStore] 	at java.lang.Thread.run(Thread.java:920)
[MobStoreFlagStore] Caused by: java.lang.SecurityException: GoogleCertificatesRslt: not allowed: pkg=XYZ, sha256=[...], atk=false, ver=222116044.true (go/gsrlt)
[MobStoreFlagStore] 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2425)
[MobStoreFlagStore] 	at android.os.Parcel.createException(Parcel.java:2409)
[MobStoreFlagStore] 	at android.os.Parcel.readException(Parcel.java:2392)
[MobStoreFlagStore] 	at android.os.Parcel.readException(Parcel.java:2334)
[MobStoreFlagStore] 	at el.bc(:com.google.android.gms.dynamite_mapsdynamite@222116097@22.21.16 (190400-0):2)
[MobStoreFlagStore] 	at rh.a(:com.google.android.gms.dynamite_mapsdynamite@222116097@22.21.16 (190400-0):4)
[MobStoreFlagStore] 	at ir.e(:com.google.android.gms.dynamite_mapsdynamite@222116097@22.21.16 (190400-0):2)
[MobStoreFlagStore] 	at jq.t(:com.google.android.gms.dynamite_mapsdynamite@222116097@22.21.16 (190400-0):2)
[MobStoreFlagStore] 	at jq.u(:com.google.android.gms.dynamite_mapsdynamite@222116097@22.21.16 (190400-0):3)
[MobStoreFlagStore] 	at jq.e(:com.google.android.gms.dynamite_mapsdynamite@222116097@22.21.16 (190400-0):2)
[MobStoreFlagStore] 	at ju.handleMessage(:com.google.android.gms.dynamite_mapsdynamite@222116097@22.21.16 (190400-0):69)
[MobStoreFlagStore] 	at android.os.Handler.dispatchMessage(Handler.java:102)
[MobStoreFlagStore] 	at android.os.Looper.loopOnce(Looper.java:201)
[MobStoreFlagStore] 	at android.os.Looper.loop(Looper.java:288)
[MobStoreFlagStore] 	at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by LukasKuchta** [comment]
![Screenshot_20220622-192652](https://user-images.githubusercontent.com/105702630/175100219-2142427f-4681-41c8-821d-5c44d2605e25.jpg)

I tray it on android 8.1 and same result. Screenshot attached. No map here. Same error in log as first topic.

**Comment by LukasKuchta** [comment]
> @LukasKuchta can you please add a repro?
> 
> We're working on adding maps in the branch [here](https://github.com/dotnet/maui/tree/maps) maybe that will give you some ideas how to fix?
[map_demo.zip](https://github.com/dotnet/maui/files/8968503/map_demo.zip)

Hi, i attached the sample. Google api key is empty and error is still here.

**Comment by PureWeen** [comment]
@LukasKuchta can you upload your repro to a github repository please?

**Comment by LukasKuchta** [comment]
> @LukasKuchta can you upload your repro to a github repository please?

There it is. https://github.com/LukasKuchta/MAUI.Map.Demo Error still persists. No update for google play/maps libraries.

**Comment by LukasKuchta** [comment]
> > @LukasKuchta can you upload your repro to a github repository please?
> 
> There it is. https://github.com/LukasKuchta/MAUI.Map.Demo Error still persists. No update for google play/maps libraries.
> 
> Another guy has same trouble here on xam-forms: https://issuehint.com/issue/xamarin/xamarin-forms-samples/755

There is a some kind of workaround. Using the SupportMapFragment instead of MapView directly. But i'dont know how to use mapfragment inside the handler. But it is still workaround. Source: https://stackoverflow.com/questions/71240724/android-mapview-no-longer-working-even-after-using-updated-google-tutorial/72853786#72853786

**Comment by kristinx0211** [comment]
can be reproduced on android with https://github.com/LukasKuchta/MAUI.Map.Demo.

**Comment by LukasKuchta** [comment]
I upgraded VS to  Version 17.4.0 Preview 1.0 and google maps nugets to 
Xamarin.GooglePlayServices.Maps     {118.0.2.2}                              and stiil no change. Any workaround? 

Is this issue happen when you implementing maps in this branch https://github.com/dotnet/maui/tree/maps? Or any workaround here? It is long time with broken maps

**Comment by davefxy** [comment]
@LukasKuchta Would you have an example of what you did to fix this?
