### ISSUE TITLE
Cannot build with App.xaml.cs moved to MAUI class library

### ISSUE THREAD

**Issue by MYPOSConnect** [dotnet/maui#8585]
### Description

In Xamarin, we have a suite of apps which all reference a shared project named 'Common'. The App.xaml/App.xaml.cs files are moved to this project, along with views (e.g. login screen), functionality, API access and data models which are common to all the apps. 

The apps are then all separate XF projects within the same solution that can be easily switched between in the dropdowns on the VS ribbon, and all retain their own application names, icons etc.

In MAUI, I switched to a MAUI Class Library because the 'MAUIXaml' Build Action is not available in a regular shared project. I also moved the resources folder into the 'Common' project.

However, building the project gives this error:

_Error	MAUI0000	System.IO.IOException: The process cannot access the file 

(Full error in log output section)
   
This is a big roadblock for us. As well as smaller apps sharing login functionality, we have a large app that can either be public, waiter or till user facing. These apps share 75% of their functionality and layout, but have their own name, icons, colour schemes and crucially, package IDs. Currently with this build issue we have no way of sharing UI layouts between them.

### Steps to Reproduce

[MauiApp68.zip](https://github.com/dotnet/maui/files/9812075/MauiApp68.zip)

1) Create a new **(non-shell)** MAUI App project. 

2) Add a '.NET MAUI Class Library' called Library to the solution.

3) Add the Library project reference to the MAUI App project.

4) Move App.xaml and MainPage.xaml to the Library project, updating the namespaces accordingly.

5) Copy Resources folder to the Library project.

6) Add 'Using Library' to MauiProgram.cs.

7) Build & Run in debug mode for Windows Machine.

### Version with bug

6.0.400 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

### Affected platform versions

Windows 10.0.17763

### Relevant log output

```shell
_Error	MAUI0000	System.IO.IOException: The process cannot access the file 'C:\Xamarin\Apps\MAUI\MYPOS\MYPOS\obj\Debug\net6.0-windows10.0.19041.0\win10-x64\resizetizer\r\dotnet_bot.scale-400.png' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at Microsoft.Maui.Resizetizer.SkiaSharpTools.Resize(DpiPath dpi, String destination) in D:\a\_work\1\s\src\SingleProject\Resizetizer\src\SkiaSharpTools.cs:line 66
   at Microsoft.Maui.Resizetizer.Resizer.Resize(DpiPath dpi, String inputsFile) in D:\a\_work\1\s\src\SingleProject\Resizetizer\src\Resizer.cs:line 103
   at Microsoft.Maui.Resizetizer.ResizetizeImages.ProcessImageResize(ResizeImageInfo img, DpiPath[] dpis, ConcurrentBag`1 resizedImages) in D:\a\_work\1\s\src\SingleProject\Resizetizer\src\ResizetizeImages.cs:line 191
   at Microsoft.Maui.Resizetizer.ResizetizeImages.<>c__DisplayClass27_0.<ExecuteAsync>b__0(ResizeImageInfo img) in D:\a\_work\1\s\src\SingleProject\Resizetizer\src\ResizetizeImages.cs:line 88
   at Microsoft.Maui.Resizetizer.AsyncTaskExtensions.<>c__DisplayClass0_0`1.<ParallelForEach>b__0(TSource s) in D:\a\_work\1\s\src\SingleProject\Resizetizer\src\AsyncTaskExtensions.cs:line 21	MYPOS	C:\Program Files\dotnet\packs\Microsoft.Maui.Resizetizer.Sdk\6.0.400\targets\Microsoft.Maui.Resizetizer.targets	522_
```

**Comment by jsuarezruiz** [comment]
> Typically, after spending ages on this before posting the issue, I have solved it.
> 
> Steps to fix:
> 
> 1. Delete all folders within Library/Resources except Styles.
> 2. Delete styles folder from MAUI App/Resources.

Seems like the issue was having the same Resources in the Library and the App. Looking at this case I think we need to also add documentation related to this scenario.

**Comment by StephaneDelcroix** [comment]
I think we can close this now
