### ISSUE TITLE
Issue with AndExpandLayoutManager in converted application

### ISSUE THREAD

**Issue by Bowman74** [dotnet/maui#8816]
### Description

In the app I converted that has several nested relative layouts and andExpand stack layouts (sorry, not my code). I get a null reference exception on the layout cycle in the ArrangeChildren method.

The Microsoft.Maui.Controls.AndExpandLayoutManager.ArrangeChildren only has a single line in it that calls the GridLayoutManager's ArrangeChildren method. Based on the error seems to be null. From looking at the code it would seem that the _manager variable is likely what is null. This variable should be set in the Measure method. The error leads me to believe the measure method is not being called first on the instance of the GridLayoutManager who's ArrangeChildren method is called. 

### Steps to Reproduce

Currently unknown. Will update as I know more about the solution. This is a very complex layout any may take some significant reworking to drill down the the combination that causes the issue.

### Version with bug

6.0.408 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 30

### Did you find any workaround?

Not at this time

### Relevant log output

```shell
{System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Maui.Controls.AndExpandLayoutManager.ArrangeChildren(Rect bounds)
   at Microsoft.Maui.Controls.StackLayoutManager.ArrangeChildren(Rect bounds)
   at Microsoft.Maui.Controls.Layout.CrossPlatformArrange(Rect bounds)
   at Microsoft.Maui.Platform.LayoutViewGroup.OnLayout(Boolean changed, Int32 l, Int32 t, Int32 r, Int32 b) in D:\a\_work\1\s\src\Core\src\Platform\Android\LayoutViewGroup.cs:line 93
   at Android.Views.ViewGroup.n_OnLayout_ZIIII(IntPtr jnienv, IntPtr native__this, Boolean changed, Int32 l, Int32 t, Int32 r, Int32 b)
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPZIIII_V(_JniMarshal_PPZIIII_V callback, IntPtr jnienv, IntPtr klazz, Boolean p0, Int32 p1, Int32 p2, Int32 p3, Int32 p4)
   at Java.Interop.JniEnvironment.InstanceMethods.CallNonvirtualVoidMethod(JniObjectReference instance, JniObjectReference type, JniMethodInfo method, JniArgumentValue* args) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniEnvironment.g.cs:line 12320
   at Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeNonvirtualVoidMethod(String encodedMember, IJavaPeerable self, JniArgumentValue* parameters) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:line 46
   at Android.Views.ViewGroup.Layout(Int32 l, Int32 t, Int32 r, Int32 b)
   at Microsoft.Maui.ViewHandlerExtensions.PlatformArrangeHandler(IViewHandler viewHandler, Rect frame) in D:\a\_work\1\s\src\Core\src\Handlers\ViewHandlerExtensions.Android.cs:line 121
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.ILayout, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.LayoutViewGroup, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].PlatformArrange(Rect frame) in D:\a\_work\1\s\src\Core\src\Handlers\View\ViewHandlerOfT.Android.cs:line 15
   at Microsoft.Maui.Controls.VisualElement.ArrangeOverride(Rect bounds)
   at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IView.Arrange(Rect bounds)
   at Microsoft.Maui.Controls.Compatibility.Layout.LayoutChildIntoBoundingRegion(VisualElement child, Rect region)
   at Microsoft.Maui.Controls.Compatibility.RelativeLayout.LayoutChildren(Double x, Double y, Double width, Double height)
   at Microsoft.Maui.Controls.Compatibility.Layout.UpdateChildrenLayout()
   at Microsoft.Maui.Controls.Compatibility.Layout.OnSizeAllocated(Double width, Double height)
   at Microsoft.Maui.Controls.VisualElement.SizeAllocated(Double width, Double height)
   at Microsoft.Maui.Controls.VisualElement.UpdateBoundsComponents(Rect bounds)
   at Microsoft.Maui.Controls.VisualElement.set_Frame(Rect value)
   at Microsoft.Maui.Controls.VisualElement.ArrangeOverride(Rect bounds)
   at Microsoft.Maui.Controls.Compatibility.Layout.ArrangeOverride(Rect bounds)
   at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IView.Arrange(Rect bounds)
   at Microsoft.Maui.Controls.Compatibility.Layout.LayoutChildIntoBoundingRegion(VisualElement child, Rect region)
   at Microsoft.Maui.Controls.Page.LayoutChildren(Double x, Double y, Double width, Double height)
   at Microsoft.Maui.Controls.Page.UpdateChildrenLayout()
   at Microsoft.Maui.Controls.Page.OnSizeAllocated(Double width, Double height)
   at Microsoft.Maui.Controls.VisualElement.SizeAllocated(Double width, Double height)
   at Microsoft.Maui.Controls.VisualElement.UpdateBoundsComponents(Rect bounds)
   at Microsoft.Maui.Controls.VisualElement.set_Frame(Rect value)
   at Microsoft.Maui.Controls.ContentPage.Microsoft.Maui.IContentView.CrossPlatformArrange(Rect bounds)
   at Microsoft.Maui.Platform.ContentViewGroup.OnLayout(Boolean changed, Int32 left, Int32 top, Int32 right, Int32 bottom) in D:\a\_work\1\s\src\Core\src\Platform\Android\ContentViewGroup.cs:line 89
   at Android.Views.ViewGroup.n_OnLayout_ZIIII(IntPtr jnienv, IntPtr native__this, Boolean changed, Int32 l, Int32 t, Int32 r, Int32 b)
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPZIIII_V(_JniMarshal_PPZIIII_V callback, IntPtr jnienv, IntPtr klazz, Boolean p0, Int32 p1, Int32 p2, Int32 p3, Int32 p4)}
    base: {System.SystemException}
```

**Comment by rmarinho** [comment]
Hey @Bowman74 long time no see :) It would be great if you can push a repro so we can take a look.

**Comment by Bowman74** [comment]
@rmarinho Will do. Still tracking it down and it "appears" it might be an "andexpand" stack layout within a relative layout. I know in the converted project using a one column or row grid fixes the issue (which is what is supposed to be happening under the covers anyway).

When I get it sorted with a simple reproduction, I'll push a repo.

**Comment by Bowman74** [comment]
@rmarinho 

Here is a link to a simple repro to reproduce the issue on Android.

https://github.com/Bowman74/AndExpandIssue/tree/master/AndExpandIssue

I have verified this on two physical devices, a OnePlus 7 Pro and a Samsung A52.

I updated the original bug to include the workaround. The workaround is to change using the Microsoft.Maui.Controls.StackLayout to use the Microsoft.Maui.Controls.Compatibility.StackLayout instead in the base view.

**Comment by Bowman74** [comment]
@rmarinho @hartez I see this is still listed as needs attention. Is there anything else I need to do to give you full information on the problem and re-create it? Thanks!

**Comment by hartez** [comment]
@Bowman74 The "needs attention" is for the maintainers - sorry for the confusion.

**Comment by hartez** [comment]
@Bowman74 I'm getting a 404 on that repro link.

**Comment by Bowman74** [comment]
@hartez I was silly and forgot to make the visibility public. Try it now and let me know if you have any issues. Thanks!
