### ISSUE TITLE
Maui Blazor fails to show messagebox in Release configuration on Android

### ISSUE THREAD

**Issue by GarageGadget** [dotnet/maui#9117]
### Description

When trying to display a message using the MudBlazor MessageBox method on Maui Blazor app in release configuration on Android the message box fails to display and reports the following error message on the Browser Console:-

blazor.webview.js:1 Arg_NoDefCTor, MudBlazor.MudMessageBox
   at System.RuntimeType.CreateInstanceMono(Boolean , Boolean )
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean , Boolean )
   at System.Activator.CreateInstance(Type , Boolean , Boolean )
   at System.Activator.CreateInstance(Type , Boolean )
   at System.Activator.CreateInstance(Type )
   at Microsoft.AspNetCore.Components.DefaultComponentActivator.CreateInstance(Type )
   at Microsoft.AspNetCore.Components.ComponentFactory.InstantiateComponent(IServiceProvider , Type )
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateComponent(Type )
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateChildComponentOnFrame(RenderTreeFrame& , Int32 )
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(DiffContext& , Int32 )
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& , Int32 )
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& , Int32 )
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& , Int32 )
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& , Int32 )
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& , Int32 , Int32 , Int32 , Int32 )
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer , RenderBatchBuilder , Int32 , ArrayRange`1 , ArrayRange`1 )
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder , RenderFragment , Exception& )
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry )
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()

### Steps to Reproduce

**Microsoft Visual Studio Professional 2022 (64-bit) - Preview Version 17.3.0 Preview 5.0**

**Steps**
1. Create a Maui Blazor app.
2. Add the MudBlazor nuget package
3. Follow the MudBlazor Getting started instructions to setup the Main Layout and references.
4. Update the Index page to with a button which is used to invoke the message box.
5. Inject the reference to the IDialogService.
6. Add button to page to invoke the MessageBox
7. Start the App on Windows on Debug configuration.
8. Press the button and the MessageBox will display correctly
9. Start the App on Android on Debug configuration.
10. Press the button and the MessageBox will display correctly

Repeat the steps 7 to 10 in Release configuration.
Windows will work without issue
Android will fail with an unhandled exception message.

**Example Page:**

![image](https://user-images.githubusercontent.com/24795067/182226188-bf41a43b-9796-4980-a67d-f87235967349.png)

**MudBlazor Reference**
https://mudblazor.com/getting-started/installation#manual-install-add-components

**Windows Release Configuration**
![image](https://user-images.githubusercontent.com/24795067/182224224-6c797df7-70cf-4ba3-a893-990c52c5a32e.png)

**Android Release Configuration**

![image](https://user-images.githubusercontent.com/24795067/182224512-c8c0c674-bb29-4744-87fd-d2ec9ff4bde1.png)

![image](https://user-images.githubusercontent.com/24795067/182225432-2251c491-9cf1-4d55-a5a0-9f68dcc48743.png)

### Version with bug

6.0.400

### Last version that worked well

6.0.400

### Affected platforms

Android

### Affected platform versions

Android 9

### Did you find any workaround?

No

### Relevant log output

```shell
blazor.webview.js:1 Arg_NoDefCTor, MudBlazor.MudMessageBox
   at System.RuntimeType.CreateInstanceMono(Boolean , Boolean )
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean , Boolean )
   at System.Activator.CreateInstance(Type , Boolean , Boolean )
   at System.Activator.CreateInstance(Type , Boolean )
   at System.Activator.CreateInstance(Type )
   at Microsoft.AspNetCore.Components.DefaultComponentActivator.CreateInstance(Type )
   at Microsoft.AspNetCore.Components.ComponentFactory.InstantiateComponent(IServiceProvider , Type )
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateComponent(Type )
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateChildComponentOnFrame(RenderTreeFrame& , Int32 )
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(DiffContext& , Int32 )
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& , Int32 )
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& , Int32 )
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& , Int32 )
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& , Int32 )
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& , Int32 , Int32 , Int32 , Int32 )
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer , RenderBatchBuilder , Int32 , ArrayRange`1 , ArrayRange`1 )
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder , RenderFragment , Exception& )
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry )
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Does this work in Debug configuration on Android?
Also, can you try to disable trimming and see if that fixes the issue?

**Comment by mkArtakMSFT** [comment]
To disable triming you can set the `<PublishTrimmed>false</PublishTrimmed>` property in your project file.

**Comment by GarageGadget** [comment]
Hi @mkArtakMSFT.

The code works on Windows and Android in Debug configuration.

I rebuilt with trimming disabled as suggested.

The App starts running displaying the .NET splash but terminates after +- 1 sec.

Logcat reported the following on startup filtering on the DOTNET tag.

![image](https://user-images.githubusercontent.com/24795067/182693675-96f08381-0dc2-4b3e-9f6e-7223d8351ca6.png)

**Comment by MackinnonBuck** [comment]
Thanks for getting back to us @GarageGadget. Could you try creating an empty MAUI Blazor project and checking if the app runs correctly? It might be a problem with your environment.

**Comment by GarageGadget** [comment]
Hi, 

To resolve the starting issue - _The App starts running displaying the .NET splash but terminates after +- 1 sec._
1. I deleted the folders under the **obj** folder
2. Re-started Visual Studio
3. Rebuilt and deployed
4. The App started but the MessageBox failed with the same error as before.

**Workaround for the MessageBox**
I replaced the MessageBox method with MudBlazor DialogService Show<>() method with a custom MessageBox razor component.

_The DailogService.Show<>() works in all build configurations for **Windows** and **Android**_
