### ISSUE TITLE
Can't consume a custom font in GraphicsView

### ISSUE THREAD

**Issue by gdamino** [dotnet/maui#9252]
### Description

Assuming a font registered globally with:
` public static MauiApp CreateMauiApp()
	{
		var builder = MauiApp.CreateBuilder();
		builder
			.UseMauiApp<App>()
			.ConfigureFonts(fonts =>
			{
				fonts.AddFont("MyFont.ttf", "MyFont");
			});
        return builder.Build();
	}`

In the Drawable implementation of a GraphicsView when I try to use that font:

` 
using Font = Microsoft.Maui.Graphics.Font;
public void Draw(ICanvas canvas, RectF dirtyRect)
        {
            canvas.Font = new Font("MyFont");
  ....
}`

the canvas ignore that font. 
And this is a big problem because we are porting an app from Xamarin (we was using SkiaSharp) to MAUI and we made a diffuse use of this kind of object.
I'm wrong with some thing or this is a bug?
thanks in advice

### Steps to Reproduce

1. Create a new .Net MAUI project
2. Register a custom font in CreateMauiApp() -> MauiProgram.cs
3. Use that font in a canvas (in the Draw() function of a IDrawable interface implementation of a GraphicsView)

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 7 and Up

### Did you find any workaround?

no

### Relevant log output

```shell
no log
```

**Comment by gdamino** [comment]
Any workaround or proper way to use custom fonts with Graphicsview?

**Comment by profix898** [comment]
Same problem here. I'm working on a graphics-heavy MAUI app. Unfortunately, there appears to be no supported way for using custom MAUI fonts with Maui.Graphics. Really?!

I found a corresponding issue from June 2022 in the Microsoft.Maui.Graphics repo:
dotnet/Microsoft.Maui.Graphics#451

**Comment by profix898** [comment]
Actually, this was initially reported back in August 2021:
dotnet/Microsoft.Maui.Graphics#232

**Comment by gdamino** [comment]
> Same problem here. I'm working on a graphics-heavy MAUI app. Unfortunately, there appears to be no supported way for using custom MAUI fonts with Maui.Graphics. Really?!
> 
> I found a corresponding issue from June 2022 in the Microsoft.Maui.Graphics repo: [dotnet/Microsoft.Maui.Graphics#451](https://github.com/dotnet/Microsoft.Maui.Graphics/issues/451)

I solved rewriting it using SkiaSharp package, if you don't have an huge amount of code you can try this way.
I don't know why MAUI developers don't prioritize graphics instead of other minor things.
MAUI is basically not usable for a big company app, by our test is slower than Xamarin (which in itself was very slow), it don't resolve any problem of Xamarin and brings new MAUI specific problems.
Graphics is the way to speed user interface because drawing is 100x faster but it is completely abandoned.
This issue, and other similar ridicoulus issues, suggests that there are very few companies producing apps with MAUI, and this is a big problem.

**Comment by Mashedpoturtles** [comment]
Is it JUST not working in graphics? Because for me consuming fonts don't work in general

**Comment by aabc123** [comment]
I'm seeing this on iOS too.  The custom font works across our application just not when used as a Graphics.Font with ICanvas.DrawString.

**Comment by xtuzy** [comment]
Try custom draw string api. 
Current Maui have Maui.Font and Graphics.Font, Maui.Font can get better support by FontManager,  ICanvas's draw text api use Graphics.Font, it don't use FontManager to get platform font, so have some bug, you can copy DrawText source code of PlatformCanvas, and use Maui.Font to convert to platform font, not use Graphics.Font.
I have some code:
https://github.com/xtuzy/Yang.Maui.Helper/tree/master/Yang.Maui.Helper/Graphics

**Comment by aabc123** [comment]
Any update if this will be fixed in .Net 8?

**Comment by DoubleDBE** [comment]
I'm also wondering where this stands. We really need this to work for .NET 8!

**Comment by lfmouradasilva** [comment]
Any updates?

**Comment by danielancines** [comment]
This feature will be great to customize text controls made on Canvas.

**Comment by homeyf** [comment]
Verified this issue with VSM 17.6.7 (build 417). Can repro on Android platform.

**Comment by john-hollander** [comment]
The workaround for this is to use "MyFont.ttf", instead of "MyFont" for Android - i.e. the full name of the font file, instead of the alias. However, using the full name won't work for Windows or iOS, so you'll need a special case.

**Comment by billreiss** [comment]
> The workaround for this is to use "MyFont.ttf", instead of "MyFont" for Android - i.e. the full name of the font file, instead of the alias. However, using the full name won't work for Windows or iOS, so you'll need a special case.

John do you have a sample? I can't get it to work.

**Comment by john-hollander** [comment]
> > The workaround for this is to use "MyFont.ttf", instead of "MyFont" for Android - i.e. the full name of the font file, instead of the alias. However, using the full name won't work for Windows or iOS, so you'll need a special case.
> 
> @john-hollander using the full name works for me on Android, do you have something that works on iOS and Windows?

I have an example here, that you can look at:
https://github.com/john-hollander/Maui-Tests/tree/master/IDrawableFontTest

A few notes:
1. Make sure to configure the font in the MauiProgram class.
2. Make sure the font is in the Fonts subfolder of the Resources folder, and the build action is set to "MauiFont".
3. The `canvas.FontSize = fontSize * 0.9921f;` line is there to adjust the font size to fit inside the drawing rectangle because otherwise it overflows (comment it out and see).
4. I set it up so that you can tap on the form to resize the text for testing purposes.
5. It's dirty, but good enough to test things out with.

**Comment by jsuarezruiz** [comment]
The main problem is that we have two font types and two different approaches to manage fonts in Graphics and Core.
Only in Core we have and use IFontRegistrar which allows us to resolve the path to a font given its name:

fonts.AddFont("FontName-FontType.ttf", "FontName");

We don't use this in Graphics. To resolve the issue we will require changes to public APIs. We could take two approaches:
- The one that requires more changes but that I think is better, move IFontRegister and other dependencies to Graphics as we already have, for example IFont, leaving a single implementation that will use the same logic to register and resolve fonts everywhere, Core and Graphics.
- Move only what is essential and apply the minimum changes. Still, it requires changes to public APIs and access to IFontRegistrar from Graphics.
@matthoi

So, it requieres changes, a fix. As a workaround for now, custom fonts are supported on each platform although it is not enough to use the font name. On Android, for example, it would be:

fonts.AddFont("FontName-FontType.ttf", "FontName");
Font font = new Font("FontName-FontType.ttf");

@mattleibow Thoughts?

**Comment by anotherlab** [comment]
I'm all for doing the first approach of moving IFontRegister and friends to Graphics.  One of the benefits of using .NET MAUI over other frameworks is the ability to create a custom control with little to no platform-specific code.

**Comment by Dokug** [comment]
Is there any indication when this might be fixed?
For me, this is working on neither Windows nor iOS/Mac.

I would need this functionality for an important custom control, but if this isn't supposed to be fixed in the intermediate future, I'll start looking for alternate implementations right away..

**Comment by yurkinh** [comment]
Any updates on this?

**Comment by jsuarezruiz** [comment]
Example using https://learn.microsoft.com/es-es/typography/font-list/showcard-gothic

```
#if ANDROID
            canvas.Font = new Microsoft.Maui.Graphics.Font("SHOWG.TTF");
#elif IOS
            canvas.Font = new Microsoft.Maui.Graphics.Font("Showcard Gothic");
#elif WINDOWS
            canvas.Font = new Microsoft.Maui.Graphics.Font("SHOWG.TTF#Showcard Gothic");
#endif
```

This as workaround meanwhile, the bug is fixed.

**Comment by Dokug** [comment]
I'm sorry to report that this doesn't work for me, using MAUI 8.0.21
I've registered my font in the MauiProgram using the standard `fonts.AddFont("MCDU.ttf", "MCDU");` and tried your workaround with

```
#if IOS || MACCATALYST
        canvas.Font = new Microsoft.Maui.Graphics.Font("MCDU");
#elif WINDOWS        
        canvas.Font = new Microsoft.Maui.Graphics.Font("MCDU.ttf#MCDU");
#endif
```
in my Drawable's `Draw()` method, but to no avail.

The drawn text does show up, but it is rendered using the "default" drawable font.

**Comment by anotherlab** [comment]
I can not get the workaround that @jsuarezruiz posted as https://github.com/dotnet/maui/issues/9252#issuecomment-2097566823 to work on Windows.  I get a System.ArgumentException exception when I call `canvas.GetStringSize`.  I tried this with multiple fonts, including the "Showcard Gothic" from that example.

Works fine for iOS and Android, fails on Windows.  This is on .NET 9 RC 1

The call stack from the exception.
```
System.ArgumentException
  HResult=0x80070057
  Message=Value does not fall within the expected range.
  Source=WinRT.Runtime
  StackTrace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at Microsoft.Graphics.Canvas.Text.CanvasTextLayout._ICanvasTextLayoutFactory.Create(ICanvasResourceCreator resourceCreator, String textString, CanvasTextFormat textFormat, Single requestedWidth, Single requestedHeight)
   at Microsoft.Graphics.Canvas.Text.CanvasTextLayout..ctor(ICanvasResourceCreator resourceCreator, String textString, CanvasTextFormat textFormat, Single requestedWidth, Single requestedHeight)
   at Microsoft.Maui.Graphics.Win2D.W2DStringSizeService.GetStringSize(String value, IFont font, Single textSize, HorizontalAlignment horizontalAlignment, VerticalAlignment verticalAlignment)
   at Microsoft.Maui.Graphics.AbstractCanvas`1.GetStringSize(String aString, IFont font, Single aFontSize, HorizontalAlignment aHorizontalAlignment, VerticalAlignment aVerticalAlignment)
   at TimerButtonDemo.Drawables.TimerButtonDrawable.CalcFontSize(ICanvas canvas, RectF dirtyRect, Font font) in D:\dev\tvug\2024\TimerButtonDemo\Drawables\TimerButtonDrawable.cs:line 65
```  
If I bypass `canvas.GetStringSize` and just hardcode a `canvas.FontSize` to value that _should work_ and call `canvas.DrawString`, it fails with more or less the same exception.  I have a demo project that I am using for user group demos that has code to replicate the problem: https://github.com/anotherlab/TimerButtonDemo

**Comment by tounaobun** [comment]
Can't believe this issue existed for 2 years.

**Comment by tounaobun** [comment]
Finally resolved it. The key point is that font file name is not necessarily equal to family name. For example, MyFont.tff file's family name may be My Font.
So in order to make it work on all platforms(Including Windows), please use family name instead of file name.

`Font font = new Font("My Font");`

**Comment by MasterOliver21** [comment]
Any update on this issue? I tried the suggested workaround and it does work, but in my project it became too heavy and unmaintainable.
Is there any plan to support this natively in a future release?

**Comment by john-hollander** [comment]
Currently I'm using something like this to work around things:

```
using SkiaSharp;
using System.Collections.Concurrent;

namespace Custom.Namespace;

public static class SKFontFactory
{
    private static readonly ConcurrentDictionary<string, SKTypeface> _fonts = [];
    private static readonly ConcurrentDictionary<string, string> _locationsByAlias = [];

    public static void AddFont(string fontLocation, string alias)
    {
        SKTypeface typeface;

        using (Stream data = FileSystem.OpenAppPackageFileAsync(fontLocation).GetAwaiter().GetResult())
            typeface = SKTypeface.FromStream(data);

        _fonts.TryAdd(fontLocation, typeface);
        _fonts.TryAdd(alias, typeface);

        _locationsByAlias.TryAdd(alias, fontLocation);        
    }

    public static SKTypeface GetTypeFace(string fontFamily)
    {
        if (_fonts.TryGetValue(fontFamily, out SKTypeface? typeface))
            return typeface;

        return SKTypeface.Default;
    }

    public static Microsoft.Maui.Graphics.Font GetFont(string fontFamily)
    {
        if (string.IsNullOrEmpty(fontFamily))
            return Microsoft.Maui.Graphics.Font.Default;

#if WINDOWS
        if (_locationsByAlias.TryGetValue(fontFamily, out string? font))
            return new(font.ToUpper() + "#" + fontFamily);
        else
            return new(fontFamily);
#else
        return new(fontFamily);
#endif
    }
}
```

And I set it up like this:

```
using SkiaSharp.Views.Maui.Controls.Hosting;

namespace Custom.Namespace;

public static class MauiProgram
{
    public static MauiApp CreateMauiApp()
    {
        var builder = MauiApp.CreateBuilder();
        builder
            .UseMauiApp<App>()
            .UseSkiaSharp()
            .ConfigureFonts(fonts =>
            {
                AddFont(fonts, "BaiJamjuree-Bold.ttf", "BaiJamjuree-Bold");
                AddFont(fonts, "BaiJamjuree-Light.ttf", "BaiJamjuree-Light");
                AddFont(fonts, "BaiJamjuree-Medium.ttf", "BaiJamjuree-Medium");
                AddFont(fonts, "BaiJamjuree-Regular.ttf", "BaiJamjuree-Regular");
                AddFont(fonts, "BaiJamjuree-SemiBold.ttf", "BaiJamjuree-SemiBold");
                AddFont(fonts, "OpenSans-Regular.ttf", "OpenSansRegular");
                AddFont(fonts, "OpenSans-Semibold.ttf", "OpenSansSemibold");
                AddFont(fonts, "Cinzel-Black.ttf", "Cinzel-Black");
                AddFont(fonts, "Cinzel-Bold.ttf", "Cinzel-Bold");
                AddFont(fonts, "Cinzel-ExtraBold.ttf", "Cinzel-ExtraBold");
                AddFont(fonts, "Cinzel-Medium.ttf", "Cinzel-Medium");
                AddFont(fonts, "Cinzel-Regular.ttf", "Cinzel");
                AddFont(fonts, "Cinzel-SemiBold.ttf", "Cinzel-SemiBold");
                AddFont(fonts, "Goldman-Regular.ttf", "Goldman-Regular");
                AddFont(fonts, "Goldman-Bold.ttf", "Goldman-Bold");
            });

        return builder.Build();
    }

    private static void AddFont(IFontCollection fonts, string fontLocation, string alias)
    {
        fonts.AddFont(fontLocation, alias);
        SKFontFactory.AddFont(fontLocation, alias);
    }
}
```

You can remove the Skia-specific code if you're not using SkiaSharp, but maybe this will be useful to someone.

**Comment by danielancines** [comment]
Thanks for share the code with us @john-hollander, but in my tests, this part of code let my application slow. My app has a high frequency of updates and creating the custom font using this approach, let the design of canvas slower, forcing me to not use it. Did u experienced this king of behavior on your app?

`if (_locationsByAlias.TryGetValue(fontFamily, out string? font))
            return new(font.ToUpper() + "#" + fontFamily);
        else
            return new(fontFamily);`

**Comment by john-hollander** [comment]
@danielancines You can try this if you want, it's a bit more complete with font caching in a dictionary, but I haven't tested it yet:

```
using SkiaSharp;
using System.Collections.Concurrent;
using Microsoft.Maui.Graphics;

namespace Custom.Namespace;

public static class SKFontFactory
{
    private static readonly ConcurrentDictionary<string, SKTypeface> _typefaces = [];
    private static readonly ConcurrentDictionary<string, string> _locationsByAlias = [];
    private static readonly ConcurrentDictionary<string, Microsoft.Maui.Graphics.Font> _fonts = [];

    public static void AddFont(IFontCollection fonts, string fontLocation, string alias)
    {
        if (string.IsNullOrEmpty(fontLocation))
            throw new ArgumentNullException(nameof(fontLocation));
        if (string.IsNullOrEmpty(alias))
            throw new ArgumentNullException(nameof(alias));

        try
        {
            // Load SKTypeface from MauiFont file
            SKTypeface typeface;
            using (Stream data = FileSystem.OpenAppPackageFileAsync(fontLocation).GetAwaiter().GetResult())
            {
                if (data == null)
                    throw new FileNotFoundException($"Font file not found: {fontLocation}");
                typeface = SKTypeface.FromStream(data);
                if (typeface == null)
                    throw new InvalidOperationException($"Failed to load typeface from {fontLocation}");
            }

            _typefaces.TryAdd(fontLocation, typeface);
            _typefaces.TryAdd(alias, typeface);
            _locationsByAlias.TryAdd(alias, fontLocation);

            // Create and cache Microsoft.Maui.Graphics.Font
            var font = new Microsoft.Maui.Graphics.Font(GetFontNameForPlatform(fontLocation, alias));
            _fonts.TryAdd(alias, font);

            // Register with MAUI's font collection
            fonts.AddFont(fontLocation, alias);
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error loading font {fontLocation} with alias {alias}: {ex.Message}");
            throw;
        }
    }

    public static SKTypeface GetTypeFace(string fontFamily)
    {
        if (string.IsNullOrEmpty(fontFamily))
            return SKTypeface.Default;

        if (_typefaces.TryGetValue(fontFamily, out SKTypeface? typeface))
            return typeface;

        return SKTypeface.Default;
    }

    public static Microsoft.Maui.Graphics.Font GetFont(string fontFamily)
    {
        if (string.IsNullOrEmpty(fontFamily))
            return Microsoft.Maui.Graphics.Font.Default;

        if (_fonts.TryGetValue(fontFamily, out Microsoft.Maui.Graphics.Font? font))
            return font;

#if WINDOWS
        if (_locationsByAlias.TryGetValue(fontFamily, out string? fontLocation))
        {
            var newFont = new Microsoft.Maui.Graphics.Font(GetFontNameForPlatform(fontLocation, fontFamily));
            _fonts.TryAdd(fontFamily, newFont);
            return newFont;
        }
#endif
        return new Microsoft.Maui.Graphics.Font(fontFamily);
    }

    public static void Dispose()
    {
        foreach (var typeface in _typefaces.Values.Distinct())
        {
            typeface?.Dispose();
        }
        _typefaces.Clear();
        _locationsByAlias.Clear();
        _fonts.Clear();
    }

    private static string GetFontNameForPlatform(string fontLocation, string alias)
    {
#if WINDOWS
        return fontLocation.ToUpper() + "#" + alias;
#else
        return alias;
#endif
    }
}
```

Note that you would set it up like this (hopefully this simplifies it slightly):

```
using SkiaSharp.Views.Maui.Controls.Hosting;

namespace Custom.Namespace;

public static class MauiProgram
{
    public static MauiApp CreateMauiApp()
    {
        var builder = MauiApp.CreateBuilder();
        builder
            .UseMauiApp<App>()
            .UseSkiaSharp()
            .ConfigureFonts(fonts =>
            {
                SKFontFactory.AddFont(fonts, "BaiJamjuree-Bold.ttf", "BaiJamjuree-Bold");
                SKFontFactory.AddFont(fonts, "BaiJamjuree-Light.ttf", "BaiJamjuree-Light");
                SKFontFactory.AddFont(fonts, "BaiJamjuree-Medium.ttf", "BaiJamjuree-Medium");
                SKFontFactory.AddFont(fonts, "BaiJamjuree-Regular.ttf", "BaiJamjuree-Regular");
                SKFontFactory.AddFont(fonts, "BaiJamjuree-SemiBold.ttf", "BaiJamjuree-SemiBold");
                SKFontFactory.AddFont(fonts, "OpenSans-Regular.ttf", "OpenSansRegular");
                SKFontFactory.AddFont(fonts, "OpenSans-Semibold.ttf", "OpenSansSemibold");
                SKFontFactory.AddFont(fonts, "Cinzel-Black.ttf", "Cinzel-Black");
                SKFontFactory.AddFont(fonts, "Cinzel-Bold.ttf", "Cinzel-Bold");
                SKFontFactory.AddFont(fonts, "Cinzel-ExtraBold.ttf", "Cinzel-ExtraBold");
                SKFontFactory.AddFont(fonts, "Cinzel-Medium.ttf", "Cinzel-Medium");
                SKFontFactory.AddFont(fonts, "Cinzel-Regular.ttf", "Cinzel");
                SKFontFactory.AddFont(fonts, "Cinzel-SemiBold.ttf", "Cinzel-SemiBold");
                SKFontFactory.AddFont(fonts, "Goldman-Regular.ttf", "Goldman-Regular");
                SKFontFactory.AddFont(fonts, "Goldman-Bold.ttf", "Goldman-Bold");
            });

        return builder.Build();
    }
}
```

Let me know if that helps. If you're consistently using the same font in code, I'd suggest keeping it in a class variable and only loading it at initialization (if that's possible - maybe it's not practical in your case).

**Comment by danielancines** [comment]
@john-hollander thanks, I'll try this later!

**Comment by danielancines** [comment]
Thanks again for your help, but the problem is in the code below, apparently canvas is loading the font file every new Draw, when we use this aproach, the draw performance is the worst than ever.

`#if WINDOWS
        if (_locationsByAlias.TryGetValue(fontFamily, out string? fontLocation))
        {
            var newFont = new Microsoft.Maui.Graphics.Font(GetFontNameForPlatform(fontLocation, fontFamily));
            _fonts.TryAdd(fontFamily, newFont);
            return newFont;
        }
#endif`

I've been trying something like this, using a static class to store a Font instance, but with no results.
`Font = new Font("MyFontFile.ttf#MyFontFamily"`

Any idea how to get the same performance that I get using fonts on Maui? For Canvas and Graphics View is not working well.

**Comment by john-hollander** [comment]
@danielancines you could try this, which should be more efficient:

```
public static class SKFontFactory
{
    private static readonly ConcurrentDictionary<string, SKTypeface> _typefaces = new();
    private static readonly ConcurrentDictionary<string, Microsoft.Maui.Graphics.Font> _fonts = new();

    public static void AddFont(IFontCollection fonts, string fontLocation, string alias)
    {
        if (string.IsNullOrEmpty(fontLocation))
            throw new ArgumentNullException(nameof(fontLocation));
        if (string.IsNullOrEmpty(alias))
            throw new ArgumentNullException(nameof(alias));

        // Normalize alias to lowercase
        string lower = alias.ToLowerInvariant();

        try
        {
            // Load SKTypeface from MauiFont file
            SKTypeface typeface;
            using (Stream data = FileSystem.OpenAppPackageFileAsync(fontLocation).GetAwaiter().GetResult())
            {
                if (data == null)
                    throw new FileNotFoundException($"Font file not found: {fontLocation}");
                typeface = SKTypeface.FromStream(data);
                if (typeface == null)
                    throw new InvalidOperationException($"Failed to load typeface from {fontLocation}");
            }

            // Cache typeface by both location and alias
            _typefaces.TryAdd(fontLocation, typeface);
            _typefaces.TryAdd(lower, typeface);

            // Create and cache Microsoft.Maui.Graphics.Font with platform-specific name
            var fontName = GetFontNameForPlatform(fontLocation, alias);
            var font = new Microsoft.Maui.Graphics.Font(fontName);
            _fonts.TryAdd(lower, font);

            // Register with MAUI's font collection
            fonts.AddFont(fontLocation, alias);
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error loading font {fontLocation} with alias {alias}: {ex.Message}");
            throw;
        }
    }

    public static SKTypeface GetTypeface(string fontFamily)
    {
        if (string.IsNullOrEmpty(fontFamily))
            return SKTypeface.Default;

        string lower = fontFamily.ToLowerInvariant();
        return _typefaces.TryGetValue(lower, out var typeface) ? typeface : SKTypeface.Default;
    }

    public static Microsoft.Maui.Graphics.Font GetFont(string fontFamily)
    {
        if (string.IsNullOrEmpty(fontFamily))
            return Microsoft.Maui.Graphics.Font.Default;

        string lower = fontFamily.ToLowerInvariant();

        // Return cached font if available
        if (_fonts.TryGetValue(lower, out var font))
            return font;

        // Log cache miss and use fallback
        Console.WriteLine($"Font cache miss for: {fontFamily}");
        var fallbackFont = new Microsoft.Maui.Graphics.Font(fontFamily);
        _fonts.TryAdd(lower, fallbackFont);
        return fallbackFont;
    }

    public static void Dispose()
    {
        foreach (var typeface in _typefaces.Values.Distinct())
        {
            typeface?.Dispose();
        }
        _typefaces.Clear();
        _fonts.Clear();
    }

    private static string GetFontNameForPlatform(string fontLocation, string alias)
    {
#if WINDOWS
        return fontLocation.ToUpper() + "#" + alias;
#else
        return alias;
#endif
    }
}
```

That should cache the values when it can't be found, and it eliminates the _locationsByAlias check which shouldn't be necessary, since it's added if found in the AddFont method anyway. Also, the fontFamily value is not case specific in this implementation.

For it to work, though, make sure that when you're calling GetFont, you're using the alias you supplied when adding the font as the "fontFamily", otherwise it won't find it in the dictionary, and you'll end up getting a bad font in Windows.

**Comment by danielancines** [comment]
> [@danielancines](https://github.com/danielancines) you could try this, which should be more efficient:
> 
> ```
> public static class SKFontFactory
> {
>     private static readonly ConcurrentDictionary<string, SKTypeface> _typefaces = new();
>     private static readonly ConcurrentDictionary<string, Microsoft.Maui.Graphics.Font> _fonts = new();
> 
>     public static void AddFont(IFontCollection fonts, string fontLocation, string alias)
>     {
>         if (string.IsNullOrEmpty(fontLocation))
>             throw new ArgumentNullException(nameof(fontLocation));
>         if (string.IsNullOrEmpty(alias))
>             throw new ArgumentNullException(nameof(alias));
> 
>         // Normalize alias to lowercase
>         string lower = alias.ToLowerInvariant();
> 
>         try
>         {
>             // Load SKTypeface from MauiFont file
>             SKTypeface typeface;
>             using (Stream data = FileSystem.OpenAppPackageFileAsync(fontLocation).GetAwaiter().GetResult())
>             {
>                 if (data == null)
>                     throw new FileNotFoundException($"Font file not found: {fontLocation}");
>                 typeface = SKTypeface.FromStream(data);
>                 if (typeface == null)
>                     throw new InvalidOperationException($"Failed to load typeface from {fontLocation}");
>             }
> 
>             // Cache typeface by both location and alias
>             _typefaces.TryAdd(fontLocation, typeface);
>             _typefaces.TryAdd(lower, typeface);
> 
>             // Create and cache Microsoft.Maui.Graphics.Font with platform-specific name
>             var fontName = GetFontNameForPlatform(fontLocation, alias);
>             var font = new Microsoft.Maui.Graphics.Font(fontName);
>             _fonts.TryAdd(lower, font);
> 
>             // Register with MAUI's font collection
>             fonts.AddFont(fontLocation, alias);
>         }
>         catch (Exception ex)
>         {
>             Console.WriteLine($"Error loading font {fontLocation} with alias {alias}: {ex.Message}");
>             throw;
>         }
>     }
> 
>     public static SKTypeface GetTypeface(string fontFamily)
>     {
>         if (string.IsNullOrEmpty(fontFamily))
>             return SKTypeface.Default;
> 
>         string lower = fontFamily.ToLowerInvariant();
>         return _typefaces.TryGetValue(lower, out var typeface) ? typeface : SKTypeface.Default;
>     }
> 
>     public static Microsoft.Maui.Graphics.Font GetFont(string fontFamily)
>     {
>         if (string.IsNullOrEmpty(fontFamily))
>             return Microsoft.Maui.Graphics.Font.Default;
> 
>         string lower = fontFamily.ToLowerInvariant();
> 
>         // Return cached font if available
>         if (_fonts.TryGetValue(lower, out var font))
>             return font;
> 
>         // Log cache miss and use fallback
>         Console.WriteLine($"Font cache miss for: {fontFamily}");
>         var fallbackFont = new Microsoft.Maui.Graphics.Font(fontFamily);
>         _fonts.TryAdd(lower, fallbackFont);
>         return fallbackFont;
>     }
> 
>     public static void Dispose()
>     {
>         foreach (var typeface in _typefaces.Values.Distinct())
>         {
>             typeface?.Dispose();
>         }
>         _typefaces.Clear();
>         _fonts.Clear();
>     }
> 
>     private static string GetFontNameForPlatform(string fontLocation, string alias)
>     {
> #if WINDOWS
>         return fontLocation.ToUpper() + "#" + alias;
> #else
>         return alias;
> #endif
>     }
> }
> ```
> 
> That should cache the values when it can't be found, and it eliminates the _locationsByAlias check which shouldn't be necessary, since it's added if found in the AddFont method anyway. Also, the fontFamily value is not case specific in this implementation.
> 
> For it to work, though, make sure that when you're calling GetFont, you're using the alias you supplied when adding the font as the "fontFamily", otherwise it won't find it in the dictionary, and you'll end up getting a bad font in Windows.

Got it, I'll try it, thanks.

**Comment by danielancines** [comment]
Anyone knows if it working on .net 10.0.101?
