### ISSUE TITLE
Authentication failed when trying to connect to secure websocket with android 8

### ISSUE THREAD

**Issue by Lukas123798** [dotnet/maui#9400]
### Description

I cant connect to secure websocket(wss), it just writing `Unable to connect to the remote server` and error `Authentication failed`, full log is down there, and to unsecure websocket i can connect easily on any android.
When i used android 11 phone it works fine.
I am using library 'WebSocket4Net' which working perfectly in xamarin with all androids.

### Steps to Reproduce

Connect to a secure websocket with .NET MAUI APP on android phone with android version 8, tested on both physical phone and emulator.
Or there is my repo where you can test it [Repo](https://github.com/Lukas123798/net-maui-secure-websocket)

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 8, but most likely its all older android versions

### Did you find any workaround?

I tryed copied this from Xamarin project where this websocket works fine on every platform, but its still not working.
```
<PropertyGroup Condition="$(TargetFramework.Contains('-android'))">
            <AndroidHttpClientHandlerType>Xamarin.Android.Net.AndroidClientHandler</AndroidHttpClientHandlerType>
            <AndroidTlsProvider></AndroidTlsProvider>
      </PropertyGroup>
```
Also i tryed this, but also not helpful
```
<AndroidHttpClientHandlerType>System.Net.Http.HttpClientHandler</AndroidHttpClientHandlerType>
<AndroidTlsProvider>legacy</AndroidTlsProvider>
<AndroidTlsProvider>btls</AndroidTlsProvider>
```
I tryed some settings in Websocket object with EnabledProtocols, but also nothing.

### Relevant log output

```shell
Authentication failed, see inner exception. at System.Net.Security.SsiStream<ForceAuthenticationAsy nc>d_175' 1 [(System.NetSecurity.AsyncReadWriteAdapter, System.Net.Security, Version=6.0.0.0, Culture-neutral, PublicKeyToken=b03f5f7111d50a3aMMoveNext0 at SuperSocketClientEngine.SsIStreamTcpSessio n.AuthenticateAsClientAsync(SslStream ssIStream, Security0ption securityOption)
```

**Comment by janseris** [comment]
Might be the same issue as connecting to Sql Server where SSL fails (used on log in even when not encrypting)

**Comment by Lukas123798** [comment]
Is there some solution or conclusion ?

**Comment by akravch** [comment]
Facing the same issue on a non-MAUI Android .NET 6 app with errors like this:

```
System.Net.WebSockets.WebSocketException (0x80004005): Unable to connect to the remote server
---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
---> Interop+AndroidCrypto+SslException: Exception of type 'Interop+AndroidCrypto+SslException' was thrown.
--- End of inner exception stack trace ---
at System.Net.Security.SslStream.<ForceAuthenticationAsync>d__175`1[[System.Net.Security.AsyncReadWriteAdapter, System.Net.Security, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext()
```

Also, in logcat I see the following right before the .NET exception:

```
W System.err: java.lang.IllegalStateException: Handshake has already been started
W System.err: 	at com.android.org.conscrypt.OpenSSLEngineImpl.beginHandshakeInternal(OpenSSLEngineImpl.java:335)
W System.err: 	at com.android.org.conscrypt.OpenSSLEngineImpl.beginHandshake(OpenSSLEngineImpl.java:325)
```

Switching to the legacy HTTP handler didn't help as well.
