### ISSUE TITLE
MAUI App build/compiles and runs fine on Windows but fails to build/compile for Android: com.android.tools.r8.CompilationFailedException

### ISSUE THREAD

**Issue by martin-honnen** [dotnet/maui#9413]
### Description

I have tried to write a .NET 6 MAUI app with VS 2022 17.3, the app builds/compiles/runs fine on Windows but when trying to run it on an Android emulator all I get is an error 

```
java.lang.RuntimeException: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, position: Ljava/lang/invoke/MethodHandleImpl$BindCaller$T;invoke_V(Ljava/lang/invoke/MethodHandle;[Ljava/lang/Object;)Ljava/lang/Object;, origin: obj\Debug\net6.0-android\lp\157\jl\resources.jar : java/lang/invoke/MethodHandleImpl$BindCaller$T.class	SaxonHEMauiTest1	C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.448\tools\Xamarin.Android.D8.targets	79	
```

Example is in the Github repository https://github.com/martin-honnen/SaxonHEMauiTest1.

### Steps to Reproduce

1. Clone repository https://github.com/martin-honnen/SaxonHEMauiTest1
1. Open VS 2022 17.3 or later that supports MAUI
2. Create MAUI project by cloning your clone of https://github.com/martin-honnen/SaxonHEMauiTest1
3. build the project
4. run it on Windows, runs fine
5. try to run it on Android emulator (like Pixel 5 - API 32/Android 12.1), you get an error `java.lang.RuntimeException: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, position: Ljava/lang/invoke/MethodHandleImpl$BindCaller$T;invoke_V(Ljava/lang/invoke/MethodHandle;[Ljava/lang/Object;)Ljava/lang/Object;, origin: obj\Debug\net6.0-android\lp\157\jl\resources.jar : java/lang/invoke/MethodHandleImpl$BindCaller$T.class	SaxonHEMauiTest1	C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.448\tools\Xamarin.Android.D8.targets	79`

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12.1 API 32, Android 11 API 30

### Did you find any workaround?

No, I don't know how to resolve this.

### Relevant log output

```shell
1>------ Erstellen gestartet: Projekt: SaxonHEMauiTest1, Konfiguration: Debug Any CPU ------
1>Analysetools werden übersprungen, um den Build zu beschleunigen. Sie können den Befehl „Build“ oder „Rebuild“ ausführen, um Analyzer auszuführen.
1>SaxonHEMauiTest1 -> C:\Users\marti\source\repos\SaxonHEMauiTest1\SaxonHEMauiTest1\bin\Debug\net6.0-android\SaxonHEMauiTest1.dll
1>Exception in thread "main" java.lang.RuntimeException: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, position: Ljava/lang/invoke/MethodHandleImpl$BindCaller$T;invoke_V(Ljava/lang/invoke/MethodHandle;[Ljava/lang/Object;)Ljava/lang/Object;, origin: obj\Debug\net6.0-android\lp\157\jl\resources.jar:java/lang/invoke/MethodHandleImpl$BindCaller$T.class
1>	at com.android.tools.r8.internal.Bj.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:98)
1>	at com.android.tools.r8.D8.main(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:4)
1>Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, position: Ljava/lang/invoke/MethodHandleImpl$BindCaller$T;invoke_V(Ljava/lang/invoke/MethodHandle;[Ljava/lang/Object;)Ljava/lang/Object;, origin: obj\Debug\net6.0-android\lp\157\jl\resources.jar:java/lang/invoke/MethodHandleImpl$BindCaller$T.class
1>	at Version.fakeStackEntry(Version_3.3.28.java:0)
1>	at com.android.tools.r8.internal.Bj.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:75)
1>	at com.android.tools.r8.internal.Bj.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:28)
1>	at com.android.tools.r8.internal.Bj.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:27)
1>	at com.android.tools.r8.internal.Bj.b(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:2)
1>	at com.android.tools.r8.D8.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:22)
1>	at com.android.tools.r8.D8.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:17)
1>	at com.android.tools.r8.internal.Bj.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:85)
1>	... 1 more
1>Caused by: com.android.tools.r8.internal.k2: MethodHandle.invoke and MethodHandle.invokeExact are only supported starting with Android O (--min-api 26)
1>	at com.android.tools.r8.internal.Jn.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:789)
1>	at com.android.tools.r8.internal.Jn.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:810)
1>	at com.android.tools.r8.internal.G7.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:603)
1>	at com.android.tools.r8.internal.z8.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:163)
1>	at com.android.tools.r8.internal.Jn.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:231)
1>	at com.android.tools.r8.graph.j.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:662)
1>	at com.android.tools.r8.graph.j.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:584)
1>	at com.android.tools.r8.graph.z2.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:42)
1>	at com.android.tools.r8.graph.d3.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:5)
1>	at com.android.tools.r8.internal.Un.d(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:36)
1>	at com.android.tools.r8.internal.Un.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:545)
1>	at com.android.tools.r8.internal.Bj.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:102)
1>	at com.android.tools.r8.internal.Un.b(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:235)
1>	at com.android.tools.r8.internal.Un.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:448)
1>	at com.android.tools.r8.internal.pe.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:18)
1>	at com.android.tools.r8.internal.Un.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:314)
1>	at com.android.tools.r8.internal.K9.b(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:1)
1>	at com.android.tools.r8.internal.I9.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:1)
1>	at com.android.tools.r8.internal.K9.c(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:1)
1>	at com.android.tools.r8.utils.C.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:39)
1>	at com.android.tools.r8.utils.C.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:44)
1>	at com.android.tools.r8.utils.C.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:38)
1>	at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1448)
1>	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
1>	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
1>	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
1>	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
1>	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
1>	Suppressed: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.android.tools.r8.internal.Dj: com.android.tools.r8.internal.k2: MethodHandle.invoke and MethodHandle.invokeExact are only supported starting with Android O (--min-api 26)
1>		at com.android.tools.r8.D8.d(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:766)
1>		at com.android.tools.r8.D8.c(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:1)
1>		at com.android.tools.r8.internal.Bj.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:24)
1>		at com.android.tools.r8.internal.Bj.b(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:2)
1>		at com.android.tools.r8.D8.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:22)
1>		at com.android.tools.r8.D8.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:17)
1>		at com.android.tools.r8.internal.Bj.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:85)
1>		at com.android.tools.r8.D8.main(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:4)
1>	Caused by: java.util.concurrent.ExecutionException: com.android.tools.r8.internal.Dj: com.android.tools.r8.internal.k2: MethodHandle.invoke and MethodHandle.invokeExact are only supported starting with Android O (--min-api 26)
1>		at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
1>		at com.android.tools.r8.utils.C.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:14)
1>		at com.android.tools.r8.utils.C.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:43)
1>		at com.android.tools.r8.utils.C.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:41)
1>		at com.android.tools.r8.utils.C.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:40)
1>		at com.android.tools.r8.internal.K9.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:43)
1>		at com.android.tools.r8.internal.K9.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:2)
1>		at com.android.tools.r8.internal.Un.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:263)
1>		at com.android.tools.r8.internal.Un.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:13)
1>		at com.android.tools.r8.D8.d(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:645)
1>		... 7 more
1>	Caused by: com.android.tools.r8.internal.Dj: com.android.tools.r8.internal.k2: MethodHandle.invoke and MethodHandle.invokeExact are only supported starting with Android O (--min-api 26)
1>		at com.android.tools.r8.internal.Dj.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:6)
1>		at com.android.tools.r8.internal.Bj.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:104)
1>		at com.android.tools.r8.internal.Un.b(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:235)
1>		at com.android.tools.r8.internal.Un.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:448)
1>		at com.android.tools.r8.internal.pe.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:18)
1>		at com.android.tools.r8.internal.Un.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:314)
1>		at com.android.tools.r8.internal.K9.b(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:1)
1>		at com.android.tools.r8.internal.I9.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:1)
1>		at com.android.tools.r8.internal.K9.c(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:1)
1>		at com.android.tools.r8.utils.C.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:39)
1>		at com.android.tools.r8.utils.C.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:44)
1>		at com.android.tools.r8.utils.C.a(R8_3.3.28_2aaf796388b4e9f6bed752d926eca110512a53a3f09a8d755196089c1cfdf799:38)
1>		at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1448)
1>		at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
1>		at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
1>		at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
1>		at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
1>		at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
1>	Caused by: [CIRCULAR REFERENCE: com.android.tools.r8.internal.k2: MethodHandle.invoke and MethodHandle.invokeExact are only supported starting with Android O (--min-api 26)]
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.448\tools\Xamarin.Android.D8.targets(79,5): error : java.lang.RuntimeException: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, position: Ljava/lang/invoke/MethodHandleImpl$BindCaller$T;invoke_V(Ljava/lang/invoke/MethodHandle;[Ljava/lang/Object;)Ljava/lang/Object;, origin: obj\Debug\net6.0-android\lp\157\jl\resources.jar : java/lang/invoke/MethodHandleImpl$BindCaller$T.class
1>Die Erstellung des Projekts "SaxonHEMauiTest1.csproj" ist abgeschlossen -- FEHLER.
```

**Comment by MagicAndre1981** [comment]
does it happen without using IKVM.Maven.Sdk and direct maven packages? Try to use only the official AndroidX bindings.

**Comment by martin-honnen** [comment]
@MagicAndre1981, I am not sure I understand how your suggestion helps. The used NuGet package IKVM.Maven.Sdk allows me to use Java packages from Maven under .NET, at least tested so far successfully on Windows. How would an official "AndroidX" binding help or work to run Java code from .NET on various platforms including Windows and Android (and IOs and MacOS via MacCatalyst), as MAUI promises? Or is that "use only the official AndroidX bindings" you are referring to something that works across platforms with MAUI?

**Comment by mattleibow** [comment]
This issue was moved to xamarin/xamarin-android#7766
