### ISSUE TITLE
[Android] OnAppearing only called on 1st tab of AppShell home page

### ISSUE THREAD

**Issue by davefxy** [dotnet/maui#9531]
### Description

On the Android, when I have 2 tabs defined for an AppShell homepage, the OnAppearing method doesn't get called for the ContentPage when I select the 2nd tab. It does get called on the 1st tab contentpage which is initially called when the home page is displayed .
I am using Microsoft Visual Studio Community 2022 (64-bit) - Preview
Version 17.4.0 Preview 1.0 on Windows 11.

### Steps to Reproduce

1. Compile the attached app for an Android tablet.
2. Place a breakpoint at line 14 (OnAppearing) in DogsPage.xaml.cs
3. Run the app on an Android device(i.e. Samaung Galaxy S7, Android 12, API 31)
4. Select the Dogs tab. It will not break at the OnAppearing method in DogPage.xaml.cs

### Version with bug

6.0.312

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 12, API 31

### Did you find any workaround?

No

**Comment by tom-b-iodigital** [comment]
I'm having the same problem in one of our projects

**Comment by davefxy** [comment]
This is a relatively important issue when the page is dependent on OnAppearing() to load the data for the page. Is there another alternative to OnAppearing to accomplish loading the data for the page? Should I attempt to load the data for all of the tabbed pages when the 1st tab page is initialized?

**Comment by davefxy** [comment]
I think this is already being looked at. Check out "OnAppearing not triggered when going back from Modal page #8513"

**Comment by holecekp** [comment]
I have also problems with OnAppearing for tabs. It is executed many times on Windows (https://github.com/dotnet/maui/issues/10161) and it is not executed at all when tabs are switched on Androind.

**Comment by holecekp** [comment]
It is sad that it will not be fixed in the near future. The issue is quite important because it OnAppearing is used to load data (or do other initializations that requires async/await). I am also using OnAppearing/OnDisappearing to subscribe/unsubscribe events, start/stop sound and other task that are done in background. This can cause big problems when these methods does not run when the developer expects them (in case of Android), or if the run multiple times instead of once (in case of Windows).
This also makes the migration of an existing app from Xamarin.Forms to MAUI much more difficult, because the behavior of the app can change completely.

**Comment by skynetbeta23** [comment]
Having the same issue. Lost two days of work because I thought I was doing some mistakes. MAUI really is full of bugs, and I can accept it because of its juvenility. But bugs like these I think should be prioritized. I must abandon the Tab structure in my app structure because of this issue

**Comment by durandt** [comment]
This issue has been around for 4 years, already existed in Xamarin.Forms:
https://github.com/xamarin/Xamarin.Forms/issues/3855

This makes AppShell tabs behavior very inconsistent between iOS and Android and is likely to confuse new MAUI developers a lot.
Fixing this should be high prio, considering for how long this issue has been around.

Workaround:
You should be able to listen to the AppShell event when a tab is changed and call your initialization-code there instead.

**Comment by durandt** [comment]
Duplicate of #8102 ?

**Comment by Hottemax** [comment]
> Duplicate of #8102 ?

Yes. I think @PureWeen you guys should just summarize these all into one issue (see the links just in this issue, #8513, #8102, #10161).

This really applies to many different other types of issues as well; dotnet/maui repo now has over 2.1k issues and steadily climbing, and how is it feasible to keep track of what is actually important and keep a high-level overview and do release(sprint planning if duplicates are not being eliminated?!

**Comment by eidylon** [comment]
Like many others here, I am BOGGLED that this is considered "not critical", and not worth fixing in the foreseeable future. It's a pretty common pattern to have a set of actions to do when coming into a page (any time, not just the first time it loaded). 

Things such as mentioned above, updating controls, changing styles, binding values, or any number of other things, based on the current state of the application. Not being able to do this means that MAUI is all but useless (at least on Android) for anything except the simplest, most basic of applications (ie... nothing needing to deal with local state).

**Comment by Hottemax** [comment]
@eidylon hopefully this will be fixed soon now by the upcoming solution for #8102 (duplicate?)

**Comment by SmartmanApps** [comment]
Hello. I have come here from https://github.com/dotnet/maui/issues/8513 as that was the precise scenario I was running into this (OnAppearing not running after popping a modal page), but that issue has been closed. Since this issue is still open I will add my comments here instead.

I have the same version as specified in the closed issue (7.0.59) which supposedly has the fix, and yet not fixed. In fact the opposite, this is the first time I've ever run into this issue - was working rock solid up until my latest VS upgrade (from 17.4.3 to 17.5.1). This is on Windows (I haven't tried other platforms yet).

I especially wanted to note that this only happens intermittently! So although in the closed issue it appeared to be fixed, it may not have been. I haven't yet identified any common scenario where it happens to where it doesn't happen. I'll let you know if I notice any such patterns, but yeah, this is like taking you car to the mechanic and it all works fine at the workshop, but plays up again when you get home. Argh.

**Comment by SmartmanApps** [comment]
This person also experiencing the issue a few days ago https://stackoverflow.com/questions/75635738/navigation-pushmodalasync-does-not-trigger-onappearing-in-maui

**Comment by SmartmanApps** [comment]
Just had it happen again and have some (hopefully) helpful diagnostic information for you.

Context is I have a page which, in OnAppearing, goes through and lists existing accounts on the page (which is a ContentPage nested in a NavigationPage). I have debug statements throughout OnAppearing, From this page I can click a button to edit/add an account, also with debugs throughout. It is pushed as a ModalPage, and popped when you click on the "Save" button... at which point, of course, the OnAppearing should run again and produce the updated listing of accounts. I also have a global exception catcher in App.cs AppDomain.CurrentDomain.FirstChanceException+=CurrentDomain_FirstChanceException; for anything I've missed. Between the 2 I got 2 interesting bits of info...

So what happens when it's working correctly is...
navigate to accounts page
OnAppearing
shows that there are 0 accounts
Launch EditAccount page
Save account 1
OnAppearing
shows 1 account
Launch EditAccount page
save account 2
OnAppearing
shows 2 accounts

What ACTUALLY happened this time was,,,

Ran correctly when I added the first account, BUT immediately after that I got an unhandled exception, which was...

******************* UNHANDLED EXCEPTION! Details: System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
 ---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
******************* UNHANDLED EXCEPTION! Details: System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
 ---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](Memory`1 buffer, CancellationToken cancellationToken)
******************* UNHANDLED EXCEPTION! Details: System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
 ---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](Memory`1 buffer, CancellationToken cancellationToken)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

And then the weird behaviour started (presumably as a consequence of the exception?)

Then I click to add 2nd account, and right after that OnAppearing starts running even though I just hid the page! It finishes running before I finish creating the 2nd account, and when I save that OnAppearing fails to run this time. And that then caused further problems due to resource contention (which should never happen, because OnAppearing shouldn't be running whilst I'm still in the pushed EditAccount page).

**Comment by SmartmanApps** [comment]
Hey @durandt,

   Thanks, but I tried using Shane's workaround nuget and it didn't fix my issue. It references shell, so maybe it only works with shell? I'm experiencing the issue on Windows with a Content/NavigationPage.

Thanks.

**Comment by durandt** [comment]
@SmartmanApps this issue concerns Android and Shell. Look for an existing issue matching yours for Windows or create a new one.

**Comment by SmartmanApps** [comment]
Hello @durandt,

   The issue is with OnAppearing - it only runs the first time correctly. It is not specific to Shell or Android. The underlying issue is OnAppearing. See the diagnostic information I provided showing this. The title of this issue says "only called on 1st tab", but that's not correct. My diagnostics shows after the first time it has it's sense reversed and subsequently runs on disappearing instead of on appearing. It's the same issue. Runs first time correctly, then runs opposite time to when it's supposed to run.

**Comment by SmartmanApps** [comment]
Hello @durandt,

   This is an issue with OnAppearing. It happens on both Windows and Android. i.e. it's an issue with MAUI OnAppearing, all platforms, possibly all wrappers as well (ContentPage/NavigationPage, Shell). The issue here, if not the exact same issue (which I strongly suspect it is), then it's at least an underlying issue which you can't resolve this issue until the OnAppearing issue is resolved (if in fact they are separate issues to begin with, but I strongly doubt it). Get someone who is using shell tabbed pages to put the same diagnostics in their app as I have and you will probably see the same thing happenning (OnAppearing runs a 2nd time prematurely, then doesn't run when it's supposed to the next time, in this case that would be on the 2nd tabbed page, for me it was when I did my first PopModalAsync). I'm not going to raise a new issue only to have it closed as being a duplicate of this one. I already spent half a day collecting diagnostics which I have supplied, but you need to get someone who is having this issue on shell tabbed pages to perform the same diagnostics - I suspect that will prove it's the same issue, an issue with OnAppearing (all platforms, all wrappers). This issue matches what I'm seeing, I'm just not using Shell.

**Comment by SmartmanApps** [comment]
> > Duplicate of #8102 ?
> 
> Yes. I think @PureWeen you guys should just summarize these all into one issue (see the links just in this issue, #8513, #8102, #10161).
> 

They've all been closed now - this is the only one still open. I don't think 8102 is a duplicate, because people have reported the supplied workaround works for them, but it didn't work for me (that appears to be a Shell issue, not an OnAppearing issue). On the other hand I'm pretty sure the other 2 are duplicates - in any case they've both been closed. I'm not raising another issue lest it also get closed as a duplicate of this one. We need to prove one way or another if they're all the same issue or not. See diagnostics I've supplied (put a debug at the start and end of OnAppearing, and anything else you're clicking on, like a PushModalAsync, 2nd tabbed page, whatever). I'll also note again it's an intermittent fault, so you may need to try it several times.

**Comment by SmartmanApps** [comment]
I found this and suspect it may be a fix for my issue, and probably also **this** issue, if someone can just do the necessary diagnostics to see if they are indeed the same issue - https://github.com/dotnet/maui/pull/13177#issuecomment-1472116222

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.6.0 Preview 7.0. Repro on Android platform with sample project. But windows works fine.
[Xaminals.zip](https://github.com/dotnet/maui/files/11513947/Xaminals.zip)
**Android:**
![Android](https://github.com/dotnet/maui/assets/77434865/af9fa7c3-e012-4a0f-ac30-f66bb7e101b5)
**Windows:**
![Windoes](https://github.com/dotnet/maui/assets/77434865/88044bff-7849-4e55-8c4e-bb8b568bfdd4)

**Comment by Hottemax** [comment]
What is the state here, is it fixed or not (#8102 is marked as fixed in 7.0.81), but this is still open?

**Comment by praveenkumarkarunanithi** [comment]
This issue has been verified in Visual Studio Code 1.101.0 using the updated issue sample with .NET 9 and MAUI controls version 9.0.80. Tested on Android emulator (Pixel 9 Pro, API 35). The issue is no longer reproducible with these versions.

https://github.com/user-attachments/assets/dfc7996d-7033-42da-8e9d-13910bb87a80
