### ISSUE TITLE
Maui android published apk crash

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#9697]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Maui-android-published-apk-crash/10122927)._

---
[severity:It's more difficult to complete my work]
Hello,
The application **works fine in debug mode**, but when published the application crash.
One reason was 'Binding' like this : Text="{Binding DeviceRange[0], StringFormat='Hello, World! {0}'}"; application crash "MissingMethodException"
Another one was the ZIndex property cause crash in published application with "TargetInvocationException".
I have included all solution files compressed in MauiApp6.zip, that contain the 'logcat' files crashapp.txt and crashapp2.txt.
Regards,
Antonio Lopes

---
#### Feedback Bot on 8/16/2022, 11:05 PM: 

(private comment, text removed)
#### Sigma Li (CSI Interfusion Inc) [MSFT] on 8/19/2022, 00:31 AM: 

(private comment, text removed)
#### Antonio Herrero Lopes on 8/19/2022, 01:53 AM: 

(private comment, text removed)
#### Antonio Herrero Lopes on 8/24/2022, 06:45 PM: 

(private comment, text removed)
#### Antonio Herrero Lopes on 8/19/2022, 01:58 AM: 

(private comment, text removed)
#### Sigma Li (CSI Interfusion Inc) [MSFT] on 8/23/2022, 03:28 AM: 

(private comment, text removed)
#### Feedback Bot on 8/24/2022, 02:51 AM: 

(private comment, text removed)
#### Maria Ghiondea [MSFT] on 8/24/2022, 10:53 AM: 

(private comment, text removed)
#### Feedback Bot on 8/24/2022, 08:20 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by PureWeen** [comment]
@jonathanpeppers thoughts?

**Comment by jonathanpeppers** [comment]
@StephaneDelcroix is this related to XamlC? Part of the stack trace is:
```
---> System.MissingMethodException: Method not found: char System.String[].get_Chars(int) Due to: Failed to load due to unknown reasons
  at Microsoft.Maui.Controls.Internals.TypedBinding`2[[MauiApp6.Preset, MauiApp6, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[System.Char, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ApplyCore(Object sourceObject, BindableObject target, BindableProperty property, Boolean fromTarget)
  at Microsoft.Maui.Controls.Internals.TypedBinding`2[[MauiApp6.Preset, MauiApp6, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[System.Char, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Apply(Object context, BindableObject bindObj, BindableProperty targetProperty, Boolean fromBindingContextChanged)
  at Microsoft.Maui.Controls.BindableObject.ApplyBindings(Boolean skipBindingContext, Boolean fromBindingContextChanged)
  at Microsoft.Maui.Controls.BindableObject.SetInheritedBindingContext(BindableObject bindable, Object value)
  at Microsoft.Maui.Controls.Element.SetChildInheritedBindingContext(Element child, Object context)
  at Microsoft.Maui.Controls.Element.<OnBindingContextChanged>b__82_0(BindableObject child, Object bc)
  at Microsoft.Maui.Controls.BindableObjectExtensions.PropagateBindingContext[Element](BindableObject self, IEnumerable`1 children, Action`2 setChildBindingContext)
  at Microsoft.Maui.Controls.Element.OnBindingContextChanged()
  at Microsoft.Maui.Controls.VisualElement.OnBindingContextChanged()
  at Microsoft.Maui.Controls.View.OnBindingContextChanged()
  at Microsoft.Maui.Controls.BindableObject.SetInheritedBindingContext(BindableObject bindable, Object value)
  at Microsoft.Maui.Controls.Element.SetChildInheritedBindingContext(Element child, Object context)
  at Microsoft.Maui.Controls.Element.<OnBindingContextChanged>b__82_0(BindableObject child, Object bc)
  at Microsoft.Maui.Controls.BindableObjectExtensions.PropagateBindingContext[Element](BindableObject self, IEnumerable`1 children, Action`2 setChildBindingContext)
  at Microsoft.Maui.Controls.Element.OnBindingContextChanged()
  at Microsoft.Maui.Controls.VisualElement.OnBindingContextChanged()
  at Microsoft.Maui.Controls.View.OnBindingContextChanged()
  at Microsoft.Maui.Controls.BindableObject.SetInheritedBindingContext(BindableObject bindable, Object value)
  at Microsoft.Maui.Controls.Element.SetChildInheritedBindingContext(Element child, Object context)
  at Microsoft.Maui.Controls.TemplatedPage.SetChildInheritedBindingContext(Element child, Object context)
  at Microsoft.Maui.Controls.Element.set_Parent(Element value)
  at Microsoft.Maui.Controls.Element.OnChildAdded(Element child)
  at Microsoft.Maui.Controls.VisualElement.OnChildAdded(Element child)
  at Microsoft.Maui.Controls.Page.OnInternalAdded(VisualElement view)
  at Microsoft.Maui.Controls.Page.InternalChildrenOnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
  at System.Collections.ObjectModel.ObservableCollection`1[[Microsoft.Maui.Controls.Element, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnCollectionChanged(NotifyCollectionChangedEventArgs )
  at System.Collections.ObjectModel.ObservableCollection`1[[Microsoft.Maui.Controls.Element, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnCollectionChanged(NotifyCollectionChangedAction , Object , Int32 )
  at System.Collections.ObjectModel.ObservableCollection`1[[Microsoft.Maui.Controls.Element, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].InsertItem(Int32 , Element )
  at System.Collections.ObjectModel.Collection`1[[Microsoft.Maui.Controls.Element, Microsoft.Maui.Controls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].Add(Element )
  at Microsoft.Maui.Controls.TemplateUtilities.OnContentChanged(BindableObject bindable, Object oldValue, Object newValue)
  at Microsoft.Maui.Controls.BindableObject.SetValueActual(BindableProperty property, BindablePropertyContext context, Object value, Boolean currentlyApplying, SetValueFlags attributes, Boolean silent)
  at Microsoft.Maui.Controls.BindableObject.SetValueCore(BindableProperty property, Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes)
  at Microsoft.Maui.Controls.BindableObject.SetValue(BindableProperty property, Object value, Boolean fromStyle, Boolean checkAccess)
  at Microsoft.Maui.Controls.BindableObject.SetValue(BindableProperty property, Object value)
  at MauiApp6.MainPage.InitializeComponent()
  at MauiApp6.MainPage..ctor()
```
It could also be something about the linker, though.

**Comment by jrahma** [comment]
I have the same error and not able to deploy the android app to the emulator nor device

```
System.MissingMethodException: Method not found: bool Microsoft.Maui.Layouts.LayoutExtensions.ShouldArrangeLeftToRight(Microsoft.Maui.IView)
  at at Syncfusion.Maui.Core.SfView.ArrangeContent(Rect bounds)
  at at Syncfusion.Maui.Core.SfEffectsView.ArrangeContent(Rect bounds)
  at at Syncfusion.Maui.Core.SfView.Microsoft.Maui.ILayout.CrossPlatformArrange(Rect bounds)
  at at Syncfusion.Maui.Core.Platform.LayoutViewGroupExt.OnLayout(Boolean changed, Int32 l, Int32 t, Int32 r, Int32 b)
  at Android.Views.ViewGroup.n_OnLayout_ZIIII(IntPtr jnienv, IntPtr native__this, Boolean changed, Int32 l, Int32 t, Int32 r, Int32 b) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net7.0/android-33/mcw/Android.Views.ViewGroup.cs:3655
  at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPZIIII_V(_JniMarshal_PPZIIII_V callback, IntPtr jnienv, IntPtr klazz, Boolean p0, Int32 p1, Int32 p2, Int32 p3, Int32 p4) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:429

```

**Comment by jonathanpeppers** [comment]
@jrahma you should file a new issue for your problem. It looks like SyncFusion used:

    bool Microsoft.Maui.Layouts.LayoutExtensions.ShouldArrangeLeftToRight(Microsoft.Maui.IView)

And now that method is gone?

https://github.com/dotnet/maui/commit/4d25505c2788ebe39de013ae37b8ad5ac3276d41#diff-923a4005b8fd76c6fe5a26814219f9002063666b6d6a49b6b1e19aea086628f4L210

/cc @hartez

**Comment by jonathanpeppers** [comment]
I think the issue here is SyncFusion needs to rebuild their package against the latest MAUI, do they have an update?

I don't see anything for the MAUI team to do here, if they want to change the above API.

**Comment by eXeShnik** [comment]
Its not related to SyncFusion
Its because of using indexer in xaml Binding
Text="{Binding Values[1]}"

**Comment by eXeShnik** [comment]
> I think the issue here is SyncFusion needs to rebuild their package against the latest MAUI, do they have an update?
> 
> I don't see anything for the MAUI team to do here, if they want to change the above API.

Btw you don't see anything because they put it to Backlog and forget)

**Comment by davidchieregato** [comment]
I got the same issue in .NET7, with a binding indexing an array the app will crash in Release mode but not in Debug.

I tried to make the linker include the supposed missing method without success..

```
public class LinkPreserve
{
    [DynamicDependency("get_Chars", typeof(string))]
    public void Include(string str)
    {
        var _ = str[0];
    }
}
```

Commenting the label with the indexed access (i.e. remove `Text="{Binding DayNames[0]}"` from the xaml ) the app works fine also in release. Any update on this?

**Comment by jonathanpeppers** [comment]
> I got the same issue in .NET7

Is it the same? This issue is related to Syncfusion.

> a binding indexing an array the app will crash in Release mode but not in Debug.

Are you opting the assembly into trimming? What type is `DayNames` accessing?

If this assembly shouldn't be trimmed, can you file a new issue as your problem seems unrelated?

**Comment by davidchieregato** [comment]
As I can understand the issue reported by @jrahma was related to Syncfusion but not the original issue of the first post. I got a stacktrace exactly identical to https://github.com/dotnet/maui/issues/9697#issuecomment-1241140129 and I don't have any Syncfusion dependency.

The Linker behavior is set to "Link SDK assemblies only" but the app will crash also with "Don't Link" only in Release. DayNames is a string array in my viewModel using MVVM Community Toolkit but it shouldn't change.

```
[ObservableProperty]
private string[] _dayNames;
```

It is the set like this `DayNames = CultureInfo.CurrentCulture.DateTimeFormat.AbbreviatedDayNames;`

I can try to do a separate repro and a new issue if needed if the problem is unrelated.

**Comment by jonathanpeppers** [comment]
Right, file a new issue, this seems completely unrelated?

**Comment by jfversluis** [comment]
This issue seems stale by now. Seems like the one issue is resolved and for the other a new issues was asked to be opened. Since there has been no engagement in a while I'm closing this one. If there is still something not right according to you, please open something new.
