### ISSUE TITLE
Can't assign x:Name to GradientStop

### ISSUE THREAD

**Issue by tataelm** [dotnet/maui#9841]
### Description

I would like to give x:Name to a GradientStop under LinearGradientBrush for Path.Fill.

Without x:Name, there is no problem. But as soon as I give it a name, I am getting "Object reference not set to an instance of an object." error while "InitiliazeComponent()" call

Before you ask, why do I need to give it a name: I am trying to animate gradient brushes inside for that path. Similar code is being used in a WPF application. 

I only tested it on Android. 

### Steps to Reproduce

1. Create a content view
2. Fill the content

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentView
    x:Class="ChordCollect.Views.Utility.SongContentLoadingIndicator"
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    Background="Transparent">
    <Grid>
        <Path
            x:Name="path_logo"
            Aspect="Uniform"
            Data="some svg file"
            HeightRequest="150"
            WidthRequest="150">

            <Path.Fill>
                <LinearGradientBrush StartPoint="0,0" EndPoint="1,1">
                    <GradientStop x:Name="thisThrowsAnError" Offset="0" Color="Red" />
                    <GradientStop Offset="1.0" Color="Blue" />
                </LinearGradientBrush>
            </Path.Fill>
        </Path>
    </Grid>
</ContentView>
```

3. For Path.Data, you can give any SVG data. 
4.   GradientStop x:Name="thisThrowsAnError" Offset="0" Color="Red" .... This line is what gives the error. If you erase x:Name..., it works just fine. 
 

### Link to public reproduction project repository

none

### Version with bug

6.0.312

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11 - API 30

### Relevant log output

```shell
{System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Maui.Controls.GradientStop.GetHashCode() in D:\a\_work\1\s\src\Controls\src\Core\GradientStop.cs:line 52
   at System.Collections.Generic.Dictionary`2[[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].TryInsert(Object key, String value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2[[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].set_Item(Object key, String value)
   at Microsoft.Maui.Controls.Internals.NameScope.Microsoft.Maui.Controls.Internals.INameScope.RegisterName(String name, Object scopedElement) in D:\a\_work\1\s\src\Controls\src\Core\Internals\NameScope.cs:line 28
   at Microsoft.Maui.Controls.Xaml.RegisterXNamesVisitor.Visit(ValueNode node, INode parentNode) in D:\a\_work\1\s\src\Controls\src\Xaml\RegisterXNamesVisitor.cs:line 31
   at Microsoft.Maui.Controls.Xaml.ValueNode.Accept(IXamlNodeVisitor visitor, INode parentNode) in D:\a\_work\1\s\src\Controls\src\Xaml\XamlNode.cs:line 92
   at Microsoft.Maui.Controls.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode) in D:\a\_work\1\s\src\Controls\src\Xaml\XamlNode.cs:line 153
   at Microsoft.Maui.Controls.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode) in D:\a\_work\1\s\src\Controls\src\Xaml\XamlNode.cs:line 155
   at Microsoft.Maui.Controls.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode) in D:\a\_work\1\s\src\Controls\src\Xaml\XamlNode.cs:line 153
   at Microsoft.Maui.Controls.Xaml.ElementNode.Accept(IXamlNodeVisitor visitor, INode parentNode) in D:\a\_work\1\s\src\Controls\src\Xaml\XamlNode.cs:line 155
   at Microsoft.Maui.Controls.Xaml.RootNode.Accept(IXamlNodeVisitor visitor, INode parentNode) in D:\a\_work\1\s\src\Controls\src\Xaml\XamlNode.cs:line 212
   at Microsoft.Maui.Controls.Xaml.XamlLoader.Visit(RootNode rootnode, HydrationContext visitorContext, Boolean useDesignProperties) in D:\a\_work\1\s\src\Controls\src\Xaml\XamlLoader.cs:line 208
   at Microsoft.Maui.Controls.Xaml.XamlLoader.Load(Object view, String xaml, Assembly rootAssembly, Boolean useDesignProperties) in D:\a\_work\1\s\src\Controls\src\Xaml\XamlLoader.cs:line 78
   at Microsoft.Maui.Controls.Xaml.XamlLoader.Load(Object view, String xaml, Boolean useDesignProperties) in D:\a\_work\1\s\src\Controls\src\Xaml\XamlLoader.cs:line 53
   at Microsoft.Maui.Controls.Xaml.XamlLoader.Load(Object view, Type callingType) in D:\a\_work\1\s\src\Controls\src\Xaml\XamlLoader.cs:line 49
   at Microsoft.Maui.Controls.Xaml.Extensions.LoadFromXaml[SomeView](SomeView view, Type callingType) in D:\a\_work\1\s\src\Controls\src\Xaml\ViewExtensions.cs:line 37
   at SomeProject.Views.Utility.SomeView.InitializeComponent() in F:\Clients\Mobile\Maui\Microsoft.Maui.Controls.SourceGen\Microsoft.Maui.Controls.SourceGen.CodeBehindGenerator\Views_Utility_SomeView.xaml.sg.cs:line 30
   at SomeProject.Views.Utility.SomeView..ctor() in F:\Google Drive\SomeProjects\SomeProject\Refactoring SomeProjects\SomeProject\Clients\Mobile\Maui\Views\Utility\SomeView.xaml.cs:line 9}
```

**Comment by jsuarezruiz** [comment]
The issue will be fixed by https://github.com/dotnet/maui/pull/9865
